### ISSUE TITLE
No-fail Improvements (Kind of like beat saber)

### ISSUE THREAD

**Issue by Dlol** [ppy/osu#12160] opened 2021-03-23 22:24 UTC
**Describe the new feature:** 
No-fail score reduction doesn't apply unless you fail the map.
**Proposal designs of the feature:** 
It should just be implemented in the no-fail mod I think, but it could also be a setting you can enable/disable.

**Comment by jai-x** [comment] 2021-03-23 23:08
Duplicate of https://github.com/ppy/osu/issues/9844

**Closed by jai-x** 2021-03-23 23:08 UTC
