### ISSUE TITLE
osu! Stable Directory Chooser for imports

### ISSUE THREAD

**Issue by EllySensei** [ppy/osu#12117] opened 2021-03-21 01:19 UTC
Maybe this will be a duplicate feature request, but here goes. This technically is a simple feature to implement, but in Linux, you can't choose a custom osu stable directory, even though there are the files for it, it's kind of problematic for users that use WINE to run osu and have to start from scratch. If this feature was implemented, there should be an easier way than to use, say a config file found in the (.local/share/osu) directory. 

**Proposal designs of the feature:** 
A simple button in the settings to choose a directory. Then the file browser pointing to the osu stable files.

**Comment by Wieku** [comment] 2021-03-21 01:22
Duplicate of #3763

**Comment by peppy** [comment] 2021-03-21 01:22
Linux is already an edge case. Stable is not really supported there. You can get around this manually by making a symlink to `~/.osu`

**Closed by peppy** 2021-03-21 01:22 UTC
