### ISSUE TITLE
osu!mania notes shouldn't disappear in the editor when seeking to their hit time

### ISSUE THREAD

**Issue by peppy** [ppy/osu#30639] opened 2024-11-15 10:20 UTC
This feels very anti-user.

https://github.com/user-attachments/assets/cd44209c-60a6-4d27-bd1a-8e298204e718

**Comment by bdach** [comment] 2024-11-15 10:21
related to/dupe of https://github.com/ppy/osu/issues/30588?

**Closed** 2024-11-20 08:55 UTC
Labels: ruleset/osu!mania, area:editor, priority:1
