### ISSUE TITLE
osu!lazer not playing ogg audio

### ISSUE THREAD

**Issue by pranshuthegamer** [ppy/osu#21757] opened 2022-12-22 07:22 UTC
### Type

Game behaviour

### Bug description

When i change my beatmap's audio to an opus version, it doesnt play.

### Version

2022.1208.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10284676/database.log)
[input.log](https://github.com/ppy/osu/files/10284678/input.log)
[network.log](https://github.com/ppy/osu/files/10284679/network.log)
[performance.log](https://github.com/ppy/osu/files/10284680/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10284682/runtime.log)

**Comment by bdach** [comment] 2022-12-22 07:25
From logs:

```
2022-12-22 07:18:03 [error]: An unobserved error has occurred.
2022-12-22 07:18:03 [error]: System.DivideByZeroException: Attempted to divide by zero.
2022-12-22 07:18:03 [error]: at osu.Framework.Audio.Track.Waveform.<>c__DisplayClass13_0.<.ctor>b__0()
2022-12-22 07:18:03 [error]: at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
2022-12-22 07:18:03 [error]: --- End of stack trace from previous location ---
2022-12-22 07:18:03 [error]: at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2022-12-22 07:18:03 [error]: --- End of stack trace from previous location ---
2022-12-22 07:18:03 [error]: at osu.Framework.Audio.Track.Waveform.GenerateResampledAsync(Int32 pointCount, CancellationToken cancellationToken)
2022-12-22 07:18:03 [error]: at osu.Framework.Graphics.Audio.WaveformGraph.<>c__DisplayClass35_0.<<queueRegeneration>b__1>d.MoveNext()
```

Previously reported in https://github.com/ppy/osu/discussions/16661.

@pranshuthegamer please provide the `.ogg` file for testing.

**Comment by pranshuthegamer** [comment] 2022-12-22 07:33
`yt-dlp -f251 RmYCOm4ehKs -o music.ogg`

**Comment by cdwcgt** [comment] 2023-01-07 15:57
![image](https://user-images.githubusercontent.com/34775378/211159431-de933362-4b74-49f8-a98a-ae40bf7ca100.png)
[music.zip](https://github.com/ppy/osu/files/10366655/music.zip)

> `yt-dlp -f251 RmYCOm4ehKs -o music.ogg`

Files obtained by command

**Comment by OliBomby** [comment] 2023-05-01 15:23
The problem is that osu!lazer does not play opus encoded audio. 
If you use `yt-dlp -x --audio-format vorbis RmYCOm4ehKs -o music.ogg` it will encode with vorbis which will work.

**Comment by peppy** [comment] 2023-05-02 04:01
Is this an issue for any ranked beatmap? If not, should probably be closed for now (or opened as a feature request).

**Comment by pranshuthegamer** [comment] 2023-05-19 19:29
No, but it limits my ability to use opus for audio (opus is op)

**Comment by FibreTTP** [comment] 2023-10-14 10:14
I don't believe any ranked beatmap uses opus as it is unable to be decoded on stable and lazer. Though I'm not the author of this issue, I'd like to have it re-opened as a request for osu!'s ability to decode opus-encoded .ogg files.

__However__, this should be done with an addition to the ranking criteria. It has been discussed [before](https://osu.ppy.sh/community/forums/topics/1072965) that osu! should not raise the bitrate limit (192kbps) for MP3s due to various reasons - mainly copyright. Seeing as opus [achieves transparency](https://wiki.hydrogenaud.io/index.php?title=Opus#Music_encoding_quality) (sounds identical to source) at around that same bitrate, I suggest that should a beatmap wish to be ranked, it must not contain an opus-encoded file with an average bitrate greater than 96kbps (which sounds better than MP3 at 192k).

Although, given that most mappers just search "yt2mp3" or whatever to download their songs, I doubt that this will actually matter to anyone. But hey, for anyone who does, everyone downloading the song will use half the storage space they would have before.

###### Also, I think vorbis should be limited to 128kbps too, since the perceptible quality at that bitrate also sounds better (to me) than 192kbps MP3 (and even that sounds _okay_).

**Comment by pranshuthegamer** [comment] 2023-10-14 10:22
If the issue is copyright, when an offending beat map is published, it should be removed, but the quality should not be limited because some people love having good sounding audio when playing osu! (including me). So, please don't limit opus to 96kbps

**Comment by FibreTTP** [comment] 2023-10-14 10:37
>some people love having good sounding audio when playing osu!

I suggest you read some of the reasons in the forum topic I linked. A comment there even links to Ephemeral (a dev) [stating](https://osu.ppy.sh/community/forums/posts/7120591) a few years back that "[higher quality audio] wont ever be accepted outside of FA tracks because [osu! is] not a lossless audio distribution service."

**Comment by peppy** [comment] 2023-10-14 10:41
Please take off-topic discussion elsewhere. If this isn't used in a ranked map then it won't be implemented for now.

**Closed** 2023-10-14 10:40 UTC
Labels: osu!framework issue, area:editor, audio, priority:2

**Comment by pranshuthegamer** [comment] 2023-10-14 10:50
How will it be used if its not implemented?

**Comment by FibreTTP** [comment] 2023-10-14 10:52
@pranshuthegamer Move discussion here: https://github.com/ppy/osu/discussions/25120
