### ISSUE TITLE
Seeking forward using the progress bar causes unexpected sliderend miss during replays

### ISSUE THREAD

**Issue by fuyukiSmkw** [ppy/osu#29203] opened 2024-07-30 10:29 UTC
### Type

Game behaviour

### Bug description

When watching a replay and **a slider is being played**, seeking forward **a long time** using the progress bar makes **the slider end to miss** while it actually didn't.

### Screenshots or videos

https://github.com/user-attachments/assets/8a5e1e3e-4118-46aa-8d49-b6f0333de382

In the video, I showed how to reproduce the bug. I used an SS replay for example because it could show the unexpected sliderend miss easily with an unexpected accuracy drop.
1. When a slider is being played, I used the progress bar to skip forward a long time, and then the accuracy dropped; I seeked back and watched the same slider to play without skipping and it didn't break this time. This indicates that seeking forward during a slider being played probably makes its end to miss.
2. I did same operations as step 1 on another slider and reproduced the bug. This indicates that the bug could probably occur on any slider.
3. I tried similar operations but paused before I seeked forward on 2 sliders respectively, and the bug was reproduced. This indicates that pausing probably doesn't affect this bug.
4. I tried similar operations but only seeked forward a little amount of time, and the sliderend didn't miss. This indicates that the bug probably only occur when seeking forward a long time.
5. (not within the video) I watched the replay from the very beginning to the end and it was an SS. This indicates that nothing else would cause accuracy to drop.

The replay file is attached here in case you need it.
[fuyukiS playing umu. - Ai no Sukima (Sotarks) [Emotions] (2024-07-18_21-42).zip](https://github.com/user-attachments/files/16426228/fuyukiS.playing.umu.-.Ai.no.Sukima.Sotarks.Emotions.2024-07-18_21-42.zip)

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16425906/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-07-30 11:19
Duplicate of https://github.com/ppy/osu/issues/25405

**Closed by smoogipoo** 2024-07-30 11:19 UTC
