### ISSUE TITLE
Custom hitcircleoverlay.png aren't used if a custom skin doesn't have a custom hitcircle.png

### ISSUE THREAD

**Issue by Yamakyu** [ppy/osu#12086] opened 2021-03-19 17:07 UTC
**Describe the bug:** 
I want to use a custom skin mixing elemetns from the original osu!lazer skin, and some custom elements. It seems like I can't use a custom hitcircleoverlay.png if I don't use a custom hitcircle.png alongside it.

**Screenshots or videos showing encountered issue:** 
*In the following pictures, approachcircle.png is 1x1 transparent png, as I play without approach circles.*

This is how it looks when I have only a custom hitcircle.png, and no custom hitcircleoverlay.png
![_Osu_Circleonly](https://user-images.githubusercontent.com/43894102/111815742-5084df80-88dc-11eb-8b92-1258620ca7ae.png)

This is how it looks when I have both a custom hitcircle.png and a custom hitcircleoverlay.png
![_Osu_OverlayANDCircle](https://user-images.githubusercontent.com/43894102/111815768-567ac080-88dc-11eb-9ae5-79d50e74fe72.png)

This is how it looks when I have a custom hitcircleoverlay.png, and no custom hitcircle.png
![_Osu_Overlayonly](https://user-images.githubusercontent.com/43894102/111815773-58448400-88dc-11eb-98c4-ab2a325aec1f.png)

We can see in this last screencap that despite the presence of a custom hitcircleoverlay.png in my skin, osu! uses the default lazer skin for both the hitcircle and the hitcircle overlay.

Just in case I went and checked on stable osu!, and there I can use a custom hitcircleoverlay.png without a custom hitcircle.png.

My understanding of how skinning works is limited (and especially for lazer), but I believe it is linked to [this issue](https://github.com/ppy/osu/issues/8019). I'm not entirely sure these are 2 identical matters, though.

Hope that was clear enough.

**osu!lazer version:** 2021.312.0

**Comment by bdach** [comment] 2021-03-19 17:13
The presence of the hitcircle sprite is used to determine, which one of the two available implementations of the hitcircle are used (one being the "legacy" one, and the other being the new lazer default):

https://github.com/ppy/osu/blob/86cf42d6107246842a30d9802a4a4fc1c09720c7/osu.Game.Rulesets.Osu/Skinning/Legacy/OsuLegacySkinTransformer.cs#L81-L85

The two implementations aren't really compatible, so intermixing like you want there is going to be hard if not impossible. If this happens, it probably won't be until the new drawable-based skinning system is implemented, which is probably far away given that it's something that is not required for the lazer client to replace stable.

**Comment by Yamakyu** [comment] 2021-03-19 20:21
Ah I see, so it's kinda a feature. Or at least, working as intended, that's somewhat good news.
Too bad for me but I'll do with workarounds in the meantime, there's no urge on this matter as there are plenty of nice skin elements out there to customize mine anyways.

**Comment by RockRoller01** [comment] 2021-03-19 20:38
> The two implementations aren't really compatible, so intermixing like you want there is going to be hard if not impossible. If this happens, it probably won't be until the new drawable-based skinning system is implemented, which is probably far away given that it's something that is not required for the lazer client to replace stable.

But well, this still goes against full legacy compatability, because if either of the elements is missing it should at least use the old default element then.

**Comment by bdach** [comment] 2021-03-19 20:43
> But well, this still goes against full legacy compatability, because if either of the elements is missing it should at least use the old default element then.

Correct, on a legacy skin non-skinned elements should fall back to the default legacy skin instead of the default lazer skin. That is tracked separately at #8019, however.

**Comment by peppy** [comment] 2021-03-25 07:41
Closing this one as the issue is being tracked via https://github.com/ppy/osu/issues/8019.

**Closed by peppy** 2021-03-25 07:41 UTC
Labels: area:skinning, ruleset:osu!
