### ISSUE TITLE
Animated follow lines dont repeat

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6778] opened 2019-11-09 00:50 UTC
**Describe the bug:** 
The animation of the follow line in my skin ([MHSkin1-Reduced.zip](https://github.com/ppy/osu/files/3826764/MHSkin1-Reduced.zip))
does not repeat after it's completed.
Result: the animation is over super fast and makes it hard to read fast jump maps.
**Screenshots or videos showing encountered issue:** 
lazer
![image](https://user-images.githubusercontent.com/32612290/68519692-593dbe00-0271-11ea-923c-ce25095e2e19.png)
vs stable
![image](https://user-images.githubusercontent.com/32612290/68519870-9b1b3400-0272-11ea-9564-11e63ed06da1.png)

**osu!lazer version:** 
2019.1106.0

**Comment by bdach** [comment] 2019-11-09 01:01
After loading up the skin and having a look this seems to be caused by the lack of code path separation of animated follow points from non-animated ones, which would make this a duplicate of #6214; closing as such.

**Closed by bdach** 2019-11-09 01:01 UTC
