### ISSUE TITLE
Tournament client performance issues (video decode related?)

### ISSUE THREAD

**Issue by KotRikD** [ppy/osu#11477] opened 2021-01-13 20:03 UTC
**Describe the bug:** There are strange lags on video(mp4) on certain tabs. I think this is due to the number of teams, of which we have 64. But I don't understand why it only happens on a couple of tabs

**Screenshots or videos showing encountered issue:** 
[link to video](https://baka-ero.kotworks.cyou/new/2021-01-13%2022-57-28.mp4) look on schedule/win tabs. A little lags bracket, but it is understandable, 64 commands are difficult to render. And compare it to the mappool or gameplay tabs.

**osu!lazer version:** GitHub version from this commit [*click*](https://github.com/ppy/osu/commit/faed776112746d17e1a9aacfbd74a658b81f1b21)

**Logs:**
[network.log](https://github.com/ppy/osu/files/5810816/network.log)
[performance.log](https://github.com/ppy/osu/files/5810817/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5810818/runtime.log)
[database.log](https://github.com/ppy/osu/files/5810819/database.log)

**Comment by bdach** [comment] 2021-01-13 20:07
What is the resolution of the background video itself? I have seen some pretty choppy results with 4K video backgrounds. Would be useful if you also pulled up the FPS counter and the performance window (<kbd>Ctrl</kbd>+<kbd>F11</kbd> and <kbd>Ctrl</kbd>+<kbd>F2</kbd>, respectively) so that we can see what's eating up frame time in particular.

That said the way we do video (software decoding) is not super efficient. Related issue: https://github.com/ppy/osu-framework/issues/4079

**Comment by TheEZIC** [comment] 2021-01-13 20:14
The main oddity. It does not lag in all menus. I don't remember how it's now, but it lag on the winning screen in the past.

**Comment by KotRikD** [comment] 2021-01-13 20:17
[Another vid with fps advanced counter](https://baka-ero.kotworks.cyou/new/2021-01-13%2023-13-32.mp4)
This video is 1920x1080 encoded with N.VENC with CQP=19.

I thought now, maybe it has problems with high bitrate?

**Comment by bdach** [comment] 2021-01-13 20:23
1080p isn't *that* much. High bitrate may be related, yeah, but I can't say that I've looked into video decoding perf much. Best bet is probably having a go at hardware decoding and seeing if it improves things.

**Comment by peppy** [comment] 2021-01-14 02:02
To rule out other issues, have you tried turning off the video or replacing it with another one? This seems like something that you could fix at your end in the short term (fixing video decoding performance is not that high on our priorities right now).

**Comment by KotRikD** [comment] 2021-01-14 10:49
Yesterday I tried to take video from my old tournament, it was about the same situation, also I tried to reduce the bitrate of the video, as I wrote above, but this also did not lead to any success.

**Comment by KotRikD** [comment] 2021-01-14 10:52
And I think the videos are okay, because on the mappool or gameplay tab all is fine

**Comment by peppy** [comment] 2021-01-14 15:47
Can you reproduce with *no videos loaded* then?

**Comment by bdach** [comment] 2021-01-14 17:14
As @MiraiSubject rightly pointed out on discord the tournament client shown on the video seems to have modifications applied to it (bracket matches are wider, avatars are circular). Does the same thing occur on a clean build without these modifications? Additionally, are you building the modified tournament client in release config?

**Comment by KotRikD** [comment] 2021-01-14 21:02
[video](https://baka-ero.kotworks.cyou/new/2021-01-14%2023-56-31.mp4)

from beginning - 01:06 @bdach question
01:06 - end @peppy question

**Comment by bdach** [comment] 2021-01-14 21:09
Certainly looks like bracket view isn't holding up too well perf-wise when zooming out even on master. The choppy background may still be due to decode perf, possibly because [this branch in the decode loop](https://github.com/ppy/osu-framework/blob/105a17bc99cad251fa730b54c615d2b0d9a409d3/osu.Framework/Graphics/Video/Video.cs#L135) is getting hit. Again, that may well improve with hardware decoding.

**Comment by peppy** [comment] 2022-01-25 00:31
Hardware decoding has now been added- can you re-test this if possible?

**Comment by MiraiSubject** [comment] 2022-01-26 14:47
Retested using the video in https://github.com/ppy/osu-framework/issues/3519 and have not encountered any performance issues. Decoding also correctly works on the graphics card now. 

![image](https://user-images.githubusercontent.com/803255/151184686-fbc5d6df-26ee-4d17-8e73-d09054fdb870.png)

**Comment by peppy** [comment] 2022-01-30 10:16
Will tentatively close this for now, thanks for testing.

**Closed by peppy** 2022-01-30 10:16 UTC
Labels: type:performance, framework-fix-required, area:tournament
