### ISSUE TITLE
Alternate acc display setting

### ISSUE THREAD

**Issue by Lapsyy** [ppy/osu#12828] opened 2021-05-15 17:27 UTC
A setting which allows you to displays your potential highest acc you can with your play, for example:

For the normal acc display, if your first note is a 100 in a 1000 note beatmap, the displayed acc would be **33.33%**.

For the proposed setting, the displayed acc for the same situation above will instead be **99.93%** as that would be your acc if you SSed the remaining 999 notes.

**Comment by bdach** [comment] 2021-05-15 17:32
Duplicate of #9336

**Closed by bdach** 2021-05-15 17:32 UTC
