### ISSUE TITLE
lazer crashes on linux

### ISSUE THREAD

**Issue by Neon095** [ppy/osu#18213] opened 2022-05-10 19:26 UTC
### Type

Crash to desktop

### Bug description

Sometimes, when i lose, the game crashes on the death animation.

### Version

I realised on 2022.501.0 (and after), but i think it happened to me in older versions before.

### Logs

[database.log](https://github.com/ppy/osu/files/8664435/database.log)
[network.log](https://github.com/ppy/osu/files/8664436/network.log)
[performance.log](https://github.com/ppy/osu/files/8664437/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8664438/runtime.log)

**Comment by bdach** [comment] 2022-05-10 19:28
Duplicate of #17215

**Closed by bdach** 2022-05-10 19:28 UTC
