### ISSUE TITLE
drain time and star rating not updating correctly for maps edited in lazer

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12048] opened 2021-03-18 00:09 UTC
when exiting out of a map after changes are made, the difficulty stats dont update with drain time or difficulty (it updates star rating upon restarting the game, but not drain time)

drain time is showing as zero
![image](https://user-images.githubusercontent.com/80785742/111553154-b0b04000-877b-11eb-8d03-41448189e503.png)

but the difficulty has a few notes in it
![image](https://user-images.githubusercontent.com/80785742/111553127-a3935100-877b-11eb-8c6a-cc8bc964b428.png)

osu!lazer 2021.312.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6160403/database.log)
[network.log](https://github.com/ppy/osu/files/6160404/network.log)
[performance.log](https://github.com/ppy/osu/files/6160405/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6160406/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6160407/updater.log)

**Comment by AndyThePie** [comment] 2021-04-28 04:36
If I could add my own comment to this - star rating does appear to calculate when mods are added (except for Hard Rock).

https://user-images.githubusercontent.com/25379179/116347118-95dcdc80-a7b9-11eb-80ae-98d25bed8467.mp4

The star rating stays the same when all objects are deleted as well...

https://user-images.githubusercontent.com/25379179/116346952-3d0d4400-a7b9-11eb-98de-45101acfe00e.mp4

(I have also seen discrepancies between auto + cinema while playing around with this, but I haven't been able to reproduce it.)

**Comment by peppy** [comment] 2021-04-28 04:39
I think if it's not a performance concern it's fine to just leave it calculate random each time.

**Comment by Theighlin** [comment] 2023-01-23 15:47
This has since been fixed. Can be closed.

**Comment by bdach** [comment] 2023-01-23 18:41
Resolved by https://github.com/ppy/osu/pull/18835

**Closed by bdach** 2023-01-23 18:41 UTC
Labels: area:database, type:UI
