### ISSUE TITLE
Ghost song entry in song select screen after updating a beatmap

### ISSUE THREAD

**Issue by HonkySora** [ppy/osu#21312] opened 2022-11-19 10:47 UTC
### Type

Other

### Bug description

Upon updating a beatmap using the in-game update button, when the game finishes the update and refreshes the beatmap, a ghost of the song's entry in the selection screen appears. This ghost entry persists being under the list until I exit out of the screen, in my case going back to the main menu.

As for what I'm doing while I'm updating the beatmap, I just stayed in the screen with the song highlighted. I also hovered over the update button while waiting for it to finish.

### Screenshots or videos

![osu_2022-11-19_18-31-16](https://user-images.githubusercontent.com/118601990/202846536-93cc8398-31f8-4f4e-bcb1-49eb78c78dd9.png)

### Version

2022.1117.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10046733/database.log)
[input.log](https://github.com/ppy/osu/files/10046734/input.log)
[network.log](https://github.com/ppy/osu/files/10046735/network.log)
[performance.log](https://github.com/ppy/osu/files/10046736/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10046737/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10046738/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10046739/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10046740/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10046741/updater.log)

**Comment by bdach** [comment] 2022-11-19 10:48
Duplicate of #21272

**Closed by bdach** 2022-11-19 10:48 UTC
