### ISSUE TITLE
[osu!lazer feature request]

### ISSUE THREAD

**Issue by StratusFearMe21** [ppy/osu#7894] opened 2020-02-18 22:37 UTC
One of the things I love about osu! is the fact that I can take it just about anywhere and play it on any computer from a USB drive. And I noticed that now the save data and beatmaps are stored in the AppData folder for osu!lazer. I was wondering if there is a way to change the directory to a USB drive or if this would transfer over to the final release or if I can at least, when the update launches, downgrade versions if I need to.

**Comment by smoogipoo** [comment] 2020-02-18 22:39
Dupe of https://github.com/ppy/osu/issues/960

**Closed by smoogipoo** 2020-02-18 22:39 UTC
