### ISSUE TITLE
lazer crashed while importing songs. 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#7181] opened 2019-12-13 08:53 UTC
**Describe the crash:** 
Just were sitting in the menu importing all my songs. didnt thow a notification or anything it just closed/crashed silently

**Screenshots or videos showing encountered issue:** 

N/A

**osu!lazer version:** 
1cd26a0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3959860/network.log)
[performance.log](https://github.com/ppy/osu/files/3959861/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3959862/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3959863/updater.log)
[database.log](https://github.com/ppy/osu/files/3959864/database.log)

Additonally checked the event viewer but shows nothing

**Computer Specifications:** 
i3 6100 Windows 10x 64 1909 8GB RAM.

**Comment by bdach** [comment] 2019-12-13 17:51
`database.log` shows a lot of:
```
2019-12-13 08:46:23: System.IO.IOException: System.IO.IOException: Insufficient system resources exist to complete the requested service. : 'E:\osu!\osu!\Songs\29813 Nobuo Uematsu - Not Alone'
2019-12-13 08:46:23: at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
(...)
2019-12-13 08:46:23: at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
2019-12-13 08:46:23: at osu.Game.IO.Archives.LegacyDirectoryArchiveReader.get_Filenames() in C:\Users\Nick Marcel\osu\osu.Game\IO\Archives\LegacyDirectoryArchiveReader.cs:line 30
```
followed by what seems the final death at
```
2019-12-13 08:46:23: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
2019-12-13 08:46:23: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2019-12-13 08:46:23: at Microsoft.Data.Sqlite.SqliteConnection.Open()
2019-12-13 08:46:23: at osu.Game.Database.OsuDbContext..ctor(String connectionString) in C:\Users\Nick Marcel\osu\osu.Game\Database\OsuDbContext.cs:line 72
2019-12-13 08:46:23: at osu.Game.Database.DatabaseContextFactory.CreateContext() in C:\Users\Nick Marcel\osu\osu.Game\Database\DatabaseContextFactory.cs:line 142
```

This seems to suggest resource issues, so to begin with:

* How large is the beatmap collection you're importing?
* Does this repeat? If so, can you reproduce with Task Manager open and see if the memory usage isn't spiking too much?
* How much space do you have left on disk?

**Comment by Lolihunter1337** [comment] 2019-12-14 02:38
The amount of Beatmaps is about 27550.

Yes it does repeat Ram usage does jump arround at times the max. i could see were about 7GB

Disk space left is 185GB at import and about 100GB at crash

**Comment by Lolihunter1337** [comment] 2019-12-14 19:13
@bdach well just as update i guess. i tried importing again with *existing* files and now i didnt crash up until about 19000beatmaps that being said i had to abort because the game runs really bad now 😅. System usage overall still didnt went to my 8GB Ram limit but lazer would use 4-5GB at times. If theres something else you need me to provide let me know.

**Comment by bdach** [comment] 2019-12-14 19:38
Well, another suspicion I have is that there might be a handle leak, although it'd have to be *really* bad. You could try running [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer), enabling the *Handle Count* column (right click the process table header, then *Select Columns* -> *Process Performance* tab -> check *Handle Count*) and checking that it doesn't spike too much (but then again it'd have to be [at the 16 million level](https://blogs.technet.microsoft.com/markrussinovich/2009/09/29/pushing-the-limits-of-windows-handles/) to produce the issue, so I doubt it's that).

**Comment by Lolihunter1337** [comment] 2019-12-14 19:44
thats probably something i should try only if needed in that case. importing this many maps takes well over 12h in my case so not really something i can quickly test

**Comment by peppy** [comment] 2019-12-17 06:25
Out of curiosity, do you have a swap file?

**Comment by Lolihunter1337** [comment] 2019-12-17 06:45
yes. 6144MB

**Comment by RBRat3** [comment] 2020-01-21 10:12
Just finishing up 14k beatmap import (will edit posting logs when done).

@bdach handle counts are listed in this image [https://puu.sh/F28pB/7cc188ef98.png](url)

**Comment by bdach** [comment] 2020-01-21 18:08
@RBRat3 I suppose that confirms that it's not the handles, count is way under what would cause the issue.

The video you've linked is super interesting too, as it doesn't look like a typical CPU stall caused by swapping to disk after physical memory has run out (I'd expect choppy audio and a global process stall at the least, let alone the fact you were able to capture video). The charts look also very weird, memory is full, but no CPU _or_ I/O load - looks like it might be the rollback taking place?

I'd say this needs in-person debugging by someone with dev chops so that someone can throw the perf debug kitchen sink at this problem.

**Comment by RBRat3** [comment] 2020-01-21 22:29
CPU is being loaded it just doesn't go any higher than 3% I suppose a different processor would exaggerate it better. What you don't see in that video is Lazer becoming responsive during that I/O spike, It'll process some 30-50 maps check the couch cushions for 200mb of RAM then go unresponsive for 20 minutes and repeat the whole process.

**Comment by bdach** [comment] 2020-01-21 22:33
Do you happen to have a 16-core processor with 2 logical CPUs per core? That many would indeed indicate 3% usage as worrisome (saturation of a single logical CPU). We do know import is constrained to a single core.

Those intermittent lag spikes do seem somewhat similar to swap stalls, but then again weird that they're constrained to one process only.

**Comment by RBRat3** [comment] 2020-01-21 22:35
Yes a Threadripper 1950X

**Comment by RBRat3** [comment] 2020-01-22 01:27
Figured I'd note here that after a client restart from the import song select takes an incredible amount of time to load which may or may not be related to this.
[https://puu.sh/F2mTz/b65c03e58e.mp4](https://puu.sh/F2mTz/b65c03e58e.mp4)

**Comment by peppy** [comment] 2022-01-22 05:57
Should be resolved with realm.

**Closed by peppy** 2022-01-22 05:57 UTC
Labels: area:database, type:reliability
