### ISSUE TITLE
the classic skin displays incorrect effects for long note presses in editor

### ISSUE THREAD

**Issue by QingQiz** [ppy/osu#25421] opened 2023-11-13 16:22 UTC
### Type

Game behaviour

### Bug description

in editor: 
1. The press light of long notes does not disappear with scroll back.
2. The initial brightness of long notes seems to be brighter than after scroll back.

### Screenshots or videos

Reproduction

https://github.com/ppy/osu/assets/33107216/94c1e767-b010-42ab-824d-edfbf1512ae3

![Screenshot 2023-11-14 001625](https://github.com/ppy/osu/assets/33107216/9c6f2a1a-7be0-4cea-95da-cd2e4d794fa6)

### Version

2023.1026.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13336902/database.log)
[input.log](https://github.com/ppy/osu/files/13336903/input.log)
[performance.log](https://github.com/ppy/osu/files/13336904/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13336905/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13336907/updater.log)

**Comment by bdach** [comment] 2023-11-13 16:34
Duplicate of https://github.com/ppy/osu/issues/10455

**Closed by bdach** 2023-11-13 16:34 UTC
