### ISSUE TITLE
Editor lag when scrolling through beatmap while paused

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#19955] opened 2022-08-25 03:22 UTC
### Type

Performance

### Bug description

When scrolling too fast the editor drops to under 10 frames per second, not much of an issue in itself, but might be the result of a larger underlying issue.

### Version

2022.821.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9421087/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9421088/updater.log)
[database.log](https://github.com/ppy/osu/files/9421089/database.log)
[network.log](https://github.com/ppy/osu/files/9421090/network.log)
[performance.log](https://github.com/ppy/osu/files/9421091/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9421092/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9421093/performance-update.log)

**Comment by smoogipoo** [comment] 2022-08-25 03:24
Please provide a video and the beatmap.

**Comment by Doksha** [comment] 2022-08-25 03:28
https://user-images.githubusercontent.com/72625258/186567921-4527d2c9-b8fa-44ab-b974-4452aed3f2b2.mp4

**Comment by peppy** [comment] 2022-08-25 03:31
Could you please link the beatmap you're seeing this on?

**Comment by smoogipoo** [comment] 2022-08-25 03:33
This looks like it's going to be a synchronous non-debounced `Seek()`:

![image](https://user-images.githubusercontent.com/1329837/186568514-c6c5a917-45a8-4168-906a-f8df10748f5f.png)

Can repro by smooth-scrolling on the timeline on any beatmap

**Comment by peppy** [comment] 2022-08-25 03:41
Sounds like it may be an unexpected regression from recent clock changes framework-side.

**Comment by peppy** [comment] 2022-08-25 07:22
Weirdly, I can't repro this on macOS. Potentially due to lower poll rate for input device or lower latency on seek operations (bass or otherwise).

I've create a probable fix at https://github.com/ppy/osu-framework/pull/5380, @smoogipoo would be great if you can test.

**Comment by smoogipoo** [comment] 2022-08-25 08:38
Will be fixed by https://github.com/ppy/osu-framework/pull/5380

**Closed by smoogipoo** 2022-08-25 08:38 UTC
Labels: priority:0, type:performance, area:editor
