### ISSUE TITLE
Leaving a map too early causes the score to show as failed

### ISSUE THREAD

**Issue by ParaliyzedEvo** [ppy/osu#25401] opened 2023-11-10 03:35 UTC
### Type

Game behaviour

### Bug description

Pretty much what the title says. When the map end I usually press escape to go back to the main menu as I always do. Before the newest version of lazer came out this wasn't a problem. But when I do it now the score shows as failed even though I finished the map through without failing it. Idk how you guys would fix this but I don't want to wait a second before pressing escape to go back to the menu. Hope you guys can help! (I will also provide the .osr file to help)
[Paraliyzed_evo playing nano - Bull_s eye (Chloe) [Skystar_s Extra] (2023-11-09_21-25).zip](https://github.com/ppy/osu/files/13315162/Paraliyzed_evo.playing.nano.-.Bull_s.eye.Chloe.Skystar_s.Extra.2023-11-09_21-25.zip)

### Screenshots or videos

![osu_2023-11-09_21-33-13](https://github.com/ppy/osu/assets/107338855/2061de43-d162-4aeb-992e-287883a2c1c3)

### Version

2023.1026.0

### Logs

[database.log](https://github.com/ppy/osu/files/13315146/database.log)
[input.log](https://github.com/ppy/osu/files/13315147/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13315148/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13315149/network.log)
[performance.log](https://github.com/ppy/osu/files/13315150/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13315151/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13315152/updater.log)

**Comment by bdach** [comment] 2023-11-10 03:42
Duplicate of https://github.com/ppy/osu/issues/25247

**Closed by bdach** 2023-11-10 03:42 UTC
