### ISSUE TITLE
Outro music (from a custom skin) keeps playing even after exiting to song select

### ISSUE THREAD

**Issue by Halbour** [ppy/osu#30170] opened 2024-10-09 12:31 UTC
### Type

Game behaviour

### Bug description

After playing a specific beatmap and getting B, I exited from the results screen, but the outro music was still playing and blended with the beatmap music. I use the skin in the picture.
Unfortunately, I don't have a video showcasing it. I tried to do that again, but it didn't happen (I got B).

### Screenshots or videos

![image](https://github.com/user-attachments/assets/17b8f711-d586-4b7a-8f0f-e344404e050d)
![image](https://github.com/user-attachments/assets/232b9931-12c4-45ff-99a9-e4e6ffe55c0d)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17308129/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-10-09 19:33
Duplicate of https://github.com/ppy/osu/issues/27917

**Closed by Joehuu** 2024-10-09 19:33 UTC
