### ISSUE TITLE
Mania long notes fall off the stage

### ISSUE THREAD

**Issue by RBRat3** [ppy/osu#7586] opened 2020-01-22 04:38 UTC
**Describe the bug:** Mania long notes continue to fall off the stage when hit instead of stopping at the judgement and collapsing.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/13491985/72865727-dee4dd80-3ca6-11ea-8429-bce4371a2805.png)

**osu!lazer version:** 2020.118.0

**Logs:** N/A

**Comment by smoogipoo** [comment] 2020-01-22 04:38
Duplicate of https://github.com/ppy/osu/issues/7508

**Closed by smoogipoo** 2020-01-22 04:38 UTC
