### ISSUE TITLE
Game crashes upon trying to load songs

### ISSUE THREAD

**Issue by Kidyeon** [ppy/osu#5746] opened 2019-08-17 13:12 UTC
**Describe the crash:** 
Whenever I start up osu!, it crashes from the main menu or song select with decreasing performance leading up to said crash, and the lack of ability to interact with anything besides the main menu (IE: I can't click settings, osu!direct, etc)

(An additional detail is that I spent about 16 hours importing 27k-ish songs from osu!stable prior to this, so maybe the volume of imported songs is the cause?)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/15699373/63212173-01564780-c0c6-11e9-8ba7-cdc9193f945f.png)

**osu!lazer version:** 
2109.814.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/3512025/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3512026/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3512027/updater.log)
[database.log](https://github.com/ppy/osu/files/3512028/database.log)
[network.log](https://github.com/ppy/osu/files/3512029/network.log) 

**Computer Specifications:** 
Windows 10 x64, Intel i5-4690k, Radeon RX 580, 16gb RAM

**Comment by Nyanekoy** [comment] 2019-08-17 13:42
Looks Like a duplicate of #5430

**Comment by peppy** [comment] 2019-08-19 01:59
Could you please attach your `client.db` file?

**Comment by Kidyeon** [comment] 2019-08-19 14:15
Well, due to github apparently not accepting files over 10MB and not accepting .db filetypes, I've uploaded it to mediafire instead: http://www.mediafire.com/file/t0g8byhhoyfy3k0/client.db/file

**Comment by Kidyeon** [comment] 2019-08-24 23:28
I updated my client to the newest version in an attempt to see if that would improve anything (via running the installer for the new version, as .814 didn't seem to give me the choice to update alongside everything else) and while I did get massively increased performance (which I'm guessing comes from other updates made to the master), I still had the same issues.

Here are my logs and a link to my client.db from after I updated:
[network.log](https://github.com/ppy/osu/files/3537640/network.log)
[performance.log](https://github.com/ppy/osu/files/3537641/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3537642/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3537643/updater.log)
[database.log](https://github.com/ppy/osu/files/3537644/database.log)
[client.db](http://download852.mediafire.com/ya6s7ipkm64g/h8dr6h1koll47zb/client%282%29.db)

**Comment by Joehuu** [comment] 2020-06-07 04:15
Probably fixed via https://github.com/ppy/osu/pull/8903 and other performance fixes during that time.

**Closed by Joehuu** 2020-06-07 04:15 UTC
Labels: area:database, type:crash
