### ISSUE TITLE
some icons don't show in song select

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5622] opened 2019-08-06 19:16 UTC
**Describe the bug:** some icons are blank circle in beatmap info wedge
changing beatmaps didn't make difference

**Screenshots or videos showing encountered issue:** 
![osu_2019-08-06_21-13-14](https://user-images.githubusercontent.com/32620809/62569793-450fac80-b88f-11e9-8e06-ec700f77bddb.jpg)

**osu!lazer version:** 2019.730.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3473804/database.log)
[network.log](https://github.com/ppy/osu/files/3473805/network.log)
[performance.log](https://github.com/ppy/osu/files/3473806/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3473807/runtime.log)

**Comment by iiSaLMaN** [comment] 2019-08-06 19:18
They're not implemented yet, blank circles are shown instead, you're welcome to add that.

**Comment by Joehuu** [comment] 2019-08-06 20:12
Duplicate of #2229.

**Closed** 2019-08-06 20:43 UTC
