### ISSUE TITLE
Cursor disappeared

### ISSUE THREAD

**Issue by LevelMasterGD** [ppy/osu#9554] opened 2020-07-14 01:58 UTC
I downloaded/installed latest build of osu!lazer (2020.712.0)...

At first launch the Cursor was visible, i imported beatmaps/scores...etc..., after that i restarted lazer and got a blackscreen (nothing happend).

I restarted lazer again and it started normally, but the cursor was "invisible/disappeared" and so i restarted osu!lazer again and again, but every time cursor wasn't visible (ingame too) 
(but i can see what im selecting, because of the hover effect) 

(i can give more informations, if i'm on PC "because it's night for me now")

**Comment by peppy** [comment] 2020-07-14 02:00
Duplicate of https://github.com/ppy/osu/issues/9554. Please post in the linked issue and provide your GPU model at very least.

**Closed by peppy** 2020-07-14 02:00 UTC

**Comment by LevelMasterGD** [comment] 2020-07-14 02:34
ok, i listed my specs. in the following issue
