### ISSUE TITLE
Replay data not saved correctly

### ISSUE THREAD

**Issue by Spooghetti420** [ppy/osu#23079] opened 2023-04-01 19:23 UTC
### Type

Game behaviour

### Bug description

I played a beatmap with only mouse buttons, and wanted to see how my gameplay looked, so I tried to load the replay, but it cut off my inputs very shortly after it began playing: the replay correctly reflected my first 2 or 3 inputs, before completely stopping moving the mouse and tapping altogether for the remainder of the beatmap.
What I got was exceedingly similar to https://github.com/ppy/osu/discussions/22552, but somehow it did track _some_ of the inputs rather than none.
To apparently explain why the replay was cut so short, the exported replay file (included in my logs) was no more than 1KB in size, whereas other replays for the same map and difficulty of previous plays were more like 23KB. Clearly the replay data isn't being saved correctly, for whatever reason. I cannot recall anything I did to trigger this, however.
Thanks.

### Screenshots or videos

![osu_2023-04-01_20-15-21](https://user-images.githubusercontent.com/83249561/229310008-f3232a5a-e0fe-482a-8890-21d52fc8a9ad.jpg)
Cursor is moving at the start, and it hits two hit circles.

![osu_2023-04-01_20-15-22](https://user-images.githubusercontent.com/83249561/229310009-4b49021c-34c3-4ff2-bc26-181a0dc30fdb.jpg)
After it reaches this position, it doesn't move again for 80 seconds and doesn't click.

Comparison of expected vs. replayed scores:
![osu_2023-04-01_20-13-52](https://user-images.githubusercontent.com/83249561/229310038-b44a9d78-eea8-4766-9d43-51c3e2065113.jpg)
![osu_2023-04-01_20-13-57](https://user-images.githubusercontent.com/83249561/229310039-4c1ffa71-3625-4f2f-9439-81a052a52798.jpg)

### Version

2023.326.1-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/11130396/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11130397/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11130398/updater.log)
[database.log](https://github.com/ppy/osu/files/11130399/database.log)
[input.log](https://github.com/ppy/osu/files/11130400/input.log)
[network.log](https://github.com/ppy/osu/files/11130401/network.log)

**I also uploaded the replay files here (as .txt instead of .osr). The first is the broken one, and the second a typical replay that works as expected.**
[Spooghetti420 playing Hyadain - Hyadain no Kakakata Kataomoi-C (TV Size) (Sushi) [Insane] (2023-04-01_19-58).txt](https://github.com/ppy/osu/files/11130403/Spooghetti420.playing.Hyadain.-.Hyadain.no.Kakakata.Kataomoi-C.TV.Size.Sushi.Insane.2023-04-01_19-58.txt)
[Spooghetti420 playing Hyadain - Hyadain no Kakakata Kataomoi-C (TV Size) (Sushi) [Insane] (2022-12-18_12-33) (NON-BUGGED).txt](https://github.com/ppy/osu/files/11130416/Spooghetti420.playing.Hyadain.-.Hyadain.no.Kakakata.Kataomoi-C.TV.Size.Sushi.Insane.2022-12-18_12-33.NON-BUGGED.txt)

**Comment by bdach** [comment] 2023-04-01 20:28
Duplicate of #23055

**Closed by bdach** 2023-04-01 20:28 UTC
