### ISSUE TITLE
Skins with certain missing elements show nothing instead of defaults

### ISSUE THREAD

**Issue by randomman254** [ppy/osu#10176] opened 2020-09-17 02:41 UTC
**Describe the bug:** I was playing with a few skins of mine, and I use the default hit circle overlay and default spinner approach circle, both of which were missing. This seems to be a component issue, i.e. the hit circle was skinned but there was no image for the hit circle overlay so the game displayed nothing instead of the default, same with the spinner.

**Screenshots or videos showing encountered issue:** 

Missing spinner approach circle:
![osu_2020-09-16_21-38-24](https://user-images.githubusercontent.com/30556038/93413486-00618d80-f865-11ea-8673-7cecb2552166.png)

Missing hit circle overlay:
![osu_2020-09-16_21-41-04](https://user-images.githubusercontent.com/30556038/93413656-5afae980-f865-11ea-9871-c3c2dc352c57.png)

**osu!lazer version:** 2020.910.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/5235904/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5235905/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5235906/updater.log)
[database.log](https://github.com/ppy/osu/files/5235907/database.log)
[network.log](https://github.com/ppy/osu/files/5235908/network.log)

**Comment by peppy** [comment] 2020-09-17 02:42
Duplicate of https://github.com/ppy/osu/issues/8019

**Closed by peppy** 2020-09-17 02:42 UTC
