### ISSUE TITLE
Noticable performance issue when selecting all notes on a beatmap

### ISSUE THREAD

**Issue by aerotracker** [ppy/osu#20936] opened 2022-10-25 22:22 UTC
### Type

Performance

### Bug description

The issue start to appear after more than 100 notes are selected (fps start dropping from 250 to 90 for me)
could be worse if more than 500 notes were selected at once. Threading Mode is on Multithreading
Even though its not that really causing any major effect at all, sometimes it's annoying to have a performance degradation just to check playfield usage 

Laptop specs:
CPU - Ryzen 7 4800H @ 2.9GHz
Graphic - NVidia GTX 1650 Ti 
RAM - 16 GB
 

### Version

2022.1022.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/9864392/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9864393/network.log)
[performance.log](https://github.com/ppy/osu/files/9864394/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9864395/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9864396/updater.log)
[database.log](https://github.com/ppy/osu/files/9864397/database.log)

**Comment by bdach** [comment] 2022-10-25 22:27
Duplicate of #17712

**Closed by bdach** 2022-10-25 22:27 UTC
