### ISSUE TITLE
Issue with Cursor trails

### ISSUE THREAD

**Issue by Zofainsley** [ppy/osu#6245] opened 2019-09-24 18:40 UTC
**Describe the bug:** 
Imported my skin, noticed the cursor trail was triple the size of my cursor, no in game settings to modify. 
Deleted the cursor trail and reimported all my skins after deleting the previous version and it still does the same.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
2019.919.0
**Logs:** 
N/A

**Comment by Zofainsley** [comment] 2019-09-24 18:40
Just add an ingame setting to disable trails.

**Comment by mouzedrift** [comment] 2019-09-24 18:45
theres a setting to disable the cursor trail.
also, duplicate of #6103 ?

**Comment by iiSaLMaN** [comment] 2019-09-24 20:38
Confirming this being a duplicate of #6103 by the provided details, Can be closed.

**Closed** 2019-09-24 20:39 UTC
