### ISSUE TITLE
New input system breaks 3rd party drivers

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12167] opened 2021-03-24 09:33 UTC
Hello!

Instead of using in-game driver I use this [driver](https://github.com/hawku/TabletDriver).
After new update my zone became bigger and I cant use whole screen now.

Improvements to in-game driver:

add more options to in-game driver,
make measurements more precise,
use other aspect ratio calculator for better understanding,
start calculating offset from the edge of area

![image](https://user-images.githubusercontent.com/64481039/112285038-2c355400-8c8a-11eb-8e42-464be8f126ee.png)
Can't move cursor using tablet anywhere beyond this point

![IMG_20210324_101903 (2)](https://user-images.githubusercontent.com/64481039/112286665-d5307e80-8c8b-11eb-904d-eee89e11cba9.jpg)
Pen is already beyond tablet are and cursor is only on magic stop pixel

2021.323.0

**Comment by adryzz** [comment] 2021-03-24 12:03
If you're not using the in-game driver then it's impossible that the area became bigger, as your driver and osu! do not talk to each other,

**Comment by frenzibyte** [comment] 2021-03-24 12:08
Can you confirm you've disabled the in-game driver from settings (clear check from `Enabled` in tablet section), also I'm presuming you're running in fullscreen mode, can you check whether windowed and borderless mode don't suffer from this issue?

**Comment by LemonJuicer** [comment] 2021-03-24 12:32
> If you're not using the in-game driver then it's impossible that the tablet area became bigger, as your driver and osu! do not talk to each other,

Thats why it only breaks in osu!.

**Comment by LemonJuicer** [comment] 2021-03-24 12:33
> Can you confirm you've disabled the in-game driver from settings (clear check from `Enabled` in tablet section), also I'm presuming you're running in fullscreen mode, can you check whether windowed and borderless mode don't suffer from this issue?

Windowed mode is not affected. Will chech fullscreen windowed later.

**Comment by LemonJuicer** [comment] 2021-03-24 17:34
Problem only occurs in fullscreen. If I switch to windowed and back to fullscreen it disappears. Turns out zone is not being changed, the only problem is that i cant use whole screen.

**Comment by frenzibyte** [comment] 2021-03-24 17:35
Duplicate of https://github.com/ppy/osu/issues/12156, then.

**Comment by LemonJuicer** [comment] 2021-03-24 17:36
It doesn't dissapear when switch to windowed and back to fullscreen, just got lucky.

**Closed by frenzibyte** 2021-03-24 17:35 UTC
Labels: missing details
