### ISSUE TITLE
Not enough HP drain

### ISSUE THREAD

**Issue by Ethereal-Dev** [ppy/osu#8155] opened 2020-03-06 15:06 UTC
**Describe the bug:** 
HP does not drain fast enough like on stable.
When playing, say, the big black on osu!stable, you die when missing 5 circles. However, when on osu!lazer, you are able to miss about twice as much before dying.
The same thing happens for other maps such as Blue zenith [four dimensions]

**Screenshots or videos showing encountered issue:** 
https://youtu.be/rePRiayVwig

**osu!lazer version:** 
2020.306.0

**Logs:**
none

**Comment by jai-x** [comment] 2020-03-06 15:15
Duplicate of https://github.com/ppy/osu/issues/7975

Please search for existing issues before opening new ones.

**Closed** 2020-03-06 16:22 UTC
