### ISSUE TITLE
Improve difficulty calculation and add extra statistics

### ISSUE THREAD

**Issue by Panthr75** [ppy/osu#10264] opened 2020-09-27 04:13 UTC
# Describe the new feature:
Although the star difficulty helps a user determine the difficulty of a level, there will be times where one star up could subtly increase something not shown in the difficulty (for example, `The Return` has a drop that greatly increases the speed in mania, making it near impossible to see or let alone hit objects if you are playing with a high enough speed __[both in normal osu!standard in osu!lazer]__).

Seeing as other mode's statistics (like `Approach Rate` for osu!mania or `Circle Size` in osu!taiko), don't play much of a role.

For example, `Circle Size` isn't really helpful for `osu!mania`:
![image](https://user-images.githubusercontent.com/29237603/94355499-24ce1e80-004a-11eb-9c05-11bf85c1651a.png)

Furthermore, the `I'm back, move` difficulty in `The Return` displays as 2 and 3/4 stars, but should be increased to possibly 3 to maybe even and and 1/4 because of the BPM changes:
![image](https://user-images.githubusercontent.com/29237603/94355660-8d69cb00-004b-11eb-8bde-db4ca7033f13.png)
Although yes, it the info at the top can help, but the difficulty rating should reflect the rapid change too:
![image](https://user-images.githubusercontent.com/29237603/94355742-4b8d5480-004c-11eb-839e-2694d63fccc0.png)

#### The insane BPM change:
[the_return_drop.zip](https://github.com/ppy/osu/files/5287710/the_return_drop.zip)

### Overview
With changes to the difficulty system and more useful statistics, players could get more of a feel for the difficulty of a level when playing other modes (because the osu! mode statistics work more than enough for most players)

# Proposal designs of the feature:
All modes should display a statistic that is the number of `notes per second`, which could be calculated via an average
of the following formula:
    `BPM * 60 * notes per beat`
- Sliders for `osu!` should be counted as two notes (one for the head, and one for the tail) plus one note for each additional `tick`
- Sliders in `osu!mania` should always be counted as two notes.
- Sliders (or patterns I guess) in `osu!taiko` should be counted for each `tick` in the slider/pattern.
- Normal notes should be counted as one note
- Spinners should also be counted as one note

There should be a statistic of the average `distance per two notes`
 - Hovering over said statistic would show the lowest distance per two notes, and the highest distance per two notes

Difficulty calculation should take into account the said statistics (`Distance / Note` and `Note / Second`).

Of course with these new statistics, there should be a place to put them, which I think they could fit in with the banner of levels:
![image](https://user-images.githubusercontent.com/29237603/94355854-5a283b80-004d-11eb-8646-cf3db44050cd.png)

**Comment by LastExceed** [comment] 2020-09-27 12:13
I believe there is some fundamental issues here that need to be addressed rather than worked around:
1. BPM affecting scroll speed in mania (idk about other modes), more to that here: #10267
2. osu! standard beatmap properties being repurposed in other modes. `CircleSize` for example is used for the key-count in mania maps. the x-coordinate is used for the column (by dividing the stage width by the column count, then flooring the value), y-coordinate is completely unused, single notes are sliders that end at the beginning of the map, and lots of other WTFs. Peppy mentioned in #1443 that the file format will eventually be reworked entirely.

**Comment by smoogipoo** [comment] 2020-09-28 01:51
Let me just clarify - you're mostly asking for difficulty calculation to be improved here, correct?

Display wise we could add NPS and DPN, but maps aren't a linear thing - NPS/DPN increase and decrease all over the place and I don't think average values are a good measure to use. Maybe the maximum is better, however I think a graph would be better suited? There's a big difference between a single 40NPS burst and a sustained 40NPS "kiai" section.

**Comment by abraker95** [comment] 2020-09-28 02:18
A graph would be wonderful

**Comment by LastExceed** [comment] 2020-09-28 11:22
overall NPS is an extremely inaccurate representation of difficulty, because almost every map has slow parts (usually beginning/end). A graph would *somewhat* fix this, but still hold the problem that NPS doesn't equal (not even correlate) difficulty (consider double trills).

DPN makes even less sense, as absolutely every half-decent map would always have a value very close to 100% of default scroll speed. The example in the OP is simply a very bad map.

In the end this issue here boils down to 2 things:
First, how to account for SV in difficulty calculation, for which we first need to decide whether or not we even want to do that in the first place (because of the memorization drama), and second, how detailed should difficulty be displayed. Right now we have a single number (SR) that summarizes everything. Do we want to split that into metrics for individual skill-sets like Etterna did? Or use Graphs as suggested above? We can't even begin to discuss this because we don't know yet what the new difficulty calculation system will even support.

I'd argue that this issue here is a duplicate of #2553

**Comment by smoogipoo** [comment] 2020-09-28 11:30
Yeah I think I'll close this as a duplicate of #2553, since it seems to be mostly focused around SR. Fwiw, lazer's mania SR doesn't even match stable right now.

Going forward the idea is for the difficulty calculators to output everything about the difficulty of the map, including any extra statistics that might be interesting to know. That can include NPS/DPN as extra statistics, even though they may not be factored into SR - they're just interesting to know.

**Closed by smoogipoo** 2020-09-28 11:30 UTC
Labels: area:song-select, proposal
