### ISSUE TITLE
osu!lazer multiplayer scores not submiting

### ISSUE THREAD

**Issue by Pallid3** [ppy/osu#22753] opened 2023-02-28 10:31 UTC
### Type

Other

### Bug description

In osu!lazer, when playing a map in multiplayer, the score doesn't show up in leaderboards or in Recent Plays at osu lazer website (https://lazer.ppy.sh/users/20447062 in that case.)

When playing a map in singleplayer, then score do submit and show up on leaderboard.

I made short video showing it (uploaded on yt, cuz too big file size for github upload): 
https://www.youtube.com/watch?v=rMTJMOfel3g

### Version

2023.207.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/10849174/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10849175/legacy-ipc.log)
[performance-audio.log](https://github.com/ppy/osu/files/10849176/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10849177/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10849178/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10849179/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10849180/performance.log)
[network.log](https://github.com/ppy/osu/files/10849181/network.log)
[runtime.log](https://github.com/ppy/osu/files/10849182/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10849183/updater.log)
[database.log](https://github.com/ppy/osu/files/10849184/database.log)

**Comment by bdach** [comment] 2023-03-01 18:24
Duplicate of #15888

**Closed by bdach** 2023-03-01 18:24 UTC
