### ISSUE TITLE
I beleive I have found the problem with the first frame being wrong in rewinds

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu#11333] opened 2020-12-27 08:27 UTC
https://github.com/ppy/osu/blob/6849eabf2ce56db434d9a68829f63207659b78a1/osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs#L124-L133

This checks if the time has passed the next frame ( in rewind, the previous ). However, that is not how frames work. The previous frame should be trigerred when the time is less than the current frame, not the previous. Allow me to illustrate: 
https://www.youtube.com/watch?v=eS4unB5D37A&feature=youtu.be
These should instead be something along the lines of:
```cs
if (next != null)
{
    if ( currentDirection == 1 )
    {
        if ( time >= next.Time )
        {
            currentFrameIndex = clampedNextFrameIndex;
            return CurrentTime = CurrentFrame.Time;
        }
    }
    else if ( currentDirection == -1 )
    {
        if ( CurrentFrame != null && time < CurrentFrame.Time )
        {
            currentFrameIndex = clampedNextFrameIndex;
            return CurrentTime = CurrentFrame.Time;
        }
    }
}
```

**Comment by frenzibyte** [comment] 2020-12-27 08:30
Isn't that basically what https://github.com/ppy/osu/pull/11264 fixes?

**Comment by bdach** [comment] 2020-12-27 08:32
I believe this is actually a duplicate of #6150.

**Closed by bdach** 2020-12-27 08:33 UTC
