### ISSUE TITLE
Artifacts in Fonts

### ISSUE THREAD

**Issue by sr229** [ppy/osu#6122] opened 2019-09-15 08:13 UTC
**Describe the bug:** 

There is some black artifacts surrounding the fonts and the icons. This might be my GPU but the rendering seems off.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/14976516/64918648-af433780-d7d3-11e9-8526-c786512b5dca.png)

**osu!lazer version:**  2019.913.0

**Logs:**

**Comment by Joehuu** [comment] 2019-09-15 08:20
Duplicate of #6118. Please list your specs there.

**Closed by Joehuu** 2019-09-15 08:20 UTC
