### ISSUE TITLE
An Ability to change where your songs/screenshots stuff go (the osu! folder)

### ISSUE THREAD

**Issue by JunkynioyPH** [ppy/osu#7390] opened 2019-12-29 02:49 UTC
As a person with limited OS DISK space, i like putting stuff into different places that is not the ones running out of space.

Add a way to change where the "osu!" folder is.

**Comment by EVAST9919** [comment] 2019-12-29 02:54
Duplicate of https://github.com/ppy/osu/issues/960

**Closed** 2019-12-29 04:14 UTC
