### ISSUE TITLE
Audio Glitches out

### ISSUE THREAD

**Issue by Toybonnie1234512341** [ppy/osu#4030] opened 2019-01-09 15:59 UTC
I’m not sure if I can post this here but I experienced an audio glitch that fried my MacBook Pro speaker and bottom left of the screen. I’m currently running the latest version of Osu Lazer. I’m currently trying to get my 2018 MacBook Pro 15 inch replaced because of this.

**Comment by Toybonnie1234512341** [comment] 2019-01-09 16:18
Is this just bad luck? And it’s a defect?

**Comment by jai-x** [comment] 2019-01-09 16:18
This seems like a similar issue to this: https://github.com/ppy/osu/issues/3648

It is reported that restarting the Mac fully may fix the system audio.

**Comment by Toybonnie1234512341** [comment] 2019-01-09 16:20
Full restart? Just restarting once or?

**Comment by peppy** [comment] 2019-01-09 16:39
There has also been a report of another hardware damaged system (@Tom94's). Sorry for the inconvenience. I do believe this is somewhat Apple's issue for not having hardware-level limits, but we definitely do need to get to the bottom of this soon (days), else I will be pulling the macOS build as a precautionary measure.

Closing as duplicate of #3648.

**Closed by peppy** 2019-01-09 16:39 UTC
