### ISSUE TITLE
Two factor authentication needs to be implemented

### ISSUE THREAD

**Issue by peppy** [ppy/osu#20590] opened 2022-10-06 03:35 UTC
Is currently skipped in lazer. This was fine back when lazer was read-only, but should be considered a priority now that things have evolved. Was kind of forgotten about.

### Discussed in https://github.com/ppy/osu/discussions/20589

<div type='discussions-op-text'>

<sup>Originally posted by **htmlpaws** October  6, 2022</sup>
**_Hello there!_**

I recently got a new laptop, and after logging in, I realized there is currently no account verification feature like there is on osu!stable. I feel it should be added because without it, random people are able to log into an account that might not be theirs and engage in social functions (chat, score upload, etc.) without any proof it's actually said user, which can be used to target users.

I think additionally in the future there should be a built in GUI for the code which could allow for input to be easier on mobile for example, where sometimes opening another app can fully close out the game, along with not having to open a popup browser which is annoying in general. Another security thing that I wana put in an as idea if support for 2fa apps, as having to use email can be kinda annoying if you get the code lost in a pile of emails or shoved in a random folder.

Thanks again,
_@htmlpaws (Ethacc on osu.)_</div>

**Comment by MkGuh** [comment] 2022-10-14 03:25
Duplicate of #9655.

**Comment by BlestLace** [comment] 2022-10-16 07:40
Didn't peppy open this issue xD

**Comment by peppy** [comment] 2022-10-16 07:54
Will keep this one open as metadata is more up-to-date.

**Comment by LiquidPL** [comment] 2023-08-30 18:42
I've looked into this a little, and there's one thing concerning me, mainly that the password grant we're using for auth on osu-web side appears to be [disallowed/deprecated](https://oauth.net/2/grant-types/password/) in the most recent versions of oauth. With that in mind I have a few questions:

* Would it be acceptable to implement a separate auth flow in web for lazer? It might be difficult to graft 2FA in a sane way onto password grant auth, especially since we might have limited library support going forward.
* Does lazer use any of the oauth scopes, or does it have full acccess to the API?

**Comment by peppy** [comment] 2023-08-31 06:55
I discussed this with @nanaya in recent times, and his opinion was that we should be using a standard oauth flow. A lot of other apps seem to do that these days (requiring visiting a browser to login) but I'm not sure that's the UX we want to go for.

Either way, I think @nanaya would be able to give you better answers here than I can.

In terms of UX:

- I'd hope we can keep the current flow intact.
- For the 2FA part, the game would show a message while waiting for email 2FA, and poll for completion, similar to web.

There's also consideration of https://github.com/ppy/osu-web/issues/5163, which I think would also have an in-game entry for the code to keep the UX in line with expectations. Not sure if that should come first (probably not since we just want to get things working first).

**Comment by peppy** [comment] 2023-09-10 03:45
I think that sound fine, see how it goes.

**Comment by peppy** [comment] 2023-12-20 06:29
As an update, osu-web pieces are now in place for this. I hope to revisit this week to implement the API part at our end.

**Comment by peppy** [comment] 2023-12-27 08:19
Moving out of project. This will happen early next year.

**Closed** 2024-01-29 10:14 UTC
Labels: type:online, priority:1
