### ISSUE TITLE
Hits appear behind the hitcircles and sliders instead of in front

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10284] opened 2020-09-29 03:34 UTC
**Describe the bug:** 

Just as stable does, hits should be placed in front of hit circles and sliders and not behind.
The problem is that you can not see if you are hitting right or not, because you can not see the hits.
In the case of the skin I use (smoogipo skin) hits are just dots, but I've tested with other skins and the problem remains the same.

I tested playing [this map](https://osu.ppy.sh/beatmapsets/1785#osu/21010) where is more noticeable.

**Screenshots or videos showing encountered issue:** 

Stable: 
![stable 2](https://user-images.githubusercontent.com/41755816/94509527-d73ce780-01ea-11eb-9244-bb1417ffd5e1.jpg)

Lazer:
![lazer 2](https://user-images.githubusercontent.com/41755816/94509546-ddcb5f00-01ea-11eb-8814-20c1e53d58b2.jpg)

**osu!lazer version:** 

2020.925.0

**Comment by frenzibyte** [comment] 2020-09-29 03:35
Duplicate of https://github.com/ppy/osu/issues/7584, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2020-09-29 11:22 UTC
