### ISSUE TITLE
osu!mania long notes not appearing during play

### ISSUE THREAD

**Issue by dxpperwoke** [ppy/osu#20295] opened 2022-09-14 04:19 UTC
### Type

Game behaviour

### Bug description

was using my skin imported from stable, long notes (lns) and ln tails do not appear during gameplay, but for some reason other skins i have do work. i'll attach my skin below, along with videos comparing the skin i was using when the issue was found to a skin ive used previously. 

[terraskin.zip](https://github.com/ppy/osu/files/9562595/terraskin.zip)

### Screenshots or videos

https://user-images.githubusercontent.com/85380214/190056737-7aa2062f-f0b8-45c5-b7b9-b02aba29c94c.mp4

https://user-images.githubusercontent.com/85380214/190056766-e16e2197-a2b1-44e4-b774-7b645e667017.mp4

### Version

2022.911.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9562567/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9562568/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9562569/updater.log)
[database.log](https://github.com/ppy/osu/files/9562570/database.log)
[network.log](https://github.com/ppy/osu/files/9562571/network.log)

**Comment by peppy** [comment] 2022-09-14 04:22
Duplicate of https://github.com/ppy/osu/issues/12057 (your hold note sprites are 40,000 pixels tall).

**Closed by peppy** 2022-09-14 04:22 UTC
