### ISSUE TITLE
Relax imported scores from stable show misses

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#19596] opened 2022-08-06 00:27 UTC
### Type

Game behaviour

### Bug description

Tried to import all my stable scores and noticed when replaying my relax scores that they were showing misses, presumably because of the key registration, but yeah, shouldn't be happening, I've attached two screenshots, the score itself imported from stable and the score after replaying (notice all the misses) 

### Screenshots or videos

![Screenshot_1](https://user-images.githubusercontent.com/54728307/183226106-bea895ee-33fe-4304-8833-942782daf238.png)

![image](https://user-images.githubusercontent.com/54728307/183226101-c3f931af-2ed0-4ac1-8bc4-c4c8ce345118.png)

### Version

2022.731.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9274086/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9274087/updater.log)
[database.log](https://github.com/ppy/osu/files/9274088/database.log)
[network.log](https://github.com/ppy/osu/files/9274089/network.log)
[performance.log](https://github.com/ppy/osu/files/9274090/performance.log)

**Comment by frenzibyte** [comment] 2022-08-06 00:54
Duplicate of https://github.com/ppy/osu/issues/9243

**Closed by frenzibyte** 2022-08-06 00:54 UTC
