### ISSUE TITLE
Skipping beatmap intro in multiplayer not possible. 

### ISSUE THREAD

**Issue by chiascuro** [ppy/osu#31031] opened 2024-12-09 09:53 UTC
### Type

Game behaviour

### Bug description

osu!lazer has the option to automatically skip beatmap intros in the lobby settings. With this setting enabled intros automatically get skipped so there is no problem there. However, if that setting is NOT enabled, then upon starting a map it is not possible to skip the intro, for any member of the lobby See Screenshot below. Tested with current version.
![osu!_w9SAk5niLN](https://github.com/user-attachments/assets/4bfb86f0-6784-425b-8d75-42079ca61ba1)

### Version

2024.1208.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18059518/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-12-09 09:59
Duplicate of https://github.com/ppy/osu/discussions/26273

**Closed by frenzibyte** 2024-12-09 09:59 UTC
