### ISSUE TITLE
Timings list in Lazer

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#10481] opened 2020-10-10 22:10 UTC
The normal Osu!Stable has this feature:
https://osu.ppy.sh/ss/15658057/ff30

But Lazer doesn't.
There's no timing list when hovering over anything of the map stats. (I tried everything)

I'm not sure, if there's a formula too, or if the timings are stricter/looser.

I need your help to get that into Osu!Lazer.

Greetings from germany,
JGD

**Comment by Joehuu** [comment] 2020-10-10 22:14
Duplicate of https://github.com/ppy/osu/issues/6202

**Closed by Joehuu** 2020-10-10 22:14 UTC

**Comment by GamingWithJanko** [comment] 2020-10-10 22:15
Whoops... Sorry. ^^'
