### ISSUE TITLE
bug with mouse sensitivity and tablet

### ISSUE THREAD

**Issue by Neeetale** [ppy/osu#13253] opened 2021-05-31 03:48 UTC
so there's a bug that change the area of the tablet if you change the mouse sensitivity, im using a wacom ctl 4100 and if i change from 1 in mouse sensitivity to something like 0.8 it will change the area of my tablet

**Comment by smoogipoo** [comment] 2021-05-31 03:50
How would you expect sensitivity to work? Perhaps the issue here is just that sensitivity adjustment is allowed while the in-game tablet driver is enabled.

**Comment by peppy** [comment] 2021-05-31 06:05
@smoogipoo have you actually confirmed this behaviour? there's zero sensitivity handling in the `OpenTabletDriverHandler` so I'm having trouble understanding how this could be a thing.

![20210531 150510 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/120147432-9980da80-c221-11eb-93c1-4d8db4888705.png)

Sounds like the user is not using the in-game tablet settings and... somehow expecting cursor sensitivity to be ignored (which I think is out of scope / not possible).

**Comment by smoogipoo** [comment] 2021-05-31 08:36
Tested and indeed it does work as expected. Closing as intended/invalid.

**Closed by smoogipoo** 2021-05-31 08:36 UTC
Labels: area:settings, framework-fix-required, type:input
