### ISSUE TITLE
Radius of resume cursor incorrectly changes with "gameplay cursor" setting

### ISSUE THREAD

**Issue by LunaticaUWU** [ppy/osu#25331] opened 2023-11-01 08:11 UTC
### Type

Game behaviour

### Bug description

As in the title, resume cursor window scales with Gameplay Cursor size.

### Screenshots or videos

cursor at 0.1x size, closest to resume window
![image](https://github.com/ppy/osu/assets/139059026/fca72ec3-727d-4e1f-aefb-b6886a77bf9a)
cursor at 2.0x size, closest to resume window 
![image](https://github.com/ppy/osu/assets/139059026/ebbd97b9-cda5-410c-b93c-5bbf9ef0a385)
(excat size of cursor in 1:1 ratio between the sizes)

### Version

2023.1026.0-lazer

### Logs

-

**Comment by bdach** [comment] 2023-11-01 08:26
> resume cursor window

What does this mean?

What are the pictures in the opening post? If you're changing cursor scale why isn't the cursor... smaller?

**Comment by LunaticaUWU** [comment] 2023-11-01 09:01
> > resume cursor window
> 
> What does this mean?
> 
> What are the pictures in the opening post? If you're changing cursor scale why isn't the cursor... smaller?

"Resume cursor window" - I've meant distance between cursor and _resume_ cursor

The pictures - **(excat size of cursor in 1:1 ratio between the sizes)** - I've made 2 screenshots with 2 cursors. I've made them match the size **in game** so the 0.1x cursor, **is the same size in game**, as 2.0x

**Comment by peppy** [comment] 2023-11-01 09:06
Please show this with the default skin. If it requires a custom skin to reproduce, please attach the skin.

**Comment by LunaticaUWU** [comment] 2023-11-01 09:21
https://github.com/ppy/osu/assets/139059026/04fcf44d-ff7c-4297-ab94-a4898761eab3
Im attaching a video to show it best I could

Skin to replicate:
[resumecursorbugskin.zip](https://github.com/ppy/osu/files/13225341/resumecursorbugskin.zip)

**Comment by peppy** [comment] 2023-11-02 06:34
Isn't the bug here that your cursor isn't scaling with cursor scale? Can you confirm that to be the case?

**Comment by bdach** [comment] 2023-11-02 06:38
This is what the user did to the cursor sprites:

![1698906979](https://github.com/ppy/osu/assets/20418176/0f595b83-e22d-4af7-914e-510969d2d25c)

I think it's safe to close this as "not how anything works". The game should not be trying to look at the user's cursor sprite and trying to trim the whitespace or whatever so that it scales correctly. If you put that much whitespace on your skin the issue is on you.

**Comment by LunaticaUWU** [comment] 2023-11-02 08:03
Hey, I think you missed the point. 
Im refferring to **resume cursor area**.
I made the cursor **look the same in game** to confirm the words im saying.
_Resume cursor area_ **scales** with _gameplay cursor size_, which makes resume area very small on 0.1x size, and big on 2.0x size, which is not occuring in stable (resume cursor area is the same no matter the size).
0.1x size - The distance where you can click resume cursor is very small.
2.0x size - The distance where you can click resume cursor is very big.
This is a gameplay bug, not a cosmetic one.

**Comment by bdach** [comment] 2023-11-02 08:08
Well that was about the most confusing way you could have went around demonstrating the issue.

Not sure whether I agree that stable's behaviour is the correct one though. I can see arguments for both.

**Comment by peppy** [comment] 2023-11-02 08:50
Finally we can understand what the issue is here.

**Closed** 2023-11-07 12:57 UTC
Labels: ruleset/osu!, priority:1
