### ISSUE TITLE
endless mod

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10263] opened 2020-09-26 23:31 UTC
when you pick this mod and pick a beatmap, when you finish a map, the game will pick another slightly harder map(0.00* to 0.08* harder) at random in the mode you picked the beatmap from and you will play that beatmap right away, with the only rest time you get outside of beatmaps is when the beatmap is loading

the cycle above repeats until you fail a map which at that point, the game will show you stats like how long you survived for like in a results screen

also, accuracy; combo; and score save between beatmaps
hp drain in this mod gets slightly harsher for every map passed regardless of the hp value of the beatmap, until you fail

you can also mix this mod with other mods to create more of a challenge, with the modified star ratings being used for next beatmap determination instead of original star ratings

edit: you cannot get the same map twice in a row and if you run out of maps to be chosen randomly, then the game automatically ends as if you lost

**Comment by lolxdhi1** [comment] 2020-09-27 06:45
Maybe consider adding an infinity sign as the mod icon.

**Comment by MitsukaiDokuro** [comment] 2020-11-01 21:03
Would call this Autoplay instead ;)

**Comment by imTCA** [comment] 2020-11-04 08:19
good idea and concept

**Comment by LeNitrous** [comment] 2020-11-06 03:54
I attempted in making this under the guise of a mod. The end result is that it doesn't look good. Not to mention mods only have the capability of modifying things within `Player`.

![image](https://user-images.githubusercontent.com/20495991/98323464-cb7fe480-2024-11eb-9fa9-565ebe9d3431.png)

My proposal is to add an entire new section in beatmap details like how it was done in the multiplayer lobbies where they can add and remove beatmaps where the player will play every beatmap in that playlist with their score, combo, and HP carrying over each map until the end of the defined playlist.

While the original issue requests that the beatmaps will be randomized but I'd prefer if player have control over it. As for timeshift, there can be two modes, either "free play", how it is now and "continuous" where everything on the playlist will be played in a single run.

**Comment by peppy** [comment] 2020-11-06 08:04
This definitely shouldn't exist as a mod with such local playlist configuration. It's intended to be a mode in timeshift; if there's a local playable version I highly doubt it would surface as a mod. There would likely be a playlist on solo song select similar to the timeshift system.

**Comment by Joehuu** [comment] 2020-11-06 15:04
Duplicate of https://github.com/ppy/osu/issues/5757

**Closed by Joehuu** 2020-11-06 15:04 UTC
Labels: area:mods, proposal
