### ISSUE TITLE
Active window for osu! is cut off

### ISSUE THREAD

**Issue by Petexy** [ppy/osu#12450] opened 2021-04-16 17:02 UTC
When playing any song I've noticed that I can't navigate through osu! window. Both my tablets (H420 and CTL-472) don't allow me to go to the right and to the bottom side of the window. Also, there's a problem when trying to hit circles using a pen, because of this.

https://user-images.githubusercontent.com/40914480/115059028-41e31580-9ee6-11eb-8c44-d2f727cfae27.mp4

**Comment by frenzibyte** [comment] 2021-04-16 17:04
Can you confirm disabling "high precision mouse" fixes it? if so, enable that back and set "cursor confinement" to never, then see if it fixes it as well.

**Comment by Petexy** [comment] 2021-04-16 17:09
> Can you confirm disabling "high precision mouse" fixes it? if so, enable that back and set "cursor confinement" to never, then see if it fixes it as well.

Disabling "High precision mouse" fixed that problem. However, setting "Cursor confinement" to never with "High precision mouse" enabled still causes the same problem

**Comment by frenzibyte** [comment] 2021-04-16 17:10
If you're running fullscreen that would explain it, try borderless with cursor confinement set to never instead.

**Comment by Petexy** [comment] 2021-04-16 17:19
That unfortunately did not solve this problem. When I set "Screen mode" to "Windowed" I can reach the end of the window with those settings. However, it still has a problem with inputs from a tablet, instead of using Z and X.

https://user-images.githubusercontent.com/40914480/115060851-a4d5ac00-9ee8-11eb-8490-2f0bbb37ca40.mp4

**Comment by frenzibyte** [comment] 2021-04-16 17:29
Well, I think we can consider this a duplicate of either https://github.com/ppy/osu/issues/12156 (maybe needs new title) or https://github.com/ppy/osu-framework/issues/4323. Closing.

**Closed by frenzibyte** 2021-04-16 17:29 UTC

**Comment by peppy** [comment] 2021-04-16 18:20
Please also ask these users *which* tablet software they are using. It has to be the same one for all of these reports.

**Comment by frenzibyte** [comment] 2021-04-16 18:29
One reporter states they were using OTD externally here https://github.com/ppy/osu/issues/12415, while https://github.com/ppy/osu-framework/issues/4323 states they were using hawku, so wasn't at all sure if it's due to the software they were using.

@Petexy Though it may be helpful if you answer which tablet software you were using?
