### ISSUE TITLE
Very long map loading and then freezing when playing map with long storyboard

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu#8950] opened 2020-05-06 06:15 UTC
**Describe the crash:** 
The beatmap: https://osu.ppy.sh/beatmapsets/577666#osu/1225805
The map loading takes very long, and if you wait for it long enough, it will freezes.
The bug doesn't happen when disabling storyboard.
It also doesn't happen on stable.

**osu!lazer version:** c903742d585a10bb479ee853d808695ed6215c1a

**Logs:**
[database.log](https://github.com/ppy/osu/files/4585052/database.log)
[performance.log](https://github.com/ppy/osu/files/4585053/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4585054/runtime.log)

**Comment by peppy** [comment] 2020-05-06 08:28
Storyboard optimisations are still a huge work in progress. This is a known issue.

**Comment by peppy** [comment] 2020-05-06 08:28
Duplicate of https://github.com/ppy/osu/issues/4976.

**Closed by peppy** 2020-05-06 08:28 UTC
