### ISSUE TITLE
osu!lazer doesn't run after update.

### ISSUE THREAD

**Issue by Yoppez** [ppy/osu#6109] opened 2019-09-14 10:50 UTC
**The issue:**
osu!lazer doesn't run at all after the new update and rebooting the computer.

I don't know if it has anything to do with it, but before rebooting the PC the game was working, and I deleted all the beatmaps and reinstalled them from osu!stable for testing the new background video feature. Now when I open osu!lazer, it appears a black screen for 3 - 4 seconds and then the game closes.

I also proved to unistall the game and reinstall it, but with no success.

**osu!lazer version:** 
2019.913.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/3612726/database.log)
[network.log](https://github.com/ppy/osu/files/3612727/network.log)
[runtime.log](https://github.com/ppy/osu/files/3612728/runtime.log)

**Computer Specifications:** 
CPU: Intel Core i7-3770
RAM: 8,00 GB
GPU: AMD Radeon R9 280X
OS: Windows 10 x64

Edit: Mispelled words.
Edit2: Logs added.

**Comment by iiSaLMaN** [comment] 2019-09-14 11:08
Can you try installing the latest working (in your end) lazer version just for confirming that the new lazer version is the cause of this issue?

**Comment by bdach** [comment] 2019-09-14 11:12
In addition to the above, are the log files just missing from `%AppData%/osu/logs`? If not, would you mind having a look at the system Event Viewer and checking out the `Windows Logs -> Application` category for any related entries? That would definitely help narrow down the cause.

**Comment by Yoppez** [comment] 2019-09-14 11:29
> In addition to the above, are the log files just missing from `%AppData%/osu/logs`?

My bad, I hadn't check that directory. Here are the logs:

[database.log](https://github.com/ppy/osu/files/3612648/database.log)
[network.log](https://github.com/ppy/osu/files/3612649/network.log)
[runtime.log](https://github.com/ppy/osu/files/3612650/runtime.log)

> Can you try installing the latest working (in your end) lazer version just for confirming that the new lazer version is the cause of this issue?

Done, and it seems that the issue is even in the previous version. So, unlike what I thought, the problem is **not** due to the newer version.

**Comment by bdach** [comment] 2019-09-14 11:37
Thanks for the logs. Unfortunately this looks like your sqlite database got corrupted in some way (logs show a foreign key constraint violation), so the beatmap reimport you performed is probably relevant here, and that is also why the rollback to an earlier version won't fix this.

I'm not honestly sure what could have caused this. Inspecting the database file could help, but I'm not sure if there is any particularly sensitive data in there (besides the obvious - list of beatmaps, skins, local scores etc.), so I'll defer to others that might be able to say with more certainty whether sharing that file is safe or not.

**Comment by iiSaLMaN** [comment] 2019-09-14 11:42
Can you please link your database file (`client.db`)

**Comment by Yoppez** [comment] 2019-09-14 11:46
> Can you please link your database file (`client.db`)

Here it is:
[client.zip](https://github.com/ppy/osu/files/3612671/client.zip)

**Comment by bdach** [comment] 2019-09-14 12:51
Good (?) news is, this might not be a completely random corruption, but an application error. Something isn't completely right with the schema.

The exception is generated upon startup around `BeatmapStore.Purge()`:
https://github.com/ppy/osu/blob/c157f3e817f28bdeb891230bcfd07769e4af3d75/osu.Game/Beatmaps/BeatmapStore.cs#L78-L88
There are some beatmaps in that database that are marked for deletion upon startup. The above method accounts for potential *M*-to-*N* relationships with `Metadata`. However, the database snapshot linked above has a score for beatmap with ID 5310, and in `ScoreFileInfo` the foreign key on `ScoreInfo` is `ON DELETE RESTRICT`. So, we have the following scenario:

* `BeatmapInfo` (ID 5310) deletion triggers `ScoreInfo` deletion
* `ScoreInfo` (ID 9116) deletion now triggers the violation of the `ScoreFileInfo` foreign key relation. If it was `ON DELETE CASCADE`, the issue wouldn't happen. I'm not sure if it was by design or not.
* Deleting the blocking `ScoreFileInfo` record (ID 9059) allows the `BeatmapInfo` record to be deleted.

So:
* Either that FK needs to be migrated to `ON DELETE CASCADE`, or
* `Purge()` needs to account for potential score info when purging beatmaps.

**Comment by Yoppez** [comment] 2019-09-14 13:24
Thanks a lot!
I would like to keep playing with osu!lazer. Is it okay if I delete the `%AppData%/osu` folder (after backing up, in case you want to do other investigations) and reinstall the game from scratch?

**Comment by iiSaLMaN** [comment] 2019-09-14 13:25
> Thanks a lot!
> I would like to keep playing with osu!lazer. Is it okay if I delete the `%AppData%/osu` folder (after backing up, in case you want to do other investigations) and reinstall the game from scratch?

Just move the folder somewhere else and run the game, it'll work.

**Closed** 2019-09-21 16:15 UTC
Labels: database, pending review
