### ISSUE TITLE
Placing lots of stacked notes, selecting them via timeline does not select all objects

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#20279] opened 2022-09-13 00:32 UTC
### Type

Game behaviour

### Bug description

From #18077 
Selecting a stack of notes in the timeline only selects the top 10 objects instead of all of the objects on that stack. You would expect all of the notes to be selected so you could quickly delete the whole stack all at once.

### Screenshots or videos

https://user-images.githubusercontent.com/17460441/189781714-cdc4ef03-3aae-4fe0-b7ab-98a042ddd5e6.mp4

### Version

https://github.com/ppy/osu/commit/00c9763d67f80de1673003a45eadbf8b9bfc23a9

### Logs

[runtime.log](https://github.com/ppy/osu/files/9552580/runtime.log)

**Comment by B3nn1** [comment] 2022-09-23 00:13
The ability to select hit objects via the timeline seems to be limited by the height and position of the `TimelineDragBox` used.

`TimelineDragBox` has this code to account for this:
![grafik](https://user-images.githubusercontent.com/9751465/191870928-0694a40a-0e99-4b7b-8392-c4581e052908.png)
but it still doesn't allow selecting stacks of more than 10 notes.

A (kind of cheap?) workaround could be [limiting the height of stacks in the timeline to 9 in general](https://github.com/ppy/osu/compare/master...B3nn1:osu:timeline-stacked-object-selection) since additional objects are off-screen and thus unselectable anyways. (Using 10 as the limit already leads to unwanted behaviour.)

Another idea I have is to somehow store the size of the largest stack in the map and adjust the `TimelineDragBox` accordingly. (Maybe in the `Timeline` class?)

**Comment by peppy** [comment] 2022-09-23 03:33
The selection should probably not use the visible drawables but instead just read the hitobjects.

Also am I missing something or is this a SUPER edge case because this is not used in any ranked beatmap and should not ever be used in any normal beatmap? The original implmenetation was designed knowing that it would break with usage like this, but also that usage like this is kind of out of scope.

**Comment by Feodor0090** [comment] 2022-09-23 07:41
What about 10K mania beatmaps? I don't see any problem to have 10 notes here on the same timestamp. And the 10th note won't be selectable. (if the 10th is selectable let's talk about 6K+6K)

**Comment by peppy** [comment] 2022-09-24 04:04
The game does not support "6k + 6k", and 10 notes is already selectable (the implementation was done with 10k in mind).

If the goal is future proofing, see the proposal I made in my last post.

**Closed** 2022-10-11 04:20 UTC
Labels: area:editor, type:UX, priority:2
