### ISSUE TITLE
using ctrl+1 to change mode to standard inserts "1" into search prompt or doesn't work at all

### ISSUE THREAD

**Issue by GoatSee** [ppy/osu#17735] opened 2022-04-09 00:14 UTC
### Type

Game behaviour

### Bug description

ctrl+1 doesn't change the mode to standard as it did in previous versions and just as in previous version it inserts "1" into the search prompt which it doesn't do for ctrl+2,3,4

### Screenshots or videos

![bug](https://user-images.githubusercontent.com/86989290/162548558-cda485dc-bac0-4098-a993-e62ba24cb0a4.gif)

### Version

2022.405.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8455856/performance.log)
[network.log](https://github.com/ppy/osu/files/8455858/network.log)
[runtime.log](https://github.com/ppy/osu/files/8455859/runtime.log)
[database.log](https://github.com/ppy/osu/files/8455860/database.log)
[performance-input.log](https://github.com/ppy/osu/files/8455861/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/8455862/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/8455863/performance-update.log)
[performance-draw.log](https://github.com/ppy/osu/files/8455864/performance-draw.log)

**Comment by peppy** [comment] 2022-04-09 02:15
Safe to say this is specific to your linux environment as it works for the majority.

**Comment by bdach** [comment] 2022-04-09 07:55
Duplicate of https://github.com/ppy/osu/issues/14565

**Closed by bdach** 2022-04-09 07:55 UTC
