### ISSUE TITLE
Unhandled error when attempting to access own profile

### ISSUE THREAD

**Issue by blingblang** [ppy/osu#3701] opened 2018-11-10 04:43 UTC
When I start osu!lazer and click on my profile, I get a notification that "an unhandled error has occurred" and my profile comes up empty, except for showing my username/pfp. Viewing other people's profiles still works as expected, however. Brand new to osu and all stats on the website show up as zeroes, though I've played a few games and it's not updated even after ~12-13 hours - could this be related? I verified my account on osu!stable on Windows after some failed attempts on lazer (which seems to be currently expected, so not part of my issue), though since I mainly use Linux I've only been playing on osu!lazer (wine didn't work well). Signing out from the game and back in does not fix it.

This is how it shows up -
![osu_2018-11-10_17-10-51](https://user-images.githubusercontent.com/44915471/48297453-0e2d8580-e50d-11e8-9171-09c12ba228fc.jpg)

Running latest version on Ubuntu 18.04.

[network.log](https://github.com/ppy/osu/files/2568121/network.log)
[runtime.log](https://github.com/ppy/osu/files/2568120/runtime.log)

**Comment by AtomCrafty** [comment] 2018-11-10 15:11
Does this also happen with the latest release or just with your local build?
I can't reproduce it under 2018.1108.0, my own page shows up as expected and I have no idea how to access yours since the user search doesn't seem to be implemented yet.

Regarding the scores not updating: If you only play on lazer, that is to be expected. To my knowledge lazer is not hooked up to the scoring backend as of now.

**Comment by morguldir** [comment] 2018-11-10 16:11
This is because we check if the country is null, but osu-web never sets the country to null

This is what is on this account `"country":{"code":null,"name":null}`

https://github.com/ppy/osu/blob/0833ba26923603aa3459499f50cb2e9257f3b32a/osu.Game/Overlays/Profile/ProfileHeader.cs#L370

**Comment by VPeruS** [comment] 2018-11-10 18:11
Client tries to use null strings from country, additional check if any "code" or "name" == null and assign null to user.Country will do the trick.

**Comment by Joehuu** [comment] 2019-03-26 03:10
Fixed in ppy/osu-web#4085.

**Closed** 2019-03-26 03:10 UTC
Labels: bug, pending review, user profile
