### ISSUE TITLE
Support for animated/segmented skin elements

### ISSUE THREAD

**Issue by KirbyJoe** [ppy/osu#4627] opened 2019-04-16 13:00 UTC
**Describe the missing feature:** 
As mentioned at #3673, the support for animated/segmented skin elements is missing on osu!lazer.

**Comment by KirbyJoe** [comment] 2019-07-12 03:15
It seems fixed on #5202. Does this should be closed?

**Comment by peppy** [comment] 2019-07-12 03:16
Animations aren't implemented. That PR just fixes the hacky first-frame behaviour some skin creators used.

Will leave this open until animations are supported.

**Comment by jorolf** [comment] 2019-07-28 11:58
Has somebody already started working on this or is it still left?

**Comment by peppy** [comment] 2019-07-28 17:04
It was on my list, but go for it.

**Comment by Joehuu** [comment] 2019-08-03 02:54
OP:
> As mentioned at #3673, the support for animated/segmented skin elements is missing on osu!lazer.

Duplicate of #3673. Not sure why this issue was opened if it was literally the same.

**Closed** 2019-08-21 04:15 UTC
Labels: skinning
