### ISSUE TITLE
Crashing after listening to song on beatmap listings

### ISSUE THREAD

**Issue by Layendan** [ppy/osu#11488] opened 2021-01-15 00:35 UTC
**Describe the crash:** 
I have done this multiple times:
1. Load up the game
2. Click Beatmap Listings
3. Search for "love will never" (However, I believe this is more about the song than the search query)
4. Click the play preview button of Harumachi Clover (This  song has consistently worked for me, however, I believe that there may be other songs with this issue)
5. The moment the song is done playing, the app will crash.

**Screenshots or videos showing encountered issue:** 
[Video](https://user-images.githubusercontent.com/46062388/104664944-b14e2c80-568d-11eb-9db9-88026655d222.mp4)

**osu!lazer version:** 
osu 2021.109.0.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5817612/logs.zip)

**Computer Specifications:** 
CPU: RTX 2060 SUPER
GPU: Intel Core i7-9700F
Ram: 16GB

**Comment by EVAST9919** [comment] 2021-01-15 00:36
Duplicate of https://github.com/ppy/osu/issues/11478, will be fixed next release.

**Closed** 2021-01-15 01:38 UTC
