### ISSUE TITLE
More prominent recent hit error bar

### ISSUE THREAD

**Issue by Kaurosu** [ppy/osu#10300] opened 2020-09-30 04:05 UTC
In osu when you are playing, bellow in the screen there is a hit bar with 3 colors (yellow, green and blue), okay when you hit a circle it shows exactly how you tap the note (-50, -100, -300, 300, +300, +100, +50, basically early or late), okay, the problem is that when you are playing is hard to tell how you did in tour last tap because the lanes are all the same size, so you dont really know if you was late or early unless you keep vision on the hit bar when you tap, that is clearly not optimal, so i would propouse to make litte changes to the lanes that appear on that bar when you tap, like the lane that shows the last tap you made was a little higlighted.

Also it would be nice if the recent taps lanes are bigger thant less recent ones, so them becomes tiny when new ones appear so you can clearly see how you did it in your last taps,you willl be aple to tell by the size of the lane what exaclty tap you missed acc and if you was late or early.
Sorrry for the english.

**Comment by smoogipoo** [comment] 2020-09-30 05:19
I don't know about this one. You're able to pay close enough attention to the hit error to notice per-hitobject discrepancies? I really doubt that.

**Comment by Kaurosu** [comment] 2020-09-30 05:31
yeah i see the bar, but i dont memorice where was the las tap i made, okay lets say i got a 100, but i was late or early?, i pause the game to see, but all the lanes see the same so i cant tell.

**Comment by smoogipoo** [comment] 2020-09-30 05:39
As in, even if this were to happen I don't think you'd pay that close enough attention to it. Current lazer already has a little animation when a new hit error bar is displayed. Any more than that falls under https://github.com/ppy/osu/issues/3209 which should be displayed closer to hitobjects.

Closing this as a duplicate of #3209.

**Closed by smoogipoo** 2020-09-30 05:39 UTC
Labels: area:gameplay, low-priority, proposal
