### ISSUE TITLE
On-screen keys for taiko and mania on ios? label:proposal

### ISSUE THREAD

**Issue by milankkk** [ppy/osu#4864] opened 2019-05-27 06:06 UTC
Maybe it would be a good idea to add on-screen keys for taiko an mania instead of only being able to use a physical keyboard.

**Comment by peppy** [comment] 2019-05-27 06:08
Duplicate of https://github.com/ppy/osu/issues/4201.

**Closed by peppy** 2019-05-27 06:08 UTC
