### ISSUE TITLE
Support for changing `IdleColour` and `HoverColour` of link text in `LinkFlowContainer`

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#12825] opened 2021-05-15 12:43 UTC
Currently there is no way to change `IdleColour` and `HoverColour` of link text in `LinkFlowContainer` because the colour itself is from `DrawableLinkCompiler` inside `LinkFlowContainer`.

https://github.com/ppy/osu/blob/50a3775a2281118317b9424017fe7616f2315abf/osu.Game/Graphics/Containers/LinkFlowContainer.cs#L73-L87

Example use case : change the link colour based on `OverlayColourProvider`.

---

This doesn't seem too difficult to implement. I could try to implement it if this is the direction we want.

**Comment by frenzibyte** [comment] 2021-05-15 12:44
Use case is duplicate of https://github.com/ppy/osu/issues/7822.

**Closed by frenzibyte** 2021-05-15 12:44 UTC
