### ISSUE TITLE
Can't click profile after replay

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#9446] opened 2020-07-08 02:02 UTC
**Describe the bug:** 
- Play any replay in global leaderboard (you can fast forward it).
- In result screen, player avatar become guest and not clickable.

**Screenshots or videos showing encountered issue:** 
https://files.catbox.moe/ird2i5.mp4

**osu!lazer version:** 
2020.707.0

I test with local replay and it's fine, maybe only affect replay from online leaderboard.

**Comment by smoogipoo** [comment] 2020-07-08 02:39
Duplicate of https://github.com/ppy/osu/issues/5966 - scores don't store user IDs so we don't know which user to map to.

**Closed by smoogipoo** 2020-07-08 02:39 UTC
