### ISSUE TITLE
Tournament client crash on *Win*

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#6781] opened 2019-11-09 05:33 UTC
**Describe the crash:** 
Client crashed mid *Win* Tab, attached log reveals that this crash might be related to #6715, but the build of lazer that I'm currently using already has [this PR](https://github.com/ppy/osu/pull/6736) applied.

**Screenshots or videos showing encountered issue:** 
[Twitch VOD](https://www.twitch.tv/videos/505847904?t=01h11m15s)

**osu!lazer version:** 
current master

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3826954/runtime.log)
https://puu.sh/ECsFx/2e9fdb94b0.png

**Computer Specifications:** 
i7-4790
GTX 1070Ti
8GB RAM

**Comment by bdach** [comment] 2019-11-09 12:18
Looking at the logs, the API request failures are strange, but seems to be non-fatal. The actual error that the tournament client one dies on is the nasty runtime load problem. There have been some reports of such failures in discord in normal lazer too, but it seems it's not very highly reproducible (if it was, I'd be expecting lots more reports of it). Potentially related to ppy/osu-framework#2943.

**Comment by peppy** [comment] 2019-11-09 12:21
We should definitely look to make that not cause a hard crash (the crash is in `BackgroundStackTraceCollector` which should *only* be running when performance logging is enabled).

@l3lackShark did you enable performance logging intentionally?

**Comment by peppy** [comment] 2019-11-09 12:26
Please turn off `PerformanceLogging` in your framework.ini as a temporary solution.

**Comment by l3lackShark** [comment] 2019-11-10 12:29
@peppy Yes, performance logging was enabled by accident. Turned it off, thanks for clarification. 
@bdach Do you still need Event Viewer logs?

**Comment by bdach** [comment] 2019-11-10 15:02
No, seeing @peppy has the root cause nailed down already I don't think there's any need to provide further details.

**Comment by peppy** [comment] 2019-11-11 01:08
Closing this issue as it is being tracked framework-side.

**Closed by peppy** 2019-11-11 01:08 UTC
Labels: hard crash / startup crash, tournament
