### ISSUE TITLE
Beatmap Tags/Description section are in the wrong place 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3798] opened 2018-12-01 20:22 UTC
**Describe your problem:** Sometimes after you quit a map and then go to the Beatmap Details the Tags/Description section bugs into the rest of the details

**Screenshots or videos showing encountered issue:** 
![osu_2018-12-01_21-17-34](https://user-images.githubusercontent.com/17437302/49332543-18dcb700-f5af-11e8-8591-cba7adf17fab.jpg)

**osu!lazer version:** Latest Master 

**Logs:** N/A

**Comment by peppy** [comment] 2018-12-02 13:35
If possible could you please provide a video of this happening? I can't seem to reproduce it.

**Comment by UselessToucan** [comment] 2018-12-03 07:39
> osu!lazer version: Latest Master

Can you specify the concrete git commit?

**Comment by Lolihunter1337** [comment] 2018-12-03 10:06
I think its resolved now anyways i havent been able to reproduce it. Will re-open if it happens again

**Comment by Lolihunter1337** [comment] 2019-03-09 15:45
so it happend again. but i have *no* idea how to reproduce it as it happens really random. im on the commit  312efbd and were just playing a couple of maps. https://streamable.com/4e8qn

**Comment by Joehuu** [comment] 2019-03-18 05:54
To reproduce:
- go to `Details` if not already
- go to any leaderboard
- resize window
- go back to `Details`

**Comment by peppy** [comment] 2019-03-19 01:22
looks like it may be a fill flow invalidation issue

**Comment by Joehuu** [comment] 2020-02-27 01:28
Will be fixed in https://github.com/ppy/osu-framework/pull/3307.

**Closed** 2020-03-01 01:49 UTC
Labels: area:song-select, framework-fix-required, type:UI
