### ISSUE TITLE
Wrong replay is saved with score in local db.

### ISSUE THREAD

**Issue by MythicalNewt** [ppy/osu#26466] opened 2024-01-10 09:22 UTC
### Type

Other

### Bug description

A different previously played replay is shown depending on when i decide to skip to the end of the replay.

I am using the osu lazer flatpak on Arch linux.

Please take a look at the video to get a better understanding.
Notice how the score in the playercard at the beginning of the video is not the same.
This score changes as you change the place where you skip forward.

### Screenshots or videos

https://github.com/ppy/osu/assets/89124240/c258952f-9637-4a25-83f3-0dce2d555d76

### Version

2023.1231.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13885397/compressed-logs.zip)

**Comment by MythicalNewt** [comment] 2024-01-10 09:24
https://drive.google.com/file/d/1sxdYSBZ5UhsRkSC-FMOtro-sE9rw3DS1/view?usp=sharing

Here is the exported replay if anyone wants to reproduce the bug.

**Comment by bdach** [comment] 2024-01-10 09:30
probably duplicate of one of multiple open issues concerning inaccurate replay playback, most likely https://github.com/ppy/osu/issues/25405

**Closed by bdach** 2024-01-10 09:30 UTC
