### ISSUE TITLE
'ghost' beatmap appears after updating a beatmap

### ISSUE THREAD

**Issue by kinggeert** [ppy/osu#21367] opened 2022-11-21 21:47 UTC
### Type

Cosmetic

### Bug description

After updating a beatmap, the before-updated version of the beatmap will appear in the background of the song select. This does not disappear after entering and exiting a song, but does after going to the main menu and back.

OS: Garuda Linux 2.6.3-2
Kernel: 5.15.43-1-lts arch: x86_64

Hardware:
AMD Ryzen 5 3600
NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 515.43.04

### Screenshots or videos

![osu_2022-11-21_21-55-52](https://user-images.githubusercontent.com/61026729/203161903-37488cfe-9aac-479f-9e14-076d48d94a8a.jpg)

### Version

2022.1117.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10060673/database.log)
[input.log](https://github.com/ppy/osu/files/10060674/input.log)
[network.log](https://github.com/ppy/osu/files/10060675/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/10060676/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10060677/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10060678/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10060679/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10060680/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10060681/runtime.log)

**Comment by frenzibyte** [comment] 2022-11-21 22:21
Duplicate of https://github.com/ppy/osu/issues/21272, and will be fixed in next release. Please search on both open and closed issue threads before reporting next time.

**Closed by frenzibyte** 2022-11-21 22:21 UTC
