### ISSUE TITLE
Spinner Bonus Score is Inconsistent in !lazer Editor

### ISSUE THREAD

**Issue by CYAinideXDMi** [ppy/osu#13770] opened 2021-07-04 14:47 UTC
Describe the bug:
When spinning the spinner in the !lazer editor, I noticed that the game counts the bonus score in reverse, whereas in-game the spinner must be spun fast enough before the bonus score kicks in. (Ex. Score starts from 500 in the middle of the spin then goes down to 100 at the end of the spin.) However, while writing this report, I saved the file so I could change my screen mode from full screen to windowed and when I returned to the editor, I discovered that the counter now starts at 650 and that by moving the soundtrack forward and back fast enough, the cursor would lock up and the counter would start and end at a value greater or lesser than what a spinner of its length would suggest.

Screenshots or videos showing encountered issue: [Click me.](https://drive.google.com/file/d/1w5pcRutSkdsQp7eRPz1d-btOhI8knZd_/view?usp=sharing)

osu!lazer version: 2021.703.0

Logs:
[logs.zip](https://github.com/ppy/osu/files/6760059/logs.zip)

**Comment by frenzibyte** [comment] 2021-07-04 14:48
Duplicate of https://github.com/ppy/osu/issues/10455

**Closed by frenzibyte** 2021-07-04 14:48 UTC
Labels: area:editor, priority:2, ruleset:osu!
