### ISSUE TITLE
Can't type properly on android

### ISSUE THREAD

**Issue by LukaTV939** [ppy/osu#10206] opened 2020-09-22 07:28 UTC
**Describe the bug:** 
Tried to Log In with my username and password but there was no text. Only worked when I used predictive text.
**Screenshots or videos showing encountered issue:** 
https://photos.app.goo.gl/DYdRH45RokFwy4397
I tried to find this beatmap: https://osu.ppy.sh/beatmapsets/163365#osu/398041
**osu!lazer version:** 
2020.910.0
**(I think there's noo need for logs)**

**Comment by LukaTV939** [comment] 2020-09-22 07:29
*no

**Comment by camellirite** [comment] 2020-09-22 07:33
Duplicate of #8264

**Closed** 2020-09-22 07:33 UTC
