### ISSUE TITLE
ios 10 - 10.3.3 support,

### ISSUE THREAD

**Issue by minefreaky** [ppy/osu#4272] opened 2019-02-16 21:55 UTC
I would like to see ios 10 support added because many poeple are still on ios 10-10.3.3 (me included).
I cant download many apps because i am on ios 10.3.3 and i would be devastated if i cant play Osu!

i know its hard to add support for different ios versions but please consider it,

Kind regards,

Minefreaky

**Comment by peppy** [comment] 2019-02-17 03:09
Which device are you using?

**Comment by peppy** [comment] 2019-02-17 03:11
Duplicate of #4239

**Closed by peppy** 2019-02-17 03:11 UTC
Labels: compatibility, iOS

**Comment by minefreaky** [comment] 2019-02-17 10:43
Im using ios 10.3.3 build (14G5053A)
