### ISSUE TITLE
for osu lazar! on ios

### ISSUE THREAD

**Issue by gabeis** [ppy/osu#10056] opened 2020-09-04 01:49 UTC
I think it would be really cool to have a multitouch feature like the one osu! droid has for example https://youtu.be/ss_7WulnQ08 
looking at his left hand if you know what i mean 
a feature like that

-sorry for bad english if my english is bad

**Comment by smoogipoo** [comment] 2020-09-04 01:50
Duplicate of https://github.com/ppy/osu/issues/4201

**Closed by smoogipoo** 2020-09-04 01:50 UTC
