### ISSUE TITLE
No osu!stable installation avaible!

### ISSUE THREAD

**Issue by squeezel1** [ppy/osu#11532] opened 2021-01-18 13:50 UTC
Hey, I know there are already other posts about this problem but it didn't really help me, mostly because i'm pretty new to being on PC so my understanding of it is still a little low and the posts are a bit old by now. So now to my problem, since the latest update lazer can't find the osu!stable installation and I therefore can't import anything.
![image](https://user-images.githubusercontent.com/77625010/104923318-2e361a80-599c-11eb-84ef-e4766e95e5f1.png)
So can you help a PC noob out? I'd really appreciate it!

**Comment by frenzibyte** [comment] 2021-01-18 13:56
Depends on your operating system, if you're on macOS/Linux, make a symlink from `~/.osu`, otherwise, if you're on Windows, it should automatically pinpoint the location of your installation, unless you've customized the beatmap location, which in that case this would be considered a duplicate of https://github.com/ppy/osu/issues/3763.

**Comment by squeezel1** [comment] 2021-01-18 14:04
So, I am using Windows and yes, my beatmap folder is in another location for storage purposes and i changed the Beatmapdirectory accordingly, does it also affect importing skins, scores and collections? Would storing the beatmaps in the osu! folder help with my problem?
I already reinstalled both lazer and stable and didn't mess with the locations of these other then the Beatmap folder.

**Comment by frenzibyte** [comment] 2021-01-18 14:11
I think this also affects skins, scores, and collections as well, storing in the original osu!stable folder should workaround your issue, there'll be a folder selector pop-up eventually where you can select that custom folder (might even attempt it myself).

**Comment by peppy** [comment] 2021-01-18 14:12
custom beatmap folder locations is not yet supported, see https://github.com/ppy/osu/issues/1907

**Closed by peppy** 2021-01-18 14:12 UTC
