### ISSUE TITLE
Leaderboard display error

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#20490] opened 2022-09-26 13:53 UTC
### Type

Game behaviour

### Bug description

use very quick speed to switch mapse
leaderboard will not refresh

### Screenshots or videos

![image](https://user-images.githubusercontent.com/34775378/192293653-736aeca8-42d1-40ce-82c4-b0ce0a519411.png)

after click score(switch to right set)
![image](https://user-images.githubusercontent.com/34775378/192293705-855c4ceb-cb11-4cd3-9e41-2c49d531f3f3.png)

### Version

2022.923.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/9646780/runtime.log)

**Comment by peppy** [comment] 2022-09-27 05:23
This may only apply to the release (which has an extra `Schedule` applied in my hotfix commits to avoid a crash).

Need to confirm whether it's reproducible on `master`.

**Comment by cdwcgt** [comment] 2022-09-27 11:20
![image](https://user-images.githubusercontent.com/34775378/192511963-fdc9d756-6723-4112-a8ee-e64ccb2c7c91.png)
yes, can be reproducible on `master` (sorry I change `OsuGameBase` to let it connect to Production Endpoint)

**Comment by bdach** [comment] 2023-01-23 21:00
Closing as duplicate of https://github.com/ppy/osu/issues/22002 (this issue was first, but is illegible to me, and the other one has more history).

**Closed by bdach** 2023-01-23 21:00 UTC
Labels: area:gameplay
