### ISSUE TITLE
Android crashes related to canceling web requests

### ISSUE THREAD

**Issue by Malavolence** [ppy/osu#6264] opened 2019-09-25 17:58 UTC
typing into the osu!direct search bar slowly nothing happens, typing or deleting letters very fast crashes osu! instantly

osu!lazer version 2019.925.0 on android

please tell me where logs are saved, I can't find them. I tried recording too but the app just gave me a black video.

Snapdragon 430 / Adreno 505

**Comment by ChibiSnoop** [comment] 2019-09-25 18:00
What about logs?

**Comment by Malavolence** [comment] 2019-09-25 18:00
As I already said, I don't know where the logs are saved on android. Please tell me so I can help.

**Comment by ChibiSnoop** [comment] 2019-09-25 18:01
Oh, sorry, it's in __Android/Data/sh.ppy.osulazer/logs__

**Comment by Gabixel** [comment] 2019-09-25 18:02
`Android/data/sh.ppy.osulazer/logs`

**Comment by Malavolence** [comment] 2019-09-25 18:05
https://pastebin.com/gc4BhR2h

**Comment by FayneAldan** [comment] 2019-09-25 18:06
Can easily reproduce. Here's a video:
https://www.youtube.com/watch?v=rmVfC1xl6QU

**Comment by ChibiSnoop** [comment] 2019-09-25 18:09
I see it as a bug, because this problem is actually happened on my Phone

**Comment by bdach** [comment] 2019-09-25 18:19
Upon looking at the stacktrace I have strong doubts this is originating from our code. Googling turned up mono/mono#15462 as a potential resolution we might want to keep an eye out on.

**Comment by Malavolence** [comment] 2019-09-25 18:24
Probably, the last entries in the log hint to the same answer.
I guess case closed, for the osu!dev team at least.

**Comment by bdach** [comment] 2019-09-25 18:24
Let's keep this open purely for tracking purposes, though.

**Comment by byDave251** [comment] 2019-09-25 20:29
I noticed it crashes on entering multiplayer lobby and sometimes while viewing leaderboards. The source is most likely the same.

**Comment by smoogipoo** [comment] 2019-09-26 01:48
There's also the following issue which seems a little more related (both of the mentioned cases are cases where webrequests are cancelled): https://github.com/xamarin/xamarin-android/issues/2159

**Comment by MeguMario** [comment] 2019-09-26 06:41
I just found out that only fastlane build was effected by this, complied the game yourself won't have this issue 

https://streamable.com/e7904

**Comment by peppy** [comment] 2019-09-26 06:43
probably due to different versions of `Xamarin.Android`. Could you mention which you are building against, and confirm you are building as Release.

**Comment by MeguMario** [comment] 2019-09-26 06:52
I just clone & complied this just a two hours ago, with Xamarin.Android SDK 9.4.1.1

**Comment by Jusoko** [comment] 2019-09-26 06:55
android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.) ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) [0x0024b] in <ab2051cb722145028db45fd861770537>:0 
   --- End of inner exception stack trace ---
  at osu.Framework.Platform.GameHost+<>c__DisplayClass92_0.<handleException>b__0 () [0x00000] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at osu.Framework.Threading.ScheduledDelegate.RunTask () [0x00013] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at osu.Framework.Threading.Scheduler.Update () [0x001e5] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at osu.Framework.Threading.GameThread.ProcessFrame () [0x00050] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at osu.Framework.Threading.InputThread.RunUpdate () [0x00000] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at osu.Framework.Platform.GameHost.<Run>b__113_1 (System.Object <p0>, osuTK.FrameEventArgs <p1>) [0x00011] in <8d2e2f2dd28c4353b6b543101f1f4311>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[osuTK.FrameEventArgs].invoke_void_object_TEventArgs(object,osuTK.FrameEventArgs)
  at osuTK.GameViewBase.OnUpdateFrame (osuTK.FrameEventArgs e) [0x00008] in <7484b4753167456b82f11e78c0669d25>:0 
  at osuTK.Android.AndroidGameView.UpdateFrameInternal (osuTK.FrameEventArgs e) [0x00009] in <7484b4753167456b82f11e78c0669d25>:0 
  at osuTK.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x00051] in <7484b4753167456b82f11e78c0669d25>:0 
  at osuTK.Android.AndroidGameView+<>c__DisplayClass58_0.<StartThread>b__2 (System.Object _) [0x00000] in <7484b4753167456b82f11e78c0669d25>:0 
  at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <64fd2296b115462190129b51b48e6951>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <64fd2296b115462190129b51b48e6951>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <64fd2296b115462190129b51b48e6951>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.20(intptr,intptr)
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MobileAuthenticatedStream'.
  at Mono.Net.Security.MobileAuthenticatedStream.StartOperation (Mono.Net.Security.MobileAuthenticatedStream+OperationType type, Mono.Net.Security.AsyncProtocolRequest asyncRequest, System.Threading.CancellationToken cancellationToken) [0x0024b] in <ab2051cb722145028db45fd861770537>:0 <---

	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:208)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)
I got this error when I was browsing osu!direct on android

**Comment by peppy** [comment] 2019-09-26 07:06
If it's a web exception, we can likely switch the backend being used for web requests (if it's anything like iOS).

**Comment by MeguMario** [comment] 2019-09-26 07:20
It didn't explain why the local builds was unaffected though

**Comment by XIDigbyKun** [comment] 2019-10-06 04:23
Hmm i have idea but idunno is work or not
Try remove automatically refersh. Automatically refersh make the android lag

**Comment by Ernst20** [comment] 2019-10-08 13:25
aye it crashes itself after i opened osu!direct/multi lobby. I just think because it was on android so it was different with the osu!lazer on PC

**Comment by bdach** [comment] 2019-10-25 11:18
Renaming and broadening this in scope to cover all cases of crashes on canceling web requests (see #6605 for an example).

**Comment by peppy** [comment] 2019-11-21 06:57
Someone needs to isolate and report this to Xamarin.

**Comment by bdach** [comment] 2019-11-23 14:47
The switch to managed component that aimed to temporarily bypass this (at #6899) seems to have broken online entirely ([see example `network.log`](https://github.com/ppy/osu/files/3882574/network.log), and also #6931). Haven't looked in detail as to why, just confirmed that it is broken on 2019.1122.0.

**Comment by bdach** [comment] 2019-11-23 22:08
After an inordinate amount of time struggling with the debugger and tooling in general, these exceptions seem to not be thrown from anywhere sane - they just pop up from task finalizers and kill everything. Therefore I think this can be only bypassed for now by subscribing to `Host.ExceptionThrown` in `AndroidGameView` and just telling it to shut these up:

```csharp
        private bool handleException(Exception ex)
        {
            // suppress exceptions related to MobileAuthenticatedStream disposal
            // (see: https://github.com/ppy/osu/issues/6264 and linked related mono/xamarin issues)
            // to be removed when upstream fixes come in
            return ex is AggregateException ae
                && ae.InnerException is ObjectDisposedException ode
                && ode.ObjectName == "MobileAuthenticatedStream";
        }
```

Although the above does not entirely silence the exceptions, since they are written to the error log and henceforth show up as notifications. I'd have to modify the `ExceptionThrown` delegate to allow full silencing (probably by making the `bool` into an `enum`).

In perhaps slightly better news, after checking merged PRs in mono I think mono/mono#17393 is the fix we're looking for. Unfortunately though it looks like it's queued up in their `2019-10` branch, which means it's probably two releases away (currently VS 2019 preview's xamarin version works with `2019-08` or mono 6.6, so I assume `2019-10` is going to be 6.8 and quite a ways away).

**Comment by peppy** [comment] 2019-11-25 02:03
Thanks for the in-depth investigation! Are you able to try a [nightly](https://www.mono-project.com/download/nightly/) mono build to see if it resolves the issue? If so, I can probably switch to a build with the fix on our deploy server as a temporary resolution.

I'm also not against a local fix, even if it doesn't suppress the notifications (as it is better than a hard crash for sure).

**Comment by bdach** [comment] 2019-11-25 19:42
Installing mono nightly seems to have no effect on the version compiled by Xamarin. After turning up msbuild log output to noisiest I can't see it even trying to run/access the mono executables; closest thing is `Mono.Android` which I think is Xamarin-provided. I might be doing things incorrectly, however.

**Comment by peppy** [comment] 2020-02-12 04:30
Has been locally fixed (and is being tracked framework-side).

**Closed by peppy** 2020-02-12 04:30 UTC
Labels: high priority, platform:android
