### ISSUE TITLE
Note expand with number.

### ISSUE THREAD

**Issue by KoleckOLP** [ppy/osu#8878] opened 2020-04-27 17:22 UTC
**Describe the bug:** 
For some reason playing lazer felt weird to me and I have finally found why.
When you click a note the note expands, in stable the number of the note disapears in lazer it stays and expand.

I would like to be able to toggle this off. I'd like if the number could disapear like it does in stable.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/TQLLDakOdDY (unlisted video)

**osu!lazer version:** 
2020.421.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4541119/logs.zip)

**Comment by Joehuu** [comment] 2020-04-27 17:34
Duplicate of https://github.com/ppy/osu/issues/5537

**Closed by Joehuu** 2020-04-27 17:34 UTC
