### ISSUE TITLE
Pausing game lead to weird behaviour while having a bad internet connection

### ISSUE THREAD

**Issue by meirilia** [ppy/osu#22349] opened 2023-01-22 13:06 UTC
### Type

Game behaviour

### Bug description

The bug happen quite frequently if i have bad internet connection, but with recent update the "pause bg music" thingy (i forgot what its called) get overlayed with current playing song, which didnt happen before. 

### Screenshots or videos

https://0x0.st/oh0T.mkv

### Version

2023.121.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10474469/database.log)
[input.log](https://github.com/ppy/osu/files/10474470/input.log)
[network.log](https://github.com/ppy/osu/files/10474471/network.log)
[performance.log](https://github.com/ppy/osu/files/10474472/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10474473/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10474474/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10474475/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10474476/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10474477/runtime.log)

**Comment by bdach** [comment] 2023-01-22 15:03
has nothing to do with internet connection, duplicate of https://github.com/ppy/osu/issues/22173, will be fixed next release

**Closed by bdach** 2023-01-22 15:03 UTC
