### ISSUE TITLE
Local Result Screen 

### ISSUE THREAD

**Issue by TravisDavis-ops** [ppy/osu#12876] opened 2021-05-20 00:48 UTC
**Describe the new feature:** 
At the moment we only have the choice of seeing the best clears on the result screen. I so days this screen inspires me to keep going other days it just make me want to quit. It would be great to have the choice to only see the results of your runs

**Comment by Joehuu** [comment] 2021-05-20 00:52
Duplicate of https://github.com/ppy/osu/issues/9201

**Closed by Joehuu** 2021-05-20 00:52 UTC
