### ISSUE TITLE
Sorting on star rating not working

### ISSUE THREAD

**Issue by vruss** [ppy/osu#7251] opened 2019-12-17 18:37 UTC
**Describe the bug:** 
When clicking the green difficulty button for sorting, nothing appears to happen. 
The beatmaps decouples in Stable, allowing for difficulty sorting, this does not happen on here. 

**Screenshots or videos showing encountered issue:** 
[Imgur album with descriptions](https://imgur.com/a/NzGSusS)

**osu!lazer version:** 
2019.1216.0

**Logs:**

**Comment by EVAST9919** [comment] 2019-12-17 18:39
Duplicate of https://github.com/ppy/osu/issues/2536

**Comment by bdach** [comment] 2019-12-17 18:40
This is a duplicate / consequence of lack of implementation of #2547; closing.

**Closed by bdach** 2019-12-17 18:40 UTC
