### ISSUE TITLE
osu! lazer beatmap search doesn't have all the beatmap that would normally find on the website

### ISSUE THREAD

**Issue by Thomas-Harit** [ppy/osu#23363] opened 2023-05-02 01:34 UTC
### Type

Game behaviour

### Bug description

When searching beatmaps within the included navigator, a lot of beatmaps are missing from the same research done on the website.

### Version

2023.419.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11369030/network.log)
[performance.log](https://github.com/ppy/osu/files/11369031/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11369032/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11369033/updater.log)
[database.log](https://github.com/ppy/osu/files/11369034/database.log)
[input.log](https://github.com/ppy/osu/files/11369035/input.log)

**Comment by Joehuu** [comment] 2023-05-02 03:19
Duplicate of https://github.com/ppy/osu/issues/22009. Lazer by default has the featured artist filter set.

**Closed by Joehuu** 2023-05-02 03:19 UTC
