### ISSUE TITLE
Highest rank is wrong

### ISSUE THREAD

**Issue by Wildthing0** [ppy/osu#27575] opened 2024-03-11 20:38 UTC
### Type

Cosmetic

### Bug description

Went to check peak rank and it was off by 200k
Android btw

### Screenshots or videos

![Screenshot_20240312_073152](https://github.com/ppy/osu/assets/90672169/321ace67-2a50-4332-a165-bc42f1d2cf49)

### Version

2024.312.0

### Logs

Could not access the data folder

**Comment by Gabixel** [comment] 2024-03-11 21:29
I think this is a duplicate of https://github.com/ppy/osu-web/issues/10937

**Comment by Joehuu** [comment] 2024-03-11 21:45
Yes, but leaving this open for visibility.

**Comment by snalgae** [comment] 2024-03-12 09:58
i also have this problem

**Comment by frenzibyte** [comment] 2024-03-12 10:00
> i also have this problem

Thank you but the underlying issue is known, there's no need for +1 comments like yours.

**Comment by Wildthing0** [comment] 2024-03-14 03:25
> I think this is a duplicate of [ppy/osu-web#10937](https://github.com/ppy/osu-web/issues/10937)

yeah but thats for osu web and this if for osu lazer

**Comment by frenzibyte** [comment] 2024-03-14 03:31
osu! sources the highest rank from web API, so no, they lead to the same thing, but this is still open for a different reason (visibility).

**Comment by peppy** [comment] 2024-03-17 16:41
https://github.com/ppy/osu-web/issues/10937

**Closed by peppy** 2024-03-17 16:41 UTC
Labels: type:online, area:overlay-user-profile, external component
