### ISSUE TITLE
Accel/Decel slider causes big lag spike

### ISSUE THREAD

**Issue by vart1on** [ppy/osu#26093] opened 2023-12-24 01:24 UTC
### Type

Performance

### Bug description

On the insane diff of https://osu.ppy.sh/beatmapsets/1746664#osu/3598398 at about 2:20 an accelerating slider causes lazer 2023.1224.0 to have a massive lag spike.

I recorded the issue here : https://www.youtube.com/watch?v=yZu-D1Y2ZCI (slider at 2:30)

I hope this issue is repeatable and can be fixed relatively quickly and painlessly.

### Version

2023.1224.0

### Logs

[osu!logs.zip](https://github.com/ppy/osu/files/13760598/osu.logs.zip)

**Comment by bdach** [comment] 2023-12-24 14:26
Duplicate of https://github.com/ppy/osu/discussions/23500

**Closed by bdach** 2023-12-24 14:26 UTC
