### ISSUE TITLE
Not able to install new update

### ISSUE THREAD

**Issue by Elumati** [ppy/osu#6926] opened 2019-11-23 12:29 UTC
**Describe the bug:** 
I dont know why this is happening I downloaded the new version of laser and it keeps on saying app not installed 
**Screenshots or videos showing encountered issue:** 
![Screenshot_20191123-122129_Package installer](https://user-images.githubusercontent.com/58108260/69478664-d37f4e00-0dec-11ea-8441-b5a68734aeda.jpg)

**osu!lazer version:** 
2019.1122.0
**Logs:**

**Comment by huoyaoyuan** [comment] 2019-11-23 12:30
Duplicate of #6921 .

**Closed** 2019-11-23 12:33 UTC
