### ISSUE TITLE
Discrepancy between Doubletime and Nightcore star ratings when hidden is selected on certain maps

### ISSUE THREAD

**Issue by rtiosfu** [ppy/osu#11694] opened 2021-02-06 19:27 UTC
For some maps, the star rating preview between doubletime and nightcore are different despite the speed being the same. 

On [Glaive - Astrid - from the heart](https://osu.ppy.sh/beatmapsets/1275747#osu/2650657), the star rating is displayed as 6.12* when doubletime is selected and 7.15* when nightcore is selected combined with hidden. The star rating is the same when hidden is deselected. 

Another map I've found this behaviour on is [Orangestar - Asu no Yozora Shoukaihan - iyasine_sk's Extra](https://osu.ppy.sh/beatmapsets/219728#osu/563946)
where the star ratings are 7.43* and 8.81* for doubletime and nightcore respectively.

[Here is a video of the behaviour.](https://youtu.be/on7_-fgASdA)

I've only looked at a few maps, so I don't know how many are affected.

**osu!lazer version:** 2021.205.1

**Comment by bdach** [comment] 2021-02-06 19:39
I think I can reproduce. Did you change the speed setting of either DT or NC?

**Comment by rtiosfu** [comment] 2021-02-06 20:59
Yes, actually. I played a few other maps with 1.25-1.30x selected under dt.

**Comment by Joehuu** [comment] 2021-02-06 21:02
Duplicate of https://github.com/ppy/osu/issues/9669

**Closed by Joehuu** 2021-02-06 21:02 UTC
Labels: area:mods
