### ISSUE TITLE
Searching in SongSelect and pressing Enter too fast crashes the game

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1719] opened 2017-12-21 16:28 UTC
If you enter your search term in SongSelect and immediately press ENTER before the animation is done the game crashes:
![qq](https://user-images.githubusercontent.com/27222621/34264775-3bab340a-e674-11e7-9d84-7483d2c23009.png)
![qq](https://user-images.githubusercontent.com/27222621/34264708-0d64aaea-e674-11e7-96b0-bfec90b4c354.png)

**Comment by FreezyLemon** [comment] 2017-12-25 21:57
This is not _really_ caused by the search process, but rather by the selected beatmap changing _after_ the Start method has been called. (since the search takes a second it can change the beatmap after starting the player loader).
The `Bindable<WorkingBeatmap> Beatmap` is disabled as soon as the map starts to load and when the search completes -> the carousel selection changes -> it tries to change `Beatmap.Value` -> the exception is thrown.

The easiest way to fix this would be checking for `Beatmap.Disabled` and only changing the value if it isn't, though this might prevent other issues from appearing correctly. Would be better to check for some kind of `IsStarting` or `IsLoading` but that doesnt exist as far as i'm aware.

**Comment by Aergwyn** [comment] 2017-12-25 21:58
It's crashing generally if you press enter without a valid beatmap selected.

**Comment by FreezyLemon** [comment] 2017-12-25 22:11
If no map is selected, (at least for me) it shows the `Beatmap couldn't be loaded` notification. That might not be ideal yet, but it doesn't crash.

If you try to open the "dummy map" and then do the same thing (change beatmap while it's loading), it gives the same error.
Same when you open a normal map and then filter the songselect to no maps again. It then tries to set the bindable to the dummy map and crashes aswell.

**Comment by FreezyLemon** [comment] 2017-12-25 22:24
[The fix](https://github.com/FreezyLemon/osu/blob/fix-songselect-search-crash/osu.Game/Screens/Select/SongSelect.cs#L253).

Probably not perfect, as mentioned. It works, but might hide other issues if the Bindable gets disabled.

**Comment by peppy** [comment] 2017-12-28 12:46
Closing in favour of #1757

**Closed by peppy** 2017-12-28 12:46 UTC
Labels: bug, high priority, songselect
