### ISSUE TITLE
Cursor can leave the screen boundaries in fullscreen mode

### ISSUE THREAD

**Issue by bazded** [ppy/osu#10948] opened 2020-11-23 18:23 UTC
yeah. cursor can leave screen boundaries and by moving it to side you choose you want you can get rid off background

![osu_2020-11-23_19-07-36](https://user-images.githubusercontent.com/74927508/99999884-189fdc80-2dc1-11eb-8989-dbe8b9992614.jpg)

laser ver: 2020.11.21

resolution: 1366x768

**Comment by Game4all** [comment] 2020-11-23 18:33
Duplicate of #10465. As an aside, you should search existing issues before opening another one, especially when it has the exact same name as the mentionned one ...

**Closed** 2020-11-23 18:34 UTC
