### ISSUE TITLE
Difficulty Adjust replay bug

### ISSUE THREAD

**Issue by GamerPaprika4785** [ppy/osu#11794] opened 2021-02-16 07:00 UTC
**Describe the bug:** 
I just playing some map with Difficulty Adjust on and i check the replay, the replay Circle size and the difficulty adjust Circle size is not matching in the replay. The replay use the original CS size from the map and not using the difficulty adjust CS

And i dont know why i get "Texture could not be loaded via STB;" error message after the gameplay

**Screenshots or videos showing encountered issue:** 

Gameplay video:
https://www.youtube.com/watch?v=hXB2JvqJYZs

**osu!lazer version:** 
2021.212.0 Stable

**Logs:**
[network.log](https://github.com/ppy/osu/files/5986673/network.log)
[performance.log](https://github.com/ppy/osu/files/5986674/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5986676/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5986677/updater.log)
[database.log](https://github.com/ppy/osu/files/5986678/database.log)

**Comment by smoogipoo** [comment] 2021-02-16 07:12
Duplicate of https://github.com/ppy/osu/issues/8569. As for the texture load issue - it's probably something with your skin, so make a separate issue with that.

**Closed by smoogipoo** 2021-02-16 07:12 UTC
