### ISSUE TITLE
Approach circle is too small

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#6503] opened 2019-10-14 13:55 UTC
Describe the bug:
Approach circle seems small in some skins. (Selyu v2.3)
skin download: https://drive.google.com/drive/folders/1e1B99Rp2_6mxEnSf1T5gc-qp6VSC6tBA

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=nluzUxH_tmc&feature=youtu.be

![스크린샷(66)](https://user-images.githubusercontent.com/51792037/66756791-b5f9c300-eed5-11e9-8fb0-03d704534531.png)
![스크린샷(67)](https://user-images.githubusercontent.com/51792037/66756805-babe7700-eed5-11e9-9e58-77dda6400543.png)

osu!lazer version: 
2019.1011.0

**Logs:** 
I will upload it if necessary.

**Comment by LittleEndu** [comment] 2019-10-14 14:34
Duplicate of #2358 ?

**Comment by bdach** [comment] 2019-10-14 14:47
Closing as duplicate.

**Closed by bdach** 2019-10-14 14:47 UTC
