### ISSUE TITLE
Speed multipliers from legacy maps display too much precision

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#12573] opened 2021-04-25 15:43 UTC
Some speed multipliers are converted incorrectly from stable. Noticed it on [this map](https://osu.ppy.sh/beatmapsets/1362166) where inherited timingpoints using `1.4` multipliers are changed to `1.4000000000000001` in lazer. I'm guessing that this is some kind of rounding/off-by-one error.

![](https://pennek.s-ul.eu/HU2sbZmv.png)
**osu!lazer version:** 2021.424.0

**Comment by bdach** [comment] 2021-04-25 15:48
This is partially known and is due to this legacy-preserving code path:

https://github.com/ppy/osu/blob/7654df94f6f37b8382be7dfcb4f674e03bd35427/osu.Game/Beatmaps/Formats/LegacyDecoder.cs#L182-L185

The precision is turned all the way down to avoid changing gameplay characteristics in legacy maps that may have been hand-edited. Not sure what the way forward here is, most likely simply some rounding of the displayed value on the UI side.

**Comment by peppy** [comment] 2021-04-26 03:28
Wondering if we could get away with something like `Precision.AlmostEquals(multiplier, Math.Round(multiplier, 2))` (not sure if rounding to 1 or 2 d.p.).. would need to check which outlier cases are requiring the extra precision, but I think the cases are not ones which are close to being round number in the first place.

**Comment by smoogipoo** [comment] 2021-04-26 05:26
I'm not sure what you mean, when would you use the `Precision.AlmostEquals()` line? The issue is that 1.4 is unrepresentable in base-2 regardless of how you round it, so you're still going to get that. This sounds more like something that should be fixed at a UI level? You can round at the UI level and at the storage level, but once you read that into a `double` it's always going to be a slightly different value.

**Comment by peppy** [comment] 2021-04-26 05:29
I guess we need to change how the precision specification is done on UI controls then, since it's currently hard coupled to the bindable precision. How would you see the "set to default" light working for such cases? Or the case where the user "drags" to the current location - would it update the value to the non-precise version at that point? Gets a bit weird once we start doing this, so not sure if it's the best idea..

**Comment by smoogipoo** [comment] 2021-04-26 07:56
Set to default could use `Precision.AlmostEquals()`, probably with the default precision. But the rounding is only done for display/sliderbar notches. Yes, I've suggested not hard coupling the bindables several times before.

Dunno. Bottom line that you have to keep in mind is that _no matter what you do_, the `double` is going to have the wrong value.

**Closed** 2022-01-08 15:58 UTC
Labels: area:editor, type:UI, priority:2
