### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by fhzzzs** [ppy/osu#3996] opened 2019-01-04 00:52 UTC
**Describe your problem:** Lag when I try to drag the progress bar in autoplay, and also lag when i load the maps. the cpu usetage rate will drop somehow.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 20181228
**Logs:**

**Comment by peppy** [comment] 2019-01-04 00:53
Duplicate of #2347.

**Closed by peppy** 2019-01-04 00:53 UTC
