### ISSUE TITLE
Using a tablet input in borderless mode may result in multiple cursors

### ISSUE THREAD

**Issue by sr229** [ppy/osu#12175] opened 2021-03-25 02:50 UTC
**Describe the bug:** 

Using a tablet input in non-exclusive full screen will result in two cursors. Another thing to note is that the "blinking" cursor would sometimes even register a hit.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/14976516/112411294-9ec03580-8d57-11eb-81e0-08ee20817e07.mp4

**osu!lazer version:**  2021.323.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6201706/runtime.log)
[database.log](https://github.com/ppy/osu/files/6201707/database.log)
[network.log](https://github.com/ppy/osu/files/6201708/network.log)
[performance.log](https://github.com/ppy/osu/files/6201709/performance.log)

**Comment by peppy** [comment] 2021-03-25 02:55
Duplicate of #

**Comment by smoogipoo** [comment] 2021-03-25 02:55
Likely Wacom drivers also active at the same time? Which would make this a duplicate of https://github.com/ppy/osu/issues/12171. Also mentioned in the changelog notes (https://osu.ppy.sh/home/changelog/lazer/2021.320.0) that this scenario will eventually be detected.

**Comment by sr229** [comment] 2021-03-25 02:56
> Likely Wacom drivers also active at the same time? Which would make this a duplicate of #12171. Also mentioned in the changelog notes (https://osu.ppy.sh/home/changelog/lazer/2021.320.0) that this scenario will eventually be detected.

This is a XP-Pen G420 for the test so I assume it also affects XP-PEN.

**Closed** 2021-03-25 02:55 UTC

**Comment by smoogipoo** [comment] 2021-03-25 02:58
It will affect all tablets, yes.
