### ISSUE TITLE
Hitting the escape key during fade-out causes the result screen to not show up.

### ISSUE THREAD

**Issue by Vanilla7chan** [ppy/osu#7353] opened 2019-12-26 01:16 UTC
**Describe the bug:** Basically, on stable, if you finish a map and hit "esc" after finishing the map it makes it "skip" to the results screen. When done on lazer it does nothing. You don't get to see the results screen, the score doesn't save, all you see is empty black screen.

**Screenshots or videos showing encountered issue:** https://streamable.com/2m01z

**osu!lazer version:** 2019.1225.0

**Logs:**

**Comment by bdach** [comment] 2019-12-26 08:44
Duplicate of #6848.

**Closed by bdach** 2019-12-26 08:44 UTC
