### ISSUE TITLE
Song select star rating search and difficulty sort does not account for mods, 

### ISSUE THREAD

**Issue by Fuutur3** [ppy/osu#31185] opened 2024-12-18 16:23 UTC
### Type

Game behaviour

### Bug description

While searching for a 5.5 star map with doubletime enabled I instead see high 7 stars to low 8 stars, this effectively also makes difficulty sort useless, as shown in screenshots an 8* is showing in a lower difficulty sort than a 7.7* as well as them showing with a 5.5* search

### Screenshots or videos

![image](https://github.com/user-attachments/assets/7f71bd28-a319-4e0e-bb70-7bdb3a77bf76)
![image](https://github.com/user-attachments/assets/0cbd062e-d99b-4df7-a958-f69e3c1d4f60)

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18185962/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-12-18 17:38
Duplicate of https://github.com/ppy/osu/issues/12628 and https://github.com/ppy/osu/issues/19947. Try searching next time!

**Closed by frenzibyte** 2024-12-18 17:38 UTC
