### ISSUE TITLE
Strange slider tail

### ISSUE THREAD

**Issue by plankp** [ppy/osu#4049] opened 2019-01-12 17:37 UTC
**Describe your problem:** The tail of the (first) slider has strange thing attached to it. (see attached screenshot) Beatmap is [fhana - RHAPSODY OF BLUE SKY ([Kamiya]) [Pata-Mon's Insane]](https://osu.ppy.sh/beatmapsets/586841#osu/1249647)

**Screenshots or videos showing encountered issue:** 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7527421/51076412-1b2e3880-1666-11e9-9d5e-e6202df68a23.png">

**osu!lazer version:** 2018.111.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2752319/database.log)
[debug.log](https://github.com/ppy/osu/files/2752320/debug.log)
[network.log](https://github.com/ppy/osu/files/2752321/network.log)
[performance.log](https://github.com/ppy/osu/files/2752322/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2752323/runtime.log)

**Comment by Joehuu** [comment] 2019-01-12 17:56
Duplicate of #4036. Will be fixed on next build, I guess.

**Closed** 2019-01-12 18:32 UTC
