### ISSUE TITLE
Gameplay start freeze on certain beatmaps

### ISSUE THREAD

**Issue by Semro** [ppy/osu#24985] opened 2023-10-01 19:07 UTC
### Type

Game behaviour

### Bug description

There is a gameplay freeze before the first object on the map, it's more noticeable when using wireless headphones.
Reproduces on the maps below:
[polygon](https://osu.ppy.sh/beatmapsets/422136#osu/1027496)
[Formless Canvas](https://osu.ppy.sh/beatmapsets/1727694#osu/3667381)
[Turkish March - Owata \(^o^)/](https://osu.ppy.sh/beatmapsets/399096#osu/1004492)
[World's End, Girl's Rondo(Asterisk DnB Remix) ](https://osu.ppy.sh/beatmapsets/331499#osu/734339)
[LEZHAT' + SOSAT'](https://osu.ppy.sh/beatmapsets/777949#osu/1634119)

### Screenshots or videos

Recorded when using wireless headphones: https://github.com/ppy/osu/assets/3332159/9ff61a3a-c081-4d3d-bb94-24029953bbd0

### Version

2023.924.1

### Logs

[database.log](https://github.com/ppy/osu/files/12777901/database.log)
[input.log](https://github.com/ppy/osu/files/12777902/input.log)
[network.log](https://github.com/ppy/osu/files/12777903/network.log)
[performance.log](https://github.com/ppy/osu/files/12777904/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12777905/runtime.log)

**Comment by bdach** [comment] 2023-10-02 06:50
Duplicate of #22488

**Closed by bdach** 2023-10-02 06:50 UTC
