### ISSUE TITLE
Selecting "Loved" in osu!direct breaks the game in several ways

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu#2452] opened 2018-04-24 20:43 UTC
- Open osu!lazer
- Login to an account with supporter tag
- Have osu!direct load in the default "Ranked & Approved" results.
- Switch to "Loved" in the dropdown box:
![image of dropdown box before crash](https://i.imgur.com/ZSx03eV.jpg)
Error: System.Net.WebException

**Comment by peppy** [comment] 2018-04-24 23:30
This really depends on what the exception was. If you are running in debug, your IDE may be set to break on handled exceptions (which you don't want).

**Comment by Aergwyn** [comment] 2018-06-04 16:17
What generally seems to happen is that [this line](https://github.com/ppy/osu/blob/69e75bfa09c574911927799c6b759b3892ba5bd3/osu.Game/Overlays/DirectOverlay.cs#L289) prevents refetching.

In detail:
So as long as the tab(?) isn't `Search` everything will behave fine. You can change tabs (I should call them search presets) and categories(?) and see fresh results.
Once you touch the filter(?) it jumps to `Search` and any refetch will be prevented until you enter some text. Deleting text also works fine but only once. Any change while the box is empty will, as mentioned, cause an early return.

**Comment by Joehuu** [comment] 2019-10-28 23:22
Can't reproduce, and it should happen with any category. Maybe fixed in https://github.com/ppy/osu/pull/4456?

The above comment was resolved in https://github.com/ppy/osu/pull/4324.

**Closed by Joehuu** 2019-10-28 23:22 UTC
Labels: online / API
