### ISSUE TITLE
Key counter's counting timing

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#4690] opened 2019-04-30 14:18 UTC
**Describe the missing feature:** 
osu!stable's key counter stops counting when beat map is intro time or break time.
but osu!lazer's key counter doesn't stop.

video: https://streamable.com/hfwrt

**Comment by Morilli** [comment] 2019-04-30 14:43
Duplicate of #2707?

**Closed** 2019-04-30 14:59 UTC
