### ISSUE TITLE
Can't move the installation folder.

### ISSUE THREAD

**Issue by tigwersparkz** [ppy/osu#11244] opened 2020-12-21 13:42 UTC
I tried moving the folder location from one disk to another but it gives me this error every time, I've tried restarting my pc, running with admin rights and using another disk to import it to. Nothings worked, i'm not exactly a tech person so i'm sorry if the solution is obvious.
It just constantly says that there was an error, and that it can't access the file where the game is CURRENTLY installed, not where i'm trying to install it onto, because it's being used by another process which is obvious because the game is open from where it's currently installed. Looked at logs, all that i saw was:

"MigrationSelectScreen" then to "MigrationRunScreen"

2020-12-21 13:26:19 [verbose]: [?????] Beginning import...
2020-12-21 13:26:19 [verbose]: [a1556] Validating online IDs for 1 beatmaps...
2020-12-21 13:26:19 [verbose]: [a1556] Performing online lookups...
2020-12-21 13:26:19 [verbose]: [a1556] Found existing beatmap for cYsmix - triangles (peppy) (ID 1) – skipping import.
2020-12-21 13:26:19 [verbose]: [a1556] Dereferencing files for incomplete import.
(Not sure if this here is related.)

Screenshots:
![ulZS15](https://user-images.githubusercontent.com/70112021/102781989-7a3b7280-4390-11eb-9680-a3fb08e742a3.jpg)
or 
https://snipboard.io/ulZS15.jpg

I've made previous post not too long ago but i don't know how to reopen it and so i made this one, sorry for inconvenience.

Thanks in advance. Again.

**Comment by bdach** [comment] 2020-12-21 13:43
Duplicate of #9746

**Closed by bdach** 2020-12-21 13:43 UTC
