### ISSUE TITLE
Difficulty Adjust doesn't change cursor size

### ISSUE THREAD

**Issue by Avijojo** [ppy/osu#7826] opened 2020-02-13 19:29 UTC
**Describe the bug:** 
Turn on "Adjust gameplay cursor size based on current beatmap" in the settings panel, then go to a map and adjust its circle size, the cursor size won't change.
**Screenshots or videos showing encountered issue:** 
 https://youtu.be/2N5gafv5Cyo
**osu!lazer version:** 
2020.208.0
**Logs:**

**Comment by Joehuu** [comment] 2020-02-13 21:45
Duplicate of https://github.com/ppy/osu/issues/6342

**Closed by Joehuu** 2020-02-13 21:45 UTC
Labels: area:mods, ruleset:osu!
