### ISSUE TITLE
Multiple beatmap authors not displayed on sets by Multiple Creators

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu#1374] opened 2017-10-14 05:16 UTC
Lazer lists that diffs from all modes are mapped by Deif
Stable lists each set creator individually (MMzz & Gamu)
https://puu.sh/xXHwe/e532769b1d.png
https://puu.sh/xXHft/5153a12964.png

edit: In case puush links go down, download renatus and open them on lazer & cutting edge, should not have used puush

**Comment by peppy** [comment] 2017-11-21 06:10
This is related to Metadata currently only being stored on a BeatmapSet level.

**Comment by Aergwyn** [comment] 2017-11-22 20:26
This would be fixed by simply removing one line of code. But there is a comment that I don't quite understand. So it was intended? [LINK](https://github.com/Aergwyn/osu/blob/37c0772537ec141bbe55fc6a2e2da545509ecd9d/osu.Game/Beatmaps/BeatmapManager.cs#L519)

**Comment by peppy** [comment] 2017-12-11 07:58
Resolved by #1567

**Closed by peppy** 2017-12-11 07:58 UTC
Labels: bug
