### ISSUE TITLE
Voice not working

### ISSUE THREAD

**Issue by yuto0214w** [ppy/osu#7413] opened 2020-01-01 03:32 UTC
**Bug:**
osu!lazer doesn't make a voice (If you don't understand what I mean, please see the video).
(Should I open this to feature request?)

**Videos showing encountered issue:** 
osu!stable: https://youtu.be/sC3oiMW70ao
osu!lazer: https://youtu.be/EojtFO79nnU

**osu!lazer version:** 
2019.1227.0

**Comment by swoolcock** [comment] 2020-01-01 03:47
Sample playback in storyboards not yet implemented, duplicate of #6981

**Closed by swoolcock** 2020-01-01 03:47 UTC
