### ISSUE TITLE
"No osu!stable installation available!"

### ISSUE THREAD

**Issue by JayFlowGT** [ppy/osu#9486] opened 2020-07-09 22:41 UTC
![image](https://user-images.githubusercontent.com/40595555/87097094-ab8e0f00-c244-11ea-89b0-6049d1080807.png)
So I have seen this issue apparently being fixed and all issues closed around mid to late 2019 yet keeps persisting on my installation. Although I have tried deleting and reinstalling lazer a couple of times before and after that time period in an attempt to fix the issue.

I have not moved the osu!lazer installation ("\AppData\Local\osulazer"). The stable version is located under "C:\osu!" having moved the "Songs" folder to "D:\Songs" linked through the personal config file.

All versions of both installations through out the issue persisting have always been up to date. OS is Windows 10.

**Logs:**
[database.log](https://github.com/ppy/osu/files/4899820/database.log)
[performance.log](https://github.com/ppy/osu/files/4899821/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4899822/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4899823/updater.log)

**Comment by bdach** [comment] 2020-07-09 22:47
Sounds like a duplicate of #3763. Importing from stable after having customised beatmap directory will not work for now.

We can probably look into having the user point manually towards the installation as we now have a file dialog component available but it's not the highest priority for now.

**Closed by bdach** 2020-07-09 22:47 UTC
