### ISSUE TITLE
Skinnable animation performance regression on first map play

### ISSUE THREAD

**Issue by treier57lol** [ppy/osu#8581] opened 2020-04-02 19:34 UTC
**Describe the bug:** 
When any other skin other than the default osu!lazer skin is selected, every beatmap played will have random lag and stuttering when skin elements are present. Unskinned things (like spinners) don't have any lag. Once you switch skins mid-map, the lag is gone. Default skin works fine. This issue doesn't occur on versions prior to 2020.403.0.

**Screenshots or videos showing encountered issue:** 
[Video of the bug](https://drive.google.com/open?id=1tEtGuwDecSh46SfTJCMzaXbIfluGLzHy) (Using [MangoHud](https://github.com/flightlessmango/MangoHud) to show frametime)

**osu!lazer version:** 
2020.403.0 (AppImage) on Manjaro Linux 19.0.2

**Logs:**
[database.log](https://github.com/ppy/osu/files/4423202/database.log)
[network.log](https://github.com/ppy/osu/files/4423203/network.log)
[performance.log](https://github.com/ppy/osu/files/4423204/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4423205/runtime.log)

**Comment by bdach** [comment] 2020-04-02 19:49
Can reproduce. `SkinnableTextureAnimation` appears to be taking quite a bit of update frame time:

![osu_2020-04-02_21-46-15](https://user-images.githubusercontent.com/20418176/78295098-d709ab00-752b-11ea-9ab4-f3dd128f30bf.jpg)

It does go away after switching skins too. Don't know much more else than that at this point.

**Comment by MCSulphate** [comment] 2020-04-02 23:00
I think this is the issue I'm having, so just to add to this that for me it seems to be mainly caused by sliders, especially the repeating sliders - gimmick slider maps drop to around 5-6fps before making it impossible to hit them.

Additionally, this problem only exists with multithreading enabled for me. I was going to open this as an issue so I made a video for it, it may or may not help at all. A notification popped up at 1:53 saying "DrawableSliderHead took 16.04ms to load (and blocked the update thread)".

Video link: https://www.youtube.com/watch?v=Rn2L0Uxq3po

**Comment by bdach** [comment] 2020-04-02 23:02
Yes, animated sliders will trigger this.

**Comment by peppy** [comment] 2020-04-03 01:42
Looking into this one.

**Comment by peppy** [comment] 2020-04-03 03:22
For those experiencing this, a temporary solution is to change frame limiter to unlimited or use default skin.

The cause is `Animation` processing the game-wide clock a second time. I'm working on a framework fix for this (and better protection against this happening).

**Closed** 2020-04-03 11:07 UTC
Labels: area:skinning, type:performance
