### ISSUE TITLE
The volume of the slider body is the same as the slider head.

### ISSUE THREAD

**Issue by shiumano** [ppy/osu#28921] opened 2024-07-18 15:40 UTC
### Type

Cosmetic

### Bug description

Slider body volume is the same as the slider head.
Uncomfortable to gameplay.
It can also be checked in the editor

Anyway, I found it and reported it. I think it is a common problem as it was confirmed in several maps.

### Screenshots or videos

Previous Release
![Screenshot_20240719-002657](https://github.com/user-attachments/assets/457252e4-f406-4173-955d-58627ab281f9)

2024.718.0
![Screenshot_20240719-002756](https://github.com/user-attachments/assets/c5f22c9e-f8dc-4538-b32b-f19bab3166ac)

Beatmap: https://osu.ppy.sh/beatmapsets/1767982#osu/3618986

### Version

2024.718.0

### Logs

[logs.zip](https://github.com/user-attachments/files/16285566/logs.zip)

**Comment by shiumano** [comment] 2024-07-19 04:01
Hmmm, that was a poor explanation.
I can see this problem in the editor, but it also occurs when the map is started without the editor open after import.
I thought it might be due to area:beatmap-parsing, but if it can be fixed by changing the editor, this would be the right solution.

**Comment by smoogipoo** [comment] 2024-07-19 04:18
I'm still not sure what the issue is here, is it that the slider body is 100% opaque?

**Comment by bdach** [comment] 2024-07-19 04:27
I believe user is complaining at changes to beatmap parsing made to accommodate saving sample volume of sliders but am yet to cross check stable.

**Comment by bdach** [comment] 2024-07-19 07:49
Upon investigation I am... not convinced that this is a real issue.

The screenshots appear to point at this slider:

```
118,209,210820,6,0,P|223:234|326:267,1,216.666666666666,8|0,3:2|2:0,2:0:0:0:
```

There are two "green lines" that are relevant here:

```
210820,-38.4615384615385,4,2,1,80,0,0
211097,-38.4615384615385,4,2,1,5,0,0
```

One is at the start of the object, one is just before its ending. As far as I can tell stable _respects this_ and only uses volume 5 _for the tail_.

On an audible comparison I basically cannot tell the difference (other than apparent different baseline levels of loudness):

https://github.com/user-attachments/assets/fbd9a408-d8f3-4f76-9f7b-09a0e0066196

That though could be ascribed to the custom sample set that the beatmap uses, so here's an audible comparison with custom sample banks off:

https://github.com/user-attachments/assets/edd5fc0b-7ea5-4537-b657-772e5d12ad51

Note that in stable `sliderslide` *is* audible, and so it is in lazer. When I _manually_ set `sliderslide` volume to 5 the slider sounds completely different.

So unless I'm misunderstanding what the issue is, I believe that the one example given is not an issue. @shiumano please advise and/or provide other examples if you believe this is still a problem.

**Comment by peppy** [comment] 2024-07-19 08:22
I think this looks correct. As far as my recollection serves me, the volume of the body should be taken from the start time of the slider, not just-before-the-end.

**Comment by shiumano** [comment] 2024-07-19 14:12
I like “originally buggy, but now aligned with Stable.” I also checked and confirmed that it is in fact that behavior with Stable. Sorry for my lack of knowledge.

I started with lazer (yes, I created my account on a phone), so all my standards are Lazer circa 2022. Sorry once again.

**Comment by bdach** [comment] 2024-07-19 14:58
Closing as intended then I guess.

**Closed** 2024-07-19 14:58 UTC
Labels: missing details, area:beatmap-parsing, audio
