### ISSUE TITLE
client.db corrupted with foreign key constraint failure

### ISSUE THREAD

**Issue by ghost** [ppy/osu#10480] opened 2020-10-10 20:42 UTC
**Describe the crash:**
The game fails to launch with error
`Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'`
[error.txt](https://github.com/ppy/osu/files/5360044/error.txt)
[client.db.zip](https://github.com/ppy/osu/files/5360041/client.db.zip)

This happened after playing on 2020.1005.0 then switching back to 2020.925.0
Is there any way to recover?

**osu!lazer version:** 
2020.925.0 and 2020.1005.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5360024/logs.zip)

**Computer Specifications:** 
CPU: AMD Ryzen 9 3900XT
GPU: NVIDIA GeForce RTX 2070
RAM: 64 GB
OS: Ubuntu 20.04.1 LTS x86_64

**Comment by AuracleTech** [comment] 2020-10-10 22:37
After updating, I imported again maps from stable because I added a lot since I played lazer, and I have lots of maps like this now.
Could this be related?

![Corrupted](https://user-images.githubusercontent.com/40531871/95666428-818c0780-0b27-11eb-9afd-8a5d167a08d2.jpg)

**Comment by peppy** [comment] 2020-10-11 01:16
you probably had an import running while quitting the game. if you're not attached to our database, the current solution to this is deleting it and re-importing.

**Comment by szmarczak** [comment] 2021-05-14 16:45
I'm able to reproduce the issue every time. I'll record a video.

**Comment by szmarczak** [comment] 2021-05-14 17:11
@peppy @frenzibyte https://www.youtube.com/watch?v=BpsQkV8zioM

Basically the steps are:

1. Import maps.
2. Edit a map and complete it.
3. Import maps again.
4. Crash.

**Comment by bdach** [comment] 2021-05-14 17:35
There is no need to provide more details.

**Comment by peppy** [comment] 2021-06-23 08:01
I'm going to look into fixing this, but just to document what is going on here:

- A map exists loaded in lazer
- At least one score is associated with the map
- The set is changed, to the point where a reimport will need to delete the old copy and import a new copy
- The existing set is determined by matching `OnlineBeatmapSetID` (see https://github.com/ppy/osu/blob/17fa2426d47cd6801863871d98d48a758f21f824/osu.Game/Beatmaps/BeatmapManager.cs#L179-L181), which triggers an immediate delete and purge
- Due to the purge occurring from within the import context, the event which causes the related scores to be deleted (see https://github.com/ppy/osu/blob/28f4c56cd6531b64f6631076fa911d62a2867b43/osu.Game/OsuGameBase.cs#L270-L274) is delayed due to the `delayEvents` flow.
- The scores aren't deleted and there is a foreign key constraint hit, since the beatmap they are related to is gone.

I have a fix which resolves this for the import flow in a pretty sane way (avoiding using the purge logic at all), but there's a remaining fail case which can cause startup failures:

https://github.com/ppy/osu/blob/8f5b28d26452211a913f7e2a2b67aece638367a0/osu.Game/Database/ArchiveModelManager.cs#L109

If purge logic is run from here, we hit the same issue, not because of `delayEvents`, but because the score deletion event is not hooked up yet. And even if it was, the scores would not be purged in time (just marked for deletion instead). This would leave the database in a sane state after one extra restart, but before that can happen the game would crash during startup logic due to the foreign key constraint.

I think the path forward here is:

- I will apply my local fix for the import flow, but I'm not sure that's the only way a database can get into this bad state. The one linked in this issue, for instance, somehow got in a state of startup crashing too (likely via a different flow, since the import failure will abort/crash before the database is left in a bad state).
- I think we should probably just turn off foreign key constraints for these cases and let the database have dangling/detached objects. It beats dealing with these startup failures. As we are probably rewriting the whole database backend I don't think it's worth spending too much time on these individual issues and would rather to apply fire and just ensure issues with FK/deletion don't trigger a user error. They have negligible/zero chance of actually causing a follow-up problem, as old IDs will not be reused in autoincrement.

@smoogipoo thoughts on this (mainly the second last bullet point)?

**Comment by peppy** [comment] 2021-06-23 08:36
As an example of how the database could still get into the startup-failing state: If the game were to crash between the beatmap import completing and the score deletion callback event firing and deleting the relevant scores, we would be in this same state. Really, the scores need to be removed/marked in the same transaction as the beatmap. Out of scope for the current EF core logic, I think.

**Comment by smoogipoo** [comment] 2021-06-23 12:35
So long as dangling objects don't result in other unexpected failures, such as somehow an object being removed and then the user restoring an object which depended on it. I don't think it could with any structures we have currently, but the case I'm thinking is something like if `BeatmapMetadata` got removed but the `BeatmapSetInfo` wasn't removed and gets restored by the user.

Otherwise, dangling objects sound fine.

**Comment by frenzibyte** [comment] 2021-07-05 10:10
Closing as now foreign key constraints have been disabled, as per https://github.com/ppy/osu/pull/13780.

**Closed by frenzibyte** 2021-07-05 10:10 UTC
Labels: area:database
