### ISSUE TITLE
Primary mouse button setting for osu!lazer takes precendence over that of the device.

### ISSUE THREAD

**Issue by Super-Lovers** [ppy/osu#8921] opened 2020-05-01 12:09 UTC
I use the left hand and mouse for playing osu. The old client has no problem with me switching the primary mouse button, but when I play in osu!lazer, my primary mouse button is not the same as the one I have on my computer. It is as if its hardcoded to use the specific key on the mouse or maybe it is not implemented as a feature yet. I could not find any options to switch the primary key in the client either.

Screenshots or videos showing encountered issue: none 
osu!lazer version: 2020.429.0

**Comment by bdach** [comment] 2020-05-01 12:11
To make sure I understand correctly: is the problem such that you switched the primary mouse button to be the right one in system settings, but the game still considers the left one the primary?

**Comment by Super-Lovers** [comment] 2020-05-01 12:14
You understand correctly and I use raw input yes

**Comment by bdach** [comment] 2020-05-01 12:15
This issue is then a duplicate of #5628 - closing as such.

It's possible that a future switch to SDL will handle this cleanly for us.

**Closed by bdach** 2020-05-01 12:15 UTC
