### ISSUE TITLE
Unusual Screen Size error on Intro Screen

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3474] opened 2018-09-22 18:48 UTC
This started to happen since a few minutes ago when trying to open Lazer.

https://pastebin.com/RnefCTQw

**Comment by Chronody** [comment] 2018-09-22 19:09
https://pastebin.com/T1m6RXsa Same error on every start.

Seems related to some issue with resolution. 
In the log the error reads something about `({Width=1906, Height=1026})` which was the resolution set in the `framework.ini` for "SizeFullscreen". 
Changing that value in the ini-file to `1920x1080` fixed the crash entirely.

**Comment by Gabixel** [comment] 2018-09-22 19:11
Basically, (just found) the issue happens when I disconnect the 1920x1080 monitor/TV (in my case), keeping that resolution when closing Lazer, and reopening Lazer on a lower resolution screen (in my case: the portable one)

**Comment by smoogipoo** [comment] 2018-10-01 06:42
Possible @AtomCrafty

**Comment by AtomCrafty** [comment] 2018-10-01 10:58
Will look into it

**Comment by AtomCrafty** [comment] 2018-10-01 15:44
> `({Width=1906, Height=1026})`

I wonder how those values ended up in your config in the first place...
Not exactly a common display resolution.

Also I don't understand why the game didn't crash for @Gabixel even though it does for several other people (including me if I edit the config).

**Comment by SavvyDev06** [comment] 2018-10-14 09:15
I found out that this problem also happens to me only when my WiFi is turned off...
Perhaps Osu! crashes if it can't connect to the server?

**Comment by plankp** [comment] 2018-10-14 10:52
Does it give you a similar (or same) output in network.log like #3572 ?

**Comment by AtomCrafty** [comment] 2018-10-14 12:02
@SavvyDev06 did you mean to post that under a different issue?

**Comment by SavvyDev06** [comment] 2018-10-17 18:01
> @SavvyDev06 did you mean to post that under a different issue?

I had created a separate issue about this, issue #3480, which Dean said it looked like a duplicate of this issue...

**Comment by SavvyDev06** [comment] 2018-10-17 18:02
> @SavvyDev06 Does it give you a similar (or same) output in network.log like #3572 ?

I'll check, and let you know ASAP!

**Comment by smoogipoo** [comment] 2018-11-20 01:43
This was fixed via the framework PR.

**Closed by smoogipoo** 2018-11-20 01:43 UTC
Labels: critical, pending review, regression
