### ISSUE TITLE
Storyboard causes memory leak and eventual crash

### ISSUE THREAD

**Issue by ChenMerami** [ppy/osu#25416] opened 2023-11-12 23:01 UTC
### Type

Crash to desktop

### Bug description

Storyboard on this beatmap https://osu.ppy.sh/beatmapsets/1108479 causes map to load indefinitely while memory usage goes up. Disabling storyboard solves the issue

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/81158712/7728b603-576f-401b-8500-2af4d7d5c622)

### Version

2023.1026.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13329394/network.log)
[performance.log](https://github.com/ppy/osu/files/13329395/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13329396/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13329397/updater.log)
[database.log](https://github.com/ppy/osu/files/13329398/database.log)
[input.log](https://github.com/ppy/osu/files/13329399/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13329400/legacy-ipc.log)

**Comment by bdach** [comment] 2023-11-12 23:31
Either duplicate of #23258, or generally known issue as storyboards are generally not very optimal yet.

**Closed by bdach** 2023-11-12 23:31 UTC
