### ISSUE TITLE
Mapper's Name hyperlink throws gder profile instead of host

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#24937] opened 2023-09-26 16:38 UTC
### Type

Game behaviour

### Bug description

If i'm clicking on mapped by (host name) while i have guest difficulty selected it throws me to gders profile

i'm pretty sure it's planned to be so, but shouldn't this label change to mapped by (mapper)

### Screenshots or videos

https://github.com/ppy/osu/assets/42616718/2987e7b2-b6f4-41a1-a144-00f61b8fc213

### Version

2023.924-1

### Logs

no need in logs

**Comment by Joehuu** [comment] 2023-09-26 18:33
Duplicate of https://github.com/ppy/osu/issues/12965

**Closed by Joehuu** 2023-09-26 18:33 UTC
