### ISSUE TITLE
Stuck on Loading ChangeLogOverlay on Arch Linux ARM

### ISSUE THREAD

**Issue by jedi2light** [ppy/osu#10175] opened 2020-09-16 22:13 UTC
Just stucks on Loading ChangeLogOverlay when trying to launch it on my PineTab running Arch Linux ARM with the latest updates installed.

**osu!lazer version:** 2020.229.1

**Logs:**
```
2020-09-16 21:47:36 [verbose]: ----------------------------------------------------------
2020-09-16 21:47:36 [verbose]: runtime Log for stoian (LogLevel: Debug)
2020-09-16 21:47:36 [verbose]: osu 0.0.0.0
2020-09-16 21:47:36 [verbose]: Running on Unix 5.7.19.4, 4 cores
2020-09-16 21:47:36 [verbose]: ----------------------------------------------------------
2020-09-16 21:47:36 [verbose]: GL Initialized
2020-09-16 21:47:36 [verbose]: GL Version:                 2.1 Mesa 20.3.0-devel (git-c7719b8cfc)
2020-09-16 21:47:36 [verbose]: GL Renderer:                Mali400
2020-09-16 21:47:36 [verbose]: GL Shader Language version: 1.20
2020-09-16 21:47:36 [verbose]: GL Vendor:                  lima
2020-09-16 21:47:36 [verbose]: GL Extensions:              GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_pixel_buffer_object GL_ARB_texture_rectangle GL_EXT_pixel_buffer_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_gpu_program_parameters GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_half_float_vertex GL_ARB_map_buffer_range GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_shader_texture_lod GL_EXT_provoking_vertex GL_NV_copy_image GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_EXT_direct_state_access GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_EXT_framebuffer_multisample_blit_scaled GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_shading_language_include GL_ARB_get_texture_sub_image GL_KHR_context_flush_control GL_ARB_parallel_shader_compile GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_EGL_sync
2020-09-16 21:47:39 [debug]: Loading Font OpenSans...
2020-09-16 21:47:39 [debug]: Loading Font FontAwesome-Solid...
2020-09-16 21:47:39 [debug]: Loaded Font FontAwesome-Solid!
2020-09-16 21:47:39 [debug]: Loading Font FontAwesome-Regular...
2020-09-16 21:47:39 [debug]: Loaded Font FontAwesome-Regular!
2020-09-16 21:47:39 [debug]: Loading Font FontAwesome-Brands...
2020-09-16 21:47:39 [debug]: Loaded Font FontAwesome-Brands!
2020-09-16 21:47:39 [debug]: Loading Font osuFont...
2020-09-16 21:47:39 [debug]: Loaded Font osuFont!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-Medium...
2020-09-16 21:47:39 [debug]: Loaded Font OpenSans!
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-Medium!
2020-09-16 21:47:39 [debug]: Loading Font OpenSans-Bold...
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-MediumItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-MediumItalic!
2020-09-16 21:47:39 [debug]: Loading Font Noto-Basic...
2020-09-16 21:47:39 [debug]: Loaded Font OpenSans-Bold!
2020-09-16 21:47:39 [debug]: Loading Font OpenSans-Italic...
2020-09-16 21:47:39 [debug]: Loaded Font Noto-Basic!
2020-09-16 21:47:39 [debug]: Loading Font Noto-Hangul...
2020-09-16 21:47:39 [debug]: Loaded Font OpenSans-Italic!
2020-09-16 21:47:39 [debug]: Loading Font OpenSans-BoldItalic...
2020-09-16 21:47:39 [debug]: Loaded Font OpenSans-BoldItalic!
2020-09-16 21:47:39 [debug]: Loaded Font Noto-Hangul!
2020-09-16 21:47:39 [debug]: Loading Font Noto-CJK-Basic...
2020-09-16 21:47:39 [verbose]: BASS Initialized
2020-09-16 21:47:39 [verbose]: BASS Version:               2.4.15.0
2020-09-16 21:47:39 [verbose]: BASS FX Version:            2.4.12.1
2020-09-16 21:47:39 [verbose]: Device:                     Default
2020-09-16 21:47:39 [verbose]: Drive:                      default
2020-09-16 21:47:39 [debug]: Loaded Font Noto-CJK-Basic!
2020-09-16 21:47:39 [debug]: Loading Font Noto-CJK-Compatibility...
2020-09-16 21:47:39 [debug]: Loaded Font Noto-CJK-Compatibility!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-Regular...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-Regular!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-RegularItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-RegularItalic!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-SemiBold...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-SemiBold!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-SemiBoldItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-SemiBoldItalic!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-Bold...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-Bold!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-BoldItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-BoldItalic!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-Light...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-Light!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-LightItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-LightItalic!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-Black...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-Black!
2020-09-16 21:47:39 [debug]: Loading Font Exo2.0-BlackItalic...
2020-09-16 21:47:39 [debug]: Loaded Font Exo2.0-BlackItalic!
2020-09-16 21:47:39 [debug]: Loading Font Venera...
2020-09-16 21:47:39 [debug]: Loaded Font Venera!
2020-09-16 21:47:39 [debug]: Loading Font Venera-Light...
2020-09-16 21:47:39 [debug]: Loaded Font Venera-Light!
2020-09-16 21:47:39 [debug]: Loading Font Venera-Medium...
2020-09-16 21:47:39 [debug]: Loaded Font Venera-Medium!
2020-09-16 21:47:59 [error]: Texture could not be loaded via STB; falling back to ImageSharp.
2020-09-16 21:47:59 [error]: System.DllNotFoundException: Unable to load shared library 'stbi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libstbi: cannot open shared object file: No such file or directory
2020-09-16 21:47:59 [error]: at StbiSharp.Stbi.LoadFromMemory(Byte* data, Int64 len, Int32& width, Int32& height, Int32& numChannels, Int32 desiredNumChannels)
2020-09-16 21:47:59 [error]: at StbiSharp.Stbi.LoadFromMemory(ReadOnlySpan`1 data, Int32 desiredNumChannels)
2020-09-16 21:47:59 [error]: at StbiSharp.Stbi.LoadFromMemory(MemoryStream data, Int32 desiredNumChannels)
2020-09-16 21:47:59 [error]: at osu.Framework.Graphics.Textures.TextureUpload.LoadFromStream[TPixel](Stream stream)
2020-09-16 21:48:03 [debug]: Loading OsuLogo...
2020-09-16 21:48:04 [debug]: Loaded OsuLogo!
2020-09-16 21:48:04 [debug]: Loading Toolbar...
2020-09-16 21:48:04 [verbose]: Screen changed → Loader
2020-09-16 21:48:06 [debug]: Loaded Toolbar!
2020-09-16 21:48:06 [debug]: Loading VolumeOverlay...
2020-09-16 21:48:06 [debug]: Loaded VolumeOverlay!
2020-09-16 21:48:06 [debug]: Loading OnScreenDisplay...
2020-09-16 21:48:06 [debug]: Loaded OnScreenDisplay!
2020-09-16 21:48:06 [debug]: Loading MusicController...
2020-09-16 21:48:08 [debug]: Loaded MusicController!
2020-09-16 21:48:08 [debug]: Loading NotificationOverlay...
2020-09-16 21:48:08 [verbose]: Screen changed → IntroTriangles
2020-09-16 21:48:08 [debug]: Loaded NotificationOverlay!
2020-09-16 21:48:08 [debug]: Loading ScreenshotManager...
2020-09-16 21:48:09 [debug]: Loaded ScreenshotManager!
2020-09-16 21:48:09 [debug]: Loading DirectOverlay...
2020-09-16 21:48:12 [verbose]: decoupled ruleset transferred ("" -> "osu!"
2020-09-16 21:48:13 [debug]: Loaded DirectOverlay!
2020-09-16 21:48:13 [debug]: Loading SocialOverlay...
```

```
2020-09-16 21:47:59 [verbose]: ----------------------------------------------------------
2020-09-16 21:47:59 [verbose]: performance Log for stoian (LogLevel: Debug)
2020-09-16 21:47:59 [verbose]: osu 0.0.0.0
2020-09-16 21:47:59 [verbose]: Running on Unix 5.7.19.4, 4 cores
2020-09-16 21:47:59 [verbose]: ----------------------------------------------------------
2020-09-16 21:47:59 [verbose]: TextureAtlas initialised (1024x1024)
2020-09-16 21:48:00 [verbose]: TextureAtlas initialised (1024x1024)
2020-09-16 21:48:03 [verbose]: Texture requested (1920x8) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2020-09-16 21:48:04 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
2020-09-16 21:48:12 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
```

```
2020-09-16 21:22:58 [verbose]: ----------------------------------------------------------
2020-09-16 21:22:58 [verbose]: database Log for stoian (LogLevel: Debug)
2020-09-16 21:22:58 [verbose]: osu 0.0.0.0
2020-09-16 21:22:58 [verbose]: Running on Unix 5.7.19.4, 4 cores
2020-09-16 21:22:58 [verbose]: ----------------------------------------------------------
2020-09-16 21:22:58 [verbose]: [?????] Beginning import...
2020-09-16 21:23:08 [verbose]: [a1556] Validating online IDs...
2020-09-16 21:23:16 [verbose]: [a1556] Import successfully completed!
```

**Comment by bdach** [comment] 2020-09-16 22:47
Both OpenGL and GLSL versions reported seem quite low on the attached log excerpts. Please confirm that the device can not go any higher - if not, then there's not much we can do at this point. Support for alternatives like vulkan is planned but not in the immediate future.

As an aside, 2020.229.1 is a quite ancient release at this point.

**Comment by jai-x** [comment] 2020-09-16 22:59
The Mali 400 GPU does indeed only support [up to OpenGL ES 2.0](https://developer.arm.com/ip-products/graphics-and-multimedia/mali-gpus/mali-400-gpu). (released in 2008!).

Additionally, I'm not sure if all the required nativelibs are packaged for AArch64

**Comment by bdach** [comment] 2020-09-16 23:00
Thanks. I guess I'll just mark this down as a duplicate of #7166 + #9673, then.

**Closed by bdach** 2020-09-16 23:00 UTC

**Comment by jedi2light** [comment] 2020-09-16 23:29
Thank you all.
