### ISSUE TITLE
osu!lazer crashes at startup

### ISSUE THREAD

**Issue by Naranzhia** [ppy/osu#1743] opened 2017-12-25 05:23 UTC
Every time I try to open osu!lazer, it stopped working even this time. This is all event log i've got.

> Log Name:      Application
Source:        .NET Runtime
Date:          12/25/2017 1:15:35 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Admin-PC
Description:
Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.ES30.GL.GenFramebuffer()
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.Initialize(Boolean, OpenTK.Graphics.ES30.All)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.bindFrameBuffer(osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer, OpenTK.Vector2)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.drawChildren(System.Action`1<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>, OpenTK.Vector2)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.Draw(System.Action`1<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>)
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(System.Action`1<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>)
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

 Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-12-25T05:15:35.000000000Z" />
    <EventRecordID>7088</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Admin-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.ES30.GL.GenFramebuffer()
   at osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer.Initialize(Boolean, OpenTK.Graphics.ES30.All)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.bindFrameBuffer(osu.Framework.Graphics.OpenGL.Buffers.FrameBuffer, OpenTK.Vector2)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.drawChildren(System.Action`1&lt;osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D&gt;, OpenTK.Vector2)
   at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.Draw(System.Action`1&lt;osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D&gt;)
   at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(System.Action`1&lt;osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D&gt;)
   at osu.Framework.Platform.GameHost.DrawFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by peppy** [comment] 2018-02-28 00:25
Duplicate of #1680

**Closed by peppy** 2018-02-28 00:25 UTC
Labels: bug, framework fix required
