### ISSUE TITLE
Replay takeover (training?)

### ISSUE THREAD

**Issue by Pythonimous** [ppy/osu#8442] opened 2020-03-25 18:42 UTC
**Describe the new feature:** 
Since replays are now a thing (and skipping towards certain points of a replay / autoplay have been a thing for a long time), how about an unranked option for players to take over from a certain point, to e.g. try out / master a tricky segment while not having to play the map from the beginning?

If I remember correctly, the standard player workaround is to create a separate difficulty and cut all the notes before, but, while it does the job, it's sometimes kind of cumbersome, so maybe this could help.

**Comment by Joehuu** [comment] 2020-03-25 18:47
Duplicate of https://github.com/ppy/osu/issues/4175

**Closed by Joehuu** 2020-03-25 18:47 UTC
