### ISSUE TITLE
lazer not opening

### ISSUE THREAD

**Issue by naemwear** [ppy/osu#14604] opened 2021-09-01 12:06 UTC
So I decided to install osu!lazer but when I did nothing opened so I searched in the search bar and found osu!(lazer) but when I opened it nothing happened I tried opening the regular osu! and nothing happened again I closed the regular one opened the event viewer tried to open osu!lazer once again and I got these error messages:

![Screenshot_517](https://user-images.githubusercontent.com/84918419/131668281-1d1c0589-1d5a-4c24-8cb6-2407edc44601.png)
![Screenshot_518](https://user-images.githubusercontent.com/84918419/131668286-4f82c384-639f-4a0f-93fa-e9865f4c5d82.png)

**Comment by frenzibyte** [comment] 2021-09-01 12:12
Duplicate of https://github.com/ppy/osu/issues/13634.

**Closed by frenzibyte** 2021-09-01 12:12 UTC
