### ISSUE TITLE
osu! lazer 2020.1009.0 iOS crashes when you exit Beatmap Editor

### ISSUE THREAD

**Issue by KweenAriel** [ppy/osu#10464] opened 2020-10-09 18:55 UTC
On iOS Lazer if you're editing a beatmap and click "File" -> "Exit" -> "Forget All Changes" the app always crashes. If you choose "Save My Masterpiece", sometimes the app straight up crashes immediately and other times you can successfully exit back to the osu! main screen but the next time you try to go back into the editor the app will still crash.

Video of both issues:
https://youtu.be/0Dkf5FOkcII

osu! lazer 2020.1009.0

Logs Folder: 
[logs.zip](https://github.com/ppy/osu/files/5357007/logs.zip)

Apple iPhone 7 Plus

**Comment by bdach** [comment] 2020-10-09 18:58
On iOS logs can be obtained by connecting your device to your desktop and [copying the `logs` directory from the app's own document storage using iTunes.](https://support.apple.com/en-us/HT201301#copy-to-computer)

**Comment by KweenAriel** [comment] 2020-10-09 19:02
> On iOS logs can be obtained by connecting your device to your desktop and [copying the `logs` directory from the app's own document storage using iTunes.](https://support.apple.com/en-us/HT201301#copy-to-computer)

Alrighty I posted the logs, they're in the original comment :)

**Comment by bdach** [comment] 2020-10-09 19:08
Turns out this actually seems to be a duplicate of #10435. Closing as such, but this issue might warrant looking into quite soon after all if just a save can do this...

**Closed by bdach** 2020-10-09 19:08 UTC
Labels: area:editor, missing details, type:crash
