### ISSUE TITLE
Not Opening

### ISSUE THREAD

**Issue by ajr0709** [ppy/osu#2463] opened 2018-04-26 20:34 UTC
I Downloaded install.exe for osu!lazer, But then I noticed something pretty strange... When I Open osu!lazer, It just closed. I Hope you can fix this come I am eager to try this out.

**Comment by AlFasGD** [comment] 2018-04-27 05:03
You need to provide all the information that is logged so that the issue is examined. This includes:
- Log files (basically files with .log extension)
- System information
Also it would be great if you provided links to the files after uploading them anywhere.

**Comment by Chisk** [comment] 2018-04-27 20:41
I have same problem, I run Windows 10 Home Edition. 
![image](https://user-images.githubusercontent.com/26637455/39384150-cc5c3fb6-4a39-11e8-8a4f-73e2e5efe023.png) It doesn't create any logs when it crashes with this, I've checked.

**Comment by Chisk** [comment] 2018-04-27 20:55
okay used 342 or somewhere near there to get to osu folder for logs and let it update. I got one log, Nothing special in it but maybe it'll help?
4/27/2018 8:53:05 PM: Focus contention triggered by NotificationOverlay (308,0) 320x768.
4/27/2018 8:53:39 PM: Focus contention triggered by NotificationOverlay (283,0) 320x768.

**Comment by Deldo123** [comment] 2018-04-28 08:55
My Osu!Lazer Wont Start I Just See Black Screen and later is not responding
![wt](https://user-images.githubusercontent.com/38328805/39394459-9a68b0cc-4ad2-11e8-9009-fc177256b846.png)

**Comment by peppy** [comment] 2018-05-02 11:12
Please try reinstalling using the [latest release](https://github.com/ppy/osu/releases) and report back.

**Comment by KSTBAD** [comment] 2018-05-04 16:06
I have installed the latest release, however, I am still having the same issue as deldo123 where starting osu lazer leads to a black screen before a popup saying 'osu! has stopped working'.

**Comment by babouaya** [comment] 2018-05-06 15:03
The newest release doesn't start either. Here is what I found in the journal : 
```
Application : osu!.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : osu.Framework.Allocation.RecursiveLoadException
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à osu.Framework.Allocation.DependencyContainer+<>c__DisplayClass6_1.<register>b__5(System.Object)
   à System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   à osu.Framework.Allocation.DependencyContainer+<>c__DisplayClass6_0.<register>b__1(osu.Framework.Allocation.DependencyContainer, System.Object)
   à osu.Framework.Allocation.DependencyContainer.Inject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, Boolean, Boolean)
   à osu.Framework.Graphics.Drawable.Load(osu.Framework.Timing.IFrameBasedClock, osu.Framework.Allocation.IReadOnlyDependencyContainer)
   à osu.Framework.Platform.GameHost.bootstrapSceneGraph(osu.Framework.Game)
   à osu.Framework.Platform.GameHost.Run(osu.Framework.Game)
   à osu.Desktop.Program.Main(System.String[])
```

**Comment by AlFasGD** [comment] 2018-05-06 15:06
It looks like your .NET Framework version is way too low. Consider updating to 4.7.1 at least in order to open osu!lazer.

**Comment by babouaya** [comment] 2018-05-06 15:11
I *have* 4.7.1, actually if I try to install the latest 4.7.1 It says it's already installed. 
.

**Comment by Lolihunter1337** [comment] 2018-05-06 16:36
@babouaya have you tried to completly re-install .NET Framework?

**Comment by ShowBR** [comment] 2018-05-27 19:41
same issue here

**Comment by peppy** [comment] 2018-05-28 03:45
The last exception in this thread has nothing to do with .NET version. It's hard to say what's causing it, but it's not related to the OP, which has most definitely been fixed so I'm going to close this issue.

**Closed by peppy** 2018-05-28 03:45 UTC
Labels: bug, startup crash
