### ISSUE TITLE
Korean input bugs in the chat.

### ISSUE THREAD

**Issue by libneko** [ppy/osu#3230] opened 2018-08-14 17:48 UTC
![1](https://user-images.githubusercontent.com/22436695/44108405-456a0b44-a035-11e8-9c31-20717be1dcfa.png)

It caused on windows 10 (64 bits).

**Comment by Morilli** [comment] 2018-08-14 17:50
Looks like a duplicate of #2779

**Comment by libneko** [comment] 2018-08-14 17:56
It seems not to be related to it. other characters shown without problems...

**Comment by ZapTech43** [comment] 2018-08-15 02:42
Unicode Problems?

**Comment by Alex4386** [comment] 2018-08-15 02:50
Looks like IME Problem for me.

@libneko
Which build of OS are you using?
And also, Which IME are you using? 
Microsoft's one? or Custom one?

**Comment by Alex4386** [comment] 2018-08-21 10:16
![image](https://user-images.githubusercontent.com/27724108/44396001-8d4a9780-a576-11e8-8f5d-0d1be81ddf7c.png)
Successfully Reproduced on latest build v.2018.820.0

Technical Details:
Microsoft Windows 10 1803 Build 17134.1

**Comment by Alex4386** [comment] 2018-08-27 07:26
I guess this is the framework issue.
Could you look at this please? @peppy 

This means, every single language input uses ime is not functioning properly (e.g. Japanese, Chinese, Korean (a.k.a. CJK))

**Comment by Alex4386** [comment] 2018-08-27 07:39
![image](https://user-images.githubusercontent.com/27724108/44646961-b015f980-aa17-11e8-9d93-faef7eee06d0.png)
Expected Results were occurred on Japanese Input.

**Comment by Alex4386** [comment] 2018-08-27 07:47
Just found out that this issue is caused due to Handling Input via `Window.KeyPress`
check opentk/opentk#437 for more details.

**Comment by Alex4386** [comment] 2019-07-21 23:17
in macOS 10.14.5 Mojave, the FocusedTextBox actually inputs the actual character depending on keypress. (Still not handled by IME perfectly)  
while KeyDownEvent Actually recognizes the actual key of the keystroke.  
(Please refer to the image below for more detail)  
  
![image](https://user-images.githubusercontent.com/27724108/61598417-bda02780-ac58-11e9-8c58-c9a87073bc4e.png)

**Comment by huoyaoyuan** [comment] 2019-11-19 14:24
Should be the same with ppy/osu-framework#2945 .

**Comment by lime9360** [comment] 2020-04-01 15:56
![캡osu처](https://user-images.githubusercontent.com/63007754/78158742-9868e780-747c-11ea-85c4-e215110b8954.PNG)

it does not work on 32bit nighter

**Comment by peppy** [comment] 2020-04-08 10:07
Closing as duplicate of https://github.com/ppy/osu/issues/2954.

**Closed by peppy** 2020-04-08 10:07 UTC
Labels: framework-fix-required, type:input
