### ISSUE TITLE
Allow the mod "Difficulty adjust" to change the AR and OD to values up to 11

### ISSUE THREAD

**Issue by RadekMojzis** [ppy/osu#11506] opened 2021-01-15 21:37 UTC
**Describe the new feature:** 
A lot of the times i want to practice on something like a 5* map but with AR > 10 (For double time practice)
as is i have to create a new map that is 1.5* slower and use DT. also it might be nice to make AR and OD sliders not affected by speed multiplyer on the map.

**Comment by bdach** [comment] 2021-01-15 21:39
#11133 was supposed to add this but got forgotten about.

**Comment by bdach** [comment] 2021-01-15 21:40
Actually, duplicate of #7378.

**Closed by bdach** 2021-01-15 21:40 UTC
Labels: area:mods
