### ISSUE TITLE
Changing osu!mania key count in editor is convoluted

### ISSUE THREAD

**Issue by peppy** [ppy/osu#16339] opened 2022-01-06 05:52 UTC
### Discussed in https://github.com/ppy/osu/discussions/16338

<div type='discussions-op-text'>

<sup>Originally posted by **KuribohG** January  6, 2022</sup>
It is 5 keys in default. How should I change the key count to 4?</div>

**Comment by bdach** [comment] 2022-01-06 08:46
Duplicate of #12904

**Closed by bdach** 2022-01-06 08:47 UTC
Labels: area:editor, priority:2
