### ISSUE TITLE
Notifications can have text hidden due to overflow

### ISSUE THREAD

**Issue by kindlyfire** [ppy/osu#12467] opened 2021-04-17 19:28 UTC
**Describe the bug:** 
I've encountered a notification that has text hidden due to text overflow. The notification also did nothing when clicked, and I couldn't copy the link either... I did manage to get it from the log file though

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2021-04-17 21-06-24](https://user-images.githubusercontent.com/10267586/115124562-31ed3380-9fc3-11eb-9181-f66473428945.png)

**osu!lazer version:** 
2021.416.0

**Comment by BojayB** [comment] 2021-04-17 22:38
Same problem. changing screen resolution did nothing to resize the text either. I'd love to be able to use the integrated OTD settings and see if they'd finally work! (my tablets are the star G540 and G430_B but don't work using normal OTD)

**Comment by frenzibyte** [comment] 2021-04-17 22:39
The issue is quite clear, no need for "same"/"+1" comments, unless the issue requires further details and you would like to provide some, but is not for this issue specifically.

**Comment by mk56-spn** [comment] 2022-09-21 14:49
interested in fixing this, whats the desired behaviour? the box autosizing to fit the text it holds?

**Comment by peppy** [comment] 2022-09-22 04:21
The notification is already autosizing, so I think you'll find the issue here is a single word that's too long to be broken up. You can start by reproducing the issue and checking this yourself.

**Comment by DirkieDurky** [comment] 2023-09-23 21:52
I have the same issue, like @peppy said it's a word too long to be broken up. I'd say the desired behaviour would be a way to view a notification in full screen (by clicking it). I'd imagine in that screen you would also be able to click a link or copy text inside a notification for example.

**Comment by Joehuu** [comment] 2024-07-03 18:13
Has since been fixed in https://github.com/ppy/osu-framework/pull/6231.

**Closed by Joehuu** 2024-07-03 18:13 UTC
Labels: osu!framework issue, type:cosmetic, priority:3
