### ISSUE TITLE
Settings icons not in sync with section

### ISSUE THREAD

**Issue by fufexan** [ppy/osu#11157] opened 2020-12-12 16:44 UTC
**Describe the bug:** 
When in the settings view, clicking on a section icon (e.g. Audio, Input), the corresponding icon doesn't get "highlighted", and instead the one above it does. This only happens when going down in the list; going up through it works as intended. Also, when clicking the *debug* icon, it correctly highlights.
This behaviour also happens in the Key Configuragions icons submenu (global, osu!, osu!taiko, etc), the same way as described above.

This seems to be platform-agnostic, as I have tested it on Linux, Windows and Android and the behaviour is the same.

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1KY_-TDIexUitx9VKPLrg87EyTMZqmwA-/view?usp=sharing

**osu!lazer version:** 
2020.1212.0

**Logs:**
https://drive.google.com/drive/folders/1bf4xD8-J_bJtL3Aypcc7fr4VKW9_tX0m?usp=sharing

**Comment by Game4all** [comment] 2020-12-12 16:48
Duplicate of  #9196 . In the future, please search already opened issues before opening a new one.

**Comment by fufexan** [comment] 2020-12-12 16:55
Oh well, I'd gone down to 2019 and didn't find anything related. Guess "Icon" isn't the first thing that comes to mind.

**Closed** 2020-12-12 16:54 UTC
