### ISSUE TITLE
osu!mania editor not displaying some notes, or displaying notes that have been deleted

### ISSUE THREAD

**Issue by zyletinee** [ppy/osu#22677] opened 2023-02-18 05:46 UTC
### Type

Cosmetic

### Bug description

Notes in the editor sometimes disappear or after being deleted, still appear/act like they are in the playfield.

After alt-tabbing out of the game then back in, some of the sliders disappeared, although you can still hear the hitsounds.
Later, I deleted all notes and sliders in the map, and then column 3's hit lighting was still enabled, even though there were no sliders in that column.

If it helps, this map was originally a map that I created in stable that I imported into osu!lazer around last year.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/125720535/219843213-3989d454-da1b-40de-a59d-ebcd51ce2572.png)
![image](https://user-images.githubusercontent.com/125720535/219843036-a502b04d-8486-476c-a468-2f05dcb562d4.png)

### Version

2023-123.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10773433/network.log)
[performance.log](https://github.com/ppy/osu/files/10773434/performance.log)
[input.log](https://github.com/ppy/osu/files/10773438/input.log)
[database.log](https://github.com/ppy/osu/files/10773439/database.log)
[runtime.log](https://github.com/ppy/osu/files/10773440/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10773441/updater.log)

**Comment by bdach** [comment] 2023-02-18 09:43
> some of the sliders disappeared, although you can still hear the hitsounds

Just to make sure: all you did to make that happen is tab out and back in again? You did not rewind the map or something along those lines?

**Comment by zyletinee** [comment] 2023-02-19 12:59
Yes, although after I noticed they didn't display anymore, I rewinded it to check if the hitsounds still played if that's relevant.

**Comment by peppy** [comment] 2023-02-21 08:37
Duplicate of https://github.com/ppy/osu/issues/21090? Fixed in next release if so.

**Closed** 2023-02-21 08:37 UTC
