### ISSUE TITLE
Permanent black screen

### ISSUE THREAD

**Issue by Histmy** [ppy/osu#7483] opened 2020-01-08 17:44 UTC
I was curious to try osu!laser after a year maybe. After succesfull installation and login i wanted to change screen from window to borderless and than it crashed. When I try to start it again, sounds play normaly but I see nothing more than black screen.

osu!lazer version: 2020.104.0

Logs: I don't know where to find them. Probably they don't exist.

Computer Specifications:

- Processor: Intel i5 8500 2.8GHz

- Graphics Cards: MSI Nvidia GeForce GTX 1050 Ti

- Monitor: AOC G2590FX - LED monitor 25"

**Comment by bdach** [comment] 2020-01-08 17:47
Please check for log existence in either:

* `%AppData%/osu/logs` (on Windows),
* `~/.local/share/osu/logs` (on Linux and macOS).

**Comment by Histmy** [comment] 2020-01-08 17:52
There are some files, but I play osu standard too. Isn't this folder for both?

**Comment by bdach** [comment] 2020-01-08 17:56
It's not. Stable's is `%localappdata%/osu!/Logs`.

**Comment by Histmy** [comment] 2020-01-08 18:00
[database.log](https://github.com/ppy/osu/files/4036602/database.log)
[network.log](https://github.com/ppy/osu/files/4036603/network.log)
[performance.log](https://github.com/ppy/osu/files/4036604/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4036605/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4036606/updater.log)

**Comment by bdach** [comment] 2020-01-08 18:02
Nothing notable in the files attached besides the fact that the runtime log cuts out after entering the disclaimer screen. Please try waiting a little longer, seeing if anything changes and reattaching the logs if it does.

Failing that please attach Windows Event Viewer info after launching the game by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Histmy** [comment] 2020-01-08 18:16
GitHub was not wanting me to upload a evtx file, so i renamed it to txt. It should work when you rename it back i hope. If not, I can upload it somewhere else.

[events.txt](https://github.com/ppy/osu/files/4036659/events.txt)

**Comment by bdach** [comment] 2020-01-08 18:20
Event log turns up these interesting entries:

```
The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=11056 osu!.exe 64bit)
```

I am skeptical any GTX 1050 ran out of memory trying to run lazer when I'm fine on my GT 555M laptop. I'd try checking for device driver updates, maybe it's a bug in their opengl driver.

**Comment by Histmy** [comment] 2020-01-09 16:06
I don't know if it can help you somehow but if I open laser and immediately after open for example total commander, it starts up and I can even change volume with scroll wheel. But the moment I click into it, it just right away crashes. You can see it in [this picture](https://user-images.githubusercontent.com/59661489/72083470-2a3fd900-3302-11ea-893f-ce6848c5596e.jpg).

**Comment by bdach** [comment] 2020-01-09 16:30
At your attached screenshot I'm noticing an FPS overlay of sorts (fraps? shadowplay?). I'd try disabling it, it might be running some interference and therefore leading to the crash.

**Comment by Histmy** [comment] 2020-01-09 21:40
It is GeForce Expirience overlay. When I disable it manualy, it starts by itself when I open osu!laser. And I don't think there is a way to disable it without uninstalling the program and I don't want to do that. I also tried to tick check box "start aplication in 640x480" in [compatibility menu in properties of the game aplication](https://user-images.githubusercontent.com/59661489/72106817-61c57a00-3330-11ea-98a8-a91c08fe3d41.png) and I was able to "play" the game in the corner of my screen as you can see [here](https://user-images.githubusercontent.com/59661489/72106881-7efa4880-3330-11ea-9f9b-b14963400e6e.png). I was even able to change the screen mode to *fullscreen* insted of *borderless* and now I can play the game without any problems. Even with GeForce Expirience overlay.

**Comment by bdach** [comment] 2020-03-01 16:22
Going to close this for now due to lack of new developments. As it stands it looks like a hardware-related issue that we can't really do much about without a reliable reproduction environment.

**Closed by bdach** 2020-03-01 16:22 UTC
Labels: missing details
