### ISSUE TITLE
Ctrl+1/0/9 or Alt+(any key) will input characters into the focused textbox

### ISSUE THREAD

**Issue by rednir** [ppy/osu#14565] opened 2021-08-29 12:53 UTC
**Describe the bug:**
Ctrl+1, Ctrl+0, Ctrl+9 inputs the respective number into the currently focused textbox the next time that textbox receives normal input.
Alt+(any key) also inputs the respective key to the focused textbox.

https://user-images.githubusercontent.com/10225220/131250677-c786e5a5-b422-4a9c-852d-6054149087c9.mp4

**osu!lazer version:** 2021.828.0

**Logs:**
looks normal to me
```
[runtime] 2021-08-29 12:38:08 [debug]: MouseClick handled by SeekLimitedSearchTextBox.
[runtime] 2021-08-29 12:38:10 [debug]: KeyDownEvent(Number2, False) handled by ToolbarRulesetSelector.
[runtime] 2021-08-29 12:38:11 [debug]: KeyDownEvent(Number1, False) handled by ToolbarRulesetSelector.
[runtime] 2021-08-29 12:38:11 [debug]: KeyDownEvent(Number2, False) handled by ToolbarRulesetSelector.
[runtime] 2021-08-29 12:38:12 [debug]: KeyDownEvent(Number1, False) handled by ToolbarRulesetSelector.
[runtime] 2021-08-29 12:38:24 [debug]: KeyDownEvent(A, False) handled by SeekLimitedSearchTextBox.
```

**Comment by bdach** [comment] 2021-08-29 13:09
<kbd>AltGr</kbd> is known to be broken (https://github.com/ppy/osu-framework/issues/1965). First time I've seen <kbd>Ctrl</kbd> being mentioned as broken the same way, though, and it does seem to reproduce with raw framework even. Investigating.

**Comment by bdach** [comment] 2021-08-29 13:21
@rednir do you mind clarifying what OS/platform this is on? are you using a linux distribution? if so, then wayland or x11?

**Comment by rednir** [comment] 2021-08-29 13:22
Arch Linux on x11

**Comment by bdach** [comment] 2021-08-29 13:24
Right, this seems to be an upstream bug, then. See https://github.com/libsdl-org/SDL/issues/4695.

Nothing more we can do here, closing.

**Closed by bdach** 2021-08-29 13:24 UTC
Labels: framework-fix-required
