### ISSUE TITLE
Blinds crashes iOS

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4396] opened 2019-03-03 05:25 UTC
How to replicate:

Turn on blinds mod

Go on a song

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smoogipoo** [comment] 2019-03-03 05:53
Duplicate of https://github.com/ppy/osu/issues/4293

**Closed by smoogipoo** 2019-03-03 05:53 UTC
