### ISSUE TITLE
Quickly changing beatmaps in song select screen using arrows can move you to the top

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#8126] opened 2020-03-04 05:48 UTC
**Describe the bug:** When using right arrow to scroll downwards, it will move you to the top, and using the left one, it will move to the bottom of song select.

**Screenshots or videos showing encountered issue:** https://youtu.be/2stwzSzrwyY

**osu!lazer version:** 2020.229.1

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4285272/runtime.log)

**Comment by peppy** [comment] 2020-03-04 05:50
Quite potentially related to https://github.com/ppy/osu/issues/8111, which I am currently investigating.

**Comment by Joehuu** [comment] 2020-03-04 05:53
Duplicate of https://github.com/ppy/osu/issues/3051

**Closed by Joehuu** 2020-03-04 05:53 UTC
Labels: area:song-select
