### ISSUE TITLE
Osu!Lazer won't open

### ISSUE THREAD

**Issue by SaintePayette** [ppy/osu#7985] opened 2020-02-24 15:43 UTC
Hi, im on MacOS Mojave (1.14.6), I just downloaded the app (2020.221.0), but it won't launch. Its icon appears for around 1 sec then disappears.
Maybe it is because I have an other version of normal Osu! installed (b20200208) I don't know. (btw discord rich presence doesn't work for this one even if i replaced with the good file)

**Comment by peppy** [comment] 2020-02-24 15:57
Duplicate of https://github.com/ppy/osu/issues/7791. We require more details to figure out what's goingon here.

**Closed by peppy** 2020-02-24 15:57 UTC
