### ISSUE TITLE
Offset saved for different mp3

### ISSUE THREAD

**Issue by AosUK** [ppy/osu#24633] opened 2023-08-23 17:01 UTC
### Type

Crash to desktop

### Bug description

self explanatory see video

### Screenshots or videos

https://github.com/ppy/osu/assets/134084802/720db208-e2d4-4200-8ef2-5177f7e3be75

### Version

2023.815.0

### Logs

[performance-input.log](https://github.com/ppy/osu/files/12421635/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12421636/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12421637/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12421638/updater.log)
[database.log](https://github.com/ppy/osu/files/12421626/database.log)
[input.log](https://github.com/ppy/osu/files/12421627/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12421628/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12421631/network.log)
[performance.log](https://github.com/ppy/osu/files/12421632/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/12421633/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12421634/performance-draw.log)

**Comment by bdach** [comment] 2023-08-23 17:03
Duplicate of https://github.com/ppy/osu/issues/24558

**Closed by bdach** 2023-08-23 17:03 UTC
