### ISSUE TITLE
osu!mania custom skin support

### ISSUE THREAD

**Issue by frederik69420** [ppy/osu#7320] opened 2019-12-21 21:14 UTC
**Describe the new feature:** 
If you had a osu!mania skin you were using on stable and tried to use it on osu!lazer mania then it wouldn't work, But with This Feature, It Would Work!
**Proposal designs of the feature:** 
Use All elements From the Skin Excluding : the score, the combo, the accuracy, the hp bar, and the ranking screen, etc.

**Comment by peppy** [comment] 2019-12-21 21:31
Closing as duplicate of https://github.com/ppy/osu/issues/4896.

**Closed by peppy** 2019-12-21 21:31 UTC

**Comment by frederik69420** [comment] 2019-12-21 21:36
i didn't know someone already did that sorry!
