### ISSUE TITLE
Performance drop when drawing near infinite length perfect sliders

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#10368] opened 2020-10-04 18:05 UTC
**Describe the bug:** 
When a perfect slider, with a body going from A to C through B, has its points in a line going ACB (see screenshot), having such slider on screen causes a major performance drop. This can happen accidentally in editor when dragging the middle point B to a new position.

**Screenshots or videos showing encountered issue:** 
![osu_2020-10-04_20-56-17](https://user-images.githubusercontent.com/11320483/95023238-975f7f80-0684-11eb-970d-2b73b7f62d5f.png)
Screenshot shows me having 18fps but that's after a 3 second long freeze.

**osu!lazer version:** 
2020.1002.0

**Comment by bdach** [comment] 2020-10-04 18:08
It should not even be possible to be able to arrange the points in such a manner. The blueprint should refuse to update upon detecting that this could happen.

**Comment by peppy** [comment] 2020-10-04 21:28
Duplicate of https://github.com/ppy/osu/issues/5538

**Closed by peppy** 2020-10-04 21:28 UTC
Labels: area:editor, type:performance
