### ISSUE TITLE
Importing some skins causes System.InvalidOperationException

### ISSUE THREAD

**Issue by MrTheMake** [ppy/osu#2311] opened 2018-03-24 13:12 UTC
Importing some specific skins basically results in the same errors seen in https://github.com/ppy/osu/issues/2306.
An example is [#!Shengentora GAR.zip](https://github.com/ppy/osu/files/1844400/Shengentora.GAR.zip).

**Comment by Aergwyn** [comment] 2018-03-24 20:48
So it's a duplicate issue. Can you close it and add your info to the existing one instead?

**Comment by MrTheMake** [comment] 2018-03-26 11:21
If I understand it correctly, then https://github.com/ppy/osu/issues/2306 is about handling exceptions better (with the example given) while this issue is about skins that cause exceptions in the first case.

**Comment by peppy** [comment] 2018-03-29 06:43
Duplicate of #2306.

**Closed by peppy** 2018-03-29 06:43 UTC
