### ISSUE TITLE
I don't know how this is caused but I found a bug where lazer would let you spin 8k times per minute and tap twice at once with the pen. https://youtu.be/hd1DOYX22Gs

### ISSUE THREAD

**Issue by verysmallgiant** [ppy/osu#12200] opened 2021-03-27 04:29 UTC
https://youtu.be/hd1DOYX22Gs
-I used my mouse for all the non buggy parts.

my theory - I think it is because I had my pentablet software on

**Comment by bdach** [comment] 2021-03-27 06:53
Duplicate of #12171

**Closed by bdach** 2021-03-27 06:53 UTC
