### ISSUE TITLE
Pause screen sound still plays after unpause

### ISSUE THREAD

**Issue by Tellilum** [ppy/osu#9777] opened 2020-08-05 00:30 UTC
**Describe the bug:** 
When osu is unpaused the pause audio will periodically continue to faintly play in the background until exiting to the main menu
**osu!lazer version:** 
2020.801.0
**Logs:**

[network.log](https://github.com/ppy/osu/files/5025427/network.log)
[performance.log](https://github.com/ppy/osu/files/5025428/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5025429/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5025430/updater.log)
[database.log](https://github.com/ppy/osu/files/5025431/database.log)

**Comment by peppy** [comment] 2020-08-05 00:30
Duplicate of https://github.com/ppy/osu/issues/9739 please search before reporting.

**Closed by peppy** 2020-08-05 00:30 UTC
