### ISSUE TITLE
Play others modes on mobile

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8189] opened 2020-03-09 19:28 UTC
**Describe the new feature:** 

Just add a way to play taiko, mania, and CTB on Android/IOS

**Proposal designs of the feature:** 

Taiko: If we tap on the left side of the screen that will trigger the blue button and the right side for red button

Mania: Add 4 buttons at the bottom of the notes

CTB: Slide the finger to move the catcher

**Comment by bdach** [comment] 2020-03-09 19:30
Duplicate of #4201

**Closed by bdach** 2020-03-09 19:30 UTC
