### ISSUE TITLE
Incorrect leaderboard display on map switch

### ISSUE THREAD

**Issue by dequubi** [ppy/osu#22002] opened 2023-01-02 16:38 UTC
### Type

Game behaviour

### Bug description

Switching from ranked to unranked map right when the leaderboard is loaded causes it to display on the unranked map. Also displays that leaderboard during gameplay.

Maps shown in the video:
- https://osu.ppy.sh/beatmapsets/292644#osu/658561 (ranked)
- https://osu.ppy.sh/beatmapsets/326102#osu/724194 (unranked)

### Screenshots or videos

https://user-images.githubusercontent.com/47535336/210258372-8f1bb94d-b2bc-4f4a-8a7e-41bc2eeda491.mp4

### Version

2022.1228.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10332589/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10332590/updater.log)
[database.log](https://github.com/ppy/osu/files/10332591/database.log)
[input.log](https://github.com/ppy/osu/files/10332592/input.log)
[network.log](https://github.com/ppy/osu/files/10332593/network.log)
[performance.log](https://github.com/ppy/osu/files/10332594/performance.log)

**Comment by dequubi** [comment] 2023-01-23 18:44
I'm afraid this hasn't fixed the issue. Reproduced it on the latest version (2023.123.0)

https://user-images.githubusercontent.com/47535336/214122223-6e476bd5-29c1-4bd9-bd1b-16feacbfb0a3.mp4

[network.log](https://github.com/ppy/osu/files/10482707/network.log)
[performance.log](https://github.com/ppy/osu/files/10482708/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10482709/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10482710/updater.log)
[database.log](https://github.com/ppy/osu/files/10482711/database.log)
[input.log](https://github.com/ppy/osu/files/10482712/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10482713/legacy-ipc.log)

**Comment by bdach** [comment] 2023-01-23 18:47
Yeah, can reproduce. The remaining cases will be related to the final map not having a leaderboard for one reason or another (in the video above, it's because the first map is ranked, and the second is graved).

**Comment by Theighlin** [comment] 2023-01-23 20:51
Duplicate of #20490 or the other way around?

**Comment by bdach** [comment] 2023-01-23 21:00
I don't know. Maybe. I'll close that other one because @cdwcgt seems to think it's the same issue and I'm not sure anybody else on this god's green earth knows better.

**Comment by peppy** [comment] 2023-01-24 04:39
Threading, debouncing, scheduling and async was a mistake.

**Closed** 2023-01-24 18:49 UTC
Labels: type:online, area:gameplay, area:song-select
