### ISSUE TITLE
Approach circle doesn't align with hit circle

### ISSUE THREAD

**Issue by Nioheel** [ppy/osu#6229] opened 2019-09-24 00:01 UTC
So I realized that after switching my skin on lazer that the actual hit circle is smaller than what is displayed. The approach circle goes through the hit circle and registers a "perfect" hit when it's within the circle. The screen shot is from a slider to show where the circle is ending up. This may just be a skin problem but I just wanted to address this just in case other people were having the same problem.

![osu lazer bug](https://user-images.githubusercontent.com/55721359/65470912-f9569980-de21-11e9-9684-12a54da4deaf.jpg)

osu!lazer 2019.919.0

skin:
http://bit.ly/2mbFdhV

**Comment by iiSaLMaN** [comment] 2019-09-24 00:06
Duplicate of #2358

**Closed** 2019-09-24 00:07 UTC
