### ISSUE TITLE
Raw input on osu lazer is broken on mac

### ISSUE THREAD

**Issue by gemskingZZZ** [ppy/osu#7102] opened 2019-12-08 21:49 UTC
**Describe the bug:** 
I already ~~fucking~~ described it but GitHub decided to reset this ffs

short version: I turned raw input on and I can't move my cursor nor click I can use f4 to move my cursor and go back but I can't click with it on sadly. my pen and mouse dont work with this on. luckily I can exit with ESC hehe I wish there was a shortcut for settings on the keyboard 

**Screenshots or videos showing the encountered issue:** 
no

**osu!lazer version:** 
latest of 9th Dec

**Logs:** 
wtf is dis

**Comment by bdach** [comment] 2019-12-08 21:55
Duplicate of at least #6290 - issues with raw input on macOS are widely known.

To reset the raw input setting, try <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>R</kbd>.

**Closed by bdach** 2019-12-08 21:55 UTC

**Comment by gemskingZZZ** [comment] 2020-02-11 08:50
> Duplicate of at least #6290 - issues with raw input on macOS are widely known.
> 
> To reset the raw input setting, try Command+Option+R.

tried command+option+R but it still doesn't  fix

**Comment by swoolcock** [comment] 2020-02-11 12:16
Pretty sure it’s ctrl+cmd+R, I’m not at a computer to test.

**Comment by gemskingZZZ** [comment] 2020-02-15 03:14
still, it doesn't work, I've tried deleting every trace of osu!lazer (even the zip files) and after reinstalling the settings are still there (raw input) so I just made a new computer account and it worked fine... thanks for all the help everyone! :)

**Comment by swoolcock** [comment] 2020-02-15 03:37
osu!lazer stores its data in `~/.local/share/osu`.  Just delete that.
