### ISSUE TITLE
Options menu sliders not showing certain characters

### ISSUE THREAD

**Issue by PsychoStatic** [ppy/osu#6566] opened 2019-10-21 18:15 UTC
I recently just reinstalled a fresh version of Lazer, since it has been a while since I last tested it out, and found that some characters were missing. I'm not sure if this is just a failed install issue (or something else) but it's kinda odd IMO.
(It appears to be only 0 and 1 that are missing)
But the resolution options still feature 0 & 1 so I'm not 100% sure if it's just an options slider issue.

![osu_2019-10-21_19-09-44](https://user-images.githubusercontent.com/33607709/67231032-6a479c00-f436-11e9-8303-9366de732db6.png)
https://www.dropbox.com/s/4rw1bzuewdyubqj/osu%21%202019.10.21%20-%2019.02.32.01_Trim.mp4

2019.1021.0

**Comment by PsychoStatic** [comment] 2019-10-21 18:17
nvm i found the logs.
[network.log](https://github.com/ppy/osu/files/3752303/network.log)

[runtime.log](https://github.com/ppy/osu/files/3752300/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3752301/updater.log)
[database.log](https://github.com/ppy/osu/files/3752302/database.log)




[Uploading performance-gamethread.audio.log…]()
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3752297/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3752298/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3752299/performance-gamethread.update.log)

**Comment by bdach** [comment] 2019-10-21 18:20
Looks like this might be yet another instance of #1488, but I'm not a 100% sure.

**Comment by peppy** [comment] 2019-10-22 06:28
I may be blind, but I can't see the missing characters in the screenshot. Is it the frame display?

**Comment by bdach** [comment] 2019-10-22 06:39
The hold-to-confirm slider tooltip is missing some zeroes.

**Comment by peppy** [comment] 2019-10-22 14:33
This should be a duplicate of #1488 then, yes.

**Closed by peppy** 2019-10-22 14:33 UTC
