### ISSUE TITLE
can't run (android version)

### ISSUE THREAD

**Issue by ikhoeyZX** [ppy/osu#12196] opened 2021-03-26 11:37 UTC
**Describe the bug:** 
when open app force close by self.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/79812109/112625186-8a6c5d80-8e69-11eb-93e1-360841f31b03.mp4

**osu!lazer version:** 
osu!lazer version : 0.1 (2021.323.0)
android version : 7.1.2 x86

**Logs:**
(!) no folder in Android/Data/sh.ppy.osulazer
so i just upload android logcat instead.
[logcat.txt](https://github.com/ppy/osu/files/6211468/logcat.txt)

**Comment by jai-x** [comment] 2021-03-26 11:54
Would you be able to post your device's make and model?

**Comment by ikhoeyZX** [comment] 2021-03-26 13:47
i'm using asus zenfone 5 (T00F), yes it's x86 phone (intel atom chipset), it use PowerVR SGX544MP2 GPU (OpenGLES 2.0)

**Comment by jai-x** [comment] 2021-03-26 14:44
Thanks for confirming your device specifications.

osu!lazer currently doesn't supply builds for Android x86, only Android ARM currently.

This may change in the future, but the priority is currently for completing the desktop PC version before making mobile fixes.

Duplicate of https://github.com/ppy/osu/issues/7241

**Closed by jai-x** 2021-03-26 14:44 UTC
Labels: missing details, platform:android, type:crash

**Comment by bdach** [comment] 2021-03-26 15:11
Framework *does* ship x86 binaries, but we're very much not actively supporting them. The actual issue here is likely to be GL ES 2.0, which we cannot currently support, making this a duplicate of #9673.

**Comment by hmtheboy154** [comment] 2021-06-27 18:28
> Framework _does_ ship x86 binaries, but we're very much not actively supporting them. The actual issue here is likely to be GL ES 2.0, which we cannot currently support, making this a duplicate of #9673.

Hello, I am running on some Android-x86 builds like 7.1 (PhoenixOS), 9 (BlissOS 11.14) and 11 (BlissOS 14.3), test the latest builds of osu and it always crash.

My graphic card is a Intel HD Graphic 2000, which support OpenGLES 3.0 and can already run osu on Linux and Windows

Is there any files that I can get for you guys for debugging ? (logcat or tombstones)

**Comment by bdach** [comment] 2021-06-27 18:30
Please begin with actual game logs from `Android/Data/sh.ppy.osulazer/logs`, if there are any. Do note though that android is not a priority (compared to the desktop version) and we're not likely to put effort in for now unless the resolution is trivial.

**Comment by hmtheboy154** [comment] 2021-06-27 19:20
> Please begin with actual game logs from `Android/Data/sh.ppy.osulazer/logs`, if there are any. Do note though that android is not a priority (compared to the desktop version) and we're not likely to put effort in for now unless the resolution is trivial.

Hi, the logs folder is empty, there is no files generated when I run the game. However, the Android system did have a tombstones file after the game is crash

This is on PhoenixOS, if you want me to get the rest like BlissOS I'll do it soon.
[tombstone_00.txt](https://github.com/ppy/osu/files/6722168/tombstone_00.txt)

**Comment by bdach** [comment] 2021-06-27 19:29
The attached file is showing a segfault on a memory free in `monosgen` (a mono implementation of the .NET GC). It's as low-level an issue as it can realistically get on android. It seems extremely likely that tracking this down and isolating the bug would require weeks of dedicated debugging by a highly skilled developer to track down the cause of it, not to mention the fact that it is likely that the issue is also hardware-specific, so said developer would also have to own an x86 android device.

I'm sorry to say this but your issue is not even near high enough priority to warrant spending that much resources on it.
