### ISSUE TITLE
Add a setting to add skip button for breaks

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12493] opened 2021-04-20 02:31 UTC
There is a skip button for the beginning of the song, so is it possible to add a setting for a skip button during very long breaks? This will skip to a few seconds before the next note.

**Comment by peppy** [comment] 2021-04-20 02:33
Duplicate of https://github.com/ppy/osu/issues/6871. Please search first.

**Closed by peppy** 2021-04-20 02:33 UTC
