### ISSUE TITLE
osu! tracks mouse in fullscreen when unfocused

### ISSUE THREAD

**Issue by DavidHusicka** [ppy/osu#12336] opened 2021-04-08 08:46 UTC
**Describe the bug:** 
osu!lazer tracks mouse even if the window is unfocused. This causes hover sound effects playing while having osu! running in the background. This bug does not appear in version 2021.331.0. Tested on Linux machine with DWM (Xorg server). osu! is set to fullscreen.

**Screenshots or videos showing encountered issue:**  
https://youtu.be/0LCZd5Odsok

**osu!lazer version:** 2021.407.1

**Comment by peppy** [comment] 2021-04-08 09:08
Duplicate of https://github.com/ppy/osu-framework/issues/4347.

**Closed by peppy** 2021-04-08 09:08 UTC
Labels: framework-fix-required, platform:linux, type:input
