### ISSUE TITLE
Failed replays imported from stable to lazer play out

### ISSUE THREAD

**Issue by Bitslayn** [ppy/osu#29826] opened 2024-09-09 19:20 UTC
### Type

Game behaviour

### Bug description

I saved a replay from osu!(stable) and imported it into osu!lazer then viewed the replay. The results screen showed a rating higher than F and watching the replay, it doesn't fail but plays to the end with no inputs. This isn't expected behavior as viewing replays made in osu!lazer results in the replay ending where I failed.

### Screenshots or videos

Imported from stable
---

https://github.com/user-attachments/assets/1fdc5786-c87d-48ba-ab18-7aa8c3e6308d

https://github.com/user-attachments/assets/a7cc691f-8c76-4b7d-84b2-45634465a490

Played, saved, and replayed in lazer
---

https://github.com/user-attachments/assets/2c26d8ad-64f7-4f5d-a57e-7ac8d6bc1133

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16935471/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-12 20:45
Duplicate of https://github.com/ppy/osu/issues/20857

**Closed by Joehuu** 2024-09-12 20:45 UTC
