### ISSUE TITLE
"click to view logs" crashes on mobile devices

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5984] opened 2019-09-04 03:19 UTC
If notification center prompts an error and asks user to view the logs, then the game will crash on click. 

**Logs**
https://pastebin.com/kzD64FTE

**Comment by swoolcock** [comment] 2019-09-04 04:43
Known issue, is caused by the loss of OpenGL context and the current workaround of force closing the app.

**Comment by peppy** [comment] 2019-09-05 00:35
This is a different issue to the GL context loss (see attached log).

**Comment by ThatsNiceGuy** [comment] 2019-09-06 04:15
happens on iOS too

**Comment by frenzibyte** [comment] 2024-12-09 12:20
Has long been resolved since https://github.com/ppy/osu-framework/pull/5075

**Closed by frenzibyte** 2024-12-09 12:20 UTC
Labels: platform/mobile
