### ISSUE TITLE
Song select transitioned from main menu does not always use currently playing song

### ISSUE THREAD

**Issue by signedinteger** [ppy/osu#10129] opened 2020-09-11 00:52 UTC
**Describe the bug:** 
Going from main menu where song A is playing, into song select screen, sometimes a different song's beatmap is displayed instead

**Screenshots or videos showing encountered issue:** 
"normal": https://streamable.com/5ctfr2
"bugged": https://streamable.com/5p1i7l

**osu!lazer version:** 2020.910.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5205274/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5205277/performance.log)

**Comment by Joehuu** [comment] 2020-09-11 00:58
Duplicate of https://github.com/ppy/osu/issues/9772

**Comment by signedinteger** [comment] 2020-09-11 01:02
not sure I understand how this is same as #9772, this is not about songs with maps in a different ruleset, the songs shown in video both only have maps in the osu! ruleset and I'm going into the song select in osu! ruleset

**Comment by Joehuu** [comment] 2020-09-11 01:08
It seems like you have a star rating filter applied and the now playing map wasn't in the range, will reopen for now as the issue is different.

**Comment by Joehuu** [comment] 2020-09-11 01:14
Both issues can be fixed though by making the beatmap carousel not select anything if the current song is not in the filter (like in stable).

**Comment by peppy** [comment] 2020-09-11 01:36
It's the same thing.

**Closed** 2020-09-11 01:36 UTC
Labels: area:song-select, type:UX
