### ISSUE TITLE
osu!mania scoring does not match stable

### ISSUE THREAD

**Issue by Hana-Sakuna** [ppy/osu#11172] opened 2020-12-14 13:46 UTC
:3 Idk how to explain, just showing some pic to tell it

Real Accuracy:
![image](https://user-images.githubusercontent.com/75989631/102088061-58546400-3e55-11eb-9c29-0783a2acc023.png)

Accuracy of Replay
![image](https://user-images.githubusercontent.com/75989631/102088511-fc3e0f80-3e55-11eb-9df0-132fc3add6af.png)

It's the latest ver. by now: 2020.12.12

**Comment by bdach** [comment] 2020-12-14 16:01
Score is https://osu.ppy.sh/scores/mania/323673415.

**Comment by Eeveelution** [comment] 2020-12-22 14:16
Speaking of accuracy, in osu!standard when only clicking a slider head and dropping the rest of the slider, 
you should (in regular osu stable) get a 100 but in lazer it still gives a 300, 

best example of this would be this play by me: https://osu.ppy.sh/scores/osu/3127077961 
where on stable it has an accuracy of 88% and on lazer im getting nearly 96% iirc, 

should i maybe make this into an seperate issue? (assuming one hasnt been made yet? i havent checked) or is this comment enough?

**Comment by bdach** [comment] 2020-12-22 17:33
@Eeveelution lazer uses a semi-experimental unified scoring mode, and as such that is intended for now (although **do note that doesn't mean that this is how things will be in the end**). [more details can be seen here](https://github.com/ppy/osu/wiki/Scoring).

as an aside this issue thread is intended for mania only. please avoid derailing threads in this manner in the future.

**Comment by Hana-Sakuna** [comment] 2020-12-23 02:46
So, this problem Is due to experimental, and there may be a different way of calculation in the future.

**Comment by peppy** [comment] 2021-01-18 05:44
Attaching replay just in case it goes missing before this issue is revisited:

[replay-mania_471698_323673415.osr.zip](https://github.com/ppy/osu/files/5828070/replay-mania_471698_323673415.osr.zip)

**Comment by smoogipoo** [comment] 2021-04-06 01:38
Closing as intended.

**Closed by smoogipoo** 2021-04-06 01:38 UTC
Labels: area:scoring, ruleset:osu!mania
