### ISSUE TITLE
Volume Mixer bugged because of osu!lazer

### ISSUE THREAD

**Issue by lolicop123** [ppy/osu#6712] opened 2019-11-04 16:31 UTC
So when I have osu!lazer open, and I open volume mixer (task-bar -> right click on sound icon -> Open Volume Mixer), it looks really bugged out. I'm pretty sure its to do with osu! as I haven't experienced this with any other application. I can still change the volume slider, I just cant see it. I am also on Windows 8.1.

https://i.ibb.co/YpBS6Zv/image.png

Version 2019.1029.0

Logs:
[performance.log](https://github.com/ppy/osu/files/3804982/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3804983/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3804984/updater.log)
[database.log](https://github.com/ppy/osu/files/3804985/database.log)
[network.log](https://github.com/ppy/osu/files/3804986/network.log)

**Comment by jai-x** [comment] 2019-11-04 16:35
Duplicate of https://github.com/ppy/osu/issues/2424

**Closed** 2019-11-04 16:46 UTC
