### ISSUE TITLE
Changing volume in replay causes lags

### ISSUE THREAD

**Issue by Kolonsky** [ppy/osu#10515] opened 2020-10-15 15:21 UTC
**Describe the bug:**
The game starts lagging when changing master volume in replay.
Looks like it happening not in the very beginning of replay. In example below it's 1:50. 

**Screenshots or videos showing encountered issue:**
https://youtu.be/_LNaLyzl0yI

**osu!lazer version:**
2020.1009.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/5385936/runtime.log)

**Comment by peppy** [comment] 2020-10-15 15:25
This is a known issue and will be resolved with hitobject pooling.

**Comment by Joehuu** [comment] 2020-10-15 18:11
Duplicate of https://github.com/ppy/osu/issues/6129

**Closed by Joehuu** 2020-10-15 18:11 UTC
Labels: area:gameplay, type:performance
