### ISSUE TITLE
Add Left-handed support for tablet integration

### ISSUE THREAD

**Issue by hal0423** [ppy/osu#12137] opened 2021-03-22 05:18 UTC
Pretty much what I want is said in the title. I'm already used to the left-handed mode (both Wacom and Hawku driver support this mode) since it's a CTL-470, not necessarily because I'm left-handed but rather of how the cable is attached to the tablet sideways and I find it easier to just use left-handed mode with the cable attached to the right side. I believe this proposal would also benefit any tablet that has the cable attached to the sideways.

**Comment by peppy** [comment] 2021-03-22 05:18
Duplicate of https://github.com/ppy/osu/issues/12097

**Closed by peppy** 2021-03-22 05:18 UTC
