### ISSUE TITLE
HP for low star mania maps is extremely strict, it is almost impossible for a (new) player to pass any map without full combo.

### ISSUE THREAD

**Issue by Doksha** [ppy/osu#12383] opened 2021-04-12 18:05 UTC
**Describe the new feature:** Better and more reasonable HP for low star maps (a single miss anywhere past halfway, even if high accuracy will result in a fail)

**Proposal designs of the feature:**  Revert to the old HP system, or find a middle ground that will allow new players to play mania without needing no fail.

**Comment by peppy** [comment] 2021-04-12 18:06
Duplicate of https://github.com/ppy/osu/issues/10566.

**Closed by peppy** 2021-04-12 18:06 UTC
