### ISSUE TITLE
languages in Osu!Lazer

### ISSUE THREAD

**Issue by aewastaken** [ppy/osu#12889] opened 2021-05-20 17:47 UTC
**Describe the new feature:** Add other languages to Osu!Lazer (it can took while, i understand) 
**Proposal designs of the feature:** 
Since Osu!Stable have almost all languages, i would like to see them in Osu!Lazer as well.
because you know... some people dont undertstand english so it would be harder for them to play Osu.
i can help with translating if you would like to.

**Comment by frenzibyte** [comment] 2021-05-20 17:48
Duplicate of https://github.com/ppy/osu/issues/4757. Please search.

**Closed by frenzibyte** 2021-05-20 17:48 UTC

**Comment by bdach** [comment] 2021-05-20 18:02
There has been recent progress in this area. See https://github.com/ppy/osu/pull/12495.

In general, pointing out that stale issues are stale is not very helpful. You've even said that "it takes time" yourself. Please look at the open issue counter, we're nearing a thousand.
