### ISSUE TITLE
Skin doesn't appear when I import from stable.

### ISSUE THREAD

**Issue by Guestest** [ppy/osu#11760] opened 2021-02-12 07:10 UTC
**Describe the bug:**
When I click import skins from stable, this skin does not even appear after it's done loading. [https://osuskins.net/skin/tD0wr9N](url)

**Screenshots or videos showing encountered issue:**
![osu_2021-02-12_00-56-19](https://user-images.githubusercontent.com/78949747/107738862-2c2a5780-6ccd-11eb-9167-b7975fb43733.jpg)
 
![image](https://user-images.githubusercontent.com/78949747/107738914-4b28e980-6ccd-11eb-8f1b-3981db9a14a1.png)

**osu!lazer version** 
2021.212.0.

**Comment by frenzibyte** [comment] 2021-02-12 07:15
I see it, it's named "- elohere x Seouless (Seouless)". Keep in mind that lazer uses whatever is set to `Name` in the skin's `skin.ini` file, unlike stable where it basically takes the skin folder's name.

**Comment by Guestest** [comment] 2021-02-12 07:16
Not sure how to add labels so sorry bout that.

**Comment by peppy** [comment] 2021-02-12 07:16
Confirm that it is actually loaded and just had an unexpected name?

**Comment by Guestest** [comment] 2021-02-12 07:17
No, a skin with that name is also not in the folder

**Comment by peppy** [comment] 2021-02-12 07:17
In your lazer skin dropdown, not the folder.

**Comment by Guestest** [comment] 2021-02-12 07:17
That's what I meant, sorry

**Comment by peppy** [comment] 2021-02-12 07:27
Have you tried scrolling to the top? As it starts with a `-` it will be at the top or the bottom of the list.

**Comment by Guestest** [comment] 2021-02-12 07:31
I have tested all the skins in the list and none of them are it, and when I look in the osu! skin folder it just tells me the name is  - elohere x Seouless. However if there is a way to check the lazer skin folder I don't know what it is

**Comment by peppy** [comment] 2021-02-12 12:37
Please change the name in the skin.ini or redownload the skin. This is most likely not a bug so I'm closing this issue.

**Closed** 2021-02-12 12:37 UTC
