### ISSUE TITLE
error when leaving multiplayer and multi map starts at same time

### ISSUE THREAD

**Issue by TryhardPickles** [ppy/osu#29898] opened 2024-09-17 10:17 UTC
### Type

Game behaviour

### Bug description

if i leave and the multiplayer map starts, this error occurs. i was in a singleplayer (only me in the room) multi room. i think it has something to do with the order of how osu! handles processing order, (could be wrong) so it starts the map, but then it realizes that the multi room doesn't exist anymore. thanks!

### Screenshots or videos

[osu_2024-09-17_19-11-39](https://github.com/user-attachments/assets/8bf46ca4-a815-47dd-9ab8-d907fcdb0e79)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17026706/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-17 17:33
Duplicate of https://github.com/ppy/osu/issues/29858

**Closed by Joehuu** 2024-09-17 17:33 UTC
