### ISSUE TITLE
[Duplicated #3377] Update failed 1004.1 -> 1017.0 | 1020.0

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3612] opened 2018-10-18 12:04 UTC
I ran `\AppData\Local\osulazer\osudll.cmd` via running lazer rev 1004.1, got that:
```
2018-10-18 20:38:20> Program: Starting Squirrel Updater: --processStartAndWait osu!.dll
2018-10-18 20:38:21> Program: Want to launch 'C:\Users\xxx\AppData\Local\osulazer\app-2018.1017.0\osu!.exe'
2018-10-18 20:38:21> Program: About to wait for parent PID 1728
2018-10-18 20:38:22> Program: About to launch: 'C:\Users\xxx\AppData\Local\osulazer\app-2018.1017.0\osu!.exe': 
2018-10-18 20:38:22> Program: Failed to start process: System.ComponentModel.Win32Exception (0x80004005): アクセスが拒否されました。
   場所 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   場所 System.Diagnostics.Process.Start()
   場所 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   場所 Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
```
(where xxx is censored my computer name)
the 1017 exe exists there.
also, I'd like to know what the errorcode means.

details:
OS: windows 7 x 64
Note: I set the update.exe's property 'run as admin' checked.

**Comment by Wieku** [comment] 2018-10-18 22:07
Duplicate of #3377. Game does update properly but it fails to make shortcut. What happens when you run it by `\AppData\Local\osulazer\osu!.exe`?

**Comment by lolita-is-godddd** [comment] 2018-10-19 12:58
It says "Could not access specified device, directory, or file. Maybe you have not permitted."
But idk where it will access (when update to 1004, too), so I'm doing stay 1004.

**Comment by lolita-is-godddd** [comment] 2018-10-19 16:02
Also, I ran install.exe 1017 release, it said same error.
~~it requires administrator and I'm not so can't run it lol~~

**Comment by lolita-is-godddd** [comment] 2018-10-21 12:40
I ran `update --install=app-2018.1020.0` :
```
2018-10-21 21:34:01> Program: Starting Squirrel Updater: --install=app-2018.1020.0
2018-10-21 21:34:02> Program: Starting install, writing to C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0
2018-10-21 21:34:02> Program: RELEASES doesn't exist, creating it at C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0\RELEASES
2018-10-21 21:34:03> Unhandled exception: System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.IO.DirectoryNotFoundException: パス 'C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0' の一部が見つかりませんでした。
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   場所 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   場所 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   場所 System.IO.DirectoryInfo.GetFiles()
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Squirrel.Update.Program.executeCommandLine(String[] args)
   場所 Squirrel.Update.Program.main(String[] args)
---> (内部例外 #0) System.IO.DirectoryNotFoundException: パス 'C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0' の一部が見つかりませんでした。
   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.FileSystemEnumerableIterator`1.CommonInit()
   場所 System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   場所 System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   場所 System.IO.DirectoryInfo.GetFiles()
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```
I think it should create directory app-{version} .
Btw if there exists,
```
2018-10-21 21:36:45> Program: Starting Squirrel Updater: --install=app-2018.1020.0
2018-10-21 21:36:45> Program: Starting install, writing to C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0
2018-10-21 21:36:45> Program: RELEASES doesn't exist, creating it at C:\Users\xxx\AppData\Local\osulazer\app-2018.1020.0\RELEASES
2018-10-21 21:36:46> Unhandled exception: System.AggregateException: 1 つ以上のエラーが発生しました。 ---> System.InvalidOperationException: シーケンスに要素が含まれていません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- 内部例外スタック トレースの終わり ---
   場所 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   場所 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   場所 System.Threading.Tasks.Task.Wait()
   場所 Squirrel.Update.Program.executeCommandLine(String[] args)
   場所 Squirrel.Update.Program.main(String[] args)
---> (内部例外 #0) System.InvalidOperationException: シーケンスに要素が含まれていません
   場所 System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   場所 Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```
(same #3550 )
If someone has any version the update worker, please tell me.

**Comment by peppy** [comment] 2018-10-22 14:57
Closing as duplicate of #3377 (please don't add this to the title in future).

**Closed by peppy** 2018-10-22 14:57 UTC
Labels: installation
