### ISSUE TITLE
Map selection fails when spamming "random map"

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3383] opened 2018-09-07 15:07 UTC
If the random button (or the F2 key) is repeatedly pressed and a map is selected while doing that, osu!lazer will almost always throw an error and can fail to select the current map correctly.
Video: https://streamable.com/pzuq9
Example log output:
```
07.09.2018 14:58:35: beatmap changed from "Imperial Circus Dead Decadence - Yomi yori Kikoyu, Koukoku no Tou to Honoo no Shoujo [Ringtone Size] (zPeanut) [Apollo's Keter]" to "Fractal Dreamers - Blue Haven (Gero) [Paradise]"
07.09.2018 14:58:35: working beatmap updated to Fractal Dreamers - Blue Haven (Gero) [Paradise]
07.09.2018 14:58:35: Screen changed → PlayerLoader
07.09.2018 14:58:35: updating selection with beatmap:4977 ruleset:0
07.09.2018 14:58:35: beatmap changed from "Fractal Dreamers - Blue Haven (Gero) [Paradise]" to "yumemidoll - Lyrith -Meikyuu Lyrith- (eiri-) [Uberzolik's Insane]"
07.09.2018 14:58:35: Unhandled exception has been allowed with 0 more allowable exceptions .
07.09.2018 14:58:35: An unhandled error has occurred.
07.09.2018 14:58:35: System.InvalidOperationException: Can not set value to "yumemidoll - Lyrith -Meikyuu Lyrith- (eiri-) [Uberzolik's Insane]" as bindable is disabled.
07.09.2018 14:58:35: at osu.Framework.Configuration.Bindable`1.set_Value(T value)
07.09.2018 14:58:35: at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass31_0.<performUpdateSelected>g__run|0()
07.09.2018 14:58:35: at osu.Framework.Threading.ScheduledDelegate.RunTask()
07.09.2018 14:58:35: at osu.Framework.Threading.Scheduler.Update()
07.09.2018 14:58:35: at osu.Framework.Graphics.Drawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
07.09.2018 14:58:35: at osu.Framework.Platform.GameHost.UpdateFrame()
07.09.2018 14:58:35: at osu.Framework.Threading.GameThread.ProcessFrame()
07.09.2018 14:58:35: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by LittleEndu** [comment] 2018-09-07 15:31
Duplicate of #1905

**Comment by Morilli** [comment] 2018-09-07 15:33
Did you watch the video? My issue has nothing to do with importing beatmaps.

**Comment by LittleEndu** [comment] 2018-09-07 15:35
I didn't, sorry. It's just that I get the same log output.

**Closed** 2019-03-22 05:36 UTC
Labels: bug, songselect
