### ISSUE TITLE
Crash while booting

### ISSUE THREAD

**Issue by Nyanekoy** [ppy/osu#3231] opened 2018-08-15 03:10 UTC
[runtime.log](https://github.com/ppy/osu/files/2289072/runtime.log)

**Comment by Nyanekoy** [comment] 2018-08-15 03:28
nope

**Comment by ZapTech43** [comment] 2018-08-15 03:31
15.08.2018 03:04:26: fatal error:
15.08.2018 03:04:26: **System.Collections.Generic.KeyNotFoundException: The given key '131072' was not present in the dictionary.**
15.08.2018 03:04:26: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
15.08.2018 03:04:26: at OpenTK.Graphics.GraphicsContext.get_CurrentContext()
15.08.2018 03:04:26: at OpenTK.GameWindow.get_VSync()
15.08.2018 03:04:26: at osu.Framework.Platform.GameHost.DrawFrame()
15.08.2018 03:04:26: at osu.Framework.Threading.GameThread.ProcessFrame()
15.08.2018 03:04:26: at osu.Framework.Threading.GameThread.runWork()
15.08.2018 03:04:26: at System.Threading.Thread.ThreadMain_ThreadStart()
15.08.2018 03:04:26: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
15.08.2018 03:04:26: --- End of stack trace from previous location where exception was thrown ---
15.08.2018 03:04:26: at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by smoogipoo** [comment] 2018-08-15 05:02
Duplicate of https://github.com/ppy/osu/issues/1482.

**Closed by smoogipoo** 2018-08-15 05:02 UTC
Labels: opentk, startup crash
