### ISSUE TITLE
weird relationalship between draw FPS and Drawing taken time in ms

### ISSUE THREAD

**Issue by lolita-is-godddd** [ppy/osu#3593] opened 2018-10-14 11:59 UTC
![this shows 267fps but taken 1466.39ms](https://user-images.githubusercontent.com/25249461/46916311-aeb68580-cff3-11e8-9cff-be1e07ccfcc9.png)
This shows 267fps but taken 1466.39ms, so I'm not sure which is correct (or neither).

**Comment by peppy** [comment] 2018-10-14 12:00
Do the displays stay around these numbers throughout execution?

**Comment by lolita-is-godddd** [comment] 2018-10-14 12:18
![osu_2018-10-14_21-06-13](https://user-images.githubusercontent.com/25249461/46916396-2c2ec580-cff5-11e8-8153-f20fca7700ef.png)
![osu_2018-10-14_21-06-18](https://user-images.githubusercontent.com/25249461/46916397-2c2ec580-cff5-11e8-9b81-6b5c1d88f628.png)
![osu_2018-10-14_21-06-58](https://user-images.githubusercontent.com/25249461/46916398-2c2ec580-cff5-11e8-813b-63e332dda756.png)
![osu_2018-10-14_21-05-50](https://user-images.githubusercontent.com/25249461/46916399-2cc75c00-cff5-11e8-812d-cf77e1311d2f.png)
![osu_2018-10-14_21-05-58](https://user-images.githubusercontent.com/25249461/46916400-2cc75c00-cff5-11e8-83d2-728881c0a177.png)
![osu_2018-10-14_21-06-05](https://user-images.githubusercontent.com/25249461/46916401-2d5ff280-cff5-11e8-9041-9a82999f1761.png)
![image](https://user-images.githubusercontent.com/25249461/46916402-2e911f80-cff5-11e8-839f-cce2b7b9523e.png)
Here you are.
Example, the first one, draw one is 551fps but taken 2.19ms. If 2.19ms, the fps should be (`1000/2.19=`)456. Or if 551fps, the ms should be (`1000/551=`)1.81 .

**Comment by smoogipoo** [comment] 2018-10-15 05:28
Have been able to replicate this a few times. Started happening after the last changes to clocks/frame time calculations.

**Comment by Joehuu** [comment] 2020-09-20 04:39
Can't reproduce for a while now (the large ms and the numbers being stuck sometimes). Seems to be duplicate of https://github.com/ppy/osu-framework/issues/2532 which was fixed in https://github.com/ppy/osu-framework/pull/2962.

**Closed by Joehuu** 2020-09-20 04:39 UTC
Labels: area:tooling, framework-fix-required, low-priority
