### ISSUE TITLE
I can't import audio or background on HarmonyOS 2.0( Huawei device ) 

### ISSUE THREAD

**Issue by DJ5-1** [ppy/osu#21419] opened 2022-11-25 11:42 UTC
### Type

Game behaviour

### Bug description

Uhm I don't know why and how but watch video... 

### Screenshots or videos

https://user-images.githubusercontent.com/84573116/203977143-2156957b-7969-4003-8e9b-33966b121318.mp4

### Version

2022.1123.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10092427/runtime.log)
[input.log](https://github.com/ppy/osu/files/10092433/input.log)
[network.log](https://github.com/ppy/osu/files/10092437/network.log)
[database.log](https://github.com/ppy/osu/files/10092438/database.log)
[performance.log](https://github.com/ppy/osu/files/10092441/performance.log)

**Comment by jai-x** [comment] 2022-11-25 11:49
Duplicate of https://github.com/ppy/osu/issues/11911

**Closed by jai-x** 2022-11-25 11:49 UTC
