### ISSUE TITLE
The game crash when changing some visual setting in autoplay mod

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#12066] opened 2021-03-18 18:22 UTC
**Describe the crash:**
I play osu!lazer on macOS and when I set mods to autoplay (to watch autoplay) and change some visual setting during watching autoplay the game crashed all time. After I reopen a game the game still remember a visual setting choice before crash like before crash I set 'Beatmap colours' in visual setting from ON to OFF, the game crash. After I reopen game and use autoplay mod again a 'Beatmap colours' in visual setting showing OFF. This crash happen in changing visual setting both ON to OFF and OFF to ON.

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1oHL64tfP9DRiT91KE0PDorJiB0FdZfdq/view?usp=sharing
In this screen record I try to change 'Beatmap colours' from OFF to ON and it's crash.

I try it more about 3 times and I record all time that I test. This link below is contain screen record, log, apple crash log report and beatmap link.
https://drive.google.com/drive/folders/1DO7lGYxoNk0oH8rT_HgGpzzW-RwaoeMz?usp=sharing

**osu!lazer version:** 
2021.312.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6166398/database.log)
[network.log](https://github.com/ppy/osu/files/6166399/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/6166400/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6166401/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6166402/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/6166403/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6166405/runtime.log)

**Computer Specifications:** 
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Processor: 2 GHz Quad-Core Intel Core i5
Memory: 16 GB 3733 MHz LPDDR4X
Graphics: Intel Iris Plus Graphics 1536 MB
OS: macOS Big Sur 11.2

**Comment by bdach** [comment] 2021-03-18 18:28
Duplicate of #5798

**Closed by bdach** 2021-03-18 18:28 UTC
