### ISSUE TITLE
Autoplay misses when you wiggle playback speed.

### ISSUE THREAD

**Issue by Zozimoto** [ppy/osu#2228] opened 2018-03-15 15:09 UTC
As the title says, Auto misses when you wiggle around the playback speed.

Here's a video showing it because github doesn't support video files: https://drive.google.com/uc?id=1KAbGqjkhHPZ3D_PRgA0r7rySUvDrPlON

**Comment by jacksonisiah** [comment] 2018-03-16 14:38
Duplicate of #1825

**Comment by Zozimoto** [comment] 2018-03-16 20:31
not exactly what i wrote, that thread is talking about how you skip around in the replay, auto misses. what i'm talking about, is that auto misses, when you change the playback speed fast.

**Comment by peppy** [comment] 2019-04-04 02:15
This should be resolved (via `FrameStabilityContainer` and other replay handling  improvements).

**Closed by peppy** 2019-04-04 02:15 UTC
Labels: bug, replay
