### ISSUE TITLE
Self-fixing slider velocity multiplier

### ISSUE THREAD

**Issue by hi-mei** [ppy/osu#3951] opened 2018-12-27 18:58 UTC
**The problem***
Basically, when you work with sliders, adjusting their length is super frustrating - you have to always deal with velocity multiplier to match the slider end to the specific tick in timeline. 
So lets say you made this slider out of huge ton of white anchors
![](https://osu.ppy.sh/ss/12394506)

And suddenly you realize that it doesnt match to the tick it meant to... All you can do now is
a. adjust the sldier shape to the velocity multiplier
b. adjust the multiplier to match the slider shape

So basically it becomes super frustrating especially if you work with some kind of grid, for example
![](https://puu.sh/CnUnT/25aeb1e548.png)

Where you have to put the slider end and sldier start at the specific place but at the same time to add a variety to the slider shape. Trust me, its VERY frustrating to work with.

**The solution**
Basically, add a mode when you can automatically adjust the slider length to the closest tick of the current beat snap divisor, which will fix the slider velocity multiplier to match the timing and shape.

**Comment by peppy** [comment] 2021-03-17 07:27
This is basically a duplicate of #7882.

**Closed by peppy** 2021-03-17 07:27 UTC
Labels: area:editor, proposal
