### ISSUE TITLE
Beatmap starrating is not updated

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#14195] opened 2021-08-10 05:49 UTC
**Describe the bug:** 
When I change the speed of the map, the star rating is not updated.
Also, when "Difficulty Adjust" is turned on, the star rating is updated once, and after that it remains the same

**Screenshots or videos showing encountered issue:** 
Video: https://drive.google.com/uc?id=1WeBUSTn8k8JDnb_fonyRxt_9ZSmvYrMv

**osu!lazer version:** 
2021.809.0-lazer

**Logs:**

[logs.zip](https://github.com/ppy/osu/files/6959273/logs.zip)

**Comment by smoogipoo** [comment] 2021-08-10 06:00
Duplicate of https://github.com/ppy/osu/issues/10580

**Closed by smoogipoo** 2021-08-10 06:00 UTC
