### ISSUE TITLE
Storyboard cannot play content before offset 0

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu#22410] opened 2023-01-25 09:27 UTC
### Type

Game behaviour

### Bug description

Link: https://osu.ppy.sh/beatmapsets/1913687#osu/3947758
It can be played in stable, is this a bug or is it not intended to be implemented?

### Version

osu! 2023.123.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10497909/runtime.log)

**Comment by peppy** [comment] 2023-01-25 09:32
Duplicate of #22403.

**Closed by peppy** 2023-01-25 09:32 UTC
