### ISSUE TITLE
Rulesets could not load

### ISSUE THREAD

**Issue by SmolPancake** [ppy/osu#10360] opened 2020-10-04 04:11 UTC
This bug/glitch doesn't let me type my account to sign in,
In addition, I cant really do anything in the app which includes downloading beatmaps through osu direct, viewing scoreboard, and literally everything else. My phone is a samsung note 8 that's updated to the latest version. Thanks in advance for the help :)
 
![Screenshot_20201003-205259](https://user-images.githubusercontent.com/72329112/95006749-67e54000-05bc-11eb-9be0-c983924d6874.jpg)

Latest one they just released on Oct. 3

**Comment by enoslayd** [comment] 2020-10-04 04:36
Logs? (Located at internal or sd card/android/data/sh.ppy.osulazer. depends on the phones settings)

**Comment by peppy** [comment] 2020-10-04 04:37
Likely duplicate of https://github.com/ppy/osu/issues/6507?

**Comment by Joehuu** [comment] 2020-10-04 04:44
> This bug/glitch doesn't let me type my account to sign in

That shouldn't block you from signing in. If you can't sign in, there is probably something in the logs that can help us.

And yeah the ruleset thing is a duplicate.

**Comment by SmolPancake** [comment] 2020-10-04 05:11
Soo umm just how exactly do u access these logs? Sorry, I'm fairly new so I dont know what to do, and if anyone is wondering how I can't sign in, it's where if i type something, the letters don't show up. Here's a screenshot
![20201003_221114](https://user-images.githubusercontent.com/72329112/95007482-6704dc00-05c5-11eb-8466-cd3f2ab8c0c6.jpg)

**Comment by Joehuu** [comment] 2020-10-04 05:28
That seems like the samsung keyboard, try using the google keyboard for now. This is a duplicate of https://github.com/ppy/osu/issues/8264.

**Closed by Joehuu** 2020-10-04 05:28 UTC

**Comment by SmolPancake** [comment] 2020-10-04 05:37
Thanks for the help everyone, it finally is able to work, so I guess it was just the Samsung keyboard lol. However, how do I get ride of this notification saying that the Ruleset couldn't load

**Comment by bdach** [comment] 2020-10-04 09:27
There's nothing you can do for now. The error is not fatal and should not affect gameplay, save for being mildly annoying. See #6507.
