### ISSUE TITLE
Black Screen and Cursor's texture isn't display

### ISSUE THREAD

**Issue by ItsukaHiro** [ppy/osu#8897] opened 2020-04-29 11:54 UTC
- Sorry. I'm not a coder -
After I finished install and Alt+F4, I go back to osu!lazer and cannot see anything (the music still be played).
I close osu!lazer once again, now I can see everything, but mouse is disappeared

**Comment by enoslayd** [comment] 2020-04-29 14:37
Any screenshot or logs? Logs can be found on %appdata%\osu\logs
Also lazer version?

**Comment by ItsukaHiro** [comment] 2020-05-01 00:39
![osu_2020-05-01_07-32-34](https://user-images.githubusercontent.com/64533662/80771582-1c96b380-8b7e-11ea-836c-901dc511fd10.jpg)

You can see that the mouse is on the "Osu" mode, but texture of mouse isn't display

[logs.zip](https://github.com/ppy/osu/files/4562008/logs.zip)

And I sent you my logs files. I think it can help you.
Something I has black screen, but after re-open osu!lazer, everything comeback normally.

**Comment by Joehuu** [comment] 2020-05-25 03:22
Duplicate of https://github.com/ppy/osu/issues/8487. Logs point out the same graphics card.

**Closed by Joehuu** 2020-05-25 03:22 UTC
Labels: missing details
