### ISSUE TITLE
Rendering issues with OpenGL Legacy

### ISSUE THREAD

**Issue by sineplusx** [ppy/osu#23271] opened 2023-04-21 14:50 UTC
### Type

Cosmetic

### Bug description

Since the new update, some objects render incorrectly on my setup:
- The small osu! logo that appears before gameplay. All other logos, like the big one on the main menu, still appear fine
- There is an issue involving transparency of objects, most noticeably the cursor, which is barely visible. Another instance is the star icon on the difficulty info box (On the same screen as the osu logo, compare the screenshots)

I tested this on Ubuntu 22.10 and an Intel iGPU. There is a chance that this is something driver-related, but the last release was working fine for me.

Related? #23240

### Screenshots or videos

OpenGL (Legacy)
![legacy1](https://user-images.githubusercontent.com/112003827/233661265-032e5843-3b2d-4357-8a62-a629759970fd.png)
![legacy2](https://user-images.githubusercontent.com/112003827/233661306-df85a9b6-a81a-48e6-a2e4-f306255201d5.png)

OpenGL (Veldrid)
![veldrid1](https://user-images.githubusercontent.com/112003827/233661451-29011256-ae6d-409b-a1ad-92d4a6b5d6fa.png)
![veldrid2](https://user-images.githubusercontent.com/112003827/233661501-90ec5a63-1a92-4f33-9bac-b793e5bb902f.png)

### Version

2023.419.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11296557/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11296561/runtime.log)

**Comment by frenzibyte** [comment] 2023-04-22 07:24
Those look like atlas mipmap levels not generating correctly, let's mark this as a duplicate of https://github.com/ppy/osu/issues/2324.

**Closed by frenzibyte** 2023-04-22 07:24 UTC
Labels: renderer:legacy-gl
