### ISSUE TITLE
Text looks really buggy and is unreadable 

### ISSUE THREAD

**Issue by FlickzGamez** [ppy/osu#11217] opened 2020-12-20 11:19 UTC
**Describe the bug:** 
text looks buggy 
![Screenshot 2020-12-19 at 13 43 54](https://user-images.githubusercontent.com/74789386/102711905-00828680-42b5-11eb-960c-5af3729ab404.png) 

**osu!lazer version:** 
2020.1204.0
**Logs:**

**Comment by peppy** [comment] 2020-12-20 11:29
You are missing attaching logs. Also, since this is a graphical / GPU issue, please include your full PC specs and operating system. And check your drivers are up-to-date.

**Comment by bdach** [comment] 2020-12-20 11:39
Duplicate of #9314

**Closed by bdach** 2020-12-20 11:39 UTC
Labels: missing details
