### ISSUE TITLE
Ability to submit scores to Bancho and record play time

### ISSUE THREAD

**Issue by HDAcai** [ppy/osu#8725] opened 2020-04-11 22:36 UTC
**Describe the new feature:** 
Being able to submit scores to Bancho from osu! Lazer from any platform, not only recent but past scores from previous Osu! Lazer versions. Also being able to record play time from osu! Lazer as players may also play Lazer and should count towards their total play time. This would also mean being able to earn pp from osu! Lazer despite the scoring and accuracy differences between versions.

For life reasons I’m not able to play stable and I don’t know much about how to code in this feature, but I think it should look something like this:  
![7C3424F2-FCCF-4B11-AB32-566658E2766B](https://user-images.githubusercontent.com/57856097/79056319-fda1a300-7c09-11ea-8157-8c794a953173.png)

**Comment by bdach** [comment] 2020-04-11 22:40
Duplicate of #7957

**Closed by bdach** 2020-04-11 22:40 UTC
