### ISSUE TITLE
Multitouch problem with spinner.

### ISSUE THREAD

**Issue by keremsaracli** [ppy/osu#8949] opened 2020-05-06 01:53 UTC
I just happened to find a bug in osu!lazer’s mobile version. When you put at least 3 fingers around a spinner, it spins automaticly and fast. I guess that happens because of lazer doesn’t allow multi cursor.

Here’s the video of the bug: https://youtu.be/Td1-5FyjCZ4

The osu!lazer version that bug happened is 2020.306.0

I have no idea how to find logs and share it on Ios.

**Comment by iiSaLMaN** [comment] 2020-05-06 01:55
Duplicate of https://github.com/ppy/osu/issues/8224

**Closed** 2020-05-06 02:07 UTC
