### ISSUE TITLE
Osu!Lazer doesn't run in fullscreen after second launch

### ISSUE THREAD

**Issue by Frezzy123** [ppy/osu#1679] opened 2017-12-09 02:04 UTC
(Sorry for bad english) Basically I installed osu!lazer an hour ago and it all went fine and all but when I closed it and launched it again for some reason it does a weird glitch and it doesn't let me play on fullscreen, if I go windowed or borderless it works but I don't know why when i go to fullscreen it goes black and the colours of my screen go black and white or something similar... I tried, restarting computer, reinstalling, and I have latest drivers and client..

Here is my PC specs:
Intel i3 7100
8 gb RAM
Intel HD 630 Graphics

I'll attach a video too so you can see what's going on (I converted the video to mp4 so it was smaller, since the original video was 40 mb, the video its a bit low quality cuz of the extreme conversion but you can see at least what is going on)

[VID_20171209_025519.zip](https://github.com/ppy/osu/files/1544268/VID_20171209_025519.zip)

**Comment by peppy** [comment] 2017-12-09 04:10
Likely going to require a framework fix. Also likely intel driver specific.

**Comment by lunafreya** [comment] 2019-11-06 03:57
Is this still active, @peppy?

**Comment by peppy** [comment] 2019-11-06 07:19
What does your comment infer? Can you still reproduce this?

**Comment by Frezzy123** [comment] 2019-11-06 16:50
Idk what happened but now it works + I get like 100 fps more since I last tested Lazer, thanks for fixing this

**Comment by bdach** [comment] 2019-11-06 16:53
Well, good to hear that; closing as resolved, I suppose.

**Closed by bdach** 2019-11-06 16:53 UTC
Labels: bug, framework fix required

**Comment by LarssJakobsons** [comment] 2022-04-02 11:39
Same problem! I can hear the music and me clicking but osu doesnt show. If I press F11 it finnally shows something... How to fix this?

**Comment by peppy** [comment] 2022-04-02 11:44
Being tracked via https://github.com/ppy/osu/issues/17552. We have no idea how to fix this yet, nor what the issue is. Please run windowed for now.
