### ISSUE TITLE
Beatmap selection jumps to the top when holding next

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8456] opened 2020-03-26 18:36 UTC
**Describe the bug:** 
When you hold right arrow key in song select, sometimes (when beatmaps are still loading in it seems) beatmap selection fails and reset to the first beatmap. 

[This test](https://github.com/LittleEndu/osu/blob/traversal-is-broken/osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs#L86-L117) shouldn't fail.

**osu!lazer version:** 
master commit a141e2e8b78418ac723fc682389ec4e43d5e96c2

**Comment by Joehuu** [comment] 2020-03-27 00:50
Duplicate of https://github.com/ppy/osu/issues/3051

**Closed by Joehuu** 2020-03-27 00:50 UTC
