### ISSUE TITLE
Crash during replay

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11076] opened 2020-12-03 14:31 UTC
Crashed while watching a replay on [this beatmap](https://osu.ppy.sh/beatmapsets/873671). Running with `--tk` doesn't seem to help

**osu!lazer version:** 2020.1203.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5636660/runtime.log)

**Comment by PercyDan54** [comment] 2020-12-03 14:37
Duplicate of #11052

**Closed** 2020-12-03 14:39 UTC
