### ISSUE TITLE
Unable to edit "romanized title" with certain characters

### ISSUE THREAD

**Issue by waaipe** [ppy/osu#27518] opened 2024-03-07 10:01 UTC
### Type

Other

### Bug description

I am using a title that is not "romanised" due to using characters with accents. In my specific case, characters with ´ are already considered romanised while characters with ˇ are not. Due to this, I am unable to edit romanised song title here.

In my screenshot, I am able to edit the romanised artist, but not title. I would expect to be able to edit both.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/155621949/70bf2c34-b4ef-407e-b4f8-60d568384a17)

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14522340/compressed-logs.zip)

**Comment by bdach** [comment] 2024-03-07 10:07
[This is mostly intentional behaviour](https://github.com/ppy/osu/pull/13438#discussion_r649503903).

Closing, but mostly because this is a duplicate of https://github.com/ppy/osu/issues/6552 if anything.

**Closed by bdach** 2024-03-07 10:07 UTC
