### ISSUE TITLE
Circles start up source

### ISSUE THREAD

**Issue by Inkninjaaa** [ppy/osu#7448] opened 2020-01-05 22:32 UTC
Starting the game with the circles source freezes the game

Could not get any of these

osu!lazer version: 12/27/19 - 01/04/20

Logs: this is the only start up that has had this happen.

Computer Specifications: Moto z3 on Android 10.0

**Comment by bdach** [comment] 2020-01-06 06:00
Duplicate of #6315.

**Closed by bdach** 2020-01-06 06:00 UTC
