### ISSUE TITLE
Freeze after loading a slider of beatmap First Of The Year (2359830) in the editor 

### ISSUE THREAD

**Issue by Tommy2103** [ppy/osu#26013] opened 2023-12-21 17:35 UTC
### Type

Performance

### Bug description

beatmap: https://osu.ppy.sh/beatmapsets/1125563#osu/2359830 (top diff)
While playing the map I start lagging when it tries to load this slider `01:04:667 (1) -` (also `02:10:873 (1) -`).
If I try to select this slider in the editor then osu! freezes and then i have to terminate the process.
From osu!stable i can see there are a lot of slider anchors, so probably lazer is having a hard time trying to render all of these anchors.
Also when selecting the slider the RAM usage goes up to 10gb of memory. 
Selecting other complex sliders is fine since they have not so many anchors compared to this one. 

### Screenshots or videos

![osu_2023-12-21_18-28-22](https://github.com/ppy/osu/assets/62664757/03689c32-df26-47de-a9d4-e59b410e1f79)
![Screenshot_1](https://github.com/ppy/osu/assets/62664757/1ab0f87a-93d7-46e4-bd23-14fec8b4d740)

### Version

2023.1222.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13744733/compressed-logs.zip)

**Comment by bdach** [comment] 2023-12-21 17:40
Duplicate of https://github.com/ppy/osu/discussions/23500

**Closed by bdach** 2023-12-21 17:40 UTC
