### ISSUE TITLE
The judgement of Hyper Dash seems very strange.

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#8032] opened 2020-02-27 12:37 UTC
**Describe the bug:** 
I played a specific map to show this bug clearly. It seems that I need to keep pressing dash key to finish a hyper dash but it sometimes doesn't work. The judgement is very strange. (You can see my key overlay in gameplay to analyze.) Is there anything regressed?
**Screenshots or videos showing encountered issue:** 
0226ver.
https://www.dropbox.com/s/med8ae45s1sxt42/hyper%20dash%20bug.flv?dl=0
0215ver.
https://www.dropbox.com/s/1v99qvpaxtdar3r/hyper%20dash%20%280215ver.%29.flv?dl=0

**osu!lazer version:** 
0226
**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*

**Comment by bdach** [comment] 2020-02-27 17:36
Duplicate of #8016 (I think)

**Closed by bdach** 2020-02-27 17:36 UTC
