### ISSUE TITLE
[bug] on loading certain maps, lazer will consume high amounts of ram before ever loading

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#12832] opened 2021-05-16 02:01 UTC
**Describe the bug:** 
When loading [this beatmap](https://osu.ppy.sh/beatmapsets/988533), osu!lazer will never finish loading it (on a 32gb ram system, maybe someone with 128gb of ram can get it to load lmao) and instead just "load" forever while consuming more and more RAM, to the point of causing swapping and Windows instability.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/10524728/118382709-381c0300-b5b5-11eb-9b1a-3d255f2cca2a.png)
Would capture a clear video but right now both of my GPUs decided to show code 43 shortly after taking screenshots and I am troubleshooting that (submitting this issue from glorious 1024x768 uefi gop res lol) so probably the video comes later.

What I can give you right now are steps to reproduce:
Use the below lazer version, import [the map mentioned](https://osu.ppy.sh/beatmapsets/988533), use 3840x2160@144hz (idk if this is required, im just saying how it happened), use stock osu lazer skin, use osu!standard ruleset, enable auto mod, start loading the map with storyboard enabled, check task manager and see rising memory usage

**osu!lazer version:** 
2021.515.0 Windows x64

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6488528/logs.zip)

**Comment by peppy** [comment] 2021-05-16 03:13
Can you test with a storybord disabled? Storyboards are a known area which has not been optimized yetz

**Comment by Headline** [comment] 2021-05-16 06:17
> 
> Can you test with a storyboard disabled? Storyboards are a known area which has not been optimized yet.

I was able to reproduce, disabling the storyboard prevents the issue. 

I'm interested in contributing, could you perhaps point me in the right direction to tackle this?

**Comment by bdach** [comment] 2021-05-16 06:54
@Headline with all due respect, I'm afraid I don't think this is a very good first issue. I'd recommend something simpler first, just to get to grips how the framework works, as that knowledge will be instrumental to resolving any type of performance problem.

**Comment by Headline** [comment] 2021-05-16 07:15
No worries, I poked a little bit so I'll share what's actually eating so many resources and then defer this to you guys. I'm sure you already suspected what was going on, but just in case it's useful:

We're spending all of the time inside of ApplyTransforms
![](http://i.michaelwflaherty.com/u/JLjPzg0dMT.png)

Objects
![](http://i.michaelwflaherty.com/u/17MfxaWbNZ.png)

**Comment by peppy** [comment] 2021-05-16 07:25
Duplicate of https://github.com/ppy/osu/issues/12401.

**Closed by peppy** 2021-05-16 07:25 UTC
