### ISSUE TITLE
SIGSEV when launching osu! (Degub) on Linux ( Ubuntu 19.10 )

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#7043] opened 2019-12-02 17:12 UTC
### **Steps to reproduce:** 
```bash
git clone https://github.com/ppy/osu.git
dotnet run --project osu.Desktop > theLogd.log
```
**What I tried**
Since it failed I tried running `git checkout master;git pull` and retried the `dotnet` build, same log output.
So I tried running the binary `./osu.Desktop/bin/Debug/netcoreapp3.0/osu\! >theLogdr.log` (Same output, just different font loading  order) 
Also tried `git checkout` on previous branches and redtried the `dotnet` build, but they run dotnet version < 3.0
### **osu!lazer version:** 
Not sure, just cloned and tried to build according to the README.md (piped the output to a file uploaded below)
### **Logs:** 
[theLogd.log](https://github.com/ppy/osu/files/3912262/theLogd.log)
[theLogdr.log](https://github.com/ppy/osu/files/3912303/theLogdr.log)

### **Computer Specifications:** 
```json
GL Version:                 4.6.0 NVIDIA 390.129
GL Renderer:                GeForce GTX 1060 3GB/PCIe/SSE2
GL Shader Language version: 4.60 NVIDIA
GL Vendor:                  NVIDIA Corporation
CPU:                        AMD® Ryzen 5 1600 six-core processor × 12
RAM:                        16 GB DDR4 ( 15.7GiB )
```
Edit:
```json
Kernel: 5.3.0-24-generic
Resolution: 1280x1024
```
Can can someone help me with this?

**Comment by peppy** [comment] 2019-12-02 17:15
I believe this is already [fixed framework side](https://github.com/ppy/osu-framework/pull/3057) and should be fixed osu! side with the next framework update.

**Comment by jai-x** [comment] 2019-12-02 17:18
Duplicate of: https://github.com/ppy/osu/issues/7025
Has been fixed in: https://github.com/ppy/osu-framework/pull/3057

A new release of the osu!framework hasn't been released yet so osu!lazer still uses the unfixed version. You will have to wait for that to happen or manually build against a locally cloned osu!framework.

**Comment by MightyHelper** [comment] 2019-12-02 17:19
I saw it and since it was closed I thought it was implemented. Sorry.

**Comment by bdach** [comment] 2019-12-02 17:19
Let's leave this open until the next bump so that we don't get a sixth instance of this opened I guess.

**Closed** 2019-12-04 15:49 UTC
Labels: hard crash / startup crash, linux
