### ISSUE TITLE
osu not opening osz

### ISSUE THREAD

**Issue by speedyninja12** [ppy/osu#29753] opened 2024-09-07 02:24 UTC
### Type

Game behaviour

### Bug description

it wont extract osz files in the new update

### Screenshots or videos

https://github.com/user-attachments/assets/50f3f7b1-284b-4a6d-a834-ee700387d805

### Version

2023.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16914056/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-07 02:41
Duplicate of https://github.com/ppy/osu/issues/29730

**Closed by Joehuu** 2024-09-07 02:41 UTC
