### ISSUE TITLE
Crash by selecting non-existent text

### ISSUE THREAD

**Issue by bdach** [ppy/osu#23616] opened 2023-05-21 17:04 UTC
### Discussed in https://github.com/ppy/osu/discussions/23614

<div type='discussions-op-text'>

<sup>Originally posted by **soopax** May 21, 2023</sup>
# Steps to reproduce
1. Import a beatmap and open it in the editor.
2. Go to the setup tab.
3. Select some text with the cursor. Don't make any changes to the beatmap. (See this screenshot for an example:)
![Screenshot from 2023-05-21 15-35-15](https://github.com/ppy/osu/assets/101510334/ad288361-1392-41c6-b465-2538a4c37522)
4. Don't move the cursor. Keep the left mouse button pressed on the text selection.
5. Press `Esc` twice to exit the editor. Your cursor should still be pink.
6. Move the cursor again.

This also happens with sliders or spinners in the compose tab.
1. Select a hit circle or slider
2. Don't move the cursor. Keep the left mouse button pressed on the object.
3. Press `Esc` to exit the editor. Your cursor should still be pink.
4. Move the cursor again.

Log:
[runtime.log](https://github.com/ppy/osu/files/11524574/runtime.log)

Edit: clarification</div>

**Comment by Susko3** [comment] 2023-05-24 21:22
The second problem is a duplicate of #21294.

Checking with a debugger, the `Parent` [here](https://github.com/ppy/osu-framework/blob/9bbc6a81a2b8f035e2b043d3718d2db6e4f1d868/osu.Framework/Graphics/UserInterface/TextBox.cs#L576) is null, causing the crash. The textbox in question is also removed from the scene graph and disposed.

Looks to be another case of removed/disposed drawables receiving events: https://github.com/ppy/osu-framework/issues/5156 / https://github.com/ppy/osu-framework/pull/5557.

**Comment by frenzibyte** [comment] 2023-12-30 22:22
This has already been resolved by https://github.com/ppy/osu-framework/pull/5557. Cannot reproduce both of the scenarios mentioned in OP.

**Closed by frenzibyte** 2023-12-30 22:22 UTC
Labels: osu!framework issue, type:reliability, priority:1
