### ISSUE TITLE
Replayed accuracy not same with the local accuracy

### ISSUE THREAD

**Issue by 113Jiang** [ppy/osu#29354] opened 2024-08-08 16:41 UTC
### Type

Game behaviour

### Bug description

After passing [this beatmap](https://osu.ppy.sh/beatmapsets/450069#mania/965654) , I recorded a video of the replay which was uploaded to [this website](https://www.bilibili.com/video/BV1npYbe4Evp) . But after the replay ended, I found that the accuracy of the replay isn't the same with the accuracy shown in the local leaderboard. This issue can also be seen in the video mentioned above. The result screen at the start shows 95.78%, but in the end, it shows 95.88%. I have already seen the same kind of bug couple of times.

### Screenshots or videos

The local record: ![The local record](https://github.com/user-attachments/assets/1f3509f1-1ab1-4339-8814-e6d6a5128cae)
The original result screen: ![The original result screen](https://github.com/user-attachments/assets/5d862710-8896-410b-90d7-80f4d0d334e4)
The result screen after the replay: ![The result screen after the replay](https://github.com/user-attachments/assets/2d984ef9-d9ea-479f-8afe-a0920b93bf2a)
Full video: https://www.bilibili.com/video/BV1npYbe4Evp
I can't upload the video to this site because it's to big, sorry.

### Version

2024.731.0-lazer

### Logs

The logs may be outdated because I recorded the video the day before yesterday but I found the error today. However, when I opened the replay again, the game played the replay just the same way as I described above, so the logs may be useful.
[compressed-logs.zip](https://github.com/user-attachments/files/16551020/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-08-09 04:44
Duplicate of https://github.com/ppy/osu/issues/29217, https://github.com/ppy/osu/issues/28744, and the multitude of replay-related issues. https://github.com/ppy/osu/labels/area%3Areplay

**Closed by smoogipoo** 2024-08-09 04:44 UTC
