### ISSUE TITLE
Add missing back button functionality

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6952] opened 2019-11-24 19:50 UTC
If you press the hardware back button (e.g. on your mouse or keyboard), you can back out of some things, but not others. Generally, screen transitions have back button functionality, but panels and overlays (settings, chat, mod selector, osu!direct, music player, etc.) do not, even though you can back out of them with Esc.

**Comment by Joehuu** [comment] 2019-11-24 20:05
Duplicate of https://github.com/ppy/osu/issues/6026

**Closed by Joehuu** 2019-11-24 20:05 UTC
Labels: input, user interface, ux
