### ISSUE TITLE
Creating a room while joining a different one can crash the game

### ISSUE THREAD

**Issue by MaybeNotWrong** [ppy/osu#11317] opened 2020-12-26 01:45 UTC
**Describe the bug:** Clicking to join a room, then quickly clicking create room several times will freeze the game and result in a crash shortly after.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/37958125/103144098-faacfb00-4723-11eb-9c62-38510e93fcf6.mp4

**osu!lazer version:** 2020.1225.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5742576/runtime.log)

**Comment by Joehuu** [comment] 2020-12-26 01:56
Can you reproduce, the logs don't show anything.

I tried to reproduce, and I'm getting different behaviors:

- Crash (same as OP, looks to be dupe of https://github.com/ppy/osu/issues/11302) [runtime.log](https://github.com/ppy/osu/files/5742582/runtime.log)

- Doesn't crash, but bugs stuff:

https://user-images.githubusercontent.com/35318437/103144191-58b4f080-46da-11eb-8918-e407430b016b.mp4

**Comment by MaybeNotWrong** [comment] 2020-12-26 02:07
I can reproduce it reliably. I wrote that I clicked "Create Room" several times, that was because I could reproduce it 100% of the time that way. Clicking it just once I could also reproduce the bugged behaviour shown in your video.

Logs seems to be the very similar: 
[runtime.log](https://github.com/ppy/osu/files/5742593/runtime.log)

**Closed** 2021-01-09 08:42 UTC
Labels: area:multiplayer
