### ISSUE TITLE
Beatmap search parameter "played=false" is ignored after exiting a map

### ISSUE THREAD

**Issue by imvanni** [ppy/osu#31165] opened 2024-12-16 21:32 UTC
### Type

Cosmetic

### Bug description

When searching local beatmaps with the `played=false` param, load any map then exit.
After exiting, beatmaps are searched again using the same parameters except for `played=false` - maps played also show up again.

Clearly solvable by just tapping space or modifying the search box, but it's still not the expected behavior.

### Screenshots or videos

https://github.com/user-attachments/assets/10d5f1c3-f879-4bf4-9fd6-9e639143bd2d

### Version

2024.1208.0

### Logs

[logs.zip](https://github.com/user-attachments/files/18157307/logs.zip)

**Comment by imvanni** [comment] 2024-12-16 21:41
wait, this was supposed to take a number instead of boolean?
![image](https://github.com/user-attachments/assets/dff15207-9e90-45ba-a430-b4030f0e88a0)

does it matter, then?

**Comment by Joehuu** [comment] 2024-12-16 21:58
Duplicate of https://github.com/ppy/osu/issues/29751

**Closed by Joehuu** 2024-12-16 21:58 UTC
