### ISSUE TITLE
Language changing via WIN+Space hotkey causes issue with input detection.

### ISSUE THREAD

**Issue by SuperNeon4ik** [ppy/osu#12613] opened 2021-04-28 16:41 UTC
**Describe the bug:** 
The game thinks that I am still holding WIN button after switching the language using WIN+Space on Win 10. 
It may be why I can't type after I change my language.
If you wonder, if I have Z bind (not LWIN+Z) and I change languages, then my Z bind won't work.

**Screenshots or videos showing encountered issue:** [Screen Recording](https://user-images.githubusercontent.com/52915540/116439773-95dfe980-a858-11eb-9c0b-1b4e50b61c4a.mp4)
I play fullscreen 1600x900, that's why I have my game in the corner on the recording. First black screen (in game settings) turns when I am changing language Win+Space. Second time I am Alt+TAB'ing and then it is fixed.

**osu!lazer version:** 2021.424.0 at Windows 10

**Logs:** [logs.zip](https://github.com/ppy/osu/files/6393378/logs.zip)

**Comment by Game4all** [comment] 2021-04-28 16:50
Dupe of / similar to #9834

**Comment by frenzibyte** [comment] 2021-04-28 16:53
Let's close it as a duplicate for now.

**Closed by frenzibyte** 2021-04-28 16:53 UTC
