### ISSUE TITLE
Sudden crash during multiplayer

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#11304] opened 2020-12-25 07:57 UTC
**Describe the crash:** Playing in a multiplayer lobby, suddenly crashed.

**Screenshots or videos showing encountered issue:** Didn't catch it, not sure how to replicate it.

**osu!lazer version:** 2020.1225.0.0

**Logs:** [logs.zip](https://github.com/ppy/osu/files/5741455/logs.zip)

**Computer Specifications:** AMD Ryzen 5 3600, 16.0 GB RAM, GeForce RTX 3070

**Comment by frenzibyte** [comment] 2020-12-25 08:03
Duplicate of #11302, investigating that.

**Closed** 2020-12-25 08:43 UTC
