### ISSUE TITLE
Brief visual "MISS" judgement bug while rewind the replay.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#22445] opened 2023-01-28 09:39 UTC
### Type

Cosmetic

### Bug description

Brief visual "MISS" judgement bug if rewind the replay. If you rewind the replay, the MISS judgement immediately show up exactly when slider head start. These only effects a few seconds after rewind.

### Screenshots or videos

https://user-images.githubusercontent.com/7066150/215259451-623dd368-2683-4227-8580-3451c2f244cc.mp4

### Version

2023.123.0

### Logs

[updater.log](https://github.com/ppy/osu/files/10526885/updater.log)
[database.log](https://github.com/ppy/osu/files/10526886/database.log)
[input.log](https://github.com/ppy/osu/files/10526887/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10526888/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10526889/network.log)
[performance.log](https://github.com/ppy/osu/files/10526890/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10526891/runtime.log)

**Comment by bdach** [comment] 2023-01-28 10:29
Duplicate of #17413

**Closed by bdach** 2023-01-28 10:29 UTC
