### ISSUE TITLE
Cannot input spaces when filtering beatmap collections if 'Select' key is mapped to 'Space'

### ISSUE THREAD

**Issue by 3047256** [ppy/osu#26025] opened 2023-12-21 23:41 UTC
### Type

Game behaviour

### Bug description

`Space` is one of the default key bindings for `GlobalAction.Select`:  
https://github.com/ppy/osu/blob/master/osu.Game/Input/Bindings/GlobalActionContainer.cs#L91

If a beatmap is selected, even when the beatmap collection filter is focused, any spaces entered will be overriden by the the select action in song select.

### Screenshots or videos

https://github.com/ppy/osu/assets/154562391/513418da-913b-40c5-98e9-3912e10924ae

### Version

2023.1222.0-lazer

### Logs

-

**Comment by smoogipoo** [comment] 2023-12-22 04:14
That is shocking.

**Comment by peppy** [comment] 2023-12-22 04:40
@frenzibyte another case of nested input manager going wrong

**Comment by frenzibyte** [comment] 2023-12-22 10:40
Duplicate of https://github.com/ppy/osu/issues/25769

**Closed by frenzibyte** 2023-12-22 10:40 UTC
Labels: type:input, area:main-menu, priority:1
