### ISSUE TITLE
Can't download replay after once you deleted it

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu#14680] opened 2021-09-08 11:30 UTC
https://user-images.githubusercontent.com/86934170/132501696-b12edb36-94ef-457a-a97a-c4a58b57ff00.mp4

**Comment by peppy** [comment] 2021-09-08 11:34
Duplicate of https://github.com/ppy/osu/issues/14574

**Closed by peppy** 2021-09-08 11:34 UTC
