### ISSUE TITLE
Searching drops performance on a big library of songs

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu#21958] opened 2022-12-30 21:34 UTC
### Type

Performance

### Bug description

I imported my entire library today (~100GB) and I'm encountering some performance issues while searching for beatmaps. 

Most notably:
- Letters in the search box appear after a long delay, similar to when you are dropping frames.
- The ui becomes quite non-reactive while searching

This is **not** a pc hardware issue, since this is not what I am experiencing in stable(+wine) and I'm running on a NVMe drive + Ryzen 5 3500x.
You can see a big freeze in the video below.

### Screenshots or videos

https://user-images.githubusercontent.com/31241607/210113031-9f1dd735-eac7-414e-b150-f80491a1e9fb.mp4

### Version

2022.1228.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10326328/database.log)
[input.log](https://github.com/ppy/osu/files/10326329/input.log)
[network.log](https://github.com/ppy/osu/files/10326330/network.log)
[performance.log](https://github.com/ppy/osu/files/10326331/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10326332/runtime.log)

**Comment by Joehuu** [comment] 2022-12-30 21:38
Duplicate of https://github.com/ppy/osu/issues/11571

**Closed by Joehuu** 2022-12-30 21:38 UTC
