### ISSUE TITLE
Bug report (screen bug)

### ISSUE THREAD

**Issue by lordespectro** [ppy/osu#9828] opened 2020-08-11 00:37 UTC
When i use borderless or fullscreen and i use alt+tab the screen goes bug when i back to osu!.
Ubuntu 20.04.1 LTS

Screenshot
![Screenshot from 2020-08-10 21-03-36](https://user-images.githubusercontent.com/69489534/89843983-8eed3b80-db50-11ea-8816-a91ea1e7cf35.png)
![Screenshot from 2020-08-10 21-30-48](https://user-images.githubusercontent.com/69489534/89844045-c52abb00-db50-11ea-8208-bd4633a5b3ef.png)

osu!lazer version 2020.806.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5054126/database.log)
[network.log](https://github.com/ppy/osu/files/5054127/network.log)
[performance.log](https://github.com/ppy/osu/files/5054128/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5054129/runtime.log)

**Comment by smoogipoo** [comment] 2020-08-11 00:51
Please try running osu! with `--sdl`.

**Comment by bdach** [comment] 2020-08-11 17:14
Duplicate of #8049 / #7141 (I thought I've seen something like this before...)

**Closed by bdach** 2020-08-11 17:14 UTC
Labels: framework-fix-required, platform:linux
