### ISSUE TITLE
Using Shift+Backspace doesn't delete characters.

### ISSUE THREAD

**Issue by DentsHub** [ppy/osu#2535] opened 2018-05-13 21:15 UTC

**Comment by peppy** [comment] 2018-05-14 01:08
Which platform are you on, and what is the behaviour you expect for this?

**Comment by tomdenty1** [comment] 2018-05-14 16:27
Windows 10, pretty much globally in anywhere where you can input text, holding down shift while trying to delete characters with backspace doesn't let you delete text

**Comment by swoolcock** [comment] 2018-05-15 03:26
Text manipulation is handled by `PlatformAction`s, and there is no action registered for Shift+Backspace.  Manually adding one is a possibility, but it seems more like a bandaid solution.  It would have to be done for macOS too, since that overrides the `PlatformAction` registration.

**Comment by Joehuu** [comment] 2019-10-13 16:53
The similar/modern issue (https://github.com/ppy/osu/issues/5180) was fixed in https://github.com/ppy/osu/pull/5372.

https://github.com/ppy/osu/issues/5180 was a regression, so it was fixed somewhere before. Going to close anyway as it was resolved.

**Closed by Joehuu** 2019-10-13 16:53 UTC
Labels: input, missing details
