### ISSUE TITLE
osu! Linux AppImage hangs straight after "This is an early development build" screen

### ISSUE THREAD

**Issue by lbrame** [ppy/osu#7959] opened 2020-02-22 14:56 UTC
**Describe the crash:** 
The game seems to open correctly, but it freezes right after showing the "development build" splash screen. No terminal output is shown. The window is also unresponsive to the close command, it's necessary to `kill` the frozen game.

**Screenshots or videos showing encountered issue:** 

[simplescreenrecorder-2020-02-22_15.44.59.zip](https://github.com/ppy/osu/files/4239468/simplescreenrecorder-2020-02-22_15.44.59.zip)

![Screenshot_20200222_154651](https://user-images.githubusercontent.com/45152996/75094353-8ac16780-558a-11ea-9f1c-399cb08abaa7.png)

**osu!lazer version:** 
2020.221.1

**Logs:** 
No terminal output, no logs written to journal or to file.

**Computer Specifications:** 
CPU: Intel i5 7200-U (dual core)
GPU: Intel HD Graphics 620
Memory: 8 GB
Display resolution: 1920x1080
OS: Arch Linux
Kernel version:  5.5.5-arch1-1

**Comment by jai-x** [comment] 2020-02-22 15:08
There should definitely be log files if the game window launches.
Have you checked the logfile location at `~/.local/share/osu!` ?

**Comment by bdach** [comment] 2020-02-22 15:08
Do you have ffmpeg installed? If yes, which version?

**Comment by lbrame** [comment] 2020-02-22 16:29
Sorry - I didn't notice osu was putting logs in that folder.

As for `ffmpeg` - yep, I have it installed, version n4.2.2.

As for the logs - here are all the logs that I found in `~/.local/share/osu`

[database.log](https://github.com/ppy/osu/files/4239595/database.log)
[network.log](https://github.com/ppy/osu/files/4239596/network.log)
[performance.log](https://github.com/ppy/osu/files/4239597/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4239599/runtime.log)

**Comment by bdach** [comment] 2020-02-22 16:34
Logs look clean, no stack trace in sight, but the GL shader version looks a bit on the low side (reported as 1.30). I'm assuming it might be a tad too low for what lazer requires. Mind having a look at `dmesg` and checking if there aren't any segfaults or interesting messages there?

**Comment by lbrame** [comment] 2020-02-22 17:47
I've inspected my `dmesg` and I haven't found anything weird.

I have also tried loading the game both with [https://wiki.archlinux.org/index.php/Intel_graphics#Enable_GuC_/_HuC_firmware_loading](HuC / GuC) early loading enabled (tainted kernel) and disabled (untainted kernel). It doesn't seem to make a difference.

This is my dmesg loading newest GPU firmware with HuC / GuC:
[dmesg_tainted.txt](https://github.com/ppy/osu/files/4239694/dmesg_tainted.txt)

This is my dmesg loading the untainted kernel:
[dmesg_clean.txt](https://github.com/ppy/osu/files/4239699/dmesg_clean.txt)

Additionally, I'm using kernel modesetting drivers for Intel, which are the new default recommended by most distros.

I have deleted the osu folder and tried launching the game again while loading an untainted kernel, so I have new logs. Diffing them with the old ones, they seem to be different:

[database.log](https://github.com/ppy/osu/files/4239703/database.log)
[network.log](https://github.com/ppy/osu/files/4239704/network.log)
[performance.log](https://github.com/ppy/osu/files/4239705/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4239706/runtime.log)

**Comment by bdach** [comment] 2020-02-22 18:01
Still nothing useful to go on... Logs are different, but as far as I can tell, not meaningfully (a couple of different longer loads). No changes in runtime logs still, where I'd expect the most pertinent info.

Mind pasting the output of `glxinfo`? If we glean nothing from it then I'm afraid you might have to dig in on your own as to what's wrong, since it seems hardware-/environment-related.

**Comment by lbrame** [comment] 2020-02-22 18:05
Sure! Here are the outputs of `glxinfo` and `glinfo`:

[glxinfo.txt](https://github.com/ppy/osu/files/4239730/glxinfo.txt)
[glinfo.txt](https://github.com/ppy/osu/files/4239731/glinfo.txt)

**Comment by bdach** [comment] 2020-02-22 18:16
It all looks fine. On second thought the graphics investigation might have been a red herring, as the opengl versions themselves look fine, it's just the driver version that was low - and driver version seem to be vendor-specific which I didn't realise until now.

Upon comparing your `runtime.log` with an actually-loading one the BASS initialisation header jumped out to me. I'm thinking this could be an audio issue - mind changing `IntroSequence=Triangles` to `IntroSequence=Circles` in `~/.local/share/osu/game.ini` and checking if the game starts? If it does, that confirms audio and you might have to tinker with your alsa settings (maybe something from #7672 might help?)

**Comment by kindlyfire** [comment] 2020-02-22 18:42
I had a crash on startup as well, although some things rendered. It got as for as to say "welcome to osu", then after some short animations it crashed with the following output: [gist](https://gist.github.com/kindlyfire/44078a7249e890fc92e811f4e4137941).

Changing `IntroSequence = Triangles` to `IntroSequence = Circles` fixes the error on startup, but Osu still crashes when starting a map. This is the second error: [gist](https://gist.github.com/kindlyfire/0aa51ef1ed09e3935acf82c6c96adbb8)

**Comment by bdach** [comment] 2020-02-22 18:50
@kindlyfire Your issue is different and not related to audio, but to video, ffmpeg in particular. See: #7947, #7963.

**Comment by lbrame** [comment] 2020-02-22 19:16
It seems to be working just fine with `IntroSequence = Circles!`

The only thing that did not immediately work as audio. But it was sufficient to switch it from "Default" to "PulseAudio Server" to rectify that - and it is unrelated to the issue.

I have tried playing a few beatmaps and playing around with the settings - excluding other known issues, everything works fine as long as the intro sequence is set to circles.

![Screenshot_20200222_194555](https://user-images.githubusercontent.com/45152996/75097522-ed772b00-55ab-11ea-975d-64df60f67ec4.png)

Anyway, here are the new logs.

[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4239806/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4239807/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4239808/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4239809/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4239810/runtime.log)

For some reason, performance.long has gotten too big for GitHub (68 MB big). Let me know if it would still be useful to upload elsewhere.

**Comment by bdach** [comment] 2020-02-22 19:20
Interesting - even after setting the sound device, does `IntroTriangles` still not work? Not something I'd have expected.

I don't suspect this being an issue with the `IntroTriangles` video, however, as it'd crash slightly later in the intro sequence (audio comes first).

**Comment by lbrame** [comment] 2020-02-22 19:23
I have tried again with `IntroSequence = Triangles` on after manually setting the audio device and everything works fine now!

**Comment by bdach** [comment] 2020-02-22 19:24
Great to hear. I'll close this issue for now, but this failure pattern is a recurring theme that needs addressing framework-side. Thanks for the help diagnosing this issue!

**Closed by bdach** 2020-02-22 19:24 UTC
Labels: missing details, platform:linux

**Comment by kevinsmia1939** [comment] 2020-02-23 22:04
I can confirm the issue on openSUSE Tumbleweed.
Changing IntroSequence = Triangles to IntroSequence = Circles solve the problem.

**Comment by mrlinuxfish** [comment] 2020-04-27 23:27
I had to change the IntroSequence = Circles also.
Arch Linux current.
