### ISSUE TITLE
Osu!Lazer bug when Raw Input is turned on.

### ISSUE THREAD

**Issue by ThundahK** [ppy/osu#1646] opened 2017-12-02 06:11 UTC
Okay, so while I tried the new osu!lazer update yesterday, I turned on Raw Input (because I am on Windows 10 and tablet area is already shrunk to minimum but whatever) and as soon as I hovered my pen to the tablet, parallax and cursor disappeared. Then I tried to move the mouse, and realized the parallax image is coming back from the bottom right corner, but the cursor could only be fixed with a restart of the program.
I tried it today and the parallax issue was fixed, but another one showed up. It is just my cursor freaking out when raw input is on (not sure if this is just for me) but it wasn't freaking out in a normal way, it just looked like I rolled my pen on the tablet (going to random places).

**Comment by Nightfirecat** [comment] 2017-12-02 08:33
Duplicate of #1301.

**Closed** 2017-12-02 09:14 UTC
