### ISSUE TITLE
Manipulating time using the song progress skin element in osu!catch editor test mode can sometimes freeze its autoplay and can end the test mode earlier than expected

### ISSUE THREAD

**Issue by snalgae** [ppy/osu#30990] opened 2024-12-06 20:44 UTC
### Type

Game behaviour

### Bug description

While investigating whether autoplay (is it even called that in the editor?) in the test mode (hitting the `tab` kry) also missed the fruit mentioned in #30989, to find the right place I had to use the song progress line that was on my skin. After which I saw autoplay freeze up and to "reactivate" it I had to press `tab` twice or scroll forward in time. But it doesn't freeze every time? I know it freezes up if I scroll _back_ in time, but that doesn't happen always, I'm not sure what is the pattern. After making attempts to record it, I also found that the test mode may end prematurely after I scrolled around the map, especially if I touch the later parts of the beatmap.

The issue is reproducible on different beatmaps too

### Screenshots or videos

I have trouble checking whether this video is loaded, so I made a youtube link as well

https://github.com/user-attachments/assets/0d29c606-2aaf-4554-85dd-d66eaf78efc3

https://youtu.be/rlqWnFDDKLo

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18043519/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-12-06 22:36
Duplicate of https://github.com/ppy/osu/issues/30107 / https://github.com/ppy/osu/issues/30177

**Closed by Joehuu** 2024-12-06 22:36 UTC
