### ISSUE TITLE
Wiki article code block text isn't aligned correctly

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#13422] opened 2021-06-09 19:43 UTC
page: Gameplay > Score

**Screenshots or videos showing encountered issue:** 
osu! web:
![chrome_yVCMxlZijV](https://user-images.githubusercontent.com/43358824/121418384-30a90900-c96b-11eb-838b-133537e3886e.png)

osu! lazer:
![osu!_IUZXaIsmcy](https://user-images.githubusercontent.com/43358824/121418396-34d52680-c96b-11eb-9e39-dcfa43f4a4c1.png)

**osu!lazer version:** 
commit aed490803fd6d9da10db184bc14c1fd382588266

**Comment by bdach** [comment] 2021-06-09 19:56
Duplicate of / shall hopefully be resolved via #13270.

**Closed by bdach** 2021-06-09 19:56 UTC
