### ISSUE TITLE
Osu! Crashes on Android while on multi threaded mode.

### ISSUE THREAD

**Issue by cheeezie** [ppy/osu#18019] opened 2022-04-29 08:22 UTC
### Type

Crash to desktop

### Bug description

Information: Phone: OnePlus 8T / OS: Android 12 Build: KB2003_11_C.16 / osu! version: 2022.424.1 (the issue was present in older versions of osu! dating back to march of this year.)

The game crashes when threading is set to multi instead of single, happens when the app is being switched to another or minimized without killing the task. Battery optimizations is disabled for the game as well as batter saver mode.

### Screenshots or videos

https://user-images.githubusercontent.com/102518950/165908591-82a83ec6-7da8-483a-a681-b6f9a7f3faca.mp4

### Version

2022.424.1 Android Build

### Logs

[logs.zip](https://github.com/ppy/osu/files/8589254/logs.zip)

**Comment by bdach** [comment] 2022-04-29 19:43
duplicate of https://github.com/ppy/osu-framework/issues/4994

**Closed by bdach** 2022-04-29 19:43 UTC
