### ISSUE TITLE
When audio is set to mute, specific audio samples are still occasionally played

### ISSUE THREAD

**Issue by Frontear** [ppy/osu#2286] opened 2018-03-22 20:19 UTC
Best method to reproduce:

- Mute volume (master and all other volume types be set to 100% to audibly hear sample)
- Hover over one of the menu options (settings, play, editor)
- A somewhat knock sound should be heard

Video: https://streamable.com/oi2f1

**Comment by FreezyLemon** [comment] 2018-03-22 20:53
Can't reproduce. You meant muting as in Ctrl-F4 (hitting the mute toggle on the overlay)?

**Comment by peppy** [comment] 2018-03-24 05:59
This has always been an issue with bass. I believe we need to look into a better way of muting, as just setting volume to zero doesn't seem to be enough.

**Comment by iiSaLMaN** [comment] 2019-09-25 22:13
> This has always been an issue with bass. I believe we need to look into a better way of muting, as just setting volume to zero doesn't seem to be enough.

Setting Frequency of the samples to 0hz can be used as a temporary fix once ppy/osu-framework#2808 is merged as it maintains an internal pause inside the sample which should not result in any playback.

**Comment by frenzibyte** [comment] 2020-05-20 21:02
Looking into this again I think this can be resolved by also maintaining an internal pause inside the bass-specific sample class (in the same way https://github.com/ppy/osu-framework/pull/2808 is doing), will check if that works when I have the time for it.

**Comment by peppy** [comment] 2020-05-20 23:43
Are you sure this is actually still an issue? We have since updated bass and solved similar issues that were related to bass entering a "standby" driver mode which would potentially cause a click on resume.

**Comment by peppy** [comment] 2020-10-07 11:47
Closing this as I believe it has been resolved via a bass update.

We also don't play samples with zero volume any more.

**Closed by peppy** 2020-10-07 11:47 UTC
Labels: type:audio
