### ISSUE TITLE
Changing the BeatmapDirectory in stable causes osu!lazer to not detect an install and fail to import skins or maps

### ISSUE THREAD

**Issue by vladfrangu** [ppy/osu#8295] opened 2020-03-16 17:47 UTC
**Describe the bug:** 

This might have been reported before, or is an extension of an issue, and if so, feel free to close this issue! 😅 

My stable install location is the default (`%LocalAppData%/osu!`), however, I edited my `osu!.<USERNAME>.cfg`'s `BeatmapDirectory` to a different path (in this case `D:\osu!\Songs` since it has more space than my SSD)
This change causes osu!lazer to be unable to detect the install or import anything, be it skins or maps. I can understand why it may not be able to import maps (from reading a couple of other issues) but skins make no sense, as they are in the same `Skins` folder as the stable executable. Reverting the change makes the game detect the install and import correctly

**EDIT**: It WAS, however, able to import scores with the config file changed, although, of course, throwing errors due to missing beatmaps.

**Screenshots or videos showing encountered issue:** None

**osu!lazer version:** 2020.312.0.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/4339580/runtime.log)

**Comment by smoogipoo** [comment] 2020-03-18 02:27
Custom locations aren't supported yet. This is covered / a duplicate of https://github.com/ppy/osu/issues/3763 .

**Closed by smoogipoo** 2020-03-18 02:27 UTC
Labels: area:database
