### ISSUE TITLE
Sprites are corrupted in new update but works fine in older versions

### ISSUE THREAD

**Issue by KevRub** [ppy/osu#6183] opened 2019-09-19 22:39 UTC
**Describe the bug:** hit circles are invisible and all png files have a black box

**Screenshots or videos showing encountered issue:** 
![Screenshot (89)](https://user-images.githubusercontent.com/55562794/65286202-b2f4f800-db0c-11e9-8bdf-6bfb4ffa1048.png)

**osu!lazer version:** 
latest version
**Logs:**

**Comment by iiSaLMaN** [comment] 2019-09-19 22:42
Can you please inform us of your GPU? which version was the latest working? also does this affect the main menu and song select?

**Comment by smoogipoo** [comment] 2019-09-20 04:38
Duplicate of https://github.com/ppy/osu/issues/5199 (yes please provide system info).

**Closed by smoogipoo** 2019-09-20 04:38 UTC

**Comment by KevRub** [comment] 2019-09-20 12:22
I use the dell inspiron plug and play running windows 8.1
