### ISSUE TITLE
Significant stutter caused by long slider

### ISSUE THREAD

**Issue by mdkt** [ppy/osu#13659] opened 2021-06-25 09:25 UTC
**Describe the bug:** 
This might just be a weird edge case but osu-stable doesn't seem to have this issue. Loading a long slider causes a stutter both during gameplay and in the editor.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/51028359/123401949-ed2bdd00-d5af-11eb-913e-fd3fb4673ed8.mp4

**osu!lazer version:**  2021.623.0

**Comment by ekrctb** [comment] 2021-06-25 09:36
Probably the root cause is same as #12659 (nested hit objects are loaded at once).

**Comment by peppy** [comment] 2021-06-25 09:43
I think it's safe to close this as a duplicate.

**Closed by peppy** 2021-06-25 09:43 UTC
