### ISSUE TITLE
Releasing LN doesn't count as a miss if you double tap it in osu!mania

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#18275] opened 2022-05-15 10:10 UTC
### Type

Game behaviour

### Bug description

Hi, here is a bug caused by the new LN system : If you double tap the LN, it doesn't count as a miss. 

As you can see on the video, i can double tap a lot of time without any miss. I don't know if it's intended or not, but this is one of the other osu!mania breaking gameplay change. Is there any way to make it miss again with the new LN system ? 

### Screenshots or videos

https://user-images.githubusercontent.com/31996023/168467517-553b79e8-5416-4576-a94c-cd3c0cc36177.mp4

### Version

2022.515.0

### Logs

[database.log](https://github.com/ppy/osu/files/8694704/database.log)
[network.log](https://github.com/ppy/osu/files/8694705/network.log)
[performance.log](https://github.com/ppy/osu/files/8694706/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8694707/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8694708/updater.log)

**Comment by bdach** [comment] 2022-05-15 12:41
Duplicate of #8744, I'm pretty sure.

**Closed by bdach** 2022-05-15 12:41 UTC
