### ISSUE TITLE
Actions that advance past last received frame in spectate mode should be blocked

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#11173] opened 2020-12-14 15:08 UTC
as going full 2.0 rate after some time creates strange glitches

**osu!lazer version:** 
2020.1212.0

**Comment by bdach** [comment] 2020-12-14 15:59
Expanding this to cover all actions that can potentially attempt to advance the clock past the last received frame.

**Comment by peppy** [comment] 2020-12-15 02:56
What does "full 2.0 rate" mean here? Attempting to watch the replay at double speed? Is this same behaviour seen when seeking beyond the received data?

Could you clarify what the "strange glitches" are?

**Comment by frenzibyte** [comment] 2021-08-28 19:52
Duplicate of #14502

**Closed by frenzibyte** 2021-08-28 19:52 UTC
Labels: area:spectator
