### ISSUE TITLE
Missing elements with custom skin.ini location should fall back to skin folder root first instead of default lazer skin (legacy skinning)

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#12130] opened 2021-03-21 15:59 UTC
This issue might seem similar to #8019 and #12086, but this issue covers a different part of skin element fallbacks. 

Currently, lazer searches for skin elements in this order for legacy skins: `skin.ini custom location > default lazer skin`. 
It would be better if the order was like this: `skin.ini custom location > skin folder root (this issue) > default classic skin` (#8019). 

This is the same behaviour as stable, which results in better compatibility with some poorly configured legacy skins. 
This fixes skins that specify a custom location for a skin element in skin.ini while it is not in fact there, and expect osu! to look for it in the root folder instead.

version: 2021.320.0

**Comment by bdach** [comment] 2021-03-21 16:01
Seems like a duplicate of #9863

**Closed by bdach** 2021-03-21 16:01 UTC
