### ISSUE TITLE
The "featured artists" filter in beatmap listing overlay is still not quite clear for first-time user

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#24976] opened 2023-09-30 19:26 UTC
### Type

Game behaviour

### Bug description

This happened to me a handful of times after not launching osu!(lazer) for a short period of time, and has also just been [encountered by a user](https://discord.com/channels/188630481301012481/1097318920991559880/1157753736513474691) recently. Opening this issue thread to raise a bit of discussion before osu!(lazer) becomes ranked and many stable players switch to lazer (not sure if it deserves being included in the project though).

Part of this confusion likely rises from the fact that the osu! website does not enable the "featured artists" filter in beatmap listing by default. But I'm not sure if the website will have it enabled by default any time soon.

I'm not sure how much of noting is acceptable, but would maybe adding a line strip at the top of the search results stating that this is searching for beatmaps with the "featured artist" filter enabled? Or at the very least, maybe bring the filter to the right side of the search bar in some shape or form, e.g.:

<img width="1005" alt="CleanShot 2023-09-30 at 22 21 22@2x" src="https://github.com/ppy/osu/assets/22781491/36da2269-d8a8-46f5-adb8-8a87b5510006">

cc @ppy/team-client

### Version

-

### Logs

-

**Comment by Joehuu** [comment] 2023-09-30 21:36
Duplicate of https://github.com/ppy/osu/issues/22009

**Closed by Joehuu** 2023-09-30 21:36 UTC
Labels: type:behavioural, area:overlay-beatmap-listing
