### ISSUE TITLE
Beatmaps with spurious Update indicators

### ISSUE THREAD

**Issue by Gyoshi** [ppy/osu#23498] opened 2023-05-12 03:02 UTC
### Type

Other

### Bug description

I have 2 beatmaps that show an Update indicator despite not needing an update. The indicator does not go away after clicking and updating the maps. 
These are:
- https://osu.ppy.sh/beatmapsets/370819#osu/831724
- https://osu.ppy.sh/beatmapsets/5213#osu/26179

Deleting the maps and redownloading does not fix the issue.

Note that these beatmaps have not received any updates since I downloaded them in the past few days. They had "Update" indicators from the start.

### Screenshots or videos

https://github.com/ppy/osu/assets/41743877/5d93da8a-1121-4da8-bc99-aeaee1b26f32

### Version

2023.511.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11458490/database.log)
[input.log](https://github.com/ppy/osu/files/11458491/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11458492/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11458493/network.log)
[performance.log](https://github.com/ppy/osu/files/11458494/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11458495/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11458496/updater.log)

**Comment by Joehuu** [comment] 2023-05-12 05:13
Duplicate of https://github.com/ppy/osu/issues/22148

**Closed by Joehuu** 2023-05-12 05:13 UTC
Labels: area:beatmap-change-tracking
