### ISSUE TITLE
Scrollbar goes behind the searchbar on songselect

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2865] opened 2018-06-22 23:58 UTC
Does Happen when a map when a map has to many diffs
![ss 2018-06-23 at 01 56 08](https://user-images.githubusercontent.com/17437302/41803406-c93da6aa-7688-11e8-8b7d-238f2cd525b2.jpg)

**Comment by Joehuu** [comment] 2018-06-23 00:02
Duplicate of #2241.

**Closed** 2018-06-23 00:07 UTC
