### ISSUE TITLE
Custom FPS Limit for G-Sync

### ISSUE THREAD

**Issue by Nyunyun** [ppy/osu#5586] opened 2019-08-03 16:23 UTC
**Describe the new feature:** 
Well, it's easy. 
I (others probably too) just want a custom fps-limit so I could use G-Sync with the in-game fps-limiter, as external limiter introduces 1 (Rivatuner) or 2 (Nvidia-Inspector) frame-latency 
**Proposal designs of the feature:**

**Comment by peppy** [comment] 2020-08-08 14:03
@bdach curious: were you able to confirm this is fixed in sdl with no further changes? very interested in the root cause, because the lack of offering a "custom fps limit" is probably not the main issue here.

**Comment by bdach** [comment] 2020-08-08 14:05
I don't own a display I could test with. I mostly went off information provided by @Joppe27 in the linked issue.

**Comment by Joppe27** [comment] 2020-08-08 17:32
I tested more and this bug is not actually fixed in sdl. This bug occuring seems to be purely luck based in sdl (sometimes sdl works decently, other times it doesn't) whereas on the main build the bug always occurs. Sdl does seem to be a little better than the main build even when the bug does occur, but still not good.

**Comment by peppy** [comment] 2020-08-08 23:58
honestly i'm pretty sure what you are seeing is precisely how gsync works and nothing is wrong here. can you confirm and provide an example of a different game running at the frame draw FPS you are running lazer at gets different results?

**Comment by Joppe27** [comment] 2020-08-09 11:05
> 
> 
> honestly i'm pretty sure what you are seeing is precisely how gsync works and nothing is wrong here. can you confirm and provide an example of a different game running at similar draw FPS you are running lazer at gets different results?

Gsync and osu were indeed working correctly. I found the actual cause of this bug: lazer was running in borderless mode (G-sync supports it) and somehow the window size is not set correctly in borderless mode on lazer, making the app extend 1 pixel off of the main monitor onto my second display (ppy/osu-framework#3456). G-sync only works correctly in windowed/borderless when the application is displayed solely on the main monitor, which is why lazer was acting weird.

**Comment by peppy** [comment] 2020-08-10 04:10
Going to close this one for now. We'll continue investigation on the framework side thread.

**Closed by peppy** 2020-08-10 04:10 UTC
Labels: proposal

**Comment by Nyunyun** [comment] 2020-08-10 15:49
Uh, why did this feature request for a whole another matter get closed for a framework bug?
Me requesting a custom frame-rate limit (or monitor refresh rate*0.98, this would work too) for G-Sync has another background than something not working as intended.

G-Sync works below the maximum refresh rate of the monitor, meaning with 144Hz one would want ~140fps. Having 144fps would disable G-Sync and, if enabled, trigger V-Sync. Adding a huge amount of latency. (It's still recommended to enable NVCP V-Sync, as this, for whatever reason, lowers the frame latency)

While it's doable with an external frame-rate limiter, it would add one or two frames of latency (usually one nowadays, Nvidia pushed an update for  this), thus making G-Sync obsolete.

If there is an option to limit the fps, then sorry as I didn't see it. I didn't see such an option in the config as well (besides "FrameSync",  where I can't do much with), while on the "original" osu I could just change "CustomFrameLimit" to my desired rate.

**As a proposal for how the feature could look like:**
Maybe add an extra option below V-Sync, named "Adaptive Sync" (both G-Sync and FreeSync).
That option can lock the frame-rate to monitor refresh rate*0.98 and disable V-Sync. Maybe even give a dialog box that recommends to enable V-Sync in NVCP for an improved experience (lower latency). AMD doesn't need this, V-Sync in AMD settings doesn't influence the frame-latency, as it's the case with G-Sync.

**Comment by bdach** [comment] 2020-08-10 15:56
You should have explained the proposal better, then, not started with "well, it's easy". Not everyone is intimately familiar with every vendor-specific hardware feature.

The fact that it's vendor-specific is also a reason why I would personally be opposed to such an addition.

**Comment by Nyunyun** [comment] 2020-08-10 16:05
How is it vendor specific, if FreeSync or G-Sync is used in every modern monitor and both work similar, which would make the feature applicable to both AMD and Nvidia? Also I think that my request was pretty obvious about being a request and not a bug report, talking about added latency if I use an external solution.

Both the option which I proposed just now and a customframelimit, as it was included in the old, would work. As people that use adaptive sync generally know how it works and how to use it.
The adaptive sync option would be easier for "common" folk to use, as you don't need to fiddle in config files.

**Comment by peppy** [comment] 2020-08-10 21:48
having to force frame rate to "2% lower than real vsync" is 100% a hardware or driver failure. Or a placebo. It sounds like the kind of setting we should explicitly not offer because users are going to shoot themselves in the foot.

We'll investigate this locally at a point in the future if you open up an issue against osu-framework not asking for a feature, but describing specifically the issue you are seeing, along with documentation that allows us to reproduce and figure a path forward if required from there.
