### ISSUE TITLE
External link dialog overflows if the destination link is very long

### ISSUE THREAD

**Issue by 3stantedja** [ppy/osu#24789] opened 2023-09-12 07:32 UTC
### Type

Cosmetic

### Bug description

Visiting the link on the [pinned comment](https://osu.ppy.sh/comments/2529311) for this beatmap (https://osu.ppy.sh/beatmapsets/1871670) results in the link overflowing out of the dialog instead of wrapping within the dialog. In this case, because the dialog does not dim the beatmap info overlay it also made the destination link somewhat hard to read.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/3055647/e7efc039-e355-4192-a472-2022da16f119)

### Version

2023.908.2

### Logs

[runtime.log](https://github.com/ppy/osu/files/12583579/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12583580/updater.log)
[database.log](https://github.com/ppy/osu/files/12583581/database.log)
[network.log](https://github.com/ppy/osu/files/12583582/network.log)
[performance.log](https://github.com/ppy/osu/files/12583583/performance.log)

**Comment by Joehuu** [comment] 2023-09-12 18:26
Duplicate of https://github.com/ppy/osu/issues/10085

**Closed by Joehuu** 2023-09-12 18:26 UTC
Labels: type:cosmetic, area:overlays
