### ISSUE TITLE
"Hold-to-confirm activation time" should not effect quick retry button ("`")

### ISSUE THREAD

**Issue by tasnimtamim** [ppy/osu#7475] opened 2020-01-08 14:33 UTC
**Describe the bug:** 
If I set the "Hold-to-confirm activation time" to 0ms, it makes Esc press delay to 0ms along with the quick retry button ("`"). This should not happen. I accidentally retried way too much time when my intention was to press Esc. Quick retry should be a exception from "Hold-to-confirm activation time" 
**Screenshots or videos showing encountered issue:** https://streamable.com/dfmaq

**osu!lazer version:** 2020.104.0

**Logs:** Let me know if it's required, which I highly doubt is.

**Comment by iiSaLMaN** [comment] 2020-01-08 14:35
Almost duplicate of https://github.com/ppy/osu/issues/6397, which has been rejected.

**Comment by bdach** [comment] 2020-01-08 15:17
Closing as duplicate of the aforementioned issue.

**Closed by bdach** 2020-01-08 15:17 UTC
