### ISSUE TITLE
Cannot change gamemode on userprofiles

### ISSUE THREAD

**Issue by Finxert** [ppy/osu#8718] opened 2020-04-11 14:33 UTC
**Describe the bug:** 

You can't change the displayed game mode (std, taiko, mania or ctb) when viewing someones profile.

For example if I want to see my mania stats and rank instead of my std stats and rank on my profile in-game I can't switch to another game mode like you would be able to from the browser.

**Screenshots or videos showing encountered issue:** 

![osu_2020-04-11_16-28-58](https://user-images.githubusercontent.com/21173997/79046550-283b2e00-7c01-11ea-9b02-79d0aa2f2dfb.jpg)

As you can see the game mode selection should be in the player info banner.

![1586615531](https://user-images.githubusercontent.com/21173997/79046565-456ffc80-7c01-11ea-9968-2b6de9ae26f2.png)

**osu!lazer version:** 
Latest on arch linux

**Comment by LittleEndu** [comment] 2020-04-11 14:36
Duplicate of #3606

**Closed** 2020-04-11 15:08 UTC
