### ISSUE TITLE
Gameplay cursor should disappear if idle

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu#5474] opened 2019-07-26 06:27 UTC
If the mouse is not being moved by the user, the cursor should disappear. The cursor will reappear when the mouse is no longer idle.

**Comment by peppy** [comment] 2019-07-26 06:41
* during gameplay

**Comment by Joehuu** [comment] 2019-10-29 02:38
Duplicate of https://github.com/ppy/osu/issues/2901

**Closed by Joehuu** 2019-10-29 02:38 UTC
Labels: gameplay, input, user interface
