### ISSUE TITLE
Game crashes everytime when I try to search for someone or a song in osu!direct tab

### ISSUE THREAD

**Issue by Heavlieddor** [ppy/osu#6509] opened 2019-10-14 19:34 UTC
As I said game, game crashes when I try to try to search something. Seems like it happens everytime when all stuff is already loaded and when I type something to the prompt it crashes

I took screenshots of logs. 
![Screenshot_2019-10-14-18-21-23-512_com miui bugreport](https://user-images.githubusercontent.com/56561425/66777846-63ff7000-eeca-11e9-9287-3ea05ec1bb4e.png)
![Screenshot_2019-10-14-18-21-29-929_com miui bugreport](https://user-images.githubusercontent.com/56561425/66777848-64980680-eeca-11e9-9e06-d6f060872ae0.png)
![Screenshot_2019-10-14-18-21-32-852_com miui bugreport](https://user-images.githubusercontent.com/56561425/66777849-64980680-eeca-11e9-9991-fb205792b711.png)

Client version: 2019.1011.0

I play on android. It's pretty old phone: Xiaomi Redmi 3S

**Comment by bdach** [comment] 2019-10-14 19:35
Duplicate of #6264.

**Closed by bdach** 2019-10-14 19:35 UTC
