### ISSUE TITLE
First Person osu

### ISSUE THREAD

**Issue by Gautam-C** [ppy/osu#11332] opened 2020-12-27 04:30 UTC
Essentially the idea of a mod for having osu! act as a training ground for first person shooters. Converting normal osu!standard maps to the first person view. The implementation in McOsu is pretty decent for this, but it would be nice to see it in the future official client. 

Here is a link to some gameplay I found on YouTube of how it's implemented in McOsu. [vid](https://www.youtube.com/watch?v=HBoXyMFGFx0)

**Comment by Joehuu** [comment] 2020-12-27 04:31
Duplicate of https://github.com/ppy/osu/issues/6024

**Closed by Joehuu** 2020-12-27 04:31 UTC
