### ISSUE TITLE
Link text overflows outside of external link warning prompt

### ISSUE THREAD

**Issue by zacwm** [ppy/osu#26232] opened 2023-12-29 16:05 UTC
### Type

Cosmetic

### Bug description

First discovered this with some of the news posts, any link too long will overflow outside of the prompt container.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/17349626/fe35adce-326c-4a7d-9abd-602d62e3b631)

### Version

2023.1229.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13794754/compressed-logs.zip)

**Comment by Gabixel** [comment] 2023-12-29 16:16
Duplicate of #10085

**Closed** 2023-12-29 16:23 UTC
