### ISSUE TITLE
"Auto" profile

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8373] opened 2020-03-20 11:09 UTC
In the results window, you can click on the profile, even if it was autoplay. In this case, an unfilled profile will be displayed.
![osu_2020-03-20_21-05-32](https://user-images.githubusercontent.com/59089206/77158292-c4848000-6aee-11ea-8087-9e6c046017ec.png)
osu!lazer version:
2020.320.1
I think that it’s enough to remove the possibility of opening this profile or insert another page there.

**Comment by GSculerlor** [comment] 2020-03-20 11:10
Duplicate of #8372

**Closed** 2020-03-20 11:10 UTC
