### ISSUE TITLE
strict tracking gives more score than nomod 

### ISSUE THREAD

**Issue by ZythePDX** [ppy/osu#28453] opened 2024-06-12 01:22 UTC
### Type

Game behaviour

### Bug description

I should have clarified that its about classic scoring.
im pretty sure this is not intended gaining more classic score than usual.
just put on strick tracking with any map and you will gain more score than usual, obvious but it only works if the map has sliders.

some examples
without strict tracking
![image](https://github.com/ppy/osu/assets/50603224/77d763e2-bd19-47fb-951f-059f54c07b43)

with strict tracking
![image](https://github.com/ppy/osu/assets/50603224/9e55ffc0-7e85-4fdd-9e56-8e7f49c1db44)

and the worse i've seen it 
without strict tracking
![image](https://github.com/ppy/osu/assets/50603224/c3e79ef1-4110-41f1-b171-4c8e6f617a78)

with strict tracking
![image](https://github.com/ppy/osu/assets/50603224/46b2ebc8-43f1-4ecb-9349-f4f320fba214)

i want to play strict tracking without seeming like im abusing it for score farming

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15796520/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-06-12 01:56
To a degree, this is "intentional" since it's changing the tail judgement to be the same as a normal hit.

**Comment by ZythePDX** [comment] 2024-06-12 03:13
yea i wasn't entirely sure if it was intentional or not, the score gain just seemed alot

**Comment by bdach** [comment] 2024-06-12 04:05
duplicate of #19232

**Closed by bdach** 2024-06-12 04:06 UTC
Labels: ruleset/osu!, area:mods
