### ISSUE TITLE
Opening skin editor in gameplay (not replay/autoplay) with a protected skin results in a dead lock

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu#25204] opened 2023-10-22 00:41 UTC
### Type

Crash to desktop

### Bug description

Regressed in https://github.com/ppy/osu/pull/22094.

Currently, when entering a gameplay session, all realm importers are paused. If the selected skin is protected, the skin editor will have to create a copy of the skin and import it to the database, but it cannot proceed because the importers are paused, therefore a deadlock occurs.

```
[runtime] 2023-10-22 00:28:35 [debug]: Pressed (HoldForHUD) handled by HUDOverlay.
[runtime] 2023-10-22 00:28:35 [debug]: KeyDownEvent(ControlLeft, False) handled by GlobalActionContainer.
[runtime] 2023-10-22 00:28:35 [debug]: Pressed (ToggleSkinEditor) handled by GlobalActionContainer.
[runtime] 2023-10-22 00:28:35 [debug]: KeyDownEvent(S, False) handled by GlobalActionContainer.
[runtime] 2023-10-22 00:28:35 [verbose]: SkinImporter is being paused.
```

![](https://cdn.discordapp.com/attachments/188630652340404224/1165447175401132174/CleanShot_2023-10-22_at_03.30.49.png?ex=6546e243&is=65346d43&hm=7be300595d0e4f0a881e69b64a5eea3c333fec6721681d338a4cd1fc37f2a9a6&)

Simplest solution I can think of would be to disable entering skin editor when in an actual gameplay session, as opposed to replays/autoplay.

cc @ppy/team-client 

### Version

57bc0a333fcd25f1a7e8d80a5d58a40f83a2350d

### Logs

-

**Comment by DarkbitNetwork** [comment] 2023-10-22 05:27
Duplicate of #22486 ?

**Closed** 2023-10-22 07:00 UTC
Labels: priority:0, area:gameplay, area:skin-editor
