### ISSUE TITLE
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue

### ISSUE THREAD

**Issue by DecoyIV** [ppy/osu#2014] opened 2018-02-02 22:26 UTC
Played a beatmap and failed, hit the retry button and this happend

![e59ed15f92ab0b778f26ee070aef36a2](https://user-images.githubusercontent.com/36089309/35757663-35bf4914-083e-11e8-966a-aae1cf6f4449.png)

**Comment by LittleEndu** [comment] 2018-04-18 17:36
Close in favour of #2158 ?

**Comment by peppy** [comment] 2018-05-24 07:43
Duplicate of #2158

**Closed by peppy** 2018-05-24 07:43 UTC
Labels: gameplay, input
