### ISSUE TITLE
When clicking on the X in the taskbar to close lazer (while lazer is minimized) it just opens the "do you really want to quit" dialog inside lazer

### ISSUE THREAD

**Issue by Smorty100** [ppy/osu#14550] opened 2021-08-28 15:39 UTC
Long title I know. So yeah, when lazer is minimized, and one clicks on the x in the taskbar to close lazer, it does nothing at first glanze. Then when one opens lazer manually then it shows that do you really wanna quit dialog. It would be better, if the click on the x would instantly close lazer.

**Comment by peppy** [comment] 2021-08-28 15:42
Exit confirmation will eventually only be presented when an ongoing operation requires confirmation. In such cases, the window should probably un-minimise to show the confirm dialog as well.

**Comment by bdach** [comment] 2021-08-28 15:57
The above is tracked at #3952.

Closing as duplicate of #10879 / #6506.

**Closed by bdach** 2021-08-28 15:57 UTC
Labels: type:UX
