### ISSUE TITLE
osu!mania doesn't convert SVs like stable does

### ISSUE THREAD

**Issue by yuuiko** [ppy/osu#5830] opened 2019-08-25 11:22 UTC
**Describe the bug:** 
Not sure if this is #2169 or not, but SVs in osu mode are always converted into the scroll speed in lazer mania. In stable this is not the case.

**osu!lazer version:** 
2019.823.0

**Comment by smoogipoo** [comment] 2019-08-26 07:36
Seems to be a duplicate of https://github.com/ppy/osu/issues/5802

**Closed** 2019-08-26 08:24 UTC
