### ISSUE TITLE
Random stutters throughout the game

### ISSUE THREAD

**Issue by LeaPhant** [ppy/osu#12155] opened 2021-03-23 11:24 UTC
**Describe the bug:** 

Occasional stuttering in song selection screen when clicking maps and stuttering during gameplay at random times with varying intensity. Tried with different (or no) frame limiter, single-/multithreading, online/offline, with a few and with many maps - no change. Playing on Manjaro Linux.

**Screenshots or videos showing encountered issue:** 

https://streamable.com/rqmlk7

**osu!lazer version:** 

Both latest master (https://github.com/ppy/osu/commit/ade542191aa1eb0e97a81b12847c97d65dba1694) and 2021.320.0 release affected.

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6189108/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6189109/performance.log)
[database.log](https://github.com/ppy/osu/files/6189110/database.log)
[network.log](https://github.com/ppy/osu/files/6189113/network.log)

**Comment by smoogipoo** [comment] 2021-03-23 11:26
https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+stutter Please search before posting. Duplicate of https://github.com/ppy/osu/issues/11800

**Closed by smoogipoo** 2021-03-23 11:26 UTC
