### ISSUE TITLE
Cursor position doesn't update on "mouse-down" event using a tablet PC

### ISSUE THREAD

**Issue by GRA0007** [ppy/osu#6919] opened 2019-11-23 07:11 UTC
**Describe the bug:** 
When using a tablet PC (Windows 10) and the touchscreen, tapping and dragging work, but the cursor position on the screen is not updated until lifting the finger or moving the finger across the screen.
The cursor position should update as soon as the finger is pressed onto the screen (i.e. the mousedown event, as opposed to the mouseup event).

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/file/d/1IKN10H8m-ILXybifa0W1keX3qhRsoC9w/view?usp=sharing

**osu!lazer version:** 
2019.1122.0

**Comment by bdach** [comment] 2019-11-23 08:09
Duplicate of ppy/osu-framework#1514.

**Closed by bdach** 2019-11-23 08:09 UTC
