### ISSUE TITLE
osu!lazer stuck on black screen but doesn't crash after start

### ISSUE THREAD

**Issue by DanielSvindseth** [ppy/osu#11927] opened 2021-02-28 21:28 UTC
**Describe the bug:** 
When starting osu!lazer, the starting animation runs fine, but the osu! logo and everything else never starts. There is no music, no UI and keypresses don't work. The fps meter in the bottom right does update like normal. The game never crashes or freezes and can be in this state indefinitely.

I am running Manjaro Linux and Arch Linux (both affected)

**Screenshots or videos showing encountered issue:** 
![Screenshot from 2021-02-28 22-15-58](https://user-images.githubusercontent.com/15878879/109433806-94d63b80-7a12-11eb-880a-c4aac19412ab.png)

![Screenshot from 2021-02-28 22-11-06](https://user-images.githubusercontent.com/15878879/109433733-4163ed80-7a12-11eb-857b-8a503aee4229.png)

**osu!lazer version:** 
2021.226.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6057992/database.log)
[network.log](https://github.com/ppy/osu/files/6057993/network.log)
[performance.log](https://github.com/ppy/osu/files/6057994/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6057995/runtime.log)

**Comment by jai-x** [comment] 2021-02-28 21:32
From your `runtime.log` file:
```
2021-02-28 21:15:53 [verbose]: Connected MIDI device: Midi Through Port-0
```

It seems that osu!lazer has connected to a MIDI device at startup and as such is unable to play the intro track through this device and has stalled as a result.

I would try and ensure this device is not connected at startup and/or ensure that your system audio is configured correctly such that the MIDI device is not the first/default device available.

**Comment by bdach** [comment] 2021-02-28 23:08
Likely another instance of https://github.com/ppy/osu-framework/issues/3297

**Comment by DanielSvindseth** [comment] 2021-03-01 15:48
> I would try and ensure this device is not connected at startup and/or ensure that your system audio is configured correctly such that the MIDI device is not the first/default device available.

Thanks for the help. It is not a physical MIDI-device easy unpluggable from the system. It looks like a dummy/passthrough port created by the system. I am unaware of how I would make osu! not select that as default though.

![Screenshot from 2021-03-01 07-07-42](https://user-images.githubusercontent.com/15878879/109458330-e1466900-7a5c-11eb-8ef0-1340f2872a40.png)
Screenshot showing my jack connections. The problem arises whether jack is running or not.

The MIDI device in question looks like jack's ALSA MIDI bridge, but stopping it doesn't make a difference. Removing a2jmidid also does not help.

The log still says it is connected to the MIDI brigde so I am unsure what to do.

**Comment by DanielSvindseth** [comment] 2021-03-01 16:08
Where does osu! fetch the default audio device from? (a list/file etc.)
Also, why would osu! connect to a MIDI device at all? Does osu! treat it like any audio device?

**Comment by bdach** [comment] 2021-03-01 18:15
> Where does osu! fetch the default audio device from? (a list/file etc.)

Whichever audio subsystem you're using, I presume.

> Also, why would osu! connect to a MIDI device at all? Does osu! treat it like any audio device?

I'm pretty sure that's not how it works. osu! will exclusively open MIDI devices if it detects any but that has nothing to do with audio output.

[Here's a temporary mitigation](https://github.com/ppy/osu/issues/8985#issuecomment-626315769) for you to try and determine if it is the output device indeed. If it works, you will be able to change the device and change the intro sequence back to triangles if you wish.

**Comment by DanielSvindseth** [comment] 2021-03-01 18:44
> [Here's a temporary mitigation](https://github.com/ppy/osu/issues/8985#issuecomment-626315769) for you to try and determine if it is the output device indeed. If it works, you will be able to change the device and change the intro sequence back to triangles if you wish.

This workaround worked in my case too. It seems the biggest problem here is how convoluted and complex the Linux audio system is with countless different implementations.

Would it be too difficult to automatically detect if osu! stalls, and automatically change the intro-sequence to circles? It would probably help in a few cases.

**Comment by bdach** [comment] 2021-03-01 18:57
> Would it be too difficult to automatically detect if osu! stalls, and automatically change the intro-sequence to circles? It would probably help in a few cases.

That should not be the solution. As mentioned in the issue I linked before it needs to be investigated what's wrong with the initial default in some cases, and how to select a better one.

In the mean time, closing this as a duplicate of the framework issue.

**Closed by bdach** 2021-03-01 18:57 UTC
Labels: missing details, platform:linux
