### ISSUE TITLE
Black screen and close osu!lazer

### ISSUE THREAD

**Issue by FahJSKY** [ppy/osu#2688] opened 2018-05-30 20:04 UTC
Hi!
I have a problem
Running osu!lazer application show me this and after some time close this app.
I tried some ways from this blog, but they don't work :/
I would like to problem was quickly resolved

![zrzut ekranu 6](https://user-images.githubusercontent.com/39778323/40744174-16763d98-6454-11e8-9837-db4a709978c3.png)
Here is runtime log:
[runtime.log](https://github.com/ppy/osu/files/2055473/runtime.log)
(Sorry for any misspellings, but I don't use English every day)

**Comment by FreezyLemon** [comment] 2018-05-30 20:07
Looks like there is a wrong GL version being detected:
```
GL Version: 1.1.0
GL Renderer: GDI Generic
```

@FahJSKY What GPU do you have?

**Comment by FahJSKY** [comment] 2018-05-30 20:08
Intel HD Graphics 3000

**Comment by leodes99** [comment] 2018-05-30 20:14
i have the same problem 
 my gpu is a intel g41 express chipset

**Comment by FreezyLemon** [comment] 2018-05-30 20:19
Have you checked whether you have the appropriate graphics drivers installed and updated?

**Comment by leodes99** [comment] 2018-05-30 20:29
yeah my drivers are the latest for mi pc whit windows 7


sorry for mi english i speak spanish

**Comment by FreezyLemon** [comment] 2018-05-30 20:32
@FahJSKY 
I'm not sure that I can help you in that case..
From [what I found](https://www.intel.com/content/www/us/en/support/articles/000005526/graphics-drivers.html?wapkw=cs-034343), it seems that your chip is not supported on Win10, which means that this might be a problem on your end. [This](https://communities.intel.com/thread/61432) can maybe help you though. I don't know.

Anyways, this is a duplicate of ppy/osu-framework#1144 as I just noticed, so you should probably keep an eye on that one and close this issue.

**Closed** 2018-05-30 20:36 UTC
