### ISSUE TITLE
Multiplayer crashing Android build

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6311] opened 2019-09-28 21:18 UTC
**Describe the bug:** Basically, whenever I click on multiplayer on the Android build, it also crashes the app

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.920.0

**Logs:** I don't know which log file this would be under

**Comment by bdach** [comment] 2019-09-28 21:22
Are you running on an Android device with a non-English language set? If so, this is most likely a duplicate of #6261.

To confirm, please attach all logs from the `Android/data/sh.ppy.osulazer/logs` directory.

**Comment by X4X5** [comment] 2019-09-28 21:27
[database.log](https://github.com/ppy/osu/files/3666018/database.log)
[network.log](https://github.com/ppy/osu/files/3666019/network.log)
[performance.log](https://github.com/ppy/osu/files/3666020/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3666021/runtime.log)
Here they are.

**Comment by bdach** [comment] 2019-09-28 21:34
These look clean. They show you entering the multiplayer screen, but there's no actual stacktrace in sight. Is there any more details you can provide? How does the crash look like, are there any dialogs popping up after?

**Comment by X4X5** [comment] 2019-09-28 21:59
I clock on multiplayer, then it goes to black screen for a split second, then kicks me out of the app.

**Comment by smoogipoo** [comment] 2019-10-01 06:50
This is going to be a duplicate of #6261. runtime.log shows a mobile/arm chipset.

**Closed by smoogipoo** 2019-10-01 06:50 UTC
Labels: android
