### ISSUE TITLE
Creating and saving difficulties freezes game for several seconds

### ISSUE THREAD

**Issue by bdach** [ppy/osu#22202] opened 2023-01-14 18:23 UTC
### Type

Performance

### Bug description

Reproduction steps:

1. Open editor
2. Create new difficulty
3. Game will freeze for a couple of seconds and then drop you into the new difficulty

Is happening because the beatmap creation flow ends up triggering a synchronous API request on the update thread via the beatmap updater flow:

![1673719570](https://user-images.githubusercontent.com/20418176/212488955-8df8aa38-a196-460d-9dd5-a27191f9db66.png)

(read top-down)

### Screenshots or videos

https://user-images.githubusercontent.com/20418176/212489665-11253ea3-054c-4908-90ed-3df031915ab2.mp4

### Version

current master

### Logs

[performance-update.log](https://github.com/ppy/osu/files/10418526/performance-update.log)

```
2023-01-14 18:20:13 [verbose]: | Slow frame on thread "Update"
2023-01-14 18:20:13 [verbose]: |
2023-01-14 18:20:13 [verbose]: | * Thread time  : 47,062ms
2023-01-14 18:20:13 [verbose]: | * Frame length : 5,093ms (allowable: 10ms)
2023-01-14 18:20:13 [verbose]: |
2023-01-14 18:20:13 [verbose]: | Call stack was not recorded.
```

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 17:05
Do you know what this API does? I'm new to open source and I want to help.

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 17:13
I was not able to reproduce the bug by following the instructions you gave. Can you give more details?

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 17:27
As you can see in the video below, there was no freeze when I attempted to reproduce the bug.

https://user-images.githubusercontent.com/123326846/214107677-03676020-ab12-499b-86fc-74dee4af46c5.mp4

Sorry if I committed some mistake in the reproduction of the bug.

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 17:30
I was able to reproduce the bug. It only affects creating new osu!taiko, osu!catch and osu!mania difficulties, osu! is not affected.

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 17:38
How do I access the debug logs?

**Comment by FlightSimEnjoyer** [comment] 2023-01-23 18:43
Okay, I understand. Thank you for pointing out my mistakes. I will look for another issue for my first contribution then.

**Comment by honguyenminh** [comment] 2023-01-24 00:54
It happens on every map save I think. Saving a map also freezes my game for a few seconds, but that can also be a result of crappy computer. Might need more confirmation from other people.

**Closed** 2023-04-12 12:55 UTC
Labels: priority:0, type:performance, area:editor
