### ISSUE TITLE
Multi Lobby Creation Crash

### ISSUE THREAD

**Issue by Outlinerr** [ppy/osu#7915] opened 2020-02-19 17:53 UTC
**Describe the crash:** 
When creating a lobby, if you add a map, then change the map, then click and drag on the three bars to the left of the song name in a direction, the game will crash instantly. It doesn't happen 100% of the time, sometimes it reports a bug and other times it crashes.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=WDNcBI3YqHk

**osu!lazer version:** 
2020.215.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/4226513/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4226514/runtime.log)
[database.log](https://github.com/ppy/osu/files/4226515/database.log)
[network.log](https://github.com/ppy/osu/files/4226516/network.log)

**Computer Specifications:** 
i5 8400, 8gb DDR4 RAM, GTX 750ti, windows 10 x64 version 1909

**Comment by mouzedrift** [comment] 2020-02-19 18:03
duplicate of #7860. this should be fixed in the next release.

**Closed** 2020-02-19 18:08 UTC
