### ISSUE TITLE
optional to apply osu.Game.Resources

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#11559] opened 2021-01-21 17:59 UTC
**Describe the new feature:** osu.Game.Resources is required to use osu.Game in nuget. If we are going to remove dependencies(osu-resource), we can use osu.Game without [remove the contents by forking the sauce.](https://github.com/osukeesu/osu/commit/8114ea90eb555531b15a05e8d07ba5531ae1ec85) for removing some megabytes. 

(only 6MB if _osu.Game, osu.Game.Ruleset.Catch, osu.Game.Ruleset.Mania, osu.Game.Ruleset.Osu, osu.Game.Ruleset.Taiko_ builded from plain project without osu-resources)

**Proposal designs of the feature:** I don't know the definite answer because I didn't fully understand the code, but I only see to inject osu-resources into execution projects like osu.Desktop, osu.Android

https://github.com/ppy/osu/blob/master/osu.Game/OsuGameBase.cs#L166

**Comment by bdach** [comment] 2021-01-21 18:01
Duplicate of #4241

**Closed by bdach** 2021-01-21 18:01 UTC
