### ISSUE TITLE
Keeps crashing when Im going to search in online or anything related online.

### ISSUE THREAD

**Issue by thefirstmine** [ppy/osu#6381] opened 2019-10-03 16:43 UTC
**Describe the crash:** 
I just installed osu!lazer for android. I just logged in then go to osu!direct to download beatmaps and then... The app crashed.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/kCM_WOwfMZg
On youtube since icant even upload videos on mobile
**osu!lazer version:** 
Android 0.1
**Logs:** 
[database.log](https://github.com/ppy/osu/files/3687166/database.log)
[network.log](https://github.com/ppy/osu/files/3687167/network.log)
[performance.log](https://github.com/ppy/osu/files/3687169/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3687172/runtime.log)
**Computer Specifications.**
Not on computer just on mobile.

**Comment by thefirstmine** [comment] 2019-10-03 16:45
P.S- Video was low quality I know. Its the screen recorders fault not mine lmao

**Comment by bdach** [comment] 2019-10-03 16:45
Duplicate of #6264.

**Closed by bdach** 2019-10-03 16:45 UTC
