### ISSUE TITLE
in french, thousands separator for numbers is a "?"

### ISSUE THREAD

**Issue by SailorSnoW** [ppy/osu#22365] opened 2023-01-23 01:36 UTC
### Type

Cosmetic

### Bug description

Using french localisation, all numbers have a "?" as thousands separator. (e.g 1?000?000 instead of 1.000.000).
Happen on every platform that I have tested (Windows 11, Mac OS 13.0.1).

We expect separator character to be a space as is it usually written in France and this is the one used on the osu website for french localisation.

### Screenshots or videos

![osu_2023-01-23_02-29-34](https://user-images.githubusercontent.com/49660929/213952205-040caf94-4e33-4b59-b87f-32a878f0ba3e.jpg)
![osu_2023-01-23_02-28-47](https://user-images.githubusercontent.com/49660929/213952159-eea51511-8c01-4868-85f3-9209b62454c6.jpg)

### Version

2023.123.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10476053/network.log)
[performance.log](https://github.com/ppy/osu/files/10476054/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10476055/runtime.log)

**Comment by peppy** [comment] 2023-01-23 06:02
We probably need to map the french-space to a normal space.

**Comment by bdach** [comment] 2023-01-23 06:11
Duplicate of https://github.com/ppy/osu/issues/15135

**Closed** 2023-01-23 06:11 UTC
Labels: type:localisation
