### ISSUE TITLE
crashing on iPad 5th gen with iOS 14.3

### ISSUE THREAD

**Issue by RoxasGrylls** [ppy/osu#23198] opened 2023-04-13 17:58 UTC
### Type

Crash to desktop

### Bug description

As stated in the title, I tried to install osu!lazer on my iPad 5th gen with iOS 14.3.
The only thing I can point out is that the iPad is jailbroken and osu! doesn't even create a log file.
Please let me know if you need some other details.
Thank you.

### Version

2023.403.1

### Logs

No logs available.

**Comment by RoootTheFox** [comment] 2023-04-17 23:24
I'm having the exact same issue (iPad7, iOS 14.2), it seems to be related to missing symbols referenced from veldrid
I'm assuming this is because veldrid was built targeting iOS 16.2 and 14.2 has an older libc++ version (from what my 1am brain can tell at least)

Here's the crash log:
[2023-04-18_1-18_am.log](https://github.com/ppy/osu/files/11256516/2023-04-18_1-18_am.log)

**Comment by RoootTheFox** [comment] 2023-04-17 23:29
After about a minute of digging I found that the issue is most likely related to [this prebuilt spriv veldrid binary](https://github.com/ppy/osu-framework/blob/019864011cabfeaec6f6b609a451aa202477dfbc/osu.Framework.iOS/runtimes/ios/native/veldrid-spirv.xcframework/ios-arm64/veldrid-spirv.framework/veldrid-spirv)

**Comment by RoxasGrylls** [comment] 2023-04-18 06:48
> After about a minute of digging I found that the issue is most likely related to [this prebuilt spriv veldrid binary](https://github.com/ppy/osu-framework/blob/019864011cabfeaec6f6b609a451aa202477dfbc/osu.Framework.iOS/runtimes/ios/native/veldrid-spirv.xcframework/ios-arm64/veldrid-spirv.framework/veldrid-spirv)

Cool! Maybe we can find a veldrid-spriv by ourselves and recompile the .ipa?

**Comment by RoootTheFox** [comment] 2023-04-18 09:01
I tried building veldrid-spirv from a repo I found, however that gave me a library (`.a`) file that was about 10MB bigger than the one found in osu!framework so I highly doubt that one would work.
Sadly there were no instructions or hints on how to build that veldrid-spirv binary (or where it came from in the first place)

I'd assume @frenzibyte (apologies for the mention) knows, since they committed the file to the repo - maybe they can help?

**Comment by frenzibyte** [comment] 2023-04-18 09:09
The veldrid-spirv binary was compiled with local changes (will be pushed somewhere soon), I'll compile a version with lower iOS target and loop back to you.

**Comment by RoootTheFox** [comment] 2023-04-18 09:12
Thank you!

**Closed** 2023-04-18 14:15 UTC
Labels: framework-fix-required, platform:iOS, type:reliability
