### ISSUE TITLE
Osu!lazer Glitching with HR

### ISSUE THREAD

**Issue by kirai69** [ppy/osu#6725] opened 2019-11-05 17:33 UTC
Happens when you play "osu.ppy.sh/beatmapsets/42837#osu/134621" with Hard Rock Mod and quick restart the Map. The Audio is Glitching and the Beatmap going Very slow. 
idk if it is a known issue, the Game itself dosen't Report this Error/Bug so i guess its a unknown issue.

**osu!lazer version:** 
2019.1105.0

**Video**
youtu.be/eK0SO0nQl-Q

**Comment by bdach** [comment] 2019-11-05 17:43
Duplicate of #6704; as far as I'm aware this is not mod- or beatmap-specific, but happens every time on restart through a pause/fail overlay.

**Closed by bdach** 2019-11-05 17:43 UTC
