### ISSUE TITLE
Samsung devices don't allow to change folders

### ISSUE THREAD

**Issue by lightthefox** [ppy/osu#21681] opened 2022-12-17 13:58 UTC
### Type

Other

### Bug description

When you go to the beatmap creator, and want to change the song it goes to
**/sdcard**
When it should go to
**/storage/emulated/0**
or
**/storage/emulated/10**
or similar..
Basically, please change the folder,or use the inbuilt android/device file explorer or atleast add a button to do so.

### Version

2022.1208.0

### Logs

Found no log for it

**Comment by toadsworth-jr** [comment] 2022-12-17 14:00
Do you have storage permissions turned on manually via your phone's settings?

**Comment by jai-x** [comment] 2022-12-17 14:02
Duplicate of https://github.com/ppy/osu/issues/11911

**Closed** 2022-12-17 14:04 UTC
