### ISSUE TITLE
Android lazer is buggy

### ISSUE THREAD

**Issue by LavatriceX** [ppy/osu#9110] opened 2020-05-25 15:48 UTC
Hey so i play on a Galaxy A51 Device and its pretty much buggy
Here are some bugs i have:
- typing anywhere is such a pain, specifically on login, you need to type then press enter to insert the user name, and to literally use the quick keyboard text to use the password, also on chat i was typing a long message and all it wrote is this.
![Screenshot_٢٠٢٠٠٥٢٥-١٨٤٦٥٤](https://user-images.githubusercontent.com/60001654/82827693-321aa700-9eb8-11ea-8573-62af1bcaa29a.jpg)
- also what those mean???
![Screenshot_٢٠٢٠٠٥٢٥-١٨٤٧٠٥](https://user-images.githubusercontent.com/60001654/82827712-3c3ca580-9eb8-11ea-927a-1cc65437e8f1.jpg)

Thanks for reading and please fix asap.

**Comment by bdach** [comment] 2020-05-25 15:52
Duplicate of both #8264 and #7062

**Closed by bdach** 2020-05-25 15:52 UTC
