### ISSUE TITLE
UI issue with rounded screen on mobile

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#12253] opened 2021-04-01 12:54 UTC
**Describe the bug:** 
The UI don't fit on phone with rounded screen, and now, most of phones have rounded screen. I have the same problem on landscape mode.

**Here is a screen with my mobile frame:** 
![Capture d’écran 2021-04-01 145242](https://user-images.githubusercontent.com/31996023/113296615-fcc1bf80-92f9-11eb-9a6e-f65602a5b720.png)

**Comment by jai-x** [comment] 2021-04-01 13:09
Duplicate of https://github.com/ppy/osu/issues/4330

**Closed** 2021-04-01 13:10 UTC
