### ISSUE TITLE
Settings Dashboard Item selection issue

### ISSUE THREAD

**Issue by Nirioppai** [ppy/osu#11128] opened 2020-12-08 13:10 UTC
**Describe the bug:** 
At the settings screen on the main menu, when you click on the menus downward, the highlight follows the previous item instead of the current one
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/57257533/101487711-83dcd780-3999-11eb-89dc-8726dbf22216.png)

**osu!lazer version:** 
2020.1204.0

**Logs:**

**Comment by frenzibyte** [comment] 2020-12-08 13:11
Duplicate of https://github.com/ppy/osu/issues/9196, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2020-12-08 13:12 UTC

**Comment by Nirioppai** [comment] 2020-12-09 13:12
Hello, I would like to ask how does osu! know a chorus of a song for audio
playback in song selection?

**Comment by LittleEndu** [comment] 2020-12-09 13:29
You responded to a github email. Please do not ask questions like these on github.

Mapper set preview points is the answer
