### ISSUE TITLE
Osu! Lazer can't run

### ISSUE THREAD

**Issue by NickKyKunG** [ppy/osu#2712] opened 2018-06-02 08:50 UTC
This is not first time. When is install osu! lazer and run game, game has run but it don't show anything
the game is has black screen and then the game has close, I tried several times but it not work.

I hope you can help me.
thank you.

ps. sorry for my language. I'm not good at English language

**Comment by UselessToucan** [comment] 2018-06-02 08:54
> I hope you can help me.

No, we can't help you without logs. You can find them here: %AppData%\osu\logs

**Comment by FreezyLemon** [comment] 2018-06-02 08:56
Possible duplicate of #2571.

**Comment by NickKyKunG** [comment] 2018-06-02 09:01
@FreezyLemon here. my runtime.
[runtime.log](https://github.com/ppy/osu/files/2064823/runtime.log)

**Comment by LittleEndu** [comment] 2018-06-02 09:43
I don't know why other devs aren't asking for it... but can you also include your ``client.db`` file from ``%appdata%\osu``? It would help them reproduce the error everyone seems to be having but nobody can reproduce...

**Comment by peppy** [comment] 2018-06-02 09:46
It likely has nothing to do with the contents of the database; the migration failure fallback is failing. You can test this by making an arbitrary corrupt database.

**Comment by NickKyKunG** [comment] 2018-06-02 09:48
@peppy how can i do?

**Comment by peppy** [comment] 2018-06-02 11:34
Could you attach your client.db (found in the parent directory of the logs)?

After doing so, if you'd just like to make lazer run again, delete `client.db` and lazer will build it again from scratch.

**Comment by NickKyKunG** [comment] 2018-06-02 11:42
Ohhh!!! Thank you!!! @peppy  I can open Osu! Lazer now.

Thank you so much!!! ;w;

**Closed** 2018-06-06 13:53 UTC
Labels: database, startup crash
