### ISSUE TITLE
Autoplay is now missing on certain maps where it previously didn't

### ISSUE THREAD

**Issue by Supersonicboss1** [ppy/osu#12664] opened 2021-05-02 22:10 UTC
**Describe the bug:** 
On maps such as https://osu.ppy.sh/beatmapsets/756794#osu/1605148 and https://osu.ppy.sh/beatmapsets/150945#osu/372245 Autoplay is missing where it didn't previously. In Mayday's case, real replays do not miss there and get a higher score that Autoplay. This seems to have been caused by release 2021.416.0 as it does not happen on earlier releases
**Screenshots or videos showing encountered issue:** 
On latest release (2021.502.0)
![osu_2021-05-02_22-51-54](https://user-images.githubusercontent.com/36936474/116828993-13c62c80-ab9a-11eb-8e2e-6b7608eb07b3.jpg)
On release 2021.410.0
![osu_2021-05-02_23-01-42](https://user-images.githubusercontent.com/36936474/116829035-7cada480-ab9a-11eb-8fa6-d4707e9875b8.jpg)

**osu!lazer version:** 
this occurs on version 2021.416.0 and above, including latest
**Logs:**
From latest release:
[network.log](https://github.com/ppy/osu/files/6412343/network.log)
[performance.log](https://github.com/ppy/osu/files/6412344/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6412345/runtime.log)

**Comment by frenzibyte** [comment] 2021-05-02 22:16
Duplicate of #12651

**Closed by frenzibyte** 2021-05-02 22:16 UTC
