### ISSUE TITLE
osu!lazer crash

### ISSUE THREAD

**Issue by odenstyle** [ppy/osu#6544] opened 2019-10-19 19:38 UTC
osu!lazer is almost guaranteed to crash within the first or second song you play. At least in my iDevice

version 2019.1011.0?
iOS 13

**Comment by bdach** [comment] 2019-10-19 19:44
Please provide more specifics, we can't fix your issue if you don't say when the problem occurs exactly.

I'm thinking you're trying to report the same issue as in #6355, but again I can't know for sure with what you've provided so far.

**Comment by odenstyle** [comment] 2019-10-19 21:01
all the osu lazer crashes I’ve experienced so far we’re from during gameplay. crashes either start from as early as just after launching the beatmap to finishing a beatmap. But so far, I’ve only encountered these crashes while playing a beatmap.

**Comment by bdach** [comment] 2019-10-19 22:03
From your description it sounds like a duplicate of the aforementioned issue; closing.

**Closed by bdach** 2019-10-19 22:03 UTC
Labels: missing details
