### ISSUE TITLE
Gap between UI and screen bottom when Alt+Tab

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#7689] opened 2020-01-31 03:58 UTC
**Describe the bug:** 
The gap between UI and screen bottom shows the rest of background if I alt+tab to back to osu!lazer.
I am not sure this bug was there last week because I had been using windowed mode until today.
I use Ubuntu MATE 19.10.

EDIT: Only borderless mode works fine. Windowed mode with full screen resolution which seems like fullscreen has the same issue

**Screenshots or videos showing encountered issue:** 
![osu_2020-01-31_12-53-17](https://user-images.githubusercontent.com/9151706/73511398-d6b83b00-4428-11ea-862b-34270dc502a3.jpg)

**osu!lazer version:** 
2020.130.0-2-gd5b9df049

**Logs:** 
https://gist.github.com/coinworld/f72783c7b08e263e5d14584901af8f70

**Comment by peppy** [comment] 2020-01-31 08:46
what is that height? is it your window decoration height or taskbar or something?

**Comment by coinworld** [comment] 2020-01-31 12:30
![gap](https://user-images.githubusercontent.com/9151706/73539432-b9a75a80-4470-11ea-9a2b-0eccd34d7655.png)

gap is a bit bigger than my decoration

**Comment by BojayB** [comment] 2020-10-04 17:22
(pictures are a little big for a comment I apologize)
![image](https://user-images.githubusercontent.com/41974762/95021941-0962a500-0642-11eb-8ee1-305c2ddd11f5.png)
![image](https://user-images.githubusercontent.com/41974762/95021985-47f85f80-0642-11eb-92be-4425eaf5a8cf.png)
This hurts gameplay majorly.
Running Lubuntu (Ubuntu 20.04.1)

**Comment by peppy** [comment] 2020-10-05 08:10
can someone confirm this is fixed with SDL?

**Comment by Joehuu** [comment] 2020-10-06 02:01
Yep, on a new Ubuntu install I can't reproduce with SDL.

**Comment by BojayB** [comment] 2020-10-06 19:14
sorry, but what is SDL? and how do I use it?

**Comment by bdach** [comment] 2020-10-06 19:15
It's an experimental windowing/input backend we're trying out to potentially replace the fork of opentk we're using currently. To use it, start lazer with the `--sdl` command line argument.

**Comment by BojayB** [comment] 2020-10-06 19:15
thank you so much!

**Comment by Joehuu** [comment] 2020-10-11 21:06
Duplicate of https://github.com/ppy/osu/issues/7141

**Closed by Joehuu** 2020-10-11 21:06 UTC
Labels: fixed-in-sdl, low-priority, platform:linux
