### ISSUE TITLE
Streaming in osu lazer ios

### ISSUE THREAD

**Issue by 0Tommy0** [ppy/osu#5032] opened 2019-06-15 11:06 UTC
Add 2 button in the left side or in the right side . We will use it for clicking for streaming circles.

**Comment by peppy** [comment] 2019-06-15 11:06
Duplicate of https://github.com/ppy/osu/issues/4201.

**Closed by peppy** 2019-06-15 11:06 UTC

**Comment by 0Tommy0** [comment] 2019-06-15 11:09
> Add 2 button in the left side or in the right side . We will use it for clicking for streaming circles.
