### ISSUE TITLE
Crash when moving slideranchor behind sliderhead or sliderend

### ISSUE THREAD

**Issue by Gottagof4st** [ppy/osu#3858] opened 2018-12-14 15:17 UTC
**Describe your problem:** When moving slideranchors while the slider isn't in bezier mode (so most often if there is only 1 slideranchor), you can drag it past the head or the tail which makes it go infinite, and with that also crashing everything.
Can't alt+tab out or access task manager to stop it so you have to force restart your pc losing anything that wasnt done or saved.

**Screenshots or videos showing encountered issue:** https://puu.sh/C2J8u/7ac66d19da.mp4 freeze happens at exactly 0:22

**osu!lazer version:** 2018.1207.0

The stable client doesnt have this as when the slider goes past a certain angle behind the first or last anchor, then it just turns into a bezier slider like https://puu.sh/C2JtH/a78deebd18.png .
When importing a map with objects like these from stable to lazer it automatically converts the anchors to red ones so there is no problem there.
Have also confirmed that this crashed for the 2 other pcs i tested this on

Tried to find a fix myself first but as I am only able to do python, I can't really do it

**Comment by peppy** [comment] 2020-11-13 03:32
Duplicate of https://github.com/ppy/osu/issues/5538.

**Closed** 2020-11-13 03:32 UTC
Labels: area:editor
