### ISSUE TITLE
Pressing ALT+F4 shuts the music down but never brings it back up

### ISSUE THREAD

**Issue by Teelry** [ppy/osu#7948] opened 2020-02-21 23:25 UTC
When pressing alt+f4 in game, the music is shut to 0. it does not come back if you press "Just a little more". If you try to change it using the volume rocker, it stays at 0. When trying to play a map, you get the notification that your sound is set to 0, and it comes back to max volume if you press the notification.

**Comment by bdach** [comment] 2020-02-21 23:31
Duplicate of #3483

**Closed by bdach** 2020-02-21 23:31 UTC
