### ISSUE TITLE
User profile overlay does not support showing per-ruleset info

### ISSUE THREAD

**Issue by bdach** [ppy/osu#16565] opened 2022-01-22 15:16 UTC
By which I mean the selector on the right here:

![2022-01-22-161503_1080x127_scrot](https://user-images.githubusercontent.com/20418176/150644328-f1ec0e1d-da15-414d-a28c-16f143825196.png)

By default, osu! info is used.

There are [parts that look like they should eventually support this](https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Profile/Header/Components/ProfileRulesetSelector.cs), but they're not hooked up to anything except tests.

**Comment by LittleEndu** [comment] 2022-01-22 17:17
Duplicate of #3606

**Closed** 2022-01-22 17:28 UTC
Labels: area:overlay-user-profile
