### ISSUE TITLE
[OSX] input issue

### ISSUE THREAD

**Issue by toutouyoutoo** [ppy/osu#6887] opened 2019-11-20 03:53 UTC
hi, after activating raw input, the ingame cursor froze. mouse or trackpad, none is capable of moving the cursor.
I now can't go back even uninstalling/reinstalling the game does not change anything(maybe a settings file is hidden somewhere).

**Comment by swoolcock** [comment] 2019-11-20 04:12
Duplicate of #6845, please search in future.

Press Ctrl+Alt+R.

**Closed by swoolcock** 2019-11-20 04:12 UTC

**Comment by toutouyoutoo** [comment] 2019-11-20 04:37
@swoolcock sorry i'm new on GitHub i searched in the issue tab but found nothing about OS X, thanks a lot
