### ISSUE TITLE
Sometimes maps don't load in realtime multiplayer

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#11776] opened 2021-02-14 02:01 UTC
**Describe the bug:** 

Sometimes when someone else selects a new map it'll just go blank and show a notification that an error occured.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2021.212.0

**Logs:**

```
2021-02-14 01:50:11 [verbose]: Screen changed → PlayerLoader
2021-02-14 01:50:17 [verbose]: Screen changed → MultiplayerPlayer
2021-02-14 01:52:12 [verbose]: Screen changed → MultiplayerResultsScreen
2021-02-14 01:52:18 [verbose]: Screen changed ← MultiplayerPlayer
2021-02-14 01:52:18 [verbose]: Screen changed ← PlayerLoader
2021-02-14 01:52:18 [verbose]: Screen changed ← Multiplayer
2021-02-14 01:52:18 [verbose]: Polling adjusted (listing: 0, selection: 0)
2021-02-14 01:52:53 [verbose]: Polling adjusted (listing: 0, selection: 0)
2021-02-14 01:52:53 [verbose]: Screen changed → PlayerLoader
2021-02-14 01:52:56 [verbose]: Screen changed → MultiplayerPlayer
2021-02-14 01:55:51 [verbose]: Screen changed → MultiplayerResultsScreen
2021-02-14 01:56:00 [verbose]: Screen changed ← MultiplayerPlayer
2021-02-14 01:56:00 [verbose]: Screen changed ← PlayerLoader
2021-02-14 01:56:00 [verbose]: Screen changed ← Multiplayer
2021-02-14 01:56:00 [verbose]: Polling adjusted (listing: 0, selection: 0)
2021-02-14 01:57:04 [error]: An unhandled error has occurred.
2021-02-14 01:57:04 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'first')
2021-02-14 01:57:04 [error]: at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2021-02-14 01:57:04 [error]: at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
2021-02-14 01:57:04 [error]: at osu.Game.Online.Multiplayer.MultiplayerRoomSettings.Equals(MultiplayerRoomSettings other) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs:line 40
2021-02-14 01:57:04 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.updatePlaylist(MultiplayerRoomSettings settings, APIBeatmapSet onlineSet) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 529
2021-02-14 01:57:04 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.<>c__DisplayClass65_0.<updateLocalRoomSettings>b__1(APIBeatmapSet res) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 521
2021-02-14 01:57:04 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-02-14 01:57:04 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:04 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-02-14 01:57:04 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-02-14 01:57:04 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2021-02-14 01:57:04 [verbose]: Focus contention triggered by NotificationOverlay.
2021-02-14 01:57:09 [verbose]: Polling adjusted (listing: 15000, selection: 15000)
2021-02-14 01:57:11 [verbose]: Polling adjusted (listing: 0, selection: 0)
2021-02-14 01:57:11 [error]: An unhandled error has occurred.
2021-02-14 01:57:11 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'first')
2021-02-14 01:57:11 [error]: at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2021-02-14 01:57:11 [error]: at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
2021-02-14 01:57:11 [error]: at osu.Game.Online.Multiplayer.MultiplayerRoomSettings.Equals(MultiplayerRoomSettings other) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs:line 40
2021-02-14 01:57:11 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.updatePlaylist(MultiplayerRoomSettings settings, APIBeatmapSet onlineSet) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 529
2021-02-14 01:57:11 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.<>c__DisplayClass65_0.<updateLocalRoomSettings>b__1(APIBeatmapSet res) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 521
2021-02-14 01:57:11 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-02-14 01:57:11 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:11 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-02-14 01:57:11 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-02-14 01:57:11 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2021-02-14 01:57:11 [verbose]: Focus contention triggered by NotificationOverlay.
2021-02-14 01:57:55 [error]: An unhandled error has occurred.
2021-02-14 01:57:55 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'first')
2021-02-14 01:57:55 [error]: at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2021-02-14 01:57:55 [error]: at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
2021-02-14 01:57:55 [error]: at osu.Game.Online.Multiplayer.MultiplayerRoomSettings.Equals(MultiplayerRoomSettings other) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs:line 40
2021-02-14 01:57:55 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.updatePlaylist(MultiplayerRoomSettings settings, APIBeatmapSet onlineSet) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 529
2021-02-14 01:57:55 [error]: at osu.Game.Online.Multiplayer.StatefulMultiplayerClient.<>c__DisplayClass65_0.<updateLocalRoomSettings>b__1(APIBeatmapSet res) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs:line 521
2021-02-14 01:57:55 [error]: at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
2021-02-14 01:57:55 [error]: at osu.Framework.Threading.Scheduler.Update()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2021-02-14 01:57:55 [error]: at osu.Framework.Platform.GameHost.UpdateFrame()
2021-02-14 01:57:55 [error]: at osu.Framework.Threading.GameThread.ProcessFrame()
2021-02-14 01:57:55 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
2021-02-14 01:57:55 [verbose]: Focus contention triggered by NotificationOverlay.
```

**Comment by frenzibyte** [comment] 2021-02-14 02:15
Duplicate of https://github.com/ppy/osu/issues/11686, please let the other users update their clients.

**Closed by frenzibyte** 2021-02-14 02:15 UTC
