### ISSUE TITLE
Key conversion mod should not be selected when play a mania specialized map

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu#27442] opened 2024-03-01 04:53 UTC
### Type

Game behaviour

### Bug description

Key conversion mod is useless for mania specialized map, they need be removed when enter in gameplay or let them cannot be selected.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/34775378/918d7acc-6f85-420f-baf9-fc67f21bb0cc)
![image](https://github.com/ppy/osu/assets/34775378/4d914e71-4eda-4e6d-abef-943cb91ccc7b)

### Version

2024.221.0

### Logs

na

**Comment by Joehuu** [comment] 2024-03-01 06:41
Duplicate of https://github.com/ppy/osu/issues/18562

**Closed by Joehuu** 2024-03-01 06:41 UTC
