### ISSUE TITLE
Key presses during break times count up towards total

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#2707] opened 2018-06-01 16:37 UTC
They do not on stable

**Comment by turbedi** [comment] 2018-07-14 09:45
Duplicate of issue #3032 , fixed by PR #3035

**Comment by HoutarouOreki** [comment] 2018-07-14 23:22
@peppy This is neither a duplicate nor is it fixed by that PR. This one is about break times, that issue and PR are about pauses.

**Comment by galister** [comment] 2019-04-05 17:42
This is also the case during song intro:
https://i.imgur.com/efxWVtO.jpg

**Closed** 2020-03-06 09:42 UTC
Labels: area:gameplay
