### ISSUE TITLE
Beatmap Video Latency

### ISSUE THREAD

**Issue by otiskujawa** [ppy/osu#7617] opened 2020-01-25 18:41 UTC
The problem is the beatmap video noticeably shifted forward.
On screenshots this same beatmap in osu! and osu!lazer:
![osu!lazer BAD](https://user-images.githubusercontent.com/49094075/73125706-37b7bd00-3faa-11ea-8aab-5a409767d6b5.jpg)
![Osu!](https://user-images.githubusercontent.com/49094075/73125718-53bb5e80-3faa-11ea-98b9-1a53aa9c5f30.jpg)
Several beatmaps work well
Sound offset is the same in this versions(7/8 ms).
How to fix it ?

**Comment by bdach** [comment] 2020-01-25 18:43
Duplicate of #6101

**Closed by bdach** 2020-01-25 18:43 UTC
