### ISSUE TITLE
Double time and pause bug.

### ISSUE THREAD

**Issue by ShizuVoice** [ppy/osu#21970] opened 2022-12-31 14:56 UTC
### Type

Game behaviour

### Bug description

While playing osu!lazer, if I attempt to do a retry/pause/quit these are the possible things that could happen:

- No music audio in a few seconds, midway, or all-through the beatmap, even on menu (discovered more than two months ago)
- Pause music keeps still playing after retrying from pause or on menu, multiplies if you try to spam it by pausing and retrying (discovered more than two months ago)
- Double time bugs out which becomes too fast (recently discovered)
- Stuck on the play screen with an opaque cursor (recently discovered)

Probably this is not the typical issue report but it just happened more than a single bug in one sitting and it is hard to explain.

_But one thing I've noticed after 6 months of playing osu!lazer is that **this happens when connected to a very slow/unstable WiFi**. This doesn't happen when the WiFi or internet is fast and if my conditions can be replicated by other users then this is an issue to players with unstable internet._

I'm going to upload two logs just in case.

### Screenshots or videos

[Video 1 (with DT)](https://youtu.be/rfcuApQP7ZY)
[Video 2 (stuck on play screen)](https://youtu.be/fDhaxvy98AQ)
[Video 3 (no audio after quick retry)](https://youtu.be/gyOmrsKqT9k)

### Version

2022.1228.0-lazer

### Logs

[1-database.log](https://github.com/ppy/osu/files/10327451/database.log)
[1-input.log](https://github.com/ppy/osu/files/10327452/input.log)
[1-network.log](https://github.com/ppy/osu/files/10327453/network.log)
[1-performance.log](https://github.com/ppy/osu/files/10327458/performance.log)
[1-runtime.log](https://github.com/ppy/osu/files/10327459/runtime.log)

[2-database.log](https://github.com/ppy/osu/files/10327496/database.log)
[2-input.log](https://github.com/ppy/osu/files/10327499/input.log)
[2-network.log](https://github.com/ppy/osu/files/10327502/network.log)
[2-performance.log](https://github.com/ppy/osu/files/10327506/performance.log)
[2-runtime.log](https://github.com/ppy/osu/files/10327507/runtime.log)

**Comment by bdach** [comment] 2022-12-31 15:07
Duplicate of #20908

**Closed by bdach** 2022-12-31 15:07 UTC
