### ISSUE TITLE
Large banana showers cause significant lag when loaded during gameplay

### ISSUE THREAD

**Issue by snalgae** [ppy/osu#28241] opened 2024-05-19 16:59 UTC
### Type

Performance

### Bug description

I decided to investigate the cause of this lag because it has affected 2 of my plays on a map. I managed to isolate this lag to the banana shower. It is consistent and a long enough banana shower by itself can produce it.
Here's the map if you need it: https://osu.ppy.sh/beatmapsets/2138244#fruits/4500030

### Screenshots or videos

https://github.com/ppy/osu/assets/104220939/bfb5f450-4c53-40cd-9f95-49b24bb42814

### Version

2024.519.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15370133/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-05-20 12:17
Yeah, that PR was a bit of a best effort because DHOs don't have a lifetime management container and all that.

Not sure of an immediate solution, but I'd move towards "don't retrieve all of the bananas from pool immediately" with the future refactoring/rework of hitobject lifetime management.

**Comment by bdach** [comment] 2024-06-04 14:22
Randomly found https://github.com/ppy/osu/issues/12659, which this is a duplicate of.

**Closed by bdach** 2024-06-04 14:22 UTC
Labels: type:performance, ruleset/osu!catch, priority:2
