### ISSUE TITLE
Delayed misses/Sudden fail

### ISSUE THREAD

**Issue by UneCloud** [ppy/osu#26843] opened 2024-01-30 22:25 UTC
### Type

Game behaviour

### Bug description

Casual playing, only using "stable" mods (HR to be more specific). Caught the bug twice over 3 hours of gameplay. The game stutters once and counts in phantom or delayed misses (can't specify that part)

I have attached a link to a VOD below, but here are timestamps and extra info:

VOD Timestamp (Exact second when it happened in the logs)

01:44:55 (20:42:49) 
02:40:20 (21:38:26)

### Screenshots or videos

Full VOD: https://www.twitch.tv/videos/2048272631 (reuploaded to YT in case it disappears. Being processed at the time of writing this: https://youtu.be/5SqJEsSFsds )

### Version

2024.130.2-lazer

### Logs

[1706639733.network.log](https://github.com/ppy/osu/files/14104947/1706639733.network.log)
[1706639733.performance.log](https://github.com/ppy/osu/files/14104948/1706639733.performance.log)
[1706639733.runtime.log](https://github.com/ppy/osu/files/14104949/1706639733.runtime.log)
[1706639733.database.log](https://github.com/ppy/osu/files/14104950/1706639733.database.log)

**Comment by bdach** [comment] 2024-01-30 22:41
![1706654364](https://github.com/ppy/osu/assets/20418176/e1025cda-c2ac-4712-84b1-97c06a22b45d)

This does not look right...

Do you have the replays for these scores handy? Can you export them and attach them zipped here? Would be much easier to work with.

**Comment by UneCloud** [comment] 2024-01-30 22:54
I do have the first case saved as a replay, but not the second one unfortunately. I have attached the first case. I will make sure to save and export more, if or when I encounter this bug next session

[26843_timestamp_204249.zip](https://github.com/ppy/osu/files/14105203/26843_timestamp_204249.zip)

**Comment by UneCloud** [comment] 2024-02-02 23:46
Hit the bug once again today. However, it looked more like #26879 this time visually in gameplay.
But when I looked through the replay it still visually looked exactly like the replay I've sent before. (cursor getting stuck to specific coords and having a stroke trying to follow the real cursor position)

Exact timestamp VOD - LOG : 01:21:49 -  20:51:18

Twitch VOD:
https://www.twitch.tv/videos/2051165512?t=01h21m45s 

YT reupload in case the VOD gets deleted: 
https://www.youtube.com/watch?v=ytQkrWiOMPg&t=4905
 
 
 [26843_timestamp_205718.zip](https://github.com/ppy/osu/files/14146495/26843_timestamp_205718.zip)
 [26843_03022024.zip](https://github.com/ppy/osu/files/14146601/26843_03022024.zip)

**Comment by Vince7778** [comment] 2024-02-05 02:43
Here's a replay and video where it happened to me (reported in #26988)

approx. 2:42 in the replay, on [this map](https://osu.ppy.sh/beatmapsets/1456709#osu/2993974)

[replay.zip](https://github.com/ppy/osu/files/14159873/replay.zip)

https://github.com/ppy/osu/assets/32619800/773d8db6-bda8-4257-a791-19f46819f7ff

**Comment by layfiel** [comment] 2024-02-07 15:16
Just encountered a similar bug but mine looks slightly different. There was no visual indication anything strange was happening like in the videos/replays above but I instantly failed. When I look at the replay after the break at 1:14 I hit the first set of notes and then it looks like I simply stopped playing, however I did hit every note until I failed. Sadly I don't have a liveplay.
[replay.zip](https://github.com/ppy/osu/files/14195644/replay.zip)

**Comment by bdach** [comment] 2024-02-23 07:58
Looking at logs again:

```
2024-01-30 20:42:48 [verbose]: Playback discrepancy detected (1 of allowed 5): 16,617.5 vs 35,375.2
```

```
2024-01-30 21:38:20 [verbose]: Playback discrepancy detected (1 of allowed 5): 10,003.9 vs 21,863.7
```

which lines up with the times reported in the OP, and as such this is probably indeed a duplicate of https://github.com/ppy/osu/issues/26879. Goes for @Vince7778's case too. Not sure about @layfiel's because no logs.

**Closed by bdach** 2024-02-23 07:58 UTC
Labels: ruleset/osu!, area:gameplay
