### ISSUE TITLE
Images and videos don't actually appear in the release notes

### ISSUE THREAD

**Issue by novialriptide** [ppy/osu#20051] opened 2022-08-31 18:51 UTC
### Type

Cosmetic

### Bug description

Just go to the release notes section of osu!lazer and scroll to version 2022.821.0

### Screenshots or videos

![image](https://user-images.githubusercontent.com/35881688/187756962-7d4329c9-eaa7-45b5-a0a4-25ad908ef481.png)
![image](https://user-images.githubusercontent.com/35881688/187759466-e9a4ca73-1dc9-4a9c-bb97-fe81ba2c2ef2.png)

### Version

2022.821.0

### Logs

[network.log](https://github.com/ppy/osu/files/9464125/network.log)
[performance.log](https://github.com/ppy/osu/files/9464126/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9464127/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9464128/updater.log)
[database.log](https://github.com/ppy/osu/files/9464129/database.log)

**Comment by Joehuu** [comment] 2022-08-31 18:54
Duplicate of https://github.com/ppy/osu/issues/12465

**Closed by Joehuu** 2022-08-31 18:54 UTC
