### ISSUE TITLE
Spinner Bug

### ISSUE THREAD

**Issue by danielallen939** [ppy/osu#22348] opened 2023-01-22 12:26 UTC
### Type

Other

### Bug description

With the spinner you can completely skip spinning your cursor around the centre. Instead you can just move your mouse left to right. I don't know if this is intended but it really seems like a big issue and needs to be fixed. In the stable version of Osu you cant do this. I hope this gets fixed

### Screenshots or videos

https://user-images.githubusercontent.com/71334888/213915592-422c55d5-b255-46d8-954b-1edec305fe54.mp4

### Version

2023.121.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10474408/database.log)
[input.log](https://github.com/ppy/osu/files/10474409/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10474410/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10474411/network.log)
[performance.log](https://github.com/ppy/osu/files/10474412/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10474414/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10474415/updater.log)

**Comment by FriendsNone** [comment] 2023-01-22 14:32
I've just found out about this as well. Even tried different skins, and toggling the classic mod in lazer. Below is a screen record of recreating the bug in both stable and lazer, no mods and in the classic skin

[Beatmap #371128](https://osu.ppy.sh/beatmapsets/371128#osu/814293)

stable
https://user-images.githubusercontent.com/4056272/213921123-94b0c5fb-d81a-4f8d-8971-99f29a292528.mp4

lazer
https://user-images.githubusercontent.com/4056272/213921139-98e0d91d-65be-401f-a34a-6a230f860d4d.mp4

lazer logs
[runtime.log](https://github.com/ppy/osu/files/10474619/runtime.log)
[network.log](https://github.com/ppy/osu/files/10474620/network.log)
[performance.log](https://github.com/ppy/osu/files/10474621/performance.log)
[updater.log](https://github.com/ppy/osu/files/10474622/updater.log)
[database.log](https://github.com/ppy/osu/files/10474623/database.log)

**Comment by Joehuu** [comment] 2023-01-22 20:30
Duplicate of https://github.com/ppy/osu/issues/8224

**Closed by Joehuu** 2023-01-22 20:30 UTC
Labels: ruleset:osu!, area:gameplay, type:input
