### ISSUE TITLE
Cant login.

### ISSUE THREAD

**Issue by CRAZECRAZE** [ppy/osu#12223] opened 2021-03-30 07:39 UTC
I've checked every single bug report about this but, nothing actually worked.

Its been like that for a while now, I cant log into my account using Lazer.

Whenever I'm trying to connect, it wont let me, when I press login, it shows that for like 1/10 of a second and then nothing, plus, whenever I start the client, it shows like 3 or 4 unknown errors? 

a picture and a small video showing the errors:
![image](https://user-images.githubusercontent.com/67030091/112951115-b0cd1a00-9143-11eb-9b72-c5eb5f445ade.png)

https://user-images.githubusercontent.com/67030091/112951454-0b667600-9144-11eb-9c8b-e60f5124e8ad.mp4

osu!lazer version: 2021.323.0

logs:
[network.log](https://github.com/ppy/osu/files/6227227/network.log)
[performance.log](https://github.com/ppy/osu/files/6227228/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6227229/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6227230/updater.log)
[database.log](https://github.com/ppy/osu/files/6227231/database.log)

**Comment by bdach** [comment] 2021-03-30 07:43
Duplicate of #12209

**Closed by bdach** 2021-03-30 07:43 UTC
