### ISSUE TITLE
Leaderboard placements are incorrect due to sorting by score ID, rather than date achieved (osu!lazer & osu!web)

### ISSUE THREAD

**Issue by Digitalfear117** [ppy/osu#27731] opened 2024-03-26 12:12 UTC
### Type

Game balance

### Bug description

In instances where two players achieve the same score on a map, osu! determines which score should be placed first based on score ID. This worked great in the old stable database where you could guarantee that score ID and date submission worked together in chronological order. However, when scores from the stable database were imported into the new lazer database, scores were not always imported in perfect chronological order. This causes leaderboard placements to be wrong.

Here is a map that exhibits this problem: https://osu.ppy.sh/beatmapsets/1980266#fruits/4288669

On this map in CtB on osu!stable, I achieved rank 1 on the map on October 21st, 2023 at 22:01, with a score of 16,581,981. Two days later on October 23rd, 2023 at 08:51, user Novoids achieved rank 2 on the map with an identical score of 16,581,981. After the switch to the lazer database on osu!web, our scores switched, with the site placing his score above mine.

In the old stable database, my score ID was [214575709](https://osu.ppy.sh/scores/fruits/214575709), and Novoids score was ID [214593084](https://osu.ppy.sh/scores/fruits/214593084)

In the new lazer database, my score ID became [1961650557](https://osu.ppy.sh/scores/1961650557), and Novoids score ID became [1961650466](https://osu.ppy.sh/scores/1961650466)

This is my hypothesis on why my score is rank 2 now on osu!web and osu!lazer, whereas on osu!stable my score is still rank 1 as it should be.

### Screenshots or videos

![IMG_4351](https://github.com/ppy/osu/assets/28713262/fc26fb36-1379-4aaf-883f-29bd69350666)

### Version

2024.312.1

### Logs

.

**Comment by bdach** [comment] 2024-03-26 12:20
duplicate of https://github.com/ppy/osu-web/issues/10922

**Closed by bdach** 2024-03-26 12:20 UTC

**Comment by Digitalfear117** [comment] 2024-03-26 12:24
Sorry, didn’t find anything searching in here, didn’t think to check ous!web’s github too
