### ISSUE TITLE
Gameplay components become unscalable (and start moving) after shrinking too much

### ISSUE THREAD

**Issue by ClanTX** [ppy/osu#20874] opened 2022-10-22 23:49 UTC
### Type

Game behaviour

### Bug description

When you try to shrink any gameplay element beyond positive values, it'll become impossible to scale back.
And if you try to scale back the bugged value, it'll start moving the component instead of scaling.

This happens with any gameplay element across both the song select and gameplay screens.

### Screenshots or videos

https://user-images.githubusercontent.com/70714793/197366158-2cedfb42-02a2-4ea7-9901-a04bc038c101.mp4

(audio does weird stuff bc pc bad)

### Version

2022.1022.0-lazer

### Logs

[performance-audio.log](https://github.com/ppy/osu/files/9845418/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9845419/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9845420/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9845421/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9845422/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9845423/updater.log)
[database.log](https://github.com/ppy/osu/files/9845424/database.log)
[network.log](https://github.com/ppy/osu/files/9845425/network.log)
[performance.log](https://github.com/ppy/osu/files/9845426/performance.log)

**Comment by ekrctb** [comment] 2022-10-23 05:01
Duplicate of #13398

**Closed by ekrctb** 2022-10-23 05:01 UTC

**Comment by ClanTX** [comment] 2022-10-23 11:34
> Duplicate of #13398

oh i didn't realize
glad i wasn't the first one noticing that bug then
