### ISSUE TITLE
offset goes broken overtime when osu!lazer is open

### ISSUE THREAD

**Issue by Pallid3** [ppy/osu#26842] opened 2024-01-30 21:31 UTC
### Type

Game behaviour

### Bug description

It seems like, when osu!lazer is open for a while, then game and music desyncs/offsets.
You can clearly hear that, hitsounds are off when automod plays in lazer:
https://www.youtube.com/watch?v=7f5dgspK8OU

It fixes itself if I restart osu!lazer, but it always comes back after some playing and makes game basically unplayable.
I have notice that bug for basically entire time i have tired out lazer, but I had simple test map right now, so I could make video showing the bug.

### Version

2024-130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14104173/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-30 21:45
Duplicate of https://github.com/ppy/osu/issues/26237

**Closed by bdach** 2024-01-30 21:45 UTC
