### ISSUE TITLE
Multiplayer username overlapping chat in time shifted room

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#4316] opened 2019-02-23 00:33 UTC
**Describe your problem:**

The usernames in the chat of a time shifted multiplayer room can cause overlapping.

**Screenshots or videos showing encountered issue:** 

![picture](https://puu.sh/CQjeG/15857e0b82.png)

**osu!lazer version:**

[2019.216.0](https://github.com/ppy/osu/tree/2019.216.0)

**Logs:**

Not needed.

**Comment by AltenGD** [comment] 2019-02-23 01:00
Seems to be a duplicate of #2819

**Closed** 2019-02-23 06:01 UTC
