### ISSUE TITLE
Discrepancy in color between background tournament video playing in tournament client and any other video player

### ISSUE THREAD

**Issue by zAngarn** [ppy/osu#31011] opened 2024-12-08 20:21 UTC
### Type

Other

### Bug description

The title is pretty self-explanatory. We found this when trying to get the gfx for our tournament working when we noticed that the colors where not the same (The one we wanted is 'hex: ec675d')

### Screenshots or videos

![5AE4C143-AF93-414A-85D0-09CFB6ADF9B2](https://github.com/user-attachments/assets/1a083ff8-2601-41b1-9dc1-a837e4d20995)
 
[Background video that we were using](https://drive.google.com/file/d/1UdvorIgY0XQIE2mdEaeQCkftqi8jSwhL/view?usp=sharing)

### Version

2024.1115.3

### Logs

[logs.zip](https://github.com/user-attachments/files/18053836/logs.zip)

**Comment by bdach** [comment] 2024-12-08 20:47
Duplicate of https://github.com/ppy/osu-framework/issues/6402, probably

**Closed by bdach** 2024-12-08 20:47 UTC
