### ISSUE TITLE
Scaling of note speed at vertical resolution in taiko causes abusable behaviour for Flashlight

### ISSUE THREAD

**Issue by zethz161** [ppy/osu#22508] opened 2023-02-03 10:15 UTC
### Type

Game behaviour

### Bug description

(credits to [Cynplytholowazy](https://osu.ppy.sh/users/3901754) for raising this up to me, this is initially raised for score abuse in beatmap Spotlights but it is a huge gameplay issue that could extend into normal ranked gameplay)

starting from changes addressed in lazer update 2023.121.0, taiko allows scaling of playfield for resolution ratio below 16:9 to mimic how resolution works in stable taiko and where a lot of players (including prominent top players) are really used to (4:3 players as they're called, takes up a significant portion of top players in the game). 
![image](https://user-images.githubusercontent.com/69066569/216572146-ea77983c-fb54-4cdb-9b07-e7d72fd5a28b.png)

however, the scaling down of resolution in lazer works differently in that it also scales down the relative note speed (i will refer to as sv after this point) of the entire chart so that the amount of notes stayed the same on the screen. this creates an issue which could be abusable for gaining advantage in leaderboards and ESPECIALLY in Spotlights

if a player were to play lazer in a vertical or near vertical resolution (Cynply used something like 1:1.8 in his example), it makes flashlight basically obsolete because almost all notes will be visible within the area of visibility for flashlight, as shown in the first image below (courtesy of Cynply). this, combined with the ability to skin the taiko notes to different sizes, makes it an easily abusable way to gain score advantage in competitive leaderboards or playlists like Spotlights, as shown in 2nd image below.
![image](https://user-images.githubusercontent.com/69066569/216573577-2ae2e766-e878-4efc-adb7-45dc9fe41bcb.png)
![image](https://user-images.githubusercontent.com/69066569/216574131-3cc707e0-cab2-4fcb-b592-641f81f51082.png)

### Version

2023.121.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/10577925/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10577927/updater.log)
[database.log](https://github.com/ppy/osu/files/10577928/database.log)
[input.log](https://github.com/ppy/osu/files/10577929/input.log)
[network.log](https://github.com/ppy/osu/files/10577930/network.log)
[performance.log](https://github.com/ppy/osu/files/10577931/performance.log)

**Comment by zethz161** [comment] 2023-02-03 10:24
UPDATE

Cynply has also tested HDFL on this setup (HDFL is widely considered as memorisation mod combo in taiko because HD hides the visibility of the first half or so of the playfield, and FL hides the rest, which makes no notes visible AT ALL in any given moment. however, under the above setup (vertical resolution + modified skin with small objects), HDFL behaves almost exactly like HD because of how big the FL visibility area gets in vertical resolution, which also makes it abusable in leaderboard and playlists
![image](https://user-images.githubusercontent.com/69066569/216576226-43cf6994-4eeb-4e09-ab33-d54e2dbe94c7.png)

**Comment by sw1tchbl4d3r** [comment] 2023-02-03 13:50
This is already fixed as of #22325 and will be part of the next release.

**Comment by zethz161** [comment] 2023-02-03 13:56
![image](https://user-images.githubusercontent.com/69066569/216621256-50c4f0f6-9cc8-47e7-95e0-d1d3cd67f81d.png)

**Comment by bdach** [comment] 2023-02-03 17:57
No reason to keep this open if the issue is fixed. The fact that this is abusable is duly noted.

**Closed by bdach** 2023-02-03 17:57 UTC
Labels: ruleset:osu!taiko, area:gameplay
