### ISSUE TITLE
Text goes off-screen when opening link which is too long

### ISSUE THREAD

**Issue by StalkyBoi43815** [ppy/osu#27196] opened 2024-02-16 16:27 UTC
### Type

Cosmetic

### Bug description

When you open a link and the link is too long, the link goes off screen. Similar behaviour is known, but not in English.

### Screenshots or videos

![Screenshot_20240216_171840](https://github.com/ppy/osu/assets/148560144/10bb78ab-81f4-4d8d-b423-3ca56c12b2ea)

### Version

2024.131.0 Lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14313446/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-02-16 16:28
Duplicate of https://github.com/ppy/osu/issues/10085. Please search next time.

**Closed by frenzibyte** 2024-02-16 16:28 UTC

**Comment by StalkyBoi43815** [comment] 2024-02-16 16:37
> Duplicate of #10085. Please search next time.

I did search but I didn't find that. Thanks for the heads up.
