### ISSUE TITLE
Keybind allowing for double input

### ISSUE THREAD

**Issue by C9Glax** [ppy/osu#5750] opened 2019-08-17 23:05 UTC
You are able to bind a single key (for example "x") to Left button as well as Right button at the same time.
Through this you are able to "click" twice as fast.
![image](https://user-images.githubusercontent.com/13404778/63218126-35784980-c154-11e9-92e1-ca11e8cee00b.png)

**Comment by iiSaLMaN** [comment] 2019-08-17 23:06
Duplicate of #5089

**Comment by iiSaLMaN** [comment] 2019-08-17 23:08
> Through this you are able to "click" twice as fast.

Afaik, it doesn't make a slightest change if you bind 2 buttons to 1 key, it'll just check if one of these buttons was hit for the current hit object.

**Closed** 2019-08-17 23:24 UTC
