### ISSUE TITLE
Database reset failures still occurring in some cases

### ISSUE THREAD

**Issue by NexisLexis** [ppy/osu#2816] opened 2018-06-15 15:55 UTC
This has been happening in the past previous builds I've installed. 
I have also been trying to run osu!lazer as an admin but they resulted the same.
[database.log](https://github.com/ppy/osu/files/2106692/database.log)
[runtime.log](https://github.com/ppy/osu/files/2106693/runtime.log)

**Comment by LittleEndu** [comment] 2018-06-15 16:16
Duplicate of all the other database failure issues. If you want it fixed quick then just delete ``client.db`` in ``%appdata%\osu`` and when you then run the game new database will be built.

**Comment by peppy** [comment] 2018-06-15 16:17
Deleting the database will not help us resolve this issue. Please do not suggest this.

**Comment by NexisLexis** [comment] 2018-06-16 03:56
Hi I've recently just updated, still the same results. Here are the updated logs.
[database.log](https://github.com/ppy/osu/files/2107855/database.log)
[runtime.log](https://github.com/ppy/osu/files/2107856/runtime.log)

**Comment by peppy** [comment] 2018-06-16 04:19
Thanks, that is helpful. Can you now try deleting `client.db` and see if it recreates it correctly (as suggested just above)?

**Comment by NexisLexis** [comment] 2018-06-16 04:35
It finally worked because of that. Thanks!

**Comment by peppy** [comment] 2018-06-16 04:39
Leaving this one open pending further investigation on why the purging returned "success" when it didn't seem to work.

**Comment by peppy** [comment] 2018-06-28 10:10
This needs further investigation and testing; moving forward to July.

**Comment by peppy** [comment] 2018-08-03 10:46
This has been resolved (#3109).

**Closed by peppy** 2018-08-03 10:46 UTC
Labels: database, startup crash
