### ISSUE TITLE
Crash when dragging in editor timeline

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14210] opened 2021-08-10 13:04 UTC
The game crashes when i drag in the editor timeline while the song is playing. I can reproduce this consistently

**video:** https://www.youtube.com/watch?v=HA1_egZUvXM
**osu!lazer version:** 2021.809.0-lazer

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6961811/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6961812/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6961813/updater.log)
[database.log](https://github.com/ppy/osu/files/6961814/database.log)
[network.log](https://github.com/ppy/osu/files/6961815/network.log)

**Comment by jai-x** [comment] 2021-08-10 13:23
Is this happening for every beatmap or just that specific one? If it's just that specific one would you be able to upload/link the beatmap in this issue thread please?

**Comment by Pennek** [comment] 2021-08-10 13:27
I can make it happen on a lot of different maps

**Comment by Pennek** [comment] 2021-08-10 16:47
Here are some examples. These don't crash as fast/reliably as the completely new map i made but still do at some point https://osu.ppy.sh/beatmapsets/1093465
https://osu.ppy.sh/beatmapsets/995205

Here are logs showing a crash on one of them [runtime.log](https://github.com/ppy/osu/files/6963130/runtime.log)

**Comment by frenzibyte** [comment] 2021-08-10 23:14
I've went through both beatmaps on the same exact difficulties in the logs and have been dragging for a while now, yet I can't reproduce. I was testing this on macOS so it's probably going to be Windows-specific as mentioned above, or even CPU-specific possibly? could you state yours.

**Comment by Pennek** [comment] 2021-08-11 10:47
I'm using an AMD Ryzen 7 3700X

**Comment by bdach** [comment] 2021-08-11 17:50
I've tried again, this time on windows and latest `master`, and could not reproduce this again.

Not impossible that this has been since fixed in a non-transparent manner by one of the BASS fixes, but all in all without a reliable repro I cannot possibly see what the proper resolution here would be.

**Comment by Pennek** [comment] 2021-08-13 14:41
Is there anything I can do provide that might make this easier to figure out?

**Comment by bdach** [comment] 2021-08-13 19:19
Difficult to say. I'd try the next release first and see if any of the BASS fixes also happen to fix this by some chance. If it still happens after that please let us know.

**Comment by Pennek** [comment] 2021-08-16 17:38
I've tested with version 2021.815.0-lazer and it seems to have fixed the issue. Closing for now

**Comment by Velyro** [comment] 2021-12-20 21:35
I seem to be getting a very similar issue and it happens on every map with varying amounts of time I have to spend dragging. The one difference is that it only happens when the song is **not** playing.

Logs:
[network.log](https://github.com/ppy/osu/files/7748035/network.log)
[performance.log](https://github.com/ppy/osu/files/7748036/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7748037/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7748038/updater.log)
[database.log](https://github.com/ppy/osu/files/7748039/database.log)

PC Specs:
![image](https://user-images.githubusercontent.com/30195720/146835416-244c82ad-2fab-49dd-8872-6b06d8c9b9bd.png)

Reproduction steps: pick any random map, edit it, pause the song, and drag the timeline for a bit, (depending on the map, this seems to take anywhere between a second and 20 seconds) eventually the game freezes and you have to close it with the task manager. I think it may possibly have something to do with which way the cursor is pointing on the timeline when the game freezes, but I'm not sure.

Video of freeze: https://youtu.be/Ok0D3ZMmpuk

**Comment by bdach** [comment] 2021-12-20 21:38
I've also had this happen to me at least twice today. Reopening for investigation.

**Comment by bdach** [comment] 2021-12-21 12:54
Upon closer investigation it appears to be a native deadlock on a mixer flush framework-side (https://github.com/ppy/osu-framework/blob/c81042ffaa1a1f37cce981ef0b313132ed6a82e7/osu.Framework/Audio/Mixing/Bass/BassAudioMixer.cs#L427-L431).

As it also turns out the native libs haven't been pushed out since August (last nativelibs package). On checking with the latest versions pulled from un4seen I can no longer reproduce, and they're the same versions as the bump in https://github.com/ppy/osu-framework/pull/4903 lists, so the hope would be that a nativelibs release and bump will fix this.

**Comment by bdach** [comment] 2021-12-27 09:06
Going to tentatively close this one again after the nativelibs bump. Will reopen if this gets reported again.

**Closed by bdach** 2021-12-27 09:06 UTC
Labels: area:editor, type:reliability, priority:1
