### ISSUE TITLE
catch hit lighting slows down the speed of falling fruits

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#10070] opened 2020-09-06 08:18 UTC
**Describe the bug:** when hit lighting is turned on, every time you catch a fruit, the speed of fruits falling temporarily slows down (ala slider velocities in mania). i suspect this is because of draw fps drops but i dont really have a clue.

**Screenshots or videos showing encountered issue:**
https://drive.google.com/file/d/1efIPYDzz69hJ-RIqrCwfwMNbpGSeqX8L/view?usp=sharing (auto)
https://drive.google.com/file/d/16fClTgOC0FzX_rynnadv8IjpjVOjXGCS/view?usp=sharing

**osu!lazer version:** 2020.903.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5179253/runtime.log)

**Comment by peppy** [comment] 2020-09-06 11:00
What kind of frame rate are you running at when this happens?

**Comment by enoslayd** [comment] 2020-09-06 11:09
In my original post it is unlimited but it also happens on other frame rates no matter if it is multi or single thread

**Comment by bdach** [comment] 2020-09-06 11:12
Mind capturing another video with the full fps graph? (press <kbd>Ctrl</kbd>+<kbd>F11</kbd> twice if the graph is off or once if it is displayed as in the videos in the first post)

Might also try to open performance statistics (<kbd>Ctrl</kbd>+<kbd>F2</kbd>) but I'm not expecting to see much there.

**Comment by enoslayd** [comment] 2020-09-06 11:33
Is it ok if i use single thread in full fps graph? My laptop lags when displaying that graph in multi thread.

**Comment by bdach** [comment] 2020-09-06 11:34
as long as the issue is still visible in single thread with the graph on, yes

**Comment by enoslayd** [comment] 2020-09-06 13:08
https://drive.google.com/file/d/1o5_QnnbKYCdIP9l02ZO3_udcC1kLAL2O/view?usp=sharing

sorry for no audio since my surroundings is so noisy. one thing that i noticed just now is that it happens worse when catching droplets or juice (i dont know the term(s))

**Comment by smoogipoo** [comment] 2020-09-07 05:39
Gonna assume it's your GPU that's struggling here. runtime.log says it supports GL 2.1, which probably indicates it's using some forward-compatibility model.

Please provide your [dxdiag output](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe).

**Comment by enoslayd** [comment] 2020-09-07 05:42
@smoogipoo you're right. Ill provide the dxdiag later

**Comment by enoslayd** [comment] 2020-09-07 06:24
[DxDiag.txt](https://github.com/ppy/osu/files/5181355/DxDiag.txt)
Processor: Intel Pentium P6200
Memory: 6GB
GPU: Intel 1st gen (i think??) HD Graphics (OpenGL 2.1)

**Comment by smoogipoo** [comment] 2020-09-07 06:52
There's nothing that can be actioned on at this point so I'm going to close this issue. I've ordered a laptop that has similar specs so it can be used for future testing/performance improvements.

**Closed by smoogipoo** 2020-09-07 06:52 UTC
Labels: area:gameplay, ruleset:osu!catch, type:performance

**Comment by enoslayd** [comment] 2020-09-07 07:36
Ok thank you very much
