### ISSUE TITLE
Blank profile picture after watching a replay

### ISSUE THREAD

**Issue by adryzz** [ppy/osu#12864] opened 2021-05-19 10:06 UTC
**Describe the bug:** 
Take any map, go on global leaderboards, and select any replay.
The user's profile picture is there.
Play the replay, and the results screen will have no profile picture.
**Screenshots or videos showing encountered issue:** 

### Before:
![osu_2021-05-19_13-57-06](https://user-images.githubusercontent.com/46694241/118794531-f41d4c80-b899-11eb-9e95-eaf02c31fca3.png)

### After:
![osu_2021-05-19_13-56-47](https://user-images.githubusercontent.com/46694241/118794671-1b741980-b89a-11eb-9359-836fe079d132.png)

**osu!lazer version:** 
2021.515.0
**Logs:**
shouldn't be needed but here
[database.log](https://github.com/ppy/osu/files/6507760/database.log)
[network.log](https://github.com/ppy/osu/files/6507761/network.log)
[performance.log](https://github.com/ppy/osu/files/6507762/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6507763/runtime.log)

**Comment by bdach** [comment] 2021-05-19 10:07
Duplicate of #5966

**Closed by bdach** 2021-05-19 10:07 UTC

**Comment by adryzz** [comment] 2021-05-19 10:11
I checked that issue before, and i thought it was separate but it's the same t's `user_id` linking issue
