### ISSUE TITLE
Holding note while restarting causes error in osu!mania

### ISSUE THREAD

**Issue by Minfest325** [ppy/osu#21454] opened 2022-11-29 15:53 UTC
### Type

Crash to desktop

### Bug description

Holding note while restarting causes error.
Holding 2 or more notes causes crashing.

### Screenshots or videos

https://user-images.githubusercontent.com/80772245/204575468-8c794d42-d057-4fef-adb2-0b2c156e4d49.mp4

https://user-images.githubusercontent.com/80772245/204575484-511d5e20-dea6-4ddc-a615-fa2e3c02bff3.mp4

### Version

2022.1123.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10114661/database.log)
[input.log](https://github.com/ppy/osu/files/10114662/input.log)
[network.log](https://github.com/ppy/osu/files/10114664/network.log)
[performance.log](https://github.com/ppy/osu/files/10114665/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10114666/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10114667/updater.log)

**Comment by bdach** [comment] 2022-11-29 16:11
There is no exception trace in the logs attached. Please reproduce the issue again and reupload fresh logs. Do not restart the game after reproducing this bug.

**Comment by Minfest325** [comment] 2022-11-29 16:16
[database.log](https://github.com/ppy/osu/files/10114903/database.log)
[input.log](https://github.com/ppy/osu/files/10114904/input.log)
[network.log](https://github.com/ppy/osu/files/10114905/network.log)
[performance.log](https://github.com/ppy/osu/files/10114906/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10114907/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10114908/updater.log)

**Comment by bdach** [comment] 2022-11-29 16:34
Duplicate of #19908

**Closed by bdach** 2022-11-29 16:34 UTC
Labels: missing details
