### ISSUE TITLE
Beatmap track restarts to the preview point on track ending

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5672] opened 2019-08-10 18:19 UTC
**Describe the bug:** when song in song select ends it should start at start of the song not preview point

**Comment by iiSaLMaN** [comment] 2019-08-10 18:24
Please change the title to be descriptive a bit: `Beatmap track restarts to the preview point on track ending`

**Comment by Aergwyn** [comment] 2019-08-10 18:42
It was intentionally changed to restart at preview point according to stable.

**Comment by ticotaco72** [comment] 2019-08-10 18:42
but when starting again it should go at start of the song i think

**Comment by Joehuu** [comment] 2019-08-10 21:57
Duplicate of #4684. Should continue playing at the same point in gameplay, not the beginning.

**Comment by Joehuu** [comment] 2019-08-10 21:58
Whoops wrong thought

**Comment by peppy** [comment] 2019-08-11 04:10
Closing as duplicate of #4684.

**Closed by peppy** 2019-08-11 04:10 UTC

**Comment by ticotaco72** [comment] 2019-08-11 08:28
It is not a duplicate as I mean here case that you aren't playing but you are in song select long enough that whole song has played and starts again

**Comment by peppy** [comment] 2019-08-11 08:39
this already matches stable, which i believe is correct for now.
