### ISSUE TITLE
Followpoints render incorrectly on some imported skins

### ISSUE THREAD

**Issue by reflect-git** [ppy/osu#6214] opened 2019-09-23 00:09 UTC
**Describe the bug:** 
Compared to stable, some imported skins have followpoints that render differently/incorrectly.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=rz4bQ-X9E9I

**osu!lazer version:** 
2019.919.0

**Skin:** 
[Comfort Skin.zip](https://github.com/ppy/osu/files/3640295/Comfort.Skin.zip)

**Comment by reflect-git** [comment] 2019-09-23 00:13
Now, I am completely clueless when it comes to skinning, but it seems to only happen with skins that use followpoints like this:
[image](https://user-images.githubusercontent.com/18745452/65396524-b9ef6500-ddaf-11e9-9f61-1adf84849b75.png)

However, skins that use them like this seem to work fine:
[image2](https://user-images.githubusercontent.com/18745452/65396565-0aff5900-ddb0-11e9-8b68-080ce2ccb2e5.png)

**Comment by iiSaLMaN** [comment] 2019-09-23 00:24
> Now, I am completely clueless when it comes to skinning, but it seems to only happen with skins that use followpoints like this:
> [image](https://user-images.githubusercontent.com/18745452/65396524-b9ef6500-ddaf-11e9-9f61-1adf84849b75.png)
> 
> However, skins that use them like this seem to work fine:
> [image2](https://user-images.githubusercontent.com/18745452/65396565-0aff5900-ddb0-11e9-8b68-080ce2ccb2e5.png)

I guess it's because of the animation? the broken one has 5 empty frames on the follow point animation while the working one has only 1 empty frame, can you check whether removing the empty frames solves it?

**Comment by reflect-git** [comment] 2019-09-23 00:52
As said, I don't know how skinning works, so I might be doing it wrong.

That disclaimer aside, I tried deleting the end frames, all empty frames and just copy-pasting them from a working skin (yugen). Same results all around. If I deleted the empty frames without renaming the rest to being in order again, it just used the lazer default followpoints.

The way I did this was deleting the png files in the stable skin folder, renaming them if necessary, deleting all skins from lazer, and finally importing from stable. Again, this might be me doing it wrong.

I'm gonna upload a skin that works fine as well (previously mentioned yugen skin):
[- YUGEN FINAL - Widescreen.zip](https://github.com/ppy/osu/files/3640349/-.YUGEN.FINAL.-.Widescreen.zip)

**Comment by peppy** [comment] 2019-09-23 02:26
There is still a minor discrepancy in follow point animation of follow points because we have no separated paths for particle-containing skins vs non-particle-containing skins.

**Comment by bdach** [comment] 2020-02-17 20:51
This seems to have improved with the merge of #7746. The underlying reason seems to have been this framerate change:

https://github.com/peppy/osu/blob/544685be4863631b47df94f19d4f6307cb014d71/osu.Game/Skinning/LegacySkinExtensions.cs#L58-L71

Before, an animation playback rate of 60fps was assumed; after the PR was merged the playback rate is now such that all sprites get cycled in a second. Since follow point animations do not loop, custom animations that would end on transparent sprites would therefore animate too fast.

Closing as resolved; please leave a comment or reopen if there are still cases of this remaining. I couldn't reproduce with either skin from the original report.

**Closed by bdach** 2020-02-17 20:51 UTC
Labels: area:skinning, ruleset:osu!
