### ISSUE TITLE
Unpausing the game does not require you to put your cursor where it was if the game was paused via tabbing out

### ISSUE THREAD

**Issue by Hackattack242** [ppy/osu#11624] opened 2021-01-29 07:46 UTC
As the title says, when the game pauses due to tabbing out (alt tabbing or another program stealing focus) the game does not require you to go through the process of putting your cursor back where it was, like you normally would. I think part of the problem is that it does not pause immediately as I was actually able to tab out and back in once without it pausing.

Video [here](https://youtu.be/jZPvDh7RDfA) of me demonstrating. The black screen is me tabbing out, it takes a second for OBS to re-focus on osu! after tabbing back in.

osu! lazer 2021.129.0

I don't really think they will be helpful, but here are my logs:

[network.log](https://github.com/ppy/osu/files/5892300/network.log)
[performance.log](https://github.com/ppy/osu/files/5892301/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5892302/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5892297/updater.log)
[database.log](https://github.com/ppy/osu/files/5892298/database.log)

**Comment by peppy** [comment] 2021-01-29 08:48
Are you able to upload the video directly to github (or somewhere apart from youtube)? I can't view it due to copyright issues. Alternatively, upload without an audio track.

**Comment by Hackattack242** [comment] 2021-01-29 18:27
Sorry about that. [Here's](https://youtu.be/fWwlGnp2XuQ) a version with no audio and no copyright claim on youtube.

**Comment by frenzibyte** [comment] 2021-01-29 18:38
Can reproduce as well, will investigate through.

**Comment by frenzibyte** [comment] 2021-01-30 00:25
This is happening because of the hold delay between "user focusing out of the game" and "the player pausing", making the gameplay cursor hide before the player is paused, which causes `LastFrameState` to be `Hidden`, and therefore not show the resume overlay, due to the conditions in there (`LastFrameState == Visible` for avoiding showing resume overlay when the pause is done by the user manually moving to the hold-for-menu button, in which case the gameplay cursor will become hidden):https://github.com/ppy/osu/blob/1793385e96270a9b07050845b37b14fde04fe5c5/osu.Game/Rulesets/UI/DrawableRuleset.cs#L217-L224

There are two ways to fix this, either:
 1. not apply the hold delay to pausing on cases like alt-tabbing
 2. or not let the game cursor hide when alt-tabbing. 

not sure what fix to apply, I would personally go with (1) as it feels incorrect to delay it, but that's just my opinion.

**Comment by peppy** [comment] 2021-01-31 04:57
I would say the second is the correct resolution? There's no reason the gameplay cursor should become hidden when the window focus is lost (I'm not even sure how this would be happening). It should be exclusively managed by the gameplay logic.

**Comment by frenzibyte** [comment] 2021-01-31 06:48
For reason why, it's because when the window focus is lost, all hovered drawables become unhovered, causing the cursor target to switch back to the menu cursor and therefore hide the gameplay cursor:
https://github.com/ppy/osu/blob/1a55d92c719c0d2db2eb0d2c977be242fe2afda8/osu.Game/Graphics/Cursor/MenuCursorContainer.cs#L61-L78

My current fix is to basically early-return if `host.Window.CursorInWindow` became false, but will see if I can fix it at a gameplay level.

**Comment by frenzibyte** [comment] 2021-02-04 11:13
Looking back at this, not making the gameplay cursor hide when focus lost doesn't seem like a simple thing to do, as the cursor can potentially be in a place where menu cursor could take over (like hold-for-menu button), and therefore cause a resume overlay to appear in that place. 

I'm all in favour of just making the pause instant on focus lost, I can't see any reason why it's delayed to begin with, and just feels all incorrect to try fixing this issue by not updating `LastFrameState` on focus lost.

**Comment by peppy** [comment] 2021-02-04 11:15
Being able to potentially delay pause was something we wanted to have around as a gameplay balance measure (to help discourage pausing), but as we now have the setting to adjust the length that is less of a concern.

**Comment by Hackattack242** [comment] 2021-02-04 23:36
As a player, it feels really weird when it does not pause immediately upon losing focus.

**Closed** 2021-02-08 08:00 UTC
Labels: area:gameplay
