### ISSUE TITLE
Editor does not return to edit screen after map has finished in testing

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu#24407] opened 2023-07-29 12:40 UTC
### Type

Game behaviour

### Bug description

When previewing a map in the editor via the "Test!" button, if you preview until the map ends it will not kick you back to the editor, instead it will just sit there forever.

In the video attached I showcased both current lazer and stable behaviour, I felt this was more of an issue rather than a suggestion, but I may be wrong.

### Screenshots or videos

https://github.com/ppy/osu/assets/24534022/48a739c1-c138-433f-98e7-9f9d4a1a2e8e

### Version

2023.717.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12207160/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12207161/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12207162/updater.log)
[database.log](https://github.com/ppy/osu/files/12207163/database.log)
[input.log](https://github.com/ppy/osu/files/12207164/input.log)
[network.log](https://github.com/ppy/osu/files/12207165/network.log)

**Comment by bdach** [comment] 2023-07-29 13:54
Duplicate of https://github.com/ppy/osu/issues/17395

**Closed by bdach** 2023-07-29 13:54 UTC
