### ISSUE TITLE
Slider repeat arrows are drawn below hitcircles

### ISSUE THREAD

**Issue by Azureharp** [ppy/osu#7004] opened 2019-11-28 21:05 UTC
**Describe the bug:** 
The repeat arrows are drawn below hitcircles causing them to be impossible to see after the short fade in. Here is the shown map, this issue pops up a fair bit at the start in it https://osu.ppy.sh/beatmapsets/319375#osu/710881
**Screenshots or videos showing encountered issue:** 
![osu_2019-11-28_14-54-34](https://user-images.githubusercontent.com/42692316/69831577-8f76b980-11ef-11ea-91df-59be08e92b25.png)
![osu_2019-11-28_14-56-25](https://user-images.githubusercontent.com/42692316/69831580-956c9a80-11ef-11ea-89ee-e695b069610b.png)
**osu!lazer version:** 
2019.1128.0

**Comment by Joehuu** [comment] 2019-11-29 00:48
Duplicate of https://github.com/ppy/osu/issues/2147

**Closed by Joehuu** 2019-11-29 00:48 UTC
Labels: gameplay, graphics, skinning
