### ISSUE TITLE
Beatmap background sometimes not loading

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu#11141] opened 2020-12-10 11:27 UTC
**Describe the bug:** 
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/50285552/101764779-70597a00-3b1b-11eb-8883-3f0c693d6134.png)
https://youtu.be/ty5JIKjRuDg
**osu!lazer version:** 
https://github.com/PercyDan54/osu/tree/custom
(I belive this is not because of me)
**Logs:**
Not the log in the video, but a reproduced one
[performance.log](https://github.com/ppy/osu/files/5672302/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5672303/runtime.log)

**Comment by bdach** [comment] 2020-12-10 11:37
The background is not missing. The wedge is, as are carousel panels.

Please try reproducing on `master`. If this is still present on master, please attach a screenshot or video with the texture preview window open (ctrl-F3).

**Comment by smoogipoo** [comment] 2020-12-10 11:41
This is going to be because of web requests, things like avatar loads (via `OnlineStore.Get()`) will block a full BDL load thread.

**Comment by PercyDan54** [comment] 2020-12-10 11:45
> The wedge is also missing, as are carousel panels.
> 
> Please try reproducing on `master`. If this is still present on master, please attach a screenshot or video with the texture preview window open (ctrl-F3).
> 
> Also this is 99% not caused by the linked PR. Please don't guess blindly and leave the investigation to us.

Sometime the carousel is loaded but the bg isn't 
https://youtu.be/mZx6iP4RtQ0
![image](https://user-images.githubusercontent.com/50285552/101768024-098a8f80-3b20-11eb-8509-65afe80dca40.png)

**Comment by PercyDan54** [comment] 2020-12-10 11:45
> This is going to be because of web requests, things like avatar loads (via `OnlineStore.Get()`) will block a full BDL load thread. Notice how the rest of the game appeared right as the avatar popped in.

Seems you're right. The bg loaded when the avatar loaded

**Comment by peppy** [comment] 2020-12-15 04:15
The weird part here is that `DrawableAvatar` is correctly marked as `[LongRunningLoad]`, meaning it should not hold a thread on the main BDL load pool.

@PercyDan54 are you sure you don't have any custom code which could be causing this blocking? Are you able to reproduce on the latest `master`?

**Comment by PercyDan54** [comment] 2020-12-15 11:03
> The weird part here is that `DrawableAvatar` is correctly marked as `[LongRunningLoad]`, meaning it should not hold a thread on the main BDL load pool.
> 
> @PercyDan54 are you sure you don't have any custom code which could be causing this blocking? Are you able to reproduce on the latest `master`?

The second video is already reproduced on master

**Comment by peppy** [comment] 2020-12-15 11:10
No idea what's going on here then. Since you are reproducing this with a dev setup I'd recommend you do some more digging. Also confirm it still happens without the debug overlays visible (they have been prone to causing issues in the past).

**Comment by PercyDan54** [comment] 2020-12-15 11:26
> No idea what's going on here then. Since you are reproducing this with a dev setup I'd recommend you do some more digging. Also confirm it still happens without the debug overlays visible (they have been prone to causing issues in the past).

This only happens when the network stuck at recieving avatar. If the login request time out on the first time, The user will be shown as Guest and everything is normal

**Comment by smoogipoo** [comment] 2020-12-15 11:31
Fwiw I have been able to replicate this, but haven't looked into it. Should take 5 minutes with network conditioning.

It's likely not the LCA threadpool to worry about, it's the .NET threadpool. Spectator connecting takes time, as does other online store retrievals, and it's possible that something in song select waits on the threadpool at some point and is effectively deadlocked by these other processes also waiting on the threadpool.

**Comment by PercyDan54** [comment] 2020-12-15 11:34
A network.log:
`2020-12-15 11:33:20 [verbose]: ----------------------------------------------------------
2020-12-15 11:33:20 [verbose]: network Log for PercyDan (LogLevel: Debug)
2020-12-15 11:33:20 [verbose]: osu 0.0.0.0
2020-12-15 11:33:20 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 12 cores
2020-12-15 11:33:20 [verbose]: ----------------------------------------------------------
2020-12-15 11:33:20 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:23 [verbose]: Request to https://osu.ppy.sh/api/v2/me/ successfully completed!
2020-12-15 11:33:23 [verbose]: Performing request osu.Game.Online.API.Requests.GetSeasonalBackgroundsRequest
2020-12-15 11:33:23 [verbose]: Performing request osu.Game.Online.API.Requests.GetSeasonalBackgroundsRequest
2020-12-15 11:33:23 [verbose]: Spectator client connecting...
2020-12-15 11:33:24 [verbose]: Request to https://osu.ppy.sh/api/v2/seasonal-backgrounds successfully completed!
2020-12-15 11:33:25 [verbose]: Request to https://osu.ppy.sh/api/v2/seasonal-backgrounds successfully completed!
2020-12-15 11:33:25 [verbose]: Spectator client connected!
2020-12-15 11:33:28 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2020-12-15 11:33:30 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2020-12-15 11:33:30 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:31 [verbose]: Request to https://a.ppy.sh/17268434 successfully completed!
2020-12-15 11:33:32 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/osu successfully completed!
2020-12-15 11:33:32 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:33 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/taiko successfully completed!
2020-12-15 11:33:33 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:34 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/fruits successfully completed!
2020-12-15 11:33:34 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:37 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/mania successfully completed!
2020-12-15 11:33:37 [verbose]: Performing request osu.Game.Online.API.Requests.GetBeatmapRequest
2020-12-15 11:33:38 [verbose]: Request to https://osu.ppy.sh/api/v2/beatmaps/lookup?id=680919&checksum=b702d07167acbaabb68b6040aeb2b236&filename=xi%20-%20Blue%20Zenith%20(Asphyxia)%20[Easy].osu successfully completed!
2020-12-15 11:33:38 [verbose]: Performing request osu.Game.Online.API.Requests.GetMessagesRequest
2020-12-15 11:33:38 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/channels/7/messages successfully completed!
2020-12-15 11:33:38 [verbose]: Performing request osu.Game.Online.API.Requests.ListChannelsRequest
2020-12-15 11:33:39 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/channels successfully completed!
2020-12-15 11:33:39 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2020-12-15 11:33:39 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2020-12-15 11:33:42 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:43 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/osu successfully completed!
2020-12-15 11:33:43 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:43 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/taiko successfully completed!
2020-12-15 11:33:43 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:46 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/fruits successfully completed!
2020-12-15 11:33:46 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2020-12-15 11:33:46 [verbose]: Request to https://osu.ppy.sh/api/v2/users/17268434/mania successfully completed!
2020-12-15 11:33:46 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
`

**Comment by peppy** [comment] 2020-12-22 04:28
This is likely going to revolve around the internal implementation of threading in `WebRequest` (framework side) in that case - specifically the non-`async` usage of it, where each request is going to be eating a thread pool thread.

Not sure what the best path forward is... maybe the synchronous path needs to avoid this from occurring in the first place, though.

**Comment by peppy** [comment] 2021-02-16 10:34
@smoogipoo how recently did you repro this? i've tried with pretty serious throttling applied and can't seem to hit any kind of contention (and checking the threads view doesn't show anything piling up).

i'm wondering if it has something to do with difficulty calculation or a similarly rare operation that i may not be encountering with my beatmap library..

**Comment by PercyDan54** [comment] 2021-02-16 10:54
> @smoogipoo how recently did you repro this? i've tried with pretty serious throttling applied and can't seem to hit any kind of contention (and checking the threads view doesn't show anything piling up).
> 
> i'm wondering if it has something to do with difficulty calculation or a similarly rare operation that i may not be encountering with my beatmap library..

Seems even I can't reproduce it anymore
![image](https://user-images.githubusercontent.com/50285552/108053466-6bb7c180-7088-11eb-8c55-1e33fa504f90.png)

**Comment by smoogipoo** [comment] 2021-02-16 10:57
@peppy the easiest way is to put a `Thread.Sleep(30000)` in `OnlineStore.Get()` and `OnlineStore.GetAsync()` and go in and out of song select multiple times.

Here's the parallel stacks (should be obvious why):
![image](https://user-images.githubusercontent.com/1329837/108053730-26e45880-7091-11eb-8549-8b3860fa89fc.png)

**Comment by smoogipoo** [comment] 2021-02-16 11:02
Oh also I forgot to mention that you need to wait for the drawable avatar to start loading (so for you to log in), it doesn't repro before that time. I mention this because login for me always takes 5-10 secs.

**Comment by peppy** [comment] 2021-02-16 11:03
And you can reproduce non-LongLoad drawables being affected by this?

**Comment by smoogipoo** [comment] 2021-02-16 11:05
I'm just reproducing with song select... https://drive.google.com/file/d/1h9piZKtD4dgvFP90rkSxWWHLv59lqfRK/view?usp=sharing

**Comment by peppy** [comment] 2021-02-16 11:40
Thanks, can repro.

**Closed** 2021-02-19 01:28 UTC
Labels: area:song-select, framework-fix-required, type:online
