### ISSUE TITLE
Cursor can leave the screen boundaries in fullscreen mode

### ISSUE THREAD

**Issue by Squaduck** [ppy/osu#10465] opened 2020-10-09 23:57 UTC
**Describe the bug:** 
In fullscreen, I can drag my cursor way out of where it should be
**Screenshots or videos showing encountered issue:** 
![osu_2020-10-09_19-45-49](https://user-images.githubusercontent.com/55469508/95639891-2f37e180-0a68-11eb-8e45-c9883d0d76ca.jpg)
**osu!lazer version:** 
2020.1009.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/5358099/database.log)
[network.log](https://github.com/ppy/osu/files/5358100/network.log)
[performance.log](https://github.com/ppy/osu/files/5358101/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/5358102/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5358103/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5358096/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5358105/updater.log)

**Comment by Joehuu** [comment] 2020-10-10 02:52
Duplicate of https://github.com/ppy/osu-framework/issues/2247. Will just leave this issue open for visibility in this repo.

**Comment by YuwaneHaku** [comment] 2020-10-10 21:41
In borderless，it can happen, too.

**Comment by beastdestroyer** [comment] 2020-10-22 07:20
Still happens in latest lazer: 2020.1020.0

**Comment by peppy** [comment] 2020-10-22 07:32
Yes, it still happens. Because the issue is still open.

**Comment by imTCA** [comment] 2020-11-05 03:16
Kind of a weird bug imo.

**Comment by peppy** [comment] 2020-11-05 03:22
@imTCA if you continue making comments like this you will be blocked from this repo. please only post if you have something meaningful to add.

**Comment by imTCA** [comment] 2020-11-06 05:17
I actually (accidentally) reproduced this. When I (tried) to go to the left side of the screen (for something), it went off-bounds and I couldn't (for the life of me at least) get the cursor back. Kinda weird.

**Comment by Joehuu** [comment] 2020-12-03 23:09
Doesn't seem to be fixed in SDL (at least on Windows 10).

Before https://github.com/ppy/osu/pull/11060 was merged though, it would confine in a weird way (i.e. cursor will go off screen for ~one pixel, and moving it more off will make it appear fully on screen again.

**Comment by peppy** [comment] 2020-12-04 00:22
Solution here should be to force confine mode when fullscreen.

**Comment by peppy** [comment] 2020-12-04 04:18
I'm looking to fix this, but it would seem that behaviour is different within a VM as opposed to a native windows install. I am pretty sure that what we want to do is *remove* the "never" option from confine modes (as we generally always want to confine to the game window when running fullscreen).

If this is the case, we have two options: Either not exposing "never" at the osu!-side, or removing it as an option from framework. Not sure if there's a use case for it in other projects, though... can potentially be considered the behaviour one may want if making a FPS game for example, so it may be best to leave for now.

Will get to providing a solution and testing further when i'm at my windows box.

**Closed** 2020-12-04 12:52 UTC
Labels: fixed-in-sdl, high-priority, type:input
