### ISSUE TITLE
using the editor enlarge tool can result in a crash when you try to drag the tool through itself

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12047] opened 2021-03-17 23:29 UTC
when using the enlarge drag tool, it can be quite buggy when trying to size it smaller than the dimensions of the slider itself, so trying to change the dimensions of a slider so that it flips planes seems to result in freezes and crashes

https://clips.twitch.tv/SleepySparklingDeerKreygasm-kyqSEys925GauFCv as an example, i managed to replicate the game fully crashing around 3-4 times though (most other times it would just freeze for around 10-20 seconds)

this is easily replicable with just playing around with the tool, and from what i can see its a slightly different issue than moving the head to the tail of the slider because it seems like the editor cant deal with the enlargement zone being flipped/negative?

osu!lazer 2021.312.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6160315/database.log)
[network.log](https://github.com/ppy/osu/files/6160316/network.log)
[performance.log](https://github.com/ppy/osu/files/6160317/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6160318/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6160319/updater.log)

**Computer Specifications:** 
i have no clue what to put here but if you need specifics then lmk

**Comment by DeviousPanda** [comment] 2021-03-17 23:32
also by dragging the tool through i think it can also invert the dimensions of the tool but im not sure if this is intended or not https://clips.twitch.tv/WrongAdorablePhoneArgieB8-gO82DYq29y4fEpCH

**Comment by bdach** [comment] 2021-03-17 23:36
As long as the freezes/crashes occur only with perfect sliders, they are the same issue as #5538. Trying to make a perfect slider, when its three control points are nearly in a straight line, technically results in a circle of nearly infinite radius, causing memory exhaustion.

Stable deals with this by clamping the size of the slider to a reasonable maximum. I was looking at resolving this today, actually, but still have not come up with anything that works reliably.

The inversion is yet another thing entirely.

**Comment by peppy** [comment] 2021-03-25 09:42
Closing as duplicate of #5538. The inversion issue can be opened as a separate issue if you'd like. It's something we'll eventually need to tackle.

**Closed by peppy** 2021-03-25 09:42 UTC
Labels: area:editor, type:crash
