### ISSUE TITLE
Kindly remove or hide Navigation bar on Android

### ISSUE THREAD

**Issue by ModiFlasher** [ppy/osu#6597] opened 2019-10-25 02:41 UTC
Make own setting for that
![Screenshot_20191025-093925](https://user-images.githubusercontent.com/13981274/67539159-761fb080-f70b-11e9-96b7-ef70bf1711fe.jpg)

**Comment by iiSaLMaN** [comment] 2019-10-25 02:43
Duplicate of #6266

**Closed** 2019-10-25 02:43 UTC
