### ISSUE TITLE
a "beatmap preview "feature

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu#12773] opened 2021-05-12 17:14 UTC
**Describe the new feature:** 
like "ETT" before playing, you can press the shortcut key to put a preview window on the front desk to show the Beatmap, and the progress of the current music is the same.

This is cool, and also helps players preview the spectrum difficulty before starting the game.

![lazer1121](https://user-images.githubusercontent.com/52590027/118016683-446f4880-b388-11eb-90c3-94e601ae1d25.png)
![lazer2213](https://user-images.githubusercontent.com/52590027/118016848-77194100-b388-11eb-865a-8feb5c9dd0bf.png)

**Comment by Game4all** [comment] 2021-05-12 17:16
Dupe of / similar to  #9632

**Closed** 2021-05-12 17:16 UTC
