### ISSUE TITLE
Favourite Beatmaps list on profile appears as unfinished even though all maps are present. 

### ISSUE THREAD

**Issue by mmotkim** [ppy/osu#31269] opened 2024-12-25 13:20 UTC
### Type

Game behaviour

### Bug description

On Shadren's [profile](https://osu.ppy.sh/users/745494) in Lazer, the Favourite Beatmaps section shows up as unfinished even though all his 6 maps are present.
Upon clicking the Show More button it turns into a forever loading indicator

### Screenshots or videos

![osu!_QSbZ4SjqtB](https://github.com/user-attachments/assets/ffcf4509-713e-4273-8105-18cce103a230)

### Version

2024.1224.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18246083/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-12-25 22:08
Duplicate of https://github.com/ppy/osu/issues/9203

**Closed by Joehuu** 2024-12-25 22:08 UTC
Labels: area:overlay-user-profile
