### ISSUE TITLE
Sudden Death not working with this mod combination

### ISSUE THREAD

**Issue by Axzyk** [ppy/osu#28403] opened 2024-06-05 21:52 UTC
### Type

Game behaviour

### Bug description

I managed to drop misses with SD enabled using this mod combination.

Replays & screenshots attached

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/111462423/ecff500a-99db-445c-bce4-c7a419a93765)
![image](https://github.com/ppy/osu/assets/111462423/86c5eda6-6062-4fcb-9e1e-46627b3cd86e)

![image](https://github.com/ppy/osu/assets/111462423/0953e0af-6fea-4ae6-b376-189fa84a592d)

[[Akeno] playing Tanaka Hirokazu - C-TYPE (Arf) [A-TYPE] (2024-06-05_23-41).zip](https://github.com/user-attachments/files/15596983/Akeno.playing.Tanaka.Hirokazu.-.C-TYPE.Arf.A-TYPE.2024-06-05_23-41.zip)

[[Akeno] playing Tanaka Hirokazu - C-TYPE (Arf) [A-TYPE] (2024-06-05_23-44).zip](https://github.com/user-attachments/files/15596977/Akeno.playing.Tanaka.Hirokazu.-.C-TYPE.Arf.A-TYPE.2024-06-05_23-44.zip)

### Version

2024.521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15597001/compressed-logs.zip)

**Comment by ssz7-ch2** [comment] 2024-06-05 23:21
duplicate of https://github.com/ppy/osu/issues/20511

**Closed** 2024-06-06 06:56 UTC
