### ISSUE TITLE
Doesn't hide android navigation buttons

### ISSUE THREAD

**Issue by KoleckOLP** [ppy/osu#6266] opened 2019-09-25 18:42 UTC
the game doesn't go fully fullscreen (keeps the navigation buttons on screen)

![Screenshot_20190925-203858](https://user-images.githubusercontent.com/22729896/65629959-c0aaf180-dfd4-11e9-903b-82dadb6018be.png)

build: 2019.925.0 (official apk)
Android 7.0 on snapdragon 430

**Comment by ChibiSnoop** [comment] 2019-09-25 18:47
Well, I can relate(have tried it with buttons on) , but I'm playing with fullscreen mode(you can find it on settings, but if you Don't want to try New control scheme - I Don't know)

I think It's probably Android's issue

**Comment by KoleckOLP** [comment] 2019-09-30 17:18
it's not an android issue some apps hide the software buttons just fine, and my phone doesn't let me hide them permanently in settings.

**Comment by peppy** [comment] 2019-10-02 12:31
May be a regression (have a report of these not being visible on previous builds)

**Comment by KoleckOLP** [comment] 2019-10-13 09:48
still an issue on build 2019.1011.0

**Comment by bdach** [comment] 2019-10-13 10:37
There has been no work done regarding looking into this issue so far, as the Android release is not an immediate priority. Please be patient - you will know when this has been fixed once the issue is closed with a PR merge.

**Comment by Joehuu** [comment] 2019-10-29 02:22
Fixed in https://github.com/ppy/osu-framework/pull/2927.

**Closed by Joehuu** 2019-10-29 02:22 UTC
Labels: android, pending review
