### ISSUE TITLE
Replay bug

### ISSUE THREAD

**Issue by bartek518** [ppy/osu#8906] opened 2020-04-30 03:28 UTC
**Describe the bug:** 

When you put DT/NC mod on, you can adjust speed from 1.01x up to 2.0x. However, no matter what value between 1.01x - 2.00x do you choose, after you play a map and download replay of your play, in this replay speed will always be set to 1.5x
To replicate this bug : put on DT mod, adjust speed to 1.01, play any map, then download a replay of your play and watch it - you will clearly see that replay is being played faster than your original play.

(It works fine with wind up mod, seems like only DT/NC has this issue)

**osu!lazer version:** 
2020.429.0

**Comment by peppy** [comment] 2020-04-30 03:29
Duplicate of https://github.com/ppy/osu/issues/8569

**Closed by peppy** 2020-04-30 03:29 UTC
