### ISSUE TITLE
Map gets started when typing space in collection search textbox

### ISSUE THREAD

**Issue by Fabiano1337** [ppy/osu#28176] opened 2024-05-14 20:32 UTC
### Type

Game behaviour

### Bug description

**How to replicate**
1. Go into the Collection Search
2. Search something that has a space seperating words for example Double Time
3. Map starts as soon as the Space gets typed

**Expected Behaviour**
The map should not start when searching for collections and typing a space

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/28962347/84218eee-c3a0-4b62-b578-24f9fb6b5f3c)

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15313533/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-05-14 21:33
Duplicate of https://github.com/ppy/osu/issues/25769

**Closed by Joehuu** 2024-05-14 21:33 UTC
