### ISSUE TITLE
Redo/Undo Hotkeys not working as intended on different (HUN) Keyboard layout

### ISSUE THREAD

**Issue by RatinFX** [ppy/osu#25327] opened 2023-10-31 17:22 UTC
### Type

Game behaviour

### Bug description

On the Hungarian Keyboard layout, the positions of Z and Y are swapped.
In the Editor, this swap seems to be ignored, meaning Undo requires the user to press `Ctrl + Y` instead of `Ctrl + Z` (while Redo requires `Ctrl + Z`).

### Screenshots or videos

I set up a quick Slider and moved one of its points to showcase Undo in-game, on ENG, and on HUN layout with an on-screen keyboard.
- Keyboard layout change at 0:15

https://github.com/ppy/osu/assets/38523955/66131150-6554-4a2b-acab-9eed161532e4

### Version

2023.1026.0-lazer

### Logs

Nothing special in the logs but here they are:
[database.log](https://github.com/ppy/osu/files/13219516/database.log)
[network.log](https://github.com/ppy/osu/files/13219517/network.log)
[performance.log](https://github.com/ppy/osu/files/13219518/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13219519/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13219520/updater.log)

**Comment by bdach** [comment] 2023-10-31 17:27
Duplicate of #11143

**Closed by bdach** 2023-10-31 17:27 UTC
