### ISSUE TITLE
Add back the Offset Wizard

### ISSUE THREAD

**Issue by matteoturini** [ppy/osu#10572] opened 2020-10-21 13:10 UTC
**Describe the new feature:** 
The offset wizard from osu!stable

**Comment by frenzibyte** [comment] 2020-10-21 13:37
Based on what I get from this, this should be a duplicate of https://github.com/ppy/osu/issues/9866? if so, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Comment by smoogipoo** [comment] 2020-10-21 13:44
Yep. Closing as duplicate.

**Closed by smoogipoo** 2020-10-21 13:44 UTC
Labels: area:settings, type:audio
