### ISSUE TITLE
clicking escape in songselect doesn't clear search but exits instead

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5536] opened 2019-07-30 18:42 UTC
**Describe the bug:** when you type something in search at song select and you click escape to erase all of that when you get out of song select instead

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.730.0

[database.log](https://github.com/ppy/osu/files/3448388/database.log)
[network.log](https://github.com/ppy/osu/files/3448395/network.log)

[performance.log](https://github.com/ppy/osu/files/3448390/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3448391/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3448392/updater.log)

**Comment by Joehuu** [comment] 2019-07-30 18:54
Duplicate of #5177.

**Closed** 2019-07-30 18:54 UTC
