### ISSUE TITLE
Multiplayer for custom rulesets.

### ISSUE THREAD

**Issue by HeyItsJinx** [ppy/osu#12147] opened 2021-03-22 23:31 UTC
So to keep it simple. not short.

I play a custom ruleset as my main. im not one that cares for pp and will wait for it. i just want to suggest a multiplayer of some sort for custom rulesets where the user has to have the same game mode as the other to join it.

It gets lonely playing this as its very fun but if were against people it will liven custom rulesets up a bit.

**Comment by bdach** [comment] 2021-03-22 23:36
Duplicate of #11736

**Closed by bdach** 2021-03-22 23:36 UTC
