### ISSUE TITLE
Increase visibility of reverse arrow

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#5203] opened 2019-07-01 13:04 UTC
![](https://user-images.githubusercontent.com/19843905/60438434-f5dfb780-9c10-11e9-80a6-318e39ae954f.png)

In my opinion, the current design of the reverse arrow is underwhelming, making it barely visible on faster maps. It should be improved for the sake of readability and user experience during gameplay, as it starts getting annoying, because you can't see an important element of a hit object.

**Comment by peppy** [comment] 2019-07-01 13:05
I believe there is an updated design which involves the edge of the slider (the border) also having the repeatedness visible.

@arflyte

**Comment by Joehuu** [comment] 2019-07-01 13:05
Duplicate of #2147.

**Comment by peppy** [comment] 2019-07-01 13:06
Closing as duplicate. Assigned @arflyte to previous issue.

**Closed by peppy** 2019-07-01 13:06 UTC
