### ISSUE TITLE
Multiplayer spectator clocks begin to run in reverse on certain beatmaps

### ISSUE THREAD

**Issue by Taitranz** [ppy/osu#14162] opened 2021-08-07 22:38 UTC
**Describe the bug:** 

Hi

When spectating some maps in multiplayer hard rock with classic appears to break the spectating feature. This map and others with small hit circle appears to not function.
https://osu.ppy.sh/beatmapsets/38472#osu/123152
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2021.808.0
**Logs:**

**Comment by frenzibyte** [comment] 2021-08-07 23:08
I'm not exactly sure what your report is here, but there's an intermittent error in the track playback causing it to play from the middle when spectating, I'll investigate further.

**Comment by Taitranz** [comment] 2021-08-08 00:24
In multiplayer, on certain maps. If the player is using hard rock and classic mod together, The Osu map will not play any music but instead the game timer will begin to counter backward from 0 - -30,  this only occurs from the spectator's perspective also it appears the reducing the hit circle size increases the likeness of this occurring. I will try to replicate this bug and submit a video, but I can not at the moment.

**Comment by bdach** [comment] 2021-08-08 13:35
@frenzibyte it would have been *quite* helpful to list examples of maps on which you're seeing these "intermittent errors".

**Comment by frenzibyte** [comment] 2021-08-08 15:23
I wouldn't have thought it to be relevant to the beatmap track file itself as it also happens randomly on the same beatmap.

But I'll check again with one I remember to have had the issue.

**Comment by frenzibyte** [comment] 2021-08-09 01:51
As this is irrelevant from the BASSmix changes and specific to the multi-spectator logic, I've attempted to investigate through what's exactly happening, but it was too complicated that I only ended up getting few potentially useful info for further investigating and resolving this:

First of all, I can reliably reproduce the bug with this beatmap https://osu.ppy.sh/beatmapsets/212387#osu/499344.

The bug could be either the spectator clock running indefinitely backwards at -81ms elapsed time per frame, or stay still indefinitely.

Deep in the clock hierarchy, 
 - the `MasterGameplayClockContainer` is completely stopped (due to `MasterState` set to `TooFarAhead`).
 - the framed clocks containing the master's `AdjustableClock` (the first `HardwareCorrectionOffsetClock` in this case) have `CurrentTime` set to a time that's actually less than `LastFrameTime`, and therefore computes `ElapsedFrameTime` to be -81ms.

    they remain in this state indefinitely due to the gameplay clock container being stopped and therefore clocks not being processed.
 - the `CatchUpSpectatorPlayerClock` reads the source/master clock's `ElapsedFrameTime` (which is -81ms) and increases its time by it to "catch up", causing it to actually move far away and thus resulting in the spectator clock running backwards indefinitely.

One interesting part is that not stopping the `MasterGameplayClockContainer` when `MasterState = TooFarAhead` resolves the issue, and that got me thinking whether `MasterState` should become `TooFarAhead` if it's actually too far behind, as I assume the purpose of stopping it is to let the players catch up and not cause a "catch-22" situation.

But with all of that aside, it still doesn't make sense why it only happens on certain beatmaps and not all of them in that case, the one I attached has `AudioLeadIn: 2000` if that would explain anything.

**Comment by bdach** [comment] 2021-08-10 15:07
@frenzibyte can you explain why exactly your last comment is hidden?

**Comment by frenzibyte** [comment] 2021-08-10 17:25
It was outdated, I'll write up what I've found now that I've got to the bottom of this, just in a bit.

**Comment by KommToby** [comment] 2021-09-17 00:48
As of 4 days ago, this bug is still happening, I think this issue fits the description of the bug. Here is the clip: [https://clips.twitch.tv/EncouragingAcceptableBoarRuleFive-mL6vNKf4EeNIRBQu](url)

**Comment by Taitranz** [comment] 2021-09-17 15:17
This bug is very common and it seems to occur more often with songs that have a very short beginner timer 


Sent from Yahoo Mail for iPhone


On Friday, September 17, 2021, 10:48 am, Toby ***@***.***> wrote:




As of 4 days ago, this bug is still happening, I think this issue fits the description of the bug. Here is the clip: https://clips.twitch.tv/EncouragingAcceptableBoarRuleFive-mL6vNKf4EeNIRBQu

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by peppy** [comment] 2021-12-14 05:40
When working on and/or closing this issue, make sure it solves the following (and create separate tracking issues if it doesn't):

https://github.com/ppy/osu/discussions/15825
https://github.com/ppy/osu/discussions/15830

**Closed** 2022-01-31 09:33 UTC
Labels: area:spectator, priority:1
