### ISSUE TITLE
CtB: Custom skins do not apply

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#5101] opened 2019-06-21 08:18 UTC
When selecting a custom skin everything appears to work in Standard, but in CtB (and Mania) the skin doesn't apply and the default Lazer skin is used instead

**Comment by Game4all** [comment] 2019-06-21 08:24
Skinning for catch and mania gamemode isn't implemented yet.

**Comment by Game4all** [comment] 2019-06-21 08:27
Duplicate of #3967

**Comment by nyquillerium** [comment] 2019-06-21 08:40
Closing as duplicate of https://github.com/ppy/osu/issues/3967

**Closed by nyquillerium** 2019-06-21 08:40 UTC
