### ISSUE TITLE
Osu immediately crashes after changing screen resolution/size - URGENT! (MacOS)

### ISSUE THREAD

**Issue by SavvyDev06** [ppy/osu#3480] opened 2018-09-23 08:18 UTC
When I remove my monitor which had a bigger resolution than my Mac's screen after running osu! on the monitor, when I then try to launch osu! on my Mac's screen (which has a different resolution), osu launches, but, before it shows the development build screen, it immediately crashes. To fix that, I usually have to plug in my monitor again, and then move osu! from my monitor to my Mac's screen whilst running, so that it can switch resolution.
There has also been a case (like now), where osu completely doesn't launch even if I try to change resolution...

**Comment by Aergwyn** [comment] 2018-09-23 08:44
Looks like a duplicate of #3474.

**Comment by Gabixel** [comment] 2018-09-23 09:52
@Aergwyn Not really a duplicate: in my case the game doesn't crash, just show a resolution error on the Intro Screen and then the game start (but with some bugs)

**Comment by miterosan** [comment] 2018-09-27 21:56
Can you provide logs and screenshots?

**Comment by AtomCrafty** [comment] 2018-10-02 12:41
Propably also related to ppy/osu-framework#1945

**Comment by SavvyDev06** [comment] 2018-10-04 14:36
Firstly, let me apologise for the delay, but since this newest update, I have had no problems so far, but if I get this error again, I will send you the logs, and any screenshots required to solve the problem!

**Comment by peppy** [comment] 2018-10-04 14:39
Closing as duplicate of #3474, which has a pending fix.

**Closed by peppy** 2018-10-04 14:39 UTC
Labels: framework fix required
