### ISSUE TITLE
Video not synchronized with Music ;(

### ISSUE THREAD

**Issue by QuentinMan** [ppy/osu#6294] opened 2019-09-27 16:42 UTC
It's a bug happening when you play a beatmap with a video, the video is not synchronized with the play.

https://www.youtube.com/watch?v=kOjrunq4NyY&feature=youtu.be

osu!lazer 2019.925.0

Thank You for this beautiful game peppy :D

**Comment by bdach** [comment] 2019-09-27 16:45
Duplicate of #6101.

**Closed** 2019-09-27 16:55 UTC
