### ISSUE TITLE
Spinners in editor show incorrect bonus

### ISSUE THREAD

**Issue by yoyyoy** [ppy/osu#25363] opened 2023-11-05 00:17 UTC
### Type

Cosmetic

### Bug description

in the editor, the amount of bonus that is shown during a spinner isn't reset when rewinding. 

### Screenshots or videos

https://github.com/ppy/osu/assets/43836438/293b19ec-27f1-498d-a19b-35cce503acd3

### Version

2023.1026.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/13257993/network.log)
[performance.log](https://github.com/ppy/osu/files/13257994/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/13257995/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/13257996/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/13257997/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/13257998/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/13257999/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13258000/updater.log)
[database.log](https://github.com/ppy/osu/files/13258001/database.log)
[input.log](https://github.com/ppy/osu/files/13258002/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13258003/legacy-ipc.log)

**Comment by Joehuu** [comment] 2023-11-05 00:49
Duplicate of https://github.com/ppy/osu/issues/10455

**Closed by Joehuu** 2023-11-05 00:49 UTC
