### ISSUE TITLE
Can't play osu!lazer on android anymore

### ISSUE THREAD

**Issue by dragonGod97677** [ppy/osu#9332] opened 2020-06-21 13:13 UTC
**Describe the crash:** Before i update to 2020.620.0, i can still play lazer but now, not anymore

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2020.620.0

**Logs:**
 
[runtime.log](https://github.com/ppy/osu/files/4809494/runtime.log)

**Computer Specifications:** Vivo V5 Lite, Android 6.0 Marshmallow with Funtouch OS 3.0, MediaTek MT6750 Octa Core CPU Cortex-A53 @ 1.5GHz, Mali-T760 GPU, 3GB RAM

**Comment by dragonGod97677** [comment] 2020-06-21 13:16
I only attached one log file because there's nothing interested in other log files

**Comment by bdach** [comment] 2020-06-21 13:29
Duplicate of #9321; this will be fixed next release.

For now you can disable multi-threading to play on the current version.

**Closed by bdach** 2020-06-21 13:29 UTC
