### ISSUE TITLE
Crash on Android 14

### ISSUE THREAD

**Issue by AAGaming00** [ppy/osu#23773] opened 2023-06-06 11:03 UTC
### Type

Crash to desktop

### Bug description

After opening osu! on Android 14 Beta 2.1 on my Pixel 6, the screen rotates, then the game exits and returns to the home screen.

### Screenshots or videos

https://github.com/ppy/osu/assets/42613600/34a18867-07c2-44b8-8f2f-7502ce74f40a

### Version

2023.605.0

### Logs

[relevant logcat messages](https://github.com/ppy/osu/files/11663618/2023-06-06-06-46-09.txt)
[runtime.log](https://github.com/ppy/osu/files/11663622/runtime.log)

**Comment by AAGaming00** [comment] 2023-06-06 11:06
Game folder looks like this currently
![Screenshot_20230606-070531](https://github.com/ppy/osu/assets/42613600/26fb11fb-edfe-4ec3-a47f-a308b19c56ce)

**Comment by bdach** [comment] 2023-06-06 18:49
Seems to be a realm issue. Already reported upstream as https://github.com/realm/realm-core/issues/6664, but I cannot reproduce on my device and couldn't say why you are seeing this. Hell it may be even something about the android 14 beta you're running (my test device has 13).

**Comment by peppy** [comment] 2023-06-07 03:18
I wonder if we could add more context to the thread on that realm-side issue (are we attempting to do external file writes in this case?)

**Comment by AAGaming00** [comment] 2023-06-07 11:06
> Seems to be a realm issue. Already reported upstream as https://github.com/realm/realm-core/issues/6664, but I cannot reproduce on my device and couldn't say why you are seeing this. Hell it may be even something about the android 14 beta you're running (my test device has 13).

If you have a Pixel (or any other device with this option) you can go to Developer options > DSU Loader to create an ephemeral, temporary Android 14 Beta install to test without modifying your existing system.

**Comment by Art34222** [comment] 2023-09-25 20:26
In new beta of Android 14 osu don't crashes, BUT the game becomes VERY unstable, laggy and sometimes breaks Pixel Launcher, rebooting the phone. Maybe, create a new Issue?

https://github.com/ppy/osu/assets/127204156/3e815da1-0135-4ccf-81e4-587117444699

**Comment by Joehuu** [comment] 2023-09-25 20:36
There is nothing we can do when Android betas break things. Closing and will revisit once released.

**Closed by Joehuu** 2023-09-25 20:36 UTC
Labels: realm, platform/android

**Comment by AAGaming00** [comment] 2023-10-05 11:09
Still crashing on stable 14 (UP1A.231005.007)

**Comment by AAGaming00** [comment] 2023-10-10 19:16
@Joehuu can this please be reopened? The same bug happens on stable android 14

**Comment by Joehuu** [comment] 2023-10-10 19:35
This was superseded by https://github.com/ppy/osu/issues/25020.
