### ISSUE TITLE
Incorrect Cyrillic input

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8098] opened 2020-03-03 02:43 UTC
The lazer can correctly display messages in Russian, but when you try to enter incorrect letters appear. In the search for maps and direct the same
![image](https://user-images.githubusercontent.com/59089206/75737823-6f094e80-5d4c-11ea-8d17-2c1ba80beb40.png)
osu!lazer version:
2020.229.1

**Comment by smoogipoo** [comment] 2020-03-03 02:53
Duplicate of https://github.com/ppy/osu/issues/5827

**Closed by smoogipoo** 2020-03-03 02:53 UTC
