### ISSUE TITLE
old scores not displaying correctly on the result screen

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#11785] opened 2021-02-15 08:48 UTC
**Describe the bug:** 
old scores (both stable and lazer scores) not displaying 100s properly
50s and misses are correct

I looked into it a bit and found this is 3 issues.
Old scores imported from stable are not showing 100s.
"New" scores from lazer, straight have their replays missing.
And these lazer scores with no replays are not displaying result correctly.

what's "new score"? My scores from July 2020 or before are missing, my scores after Oct 2020 are fine. 
I don't play osu too often, so I can't give you a correct time frame, 
Since lazer doesn't have "last played" or any similar feature I know of, hard for me to find or recall any plays I did.
If I didn't randomly find that one July score I would think scores are missing since Feb.

**osu!lazer version:** 
2021.212.0

**Comment by peppy** [comment] 2021-02-15 09:22
We can't really help you unless you include the replays for the plays you're talking about, along with reproduction steps.

**Comment by dolkilu** [comment] 2021-02-15 09:38
Old scores imported from stable are not showing 100s.
= Any old stable scores, then imported to lazer after I first downloaded lazer. These scores are playable, only the result not displaying correctly. Watching the replay does not fix the result, still 0 100s
![osu_2021-02-15_17-36-39](https://user-images.githubusercontent.com/16611027/107929277-625d2500-6fb4-11eb-8db9-a59cc8675177.jpg)


For new lazer scores, the replays are missing
example screenshots, the replay button is dimmed, replay unavailable:
![osu_2021-02-15_17-32-18](https://user-images.githubusercontent.com/16611027/107928894-e236bf80-6fb3-11eb-835d-6feb74bbe4f9.jpg)
![osu_2021-02-15_17-32-03](https://user-images.githubusercontent.com/16611027/107928901-e4008300-6fb3-11eb-9a23-92a90d669659.jpg)

**Comment by frenzibyte** [comment] 2021-02-15 13:23
For the old stable score, as mentioned previously, please attach the score here so we can get to check what went wrong. 

As for the lazer scores, any score you have on lazer that's older than when the replay recording functionality was supported will *obviously* not have a replay available. The feature is first supported in release `2020.325.0`, while the score in question (from the screenshot) appears to have been made one month ago (feburary 11th).

**Comment by bdach** [comment] 2021-02-15 13:59
Old stable scores probably broke with the scoring changes from last year as well. Reimporting is likely the solution in that case.

**Comment by dolkilu** [comment] 2021-02-15 16:01
I don't know how to export a replay from lazer.
Reimporting scores to see if it works.

**Comment by dolkilu** [comment] 2021-02-15 17:09
Update, after deleting and reimport, the score is fine, I can see the 100s.
I still suspect  this is a new issue, because I used to compare my old scores, and the scores were displaying correctly

**Comment by bdach** [comment] 2021-02-15 18:06
I believe no replay recording support prior to March of last year and the scoring changes from last year will cover the cause of all of your issues. Closing, as I see no clear evidence that this would be a new issue.

If this occurs again, please comment here and we will re-investigate.

**Closed by bdach** 2021-02-15 18:06 UTC
Labels: area:scoring, missing details, ruleset:osu!
