### ISSUE TITLE
Global Rank text overflows the Country Rank in the UserRankPanel at high digit ranks

### ISSUE THREAD

**Issue by AsoDesu** [ppy/osu#27637] opened 2024-03-16 20:54 UTC
### Type

Cosmetic

### Bug description

When at a very large global rank, the text seems to overflow under the Country Rank in the UserRankPanel

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/53526710/4875e027-3510-4d71-9597-6680ecd446e0)

### Version

2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14625229/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-03-17 00:00
Duplicate of https://github.com/ppy/osu/issues/27296

**Closed by frenzibyte** 2024-03-17 00:00 UTC
