### ISSUE TITLE
Tablet Invert Play Area for osu! lazer

### ISSUE THREAD

**Issue by slandotski** [ppy/osu#12201] opened 2021-03-27 05:42 UTC
The feature simply inverts input of the tablet to the game for players with flipped tablets or are left handed. Hawku drivers have this, so osu should have it too!

just a toggle button would be nice.

![909fd81](https://user-images.githubusercontent.com/37074870/112711279-2a75c580-8f02-11eb-89f7-170fc0cfe711.PNG)

**Comment by mouzedrift** [comment] 2021-03-27 06:02
duplicate of #12097

**Closed** 2021-03-27 06:08 UTC
