### ISSUE TITLE
[osu!lazer] Weird visual bug (Green Lines)

### ISSUE THREAD

**Issue by NWJ9PB** [ppy/osu#22395] opened 2023-01-24 12:44 UTC
### Type

Game behaviour

### Bug description

Fresh Installation

Still fresh installation of Windows 11

### Screenshots or videos

1
![image_1](https://user-images.githubusercontent.com/69032826/214293632-a16dd1f7-de5f-4fff-b38c-99e496a0c43b.png)
2
![image_2](https://user-images.githubusercontent.com/69032826/214293638-10484b14-35e6-48f9-8959-cb898f6a4c12.png)

### Version

2023.123.0

### Logs

[performance.log](https://github.com/ppy/osu/files/10489688/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10489689/runtime.log)

**Comment by bdach** [comment] 2023-01-24 17:53
Duplicate of https://github.com/ppy/osu/issues/12362

Recommend that you try and update your graphics cards drivers.

**Closed by bdach** 2023-01-24 17:53 UTC
