### ISSUE TITLE
Beatmap video doesn't play

### ISSUE THREAD

**Issue by cityevil000** [ppy/osu#25086] opened 2023-10-10 21:08 UTC
### Type

Game behaviour

### Bug description

In all difficulties, the video doesn't play.

https://osu.ppy.sh/beatmapsets/5723

### Screenshots or videos

https://github.com/ppy/osu/assets/147069922/4d694957-3f18-4611-a9b2-cdae5a1df95f

### Version

2023.1008.1-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12861821/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12861822/runtime.log)

[updater.log](https://github.com/ppy/osu/files/12861823/updater.log)
[database.log](https://github.com/ppy/osu/files/12861824/database.log)
[input.log](https://github.com/ppy/osu/files/12861825/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12861826/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12861827/network.log)

**Comment by cityevil000** [comment] 2023-10-10 21:09
Gameplay video where the beatmap video does work: https://www.youtube.com/watch?v=57SC35UHt1Q

**Comment by toadsworth-jr** [comment] 2023-10-11 10:55
Just to be sure, did you download the "no video" version of this map by accident?

**Comment by cityevil000** [comment] 2023-10-11 13:05
> Just to be sure, did you download the "no video" version of this map by accident?

I downloaded the "with video" version. In the runtime.txt, it appear to throw an error when decoding the video.

**Comment by peppy** [comment] 2023-10-12 05:46
Error:

```log
[runtime] 2023-10-12 05:44:34 [verbose]: 🖍️ Shader Texture2D/Video loaded from cache!
[avi @ 0x125023200] Could not find codec parameters for stream 1 (Audio: mp3 (U[0][0][0] / 0x0055), 22050 Hz, 1 channels, 64 kb/s): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
```

cc @FreezyLemon since you'll probably know best what's going on here 😅

**Comment by FreezyLemon** [comment] 2023-10-12 12:53
The video included in the beatmapset uses the `xvid` codec, which isn't currently enabled in the build scripts. This was an oversight when originally defining which codecs should be supported, probably because xvid/divx are rarely used compared to H.264 etc.

The linked PR fixes this issue, local testing shows that the newly built libraries play the video fine.

**Comment by bdach** [comment] 2023-10-28 16:57
I somehow can reproduce. Not sure how that happened. I'm pretty sure I tested before.

**Comment by FreezyLemon** [comment] 2023-10-28 18:24
The fix was merged after the latest framework release, so it's just not included yet. Next framework release should fix it

**Comment by peppy** [comment] 2023-10-28 18:25
Yeah I realised this when doing the release, but it was too late to worry about it.

**Comment by bdach** [comment] 2023-11-11 11:05
Should be better next release.

**Closed by bdach** 2023-11-11 11:05 UTC
Labels: osu!framework issue
