### ISSUE TITLE
Clicking on the bottom tabs out from the game

### ISSUE THREAD

**Issue by ItzNico** [ppy/osu#19541] opened 2022-08-02 02:10 UTC
### Type

Game behaviour

### Bug description

Windows 10, osu! is in fullscreen:
Steps(?):
Click on the bottom of the client(like I would do going for the mods section)
Game tabs out and on the very same click it allows me to open a program that's on the taskbar

Hopefully the video explains the problem(Recorded with OBS if anything): https://youtu.be/bmYjExAP3Cw

### Version

2022.731.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9238483/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9238484/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9238486/network.log)
[performance.log](https://github.com/ppy/osu/files/9238487/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9238488/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9238489/updater.log)

**Comment by peppy** [comment] 2022-08-02 04:28
Duplicate of https://github.com/ppy/osu/issues/12157.

**Closed by peppy** 2022-08-02 04:28 UTC
Labels: type:UX, platform:windows
