### ISSUE TITLE
Make all local scores comform to the same format

### ISSUE THREAD

**Issue by mcendu** [ppy/osu#7090] opened 2019-12-08 01:14 UTC
**Describe the new feature:** e.g. If I used classic mode to play, and I switch to standardized mode, the past scores are also displayed in standardized. Can prevent problems from happening when lazer scores can be uploaded (far future?).

**Proposal designs of the feature:** Scores are internally stored as classic. We would scale(?) it to standardized when displaying.

Alternatively, we can choose to store only the amount of Great/Good/Meh/Misses, and calculate the score when we need to display it.

Mania scores should always be standardized, but that would be a separate feature.

**Comment by bdach** [comment] 2019-12-08 08:25
Duplicate of #5350.

**Closed by bdach** 2019-12-08 08:25 UTC
