### ISSUE TITLE
dropdown menu is overlapped

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#10132] opened 2020-09-11 07:23 UTC
**Describe the bug:** sorting dropdown menu is overlapped by collection tab

**Screenshots or videos showing encountered issue:** 
![Te24gdwlAk](https://user-images.githubusercontent.com/21735205/92882194-359e5380-f3ff-11ea-85c2-5c59846748c1.gif)

**osu!lazer version:** 2020.910.0

**Comment by smoogipoo** [comment] 2020-09-11 07:24
Duplicate of https://github.com/ppy/osu/issues/10120

Fixed in upcoming release.

**Closed by smoogipoo** 2020-09-11 07:24 UTC
