### ISSUE TITLE
New feature: Subscribing to mappers.

### ISSUE THREAD

**Issue by Finxert** [ppy/osu#8796] opened 2020-04-18 21:56 UTC
**Describe the new feature:** 

I think I heard this being talked about a few years ago by peppy, maybe on coffee hour or something.
The idea is to implement a subscription system that automatically downloads all the maps of the mappers you are subscribed to and the future maps they will release.

I know this would be pretty hard to implement but I think the feature would be well worth it. It would reward the mapper further by building a following and make playing the game a lot easier. A big issue with this game is finding good maps to play and remembering all the mappers you like.
While osu!direct has made this a lot easier it's still a pain to keep up with the dozens if not hundreds of mappers you like.

**Proposal designs of the feature:** 

I won't bother explaining how I would handle this on the "server side" because I have no experience with these kinds of things and my solution could be less convinient while somebody here probably already knows the best way to set this up, so I will just describe the end result instead to save everyones time.

There would be a "subscribe" button next to a users name, on their profile, and clicking it would call osu!direct to download all the maps this user has made whether they be graveyarded, ranked, pending, approved or loved. Subscribing would also download all the future maps the person will release/upload. 
When a mapper uploads a new map the subscriber would be notified in game, via the notification system or maybe a bot like tillerino, whichever you deem more convinient I guess.
The notification would say that x mapper made a new map and map y, z, x... were downloaded with direct links to them ingame.

Another way to make this would be a sub feed like youtube or twitter where you get notified with all the new uploads from the mappers with osu!direct links to them. This solution would be less intensive on the servers maybe and also easier to implement.

**Comment by iiSaLMaN** [comment] 2020-04-18 22:03
I would see this as being customizable in the settings, whether you want *all* beatmpps

**Comment by iiSaLMaN** [comment] 2020-04-18 22:16
Sounds like a good osu!supporter feature IMO given the API required for it. (being notified on every beatmap the mapper makes and automatically download them)

**Comment by Finxert** [comment] 2020-04-18 22:32
> Sounds like a good osu!supporter feature IMO given the API required for it. (being notified on every beatmap the mapper makes and automatically download them)

Isn't osu supporter supposed to be only for supporting the project and not unlocking extra features? idk if peppy changed his mind but iirc he said that in lazer supporter will only be for actually supporting the game and not getting additional services.

**Comment by iiSaLMaN** [comment] 2020-04-18 22:36
Just sharing my own opinion here, don't really have much clue about what will happen next but given what we use osu!supporter for currently (in osu!lazer), this would sound like a candidate for it.

**Comment by Finxert** [comment] 2020-04-18 22:44
> Just sharing my own opinion here, don't really have much clue about what will happen next but given what we use osu!supporter for currently (in osu!lazer), this would sound like a candidate for it.

Yeah me neither, I haven't kept up in recent times and what I know could be out of date. I thought maybe you knew more :)

**Comment by enoslayd** [comment] 2020-04-19 04:40
Suggestion: make a toggle switches or checkboxes that a player can toggle the graveyard, ranked, approved, etc. because some players want to play only ranked maps, some wants only beatmaps with leaderboards, etc.

**Comment by peppy** [comment] 2020-04-19 04:41
This is so far away from happening (and requires server-side support) that I'm marking low priority (and leaning towards closing).

**Comment by peppy** [comment] 2020-04-19 04:41
Going to close for now, in fact. Duplicate of https://github.com/ppy/osu-web/issues/5635.

**Closed by peppy** 2020-04-19 04:41 UTC
Labels: low-priority, proposal
