### ISSUE TITLE
Background of maps with storyboard doesn't dim properly when screen scaling is applied

### ISSUE THREAD

**Issue by 120-cell** [ppy/osu#23184] opened 2023-04-11 15:40 UTC
### Type

Cosmetic

### Bug description

The background does become darker when raising the dim setting, but becomes completely transparent when the setting reaches 100%, which lets the extra background from screen scaling show through. This only happens on some maps and I believe it's because they have a storyboard.

### Screenshots or videos

Here it is showing the described behavior:
https://user-images.githubusercontent.com/120076941/231214263-485faec4-a40c-4e7d-b6a8-63320b0c1e3f.mp4

Here it is working normally:
https://user-images.githubusercontent.com/120076941/231214482-ad13c971-36f9-40c3-8558-bdb4515893cc.mp4

### Version

2023.403.1

### Logs

[network.log](https://github.com/ppy/osu/files/11202305/network.log)
[performance.log](https://github.com/ppy/osu/files/11202306/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11202307/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11202308/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11202309/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11202310/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11202311/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11202312/updater.log)
[database.log](https://github.com/ppy/osu/files/11202313/database.log)
[input.log](https://github.com/ppy/osu/files/11202314/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11202315/legacy-ipc.log)

**Comment by bdach** [comment] 2023-04-11 15:58
Duplicate of #22238

**Closed by bdach** 2023-04-11 15:58 UTC
