### ISSUE TITLE
Slider isnt same as osu!stable

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu#12150] opened 2021-03-23 06:22 UTC
**Describe the bug:** 
[this map](https://osu.ppy.sh/beatmapsets/1164149#osu/2428468)'s last diff's last hitobject(slider) isnt same as osu!stable.
I have no idea for titling this since i only found this bug at one map.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/37479424/112102308-63a0f380-8beb-11eb-85ed-74d268b121e9.png)
![image](https://user-images.githubusercontent.com/37479424/112102360-7f0bfe80-8beb-11eb-8a1e-99d0b445ee8f.png)

**osu!lazer version:** 2021.320.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6187351/logs.zip)

**Comment by smoogipoo** [comment] 2021-03-23 06:27
Duplicate of https://github.com/ppy/osu/issues/12109
Fixed by https://github.com/ppy/osu-framework/pull/4302

**Closed by smoogipoo** 2021-03-23 06:27 UTC
