### ISSUE TITLE
Unable to login: The SSL connection could not be established

### ISSUE THREAD

**Issue by ToppleKek** [ppy/osu#4145] opened 2019-01-25 01:15 UTC
**Describe your problem:**
Debian sid (linux 4.19.0-1)
Whenever I try to login to osu!lazer, there is no visual notification of any sort saying that my login failed. Only the password box gets cleared. I can login fine from normal osu! (In Windows) and access the website and all that.

I get this error when I try to login however:

```
[network:verbose] 2019-01-25 12:55:51 a.m.: We just went Connecting!
[runtime:debug] 2019-01-25 12:55:51 a.m.: Focus on "OsuPasswordTextBox" no longer valid as a result of unfocusIfNoLongerValid.
[runtime:debug] 2019-01-25 12:55:51 a.m.: Focus changed from OsuPasswordTextBox to nothing.
[runtime:debug] 2019-01-25 12:55:51 a.m.: Focus changed from nothing to LoginOverlay.
Console output is being limited. Please check runtime.log for full logs.
[network:verbose] 2019-01-25 12:55:51 a.m.: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
[network:verbose] 2019-01-25 12:55:51 a.m.: at Interop.SslInitializer..cctor()
[network:verbose] 2019-01-25 12:55:51 a.m.: --- End of inner exception stack trace ---
[network:verbose] 2019-01-25 12:55:51 a.m.: at Interop.Ssl..cctor()
[network:verbose] 2019-01-25 12:55:51 a.m.: --- End of inner exception stack trace ---
[network:verbose] 2019-01-25 12:55:51 a.m.: at Interop.Ssl.SslV2_3Method()
[network:verbose] 2019-01-25 12:55:51 a.m.: at Interop.Ssl.SslMethods..cctor()
[network:verbose] 2019-01-25 12:55:51 a.m.: --- End of inner exception stack trace ---
[network:verbose] 2019-01-25 12:55:51 a.m.: at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
[network:verbose] 2019-01-25 12:55:51 a.m.: --- End of inner exception stack trace ---
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: --- End of inner exception stack trace ---
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.ValueTask`1.get_Result()
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.ValueTask`1.get_Result()
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Threading.Tasks.ValueTask`1.get_Result()
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[network:verbose] 2019-01-25 12:55:51 a.m.: at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
[network:verbose] 2019-01-25 12:55:51 a.m.: at osu.Framework.IO.Network.WebRequest.internalPerform() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 323.
[network:verbose] 2019-01-25 12:55:51 a.m.: Processing response from https://osu.ppy.sh/oauth/token failed with System.ArgumentNullException: Value cannot be null.
[network:verbose] 2019-01-25 12:55:51 a.m.: Parameter name: value
[network:verbose] 2019-01-25 12:55:51 a.m.: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 818
[network:verbose] 2019-01-25 12:55:51 a.m.: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 786
[network:verbose] 2019-01-25 12:55:51 a.m.: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse() in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\JsonWebRequest.cs:line 21
[network:verbose] 2019-01-25 12:55:51 a.m.: at osu.Framework.IO.Network.WebRequest.Complete(Exception e) in C:\projects\osu-framework-a4n7e\osu.Framework\IO\Network\WebRequest.cs:line 486.
[network:verbose] 2019-01-25 12:55:51 a.m.: Login failed!
[network:verbose] 2019-01-25 12:55:51 a.m.: We just went Offline!
```

**Screenshots or videos showing encountered issue:** 
https://youtu.be/9VmbvnobvtY

**osu!lazer version:** 
I don't see it at the bottom of my screen, maybe I'm blind but I'm using the current latest master commit (d2ee08a).  
**Logs:** 
[database.log](https://github.com/ppy/osu/files/2794243/database.log)
[performance.log](https://github.com/ppy/osu/files/2794244/performance.log)
[network.log](https://github.com/ppy/osu/files/2794245/network.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2794246/performance-gamethread.audio.log)
[runtime.log](https://github.com/ppy/osu/files/2794247/runtime.log)

**Comment by peppy** [comment] 2019-01-25 01:15
Your PC is likely compromised by a virus. Please consider reformatting.

Feedback issue duplicate of #4086

**Closed by peppy** 2019-01-25 01:15 UTC

**Comment by ToppleKek** [comment] 2019-01-25 01:19
Sorry, I don't believe this is the exact same issue. I'm not requesting a login notification (maybe should have been more clear on that) but rather I'm completely unable to login.

**Comment by peppy** [comment] 2019-01-25 01:20
See the first line of my response.
