### ISSUE TITLE
Beatmap offset seems incorrect on non-windows platforms (and in the editor)

### ISSUE THREAD

**Issue by Vitaliaosu** [ppy/osu#12064] opened 2021-03-18 14:05 UTC
As the title says, the wafeform is offset and it makes the wave form totally pointless.

This image shows the wafeform clearly being offset.
https://i.imgur.com/MyQnPmm.png

v. 2021.312.0

**Comment by peppy** [comment] 2021-03-18 14:50
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

- Include the beatmap you are seeing this issue on
- Include your universal offset setting value

**Comment by Vitaliaosu** [comment] 2021-03-18 21:06
Sorry for leaving little information.

This happens on all maps I've downloaded.

I have no audio offset.
![Screenshot 2021-03-18 at 21 58 46](https://user-images.githubusercontent.com/69867797/111697725-355f9480-8836-11eb-9db3-fa9e4f0c9d6f.png)


https://osu.ppy.sh/beatmapsets/1378026#osu/2847746
![Screenshot 2021-03-18 at 21 59 22](https://user-images.githubusercontent.com/69867797/111697620-152fd580-8836-11eb-9a1f-0b7365ba42cf.jpeg)

https://osu.ppy.sh/beatmapsets/1378026#osu/2847746
![Screenshot 2021-03-18 at 22 02 48](https://user-images.githubusercontent.com/69867797/111697705-2f69b380-8836-11eb-957d-5c739ce1c493.jpeg)

**Comment by bdach** [comment] 2021-03-18 21:32
Well, to tell you the truth, on comparing with external software I'm not sure that the waveforms are incorrect.

Comparing on one of the maps you gave (Polyphia - O.D., https://osu.ppy.sh/beatmapsets/1378026#osu/2847746), on one bar (00:52:082-00:52:193)

| lazer | audacity |
| :-: | :-: |
| ![2021-03-18-222126_226x156_scrot](https://user-images.githubusercontent.com/20418176/111699362-4f01db80-8838-11eb-8676-fcd67bea7aff.png) | ![2021-03-18-222226_277x374_scrot](https://user-images.githubusercontent.com/20418176/111699530-8b353c00-8838-11eb-815b-bd61ff98bf5c.png) |

As you can see in both cases the start of the bar does not coincide with peak intensity of the waveform. And I'd hope audacity would get this sort of stuff right.

Also note that at that scale, what seems like huge offsets is actually 20-30 milliseconds of difference. In fact, as there is some offset fudging done for windows:

https://github.com/ppy/osu/blob/a86a7b08dfe8f81e3be2b920a55629bf03662745/osu.Game/Screens/Play/GameplayClockContainer.cs#L87-L89

this might as well boil down to something of that sort.

**Comment by Vitaliaosu** [comment] 2021-03-18 21:51
You're completely right, although I do think that it's off-putting for new users or even old users to set the timing point at what is supposed to be it's peak loudness. Otherwise the waveform would look distracting and confusing. All samples do seem to have a bit of an attack roll-off, which is perfectly normal for a lot of music, but in a case like this i do think it's better for the peak loudness to be the impact. This is only if possible of course, I do think a lot of mappers would like this.

**Comment by Vitaliaosu** [comment] 2021-03-19 07:45
This might have something to do with it, I’m not educated at all in this, but could it just be general audio driver latency which causes this issue?

**Comment by bdach** [comment] 2021-03-19 07:49
Latency has nothing to do with it, I'm pretty sure. The waveform is directly derived from the track's audio amplitudes. It's direct digital signal processing, so I'm not sure how driver latency would factor into it at all.

**Comment by Vitaliaosu** [comment] 2021-03-19 08:22
Then I maybe it’s the timing point(s) that behaves in an odd manner. I can’t tell you why.

**Comment by Vitaliaosu** [comment] 2021-03-19 08:23
Or perhaps even the way the waveform gets visually rendered.

**Comment by Vitaliaosu** [comment] 2021-03-19 08:48
It’s not really an issue with the audio it’s just the waveform that would make a lot more sense if the initial peak is where the bar would reset.

![AACEBBD5-9062-4DE5-B87C-5C41D2FF0134](https://user-images.githubusercontent.com/69867797/111754345-2a3d5080-8898-11eb-9b76-25cfd95776f0.jpeg)
*Red indicates the gap between the peak loudness of the sound and the start of the bar.*

**Comment by peppy** [comment] 2021-03-19 08:49
You don't need to respond to this thread any more. Please. There is an issue and we will investigate, but what you're doing is spam.

**Comment by Vitaliaosu** [comment] 2021-03-19 08:50
Sorry, just trying to help from a players perspective.

**Comment by octo-kumo** [comment] 2021-03-30 15:34
The hit sound sync up with the beat if the note is placed a little before the beat

**Comment by peppy** [comment] 2021-04-22 07:14
both of the beatmaps you provided match waveform and match in audible difference. the maps are mistimed or the sections you are aligning are intentionally not in time. to my ear both sound mistimed.

**Comment by peppy** [comment] 2021-04-22 07:17
That said, this mistiming seems to apply to other beatmaps, which would suggest something is actually incorrect with lazer's underlying offset (at least for me, on macOS). Wondering if the "platform offset" which is being applied for windows is actually something we need to apply everywhere?

**Comment by jansenmtan** [comment] 2022-07-17 18:39
I believe lazer's beatmap offset is correct. I see this in Windows 10 as well. As bdach mentioned, the waveform timings match on Audacity. I believe that osu! (standard's) ranked beatmap standards for timing are 26 ms off-time (26 ms late in terms of judgement, 26 ms early relative to audio). I explored this phenomenon in this [Twitter thread](https://twitter.com/whishk1/status/1533189069848690691?s=20&t=FXGffEOwp-950W_pmlvMJw), and came up with 26 ms from this [spreadsheet](https://docs.google.com/spreadsheets/d/1eI3QlhFUs2ivXgZGvil2WZr3MAnHuzLv9_nRz2piqoM/edit?usp=sharing) I made after.

I don't know why exactly this is the case, I suspect it has to do with audio latency and hitsounding. This [reddit comment](https://www.reddit.com/r/osugame/comments/v4y9i2/comment/ib6tjvq/?utm_source=share&utm_medium=web2x&context=3) agrees with my thinking. 

However, 26 ms is a bit much. I've measured audio latency on my previous PC to be at worst 10 ms by using [ThePoon's method](https://blog.thepoon.fr/osuLinuxAudioLatency/). The PC I currently use seems to have 1-2 ms audio latency on Linux and 15-16 ms audio latency on Windows 10. This is based off my audio/global offset on osu!, which is -28 ms on Linux and -42 ms on Windows. Assuming audio latency on most Windows machines is around the range of 10-15 ms, this still leaves 15-10 ms of discrepancy.

idk. 10-15 ms of discrepancy is unplayable for me, but everyone else seems to play okay, so there must be something else to this.

**Comment by peppy** [comment] 2022-07-17 18:57
Yes osu! maps are historically timed not matching waveform, due to the audio library changing over the years and needing backwards compatibility.

Going to close this issue as a path to resolution is being tracked in https://github.com/ppy/osu/issues/11400

**Closed by peppy** 2022-07-17 18:57 UTC
Labels: area:editor, priority:2

**Comment by jansenmtan** [comment] 2022-09-02 15:36
#11400 was closed a few days ago and yet this issue still remains. Waveform is still offset from timing; changing audio offset or local offset does nothing.

**Comment by peppy** [comment] 2022-09-02 16:04
Please open a new issue with video showing you adjusting universal offset and what you are expecting to see.

This has been confirmed through review by multiple people to be working as expected.
