### ISSUE TITLE
show nothing using OpenGL+Singlethread renderer

### ISSUE THREAD

**Issue by wdnmd23333fdhsuidus** [ppy/osu#23512] opened 2023-05-12 10:33 UTC
### Type

Game behaviour

### Bug description

When I use singlethread+OpenGL renderer in fullscreen mode it mostly outputs nothing,and play windows background sound sometimes output normally

### Screenshots or videos

https://github.com/ppy/osu/assets/81455657/b26f6bbd-1318-4cf6-9e5b-b653f2de2547

(Please unmute video)

### Version

2023.511.0

### Logs

[performance-draw.log](https://github.com/ppy/osu/files/11462202/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11462213/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11462218/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11462225/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11462229/updater.log)
[database.log](https://github.com/ppy/osu/files/11462233/database.log)
[input.log](https://github.com/ppy/osu/files/11462239/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11462246/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11462251/network.log)
[performance.log](https://github.com/ppy/osu/files/11462255/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11462259/performance-audio.log)

**Comment by Theighlin** [comment] 2023-05-12 10:37
Duplicate of #23466, search before opening new issues.

**Closed** 2023-05-13 05:43 UTC
