### ISSUE TITLE
Lazer does something strange with my gpu. 

### ISSUE THREAD

**Issue by et013** [ppy/osu#18418] opened 2022-05-25 20:40 UTC
### Type

Performance

### Bug description

Hello. I dont know why but lazer at start uses my integrated gpu. then in-game starts to use sometimes my main gpu and it jumps from one to other. it leads to lag spikes... I dont know how to explain. But here are screenshots of what happens every second. 
I also put on autopilot to spec what happens while gameplay. So basically when many objects appear it starts to use gtx1050 and less it goes back more on uhd... 

My specs gtx 1050 3gb and uhd 630 
i5 9300h 8gb ram 
HP laptop

p.s. didnt have this issue year ago. And stable works perfect... 

### Screenshots or videos

![download (1)](https://user-images.githubusercontent.com/106277957/170361482-c397a43b-ccf3-4258-98ee-0439011a1e36.png)
![download](https://user-images.githubusercontent.com/106277957/170361485-6f8cf5e2-e7de-4ebd-af49-4fa7986f7d72.png)

### Version

2022.523.0

### Logs

I dont have log folder in lazer...

**Comment by jai-x** [comment] 2022-05-25 20:43
Duplicate of https://github.com/ppy/osu/issues/8165

**Closed by jai-x** 2022-05-25 20:43 UTC

**Comment by SonoSooS** [comment] 2022-05-25 22:51
This is a known issue with the UHD630 in some cases, try updating your Intel graphics driver from Windows Update.

Logs are located in `%APPDATA%\osu\logs`, please share them.

**Comment by smoogipoo** [comment] 2022-05-26 03:41
Overall usage graphs are misleading. If you're using the integrated display than the integrated GPU will always be used regardless, but mostly only the "Copy" subsystem. The "3D" subsystem will still be used for display output but not for rendering in this case.  
You'd need to show the individual graphs to see see what's actually going on.

As for why this would happen, it's because you're running at unlimited frame limiter, and you shouldn't be doing this. Try using a more sane frame limiter like 4x or 8x.

More technically, it's because when more objects appear on the screen your dGPU is actually doing meaningful work. When there's no objects your dGPU's pushing out thousands of frames and the bottleneck becomes the operation copying frames between your dGPU and iGPU.

**Comment by et013** [comment] 2022-05-26 18:35
> Logs are located in `%APPDATA%\osu\logs`, please share them.

those are osu standart but ok 

[runtime.log](https://github.com/ppy/osu/files/8781308/runtime.log)
[session.log](https://github.com/ppy/osu/files/8781309/session.log)
[update.log](https://github.com/ppy/osu/files/8781310/update.log)
[update_success.log](https://github.com/ppy/osu/files/8781311/update_success.log)
[network.log](https://github.com/ppy/osu/files/8781312/network.log)
[performance.log](https://github.com/ppy/osu/files/8781313/performance.log)

**Comment by bdach** [comment] 2022-05-26 18:39
@et013 you have the wrong logs, then. please find the right ones. you've likely checked `AppData/Local/osu!` rather than `AppData/Roaming/osu` (no exclamation point).

**Comment by et013** [comment] 2022-05-26 19:03
true

p.s using 4x made it better but some maps feel laggy 

[database.log](https://github.com/ppy/osu/files/8781415/database.log)
[updater.log](https://github.com/ppy/osu/files/8781416/updater.log)
[runtime.log](https://github.com/ppy/osu/files/8781417/runtime.log)
[performance.log](https://github.com/ppy/osu/files/8781418/performance.log)
[network.log](https://github.com/ppy/osu/files/8781419/network.log)
e

**Comment by smoogipoo** [comment] 2022-05-27 00:15
Maps feel laggy because we're unable to make exclusive fullscreen work for your system at the moment. This will be fixed in the future.
