### ISSUE TITLE
Nobody on chat

### ISSUE THREAD

**Issue by MeuhMeuh62** [ppy/osu#23878] opened 2023-06-11 17:26 UTC
### Type

Game behaviour

### Bug description

Hello, i found a bug on osu! chat.
When we add more channels, osu! tell how much pepole are in, but osu! say 0 pepole here.
Is a little bug but that's right.
Look youtube video 
Have a nice day !

### Screenshots or videos

https://youtu.be/spnIgAgf4BU

### Version

2023.610.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11715317/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11715318/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11715319/updater.log)
[database.log](https://github.com/ppy/osu/files/11715320/database.log)
[input.log](https://github.com/ppy/osu/files/11715321/input.log)
[network.log](https://github.com/ppy/osu/files/11715322/network.log)

**Comment by Joehuu** [comment] 2023-06-11 20:34
Duplicate of https://github.com/ppy/osu/issues/5327

**Closed by Joehuu** 2023-06-11 20:34 UTC
