### ISSUE TITLE
Leaderboard scores don't reflect true accuracy and score order

### ISSUE THREAD

**Issue by AlexHgC** [ppy/osu#12305] opened 2021-04-05 12:46 UTC
**Describe the bug:** 
With the latest pull request for fix osu!mania scoring #12294  ( thanks for that ), scores conversion have some problems : 

- The score leaderboard is bad, you can see the #.3 is now lower than the #.4
- Accuracy is not updated
- When we watch replay, the score at the end of the map is higher than the converted score at result screen. Maybe because the new 99:1 ratio for acc/combo and new HitResult are not count on converted score ? Exemple: my 944k score is a 971k at the end of replay :

![image](https://user-images.githubusercontent.com/31996023/113574232-f7c37f80-961b-11eb-8d0a-4f9fd8db2081.png)

**Here the converted score on osu!lazer with latest score fix commit :** 
![Scores_converted](https://user-images.githubusercontent.com/31996023/113573768-1412ec80-961b-11eb-887b-b75db75cba7e.png)

**Here the base score on actual osu!lazer version :** 
![Scores_base](https://user-images.githubusercontent.com/31996023/113573760-0fe6cf00-961b-11eb-88fe-2a3bf97475ea.png)

**Comment by smoogipoo** [comment] 2021-04-05 12:51
These are both known issues. We don't currently recalculate accuracy for either the score or the %.

The leaderboard ordering is a harder one to fix, because it means recalculating all scores before displaying any of them.

**Comment by bdach** [comment] 2021-04-05 12:54
FWIW, re: the 3rd point - I did observe that the replay would sometimes show a higher score than the results screen would show, at one point ([see discord message from ages ago](https://discord.com/channels/188630481301012481/188630652340404224/775670504245035048)). It seemed to be caused by GREAT judgements being converted to PERFECTs. I don't believe there is an issue tracking that either, but it should probably be a separate one.

**Comment by smoogipoo** [comment] 2021-04-05 12:57
While that could be the case, it has to be very accurate right? In this case it's mostly just the change in acc% as a result of lowering PERFECT from 350 to 315, along with the acc portion going up from 95% -> 99%, causing the difference in score.

**Comment by bdach** [comment] 2021-04-05 13:00
The results screen doesn't recompute scores either, does it... I keep confusing it with star rating which is recomputed. Most likely safe to say that is the core issue there.

**Comment by AlexHgC** [comment] 2021-04-05 13:03
> FWIW, re: the 3rd point - I did observe that the replay would sometimes show a higher score than the results screen would show, at one point ([see discord message from ages ago](https://discord.com/channels/188630481301012481/188630652340404224/775670504245035048)). It seemed to be caused by GREAT judgements being converted to PERFECTs. I don't believe there is an issue tracking that either, but it should probably be a separate one.

The #12060 have fixed that no ?

**Comment by smoogipoo** [comment] 2021-04-05 13:04
All total score displays game wide use recomputed values, but acc% isn't recomputed. So the same issue is present in the results screen, but the total score is "accurate" to the acc% present in the ScoreInfo.

**Comment by bdach** [comment] 2021-04-05 13:06
> So the same issue is present in the results screen, but the total score is "accurate" to the acc% present in the ScoreInfo.

Oh yep, with you now. Makes sense.

> The #12060 have fixed that no ?

No, that doesn't sound related to what I mentioned as far as I can tell.

**Comment by smoogipoo** [comment] 2021-09-13 09:54
Accuracy is extremely difficult if not impossible to fix because replays have lost too much data to be able to discern, e.g., the number of slider ticks hit.

Closing a resolved.

**Closed by smoogipoo** 2021-09-13 09:54 UTC
Labels: area:scoring, priority:1
