### ISSUE TITLE
Game hangs up upon launching

### ISSUE THREAD

**Issue by flirtyxd** [ppy/osu#29000] opened 2024-07-22 13:30 UTC
### Type

Game behaviour

### Bug description

My installation of lazer suddenly began hanging up on the intro animation.  Deleting the framework.ini file or a complete reinstall did initially make the game run again, however after the next couple launches it hangs up again. 

### Version

2024.718.1

### Logs

[1721654583.auth.log](https://github.com/user-attachments/files/16334074/1721654583.auth.log)
[1721654583.input.log](https://github.com/user-attachments/files/16334075/1721654583.input.log)
[1721654583.network.log](https://github.com/user-attachments/files/16334076/1721654583.network.log)
[1721654583.performance.log](https://github.com/user-attachments/files/16334077/1721654583.performance.log)
[1721654583.runtime.log](https://github.com/user-attachments/files/16334078/1721654583.runtime.log)
[1721654583.updater.log](https://github.com/user-attachments/files/16334080/1721654583.updater.log)

**Comment by Fabiano1337** [comment] 2024-07-22 16:05
Same here, game stuck on intro and if it starts i can't log in to my account

**Comment by ekamtaneja** [comment] 2024-07-23 03:59
Me too, it gets stuck just as the game is launching. I can still hear the audio in the background. Alt + F4 didn't work to exit. When I pressed it, I didn't hear the exit menu pop up either.

**Comment by smoogipoo** [comment] 2024-07-23 04:58
Does setting the environment variable `OSU_SDL3=1` fix things?

**Comment by peppy** [comment] 2024-07-23 06:52
We've rolled back an update which may have been causing this freeze, please restart the game and report back.

**Comment by flirtyxd** [comment] 2024-07-23 06:56
> We've rolled back an update which may have been causing this freeze, please restart the game and report back.

Yup, works perfectly fine now.

**Comment by peppy** [comment] 2024-07-23 06:58
Thanks for the quick response. Will close this for now.

**Closed by peppy** 2024-07-23 06:58 UTC

**Comment by flirtyxd** [comment] 2024-07-25 07:54
The issue seems to be back after the 2024.725.0 update.

**Comment by smoogipoo** [comment] 2024-07-25 09:04
Please post logs, and also find the AuthNative.dll file alongside the logs folder, delete it, and try again.

**Comment by flirtyxd** [comment] 2024-07-25 09:35
[1721900042.performance.log](https://github.com/user-attachments/files/16373756/1721900042.performance.log)
[1721900042.runtime.log](https://github.com/user-attachments/files/16373757/1721900042.runtime.log)
[1721900042.updater.log](https://github.com/user-attachments/files/16373758/1721900042.updater.log)
[1721900042.auth.log](https://github.com/user-attachments/files/16373759/1721900042.auth.log)
[1721900042.input.log](https://github.com/user-attachments/files/16373760/1721900042.input.log)
[1721900042.network.log](https://github.com/user-attachments/files/16373761/1721900042.network.log)

**Comment by flirtyxd** [comment] 2024-07-25 09:35
Deleting AuthNative.dll did not help.

**Comment by smoogipoo** [comment] 2024-07-25 12:29
Okay, very weird. We've just found the root cause of this so it's very disappointing it's still happening.

While osu! is in a hung state, right click the process in task manager, select "Create memory dump file", compress it (right click -> compress to zip file), and then email it to pe@ppy.sh.

**Comment by smoogipoo** [comment] 2024-07-25 13:31
Also, have you tried just... waiting? I know it sounds silly but I've seen Windows Defender take around 10s to scan that AuthNative file, albeit a dev version of it.

**Comment by flirtyxd** [comment] 2024-07-25 13:37
I've waited about a minute or two, still no luck.

**Comment by smoogipoo** [comment] 2024-07-25 14:22
We've reverted for now, you should be able to start the game, or failing that delete AuthNative.dll + startup the game.
