### ISSUE TITLE
crash when select a beatmap

### ISSUE THREAD

**Issue by taizi-tp** [ppy/osu#7263] opened 2019-12-18 12:19 UTC
**Describe the crash:when i want to start playing Chika（https://osu.ppy.sh/beatmapsets/802301   from osu！direct），it will crash，and i tried three times and different difficulty ，it still crash again,whenever it is with or without video

**Screenshots or videos showing encountered issue: https://youtu.be/EaebSrn3RS0 

**osu!lazer version:2019.1216.0 

**Logs: 
[network.log](https://github.com/ppy/osu/files/3978340/network.log)
[performance.log](https://github.com/ppy/osu/files/3978342/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3978343/runtime.log)

**Computer Specifications:windows10 1909

**Comment by smoogipoo** [comment] 2019-12-18 12:23
This is caused by https://github.com/ppy/osu-framework/issues/3120, and has been fixed (will be fixed in the next release).

**Closed by smoogipoo** 2019-12-18 12:23 UTC
