### ISSUE TITLE
Wiggle mod can break hit circle's flash effect

### ISSUE THREAD

**Issue by Feodor0090** [ppy/osu#13752] opened 2021-07-02 22:17 UTC
When wiggle mod is enabled, the flash of hit circle can appear in wrong place.

https://user-images.githubusercontent.com/53872073/124332673-ad11bf00-db9a-11eb-8592-3766b06cf900.mp4

Map: https://osu.ppy.sh/beatmapsets/1074044#osu/2248511 (Normal)

**osu!lazer version:** 2021.703.0

**Logs:** https://drive.google.com/file/d/154EpaU-r0dZRSNjXjtybc5zjVb1VMMba/view?usp=sharing

**Comment by Joehuu** [comment] 2021-07-02 22:19
Duplicate of https://github.com/ppy/osu/issues/12661

**Closed by Joehuu** 2021-07-02 22:19 UTC
