### ISSUE TITLE
Crash whilst viewing replay 

### ISSUE THREAD

**Issue by Axilotl17** [ppy/osu#21492] opened 2022-12-02 05:22 UTC
### Type

Crash to desktop

### Bug description

I was watching a replay & it crashed; replay was also having misses where there shouldnt be (it was an FC replay) and other issues before crashing. 

### Screenshots or videos

N/A

### Version

2022.1123.0-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/10138284/logs.zip)

**Comment by Axilotl17** [comment] 2022-12-02 05:23
[replay-osu_111680_4327635852.zip](https://github.com/ppy/osu/files/10138288/replay-osu_111680_4327635852.zip)
forgot to add replay

**Comment by peppy** [comment] 2022-12-02 07:20
Duplicate of https://github.com/ppy/osu/issues/20737

**Closed by peppy** 2022-12-02 07:20 UTC
