### ISSUE TITLE
Single-thread sound bug

### ISSUE THREAD

**Issue by Pythonimous** [ppy/osu#8416] opened 2020-03-23 18:51 UTC
**Describe the bug:** 
While single-threaded, weird clicking appear throughout the gameplay (check attached archive for audio file). The noises do not seem to be connected to any specific hit/miss scenario, although it might help to check the beatmap itself for reference (for testing purposes, I used https://osu.ppy.sh/beatmapsets/399372#osu/869222 ).
The noises might be getting frequent with overheating and / or the longer the map goes. However, they do not occur while multi-threaded (different issues there: random lag spikes, etc.), and gameplay is problem-free, save for noises. It also seems to be gameplay-only, no such thing in menu (e.g. simply listening to a song).
Edit 1: I have hitsounds disabled, so this bug appears to be unrelated to them.
**Screenshots or videos showing encountered issue:** 

[sound bug.zip](https://github.com/ppy/osu/files/4371283/sound.bug.zip)
Approximate "click" timings (for easier analysis) are:
Mp3 file - 0:18, 0:25, 0:54, 1:25, 1:45, 2:18, 2:38, 3:15, 3:19, 4:10, 4:26;
Beatmap - 0:02, 0:09, 0:38, 1:09, 1:29, 2:02, 2:22, 2:59, 3:03, 3:54, 4:12.

**osu!lazer version:** 
Ubuntu, AppImage; 2020.320.1

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4371510/logs.zip)

**Comment by Pythonimous** [comment] 2020-03-23 19:12
- Unrelated to FPS limit (I initially encountered the issue at "unlimited", but 8x, 4x, etc. have it as well)
- Switching between devices (Intel, PulseAudio Sound Server) does not resolve the issue either.
- Unrelated to layout: replicated a bug both in windowed and borderless (encountered in fullscreen)

**Comment by peppy** [comment] 2020-03-24 01:59
As you are using linux, it is likely related to something outside of the game. We can't really support linux-side issues. I could recommend you try resetting your audio setup or kernel.

If someone can repro this on windows or macOS we can begin to investigate further.

**Comment by Pythonimous** [comment] 2020-03-24 08:27
Replicated on Windows, description identical.
Logs attached.
[win_logs.zip](https://github.com/ppy/osu/files/4374068/win_logs.zip)

**Comment by peppy** [comment] 2020-03-24 08:28
Could you please run with the Ctrl-F2 view open? After doing so for a few minutes (maybe play one or two beatmaps), please attach the generated performance logs (there should be a few new files).

**Comment by Pythonimous** [comment] 2020-03-24 08:36
Do I need to do this on Win, or Linux is ok?

**Comment by peppy** [comment] 2020-03-24 08:40
Windows. The logs are only generated correctly on windows.

**Comment by Pythonimous** [comment] 2020-03-24 08:51
Here you go. Might be some extra lines because laptop ran out of battery on me, I don't know what the behaviour is in such a case :)

[win_logs.zip](https://github.com/ppy/osu/files/4374213/win_logs.zip)

**Comment by peppy** [comment] 2020-03-24 08:53
So from that, it looks like your audio thread is running *insanely* slow. Likely due to the number of samples being played back. Could you please include your hardware specs?

**Comment by Pythonimous** [comment] 2020-03-24 09:03
Separate laptops, Win is old, Ubuntu was bought strictly for work / studies.
Intel Core i7-8665U 1.90x8, 16gb RAM Mesa Intel UHD Graphics 620 (WHL GT2) - Linux
Intel Core i7-4510U 2.00x2, 8gm RAM, GeForce 840M - Win
To reiterate, multi-thread shows performance issues (random lag spikes, etc.) without any sound problems, while single-thread runs smoothly, but has sound lag.

**Comment by Pythonimous** [comment] 2020-03-24 09:04
Will include complete specs, if need be.

**Comment by peppy** [comment] 2020-03-24 09:12
And confirm it only happens during gameplay, not song select?

**Comment by Pythonimous** [comment] 2020-03-24 09:17
True, gameplay only (both my own, autoplay and replays). Although it might also occur in main menu (was unable to replicate it intentionally, but very rarely going from menu to song list also clicks.

**Comment by peppy** [comment] 2020-03-24 09:19
Are you able to make a sound recording on windows? I'm curious if it sounds the same or not. If this is caused by buffer underrun it will probably sound different on windows.

**Comment by Pythonimous** [comment] 2020-03-24 09:21
On it, but as far as I could tell, it sounded virtually the same.

**Comment by Pythonimous** [comment] 2020-03-24 09:44
Here you go.
I switched maps mid-recording (https://osu.ppy.sh/beatmapsets/180138#osu/433005), and the sound, funnily enough (on win, same sounds on linux) changed to a more of a quiet thump (might be hard to hear, but those are definitely not supposed to be in a map). Went for some autoplay by the end, there a couple of lags there as well.
[win-rec.zip](https://github.com/ppy/osu/files/4374415/win-rec.zip)
Approximate time stamps (at least those I've caught)
Clicks: 0:45, 1:05, 1:45, 2:00; 2:51 (faint, 2 in a row);
Thumps: 2:21, 2:27, 3:04, 3:11, 3:44, 3:47.

**Comment by Joehuu** [comment] 2021-04-22 18:47
This is probably fixed in https://github.com/ppy/osu-framework/pull/4336.

**Closed by Joehuu** 2021-04-22 18:47 UTC
Labels: area:gameplay, type:audio, type:performance
