### ISSUE TITLE
osulazer android crashed

### ISSUE THREAD

**Issue by bankerza123** [ppy/osu#5400] opened 2019-07-18 10:54 UTC
i cannot play osu lazer on android.
1.https://youtu.be/FyC50gwx2n8
when i click on music in osu!direct it crashed.
2.https://youtu.be/DM2f-dT6wjE
When i go to play on solo, it crashed.

Fix please. i compiled from xamarin. It same problem, And i download from play store. It same problem.
i using nubia z9 max android 5.1
and xiaomi redmi 5a android 7.1.2(same crashed)

Sorry for bad english. i am from thailand ,i not good english.

**Comment by l3lackShark** [comment] 2019-07-18 20:53
First of all, do not download the game from anywhere besides GitHub. It is the only source that osu!lazer provide official builds. It can potentially have some malware in it. Plus, these videos won't be much help as long as you don't provide the logs of the crash. I can only assume that the problem might have to do with your system language. Please, change the language and report if the crash disappeared. If it is a humanizer problem, then this could be closed as a duplicate of #5279

**Comment by bankerza123** [comment] 2019-07-19 05:09
Thank you, When i change my language to english, crash has disappeared. But it so lag.

**Comment by Joehuu** [comment] 2019-07-19 05:26
Indeed a duplicate of #5279.

**Closed** 2019-07-22 10:04 UTC
Labels: missing details
