### ISSUE TITLE
Can't login Bad Request

### ISSUE THREAD

**Issue by Galaxy-VN** [ppy/osu#13779] opened 2021-07-05 04:27 UTC
**Describe the bug:** 
I can't login to osu!lazer after my parents change the wifi since osu!stable can still login fine

**osu!lazer version:** 
2021.703.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6761640/network.log)

**Comment by peppy** [comment] 2021-07-05 04:29
Are you sure you are using your email address to login?

If so, please provide your username or user id so I can investigate further (this may be a backend issue with your account).

**Comment by Galaxy-VN** [comment] 2021-07-05 04:36
Im 

> Are you sure you are using your email address to login?
> 
> If so, please provide your username or user id so I can investigate further (this may be a backend issue with your account).

Im using my username to login in, my username is GalaxyVN

**Comment by peppy** [comment] 2021-07-05 04:41
One thing I can suggest you try is going into your account settings on the website and removing all oauth authorisations (should be at the bottom of your settings area).

**Comment by Galaxy-VN** [comment] 2021-07-05 04:43
> One thing I can suggest you try is going into your account settings on the website and removing all oauth authorisations (should be at the bottom of your settings area).

all cache authorize? hmm im using brave client anyway

**Comment by peppy** [comment] 2021-07-05 04:44
Actually as it turns out lazer sessions aren't listed there yet. I'll look into this for you later.

**Comment by Galaxy-VN** [comment] 2021-07-05 04:45
> Actually as it turns out lazer sessions aren't listed there yet. I'll look into this for you later.

ok thanks you

**Comment by nanaya** [comment] 2021-07-05 05:04
Apparently it's a very badly worded message for invalid password?

**Comment by peppy** [comment] 2021-07-05 05:09
Closing as duplicate of https://github.com/ppy/osu/issues/4086 (and will add this to my own todo list, as it's a pretty bad UX right now).

@Galaxy-VN please check your password as you're likely typing it wrong.

**Closed by peppy** 2021-07-05 05:09 UTC
Labels: type:online

**Comment by Galaxy-VN** [comment] 2021-07-05 06:01
> Closing as duplicate of #4086 (and will add this to my own todo list, as it's a pretty bad UX right now).
> 
> @Galaxy-VN please check your password as you're likely typing it wrong.

tks its worked now, i just remember i was changed password 3days because can't login so i though changed password will work
