### ISSUE TITLE
Increasing mouse sensitivity with Raw input makes cursor fly to the edges of the screen instantly

### ISSUE THREAD

**Issue by WhiteSp1rit** [ppy/osu#8184] opened 2020-03-08 21:08 UTC
**Describe the bug:** 
On Linux with Raw Input enabled, increasing mouse sensitivity by any amount gives cursor insane speed, it goes to the edge of the screen with the smallest movement, making it uncontrollable.

**osu!lazer version:** 
2020.306.0

**Logs:**
[logs.tar.gz](https://github.com/ppy/osu/files/4303856/logs.tar.gz)

**Comment by jai-x** [comment] 2020-03-08 21:10
Duplicate of https://github.com/ppy/osu/issues/3489

Please search for existing issues before opening new ones

**Closed** 2020-03-08 21:19 UTC
