### ISSUE TITLE
Multi finger tapping for mobile

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#12409] opened 2021-04-14 05:45 UTC
On mobile I am sure that playing a steam map or alternation map is really difficult with only one hand or with out a keyboard, so when your on the go you should be able to use two fingers to click on the side or somewhere like how osu droid or opsu does it.

**Comment by frenzibyte** [comment] 2021-04-14 05:46
Duplicate of https://github.com/ppy/osu/issues/4201, please search for existing issues before reporting as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

**Closed by frenzibyte** 2021-04-14 05:46 UTC
