### ISSUE TITLE
Bass is busy! Linux

### ISSUE THREAD

**Issue by DomiZone1** [ppy/osu#11591] opened 2021-01-24 22:26 UTC
**Describe the bug:** 
Since propably 2020.814.0 i get Bass is busy error everytime some other application is open like Firefox,
if i start osu!lazer after as first application and then Firefox, Firefox wont be able to play any sound!

---
After a litle testing it seems only when a for ex. a youtube video is playing while osu!lazer is starting the error occurs,
also when the bass is busy error message pops up all applications includíng osu!lazer can play audio!

**osu!lazer version:** 
Started propably with 2020.814.0
before that i had extrem issues with audio latency!
Currently using: 2021.118.1

OS: Linux Ubuntu 20.04

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5863328/runtime.log)

**Comment by bdach** [comment] 2021-01-24 22:31
I can guarantee you that this does not always happen on linux, and there is not enough information about your audio setup in your description to even hazard a guess what the cause might be. I'd recommend reviewing your audio device setup and seeing whether changing anything helps.

Closing due to not enough info and high likelihood this is local to your setup. Will be reopened if you provide more info that indicates that is not the case.

**Closed by bdach** 2021-01-24 22:31 UTC
