### ISSUE TITLE
pressing ` (grave) key with esc at the same time in song select screen causes wierd bug (most likely game crash)

### ISSUE THREAD

**Issue by owoDeveloper** [ppy/osu#12900] opened 2021-05-22 07:04 UTC
**Describe the bug:** 
If you press ` key and ESC key at the same time in song select screen, most likely it causes game crash after a wierd bug.

**Screenshots or videos showing encountered issue:** 

*No audio included.*

https://user-images.githubusercontent.com/77315866/119217703-d9a3d700-bb16-11eb-9406-237a11d65aec.mp4

**osu!lazer version:** 
2021.515.0 (official latest release from github.)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6525981/database.log)
[network.log](https://github.com/ppy/osu/files/6525982/network.log)
[performance.log](https://github.com/ppy/osu/files/6525983/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6525984/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6525985/updater.log)

**Comment by frenzibyte** [comment] 2021-05-22 08:12
Duplicate of #11511

**Closed by frenzibyte** 2021-05-22 08:12 UTC
