### ISSUE TITLE
Raw input broken for trackpads in macOS Catalina

### ISSUE THREAD

**Issue by Mic238** [ppy/osu#4959] opened 2019-06-08 03:28 UTC
I played with TUIO trackpad on Mac and raw input doesn't seem to response to trackpad or TUIO input, only the mouse would work. 

MacOS 10.15 Catalina Dev Beta 1, osu! Lazer  2019.607
I'm not sure if it's the problem of the new system, as the old wine client works fine in the previous system. But it stops working on Catalina and I have to move to Lazer. 
Catalina has input monitor permission which has been opened for osu, otherwise raw input would completely stop working including mouse.

**Comment by swoolcock** [comment] 2019-06-08 05:36
Catalina was only announced days ago and is currently bleeding edge.  I'd consider this low priority.

**Comment by peppy** [comment] 2019-06-08 06:36
Can you confirm you are talking about lazer? This repository is not for wine support.

**Comment by Mic238** [comment] 2019-06-08 07:34
> Can you confirm you are talking about lazer? This repository is not for wine support.

yes and all I mean was, I only installed lazer in Catalina and I haven't tried it on the older ones, so I'm not sure if this problem happened only in the new system or it was in the earlier systems as well, obviously this will make the priority difference.

**Comment by Mic238** [comment] 2019-10-01 12:41
#6290 This seems to be the same issue as in Mojave as well, not exclusively in Catalina

**Comment by peppy** [comment] 2019-10-02 21:29
Closing as duplicate of #6290

**Closed by peppy** 2019-10-02 21:29 UTC
Labels: framework fix required, low priority, macOS
