### ISSUE TITLE
Touch Screen Support on Android Build.

### ISSUE THREAD

**Issue by n1zmarck** [ppy/osu#10341] opened 2020-10-02 21:26 UTC
**Describe the new feature:** 
Support for touchscreen in osu mania,
**Proposal designs of the feature:** 
register as respective keypress on toggle/collision zones.

**Comment by frenzibyte** [comment] 2020-10-02 21:26
Duplicate of https://github.com/ppy/osu/issues/4201, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2020-10-02 21:28 UTC
