### ISSUE TITLE
Statistics not being synced in osu website and also in app's profile section

### ISSUE THREAD

**Issue by 1CH1GO** [ppy/osu#9223] opened 2020-06-06 19:21 UTC
**Describe the bug:** 
* For some reason, my osu statistics are not being updated in osu site. I have an internet connection while playing the game.
**Screenshots or videos showing the encountered issue:** 
<a href="https://ibb.co/mvmJyP6"><img src="https://i.ibb.co/jVdhwjg/Screenshot-from-2020-06-07-00-41-35.png" alt="Screenshot-from-2020-06-07-00-41-35" border="0"></a>

* As you can see i have played two normal maps and got a C rank but the same is not updated in my profile and the osu website profile.

<a href="https://ibb.co/0QPnCQ2"><img src="https://i.ibb.co/M9qgc9S/Screenshot-from-2020-06-07-00-50-16.png" alt="Screenshot-from-2020-06-07-00-50-16" border="0"></a>

* Here my played games are zero.

**osu!lazer version:** 
2020.603.0
**Logs:**

[database.log](https://github.com/ppy/osu/files/4740861/database.log)
[network.log](https://github.com/ppy/osu/files/4740862/network.log)
[performance.log](https://github.com/ppy/osu/files/4740863/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4740864/runtime.log)

**Comment by aspriddell** [comment] 2020-06-06 19:27
osu!Lazer does not yet submit scores. If you want to get your scores to show on the site and on leaderboards, you'll need to play them on the stable version of the client (see https://osu.ppy.sh/home/download).

**Comment by Game4all** [comment] 2020-06-06 19:29
Duplicate of #7379

**Closed** 2020-06-06 19:30 UTC

**Comment by 1CH1GO** [comment] 2020-06-06 19:38
Ok, thanks for the lightning-fast reply :slightly_smiling_face: . I am on Linux and I downloaded the osu file from here. So is there any stable-version of osu for Linux?. The one that is linked here is only osu!lazer.

Again thanks for your time and have a good day.

**Comment by peppy** [comment] 2020-06-07 02:37
There is not (although you can find wine installation guides if that's your kind of thing). We hope to add more stats tracking to lazer in the near future, though.
