### ISSUE TITLE
Replays using the Difficulty Adjust mod play back without the difficulty parameters set by the mod

### ISSUE THREAD

**Issue by kiutsushou** [ppy/osu#10547] opened 2020-10-17 02:06 UTC
**Description:** Saved replays of plays using the Difficulty Adjust mod play back as if it is a NoMod play, especially noticeable when the difficulty was adjusted to have a lower circle size or accuracy/OD
As far as I'm aware reproducing the bug is as simple as saving a replay with Difficulty Adjust with changed CS and playing it back

**osu!lazer version:** 2020.1017.0 /    current

**Comment by Joehuu** [comment] 2020-10-17 02:38
Duplicate of https://github.com/ppy/osu/issues/8569

**Closed by Joehuu** 2020-10-17 02:38 UTC
