### ISSUE TITLE
The cursor become invisible after 2nd starting

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#9269] opened 2020-06-12 22:13 UTC
**Describe the bug:** 

Recently I updated osu!lazer to 2020.603.0 everything was okay but after some restarts the cursor is invisible. I reinstalled osu!lazer but for the first start the cursor is visible, but after the 2nd it disapear...

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

2020.613.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4773456/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4773457/performance-gamethread.audio.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4773458/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4773459/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4773461/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4773462/updater.log)
[database.log](https://github.com/ppy/osu/files/4773463/database.log)
[network.log](https://github.com/ppy/osu/files/4773464/network.log)

**Comment by frenzibyte** [comment] 2020-06-12 22:15
PC specification please

**Comment by MTGPROD** [comment] 2020-06-12 22:30
Dell Optiplex 7010:

8GB of RAM
i3-3220 3.30Ghz
Intel HD Graphics 4000 or 2500 idk
Win 10 Pro

**Comment by Joehuu** [comment] 2020-06-12 22:34
Duplicate of https://github.com/ppy/osu/issues/8487. Try doing https://github.com/ppy/osu/issues/8487#issuecomment-618124942 and comment there if it fixes the issue or not.

**Closed by Joehuu** 2020-06-12 22:34 UTC
