### ISSUE TITLE
Glow stacks and do not disappear when rewinding in autoplay or replay

### ISSUE THREAD

**Issue by Lilly-Soryu** [ppy/osu#20115] opened 2022-09-03 18:38 UTC
### Type

Cosmetic

### Bug description

In autoplay or replay mode, when rewinding the glow of the notes starts to build up and doesn't fade away. The only way to make it disappear without leaving the map is to go too far forward.
This doesn't happen if you've fast-forwarded and rewinded to a part that hasn't been loaded yet.

### Screenshots or videos

![Glow](https://user-images.githubusercontent.com/96931452/188283113-18c777ff-40a2-468c-943a-d776731eb5d9.png)

### Version

2022.902.1

### Logs

[database.log](https://github.com/ppy/osu/files/9483145/database.log)
[network.log](https://github.com/ppy/osu/files/9483146/network.log)
[performance.log](https://github.com/ppy/osu/files/9483147/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9483148/runtime.log)

**Comment by peppy** [comment] 2022-09-08 06:17
Duplicate of https://github.com/ppy/osu/issues/9117

**Closed by peppy** 2022-09-08 06:17 UTC
Labels: ruleset:osu!mania, type:UI, priority:1
