### ISSUE TITLE
Cursor Is Not Bound To A Screen/IO Constraint

### ISSUE THREAD

**Issue by Menthol1023** [ppy/osu#1652] opened 2017-12-04 00:06 UTC
The cursor on Osu!Lazer is able to move far off the screen, making it very difficult to have it go back to where you can see it. It is also obvious when the background moves and moves opposite of the mouse, and it will move off the screen, meaning the cursor has also moved off the screen, far beyond where the player can see/and or you can interact with.

**Comment by peppy** [comment] 2017-12-04 00:19
Duplicate of https://github.com/ppy/osu-framework/issues/811

**Closed by peppy** 2017-12-04 00:19 UTC
