### ISSUE TITLE
Lazer opens wrong user when selecting mapper on song select

### ISSUE THREAD

**Issue by hrfarmer** [ppy/osu#14292] opened 2021-08-14 16:13 UTC
**Describe the bug:** 
On multiple maps by [Ryuusei Aika](https://osu.ppy.sh/users/7777875), Lazer will open the wrong profile when selecting them on song select. It instead opens a profile of one of the people who made a GD.

3 of the maps that have this issue 
https://osu.ppy.sh/beatmapsets/952132#osu/1994790
https://osu.ppy.sh/beatmapsets/1480388#osu/3036790
https://osu.ppy.sh/beatmapsets/1515350#osu/3102460

**Screenshots or videos showing encountered issue:** 
https://streamable.com/y202zw
**osu!lazer version:** 
2021.809.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6986787/database.log)
[network.log](https://github.com/ppy/osu/files/6986788/network.log)
[performance.log](https://github.com/ppy/osu/files/6986789/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6986790/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6986791/updater.log)

**Comment by frenzibyte** [comment] 2021-08-14 16:15
Duplicate of https://github.com/ppy/osu/issues/12965

**Closed by frenzibyte** 2021-08-14 16:15 UTC
