### ISSUE TITLE
Slider reverse arrow appears in incorrect place when modifying via timeline

### ISSUE THREAD

**Issue by Maks1mio** [ppy/osu#26633] opened 2024-01-19 22:56 UTC
### Type

Cosmetic

### Bug description

I made the map through the editor osu!lazer and on the 27th second of the map I got this bug

### Screenshots or videos

https://evt.tixte.co/131202024.mp4

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13995304/compressed-logs.zip)

**Comment by shps18ppt** [comment] 2024-01-21 12:57
can you elaborate?

**Comment by bdach** [comment] 2024-01-21 14:04
![image](https://github.com/ppy/osu/assets/20418176/68276065-ef50-4553-9436-5f57fa23cf60)

this doesn't need elaborating

**Comment by shps18ppt** [comment] 2024-01-21 14:10
ah. didnt notice that xD

**Comment by shps18ppt** [comment] 2024-01-21 14:53
no issues on my end, so i think its already fixed.

**Comment by frenzibyte** [comment] 2024-01-21 22:23
@shps18ppt I know you're trying to help here, but it's simply noise to say that an issue is resolved without linking any relevant changes (let alone the fact that it was reported no longer than 2 days ago).

I checked on latest master (b588715d2168543d2f64f843efde0d747dca0d12) and I can confirm the issue is still there.

**Comment by shps18ppt** [comment] 2024-01-21 23:39
> @shps18ppt I know you're trying to help here, but it's simply noise to say that an issue is resolved without linking any relevant changes (let alone the fact that it was reported no longer than 2 days ago).
> 
> 
> 
> I checked on latest master (b588715d2168543d2f64f843efde0d747dca0d12) and I can confirm the issue is still there.
> 
> 
> 
> 
> 
> https://github.com/ppy/osu/assets/22781491/3daa2b1d-f966-406b-a9a6-b8901ae435b2
> 
> 
> 
> 

👍

**Closed** 2024-01-22 08:21 UTC
Labels: ruleset/osu!, area:editor
