### ISSUE TITLE
Beatmap status doesn't update

### ISSUE THREAD

**Issue by Antholony** [ppy/osu#8166] opened 2020-03-07 21:38 UTC
**Describe the bug:** For example, beatmaps that were downloaded when they were qualified don't show up as ranked when they get ranked. Pretty sure the same thing goes for maps getting qualified, loved and so on. The leaderboards are correct though. Redownloading the map doesn't fix the issue either, as shown in the video linked below.

**Screenshots or videos showing encountered issue:** [Video](https://youtu.be/w-dSjwNQi6o)

**osu!lazer version:** Latest commit

**Logs:** Not needed

**Comment by bdach** [comment] 2020-03-07 21:44
Duplicate of #4823

**Comment by bdach** [comment] 2020-03-07 21:45
As for the status not updating, please restart the game and re-download again. Beatmaps get purged at next startup after deletion.

**Closed by bdach** 2020-03-07 21:44 UTC
