### ISSUE TITLE
Unable to change keybindings correctly

### ISSUE THREAD

**Issue by elramaxx** [ppy/osu#12311] opened 2021-04-06 18:48 UTC
So I decided to jump back into osu lazer and when trying to configure my keybindings (down arrow key and right arrow key) it just says [whatever key I press]-aux-tablet for example down-arrow-aux-tablet instead of just down arrow, I tried it and it doesnt work ingame. The only way I've been able to set my keys correctly is to do so VERY quickly after opening osu lazer.
Also dont know If I should add this too but Im also unable to minimize the game when in fullscreen, by ANY means.

**Comment by Joehuu** [comment] 2021-04-06 19:02
Duplicate of https://github.com/ppy/osu/issues/12164

**Closed by Joehuu** 2021-04-06 19:02 UTC
