### ISSUE TITLE
Circles progressively get more offset from the audio

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#12056] opened 2021-03-18 03:31 UTC
Originally reported in https://github.com/ppy/osu-stable-issues/issues/306

It looks like users also experience this in osu!lazer, but neither me nor @peppy can reproduce it. It's likely a BASS fix or a config setting for it that o!f can set, but we need someone that can replicate this and is able to debug, report to BASS (if required), and fix the issue.

I'm putting a minimum $150 bounty on this, because it's something that will hold back osu!lazer from replacing osu!stable for a worryingly large number of users.

**Comment by harshavb** [comment] 2021-03-18 03:42
Probably should add a bounty label.

**Comment by peppy** [comment] 2021-03-18 04:05
We can offer a bounty of up to $500 on this depending on difficulty of solution and implementation quality, for sure.

**Comment by Fvern** [comment] 2021-03-18 05:22
it's not directly relevant to this issue, but I wonder if this is related to the latency issues I experience detailed in #11763. I'll check on it if someone finds a solution.

**Comment by Vitaliaosu** [comment] 2021-03-19 00:45
Does the audio perhaps get stretched slightly somehow during processing?

**Comment by AlexCatDev** [comment] 2021-03-19 01:29
use ASIO

**Comment by shaneMenzies** [comment] 2021-03-27 02:22
I believe I have been able to recreate this bug, which seems to be caused by Windows' Audio management keeping BASS from being able to set certain device properties itself, and instead using whatever the system chooses to, specifically on Device update period and buffer length ( sources [here](https://www.un4seen.com/doc/#bass/BASS_CONFIG_DEV_PERIOD.html) and [here](https://www.un4seen.com/doc/#bass/BASS_CONFIG_DEV_BUFFER.html) ). This also lines up with previous statements of reinstalling Windows or moving to the 2016 BASS dll, since the functionality to change the device update period only came to BASS in January 2019 ([source](https://www.un4seen.com/doc/#bass/bass.html)), so I suspect that some change in how BASS interacts with that was significantly changed at that point. 

Luckily there is BASSWasapi, which allows these settings to be controlled through requests to the windows audio session, and with implementing Wasapi.Init(), it is possible to specify these values as shown in this [video](https://youtu.be/G27i2feMGCk), where I first set both values to a massive 1000ms to exaggerate the offset more, but I found lower combinations here to be fairly similar to what was originally reported.

I have placed a pull request in osu-framework to address this issue by including ManagedBass.Wasapi and adding a little bit of logic in InitBass to try to Initialize through Wasapi first on Windows systems, with set values that seem to be known to work (10ms Device buffer and 5ms Device Update Period), before falling back to the same method currently used if Wasapi fails. It can be found [here](). I'm not particularly experienced with C# myself, so feel free to let me know if there are better ways of implementing this, but I hope my investigation was useful nonetheless.

**Comment by peppy** [comment] 2021-03-27 02:42
Thanks for your investigation. This sounds like something we'd want to report to bass, in addition to ( 
or instead of) working around. If you feel confident, i'd suggest also opening a bug report thread on the un4seen forums stating what you've found so far. The dev will likely be able to use only the information you've given here to figure something out.

**Comment by shaneMenzies** [comment] 2021-03-27 04:40
[Done](https://www.un4seen.com/forum/?topic=19316.0). I will update here when we get a conclusion.

**Comment by peppy** [comment] 2021-03-29 04:34
I'm not sure the report you've made at bass is going to be easy to comprehend. You might want to mention the actual issue, which is desync of the clock or whatever it turns out to be.

Or put differently: the update period / buffer length changes potentially *not* propagating still should not lead to desynchronisation.

**Comment by peppy** [comment] 2021-03-30 07:20
@shaneMenzies are you 100% sure what you are seeing is the same issue? Can you make a video showing the audio offset getting worse over time?

**Comment by shaneMenzies** [comment] 2021-03-31 00:23
Hmmm, looking back at some of the original videos of the issue do seem to very clearly have it start out fine and get worse over time, were as from what I was looking at it's more of a flat delay on all sounds, so I'm starting to feel more like I was wrong in saying that I was able to replicate the issue. Sorry about that.

**Comment by peppy** [comment] 2022-07-01 09:09
Potentially related:

#18909 
ppy/osu-stable-issues#306

**Comment by OniCado** [comment] 2022-08-12 10:23
Today i was testing if multithreading affects this issue after looking at #10885 and noticed that (for me) the issue gets progressively worse over the entire session, when just starting lazer a short map may be completely playable, but after trying again the offset will already be significant at the start of the map. Pausing the map does not seem to help/reset the issue. Using Audio Compatability Mode in Stable for similar reasons. Multithreading does not seem to have any influence on it.
Windows 10 Pro N 21H2 Build 19044.1826

**Comment by peppy** [comment] 2022-08-12 10:24
Thanks for the information, but this unfortunately brings nothing new to the table in terms of figuring what causes this.

**Comment by yoyyoy** [comment] 2023-01-21 00:58
This may be related but I'm not sure. for me, the longer osu!lazer runs, the more positive offset I need. Here's an example of what can happen. The first part is after letting lazer idle on the main screen for about an hour, second part is immediately after restarting lazer, third is both played at the same time.

https://youtu.be/KNELkUuuDoM

It seems to be caused by the first circle being stuck on something, While the song plays without any delay, thus offsetting the circles. The actual audio isn't delayed like I can still hear all the hit sounds instantly. Note that in the example, when both clips are playing I had the audio play in each ear and the song synced up perfectly in both.

Side note, this didn't happen the first time I launched osu!lazer after a windows update even after 3 hours of playing, but the second time I played it happened. So it looks like that the first time launching lazer after a reboot everything works fine but something isn't cleaned up and messes things up after launching again

**Comment by peppy** [comment] 2023-01-23 04:34
This is definitely going to be something low-level in bass that we're going to have to first isolate, then report to Ian.

It may also lead to a solution (or better understanding) for https://github.com/ppy/osu-stable-issues/issues/306, although those cases look to be over the span of one beatmap play, rather than a long game session.

If what you claim is happening is actually happening, the only possibilities are:
- Bass is reporting incorrect time to us
- Your audio driver is reporting incorrect time to bass

**Comment by peppy** [comment] 2023-10-13 06:16
Is anyone subscribed to this thread still experiencing this issue actively? Have things gotten any better as of recent releases?

**Comment by yoyyoy** [comment] 2023-10-14 00:26
personally, the issue I've been having has been resolved. been exclusively playing lazer ever since that august patch and it hasn't happened since

**Comment by peppy** [comment] 2023-10-16 04:44
That's great to hear. @yoyyoy do you remember which patch particularly fixed this?

**Comment by yoyyoy** [comment] 2023-10-16 23:16
it was right after watching the lazer updates video on august 11th. I was a day late to that so 2023.812.0 is the patch I played on. but if I had to guess it was probably 2023.803.0 that actually fixed it

**Comment by peppy** [comment] 2023-10-17 06:44
Thanks for the info. I'll tentatively close this as resolved.

**Closed by peppy** 2023-10-17 06:44 UTC
Labels: osu!framework issue, audio, priority:2
