### ISSUE TITLE
Bug: can not copy past if I did use not widely used keyboard layouts

### ISSUE THREAD

**Issue by Lukas1818** [ppy/osu#13987] opened 2021-07-22 19:00 UTC
**Describe the bug:** 
If I did use the koy or the german devorak keyboard layout I can not copy and paste texts. I think this will also happen for the some other layouts too.
This does not happen with the normal de and us layout. I was also not able to reproduce  this issue with other application.

**osu!lazer version:** 
Manjaro linux [osu-lazer aur package](https://aur.archlinux.org/packages/osu-lazer/) 2021.720.0-1

**steps to reproduce:**
 * `$ setxkbmap de koy`
 * start osu lazer
 * try to copy and paste text in the search or the login-field (`v` is now at the position of the english `y`)

**Comment by bdach** [comment] 2021-07-22 19:04
Duplicate of #11143

**Closed by bdach** 2021-07-22 19:04 UTC

**Comment by Lukas1818** [comment] 2021-07-22 19:06
sorry did not see it, as I have check the existing issues

**Comment by Susko3** [comment] 2021-07-22 19:10
You can copy/paste if you press where the `C` and `V` keys would be on a US/DE keyboard. (Regardless if those keys are labelled differently on your current keyboard layout).

**Comment by Lukas1818** [comment] 2021-07-22 19:13
I have simple switch back temporally to the normal de layout for pasting my password. But I will key this workaround in mind. Thanks
