### ISSUE TITLE
i mess up when i am not supposed to, the health meter runs out way to fast 

### ISSUE THREAD

**Issue by dreaph10** [ppy/osu#8164] opened 2020-03-06 22:16 UTC
type:gameplay 
in most of my osu maps, I have downloaded the meter at the top or health meter runs out to fast when normal on regualr osu i can finish it no problem

**Comment by bdach** [comment] 2020-03-06 22:20
Duplicate of #7975

**Closed by bdach** 2020-03-06 22:20 UTC
