### ISSUE TITLE
Mods menu animation cutoff

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4215] opened 2019-02-06 13:40 UTC
**Describe your problem:** 
When opening and closing the mods menu the animation/ menu is cutoff somewhere random in the middle of the screen

**Screenshots or videos showing encountered issue:** 
Opening animation:
![osu_2019-02-06_14-36-47](https://user-images.githubusercontent.com/13122796/52345083-a9ef6480-2a1c-11e9-8285-d4d6b0a8e013.png)
Closing animation:
![osu_2019-02-06_14-38-56](https://user-images.githubusercontent.com/13122796/52345248-fe92df80-2a1c-11e9-92e4-0efee9518b36.png)

**osu!lazer version:**
2019.131.0

**Comment by peppy** [comment] 2019-02-06 14:13
I'm 99% sure this is intentional.

**Comment by oSumAtrIX** [comment] 2019-02-06 14:14
Still seems a bit strage, would need some improvements like hiding the other backgrounds behind the menu when its opened to avoid this cutoff effect

**Comment by peppy** [comment] 2021-02-18 06:56
Closing as intended. There's really no way to fix this. Also, the mods overlay is getting redesigned in the near future.

**Closed by peppy** 2021-02-18 06:56 UTC
Labels: type:UX
