### ISSUE TITLE
Recent Page

### ISSUE THREAD

**Issue by FaadeFC** [ppy/osu#29125] opened 2024-07-26 22:45 UTC
### Type

Other

### Bug description

When playing in lazer, scores do not appear in the "Recent" section of osu profile.

### Screenshots or videos

These are scores only from stable.

![image](https://github.com/user-attachments/assets/f18d88f2-9958-4d01-b2e3-7cab76e486fd)

![image](https://github.com/user-attachments/assets/8545158c-055b-4184-9233-3b3e5b9a7a54)

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16397246/compressed-logs.zip)

**Comment by bdach** [comment] 2024-07-27 00:19
duplicate of https://github.com/ppy/osu-infrastructure/issues/27

**Closed by bdach** 2024-07-27 00:19 UTC
