### ISSUE TITLE
Changing beatmap and playing it afterwards still publishes the score

### ISSUE THREAD

**Issue by eemunni** [ppy/osu#19286] opened 2022-07-21 20:01 UTC
### Type

Game behaviour

### Bug description

If you change any beatmap (for example I changed the beatmap to only have 1 spinner) and play it afterwards, the score still gets published although the beatmap was modified.

As you can see from the screenshot, people can get easy SS+ from any beatmap only by changing it to have one spinner or something else.

### Screenshots or videos

![osuthing](https://user-images.githubusercontent.com/58708787/180304647-aa8a4b93-9443-490b-822d-acc9b4c8c256.png)

### Version

2022.719.0

### Logs

[network.log](https://github.com/ppy/osu/files/9162373/network.log)
[performance.log](https://github.com/ppy/osu/files/9162374/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9162375/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9162376/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9162377/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9162378/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9162379/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9162380/updater.log)
[database.log](https://github.com/ppy/osu/files/9162382/database.log)

**Comment by apollo-dw** [comment] 2022-07-21 20:02
duplicate of https://github.com/ppy/osu/issues/11922

**Closed by apollo-dw** 2022-07-21 20:02 UTC
