### ISSUE TITLE
Editor Timeline scrolls past the mp3

### ISSUE THREAD

**Issue by Feerum** [ppy/osu#12021] opened 2021-03-16 23:15 UTC
**Describe the bug:**  
When looking at a beatmap in the editor, the timeline scrolls past the end of the mp3 length. I tested it for around 30sec and it continues. I have to assume it would continue infinite.

I also tested it on various existing beatmaps. Ranked, loved, pending, unsubmitted etc. I also tested it using different game modes. It seem to happen on every one. On the stable client it stops once it reached the end of the mp3. This doesn't seem like intended behavior. 

Tried to search but couldn't find any open issue for this bug. If it already exist, sorry for double.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=rCc8wXWHSWE
Beatmap in the video: https://osu.ppy.sh/beatmapsets/1197802#osu/2496542

**osu!lazer version:**  **osu!lazer** 2021.312.0

**Comment by LeNitrous** [comment] 2021-03-17 00:20
Just 2 cents after checking for a few minutes as I might take this on or not. The issue is with `EditorClock` not respecting the length of the currently playing track.

**Comment by peppy** [comment] 2021-03-17 00:21
This is to do with `EditorClock` currently running in a decoupled mode, intended to be used to view storyboard intro/outro sections. A simple fix would be to turn it off for now (it was left on mostly so we had an example usage of this behaviour, since it's quite rare).

**Comment by LeNitrous** [comment] 2021-03-17 00:30
Doing `IsCoupled = true` would be too naive and also breaks editor seeking. It would be better to know when is the earliest start time and latest end time based on the first storyboard element or hit object. We can keep coupling but would instead add restraints to how far seeking can go.

**Comment by peppy** [comment] 2021-03-17 00:32
Yep, should be simple enough. The earliest storyboard element is already exposed, FWIW.

**Comment by bdach** [comment] 2021-03-17 05:15
Duplicate of #8134

**Closed by bdach** 2021-03-17 05:15 UTC
Labels: area:editor
