### ISSUE TITLE
osu!catch droplets don't account for the final accuracy percentage

### ISSUE THREAD

**Issue by VelperK** [ppy/osu#8079] opened 2020-03-01 16:56 UTC
Droplets account for the final accuracy % count in stable and it's been like this for years, I don't see why that should be different in lazer

**Comment by bdach** [comment] 2020-03-01 17:32
Currently big droplets are accounted for in accuracy and tiny droplets are not (due to having `AffectsCombo` set to `False`, which makes them bonus judgements). I don't know for sure if that was intentional or not but please be aware that lazer might not necessarily mechanically mirror stable 1:1 in all regards.

**Comment by peppy** [comment] 2020-03-02 05:20
I believe this should be changed to match stable.

**Comment by Shadowthegod** [comment] 2020-08-01 16:54
Bumping this up as we are currently discussing an alternative scoring for catch mode and this came up as an issue meanwhile. However, droplets, or TinyDroplets as it is used in CatchTinyDropletJudgement.cs should not affect combo, only accuracy. That way scoring should match with stable almost 1:1 and then we can try to figure out how accuracy and combo could be weighted towards 1m and make suggestions if needed.

**Comment by smoogipoo** [comment] 2020-08-03 10:55
@Shadowthegod I'm aware there are people working on catch's scoring behind-the-scenes, but do note that tiny ticks already don't affect combo: https://github.com/ppy/osu/blob/8a9036938f30da45e3fa37b3446a636abad45cec/osu.Game.Rulesets.Catch/Judgements/CatchTinyDropletJudgement.cs#L10

**Comment by Shadowthegod** [comment] 2020-08-03 11:15
The problem is, that they are not affecting accuracy either even though that they should. And they do not count towards score either. Not affecting combo is good, that is something we want, but they should still affect everything else.

**Comment by smoogipoo** [comment] 2020-08-03 11:23
Hmm seems like maybe the current structure of Judgements is inadequate for this... Something like:
```csharp
class Judgement
{
    // Whether a hit/miss will increase/decrease the combo.
    public virtual bool AffectsCombo => true;

    // Whether the result should apply to the accuracy portion of the score and affect the shown accuracy percentage.
    public virtual bool AffectsAccuracy => AffectsCombo;

    // Whether the result should apply to the bonus portion of the score.
    public virtual bool IsBonus => !AffectsAccuracy;

    public Judgement()
    {
        Debug.Assert(AffectsAccuracy != IsBonus);
    }
}
```
This would be a non-breaking way of going about it, though as I've mentioned in the past, these bools are becoming a bit unwieldy, and almost like there should be a different data type for them.

**Comment by bdach** [comment] 2020-08-03 12:02
Small ticks should also give score (10 points to be exact). If they don't then that sounds like an actual bug.

I'll play devil's advocate here for a while and say that I'd dislike more scoring complexity. Right now scoring rules are dead simple in that a judgement either:

* affects combo, counts for accuracy, is included in 1M score cap, or
* does not affect combo, does not affect accuracy, is not included in 1M score cap (but *does* award bonus score).

Clear distinction of what's important to hit and what's a bonus. More complexity could obstruct user understanding.

**Comment by Shadowthegod** [comment] 2020-08-03 12:17
Tiny Droplets should not count as bonus but actual hitobjects, without affecting combo. I see that they are currently implemented to give 10 score but that should go into the base 1.000.000 and not above. Unless this is already the case and I misunderstood the code somewhere and my testing had a hole. 

@bdach More scoring complexity is required because currently, osu!catch is a pure combo game and people already quitting Spotlights because of this. It needs to be improved to create a competitive and actually fun environment to play. This requires that the current scoring be at least 1:1 with stable first, which does count droplets as an object without affecting combo. Is it important to hit? No, but else it lowers your accuracy. And we have a plan to include accuracy in the final score in the future but that is for another topic after this is fixed.

**Comment by peppy** [comment] 2020-09-08 08:00
Decoupling combo and accuracy is something we have avoided doing in lazer until now. I'd be hesitant to do this without consideration.

**Comment by bdach** [comment] 2024-07-06 05:50
Pretty sure this is resolved by now.

**Closed by bdach** 2024-07-06 05:50 UTC
Labels: ruleset/osu!catch, area:gameplay
