### ISSUE TITLE
Circle fade out effect

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4212] opened 2019-02-05 20:36 UTC
**Describe the feature:** 
An osu! like fade out effect the circles gave, when they were clicked.
Something like this could be avoided in osu! skins when the hit circles were invisible and instead drawn as default numbers of the circles. Lazer right now doesn't have this fade out effect so this could be added as a setting or by default and be disabled by the trick with the skin. This effect makes the gameplay feel really smooth so I would be glad to see that feature come back on osu!Lazer
**Proposal designs of the feature:** 
![effect](https://user-images.githubusercontent.com/13122796/52302419-66014e80-298d-11e9-9c5c-73988cd4fde3.png)

**Comment by peppy** [comment] 2019-02-05 23:05
This is only missing for skinned circles, and was intended to be added back of course.

**Comment by Joehuu** [comment] 2019-08-22 08:57
Fixed in #5464.

**Closed** 2019-08-22 09:01 UTC
Labels: skinning
