### ISSUE TITLE
fail rate bars are broken

### ISSUE THREAD

**Issue by KisaragiEffective** [ppy/osu#5125] opened 2019-06-23 02:19 UTC
**Describe the bug:** fail rate graph bars are vertical mirrored

**Screenshots or videos showing encountered issue:** ![A8013A8E-EC62-47FA-B413-A8072C12A7DE](https://user-images.githubusercontent.com/48310258/59970732-83376200-95a8-11e9-9575-6f1ded3c8ab9.png)

**osu!lazer version:** 2019.6.21 on iphone 7, ios 12

**Logs:** none

**Comment by Joehuu** [comment] 2019-06-23 02:22
Duplicate of #4931.

**Comment by nyquillerium** [comment] 2019-06-23 15:06
closing as duplicate

**Closed by nyquillerium** 2019-06-23 15:06 UTC
