### ISSUE TITLE
Score on touch device doesn't submit touch mod

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#12548] opened 2021-04-23 13:08 UTC
**Describe the bug:** Score on touch device doesn't submit to osu! profile as touch mods. I don't know that is that related to #4201 or not.

**Screenshots or videos showing encountered issue:** 
This is submitted on profile.
![image](https://user-images.githubusercontent.com/7066150/115875256-386e2600-a46f-11eb-9d83-9eea0ab7b2c6.png)

This is score in local.
![image](https://user-images.githubusercontent.com/7066150/115875415-63f11080-a46f-11eb-9cbd-8aebe49b8300.png)

**osu!lazer version:** 2021.416.0

**Logs:**
`I can't find any logs folder on android by the directory you provided in comment.`

**Comment by bdach** [comment] 2021-04-23 20:47
As far as I know the game does not attempt yet to ascertain whether the score was achieved using a touch device in any way (or at least I don't see a code path that would look like it's doing so), so it's only natural that this would not work *yet*.

**Comment by Joehuu** [comment] 2021-04-24 16:10
Duplicate of https://github.com/ppy/osu/issues/5378

**Closed by Joehuu** 2021-04-24 16:10 UTC
Labels: area:scoring
