### ISSUE TITLE
Sudden unexpected misses

### ISSUE THREAD

**Issue by Vince7778** [ppy/osu#26988] opened 2024-02-03 02:37 UTC
### Type

Game behaviour

### Bug description

Was just playing normally and suddenly the game retroactively gave me several misses. The misses do not appear in the replay. See the video

### Screenshots or videos

https://github.com/ppy/osu/assets/32619800/46fb9eca-d9e6-4a90-8a99-c9f353eb6706

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14149415/compressed-logs.zip)

**Comment by bdach** [comment] 2024-02-03 15:18
Likely duplicate of #26843, let's track together.

Please upload replay to that thread.

**Closed by bdach** 2024-02-03 15:18 UTC
