### ISSUE TITLE
When Autoplay plays a map, the scrollbar in the top right diseappears while setting them if we move the cursor out of the area where the scrollbar is

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#25256] opened 2023-10-26 19:31 UTC
### Type

Crash to desktop

### Bug description

When a map is played through the Autoplay mode, you can access the Playback, Visual and Audio Settings at any time.

However, when you hold a scrollbar to set something, such as the playback or the background dim, if you move your cursor out of the box where the scrollbar is located, it will hide.

Even more weird, if you moved the value at any moment, even if you go back to the original value, THEN leave the box with our cursor, you are still able to change the value, even if the scrollbar is hidden...

See video below.

**Note:** This bug does NOT happens with the loading screen when starting a beatmap, as the settings boxes aren't supposed to hide when we don't have the mouse on it.

### Screenshots or videos

https://github.com/ppy/osu/assets/57914482/bdaa332c-225d-4d8f-87c1-29dc3c9e093c

### Version

2023.1026.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13181891/database.log)
[input.log](https://github.com/ppy/osu/files/13181894/input.log)
[network.log](https://github.com/ppy/osu/files/13181895/network.log)
[performance.log](https://github.com/ppy/osu/files/13181896/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13181897/runtime.log)

**Comment by bdach** [comment] 2023-10-26 19:46
Duplicate of https://github.com/ppy/osu/issues/6121, https://github.com/ppy/osu/issues/23674, https://github.com/ppy/osu/issues/24931

**Closed by bdach** 2023-10-26 19:46 UTC
