### ISSUE TITLE
[Beatmap Editor] After slowing down map in the editor the song plays at selected speed even after quitting the editor

### ISSUE THREAD

**Issue by Rafrad** [ppy/osu#7599] opened 2020-01-24 10:41 UTC
**Describe the bug:** 
Description: After slowing down map in the editor the song plays at selected speed even after quitting the editor
Computer System: macOS
Starting state: Editor compose screen
Steps:
- Select 50% playback speed.
- Press ESC to return to the main menu.
Results: Song plays at 50% speed.
Note: Playback speed fixes after selecting a different song.

**Screenshots or videos showing encountered issue:** 
[https://drive.google.com/file/d/1EM9IDvcFDrSNPoFdFi4Njk_TIIZu__pf/view?usp=sharing](url)

**osu!lazer version:** 
osu!lazer 2020.118.0

**Comment by Gabixel** [comment] 2020-01-24 10:58
Duplicate of https://github.com/ppy/osu/issues/7468 and fixed with https://github.com/ppy/osu/pull/7594

**Closed** 2020-01-24 15:50 UTC
