### ISSUE TITLE
ModSelectOverlay causes the Home button to work incorrectly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3812] opened 2018-12-03 16:17 UTC
**Describe your problem:** The issue basically happens when the `ModSelectOverlay` is open: the `Home` button doesn't send you to the `MainMenu`, but it just closes the `ModSelectOverlay`.

**Comment by Gabixel** [comment] 2019-02-17 11:40
Seems like this issue happens again

**Comment by Joehuu** [comment] 2019-06-26 01:23
Regressed in #5149.

**Comment by peppy** [comment] 2019-06-26 01:30
This regression was intentional for now.

**Comment by Joehuu** [comment] 2019-07-28 14:47
Can reopen.

**Comment by Gabixel** [comment] 2019-09-19 16:54
Seems like this issue also happens when pressing the `X` button on Windows with the new `2019.919.0` version

**Comment by Joehuu** [comment] 2019-09-30 02:17
When the mod select is open, should clicking back button close it (current implementation) or exit to main menu?

![](https://puu.sh/EmZxe/34b913ddb9.png)

We have this close button and the escape key already.

**Comment by smoogipoo** [comment] 2019-09-30 02:29
I think we intended the back button to close mod select.

**Comment by peppy** [comment] 2019-09-30 03:09
Yep, for now this is intended.

**Comment by Joehuu** [comment] 2020-07-14 04:26
I'm trying to fix this, and wondering if there's something to check if a drawable (in this case a button) is clicked.

I'm planning to make `BackButton` public in `OsuGame`, DI `OsuGame` to `SongSelect`, and add a clicked check to the current logic inside `OnExiting`.

**Comment by peppy** [comment] 2020-07-14 04:30
A better way is likely going to be adding a new interface `ICustomBackButtonAction : IOsuScreen { Func<bool> OnBackButton() }`, then adding code in the `BackButton.Action` delegate in `OsuGame` to check whether the current screen implements this new interface, then give it a chance to handle and block (don't call `ScreenStack.Exit()`) if it returns `true`.

**Comment by peppy** [comment] 2020-07-14 04:30
In fact, you can probably get away with just adding it to `IOsuScreen` / `OsuScreen` as `protected virtual bool OnBackButton() => false;`

**Closed** 2020-07-15 05:00 UTC
Labels: area:main menu, area:song-select, type:UX
