### ISSUE TITLE
osu!mania missaligned keypress overlay when autoplaying

### ISSUE THREAD

**Issue by Lombeelo** [ppy/osu#21600] opened 2022-12-10 21:09 UTC
### Type

Cosmetic

### Bug description

When I played a beatmap in autoplay, I noticed that keys in keypress counter are not aligned same as on the main board - the first key is space (B2 on screenshot), then the other keys in right order. I have default key assignments. It causes confusion.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/73432723/206875201-12085699-ecdd-464a-8a44-c9e1b0e26897.png)
![image](https://user-images.githubusercontent.com/73432723/206875211-cb9a8c3a-46e4-4455-b738-d25a605f4a67.png)
![image](https://user-images.githubusercontent.com/73432723/206875219-55557f29-c7e1-4b4e-968d-7ef8e513960c.png)
![image](https://user-images.githubusercontent.com/73432723/206875225-8d20bd3c-0d63-4f34-9e8c-84eee36d3410.png)
![image](https://user-images.githubusercontent.com/73432723/206875282-a86f4bd4-9529-411e-9035-21bf8e520d62.png)
![image](https://user-images.githubusercontent.com/73432723/206875247-9fd4babb-9d8b-47fa-a18a-fa69cf372c00.png)
![image](https://user-images.githubusercontent.com/73432723/206875264-add79626-1808-44c6-ae56-895c3b218e1a.png)

### Version

2022.1208.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10200947/database.log)
[input.log](https://github.com/ppy/osu/files/10200948/input.log)
[network.log](https://github.com/ppy/osu/files/10200949/network.log)
[performance.log](https://github.com/ppy/osu/files/10200950/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10200951/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10200952/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10200953/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10200954/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10200955/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10200956/updater.log)

**Comment by loma-baldsson** [comment] 2022-12-10 21:28
duplicate of #20005

**Closed** 2022-12-10 21:46 UTC
