### ISSUE TITLE
I cant use target mod in lazer

### ISSUE THREAD

**Issue by OneWeebyBoi** [ppy/osu#9209] opened 2020-06-04 07:31 UTC
I tried to use the target mod but the icon is dark and im unable to play with it.

**Comment by peppy** [comment] 2020-06-04 07:32
That's because it is not implemented yet.

**Comment by peppy** [comment] 2020-06-04 07:32
Duplicate of https://github.com/ppy/osu/issues/8549

**Comment by OneWeebyBoi** [comment] 2020-06-04 07:33
ah ok, thanks.

**Closed by peppy** 2020-06-04 07:32 UTC
