### ISSUE TITLE
Samsung playing with stylus doesn't work properly

### ISSUE THREAD

**Issue by s6nistam** [ppy/osu#23487] opened 2023-05-11 17:23 UTC
### Type

Game behaviour

### Bug description

when trying to play with the s-pen on a Samsung galaxy S22 Ultra, aiming with the pen and tapping with the fingers on the side doesn't work. when you use the s-pen, no other touch inputs are accepted

### Version

2023.511.0

### Logs

[there is no log to this.log](https://github.com/ppy/osu/files/11454831/there.is.no.log.to.this.log)

**Comment by bdach** [comment] 2023-05-11 17:59
Duplicate of https://github.com/ppy/osu/discussions/22771

**Closed by bdach** 2023-05-11 17:59 UTC
