### ISSUE TITLE
Some maps not work

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#7991] opened 2020-02-25 18:37 UTC
**Describe the bug:** 

With specific beatmaps the game load the map and when it is lauched the music stop and nothing append. 

**Screenshots or videos showing encountered issue:** 

I'll add a video in few hours

**osu!lazer version:** 

2020.225.0

**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*

Still on Android

**Comment by bdach** [comment] 2020-02-25 18:39
Duplicate of #7444

**Closed by bdach** 2020-02-25 18:39 UTC
