### ISSUE TITLE
Result screen has different result for failed scores exported from osu classic before and after watching the replay

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#26126] opened 2023-12-25 18:34 UTC
### Type

Cosmetic

### Bug description

After exporting a failed score from osu classic to lazer first you see the result screen with the info like it was set in stable. After watching the replay the result screen is shown again and now it contains the misses after the play was failed.

### Screenshots or videos

For example for the replay (remove .zip at the end) the result screens before and after watching the replay look like this (the fail is at the end of the map)
[-Hindeko playing xi - over the top (-Hwangbo) [Sanctimonious] (2023-12-03_02-22).osr.zip](https://github.com/ppy/osu/files/13766996/-Hindeko.playing.xi.-.over.the.top.-Hwangbo.Sanctimonious.2023-12-03_02-22.osr.zip)
![osu_2023-12-26_03-11-45](https://github.com/ppy/osu/assets/38129679/488e58d1-5c19-4065-83af-d19108fdd824)
![osu_2023-12-26_03-12-39](https://github.com/ppy/osu/assets/38129679/691483c9-3de2-44b2-b73c-0bfa633ad783)
As you see the second one includes notes after the fail as misses. The accuracy is also affected for the same reason.
As the side note, for some reason the max combo is different by 4 and the amount of GREAT and GOOD are different.

### Version

2023.1224.0-lazer

### Logs

N/A (assuming not needed)

**Comment by bdach** [comment] 2023-12-25 18:58
Various versions of this have been reported to the point that I don't even want to waste the time to search out the most appropriate duplicate of this.

**Closed by bdach** 2023-12-25 18:58 UTC

**Comment by akiya-nagatsuka** [comment] 2023-12-25 19:07
Sure, thank you for confirming
