### ISSUE TITLE
Just WOW. (Build 18.324.1)

### ISSUE THREAD

**Issue by Gavator234** [ppy/osu#2323] opened 2018-03-28 22:50 UTC
**Screenshots:**
https://drive.google.com/open?id=1irOCdETf9NU-fKnOlDYy4lQTwLCyaXB2

**Details:**
Well then, this might be a problem. I have a DELL Inspiron 5558 running Windows 8.1 64x. I have no idea what the actual problem is, I'm just showing this to you because I have no idea whats happening. Everything's flickering rapidly and... yeah. I have just installed it on a brand new system.

Please provide where the log is so I can show it in the comments (I cannot find it anywhere on the internet). Thank you!

**Comment by jacksonisiah** [comment] 2018-03-28 22:52
the link is broken.

also, go to your Event Viewer and grab your logs there.

**Comment by jai-sharma** [comment] 2018-03-28 22:52
Duplicate of this issue: https://github.com/ppy/osu/issues/1488

**Comment by FreezyLemon** [comment] 2018-03-28 22:55
Might still be useful to get logs, since this seems to be somewhat different to the mentioned issue (that one only had issue with text not rendering properly)

You can find the logs at `%appdata%\osu\logs`.

**Comment by Gavator234** [comment] 2018-03-29 00:37
I fixed the link to show you the screenshots

**Comment by jacksonisiah** [comment] 2018-03-29 00:40
where are the logs?

>

**Comment by Gavator234** [comment] 2018-03-29 00:44
Sorry about that, I forgot about the logs for a second. I put them in the same folder as the screenshots.

**Closed** 2018-03-29 04:32 UTC
