### ISSUE TITLE
game window doesn't minimize when pressing Win+D or Win+Tab

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#6774] opened 2019-11-08 15:48 UTC
when pressing Win+D while in fullscreen, the desktop cursor becomes visible and I can interact with the desktop (click/select things ect) but the game window only hides when causing tooltips to show (e.g. "click the circles. to the beat." when hovering over the osu desktop shortcut). Same problem when using Win+Tab (Alt+Tab works fine however)

[video](https://drive.google.com/open?id=0Bz9AMQY2JNRuVTd0MU9wM2FZakk3R2RhOVhSc3laTXU2eFZR)

**Comment by bdach** [comment] 2019-11-08 16:11
Can't reproduce on my local 2019.1106.0 install actually, <kbd>Win</kbd>+<kbd>D</kbd> looks to yield focus nicely and fully in all three display modes here, both on single- and multi-monitor setups - mind giving your Windows version or some other details that could be relevant?

**Comment by LastExceed** [comment] 2019-11-08 16:25
Windows 10 Version 1903 Build 10.0.18362 x64
Dunno what else could be interesting, there's nothing peculiar in the logs or event viewer

**Comment by bdach** [comment] 2019-11-08 16:31
I seem to have the exact same version, so kind of stumped what else could be causing this. Do you have any vendor OEM programs running that could mess things up, things that could be hooking up to graphics windows, other GPU-intensive applications in the background? Heck, it could be Windows system rot for all I know...

**Comment by LastExceed** [comment] 2019-11-08 17:21
The only thing I could think of is Wallpaper Engine, but I already checked that (the video above is recorded without wallpaper engine running, hence the black desktop bg)

**Comment by peppy** [comment] 2019-11-09 03:16
Everything works as expected here too.

**Comment by bdach** [comment] 2019-12-17 18:00
Closing due to lack of reliable reproduction steps.

**Closed by bdach** 2019-12-17 18:00 UTC
Labels: compatibility, missing details
