### ISSUE TITLE
Disabled mouse failure

### ISSUE THREAD

**Issue by LamGC** [ppy/osu#2868] opened 2018-06-24 02:39 UTC
OSU Lazer will still enable mouse after disabled mouse is enabled.

![image](https://user-images.githubusercontent.com/16975255/41815354-c5d133f2-779a-11e8-82e2-9c5b595d1dc3.png)
Version: 2018.622.0

**Comment by peppy** [comment] 2018-06-24 06:18
Are you saying that the buttons actually work during gameplay? Or just get counted in the key counter?

**Comment by LastExceed** [comment] 2018-06-24 06:45
Cannot reproduce, works just fine for me (mouse inputs get ignored and key counter doesn't increase).

Are you experiencing this all the time or only under certain conditions? If the latter, please provide steps to reproduce

**Comment by ekrctb** [comment] 2018-06-24 06:48
I can confirm this bug is my responsibility (from ppy/osu-framework#1611).
InputManager.TransformState is forgotten and is unreachable.

**Comment by LamGC** [comment] 2018-06-24 07:18
@peppy This situation will be fed back to the game, not just on the keypad counter.

**Comment by LamGC** [comment] 2018-06-24 07:19
@LastExceed Press F10 to disable the mouse button and click on the digital board is effective.

**Comment by amirzaidi** [comment] 2018-07-01 14:12
The Z and X buttons now become unresponsive when holding LMB/RMB while playing. I frequently squeeze my mouse with my hand and press the buttons that way, so this results in a lot of clicks not registering

**Comment by peppy** [comment] 2018-07-01 14:16
Moving to next milestone as a regression.

**Closed** 2018-07-11 09:04 UTC
Labels: bug, gameplay, input, regression
