### ISSUE TITLE
[Osu!mania] Perfect mode ended with unhandled exception

### ISSUE THREAD

**Issue by y0rune** [ppy/osu#20787] opened 2022-10-16 20:57 UTC
### Type

Crash to desktop

### Bug description

I has been started play in Osu! So I decided to have a "perfect - SS" in the my favourite map. When I played several time it ended with ended with unhandled exception.

I use the Macbook Pro with M2 chip. In case I should reproduce the bug and gather more information please give the comment in the issue. Thank you!

### Screenshots or videos

https://user-images.githubusercontent.com/10187235/196057821-53ec13a3-f503-4f0f-8283-043b72cc06b4.mp4

### Version

2022.1008.2

### Logs

[database.log](https://github.com/ppy/osu/files/9795672/database.log)
[input.log](https://github.com/ppy/osu/files/9795673/input.log)
[network.log](https://github.com/ppy/osu/files/9795674/network.log)
[performance.log](https://github.com/ppy/osu/files/9795675/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9795676/runtime.log)

**Comment by bdach** [comment] 2022-10-16 21:23
Duplicate of #19908

**Closed by bdach** 2022-10-16 21:23 UTC
