### ISSUE TITLE
Direct3D 11 renderer draws only 60 fps

### ISSUE THREAD

**Issue by Airkek** [ppy/osu#25828] opened 2023-12-18 09:07 UTC
### Type

Performance

### Bug description

After updating lazer to 2023.1218.0-lazer game started to draw only 60 fps with Direct3D 11 renderer
All works just fine with OpenGL and OpenGL legacy

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/45855057/2834cb4c-5219-46df-9d1e-f565a4703758)

### Version

2023.1218.0-lazer

### Logs

[1702890232.network.log](https://github.com/ppy/osu/files/13701653/1702890232.network.log)
[1702890232.performance.log](https://github.com/ppy/osu/files/13701654/1702890232.performance.log)
[1702890232.runtime.log](https://github.com/ppy/osu/files/13701655/1702890232.runtime.log)
[1702890232.updater.log](https://github.com/ppy/osu/files/13701656/1702890232.updater.log)

**Comment by bdach** [comment] 2023-12-18 09:14
Which version did you update from?

**Comment by Airkek** [comment] 2023-12-18 09:20
> Which version did you update from?

2023.1130.0

![image](https://github.com/ppy/osu/assets/45855057/75970e01-fbfa-42be-848a-56e03a8b0bc7)

**Comment by bdach** [comment] 2023-12-18 09:41
there is zero reason i can immediately think of why this would have broken from last release, though...

**Comment by EVAST9919** [comment] 2023-12-18 09:56
Can replicate, though this issue persists for some time and happens only in `Borderless` mode. No matter the selected refresh rate - it caps to vsync.

**Comment by Airkek** [comment] 2023-12-18 10:00
> happens only in `Borderless` mode. 

Reproducing even in fullscreen

**Comment by Airkek** [comment] 2023-12-18 10:02
> > happens only in `Borderless` mode.
> 
> Reproducing even in fullscreen

ah no, my bad, all works fine in fullscreen

**Comment by longnguyen2004** [comment] 2023-12-18 10:12
Probably comes from here https://github.com/ppy/osu-framework/blob/ba569bf2755d9d6e3c70d89b1d74d4450a6204f6/osu.Framework/Platform/GameHost.cs#L493

Not allowing tearing, by definition, is VSync. I'm using a graphics tuning tool ([Special K](https://wiki.special-k.info/) if you're interested), that allows you to override that flag, and unlimited fps works fine in borderless with the override.

**Comment by longnguyen2004** [comment] 2023-12-18 10:40
Yes, but this behavior was here for basically forever (from @EVAST9919 and my own experience), so the fact that it worked back then can probably be due to interaction with external software.
Someone also described the same issue in https://github.com/ppy/osu/issues/22962, along with a couple other cases that we weren't able to root cause.

**Comment by Airkek** [comment] 2023-12-18 10:40
> you're

probably i accidentally turned borderless mode after update

**Comment by bdach** [comment] 2023-12-18 10:41
Closing as duplicate of aforementioned discussion.

**Closed by bdach** 2023-12-18 10:41 UTC
Labels: type:performance, renderer/directx
