### ISSUE TITLE
Statistics not counted in multiplayer

### ISSUE THREAD

**Issue by Packsolite** [ppy/osu#18482] opened 2022-05-29 17:45 UTC
### Type

Game behaviour

### Bug description

Playing osu! lazer multiplayer does not increase your playtime, play count, points, hits and other statistics.

No sure if this is a bug or considered intended behaviour, but if it is intended, it is bad design imo. (should i open feature request?)
People mainly playing multiplayer building their skill in mp lobbies can be mistaken as cheaters or smurf accounts, as their playtime shows something like 1-2 hours but in reality they've played multiple days.

Statistics in osu! lazer singleplayer aswell as on stable single- and multiplayer do work, so why is lazer mp the exception?

### Screenshots or videos

Playing ALOT of multiplayer, but the statistics still look like ones of a new player:
![direct](https://user-images.githubusercontent.com/102829507/170883805-b539e85d-bb83-4572-be7e-092e632c5ab5.jpg)

### Version

2022.528.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8793920/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8793921/updater.log)
[database.log](https://github.com/ppy/osu/files/8793922/database.log)
[network.log](https://github.com/ppy/osu/files/8793923/network.log)
[performance.log](https://github.com/ppy/osu/files/8793924/performance.log)

**Comment by bdach** [comment] 2022-05-29 17:50
duplicate of #15888

**Closed** 2022-05-29 17:50 UTC
