### ISSUE TITLE
no beatmap crashes game when going into the editor.

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#8841] opened 2020-04-23 03:06 UTC
**Describe the crash:** 
Have a fresh lazer installation with no beatmaps. go into song select and ~~select mods~~. Then go into editor and see result.

Edit: No need to select mods. just go back to the menu and then to the editor

**Screenshots or videos showing encountered issue:** 
https://streamable.com/kd2mwt

**osu!lazer version:** 

97dcd54

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4519991/runtime.log)

**Computer Specifications:** 
Windows 10 Pro x64 2004, 8GB RAM, i3 6100, GTX1050Ti

**Comment by bdach** [comment] 2020-04-23 15:24
Duplicate of #7925

**Closed by bdach** 2020-04-23 15:24 UTC
