### ISSUE TITLE
Difficulty adjust can set positive or negative 0 AR, depending how you drag the slider

### ISSUE THREAD

**Issue by quat1024** [ppy/osu#28177] opened 2024-05-15 01:50 UTC
### Type

Cosmetic

### Bug description

If you enable Difficulty Adjust, enable "Extended Limits", drag the Approach Rate setting to the left side, then carefully drag it back to 0, *sometimes* the AR can be set to `-0.0` instead of `0.0`.

It doesn't happen every time, and the AR will not display as negative zero in the tooltip of the slider or next to bpm/star difficulty, but it will display as negative 0 in places where you can hover over the Difficulty Adjust mod.

Didn't see anything unusual in gameplay or with [a score submitted while the AR was set to -0.0](https://osu.ppy.sh/scores/2832278834) so I think it's just cosmetic.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/2068021/86baf7f6-2df3-48b5-97e0-917a144050ec)
![image](https://github.com/ppy/osu/assets/2068021/f0ea97d4-6208-40e5-8b95-ed8a3181d7a3)
![image](https://github.com/ppy/osu/assets/2068021/a3390aca-dedc-4322-9b8f-b66889fd4fb3)

### Version

2024.412.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15315296/compressed-logs.zip)

**Comment by bdach** [comment] 2024-05-15 06:28
Previously: https://github.com/ppy/osu/issues/23339

Potential regression from the generic math changes

**Comment by bdach** [comment] 2024-05-16 17:08
Actually the generic math changes haven't seen a release yet. And I am like 99% sure this is already fixed in master already by https://github.com/ppy/osu-framework/pull/6249.

The tl;dr is that this could happen due to the round-to-precision logic combined with the ~~stupid~~ implementation detail that in floating point, +0 and -0 are *two disparate bit patterns* that *test equal to each other* (because they're both zero). When dragging the slider from the left this -0 thing could happen if a value was rounded up to 0.

Post-https://github.com/ppy/osu-framework/pull/6249, this nonsense can no longer happen, because "signed zero" does not appear to be a thing when it comes to `decimal`s even if [the standard uses *very* wishy-washy wording on this:](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#838-the-decimal-type)

> The `decimal` type does not necessarily support signed zeros, infinities, or NaN’s.

(by the way, how do you define a language this way??? what does "not necessarily" even mean??? but I digress)

Either way I cannot reproduce in master and I can pretty reliably on last release (although it is kinda finicky, I had to mess with UI scaling to make it easier to repro). I'm gonna tentatively close as already-resolved. @quat1024 if you happen to run into this again after the next release please let us know and we'll look into this again.

Note that past replays will _not_ get fixed because they generally have `-0.0` already stored to the mods json in the replay, which then gets parsed by `Bindable.Parse`, and that bypasses all of the precision clamping logic (because `DifficultyBindable` is a `Bindable<float?>`, not a `BindableNumber<float>`). But it really doesn't matter even if it looks ugly. It's still zero. Any issue there is purely cosmetic.

**Closed by bdach** 2024-05-16 17:08 UTC
