### ISSUE TITLE
Keyboard got disabled somehow

### ISSUE THREAD

**Issue by DutchEllie** [ppy/osu#24879] opened 2023-09-21 18:28 UTC
### Type

Game behaviour

### Bug description

None of my function keys and other special keys like escape, ctrl, alt and backspace were not working at all in-game! Typing keys into the search bar worked though, but they could not be removed because backspace was broken.

I have already fixed the issue. It turns out that for whatever reason, the `input.json` file was changed to include a "false" in the "Enabled" field for the "osu.Framework.Input.Handlers.Keyboard.KeyboardHandler" type. I have NO clue why that happened at all, but this is what happened immediately before that happened for the first time, not sure if this is related.

So what happened was that I opened osu! today. It initially didn't start using the normal shortcut in the start menu (I'm using Linux btw) and it didn't work twice. So then I started it using the `flatpak run sh.ppy.osu` command from the terminal. That started the game, but then the error occurred as described above. The game would now start using the normal shortcut, but the issue persisted. After a reinstall, a consequent realization that the `files` directory truly cannot be copied over like before, and a subsequent restoration of the game files with a backup, my game was back. It was then that I looked through the `input.json` file, since it sounded like it could have been related. And that's where I saw the keyboard was disabled...

My main question is: what happened? Why would the keyboard be disabled? What disabled the keyboard and how can it be prevented in the future?
 

### Version

2023.914.0

### Logs

The logs provided are from my backup, but by then I had already restarted the game a bunch of times since it stopped working and I had to start it using flatpak again.
[runtime.log](https://github.com/ppy/osu/files/12690302/runtime.log)
[network.log](https://github.com/ppy/osu/files/12690303/network.log)
[database.log](https://github.com/ppy/osu/files/12690304/database.log)
[performance.log](https://github.com/ppy/osu/files/12690305/performance.log)
[input.log](https://github.com/ppy/osu/files/12690306/input.log)
[performance-update.log](https://github.com/ppy/osu/files/12690307/performance-update.log)
[performance-input.log](https://github.com/ppy/osu/files/12690308/performance-input.log)
[performance-audio.log](https://github.com/ppy/osu/files/12690309/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12690310/performance-draw.log)

**Comment by bdach** [comment] 2023-09-21 18:33
Duplicate of #24260

Unfortunately without capturing the original failure which caused the keyboard handler to be disabled there's not much we can work with here.

**Closed by bdach** 2023-09-21 18:33 UTC
