### ISSUE TITLE
osu!taiko blue drums cannot be hit on iOS

### ISSUE THREAD

**Issue by jbmagination** [ppy/osu#4963] opened 2019-06-08 14:08 UTC
### Bug
I attempted to play osu!taiko and was unable to hit the blue drums.

### What I expected to happen
I would be able to make a two-finger gesture (or right-click kind of) to hit the blue drum.

### What happened
The game (or maybe iOS) did not pick up my gesture and I could only hit red drums

I am using iOS 12.1 on an iPad Pro, osu!lazer version 0.1 (2019.608.0)

**Comment by swoolcock** [comment] 2019-06-08 15:34
Multi-input for non-osu! rulesets has not yet been implemented for touchscreen.  This is likely to be implemented with on-screen virtual controls.  In the meantime, a Smart Keyboard or other external keyboard should work fine.

**Comment by peppy** [comment] 2019-06-08 15:43
Duplicate of #4201.

**Closed by peppy** 2019-06-08 15:43 UTC
