### ISSUE TITLE
Using relax or autopilot mods won't allow you to fail

### ISSUE THREAD

**Issue by JustSimplyKyle** [ppy/osu#20882] opened 2022-10-23 08:29 UTC
### Type

Game behaviour

### Bug description

No, I'm not using No fail
Although this might be intended behavioiur?

### Version

2022.1022.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9846011/database.log)
[input.log](https://github.com/ppy/osu/files/9846012/input.log)
[network.log](https://github.com/ppy/osu/files/9846013/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/9846014/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9846015/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9846016/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9846017/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/9846018/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9846019/runtime.log)

**Comment by toadsworth-jr** [comment] 2022-10-23 08:55
This is intended behavior. Don't ask about this.

**Comment by bdach** [comment] 2022-10-23 15:40
See above, closing as intended.

**Closed by bdach** 2022-10-23 15:40 UTC
