### ISSUE TITLE
Fail to load score in single player mode.

### ISSUE THREAD

**Issue by UnnamedOrange** [ppy/osu#9288] opened 2020-06-15 06:54 UTC
**Describe the bug:** 

When click into the **local** score in single player mode, nothing pops out. It shows that "An unhandled error has occured."

**osu!lazer version:** 

2020.613.0(Both Windows and macOS)

**Comment by bdach** [comment] 2020-06-15 07:01
Possibly duplicate of #9266, but it should crash if it were... Please include the log files as requested in the issue template.

**Comment by UnnamedOrange** [comment] 2020-06-15 07:25
Sorry for not attaching log files because I believed they would be sent automatically...

[database.log](https://github.com/ppy/osu/files/4778633/database.log)
[network.log](https://github.com/ppy/osu/files/4778634/network.log)
[performance.log](https://github.com/ppy/osu/files/4778635/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4778636/runtime.log)

Just now I cloned the project and tried it in local debug, and it seemed all right. Maybe it has already been solved.

**Comment by peppy** [comment] 2020-06-15 07:26
Log confirms it's the already fixed issue!

**Closed by peppy** 2020-06-15 07:26 UTC
Labels: missing details
