### ISSUE TITLE
Can't import beatmaps from stable if not using default beatmap folder

### ISSUE THREAD

**Issue by uShldGetCeleste** [ppy/osu#10051] opened 2020-09-03 16:53 UTC
**Describe the bug:** When importing songs from osu! stable, osu! lazer will check the default location for the songs folder and won't check osu!.PC Username.cfg for the beatmap directory.

**osu!lazer version:** 2020.825.0

**Comment by bdach** [comment] 2020-09-03 18:31
Duplicate of #3763 (and several others). Please search before opening an issue.

**Closed by bdach** 2020-09-03 18:31 UTC
