### ISSUE TITLE
Score from replay is different from submitted score

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#26298] opened 2023-12-31 22:37 UTC
### Type

Game behaviour

### Bug description

As mentioned in #26104, I'm opening this as I know it'll come up as an issue soon with the assumed high volume of people that will be playing on lazer soon due to pp and score submission. I couldn't find another issue mentioning this and I doubt this isn't known already so sorry if it's a duplicate issue.

### Screenshots or videos

See https://github.com/ppy/osu/discussions/26104#discussioncomment-7969152

### Version

2023.1231.0

### Logs

.

**Comment by bdach** [comment] 2024-01-01 00:10
duplicate of at least one of these https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%3Areplay+

**Closed by bdach** 2024-01-01 00:10 UTC
