### ISSUE TITLE
Insufficient beatmap import capabilities

### ISSUE THREAD

**Issue by vjdato21** [ppy/osu#5515] opened 2019-07-29 16:03 UTC
**Describe the bug:** 
osu!lazer won't import a beatmap if the beatmap directory from osu!stable config was customized by the end-user.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/51854537/62063152-ef1e8180-b25c-11e9-9274-896e33766485.png)
![image](https://user-images.githubusercontent.com/51854537/62063450-6bb16000-b25d-11e9-9a99-82335781a701.png)

**osu!lazer version:** 
2019.727.0
**Logs:** 
[database.log](https://github.com/ppy/osu/files/3443127/database.log)
[debug.log](https://github.com/ppy/osu/files/3443128/debug.log)
[network.log](https://github.com/ppy/osu/files/3443129/network.log)
[performance.log](https://github.com/ppy/osu/files/3443130/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3443131/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3443132/updater.log)

**Comment by jai-x** [comment] 2019-07-29 16:07
Duplicate of https://github.com/ppy/osu/issues/3763 I think.

**Comment by peppy** [comment] 2019-07-29 16:14
Closing as duplicate and bumping priority of original.

**Closed** 2019-07-29 16:14 UTC
