### ISSUE TITLE
"Player Rank pre-view" box , "Player Info" page and "Rankings" page. INGAME is missing some things.

### ISSUE THREAD

**Issue by Dantto** [ppy/osu#30675] opened 2024-11-16 00:33 UTC
### Type

Other

### Bug description

Even though the 3 topics ca be posted separately I thought it will be simpler to treat it as 1 thing.
I'm going to refer as "web' and "ingame" to diferenciate between one and another

### **"Player Rank Pre-view" box**
![image](https://github.com/user-attachments/assets/830f2c03-4ec6-42d0-966f-44394edae297)

Love the Global an country rank by the way

I like calling it Player pre-view box
currently is showing the default game mode that the player set in the profile page
It is showing  my actual 15/11/2024 Mania Rank 

But I am playing Standar Osu! and want to see the score on this mode.
![image](https://github.com/user-attachments/assets/a1c716da-dd95-47b6-b4e8-1b58cafce6d8)

.
.
.

This should be showing the Rank of the selected mode 

if you are in osu! should be showing my osu! rank
![image](https://github.com/user-attachments/assets/6cf0ca51-19a8-443c-96d4-056be34683be)

if you are in osu!mania should be showing my osu!mania rank
![image](https://github.com/user-attachments/assets/e934854b-f978-451a-850d-15904aa2cab7)

---

### **"Player Info" Page Ingame**

This page has gone through a lot 
And here's one more thing

**The default mode selector**
This is only available in web
![image](https://github.com/user-attachments/assets/11132b0f-df19-4900-a2b1-2d0bdf2c2032)

while in game it looks like this..
![image](https://github.com/user-attachments/assets/7ec86c2e-e2c7-4317-a54c-37c8807917c5)

not big a deal just a detail.

**Pop-up info box**
whe you place the mouse cursor on top of the rank it shows aditional information
in web
![image](https://github.com/user-attachments/assets/2cd22c53-5018-4344-9793-2691c123a6e9)
in game
![image](https://github.com/user-attachments/assets/55bea374-c715-4b4d-9372-a679e0f70e18)

For osu! Standar is all right, text boxes are different but what ever
Country rank dont show highest rank but, it never did, but it could
.
.

When it comes to osu!mania though

Global Rank in web shows 4k and 7k info
![image](https://github.com/user-attachments/assets/6fd8eaa6-63d4-4216-961e-20f6e8cc6500)

Global Rank in game shows general info and not 4k and 7k
![image](https://github.com/user-attachments/assets/7f293e02-0d21-4d3c-8291-8ffbab37515a)

Country Rank in web shows the current rank in both 4k and 7k
![image](https://github.com/user-attachments/assets/b82ec9fb-a26e-43da-af6e-a40fc4d6e192)

Country rank in game doesn't
![image](https://github.com/user-attachments/assets/98d55544-a508-4dc8-8ee0-e3d154c37d36)

**Profile Picture**
Maybe in a future this could be added 
![image](https://github.com/user-attachments/assets/2125e729-8e92-41bb-9de2-379fa8216250)
be able to change avatar though the the client
this is web by the way

---

### **"Rankings" page**

While in web you are abel to browse through every page 
![image](https://github.com/user-attachments/assets/9f26bdac-9c69-49fa-a208-781c030a42d8)

In game only have acces to the top 50
![image](https://github.com/user-attachments/assets/21fb598b-f05e-4507-bc1b-aad49eb08d80)
![image](https://github.com/user-attachments/assets/ccfc71bf-9ad7-478e-b9b0-9ef6cfff995d)

Sad day to be a low rank player 😭

For  Osu!Mania, the necessities are kind different

in web shows pages yes, but more importantly the variant 4k and 7k
![image](https://github.com/user-attachments/assets/a020e8b3-fe00-4090-b463-b6102f4ff0a0)

mean while in game doesn't show either of them
![image](https://github.com/user-attachments/assets/4eef6c7e-95ae-43e7-b463-d4028e7710e4)

.
.
.

maybe its not necessary to add all the pages of the rank data base

For those simple mortal like us
add a second tab 

something call Current Rank
that will open the page on where we appear
and when time comes that whe appear in the first page 

that the seccond page gets eliminated.

And for gods Sake change it form top 50 to top 100
![image](https://github.com/user-attachments/assets/5d18019e-2464-45b1-be65-396cca0a7f45)

larger pages but half of them 

Thats all!

### Version

2024.1115.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17782675/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-11-16 01:39
> Even though the 3 topics ca be posted separately I thought it will be simpler to treat it as 1 thing.

It is not. Having one thing pointed out each issue thread is easier to track. For example, one thing may have more priority than the rest or can be assigned to different ppl to implement. Or devs will overlook some things posted here.

> "Player Rank Pre-view" box
	This should be showing the Rank of the selected mode

Duplicate of https://github.com/ppy/osu/issues/26802

---

Web features being inconsistent or not in lazer is known. You can post those separately if you want.

**Closed by Joehuu** 2024-11-16 01:39 UTC

**Comment by Dantto** [comment] 2024-11-22 20:00
> > Even though the 3 topics ca be posted separately I thought it will be simpler to treat it as 1 thing.
> 
> It is not. Having one thing pointed out each issue thread is easier to track. For example, one thing may have more priority than the rest or can be assigned to different ppl to implement. Or devs will overlook some things posted here.
> 
> > "Player Rank Pre-view" box
> > This should be showing the Rank of the selected mode
> 
> Duplicate of #26802
> 
> Web features being inconsistent or not in lazer is known. You can post those separately if you want.

ok im going separate them and delete the part that has  already a thread. Thanks
