### ISSUE TITLE
Small glitch with glowing elements

### ISSUE THREAD

**Issue by AirOne01** [ppy/osu#10506] opened 2020-10-14 20:04 UTC
**Describe the bug:** 
Glowing elements in the menu are not darkened when opening options menu or messages, this is a really small bug but I keep noticing it.

**Screenshots or videos showing encountered issue:** 
![osu](https://user-images.githubusercontent.com/21955960/96039420-e6699980-0e68-11eb-8285-a47469e21771.jpg) In options menu
![osu2](https://user-images.githubusercontent.com/21955960/96039421-e7023000-0e68-11eb-8f8a-fd5dcded334c.png) In notifications menu
![osu3](https://user-images.githubusercontent.com/21955960/96039424-e79ac680-0e68-11eb-80c7-b2dbdf4e29be.png) Normally (the glowing is the same)

**osu!lazer version:** 
2020.1009.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5380573/database.log)
[network.log](https://github.com/ppy/osu/files/5380574/network.log)
[performance.log](https://github.com/ppy/osu/files/5380575/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/5380576/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5380577/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5380578/runtime.log)

**Comment by Game4all** [comment] 2020-10-14 20:12
Duplicate of #4229

**Closed** 2020-10-14 20:13 UTC
