### ISSUE TITLE
Friend dashboard doesn't update live when going On and Offline

### ISSUE THREAD

**Issue by FakeCxrpss** [ppy/osu#30683] opened 2024-11-16 05:41 UTC
### Type

Game behaviour

### Bug description

When a player goes Offline the game's Friend dashboard does not update unless the Game is Restarted, A player will show their status that it was when the game was first opened for the user and does not change no matter what. This isn't that big of an issue in the end but it is an annoying this for me to deal with. Also, Unrelated but showing the spectators you have would be nice to have

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17783668/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-11-16 05:47
Duplicate of https://github.com/ppy/osu/issues/13604

**Closed by Joehuu** 2024-11-16 05:47 UTC
