### ISSUE TITLE
additive accuracy option

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#9885] opened 2020-08-17 08:02 UTC
additive accuracy works by adding an amount of accuracy for every judgement you get
additive accuracy will assume you will not hit anymore notes and will only increase if you any non-miss judgement

additive accuracy can be used to measure progress in the beatmap

**Comment by peppy** [comment] 2020-08-17 08:04
Seems like a pointless duplicate of score display?

**Comment by igontusuwu** [comment] 2020-08-17 08:08
in all modes, score works in a multiplicative way, this idea works accuracy into a additive display where combo doesn't influence said display
said display can be used as an raw score display or something like that

**Comment by bdach** [comment] 2020-08-17 08:18
So this would be like the opposite of #9336?

**Comment by igontusuwu** [comment] 2020-08-17 08:19
yes

**Closed** 2021-05-27 09:16 UTC
Labels: area:scoring, proposal
