### ISSUE TITLE
Able To Choose The Game File Location

### ISSUE THREAD

**Issue by hafizdkren** [ppy/osu#3333] opened 2018-08-29 07:35 UTC
Hey Dean. I'm Interest With Your Project Right Now. But Can You Make The Windows Installer For osu!lazer Because Everytime I Wanna Put Into Program Files By Copypasta It Make Some Confuse. Because It Supposed To Be Program Where Save Of Specific Location. Sorry For My Bad Grammar. But I Hope This Can Be A Feature So Person Who Had Partition / Many Drives Can Put Files Specific Place Such As Program Files

**Comment by ZenitH-AT** [comment] 2018-08-29 09:31
I think the intent at the moment is to make installation quick and wizard-less so that it can be tested quickly.

(I think there should be an option to choose songs folder location though)

**Comment by hafizdkren** [comment] 2018-08-29 09:36
Yeah. But if people wanna search code or files or folders. It will super mess because if you doesn't want to open the game it kinda must be open. Yeah we can open user show hidden folder. But it make usual people got sick. I'm a expert but i think it supposed to make a option so people not to confuse about

**Comment by peppy** [comment] 2018-08-29 09:36
There's a button in options.

**Comment by hafizdkren** [comment] 2018-08-29 09:37
And sorry for my grammar

**Comment by hafizdkren** [comment] 2018-08-29 09:42
Ok I will check.

**Comment by peppy** [comment] 2018-09-06 18:13
Duplicate of #960

**Closed by peppy** 2018-09-06 18:13 UTC
