### ISSUE TITLE
osu!lazer isn't starting up. (osu.Framework.RuntimeInfo threw an exception)

### ISSUE THREAD

**Issue by nybbleosu** [ppy/osu#2412] opened 2018-04-17 09:45 UTC
osu!lazer doesn't run.
I built it on my iMac using Visual Studio, then run it. (I was following the steps of this video: https://www.youtube.com/watch?v=_UFkvorUto)
Then, I recieved this:

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'osu.Framework.RuntimeInfo' threw an exception. ---> System.EntryPointNotFoundException: GetModuleHandle
  at (wrapper managed-to-native) osu.Framework.RuntimeInfo.GetModuleHandle(string)
  at osu.Framework.RuntimeInfo..cctor () [0x000fc] in /Users/Rythmic/Desktop/osu/osu-framework/osu.Framework/RuntimeInfo.cs:48 
   --- End of inner exception stack trace ---
  at osu.Desktop.Program.Main (System.String[] args) [0x00001] in /Users/Rythmic/Desktop/osu/osu.Desktop/Program.cs:23 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'osu.Framework.RuntimeInfo' threw an exception. ---> System.EntryPointNotFoundException: GetModuleHandle
  at (wrapper managed-to-native) osu.Framework.RuntimeInfo.GetModuleHandle(string)
  at osu.Framework.RuntimeInfo..cctor () [0x000fc] in /Users/Rythmic/Desktop/osu/osu-framework/osu.Framework/RuntimeInfo.cs:48 
   --- End of inner exception stack trace ---
  at osu.Desktop.Program.Main (System.String[] args) [0x00001] in /Users/Rythmic/Desktop/osu/osu.Desktop/Program.cs:23 

Press any key to continue...

**Comment by FreezyLemon** [comment] 2018-04-17 11:14
Likely a duplicate of #2367

**Comment by smoogipoo** [comment] 2018-04-17 11:43
You will need to update `mono` to at least 5.10 (the latest stable release).

**Closed** 2018-04-17 11:43 UTC
