### ISSUE TITLE
Can't login to osu!lazer

### ISSUE THREAD

**Issue by Kyoooooooo** [ppy/osu#12942] opened 2021-05-24 21:26 UTC
When I login it loads for a second then when back to the login screen again
as for other login problems they were stuck at attempting to connect.
[network.log](https://github.com/ppy/osu/files/6535063/network.log)
[performance.log](https://github.com/ppy/osu/files/6535064/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6535065/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6535066/updater.log)
[database.log](https://github.com/ppy/osu/files/6535067/database.log)

**Comment by frenzibyte** [comment] 2021-05-24 21:33
```
2021-05-24 21:16:03 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.Http.HttpRequestException: An error occurred while sending the request.
2021-05-24 21:16:03 [verbose]: ---> System.IO.IOException: The read operation failed, see inner exception.
2021-05-24 21:16:03 [verbose]: ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
2021-05-24 21:16:03 [verbose]: ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
2021-05-24 21:16:03 [verbose]: --- End of inner exception stack trace ---
2021-05-24 21:16:03 [verbose]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
2021-05-24 21:16:03 [verbose]: at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Byte[] buffer)
2021-05-24 21:16:03 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-05-24 21:16:03 [verbose]: --- End of inner exception stack trace ---
2021-05-24 21:16:03 [verbose]: at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean async, Boolean foldedHeadersAllowed)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: --- End of inner exception stack trace ---
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2021-05-24 21:16:03 [verbose]: at osu.Framework.IO.Network.WebRequest.internalPerform(CancellationToken cancellationToken).
2021-05-24 21:16:03 [verbose]: Login failed!
```

Looks like an SSL/TLS handshake failure. Are you able to visit the website regularly on your browser? (https://osu.ppy.sh/)

**Comment by Kyoooooooo** [comment] 2021-05-24 21:39
Yep, I can login on the website it works perfectly. Also, I was able to login to osu!lazer on my phone but not on my pc which is the problem right now.

**Comment by peppy** [comment] 2021-05-25 00:33
Probably a duplicate of https://github.com/ppy/osu/issues/12479.

Something weird about your OS (you might have disabled system services; you might be on an old version or missing a service pack).

**Closed by peppy** 2021-05-25 00:33 UTC
