### ISSUE TITLE
Pause bar fills but does not pause the game

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#10438] opened 2020-10-09 00:23 UTC
After pausing and resuming, holding `ESC` immediately will fill the pause bar but will not pause the game. If the intent here is to disallow pause spamming then the bar probably shouldn't be allowed to fill/show until pausing is allowed again.

video: https://www.youtube.com/watch?v=jZ-BtahrqMs
osu!lazer version: 2020.1005.0

**Comment by Joehuu** [comment] 2020-10-09 00:26
Duplicate of https://github.com/ppy/osu/issues/10438

**Closed by Joehuu** 2020-10-09 00:26 UTC
