### ISSUE TITLE
The game doesn't stays at background

### ISSUE THREAD

**Issue by NightmareDreemurr** [ppy/osu#11917] opened 2021-02-27 13:43 UTC
**Describe the bug:** 
The game closes itself when I switched to multitask interface, I've already changed the "Power-saving Strategy" of osu!lazer to unlimited

**Screenshots or videos showing encountered issue:** 
This is when my game starts 
![Screenshot_2021-02-27-21-39-41-306_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/59122229/109388819-68ec8480-7944-11eb-998b-396c60bd15eb.jpg)

This is when i switched to multitask interface
![Screenshot_2021-02-27-21-40-20-719_com.miui.home.jpg](https://user-images.githubusercontent.com/59122229/109388821-6d18a200-7944-11eb-901b-4d4e976dad7d.jpg)

This is when i tapped the window to get in this app again

![Screenshot_2021-02-27-21-40-24-145_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/59122229/109388824-6ee26580-7944-11eb-9a45-d456affc31e8.jpg)
uhh sorry i cant upload the video to anywhere outside China
**osu!lazer version:** 
2021.219.0
**Logs:**
Where can I locate logs on Android?

**Comment by bdach** [comment] 2021-02-27 13:45
Duplicate of https://github.com/ppy/osu-framework/issues/4200

**Closed by bdach** 2021-02-27 13:45 UTC
