### ISSUE TITLE
Can't pause song in multiplayer room

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu#9755] opened 2020-08-02 11:46 UTC
**Describe the bug:** 

You can't pause song via now playing overlay or shortcut key in multiplayer room. Is this intended?

**Screenshots or videos showing encountered issue:** 

https://streamable.com/7vnbzg (skip to 00:15 for the main issue)

**Comment by bdach** [comment] 2020-08-02 11:58
In the multiplayer room, selection of a map disables the possibility to change the working beatmap, which the now playing overlay responds to by disabling all music controller buttons. This is desirable in other contexts (as trying to e.g. pause the current track during gameplay breaks things) but in this one possibly not so much.

Maybe the ability to pause/play can be enabled if overlays are blocked during gameplay (#9743). Not sure.

**Comment by gagahpangeran** [comment] 2020-08-02 12:03
It can just enable the play/pause button only everytime there's a song played, rather than disable all the the function.

**Comment by Joehuu** [comment] 2020-08-02 17:27
Duplicate of https://github.com/ppy/osu/issues/4820

**Closed by Joehuu** 2020-08-02 17:27 UTC
Labels: area:multiplayer, proposal
