### ISSUE TITLE
Crash when alt-tabbing or changing window size (ChromeOS)

### ISSUE THREAD

**Issue by clay53** [ppy/osu#6295] opened 2019-09-27 17:40 UTC
**Describe the crash:** 
When using the APK file on ChromeOS, the client crashes if the user switches windows or tries to change the window's size.

**Screenshots or videos showing encountered issue:** 
https://www.loom.com/share/31adb467cee34857a2442a3c93c64f52

**osu!lazer version:** 
2019.925.0 APK

**Logs:** 
[Send Anywhere (2019-09-27 13-37-21).zip](https://github.com/ppy/osu/files/3663928/Send.Anywhere.2019-09-27.13-37-21.zip)

**Computer Specifications:** 
Samsung Chromeboook 3
Chrome OS Version: Version 78.0.3904.35 (Official Build) dev (64-bit) - crashes on stable, beta, and dev channel.

**Comment by bdach** [comment] 2019-09-27 18:02
Probably relevant log excerpt:
```
2019-09-27 05:31:08: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) (Value cannot be null.
2019-09-27 05:31:08: Parameter name: value) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
```
Looks like either a problem with SSL itself, or you managing to interrupt the SSL connection by alt-tabbing in the middle of it, causing a server-side connection drop. Does the crash happen when you don't alt-tab, or does the game run normally? Also, is it consistent?

I'm also curious if the logs for the resize case are the same, since I don't think that's likely from the log attached. But then again android-related stuff seems to be full of strange surprises.

**Comment by clay53** [comment] 2019-09-27 21:30
Yes, it is consistent. To be more precise, it happens whenever focus is taken away from the game which includes resizing the window.

**Comment by ticotaco72** [comment] 2019-09-27 21:40
if i remember well, osu is made in a way that it forces close on focus loss

**Comment by ticotaco72** [comment] 2019-09-27 21:41
on android

**Comment by bdach** [comment] 2019-09-27 21:44
Yeah, it's likely the context switch that does it, I just wanted to make sure it wasn't something else entirely.

**Comment by peppy** [comment] 2019-09-27 23:28
Sounds like a duplicate of the back button crash issue.

**Comment by bdach** [comment] 2019-12-17 18:17
I'm going to go on a limb and assume this is due to the [OpenGL context switches forcing the game to be killed](https://github.com/ppy/osu/issues/6593#issuecomment-546041485); therefore closing as a known issue. Please try running on ChromeOS via the Linux route, although do note that Chromebooks are pretty low-end and niche hardware and you're likely to get inadequate performance.

**Closed by bdach** 2019-12-17 18:17 UTC
Labels: hard crash / startup crash
