### ISSUE TITLE
Ability to seek and play part of a beatmap

### ISSUE THREAD

**Issue by Cholapat** [ppy/osu#11717] opened 2021-02-09 11:12 UTC
**Describe the new feature:** 
During a game, players could skip to the part they want to practice or to their favorite part.

**Proposal designs of the feature:** 
It could be an unranked mod. You could seek with the arrow keys or by clicking the progress bar when this mod is enabled.

**Comment by Gabixel** [comment] 2021-02-09 12:44
Duplicate of https://github.com/ppy/osu/issues/4175? He seems to propose the same main idea (i.e. play a part of beatmap)

**Closed** 2021-02-09 12:54 UTC
Labels: area:gameplay
