### ISSUE TITLE
Inconsistent health in gameplay and it's replay

### ISSUE THREAD

**Issue by THEKILLINGNAME** [ppy/osu#27765] opened 2024-04-01 08:10 UTC
### Type

Game behaviour

### Bug description

When i played a map, i was able to finish it for 98%, but in replay, it fails on 63%. However, if i skip skip the part, where replay fails, i'am able to watch untill 98%

### Screenshots or videos

[THEKILLINGNAME playing ryo(supercell) feat. Hatsune Miku - ODDS_ENDS (Speed Up Ver.) (elchxyrlia) [Arles] (2024-03-31_21-08).zip](https://github.com/ppy/osu/files/14821197/THEKILLINGNAME.playing.ryo.supercell.feat.Hatsune.Miku.-.ODDS_ENDS.Speed.Up.Ver.elchxyrlia.Arles.2024-03-31_21-08.zip)

https://osu.ppy.sh/beatmapsets/617809#osu/1302566

### Version

Lazer 2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14821400/compressed-logs.zip)

**Comment by Rekunan** [comment] 2024-04-01 08:46
I can't seem to reproduce on my end or find anything in the log files. Would it be possible to get a video of it failing early?

**Comment by THEKILLINGNAME** [comment] 2024-04-02 06:18
> Would it be possible to get a video of it failing early?


https://github.com/ppy/osu/assets/66118745/7d916633-be7d-48db-8196-a3f8269c1ca3

**Comment by 64ArthurAraujo** [comment] 2024-04-02 07:10
For me you don't even die in 98% your cursor just stops moving, also i cant open the replay on stable

![image](https://github.com/ppy/osu/assets/90941580/eb0fe9dd-5fcf-4c67-9d93-b5f71f6d88c1)

**Comment by THEKILLINGNAME** [comment] 2024-04-02 08:43
Is it possible that replays on different clients can show different plays?

**Comment by THEKILLINGNAME** [comment] 2024-04-02 08:45
> For me you don't even die in 98% your cursor just stops moving

When i was playing this map, i failed for 200%

**Comment by Rekunan** [comment] 2024-04-02 09:36
Well I have good reason to believe that part of the discrepancies is due to the seeking: In my further testing I also got a lower score than 368,793, but only if I was seeking ahead. Seems to be backed up by #26104

> For me you don't even die in 98% your cursor just stops moving, also i cant open the replay on stable

Same for me here, most likely the reason why we can't repro the early fail. I think the stable part is expected, since it's a lazer score.

Also considering the video, def something @ppy/team-client should look at.

**Comment by frenzibyte** [comment] 2024-04-14 22:30
@Rekunan The issue thread should be properly labeled before pinging the team.

**Comment by frenzibyte** [comment] 2024-04-14 23:40
If you seek to the point at which the score is failed, you will notice health does reach zero, but it doesn't trigger a failure. You will also notice the score rank after import is B, not F like in the video. That is the reason why a failure is not triggered, see [code](https://github.com/ppy/osu/blob/d34834af05ca94db36cbc64ff5fa60577881529b/osu.Game/Screens/Play/ReplayPlayer.cs#L40-L41). Tracking this in https://github.com/ppy/osu/issues/27865.

For the inaccuracy, maybe @tybug can give a better comment on what's causing it, but I'm tentatively closing it as it's likely tracked in other issue threads linked by https://github.com/ppy/osu/issues/27704#issuecomment-2017171362.

**Closed by frenzibyte** 2024-04-14 23:40 UTC
Labels: area:replay
