### ISSUE TITLE
Input issue

### ISSUE THREAD

**Issue by Dangan2020** [ppy/osu#8466] opened 2020-03-27 11:21 UTC
It's about an input issue that happens in lazer but it works all good on stable...
I use a computer that has TouchSmart system that allows you to use the computer screen as a touch screen, but the input when I'm using TouchSmart doesn't work properly on lazer. What's weird is that it works good on stable.

**Comment by bdach** [comment] 2020-03-27 18:04
Duplicate of ppy/osu-framework#1514.

**Closed by bdach** 2020-03-27 18:04 UTC
