### ISSUE TITLE
Wrong PP values shown when using DT that isn't 1.5x

### ISSUE THREAD

**Issue by WolfyGamingWorld** [ppy/osu#21125] opened 2022-11-04 13:35 UTC
### Type

Game behaviour

### Bug description

I have used 1.07x DT on a map, and I got 262pp out of 383pp max, but on the replay it shows 743pp as if I played with 1.5x DT. The issue is that the PP calculation on the replay thing always takes it as 1.5x and not other values, this applies to all maps I used different values of DT.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/54710356/199984758-4e397c15-fdca-4aa6-a393-0290c8bac826.png)

### Version

2022.1101.0-lazer

### Logs

Couldn't find logs for lazer

**Comment by Flamiii** [comment] 2022-11-05 22:30
Duplicate of https://github.com/ppy/osu/discussions/19222

**Comment by developomp** [comment] 2024-06-28 02:46
This issue can be closed now.

**Closed** 2024-06-28 02:48 UTC
Labels: area:scoring
