### ISSUE TITLE
Play not starting

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7322] opened 2019-12-22 02:37 UTC
**Describe the bug:** 
-
After choose a beatmap to play, game is not going to start
No freezing but wont start

**Screenshots or videos showing encountered issue:** 
-
![Unknow glich](https://user-images.githubusercontent.com/56265123/71316190-e007cc80-24a6-11ea-8a74-03547d50698a.png)

**osu!lazer version:** 
-
app-2019.1219.0

**Logs:** 
-
[logs.zip](https://github.com/ppy/osu/files/3992075/logs.zip)

**Comment by l3lackShark** [comment] 2019-12-22 05:28
Duplicate of #7311

**Closed** 2019-12-22 07:48 UTC
