### ISSUE TITLE
Most letters missing?

### ISSUE THREAD

**Issue by SoulYayz** [ppy/osu#4052] opened 2019-01-13 04:25 UTC
**Describe your problem:**So I just installed osu!lazer onto my PC, and most of the letters are missing from the font? Is that an issue with my PC or something else? 

**Screenshots or videos showing encountered issue:** https://imgur.com/a/HTiTNh5

**osu!lazer version:** 2019.111.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/2752799/network.log)
[performance.log](https://github.com/ppy/osu/files/2752800/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2752801/runtime.log)
[database.log](https://github.com/ppy/osu/files/2752802/database.log)

**Comment by GSculerlor** [comment] 2019-01-13 04:47
Duplicate #3277, I guess

**Comment by peppy** [comment] 2019-01-13 14:36
Yes, duplicate of #3277.

**Closed by peppy** 2019-01-13 14:36 UTC
