### ISSUE TITLE
The delay of the touch device.

### ISSUE THREAD

**Issue by Frederisk** [ppy/osu#5610] opened 2019-08-05 23:11 UTC
When I use stylus or finger to play osu, I can feel a serious delay. This is not the question of synchronization of video and audio, but the click of the touch device takes a long time to be responded.

I don't know why, this problem is more serious in full screen mode than in borderless mode. Fingers are more serious than styluses.

This problem also appears in the stable version. But in the stable version, I can use the compatibility mode to solve this problem. But the Lazer version does not have this option.
My device is a Surface Book 2 15 inch. The touch device is New Surface Pen or finger with touch screen.

osu 2019.730.0.0
And this is the [logs](https://github.com/ppy/osu/files/3469679/logs.zip).

**Comment by peppy** [comment] 2019-08-05 23:22
We have not yet implemented the APIs required to handle windows touch events.

**Comment by peppy** [comment] 2019-08-05 23:23
Duplicate of https://github.com/ppy/osu-framework/issues/1514.

**Closed by peppy** 2019-08-05 23:23 UTC
