### ISSUE TITLE
Possible to cause miss on autoplay when dragging song progress nub back and front

### ISSUE THREAD

**Issue by Trung0246** [ppy/osu#20915] opened 2022-10-25 05:29 UTC
### Type

Game behaviour

### Bug description

OD set to 11 while doing this.

As the song end abruptly (since I like to test how the song would play out with autoplay), I decided to drag the progress nub back and front, and the result is shown in the video.

### Screenshots or videos

https://user-images.githubusercontent.com/11626920/197689633-058c3917-b0ec-45a3-94b9-d451360ac5f3.mp4

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9857366/database.log)
[input.log](https://github.com/ppy/osu/files/9857367/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9857368/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9857369/network.log)
[performance.log](https://github.com/ppy/osu/files/9857370/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9857371/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9857372/updater.log)

**Comment by smoogipoo** [comment] 2022-10-26 04:50
Duplicate of https://github.com/ppy/osu/issues/13352

**Closed by smoogipoo** 2022-10-26 04:50 UTC
Labels: area:replay
