### ISSUE TITLE
osu!taiko UI bug on mobile

### ISSUE THREAD

**Issue by Matiyasu** [ppy/osu#11631] opened 2021-01-30 18:41 UTC
**Describe the bug:** 
Mobile Build of osu!lazer has an issue with osu!taiko UI
**Screenshots or videos showing encountered issue:** 

https://drive.google.com/file/d/1PDxbLVIJ2idK4aP_6fAn8FJTHgVShN1k/view?usp=drivesdk

**osu!lazer version:** 2021.129.0

**Comment by Matiyasu** [comment] 2021-01-30 18:42
If the link to the video isn’t working, let me know

**Comment by bdach** [comment] 2021-01-30 19:04
Video does not in fact work (says to "try again later").

**Comment by Matiyasu** [comment] 2021-01-30 20:26
> Video does not in fact work (says to "try again later").

I have now fixed it. Try it again

**Comment by frenzibyte** [comment] 2021-01-30 20:28
Nothing in the video explains what's going on from what the title / description says, I'm guessing you're talking about the katu (blue notes) not hittable on mobile? if so, then that goes under https://github.com/ppy/osu/issues/4201, and this can be closed as a duplicate.

**Comment by bdach** [comment] 2021-01-30 20:37
Tentatively closing as it's unclear what the issue is from the lack of a proper description and the unhelpful "WTF" in the video.

**Closed by bdach** 2021-01-30 20:37 UTC
Labels: missing details
