### ISSUE TITLE
replays inconsistent with normal osu! client

### ISSUE THREAD

**Issue by Pechu317** [ppy/osu#11812] opened 2021-02-17 16:06 UTC
**Describe the bug:** 

The current global top score on [this beatmap](https://osu.ppy.sh/beatmapsets/10435#osu/42019) has a 100% Accuracy FC, and that reflects on the normal osu! client. but when the replay is shown in osu!lazer, it shows that they missed one, when according to the leaderboards, they didn't.

**osu!lazer version:** 

2021.212.0

**Logs:**
<!--
*please attach logs here, which are located at:*

[network.log](https://github.com/ppy/osu/files/5996968/network.log)
[performance.log](https://github.com/ppy/osu/files/5996969/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5996970/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5996971/updater.log)
[database.log](https://github.com/ppy/osu/files/5996972/database.log)
can you guys see the files? i can't

**Comment by Pechu317** [comment] 2021-02-17 16:06
no clue why my logs aren't showing, sorry

**Comment by frenzibyte** [comment] 2021-02-17 16:07
Duplicate of https://github.com/ppy/osu/issues/5514, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed by frenzibyte** 2021-02-17 16:07 UTC
