### ISSUE TITLE
OperationCancelledException when exiting gameplay

### ISSUE THREAD

**Issue by TheWildTree** [ppy/osu#7759] opened 2020-02-07 20:24 UTC
**Describe the crash:** 
Sometimes when exiting from gameplay to the song select screen while debugging, the game will throw the following exception:

![image](https://user-images.githubusercontent.com/27722894/74062809-63499700-49ef-11ea-8274-c3f7b0356729.png)

Game works fine after resuming in the IDE and this is not visible in logs, but I think it's still not something that should be happening

**osu!lazer version:** 
latest master as of 07/02

**Comment by bdach** [comment] 2020-02-07 20:28
Is this an uncaught exception (i.e. does an error notification fire, and an entry is written to logs) or is it caught somewhere? There are a few places that catch `OperationCanceled`.

It might just be that the throw is the sanest way to cancel the operation by unwinding the stack, not sure.

**Comment by TheWildTree** [comment] 2020-02-07 20:34
What would be the easiest way to check that?

**Comment by bdach** [comment] 2020-02-07 20:35
Well, you should be able to just keep stepping out of the exception throw site until you hit a `catch`. VS also has an event log that shows where exceptions are caught and rethrown but I can see you're on Rider, not sure if it has an equivalent.

**Comment by peppy** [comment] 2020-02-08 00:06
What IDE are you using? Please turn off "break on user handled" mode.

**Comment by Joehuu** [comment] 2020-02-08 01:35
![image](https://user-images.githubusercontent.com/35318437/74076755-34232d80-49cf-11ea-8b5c-ee0dc9eaadda.png)

Based on what was said on discord and the image shown, probably VSCode. Unchecking this works.

**Comment by peppy** [comment] 2020-02-08 02:02
Actually this is quite well spotted and something we *can* avoid. Will PR a change to avoid exception usage.

**Comment by Joehuu** [comment] 2020-02-10 04:58
Closing as intended.

**Closed by Joehuu** 2020-02-10 04:58 UTC
