### ISSUE TITLE
Text is upside down when area is too small

### ISSUE THREAD

**Issue by loic2665** [ppy/osu#9583] opened 2020-07-16 15:47 UTC
**Describe the bug:** 

Issue : text is placed upside down when windows area is too small. (bottom to top)
Exception : the text must be top to bottom

**Screenshots or videos showing encountered issue:** 

https://streamable.com/txvurf

![osu bug](https://user-images.githubusercontent.com/22454094/87692720-56925180-c78c-11ea-908c-6143487e8228.png)

**osu!lazer version:** 

2020.714.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/4932562/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4932563/updater.log)
[database.log](https://github.com/ppy/osu/files/4932564/database.log)
[network.log](https://github.com/ppy/osu/files/4932565/network.log)
[performance.log](https://github.com/ppy/osu/files/4932566/performance.log)

Take care guys !

**Comment by Joehuu** [comment] 2020-07-16 15:50
Duplicate of https://github.com/ppy/osu/issues/8580

**Closed by Joehuu** 2020-07-16 15:50 UTC

**Comment by loic2665** [comment] 2020-07-16 17:35
Oops. Sorry. 

Have a nice day, I should have checked this before...
