### ISSUE TITLE
Very long osu!mania hold note sprites (aka "percy" skins) are not displayed

### ISSUE THREAD

**Issue by MasterZitron** [ppy/osu#12057] opened 2021-03-18 05:12 UTC
If for some weird reason the long note image is 25000 pixels in height(no fucking clue why it just is) it will not be visible in lazer, but weirdly enough it is on stable

skin: 
[-  mayu (orbs)low.zip](https://github.com/ppy/osu/files/6161433/-.mayu.orbs.low.zip)

screenshot: 
![image](https://user-images.githubusercontent.com/32692021/111576278-f3c7de80-878e-11eb-92fb-230f7d27427f.png)

version: 2021.312.0

**Comment by smoogipoo** [comment] 2021-03-18 06:10
We can't support this. GPUs have texture size limits, and this is just generally detrimental to the performance of the game...

I suggest fixing the skin. Labelling as low priority until we discuss this in the far future and/or probably just close the issue as intended.

**Comment by peppy** [comment] 2021-03-18 06:16
I think this is fine to close for now. We can revisit if there's actually a demand for this (ie. if it gets re-requested in the future).

**Comment by Fvern** [comment] 2021-03-18 06:31
just commenting the reason why skins sometimes have this long LN body is for higher customisation of the tail end. some effects (like a tapered end that ends directly at the head of the next LN) are impossible without it. so the new skinning engine, whenever that comes around, will be the fix for this.

**Comment by peppy** [comment] 2022-08-01 04:06
Going to reopen this as it keeps coming up (https://osu.ppy.sh/comments/2357343 / https://github.com/ppy/osu/issues/17645 as two examples).

We're going to have to support these somehow (probably by analysing the pixels and trimming the texture to make it work).

**Closed** 2023-01-25 22:41 UTC
Labels: priority:0, ruleset:osu!mania, area:skinning
