### ISSUE TITLE
Hitsounds aren't dimmed along with music in editor

### ISSUE THREAD

**Issue by XeZey** [ppy/osu#26286] opened 2023-12-31 11:24 UTC
### Type

Game behaviour

### Bug description

When clicking on "Test!" in an unsaved beatmap, the music dims. I assume the intention would be for the hitsounds to dim too, as this appears a bit weird.

### Screenshots or videos

https://github.com/ppy/osu/assets/83080509/69057807-36cc-4073-b58c-5f7a3a6f33bd

### Version

2023.1229.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13800937/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-01 00:17
duplicate of https://github.com/ppy/osu/issues/23043

**Closed by bdach** 2024-01-01 00:17 UTC
