### ISSUE TITLE
osu! lazer unplayable due to cursor issue (MacOS)

### ISSUE THREAD

**Issue by xdAlimant** [ppy/osu#9456] opened 2020-07-08 15:59 UTC
**Describe the bug:** 
I clicked on the Confine Mouse Cursor Setting and changed it to always. The cursor now doesn't appear on the osu! screen and I can't click anything. The cursor is forced to stay at the bottom right of my screen. I am unable to move it elsewhere as long as osu is open. I have tried reinstalling but issue remains. In the video attached, my bottom right corner is my hotkey for my screensaver hence the constant flashing to a clock. I'm playing on Mac OS Catalina.

**Screenshots or videos showing encountered issue:** 
[https://drive.google.com/file/d/1HRlPMxQoPHSEjmqN0zMZSacZ-pK_cDfj/view?usp=drivesdk/](https://drive.google.com/file/d/1HRlPMxQoPHSEjmqN0zMZSacZ-pK_cDfj/view?usp=drivesdk/) 

**osu!lazer version:** 
2020.707.0

**Logs:**

*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS)*

May get logs later if needed (its very late at the current time I'm making the post so)

**Comment by bdach** [comment] 2020-07-08 17:26
Duplicate of #8280

For now you can reset the setting in question by editing `~/.local/share/osu/framework.ini` and setting `ConfineMouseMode = Never`.

**Closed by bdach** 2020-07-08 17:26 UTC
