### ISSUE TITLE
Double time speed increase score multiplier may be abusable for playlist leaderboards

### ISSUE THREAD

**Issue by ilucaa** [ppy/osu#12678] opened 2021-05-04 15:01 UTC
**Describe the bug:** Playing the game with DT and score multiplier set to 1.01x (virtually normal speed as the original map offers) will let you keep the same score multiplier as it would with normal DT. 
This would let me get more advantage in playlist score leaderboards without having to actually play DT itself, and even further I could add HD and HR on top of it to get the best score multiplier possible.
**This might need further testing.** 

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/51536354/117024005-d097c500-ad23-11eb-8ac1-09fc71cd7474.png)
![image](https://user-images.githubusercontent.com/51536354/117023974-c970b700-ad23-11eb-8181-398cb1d0db4b.png)

**osu!lazer version:** 2021.502.2

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6421972/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6421974/updater.log)
[database.log](https://github.com/ppy/osu/files/6421975/database.log)
[performance.log](https://github.com/ppy/osu/files/6421977/performance.log)
[network.log](https://github.com/ppy/osu/files/6421986/network.log)

**Comment by bdach** [comment] 2021-05-04 15:02
Duplicate of #7698

**Closed by bdach** 2021-05-04 15:02 UTC
