### ISSUE TITLE
Result screen always shows global leaderboard even when local leaderboard is selected

### ISSUE THREAD

**Issue by jxu** [ppy/osu#18233] opened 2022-05-12 03:15 UTC
### Type

Game behaviour

### Bug description

Result screen (the one that shows up after completing a map) always shows global leaderboard, even when local leaderboard is selected in song select. 

### Version

2022.501

### Logs

NA

**Comment by peppy** [comment] 2022-05-12 03:30
Duplicate of https://github.com/ppy/osu/issues/9201.

**Closed by peppy** 2022-05-12 03:30 UTC
