### ISSUE TITLE
Performance drop when using Radeon Enchanced Sync

### ISSUE THREAD

**Issue by XLGamer10** [ppy/osu#23239] opened 2023-04-19 17:44 UTC
### Type

Performance

### Bug description

I have an rx 5700 (not flashed with an xt bios) and an r7 3700x
Both with Enchanced Sync on and off and with all frame limiter settings were the fps and delay reported the same.
However, there was an always noticeable stutter when playing. This stutter was always noticeable during gameplay, though the lag caused by it varied.
I tried turning off settings in my driver software and found that Enchanced Sync was causing this problem.
This does not happen with osu!stable and I haven't noticed this behavior in any other games, so I suspect this may be a compatibilty issue with lazer.
The setting is in the graphics section of the settings in the AMD Adrenalin drivers.

### Version

2023.419.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11276140/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11276141/updater.log)
[database.log](https://github.com/ppy/osu/files/11276142/database.log)
[input.log](https://github.com/ppy/osu/files/11276143/input.log)
[network.log](https://github.com/ppy/osu/files/11276144/network.log)
[performance.log](https://github.com/ppy/osu/files/11276145/performance.log)

**Comment by frenzibyte** [comment] 2023-04-21 09:00
Did this just occur on latest release? Or do you see the same issue happening on previous releases. Also if the game is working well with that setting being turned off then there's probably no need to have it turned on for it.

**Comment by james58899** [comment] 2023-04-21 12:11
AMD Enhanced Sync only supports DirectX, so it only happens with the latest version of osu lazer and osu stable with compatibility mode enabled.

I have also encountered lag caused by Enhanced Sync in other games before, so I think it is a problem with the AMD driver itself.

**Comment by frenzibyte** [comment] 2023-04-23 13:34
I'm going to close this for now given that it's caused by an option.

**Closed by frenzibyte** 2023-04-23 13:34 UTC
Labels: type:performance, platform:windows, renderer:d3d11
