### ISSUE TITLE
Can’t disable touch input on iOS 

### ISSUE THREAD

**Issue by FayneAldan** [ppy/osu#12191] opened 2021-03-26 00:05 UTC
Disabling the “mouse buttons” setting on iOS should disable touch input as there is currently no way to disable touch. This would be useful for using touch with a Bluetooth keyboard or keyboard case.

**Comment by Joehuu** [comment] 2021-03-26 00:27
Duplicate of https://github.com/ppy/osu/issues/12019

**Closed by Joehuu** 2021-03-26 00:27 UTC

**Comment by peppy** [comment] 2021-03-26 01:10
We intentionally didn't allow disabling touch. How do you intend to interact with just a keyboard?

If you're looking to disable presses from touch, please remove the key bindings for mouse.

**Comment by FayneAldan** [comment] 2021-03-26 02:05
> How do you intend to interact with just a keyboard?
No, I use my finger or an Apple Pencil / any stylus to aim and my keyboard to "click", similar to how any pro player would play on PC.

**Comment by FayneAldan** [comment] 2021-03-26 02:09
To clarify, I want to disable touching to "click", not touching entirely.

**Comment by peppy** [comment] 2021-03-26 02:11
Yes, which can be done by the methods mentioned.
