### ISSUE TITLE
Black screen and nothing loads

### ISSUE THREAD

**Issue by LinkzStudMufnz** [ppy/osu#6729] opened 2019-11-06 02:54 UTC
Lazer opens, installs (somewhat?) and reopens to launch the game. Gets past the 'this is a development build' splash screen, but does not show the rolling 'welcome' part of 'welcome to osu' and instead stays black. No crash log because it's not a crash?
Is there anything I can attempt to do to fix this? 
Lazer runs and plays on version 2019.227.0

Running on a laptop with-
7700HQ
GTX 1060
NOT running on integrated graphics.

**Comment by bdach** [comment] 2019-11-06 07:11
Even if this is not a hard crash, please attach logs from:
* `%AppData%/osu/logs` (on Windows),
* `~/.local/share/osu/logs` (on Linux and macOS).
It seems likely that this is going to be an audio device issue.

**Comment by peppy** [comment] 2019-11-06 07:17
We should probably have one issue open and tracking this if that's not already the case. It's a recurring report.

**Comment by LinkzStudMufnz** [comment] 2019-11-07 20:25
[database.log](https://github.com/ppy/osu/files/3821522/database.log)
[updater.log](https://github.com/ppy/osu/files/3821524/updater.log)
[runtime.log](https://github.com/ppy/osu/files/3821525/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3821526/performance.log)

**Comment by bdach** [comment] 2019-11-07 21:08
Lack of BASS initialization header seems to confirm this is an audio device problem. Closing as duplicate of #5866 / #1302.

Please check if you have an audio device enabled and adjust settings accordingly if not.

**Closed by bdach** 2019-11-07 21:08 UTC
Labels: missing details
