### ISSUE TITLE
Allow beatmap conversion based on interfaces, rather than only from osu! ruleset

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#11942] opened 2021-03-02 03:22 UTC
this idea allows for the bundled gamemodes taiko, ctb, and mania to be converted into a custom gamemode
the ruleset maker can decided which gamemodes they will allow to convert into the custom gamemode

this is because the different gamemodes are mapped differently(taiko is based on pitch, ctb is based on 2d movement, and mania is based on synthesizers/pianos) which can give the custom gamemodes a style that standard osu maps cannot create when converted to the custom gamemode

**Comment by peppy** [comment] 2021-03-02 04:00
At a code level, this is already mostly supported. I'm *sure* there's an existing issue covering this but cannot find it.

**Comment by bdach** [comment] 2021-03-02 16:45
Duplicate of #9263

**Closed by bdach** 2021-03-02 16:45 UTC
Labels: area:ruleset-api
