### ISSUE TITLE
Classic mod counts dropped slider ends in combo

### ISSUE THREAD

**Issue by facespkz** [ppy/osu#12605] opened 2021-04-27 21:13 UTC
**Describe the bug:** In classic mod, dropped slider ends are a part of combo, leading to an FC that wouldn't be possible on stable.

[reproduction.zip](https://github.com/ppy/osu/files/6387684/reproduction.zip)

**Screenshots or videos showing encountered issue:** 

### Lazer

https://user-images.githubusercontent.com/22137884/116310990-8c268b00-a75f-11eb-9fbc-05f23c27379f.mp4

### Stable

https://user-images.githubusercontent.com/22137884/116310972-88930400-a75f-11eb-9b22-483f280e45ad.mp4

**osu!lazer version:** Local Release (0.0.0.0)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6387617/database.log)
[network.log](https://github.com/ppy/osu/files/6387619/network.log)
[performance.log](https://github.com/ppy/osu/files/6387620/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6387621/runtime.log)

**Comment by frenzibyte** [comment] 2021-04-27 21:16
Duplicate of https://github.com/ppy/osu/issues/11769

**Closed by frenzibyte** 2021-04-27 21:16 UTC
