### ISSUE TITLE
Crash on opening "People" while osu!direct is also on

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#4994] opened 2019-06-11 12:48 UTC
**Describe the crash:** 
I was on osu!direct and then opened the "People" tab on the top taskbar. Osu suddenly froze after it pulled up the tab and went to a black screen when I pressed the Windows key. It gradually came back but you should probably fix.

**Screenshots or videos showing encountered issue:** 
![osu_2019-06-11_18-02-29](https://user-images.githubusercontent.com/32044067/59272191-1a302000-8c73-11e9-8440-ba031f4bf0fc.jpg)

**osu!lazer version:**
2019.611.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3276511/runtime.log)

**Computer Specifications:** Windows 10 Pro, 12 GB RAM, 64 Bit, Intel Core i5 Processor

**Comment by peppy** [comment] 2019-06-12 02:01
Sounds like blocking online requests. Could you also provide your `performance.log` after reproducing this again?

**Comment by peppy** [comment] 2020-02-12 04:43
Closing this one due to missing details of any kind. Probably already fixed with the decoupling of online loads from the main BDL queue.

**Closed by peppy** 2020-02-12 04:43 UTC
Labels: overlays, type:performance
