### ISSUE TITLE
Beatmap freezes when loading a song. (Android)

### ISSUE THREAD

**Issue by pxfff** [ppy/osu#8194] opened 2020-03-10 02:23 UTC
**Describe the bug:** 
When I load a song, the song and the map freezes but my game doesn't. Playing on Samsung Galaxy A70's latest version.

**Screenshots or videos showing encountered issue:** https://streamable.com/j3yxj

**osu!lazer version:** v2020.306.0

**Logs:**

**Comment by smoogipoo** [comment] 2020-03-10 04:31
The replication case is different, but I'm 99.99% sure this is the same issue as https://github.com/ppy/osu/issues/8093 and https://github.com/ppy/osu/issues/7886. I'll keep this open for now though.

**Comment by bdach** [comment] 2020-03-10 06:03
100% duplicate of #7344, I'd say; closing.

**Closed by bdach** 2020-03-10 06:03 UTC
Labels: area:gameplay
