### ISSUE TITLE
Multiple audio tracks while playing

### ISSUE THREAD

**Issue by B0und** [ppy/osu#11886] opened 2021-02-23 16:50 UTC
I\`m on Manjaro. Running lazer from an AppImage file. 
Osu lags a little bit after starting the map, and at some point its very obvious that there is >1 audio playing.
Map: https://osu.ppy.sh/beatmapsets/647615#osu/1372142

Its unranked, but there aren\`t any gimmicks or anything.
Single/multi thread mode doesnt change anything. Re-downloading map doesn\`t help.
Other maps seem to work fine, so idk if its even worth reporting.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=PEYSLV8g21g
**osu!lazer version:** 
2021.220.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6029760/database.log)
[network.log](https://github.com/ppy/osu/files/6029761/network.log)
[performance.log](https://github.com/ppy/osu/files/6029762/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6029763/runtime.log)

**Comment by MishterKirby** [comment] 2021-02-23 16:59
Does it happen with other maps? Or just this specific one?

**Comment by B0und** [comment] 2021-02-23 17:11
Only happens on this map

**Comment by frenzibyte** [comment] 2021-02-23 17:12
After listening to it, that isn't any other track playing simultaneously. It's the beatmap own hitsounds not synced with the track itself. 

Can you confirm you didn't play with the `Audio Offset` slider in the settings?

**Comment by B0und** [comment] 2021-02-23 17:15
I did have +25 offset when i recorded that, just tried changing it to 0, and it doesnt help

**Comment by MishterKirby** [comment] 2021-02-23 17:16
> 
> 
> After listening to it, that isn't any other track playing simultaneously. It's the beatmap own hitsounds not synced with the track itself.
> 
> Can you confirm you didn't play with the `Audio Offset` slider in the settings? that would affect the synchronization between track and hitsounds.

It could be this, or that the music track itself is out of sync.

**Comment by B0und** [comment] 2021-02-23 17:19
Disabling beatmap hitsounds does work!

**Comment by frenzibyte** [comment] 2021-02-23 17:38
Can you actually confirm default skin hitsounds are properly synced? best way is muting the music entirely and starting autoplay.

Because since this is Linux, can only say this is likely relevant to https://github.com/ppy/osu/issues/3800 (closest match https://github.com/ppy/osu/issues/10624).

**Comment by B0und** [comment] 2021-02-23 17:54
Sounds good to me.
https://www.youtube.com/watch?v=shhtLJxQ9VA

**Comment by frenzibyte** [comment] 2021-02-23 17:56
To be extra clear, have you also confirmed that the beatmap hitsounds are the ones out of sync from track and not the other way around?

**Comment by B0und** [comment] 2021-02-23 18:17
My issue was that this song sounded like a broken record, which turned out to be out of sync beatmap hitsounds, as it sounds ok when they are turned off. The track with only std skin hitsounds seems fine to me

**Comment by bdach** [comment] 2021-02-23 19:51
I'm going to go ahead and close this as a duplicate of #3800.

**Closed by bdach** 2021-02-23 19:51 UTC
Labels: missing details, platform:linux, type:audio
