### ISSUE TITLE
Impossible to navigate to other chat channels in F8

### ISSUE THREAD

**Issue by Ztumpie905509** [ppy/osu#13902] opened 2021-07-16 12:06 UTC
**Describe the bug:** 
When I scroll / drag the chat list it automatically rebounds upwards, making the chats in lower position of the list impossible to access
Dragging the icons are also useless on helping me navigate between chats

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/48085506/125944801-ec1e929b-dbba-46c2-8cab-5c5d17cacc91.mp4

**osu!lazer version:** 
2021.707.0-lazer

**Comment by smoogipoo** [comment] 2021-07-16 12:14
Duplicate of https://github.com/ppy/osu/issues/10541

**Closed by smoogipoo** 2021-07-16 12:14 UTC
