### ISSUE TITLE
When multiple notes are stacked in the editor the note on the top is always prioritised over any highlighted objects below it

### ISSUE THREAD

**Issue by DeviousPanda** [ppy/osu#12046] opened 2021-03-17 23:17 UTC
when there are two notes stacked on top of eachother, and you highlight the bottom note, if you then try to select that bottom note it will always auto select the note on top of the stack (this also goes for multiple notes highligted at the same time) 

i dont have recording software but i managed to clip some examples for a quick explanation (https://clips.twitch.tv/CorrectTawdryEggUnSane-9eFUO2KO-8hNVbHE)

**Comment by bdach** [comment] 2021-03-17 23:20
Related to (but seemingly not duplicate of) #11059.

**Comment by bdach** [comment] 2021-09-25 17:31
Looked into this one. Things seem to have improved somewhat since the original report since I cannot reproduce the issue in the exact scenario given, but I can do so with a slightly different setup (if all hitobjects have the same start time):

![2021-09-25-192826_461x593_scrot](https://user-images.githubusercontent.com/20418176/134780718-d0aceefc-2076-4211-a1d5-963de3eecf80.png)

Clicking at the position here will select the object with index 4.

This is another failure of `HitObjectOrderedSelectionContainer`'s [compare-based sorting logic](https://github.com/ppy/osu/blob/671fe772136671189cd404d6d9f723dc698050ad/osu.Game/Screens/Edit/Compose/Components/HitObjectOrderedSelectionContainer.cs#L67-L81) (the other one being #13473). I'm not immediately sure how to fix this without cramming more bindables into it. Frankly just considering having the container re-sort objects on every editor change (via `EditorChangeHandler.OnStateChange`) because otherwise things just get ridiculous.

**Closed** 2021-09-27 06:13 UTC
Labels: area:editor, type:UX, priority:1
