### ISSUE TITLE
Major Graphical Issues (Intel HD Graphics 3000)

### ISSUE THREAD

**Issue by Bixybob** [ppy/osu#5199] opened 2019-06-30 22:27 UTC
I got the same issue again with the UI but even worst. This always happens when I restart Osu! Lazer after going full screen. Could this be because of my graphics card? It could be because of the graphics card updates or my graphics card being very old.
This problem does not occur when I restart Osu Lazer! after going windowed or borderless mode. Other than the graphical issues, there are a lot of code problems and some other problems related to codes, too.
These problems happen every time I restart Osu!Lazer in fullscreen mode. For example, when I try to click alt + tab to exit out of the game without closing it. Nothing happens. Only my windows mouse appears. Indicating that the windows focus moved but I see nothing except Osu!Lazer the game and the windows mouse. I also tried to press the windows startup button but the windows startup menu does not appear. There were clues that it was open but I was not able to access it. Basically, even if I move the windows focus, nothing will happen except the windows cursor showing up. !taiko does not have colours, only the circles. The circles have colors when we hit them and will have them untill they exit out of the screen. The colors of ALL circles temporarily return when there is a spinner in !Taiko.
All of !Mania's notes are invisible. Almost everything is invisible or black. !Mania is unplayable.
The spinners in Osu!Standard have colors temporarily. After a second, the colours of the spinners disappear.
In !catch, there are some visuals missing like the combo color ones (dots appear for a certain combo colour on the plate and stack up until there is another combo color and then explode. This only happens when I do not not restart osu lazer when I am in fullscreen mode.)
There are a lot of more issues than I have mentioned here. These are just some of the major examples.
I do not think that this is because of the windows I use. I think (Yes, I think) I have all of the necessary components, software, hardware and programs for the game. Someone told me that I should use NVIDIA GeForce GT 525M graphics card which I already have. Well, I installed it virtually. The original graphics card that my computer still has is Intel(R) HD Graphics 3000. Also, when I enable bypass-front-to-back, I get the same results as this issue I previously created: #4492. Issues like the ones in these are also present when enabling bypass-front-to-back.
This is confusing.

![osu_2019-07-01_02-41-52](https://user-images.githubusercontent.com/48629581/60402576-22f97f00-9bab-11e9-8a41-14149c064c68.jpg)
![osu_2019-07-01_02-41-55](https://user-images.githubusercontent.com/48629581/60402578-27be3300-9bab-11e9-9f1b-2bcaab7e1faa.jpg)
![osu_2019-07-01_02-41-59](https://user-images.githubusercontent.com/48629581/60402579-2a208d00-9bab-11e9-84cd-6fda116972e3.jpg)
![osu_2019-07-01_02-42-03](https://user-images.githubusercontent.com/48629581/60402581-2d1b7d80-9bab-11e9-8b77-11cde79afe9f.jpg)
![osu_2019-07-01_02-42-55](https://user-images.githubusercontent.com/48629581/60402582-2ee54100-9bab-11e9-8f02-f35233624f7d.jpg)
![osu_2019-07-01_03-03-31](https://user-images.githubusercontent.com/48629581/60402730-ea5aa500-9bac-11e9-9318-f6f8744d4ecd.jpg)
![osu_2019-07-01_03-02-15](https://user-images.githubusercontent.com/48629581/60402733-ef1f5900-9bac-11e9-8481-a294417db84f.jpg)
![osu_2019-07-01_03-02-16](https://user-images.githubusercontent.com/48629581/60402734-f2b2e000-9bac-11e9-8b62-28eeb2e19c13.jpg)
![osu_2019-07-01_02-58-52](https://user-images.githubusercontent.com/48629581/60402738-f6defd80-9bac-11e9-878b-545449ccff67.jpg)
![osu_2019-07-01_02-55-36](https://user-images.githubusercontent.com/48629581/60402740-fcd4de80-9bac-11e9-8e70-9d16b87866da.jpg)
![osu_2019-07-01_03-03-07](https://user-images.githubusercontent.com/48629581/60402753-1ece6100-9bad-11e9-9850-b623306a4459.jpg)
![osu_2019-07-01_03-02-48](https://user-images.githubusercontent.com/48629581/60402757-24c44200-9bad-11e9-980e-52facadff24b.jpg)
![osu_2019-07-01_03-00-31](https://user-images.githubusercontent.com/48629581/60402758-2c83e680-9bad-11e9-9f35-418249815538.jpg)
![osu_2019-07-01_03-00-43](https://user-images.githubusercontent.com/48629581/60402760-30176d80-9bad-11e9-945e-8f3aa69ecfda.jpg)
![osu_2019-07-01_03-01-12](https://user-images.githubusercontent.com/48629581/60402761-3279c780-9bad-11e9-8b88-0b60727275be.jpg)
![osu_2019-07-01_02-58-52](https://user-images.githubusercontent.com/48629581/60402764-3a396c00-9bad-11e9-8f7b-f00e8e5d7b26.jpg)
![osu_2019-07-01_02-55-41](https://user-images.githubusercontent.com/48629581/60402767-40c7e380-9bad-11e9-884b-667cc7c4a74b.jpg)
![osu_2019-07-01_22-26-33](https://user-images.githubusercontent.com/48629581/60455541-07947f80-9c50-11e9-978f-63c3bf1ebe80.jpg)
![osu_2019-07-01_22-26-33](https://user-images.githubusercontent.com/48629581/60455542-08c5ac80-9c50-11e9-8ce5-e4bf8c9eefeb.jpg)
![osu_2019-07-01_22-18-48](https://user-images.githubusercontent.com/48629581/60455549-0ebb8d80-9c50-11e9-9645-7e124099373b.jpg)
![osu_2019-07-01_22-39-49](https://user-images.githubusercontent.com/48629581/60455989-67d7f100-9c51-11e9-9951-bd9b8fa24e7f.jpg)

osu!lazer version: 2019.702.0

Logs: 
[runtime.log](https://github.com/ppy/osu/files/3343382/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3343383/updater.log)
[database.log](https://github.com/ppy/osu/files/3343384/database.log)
[network.log](https://github.com/ppy/osu/files/3343385/network.log)
[performance.log](https://github.com/ppy/osu/files/3343386/performance.log)
[PC INFO.txt](https://github.com/ppy/osu/files/3343399/PC.INFO.txt)
[DISPLAY INFO.txt](https://github.com/ppy/osu/files/3346225/DISPLAY.INFO.txt)

### **_I might update this issue further in the future._**

**Comment by iiSaLMaN** [comment] 2019-06-30 22:32
```
2019-06-30 09:54:52: GL Version:                 3.1.0 - Build 9.17.10.4229
2019-06-30 09:54:52: GL Renderer:                Intel(R) HD Graphics 3000
2019-06-30 09:54:52: GL Shader Language version: 1.40 - Intel Build 9.17.10.4229
2019-06-30 09:54:52: GL Vendor:                  Intel
```
Duplicate of #4621, but i'll close mine as yours have nice details.
also, you can use your other graphics card (`NVIDIA GeForce GT 525M`), as the issue is related to HD 3000's GL.

**Comment by iiSaLMaN** [comment] 2019-06-30 22:36
Also, Close #4492.

**Comment by Bixybob** [comment] 2019-07-01 14:59
> ```
> 2019-06-30 09:54:52: GL Version:                 3.1.0 - Build 9.17.10.4229
> 2019-06-30 09:54:52: GL Renderer:                Intel(R) HD Graphics 3000
> 2019-06-30 09:54:52: GL Shader Language version: 1.40 - Intel Build 9.17.10.4229
> 2019-06-30 09:54:52: GL Vendor:                  Intel
> ```
> 
> Duplicate of #4621, but i'll close mine as yours have nice details.
> also, you can use your other graphics card (`NVIDIA GeForce GT 525M`), as the issue is related to HD 3000's GL.

I already have VIDIA GeForce GT 525M.

**Comment by iiSaLMaN** [comment] 2019-07-01 21:26
After a couple of experimenting with me and @swoolcock, we found that the issue with the black boxes is happening due to the texture shader `sh_Texture.fs` not loading somehow, so that's a framework bug (you can see this issue by simply failing the compilation of that shader), we are still looking for the other issues...

**Comment by swoolcock** [comment] 2019-07-01 22:48
Not 100% on that one but I do believe it’s shader related based on some initial googling.

**Comment by swoolcock** [comment] 2019-07-02 11:02
Seems to only happen when rendering the white pixel texture.  Also seems to not render at all if the alpha is less than 1.  Something to do with blending, or maybe mipmap filtering?

**Comment by iiSaLMaN** [comment] 2019-07-02 12:00
can you please add ` with Intel HD Graphics 3000` to the title

**Comment by iiSaLMaN** [comment] 2019-08-30 19:19
**UPDATE**: after the text builder and other changes: https://imgur.com/a/9dWtbW2

**Comment by smoogipoo** [comment] 2019-09-05 05:48
The textbuilder issue is a separate issue (#5885).

@Bixybob can you confirm whether this has been fixed? There's been a few changes recently that may have fixed this (white pixel size was increased).

**Comment by iiSaLMaN** [comment] 2019-09-05 10:19
@smoogipoo Confirming that it's not been fixed but got worser.

**Comment by smoogipoo** [comment] 2019-09-06 03:34
Have you tried enabling the "bypass front to back pass" option in the settings?

**Comment by kravque** [comment] 2019-09-06 10:47
Yes I ( and others ) Tried it, but it doesn't work even if others tried it.
Even from a few days i wanted to switch into windows 10 ( because i like it ).
it's still there and the solution didn't get fixed,
the weird thing is that i have a older pc but the problem is not there,
i'll give you the system information ( from older pc ):
Net Framework: latest version
OS: Windows 7 6.1 Ver ( unknown build )
Intel(R) G41 Express Chipset 64MB VRAM ( worse )
2GB DDR3 1140MHz
Hard drive from blue 500GB ( missed what the company was )
Intel Pentium Inside 3.00GHz ( better than the cpu i'm using it on my laptop )

and there is like nothing wrong and it's fine.

**Comment by kravque** [comment] 2019-09-06 11:09
This is from 2019.07.27 Update ( 1 month ago from 2018.08.30 Update )
On Intel(R) HD Graphics ( the one i'm currently using it. )

![osu_2019-07-27_10-40-31](https://user-images.githubusercontent.com/46227763/64423117-64784000-d0ae-11e9-9931-f8f33d8714b5.jpg)

And This is An Updated photos, but this is better. https://imgur.com/a/BVGgNxK

**Comment by smoogipoo** [comment] 2019-09-06 11:20
Is the 20190727 the last build that works? Is there a build after it which works, and if so can you find the last one?

**Comment by kravque** [comment] 2019-09-06 11:22
the last update that it worked fine ?
yes, 2019.823.0,
and this update 2019.828.0 made the problem happen.

**Comment by iiSaLMaN** [comment] 2019-09-06 12:47
@kravque you need to confirm which mode is this, the graphics bug issue for me happens on full screen mode only

**Comment by kravque** [comment] 2019-09-06 12:53
Full screen.

**Comment by enoslayd** [comment] 2019-09-07 06:18
Happens to me too (my laptop sports an old intel hd graphics (2009 era?)).

**Comment by minhducsun2002** [comment] 2019-09-07 16:15
Running this on a i3-2330M laptop with HD Graphics 3000 running Arch Linux. No problem so far. (Except from performance, but not to the extent of unplayability : this GPU is years old after all)

**Comment by iiSaLMaN** [comment] 2019-09-07 16:17
> Running this on a i3-2330M laptop with HD Graphics 3000 running Arch Linux. No problem so far. (Except from performance, but not to the extent of unplayability : this GPU is years old after all)

Yeah, the issue seems to be windows only, probably the drivers not having correct support

**Comment by MeguMario** [comment] 2019-09-07 16:57
The only fix that works for me is to launch the game in Window/Borderless Mode, than switch back to Fullscreen

Also you might want to update your GPU driver, with Intel HD 3000, you might want to install Intel provided driver than update it using Windows Update, since as far as I know, the one microsoft provide you is missing a lot of feature

**Comment by kravque** [comment] 2019-09-14 09:14
I Just Found Another issue, When i enable Screen Scaling it makes everything worse.

![osu_2019-09-14_12-10-48](https://user-images.githubusercontent.com/46227763/64905995-e852ad80-d6e8-11e9-8389-b90a1ac719ef.jpg)
![osu_2019-09-14_12-10-56](https://user-images.githubusercontent.com/46227763/64905996-e852ad80-d6e8-11e9-831a-7caeff73e23e.jpg)

**Comment by kravque** [comment] 2019-09-14 11:45
looks like the black thing goes off after clicking the circle by 0.4s
![osu_2019-09-14_14-42-11](https://user-images.githubusercontent.com/46227763/64907658-260e0100-d6fe-11e9-845d-d4b71525f503.jpg)
![osu_2019-09-14_14-42-59](https://user-images.githubusercontent.com/46227763/64907659-260e0100-d6fe-11e9-8bd0-70ffd8d38aa2.jpg)

**Comment by kravque** [comment] 2019-09-14 11:57
And Also, when i tried to use the osu!classic skin on osu!lazer there wasn't black thing on the circle but it was around the circle.
![osu_2019-09-14_14-53-14](https://user-images.githubusercontent.com/46227763/64907763-7f2a6480-d6ff-11e9-99ab-fa95910d5c62.jpg)

**Comment by iiSaLMaN** [comment] 2019-09-14 12:22
That's because osu!lazer skin has drawable elements, not textures like other skins. the "black thing" here is because the texture white pixel having black color due to some shader problems https://github.com/ppy/osu/issues/5199#issuecomment-507452670

**Comment by MeguMario** [comment] 2019-09-16 18:12
Mine was only happened when I updated to tag 2019.906.0, before that lazer would works fine

**Comment by iiSaLMaN** [comment] 2019-09-16 18:34
> Mine was only happened when I updated to tag 2019.906.0, before that lazer would work fine
> (the comment i made on this issue 9 days ago)
> 
> It's seems like it is effected mostly on transparent objects, as storyboard is also ruined with big black box
> ![image](https://user-images.githubusercontent.com/44724359/64916480-07fcdb00-d7a8-11e9-9b26-ab80de10c17c.png)

Can you confirm that running older version doesn't reproduce this issue? (2019.620.1 has the issue as can be seen in the OP screenshots)

Could you please inform us of your GPU?

**Comment by MeguMario** [comment] 2019-09-17 00:50
> > Mine was only happened when I updated to tag 2019.906.0, before that lazer would work fine
> > (the comment i made on this issue 9 days ago)
> > It's seems like it is effected mostly on transparent objects, as storyboard is also ruined with big black box
> > ![image](https://user-images.githubusercontent.com/44724359/64916480-07fcdb00-d7a8-11e9-9b26-ab80de10c17c.png)
> 
> Can you confirm that running older version doesn't reproduce this issue? (2019.620.1 has the issue as can be seen in the OP screenshots)
> 
> Could you please inform us of your GPU?

So, this is what I got (starting from 2019.814.0 (btw my gpu is the same as the op, Intel HD Graphics 3000)

**2019.814.0 (use workaround by starting the game from window mode, otherwise the bug will appear)**
![image](https://user-images.githubusercontent.com/44724359/65002671-2f29e880-d91f-11e9-946c-ec8ce81b2af4.png)
![image](https://user-images.githubusercontent.com/44724359/65002778-934cac80-d91f-11e9-8cbc-cabfaaa7fb89.png)
and btw this is what happen when start the game from fullscreen mode
![image](https://user-images.githubusercontent.com/44724359/65002823-c2fbb480-d91f-11e9-8fac-e416f8bd71c5.png)

**Comment by MeguMario** [comment] 2019-09-17 01:16
> Mine was only happened when I updated to tag 2019.906.0, before that lazer would work fine
> (the comment i made on this issue 9 days ago)
> 
> It's seems like it is effected mostly on transparent objects, as storyboard is also ruined with big black box
> ![image](https://user-images.githubusercontent.com/44724359/64916480-07fcdb00-d7a8-11e9-9b26-ab80de10c17c.png)

for some reason windows won't let me screenshot this properly so sorry


**2019.814.0**
![image](https://user-images.githubusercontent.com/44724359/65002968-7cf32080-d920-11e9-9eb6-14069583086a.png)
![image](https://user-images.githubusercontent.com/44724359/65003604-6a2e1b00-d923-11e9-8846-199dc5860c44.png)

**Comment by iiSaLMaN** [comment] 2019-09-20 00:13
After bisecting between the two tags, I've realized the issue was indeed fixed by ppy/osu-framework#2782. this issue can be closed as the rest is tracked in #5885

**Comment by smoogipoo** [comment] 2019-09-20 04:35
Wait what? The poster above said the builds _after_ 2019.823.0 are broken?

**Comment by kravque** [comment] 2019-09-20 05:49
> the last update that it worked fine ?
> yes, 2019.814.0,
> and this update 2019.823.0 made the problem happen.
> EDIT: i meant ( 2019.814.0 ), NOT ( 2019.823.0 )

I Said That Before.

**Comment by smoogipoo** [comment] 2019-09-20 08:53
Going to close this as the OP's issue was fixed (black backgrounded boxes) in https://github.com/ppy/osu-framework/pull/2782 .

**Closed by smoogipoo** 2019-09-20 08:53 UTC
Labels: framework fix required, graphics
