### ISSUE TITLE
Hit animations sometimes do not appear in the editor

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#12266] opened 2021-04-02 10:53 UTC
Sometimes the hit animations do not appear on hit object in the editor. Specifically this happens when the map starts playing on the exact start time of the hit object after rewinding back in time. It can also happen when pausing and unpausing the song really fast.

Video showing the issue: https://drive.google.com/file/d/1WJ8Z4GXpew-7bwZsFQrnbrG73L6lZexX/view?usp=drivesdk

**osu!lazer version:** 2021.331.0

**Comment by bdach** [comment] 2021-04-02 11:09
Duplicate of #10909

**Closed by bdach** 2021-04-02 11:09 UTC
