### ISSUE TITLE
Replay keeps loading and never starts

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14409] opened 2021-08-20 14:26 UTC
Replay keeps loading and never starts. This is the only replay I've found this issue with so far
Couldn't find a way to export the replay in lazer but it's the number one EZ play on [this map](https://osu.ppy.sh/beatmapsets/1069145#osu/2238164)

**video:** https://www.youtube.com/watch?v=5xZgWj8E4TI
**osu!lazer version:** 2021.815.0-lazer

**Logs:**
[performance.log](https://github.com/ppy/osu/files/7022146/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7022147/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7022149/updater.log)
[database.log](https://github.com/ppy/osu/files/7022150/database.log)
[network.log](https://github.com/ppy/osu/files/7022151/network.log)

**Comment by bdach** [comment] 2021-08-21 16:22
I've downloaded the replay from web but it starts fine here, so I'm not sure what's going on there exactly...

**Comment by frenzibyte** [comment] 2021-08-21 17:59
As I suspected, this is not relevant to the replay score, but rather, it is relevant to the beatmap's own storyboard, which is causing this indefinite-looking load time that doesn't occur when storyboard is disabled in settings.

Attaching a debugger shows that the storyboard has command loops with over 800,000 iterations:
![CleanShot 2021-08-21 at 20 45 12](https://user-images.githubusercontent.com/22781491/130330670-ec069f05-51e1-4f85-ac00-9fcae213053f.png) 

which gets called on each transformable component inside each of the 60 sprites which specify such massive loop.
![CleanShot 2021-08-21 at 20 53 31](https://user-images.githubusercontent.com/22781491/130330882-619de83a-5fba-4f2a-8b57-be1ea222acb2.png)

Safe to close this as a duplicate of https://github.com/ppy/osu/issues/12401.

**Closed by frenzibyte** 2021-08-21 17:59 UTC
Labels: missing details, area:replay
