### ISSUE TITLE
Copy and paste shortcuts are bound to physical keys

### ISSUE THREAD

**Issue by Curstantine** [ppy/osu#24786] opened 2023-09-11 17:28 UTC
### Type

Other

### Bug description

It's pretty unnatural for osu to handle it like this. Both windows and linux binds the layout key instead of the physical location of the key for these shortcuts.

Dvorak layout:
Ctrl + J -> Copy
Ctrl + K -> Paste

### Version

2023-815.0

### Logs

[out of scope, mention me if it really needs a log]

**Comment by peppy** [comment] 2023-09-11 17:31
Duplicate of https://github.com/ppy/osu/issues/11143 / https://github.com/ppy/osu-framework/pull/5790

**Closed by peppy** 2023-09-11 17:31 UTC
