### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by kirillitsa** [ppy/osu#10920] opened 2020-11-20 06:57 UTC
**Describe the bug:** 
I can't log in, but I'm sure that I'm entering the login and the password is correct
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/74759393/99768310-217d7d80-2b37-11eb-9a04-c9fc71323526.png)

**osu!lazer version:** 
2020.1114.0
**Logs:**

[database.log](https://github.com/ppy/osu/files/5571819/database.log)
[network.log](https://github.com/ppy/osu/files/5571820/network.log)
[performance.log](https://github.com/ppy/osu/files/5571821/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5571822/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5571823/updater.log)

**Comment by smoogipoo** [comment] 2020-11-20 06:58
```
**Logs:**
<!--
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
-->
```
Please read the issue template.

**Comment by peppy** [comment] 2020-11-20 08:35
This may be related to IPv6 support. Are you able to try disabling your IPv6 tcp protocol under network adapter settings and see if it helps at all?

**Comment by kirillitsa** [comment] 2020-11-20 09:02
peppy, I already disabled the IPv6 and this worked! Thank You very much!

**Comment by peppy** [comment] 2020-11-20 09:21
Thanks for the confirmation. This is a duplicate of https://github.com/ppy/osu/issues/3507. Will bump that one in priority.

**Closed by peppy** 2020-11-20 09:22 UTC
Labels: type:online
