### ISSUE TITLE
Watching a replay in Daily Challenge sets that replay's mods for the player

### ISSUE THREAD

**Issue by kstefanowicz** [ppy/osu#29171] opened 2024-07-28 13:26 UTC
### Type

Game behaviour

### Bug description

After watching a replay from the Daily Challenge screen, that replay's mods will be applied to the player without showing in the "Free Mod" screen as applied. After toggling any mod, they revert back to the Daily Challenge's default mods.

### Screenshots or videos

[daily-challenge-replay-mods.webm](https://github.com/user-attachments/assets/faff1ad3-6ef4-47c2-ba3d-3bdf4573bc98)

### Version

202.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16403876/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-28 14:31
Duplicate of https://github.com/ppy/osu/issues/29133

**Closed by frenzibyte** 2024-07-28 14:31 UTC
