### ISSUE TITLE
Pressing enter and backslash key at the same time with text on searchbar cause the osu! to trigger a bug

### ISSUE THREAD

**Issue by ShizuVoice** [ppy/osu#21120] opened 2022-11-04 09:41 UTC
### Type

Other

### Bug description

When I type a keyword when searching a beatmap and then pressing enter to that beatmap but also accidentally pressing backslash it triggers an exception according to the logs in osu!lazer. This can be reproduced easily like how I do in the attached video. Note that the way I triggered the bug is not the same as how I discovered the bug, this is just to ease up on replicating the bug.

### Screenshots or videos

https://youtu.be/3lWU32vXcCw

### Version

2022.1101.0-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/9936824/input.log)
[network.log](https://github.com/ppy/osu/files/9936825/network.log)
[performance.log](https://github.com/ppy/osu/files/9936828/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9936829/runtime.log)

**Comment by Gabixel** [comment] 2022-11-05 17:54
Unless I'm missing something, it looks like a duplicate of https://github.com/ppy/osu/issues/19803

**Comment by ShizuVoice** [comment] 2022-11-06 07:42
> Unless I'm missing something, it looks like a duplicate of #19803

I seems like it is. But one thing I never did try is to do the same thing you did (no word search but also adding backslash) and I've been able to reproduce it.

**Comment by peppy** [comment] 2022-11-06 09:32
Let's keep this one open since the sentry issue is linked here.

**Comment by saumon-brule** [comment] 2024-09-16 22:56
I don't know if this can help but I found the glitch and then played a little bit with it and it made my game crash, is it a normal behavior when the game reports too much errors or is it the bug ?

**Closed** 2024-09-18 09:45 UTC
Labels: area:song-select, type:reliability
