### ISSUE TITLE
11k Songs and opening song list freeze the game

### ISSUE THREAD

**Issue by realrEDGUY** [ppy/osu#12241] opened 2021-03-31 11:09 UTC
**Describe the bug:** 
Having around 11k songs and opening "Now playing" makes the whole game freeze

**Screenshots or videos showing the encountered issue:** 
https://xn--pcktb1c2c9f.140er.club/wYgjcMOJGz.mp4 (It only takes a long time to load them but in fullscreen you are unable to continue and you have to restart the game, unable to record while fullscreen)

**osu!lazer version:** 
2021.331.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6236082/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6236083/updater.log)
[performance.log](https://github.com/ppy/osu/files/6236084/performance.log)

**Comment by peppy** [comment] 2021-03-31 11:10
Duplicate of https://github.com/ppy/osu/issues/7767

**Closed by peppy** 2021-03-31 11:10 UTC
