### ISSUE TITLE
Hp drain on mania

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#7396] opened 2019-12-30 01:41 UTC
Since the implementation of hp drain, mania has been affected as well which shouldn't have been like in stable

*sorry no screenshot or video. Just try playing a mania map

**osu!lazer version:2019.1227.0

*no logs(for now)

**Comment by peppy** [comment] 2019-12-30 01:42
Duplicate of https://github.com/ppy/osu/issues/7370.

**Closed by peppy** 2019-12-30 01:42 UTC
