### ISSUE TITLE
The Replay speed bugs in Mods: Wind up (or Wind down)

### ISSUE THREAD

**Issue by soloopooo** [ppy/osu#12096] opened 2021-03-20 09:56 UTC
**Describe the bug:** 

I played a beatmap using Wind up mods with customized speed (from 0.5 to 2.0), but when i open and watch the replay file, it shows that wind up speed is from 1.0 to 1.5 (Default value). And the in-game replay speed is also not right but the replay score is normal.

**And one more thing, the Wind up's description is right when the game just ends. If you click "watch replay" or go back to choose songs, the speed would become default value again.**

**Screenshots or videos showing encountered issue:** 

![This is the mod's customization page.](https://user-images.githubusercontent.com/36123081/111865852-63fb7d80-89a4-11eb-82f8-801dee9446bc.png)

![image](https://user-images.githubusercontent.com/36123081/111865872-8ab9b400-89a4-11eb-919c-f52c61713f46.png)

Just take a look at the replay's description.

The following is a new replay with 0.95x - 1.14x. 

![image](https://user-images.githubusercontent.com/36123081/111866047-85109e00-89a5-11eb-9c57-31c3a951979d.png)

![image](https://user-images.githubusercontent.com/36123081/111866049-8c37ac00-89a5-11eb-8f76-04921396f24a.png)

**osu!lazer version: 2021.320.0**

**Comment by bdach** [comment] 2021-03-20 09:58
Duplicate of #8569

**Closed by bdach** 2021-03-20 09:58 UTC
