### ISSUE TITLE
osu!lazer multiplayer room chatbox overlap (or something is wrong with time)

### ISSUE THREAD

**Issue by Hazuki-san** [ppy/osu#5314] opened 2019-07-10 00:35 UTC
**Describe the bug:** Time and Name are overlap

**Screenshots or videos showing encountered issue:** https://i.imgur.com/U7Rptbor.png

**osu!lazer version:** 2019.704.0 (Android)

**Logs:** None (I don't know where to get it)

**Comment by Joehuu** [comment] 2019-07-10 01:14
Duplicate of #2819.

**Closed** 2019-07-10 01:14 UTC
