### ISSUE TITLE
Combo Burst

### ISSUE THREAD

**Issue by gamerturtlepoggers** [ppy/osu#12658] opened 2021-05-02 11:26 UTC
**Describe the new feature:** 
A celebration of achieving a combo milestone.
**Proposal designs of the feature:** 
In regular osu there is combo burst, and I think it would be nice if osu lazer would also have combo burst as it shows a milestone and it's nice

**Comment by LittleEndu** [comment] 2021-05-02 11:28
Duplicate of #4629

**Closed** 2021-05-02 11:50 UTC
