### ISSUE TITLE
confine cursor should be set to fullscreen by default

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#10648] opened 2020-11-01 15:47 UTC
**Describe the bug:** 

A lot of people lately have been reporting that their cursor can move out of the screen, i think this behavior changed after one update when #9883 was merged, looks like confine cursor was set to "during gameplay" by default, and i've seen people asking about it as you can see in the screenshots below

I tried installing 2020.1009.0 but nothing seemed to change so i am not 100% sure about this problem now, i think this is because i changed the setting to fullscreen when this issue happened to me so now it does not affect me anymore

**Screenshots or videos showing encountered issue:** 

![3](https://user-images.githubusercontent.com/41755816/97806974-01942180-1c3d-11eb-88c1-7f378103fc58.png)

![2](https://user-images.githubusercontent.com/41755816/97806896-b5e17800-1c3c-11eb-8236-6b5a21823f50.png)

**osu!lazer version:** 

2020.1031.0 but i think this happen since 2020.1009.0

**Comment by peppy** [comment] 2020-11-01 15:54
Going off screen is a bug and will be fixed. This is also a duplicate of https://github.com/ppy/osu/issues/10465 which is *pinned*. Please search before posting.

**Closed by peppy** 2020-11-01 15:54 UTC
