### ISSUE TITLE
Osu!lazer keeps crashing without any warning

### ISSUE THREAD

**Issue by Monmon25** [ppy/osu#25519] opened 2023-11-20 20:53 UTC
### Type

Crash to desktop

### Bug description

I'm just opening lazer and it runs smoothly for about 30 seconds, then it stops and crashes to desktop. Here are my logs 

### Version

2023.1114.1-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/13419276/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13419277/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13419278/updater.log)
[database.log](https://github.com/ppy/osu/files/13419280/database.log)
[input.log](https://github.com/ppy/osu/files/13419281/input.log)
[network.log](https://github.com/ppy/osu/files/13419282/network.log)

**Comment by peppy** [comment] 2023-11-21 00:18
There's no sign of a crash in the logs attached, which means there's a high likelihood that the crash is happening in your GPU drivers or elsewhere. Are you able to check windows event viewer for any errors?

**Comment by The-Grace-God** [comment] 2023-11-30 22:48
if you can try looking at task manager and osu at the same time to try and figure out why it keeps crashing by checking which resource is getting used up

**Comment by The-Grace-God** [comment] 2023-11-30 22:50
kinda like this or if your on a single display split the screen between osu and task manager
![image](https://github.com/ppy/osu/assets/66783188/e894fe1c-c3fa-44d8-b6f0-9ab8e36782bb)

**Comment by spookosu** [comment] 2023-12-22 12:58
Thought i'd add onto here as I was having this same issue and found this - I found at least on my side that it was game bar related and would consistently throw back the a 'The server Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter did not register with DCOM within the required timeout.' error in event viewer.
Terminating the game bar process worked for me so would recommend checking for the same

**Comment by tybug** [comment] 2024-04-03 08:24
Thanks for the report! As we can't reproduce without more information, I'm going to close this issue for now. If you can provide more information or a reliable reproduction, we'll look at reopening this issue.

**Closed by tybug** 2024-04-03 08:24 UTC
Labels: missing details, type:reliability
