### ISSUE TITLE
Hit circles that are in the center of spinners are invisible

### ISSUE THREAD

**Issue by TheUnkn0wnN00b** [ppy/osu#5450] opened 2019-07-24 23:07 UTC
**Describe the bug:** 
When the hidden mod is on and there's a hit circle at the center of a spinner, it is invisible, but you can still see the approach circle. However, this makes the hit circle completely invisible in Hidden, as there is no approach circle.

**Screenshots or videos showing encountered issue:** 
![You can't see the hit circle, only the approach circle](https://user-images.githubusercontent.com/21059358/61833996-cbfa6900-ae3b-11e9-8104-82a799d1dbf0.png)
![With Hidden, the hit circle is completely invisible](https://user-images.githubusercontent.com/21059358/61834281-e5e87b80-ae3c-11e9-8c4a-0e68f68f4977.png)

**osu!lazer version:** 
Lazer 2019.719.0

**Comment by Joehuu** [comment] 2019-07-24 23:10
Duplicate of #2823.

**Comment by nyquillerium** [comment] 2019-07-25 02:15
Closing as duplicate, but it would be nice if the images from the original issue could be updated, since they seem to be missing.

**Closed by nyquillerium** 2019-07-25 02:15 UTC
