### ISSUE TITLE
Supposed S turned back to A for no reason

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#27110] opened 2024-02-10 03:21 UTC
### Type

Game behaviour

### Bug description

I finished a map, got to the results, got an "S", which somehow went back to "A" for no reason.

### Screenshots or videos

Video: [Ohne Titel.webm](https://github.com/ppy/osu/assets/48768314/b16e1741-f5de-4898-8671-3ebb037e4555)
Play: 
[JankoGoo playing AAAA Chazuke - Hop Step Adventure_ (TKS) [Muzukashii] (2024-02-10_00-22).zip](https://github.com/ppy/osu/files/14227758/JankoGoo.playing.AAAA.Chazuke.-.Hop.Step.Adventure_.TKS.Muzukashii.2024-02-10_00-22.zip) (Had to be Zipped)
Map: https://osu.ppy.sh/beatmapsets/466471#taiko/1003357

### Version

2024.209.0

### Logs

Not available anymore, since it's WAY too late.

**Comment by ssz7-ch2** [comment] 2024-02-10 03:31
S rank requires no misses for taiko and standard
https://github.com/ppy/osu/pull/26630

**Comment by GamingWithJanko** [comment] 2024-02-10 03:37
> S rank requires no misses for taiko and standard

So it doesn't need just the percentage anymore, got it.
And yet, this confuses the hell outta me.

**Comment by bdach** [comment] 2024-02-10 05:40
The animation is supposed to convey it. I don't know what else could be done to do that.

Anyway closing as intended.

**Closed** 2024-02-10 05:40 UTC
