### ISSUE TITLE
Freshly Downloaded Map does not want to Update 

### ISSUE THREAD

**Issue by PolskiKapsel** [ppy/osu#25119] opened 2023-10-14 07:37 UTC
### Type

Other

### Bug description

The bug itself is really weird. So I downloaded a beatmap, played it once and noticed an Update Button. It already has been a couple of years since it was ranked but okay - I thought clicking Update button. But the update button is still there. So I clicked it again, and again and so on. It's just there. I'm not sure If this bug already happened to someone or is it just one time thing happening just on my osu client. I'm far from being a developer, so I decided to report bug this just in case. 
Map: https://osu.ppy.sh/beatmapsets/370819

### Screenshots or videos

https://www.youtube.com/watch?v=M9icbIGH1Is

### Version

osu! 2023.1008.1-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/12903438/logs.zip)

**Comment by Joehuu** [comment] 2023-10-14 07:40
Duplicate of https://github.com/ppy/osu/issues/22148

**Closed by Joehuu** 2023-10-14 07:40 UTC
