### ISSUE TITLE
Yesterday i opened issue, but peppy closed it bcs i suck. Now i need help with this problem.

### ISSUE THREAD

**Issue by MikelvGP** [ppy/osu#10744] opened 2020-11-09 09:26 UTC
**Describe the crash:** 
I opened an issue where I told that problems with osu!lazer, but because of a crooked video, I couldn't show that optimization sucks(no offense) on my computer. Now I have prepared myself and shown that I REALLY have such a problem.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/YUCH0xCAL-k
**osu!lazer version:** 
2020.1031.0
**Logs:**

[performance.log](https://github.com/ppy/osu/files/5509409/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5509410/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5509411/updater.log)
[database.log](https://github.com/ppy/osu/files/5509412/database.log)
[network.log](https://github.com/ppy/osu/files/5509413/network.log)

**Computer Specifications:** 
CPU:Amd ryzen 3 1200
GPU:Amd radeon 550
Ram:8GB DDR4 2633Ghz
3 Hard Drive.

**Comment by smoogipoo** [comment] 2020-11-09 09:40
We don't usually leave performance issues open so I'll be closing this, but...

It would be much more helpful if you showed the frametime graphs (press Ctrl+F11 again). Also post a dxdiag report https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe, and make sure you have the latest drivers for your system.

**Closed by smoogipoo** 2020-11-09 09:40 UTC

**Comment by MikelvGP** [comment] 2020-11-09 09:56
> It would be much more helpful if you showed the frametime graphs (press Ctrl+F11 again). 


Combinatoin Ctrl+F11 in game not worked(I really tried).
But i can give you dxdiag report.
[DxDiag.txt](https://github.com/ppy/osu/files/5509551/DxDiag.txt)

**Comment by smoogipoo** [comment] 2020-11-09 10:31
dxdiag looks normal. only thing I can suggest otherwise is to make sure there's not background application interfering with lazer, such as discord, webbrowsers, f.lux, etc.

beyond that you'll have to wait for performance improvements to lazer.

**Comment by MikelvGP** [comment] 2020-11-09 10:35
>  only thing I can suggest otherwise is to make sure there's not background application interfering with lazer, such as discord, webbrowsers, f.lux, etc.
At the beginning of the video I showed that I turn off all background programs

> beyond that you'll have to wait for performance improvements to lazer.
I'm counting on this, because the problem is clearly in the game, and I'm ready to wait for optimization, just to get it resolved before the official release, because I don't want to leave osu

**Comment by peppy** [comment] 2020-11-09 10:38
As a developer we cannot say "the problem is clearly your PC". As a user please do not try and assert the same. It's not that cut and dry.

We are not ready to handle single user performance issues as we are still developing and optimising the game. You should likely wait until we support this as the primary osu! client at which point you can post for help in a the tech support forum (or hopefully your issue will already be solved due to driver/hardware/code changes).
