### ISSUE TITLE
Mention notification keeps popping up despite reading it in Daily Challenge chat

### ISSUE THREAD

**Issue by Shavixinio** [ppy/osu#30463] opened 2024-10-31 14:05 UTC
### Type

Game behaviour

### Bug description

When opening the daily challenge menu, if you were tagged in the daily challenge chat, you keep getting a notification that you got mentioned despite already reading the chat message previously.

### Screenshots or videos

https://github.com/user-attachments/assets/9ebe59e8-b8df-4a12-ae2e-9cadaaa005f0

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17588670/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-10-31 17:32
Duplicate of https://github.com/ppy/osu/issues/24715

**Closed by Joehuu** 2024-10-31 17:32 UTC
