### ISSUE TITLE
Resizing causes texture corruption or crash

### ISSUE THREAD

**Issue by czapek1337** [ppy/osu#5018] opened 2019-06-13 18:01 UTC
**Describe the bug:** When resizing the game window the whole graphics seems to get messed up.

**Screenshots or videos showing encountered issue:** https://streamable.com/dtbbd https://imgur.com/a/3wdJpNK

**osu!lazer version:** 2019.608.0

**Logs:** don't really know where they are located, if you can tell me where they are I can attach them afterwards!

**Comment by iiSaLMaN** [comment] 2019-06-13 18:02
I don't think logs would be useful here but `%appdata%\osu\logs`

**Comment by cyanidee** [comment] 2019-06-13 18:03
[runtime.log](https://github.com/ppy/osu/files/3287481/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3287482/updater.log)
[database.log](https://github.com/ppy/osu/files/3287483/database.log)
[performance.log](https://github.com/ppy/osu/files/3287484/performance.log)

Dropping logs here, thanks @iiSaLMaN !

**Comment by cyanidee** [comment] 2019-06-13 18:12
Also, if you are wondering how it looks during gameplay... https://streamable.com/8hzii

**Comment by iiSaLMaN** [comment] 2019-06-13 18:14
Try Version 2019.612.0, there were perfomance improvements

**Comment by iiSaLMaN** [comment] 2019-06-13 18:29
btw cyanidee, do not open an issue on an old release of lazer.

**Comment by smoogipoo** [comment] 2019-06-14 02:55
@cyanidee while it's in that state, can you try enabling the "bypass front to back pass" at the bottom of settings?

**Comment by Hubza** [comment] 2019-06-14 14:09
![image](https://user-images.githubusercontent.com/33783503/59515161-6028f600-8eb6-11e9-8997-06580a19fcb3.png)
can confirm, still broken on the latest release. @smoogipoo

**Comment by peppy** [comment] 2019-06-14 14:10
Did you try turning on the bypass in options as asked?

**Comment by Hubza** [comment] 2019-06-14 14:13
Enabling that seemed to fix it somewhat, but some things, like the triangles, background of "main menu slideout?" text rendering, and other parts are still broken. 
![image](https://user-images.githubusercontent.com/33783503/59515418-f8bf7600-8eb6-11e9-8edd-0e0a1b999dbb.png)
![image](https://user-images.githubusercontent.com/33783503/59515425-fc52fd00-8eb6-11e9-9295-9b0591dfa33b.png)
upon opening my user osu!lazer instantly crashed

**Comment by smoogipoo** [comment] 2019-06-14 15:40
Please try again on the latest release, with and without the bypass option. The changes I previously mentioned weren't in the previous release.

**Comment by Hubza** [comment] 2019-06-14 17:31
![image](https://user-images.githubusercontent.com/33783503/59527115-a4c28a80-8ed2-11e9-819a-4ea2b35a3c19.png)
same result still, sadly. @smoogipoo

**Comment by smoogipoo** [comment] 2019-06-14 17:33
You're gonna have to wait until the next build, the build I'm interested in was removed due to a regression.

**Comment by Hubza** [comment] 2019-06-14 17:50
Built a local release from the latest clone, i cant seem to make it happen anymore.

**Comment by iiSaLMaN** [comment] 2019-09-26 01:12
@cyanidee Does this issue still happen on the latest version? there were bug fixes that may potentially fix your issue.

**Comment by CreeperzEdge** [comment] 2019-10-16 11:21
Still occurring on 2019.1011.0
[video](https://ralsei-appreciation.club/i/qyi8p846.mp4)

**Comment by byDave251** [comment] 2019-10-16 15:29
Interesting, here it crashes when I play with resizing the window and the rendering is pretty off. (same version)

**Comment by iiSaLMaN** [comment] 2019-10-16 20:50
@byDave251 If the output is different than the OP has, please consider opening a separate issue instead. (and attach logs)

**Comment by bdach** [comment] 2019-10-16 20:57
@byDave251 You might be looking for #6419 there.

**Comment by peppy** [comment] 2019-10-17 05:10
Confirmation that this is macOS specific?

**Comment by CreeperzEdge** [comment] 2019-10-17 06:44
@peppy Occurs for me on Windows, crash occurs if you continue to resize window after texture corruption

Crash logs:
[runtime.log](https://github.com/ppy/osu/files/3737718/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3737719/updater.log)
[performance.log](https://github.com/ppy/osu/files/3737720/performance.log)

**Comment by Hubza** [comment] 2019-10-17 09:17
Cant seem to make it happen myself, after around 5 minutes of constant resizing. I'll try on MacOS later.

**Comment by Hubza** [comment] 2019-10-17 09:24
Nothing happening on MacOS either.

**Comment by peppy** [comment] 2019-10-17 09:25
Have you tried without this thing running? 
![image](https://user-images.githubusercontent.com/191335/66996339-89c78780-f10b-11e9-87ac-aeccae8e8540.png)

**Comment by Hubza** [comment] 2019-10-17 09:27
Same result, i never had it running today to begin with - I could try **with** it running, though

**Comment by CreeperzEdge** [comment] 2019-10-17 09:35
No longer happens for me when I disable the Discord overlay, in my case its #4741

**Comment by Hubza** [comment] 2019-10-17 09:37
Discord overlay, i'll try enabling that and see if i get results, or if its just you~

**Comment by Hubza** [comment] 2019-10-17 09:45
Yep, its Discord overlay - when i loaded osu!lazer i slightly resized it and it instantly broke
![image](https://user-images.githubusercontent.com/33783503/66997878-2b7ab480-f0cb-11e9-9f37-f04f6fd14bf8.png)

**Comment by peppy** [comment] 2021-02-18 07:05
Coming back to this one post-SDL2, is anyone able to reproduce any more?

**Comment by peppy** [comment] 2021-03-29 07:15
Going to close this one for now. Please comment if you are able to reproduce this still.

**Closed by peppy** 2021-03-29 07:15 UTC
Labels: framework-fix-required
