### ISSUE TITLE
Unable to log into Osu!lazer

### ISSUE THREAD

**Issue by NikoElement** [ppy/osu#8847] opened 2020-04-23 05:32 UTC
Yesterday i've installed Osu!Lazer, i tried logging in but it sends me back to the login screen after around 20 seconds, even after some hours. I tried following instructions on previous reports of this kind of issue but nothing worked

https://www.youtube.com/watch?v=kloYTwmC2KM&feature=youtu.be

Osu!Lazer version 2020.421.0

[network.log](https://github.com/ppy/osu/files/4520406/network.log)
[performance.log](https://github.com/ppy/osu/files/4520408/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4520409/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4520410/updater.log)
[database.log](https://github.com/ppy/osu/files/4520405/database.log)

**Comment by iiSaLMaN** [comment] 2020-04-23 05:53
For confirmation that this is related to the game, can you access this website: https://osu.ppy.sh/oauth/token

**Comment by NikoElement** [comment] 2020-04-23 05:59
> For confirmation that this is related to the game, can you access this website: https://osu.ppy.sh/oauth/token

it shows me this message when i open the link
![confirmation](https://user-images.githubusercontent.com/64185142/80064409-a4f2d400-8540-11ea-9cb2-a8a055fe49c2.JPG)

**Comment by huupoke12** [comment] 2020-04-24 04:53
Can you execute `ping -6 osu.ppy.sh` in the command prompt and paste the result here?

**Comment by NikoElement** [comment] 2020-04-24 07:30
> Can you execute `ping -n 8 -6 osu.ppy.sh` in the command prompt and paste the result here?

Microsoft Windows [Version 10.0.18362.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Virus>ping -n 8 -6 osu.ppy.sh

Pinging osu.ppy.sh [2606:4700:10::6814:341c] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 2606:4700:10::6814:341c:
    Packets: Sent = 8, Received = 0, Lost = 8 (100% loss),

C:\Users\Virus>

**Comment by huupoke12** [comment] 2020-04-24 11:12
So you have a global IPv6 address but it is not correctly routed. You can try restarting the modem/router (the device facing the Internet) so you can get a new IPv6 route. If it doesn't solve the problem, or you frequently have this issue, may want to contact your ISP about the problem.

But in many cases, like me, the IPv6 support of the ISP is just bad. IPv6 just randomly dies out. You can't do much about it, since the route is managed by the ISP. So the solution for it is mentioned in https://github.com/ppy/osu/issues/3507, which it should fallback to IPv4 if IPv6 fails.
For now, you can disable (global) IPv6 to make the problem go away. You can do it at the router/modem so all of your devices' global IPv6 will be disabled.

**Comment by bdach** [comment] 2020-04-24 16:38
Closing as duplicate of aforementioned issue.

**Closed by bdach** 2020-04-24 16:38 UTC
Labels: type:network
