### ISSUE TITLE
The setting list check tag does not appear in the correct location

### ISSUE THREAD

**Issue by Stapxs** [ppy/osu#11195] opened 2020-12-18 00:27 UTC
~~~
Im NOT good at English
~~~

**Describe the bug:** 
The setting list check tag does not appear in the correct location

**Screenshots or videos showing encountered issue:** 
![image](https://github.com/Stapxs/SS-Warehouse/blob/main/Files/lazer-1.gif)

**osu!lazer version:** 
2020.1212.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5712850/logs.zip)

**Comment by Joehuu** [comment] 2020-12-18 00:30
Duplicate of https://github.com/ppy/osu/issues/9196

**Closed by Joehuu** 2020-12-18 00:30 UTC
