### ISSUE TITLE
osu!direct crashing Lazer (Android)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6307] opened 2019-09-28 17:30 UTC
**Describe the bug:** Basically, when I'm trying to get a new beatmap on my Android phone using osu!direct, osu!direct keeps crashing me out of Lazer.

**Screenshots or videos showing encountered issue:** https://drive.google.com/file/d/10b6TGlSBp8LyRghrZqNBaZCyIoBiab_k/view?usp=drivesdk
**osu!lazer version:** 2019.925.19

**Logs:** Can't find logs

**Comment by bdach** [comment] 2019-09-28 17:30
Duplicate of #6264.

**Closed** 2019-09-28 17:37 UTC
