### ISSUE TITLE
Ctrl+Backspace triggers and Unhandled error when text box is empty.

### ISSUE THREAD

**Issue by nitsuga5124** [ppy/osu#7520] opened 2020-01-13 13:39 UTC
**Describe the bug:** 
An unhandled error notification shows up when pressing Ctrl+Backspace on a text box that's empty

**Screenshots or videos showing encountered issue:** 
https://5124.16-b.it/ss/14:34:06_13-01-2020.png

**osu!lazer version:** 
2020.112.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/4053802/runtime.log)

**Comment by jai-x** [comment] 2020-01-13 13:47
Duplicate of #7505, already fixed with ppy/osu-framework#3171. Issue can be closed.

**Closed** 2020-01-13 14:09 UTC
