### ISSUE TITLE
Feature request / Custom beatmaps folder path

### ISSUE THREAD

**Issue by iamapig120** [ppy/osu#2584] opened 2018-05-18 13:14 UTC
I have downloaded full pack of Ranked Beatmaps in standards version. These can be set in the same folder as osu!'s.
But in lazer version. Well.
I have no enough storage space of C:\...

So, Just a Feature request

**Comment by peppy** [comment] 2018-05-18 13:15
Duplicate of https://github.com/ppy/osu/issues/1907.

You can already do this with a junction or symlink.

**Closed by peppy** 2018-05-18 13:15 UTC
