### ISSUE TITLE
Geforce Experience shows too many "Osu!"

### ISSUE THREAD

**Issue by Kenshelent** [ppy/osu#22789] opened 2023-03-04 15:49 UTC
### Type

Other

### Bug description

After every update of "Osu! Lazer" Gefroce shows the new "osu!" without deleting the old one.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/38864337/222915639-4d1ab3bc-40bc-47e5-b7b5-99afc3646966.png)

### Version

2023.301.0-Lazer

### Logs

No logs needed

**Comment by Kenshelent** [comment] 2023-03-04 15:51
![image](https://user-images.githubusercontent.com/38864337/222915771-e8492063-407f-4006-b370-55849be9c5e0.png)


![image](https://user-images.githubusercontent.com/38864337/222915777-e9b1cac7-d223-4878-92b7-0868918fcefb.png)

**Comment by bdach** [comment] 2023-03-04 16:34
This is more or less a duplicate of #10550 (and will be fixed in the same manner).

**Closed by bdach** 2023-03-04 16:34 UTC
