### ISSUE TITLE
Twice slowdown in gameplay if there is no audio device

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9861] opened 2020-08-15 08:51 UTC
**Describe the bug:** 
If before you turn on the application without a sound device (or turn it off at any time), then the gameplay will slow down 2 times. It does not affect the operation of the laser itself. Perhaps it is worth blocking the entrance to the lazer without an audio device, as is done in the stable? No, this is not a user-side problem. This is easy to repeat.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/v3Af0iskQbU
**osu!lazer version:** 
2020.814.0

**Comment by peppy** [comment] 2020-08-15 08:53
We intend the game to continue with no audio device. This doesn't look right.

**Comment by peppy** [comment] 2020-11-02 08:25
Closing as duplicate of https://github.com/ppy/osu/issues/9938

**Closed by peppy** 2020-11-02 08:25 UTC
Labels: type:audio
