### ISSUE TITLE
Spectating in Multi sometimes has one player far behind

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14422] opened 2021-08-20 21:25 UTC
Player was using Flashlight but might have been their internet.

**video:** https://www.youtube.com/watch?v=lstDGdhyh8Y
**osu!lazer version:** 2021.820.0-lazer

**Comment by PercyDan54** [comment] 2021-08-21 06:14
Is this kinda duplicate of #11574?

**Comment by frenzibyte** [comment] 2021-08-21 07:11
The multi-spectator logic receives the first bundle and seek their respective spectator clock to that time and makes it follow the elapsed time of the master clock, meaning that the issue here is why the received frame is far behind from the other players.

Since the difference here is 5 seconds, I can't think of anything but bad internet, as it also seems like the respective spectator instance is trying to catch up but the replay frames are still getting briefly sent at that current time.

**Comment by peppy** [comment] 2021-08-24 06:34
Going to close this an continue tracking on #11574. It's the same issue.

**Closed by peppy** 2021-08-24 06:34 UTC
Labels: area:spectator
