### ISSUE TITLE
Performance drop on storyboard elements

### ISSUE THREAD

**Issue by Hunnus** [ppy/osu#24944] opened 2023-09-27 10:23 UTC
### Type

Performance

### Bug description

Today i was playing Hanabi Taikai (https://osu.ppy.sh/beatmapsets/1188324#osu/2757756) with storyboard on and experienced huge performance drop around 1 min into the map, and later on 1st when the blue waves appeared, later at fireworks.
my settings:

- Fullscreen
- Direct 3D
- 4x refresh rate
- multithreaded

on:

- i7 11800H
- RTX 3050 Ti Laptop GPU (4GB)
- 16 GB DDR4 RAM
- NVMe Samsung 980 1TB
- 144HZ adaptive sync monitor

### Version

2023.924.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/12737473/logs.zip)

**Comment by peppy** [comment] 2023-09-28 06:30
Duplicate of https://github.com/ppy/osu/issues/3756. Please post the beatmap to that thread instead, to help with any future effort to improve performance.

**Closed by peppy** 2023-09-28 06:30 UTC
