### ISSUE TITLE
menus don't open and no song info

### ISSUE THREAD

**Issue by Moxanthia** [ppy/osu#12143] opened 2021-03-22 17:27 UTC
I can select menu options leading to song selection, and all of my beatmaps do display on the righthand side, but no data appears on the left. If I try to select another song nothing happens. Additionally, trying to open the options or any of the UI elements from the top bar does nothing (the sound effect and highlight do appear when clicking on them though).

![lazer_no_song_info](https://user-images.githubusercontent.com/17536688/112031233-b6ea4780-8b00-11eb-84a4-9adb2099f9ea.png)

**osu!lazer version:** 2021.320.0 on Windows 10

**Logs:**
[network.log](https://github.com/ppy/osu/files/6184121/network.log)
[performance.log](https://github.com/ppy/osu/files/6184123/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6184124/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6184125/updater.log)
[database.log](https://github.com/ppy/osu/files/6184127/database.log)

**Comment by frenzibyte** [comment] 2021-03-22 17:28
Duplicate of https://github.com/ppy/osu/issues/12094 which has been already fixed, a hotfix release will be published soon enough.

**Closed by frenzibyte** 2021-03-22 17:28 UTC
