### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by Alex-the-Almond** [ppy/osu#20347] opened 2022-09-16 17:18 UTC
### Type

Crash to desktop

### Bug description

Installed Lazer, played for a few days, turned off PC, next day game just refuses to launch. Nothing changed with my OS environment. Uninstalling and re-installing doesn't change anything.

### Screenshots or videos

Video attached here:
https://clips.twitch.tv/HeartlessEntertainingBaboonOSsloth-TAAVSx4r9-lXhtGr

### Version

2022.911.0

### Logs

Osu!Lazer file doesn't have a Logs folder:

<img width="690" alt="no logs" src="https://user-images.githubusercontent.com/97411075/190692862-5aaf6895-acaf-4cd8-8488-7932af4625a7.PNG">

Event Viewer:

<img width="688" alt="Event Logs 1" src="https://user-images.githubusercontent.com/97411075/190693078-6a32dda5-b92c-4630-98bc-f99fc602a7cf.PNG">

<img width="686" alt="Event Logs 2" src="https://user-images.githubusercontent.com/97411075/190693212-7077479f-03ca-480e-86a1-fc2a1a6bfb9c.PNG">

Providing a copy of regular osu Logs to submit, ignore these :
[runtime.log](https://github.com/ppy/osu/files/9585971/runtime.log)
[session.log](https://github.com/ppy/osu/files/9585972/session.log)
[update_success.log](https://github.com/ppy/osu/files/9585973/update_success.log)
[osu!auth.log](https://github.com/ppy/osu/files/9585974/osu.auth.log)

**Comment by frenzibyte** [comment] 2022-09-17 14:47
Wrong logs attached. Please follow the description in the issue template. Also likely to be a duplicate of https://github.com/ppy/osu/issues/19064, please check that thread.

**Comment by Alex-the-Almond** [comment] 2022-09-17 15:00
I cannot find the logs folder, I believe my folder path is correct and there should be a logs folder there. I've dug through my osu!Lazer folder and cannot find logs anywhere. I never changed my monitor configurations so how could that be the cause of my issue? I'm trying to understand what is going wrong here. However I do also have 4 displays, just like the post you mentioned. Could it have something to do with that?

**Comment by Alex-the-Almond** [comment] 2022-09-17 15:03
Sorry for double commenting but could it be located in the Appdata Roaming folder? These are the logs from that:

[legacy-ipc.log](https://github.com/ppy/osu/files/9591972/legacy-ipc.log)
[performance.log](https://github.com/ppy/osu/files/9591973/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9591974/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9591975/updater.log)
[database.log](https://github.com/ppy/osu/files/9591976/database.log)

**Comment by frenzibyte** [comment] 2022-09-17 15:04
Have you read the description of that thread and applied as such?

**Comment by Alex-the-Almond** [comment] 2022-09-17 15:14
I see that they mentioned changing the framework.ini file, where is that located?

**Comment by frenzibyte** [comment] 2022-09-17 15:32
On the parent folder of where you found the game logs.

**Comment by Alex-the-Almond** [comment] 2022-09-17 15:41
That seems to have fixed it, had to change LastDisplayDevice = Third to LastDisplayDevice = First
Thank you!

**Closed** 2022-09-17 15:41 UTC

**Comment by Alex-the-Almond** [comment] 2022-09-17 19:37
Oops, did you need to collect any more information from me. Sorry, I figured since it was fixed we could just close it.

**Comment by frenzibyte** [comment] 2022-09-17 19:45
Just marked this as a "duplicate" close rather than "resolved".
