### ISSUE TITLE
Disconnected from multiplayer lobby mid map

### ISSUE THREAD

**Issue by harshavb** [ppy/osu#11959] opened 2021-03-03 23:27 UTC
**Describe the bug: **Got disconnected mid map in a multiplayer lobby, and an error was thrown. Nobody else got disconnected. Upon rejoining the lobby (I think?), various other errors were thrown.

**Screenshots or videos showing encountered issue:** See network.log 23:16:11 for the first error and runtime.log for the other errors.

**osu!lazer version:** 2021.302.0.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6079778/network.log)
[performance.log](https://github.com/ppy/osu/files/6079779/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6079780/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6079781/updater.log)
[database.log](https://github.com/ppy/osu/files/6079782/database.log)

**Comment by peppy** [comment] 2021-03-04 00:16
Can you confirm that restarting the game fixed the issue?

**Comment by harshavb** [comment] 2021-03-04 22:33
It seems to have - was able to play multi without any errors/disconnects.

**Comment by harshavb** [comment] 2021-03-09 11:36
I was able to rejoin the lobby. The only concern here was me getting disconnected in the first place, which happened presumably because of the initial error. The other errors were thrown when I rejoined the lobby, but they didn't actually cause any issues. I did not try playing another map afterwards, instead leaving the lobby and quitting out of the game.

**Comment by peppy** [comment] 2021-03-10 08:23
The original error here was you getting disconnected from the server, so it makes sense that things stopped working. 

That said, the follow up errors I can see in your logs look to have happened when you left the game, not when trying to rejoin it.. which doesn't match what you are saying happened.

I think the best course of action is to close this issue for now, as we are already aware of the specific errors in your log. The UX can likely be improved (presenting them in a more user-digestible way) but the cause of them is correct.

**Closed by peppy** 2021-03-10 08:23 UTC
Labels: area:multiplayer, missing details
