### ISSUE TITLE
Replays by other players are visible in the Local tab

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#5924] opened 2019-08-31 13:45 UTC
**Describe the bug:** 

Replays by other players that are downloaded are visible in the Local tab in song select.

What does *Local* mean?
- Replays of you only (stable behavior)
- Any replay that are saved on the computer

If the latter, there should be a way to selectively delete replays.

**Screenshots or videos showing encountered issue:** https://streamable.com/hg1pp

**osu!lazer version:** 2019.831.0

**Comment by Game4all** [comment] 2019-08-31 13:58
Duplicate of #5352 
That behaviour is intentional.

**Closed** 2019-08-31 13:58 UTC
