### ISSUE TITLE
Beatmap download fails after it was deleted with a score set on an edited version

### ISSUE THREAD

**Issue by KowalskiPiotr98** [ppy/osu#13344] opened 2021-06-05 20:42 UTC
**Describe the bug:** 
1. Edit an existing beatmap. Make sure there's a local score set either before or after the edit.
2. Delete all difficulties of the beatmap.
3. Without closing the game try to redownload the bitmap - an error occurs.
4. Works fine after restart.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/56399446/120904803-70f84680-c64e-11eb-9b4b-721fe0ecc080.mp4

**osu!lazer version:** 
2021.602.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6603193/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6603194/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6603195/updater.log)
[database.log](https://github.com/ppy/osu/files/6603196/database.log)
[network.log](https://github.com/ppy/osu/files/6603197/network.log)

**Comment by bdach** [comment] 2021-06-05 21:20
Duplicate of #10480

**Closed by bdach** 2021-06-05 21:20 UTC
