### ISSUE TITLE
Can't log into osu!lazer

### ISSUE THREAD

**Issue by Regolin542** [ppy/osu#11121] opened 2020-12-07 23:00 UTC
I tried to login when it didnt let me I thought i forgot my password. I can login to osu stable.

osu!lazer version:2020.1204.0.0

`2020-12-07 22:55:47 [verbose]: ----------------------------------------------------------
2020-12-07 22:55:47 [verbose]: network Log for krzys (LogLevel: Verbose)
2020-12-07 22:55:47 [verbose]: osu 2020.1204.0.0
2020-12-07 22:55:47 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 4 cores
2020-12-07 22:55:47 [verbose]: ----------------------------------------------------------
2020-12-07 22:55:47 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2020-12-07 22:55:57 [verbose]: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2020-12-07 22:55:57 [verbose]: Login failed!
`

**Comment by bdach** [comment] 2020-12-07 23:03
Presumably duplicate of #3507

**Closed by bdach** 2020-12-07 23:03 UTC
