### ISSUE TITLE
Wrong GPU selected after osu!lazer update

### ISSUE THREAD

**Issue by ghost** [ppy/osu#10550] opened 2020-10-17 20:12 UTC
**Describe the bug:**
I need to manually add osu to the list of programs nvidia will detect in order to run osu on my dedicated gpu (I'm using an old laptop from around 2009).
After updating osu the folder where osu is located has changed because it has the version numbers in it.
Not that it's a big issue but now I have to add the new version to nvidia's list after every update :smile:

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/67192919/96352594-43a95900-10bc-11eb-8cd4-24498d2522a0.png)

**osu!lazer version:** 
2020.1017.0

**Comment by bdach** [comment] 2020-10-17 20:36
I'm half inclined to say this shouldn't be our problem. Unless we change our deployment/update method to not use separate executables for each version I don't know what we could possibly do to convince the vendor software to use the actual graphics card instead of the integrated one.

**Comment by erwin-k** [comment] 2020-10-17 20:53
I've resolved this by adding a custom path appdata\local\osulazer\osu!.exe
Not sure if that's okay but if it is, maybe it can be made so that nvidia driver will find that path instead.

![image](https://user-images.githubusercontent.com/67192919/96353367-1c09bf00-10c3-11eb-9a70-024c7ed6755d.png)

**Comment by bdach** [comment] 2020-10-18 10:53
As far as I can tell optimus should be forcing high performance if some static libraries are linked, but I don't think we do any static linking. There does seem to possibly be another way but (a) it only works for some driver versions (Release 302 and above) and (b) it's absolutely hideous ([source](https://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf)):

```cpp
extern "C" {
     _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
}
```

I'm not sure how to even embed that in a .NET Core executable.

The `%LocalAppData%/osulazer/osu!.exe` path should be a reliable workaround, so I think we should go with that as the official way to make optimus switch to the higher-perf card and not add any ugly workarounds.

**Comment by erwin-k** [comment] 2020-10-18 11:11
Sorry about that, adding just that path did not work after all.

**Comment by Game4all** [comment] 2020-10-18 18:49
This overlaps with / is a dupe of #5582.

**Comment by smoogipoo** [comment] 2020-10-19 03:33
I wouldn't say this is a dupe really. Also the linked issue needs discussion anyway - I'm not convinced we should be using the dGPU by default anyway - it can, depending on the system and optimisation of the game, actually result in lower frametime/higher latency (see: osu!stable).

I'll keep this open to track the issue of driver configs not persisting across updates, as this is definitely something we'll want to fix regardless.

Maybe something to consider at the point of moving away from Squirrel (if ever).

**Comment by KarstenPH** [comment] 2020-10-20 13:27
maybe try right clicking on the .exe file and selecting the GPU from there?

**Comment by TheGloriousDuck** [comment] 2021-08-12 02:20
> maybe try right clicking on the .exe file and selecting the GPU from there?

That isn't really fixing the actual issue. OP can simply readd the exe through NVIDIA control panel, but is looking for a way to not do that and have a permanent solution.

**Comment by smoogipoo** [comment] 2021-08-12 02:23
That is the intended way to use Windows. There's even a GPU setting somewhere in the system settings these days made for this purpose and intended to replace the NVIDIA control panel setting.

**Comment by caesay** [comment] 2022-04-25 09:13
This will be fixed by https://github.com/clowd/Clowd.Squirrel/issues/24

**Closed** 2024-09-04 07:09 UTC
Labels: area:installer, platform/windows
