### ISSUE TITLE
Autoplay cannot recover from misses caused by Strict Tracking

### ISSUE THREAD

**Issue by ghost** [ppy/osu#17624] opened 2022-04-03 02:38 UTC
### Type

Game behaviour

### Bug description

Steps
1. Open any osu!standard beatmap with sliders with the mods Strict Tracking and Autoplay activated.
2. Fiddle around with the progress bar going backwards or forwards until you can get Autoplay to mess up and drop accuracy from a miss caused by how Strict Tracking works
3. Rewind before the miss

This should cause the accuracy to further drop until rewinding at the very beginning of the map will make accuracy have a value of 0%, also Autoplay won't be able to go back to 100% from the beginning of the beatmap either.

### Screenshots or videos

https://user-images.githubusercontent.com/85420241/161408602-a0e0df55-e199-4f27-a038-a0c7f88d5a1d.mp4

### Version

2022.327.0

### Logs

[runtime.log](https://github.com/ppy/osu/files/8403694/runtime.log)
[performance-audio.log](https://github.com/ppy/osu/files/8403695/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8403696/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8403697/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8403698/performance-update.log)

**Comment by integerrr** [comment] 2022-04-06 10:47
Would it be feasible to make the 2 mods incompatible with each other? As auto is already following sliders perfectly by design I don't see a reason for applying both mods at the same time

**Comment by bdach** [comment] 2022-04-06 17:45
if misses aren't reverting properly on a replay then that needs to be investigated in detail, because that may be causing issues in more places than this one. making autoplay incompatible is a band aid at best and therefore not acceptable.

**Comment by bdach** [comment] 2023-12-11 10:26
I'm closing this one because this has been reported again, but this issue due to being from a deleted account is not visible in search etc. compared to the "duplicate" of it.

**Closed by bdach** 2023-12-11 10:26 UTC
Labels: area:mods
