### ISSUE TITLE
Downloading maps is impossible

### ISSUE THREAD

**Issue by Denver323** [ppy/osu#6365] opened 2019-10-02 12:50 UTC
![Uploading  #Screenshot_20191002-204259.png…]()
**Describe the bug:** Every time I download a map on Android it fails, it crashes also.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.930.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/3681133/network.log)
[database.log](https://github.com/ppy/osu/files/3681134/database.log)
[performance.log](https://github.com/ppy/osu/files/3681135/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3681136/runtime.log)

**Comment by peppy** [comment] 2019-10-02 13:07
Duplicate of https://github.com/ppy/osu/issues/6264. Please search before posting.

**Closed by peppy** 2019-10-02 13:07 UTC
