### ISSUE TITLE
Spectator Playback speed causing music to be "scrambled"

### ISSUE THREAD

**Issue by Zalmez** [ppy/osu#14502] opened 2021-08-25 23:57 UTC
**Describe the bug:** 
When adjusting the playbck speed in spectator mode the audio gets "scrambled" in a way tested this on a few beatmaps and this is consitent between all of them so far. also been tested with a few different mods to see the effect

Reprod steps:
1. Spectate a player
2. download the map if not downloaded 
3. Increase the playback speed to max - even when adjusted down it will be weird until the value has reached 1 again

Sometimes playback works as it should, but so far majority of the time it does not so far (an example is in the video with the airman beatmap)

**Screenshots or videos showing encountered issue:** 
Added two videos with audio 
https://user-images.githubusercontent.com/8438702/130878903-4a2d74be-02db-4692-bddf-f2eb2898465a.mp4

https://user-images.githubusercontent.com/8438702/130878893-f67b629a-52db-43ca-ab72-48267834101a.mp4

**osu!lazer version:** 
2021.820.0-lazer
**Logs:**

[database.log](https://github.com/ppy/osu/files/7050556/database.log)
[network.log](https://github.com/ppy/osu/files/7050557/network.log)
[performance.log](https://github.com/ppy/osu/files/7050558/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7050559/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7050560/updater.log)

**Comment by hbnrmx** [comment] 2021-08-28 19:51
Duplicate of #11173

**Comment by frenzibyte** [comment] 2021-08-28 19:52
I'm going to close the old one instead as this one has received more activity.

**Comment by Loreos7** [comment] 2021-09-08 11:55
@bdach think it seems to be like in youtube live stream red button "Live". If you click at the end of the song the player brings you back to current (live) time. 

https://user-images.githubusercontent.com/86934170/132504937-01303482-0682-40ef-9cfe-dc5cea6243bf.mp4

**Comment by peppy** [comment] 2022-06-19 07:59
I think once spectator catches up it should force the speed back to 1.0x.

**Closed** 2022-06-21 05:41 UTC
Labels: area:spectator, priority:1
