### ISSUE TITLE
Cannot Beat Difficult Maps

### ISSUE THREAD

**Issue by BojayB** [ppy/osu#10367] opened 2020-10-04 17:47 UTC
The title may sound misleading but I don't know what else to call it. Please remove if this issue isn't a proper issue. Running on Lubuntu (Ubuntu 20.04.1).
**Describe the bug:** 
So I thought you could only die if you miss a note at a low enough health. Well, since the latest update, that doesnt happen. In the maps I play (and could play before the update) my health barely goes up (probably because I'm not that good) and once it gets too low I lose. I used to be able to play until I **actually** did bad but now i just die and cannot play the maps without full health.

**Screenshots or videos showing encountered issue:** 
(lag is due to recording, issue persists just the same without lag. Not sure how to embed video)
https://youtu.be/VG5bj5QT-6M

**osu!lazer version:** 
2020.1002.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5323806/database.log)
[network.log](https://github.com/ppy/osu/files/5323807/network.log)
[performance.log](https://github.com/ppy/osu/files/5323808/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5323809/runtime.log)

**Comment by BojayB** [comment] 2020-10-04 17:48
This also happens on multiple maps with a higher difficulty, not just one.

**Comment by bdach** [comment] 2020-10-04 17:50
Duplicate of #10337.

Please search before opening issues.

**Closed by bdach** 2020-10-04 17:50 UTC

**Comment by BojayB** [comment] 2020-10-04 17:54
i tried but couldnt find anything
