### ISSUE TITLE
Game crashes when loading Beatmap

### ISSUE THREAD

**Issue by alvarosaez316** [ppy/osu#9343] opened 2020-06-23 00:43 UTC
**Describe the bug:** 
I'm on LG K10 2017 (8-core CPU, 2GB of RAM, Mali-T860MP2 GPU), running android 8.1, with ES_es system language and no root. When I try to start a beatmap, the game crashes. If I load a beatmap, I get a typical 'App stopped' message, but there's still sound and you can even hear the fail distortion when it should happen if the game was still running, so it hasn't completely crashed.
**Screenshots or videos showing encountered issue:** 
https://imgur.com/CW7wc0Q
**osu!lazer version:** 
2020.620.0
**Logs:**
Beatmap:
[runtime[1].log](https://github.com/ppy/osu/files/4816211/runtime.1.log)
[performance[1].log](https://github.com/ppy/osu/files/4816212/performance.1.log)
[network[1].log](https://github.com/ppy/osu/files/4816213/network.1.log)
[database[1].log](https://github.com/ppy/osu/files/4816214/database.1.log)

**Comment by alvarosaez316** [comment] 2020-06-23 00:54
Edit: Split this into two issues for obvious reasons

**Comment by peppy** [comment] 2020-06-23 00:55
Fixed in next release, duplicate of https://github.com/ppy/osu/issues/9321

**Closed by peppy** 2020-06-23 00:55 UTC
