### ISSUE TITLE
The success bar is not displayed correctly in the mobile application.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9581] opened 2020-07-16 06:56 UTC
**Describe the bug:** 
It is literally upside down. Screen resolution 2400 x 1080, Android 10 (not PC). It's about the graph in the lower left corner.
**Screenshots or videos showing encountered issue:** 
![Screenshot_2020-07-16-16-48-26-07_25a1a32208bbcdc1d450b7aa854bb161](https://user-images.githubusercontent.com/59089206/87636892-c6044300-c784-11ea-96c5-8352f0f2e6ee.jpg)
**osu!lazer version:** 
2020.714.0

**Comment by Moltanicaa** [comment] 2020-07-16 07:03
The reason was found - due to the increase in Scaling UI, it gradually "turns out". With the normal interface size, everything is fine.
![Screenshot_2020-07-16-17-02-19-64_25a1a32208bbcdc1d450b7aa854bb161](https://user-images.githubusercontent.com/59089206/87637755-0f08c700-c786-11ea-9700-82e82f8fabde.jpg)

**Comment by Joehuu** [comment] 2020-07-16 07:10
Duplicate of https://github.com/ppy/osu/issues/4931

**Closed by Joehuu** 2020-07-16 07:10 UTC
Labels: area:song-select, type:UI
