### ISSUE TITLE
Co-op Mapping Integration

### ISSUE THREAD

**Issue by Smowokeman** [ppy/osu#5682] opened 2019-08-11 18:53 UTC
**Describe the new feature:** It should be similar to how Google docs work where you can have multiple people work on the same document but with mapping. Over the years mappers have found ways to make collaboratory mapping work without this but as a feature, it still holds a lot of merit for endeavors like teaching and modding.

**Proposal designs of the feature:** 
- The host can allow other users to join the map editor and every tick (quarter of a second or even real-time?) the map gets updated, potentially with a drawing features for better teaching options.
- Saving the map could create a local version of the map.
- This could also work as a solution to GDers uploading their diffs on their own to the set as everything is saved in a cloud.  
- In terms of file size, we are only talking about updating kb big .osu files and interaction data like "selected objects". 
- It might need some tinkering around people simultaneously editing on the same tick in the song as the editor is not made for multiple people to be working on simultaneously.
- A cool addition could be live updating sliders as they are being drawn.

I would also like to remind peppy of this old post https://osu.ppy.sh/community/forums/topics/108829 and refer to pishifat's videos on mapping which should fulfill the requirements for our end of the deal :)

**Comment by peppy** [comment] 2019-08-11 18:54
Duplicate of #5678 and potentailly others please search first.

**Closed by peppy** 2019-08-11 18:54 UTC

**Comment by Smowokeman** [comment] 2019-08-11 18:55
oh i checked yesterday, i didnt think someone would psot the same 5 hours ago :(

**Comment by iiSaLMaN** [comment] 2019-08-11 18:56
Just check before opening an issue.
