### ISSUE TITLE
Different download icons in sections

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8479] opened 2020-03-28 11:06 UTC
In the messages and friends section, everything is fine. In some sections, it does not exist at all.
![osu_2020-03-28_19-25-27](https://user-images.githubusercontent.com/59089206/77821684-e6f24b00-7137-11ea-92a7-ade67a3bab32.png)
![osu_2020-03-28_19-25-23](https://user-images.githubusercontent.com/59089206/77821686-ea85d200-7137-11ea-9bf1-84a7cc1adde6.png)
![osu_2020-03-28_19-25-19](https://user-images.githubusercontent.com/59089206/77821687-ea85d200-7137-11ea-8bda-9f89468af899.png)

osu!lazer version:
2020.327.0

**Comment by bdach** [comment] 2020-03-28 11:45
Duplicate of #7417

**Closed by bdach** 2020-03-28 11:45 UTC
