### ISSUE TITLE
Spamming with a few fingers during song loading will cause a crash

### ISSUE THREAD

**Issue by power9maker** [ppy/osu#9185] opened 2020-06-02 16:28 UTC
**Describe the crash:** 

When you start a map and tap the screen with a few fingers quickly, the app will crash.

**Screenshots or videos showing encountered issue:** 

[Here's a video](https://youtu.be/w-wAinpJKnE)

**osu!lazer version:** 

2020.602.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/4718394/database.log)
[network.log](https://github.com/ppy/osu/files/4718395/network.log)
[performance.log](https://github.com/ppy/osu/files/4718396/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4718398/runtime.log)

**Computer Specifications:** 

iPad Pro 10.5" 256GB WiFi + Cellular

**Comment by frenzibyte** [comment] 2020-06-02 16:31
I see no issues with the logs you've attached, perhaps you ran the game after it crashed (which would overwrite the logs)? 

Please reproduce again and attach logs before running the game post-crashing.

**Comment by bdach** [comment] 2020-06-02 16:47
Seeing that it's an iPad it might be a native xamarin/mono crash. Not sure how to get any more debugging information out of an Apple device.

**Comment by Phippe** [comment] 2020-06-02 19:57
Could reproduce on an iPhone 11, iOS 13.5 as well, maybe one these logs helps:

[database.log](https://github.com/ppy/osu/files/4719378/database.log)
[network.log](https://github.com/ppy/osu/files/4719381/network.log)
[performance.log](https://github.com/ppy/osu/files/4719391/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4719392/runtime.log)

**Comment by MiraiSubject** [comment] 2020-06-02 21:25
Managed to reproduce this on https://github.com/ppy/osu/commit/a3e31adbf91d988318d7f5e2387fe4f4b410efea. The device stays stuck on a black screen in this case and no exceptions get thrown by VS on Mac, at least on my side. 

Just the following got output by the console: 
```
2020-06-02 23:21:11.314 osu.iOS[25540:2424480] [runtime] 2020-06-02 21:21:11 [verbose]: Screen changed → Player
2020-06-02 23:21:11.857 osu.iOS[25540:2424529] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-06-02 23:21:11.881 osu.iOS[25540:2424529] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=2 "Caused GPU Hang Error (IOAF code 3)" UserInfo={NSLocalizedDescription=Caused GPU Hang Error (IOAF code 3)}
2020-06-02 23:21:11.893 osu.iOS[25540:2424534] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=4 "Ignored (for causing prior/excessive GPU errors) (IOAF code 4)" UserInfo={NSLocalizedDescription=Ignored (for causing prior/excessive GPU errors) (IOAF code 4)}

```

Tested on an iPhone 11 Pro, iOS 13.5 as well.

**Comment by peppy** [comment] 2020-06-03 03:41
Can you confirm that this only happens when touching the screen rapidly during the loading sequence?

**Comment by smoogipoo** [comment] 2020-06-03 05:31
Fwiw this happens as soon as you tap on the screen in player. Has nothing to do with the loading screen.

I'll try to get the logs myself since I can replicate, but re-dling xcode will take some time >_>

**Comment by peppy** [comment] 2020-06-03 07:03
Have confirmed this is fixed on master.

**Closed by peppy** 2020-06-03 07:03 UTC
Labels: missing details, platform:iOS
