### ISSUE TITLE
Sort by Date Submitted and Date Ranked Sorted Strangely

### ISSUE THREAD

**Issue by Zyluki** [ppy/osu#27884] opened 2024-04-15 19:38 UTC
### Type

Game behaviour

### Bug description

While sorting by when a map was submitted or ranked, it sorts it seemingly randomly in many ways. For example, Sotarks' Rockefeller Street was ranked in May of 2019, his Harumachi Clover Swing Arrangement was ranked in September of 2018, and his Kira Kira (Cut Ver.) set was ranked in 2021. The order in the song select from top to bottom is Rockefeller Street, Harumachi Clover, and Kira Kira days, which makes the order by years to be 2019, the earlier 2018, and back to a 2021 song.

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14983579/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-04-15 20:42
Duplicate of https://github.com/ppy/osu/issues/22416

**Closed by Joehuu** 2024-04-15 20:42 UTC
