### ISSUE TITLE
Music does not stop on failing a beatmap

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#1369] opened 2017-10-13 16:58 UTC
Steps to reproduce:
1. Select o!s mode
2, Use any modifier
3. Fail a beatmap

**Comment by peppy** [comment] 2017-10-13 16:58
Yes, we are well aware.

A fix would be great!

**Comment by chikahide** [comment] 2017-10-15 22:51
The bug can also occur without modifier
https://streamable.com/tc4j1

**Comment by odgaard** [comment] 2017-10-22 13:56
There seems to be some timer-based inter-dependency.
 
If a quick-fix is interesting, then adding a short sleep after stopping the timer, but before rendering the overlays fixes it (at least I can't reproduce the bug anymore)
From line 282 in onFail() in osu.Game/Screens/Play/Player.cs
```
            decoupledClock.Stop();
            HasFailed = true;
            failOverlay.Retries = RestartCount;

            System.Threading.Thread.Sleep(20);

            failOverlay.Show();
            return true;
```

**Comment by peppy** [comment] 2017-10-25 04:55
Will be resolved by https://github.com/ppy/osu-framework/pull/1120

**Comment by peppy** [comment] 2017-11-21 06:11
This has been resolved.

**Closed by peppy** 2017-11-21 06:11 UTC
Labels: framework fix required, pending review
