### ISSUE TITLE
Lazer rendered a score/replay incorrectly

### ISSUE THREAD

**Issue by PIECEofTOAST1** [ppy/osu#12760] opened 2021-05-12 03:49 UTC
I'm sorry if this has already been posted, but I tried searching all the keywords I could think of and didn't find it. 

**Describe the bug:** 
This score was played in singleplayer

Lazer didn't render a replay/score properly. The stats don't match the actual play I made, the replay doesn't match my actual play either (or the stats). My actual play was an FC, but the replay shows me missing about 300 combo in (it also shows weird tapping, my taps "bunch up" into clumps for some reason, which is not part of my playstyle). Even though there's a miss in the replay, the stats screen shows that there are 0 misses. Despite this though, it still shows the combo as 700 (so it recognized the combo break from right when the "miss" happened). Also the combo in the replay does not match the stats AT ALL, it shows me missing every 100 combo or so and getting an absolutely atrocious acc, despite the stats not reflecting that.

Interestingly, the replay plays out completely differently if it's loaded in lazer or stable. In lazer there's a lot of "tap clumping" as I described earlier, and the first miss happens around 300 combo. On stable on the other hand, the tap clumping was gone, and only 1 miss happens around 700 combo instead. 

**Screenshots or videos showing encountered issue:** 
https://cdn.discordapp.com/attachments/805553077087764510/841843819510890566/PIECEofTOAST_playing_UNDEAD_CORPORATION_-_Karakurenai_Entry_Lunatic.osr
here is a link to the replay itself, I hosted it with discord because github told me they cannot host that filetype. If need be I can try to load it up and record gameplay footage of it but I'm honestly kind of lazy and really don't feel like sitting down to record all of this when the replay should show everything you need (and more). 

**reproduction**
currently unknown, this is my first and only experience of this issue. 

**pc specs**
graphics: nvidia GTX 970
cpu: AMD Ryzen 3600
ram: 16gb
harddrive: osu is installed on a 500gb SSD

**osu!lazer version:** 
2021.502.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6463212/database.log)
[network.log](https://github.com/ppy/osu/files/6463213/network.log)
[performance.log](https://github.com/ppy/osu/files/6463214/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6463215/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6463216/updater.log)

**Comment by PIECEofTOAST1** [comment] 2021-05-12 03:59
So an update, something I didn't realize before I posted this. When you load the replay into lazer it automatically adjusts the score and combo to reflect what the replay shows (it did not do this until I exported the replay and re-opened it). However if you open it in stable you can still see the broken stats (score, combo, etc.). Here is a picture of them. 
![image](https://user-images.githubusercontent.com/84053419/117916311-ecb3dd00-b2b4-11eb-933f-d5940944023a.png)

**Comment by bdach** [comment] 2021-05-12 19:58
On latest `master` I am seeing one combo break at 651x. So I think this is partially resolved by #12665, as that change hasn't landed in a release yet.

Not sure about the rest, because this issue is really confusing to make sense of as to what stats are expected and what stats are wrong.

**Comment by PIECEofTOAST1** [comment] 2021-05-12 23:56
> On latest `master` I am seeing one combo break at 651x. So I think this is partially resolved by #12665, as that change hasn't landed in a release yet.

You might be correct that #12665 fixes the issue, though the combo break you see is still not correct. The original play was a full-combo with no breaks or sliderbreaks. I'm unsure if this replay is broken due to a rendering issue (aka, it's unfixable) or if it is just broken in playback and can be fixed in a patch or not (such as #12665 )

> Not sure about the rest, because this issue is really confusing to make sense of as to what stats are expected and what stats are wrong.

Ya sorry if this is confusing, but the issue is extremely all over the place. The _expected_ results are a full combo score with a few 100s, and no doubletapping (the replay shows me doubletapping constantly on bursts and stuff, but I definitely didn't do that). In my experience, depending on where I view it, it shows a much lower accuracy than my original score, random misses, or in the case of stable it shows a single sliderbreak at around 700 combo.

The stats screen in the screenshot shown earlier is also confusing, the score seems right (around 1 mill was expected), but the combo and notecounts are way off. It shows a combo of only 749, and the 300s, 100s, and 50s add up to about that as well, but the actual map has around 300 more notes. The actual combo length of the song is around 1010 if I remember right. For some reason the stats screen is missing 300 notes but still shows it as a "perfect" score.

**Comment by integerrr** [comment] 2021-05-13 11:55
was this score set in lazer or stable, if this is set in lazer then did you play this with the classic mod on?

**Comment by PIECEofTOAST1** [comment] 2021-05-13 16:41
> was this score set in lazer or stable, if this is set in lazer then did you play this with the classic mod on?

Set in lazer, I had HD mod but other than that it was vanilla.

**Comment by integerrr** [comment] 2021-05-13 16:53
The combo break @bdach and I saw at around 651x was probably caused by the classic mod added by the game when we imported the replay, which changes the judgements. with 2021.514.0 coming out please check if the issue you mentioned (doubletapping) still exists. If the issue goes away then it's a duplicate of #12651 

As for the second "issue" you pointed out in the comment, the slider ends don't give combo currently, so the 261 combo "missing" is correct behaviour: 749 + 261 = 1010

![osu_2021-05-13_17-51-59](https://user-images.githubusercontent.com/7279624/118158625-f0aa4100-b413-11eb-8a86-60242f4c3489.png)

**Comment by PIECEofTOAST1** [comment] 2021-05-13 17:17
apologies for the sliderend thing, didn't realize that was a mechanic. 

Just to be clear though, I was noticing missed notes before I imported the replay. When I watched the replay back it showed about 5 or so misses directly after i made the play (didn't import anything). So I'm not sure if the issue stems from the classic mod thing you were talking about. Unfortunately, when I tested to make sure the replay file I linked worked it overwrote my previous replay. I guess they shared the same metadata or something. So now I just see what you guys see. 

Because a patch is coming though I will just keep an eye out after that drops. If I see anything again then I'll report it, otherwise we'll be all good.

**Comment by frenzibyte** [comment] 2021-05-14 04:50
@PIECEofTOAST1 The release is out, please check.

**Comment by integerrr** [comment] 2021-05-14 10:27
@frenzibyte how do I programmatically remove classic mod on the replay and check it myself, it seems like he overwrote his original replay (which was without classic mod) with the imported one

**Comment by frenzibyte** [comment] 2021-05-14 10:36
well, if you can compile yourself you can just comment over the implementation in the mod class itself and make it cause no effect:
```diff
diff --git a/osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs b/osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
index 77dea5b0dc..8c5a6f7393 100644
--- a/osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
+++ b/osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
@@ -34,45 +34,45 @@ public class OsuModClassic : ModClassic, IApplicableToHitObject, IApplicableToDr

         public void ApplyToHitObject(HitObject hitObject)
         {
-            switch (hitObject)
-            {
-                case Slider slider:
-                    slider.OnlyJudgeNestedObjects = !NoSliderHeadAccuracy.Value;
-
-                    foreach (var head in slider.NestedHitObjects.OfType<SliderHeadCircle>())
-                        head.JudgeAsNormalHitCircle = !NoSliderHeadAccuracy.Value;
-
-                    break;
-            }
+        //     switch (hitObject)
+        //     {
+        //         case Slider slider:
+        //             slider.OnlyJudgeNestedObjects = !NoSliderHeadAccuracy.Value;
+        //
+        //             foreach (var head in slider.NestedHitObjects.OfType<SliderHeadCircle>())
+        //                 head.JudgeAsNormalHitCircle = !NoSliderHeadAccuracy.Value;
+        //
+        //             break;
+        //     }
         }

         public void ApplyToDrawableRuleset(DrawableRuleset<OsuHitObject> drawableRuleset)
         {
-            var osuRuleset = (DrawableOsuRuleset)drawableRuleset;
-
-            if (ClassicNoteLock.Value)
-                osuRuleset.Playfield.HitPolicy = new ObjectOrderedHitPolicy();
+        //     var osuRuleset = (DrawableOsuRuleset)drawableRuleset;
+        //
+        //     if (ClassicNoteLock.Value)
+        //         osuRuleset.Playfield.HitPolicy = new ObjectOrderedHitPolicy();
         }

         public void ApplyToDrawableHitObjects(IEnumerable<DrawableHitObject> drawables)
         {
-            foreach (var obj in drawables)
-            {
-                switch (obj)
-                {
-                    case DrawableSlider slider:
-                        slider.Ball.InputTracksVisualSize = !FixedFollowCircleHitArea.Value;
-                        break;
-
-                    case DrawableSliderHead head:
-                        head.TrackFollowCircle = !NoSliderHeadMovement.Value;
-                        break;
-
-                    case DrawableSliderTail tail:
-                        tail.SamplePlaysOnlyOnHit = !AlwaysPlayTailSample.Value;
-                        break;
-                }
-            }
+        //     foreach (var obj in drawables)
+        //     {
+        //         switch (obj)
+        //         {
+        //             case DrawableSlider slider:
+        //                 slider.Ball.InputTracksVisualSize = !FixedFollowCircleHitArea.Value;
+        //                 break;
+        //
+        //             case DrawableSliderHead head:
+        //                 head.TrackFollowCircle = !NoSliderHeadMovement.Value;
+        //                 break;
+        //
+        //             case DrawableSliderTail tail:
+        //                 tail.SamplePlaysOnlyOnHit = !AlwaysPlayTailSample.Value;
+        //                 break;
+        //         }
+        //     }
         }
     }
 }
```

**Comment by integerrr** [comment] 2021-05-14 11:28
https://youtu.be/eP8oHyuDNNQ
I counted 1 more 100 than there should be, acc and score is very slightly off, I guess this is good enough to close as duplicate?

**Comment by PIECEofTOAST1** [comment] 2021-05-14 16:21
Because I overwrote my original play with the imported (classic) play I unfortunately no longer have any more info than you guys do. I will post another thread if the issue shows itself again.

I just tested the replay before and after installing the update though, and there was definitely a SIGNIFICANT improvement, mostly in that the "doubletapping" issue is gone. There's still the mysterious break that wasn't in the original play, but we can probably just chock that up to shenanigans with the classic mod being used on a non-classic replay. 

This thread can probably be closed, unless you guys have something else you want to dig into. Because I don't have the original replay, and the update changed a lot of stuff, I don't think this is a good issue to be wasting time on. I'll post again if it shows up in the future.

**Comment by bdach** [comment] 2021-05-14 18:16
Checked the attached replay with classic mod manually disabled and got a 749x full combo in result. Closing as resolved - although it is a bit of a shame that exporting lazer replays and importing them back in is a lossy operation, but there is an agreement that we don't want to be touching legacy file formats if it can be avoided
...

**Closed by bdach** 2021-05-14 18:16 UTC
Labels: area:replay
