### ISSUE TITLE
Ability to display all beatmaps regardless of mode (osu!standard, osu!taiko, osu!mania, osu!catch)

### ISSUE THREAD

**Issue by Exaskliri** [ppy/osu#9680] opened 2020-07-26 04:58 UTC
I'd like to see an additional osu!mode on toolbar that allows you to display all beatmaps regardless of mode (convert maps won't be displayed).

**Comment by frenzibyte** [comment] 2020-07-26 05:00
Duplicate of https://github.com/ppy/osu/issues/6500, please search for existing issues before opening a duplicate like this.

**Closed** 2020-07-26 05:01 UTC
