### ISSUE TITLE
Shaped screen adaptation

### ISSUE THREAD

**Issue by NightmareDreemurr** [ppy/osu#11630] opened 2021-01-30 17:30 UTC
_**(improper grammer warning)**_
**Describe the new feature:** 
So now there has been lots of phones shaped screens on the market and lots of games have already adapted to this situation.
May you guys do something to make osu adapted to shaped screens?

e.g.
My phone is equipped with a 
3200*1440 120hz screen like this
![Screenshot_2021-01-31-01-15-04-563_com.xiaomi.shop.jpg](https://user-images.githubusercontent.com/59122229/106363197-1aa68e80-6362-11eb-82b2-eb384c8bb7f0.jpg)
and this is how it looks when running osu!lazer
![Screenshot_2021-01-31-00-35-01-676_sh.ppy.osulazer.jpg](https://user-images.githubusercontent.com/59122229/106363122-8f2cfd80-6361-11eb-8241-cd73d70cfae3.jpg)

**Proposal designs of the feature:** 
I think first the bezel on the left should be adapted like this

**1.**
Try to let the program itself fill the whole screen

**2.**
Write a feature that allows players to set a "safe area"(Something like minecraft did that allows players to scale their ui but maybe in osu we can change it vertically and horizontally separately)
**_*(I know that now there is a feature that can allow us scale everything but it's just literally useless)_**

**3.**(maybe)
Detect which kind of screen (or which phone model) the player is using and apply a default margin to the player's phone

Thanks for all you guys from osu!team for your hard work!
Hope osu!lazer will soon get into stable deployment!

**Comment by jai-x** [comment] 2021-01-30 17:35
Duplicate of https://github.com/ppy/osu/issues/4330 I think.

**Closed** 2021-01-30 17:35 UTC

**Comment by NightmareDreemurr** [comment] 2021-01-30 17:36
> Duplicate of https://github.com/ppy/osu/issues/4330 I think.

It is not a duplicate
pls read carefully!

**Comment by NightmareDreemurr** [comment] 2021-01-30 17:38
> Duplicate of https://github.com/ppy/osu/issues/4330 I think.

Thanks for referring this issue to the main one
Hope it'll get fixed soon ^ ^

**Comment by peppy** [comment] 2021-01-31 04:03
As an aside, you can already manually customise the screen area. From settings, turn on "screen scaling" and set to "everything"

![image](https://user-images.githubusercontent.com/191335/106374260-b49f2300-63c4-11eb-86a1-512dd7dc7cd1.png)

**Comment by NightmareDreemurr** [comment] 2021-01-31 04:24
> As an aside, you can already manually customize the screen area. From settings, turn on "screen scaling" and set it to "everything"
> 
> ![image](https://user-images.githubusercontent.com/191335/106374260-b49f2300-63c4-11eb-86a1-512dd7dc7cd1.png)

I have tried that option sometime before but that doesn't work
When I scaled it to maximum, still can't fit the whole screen
![8}N5_MC_}KG1{3H$V{CL$Z5](https://user-images.githubusercontent.com/59122229/106374283-bb299c80-63bc-11eb-8a54-4fe0b07ea263.jpg)
The main idea of this issue is to tell you guys that maybe you should try to **_adapt the special size of shaped screen_** and I definitely know that not many users use such a long screen as mine did 
As I've shown before, my android phone's screen has a punch hole and I think the trend of the shaped screen isn't going down 
iOS's Shaped screen had already been fixed as #4330 said and I watched a few osu!lazer videos using iOS and Android
such as
[iOS](https://www.youtube.com/watch?v=_8n3AFw-Dwc)
[Android](https://www.youtube.com/watch?v=A5sHDlk7gEw)
Both of them are probably fixed but IDK why mine isn't working well

Maybe that is a bug?

My device's info
Screen: 3200 * 1400, 20:9 Screen with a punched hole on the top-left corner
Processor: Qualcomm Snapdragon 888
Android version: 11

**Comment by peppy** [comment] 2021-01-31 04:33
I'm locking this thread, I did not intend to trigger further discussion. I was just giving you a 100% work around. Take it or leave it.

**Comment by Joehuu** [comment] 2021-02-01 05:17
The window needs to be rendered to the cutout area in the first place for the workaround to be relevant.

Described in https://developer.android.com/guide/topics/display-cutout#choose_how_your_app_handles_cutout_areas, we need to add a short edges flag in game or framework side to be in line with iOS.

I could add the flag, but maybe best to wait until the UI-side is done to avoid "can't press this" instead of "screen is not rendered fully" issues like this one?

**Comment by peppy** [comment] 2021-02-01 05:38
I think it's fine to add this flag, I didn't' realise we weren't using the full screen area. May be best to have people complain about things not being perfectly pressable rather than game not taking full screen, I think (at least so iOS and android are at parity).
