### ISSUE TITLE
Beatmap skin uses classic skin instead of current skin for missing elements

### ISSUE THREAD

**Issue by dwarf17342** [ppy/osu#24938] opened 2023-09-26 19:56 UTC
### Type

Cosmetic

### Bug description

While the Beatmap skin setting is enabled and the beatmap has custom elements, elements that the beatmap does not assign will default to the classic skin for most elements. This does not affect maps with no beatmap skinning, where every element is skinned, or obviously when the beatmap skin setting is off.
 
Essentially every skinning element except for sliderb, sliderfollowcircle, and the cursor are coming from the default skin instead of current skin. approach circles, numbers, miss/50/100/300's, followpoints, are all definitely affected. This generally looks worse, does not line up with stable, and I think doesn't line up with older versions of lazer (though I may be wrong).

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/105325426/56d4cec1-5aa6-4fa1-9e04-79a00af1e641)
Using argon

![image](https://github.com/ppy/osu/assets/105325426/b4685a00-ff73-480d-bfef-46a98099f3c6)
Very obvious skin to show the differences 
![image](https://github.com/ppy/osu/assets/105325426/b02ab5f3-4cd6-477d-bf36-56d958355ea1)
Same skin in lazer, ignore hitcircle color differences

![image](https://github.com/ppy/osu/assets/105325426/f6d38e78-477a-40a8-a404-da6a4f2d288c)
The beatmap's folder and skinning elements

[Rin Kagamine - Meltdown (xxheroxx) [Hard].txt](https://github.com/ppy/osu/files/12731209/Rin.Kagamine.-.Meltdown.xxheroxx.Hard.txt)
Beatmap's .osu file as a txt, in case format version etc is important

### Version

2023.924.1-lazer

### Logs

[input.log](https://github.com/ppy/osu/files/12731382/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12731383/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12731384/network.log)
[performance.log](https://github.com/ppy/osu/files/12731385/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12731386/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12731387/updater.log)
[database.log](https://github.com/ppy/osu/files/12731388/database.log)

**Comment by peppy** [comment] 2023-09-26 20:08
See https://github.com/ppy/osu/pull/24861 / https://github.com/ppy/osu/issues/24813

Probably duplicate.

**Comment by bdach** [comment] 2023-09-26 20:45
I'm not sure any of the links above are relevant? This is not a storyboard issue, I think. That said I'm not sure what I'm supposed to be looking at in those screenshots specifically either.

@dwarf17342:

- Please link skin and beatmap
- Please describe what the screenshots are. What is the first screenshot? Why is it labeled "argon"? What are you expecting to match exactly? The last screenshot you posted looks to be using the "obvious skin" you mention, mostly, with the exception of combo colours I guess?

**Comment by dwarf17342** [comment] 2023-09-27 02:49
Apologies for being unclear, beatmap was this 2009 version of meltdown on the hard difficulty:
https://osu.ppy.sh/beatmapsets/9070#osu/36636
And the skin used in the second and third screenshots was project voez optimized:
here on the forms https://osu.ppy.sh/community/forums/topics/471776?n=1
or here for a direct download link https://drive.google.com/uc?export=download&id=1FKPdVuoMiiUVBFzoIt-u_ltW1Y1-sL7t

Okay, the first screenshot shows the argon pro skin being used, with the intent to show that 300's are being rendered like they would in the classic default skin. There are other elements of the classic default skin but they are difficult to see.  A slight mistake on my part was not including the slider, it is using the argon skin and not the classic one.
![image](https://github.com/ppy/osu/assets/105325426/79b214a3-a2ea-4539-8567-22bfe901bbbe)

The second screenshot is using the voez skin in osu stable, the skin includes default combo colors but that is actually irreverent to my point. The skinning elements themselves are what i expect to match.

The third screenshot is of the same voez skin but in lazer and once again on the same map. Similar to the argon pro skin 300's are from the classic skin instead of the current skin, voez. A few other skinning elements are also visibly mismatched in the screenshot when compared to the second screenshot, firstly the approach circles which in screenshot 2 have black shading on the outside edge and a blur to the center in the stable screenshot, but are solid color rings in lazer screenshot. Because this is by definition a legacy skin the expected behavior is to use the voez skin for these elements and not the classic skin.

I have also tested this with a second legacy skin and the same behavior as in classic occurs, I'll send screenshots if this becomes relevant.

You are right that that I expect argon to "mix into" a beatmap's legacy elements, that being the elements the beatmap put there should mix with the current skin, hearing this isn't possible is unfortunate but fine*. As you said in your last sentence I expect the skin to fall back to the active legacy skin.

*I felt like I remembered seeing argon mix into another skin, going back to test this for at least some maps this happens, the argon skin mixes just fine with this map as shown in the below screenshot, https://osu.ppy.sh/beatmapsets/1370640#osu/3974458 
![image](https://github.com/ppy/osu/assets/105325426/309de37f-3cd0-42bc-a9a4-d7cf907c767e)
This example isn't that surprising because only a single skin element (the sliderball) was replaced and it's a much later version of the .osu file. I'll probably look for more examples of skins working/ not working tomorrow, for legacy skins, argon and other lazer skins aren't expected to work in the first place.

**Comment by peppy** [comment] 2023-09-27 03:39
> I'm not sure any of the links above are relevant? This is not a storyboard issue, I think.

Right, from the original explanation I couldn't tell what was even being specified as wrong. Will go through the more recent post and see what I find.

**Comment by peppy** [comment] 2023-09-27 08:37
I'll tentatively close this, but feel free to mention any remaining issues that I may have missed. If you can provide isolated test skins (with only the affected elements) that would be appreciated.

**Comment by respektive** [comment] 2024-07-03 16:26
This is something, that has been bugging me for a while. I noticed this on a map today, because the cursor looked completely broken. 
In these videos below you can see that on lazer the game is using the default hitcircle numbers, reverse arrows, and hitsounds instead of the skins. Possibly also the default cursormiddle file which makes the cursor look broken?

https://github.com/ppy/osu/assets/22381687/a2064cd7-b4ce-426a-a00d-2c31661a089a

https://github.com/ppy/osu/assets/22381687/3af0310a-28e2-4dc4-988f-eb241b35de8a

I made a test skin with just the elements I noticed being wrong (rename to .osk): [Lazer_Test.zip](https://github.com/user-attachments/files/16087862/Lazer_Test.zip)
beatmap from the videos: https://osu.ppy.sh/beatmapsets/31506#osu/103832

**Comment by peppy** [comment] 2024-07-04 10:30
I'll bite and look into this briefly, but here's some thoughts:

The issue is caused by this line from https://github.com/ppy/osu/pull/20725:

https://github.com/ppy/osu/blob/7bc8908ca9c026fed1d831eb6e58df7624a8d614/osu.Game/Skinning/BeatmapSkinProvidingContainer.cs#L102

This includes the classic default skin before the user skin, with the goal of falling back to classic resources rather than using argon/triangles.

Where it seems to be failing is that by inserting the classic default, it hides most of the user skin completely. I have a fix in the works.

**Closed** 2024-07-05 03:05 UTC
Labels: area:skinning
