### ISSUE TITLE
Song Select keeps returning to currently selected map after releasing right click

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#25824] opened 2023-12-18 08:33 UTC
### Type

Game behaviour

### Bug description

Song Select keeps returning back to the map it was currently on after I release right click which wasn't an issue before, a large stutter happens as well which wasn't as bad but still prevalent on 2023.1130.0.

### Screenshots or videos

https://github.com/ppy/osu/assets/58333920/4bec3164-6b9b-4aab-8c40-ee28afd9e697

### Version

2023.1218.0

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/13701299/shorter_runtime.log)
[shorter_performance.log](https://github.com/ppy/osu/files/13701300/shorter_performance.log)

**Comment by Stoppedpuma** [comment] 2023-12-18 08:41
Left clicking on difficulty to play no longer works either

**Comment by peppy** [comment] 2023-12-18 08:46
Can't reproduce this. To start, can you try restarting your PC? Your global input may be in a weird state. Also check if you have any external input devices that might be doing something weird.

**Comment by peppy** [comment] 2023-12-18 08:53
Okay from your runtime logs it looks like the game is background processing all your beatmaps. Things should get better once this completes.

I'll look if we can easily show progress of this in a notification.

**Comment by Speed-sters** [comment] 2023-12-18 09:04
I had the the same thing happening to me for a bit, almost like it thought my cursor was over the leaderboards constantly while right click scrolling. But after a bit it seemed to have gone away and I couldn't reproduce anymore.

Looked at my logs and it does seem to be an issue when processing maps.

**Comment by peppy** [comment] 2023-12-19 04:08
This is fixed by https://github.com/ppy/osu/pull/25833 (in the last hotfix release)!

**Closed by peppy** 2023-12-19 04:08 UTC
Labels: area:song-select, priority:1
