### ISSUE TITLE
Lazer Tourney won't open after json file is added

### ISSUE THREAD

**Issue by Penguinosity** [ppy/osu#7199] opened 2019-12-14 03:13 UTC
If a json file is created by creating brackets or adding maps etc, the lazer tourney will no longer be able to be opened. If I add a json file into the roaming > osu folder manually, it will not open. However, the file being created doesn't crash the client if it was created while already open. It's just that the moment I try to open after having closed it, the tournament client will no longer be able to open. The file being deleted makes it usable again, but it's pretty much a lost cause if every time I open I need to create everything from scratch.

**Comment by mcendu** [comment] 2019-12-14 03:54
Dupe of #7197?

**Closed** 2019-12-14 04:55 UTC
