### ISSUE TITLE
Lazer throws an error/crashes when (un)selecting mods

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3261] opened 2018-08-20 15:10 UTC
If a map has been loaded in once, selecting any mod afterwards throws an error and sometimes even crashes the game.
Video: https://streamable.com/6qbfa (the black screen at the end is a crash)

**Comment by Morilli** [comment] 2018-08-20 15:11
Seems like the same underlying issue as #3260 yet with a slightly different outcome.

**Comment by peppy** [comment] 2018-08-20 15:13
Is a result of player being in a disposed but non-finalised state. `Ruleset.ValueChanged` is still firing in the background.

**Comment by peppy** [comment] 2018-08-20 15:13
Duplicate of #3260.

**Closed by peppy** 2018-08-20 15:13 UTC
