### ISSUE TITLE
Cursor gets stuck when alt-tabbing or pressing the windows key

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#12249] opened 2021-04-01 04:52 UTC
**Describe the bug:** 

This only happens with fullscreen mode and high precision mouse turned on, and it didn't happen before the latest release.

I can move the in-game cursor with my tablet while the regular cursor remains stuck. The black parts of the video (gonna call it "gap period" when I refer to it) are due to OBS when I alt-tab or press the windows key.

When alt-tabbing, I can move the cursor fine during this gap period (although OBS isn't the cause here) until it gets stuck as seen on video. When pressing the windows key, the cursor gets stuck immediately. When tapping the pen on something that isn't lazer and in a few other cases, I can regain control somewhat temporarily. Tapping the pen on lazer puts it in focus and things are back to normal.

I had another tablet driver running while recording. Even with it disabled the behaviour is basically the same.

When alt-tabbing and moving the cursor to another monitor, the cursor disappears after the gap period.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/36758269/113243297-0b38b880-92b3-11eb-883f-22d66b902907.mp4

**osu!lazer version:** 

Latest release: 2021.331.0

**Logs:**

N/A

**Comment by peppy** [comment] 2021-04-01 04:54
Duplicate of one of https://github.com/ppy/osu/issues/12228 or https://github.com/ppy/osu/issues/12188 or https://github.com/ppy/osu/issues/12169. Please search first.

**Closed by peppy** 2021-04-01 04:54 UTC

**Comment by Walavouchey** [comment] 2021-04-01 04:59
I found it hard to tell if those were related, but alright.
