### ISSUE TITLE
Player loader may not give enough time to change settings

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#5609] opened 2019-08-05 16:10 UTC
**Describe the bug:** beatmap loads that fast that you don't even have a chance to edit settings

**Screenshots or videos showing encountered issue:** 
[2019-08-05 18-01-11.flv.zip](https://github.com/ppy/osu/files/3468449/2019-08-05.18-01-11.flv.zip)
delete .zip from filename

**osu!lazer version:**  2019.730.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3468453/database.log)
[network.log](https://github.com/ppy/osu/files/3468455/network.log)
[performance.log](https://github.com/ppy/osu/files/3468456/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3468457/runtime.log)

**Comment by HoLLy-HaCKeR** [comment] 2019-08-05 16:19
You can upload videos to streamable.com, so it's easier to view: https://streamable.com/i39eu
(note: lag is also present in original video)

**Comment by peppy** [comment] 2019-08-05 22:11
The beatmap should not continue loading if you are editing settings

**Comment by iiSaLMaN** [comment] 2019-09-28 13:45
The loader should let you edit settings just fine (since `PlayerLoader.IsHovered` is false when a focused overlay is opened, the actual problem here is that the idle tracker cannot receive any events when an overlay is focused, and therefore the loader pushes the player even when you edit settings

Solutions for this are:
1. Add an `IdleTrackerManager` component that adds idle trackers to `OsuGame` (to allow all events being fired).
2. Add the loader idle tracker directly to the game `OsuGame.Add(new IdleTracker(750))`.

**Comment by iiSaLMaN** [comment] 2019-09-28 15:08
Another idea popped up in my head which seems the best, which is resolving the game and creating a events receptor component that would receive all inputs.

**Comment by ticotaco72** [comment] 2019-09-29 12:48
That isn't a problem I'm telling about. It's too short time to get cursor to move to settings.

**Comment by Malavolence** [comment] 2019-09-29 13:04
This could either be fixed by copying over the code that was used in the Hold-to-confirm activation time or your CPU, RAM and Storage Device is just too fast.

**Comment by iiSaLMaN** [comment] 2019-09-29 13:16
> That isn't a problem I'm telling about. It's too short time to get cursor to move to settings.

Moving the cursor delaying the idle tracker 1 second, so if you stay for 1 second not moving the cursor or pressing any keys, you would be considered idle and it will load the player. we can make that a bit longer or add it as a setting (which I doubt would happen).

> This could either be fixed by copying over the code that was used in the Hold-to-confirm activation time or your CPU, RAM and Storage Device is just too fast.

huh?

**Comment by Malavolence** [comment] 2019-09-29 13:35
in a recent update you guys implemented a slider to change the time you need to hold Esc for to close pause. you could copy that code over to that problem.

> huh?

I suspect the problem for the fast load times are a fast SSD.

**Comment by LanTenDragon** [comment] 2019-09-29 13:46
>I suspect the problem for the fast load times are a fast SSD.

Anacedote : I am using a PCIe/NVMe SSD, and have the beatmap folder on my SSD, yet I have not encountered this problem at all.

Here's my theory: 

Look at the FPS of the video, due to low FPS, the settings overlay was late to load, but the (idle tracker?) kept running and proceeded to the playfield as intended.

**Comment by iiSaLMaN** [comment] 2019-09-29 15:17
> > I suspect the problem for the fast load times are a fast SSD.
> 
> Anecdote : I am using a PCIe/NVMe SSD, and have the beatmap folder on my SSD, yet I have not encountered this problem at all.
> 
> Here's my theory:
> 
> Look at the FPS of the video, due to low FPS, the settings overlay was late to load, but the (idle tracker?) kept running and proceeded to the playfield as intended.

This is just because the idle tracker doesn't recieve input on overlays and therefore it thinks the player is in idle mode and can load the player.

**Comment by iiSaLMaN** [comment] 2020-02-15 02:22
Can be closed as solved in #7836

**Closed** 2020-02-15 03:23 UTC
Labels: area:gameplay, type:UX
