### ISSUE TITLE
PNG-based textures aren't visible 

### ISSUE THREAD

**Issue by EzzPrograms** [ppy/osu#11165] opened 2020-12-13 18:52 UTC
**Describe the bug:** 
PNG-based textures aren’t loaded in with the newest releases of osu!lazer when compiled for iOS. This was tested for versions from 2020.1203.0 up until latest master code.
The tau and sentakki logo + slide stars and chevrons from sentakki aren’t visible, with the latter one affecting gameplay.

These are the mentioned png-based textures: [sentakki](https://github.com/LumpBloom7/sentakki/tree/master/osu.Game.Rulesets.Sentakki/Resources/Textures) and [tau](https://github.com/Altenhh/tau/tree/master/osu.Game.Rulesets.Tau/Resources/Textures)

**Screenshots or videos showing encountered issue:** 
![Sentakki logo and tau paddle in logo missing.](https://user-images.githubusercontent.com/22746909/102020227-b3814a80-3db2-11eb-813a-0323ce02f60a.png)
[sentakki gameplay showing the missing slide stars and chevrons](https://youtu.be/XHTyfDxBp8w)
[sentakki gameplay with the slide stars and chevrons](https://youtu.be/VBWZqbnJaMw)

osu!lazer version: 2020.1203.0 to latest master

**Logs:**

Grabbed while investigating missing tau logo:
[runtime.log](https://github.com/ppy/osu/files/5685167/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5685168/performance.log)
[network.log](https://github.com/ppy/osu/files/5685169/network.log)
[database.log](https://github.com/ppy/osu/files/5685170/database.log)

**Comment by peppy** [comment] 2020-12-14 01:12
From logs:

```
2020-12-13 17:33:17 [error]: Texture could not be loaded via STB; falling back to ImageSharp.
2020-12-13 17:33:17 [error]: System.DllNotFoundException: stbi
2020-12-13 17:33:17 [error]: at StbiSharp.Stbi.LoadFromMemory (System.ReadOnlySpan`1[T] data, System.Int32 desiredNumChannels) [0x00011] in <3a3a8eb18047418fa91bf60ed337b5dd>:0
2020-12-13 17:33:17 [error]: at StbiSharp.Stbi.LoadFromMemory (System.IO.MemoryStream data, System.Int32 desiredNumChannels) [0x0000b] in <3a3a8eb18047418fa91bf60ed337b5dd>:0
2020-12-13 17:33:17 [error]: at osu.Framework.Graphics.Textures.TextureUpload.LoadFromStream[TPixel] (System.IO.Stream stream) [0x00022] in C:\projects\osu-framework-a4n7e\osu.Framework\Graphics\Textures\TextureUpload.cs:91
```

While this is a definite issue (STBi somehow no longer being found) it is also clear that some PNGs can be loaded (see the osu! logo, for instance). Can you attach the PNG in question? It may be something specific to your PNG encoding.

**Comment by smoogipoo** [comment] 2020-12-14 01:58
> STBi somehow no longer being found

STBI is not compatible/not compiled for mobile platforms, so that's expected.

**Comment by peppy** [comment] 2020-12-14 02:00
The underlying library is, since we did benchmark it on iOS. Seems like an oversight that we're not bundling binaries yet (I think it was considered low priority as the game host implementations already do some form of native loading).

**Comment by EzzPrograms** [comment] 2020-12-14 02:38
> While this is a definite issue (STBi somehow no longer being found) it is also clear that some PNGs can be loaded (see the osu! logo, for instance). Can you attach the PNG in question? It may be something specific to your PNG encoding.

These should be all of the PNGs:
[tau logo](https://user-images.githubusercontent.com/22746909/102034116-2c56c580-3df8-11eb-8528-b11df6aa88c2.png)
[Sentakki logo](https://user-images.githubusercontent.com/22746909/102034122-31b41000-3df8-11eb-9ea9-5b21fce43dbf.png)
[Sentakki Slide Star](https://user-images.githubusercontent.com/22746909/102034125-34166a00-3df8-11eb-9084-348e4b3c58f7.png)
[Sentakki Slide Chevron](https://user-images.githubusercontent.com/22746909/102034130-37115a80-3df8-11eb-8ec0-818ac483a864.png)
[Sentakki Touch Note](https://user-images.githubusercontent.com/22746909/102034131-3973b480-3df8-11eb-82a7-9ea4dcd461bc.png)
[Sentakki HitObjectLine](https://user-images.githubusercontent.com/22746909/102034138-3c6ea500-3df8-11eb-9129-057fb283d4d4.png)

**Comment by peppy** [comment] 2020-12-14 02:51
Try this one instead?

![102034130-37115a80-3df8-11eb-8ec0-818ac483a864](https://user-images.githubusercontent.com/191335/102034963-a12efd00-3e02-11eb-89e5-255299229fb7.png)

I'm guessing it has something to do with the embedded colour profile in the images, so I've removed this.

**Comment by EzzPrograms** [comment] 2020-12-14 07:19
> Try this one instead?
> I'm guessing it has something to do with the embedded colour profile in the images, so I've removed this.

Tried the images, but the issue still persists.
![IMG_0062](https://user-images.githubusercontent.com/22746909/102051576-be25f900-3e1f-11eb-8142-a74e1852e245.PNG)

**Comment by peppy** [comment] 2020-12-14 07:24
Going to require some further investigation. Some possibilities are:

- resources aren't being read correctly
- apple or xamarin have changed the way `pngcrush` needs to be applied (unlikely)
- *something else* in your PNGs (or your iOS build process) is not making the new version of i# happy

I'd recommend as a next step, you copy one of the PNGs from `osu-resources` and see if it loads correctly. If not, it's likely not related to the PNG files at all.

**Comment by EzzPrograms** [comment] 2020-12-14 08:17
Was trying to reproduce the issue by changing the tau logo to [this](https://raw.githubusercontent.com/ppy/osu-framework/master/osu.Framework.Templates/templates/template-empty/TemplateGame.Resources/Textures/logo.png)

It did not load the osu!framework logo too. So, probably the PNGs aren't the main source of the problem then.

**Comment by LumpBloom7** [comment] 2020-12-14 08:36
The audio samples are packed and loaded correctly, as shown in [this video](https://streamable.com/uqirvl) of Ezz testing things, showing that the resource glob in the csproj file is somewhat working. (The sparkly samples is custom, and the invisible notes are what used to be the slide star)

I don't think I have changed any resources in the past week, and I believe that Ezz's iOS build process haven't changed either.

**Comment by EzzPrograms** [comment] 2020-12-18 09:04
Took a look at ppy/osu-framework and saw that the PNG decoder configuration is in a try statement, but nothing is logged if it actually is caught in an exception. Could this be why we haven't seen anything about ImageSharp errors in the log?

Code:
https://github.com/ppy/osu-framework/blob/105a17bc99cad251fa730b54c615d2b0d9a409d3/osu.Framework.iOS/GameAppDelegate.cs#L50-L62

**Comment by bdach** [comment] 2020-12-18 09:35
probably? that's kind of obvious and not too helpful to say, though. i'd debug it myself but own no hardware.

**Comment by EzzPrograms** [comment] 2020-12-18 10:16
After building the framework with the exception logging, it seems that the PNG Decoder did threw errors.
I've attached the particular log section [here](https://pastebin.com/ddmZVjM3).

**Comment by bdach** [comment] 2020-12-18 10:20
judging from the excerpt attached, looks like we might need to take this upstream to imagesharp. can't imagine that stack trace could be caused by misuse on our side...

**Comment by bdach** [comment] 2020-12-18 10:25
upon re-checking this trace, you're not even looking at the right error. the one you found isn't even attempting to decode the actual ruleset logos.

**Comment by EzzPrograms** [comment] 2020-12-19 03:31
I've tried recompiling back with the rulesets that have the missing PNGs and I've put an exception catch in my local build of osu!framework [here](https://github.com/ppy/osu-framework/blob/4e0180366c3c800fc45998b0877ce8f01be918f3/osu.Framework/Graphics/Textures/TextureLoaderStore.cs#L27-L42) since the image used in the ruleset fails here.

After putting the exception logging again, it seems like it's trying to JIT compile an ImageSharp function in an AOT-only environment.
[Here](https://pastebin.com/q7pUB5Qc) is the log snippet that shows that error. It only happens to the ruleset based assets.

**Comment by EzzPrograms** [comment] 2020-12-19 08:41
Putting breakpoints in the code show that a successfully loaded PNG (osu! logo) and a failed to load PNG (sentakki logo) went through different parts of the code, one going through IOSTextureLoaderStore (osu!) and the other one going through TextureUpload (sentakki)

Here's the recording of both the situations:
[osu! Logo](https://user-images.githubusercontent.com/22746909/102685052-aa600580-4218-11eb-9862-e56e8646f450.mp4)
[sentakki Logo](https://user-images.githubusercontent.com/22746909/102685065-b4820400-4218-11eb-89db-688f8324ef3b.mp4)

**Comment by peppy** [comment] 2020-12-21 03:31
The difference in code path there is because you're not using the correct way of retrieving a texture store. You should be using `host.CreateTextureLoaderStore` to benefit from mobile native load paths.

**Comment by peppy** [comment] 2020-12-21 04:40
I've updated the ruleset level `TextureStore` to correctly initialise with the host specification (see #11222). This should help you if you are able to use it (is there a reason you aren't in the `CreateIcon` implementation in your videos?).

**Comment by EzzPrograms** [comment] 2020-12-21 06:16
The sentakki Logo video actually starts in the `CreateIcon` method actually, if I'm understanding that question correctly.
![image](https://user-images.githubusercontent.com/22746909/102745478-05b80200-4397-11eb-8e33-a9d8b48751c3.png)

**Comment by peppy** [comment] 2020-12-21 06:17
i have no idea what you're talking about.

i'm saying you should be using `Textures` provided by the ruleset, rather than creating your own texture store.

**Comment by EzzPrograms** [comment] 2020-12-21 06:26
That's the code that Bloom put in his sentakki ruleset, so I might probably need to ask him why.

[This one](https://github.com/LumpBloom7/sentakki/blob/4d5945892b5d104abc21cead557b1cb5366d874d/osu.Game.Rulesets.Sentakki/SentakkiRuleset.cs#L152) should be the original code before I separated the code for debugging purposes.

**Comment by peppy** [comment] 2020-12-21 06:38
again. don't create your own texture store.

i'm closing this issue for now. please open one framework side if you're interested in seeing the i# part fixed.

**Closed by peppy** 2020-12-21 06:38 UTC
Labels: framework-fix-required, platform:iOS
