### ISSUE TITLE
Problem with Russian keyboard in text fields

### ISSUE THREAD

**Issue by kebabmamedov** [ppy/osu#5827] opened 2019-08-25 01:24 UTC
**Describe the bug:** 
I have Russian letters on my keyboard. When I type Russian letters in any text field I can't see what I did typed. If I unfocus/focus on osu!lazer and typing few English letters I can see weird symbols instead of Russian ones. 

**Screenshots or videos showing encountered issue:** 
I've typed: abc xyz абв эюя
![image](https://user-images.githubusercontent.com/14090079/63644327-68d84c80-c6ef-11e9-95d9-d7e3bde8d781.png)

**osu!lazer version:**
2019.823.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/3537742/runtime.log)

**Comment by bdach** [comment] 2019-08-25 07:57
The part where characters don't appear seems to be a duplicate of ppy/osu-framework#1965. If you press a non-Russian character key after a Russian one (like spacebar), do they both appear at the same time? If yes, then this is the same issue.

The part with the character mangling seems to be code page confusion; Russian layouts seem to be using the [Windows-1251](https://en.wikipedia.org/wiki/Windows-1251) code page. The key codes that osuTK returns when handling input from the regional keyboard correspond to that code page, i.e. when the user presses `э`, the keycode `0xFD` is emitted, which is then later reinterpreted to Unicode, wherein that code corresponds to the Latin extended character `ý`. This is probably an issue to be resolved within osuTK itself.

**Comment by peppy** [comment] 2019-08-27 05:36
Likely all going to root back to the opentk keyboard layout issues, which still need to be addressed (probably by switching to a better library): https://github.com/ppy/osu-framework/issues/252

**Comment by TicClick** [comment] 2021-06-14 21:53
seems to be fixed (in https://github.com/ppy/osu-framework/issues/252 or so, I guess)

**Comment by bdach** [comment] 2021-06-14 21:55
Yeah, this should have been closed after the switch to SDL. The part with <kbd>AltGr</kbd> is already tracked elsewhere, as already stated above, so closing this.

**Closed by bdach** 2021-06-14 21:55 UTC
Labels: framework-fix-required, type:input
