### ISSUE TITLE
Mania "No Release mod" cause hit visual to repeat with certain skins.

### ISSUE THREAD

**Issue by SolosHub** [ppy/osu#28925] opened 2024-07-18 18:13 UTC
### Type

Cosmetic

### Bug description

When using a DDR style skin original designed for OSU stable this bug would occur. I would hold a hold note after it has finished but my arrow would continue to flash. The "No Release mod" has to be  active and I have to use the Galvit DDR skin.

### Screenshots or videos

https://github.com/user-attachments/assets/f58bd5f8-db5b-48b3-a605-22d814a1f60a

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16287278/compressed-logs.zip)

**Comment by SupDos** [comment] 2024-07-18 18:23
Duplicate of https://github.com/ppy/osu/issues/28901, already fixed by https://github.com/ppy/osu/pull/28905

**Closed** 2024-07-18 22:04 UTC
