### ISSUE TITLE
Can't run osu lazer with error 1114

### ISSUE THREAD

**Issue by zeeterv** [ppy/osu#6570] opened 2019-10-22 06:57 UTC
**Describe the crash:LoadLibrary with error 1114: A dynamic linkblibrary (DLL) initialization routine failed** 

**Screenshots or videos showing encountered issue:
![15717271192378286703551338742357](https://user-images.githubusercontent.com/56862783/67263743-28b8fe80-f4d3-11e9-87ac-bad1259b1085.jpg)
** 

**osu!lazer version:2019.1011.0 and newer** 

**Logs:[log.zip](https://github.com/ppy/osu/files/3754175/log.zip)** 

**Computer Specifications: Windows 10 pro 64 bit version 1903**

**Comment by bdach** [comment] 2019-10-22 07:02
Please attach logs from `%AppData%/osu/logs`, if any present, and additionally Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by zeeterv** [comment] 2019-10-22 07:18
> 
> 
> Please attach logs from `%AppData%/osu/logs`, if any present, and additionally Windows Event Viewer info by performing the following steps:
> 
>     1. Type `Event viewer` in the Windows search bar (shortcut: Windows+S) and press Enter, or open the _Run..._ button (Windows+R), type in `eventvwr` and press Enter.
> 
>     2. The _Event viewer_ window will appear. Expand _Windows Logs_ on the left and choose _Application_. It might take a while to load.
> 
>     3. In the _Actions_ pane on the right click _Save All Events As..._, then choose a location to save to.
> 
>     4. On the _Display Information_ popup, select the second option, then the checkbox to show all available languages, then _English (UK)_ (US would also do fine).
> 
>     5. Append the resulting `.evtx` file to this issue.

okay i add it

**Comment by zeeterv** [comment] 2019-10-22 08:05
Added

**Comment by iiSaLMaN** [comment] 2019-10-22 10:55
Can you provide us with your hardware info? also, is your GPU switchable? I had the same problem after the .NET Core 3.0 update in lazer.

Two things I found while trying to find the cause is:
1. This issue happens when running an installed version of osu!lazer or running `osu.Desktop` in VS 2017 (never got that on Rider 2019.2.2, VS 2019 untested)
2. This issue doesn't occur when running osu!lazer test browser or framework on any IDE (including VS 2017), though haven't tested `SampleGame` yet..

**Comment by bdach** [comment] 2019-10-22 19:29
I've looked through the event viewer logs - unfortunately nothing decisive. Only mention of osu! is a Windows Error Reporting `RADAR_PRE_LEAK_64` diagnostic entry, which as far as I can tell from googling doesn't actually mean much.

In light of that, I'd appreciate it if you could also attach DirectX diagnostic info by performing the following steps:

1. Press <kbd>Windows</kbd>+<kbd>R</kbd>, type `dxdiag` in the appearing window and press <kbd>Enter</kbd>.
2. You could be prompted if you'd want Windows to check if the device drivers are signed - there should be no harm in agreeing to that.
3. In the *DirectX Diagnostic Tool* window that will appear, click *Save All Information...* and choose a file to save to.
4. Attach the saved file to this issue.

**Comment by smoogipoo** [comment] 2019-10-23 03:35
Seems like this may be related to switchable graphics in any case. You may be able to right-click on the icon and run with a particular GPU, or you'll need to go into your driver software and make sure osu! is set to use the high performance graphics processor.

Additionally, I'd try reinstalling your graphics drivers.

**Comment by zeeterv** [comment] 2019-10-23 03:59
[DxDiag.txt](https://github.com/ppy/osu/files/3760057/DxDiag.txt)
Added

**Comment by bdach** [comment] 2019-10-23 21:58
The `dxdiag` output above shows just one card, so save for some Windows hiccup I think this is another Intel issue rather than switchable graphics in general. Driver version [seems to be the latest too](https://www.catalog.update.microsoft.com/Search.aspx?q=Intel%20hd%203000). Do releases prior to 2019.1011.0 work?

Sort of at a loss what to do next here without an actual machine I can reproduce/debug on, since this error looks like it's bound to be hairy...

**Comment by iiSaLMaN** [comment] 2019-10-23 22:50
> The dxdiag output above shows just one card, so save for some Windows hiccup I think this is another Intel issue rather than switchable graphics in general.

You may be wrong here, you don't get switchable graphics info by checking `DxDiag` (as I tested and found). a good way would be opening the device manager and checking the display cards.

**Comment by zeeterv** [comment] 2019-10-25 14:54
I'm afraid black screen Like making friends

**Comment by iiSaLMaN** [comment] 2019-11-02 10:36
@zeeterv Can you please inform us if you do have a switchable graphics card or not by doing [what I said above](https://github.com/ppy/osu/issues/6570#issuecomment-545668443)

**Comment by zeeterv** [comment] 2019-11-02 11:19
![image](https://user-images.githubusercontent.com/56862783/68070162-415fc900-fd9d-11e9-95c9-d17e6ad16773.png)

**Comment by zeeterv** [comment] 2019-11-03 05:23
[Detailed-System-Report.zip](https://github.com/ppy/osu/files/3801266/Detailed-System-Report.zip)

**Comment by zeeterv** [comment] 2019-11-03 05:24
![image](https://user-images.githubusercontent.com/56862783/68080788-e7124700-fe34-11e9-94e1-8a0aa8df1fad.png)
![image](https://user-images.githubusercontent.com/56862783/68080790-f0031880-fe34-11e9-82cc-670bc8aff1f7.png)

**Comment by zeeterv** [comment] 2019-11-03 05:26
and why i got this 
![image](https://user-images.githubusercontent.com/56862783/68080797-26409800-fe35-11e9-92ec-a6f46688174b.png)

**Comment by HerendraTJ** [comment] 2019-11-09 03:04
> and why i got this
> ![image](https://user-images.githubusercontent.com/56862783/68080797-26409800-fe35-11e9-92ec-a6f46688174b.png)

For that issue , please contact osu!support and not on github.

**Comment by bdach** [comment] 2019-12-08 16:37
After checking with @iiSaLMaN who owns the appropriate hardware it looks like #7088 might fix this too, since after it being applied the app host starts working again. Doing `dotnet osu!.dll` still doesn't work, but we can't do anything about that without modifying the binary of the `dotnet` host.

Closing and unlocking; if this does turn up again after the next release, please drop a comment and/or reopen.

**Closed by bdach** 2019-12-08 16:37 UTC
Labels: hard crash / startup crash
