### ISSUE TITLE
Add the ability to toggle some mods in replay mode

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#12250] opened 2021-04-01 04:58 UTC
**Describe the new feature:** 
Allow spectator to toggle some mods such as Hidden, FlashLight, Transform... etc when watching a replay

**Proposal designs of the feature:** 
Add a panel below Visual Settings for mods in replay mode

**Comment by peppy** [comment] 2021-04-01 04:59
Duplicate of https://github.com/ppy/osu/issues/8357.

**Closed by peppy** 2021-04-01 04:59 UTC
