### ISSUE TITLE
mouse cursor randomly shows up mid gameplay

### ISSUE THREAD

**Issue by aseotuh** [ppy/osu#28950] opened 2024-07-19 11:21 UTC
### Type

Cosmetic

### Bug description

i recently switched to tablet, and when playing with tablet, the cursor just randomly shows up during gameplay, i have to tab out and back in to fix it, has never happened with mouse, it happens on almost every map i play. 
i am running macos 15 beta 3 (24A5289h), and using opentabletdriver v0.6.4.0 with a ctl 472
it also happens when I click on some things such as my profile

### Screenshots or videos

https://github.com/user-attachments/assets/dd3d60f3-72b6-4c77-9e10-fac222a0f437

### Version

2024.718.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16311180/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-07-19 22:18
Duplicate of https://github.com/ppy/osu/issues/24620

**Closed by Joehuu** 2024-07-19 22:18 UTC
