### ISSUE TITLE
Sometimes crash when fail a map

### ISSUE THREAD

**Issue by BlubBubb** [ppy/osu#17215] opened 2022-03-10 21:00 UTC
Windows 10, PC
Intel core i5 4570, Ram 16 gb DDR3

Reproduction steps : Play a map and then fail the map sometimes it will crash the game

[performance.log](https://github.com/ppy/osu-stable-issues/files/8227115/performance.log)
[performance-audio.log](https://github.com/ppy/osu-stable-issues/files/8227107/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu-stable-issues/files/8227108/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu-stable-issues/files/8227109/performance-input.log)
[performance-update.log](https://github.com/ppy/osu-stable-issues/files/8227110/performance-update.log)
[runtime.log](https://github.com/ppy/osu-stable-issues/files/8227111/runtime.log)
[updater.log](https://github.com/ppy/osu-stable-issues/files/8227112/updater.log)
[database.log](https://github.com/ppy/osu-stable-issues/files/8227113/database.log)
[network.log](https://github.com/ppy/osu-stable-issues/files/8227114/network.log)

**Comment by peppy** [comment] 2022-03-11 08:30
Relevant log portions:

```csharp

2022-03-10 20:34:58 [verbose]: 📺 OsuScreenStack#330(depth:7) entered SoloPlayer#419
2022-03-10 20:35:36 [error]: An unhandled error has occurred.
2022-03-10 20:35:36 [error]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
2022-03-10 20:35:36 [error]: at osu.Framework.Utils.ConvexPolygonClipper`2.Clip(Span`1& buffer)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Sprites.SpriteDrawNode.BlitOpaqueInterior(Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Sprites.SpriteDrawNode.DrawOpaqueInterior(Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.DrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.CompositeDrawableDrawNode.DrawOpaqueInteriorSubTree(DepthValue depthValue, Action`1 vertexAction)

```

```csharp
2022-03-10 20:35:36 [error]: An unhandled error has occurred.
2022-03-10 20:35:36 [error]: NUnit.Framework.AssertionException
2022-03-10 20:35:36 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message)
2022-03-10 20:35:36 [error]: at System.Diagnostics.TraceInternal.Fail(String message)
2022-03-10 20:35:36 [error]: at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(Vector2 size)
2022-03-10 20:35:36 [error]: at osu.Framework.Platform.GameHost.DrawFrame()
2022-03-10 20:35:36 [error]: at osu.Framework.Threading.GameThread.processFrame()
```

Looks like something very low level, super weird.

**Comment by frenzibyte** [comment] 2022-03-12 04:11
It looks like the second exception occurred because of the first seemingly interrupting the entire drawing flow, leaving shaders bound and fail the `shaders_stack.Count == 0` assert next frame in `GLWrapper.Reset`.

**Comment by smoogipoo** [comment] 2022-03-14 08:37
@frenzibyte You're correct that that's the case. I've seen it happen before but didn't investigate, however the fix would be to make the `DrawNode` crash immediately rather than going through the whole process and eventually getting back to a `GLWrapper.Reset()`.

**Comment by nol-and** [comment] 2022-04-16 03:30
Facing similar issue, I'm pretty sure it only happens on maps with videos (from my testing so far)

Running Osu!(lazer)

Windows 11
32GB DDR5 @5200Mhz
Intel i7 12700k @ stock speeds
RTX 3080 Ti
[database.log](https://github.com/ppy/osu/files/8499178/database.log)
[network.log](https://github.com/ppy/osu/files/8499179/network.log)
[performance.log](https://github.com/ppy/osu/files/8499180/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8499181/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8499182/updater.log)

I have experienced this during a normal game sessions but I forced it by turning on auto retry and insta-fail on a map that has a video and leaving it on for about 15 minutes. The freeze occur just as i lose the map, and Osu will be stuck for like 15-30 seconds before just crashing/closing without any error message. 

This is the map in question
https://osu.ppy.sh/beatmapsets/915385#osu/1913574
It has also happened on other maps that has videos.

**Comment by bdach** [comment] 2022-04-16 08:15
@nol-and that is a different issue. please try updating your graphics drivers and disabling shadowplay if you have it enabled.

**Comment by nol-and** [comment] 2022-04-16 15:17
@bdach My computer is newly formatted, and have the newest graphics drivers installed on it. I've also disabled shadowplay, and any overlay or recording software that I can. The only exception is the Xbox Game Bar overlay which Windows 11 won't let me remove, but it shouldn't be recording AFAIK.

Is it possible Xbox Game Bar is the problem? If not, do you know of any ways for me to test further?

**Comment by bdach** [comment] 2022-04-16 15:19
if it *only* happens on maps with videos you could also try disabling hardware video acceleration in settings.

**Comment by nol-and** [comment] 2022-04-16 16:48
I tested on a map without video for a while which did not result in a crash.
I also tried using windowed borderless instead of exclusive fullscreen and did not get crash for either video or nonvideo maps.
Windowed borderless makes it hard for me to play consistently unfortunately. 

If i turn of hardware video acceleration the game occasionally (micro?)stutters which makes it unplayable for me.

Appreciate your help, but will probably play on the normal client for now.

I'm willing to test out other ideas if you have any.

**Comment by smoogipoo** [comment] 2022-05-11 09:54
@Neon095 @BlubBubb Please link your skins.

**Comment by Neon095** [comment] 2022-05-15 10:41
My skin is this one: https://mega.nz/folder/GdN1TYRQ#cqk1gYYbsykIioKeJ5bk5Q/file/iIMzFKZK

**Comment by smoogipoo** [comment] 2022-05-16 07:31
Unfortunately I can't repro this with either of the above skins :( Are either of you able to reproduce this reliably on the same beatmaps/with the same skin?

**Comment by smoogipoo** [comment] 2022-06-01 03:01
Sounds plausible. Also in that last event the crash happened right as Player was entered. From my side I've tried to put the clipper through a bunch of edge cases, and couldn't find anything, but I'll try more.

**Closed** 2022-06-03 05:08 UTC
Labels: framework-fix-required
