### ISSUE TITLE
Crash when trying to remove a timing point

### ISSUE THREAD

**Issue by xteamcrafterx** [ppy/osu#10781] opened 2020-11-10 20:28 UTC
Wanted to try mapping, misplaced an inherited point and try to remove it from an empty map with a timing point. When i tried with a normal, ranked map everything was fine. Tested again by dowloading a song from a featured artist and trying to add and delete a random inherited point, crashed.
**Version**: 2020.1109.0

**Logs:

[logs.zip](https://github.com/ppy/osu/files/5519996/logs.zip)

**Comment by bdach** [comment] 2020-11-10 20:30
Duplicate of #10456

**Closed by bdach** 2020-11-10 20:30 UTC
