### ISSUE TITLE
Duplicate customisation adjustment sliders for Difficulty Adjust mod

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#11920] opened 2021-02-28 00:30 UTC
**Additional info:** not present in other customisable mods 

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7279624/109404179-7c571a00-795b-11eb-85c1-530b93227b4d.mov

**osu!lazer version:** 2020.226.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6055978/database.log)
[network.log](https://github.com/ppy/osu/files/6055979/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/6055980/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6055981/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6055982/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/6055983/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6055985/runtime.log)

**Comment by PercyDan54** [comment] 2021-02-28 00:32
Duplicate of #11905

**Closed** 2021-02-28 00:32 UTC
