### ISSUE TITLE
Osu!lazer can’t play unless you have a keyboard

### ISSUE THREAD

**Issue by alexchiu100014** [ppy/osu#6073] opened 2019-09-11 15:10 UTC
I don’t know why but I can’t play lazer’s any mode(except clicking circles)
How should I play without a keyboard

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.910.0

**Logs:**

**Comment by jai-x** [comment] 2019-09-11 15:38
Please add additional details as you've provided hardly any information for us to work on.

Are you able to start up the game normally? Are you able to type at all? Video of whats going wrong?

Could you also tell us which platform and operating system you are using lazer on?

Can you provide log files? (They can be found by pressing the "Open osu! folder" button in settings)

**Comment by iiSaLMaN** [comment] 2019-09-11 16:16
With this information only, I'm guessing that you're a touch user and want to be able to press buttons by touching, in that case, this is a duplicate of #4201

**Closed** 2019-09-11 16:27 UTC

**Comment by alexchiu100014** [comment] 2019-09-11 18:09
Sorry about missing answers
> Please add additional details as you've provided hardly any information for us to work on.

performance and How to play this game

> Are you able to start up the game normally? Are you able to type at all? Video of whats going wrong?

I can start up the game and I can type in too

> Could you also tell us which platform and operating system you are using lazer on?

ios

> Can you provide log files? (They can be found by pressing the "Open osu! folder" button in settings)

I can’t provide it cause I didn’t find anything of open osu!folder
