### ISSUE TITLE
PP on results screen doesn't match expectations

### ISSUE THREAD

**Issue by Jeglerjeg** [ppy/osu#12542] opened 2021-04-22 21:11 UTC
**Describe the bug:** PP on the results screen is inaccurate due to sliderends not being counted in combo. On stable, an FC with this acc is worth roughly 310pp, while a score with 479 combo is worth 269pp, same as is displayed in the results screen

**Screenshots or videos showing encountered issue:** ![osu_2021-04-22_22-29-51](https://user-images.githubusercontent.com/31293237/115785311-95aa9e80-a3bf-11eb-8cb5-e487eb72edb0.png)

**osu!lazer version:** 2021.416.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6361250/database.log)
[performance.log](https://github.com/ppy/osu/files/6361254/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6361255/runtime.log)
[network.log](https://github.com/ppy/osu/files/6361268/network.log)

**Comment by bdach** [comment] 2021-04-22 21:15
Not entirely sure how to make sense of this report. Was this score achieved on stable, or on lazer? Please link the score/replay also if possible.

**Comment by Jeglet** [comment] 2021-04-22 21:29
The score was achieved on lazer. To try and clarify, the score is a full combo (as can be seen in the screenshot) and as such I'd expect it to be worth the same as a full combo on stable, but it's not. Because sliderends don't add to combo, the pp calculator seems to treat it as not being a full combo


Link to replay: https://cloud.heckin.how/s/pBWLBrJ8CHxai8F
Screenshot of a stable full combo with same acc: ![832-22-max](https://user-images.githubusercontent.com/31293237/115787454-8416c600-a3c2-11eb-963b-73b13e5f10ae.png)

**Comment by TheChurros** [comment] 2021-09-25 23:21
Here to hopefully provide more details and shine more light on this issue. This is a score I set on lazer which is said to be worth 179pp by the in game performance calculator.
![image](https://user-images.githubusercontent.com/42393999/134788031-39f7ee7b-258e-4ca4-8086-a3f739efd883.png)

Here is a similar score set by somebody else on stable, notice how the pp value is much higher despite the fact that they have worse accuracy.
![image](https://user-images.githubusercontent.com/42393999/134788116-62aafafc-bc32-426c-8f06-ce69a1b1b096.png)

What I can assume from this is that the built in performance calculator is being fed 580 combo even though it still thinks the max combo is 761. This is backed up by a 3rd party performance calculator program. When I plug in 580 combo with the same accuracy I had in my score I am given the exact same performance value.
![image](https://user-images.githubusercontent.com/42393999/134788257-f5d22862-bbe6-4b97-b8a7-0dad0f059ed7.png)

**Comment by smoogipoo** [comment] 2021-10-06 03:45
Thanks, but we don't really need more reports / corroborations. It's pretty obvious why this is happening / where the combo differences are coming from.

**Comment by smoogipoo** [comment] 2021-11-22 03:53
Prio-1-ing this as it's pretty important for lazer score submission/ppcalc.

**Comment by memesnightmares** [comment] 2022-05-28 15:48
I could be wrong, but I believe this has been resolved? I was experiencing this issue for a while, but now pp seems much more accurate to stable. The only difference I see now is attributable to scores being better on stable because of a higher acc due to slider acc.

**Comment by bdach** [comment] 2022-05-28 15:53
I believe this should be fixed after https://github.com/ppy/osu/pull/16575, yes.

**Closed by bdach** 2022-05-28 15:53 UTC
Labels: area:scoring, priority:1

**Comment by scatalfo** [comment] 2022-12-27 21:37
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7321680/209724217-211bd71b-5241-4a7d-8ba6-7121c2c88aee.png">
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/7321680/209724392-18e0b5aa-011b-49ab-bd8a-29be087ab6e1.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/7321680/209724534-3ab1cde4-71ad-4c1a-bc5b-3b228838a3f2.png">

In this example, the expected behavior would be receiving the pp for a "perfect combo", however it seems like they are awarded with the pp for getting 974/1381 combo.

**Comment by bdach** [comment] 2022-12-27 21:46
Let's continue tracking at https://github.com/ppy/osu/issues/21815 since this is a slightly different issue (and one that probably can't even be fixed in client itself)
