### ISSUE TITLE
Add more "slow down stages" in the Editor

### ISSUE THREAD

**Issue by Enterpriseosu** [ppy/osu#12830] opened 2021-05-15 20:45 UTC
**Describe the new feature:** 

Instead of having 25%/50%/75%/100% I think it's better to have more and espacially slower "stages" in the Editor.

**Proposal designs of the feature:** 

I think something like 10 "slow down stages" would be perfect for the editor: 10%/20%/.../90%/100%.

This would allow mappers to get a better and easier feeling on how to map certain stages in fast, high bpm songs.

**Comment by jai-x** [comment] 2021-05-15 20:49
I think this might be a duplicate of https://github.com/ppy/osu/issues/2393 (unsure)

See also the reasoning given in this PR: https://github.com/ppy/osu/pull/12080

**Comment by Moltanicaa** [comment] 2021-05-16 11:49
How reasonable is it to consider adding a speed of 125% (Double Time)?

**Comment by Enterpriseosu** [comment] 2021-05-16 15:55
> How reasonable is it to consider adding a speed of 125% (Double Time)?

Not a bad idea but i think adding 110%/120%/.../150% will just end up in mappers concentrating even more on making DT Farm maps as some already do. My point was to have a slower playback speed to help mappers to emphasize specific parts in maps much better and easier.

**Closed** 2021-05-27 09:17 UTC
Labels: area:editor, proposal
