### ISSUE TITLE
Don't Stop Me Now doesn't start from the start of the song.

### ISSUE THREAD

**Issue by nathanielcwm** [ppy/osu#6840] opened 2019-11-13 13:15 UTC
**Describe the bug:** 
When playing https://osu.ppy.sh/beatmapsets/5381 in lazer the song starts from the 2nd skip instead of from the start of the song. The issue also occurs when auto isn't on.

**Screenshots or videos showing encountered issue:** 
Expected:
https://gfycat.com/lankydazzlingalligatorgar
Actual:
https://gfycat.com/grandickyarcticfox

**osu!lazer version:** 
2019.1113.0

**Logs:** 
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3841266/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3841267/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3841268/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3841269/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3841270/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3841271/updater.log)
[database.log](https://github.com/ppy/osu/files/3841272/database.log)

**Comment by nathanielcwm** [comment] 2019-11-13 13:19
Tutorial works as expected. I haven't checked any other maps.

**Comment by bdach** [comment] 2019-11-13 13:32
I'm pretty sure this'll be due to the storyboard having negative time offsets. [As per the wiki playback should start from the earliest time offset *or* 0](https://osu.ppy.sh/help/wiki/Storyboard_Scripting/General_Rules#time), and the double skip in stable is due to skipping to 0 first and then to actual gameplay. I imagine this will not be exclusive to this specific map, but will happen everywhere where negative offsets are used, but I can't think of an example off the top of my head right now.

As an additional note, on restart the gameplay should go back to time offset 0, instead of playing from the earliest event again.

**Comment by nathanielcwm** [comment] 2019-11-13 13:43
Hitting restart on stable brings me to the start of the song.
Hitting the keybinding for skip on stable brings me to the second skip.

**Comment by LeNitrous** [comment] 2019-11-13 13:54
In Lazer, the gameplay always starts at -2000ms completely disregarding the first element of the storyboard whereas Stable's behavior does that. Skipping in stable also automatically skips. This should clarify on what the intended behavior should be. At least on my observation.

https://github.com/ppy/osu/blob/451ae8fc73014c095974f544adedc7948fc7306b/osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs#L66-L67

**Comment by peppy** [comment] 2019-11-13 15:02
I have a WIP fix for this https://github.com/ppy/osu/pull/4883

**Comment by nathanielcwm** [comment] 2019-11-17 02:31
I don't know if this is related but for some beatmaps like:
https://osu.ppy.sh/beatmapsets/63753
https://osu.ppy.sh/beatmapsets/1050560

The video starts at the wrong time so it's quite distracting as it's out of sync.

**Comment by peppy** [comment] 2019-11-17 02:43
See https://github.com/ppy/osu/issues/6101

**Comment by nathanielcwm** [comment] 2019-11-17 03:16
Ah ok

**Comment by Joehuu** [comment] 2021-01-03 20:44
Regressed in https://github.com/ppy/osu/pull/7302.

**Closed** 2021-01-04 19:09 UTC
Labels: area:gameplay, area:storyboard
