### ISSUE TITLE
[storyboard bug]Storyboard display different results in stable and lazer.

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu#28292] opened 2024-05-23 06:59 UTC
### Type

Crash to desktop

### Bug description

lazer: https://raw.githubusercontent.com/wanjiaXG/Image-Hosting-Service/main/lazer.mp4
stable: https://raw.githubusercontent.com/wanjiaXG/Image-Hosting-Service/main/stable.mp4
The result of stable meets my expectations.
map: https://osu.ppy.sh/beatmapsets/2030098#osu/4620314

### Version

Lazer 2024.521.2

### Logs

none

**Comment by bdach** [comment] 2024-05-23 07:26
I don't see the bug. Can you elaborate?

**Comment by EVAST9919** [comment] 2024-05-25 10:19
![Снимок экрана 2024-05-25 131817](https://github.com/ppy/osu/assets/22874522/ba830ede-a762-4103-b7d1-9215e74a56b9)
 Overlapping fade transforms, duplicate of https://github.com/ppy/osu/issues/7257

**Closed** 2024-05-25 10:22 UTC
Labels: area:storyboard
