### ISSUE TITLE
Displaying the playing field anyway

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9764] opened 2020-08-03 12:26 UTC
**Describe the new feature:** 
In the stable, there is an opportunity to designate a play space in the skin, which helps a lot to play. If you turn off the interface, then the field also disappears. It makes no sense to ask for this in the stable, so I propose to add the "always show the playing field" button in the settings, like "always show the health scale, even if you can't die".
**Proposal designs of the feature:** 
![screenshot103](https://user-images.githubusercontent.com/59089206/89181977-13cbd880-d5d8-11ea-9900-6d3a4b78fc30.jpg)

**Comment by Wieku** [comment] 2020-08-03 12:35
Duplicate of #9198

**Closed** 2020-08-03 12:35 UTC

**Comment by Wieku** [comment] 2020-08-03 12:49
Also to note: It's not a `play space in the skin`, it's a health bar background.
