### ISSUE TITLE
Collections are missing

### ISSUE THREAD

**Issue by kihure** [ppy/osu#10562] opened 2020-10-19 18:51 UTC
**Describe the bug:** Collections are getting deleted. Sorry, I'm new to github and I've closed the previous issue by mistake. After restarting the game they were gone and there was no error this time.  I made copy of the logs straightaway when it happened.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2020.1017.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5404061/network.log)
[performance.log](https://github.com/ppy/osu/files/5404063/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5404064/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5404065/updater.log)
[database.log](https://github.com/ppy/osu/files/5404066/database.log)

**Comment by bdach** [comment] 2020-10-19 18:56
We can reopen issues if need be. Please ask if necessary next time.

The logs attached show no errors. Does the file `%AppData%/osu/collection.db` exist? If so, please attach it to the issue; if not, please check if it is getting deleted by the game along with the collections.

**Comment by kihure** [comment] 2020-10-19 19:20
> We can reopen issues if need be. Please ask if necessary next time.
Sorry didn't know that. Where do i ask?

> The logs attached show no errors. Does the file `%AppData%/osu/collection.db` exist? If so, please attach it to the issue; if not, please check if it is getting deleted by the game along with the collections.

[collection.zip](https://github.com/ppy/osu/files/5404190/collection.zip)

Sorry I think I've made a mistake once again. I've already imported collections from stable so that's probably why it exists. I have a feeling it might happen again, so i'll keep updating in this issue. 
Also, one weird thing is that always one collection remains. It deletes maps that are in it but it's still there. Might be because it's called "acc" so it appears first in alphabetical order.

**Comment by bdach** [comment] 2020-10-19 19:38
> Sorry didn't know that. Where do i ask?

Just post a comment in a closed issue and we'll reopen if needed.

For what it's worth, I've copied the attached collection file to my install and it seems to be loading, although I'm unsure if the collection names are correct:

![osu_2020-10-19_21-35-35](https://user-images.githubusercontent.com/20418176/96503185-2e1a6780-1253-11eb-8ee9-dc9d9d95c829.jpg)

but please reattach a fresh version after the next time collections disappear to compare.

**Comment by kihure** [comment] 2020-10-19 20:15
> For what it's worth, I've copied the attached collection file to my install and it seems to be loading, although I'm unsure if the collection names are correct:

Yes, although that is the current state ( after importing again ) so as you can see "acc" appears twice. One of those acc's shouldn't have any beatmaps in it and that's the leftover one after the disappearing :(

**Comment by smoogipoo** [comment] 2020-10-20 07:32
Hard to say what happened. Is this something you can consistently reproduce? Are you closing the game via the X button or are you killing the task?

We're going to change the database storage in the future and make things more resilient. The current implementation is a minimum viable product and not supposed to be safeguarded against any and all scenarios like stable is.

There's too many things that could've gone wrong - we can only help you out after it errors (logs will only be filled with information when that happens). So if you can provide the logs next time it errors, that'd be very helpful. Feel free to post back in here when/if you get such logs and we'll reopen the issue.

**Closed by smoogipoo** 2020-10-20 07:32 UTC
Labels: missing details
