### ISSUE TITLE
Import folder for importing maps manually?

### ISSUE THREAD

**Issue by Kittyneko-the-glitch** [ppy/osu#6937] opened 2019-11-23 15:46 UTC
**Describe the new feature:** 
Since opsu! has a manual Import folder. Why not the Android osu!Lazer? We wish we could add that one stream practice map from Bloodcat but can't because you have to use osu!direct.. Basically it is for importing maps the opsu way and also importing deleted maps (yay).
**Proposal designs of the feature:** 
Well, it would be a folder inside the sh.ppy.osulazer folder inside "Android" and if you put a beatmap in it (e.g. Punch*Mind*Happiness by Happy Clover from Anne Happy), it will load it into osu! once you open the app.

**Comment by peppy** [comment] 2019-11-23 15:47
Duplicate of https://github.com/ppy/osu/issues/5761.

The more correct way would be adding a file association for the application. This is already done on iOS, and allows importing skins and beatmaps.

**Closed by peppy** 2019-11-23 15:47 UTC

**Comment by Kittyneko-the-glitch** [comment] 2019-11-23 15:49
I unfortunately cannot import osks and oszs since it will show up as "Open up with Ibis Paint X or Flipaclip", can you help me?

**Comment by bdach** [comment] 2019-11-23 15:50
This is not a pressing issue. The priority for now is to finish the game on desktop.

Please refrain from submitting more mobile-related reports for the time being, as per the warnings placed in the issue submission process.
