### ISSUE TITLE
Cursor stays on screen while playing [osu!catch]

### ISSUE THREAD

**Issue by VelperK** [ppy/osu#6339] opened 2019-09-30 18:52 UTC
Cursor stays on screen during osu!catch gameplay unless it's manually moved to the right edge of the screen.

It seems screenshots can't capture the cursor, but it's easy to reproduce.

osu!lazer v.2019.930.0

**Comment by bdach** [comment] 2019-09-30 18:59
Duplicate of #2901 (and #5474?)

**Closed** 2019-09-30 20:30 UTC
