### ISSUE TITLE
Beatmap loading becomes very long when storyboard is enabled

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#6549] opened 2019-10-20 02:41 UTC
**Describe the bug:** 
Some beatmap will load very long when storyboards are enabled.
It took around 2 minutes to fully load the beatmap.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=eq3vtBBuEBw&feature=youtu.be

**osu!lazer version:** 
2019.1011.0

**Logs:** 
I will upload it if necessary.

**Comment by Joehuu** [comment] 2019-10-20 03:11
Duplicate of https://github.com/ppy/osu/issues/4976

**Closed by Joehuu** 2019-10-20 03:11 UTC
