### ISSUE TITLE
Resizing the game window around a certain size snaps to a value

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#4517] opened 2019-03-24 11:02 UTC
If you resize the game window around a horizontal/vertical size it seems to snap to a specific value. This makes resizing look jarring.
Here is a [video](https://streamable.com/54hl6).

**Comment by Gabixel** [comment] 2019-03-24 11:17
At first, I thought it was just a problem on my PC, caused by the resolution of my screen or a faulty driver.
I was wrong..
Thanks for pointing this out!

**Comment by Gabixel** [comment] 2019-03-31 12:21
With the latest release seems that the game crash when you try to resize the window.
Most of the time the runtime just says `Unhandled exception has been allowed with 0 more allowable exceptions .`, and other times it says [**this**](https://github.com/ppy/osu/files/3026563/runtime.log).
I'll attach [performance-gamethread.update.log](https://github.com/ppy/osu/files/3026564/performance-gamethread.update.log) if that's useful.

**Comment by Gabixel** [comment] 2019-03-31 21:46
Actually, I was wrong (again): the crash was caused by the Discord overlay, but it's still glitchy as Aergwyn said (and probably the overlay doesn't handle window resizing correctly because of this).

**Comment by Aergwyn** [comment] 2019-04-01 14:13
I don't use the Discord overlay so it's not necessarily related to that.

**Comment by Gabixel** [comment] 2019-04-01 16:19
Perhaps what I said was misunderstood @Aergwyn  (watch this as reference: https://streamable.com/34s9r):

With Discord Overlay disabled Lazer never crash, but it snaps to a certain value when resizing the window (like you said). Instead, with the Overlay enabled, there's like an 80% chance that Lazer will crash (and like a 10% that the UI becomes invisible and glitchy, but that's not the case with the previous video) when resizing the window.
So I guess the main issue is the first one (your one) and, if this framework-level issue will be fixed, the conflict with the Discord Overlay should automagically disappear (that's why I reported this here and not with a new issue).

**Comment by peppy** [comment] 2019-04-02 01:00
The discord overlay crash is something I can reproduce. I believe there is a chance it is partly our responsibility (cross thread go operations are still happening, i believe).

**Comment by smoogipoo** [comment] 2019-05-09 04:07
Resolved by the recent resize changes. Made a separate issue for the discord overlay crash.

**Closed by smoogipoo** 2019-05-09 04:07 UTC
Labels: framework fix required, overdue
