### ISSUE TITLE
Quickly pressing ESC twice in song select exits the game

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3050] opened 2018-07-16 19:58 UTC
↑
It's pretty cool to be able to exit the game like that, but I don't think this is intended. Correct me if I'm wrong though. I can make a video if needed.

**Comment by Morilli** [comment] 2018-07-16 20:31
The outro is still playing. It basically behaves as if alt + f4 was pressed.

**Comment by Frontear** [comment] 2018-07-17 00:18
It's intended.

From song select, first ESC to return to menu. Second ESC to exit game

**Comment by peppy** [comment] 2018-07-17 00:36
It is not intended and should not happen. Please stop with these nonsense replies and suggestions. If the original issue exists it should be fixed.

**Comment by Morilli** [comment] 2018-09-12 19:08
Doing this will now sometimes throw the following error:
```
12.09.2018 19:00:33: Unhandled exception has been allowed with 0 more allowable exceptions .
12.09.2018 19:00:33: An unhandled error has occurred.
12.09.2018 19:00:33: System.InvalidOperationException: Attempting to access a TextureWithRefCount's underlying texture after all references are lost.
12.09.2018 19:00:33: at osu.Framework.Graphics.Textures.TextureWithRefCount.get_TextureGL()
12.09.2018 19:00:33: at osu.Framework.Graphics.Sprites.SpriteDrawNode.Draw(Action`1 vertexAction)
12.09.2018 19:00:33: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction)
12.09.2018 19:00:33: at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.drawChildren(Action`1 vertexAction, Vector2 frameBufferSize)
12.09.2018 19:00:33: at osu.Framework.Graphics.Containers.BufferedContainerDrawNode.Draw(Action`1 vertexAction)
12.09.2018 19:00:33: at osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(Action`1 vertexAction)
12.09.2018 19:00:33: at osu.Framework.Platform.GameHost.DrawFrame()
12.09.2018 19:00:33: at osu.Framework.Threading.GameThread.ProcessFrame()
12.09.2018 19:00:33: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by Gabixel** [comment] 2018-09-12 20:12
I don't think the error is related to that particular situation, because I get the same error sometimes when I exit the song list (without pressing ESC twice). But I don't know precisely how it happens.

**Comment by Gabixel** [comment] 2018-09-12 22:29
I tried to reproduce your issue, and it even happens to me.
But I think the problem is the background changing of the main menu when you exit the list (because when is changing, I get so much lag at that moment), and it seems like to spam the ESC button until the Exit state. I have this theory because something similar happened to me:
> When the song was changing (and the background colour too), I pressed enter to send a message in chat at the same time, and it started to spam it like 40 times until the lag stops.

That said, I have some logs that can be useful:
**runtime.log**
```
12/09/2018 22:10:33: Screen changed → PlaySongSelect
12/09/2018 22:10:35: updating selection with beatmap:64 ruleset:0
12/09/2018 22:10:35: working beatmap updated to Jason Derulo - In My Head (DiamondCrash) [Easy]
12/09/2018 22:10:38: Screen changed ← MainMenu (0,0) 1.488x728
12/09/2018 22:10:39: ButtonSystem's state changed from EnteringMode to Exit
12/09/2018 22:10:39: Screen changed ← Intro (0,0) 1.488x728
12/09/2018 22:10:41: Screen changed ← Disclaimer (0,0) 1.488x768
12/09/2018 22:10:41: Screen changed ← Loader (0,0) 1.488x768
12/09/2018 22:10:41: Screen changed ←
```
(the runtime is to show you every change)

**performance-gamethread.input.log**
```
12/09/2018 22:10:33: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:33: |
12/09/2018 22:10:33: | * Thread time  : 1.217.157ms
12/09/2018 22:10:33: | * Frame length : 60ms (allowable: 45ms)
12/09/2018 22:10:33: |
12/09/2018 22:10:33: | Call stack was not recorded.
12/09/2018 22:10:33: 
12/09/2018 22:10:34: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:34: |
12/09/2018 22:10:34: | * Thread time  : 1.218.578ms
12/09/2018 22:10:34: | * Frame length : 48ms (allowable: 36ms)
12/09/2018 22:10:34: |
12/09/2018 22:10:34: | Call stack was not recorded.
12/09/2018 22:10:34: 
12/09/2018 22:10:35: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:35: |
12/09/2018 22:10:35: | * Thread time  : 1.218.981ms
12/09/2018 22:10:35: | * Frame length : 165ms (allowable: 141ms)
12/09/2018 22:10:35: |
12/09/2018 22:10:35: | Call stack was not recorded.
12/09/2018 22:10:35: 
12/09/2018 22:10:36: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:36: |
12/09/2018 22:10:36: | * Thread time  : 1.219.636ms
12/09/2018 22:10:36: | * Frame length : 251ms (allowable: 247ms)
12/09/2018 22:10:36: |
12/09/2018 22:10:36: | Call stack was not recorded.
12/09/2018 22:10:36: 
12/09/2018 22:10:39: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:39: |
12/09/2018 22:10:39: | * Thread time  : 1.223.326ms
12/09/2018 22:10:39: | * Frame length : 546ms (allowable: 237ms)
12/09/2018 22:10:39: |
12/09/2018 22:10:39: | Call stack was not recorded.
12/09/2018 22:10:39: 
12/09/2018 22:10:41: | Slow frame on thread "GameThread.Input"
12/09/2018 22:10:41: |
12/09/2018 22:10:41: | * Thread time  : 1.224.989ms
12/09/2018 22:10:41: | * Frame length : 192ms (allowable: 104ms)
12/09/2018 22:10:41: |
12/09/2018 22:10:41: | Call stack was not recorded.
12/09/2018 22:10:41: 
```

**Comment by peppy** [comment] 2018-09-20 04:55
Seems to be caused in cases where after-action input blocking is not instant (one frame or schedule delayed).

Update frame lags/blocks while input thread is handling events, causing two down events (or potentially clicks) to fire on the next update frame.

Probably needs to be fixed on a per case basis where this comes up, and care needs to be given to future usage of input events.

**Comment by Gabixel** [comment] 2019-01-09 13:44
I discovered that it also happens in multiplayer: https://streamable.com/kd1d6

**Closed** 2019-01-17 06:32 UTC
Labels: bug, input
