### ISSUE TITLE
Extremely High RAM used

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#6795] opened 2019-11-10 12:18 UTC
**Describe the bug:** 
I had 12000+ map imported into lazer and played at lazer for 11 months. The RAM was about 2.4-3.5G. However, after updating 1106 version, 12GB+ used for just 40-min gameplay. Is there any wrong?
 
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
1106
**Logs:**

**Comment by peppy** [comment] 2019-11-10 12:19
If you are not going to provide any kind of useful diagnostic information, please don't post an issue like this. We are constantly working on performance and such reports are not useful.

**Comment by peppy** [comment] 2019-11-10 12:33
Please attach runtime.log after a play session, and a screenshot of task manager after osu! is in such a state. Also try clicking the "Clear all caches" button in settings to see if it helps at all.

**Comment by Gabixel** [comment] 2019-11-10 13:13
I can attach my [runtime.log](https://github.com/ppy/osu/files/3828428/runtime.log) since I have a similar issue. As you can see from my runtime, I entered the Editor. Then I entered Solo and played a map with Autoplay (I skipped the song using the progress bar, that's why its length is less than the expected one):

![RAM](https://user-images.githubusercontent.com/43073074/68544181-cc097f00-03c0-11ea-9927-829b71fd1787.png)

It has almost reached 4GB (the previous version uses less than 2GB), it has also reached 5GB with a previous test (Windows also "crashed" that time, but I forgot to watch the logs to see if there was any difference).
I tried to use the "Clear all caches" button when I was in the carousel (and in the main menu), but it doesn't seem to have decreased the RAM usage.

Some PC info:
OS: Windows 10 (64 bit)
RAM: 8GB
CPU: AMD Ryzen 5 (Six-Core)

**Comment by peppy** [comment] 2019-11-10 13:25
Can you reproduce without entering the editor?

**Comment by serenityP** [comment] 2019-11-10 13:26
Here are my 2 diffierent versions (1011 and 1106)  Screenshots of task manager attached. 

PC info:
OS: Windows 7 (64 bit)
RAM: 16GB  1866Mhz
CPU: E3-1230 V3

**Comment by serenityP** [comment] 2019-11-10 13:27
Sorry. I upload my screenshots again

**Comment by Gabixel** [comment] 2019-11-10 13:31
@peppy it seems so:

![image](https://user-images.githubusercontent.com/43073074/68544715-82bc2e00-03c6-11ea-84a6-91bf65f87e4f.png)

Here's the new [runtime.log](https://github.com/ppy/osu/files/3828491/runtime.log)

**Comment by serenityP** [comment] 2019-11-10 13:58
1011 and 1106 after playing 4 maps

https://www.dropbox.com/s/cvlqrl834gz6b0n/lazer_1106ver_gameplay4.jpg?dl=0
https://www.dropbox.com/s/dmavfh0k9s6xy6f/lazer_1011ver_gameplay4.jpg?dl=0

**Comment by RzoregDe96** [comment] 2019-11-10 15:00
here's mine: 
[runtime.log](https://github.com/ppy/osu/files/3828585/runtime.log)

same thing as OP and haoyaoyuan mentioned... and even my perfomance.log is 30.9MB

just updated from 1026 ver some hours ago... and 1026 ver is much faster (but with slight frame drops)

specs:
win7 x64
4GB 2.70 Hz
amd a4-3400 apu

**Comment by peppy** [comment] 2019-11-11 01:16
Could you please try disabled performance logging and see if it helps? And also attach your 30mb performance.log.

**Comment by ojh050118** [comment] 2019-11-11 08:01
Enabling performance logging uses approximately twice as much memory.

(After turning off performance logging) Some bitmaps use more than 1gb of memory.
You can reduce the memory usage by clicking Clear All Cache, but it is more than the memory usage before playing the bitmap.

And CPU utilization is high. Also, GPU usage increases significantly in the Results window.

**Comment by peppy** [comment] 2019-11-11 08:01
Could you please provide numbers and screenshots without performance logging?

**Comment by ojh050118** [comment] 2019-11-11 08:48
CPU usage and memory usage before beatmap play

![Before beatmap select menu](https://user-images.githubusercontent.com/51792037/68573018-2b8f8980-04aa-11ea-9342-3fd6d20f6ca7.png)

Memory usage after beatmap play

![Played beatmap memory](https://user-images.githubusercontent.com/51792037/68573057-44983a80-04aa-11ea-8f21-4aafabdc9bd4.png)

High GPU utilization only in results window

![Result Window](https://user-images.githubusercontent.com/51792037/68573064-48c45800-04aa-11ea-932c-f90e684c5a0d.png)

Memory usage after clear all caches

![After beatmap select menu (clicked clear all caches)](https://user-images.githubusercontent.com/51792037/68573454-1cf5a200-04ab-11ea-830f-2f3f422ffd63.png)

**Comment by peppy** [comment] 2019-11-11 08:48
These look within spec. We are only interested in memory usage above 2GB.

**Comment by RzoregDe96** [comment] 2019-11-12 09:26
here's my attached file for performance logs:

https://drive.google.com/open?id=1kO9CU1u7lSc2JnPD-vW4fpQpkqbVEXia

**Comment by peppy** [comment] 2019-11-12 09:28
As mentioned above, please turn performance logging off and test again.

**Comment by RzoregDe96** [comment] 2019-11-12 09:55
so i did turn off the performance logging, and here's what i tested...
memory usage on main menu:
![123](https://user-images.githubusercontent.com/56816547/68661147-6ad6dc80-0575-11ea-9342-ff4ea0f5e8c0.png)

memory usage after beatmap play:
![123123](https://user-images.githubusercontent.com/56816547/68661187-7b875280-0575-11ea-8c1a-bc4fef6ea8cc.png)

memory usage after clear all caches:
![123123123](https://user-images.githubusercontent.com/56816547/68661210-86da7e00-0575-11ea-8d2a-3efa72a40aae.png)

**Comment by peppy** [comment] 2019-11-12 09:56
This is all normal. As above, only interested in usage above 2gb.

**Comment by nathanielcwm** [comment] 2019-11-16 04:41
![image](https://user-images.githubusercontent.com/22572406/68988163-3d887800-086e-11ea-9eaf-7fd38ac19e16.png)

[performance-gamethread.input.log](https://github.com/ppy/osu/files/3853818/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3853819/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3853827/runtime.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3853824/performance-gamethread.audio.log)

**Comment by peppy** [comment] 2019-11-16 07:14
Please confirm it only happens with performance logging, as above.

**Comment by l3lackShark** [comment] 2019-11-16 07:26
@peppy Can confirm that performance logging drastically affects ram usage.

**Comment by nathanielcwm** [comment] 2019-11-16 16:19
never going above 1.5GB with performance logging off

**Comment by peppy** [comment] 2019-11-22 05:09
Closing this for now as I can't repro with performing logging on or off. We've made a change to framework to ensure performance logging is reset each game launch to alleviate issues.

**Closed by peppy** 2019-11-22 05:09 UTC
Labels: framework fix required, performance, regression

**Comment by home-gihub** [comment] 2023-06-17 11:54
me too i have 8GB ram and it (almost) uses all of it
