### ISSUE TITLE
osu!logo size sometimes is not synced with the rest of the ButtonSystem

### ISSUE THREAD

**Issue by ColdVolcano** [ppy/osu#1005] opened 2017-07-11 01:28 UTC
When this is done the OsuLogo will "lose its proportions", making it the size of the default state of the logo, won't go back to normal size unless the (config/play/editor/direct/exit) menu is opened again

Steps to reproduce: 
- Click the osu!logo once (open the config/play/editor/direct/exit menu)
- Press esc and immediatly press space.

Might have something to do with the recent changes to transform logic, not completely sure I can do something to help solve this issue

Video of the problem:

https://www.youtube.com/watch?v=gs4tSv-NU4M

**Comment by peppy** [comment] 2017-07-11 01:29
I had this happen once but thought it got fixed since then. Seems not!

**Comment by ColdVolcano** [comment] 2017-07-11 08:29
Somehow fixed in #1007, although...

- if going with the same steps but instead pressing esc>space>esc one right after another the issue still happens. (https://youtu.be/N8H71K6xfEI)
- just found out a similar issue can happen: if you open the same menu but instead you _click_ the "solo" button and immediatly press esc the logo goes to InitialState but when clicked it goes to PlaySongSelect (https://youtu.be/3E-8S_GqwRA), playing around with other buttons makes even crazier stuff to happen (https://youtu.be/cn0Lun5L67Q)

**Comment by peppy** [comment] 2017-08-22 02:17
I believe this was fixed by transform changes made a while back. Please reopen if you can still reproduce any of these.

**Comment by ColdVolcano** [comment] 2017-08-22 02:24
Reopening as the second point of last comment still applies

**Closed** 2017-11-18 13:52 UTC
