### ISSUE TITLE
osu!lazer beatmap search results differs from website beatmap search results

### ISSUE THREAD

**Issue by natefusion** [ppy/osu#22008] opened 2023-01-02 19:54 UTC
### Type

Game behaviour

### Bug description

I was looking for this [map](https://osu.ppy.sh/beatmapsets/1376486#osu/2853906). I could only find it using the website search. It would not show up at all in osu!lazer's search.

I'm using the flatpak version on Linux, if that helps.

### Screenshots or videos

osu!lazer search results: ![osu_2023-01-02_14-25-43](https://user-images.githubusercontent.com/47067814/210272753-bfc95bed-bd24-4774-9e65-510d9808e855.jpg)

website search results: ![Screenshot from 2023-01-02 14-33-42](https://user-images.githubusercontent.com/47067814/210272791-1daf96f3-345b-4c66-a302-8707362895ca.png)

### Version

2022.1228.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10333280/database.log)
[input.log](https://github.com/ppy/osu/files/10333281/input.log)
[network.log](https://github.com/ppy/osu/files/10333282/network.log)
[performance.log](https://github.com/ppy/osu/files/10333283/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10333284/runtime.log)

**Comment by NiceAesth** [comment] 2023-01-02 19:56
This is not a bug. You did not disable the featured artist filter in search, which is now enabled by default.

**Comment by natefusion** [comment] 2023-01-02 20:02
I didn't know that. There was no visual indication that "Featured artists" was selected, and obviously I didn't notice that all the maps were all by featured artists.

**Comment by bdach** [comment] 2023-01-02 21:07
Going to close this as this is indeed intended, but going to open another issue about the visual appearance of the filter because clearly the conveyance isn't there as this has been reported multiple times already.

**Closed by bdach** 2023-01-02 21:07 UTC
