### ISSUE TITLE
Spinner can be cheesed by moving the cursor back and forth.

### ISSUE THREAD

**Issue by archhaze24** [ppy/osu#20534] opened 2022-09-29 17:48 UTC
### Type

Game behaviour

### Bug description

You can easily cheese spinner by moving the cursor back and forth, instead of spinning. The video is attached below, in the "Screenshots or videos" section.

In stable this will give you 50-100spm, but in lazer it gives you ~400. My best try was around ~600spm.

### Screenshots or videos

Video of cheesing the spinner.

https://user-images.githubusercontent.com/49359990/193104760-e07d2776-57c8-4f90-9858-acc396e2b9f7.mp4

### Version

2022.923.1

### Logs

[database.log](https://github.com/ppy/osu/files/9677853/database.log)
[network.log](https://github.com/ppy/osu/files/9677854/network.log)
[performance.log](https://github.com/ppy/osu/files/9677855/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9677856/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9677857/updater.log)

**Comment by mk56-spn** [comment] 2022-09-29 17:51
this is known

**Comment by mk56-spn** [comment] 2022-09-29 17:52
https://github.com/ppy/osu/discussions/17173

**Comment by frenzibyte** [comment] 2022-09-29 17:54
Duplicate of https://github.com/ppy/osu/issues/8224

**Closed by frenzibyte** 2022-09-29 17:54 UTC
