### ISSUE TITLE
Show room beatmap info and match type in multiplayer lobby listing

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#14316] opened 2021-08-15 17:02 UTC
While it's fine to have the number of beatmaps at a glance in playlist because you can't show them all, ~~that really doesn't make much sense for multiplayer because it's always one beatmap~~, and now we lost information compared to old design (beatmap name and length).
The beatmap spread can stay, i said that it didn't make sense because i always saw it displaying 1, but recently it started to display the spread difficulty of the maps that were played in the room and the number, that's cool.

I suggest changing the design from this
![image](https://user-images.githubusercontent.com/53081750/129486299-c6ee893a-da8b-45bd-8514-d77174f8f8de.png)
to this
![image](https://user-images.githubusercontent.com/53081750/129486348-bea3794f-1e09-44b9-b70d-14b729bf0ea9.png)

**Comment by peppy** [comment] 2021-08-15 17:06
@arflyte i'm presuming you have some answer to this and it's in a WIP state? we did lose like 50% of the display information with the new design, which should be considered a regression to some extent.

**Comment by arflyte** [comment] 2021-08-23 06:38
The multiplayer card is still pretty WIP. I'm still trying to decide on what to add into the card, without cluttering it too much. The base design is there, any other info is to be added later.

**Comment by smoogipoo** [comment] 2021-09-14 00:36
@arflyte this one is pretty high priority. What I could do is replace the "hosted by" text under the title with the current beatmap, because that text is only there as a placeholder for the description in the designs which we don't have yet.

But that would mean two panels with slightly different layouts, because it doesn't make much sense for playlists to have the same. Does that sound fine?

**Comment by peppy** [comment] 2021-09-14 04:42
Also keep in mind that's the only place the host is currently shown clearly, so that would need to be moved somewhere if we replace that line.

**Comment by smoogipoo** [comment] 2021-09-14 04:49
Correct, in the designs it's a bit of text at the end of the bottom section, or a sheared box on the right, or... sometimes both apparently.
I'd need clarification on which one to use if so.

![image](https://user-images.githubusercontent.com/1329837/133196709-d5b1e0ad-6ebb-4ebc-bd85-a489c9d96694.png)
![image](https://user-images.githubusercontent.com/1329837/133196726-e45b6447-049a-4bba-8bdf-a0455776f24f.png)
![image](https://user-images.githubusercontent.com/1329837/133196786-c22309f4-db34-4387-bd54-01d051d774c2.png)
![image](https://user-images.githubusercontent.com/1329837/133196757-ab0ec28a-f305-4fac-abbc-3a44b9605d7e.png)

**Comment by arflyte** [comment] 2021-09-14 05:03
I'll sort this out today.

**Comment by bdach** [comment] 2021-11-08 12:58
Is https://github.com/ppy/osu/pull/14891 enough to consider this resolved, or is there other missing info yet to be added back? Seems to me that it may be enough but not sure.

**Comment by peppy** [comment] 2021-11-08 13:38
Who knows. Designer "sort this out today" generally means "never happening".

Let's just close this as we fixed it.

**Closed by peppy** 2021-11-08 13:38 UTC
Labels: type:UI, area:multiplayer, priority:1

**Comment by arflyte** [comment] 2021-11-08 13:44
Oh, this was sorted over Discord VC with smoogi on that day ._.
