### ISSUE TITLE
Migrating to folder titled "lazer" causes infinite recursion in copied directory.

### ISSUE THREAD

**Issue by willyosu** [ppy/osu#9684] opened 2020-07-26 23:14 UTC
**Describe the bug:** 
This may be an oddly specific bug but it's bound to happen more than once.

When trying to use the in-game "Change Folder Location..." setting the migration never ends because it is copying a folder within a folder infinitely. The game in this state also cannot be Alt+F4'd and you have to end the process itself. It happened to me every time that I used folder names like "osulazer" or "lazer" so I knew what the contents of the folder were. After copying to a folder just titled "New folder" it seems to work fine but anything relating to lazer in the directory name seems to cause this. 

You should be able to recreate this on Win10 by installing lazer to C:, creating a folder titled "lazer" or similar on D:, and attempting the migration although I have not tested on any machine other than my own.

![image](https://user-images.githubusercontent.com/11691902/88491398-6b32ce80-cf70-11ea-8391-a4a2f108e845.png)
_A screenshot of one attempt where the directory was named "lazer" showing several layers deep the copying recursion._

**osu!lazer version:** 
2020.725.0

**Logs:**
Nothing useful found after end process/successful transfer other than `Screen changed ← MigrationSelectScreen` in runtime.
[network.log](https://github.com/ppy/osu/files/4978903/network.log)
[performance.log](https://github.com/ppy/osu/files/4978904/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4978905/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4978906/updater.log)
[database.log](https://github.com/ppy/osu/files/4978907/database.log)

**Comment by YeaToast** [comment] 2020-07-27 13:17
This is an odd bug. Maybe because there's already a 'Lazer' or an 'osu!lazer' directory, and the program is using a ./ method of reading files. Rarely happens on windows though

**Comment by bdach** [comment] 2020-07-27 13:39
@YeaToast please refrain from posting untested theories about what you *think* might be going on. they don't help in any capacity.

**Comment by peppy** [comment] 2020-07-28 03:00
I can't seem to reproduce this, following your exact steps.

Could you provide a video or more screenshots, showing what is in each level of folder?

**Comment by willyosu** [comment] 2020-07-28 12:04
Each level contains this starting with `lazer` but stepping one level down into `lazer/osu-lazer` it contains the same files with its own `lazer/osu-lazer/osu-lazer` which contains the same etc.
![image](https://user-images.githubusercontent.com/11691902/88662753-6ec97100-d0a8-11ea-8b5b-5698151428e9.png)
It will continue creating these until the process is ended.

I was able to successfully migrate to a folder not titled "lazer" but this is something that happened multiple times across several weeks when trying to migrate to the `lazer` folder.

**Comment by bdach** [comment] 2020-07-28 20:40
I also cannot reproduce with the scenario provided. I *can* reproduce if I make a hard directory junction from within the lazer directory to itself using `mklink /j`, but it's a pretty "out there" thing to have on your file system... besides, this is what the original directory looks like if I do that:

![image](https://user-images.githubusercontent.com/20418176/88719174-24d1a100-d123-11ea-85f5-54e58a42c700.png)

(note the shortcut arrow on the junction, *although* the file type says "file folder" and *not* "shortcut").

@willyosu Would you be able to take a screenshot of your *original* lazer file folder on the C:/ drive?

**Comment by willyosu** [comment] 2020-08-01 17:00
Here's everything in my original lazer install folder but most of it has been migrated
![image](https://user-images.githubusercontent.com/11691902/89106281-a6ad1d00-d3f6-11ea-9d9f-a88b6e1f3933.png)

and here's my lazer on D: in case you'd like that as well
![image](https://user-images.githubusercontent.com/11691902/89106305-d52af800-d3f6-11ea-9725-78ced858dfa6.png)

**Comment by bdach** [comment] 2020-08-02 14:05
That looks perfectly reasonable... There is one spot I'm suspecting, namely this part:

https://github.com/ppy/osu/blob/e33c17701838851775225b9d0019767eb8ee9858/osu.Game/Overlays/Settings/Sections/Maintenance/MigrationSelectScreen.cs#L111-L115

In order to avoid mixing with unrelated files we will create a `osu-lazer` directory in the migration target dir if necessary. If `start()` fired multiple times for some reason that might give the appearance of recursion (albeit it should fire a finite number of times), but that still doesn't explain in the slightest why it would be name-specific... There definitely is *no* check for whether the migration target path contains the word `lazer` in it.

**Comment by peppy** [comment] 2020-08-02 14:07
Just as a sanity check, @willyosu can you confirm 100% that you've never setup any symlinks or junctions related to lazer in the past?

**Comment by Wieku** [comment] 2020-08-08 16:04
Also can't reproduce it, it got migrated properly
![image](https://user-images.githubusercontent.com/5307179/89714301-e13a2b00-d99d-11ea-8620-889deba74155.png)

As above it seems you've had some junctions set up. There are free tools available to search for symbolic links/junctions.

**Comment by peppy** [comment] 2020-08-10 10:45
On a quick check, it looks like there's an upcoming API for dealing with symlinks that we can consume and ensure better safety in the future https://github.com/dotnet/runtime/issues/24271.

I'm going to close this for now, though. We can revisit if others experience the same problem to the point it becomes necessary to make an interim change.

**Closed by peppy** 2020-08-10 10:45 UTC
Labels: area:settings, missing details, type:crash
