### ISSUE TITLE
Interception of control during the game

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8127] opened 2020-03-04 06:06 UTC
During the game (in particular, when you press streams), for an unknown reason, a program is activated that allows you to take a screenshot of the screen (this is a system program in Windows 10). Absolutely no keys except S and D are pressed. Disabling the service in the system does not help (the pointer is still replaced, however, the subsequent screenshot will not appear). This appears only when you press NORMAL (non-special) keys repeatedly.

https://www.youtube.com/watch?v=Tb2FVPOWmtg (0:25)
osu!lazer version:
2020.229.1

**Comment by Moltanicaa** [comment] 2020-03-05 08:46
1. I am absolutely sure that the problem is not in the key combination, because i cam relatively easily call it again, guaranteed to press only two keys. This error is more than a year old.
2. Keyboard and graphics tablet.
3. No.
4. I'll check later and let you know if there will be a different result
5. This too

**Comment by Moltanicaa** [comment] 2020-03-05 12:06
This is strange, but I can’t call him on purpose. it always happens by chance. You can not close this thread now, because I will try again and again with a program that reads clicks?

**Comment by Moltanicaa** [comment] 2020-03-06 14:05
So, I recorded a game with a fixed keystroke. Noticed that I quite often accidentally click on a shift or Q, but this program is called strictly by the key combination WIN+ shift + S. 
Moreover, I click on the "shift" very often, and only with an extremely low probability can this error appear. Even if you omit this moment with an interception of control - the osu does not pause the game (except for the game with the ability to restart) and after continuing does not offer me to click on the cursor to continue, but immediately continues the game.

And after all, I play the stable, and there isn’t such a thing (although I press the same keys).

In total, this error appeared 3 times per video, but consider it makes sense 2, which arose one after another. https://youtu.be/mcNgABbcur4
1. 13:02
2. 13:16

The game seems to be put on standby, thinking that I switch between windows.

**Comment by bdach** [comment] 2020-03-08 19:35
Did `--sdl` help at all? I don't think you answered that one. If it didn't there's really not much for us to go on here to try to fix this.

**Comment by Moltanicaa** [comment] 2020-03-09 00:52
I tried with this setting and there was no error. I will try again today to make sure.

**Comment by Moltanicaa** [comment] 2020-03-09 12:47
I caught her. The truth is I’m a little awkward that I wrote it down without fixing the keystrokes on the keyboard. But here I noticed something strange. When control is intercepted, my screen completely closes (the recording is not displayed correctly) and I can’t return to the lazer until I close it manually, however, I press something on the keyboard and it immediately addresses the lazer (i.e., keystrokes are ignored by this program for screenshots). If in the regular version of the lazer I still see the screen (just the cursor changes and slows down due to a change in speed) and I can play, then here I stop seeing it. The lazer does not even fix it and does not pause.

In general, the behavior of the laser is different each time

https://www.youtube.com/watch?v=SPS7uvQNoEI (5:40)

**Comment by peppy** [comment] 2020-04-09 08:50
Looks like something on your PC is dimming the screen when it happens? Probably the cause?

**Comment by Moltanicaa** [comment] 2020-04-09 09:04
Of course, the screenshot program is deployed to full screen.  just obs it doesn't capture

**Comment by peppy** [comment] 2020-04-09 09:07
I can't understand what you're saying, sorry.

**Comment by Moltanicaa** [comment] 2020-04-09 09:11
Dumb google translator.  The program itself does not appear on the recording, which opens, because the OBS (screen capture program) does not record it.

**Comment by LittleEndu** [comment] 2020-04-09 09:13
osu! ha built-in screenshoting. You should not use external programs to save screenshots.

**Comment by Moltanicaa** [comment] 2020-04-09 09:18
Are you serious or kidding? You read the topic, what am I writing about? Is it about SYSTEM MANAGEMENT CAPTURE that is built into the Windows 10 operating system?

**Comment by bdach** [comment] 2021-01-11 21:24
Going to close this as I *think* it was stated that SDL fixes this and I can't make much sense of the issue description either way.

**Closed by bdach** 2021-01-11 21:24 UTC
Labels: fixed-in-sdl, missing details, platform:windows
