### ISSUE TITLE
Android Song Search Crash

### ISSUE THREAD

**Issue by Germshroom** [ppy/osu#6279] opened 2019-09-26 10:51 UTC
So I can download song with direct just fine but the moment I type in the search bar osu! crashes. I don't get any crash info/logs

Video: https://drive.google.com/file/d/10VbtXpLEvn2k1C-dqC1ewZHsIejGoC7v/view?usp=drivesdk

2019.925.0

Don't have any logs

OnePlus 7 pro 8gb Ram

**Comment by Craftplacer** [comment] 2019-09-26 10:54
Duplicate of #6264

**Closed** 2019-09-26 10:56 UTC
