### ISSUE TITLE
Add a 'save for startup' option for mods

### ISSUE THREAD

**Issue by rubiksmaster02** [ppy/osu#9153] opened 2020-05-29 22:42 UTC
Add the ability to save the mods that you are currently using. So when you save your mod setup, exit the game, then reenter the game, all of the same mods will be checked.

**Comment by tybug** [comment] 2020-05-29 22:43
duplicate of https://github.com/ppy/osu/issues/6520

**Closed** 2020-05-29 22:44 UTC
