### ISSUE TITLE
Overall Ranking section shows incorrect results

### ISSUE THREAD

**Issue by Terochi** [ppy/osu#22942] opened 2023-03-23 18:23 UTC
### Type

Cosmetic

### Bug description

The overall ranking section on song result screen is very clearly showing incorrect results. 

I will rather let the images below be the explanation. Probably the easiest value to look at for clarification is the `Performance` row. 

My guess is that the data shown are cached from the previous play somehow and get shown before data from the new play override it.

I have already made an issue about this (https://github.com/ppy/osu/issues/22876), but it didn't get the recognition it should have. Otherwise I apologize if I'm completely wrong about this.

### Screenshots or videos

Play no. 1:
![image](https://user-images.githubusercontent.com/100224757/227298649-4beb8b33-698a-4618-9824-766bec6ec493.png)

Play no. 2:
The only thing making sense in the overall ranking section is the `Total Score`, everything else should be without any changes.
There is no way for me to get +3 overall pp from a 6pp play
![image](https://user-images.githubusercontent.com/100224757/227298712-1f84b2fa-58d5-4458-9264-7b7957a961d8.png)

Video as well because why not
https://user-images.githubusercontent.com/100224757/227300238-1d436e2a-f400-4149-818c-73bfe51ee573.mp4

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/11054290/database.log)
[input.log](https://github.com/ppy/osu/files/11054274/input.log)
[network.log](https://github.com/ppy/osu/files/11054278/network.log)
[performance.log](https://github.com/ppy/osu/files/11054281/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11054283/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11054289/updater.log)

**Comment by bdach** [comment] 2023-03-23 19:45
Duplicate of #22289

**Closed by bdach** 2023-03-23 19:45 UTC
