### ISSUE TITLE
Android. The application crashes if you exit the editor.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#10469] opened 2020-10-10 06:31 UTC
Describe the bug: 
As title. The check showed that third-party rulesets (they are visible in the last frames) have nothing to do with it. Removing them didn't fix the problem.
Screenshots or videos showing encountered issue: 
https://youtu.be/LkbC8WnXHFg
osu!lazer version: 
2020.1009.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/5358538/network.2.log)
[database.log](https://github.com/ppy/osu/files/5358537/database.log)
[performance.log](https://github.com/ppy/osu/files/5358535/performance.2.log)
[runtime.log](https://github.com/ppy/osu/files/5358536/runtime.2.log)

**Comment by peppy** [comment] 2020-10-10 06:48
Duplicate of https://github.com/ppy/osu/issues/10340?

**Comment by bdach** [comment] 2020-10-10 07:23
Seems like it, closing. Looks like xamarin doesn't like our `BindCollectionChanged` callbacks for some reason...

**Closed by bdach** 2020-10-10 07:23 UTC
