### ISSUE TITLE
black screen on start, only sound

### ISSUE THREAD

**Issue by HipHopCat** [ppy/osu#4067] opened 2019-01-16 05:40 UTC
**Describe your problem:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:** 

**Computer Specifications:**

**Comment by smoogipoo** [comment] 2019-01-16 07:07
Does it fix itself when you resize the window by any chance?

**Comment by smoogipoo** [comment] 2019-01-16 07:08
Duplicate of https://github.com/ppy/osu/issues/4068, closing this one.

**Closed by smoogipoo** 2019-01-16 07:08 UTC
Labels: startup crash/issue
