### ISSUE TITLE
osu! immediate crash due to external monitor on macOS

### ISSUE THREAD

**Issue by divuyes** [ppy/osu#19077] opened 2022-07-12 00:15 UTC
### Type

Crash to desktop

### Bug description

When launching the game, it tries to open for 2 seconds and then crashes before the standard "osu! quit unexpectedly" pop-up. This happened on all my older versions, and when I updated to the latest version, it didn't fix it. This only happened today and it was perfectly fine on other versions before, which is odd. I'm on macOS Big Sur 11.6, using the Apple Silicon build on an M1 MacBook Pro 13". I did see this bug for the first time while using Sidecar and putting osu! on my iPad display, however the issue did not cease after disconnecting from Sidecar so I doubt that it is the cause. The runtime.log was not very helpful, so I tried running the Unix Executable by going into osu!.app's package contents, then going into Contents, MacOS, and running osu! Here is the resulting output in my terminal.
```
divu@Advaithas-MacBook-Pro ~ % /Users/divu/Downloads/osu\!\ 2.app/Contents/MacOS/osu\! ; exit;
2022-07-11 19:11:18.852 osu![1279:31696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2022-07-11 19:11:18.852 osu![1279:31696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
2022-07-11 19:11:18.852 osu![1279:31696] NSDocumentController Info.plist warning: The values of CFBundleTypeRole entries must be 'Editor', 'Viewer', 'None', or 'Shell'.
zsh: segmentation fault  /Users/divu/Downloads/osu!\ 2.app/Contents/MacOS/osu!
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

### Version

2022.709.1

### Logs

Only the runtime.log was updated after the failed launch. Even still, little to nothing actually is seen in the log.
[runtime.log](https://github.com/ppy/osu/files/9088277/runtime.log)

**Comment by frenzibyte** [comment] 2022-07-12 00:17
Seems like you might be hitting https://github.com/ppy/osu/issues/18983 given that it occurred first when you used Sidecar.

**Comment by divuyes** [comment] 2022-07-12 00:21
Unplugged everything from my MacBook except for my headphones, and still had sidecar connected, and it worked. Seems to be an issue with my external display, despite not trying to launch it on there.

**Comment by frenzibyte** [comment] 2022-07-12 00:22
Safe to mark it as a duplicate of both linked issues then.

**Closed by frenzibyte** 2022-07-12 00:22 UTC
