### ISSUE TITLE
Add ability to add SongTicker to the gameplay screen

### ISSUE THREAD

**Issue by i3ym** [ppy/osu#12853] opened 2021-05-18 17:39 UTC
**Describe the new feature:** 
Ability to add currently playing song (which I beleive is a Songticker element) to the gameplay screen with the new skinning system.
WIll probably be useful for livestreaming

**Comment by Joehuu** [comment] 2021-05-18 17:46
Duplicate of https://github.com/ppy/osu/issues/9461

**Closed by Joehuu** 2021-05-18 17:46 UTC
Labels: proposal
