### ISSUE TITLE
osu!mania map stutter at the start

### ISSUE THREAD

**Issue by rgndxzzk** [ppy/osu#30926] opened 2024-11-30 01:30 UTC
### Type

Game behaviour

### Bug description

gameplay halts in the beginning of the map
https://osu.ppy.sh/beatmapsets/2024427#mania/4246312
https://osu.ppy.sh/beatmapsets/555076#mania/1175035
had it happen on many maps, these two for example
doesn't happen on maps that have skip at the start

### Screenshots or videos

https://github.com/user-attachments/assets/c697f490-df44-4514-95aa-c1b3f18b57dd

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17963777/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-11-30 03:00
Duplicate of https://github.com/ppy/osu/issues/22488

**Closed by Joehuu** 2024-11-30 03:00 UTC
