### ISSUE TITLE
As loading finishes, alt tabbing to other window and back after game auto pauses causes massive issues

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#4712] opened 2019-05-05 23:04 UTC
Its in the name, Weird lines and stuff appear on the screen as shown in the video and image
https://i.imgur.com/8FhPwMu.png
2019.504.0

This might be suitable for this post: AMD Radeon HD 7700 - 16GB Ram - AMD Ryzen 5 1500X,

I've tested with:
Firefox
Discord
Task Manager
AMD Radeon Settings Panel

All of them cause the same glitch, so im guessing its just a system-wide thing

https://www.youtube.com/watch?v=scNqJLigxGc&feature=youtu.be

**Comment by Morilli** [comment] 2019-05-05 23:05
Duplicate of #4605.

**Closed** 2019-05-05 23:07 UTC
