### ISSUE TITLE
Osu!Lazer failed to set tablet

### ISSUE THREAD

**Issue by Ritsukii** [ppy/osu#12135] opened 2021-03-21 20:51 UTC
Everytime I use my stylus to play it glitches, I don't know exactly why, but it says this:
![image](https://user-images.githubusercontent.com/81114694/111919884-c338bb00-8a94-11eb-8598-fef5b38834a4.png)

And here how it looks like:
https://www.youtube.com/watch?v=7q9Rzu9oHOw

**Comment by bdach** [comment] 2021-03-21 21:06
Duplicate of #12120 (at least, I think "cursor glitching"
 was also mentioned elsewhere)

**Closed by bdach** 2021-03-21 21:06 UTC

**Comment by Starwort** [comment] 2021-03-22 13:35
> (at least, I think "cursor glitching" was also mentioned elsewhere)

By me :P
For me, it was an issue with the OEM drivers conflicting with the OTD driver - disabling the OEM driver fixed the issue (but disabled my tablet elsewhere, for obvious reasons), and disabling osu!'s driver (turning off 'use tablet') worked also

@Ritsukii, does that solve your cursor issues?

**Comment by Ritsukii** [comment] 2021-03-22 18:51
> @Ritsukii, does that solve your cursor issues?

I disabled "tablet" setting and it works now. It's weird that this bug or what it was appeared so random bcs I had the tablet setting enabled before and I didn't had any problems

**Comment by Starwort** [comment] 2021-03-22 19:10
osu! now uses OTD drivers and that apparently breaks some stuff - I think the issues are mostly getting sorted out in the next framework update
