### ISSUE TITLE
score multiplier and speed bug

### ISSUE THREAD

**Issue by lexXXXey** [ppy/osu#10523] opened 2020-10-16 06:01 UTC
**Describe the bug: I have score multiplier 1.12x but speed in 1.01x** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:2020.1009.0** 
[12.zip](https://github.com/ppy/osu/files/5389496/12.zip)

**Comment by bdach** [comment] 2020-10-16 06:02
Duplicate of #7698

**Closed by bdach** 2020-10-16 06:02 UTC
