### ISSUE TITLE
Timing Selection goes back one when clicking on it.

### ISSUE THREAD

**Issue by Vadeblade** [ppy/osu#21172] opened 2022-11-08 09:05 UTC
### Type

Game behaviour

### Bug description

Timing selection I pick goes to an earlier one when selecting it.

### Screenshots or videos

https://user-images.githubusercontent.com/20312791/200521560-b86bcbeb-e7c0-47f2-99b4-7b4b483b178e.mp4

### Version

2022.1101.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9959435/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9959436/updater.log)
[database.log](https://github.com/ppy/osu/files/9959437/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9959438/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9959439/network.log)
[performance.log](https://github.com/ppy/osu/files/9959440/performance.log)

**Comment by peppy** [comment] 2022-11-09 08:48
Could you please attach the beatmap you are testing with (or a link to it)?

This is likely going to be a floating point precision issue.

**Comment by Vadeblade** [comment] 2022-11-16 10:45
I've tried recreating the issue multiple times and couldn't do it. Immediately after I deleted most the timing points in the map after reporting since I need to for the timing of the song.

**Comment by peppy** [comment] 2022-11-17 04:45
I can imagine that this can definitely happen due to the `trackActivePoint` flow running...

https://github.com/ppy/osu/blob/31a447fda0532fcf15f8c8251ca890c533386492/osu.Game/Screens/Edit/Timing/TimingScreen.cs#L171-L200

..at the same time a seek is performed, but will need a reliable repro case to figure out what is going on (the fact it's using `clock.CurrentTimeAccurate` *should* be enough in therory). If anyone happens to find one please leave more information.

**Comment by Joehuu** [comment] 2024-09-20 19:27
Closing as the OP reproduced this on a custom beatmap. Probably not an issue after https://github.com/ppy/osu/pull/29532 anyway.

**Closed by Joehuu** 2024-09-20 19:27 UTC
Labels: area:editor
