### ISSUE TITLE
Storyboard elements don't align with the background on some maps

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu#13865] opened 2021-07-12 13:47 UTC
**Describe the bug:** Storyboard elements don't align with the background on some maps
https://osu.ppy.sh/beatmapsets/49933#osu/180993
probably also because i play on 16:9 aspect ratio

**Screenshots or videos showing encountered issue:** 
![osu_2021-07-12_17-37-37](https://user-images.githubusercontent.com/5400432/125297669-7f660c00-e338-11eb-9b0f-265190331fcc.jpg)

**osu!lazer version:** 
2021.707.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/6801879/logs.zip)

---
apologies if duplicate, i could not find an issue about the exact same thing.

**Comment by Walavouchey** [comment] 2021-07-18 08:33
duplicate of #2086 pretty sure

**Comment by bdach** [comment] 2021-07-18 10:37
Seems about right. Closing as duplicate.

**Closed by bdach** 2021-07-18 10:37 UTC
Labels: area:storyboard
