### ISSUE TITLE
Crashes on skin changes due to sample disposal

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ppy/osu#5798] opened 2019-08-21 23:02 UTC
**Describe the crash:** When changing the skin while seeking, hitsounds will disappear and the game hardcrashes.

**Reproduction steps:**
- Start a beatmap with auto, a custom skin and effect volume enabled
- During gameplay, disable effect sounds
- Seek forward, and switch to default skin while seeking
- Seek backward, and enable effects volume while seeking
- Hitsounds should not play anymore. After a while (~1 minute) the game will crash (when gen2 GC runs).

**Screenshots or videos showing encountered issue:** [Video](https://streamable.com/bivsw)

**osu!lazer version:** 2019.814

**Logs:** [runtime.log](https://github.com/ppy/osu/files/3527648/runtime.log)

**Comment by peppy** [comment] 2019-08-22 05:27
I couldn't reproduce this exactly, but we are aware of issues with skinnable sounds not updating as they should on rewind.

**Comment by peppy** [comment] 2019-09-19 04:38
Trying to figure out a solid repro for this but can not. Also cannot see how this would happen logically. Very weird one – threading may be involved.

**Comment by smoogipoo** [comment] 2019-09-20 06:51
I can imagine how this happens, likely scheduled skin changes.

**Comment by peppy** [comment] 2019-11-01 01:24
@HoLLy-HaCKeR can you still repro this one?

**Comment by HoLLy-HaCKeR** [comment] 2019-11-02 01:05
Yes, just pulled latest master and it crashed while following my repro steps, doing the backwards seek.

**Comment by peppy** [comment] 2020-10-07 09:16
This happens due to the fact that `SkinChanged` is scheduled. It is run on the `DrawableHitObject` first, which then triggers a `Play` on the sample, *just* before the `SkinnableSound` runs its own `SkinChanged`, disposing the (just-played) samples and reinitialising.

This could be resolved by always guarding `Play` with a schedule (already done in `PausableSkinnableSound`) and moving the `RequestedPlaying` logic to the base class (allowing for `Stop` calls to remain unscheduled – we want `Stop` to always work even if the drawable is not alive for sanity reasons).

The blocker here is that `SampleChannel.Stop` throws an exception on disposed, which makes it very hard to fire it without a schedule (it may still throw), and there's no way to know if it's disposed or not:

https://github.com/ppy/osu-framework/blob/8736820593990436efe46ea50e370c3bef6bc948/osu.Framework/Audio/Sample/SampleChannel.cs#L35-L36

**Comment by smoogipoo** [comment] 2020-10-08 04:18
I don't understand what the issue is there. A call to `Play` _just_ before disposal should be completely fine, because it's done synchronously (not on the audio thread). The error would occur if `Play` was somehow called on just _disposed_ samples, which is the inverse of what you mention. How is that happening?

**Comment by peppy** [comment] 2020-10-08 04:21
- skin change is fired (disposes previous skin stores / samples)
- DHO receives skin change fires play on skinnablesound (disposed channel play call) <- currently failure
- SkinnableSound receives skin change and updated samples to new skin

This scenario is already fixed via the merged PR, but SkinnableSound is still unsafe if Play is called from a parent, before its local scheduler has been run.

**Comment by smoogipoo** [comment] 2020-10-09 10:55
Not sure what the best fix is there then. Do we really want to schedule `Play()`? My biggest concern with that is adding a 1-frame delay to hitsounds - it would need to be very thoroughly tested at the very least. Perhaps we want something like Play()/Stop() to not throw exceptions on disposal and instead exit silently? I'm also not sure how to handle that sanely too.

**Comment by peppy** [comment] 2021-02-09 10:09
@smoogipoo just bumping this into your scope of awareness when you revisit sample changes. not sure if it's something we can work into those changes or not. if it isn't, maybe we should unmilestone this as it seems to be a very edge case / rare crash with a complicated path to resolution.

**Comment by peppy** [comment] 2021-02-16 07:14
A few things to update on this one:

Firstly, it no longer fails, but potentially due to an oversight: `Sample.GetChannel` doesn't throw if it is disposed. I think a disposal check *probably* needs to be added there framework side?

Furthermore, it seems to be a lot harder (aka impossible) to reproduce these days. I was able to force a failure by explicitly calling `skin.OldValue?.Dispose()` in the `skinChanged` callback in [SkinManager](https://github.com/ppy/osu/blob/de9d075f941fe840e14e9a576e3329956884ee4c/osu.Game/Skinning/SkinManager.cs#L57) and the aforementioned `IsDisposed` check adding to `GetChannel`. I'm not sure if something is holding a reference to the old skin that wasn't before, but that may be enough to avoid the issue manifesting (although I'm not sure that we can call this "solved" as a result).

To rephrase the problem here, since working through this thread was quite hard to understand:

- When skins are changed, the previous skin is disposed via finalizer. As long as nothing holds a reference to the skin itself, this will cause its components (including the `SampleStore`) to be disposed.
- Due to `skinChanged` being scheduled in `DrawableHitObject`, there's a change a sample from the previous skin will be played before the samples are update to the new skin.

Possible resolutions I can see:

- Keep a reference to the old skin somewhere in our osu-side sample/sound classes (if we actually want to rely on finalizer logic still, not 100% on that)
- Remove the [explicit disposal](https://github.com/ppy/osu/blob/de9d075f941fe840e14e9a576e3329956884ee4c/osu.Game/Skinning/LegacySkin.cs#L106-L107) of the sample stores in `LegacySkin`. As `PoolableSample` already keeps a reference to the sample store (for retrieval purposes) this would avoid the issue.
- Remove the finalizer on `Skin`. As we don't manually dispose of the skin the sample store would remain active until it goes out of context (it would eventually be cleaned up by `AudioComponent`'s finalizer.

**Comment by bdach** [comment] 2021-02-16 19:10
I can definitely get behind removing a finaliser if that fixes the issue. I'm not even entirely certain why `Skin` has one.

Yielding object lifetime management to the poolable also sounds like an agreeable solution to me, but I'd probably prefer removing the finaliser.

**Comment by smoogipoo** [comment] 2021-02-17 05:39
I haven't gone through this issue in detail / don't remember exactly what it was about, but the sample store would not eventually be cleaned up by the `AudioComponent` finalizer. It's added to the `AudioManager`'s hierarchy and thus will be referenced by the `AudioManager` itself. The disposal is there to explicitly mark it as dead so that it can be removed from the `AudioManager`'s hierarchy.

**Comment by peppy** [comment] 2021-02-17 05:40
Right, which leaves us with only resolution option 1?

**Comment by peppy** [comment] 2021-02-17 05:42
Also @smoogipoo I would appreciate reading https://github.com/ppy/osu/issues/5798#issuecomment-779638148 in full. It sums up the issue and also brings to light an issue with your recent sample changes which should likely be addressed. I still can't proceed forward on this issue without more feedback from you on it.

**Comment by bdach** [comment] 2021-03-18 18:46
Renaming this for searchability, pinning, and setting priority 0. 4 duplicates in 6 days seems like enough to warrant this.

**Comment by peppy** [comment] 2021-03-20 14:49
Somewhere along the way the fix for this broke. I tried rolling back the `IDisposable` changes towards the end of the fix PR but that wasn't enough to fix, so it's something deeper. I plan to look into this as a priority over the next day.

**Closed** 2021-03-23 07:44 UTC
Labels: area:skinning, priority:0, type:audio
