### ISSUE TITLE
Beatmap import fails when multiple difficulties have the same BeatmapID

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#2970] opened 2018-07-07 22:58 UTC
When importing a beatmapset that has multiple difficulties (2 are enough) which have the same "BeatmapID" set in the .osu files, osu!lazer will throw an error and fail to import the beatmapset.

In the log files this looks similar to this:
```
07.07.2018 22:49:51: Failed executing DbCommand (2ms) [Parameters=[@p0='?', @p1='?', @p2='?', @p3='?', @p4='?', @p5='?', @p6='?', @p7='?' (Size = 64), @p8='?', @p9='?', @p10='?' (Size = 32), @p11='?', @p12='?', @p13='?' (Size = 83), @p14='?', @p15='?', @p16='?', @p17='?', @p18='?' (Size = 30), @p19='?', @p20='?' (Size = 13), @p21='?'], CommandType='Text', CommandTimeout='10']
07.07.2018 22:49:51: INSERT INTO "BeatmapInfo" ("AudioLeadIn", "BaseDifficultyID", "BeatDivisor", "BeatmapSetInfoID", "Countdown", "DistanceSpacing", "GridSize", "Hash", "Hidden", "LetterboxInBreaks", "MD5Hash", "MetadataID", "OnlineBeatmapID", "Path", "RulesetID", "SpecialStyle", "StackLeniency", "StarDifficulty", "StoredBookmarks", "TimelineZoom", "Version", "WidescreenStoryboard")
07.07.2018 22:49:51: VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21);
07.07.2018 22:49:51: SELECT "ID"
07.07.2018 22:49:51: FROM "BeatmapInfo"
07.07.2018 22:49:51: WHERE changes() = 1 AND "ID" = last_insert_rowid();
07.07.2018 22:49:51: An exception occurred in the database while saving changes for context type 'osu.Game.Database.OsuDbContext'.
07.07.2018 22:49:51: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapInfo.OnlineBeatmapID'.
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: --- Ende der internen Ausnahmestapelüberwachung ---
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: Failed executing DbCommand (0ms) [Parameters=[@p10='?', @p11='?' (Size = 64), @p12='?', @p13='?', @p14='?'], CommandType='Text', CommandTimeout='10']
07.07.2018 22:49:51: INSERT INTO "BeatmapSetInfo" ("DeletePending", "Hash", "MetadataID", "OnlineBeatmapSetID", "Protected")
07.07.2018 22:49:51: VALUES (@p10, @p11, @p12, @p13, @p14);
07.07.2018 22:49:51: SELECT "ID"
07.07.2018 22:49:51: FROM "BeatmapSetInfo"
07.07.2018 22:49:51: WHERE changes() = 1 AND "ID" = last_insert_rowid();
07.07.2018 22:49:51: An exception occurred in the database while saving changes for context type 'osu.Game.Database.OsuDbContext'.
07.07.2018 22:49:51: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: --- Ende der internen Ausnahmestapelüberwachung ---
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: Import of 358119 Sarah Connor - Cold As Ice (PH Electro Nightcore Mix) failed and has been rolled back.
07.07.2018 22:49:51: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'UNIQUE constraint failed: BeatmapSetInfo.OnlineBeatmapSetID'.
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
07.07.2018 22:49:51: bei Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: --- Ende der internen Ausnahmestapelüberwachung ---
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: bei Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
07.07.2018 22:49:51: bei osu.Game.Database.DatabaseWriteUsage.Dispose(Boolean disposing)
07.07.2018 22:49:51: bei osu.Game.Database.DatabaseWriteUsage.Dispose()
07.07.2018 22:49:51: bei osu.Game.Database.ArchiveModelManager`2.Import(ArchiveReader archive)
```

Easily reproducable with the beatmaps [Shadow gate to love](https://osu.ppy.sh/s/630109) and [Monster](https://osu.ppy.sh/s/661483).
Log file:
[database.log](https://github.com/ppy/osu/files/2173160/database.log)

**Comment by peppy** [comment] 2018-07-08 01:38
Does this happen if you are logged in?

**Comment by Morilli** [comment] 2018-07-08 10:55
Yes, it does.

**Comment by peppy** [comment] 2018-07-08 11:06
I can see how this could happen, thanks for the detailed report.

**Comment by Morilli** [comment] 2018-07-10 13:21
I just tested again, and all except one beatmapset get imported correctly now. The failing one: 
[Sarah Connor - Cold As Ice (PH Electro Nightcore Mix).zip](https://github.com/ppy/osu/files/2180494/Sarah.Connor.-.Cold.As.Ice.PH.Electro.Nightcore.Mix.zip)

I really don't know why it failed but apparently there must still be a problem with importing.

**Comment by peppy** [comment] 2018-07-10 17:29
I can see there are basically duplicates of many difficulties in there, but it still imports fine for me. Could you share your error log for that specific failure?

**Comment by Morilli** [comment] 2018-07-10 17:32
Hm, that's weird, maybe my installation is faulty in some way? Anyways, here's the log file: 
[database.log](https://github.com/ppy/osu/files/2181477/database.log)

**Comment by peppy** [comment] 2018-07-10 17:47
Figured it out with the log, thanks!

**Comment by Morilli** [comment] 2018-07-10 18:07
Makes me wonder why it didn't fail the import for you though..

**Comment by peppy** [comment] 2018-07-10 18:08
It will only fail if logged in. It was caused by the online lookup of beatmap IDs assigning the same online ID to both of the duplicate difficulties contained in that osz file. This was done *after* the duplicate checking logic had run.

**Comment by Morilli** [comment] 2018-07-10 18:12
Ah, that makes sense then!

**Comment by Morilli** [comment] 2018-07-10 20:51
Hm, after checking something I'm not sure if allowing offline imports for such maps is a good idea. These beatmaps will not get an OnlineBeatmapID assigned, therefore lazer won't be able to fetch any online leaderboards.

**Comment by peppy** [comment] 2018-07-10 22:22
This is intended. It will be resolved in the future when it matters.

**Comment by peppy** [comment] 2018-07-10 22:29
Are you going to fix this? If not, please see my last comment.

**Closed** 2018-07-13 09:09 UTC
Labels: bug, import, pending review
