### ISSUE TITLE
osu! crashes when exiting song select whilst holding "SkinnableSprite" 

### ISSUE THREAD

**Issue by 02Rusty** [ppy/osu#18716] opened 2022-06-15 16:22 UTC
### Type

Crash to desktop

### Bug description

When you are in the Skin Editor screen hold a sprite just like I did in the video and press escape to the Osu Logo Screen

### Screenshots or videos

https://user-images.githubusercontent.com/70040605/173876882-12814cf6-8e00-4f10-b714-ca621b0a94f2.mp4

### Version

2022.615.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/8911293/logs.zip)

**Comment by bdach** [comment] 2022-06-15 16:26
I'd say that 99% of the problem is that the drag continued after the skin editor was exited. It shouldn't do this.

**Comment by mouzedrift** [comment] 2022-06-15 16:49
i believe that this is a duplicate of #12692

**Comment by bdach** [comment] 2022-06-15 16:58
It's a duplicate but I'm going to close the other one this time because this already has a sentry link and everything so it's less red tape this way.

**Closed** 2022-06-20 05:47 UTC
Labels: type:reliability, priority:1, area:skin-editor
