### ISSUE TITLE
black screen, no navigation buttons, no sound after mashing escape

### ISSUE THREAD

**Issue by rokisv** [ppy/osu#8977] opened 2020-05-08 14:53 UTC
The bug is black screen, no main menu buttons, and no music playing in levels
the issue was made when i clicked play solo and instantly mashed esc to go back
the only sound that i could hear is the main button idle shake noise
I dont really remember, but i think i mashed 1 at the same time,  so could it be that i got stuck in shutting down state?

edit:
if you mashed the main osu logo you could still start the levels, the level select menu was working fine, but there was no sound in select menu, neither the levels

> 
![osu_2020-05-08_17-39-24](https://user-images.githubusercontent.com/12939300/81417292-a54fb980-9153-11ea-8d32-559f81b7be54.jpg)
![osu_2020-05-08_17-39-27](https://user-images.githubusercontent.com/12939300/81417293-a5e85000-9153-11ea-8c57-f3bd59c793b1.jpg)

**osu!lazer version:** 
2020.508.2

**Logs:**
not sure witch should i attach so im attaching all the files in my folder
[performance.log](https://github.com/ppy/osu/files/4599702/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/4599705/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4599706/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4599707/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4599708/updater.log)
[network.log](https://github.com/ppy/osu/files/4599709/network.log)

**Comment by bdach** [comment] 2020-05-08 18:09
I'm a little perplexed as to what would lead to so many drawables/textures missing...

* If there are device driver updates for your graphics card, please try installing them.
* Could you try pressing <kbd>Ctrl</kbd>+<kbd>F3</kbd> and attach a screenshot of the *Texture Atlases* window that should appear?
* In addition, you could also record a video in which you press <kbd>Ctrl</kbd>+<kbd>F1</kbd>, hover over the screen, click on some of the visible elements, then on the *up one parent* button etc. so that we can check if there isn't anything funny with the drawable hierarchy.
* If you can navigate to settings using <kbd>Ctrl</kbd>+<kbd>O</kbd>, could you try toggling the *Bypass front-to-back render pass*? (mostly clutching at straws here, but maybe I'll be surprised)

**Comment by rokisv** [comment] 2020-05-08 18:39
sadly, i cannot replicate the bug right now,
The drivers are as far as i know up to date
if it happens again i will take those screenshots that you asked.

**Comment by peppy** [comment] 2020-05-10 03:15
I do wonder if this is related to https://github.com/ppy/osu/pull/8982 somehow.. It looks like loading got interrupted but didn't crash, leaving the game in a not-to-started state.

**Comment by peppy** [comment] 2020-06-03 03:15
Going to close this for now as it may quite likely have been fixed (as mentioned above), please comment if you manage to reproduce again.

**Closed by peppy** 2020-06-03 03:15 UTC
Labels: area:main menu, missing details
