### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by sdfsdfdsfs3** [ppy/osu#8836] opened 2020-04-22 15:08 UTC
logs https://drive.google.com/open?id=11TgfREtt_AVz49qOWrGP3IDlM6odgseKUBwCbLN5YvM

**Computer Specifications:** 
win 7

**Comment by bdach** [comment] 2020-04-22 17:00
Duplicate of #3984

**Closed by bdach** 2020-04-22 17:00 UTC
