### ISSUE TITLE
osu! lazer needs more than 1 cursor (mobile)

### ISSUE THREAD

**Issue by TheMemeGuy213** [ppy/osu#8190] opened 2020-03-09 21:30 UTC
Just like _osu!evolution,_ we want **multiple** **cursors** to the game because,

It would be hard, more likely single note maps, 

it would be nice tho, most _osu!droid_ players would use 2/3/4 fingers on the left, and the latter would be only 1 finger. 

Maybe you can add like a **zone** **that** **can** **be** **adjusted** in the settings, and we want it to switch modes like: **Single** **Tap** **Mode** **(1** **Finger** **Tapping)** and **Streaming** **Mode** **(Multiple** **Finger** **Tapping).** 

I appreciate all osu!devs in advance.

**Comment by bdach** [comment] 2020-03-09 21:38
Duplicate of #4201

**Closed by bdach** 2020-03-09 21:38 UTC
