### ISSUE TITLE
Cursor hidden on iOS

### ISSUE THREAD

**Issue by shiro-h** [ppy/osu#10276] opened 2020-09-28 06:59 UTC
**Describe the bug:** cursor is not showing wright (missing) on gameplay or not on gameplay this is on ios 
Using touchscreen
**Screenshots or videos showing encountered issue:** ![image](https://user-images.githubusercontent.com/68083850/94400020-03c91300-019b-11eb-9841-80a2fa2a849b.png)
![image](https://user-images.githubusercontent.com/68083850/94400033-09265d80-019b-11eb-9a84-b254b57fdea1.png)
**osu!lazer version:** 
Newest (0.1) 2020.925.0
**Logs:**

**Comment by smoogipoo** [comment] 2020-09-28 07:02
While using touchscreen, or while using external devices (mouse/tablet)? Because this is intended when using touchscreen.

**Comment by shiro-h** [comment] 2020-09-28 07:03
While using touchscreen

**Comment by smoogipoo** [comment] 2020-09-28 07:11
When/why do you require seeing the cursor? I don't think this is what we want.

**Comment by shiro-h** [comment] 2020-09-28 07:53
I need the cursor in game and on main hud cuz i plan to use mouse and keyboard on iOS Already bought the items

**Comment by peppy** [comment] 2020-09-28 07:55
The cursor will display if you use a mouse.

**Comment by smoogipoo** [comment] 2020-09-28 07:56
Closing as answered.

**Comment by peppy** [comment] 2020-09-28 07:56
Have tested and confirmed it does, indeed, display.

**Comment by shiro-h** [comment] 2020-09-28 07:57
Could have just said earlier thanks!

**Closed** 2020-09-28 07:56 UTC
Labels: platform:iOS, type:UX
