### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by Liebelts** [ppy/osu#3651] opened 2018-10-28 23:00 UTC
Hey a time ago i discovered the game doesnt run in 32-bit computers so if you can do a 32 bit version i would be thankful

**Comment by smoogipoo** [comment] 2018-10-29 04:00
Duplicate of https://github.com/ppy/osu/issues/3524 .

32-bit binaries are not provided right now. Feel free to go ahead and compile osu! yourself.

**Closed by smoogipoo** 2018-10-29 04:00 UTC

**Comment by Liebelts** [comment] 2018-10-29 04:08
But doing it as last plan isn't viable ?

**Comment by smoogipoo** [comment] 2018-10-29 04:10
You're part of the literal 1%, it just isn't worth it at this point to get all the systems in place (redistribution + updater) while development efforts are focused elsewhere.

**Comment by Liebelts** [comment] 2018-10-29 04:12
Oh OK sorry
