### ISSUE TITLE
Audio playback/rendering issue

### ISSUE THREAD

**Issue by bramnet** [ppy/osu#4822] opened 2019-05-19 01:32 UTC
**Describe the bug:** 

I haven't encountered this beyond one beatmap, but the audio isn't playing back right (seemingly random sections are cut out), and the waveform on the editor seems to suggest the audio file is the issue, but when playing back the audio file directly, the missing sections are playing just fine.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/26863024/57976610-22fe4080-79aa-11e9-9e26-48dd548eaa2d.png)
video of playback. The second time is playing directly from the audio file using VLC player: https://1drv.ms/u/s!AnzuAlyaZAYDiIYZSoszmb9Le9CooQ

**osu!lazer version:** 

2019.518.0

**Logs:** 

[performance.log](https://github.com/ppy/osu/files/3194685/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/3194686/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/3194687/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/3194688/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/3194689/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/3194690/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3194691/updater.log)
[database.log](https://github.com/ppy/osu/files/3194692/database.log)
[network.log](https://github.com/ppy/osu/files/3194693/network.log)

**Comment by Joehuu** [comment] 2020-11-03 23:05
I assume the beatmap is https://osu.ppy.sh/beatmapsets/10965#osu/43368 as indicated in the logs. Can't seem to reproduce and the video is unavailable now.

**Comment by peppy** [comment] 2020-11-04 04:19
Going to close this for the time being due to the above. May have been an actual broken audio file somewhere in the download / import chain.

**Closed by peppy** 2020-11-04 04:19 UTC
Labels: framework-fix-required, missing details
