### ISSUE TITLE
Crash after selecting a map

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#7216] opened 2019-12-15 01:22 UTC
**Describe the crash:** 
crash while trying to play a map, "unhandled error, reported to devs" message has been shown, so Im reporting this issue just in case.
so far Ive only encountered the crash by playing a map with DT, only happens with the newest version.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.1213.0
**Logs:** 
unable to find logs with correct time stamps related to the crash
**Computer Specifications:** 
i7 9700k
gtx2080
ddr4 16gb

**Comment by bdach** [comment] 2019-12-15 07:56
We can't proceed without logs here. Where have you checked? The locations are:

* `%AppData%/osu/logs` (on Windows),
* `~/.local/share/osu/logs` (on Linux and macOS).

Also please state your OS.

**Comment by dolkilu** [comment] 2019-12-15 08:05
found it now, on windows
[runtime.log](https://github.com/ppy/osu/files/3964705/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3964706/performance.log)
[network.log](https://github.com/ppy/osu/files/3964707/network.log)

2019-12-15 01:20:16: Screen changed → PlayerLoader
2019-12-15 01:20:16: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-12-15 01:20:16: An unhandled error has occurred.
2019-12-15 01:20:16: System.ArgumentNullException: Value cannot be null.
2019-12-15 01:20:16: at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
2019-12-15 01:20:16: at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
2019-12-15 01:20:16: at osu.Framework.Graphics.Drawable.Finalize()

**Comment by bdach** [comment] 2019-12-15 08:13
Thanks, that's helpful. Just for extra information, does this happen every time, or just sometimes?

**Comment by dolkilu** [comment] 2019-12-15 09:28
Turns out it's about the map not about DT, it's just a coincidence that the map I play DT on crashes, should I edit the post?
It happens on maps that have the issue only, I tried to replicate the crash, the crash happens every time on the selected map. only happens after this update.
example of map that crashed, I can easily find them by randoming maps
https://osu.ppy.sh/beatmapsets/368985#osu/808848  Lemur diff
https://osu.ppy.sh/beatmapsets/246416#osu/567607 laurier's insane
https://osu.ppy.sh/beatmapsets/191471#osu/458813 gu's insane

**Comment by peppy** [comment] 2019-12-15 15:55
Can't reproduce with the provided beatmap links, unfortunately.

**Comment by smoogipoo** [comment] 2019-12-16 01:57
Does this happen with the default lazer skin?

**Comment by dolkilu** [comment] 2019-12-16 05:51
> 
> 
> Does this happen with the default lazer skin?

yes, tried with both team osu! skin and it still crashes


failed to re-import the map with and without deleting the map/from osu!direct, 
error shown 
![image](https://user-images.githubusercontent.com/16611027/70882151-c0395a00-2009-11ea-98f5-9f2cb544eb9b.png)
![image](https://user-images.githubusercontent.com/16611027/70882163-c92a2b80-2009-11ea-9ed2-23e6e907d13c.png)
I can still import other working maps from the site/direct.
Im using symbolic link because Ive limited C drive space, will it causes database issue?

**Comment by dolkilu** [comment] 2019-12-16 17:21
Just reporting that the map I had issue with still crashes ,although it seems there is no related update on the newest version's change log.

**Comment by peppy** [comment] 2019-12-17 06:15
It would be helpful if you can debug this. Not many details to work with here.

**Comment by dolkilu** [comment] 2019-12-17 14:27
Although I want to help, I have very little programming knowledge :(

**Comment by mouzedrift** [comment] 2019-12-17 17:35
i have the same issue and noticed that it only crashes when you compile the release version while the debug version doesnt crash

**Comment by smoogipoo** [comment] 2019-12-18 12:24
This is caused by https://github.com/ppy/osu-framework/issues/3120, and has since been fixed (will be fixed in the next release).

**Comment by mouzedrift** [comment] 2019-12-19 15:25
shouldnt this be fixed in version 2019.1219.0 ? im still crashing

**Comment by bdach** [comment] 2019-12-19 15:29
@mouzedrift Are you crashing in the exact same scenario, with the same exact stack trace? You'll have to attach some logs/details for us to know otherwise - we're not mind readers.

**Comment by mouzedrift** [comment] 2019-12-19 15:59
>Are you crashing in the exact same scenario, with the same exact stack trace?

Yup, everything is the same. I've tried these 3 maps provided by dolkilu

https://osu.ppy.sh/beatmapsets/368985#osu/808848 Lemur diff
https://osu.ppy.sh/beatmapsets/246416#osu/567607 laurier's insane
https://osu.ppy.sh/beatmapsets/191471#osu/458813 gu's insane

**Logs:**
[database.log](https://github.com/ppy/osu/files/3984389/database.log)
[network.log](https://github.com/ppy/osu/files/3984390/network.log)
[performance.log](https://github.com/ppy/osu/files/3984391/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3984392/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3984393/updater.log)

**Comment by dolkilu** [comment] 2019-12-19 16:02
tested with default skins and re-imported, still crashes.
[runtime.log](https://github.com/ppy/osu/files/3984381/runtime.log)

2019-12-19 15:52:55: beatmap changed from "solfa feat.Chata - I will (Fycho) [Normal]" to "solfa feat.Chata - I will (Fycho) [Laurier's Insane]"
2019-12-19 15:52:55: working beatmap updated to solfa feat.Chata - I will (Fycho) [Laurier's Insane]
2019-12-19 15:52:55: Screen changed → PlayerLoader
2019-12-19 15:52:55: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-12-19 15:52:55: An unhandled error has occurred.
2019-12-19 15:52:55: System.ArgumentNullException: Value cannot be null.
2019-12-19 15:52:55: at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
2019-12-19 15:52:55: at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
2019-12-19 15:52:55: at osu.Framework.Graphics.Drawable.Finalize()



2019-12-19 15:55:51: updating selection with beatmap:24211 ruleset:0
2019-12-19 15:55:51: beatmap changed from "WEAVER - Kuchizuke Diamond (jieusieu) [Easy]" to "WEAVER - Kuchizuke Diamond (jieusieu) [Lemur]"
2019-12-19 15:55:51: working beatmap updated to WEAVER - Kuchizuke Diamond (jieusieu) [Lemur]
2019-12-19 15:55:52: Screen changed → PlayerLoader
2019-12-19 15:55:52: Unhandled exception has been allowed with 0 more allowable exceptions .
2019-12-19 15:55:52: An unhandled error has occurred.
2019-12-19 15:55:52: System.ArgumentNullException: Value cannot be null.
2019-12-19 15:55:52: at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
2019-12-19 15:55:52: at osu.Framework.Graphics.Drawable.dispose(Boolean isDisposing)
2019-12-19 15:55:52: at osu.Framework.Graphics.Drawable.Finalize()

**Comment by bdach** [comment] 2019-12-19 16:03
Will see if I can reproduce in the near future.

**Comment by sora-jp** [comment] 2019-12-20 11:52
I think i figured out the bug. Apparently, when the .NET runtime calls the finalizer during a garbage collection, the order of collection is not guaranteed. This means that sometimes, the fields in the Drawable are collected before the finalizer is run. If the loadLock field happens to be collected before the finalizer is run, then we will try to lock on a null reference, and that always fails. So if the dispose method is called from the finalizer, we need to make sure we don't use any reference fields without checking if they are null. I'll open a PR in osu-framework for this.

**Comment by huoyaoyuan** [comment] 2019-12-20 11:55
> So if the dispose method is called from the finalizer

The better choice is to avoid finalizers. See ppy/osu-framework#3118

**Comment by peppy** [comment] 2019-12-20 12:11
That's not the/an issue. The problem if there's a hard crash occurring in construction (being hidden due to being a native crash, most likely).

`loadLock` is never initialised.

**Comment by sora-jp** [comment] 2019-12-20 12:21
Hmm, will try to reproduce, and see if that's the case.

**Comment by sora-jp** [comment] 2019-12-20 14:31
Yeah, peppy is correct. Tested with a small sample and it seems that fields are never collected before the finalizer is called. So, most likely there is a crash somewhere, that happens during the object construction. Will try to look into it more.

**Comment by a68366** [comment] 2019-12-22 12:45
Got the same issue with https://osu.ppy.sh/beatmapsets/204020#osu/481882 .

While trying to debug the issue i found:
 - It crashes when trying to `dispose()` some `VideoSprite`, which is null.
 - Crash happens after getting `Beatmap.Value.Video` in `osu.Game\Screens\Play\Player.cs`
 - The only(?) place it happens is [here](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/Player.cs#L162 ) and when I pass `null` instead of `Beatmap.Value.Video`, everything works fine
 - If we add `if (path == null) return null;` at the beginning of `GetStream` [here](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/NativeStorage.cs#L74 ), everything works fine

So I guess it's somehow trying to garbage collect `Beatmap.Value.Video` and the problem is in the  [GetVideo()](https://github.com/ppy/osu/blob/master/osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs#L68) or somewhere in the [storage](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/NativeStorage.cs#L74).

I'm bad at C# and new to osu! codebase, so idk how to properly fix the bug. Hope this info helps.

**Comment by sora-jp** [comment] 2019-12-22 14:50
Hmm, did you download the beatmap with or without the video? It could possibly be linked to trying to play a beatmap with video that was downloaded without the video.

**Comment by dolkilu** [comment] 2019-12-22 14:51
I always download without video, maybe that's the problem lol

**Comment by a68366** [comment] 2019-12-22 15:27
I always download without video too.
Tried to delete the song and re-download with a video -- still crashed.
Then i deleted the `client.db`, `client.db-shm`, `client.db-wal` and re-downloaded with a video -- the song played normally.
Some db corruption when downloading without a video?

**Comment by peppy** [comment] 2019-12-25 05:25
@a68366 do you still have a copy of your database? also can you confirm you're using the latest release (not self-compiled)?

i can't reproduce using any of the steps you mentioned, nor can i see how this would happen from a code perspective.

**Comment by mouzedrift** [comment] 2019-12-25 05:54
i dont know if it helps but im just gonna leave my osu lazer database here since the game crashes for me as well. im also using the latest release build (not self compiled)
[osu db.zip](https://github.com/ppy/osu/files/3999710/osu.db.zip)

**Comment by peppy** [comment] 2019-12-25 06:07
thank you, very helpful.

**Comment by peppy** [comment] 2019-12-25 06:10
Unfortunately I can't reproduce a crash. Are you able to also include your "files" folder?

**Comment by mouzedrift** [comment] 2019-12-25 06:12
> Unfortunately I can't reproduce a crash. Are you able to also include your "files" folder?

sure, but its gonna take a while since its 2GB big and my internet is pretty slow.

**Comment by peppy** [comment] 2019-12-25 06:15
that's also weird, since the db you sent only had one track. do you have many skins loaded? you could delete your skins, restart once and it should reduce in size.

**Comment by mouzedrift** [comment] 2019-12-25 06:36
i've had more beatmaps but deleted the database, skins and beatmaps to test a bit more.
anyway here is the files folder:
https://drive.google.com/file/d/1zkoIe0RDcgJp1YowiWKc831j4X2CSBEh/view?usp=sharing

**Comment by peppy** [comment] 2019-12-25 06:57
Thank you. I am able to reproduce.

**Closed** 2019-12-25 09:13 UTC
Labels: framework fix required, gameplay
