### ISSUE TITLE
Drag and drop osz files no longer works on osu!lazer for Linux

### ISSUE THREAD

**Issue by aggalex** [ppy/osu#9378] opened 2020-06-26 15:48 UTC
**Describe the bug:** 

Drag and drop osz files no longer works on osu!lazer for Linux. Also, there is no file associations, so the app cannot be used to open osz files.

**osu!lazer version:** 2020.623.1

**Comment by smoogipoo** [comment] 2020-06-26 15:55
Works fine here, you've provided no usable information.

Logs? Which OS? Are you running with `--sdl`? If not, have you tried running with `--sdl`?

**Comment by bdach** [comment] 2020-06-26 15:59
I also cannot reproduce on my ubuntu 18.04 install.

As a side note you can also import files by providing filenames as command-line arguments to the lazer executable.

**Comment by aggalex** [comment] 2020-06-26 16:04
on elementary OS 5.0

**Comment by bdach** [comment] 2020-06-26 16:05
You've answered one of four questions asked.

Closing until actual details are provided.

**Closed by bdach** 2020-06-26 16:05 UTC
Labels: missing details, platform:linux

**Comment by aggalex** [comment] 2020-06-26 16:08
sdl didn't work, command line args didn't work

**Comment by aggalex** [comment] 2020-06-26 16:09
[database.log](https://github.com/ppy/osu/files/4838010/database.log)
[network.log](https://github.com/ppy/osu/files/4838011/network.log)
[performance.log](https://github.com/ppy/osu/files/4838012/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4838013/runtime.log)

**Comment by bdach** [comment] 2020-06-26 16:10
Logs report that an import has actually completed. There seems to be no issue here.

```
2020-06-26 14:42:51 [verbose]: [?????] Beginning import...
2020-06-26 14:42:51 [verbose]: [fa63c] Import successfully completed!
```

If you're not seeing the beatmap imported you might have a non-standard star range filter set in settings.
