### ISSUE TITLE
Tablet in a state of "clicking" when hovering and in a state of "not clicking" when the pen touches the tablet - the opposite of what is supposed to happen

### ISSUE THREAD

**Issue by eugenekahekili** [ppy/osu#12247] opened 2021-03-31 21:46 UTC
Client: Lazer version 2021.331.0

Issue: While hovering my pen over the tablet in menus, the game thinks I’m constantly touching my pen to the tablet (constantly in a state of “clicking”) when I am not. Likewise, when I touch my pen to the tablet, the game thinks I am hovering. This issue does not persist in stable or any other program on my computer.

Specifications:
Tablet: Wacom Intuos Pro M
Computer:  
  CPU: Intel i7
  Ram: 16gb
  GPU: NVIDIA Geforce RTX 2060 super (8gb vram)

**Comment by eugenekahekili** [comment] 2021-03-31 22:25
> 
> 
> Does this persist when "tablet input" is disabled in the settings? If so, this may be something to report over at https://github.com/OpenTabletDriver/OpenTabletDriver.

No, the issue does not persist when "tablet input" is disabled in the settings.

**Comment by smoogipoo** [comment] 2021-04-01 04:24
Likely due to touch input? Which would put this under https://github.com/OpenTabletDriver/OpenTabletDriver/issues/935

**Comment by peppy** [comment] 2021-04-01 04:30
To confirm whether it's touch related or not, try hovering the pen without your hand touching the tablet. If the issue is still persisting then it's likely a different cause.

**Comment by eugenekahekili** [comment] 2021-04-01 04:32
Tried that and made sure touch input was disabled, issue persisted.

**Comment by smoogipoo** [comment] 2021-04-01 04:33
Best is to make an issue thread on the OTD repository in that case: https://github.com/OpenTabletDriver/OpenTabletDriver/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Closing this as it's not something we can fix our-side.

**Closed by smoogipoo** 2021-04-01 04:33 UTC
Labels: missing details, type:input
