### ISSUE TITLE
There are no any (at least easily discoverable) ways to show only favourite beatmaps in the songs listing screen

### ISSUE THREAD

**Issue by miyukiko-su** [ppy/osu#27012] opened 2024-02-04 05:04 UTC
### Type

Game behaviour

### Bug description

There are no any buttons in the song selection screen to filter songs in order to display only those beatmaps that are marked as favourites in the user's profile. Meanwhile, there is an easily accessible menu for that case in osu stable. So, as a person who uses this feature a lot and switches between "favourites only" and "all downloaded beatmaps" every several days, it is kinda a problem that, instead of just clicking two buttons to switch it, now I can't even find how to perform that at all.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/39649532/02a2b76c-5a6e-472a-adc0-e777471b4eb5)

![image](https://github.com/ppy/osu/assets/39649532/9d13d22b-5120-4f60-939e-262b00d35ae0)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14155569/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-02-04 08:53
Duplicate of https://github.com/ppy/osu/discussions/22798.

With the flow of issue threads that we're facing right now, we highly recommend you search if your issue matches any existing thread in the issues or discussion listing before reporting one. Consult the [contributing guidelines](https://github.com/ppy/osu/blob/ef2e2302d4cf3f049c5637527f99b311d999c43b/CONTRIBUTING.md) for more information.

**Closed by frenzibyte** 2024-02-04 08:53 UTC

**Comment by miyukiko-su** [comment] 2024-02-04 12:07
Apologies for the duplicate. I've tried to look for this entry via search, but unfortunately for some reason there were no any occurrences.

Regarding the actual question, may I ask why was it closed as "not planned" though? Not having this feature in the lazer literally cuts off useful feature that was available and used in stable...

Thanks.

**Comment by bdach** [comment] 2024-02-04 12:24
![image](https://github.com/ppy/osu/assets/20418176/476e28e7-aa99-4b14-991e-bf943b1d8e81)

ask github why it is this way i guess
