### ISSUE TITLE
Opening Osu!lazer inverts my Windows scheme Colors

### ISSUE THREAD

**Issue by Patchy-Sama** [ppy/osu#1704] opened 2017-12-17 06:51 UTC
I tried running it to compatibility mode to Windows XP SP3 still doesn't fix the problem. Tried running it to 640x480 resolution and Disabling Visual Themes, Desktop Composition and display scalling on high DPI settings. Still doesn't fix the problem. I tried running it to Administrator, still no luck running it properly but i can hear the osu theme playing on the bg while my windows got colored inverted.
![2017-12-17 14_45_17-greenshot](https://user-images.githubusercontent.com/34617016/34077229-9939c606-e339-11e7-981f-be8e555209af.png)

**Comment by peppy** [comment] 2017-12-17 07:49
Duplicate of https://github.com/ppy/osu/issues/1388

**Closed by peppy** 2017-12-17 07:49 UTC
