### ISSUE TITLE
Osu!lazer Android: Unable to choose audio files when making beatmaps

### ISSUE THREAD

**Issue by galaxy-01-6182** [ppy/osu#11919] opened 2021-02-27 17:30 UTC
**Describe the bug:** 
When you are on android ( osu!lazer ) and move to edit/make a beatmap, in place where you need to select an audio file for the beatmap, you can't read storage beyond the osu's data folder. And even if you moved the audio inside that folder, you can't find the audio ( .mp3 ) file. This more likely seems to be an android permissions block than a bug, but still, it should read the audio file inside its own folder

I confirmed 
   - Osu!lazer has permissions to view storage
   - the audio exists in the device storage ( as well as in osu's data folder )

**Device Details**
First Device: 
Model: OPPO A53 
Android Version: 10.0 Q

Second Device:
Model: Samsung Galaxy A10s
Android Version: 9.0 Pie

**osu!lazer version:** 
     2021.109.0 

**logs**
 I don't think i can provide logs for this issue. If I can please direct me on how to get the log related to this

**context**
 If this issue is already posted, my apologies for reposting. I would like to get troubleshoots for this. Thanks!

**Comment by bdach** [comment] 2021-02-27 17:41
Duplicate of #11911

**Closed by bdach** 2021-02-27 17:41 UTC
