### ISSUE TITLE
Non-Unicode text

### ISSUE THREAD

**Issue by Kyorie** [ppy/osu#7456] opened 2020-01-06 14:36 UTC
**Describe the bug:** 
Non-Unicode symbols don't display correctly (russian in my case)
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/hzS4aEv.png
https://i.imgur.com/JINaaC2.png
**osu!lazer version:** 
2020.104.0

**Comment by EVAST9919** [comment] 2020-01-06 14:38
Duplicate of https://github.com/ppy/osu/issues/5827

**Closed** 2020-01-06 14:39 UTC
