### ISSUE TITLE
Argon skin uses triangles elements when selecting another skin then re-selecting argon skin

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#20634] opened 2022-10-08 13:59 UTC
### Type

Cosmetic

### Bug description

steps to reproduce
1. argon must be selected by default when booting lazer
2. play any maps on osu/mania while in argon skin (autoplay is affected too)
3. select another skin (any skin) then select argon again
4. argon will use triangles elements on both mania/osu

even when restarting gameplay or switching ruleset, it still uses triangles. the only way to use argon is to select argon then restart lazer

### Screenshots or videos

when argon is selected by default
![osu_2022-10-07_08-01-59](https://user-images.githubusercontent.com/41866328/194710971-826e071a-f107-4ab5-ad0f-30b3f6c82d05.png)

argon when selecting another skin then going back to argon skin
![osu_2022-10-07_08-02-09](https://user-images.githubusercontent.com/41866328/194710977-ae479d78-dd4b-4c68-a373-0fa212b3b990.png)

### Version

2022.1008.0

### Logs

[database.log](https://github.com/ppy/osu/files/9739411/database.log)
[input.log](https://github.com/ppy/osu/files/9739412/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9739413/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9739414/network.log)
[performance.log](https://github.com/ppy/osu/files/9739415/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739416/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739417/updater.log)

**Comment by peppy** [comment] 2022-10-10 07:27
@enoslayd I can't seem to reproduce this one, are you able to provide a video showing the process?

**Comment by enoslayd** [comment] 2022-10-24 04:37
> @enoslayd I can't seem to reproduce this one, are you able to provide a video showing the process?

Sorry for the late reply, ill try to record later

As a follow-up, this doesn't happen on my android device and i suspect that its only on my pc, ill check with a clean database later

**Comment by enoslayd** [comment] 2022-10-26 07:40
here is the video
https://user-images.githubusercontent.com/41866328/197964105-da762fdd-5f7c-4bff-a178-e8bddbc23b2b.mp4

also i tried with a clean database and apparently its caused by my database. i dont want to delete it since i have soooo many beatmaps (300+GB)

**Comment by peppy** [comment] 2022-10-27 03:09
if you think it's caused by your database, could you please attach it? (zip `client.realm` and drag into github)

**Comment by enoslayd** [comment] 2022-10-27 08:55
hello, its too large for github (and maybe email too) so ill email a gdrive link instead

**Comment by peppy** [comment] 2022-11-01 10:01
@enoslayd did you happen to run any development builds during argon's development? ie. building yourself or running something provided by someone else?

**Comment by enoslayd** [comment] 2022-11-02 02:15
Hello yes i did

**Comment by peppy** [comment] 2022-11-02 02:36
Thanks. This should be an issue for only devs and not end users so I've sent you a fixed version of your database and will close the issue.

If anyone runs into this, you need to change the `InstantiationInfo` inside `Skin` for argon and triangles:

`DefaultSkinArgon` -> `ArgonSkin`
`DefaultSkinTriangles` -> `TrianglesSkin`

**Closed by peppy** 2022-11-02 02:36 UTC
Labels: missing details, area:skinning
