### ISSUE TITLE
Crashes with hidden mod related to sliderend/tails

### ISSUE THREAD

**Issue by LavaDesu** [ppy/osu#11052] opened 2020-12-02 05:05 UTC
**Describe the crash:** 
With the hidden mod enabled on maps where there are 2 sliders with enough time in between (after the first slider has been destroyed?), a crash will occur when the second slider is about to appear.

**Example maps** (almost any ranked map will work)**:**
https://osu.ppy.sh/b/1115984
https://osu.ppy.sh/b/1024483

**osu!lazer version:** 
Bisected to 18bb0cb45b944dbcb2afee1673ec1601702d6249

**Logs:**
[database.log](https://github.com/ppy/osu/files/5627016/database.log)
[network.log](https://github.com/ppy/osu/files/5627017/network.log)
[performance.log](https://github.com/ppy/osu/files/5627018/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5627019/runtime.log)

**Stacktrace** (did not appear in logs)**:**
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'osu.Game.Rulesets.Osu.Objects.SliderTailCircle' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at osu.Game.Rulesets.Osu.Mods.OsuModHidden.getFadeOutParametersFromSliderHead(OsuHitObject h) in /home/lava/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 156
   at osu.Game.Rulesets.Osu.Mods.OsuModHidden.applyState(DrawableHitObject drawable, Boolean increaseVisibility) in /home/lava/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 76
   at osu.Game.Rulesets.Osu.Mods.OsuModHidden.ApplyNormalVisibilityState(DrawableHitObject hitObject, ArmedState state) in /home/lava/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 56
   at osu.Game.Rulesets.Mods.ModWithVisibilityAdjustment.<ApplyToDrawableHitObjects>b__10_0(DrawableHitObject o, ArmedState state) in /home/lava/Projects/osu/osu.Game/Rulesets/Mods/ModWithVisibilityAdjustment.cs:line 86
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.updateState(ArmedState newState, Boolean force) in /home/lava/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 459
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.Apply(HitObject hitObject, HitObjectLifetimeEntry lifetimeEntry) in /home/lava/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 274
   at osu.Game.Rulesets.UI.Playfield.<>c__DisplayClass47_0.<osu.Game.Rulesets.UI.IPooledHitObjectProvider.GetPooledDrawableRepresentation>b__0(PoolableDrawable d) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/Playfield.cs:line 364
   at osu.Framework.Graphics.Pooling.DrawablePool`1.Get(Action`1 setupAction)
   at osu.Framework.Graphics.Pooling.DrawablePool`1.osu.Framework.Graphics.Pooling.IDrawablePool.Get(Action`1 setupAction)
   at osu.Game.Rulesets.UI.Playfield.osu.Game.Rulesets.UI.IPooledHitObjectProvider.GetPooledDrawableRepresentation(HitObject hitObject) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/Playfield.cs:line 347
   at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.Apply(HitObject hitObject, HitObjectLifetimeEntry lifetimeEntry) in /home/lava/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 233
   at osu.Game.Rulesets.UI.Playfield.<>c__DisplayClass47_0.<osu.Game.Rulesets.UI.IPooledHitObjectProvider.GetPooledDrawableRepresentation>b__0(PoolableDrawable d) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/Playfield.cs:line 364
   at osu.Framework.Graphics.Pooling.DrawablePool`1.Get(Action`1 setupAction)
   at osu.Framework.Graphics.Pooling.DrawablePool`1.osu.Framework.Graphics.Pooling.IDrawablePool.Get(Action`1 setupAction)
   at osu.Game.Rulesets.UI.Playfield.osu.Game.Rulesets.UI.IPooledHitObjectProvider.GetPooledDrawableRepresentation(HitObject hitObject) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/Playfield.cs:line 347
   at osu.Game.Rulesets.UI.HitObjectContainer.addDrawable(HitObjectLifetimeEntry entry) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 108
   at osu.Game.Rulesets.UI.HitObjectContainer.entryBecameAlive(LifetimeEntry entry) in /home/lava/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 100
   at osu.Framework.Graphics.Performance.LifetimeEntryManager.updateChildEntry(LifetimeEntry entry, Double startTime, Double endTime, Boolean isNewEntry, Boolean mutateActiveEntries)
   at osu.Framework.Graphics.Performance.LifetimeEntryManager.Update(Double startTime, Double endTime)
   at osu.Game.Rulesets.UI.HitObjectContainer.CheckChildrenLife() in /home/lava/Projects/osu/osu.Game/Rulesets/UI/HitObjectContainer.cs:line 192
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateChildrenLife()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   ...
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Game.Rulesets.UI.FrameStabilityContainer.UpdateSubTree() in /home/lava/Projects/osu/osu.Game/Rulesets/UI/FrameStabilityContainer.cs:line 99
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   ...
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass100_0.<handleException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.OsuTKWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/lava/Projects/osu/osu.Desktop/Program.cs:line 55
```

**Comment by peppy** [comment] 2020-12-02 05:18
Duplicate of https://github.com/ppy/osu/issues/11015

**Closed by peppy** 2020-12-02 05:18 UTC
