### ISSUE TITLE
Switching gamemodes on a song which is not inteded to be played on another mode causes a crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2788] opened 2018-06-12 23:50 UTC
[runtime.log](https://github.com/ppy/osu/files/2096157/runtime.log)

**Comment by peppy** [comment] 2018-06-13 02:56
Can you explain the process you're taking to reproduce this?

**Comment by Lolihunter1337** [comment] 2018-06-13 05:02
i recorded a video with the steps. probaly easier to explain. Streamable did not work for so i hope youtube is fine. https://youtu.be/ObcEhIh5dvg

**Comment by jaysc** [comment] 2018-06-14 21:00
Took a look at this:

Wasn't able to replicate it when changing songs like the video until i turned hard mod on.

Was able to replcate it majority of the time when selecting hard mod on osu, closed the mod menu fully, then switch to taiko.

I believe the problem is due to when `GetPlayableBeatmap` is ran and `mod.ApplyToHitObject(obj);` is hit since `Mods` still contain the hard mod, causing the error:
`'Unable to cast object of type 'osu.Game.Rulesets.Taiko.Objects.RimHit' to type 'osu.Game.Rulesets.Osu.Objects.OsuHitObject'.'` on `OsuModHardRock.cs`

I say sometimes the error occurs since the `Mods` gets cleared down somwhere and I can't figure out where.

**Comment by peppy** [comment] 2018-07-02 02:48
Should probably be resolved already. Please re-test.

**Comment by Lolihunter1337** [comment] 2018-07-02 05:34
works fine for me

**Comment by Lolihunter1337** [comment] 2018-07-02 05:38
ok nevermind. it does *not*

**Comment by peppy** [comment] 2018-07-05 00:20
Marking as duplicate of #2847.

**Closed by peppy** 2018-07-05 00:20 UTC
Labels: bug, songselect
