### ISSUE TITLE
Debug icon under Settings behaving unexpectedly

### ISSUE THREAD

**Issue by bdnh** [ppy/osu#6014] opened 2019-09-06 01:12 UTC
**Describe the bug:** 
When in the settings window, selecting the Debug option causes unexpected behavior. The icons on the left-hand side of the window appear to update dynamically based on the position of the section's title on the display. Since the Debug area is so small, clicking or scrolling to that section will cause it to light up for a very brief amount of time before switching to the Maintenance tab above it. This is best explained in the linked video.

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=72wnUOV_qb8

**osu!lazer version:** 
2019.905.0 Dev Build

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3581768/database.log)
[network.log](https://github.com/ppy/osu/files/3581769/network.log)
[performance.log](https://github.com/ppy/osu/files/3581770/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3581771/runtime.log)

**Comment by peppy** [comment] 2019-09-09 04:21
Not sure this is actually an issue. Eventually we'd expect this section to be long enough that this does not occur.

**Comment by smoogipoo** [comment] 2019-09-10 01:51
Closing as intended for the time being.

**Closed by smoogipoo** 2019-09-10 01:51 UTC
Labels: settings, user interface
