### ISSUE TITLE
Star rating not properly updating with custom rate dt

### ISSUE THREAD

**Issue by shrublet** [ppy/osu#9720] opened 2020-07-30 04:26 UTC
**Describe the bug:** 
When choosing a custom dt rate and then changing it, only the initial sr value will appear under the details section and will not update if the rate is changed. If selecting a new map the proper sr for the current rate will show, but again will not update its sr if the rate is changed.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/VEm5FOklCAU

**osu!lazer version:** 
2020.735.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/4998767/database.log)
[network.log](https://github.com/ppy/osu/files/4998768/network.log)
[performance.log](https://github.com/ppy/osu/files/4998769/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4998770/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4998772/updater.log)

**Comment by smoogipoo** [comment] 2020-07-30 04:33
Duplicate of https://github.com/ppy/osu/issues/9669

**Closed by smoogipoo** 2020-07-30 04:33 UTC
