### ISSUE TITLE
When FPS are shown, latency goes sometimes to negative numbers

### ISSUE THREAD

**Issue by byDave251** [ppy/osu#5974] opened 2019-09-03 18:30 UTC
**Describe the bug:** 
Latency is simply incorrect. Shouldn't go to negative numbers.

**Screenshots or videos showing encountered issue:** 
![osu_2019-09-03_20-24-52](https://user-images.githubusercontent.com/25853767/64198838-4f6e9780-ce89-11e9-873c-6112ee39ba39.png)

**osu!lazer version:** 
The latest one: 2019:903.0

**Logs:** 
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/3570895/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3570896/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3570897/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/3570898/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3570899/updater.log)
[database.log](https://github.com/ppy/osu/files/3570900/database.log)

[performance.log](https://github.com/ppy/osu/files/3570902/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/3570903/performance-gamethread.audio.log)

**Comment by byDave251** [comment] 2019-09-03 18:38
Noticed only on on Audio and Input so far.

**Comment by Game4all** [comment] 2019-09-03 19:50
Duplicate of framework issue ppy/osu-framework#696

**Comment by peppy** [comment] 2019-09-04 00:10
Framework issue https://github.com/ppy/osu-framework/issues/2532.

**Closed by peppy** 2019-09-04 00:10 UTC
