### ISSUE TITLE
[Android] Hang when exiting osu!editor

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#10574] opened 2020-10-21 15:35 UTC
**Describe the crash:** 
* Open osu!editor
* Tap File -> Exit -> Forget all changes
* The game will now hang (be unresponsive), but won't crash.

**Screenshots or videos showing encountered issue:** [Screenshot of the hang](https://user-images.githubusercontent.com/16479013/96742212-ee728d80-13c2-11eb-8394-48a6c4dd00f6.jpg)

**osu!lazer version:** 2020.1020.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/5416995/database.log)
[network.log](https://github.com/ppy/osu/files/5416996/network.log)
[performance.log](https://github.com/ppy/osu/files/5416997/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5416998/runtime.log)

**Phone Specifications:** 
Realme 6
Model: RMX2001
Android 10 with Realme UI V1.0
Processor: Mediatek Helios G90T

**Comment by bdach** [comment] 2020-10-21 15:50
Duplicate of #10340 / #10469

**Closed by bdach** 2020-10-21 15:50 UTC
