### ISSUE TITLE
Issues with moving songs within "now playing" tab 

### ISSUE THREAD

**Issue by ivbq** [ppy/osu#11181] opened 2020-12-15 22:22 UTC
**Describe the bug:** 
Attempting to move songs within the "now playing" tab while having a collection selected causes unexpected behavior, making selected songs jump up the list and preventing them from being moved down past their initial position. Varies depending on collection length, where longer collections have fewer issues, especially when selecting songs near the top of the list.

**Screenshots or videos showing encountered issue:** 

![ezgif-6-87a033ac634d](https://user-images.githubusercontent.com/59237624/102279808-51e4eb80-3f2c-11eb-9691-f07e7285f448.gif)

**osu!lazer version:** 
2020.1212.0

**Comment by Joehuu** [comment] 2020-12-15 22:24
Duplicate of https://github.com/ppy/osu/issues/10509

**Closed by Joehuu** 2020-12-15 22:24 UTC
