### ISSUE TITLE
Cursor Disappears & Gets out from the menu

### ISSUE THREAD

**Issue by ZapTech43** [ppy/osu#2015] opened 2018-02-03 05:54 UTC
So Another problem when i on the osu!lazer main menu the cursor **suddenly** disappears & when i lift my mouse up it's getting through out the game zone 
Look At The Picture for more details Thanks!

![cursor overlayed](https://user-images.githubusercontent.com/30797591/35763539-2144e5e0-08e1-11e8-8764-e9e26d50f503.png)

(This Happens When I Played it In Borderless mode but When I Played it in fullscreen The Problem is Gone)

**Comment by peppy** [comment] 2018-02-03 06:19
Could you please list your input settings (are you using raw input? sensitivity? do you have a tablet connected?)

**Comment by ZapTech43** [comment] 2018-02-03 06:34
Raw Input : Yes I'm Using it
Sensitivity : Yes 1.88x
Tablet Connected : No I Didn't connected a tablet

**Comment by peppy** [comment] 2018-02-03 06:35
Can you reproduce if your sensitivity is 1.0x?

**Comment by ZapTech43** [comment] 2018-02-03 06:36
You mean?

**Comment by ZapTech43** [comment] 2018-02-03 06:41
Yup, It Did Happens Again I Already Set The Sensitivity to 1.0x but the Raw input is still on

![cursor overlayed 2](https://user-images.githubusercontent.com/30797591/35763843-df84b5d4-08e7-11e8-95b9-e2db22073d0a.png)

**Comment by peppy** [comment] 2018-02-03 06:57
Can you also 

- check your "confine mouse mode"
- check whether you can make it happen in non-borderless (windowed)

**Comment by ZapTech43** [comment] 2018-02-03 07:24
- Confine mouse mode = Fullscreen
- In Fullscreen it doesn't happen in windowed it doesn't happen too

**Comment by LittleEndu** [comment] 2018-02-04 15:58
Correction, It does happen in maximized windowed but only left and right side. When OS takes over cursor it snaps back to correct place.
https://i.imgur.com/g2ul5dw.png

**Comment by peppy** [comment] 2018-02-05 04:36
These issues will likely be resolved by ppy/osu-framework#1371

**Comment by LittleEndu** [comment] 2018-02-05 05:25
I think I checked this on the raw input branch too and that wasn't the case. Will check again once I get on PC.

**Comment by LittleEndu** [comment] 2018-02-05 05:57
Checked this on the Raw Input PR:
Do note that I don't have multimonitor setup so I can't check if confinement works correctly, I can only check this bug.
Also note this bug only exists with raw input **on**, regardless of sensitivity, regardless if using absolute device or regular mouse

-- | Windowed | Borderless | Fullscreen
--- | --- | --- | ---
Never Confine | 🐞 | 🐞 | 🐞
Fullscreen Confine | 🐞 | 🐞 | 👍
Always Confine | 👍 | 👍 | 👍

**Comment by peppy** [comment] 2018-02-05 06:55
That table looks like exactly what I would expect. The bugs are not bugs, but just what you see when the mouse is not confined.

Could you provide a video or something because I'm still not sure what is being reported here.

**Comment by LittleEndu** [comment] 2018-02-05 07:03
I do agree that this kinda behavior is to be expected but it looks ugly and it's impossible to find your cursor again once it goes offscreen (like when you drop your mouse then your cursor might be two screens away and you have no way to get it back other than alt+tab) . So I would still call this a bug.
Solution would be to stop the parallax once there's no more background to show. And there should be a triangle that show which side the cursor is offscreen at.

**Comment by peppy** [comment] 2018-02-05 07:03
I still need a video, because it's not obvious what you are trying to show here. The original user mentions an abrupt jump, which I cannot reproduce.

**Comment by LittleEndu** [comment] 2018-02-05 07:09
Yeah I don't think there's any jumping going on other than if you move your mouse really fast or have tablet with really high sensitivity. If I am wrong the original user should correct us. 
I feel like this should be moved to low priority.

**Comment by peppy** [comment] 2018-02-05 07:10
If it's just a matter of the mouse not being confined, that's resolved by limiting the confine modes. For instance, "Never" should be removed from the options.

**Comment by LittleEndu** [comment] 2018-02-05 07:14
I feel like no confinement should be the default so that you wouldn't experience major mouse drift due to hitting the edge of the window/monitor. Or some other measure should be added that counteracts that. For me, this was basically the only reason I looked into providing more info on this issue. Not knowing where your cursor is once it's off screen is an issue for me

**Comment by peppy** [comment] 2018-02-05 07:18
Basically confining is only useful when windowed. The options should be "Fullscreen only" or "Always".

**Comment by Aergwyn** [comment] 2018-02-05 07:19
I agree. In Fullscreen the option is useless as it's basically "Always" anyways and in Borderless/Windowed it's more of a nice-to-have thing. "Never" shouldn't be an option.

**Comment by LittleEndu** [comment] 2018-02-05 07:22
Is there a way to get the number of monitors and extend "fullscreen only" to borderless when there's only one monitor?

**Comment by peppy** [comment] 2018-02-05 07:23
It needs to still apply with multiple monitors. It should still confine to available monitor space, else the user can exit in directions monitors do not exist.

**Comment by peppy** [comment] 2018-02-05 07:33
This is going to be an interesting one to fix across platforms. I'll look into it once I'm 100% on raw input implementation.

**Comment by ZapTech43** [comment] 2018-02-10 04:30
Wow XD

**Comment by leonekmi** [comment] 2018-03-16 21:27
I have a similar issue, the cursor goes on left and is uncontrollable when focused : https://up.twittolabel.fr/2018-03-16%2022-20-41.mp4

Environnement : Mono JIT compiler version 5.8.0.108 (tarball mer. mars 14 13:32:19 CET 2018)

**Closed** 2018-06-06 08:18 UTC
Labels: input, overdue, pending review

**Comment by TheDarkDnKTv** [comment] 2020-05-02 11:57
Have this issue! I think it is because of only intel graphics video card available. If i will launch osu!lazer in windowed mode, there is cursor. But if i will set to fullscreen and restart, curson will not render at all, time to time i have no cursor at all (background not moving when i move mouse).

**Comment by ZapTech43** [comment] 2020-05-02 12:04
> Have this issue! I think it is because of only intel graphics video card available. If i will launch osu!lazer in windowed mode, there is cursor. But if i will set to fullscreen and restart, curson will not render at all, time to time i have no cursor at all (background not moving when i move mouse).

Damn, this case is two years old btw...
So, the cursor disappears? Is it like the problem above?

**Comment by TheDarkDnKTv** [comment] 2020-05-02 19:31
Yes, repairs by changing to windowed and then again fullscreen.

**Comment by Gababyte** [comment] 2020-06-18 05:31
I'm pretty sure I also have the same problem. I'm using a pretty old laptop but it can run osu!lazer pretty well, the only issue I have is my cursor. The cursor functions like normal, it's just that it's missing.

**Comment by OsuTheBest** [comment] 2020-11-09 02:20
I get the same problem but in osu!stable, randomly or when I tab to another program the cursor disappears and I have to restart osu! and it's SOOOOOOOOOOOOOOO annoying. Thinking of taking a brake from osu till it's fixed
