### ISSUE TITLE
The transition to the result screen can be stopped

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#7291] opened 2019-12-19 15:49 UTC
**Describe the bug:** The transition to the results screen can be stopped by pressing <kbd>ESC</kbd> after the last hit-object of a beatmap.

**Screenshots or videos showing encountered issue:** https://streamable.com/4si16 (as you can see, I pressed <kbd>ESC</kbd> at the end of the map because the little `X` at the bottom-right corner flashed)

**osu!lazer version:** 2019.1219.0

**Logs:** the main difference is that the `SoloResults` screen doesn't appear (in the first example):
![runtime](https://user-images.githubusercontent.com/43073074/71186478-938d7880-227d-11ea-840b-c0cb47a8325a.png)

**Comment by bdach** [comment] 2019-12-19 16:01
While a bit nicer than the original report, still a duplicate of #6848.

**Closed by bdach** 2019-12-19 16:01 UTC
