### ISSUE TITLE
Autoplay & replay problem

### ISSUE THREAD

**Issue by tladudtn** [ppy/osu#8277] opened 2020-03-14 16:10 UTC
**Describe the bug:When you try to play the back of a few seconds in autoplay mode, it will be the same as the YouTube video below.**

sorry for my bad english

**Screenshots or videos showing encountered issue**
https://www.youtube.com/watch?v=rNAbQd6XipU&feature=youtu.be
 

**osu!lazer version:2020.312.0**

**Comment by bdach** [comment] 2020-03-14 16:11
Duplicate of #5119

**Closed by bdach** 2020-03-14 16:11 UTC
