### ISSUE TITLE
High precision mouse doesn't respect Windows primary mouse button

### ISSUE THREAD

**Issue by Susko3** [ppy/osu#12132] opened 2021-03-21 17:52 UTC
**Describe the bug:** 

Windows has an option switch left and right mouse buttons system-wide. The option can be found in:

- Settings > Devices > Mouse > Select your primary button
- Win+R > `main.cpl` > Switch primary and secondary buttons

osu!lazer does not respect this option while using High precision mouse.
With High precision mouse disabled, the left and right clicks are swapped, as expected.

osu!stable respects this option (with and without raw input)

**osu!lazer version:** 2021.320.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6177998/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6177999/updater.log)
[network.log](https://github.com/ppy/osu/files/6178000/network.log)
[performance.log](https://github.com/ppy/osu/files/6178001/performance.log)

**Comment by bdach** [comment] 2021-03-21 17:53
Duplicate of #5628

**Closed by bdach** 2021-03-21 17:53 UTC
