### ISSUE TITLE
Negative score shown on results screen with long beatmaps

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#3970] opened 2018-12-29 18:41 UTC
**Describe your problem:** I was playing https://osu.ppy.sh/beatmapsets/121591#osu/311269 and on singleplayer ( with auto and Classic Score mode ) and it worked fine. however on Multiplayer the map Never ends and youre stuck.

**Screenshots or videos showing encountered issue:** 
Multiplayer ![osu_2018-12-29_18-48-40](https://user-images.githubusercontent.com/17437302/50541232-80335a00-0ba1-11e9-988b-957738234da5.jpg)

Singleplayer ![osu_2018-12-29_19-14-57](https://user-images.githubusercontent.com/17437302/50541233-845f7780-0ba1-11e9-8de0-44e003f50016.jpg)

**osu!lazer version:** 2018.1228.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2716626/database.log)
[network.log](https://github.com/ppy/osu/files/2716627/network.log)
[performance.log](https://github.com/ppy/osu/files/2716628/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2716629/runtime.log)

**Comment by peppy** [comment] 2019-02-05 06:47
Potentially duplicate of #4095, but we should look into the negative score display.

**Closed** 2019-02-26 04:18 UTC
Labels: gameplay, multiplayer, pending review
