### ISSUE TITLE
Not properly displaying text. (macOS) 

### ISSUE THREAD

**Issue by FlatLineG** [ppy/osu#11674] opened 2021-02-04 13:52 UTC
**Describe the bug:** 
As the title says, it's not properly rendering the text. I tested and playing maps works fine. macOS Mojave 10.14.16

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/78546497/106901629-f7e5f280-6732-11eb-8a8b-96f3819bf64e.png)
![image](https://user-images.githubusercontent.com/78546497/106901668-0502e180-6733-11eb-9e1d-d5804b9c6906.png)
![image](https://user-images.githubusercontent.com/78546497/106901703-0c29ef80-6733-11eb-9f39-f39fe5f5c16f.png)

**osu!lazer version:** 2021.129.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5926122/database.log)
[network.log](https://github.com/ppy/osu/files/5926123/network.log)
[performance.log](https://github.com/ppy/osu/files/5926124/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5926125/runtime.log)

**Comment by smoogipoo** [comment] 2021-02-04 13:55
Duplicate of https://github.com/ppy/osu/issues/9314

**Comment by bdach** [comment] 2021-02-04 13:55
#9314

**Closed by smoogipoo** 2021-02-04 13:55 UTC
