### ISSUE TITLE
Binding one key to multiple actions for some rulesets should not be possible

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#12142] opened 2021-03-22 09:15 UTC
**Describe the bug:** 
Stable allows binding same key only for catch and osu, however in lazer it's possible to do this for any ruleset.
(IMO osu ruleset should now allow this as well, but that's a topic for another discussion)

**Screenshots or videos showing encountered issue:** 
![osu_2021-03-22_11-58-58](https://user-images.githubusercontent.com/22874522/111965991-73470c00-8b07-11eb-9095-89826d39b716.png)

**Comment by frenzibyte** [comment] 2021-03-22 09:16
Duplicate of https://github.com/ppy/osu/issues/5089

**Closed by frenzibyte** 2021-03-22 09:16 UTC
