### ISSUE TITLE
Storyboard sounds continue after exiting map

### ISSUE THREAD

**Issue by 0176** [ppy/osu#5971] opened 2019-09-03 10:21 UTC
**Describe the bug:** 
When I tried pishifat's new osu! tutorial I paused and quit the map, and his explanation of osu and whatnot continued playing after i quit the map.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/hiW553QjCGE

**osu!lazer version:** 
2019.831.0

**Logs:** 
I'm unsure as to where logs are, sorry.

**Comment by iiSaLMaN** [comment] 2019-09-03 10:21
Duplicate of #5884

**Closed** 2019-09-03 10:22 UTC

**Comment by 0176** [comment] 2019-09-03 10:24
my bad
