### ISSUE TITLE
Osu!Lazer hit objects have different order than Osu!Stable

### ISSUE THREAD

**Issue by GamingWithJanko** [ppy/osu#26972] opened 2024-02-02 19:40 UTC
### Type

Game behaviour

### Bug description

Title says it all, pretty much.

### Screenshots or videos

https://youtu.be/1bXAVvIgVWQ

### Version

2024.202.0

### Logs

I dunno, why, but oh well...
[compressed-logs.zip](https://github.com/ppy/osu/files/14144575/compressed-logs.zip)

**Comment by bdach** [comment] 2024-02-02 19:58
Please point out the exact timestamp that shows the difference.

**Comment by GamingWithJanko** [comment] 2024-02-02 20:48
The entire map. 
![screenshot235](https://github.com/ppy/osu/assets/4876
![osu_2024-02-02_21-47-35](https://github.com/ppy/osu/assets/48768314/fd8e2ac8-bfbb-4978-84a7-67be99095213)
8314/56efc66b-62fc-45e0-8f08-058a0ecd12fb)

But sure:

**Comment by GamingWithJanko** [comment] 2024-02-02 20:50
The circle of the new slider draws both under (Body and number, it seems) and onto (Head) the slider

But sometimes the slider that is newer also gets drawn under the older slider

**Comment by GamingWithJanko** [comment] 2024-02-02 20:52
![image](https://github.com/ppy/osu/assets/48768314/4e3bece2-d50d-407d-a3b2-8af78cf3e8d6)
Here's a difference that should make the order difference clear enough.

Hit circles drawn UNDER the slider

**Comment by bdach** [comment] 2024-02-03 15:27
I'm honestly not sure anything can or will be done about this because stable's z-ordering code is........... questionable when it comes to complexity. Certainly not a priority, I'd say concurrent sliders and all that "2b" stuff is as out-of-scope as supporting aspire is.

**Comment by GamingWithJanko** [comment] 2024-02-03 16:16
It's just something QOL, but it would be neat nontheless, if the lazer gameplay actually translates properly from stable.

Like... These can actually be hit in stable no problem, even if it NF-fails then. But in Lazer... You... You just can't.

**Comment by bdach** [comment] 2024-02-20 11:25
Duplicate of https://github.com/ppy/osu/issues/5539 actually.

**Closed by bdach** 2024-02-20 11:25 UTC
Labels: ruleset/osu!, area:gameplay
