### ISSUE TITLE
Apply the Difficulty range selector after releasing the mouse button instead of after the cursor stops moving

### ISSUE THREAD

**Issue by Newbie1st** [ppy/osu#31021] opened 2024-12-09 05:58 UTC
### Type

Performance

### Bug description

In the current implementation precisely changing Difficulty range selector is hard due to it freezing the game for up to a second every time the mouse stops moving, making it apply a filter after the mouse button is released should alleviate this issue.

### Screenshots or videos

Notice the "pressed" cursor state and the 180ms spike
![osu_2024-12-09_10-52-18](https://github.com/user-attachments/assets/8ef24c8d-1d6e-43b5-8acc-fdb1e567b949)

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18056943/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-12-09 07:17
Duplicate of https://github.com/ppy/osu/issues/29375

**Closed by frenzibyte** 2024-12-09 07:17 UTC
