### ISSUE TITLE
Importing Beatmaps From External Drive

### ISSUE THREAD

**Issue by AnimeDasher** [ppy/osu#7439] opened 2020-01-04 22:41 UTC
I Have Osu Stable on a external SSD and Osu Lazar cannot find my Osu Stable Beatmaps or skins, making it an inconvenience to switch to Osu Lazar at this point in time.

**Comment by recapitalverb** [comment] 2020-01-04 22:43
Use a symlink

**Comment by jai-x** [comment] 2020-01-04 22:44
Duplicate of https://github.com/ppy/osu/issues/3763 I think

**Comment by AnimeDasher** [comment] 2020-01-04 22:51
now the game won't even open -_- , i will check taht post and see if it works, if it does not work i will keep this open

**Closed** 2020-01-04 23:08 UTC
