### ISSUE TITLE
Text boxes do not recognize keys with modifier key AltGr 

### ISSUE THREAD

**Issue by MinecraftPlaye** [ppy/osu#5348] opened 2019-07-12 21:49 UTC
**Describe the bug:** 
Text boxes (e.g. login, chat) do not allow keys which are allowed on the website or in stable.
This problem occures when using keys which are require the modifier key AltGr to be pressed. Using a german keyboard, this means some keys, e.g. {,},[,],\ will not be recognized by lazer.

This can become a serious problem if someone has such key's within their email-adress or password.

**osu!lazer version:** 
2019.704.0

**System:**
Windows 10 64bit 1809 17763.557

**Comment by jorolf** [comment] 2019-07-12 21:52
Duplicate of https://github.com/ppy/osu-framework/issues/1965

**Closed** 2019-07-13 01:21 UTC
