### ISSUE TITLE
Mods appear unselected after opening the editor on a converted beatmap

### ISSUE THREAD

**Issue by LittleLilyBun** [ppy/osu#29257] opened 2024-08-02 12:57 UTC
### Type

Cosmetic

### Bug description

When selecting a mod in a non-standard ruleset and then editing a standard beatmap with converts enabled, upon exiting the editor, the mods previously selected appear unselected in the mod overlay but not on the mods button, until you exit song select and re-enter, the deselect button also appears clickable, but clicking it does nothing.

### Screenshots or videos

https://github.com/user-attachments/assets/ae204736-853f-4c84-92f5-7d1a05810d84

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16470677/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-08-02 18:22
Duplicate of https://github.com/ppy/osu/issues/22816

**Closed by Joehuu** 2024-08-02 18:22 UTC
