### ISSUE TITLE
Right mouse button cannot be used as primary button with raw input

### ISSUE THREAD

**Issue by KaijuBoi** [ppy/osu#7770] opened 2020-02-08 18:01 UTC
Hi, I use right click as my primary button on PC and play standard on 1.2x sensitivity and stable handles just fine. However, when I start lazer and increase my mouse sensitivity to 1.2x, Raw Input activates and won't let me use my right mouse button as my primary click anymore. This doesn't happen on stable with raw input so I don't know why it happens here. This is just a small issue though and doesn't affect anything else in the game, just wanted to mention it so I didn't have to constantly switch to using left click when I play lazer.

**Comment by bdach** [comment] 2020-02-08 18:11
I assume than when you say you have right click as the primary button, you've set it via Windows settings to be the primary button. In that case I can see why this would happen, as raw input most likely doesn't respect the Windows settings and processes hardware input events instead.

I don't know what stable does in terms of input or if there are any special paths to handle this. I *do* know that there is seemingly no way I can see to rebind M1 and M2 when it comes to UI actions in lazer, so there doesn't appear to be any ready-made solution for your problem.

FWIW, resolving this might become quite a chunk of work to resolve cleanly. The easiest solution would be probably to allow remapping at framework-level (by firing left mouse button events on right mouse button and vice versa), but that is a really ugly way of addressing the problem.

**Comment by Joehuu** [comment] 2020-02-08 20:35
Duplicate of https://github.com/ppy/osu/issues/5628

**Closed by Joehuu** 2020-02-08 20:35 UTC
Labels: framework fix required, input
