### ISSUE TITLE
Russian characters not showing correctly. 

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#9428] opened 2020-07-03 09:07 UTC
So basically in the search bar and text fields russian(win-1251?) not showing correctly. 
Here's screenshot: http://prntscr.com/tb08jd

osu!lazer version: 2020.629.0
Windows 10 LTSC

Logs: https://puu.sh/G3abG.zip

**Comment by peppy** [comment] 2020-07-03 09:10
If you copy text in does it work as expected?

**Comment by xDololow** [comment] 2020-07-03 09:19
> If you copy text in does it work as expected?
Yes
![image](https://user-images.githubusercontent.com/26763912/86453661-59328700-bd48-11ea-9f00-7612d758a3b0.png)

**Comment by bdach** [comment] 2020-07-03 09:22
Duplicate of #5827

**Closed by bdach** 2020-07-03 09:22 UTC
