### ISSUE TITLE
When you put in the wrong password it does not say wrong password

### ISSUE THREAD

**Issue by CloudyWhale** [ppy/osu#13621] opened 2021-06-22 19:15 UTC
**Describe the bug:** 
When you put in the wrong password it does not say wrong password

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/83542885/122985850-a8643400-d36c-11eb-8d37-f08e2c431326.mp4

**osu!lazer version:** 
2021.619.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/6696836/database.log)
[network.log](https://github.com/ppy/osu/files/6696837/network.log)
[performance.log](https://github.com/ppy/osu/files/6696838/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6696839/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6696840/updater.log)

**Comment by frenzibyte** [comment] 2021-06-22 19:16
Duplicate of https://github.com/ppy/osu/issues/4086

**Closed by frenzibyte** 2021-06-22 19:16 UTC
