### ISSUE TITLE
Track play/pause has "no key bound"

### ISSUE THREAD

**Issue by cyanidee** [ppy/osu#7481] opened 2020-01-08 16:30 UTC
**Describe the bug:** 
I'm not quite sure whether is a bug or is it intended (like no *additional* key bound maybe?) but when you press F3 or F5 to pause/play track or skip the current track, it says "no key bound". I think it should say "F3" or "F5" as it does with frame limiter.

**Screenshots or videos showing encountered issue:** 
Pause track - no key bound but you can trigger it with F3
![image](https://user-images.githubusercontent.com/32851089/71996301-437e5200-323c-11ea-9221-3a7eb7a3d280.png)

Next track - no key bound but you can trigger it with F5
![image](https://user-images.githubusercontent.com/32851089/71996320-49743300-323c-11ea-903c-d2d0e7d46b50.png)

Frame limiter - CTRL + F7
![image](https://user-images.githubusercontent.com/32851089/71996337-4f6a1400-323c-11ea-989d-905711148d3e.png)

**osu!lazer version:** 
2020.104.0

**Logs:** 
Irrelevant in that case, so I'm not going to bother 😶

**Comment by bdach** [comment] 2020-01-08 16:32
Duplicate of #6798.

**Closed by bdach** 2020-01-08 16:32 UTC
