### ISSUE TITLE
Leaderboard score not matching replay

### ISSUE THREAD

**Issue by DoubleJ-G** [ppy/osu#27343] opened 2024-02-23 12:00 UTC
### Type

Game behaviour

### Bug description

The score submitted to the leaderboard does not match the replay. After finishing a map I noticed my score was lower, my misses higher and the pp lower than what I expected. 

Opening up the score from the leaderboard shows a 561k 12 miss 92% accuracy, but going into the replay you can see I play 610k score, 6 missed and 84% accuracy. This correctly shows after the replay is finished but the leaderboard stays bugged.

It is also worth noting during the map I noticed a short ~0.1 second flash of the map ahead, like I was seeing the next 5-10 notes and failed half of them, but then it continues as normal. I think whatever happened on the client is counting these ghost notes as missed and lowering the score, I have no idea what caused this and I have no video evidence. But you can clearly see the scores misaligned before after watching the replay.

Here is the replay file: [solo-replay-osu_1104798_2393901762.osr.zip](https://github.com/ppy/osu/files/14384891/solo-replay-osu_1104798_2393901762.osr.zip)
Or straight from the site: https://osu.ppy.sh/scores/2393901762

### Screenshots or videos

This is my play from Feb 23rd 8.30PM as displayed from the song select screen and leaderboard

![Screenshot 2024-02-23 at 8 53 17 pm](https://github.com/ppy/osu/assets/63054658/29b072ff-6aac-4c7f-a04d-a404b9846fa5)
![Screenshot 2024-02-23 at 8 53 27 pm](https://github.com/ppy/osu/assets/63054658/e485f29c-3ac4-45b8-a818-7f9e300329b6)

After watching the replay this is the results screen I get 

![Screenshot 2024-02-23 at 8 53 46 pm](https://github.com/ppy/osu/assets/63054658/d6868c43-123b-42f4-9913-68854b11caa9)

As you can see both screens are showing the play as Feb 23rd 8.30PM 

I have a video showing this is from clicking the watch replay button of the 561k score. In the video skip through the replay, but can upload the actual footage if needed. Going through the map you can see I only miss 6 times but the leaderboard score seems to think I missed 12 

https://github.com/ppy/osu/assets/63054658/27fc6a49-f819-46bd-a0c0-0a4c8bf61c2c

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14384812/compressed-logs.zip)

**Comment by bdach** [comment] 2024-02-23 12:12
Multiple "playback discrepancies" found in log, so probably duplicate of https://github.com/ppy/osu/issues/27343.

**Closed by bdach** 2024-02-23 12:12 UTC
