### ISSUE TITLE
Decrease in image quality and fonts

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#9392] opened 2020-06-28 23:44 UTC
**Describe the bug:** 
If you go to the results screen and exit it, the image and font quality in one part of the screen will drop.
**Screenshots or videos showing encountered issue:** 
https://youtu.be/9QRyotxRlkQ
**osu!lazer version:** 
2020.629.0

**Comment by smoogipoo** [comment] 2020-06-29 04:59
Duplicate of https://github.com/ppy/osu/issues/9305

**Closed by smoogipoo** 2020-06-29 04:59 UTC
