### ISSUE TITLE
New key binding broken after tablet input (CTL-4100)

### ISSUE THREAD

**Issue by TheFartLord** [ppy/osu#12164] opened 2021-03-24 01:18 UTC
**Describe the bug:** 
Tablet: Wacom CTL-4100
After any tablet pointer input, all new key bindings have Tablet Aux 1-5 (sometimes multiple times, depending on last known pen position) added onto them, making it impossible to set them to anything usable. Restarting the game makes new bindings possible again until any new tablet pointer input. The issue occurs even if the tablet setting is disabled.

**Screenshots or videos showing encountered issue:** 
![osu_2021-03-24_02-04-30](https://user-images.githubusercontent.com/81272341/112238831-b0b1b380-8c45-11eb-8015-06ae7185f16e.jpg)

**osu!lazer version:** 
2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6193643/database.log)
[network.log](https://github.com/ppy/osu/files/6193644/network.log)
[performance.log](https://github.com/ppy/osu/files/6193645/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6193647/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6193648/updater.log)

**Comment by peppy** [comment] 2021-03-24 06:16
Has anyone else experienced this using a wacom device? Very hard to tell if this is something our end, OTD's end or potentially something else running on the host (ie. wacom driver interference or similar).

A quick check of button state handling at our end checks out correct, so I'm not sure where this is coming from.

@TheFartLord you mention that this happens even with tablet handling turned off, but what happens if you start the game and turn it off before making any tablet positional input? As a sanity check, that should resolve the issue at least.

**Comment by GeNeRaL-ShAdOw** [comment] 2021-03-24 08:45
Unfortunately I don't have the same tablet as @TheFartLord (ctl-4100) but confirmed the problem using ctl-472(wacom drivers). <<The cursor works fine on disabling the tablet option under input>>. However enabling this causes the cursor to do the same as stated above: https://drive.google.com/file/d/1jWYPve-LsjGT1uZfl86qqwKCzOspWC2i/view?usp=sharing

As for the problem stated by @peppy in the later half, tablet handling turned off works fine for me. The problems face by me are these: 
![image](https://user-images.githubusercontent.com/51219966/112280800-65ca8700-8cab-11eb-8936-b3306ee6152d.png)

**Comment by peppy** [comment] 2021-03-24 08:52
Are you posting in the wrong thread? This thread is related to key bindings. Your video has nothing showing key bindings working or failing.

**Comment by GopoBoi** [comment] 2021-03-24 08:53
I have the same issue, using the CTL-4100, running on linux (happens on windows as well), happens even when disabling the tablet option before making any kind of input on the tablet. I do have the same issue when using OTD on its own - so probably an issue on OTD's end

**Comment by peppy** [comment] 2021-03-24 08:54
Okay, that's a relief to hear then. Are you able to open an issue report over at their end so we can attempt to get this resolved? Quite a crippling issue in its current state.

**Comment by GopoBoi** [comment] 2021-03-24 09:01
Okay, Done https://github.com/OpenTabletDriver/OpenTabletDriver/issues/909

**Comment by GeNeRaL-ShAdOw** [comment] 2021-03-24 09:07
shoot sorry! :(

**Comment by jfoster19767** [comment] 2021-03-26 22:47
I'm using a Wacom CTL-4100 and I'm also experiencing these issues. For me if my tablet detects the pen while I am changing my keybind then it throws in that added stuff. However, if my tablet doesn't detect the pen while I am changing the keybind then the switch happens normally. I attached a video to better show this. I am also running lazer version 2021.323.0 on Windows 10.
Hope this helps!


https://user-images.githubusercontent.com/57021056/112699446-102be100-8e49-11eb-8b53-b5cdaeec825e.mp4

My logs:

[performance.log](https://github.com/ppy/osu/files/6214649/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6214650/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6214651/updater.log)
[database.log](https://github.com/ppy/osu/files/6214652/database.log)

**Comment by Hergam** [comment] 2021-03-28 15:40
I have the same problem but taking the pen off the tablet doesn't fix anything.

**Comment by jfoster19767** [comment] 2021-03-28 17:29
> I have the same problem but taking the pen off the tablet doesn't fix anything.

That's unfortunate, the easiest way around this would probably be to restart the game and change your settings before using your tablet. It sounds like it worked for TheFartLord and it works for me as well.
Hope this helps!

**Comment by peppy** [comment] 2021-03-29 05:01
As an update, a fix is in the OTD pipeline for this one, but not quite merged yet (https://github.com/OpenTabletDriver/OpenTabletDriver/pull/910)

**Comment by bdach** [comment] 2021-04-28 10:31
@GopoBoi Is this something you also experienced and therefore can confirm that it's fixed first hand? Would like such conformation before proceeding with close.

Alternatively any of the original reporter(s) could also confirm this if possible.

**Comment by GopoBoi** [comment] 2021-04-28 10:55
Yes, this was happening to me before and I can confirm that it is now fixed.

**Comment by peppy** [comment] 2021-04-29 03:07
Tentatively closing. @TheFartLord please report back if you can still reproduce the bug in the latest release.

**Closed by peppy** 2021-04-29 03:07 UTC
Labels: framework-fix-required, priority:0, type:input
