### ISSUE TITLE
Newly placed sliders do not produce any sounds in the editor

### ISSUE THREAD

**Issue by Azzirah** [ppy/osu#11357] opened 2020-12-29 02:33 UTC
**Describe the bug:** 
When placing new sliders in the editor, those will not produce any sounds until the map is saved and loaded in the editor again. From what I tried, only sliders seem to have this issue and changing skin didn't have any impact.

**osu!lazer version:** 2020.1225.0

**Comment by bdach** [comment] 2020-12-29 14:48
Can reproduce. Seems to be that `ApplyDefaults` is being called too early via `StartTimeBindable` (that is, before nested hitobjects are created). This in turn fires this logic:

https://github.com/ppy/osu/blob/71a121389b7228ca56ef873d701cb2eeee442a17/osu.Game.Rulesets.Osu/Objects/Slider.cs#L141-L143

and as `NodeSamples` are empty, the default `normal-hitnormal` sample attached here:

https://github.com/ppy/osu/blob/71a121389b7228ca56ef873d701cb2eeee442a17/osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs#L214-L215

is discarded.

The solution might just be to initialise `NodeSamples` in `SliderPlacementBlueprint`? Not sure.

**Comment by peppy** [comment] 2021-02-11 08:15
Turns out the code you mentioned didn't need to be moved and the cause was slightly different, but I do agree with moving it to `PlacementBlueprint`, i think.

**Closed** 2021-02-12 04:31 UTC
Labels: area:editor, ruleset:osu!, type:audio
