### ISSUE TITLE
Overall accuracy

### ISSUE THREAD

**Issue by iTzHard** [ppy/osu#6561] opened 2019-10-21 13:03 UTC
A toggle-able option in the settings which would display the accuracy measured against the whole beatmap.

Let's say you got a 100 at the first object, your accuracy would display 99.97% (measured against the whole map) instead of 33.33% (measured against current progress).

**Comment by nbvdkamp** [comment] 2019-10-21 14:56
Duplicate of #4638

**Closed** 2019-10-21 14:58 UTC
