### ISSUE TITLE
Crash with no reason

### ISSUE THREAD

**Issue by SuperFat-Fat** [ppy/osu#6189] opened 2019-09-20 10:02 UTC
osu! lazer started to crash a few days ago when i tried to launch the tournament mode. So i deleted it and I reinstall the latest version available. But even with that, osu!lazer doesn't launch. it shows the black screen and stop running after that.

osu!lazer version: 2019.919.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3635348/runtime.log)
[database.log](https://github.com/ppy/osu/files/3635351/database.log)
[network.log](https://github.com/ppy/osu/files/3635354/network.log)

**Comment by SuperFat-Fat** [comment] 2019-09-20 10:04
Maybe when i deleted all my beatmaps/skin/scores and re-import them, that has destroyed the database ?

**Comment by bdach** [comment] 2019-09-20 10:06
On the surface, same symptom as #6109, but due to sqlite's cagey error messages it might not be the same issue. We might need your `client.db` file to investigate in detail.

Moving away `client.db` *will* most likely work, but we won't be able to tell precisely why the crash happened.

**Comment by SuperFat-Fat** [comment] 2019-09-20 10:10
Github doesn't accept .db sorry
[client.zip](https://github.com/ppy/osu/files/3635376/client.zip)

The weirdest is that a few days ago, even on the lastest version, Osu worked perfectly fine.

**Comment by bdach** [comment] 2019-09-20 10:22
Upon investigation this is a duplicate of #6109, the cause is exact same. This query that displays beatmaps pending deletion that have scores turned up five beatmaps that are blocking things:
```sql
select distinct bsi.ID from ScoreInfo si
left join BeatmapInfo bi on si.BeatmapInfoID = bi.ID
left join BeatmapSetInfo bsi on bi.BeatmapSetInfoId = bsi.ID
where bsi.DeletePending = 1
```
Relevant IDs: 44, 193, 195, 332, 333.

Can be closed. In the meantime to continue playing lazer you can back up your database file and reimport everything from stable. Once a fix for this is deployed you might be able to go back to the backup.

**Comment by smoogipoo** [comment] 2019-09-20 10:25
Thanks for the looking into. We have a fix ready for this but testing has proved to be quite a bit of a problem (automated tests don't seem to use the DB properly...).

**Closed by smoogipoo** 2019-09-20 10:25 UTC
