### ISSUE TITLE
Show a scroller in mod selection

### ISSUE THREAD

**Issue by xenallio** [ppy/osu#6000] opened 2019-09-05 03:21 UTC
**Describe the new feature:** 
Make it easier to know that we can now scroll down the mods (I found by accident)
**Proposal designs of the feature:** 
Throw in a scroll bar or something along thoses lines

**Comment by Joehuu** [comment] 2019-09-05 03:24
Duplicate of #3433.

**Closed** 2019-09-05 03:41 UTC
