### ISSUE TITLE
"WidthForNoteHeightScale" Doesn't transfer over from stable mania skins to lazer mania skins

### ISSUE THREAD

**Issue by GavinMinus** [ppy/osu#26907] opened 2024-01-31 21:31 UTC
### Type

Game behaviour

### Bug description

Was importing things over from Stable over to Lazer and WidthForNoteHeightScale which is found in the skin.ini to change how tall a note is doesn't work in Lazer.

### Screenshots or videos

Same skin.

Lazer:
![osu!_nF4qKkeJtw](https://github.com/ppy/osu/assets/105038735/2022e23d-0a71-4a35-9c2a-48f284af60cf)

Stable:
![osu!_dFYCBWtazp](https://github.com/ppy/osu/assets/105038735/f98981cc-cbc9-4266-9ea3-1e85f287da69)

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14117498/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-31 21:35
duplicate of https://github.com/ppy/osu/issues/24664

**Closed by bdach** 2024-01-31 21:35 UTC
