### ISSUE TITLE
osu lazer flashlight 

### ISSUE THREAD

**Issue by chipscaper** [ppy/osu#12690] opened 2021-05-05 17:41 UTC
i posted this to the osu! reddit and i was told to report it here so i will
i think flashlight looks very strange and it kind of ruins the experience for me i'm wondering if it could be more like stable's flashlight or maybe an option to change it to that
lazer: https://gyazo.com/b4e742b1f2df83d6756038a802b2054a
stable: https://gyazo.com/0f0454076cc8e11235c58e17936d32b4
that's the difference

**Comment by frenzibyte** [comment] 2021-05-05 17:42
Probably duplicate of #12417

**Closed by frenzibyte** 2021-05-05 17:42 UTC
