### ISSUE TITLE
Crash by deleting a skin component while shaking it

### ISSUE THREAD

**Issue by soopax** [ppy/osu#23518] opened 2023-05-12 16:37 UTC
### Type

Crash to desktop

### Bug description

Found by messing around in the skin editor.
# Steps to reproduce
1. Open the skin editor (`Ctrl-Shift-S`)
2. In the scene library, click on song select
3. In the list of components, click on Big Black Box
4. Start dragging the Big Black Box and rapidly shaking it
5. When you are shaking the Big Black Box, press `Delete`

If the game didn't crash, undo the deletion and try repeating steps 4 and 5 a couple times.
## Expected results
The Big Black Box should get deleted.
## Actual results
Sometimes the game crashes when I do this.

### Screenshots or videos

[2023-05-12_18-43-37.zip](https://github.com/ppy/osu/files/11466078/2023-05-12_18-43-37.zip)
GitHub doesn't allow uploading the file directly 😒

### Version

2023.511.0

### Logs

[database.log](https://github.com/ppy/osu/files/11466088/database.log)
[input.log](https://github.com/ppy/osu/files/11466089/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11466090/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11466091/network.log)
[performance.log](https://github.com/ppy/osu/files/11466092/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11466093/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11466094/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11466095/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11466096/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11466097/runtime.log)

**Comment by hwabis** [comment] 2023-05-25 00:00
The cause is `drawable.Parent` being null [here](https://github.com/ppy/osu/blob/59768c5ffd9d4b99c80ce4396b92dd6e1a6211f6/osu.Game/Extensions/DrawableExtensions.cs#LL45C13-L45C28), would a fix be just to check if it's null?

**Comment by peppy** [comment] 2023-05-25 09:04
```diff
diff --git a/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs b/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
index 0fcf84ec8e..56a6b18433 100644
--- a/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
+++ b/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
@@ -92,7 +92,6 @@ private void load()
             };
 
             SelectionHandler = CreateSelectionHandler();
-            SelectionHandler.DeselectAll = DeselectAll;
             SelectionHandler.SelectedItems.BindTo(SelectedItems);
 
             AddRangeInternal(new[]
diff --git a/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs b/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
index 9e4fb26688..5cedf1ca42 100644
--- a/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
+++ b/osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
@@ -197,9 +197,9 @@ public void OnReleased(KeyBindingReleaseEvent<PlatformAction> e)
         #region Selection Handling
 
         /// <summary>
-        /// Bind an action to deselect all selected blueprints.
+        /// Deselect all selected items.
         /// </summary>
-        internal Action DeselectAll { private get; set; }
+        protected void DeselectAll() => SelectedItems.Clear();
 
         /// <summary>
         /// Handle a blueprint becoming selected.
@@ -303,7 +303,7 @@ private bool ensureSelected(SelectionBlueprint<T> blueprint)
             if (blueprint.IsSelected)
                 return false;
 
-            DeselectAll?.Invoke();
+            DeselectAll();
             blueprint.Select();
             return true;
         }
@@ -311,6 +311,7 @@ private bool ensureSelected(SelectionBlueprint<T> blueprint)
         protected void DeleteSelected()
         {
             DeleteItems(SelectedItems.ToArray());
+            DeselectAll();
         }
 
         #endregion

```

Does this patch fix the issue? I don't have a mouse handy so can't immediately test but I think it might be enough.

**Comment by peppy** [comment] 2023-05-25 14:21
Thanks, I've just committed this as part of https://github.com/ppy/osu/pull/23660.

**Closed** 2023-05-25 15:27 UTC
Labels: type:reliability, area:skin-editor
