### ISSUE TITLE
Mod select shows 0* in the Daily Challenge

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29109] opened 2024-07-26 13:37 UTC
### Type

Crash to desktop

### Bug description

The title already explains it. When picking mods i noticed that the SR is shown as 0 stars in the daily challenge menu

### Screenshots or videos

![image](https://github.com/user-attachments/assets/b91e1215-f4e8-4faf-bb2a-b68954f09d24)

### Version

osu! version: Lazer 2024.726.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16392425/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-26 13:38
Duplicate of https://github.com/ppy/osu/issues/29094, will be fixed next hotfix release.

**Closed by frenzibyte** 2024-07-26 13:38 UTC
