### ISSUE TITLE
osu!lazer keyboard inputs not working on Samsung S20 EU

### ISSUE THREAD

**Issue by Acid-Nemesis** [ppy/osu#8332] opened 2020-03-17 22:05 UTC
Problem details:
So the problem is that when I try to type in my username or my password, or just when I want to type a beatmap name, it just doesn't work, the ONLY thing that inputs something, is the auto-correct, other than that I cannot type any character.

Video showing the problem:
https://youtu.be/PMdHdTl-ncw

osu!lazer version: Lazer 2020.312.0

**Comment by TheWildTree** [comment] 2020-03-17 22:08
Duplicate of #8264.

Please try installing a different keyboard (Gboard, for example) and see if it works.

**Closed** 2020-03-17 22:15 UTC
