### ISSUE TITLE
osu!lazer hard crash on Intel HD Graphics 3000

### ISSUE THREAD

**Issue by MeguMario** [ppy/osu#6585] opened 2019-10-23 17:13 UTC
**Describe the crash:** Upon updating to tag 2019.1021.0 (edit: also happened on 2019.1011.0), the game crashed immediately. (coincidentaly both of this version use .NET Core 3.0)

**Screenshots or videos showing encountered issue:** 
2019.1021.0 https://streamable.com/7spnp
Stable works fine: https://streamable.com/u1u53
and just to be sure that everything work fine perior to 2019.1011.0, here is 2019.930.0
https://streamable.com/y0181

**osu!lazer version:** 2019.1021.0 / 2019.1011.0

**Logs:** 
2019.1021.0
[runtime.log](https://github.com/ppy/osu/files/3763530/runtime.log)
2019.1011.0
[runtime.log](https://github.com/ppy/osu/files/3763609/runtime.log)
(essentially the same)
No further log has been provided since the game not even launch
for comparison, this is 2019.930.0
[runtime.log](https://github.com/ppy/osu/files/3763642/runtime.log)

**Computer Specifications:** 
CPU: Intel Core i3-2350M 2.3GHz
GPU: Intel HD Graphics 3000
RAM: 4GB
OS: Windows 10 1903

**Comment by bdach** [comment] 2019-10-23 17:26
Judging from the bogus GDI renderer, this is a duplicate of #6496.

**Closed by bdach** 2019-10-23 17:26 UTC
