### ISSUE TITLE
Seeking to the end of a replay, waiting, and then seeking back freezes the replay

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#9602] opened 2020-07-18 01:29 UTC
**Describe the bug:** 
While playing a replay, after seeking to the end, and waiting long enough (until the audio stops...?), seeking back causes the replay to freeze once it catches up. Something like that.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/1ziqaw

**osu!lazer version:** 
2020.717.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4940895/database.log)
[network.log](https://github.com/ppy/osu/files/4940900/network.log)
[performance.log](https://github.com/ppy/osu/files/4940897/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4940898/runtime.log)

**Comment by Joehuu** [comment] 2020-07-18 02:48
Duplicate of https://github.com/ppy/osu/issues/7295

**Closed by Joehuu** 2020-07-18 02:48 UTC
