### ISSUE TITLE
osu!lazer problem

### ISSUE THREAD

**Issue by shibou3** [ppy/osu#1996] opened 2018-01-31 02:17 UTC
I used to be able to run lazer in my old pc but since i got this new laptop it doesn't run properly. Every time i try to install+run the game the screen goes like the print and nothing happens, is there any solutions?
![2018-01-31_00-07-27](https://user-images.githubusercontent.com/23579978/35601756-e3ec6e4c-061b-11e8-8aa3-4f4a612c1f1a.jpg)

**Comment by peppy** [comment] 2018-01-31 03:25
Duplicate of #1388.

**Closed by peppy** 2018-01-31 03:25 UTC
