### ISSUE TITLE
Selecting a beatmap after the song ends will move to the next song in the playlist

### ISSUE THREAD

**Issue by WalterToro** [ppy/osu#1608] opened 2017-11-28 04:11 UTC
Like the title says, also, if this happens to be the last song in the playlist, the client will crash.

Video for reference: https://walter.s-ul.eu/m1ODnYwP.mp4

**Comment by peppy** [comment] 2017-11-28 04:14
Probably related/duplicate of https://github.com/ppy/osu/issues/1522

**Comment by Aergwyn** [comment] 2017-11-28 05:06
It is a duplicate yes. I'll redo my PR to osu-framework right now that fixes this.

**Comment by Aergwyn** [comment] 2017-12-08 08:21
@WalterToro does this still happen? It should be fixed by now.

**Comment by WalterToro** [comment] 2017-12-08 21:51
@Aergwyn in song select seems to "sometimes" (i dont know how) change song and not loop the song.

Proof here (first time loops, next changes)
![](https://walter.s-ul.eu/C8grieLd.gif)

**Comment by Aergwyn** [comment] 2017-12-08 21:55
That gif doesn't seem to show enough to see anything thouhg. :( It repeats after like 3 seconds.

**Closed** 2017-12-10 15:00 UTC
Labels: audio, bug
