### ISSUE TITLE
Audio and video desync while scrolling through maps with auto

### ISSUE THREAD

**Issue by QiiXshinez** [ppy/osu#10035] opened 2020-09-01 18:46 UTC
**Describe the bug:** With auto, if you scroll through maps, the audio will retain normal speed while the gameplay speeds up, slows down, reverses, etc to try and catch up with the audio, leading to desync.

**Screenshots or videos showing encountered issue:** https://youtu.be/dwBFGRDyXT4

**osu!lazer version:** 2020.825.0 (iOS version is 13.4.1)

**Logs:** Can’t find logs on iOS, sorry

**Comment by Joehuu** [comment] 2020-09-01 19:12
Duplicate of https://github.com/ppy/osu/issues/5119

**Closed by Joehuu** 2020-09-01 19:12 UTC
