### ISSUE TITLE
Dull / grey-ish colours after game update

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#22025] opened 2023-01-04 09:33 UTC
### Type

Cosmetic

### Bug description

Since i updated the game (from lazer 20222.1208.0 to lazer 2022.1228.0) everything is a lot more dull and almost grey-ish than before, as if the game doesn't recognise i'm playing on an HDR display (i've checked both system settings and display settings, HDR is enable, works outside of the game). It is occuring game wide (main menu, song select and during gameplay).
I'm using a mac studio running macos ventura 13.0 with two acer xv272u kv displays.
I haven't changed/edited the skin for a few game versions, pratically excluding it as the cause for the change in colours.
In mania i used to have bright cyan arrows as notes, since the update to 2022.1228.0 (skipped 2022.1227.0, so could've been since that version as well) they look more like a blue-ish grey.

### Version

Lazer 2022.1208.0

### Logs

[database.log](https://github.com/ppy/osu/files/10342807/database.log)
[input.log](https://github.com/ppy/osu/files/10342808/input.log)
[network.log](https://github.com/ppy/osu/files/10342809/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/10342810/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10342811/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10342812/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10342813/runtime.log)

**Comment by peppy** [comment] 2023-01-04 10:35
I can't reproduce this locally on an HDR display on macOS, so not sure about that. Have you gone back and tested the previous release to confirm it's not an external factory already?

**Comment by SevenChords** [comment] 2023-01-04 10:57
Just did a side by side comparison between 2022.1208.0 and 2022.1228.0, the colours are a lot duller in 2022.1228.0, both on the display and in screenshots, something definitely changed, but i noticed the same difference between the two version with hdr turned off as well, so nothing to do with hdr after all, still curious tho as to what happened and if there is a way to get the old colours back.
2022.1208.0:
![image](https://user-images.githubusercontent.com/31819497/210540079-00c6244d-58a2-4003-9709-fc0729dbee1e.png)
![image](https://user-images.githubusercontent.com/31819497/210540133-5328ce49-6614-4ebd-8fd8-53cc5bd1f750.png)
2022.1228.0:
![image](https://user-images.githubusercontent.com/31819497/210540310-20efa4d0-f4b6-47f4-9358-b0d8f81cb181.png)
![image](https://user-images.githubusercontent.com/31819497/210540384-5ae2ac92-173d-4688-b2bb-710525f12d8e.png)

**Comment by frenzibyte** [comment] 2023-01-04 11:47
This change in behaviour first arose in https://github.com/ppy/osu-framework/pull/5579, which covers the following commit range https://github.com/libsdl-org/SDL/compare/413500ab69d9ac288a73946073d4414376ca17d2...faa7e3cc2e0de5867ab7c0a7376e67bca89c7f0f. I'm going to guess it's caused by https://github.com/libsdl-org/SDL/commit/d2300516c3998277c993fd4ac336fbb4ba71641a specifically given the description, and either way HDR looks too saturated according to my monitor (VG27AQ) prior to this change so it honestly looks more like a fix to me than a regression. For example, this is how it looks for me on the main menu screen:

- 2022.1208.0:
  
  ![CleanShot 2023-01-04 at 14 36 47](https://user-images.githubusercontent.com/22781491/210546989-3456dc2b-58d8-491d-b6de-10c128a2b481.png)

- 2022.1228.0:

  ![CleanShot 2023-01-04 at 14 40 55](https://user-images.githubusercontent.com/22781491/210547620-7066550d-c4b3-4136-ab68-9cfcdad80c7b.png)

But I'm not really an expert in HDR technology so I'm not entirely sure what I'm seeing here (@peppy thoughts maybe? but I guess it's hard to tell from just a screenshot).

**Comment by SevenChords** [comment] 2023-01-04 11:59
i don't mind the look in the menus, but during gameplay i find the higher contrast of the older versions a lot easier to read in mania.
the colours after the change seem to be closer to the standard/stable client, while the colours prior to the change seem to be closer to the redesigned webpage, which i always thought was intentional and part of the overall design of osu lazer

**Comment by peppy** [comment] 2023-01-04 13:36
Yeah sorry, I was testing with incorrect display settings. I can repro the change.

The new version is more correct. I've mentioned this a few times in the past as being an issue. We have also discussed internally actually making use of the HDR colourspace, but I don't think it should be linearly applied as it was until now. Especially on some devices, it created a sickeningly saturated look.

I think for now closing this as "working as intended" is correct.

**Closed by peppy** 2023-01-04 13:36 UTC
