### ISSUE TITLE
Entering and exiting songlist rapidly causing a crash

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#2797] opened 2018-06-14 00:15 UTC
[runtime.log](https://github.com/ppy/osu/files/2100378/runtime.log)

Works a bit different than the Editor one can get a video if needed

**Comment by Joehuu** [comment] 2018-06-14 00:34
Duplicate of #2681?

**Comment by peppy** [comment] 2018-06-14 07:06
Closing as duplicate of #2681.

**Closed by peppy** 2018-06-14 07:06 UTC
