### ISSUE TITLE
Local scores don't get removed after editing a map, and trying to watch them causes an error

### ISSUE THREAD

**Issue by dequubi** [ppy/osu#22062] opened 2023-01-07 12:09 UTC
### Type

Game behaviour

### Bug description

Might be the same problem as #17485? Not sure, so I'll post it just in case.

Local scores don't get removed after editing a map (in stable they do), and trying to watch them causes an error. Updating the map afterwards removes the scores from an edited difficulty.

### Screenshots or videos

https://user-images.githubusercontent.com/47535336/211149782-9a645147-c3af-4741-97cb-1d583c36a567.mp4

### Version

2022.1228.0

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/10366197/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10366198/network.log)
[performance.log](https://github.com/ppy/osu/files/10366199/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10366200/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10366201/updater.log)
[database.log](https://github.com/ppy/osu/files/10366202/database.log)
[input.log](https://github.com/ppy/osu/files/10366203/input.log)

**Comment by Cootz** [comment] 2023-01-10 18:48
### `BeatmapManager` updates score's beatmap property while saving changes made in editor
For some reason `BeatmapManager` updates score's beatmap property while saving changes (probably link to a class?). It update beatmap hash and md5hash of scores on saving and `BeatmapLeaderBord` gets scores of map's previous version as new one.
After updating the map scores cannot be resolved anymore since they have different beatmap cache.
>Updating the map afterwards removes the scores from an edited difficulty.

I've made some testing on it.
#### Test conditions
I've added some logging to `BeatmapManager.Save` and `BeatmapLeaderboard.localScoresChanged` methods that logs info about beatmap and scores (only for BeatmapLeaderBord). Representing log files are `beatmapsave` and `scores`.
Steps to reproduce:
1. play a map
1. view local scores
1. change something in editor and save the changes
1. view local scores
1. play map again
1. view local scores 

#### Logs:
- beatmapsave
```
2023-01-10 18:12:09 [verbose]: Saving beatmap RealmUser (unmanaged) - oyasumi (Speed Up Ver.)[Another]
2023-01-10 18:12:09 [verbose]: Old MD5Hash: a371a3c20a01cebba97e8afaaafee0ac Hash: 630cb43be5b4e84c4ea85320beca1d3793fb09d5d6646e034b0359eabac70772
2023-01-10 18:12:09 [verbose]: New MD5Hash: 79b630d5978863f263c066e2a4798d8d Hash: 7c0773b066aff5fcef9b08c388931a2c706669eb3781548b663e190b7b780cba
```
- scores
```
2023-01-10 18:11:52 [verbose]: Bitmap Name:oyasumi (Speed Up Ver.) Diff name: Another ID: 77156d63-2028-42a4-8876-599edd0d68db Hash: 630cb43be5b4e84c4ea85320beca1d3793fb09d5d6646e034b0359eabac70772 MD5Hash: a371a3c20a01cebba97e8afaaafee0ac
2023-01-10 18:11:52 [verbose]: Score ID: 39b38ee4-20f4-46cf-9c73-163e7d56c1de Accurasy: 0.7076010544815465 Date: 1/10/2023 6:11:43 PM +00:00
2023-01-10 18:12:58 [verbose]: Bitmap Name:oyasumi (Speed Up Ver.) Diff name: Another ID: 77156d63-2028-42a4-8876-599edd0d68db Hash: 7c0773b066aff5fcef9b08c388931a2c706669eb3781548b663e190b7b780cba MD5Hash: 79b630d5978863f263c066e2a4798d8d
2023-01-10 18:12:58 [verbose]: Score ID: d51bf189-a645-4de5-9db7-7020d1b90459 Accurasy: 0.7394270122783083 Date: 1/10/2023 6:12:57 PM +00:00
2023-01-10 18:12:58 [verbose]: Bitmap Name:oyasumi (Speed Up Ver.) Diff name: Another ID: 77156d63-2028-42a4-8876-599edd0d68db Hash: 7c0773b066aff5fcef9b08c388931a2c706669eb3781548b663e190b7b780cba MD5Hash: 79b630d5978863f263c066e2a4798d8d
2023-01-10 18:12:58 [verbose]: Score ID: 39b38ee4-20f4-46cf-9c73-163e7d56c1de Accurasy: 0.7076010544815465 Date: 1/10/2023 6:11:43 PM +00:00
2023-01-10 18:13:02 [verbose]: Bitmap Name:oyasumi (Speed Up Ver.) Diff name: Another ID: 77156d63-2028-42a4-8876-599edd0d68db Hash: 7c0773b066aff5fcef9b08c388931a2c706669eb3781548b663e190b7b780cba MD5Hash: 79b630d5978863f263c066e2a4798d8d
2023-01-10 18:13:02 [verbose]: Score ID: d51bf189-a645-4de5-9db7-7020d1b90459 Accurasy: 0.7394270122783083 Date: 1/10/2023 6:12:57 PM +00:00
2023-01-10 18:13:02 [verbose]: Bitmap Name:oyasumi (Speed Up Ver.) Diff name: Another ID: 77156d63-2028-42a4-8876-599edd0d68db Hash: 7c0773b066aff5fcef9b08c388931a2c706669eb3781548b663e190b7b780cba MD5Hash: 79b630d5978863f263c066e2a4798d8d
2023-01-10 18:13:02 [verbose]: Score ID: 39b38ee4-20f4-46cf-9c73-163e7d56c1de Accurasy: 0.7076010544815465 Date: 1/10/2023 6:11:43 PM +00:00
```

**Comment by Cootz** [comment] 2023-02-02 17:59
*Bringing some updates to this thread*
#### What causes the issue?
__Realm__
#### Why does it happen?
The `ScoreInfo` class defines `BeatmapInfo` as reference to the `Beatmap` table's entry. 
https://github.com/ppy/osu/blob/6c0aada86a1203194f66126389131c379cc873c9/osu.Game/Scoring/ScoreInfo.cs#L32
`BeatmapInfo` provides back link to `ScoreInfo`
https://github.com/ppy/osu/blob/6c0aada86a1203194f66126389131c379cc873c9/osu.Game/Beatmaps/BeatmapInfo.cs#L46-L48
With that said when `BeatmapManager.Save()` invokes it updates both `Beatmap` table entry **and** `Score` reference (see [media](#Media)).
#### What are the consequences?
Since `Beatmap` and `Score` tables are linked together whenever any class requests data from realm it gets `ScoreInfo` instance with **updated** `BeatmapInfo`. Since it requires database update, @peppy, can it be marked for now and fixed with next planned realm update?
#### Media
![image](https://user-images.githubusercontent.com/50776304/216400798-93d6e36f-37e9-454b-bd9e-b55754ef93a4.png)
![image](https://user-images.githubusercontent.com/50776304/216400884-0c8b76af-8836-44ef-a2b3-ab85700e8e26.png)

**Comment by peppy** [comment] 2023-02-03 06:13
I'm not sure what you mean by "marked".

The cause is very obvious, but it will need a fix applied at a code level, and consideration as to *how* it should be fixed.

**Comment by Cootz** [comment] 2023-02-03 12:00
> _how_ it should be fixed

Mb add `OriginalBeatmapHash` property to `ScoreInfo.cs` and check if current beatmap hash equal to original one we show the score, otherwise do not.

**Comment by Cootz** [comment] 2023-02-06 10:32
@peppy, well. I'm interested in attempting this issue. The idea is described [here](https://github.com/ppy/osu/issues/22062#issuecomment-1415770841). Should I stick to it or try any other approach?

**Closed** 2023-03-16 11:28 UTC
Labels: area:database, priority:2, area:beatmap-change-tracking
