### ISSUE TITLE
Font not displaying correctly on MacOS.

### ISSUE THREAD

**Issue by Agrrox** [ppy/osu#11730] opened 2021-02-11 00:35 UTC
**Describe the bug:** 
Font is not displaying correctly on MacOS

Specs:
OS: MacOS High Sierra 10.13.6
MacBook Pro 6,1 (17-inch, Mid 2010)
Processor:	Intel Core i7 2,66 GHz 
Memory: 8 GB 1067 MHz DDR3
Graphics: NVIDIA GeForce GT 330M 512 MB (OpenGL support: 3.3) | Intel HD Graphics 288 MB

**Screenshots or videos showing encountered issue:** 
![Screen Shot 2021-02-11 at 01 22 13](https://user-images.githubusercontent.com/10901821/107590144-bdcf9180-6c07-11eb-8bca-903ce0e07e28.png)

**osu!lazer version:** 
2021.205.1
(this issue started many versions before)

**Logs:**
[database.log](https://github.com/ppy/osu/files/5962512/database.log)
[network.log](https://github.com/ppy/osu/files/5962513/network.log)
[performance.log](https://github.com/ppy/osu/files/5962514/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5962515/runtime.log)

**Comment by frenzibyte** [comment] 2021-02-11 00:37
Duplicate of https://github.com/ppy/osu/issues/9314, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2021-02-11 00:42 UTC
