### ISSUE TITLE
Add AppImage building to CI

### ISSUE THREAD

**Issue by Dadoum** [ppy/osu#7558] opened 2020-01-18 21:10 UTC
**Describe the new feature:** 
An AppImage is an universal format for Linux. It is a DMG-like implementation that works on almost all distributions.

**Proposal designs of the feature:** 
The automation is not to hard to implement, just few commands on terminal.
The auto-updating is easy, just bundle an AppImageUpdate 
I use on my repository iCode an implementation in plain C# .NET Core (without marshal).
It is easy to detect if it is running from AppImage by looking at the environment variable APPIMAGE.
It is easy to check updates and updates by using either a libappimageupdate with cppsharp (long and hard) or a AppImageUpdate executable inside (my method).

**Comment by jai-x** [comment] 2020-01-18 21:14
Duplicate of discussion in this issue: https://github.com/ppy/osu/issues/2960

I think you would need to open a PR against the osu-deploy for this functionality: https://github.com/ppy/osu-deploy

**Comment by iiSaLMaN** [comment] 2020-01-18 21:26
This is in-fact a duplicate of #2960 and will be addressed in ppy/osu-deploy#1

**Closed** 2020-01-18 21:47 UTC

**Comment by Dadoum** [comment] 2020-01-20 21:44
@jai-x Opened pull request !
