### ISSUE TITLE
One of the beatmaps doesn't get the update prompt in song select

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#24228] opened 2023-07-15 10:10 UTC
### Type

Game behaviour

### Bug description

I had a version of the mapset for some time now, and now that it's in Qualified, for some reason it doesn't get the update prompt and it's in Pending according to the game. After clicking "Details", it shows that it's Qualified in the in-game browser

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/82095491/ffd60307-7dae-4fb8-bbd8-3e1517dd19a8)
![image](https://github.com/ppy/osu/assets/82095491/e718ed9c-778e-4185-a2f3-966d52d7a25c)

### Version

2023.621.0-lazer

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/12061110/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12061111/network.log)
[performance.log](https://github.com/ppy/osu/files/12061112/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12061113/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12061114/updater.log)
[database.log](https://github.com/ppy/osu/files/12061115/database.log)
[input.log](https://github.com/ppy/osu/files/12061116/input.log)

**Comment by Skubers** [comment] 2023-07-15 10:12
Deleting the mapset and redownloading it through website didn't work.

The thing that worked is deleting the mapset, closing the game and then redownloading it.

**Comment by bdach** [comment] 2023-07-15 12:51
Presumably duplicate of https://github.com/ppy/osu/issues/23804

**Closed by bdach** 2023-07-15 12:51 UTC
