### ISSUE TITLE
There's no way to update a map to its most recent version.

### ISSUE THREAD

**Issue by maotovisk** [ppy/osu#12329] opened 2021-04-07 18:19 UTC
As the title says, there is no option to check if a map is in its most recent version and update it. It is useful for people aiming to mod on lazer. 

Stable works like that:
Update Available  | Most Recent Version
--- | ---
![update](https://user-images.githubusercontent.com/20617307/113914459-f5942900-97b3-11eb-8d55-b9ff6d2bcb3d.png) | ![no update](https://user-images.githubusercontent.com/20617307/113914542-0a70bc80-97b4-11eb-8b7d-eebbd7b8b040.png)

**Comment by Joehuu** [comment] 2021-04-07 18:20
Duplicate of https://github.com/ppy/osu/issues/4823

**Closed by Joehuu** 2021-04-07 18:20 UTC
