### ISSUE TITLE
follow points are way to early osulazer

### ISSUE THREAD

**Issue by assailant123** [ppy/osu#7412] opened 2020-01-01 01:19 UTC
the follow points on my skin are way to early and it makes maps unreadable, it's so distracting. This is only with this skin too.

-------------------------------------

https://drive.google.com/open?id=1LagrLGCDCSFJrnafVHsXF0hjtNltZheG
clip of the issue^^

-------------------------------------

https://drive.google.com/open?id=1iDoCM99aMCBRzM8oYAyYNccmEUKbgQtj
skin^^

**Comment by mcendu** [comment] 2020-01-01 01:40
Please don't mess up with formatting.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by vruss** [comment] 2020-01-01 10:20
I also noticed this while using a [skin](https://drive.google.com/file/d/1eObmw6NdJqJ1c-ANozdcxWXjzlef_mTU/view) with less animated followpoints. I tried to take two pictures of stable and lazer using the same skin to showcase the difference:

![early lazer followpoints](https://i.imgur.com/XUbyr7B.png)
![stable followpoints](https://i.imgur.com/3hPaNnY.png)

It looks like the lazer followpoints are almost 2 notes ahead.

**Comment by bdach** [comment] 2020-01-01 10:25
Duplicate of #6214.

**Closed by bdach** 2020-01-01 10:25 UTC
