### ISSUE TITLE
Collctions dropdown menu goes off screen when game is scaled

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#26932] opened 2024-02-01 19:53 UTC
### Type

Game behaviour

### Bug description

1. Use either "Excluding overlay" or "Everything" scaling modes
2. Right click on beatmap on the edge of the scaled screen
3. Move mouse over to "Collections"
4. The collections thing show up, but you can't select anything because it's outside of the scaled screen.

This is not an issue when using scaling modes like "Off" or "Gamplay".

### Screenshots or videos

https://github.com/ppy/osu/assets/50755746/f72be75b-abf7-4e42-9f8f-fd89dbb20425

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14130045/compressed-logs.zip)

**Comment by bdach** [comment] 2024-02-01 19:59
This is a framework shortcoming. Menu overflow logic is based on the bounds of the parenting `InputManager` and not the `ContextMenuContainer`.

In 2022 [I said this](https://github.com/ppy/osu-framework/pull/4987):

> The contentious part of this may be that I'm using `GetContainingInputManager()` to perform this positioning. This is done because the menu's parent is not necessarily its clipping bounds. And it's not like the menu _has_ to have a parenting `ContextMenuContainer` or other drawable to work correctly. So clipping to the input manager seemed like the closest thing to "clipping to window bounds".

Not sure how to feel about that now. Maybe we should be trying to find a parenting `ContextMenuContainer` first and only fall back to `GetContainingInputManager()` if that fails. Bit of a scary change to make though.

**Comment by Joehuu** [comment] 2024-02-01 20:03
Duplicate of https://github.com/ppy/osu/issues/17436

**Comment by bdach** [comment] 2024-02-01 20:04
O_O okay nice find

**Closed by Joehuu** 2024-02-01 20:03 UTC
Labels: osu!framework issue, area:song-select
