### ISSUE TITLE
Allow FLAC audio in beatmaps.

### ISSUE THREAD

**Issue by ILOVEPIE** [ppy/osu#12292] opened 2021-04-04 19:08 UTC
**Describe the new feature:** 
FLAC is a lossless audio compression format that is royalty free and embed-able in a large number of container formats including .mkv/.mka and .mp4 as well as in it's own container(.flac).
**Proposal designs of the feature:** 
All this would require would be changing the compile options for the ffmpeg libraries used by laser and maybe a few small code tweaks to allow for .flac files to be imported into the beatmap editor.

**Comment by jai-x** [comment] 2021-04-04 19:09
Duplicate of https://github.com/ppy/osu/issues/10618 I think

**Closed by jai-x** 2021-04-04 19:09 UTC

**Comment by ILOVEPIE** [comment] 2021-04-04 19:10
This isn't something that's impossible to do, all you have to do is embed the .flac file in an mp4 and it will work with the online services as browsers can play flac that is embedded in an mp4.

**Comment by jai-x** [comment] 2021-04-04 19:14
It's definitely technically possible, but I would guess it's not worth the extra storage requirements server side for a marginal improvement in a audio quality. However I'm not in the best position to answer this.

**Comment by bdach** [comment] 2021-04-04 19:15
Let's just say that in the grand scheme of things this is a very low priority item. As stated in the original issue.

**Comment by peppy** [comment] 2021-04-05 01:21
This would be considered a ranking criteria change, and not one we are interested in. Has been discussed in the past. I don't see a need for this unless we are willing to provide the surrounding infrastructure support, which I'm not currently.
