### ISSUE TITLE
Scaling Doesn't Apply to the Score Screen hit Counters

### ISSUE THREAD

**Issue by Squaduck** [ppy/osu#7148] opened 2019-12-10 21:44 UTC
On the score screen after you beat a map or look at someones play the hit counters that tell you how many 300 point hits 100 point hits and 50 point hits you got isn't scaled correctly (yes I know it changed what it counts)
Scaled:
![osu_2019-12-10_16-24-07](https://user-images.githubusercontent.com/55469508/70571584-2aff1700-1b6c-11ea-9b6f-b0dd7571b459.jpg)
Normal:
![osu_2019-12-10_16-24-23](https://user-images.githubusercontent.com/55469508/70571585-2aff1700-1b6c-11ea-8068-d0dce0a4505d.jpg)

**Comment by Joehuu** [comment] 2019-12-10 21:48
Duplicate of https://github.com/ppy/osu/issues/4791

**Closed by Joehuu** 2019-12-10 21:48 UTC
