### ISSUE TITLE
Multiplayer auto skip intro doesn't work correctly

### ISSUE THREAD

**Issue by timiimit** [ppy/osu#23583] opened 2023-05-17 09:05 UTC
### Type

Game behaviour

### Bug description

When auto-skip beatmap intro option is enabled in multi room, there are 3 different cases that can happen to the player when match is started:
1) auto-skip works and player skips to the beginning of the map
2) auto-skip doesn't work and player gets the option to skip, but it does not trigger automatically
3) auto-skip doesn't work and player is completely unable to skip

This issue has been a problem ever since the option was added as far as i remember.

*2.* is not that big of a problem for players, because at least you are still able to skip. You can see this happening quite often in the video i linked.

*3.* is the real issue here. It is more rare than *2*. I was only able to replicate it once locally (wasn't recording at the time). It also seems that some people are more prone to *3.* than others. From personal experience i know that when i am playing with a certain player and *3.* happens, then it also happens for that player. There are also people for who it seems like *3.* happens very rarely or even never.

When it does happen, then everyone has to wait for the duration of the intro. Those affected by the bug wait at the beginning and the rest of the players have to wait before the results screen gets shown (waiting for those that were waiting at the beginning).

I believe that because of *3.* there are some hosts that deliberately don't enable the auto-skip option, so that everyone has the same experience of waiting together for map to begin. When I am a victim of this bug I sometimes estimate when others are going to finish and i quit gameplay early to avoid making them wait.

### Screenshots or videos

https://youtu.be/L3C4BMa2Zxg

### Version

2023.513.0

### Logs

Don't think logs will reveal anything

**Comment by peppy** [comment] 2023-05-18 06:40
p0 pending investigation, as this sounds pretty serious if broken.

**Comment by timiimit** [comment] 2023-05-19 19:48
Evidence of *3.*: https://youtu.be/UyjW8pg5ygI
look at timestamps in description.
This happened on 2nd game after I joined the room

**Comment by timiimit** [comment] 2023-05-19 20:15
better view of the bug with longer intro and showing at the end that others stopped playing: https://youtu.be/YlSw5rTxWjM

**Comment by vardhaman69** [comment] 2023-06-11 20:02
yeah can't skip intros on android devices, others with desktops in the room can tho

**Comment by peppy** [comment] 2023-07-28 05:10
When this happens, logs would be very beneficial (from the player it happened to).

It's going to be a hard one to repro, so we may want to look at adding more log output around the gameplay / multiplayer clock operations.

**Comment by peppy** [comment] 2023-09-14 09:32
I'm dropping this down in priority because it's very hard to reproduce, and seemingly by the edit, doesn't have as much of an effect anymore.

**Comment by Joehuu** [comment] 2023-09-14 17:52
The triggering twice issue seems to be a duplicate of https://github.com/ppy/osu/issues/9787, judging from that edit. [That beatmap](https://osu.ppy.sh/beatmapsets/1448953#osu/3627870) (on easy, normal, and hard diff) in the video also skips twice in solo (when quick retrying), so closing.

**Closed by Joehuu** 2023-09-14 17:52 UTC
Labels: area:multiplayer, priority:1
