### ISSUE TITLE
Error "Failed to update room" when entering Multi's Recebtly Ended tab

### ISSUE THREAD

**Issue by Azzirah** [ppy/osu#11533] opened 2021-01-18 16:18 UTC
**Describe the bug:** When entering Multi, there were no rooms in the Open tab and going to the Recently Ended tab, I got three times the same error for 3 different (active?) rooms.

**Screenshots or videos showing encountered issue:** 
![osu_2021-01-18_17-02-25](https://user-images.githubusercontent.com/65025784/104938323-364b8580-59af-11eb-9c95-c896908aa568.jpg)

**osu!lazer version:** 2021.118.1

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5831334/runtime.log)
[network.log](https://github.com/ppy/osu/files/5831337/network.log)

**Comment by bdach** [comment] 2021-01-18 16:21
Duplicate of #11309

**Closed by bdach** 2021-01-18 16:21 UTC
