### ISSUE TITLE
Add option to change (bar/pie) and move song progress display

### ISSUE THREAD

**Issue by stageosu** [ppy/osu#9965] opened 2020-08-23 22:48 UTC
**Describe the new feature:** This feature would allow a user to select an option (under the "score meter type" drop-down menu) that allows the score meter to be on the bottom (like osu!Stable). Similarly, I would love to see an option for the "song progress meter" (I'm unsure of the official name) to be placed on the sides, instead of the bottom.

**Comment by Joehuu** [comment] 2020-08-23 23:07
First part is a duplicate of https://github.com/ppy/osu/issues/5932, renamed to get other part of issue.

**Comment by frenzibyte** [comment] 2020-08-24 03:27
Sounds like the other part lands in https://github.com/ppy/osu/issues/4632.

**Comment by bdach** [comment] 2020-08-24 05:02
Yeah, let's close as duplicate.

**Closed by bdach** 2020-08-24 05:02 UTC
Labels: area:skinning, type:UI
