### ISSUE TITLE
Beatmap freezes, and only the Beatmap.

### ISSUE THREAD

**Issue by Pneu666** [ppy/osu#14164] opened 2021-08-08 00:24 UTC
**Describe the bug:** my beatmap freezes after i search anything in the beatmap listing search bar. It triggers every time you search something on it

**Screenshots or videos showing encountered issue:**  https://youtu.be/4joVLYfRziw GitHub doesnt let me send it here

**osu!lazer version:**  2021.808.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6950045/database.log)
[network.log](https://github.com/ppy/osu/files/6950046/network.log)
[performance.log](https://github.com/ppy/osu/files/6950047/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6950048/runtime.log)

**Comment by frenzibyte** [comment] 2021-08-08 00:34
The end crash shows this to be a duplicate of https://github.com/ppy/osu-framework/issues/2669. Don't have any android device to further test with the steps you mentioned, however.

**Comment by Pneu666** [comment] 2021-08-08 01:18
well, i cannot confirm its 100%, but 

> ```
> 2021-08-07 23:54:09 [error]: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> 2021-08-07 23:54:09 [error]: at osuTK.FrameEventArgs.set_Time (System.Double value) [0x0000c] in <560e6a3363094fb79871b7a588fa261e>:0
> 2021-08-07 23:54:09 [error]: at osuTK.Android.AndroidGameView.RunIteration (System.Threading.CancellationToken token) [0x00045] in <63573e355d6f463f9922df9b162d1bf2>:0
> 2021-08-07 23:54:09 [error]: at osuTK.Android.AndroidGameView+<>c__DisplayClass58_0.<StartThread>b__2 (System.Object _) [0x00000] in <63573e355d6f463f9922df9b162d1bf2>:0
> 2021-08-07 23:54:09 [error]: at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <5d9d487509a74fac89cc3115e20a05ab>:0
> 2021-08-07 23:54:09 [error]: at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <5d9d487509a74fac89cc3115e20a05ab>:0
> 2021-08-07 23:54:09 [error]: at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <5d9d487509a74fac89cc3115e20a05ab>:0
> 2021-08-07 23:54:09 [error]: at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.22(intptr,intptr)
> ```
> 
> The end crash shows this to be a duplicate of [ppy/osu-framework#2669](https://github.com/ppy/osu-framework/issues/2669). Don't have any android device to further test with the steps you mentioned, however.
> 
> Can you confirm you get the same crash and stack trace on the `runtime.log` everytime you reproduce the crash, and can 100% confirm it's always relevant to searching in the beatmap listing search bar first, that's shocking to hear at first.

well i cannot confirm it is 100% but, the 2 times i searched some beatmaps this happened, i'll try to do it again. i'll show the results later

**Comment by Pneu666** [comment] 2021-08-08 01:32
First attempt: it glitched again. but the logs dont show anything uncommon.
[runtime.log](https://github.com/ppy/osu/files/6950085/runtime.log)

**Comment by frenzibyte** [comment] 2021-08-08 01:46
Second attempt crashed without any glitch beforehand? seems interesting.

**Comment by Pneu666** [comment] 2021-08-08 01:51
> Second attempt crashed without any glitch beforehand? seems interesting.
> 
> Can you state the device you're reproducing the issue with, along with the OS version.

Redmi Note 6 Pro
Android 9.0

**Comment by frenzibyte** [comment] 2021-08-08 02:01
Tentatively closing this as a duplicate of the mentioned issue https://github.com/ppy/osu-framework/issues/2669.

**Closed by frenzibyte** 2021-08-08 02:01 UTC

**Comment by frenzibyte** [comment] 2021-08-08 02:30
@Pneu666 Actually, could you test once more but with the frame limiter set to "VSync" please, so that the update frames do not exceed 60fps.

If it doesn't crash after a while, increase the limiter again and record a video (high quality) showing the crash, just to know what's the last FPS the update had before the crash occurs.

**Comment by Pneu666** [comment] 2021-08-09 23:42
hey sorry for the very late response, i guess you might wanna take a look on this... i just figured out you dont need to open the beatmap listing and it kinda happens on mania only, now in 2021.809.0
[runtime.log](https://github.com/ppy/osu/files/6957954/runtime.log)

https://user-images.githubusercontent.com/81386229/128787715-142566e2-0767-46d2-b755-e99c7bd5ab3e.mp4

**Comment by peppy** [comment] 2021-08-10 02:00
We are aware of this and tracking in the linked issue.
