### ISSUE TITLE
Alt tabbing while holding click makes the cursor stuck at a clicking state

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu#2943] opened 2018-07-03 05:31 UTC
Steps to reproduce:
1. Hold down left or right mouse button.
2. Alt tab and tab back.

**Comment by smoogipoo** [comment] 2018-07-03 05:37
Related/duplicate of #2694

**Comment by Joehuu** [comment] 2018-07-13 01:09
It was not related.

https://puu.sh/AVs92/f8f4158d81.mp4

**Comment by peppy** [comment] 2018-07-13 10:13
Do you have raw input on or off?

FWIW I cannot reproduce on mac, so likely something on windows specifically.

**Comment by ekrctb** [comment] 2018-07-13 10:35
I have been aware of this issue. As clicking again fixes sticking, I this it is not high priority, but it should be fixed soon (probably with an another issue which occurs in raw input and two mouse devices press a button).

**Comment by Joehuu** [comment] 2018-07-13 19:09
Doesn't matter if you have raw input on or off. Forgot a step, but you have to release the mouse button on the window you alt tabbed.

https://puu.sh/AVQfg/6113aaa4e8.mp4

The indicator means to release.

The first part was a clarification and the other part is probably the behavior around it (i.e. other windows block input or something).

https://puu.sh/AVQzh/445a6a8ccc.mp4 <- Another way to reproduce is using the multiple desktops switcher.

**Comment by Joehuu** [comment] 2020-06-07 19:29
Will be fixed in SDL.

**Comment by Joehuu** [comment] 2020-12-03 23:36
Fixed in SDL as of now, but it'll release the click, making unnecessary input if you leave the cursor in the same place (noticed that before).

![NX3oeiukYA](https://user-images.githubusercontent.com/35318437/101101243-053d0000-357d-11eb-98b0-7b2de2011698.gif)

**Comment by peppy** [comment] 2020-12-04 04:09
The release click is reported [here](https://github.com/ppy/osu-framework/issues/4055), can probably close this issue and track framework-side.

**Closed by peppy** 2020-12-04 04:09 UTC
Labels: fixed-in-sdl, framework-fix-required, low-priority, type:input
