### ISSUE TITLE
Long spinners in osu!catch drain too much health

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu#8369] opened 2020-03-20 05:41 UTC
**Describe the bug:** 
In some osu!catch maps, there are very long spinners. Since these don't seem to recover health (or at least, a very small amount of health), it just seems... unfair? Maybe even impossible? I'm not sure, but I felt like bringing it up regardless.
(While on the topic of spinners - I suppose this issue could potentially affect osu!standard as well? And also are spinners in osu!catch supposed to play finish sounds for every banana caught?)

**Screenshots or videos showing encountered issue:** 
[A recording of JonZkuu's replay](https://streamable.com/wtnrl)

**osu!lazer version:** 
2020.320.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/4358068/database.log)
[network.log](https://github.com/ppy/osu/files/4358072/network.log)
[performance.log](https://github.com/ppy/osu/files/4358070/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4358071/runtime.log)

**Comment by bdach** [comment] 2020-03-20 06:56
Duplicate of #7428

Please open a separate issue about the sounds.

**Closed by bdach** 2020-03-20 06:56 UTC
