### ISSUE TITLE
Toggle visual settings on a per-map basis

### ISSUE THREAD

**Issue by Muffyn** [ppy/osu#12366] opened 2021-04-11 04:18 UTC
**Describe the new feature:** 
On stable, if you individually change any of the visual settings while the map is loading, the game will apply and remember those changes for only that beatmap. On lazer, any change in visual settings is applied to every map that you play.

**Proposal designs of the feature:** 
Should match stable. Changes made before a map starts should be saved only for that map and remembered. Changes made in the options menu should be applied globally, except for maps where the visual settings have been manually adjusted.

(the visual settings I am referring to)
![screenshot037](https://user-images.githubusercontent.com/33764011/114292037-6ad05a00-9a51-11eb-8433-86f0b3ca052c.png)
![osu_2021-04-10_23-08-10](https://user-images.githubusercontent.com/33764011/114292066-a4a16080-9a51-11eb-8e27-b649632fd33e.jpg)

**Comment by peppy** [comment] 2021-04-11 04:22
This was intentionally omitted as it has regularly caused confusion for most users on stable. Can you describe the kind of situation where you would turn these settings on for a specific beatmap and want it to be stored for that beatmap alone? I don't think this will be returning without good reason (and hopefully even then, an alternative solution can be arrived at).

**Comment by Joehuu** [comment] 2021-04-11 04:31
Duplicate of https://github.com/ppy/osu/issues/5624

**Closed by Joehuu** 2021-04-11 04:31 UTC
Labels: proposal, type:UX

**Comment by Muffyn** [comment] 2021-04-11 05:28
A few examples of maps where I have toggled things off:
* Flashing or extremely grainy video (mostly very old maps) can be significantly more distracting than the average video https://osu.ppy.sh/beatmapsets/42527#osu/133723
* Hitsounds depart from what I would expect in a way that is very annoying (here, the miss and slider break sounds bother me) https://osu.ppy.sh/beatmapsets/332532#osu/736214
* Video is too sexualized (contains several people taking off their clothes and entering a hot tub in swimwear) https://osu.ppy.sh/beatmapsets/124463#osu/317249
* Background is too sexualized https://osu.ppy.sh/beatmapsets/798007#osu/1675837 https://osu.ppy.sh/beatmapsets/977787#osu/2106505

On top of these reasons, I will occasionally turn video off if I am trying to set a top play so that I can focus more on the notes.

I realize there is nothing objectively wrong with any of these visual settings, just expressing my own experience of why this feature is helpful. I generally do enjoy playing with video and storyboard, with an exception once every hundred maps or so.
(not sure if I'm supposed to respond here or in the linked issue)
