### ISSUE TITLE
Hyperfruit generates incorrectly on repeat sliders

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#9290] opened 2020-06-15 09:12 UTC
Originally posted by @KevKjef in https://github.com/ppy/osu-stable-issues/issues/478. This also applies to osu!lazer.

Wouldn't be surprised if it's related to the two `BUG!!`s:
https://github.com/ppy/osu/blob/c09868780e1d03703a18f37e512777fba3afe89c/osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs#L77-L81

**Comment by ekrctb** [comment] 2020-06-27 09:24
@smoogipoo That code is unrelated because it is only applied with HR mod.

I'm 80% sure this kind of weird hyperfruit generation is the consequence of the algorithm, and it is working as intended. A fruit becomes hyper when the algorithm thinks the distance to the next fruit is too wide to catch. But the distance calculation is affected by previous fruit placement by approximating the movement of the catcher. I made a diagram to explain it better:

![(PNG Image, 321 × 561 pixels)](https://user-images.githubusercontent.com/32995012/85919003-a7f0a480-b8a2-11ea-97be-4b6d048ace27.png)

The dashed arrow represents the simulated movement if the hyperfruit is not generated.

Also, weird placements are "fun" elements of the converted maps.

**Comment by smoogipoo** [comment] 2020-06-30 07:55
@ekrctb HR only affects normal fruits:
https://github.com/ppy/osu/blob/c09868780e1d03703a18f37e512777fba3afe89c/osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs#L61-L62
But what you mentioned also potentially contributes to it!

**Comment by KevKjef** [comment] 2020-06-30 07:59
@ekrctb 
The situation you sketched is not what is happening in the big black:
![bigblack1](https://user-images.githubusercontent.com/64087607/86099520-df846a00-bab7-11ea-8fc0-22d286fef407.png)
At the very least not on the first one. We can prove this as removing the slider on the right, makes it so the hyperfruit is not generated on the left stack.

While this means an extended version of that image applies, I feel that it would make more sense for the hyperfruit to generate on the slider on the right/the note in the middle.

Currently you land on the right of the middle fruit, which makes it so you land on the right of the first fruit of the stack (presumably)
If the first fruit were a hyper, you could land in the middle/left of the middle note, and this issue would not be present.

While I do think this can be a weird gimmick, I still think it would make more sense (and would be more playable) if the note before would be the hyperfruit

**Comment by KevKjef** [comment] 2020-06-30 08:24
There are also other issues with the way 'movement' is calculated in ctb, which might be related. 
This can be seen on https://osu.ppy.sh/beatmapsets/416662#fruits/902515 [hard pattern] for example 
![impossible](https://user-images.githubusercontent.com/64087607/86100646-6be35c80-bab9-11ea-85d4-cf560da9b0a0.PNG)
![screenshot147](https://user-images.githubusercontent.com/64087607/86100753-8d444880-bab9-11ea-9b5f-a3e0471000dc.jpg)
In the screenshots you can see the pattern, which causes this issue.
Basically, there is not enough time to move to the right, as the next note is there before you can catch it. (meaning you can never catch all notes)
The editor shows the pattern, which causes this issue.
This is just vertical sliders next to each other, yet it seems to matter if you are going to the left/right as hyperfruits are only generated when going from right to left, despite being the same pattern, except reversed.

I don't know if this could actually be related, but this impossible pattern can be an issue.
Especially, since ranked converts could potentially use this type of pattern.

**Comment by ekrctb** [comment] 2021-06-07 12:38
I close this issue.
The case of impossible pattern generation <https://github.com/ppy/osu/issues/9290#issuecomment-651638777> is tracked in #9026.
The weird pattern is not a bug, but a consequence of the current hyperdash generation algorithm.
There could be tweaks to the hyperdash generation algorithm so it generates "more playable maps", but it is subjective, and there is currently no consensus.
Potentially, algorithm changes can be made with a guard of using the old algorithm when the classic mod is added. Proposal to such changes can be discussed in [discussion](https://github.com/ppy/osu/discussions).

**Closed by ekrctb** 2021-06-07 12:38 UTC
Labels: area:gameplay, ruleset:osu!catch
