### ISSUE TITLE
Switching lazer to fullscreen hangs X11

### ISSUE THREAD

**Issue by OwczarekGit** [ppy/osu#14130] opened 2021-08-04 23:31 UTC
**Describe the bug:** 
Since release 2021.731.0 starting the game in fullscreen or switching to fullscreen hangs up X11, can't say if that also happened before i performed a system upgrade, but i tested it with previous releases of lazer and they work as expected (it only happens in 2021.731.0). Basically everything stops responding and i have to resort to changing to different tty and killing game - then X "unhangs". After killing lazer the terminal provides the following output:

`[I] czarek@Ryzen ~/Downloads [SIGTERM]> ./osu.AppImage `
`X Error of failed request:  BadMatch (invalid parameter attributes)`
`Major opcode of failed request:  140 (RANDR)`
`Minor opcode of failed request:  7 (RRSetScreenSize)`
` Serial number of failed request:  365`
` Current serial number in output stream:  367`

Seems to be some kind  of problem with Xrandr so here is the output of `xrandr --version`

`[I] czarek@Ryzen ~> xrandr --version`
`xrandr program version       1.5.1`
`Server reports RandR version 1.6`

And `xdpyinfo` states that the version of X.Org is: `X.Org version: 1.20.13`

**Screenshots or videos showing encountered issue:** 
Sorry for the quality, i had to record it with my phone cause like i say it hangs X.

https://user-images.githubusercontent.com/32412218/128267431-e94a7ded-e780-47fa-a69e-7825ca71fab5.mp4

**osu!lazer version:** 2021.731.0

**System**
ArchLinux kernel: 5.13.7
Ryzen 5 5600x
Nvidia gtx 970 with driver: 470.57.02
DE is Gnome 40.3.0 but i also tried it in dwm and the problem persists.

**Logs:**
[database.log](https://github.com/ppy/osu/files/6934851/database.log)
[network.log](https://github.com/ppy/osu/files/6934852/network.log)
[performance.log](https://github.com/ppy/osu/files/6934853/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6934854/runtime.log)

**Comment by frenzibyte** [comment] 2021-08-04 23:32
Duplicate of https://github.com/ppy/osu/issues/14085. Please search before reporting new issues.

**Closed by frenzibyte** 2021-08-04 23:32 UTC
