### ISSUE TITLE
osu!Lazer running in background without GUI

### ISSUE THREAD

**Issue by MidKnightXI** [ppy/osu#17838] opened 2022-04-15 22:00 UTC
### Type

Game behaviour

### Bug description

So I was just trying to launch osu!Lazer like a normal day but the game wouldn't launch.
I updated my system, reboot, try to exec it as admin but nothing but I can clearly see osu! running in background in the task manager.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/35759490/163638909-1d955559-45d9-433b-ac2b-b25b34ab7311.png)

### Version

latest

### Logs

[database.log](https://github.com/ppy/osu/files/8498420/database.log)
[network.log](https://github.com/ppy/osu/files/8498421/network.log)
[performance.log](https://github.com/ppy/osu/files/8498422/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8498423/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8498424/updater.log)

**Comment by MidKnightXI** [comment] 2022-04-15 22:02
PC config:
> CPU: Ryzen 7 3800x
> TridentZ 2x8GB 3200mHz
> Asus Dual GTX 1070

**Comment by peppy** [comment] 2022-04-16 01:15
Another duplicate of https://github.com/ppy/osu/issues/17654

Please check that thread and confirm whether it was medal.tv or overwolf or something else causing the issue.

**Closed by peppy** 2022-04-16 01:15 UTC

**Comment by MidKnightXI** [comment] 2022-04-16 10:05
> Another duplicate of #17654
> 
> Please check that thread and confirm whether it was medal.tv or overwolf or something else causing the issue.

My problem is that stable is opening properly and I've nothing like Overwolf etc ... on my PC

**Comment by MidKnightXI** [comment] 2022-04-16 10:12
> Another duplicate of #17654
> 
> Please check that thread and confirm whether it was medal.tv or overwolf or something else causing the issue.

My problem is that stable is opening properly and I've nothing like Overwolf etc ... on my PC.

I also tried closing Riot Vanguard and some other apps like Logitech GHub or HyperX NGENUITY but still have the same issue

**Comment by peppy** [comment] 2022-04-16 10:56
While osu! is in the stuck state, could you please create a memory dump from task manager (right click > dump) and email it to me (pe@ppy.sh)?

**Comment by MidKnightXI** [comment] 2022-04-16 12:34
done

**Comment by MidKnightXI** [comment] 2022-04-16 19:35
Okay so I don't know what I did but Lazer is now starting properly, sorry for the bother peppy.

I think that it fixed the issue when I shutdown my computer, I got the windows prompt saying that osu was still running in background and I forced shutdown my PC.

**Comment by peppy** [comment] 2022-04-18 05:31
Checking the provided memory dump, `Medal.tv`'s hook is causing this issue:

![Parallels Desktop 2022-04-18 at 05 27 52](https://user-images.githubusercontent.com/191335/163759612-2a4ef821-c658-4374-8c0f-cf38c7db28d8.png)
