### ISSUE TITLE
Resolution option can appear after searching for it when the app is not in fullscreen mode

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#14397] opened 2021-08-19 17:07 UTC
**Describe the bug:** I remember that there was already a similar issue (#11851) but for a slightly different scenario.
If you look for the resolution option while in "Windowed" or "Borderless" mode, it will appear and then remain visible until you change from "Fullscreen" to another option.
It doesn't seem to do/break anything if you change it while not in fullscreen, but this is definitely not intentional.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/130112096-d2ca077e-2c08-464f-8dc8-11ddac805424.mp4

**osu!lazer version:** `2021.815.0`

**Comment by bdach** [comment] 2021-08-21 17:39
The cause will be the same, and the fix should probably be the same as well (disable with tooltip instead of hide)?

**Comment by respektive** [comment] 2022-04-11 11:06
Just came across this issue and i feel like the resolution option should be visible for windowed at least. I would expect it to resize the window to the set resolution. That's also how stable does it.

**Comment by frenzibyte** [comment] 2022-04-11 20:55
That's out of topic from this issue about hidden controls shown during filtering. What you want is tracked in https://github.com/ppy/osu/discussions/13885.

**Comment by frenzibyte** [comment] 2022-04-28 00:47
This has been resolved to some degree in https://github.com/ppy/osu/pull/17823, but causing yet another confusion:

<img width="628" alt="CleanShot 2022-04-28 at 03 46 31@2x" src="https://user-images.githubusercontent.com/22781491/165654247-cf086bc0-1ea1-4b72-92ea-8f12337b0a4a.png">

**Comment by peppy** [comment] 2022-04-28 05:02
Closing this in favour of #18003, which is tracking this issue along with other similar (but different) cases.

**Closed by peppy** 2022-04-28 05:02 UTC
Labels: area:settings, priority:2
