### ISSUE TITLE
Make open once like profile only/music playing only/notify only

### ISSUE THREAD

**Issue by yansaan** [ppy/osu#8035] opened 2020-02-27 19:49 UTC
**Describe the bug:** 
the notify, music player, and profile opened in same time, make it onces
**Screenshots or videos showing encountered issue:** 
![osu_2020-02-28_02-43-44](https://user-images.githubusercontent.com/21020026/75480821-8b1b9180-59d4-11ea-8235-004c14426e42.jpg)

**osu!lazer version:** 
2020.221.0
**Logs:**
*please attach logs here, which are located at:*
[runtime.log](https://github.com/ppy/osu/files/4263761/runtime.log)

**Comment by bdach** [comment] 2020-02-27 19:51
I think the only part of this screenshot I have an issue with is the music controller being open at the same time as the profile dropdown. I'm pretty sure the rest being simultaneously open is intended and kind of the entire point of overlays.

**Comment by peppy** [comment] 2020-02-27 20:00
music controller is intended to be usable anywhere, like volume control.

**Comment by bdach** [comment] 2020-02-27 20:21
I'm mostly fine with that part too, it is a bit weird however that if you try to open the profile menu with the music controller open it'll pop out *behind* it. Far from having much significance or even any actual priority, but yeah.

**Comment by Joehuu** [comment] 2020-03-11 00:39
Duplicate of https://github.com/ppy/osu/issues/4726

**Closed by Joehuu** 2020-03-11 00:39 UTC
Labels: type:UX
