### ISSUE TITLE
add possibility to change score meter size and location (to bottom of screen)

### ISSUE THREAD

**Issue by Joppe27** [ppy/osu#7616] opened 2020-01-25 17:08 UTC
Please add an option to change the location of the score meter to the bottom of the screen. This is especially useful for us mania players. We can not look at the side of the screen while playing, and because there are much more notes than on regular osu, it's very hard to see how many greats/goods you get without it. Also the default size of the score meter is very small, a slider to adjust the size of the meter like there is on stable would be awesome.

**Comment by iiSaLMaN** [comment] 2020-01-25 17:08
Duplicate of https://github.com/ppy/osu/issues/4632

**Closed** 2020-01-25 17:09 UTC
