### ISSUE TITLE
Links(?) inside popup is going out of bounds

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#26193] opened 2023-12-28 18:26 UTC
### Type

Crash to desktop

### Bug description

Pretty self-explanatory

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/15729831/25a3e3fe-1584-44e7-8a1d-ac2d1cbfafb5)

### Version

v2023.1229.0

### Logs

probably not required

**Comment by bdach** [comment] 2023-12-28 18:27
Pretty much duplicate of https://github.com/ppy/osu-framework/issues/5007

**Closed by bdach** 2023-12-28 18:27 UTC
