### ISSUE TITLE
osu lazer notifications hidden

### ISSUE THREAD

**Issue by EpsyChrist** [ppy/osu#4845] opened 2019-05-22 13:10 UTC
**Describe the bug:** Notifications are invisible when clicking music icon then notifications icon

**Screenshots or videos showing encountered issue:**  https://youtu.be/UH65D6nlQbE

**osu!lazer version:** 2019.518.0

**Logs:** N/A

**Comment by smoogipoo** [comment] 2019-05-22 13:13
Duplicate of https://github.com/ppy/osu/issues/4726

**Closed by smoogipoo** 2019-05-22 13:13 UTC
