### ISSUE TITLE
High memory usage and process getting stuck on quit

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#9521] opened 2020-07-11 04:06 UTC
**Describe the bug:** 
Discovered a memory leak in the newest Lazer build.  I updated Lazer and played a Spotlights timeshift lobby for a bit then closed Lazer.  Multiple hours later I was seeing some weird lag in non-osu things and checked my task manager. Discovered a Lazer process hanging around using 600mb of RAM. (My non-osu lag did end after killing it, no way to prove it was the cause though)  I did have quite a bit of lag while playing Lazer today and I'm wondering if the memory leak is related, but I have no evidence to support that yet.

**Screenshots or videos showing encountered issue:** 
![Task Manager](http://s.owo.lt/U4HrdWtP)
![Details](http://s.owo.lt/LmgtmYfP)

**osu!lazer version:** 
2020.710.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4906249/database.log)
[network.log](https://github.com/ppy/osu/files/4906250/network.log)
[performance.log](https://github.com/ppy/osu/files/4906251/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4906252/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4906253/updater.log)

**Comment by Snowleopard-osu** [comment] 2020-07-11 04:08
Also worth noting that while I was actively playing on Lazer today it was using just shy of 5 GB of RAM.

Win 10
32GB total RAM

Can provide more specs etc if necessary

**Comment by peppy** [comment] 2020-07-11 04:12
600mb is normal for lazer. Please reproduce the 5gb case and when in this state (not before) open up ctrl-f2 view and take screenshots of the stats there (scroll down and take multiple screenshots please).

Closing this issue for the time being since there is nothing suggesting a leak here.

Post a reply if you manage to reproduce a more serious (>4gb usage) case. Note that there's a known issue with memory usage increasing while Ctrl+F2 is visible, so please do not leave that visible during the play session.

**Comment by Snowleopard-osu** [comment] 2020-07-11 04:18
This 600mb was hours after Lazer was closed.  Your saying a 600mb Lazer process running even after you have closed the game is normal?

**Comment by peppy** [comment] 2020-07-11 04:26
Oh, that's different! This isn't a memory leak, but the process just not stopping correctly. Can you reproduce this reliably?

**Comment by Snowleopard-osu** [comment] 2020-07-11 04:29
I'm working on the 5GB RAM usage right now, once I can get it or if I can't manage to I'll see if I can reproduce the process not stopping correctly.  Trying to reproduce what I did earlier today (basically just playing ctb spotlights lobby)

**Comment by peppy** [comment] 2020-07-11 04:35
If you manage to reproduce it getting stuck, please take a memory dump from task manager:

![image](https://user-images.githubusercontent.com/191335/87216508-602a4c80-c37b-11ea-97d9-3cb3130101ae.png)

And upload it somewhere private / email it to me (pe@ppy.sh). It may contain confidential information so it's best you don't share publicly.

**Comment by Snowleopard-osu** [comment] 2020-07-11 04:38
Will do, kicking myself for not doing it initially, was in the middle of a LoL game though.

**Comment by Snowleopard-osu** [comment] 2020-07-11 05:15
up to 3,680 MB and climbing so far.  Did you want me to grab those F2 logs once I cross 4GB or wait until I'm closer to 5?

**Comment by peppy** [comment] 2020-07-11 05:23
that should be high enough.

if you can, a memory dump will provide more details if you can capture before opening ctrl-f2, but the screenshots will also be helpful.

if the game doesn't close and gets stuck in task manager, pleas take a second dump at that point too

**Comment by Snowleopard-osu** [comment] 2020-07-11 05:37
Took a mem dump, then took these screenshots (the task manager screenshot was before I took the mem dump, the others were after).  Uploading the mem dump now and will email

![Task Manager](http://s.owo.lt/nE1v0D1r)
![F2 part1](http://s.owo.lt/o57MnzBZ)
![F2 part2](http://s.owo.lt/EtaTFEhZ)
![F2 part3](http://s.owo.lt/jNmeoWvZ)
![F2 part4](http://s.owo.lt/7VAjbLPJ)

**Comment by Snowleopard-osu** [comment] 2020-07-11 05:39
Reproduction steps: Open Lazer, play the catch Spotlights lobby for an hour or so.

Also currently I still have Lazer open in case you need anything else.  I can try exiting and seeing if we get the straggling process whenever (or hang out with Lazer open, either way works with me)

**Comment by peppy** [comment] 2020-07-11 05:40
Thanks.

The only remaining thing you could try is going to the main menu and hitting the "Clear all caches" button a few times, see if memory drops. But I doubt it will.

From those screenshots it's clear that there's some kind of managed memory usage that isn't being recovered, so the dump will be very helpful.

**Comment by Snowleopard-osu** [comment] 2020-07-11 05:47
Clear all caches did not effect the memory usage reported in task manger.  Also unfortunately the process appears to have closed correctly this time.  I can try playing around with it a bit to attempt reproducing that issue though.  Mem dump email coming soon, almost done uploading, it's a big'en  (5.6 GB)

**Comment by peppy** [comment] 2020-07-11 06:22
The culprit is `HitEvent`s (used for displaying the new stats at the results screen). A single run is generating about 100mb of events which are being retained by `ScoreInfo`, in turn retained by `BeatmapInfo` which is being retained by....

![image](https://user-images.githubusercontent.com/191335/87218036-39274700-c38a-11ea-9381-e66d2bb832e3.png)
![image](https://user-images.githubusercontent.com/191335/87218039-42b0af00-c38a-11ea-9902-4c38bca00aae.png)
![image](https://user-images.githubusercontent.com/191335/87218046-4e03da80-c38a-11ea-819d-579339e59249.png)

Scary stuff. Will look into a fix.

**Comment by Snowleopard-osu** [comment] 2020-07-11 06:29
Ah I see, yea definitely scary stuff.  I have noticed that stuttering and lag in the beginning is almost non-existent and then progressively gets worse over time.  It's possible this issue is related to some of the performance complaints recently made.

**Closed** 2020-07-11 16:27 UTC
Labels: type:performance

**Comment by peppy** [comment] 2020-07-12 04:32
@Snowleopard-osu please re-test on the latest release to make sure your memory usage is sane now.

**Comment by Snowleopard-osu** [comment] 2020-07-12 06:02
Seemed to be a lot better, but it did rise a bit over time, normally in 100mb jumps.  I think the issue is likely resolved but uploading another mem dump now for you to verify

**Comment by Snowleopard-osu** [comment] 2020-07-12 06:04
![F2 logs](http://s.owo.lt/xfewJser)

**Comment by peppy** [comment] 2020-07-12 06:30
Thanks for that. That new dump is looking very clean. Internally, osu! is only using 753mb (the rest is unmanaged gpu pinned memory or free memory reserved for future use).

**Comment by Snowleopard-osu** [comment] 2020-07-12 06:52
Awesome, glad I could help
