### ISSUE TITLE
Catcher in CTB will yeet Itself to the edge of playfield when spamming Left + Right and press Skip

### ISSUE THREAD

**Issue by NguyenAnhDuy1372000** [ppy/osu#25439] opened 2023-11-14 10:38 UTC
### Type

Game behaviour

### Bug description

there is a bug in CTB where when you spamming Left and Right button, and pressing the Skip button, the Catcher will yeet itself to edge of the playfield. Found this out because this is how i warmup my hand everytime i play.

### Screenshots or videos

https://github.com/ppy/osu/assets/86595121/dd1ab9c9-bb3c-4c35-89ea-6b0406e2bf22

### Version

2023.1114.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/13347658/updater.log)
[database.log](https://github.com/ppy/osu/files/13347659/database.log)
[input.log](https://github.com/ppy/osu/files/13347661/input.log)
[network.log](https://github.com/ppy/osu/files/13347663/network.log)
[performance.log](https://github.com/ppy/osu/files/13347664/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13347665/runtime.log)

**Comment by Joehuu** [comment] 2023-11-14 18:31
Duplicate of https://github.com/ppy/osu/issues/9526

**Closed by Joehuu** 2023-11-14 18:31 UTC
Labels: ruleset/osu!catch, type:input
