### ISSUE TITLE
Sort by difficulty sorts by specific map

### ISSUE THREAD

**Issue by CATboardBETA** [ppy/osu#11620] opened 2021-01-29 05:20 UTC
Whenever 'Sort by' is set to 'Difficulty', it just sorts by the specific map.

![image](https://user-images.githubusercontent.com/66703887/106234345-adaac180-61c6-11eb-8643-91bbdae1e430.png)

**Version:** 2021.129.0

**System Specifications:**
 * CPU: AMD Ryzen 5 3600XT
 * GPU: Nvidia GeForce RTX 2060 Super
 * Ram: 16 GB (8x2) Corsair Dominator
 * OS: Windows 10 Home Edition Version 20H2 (x86_64)

**Reproduction:**
1. Launch osu!lazer.
2. Click 'Play'.
3. Click 'Solo'.
4. Click 'Difficulty' in the Sort By menu at the top of the screen.

**Logs:**

*(Which logs did I need to paste)*

**Comment by bdach** [comment] 2021-01-29 05:33
Requires/duplicate of #2547

**Closed** 2021-01-29 05:33 UTC
