### ISSUE TITLE
Add warning when trying to acces multiplayer when servers are offline

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#8803] opened 2020-04-19 11:40 UTC
**Describe the new feature:** 

It should be a good idea to add a warning text box when accessing the multiplayer when servers are offiline. Because actually the room browser stay empty and we can't create a room. 

**Proposal designs of the feature:** 

Add a warning text box that return us to the main menu or makes the multiplayer button unclickable.

**Comment by peppy** [comment] 2020-04-19 20:20
Related to (and maybe duplicate of?) https://github.com/ppy/osu/issues/7417.

**Comment by MTGPROD** [comment] 2020-04-19 20:50
It is more specific to the multiplayer menu so it's more related than duplicate of 🤔

**Comment by peppy** [comment] 2020-04-19 20:51
Understand that the thing you're specifying is not handled well *anywhere*, which is why the other issue exists.

**Comment by peppy** [comment] 2021-02-18 09:18
This looks to be handled correctly these days - a loading layer is protecting the rooms list and correctly handles disconnected  states.

**Closed by peppy** 2021-02-18 09:18 UTC
Labels: area:multiplayer, type:UX
