### ISSUE TITLE
Settings navigation doesn't highlight the correct category

### ISSUE THREAD

**Issue by camellirite** [ppy/osu#10644] opened 2020-11-01 04:00 UTC
**Describe the bug:** Clicking down the list of categorys in the settings menu will always highlight the category above the one you're clicking on. Clicking up the list works the intended way

**Screenshots or videos showing encountered issue:** https://streamable.com/yu9wdl

**osu!lazer version:** 2020.1031.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5470165/database.log)
[updater.log](https://github.com/ppy/osu/files/5470166/updater.log)
[network.log](https://github.com/ppy/osu/files/5470167/network.log)
[runtime.log](https://github.com/ppy/osu/files/5470168/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5470169/performance.log)

**Comment by Joehuu** [comment] 2020-11-01 04:01
Duplicate of https://github.com/ppy/osu/issues/9196

**Closed by Joehuu** 2020-11-01 04:01 UTC
