### ISSUE TITLE
First notes hit circle rubberbands/lags

### ISSUE THREAD

**Issue by Bageha** [ppy/osu#26787] opened 2024-01-29 21:53 UTC
### Type

Performance

### Bug description

The first note in the map lags/rubber bands. It happens on random maps ranked or non ranked, some old some new. I'm not sure why this happens and I'm sorry if its already been posted (or is a good reason for it)

### Screenshots or videos

https://gyazo.com/39d57d65a682d0f0a91be868397795fd

### Version

2024.114.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14090103/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-29 22:18
duplicate of https://github.com/ppy/osu/issues/22488

**Closed by bdach** 2024-01-29 22:18 UTC
