### ISSUE TITLE
top icon things overlap when there are too many rulesets

### ISSUE THREAD

**Issue by HoosierTransfer** [ppy/osu#17811] opened 2022-04-13 22:01 UTC
### Type

Cosmetic

### Bug description

I installed a lot of rulesets and the icons started to overlap.

i think there should be a scrollbar or something like that

### Screenshots or videos

![osu_2022-04-13_17-56-56](https://user-images.githubusercontent.com/97118529/163277180-66397b1e-0ebd-433d-a714-de109185aa11.jpg)

### Version

2022.409.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8484898/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8484899/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8484904/updater.log)
[database.log](https://github.com/ppy/osu/files/8484907/database.log)
[network.log](https://github.com/ppy/osu/files/8484908/network.log)

**Comment by Joehuu** [comment] 2022-04-13 22:03
Duplicate of https://github.com/ppy/osu/issues/13339

**Closed by Joehuu** 2022-04-13 22:03 UTC
