### ISSUE TITLE
Incorrect mods status display

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#25127] opened 2023-10-15 05:24 UTC
### Type

Game behaviour

### Bug description

In the video, it is shown that transitioning from 'osu' to 'osu mania' and then 'osu editor' and exiting will cause all mods to appear as not enabled in the list.

In fact, switching to a mode other than the 'OSU' game mode and opening the 'OSU editor' and exiting will cause this issue. Exiting the Beatmap list and re-entering can temporarily solve this problem.

If the mods activation is changed in a situation where this issue has already occurred, it will cause the previously enabled mods to become disabled. If the game is played when this issue occurs, the previously enabled mods will still take effect.

### Screenshots or videos

https://github.com/ppy/osu/assets/87159802/5514edb6-e6f1-4554-a5c6-86a45b7f8cdf

### Version

2023.1008.0

### Logs

[1.log](https://github.com/ppy/osu/files/12908687/1.log)

**Comment by Joehuu** [comment] 2023-10-15 06:17
Duplicate of https://github.com/ppy/osu/issues/22816

**Closed by Joehuu** 2023-10-15 06:17 UTC
