### ISSUE TITLE
Score/Rank does not save

### ISSUE THREAD

**Issue by GiantNuker** [ppy/osu#10492] opened 2020-10-13 05:27 UTC
**Describe the bug:** 
I play a map ive gotten a B on before, get an A, and the map still shows a B.
Only happens on this map for me
**Screenshots or videos showing encountered issue:** 
[Video](https://streamable.com/dlix8p) (had to record in low quality but shouldn't matter)
[Video of it working as intended](https://streamable.com/9czcsh)
**osu!lazer version:** 
2020.1009.0
**Logs:**

[database.log](https://github.com/ppy/osu/files/5369108/database.log)
[network.log](https://github.com/ppy/osu/files/5369112/network.log)
[performance.log](https://github.com/ppy/osu/files/5369110/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5369111/runtime.log)

Edit:
Running Arch Linux with KDE Plasma 5
Playing [This Map](https://osu.ppy.sh/beatmapsets/1209029#osu/2530352)

Had a bunch of random stuff open like IDEA, discord, database editor, etc but that shouldn't make a difference

**Comment by GSculerlor** [comment] 2020-10-13 05:51
Are you sure your A rank score is higher than your B rank score?

**Comment by GiantNuker** [comment] 2020-10-13 23:24
Oh didn't know that wasn't linked - ive only been playing about a week and it looked like a bug
(I have no idea what the previous score was)

**Comment by Joehuu** [comment] 2020-10-13 23:31
Can you go back to the same map, press local on the left side and take a picture of what's there?

**Comment by GiantNuker** [comment] 2020-10-14 00:15
Ye sorry - didn't look over there before
https://cdn.nuker.dev/kg8n5ke1/2020-10-13T17:12:49.png 

Looks like score is higher, thought it was directly linked to accuracy but i guess not
Thanks

**Comment by Joehuu** [comment] 2020-10-14 00:49
The best local score's grade is shown in the carousel (i.e. right side), closing as intended.

**Closed by Joehuu** 2020-10-14 00:49 UTC
