### ISSUE TITLE
Reversed playing after a huge lag

### ISSUE THREAD

**Issue by Lucky-fish** [ppy/osu#4707] opened 2019-05-04 19:32 UTC
**Describe the bug:** 
When I'm playing my map with auto mod, osu became very laggy on my computer and it couldn't follow the music. By the time the music ends, Osu was still playing the map with huge lag and it replayed the song. Then the map was reversed, the notes appears in the bottom and they ran to the top until Osu caught up with the song.
**Screenshots or videos showing encountered issue:** 
Sorry I cannot upload any video on YouTube or any platform ;-;
Maybe I can email you the videos?
**osu!lazer version:** 
I do not have idea which version I used. I just cloned it after the commit https://github.com/ppy/osu/commit/f05471aa1899433b0e0fcd6fff731d4b34e35c28 and ran it.
**Logs:** 
https://github.com/Lucky-fish/osu-log
Sorry for providing a repository because I cannot upload the logs correctly ;-;

**Comment by peppy** [comment] 2019-05-05 06:54
Related to (or duplicate of) #4705.

**Comment by LastExceed** [comment] 2019-05-06 07:44
> the notes appears in the bottom and they ran to the top

are you referring to osu!mania ?

**Comment by Lucky-fish** [comment] 2019-05-06 13:43
Yes I am------------------ 原始邮件 ------------------
发件人: "LastExceed"<notifications@github.com>
发送时间: 2019年5月6日(星期一) 下午3:44
收件人: "ppy/osu"<osu@noreply.github.com>;
抄送: "Lucky fish"<Lucky_fishOwO@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ppy/osu] Reversed playing after a huge lag (#4707)


 
the notes appears in the bottom and they ran to the top
  
are you referring to osu!mania ?
 
&mdash;

**Comment by Joehuu** [comment] 2019-06-17 02:56
Assuming #4705 was the same issue and resolved, this can be closed?

**Comment by peppy** [comment] 2019-06-17 02:59
Should be fixed, yep.

**Closed by peppy** 2019-06-17 02:59 UTC
Labels: bug, gameplay
