### ISSUE TITLE
Deleting a replay and redownloading/reimporting the same replay causes an error

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#14574] opened 2021-08-30 02:02 UTC
**Describe the bug:** 
- After deleting a replay and attempting to redownload said replay throws an error. 
- However, not all replays give the same behavior when deleted. I have a case where I deleted an older replay but downloading/importing still worked, until I deleted that replay and the error comes back when trying to redownload. (separate logs for this case)

- Restarting the games resolves the issue.

Sorry if this is hard to understand, I'm not sure how to put this issue to words properly

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7279624/131273889-80b66938-65f8-4edc-ad89-c41b32a6a7a6.mp4

**osu!lazer version:** 2021.828.0

**Logs:** 
These are from the video example
[database.log](https://github.com/ppy/osu/files/7073616/database.log)
[network.log](https://github.com/ppy/osu/files/7073617/network.log)
[performance.log](https://github.com/ppy/osu/files/7073618/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7073619/runtime.log)

---
These are from the other case explained above
[database.log](https://github.com/ppy/osu/files/7073689/database.log)
[network.log](https://github.com/ppy/osu/files/7073690/network.log)
[performance.log](https://github.com/ppy/osu/files/7073691/performance.log)
[runtime.log](https://github.com/ppy/osu/files/7073692/runtime.log)

**Comment by peppy** [comment] 2021-08-30 04:44
I've done some initial investigation into this but there's nothing super-obivious I can find which could be the cause. The process is much the same as beatmap deletion, but the difference comes from beatmap deletions having files at one level high (the set), which could somehow be querying some sub query as tracking (rather than `NonTracking`).

I think rather than spending too much time on this I'm going to leave it as a "fixed by realm", since that is one of my current focuses.

**Comment by peppy** [comment] 2022-01-22 05:52
Should be resolved with realm.

**Closed by peppy** 2022-01-22 05:52 UTC
Labels: area:database, priority:1, fixed-by-realm
