### ISSUE TITLE
Typed Japanese texts don't show until next alphabet input on Linux

### ISSUE THREAD

**Issue by kawaemon** [ppy/osu#8439] opened 2020-03-25 17:26 UTC
**Describe the bug:** 
Typed Japanese texts doesn't show until next alphabet input.
Seems on ArchLinux with Gnome 3.36 and Mozc (a Japanese IME for Linux) 2.23.2815.102-3

**Screenshots or videos showing encountered issue:** 
Due to recording issue, there are some noises on video. Please ignore them.
https://streamable.com/n4riz
On this video, I did:
1. Turned on IME.
2. Typed "nihonngo" (this will be "にほんご") and pressed enter key. (Didn't show anything on osu)
3. Turned off IME.
4. Pressed d key (Showed "にほんごd")

**osu!lazer version:** 
1587d4b
Local Build with dotnet 3.1.102

**Logs:**
[network.log](https://github.com/ppy/osu/files/4382390/network.log)
[performance.log](https://github.com/ppy/osu/files/4382391/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4382392/runtime.log)

**Comment by bdach** [comment] 2020-03-25 19:24
Non-ASCII chars and IME don't really work well with our current window backend (osutk). We're aware of several other issues (#3230, ppy/osu-framework#2945) and so I'm going to close this as this problem is incredibly likely to also be tied to osutk.

Please try running with the experimental `--sdl` flag to use the SDL backend and report back if the problem is resolved when using it, if you can.

**Closed by bdach** 2020-03-25 19:24 UTC

**Comment by kawaemon** [comment] 2020-03-25 19:57
I tried but `--sdl` flag didn't resolved this issue...
