### ISSUE TITLE
osu!catch visual glitches

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu#2951] opened 2018-07-03 18:19 UTC
some circles aren't disapearing in right time

[database.log](https://github.com/ppy/osu/files/2160530/database.log)
[network.log](https://github.com/ppy/osu/files/2160531/network.log)
[performance.log](https://github.com/ppy/osu/files/2160532/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2160533/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2160534/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2160536/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2160537/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2160538/runtime.log)

video(wathch from 0:18):
https://drive.google.com/open?id=1B2AHpy5STUEreZmoHZ3B7EVgNJ0ow66H
i mean effect on plate

**Comment by peppy** [comment] 2020-02-17 02:36
@ticotaco72 I can't see the exact issue in the video, but a lot of improvements have been made to osu!catch since this issue was opened. Could you please check again (alternatively someone who can identify the issue in the video would be helpful).

**Comment by EVAST9919** [comment] 2020-02-17 02:45
The issue is when the circle hits the plate - there's a small flickering of some of them (visible on video with 0.25x speed). Can't reproduce for now, though.

**Comment by peppy** [comment] 2020-02-17 03:04
I fixed a lot of animation specifics on catch, so I'd doubt this still exists. Closing for now.

**Closed by peppy** 2020-02-17 03:04 UTC
Labels: area:gameplay, missing details, ruleset:osu!catch
