### ISSUE TITLE
Gameplay track sometimes does not resume after rewinding from end

### ISSUE THREAD

**Issue by MATRIX-feather** [ppy/osu#8940] opened 2020-05-04 10:55 UTC
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 
[video.zip](https://github.com/ppy/osu/files/4574141/video.zip)

**Beatmap:**
[beatmap.zip](https://github.com/ppy/osu/files/4574144/beatmap.zip)

**osu!lazer version:** 
c3ef1d3

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/4574143/logs.zip)

**Comment by bdach** [comment] 2020-05-04 17:05
Note that the actual gameplay track also seems to stop, too, which is something I've also noticed before and will probably be the root cause of the video not rewinding. It seems to be a sort of race as there is a thin window of possibility for this to happen (specific timing is needed to get the track to stop and not resume after rewind).

**Comment by InvisibleSymbol** [comment] 2020-05-04 21:30
duplicate of #7295 ?

**Comment by bdach** [comment] 2020-05-04 21:47
Ah, good catch. Closing as this bug is a corollary of that linked one.

**Closed by bdach** 2020-05-04 21:47 UTC
Labels: area:gameplay, type:audio
