### ISSUE TITLE
Android STB issues when loading beatmaps

### ISSUE THREAD

**Issue by tildearrow** [ppy/osu#8745] opened 2020-04-13 18:21 UTC
Loading any beatmap causes this notification to pop up:
> Texture could not be loaded via STB; falling back to ImageSharp.

This was reproduced under Android 8.0 on Galaxy S9 (Qualcomm). I am not sure if it will reproduce in a different device.

Version used: 2020.413.0.

**Comment by bdach** [comment] 2020-04-13 21:51
I'm betting on this being a duplicate of #7062 (old glibc); closing as such.

**Closed by bdach** 2020-04-13 21:51 UTC

**Comment by peppy** [comment] 2020-04-14 00:33
Happens on iOS too, fwiw.
