### ISSUE TITLE
add the "keys" keyword to search for maps using a certain amount a keys in osu!mania

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10524] opened 2020-10-16 06:05 UTC
i find it annoying when i type in "10k" and half of the 10k maps i have don't show up but random other mania non-10k maps with "10k" somewhere show up

the "keys" keyword aims to solve the above issue by searching for all maps using a certain amount of keys
you can use it in something like this:
"keys=x"
where x is the maps with the amount of keys you want to search for

**Comment by smoogipoo** [comment] 2020-10-16 06:12
Duplicate of https://github.com/ppy/osu/issues/6254 and https://github.com/ppy/osu/issues/5668

**Closed by smoogipoo** 2020-10-16 06:12 UTC
