### ISSUE TITLE
Tournament client seeding screen rank issues

### ISSUE THREAD

**Issue by Kasumiikun** [ppy/osu#22207] opened 2023-01-14 21:24 UTC
### Type

Other

### Bug description

Took a quick look at qualifier results to prepare for my tournament tomorrow, and saw some various "issues" with rank. 

Ruleset is set to osu!taiko within the bracket.json, but ranks show up as the players' osu!standard rank on lazer.ppy.sh for whatever reason.
![osu!_bM9mYuQKrC](https://user-images.githubusercontent.com/13593112/212497378-271ae07d-24f6-4cdb-ab04-48c5e4a0029e.png)
![osu!_umit481cbx](https://user-images.githubusercontent.com/13593112/212497392-43d3f5d3-fdb7-48f2-a874-04259edabb82.png)

All players shown are around rank 100-130 on lazer.ppy.sh in taiko, and standard is not set as their favorite mode on website (which was why it used the wrong rank prior to the website change in the past, even if you set the correct mode).

The fact this screen uses lazer rank is also quite the issue, as it is obviously not a rank used in the community much as of now, nor is it the official rank we use for players.

To show how jarring it can be, here are the ranks of every player in the team: ![firefox_NnX5FcFJ2Q](https://user-images.githubusercontent.com/13593112/212497502-3f74b28e-b58d-4010-9c91-a7008e22adda.png)

If it's absolutely required to fix, I can send the bracket.json, but I would like to avoid it for now, as players could potentially get it from here and spoil the current state of qualifier results, which are hidden on purpose to them until the stream.

### Version

2022.1228.0

### Logs

[input.log](https://github.com/ppy/osu/files/10418851/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10418852/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10418853/network.log)
[performance.log](https://github.com/ppy/osu/files/10418854/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10418855/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10418856/updater.log)
[database.log](https://github.com/ppy/osu/files/10418857/database.log)

**Comment by bdach** [comment] 2023-01-15 15:57
So a few things:

> The fact this screen uses lazer rank is also quite the issue, as it is obviously not a rank used in the community much as of now, nor is it the official rank we use for players.

This is direct fallout from https://github.com/ppy/osu/pull/21810 and the more serious problem here. @peppy not sure how long-lived `lazer.ppy.sh` is, but for now we may want to revert this locally to tournament client by overriding endpoint configuration? Or maybe we want it switchable?

> All players shown are around rank 100-130 on lazer.ppy.sh in taiko, and standard is not set as their favorite mode on website (which was why it used the wrong rank prior to the website change in the past, even if you set the correct mode).

This I cannot reproduce. There's this line in the logs:

```
2023-01-14 21:10:26 [verbose]: Inhibiting bracket save as bracket parsing failed
```

that may mean there's something wrong with the bracket itself which may be causing this.

> If it's absolutely required to fix, I can send the bracket.json, but I would like to avoid it for now, as players could potentially get it from here and spoil the current state of qualifier results, which are hidden on purpose to them until the stream.

If confidentiality is necessary, then as a special exception you could e-mail it to me via the public email on my profile for further investigation.

**Comment by Kasumiikun** [comment] 2023-01-15 16:45
Weird you can't reproduce.
Sent you the bracket.json via e-mail for now.

**Comment by bdach** [comment] 2023-01-15 17:10
@Kasumiikun Thanks, I received the bracket. I think I may know what the issue is but it requires follow-up questions.

Did you have the ladder ruleset set to osu!taiko from the very start, or did you perhaps change it midway through entering the teams? I'm asking, because as it turns out, if a user's username, country, and rank was already fetched via API and saved to the bracket, it will not be fetched again unless the user's ID is edited on the team editor screen:

https://github.com/ppy/osu/blob/7b718d75e1bca98a96b01b81829635717097c11c/osu.Game.Tournament/TournamentGameBase.cs#L188-L192

This is pretty wrong in the case that ruleset is switched _after_ some users have been entered, and it should be addressed in some way (easiest is to probably clear saved rank data from the bracket and force user to restart tournament client to repopulate after ruleset is changed), but I just want to make sure that this is the scenario we're dealing with here and I'm not missing anything else.

The error about bracket parsing was a red herring. The message about "failed parsing" can appear if the bracket just hasn't completed loading yet, which is the case here:

https://github.com/ppy/osu/blob/7b718d75e1bca98a96b01b81829635717097c11c/osu.Game.Tournament/TournamentGameBase.cs#L303-L307

**Comment by Kasumiikun** [comment] 2023-01-15 17:25
The bracket.json gets generated by our website by default, and I believe it does not set it to osu!taiko by default, so that would be the issue.

**Comment by bdach** [comment] 2023-01-15 17:29
So, to sum up here, the following issues have been identified:

- [ ] Tournament client uses `lazer.ppy.sh` and has no way to switch back which seems undesirable for most tournament organisers
- [ ] Changing ruleset for the tournament does not invalidate prefetched rank data
- [ ] Bracket save flow can incorrectly claim that parsing bracket failed even if it hasn't been fully loaded yet

Unsure if this should be split into three issues. Feels like too much red tape. I'll leave this as-is for now unless splitting is deemed preferable.

**Comment by peppy** [comment] 2023-01-17 05:19
@Kasumiikun while we'll look to fix this, I'd recommend using a previous release of lazer for the time being. I don't know how soon we'll be able to address all issue.

**Comment by Kasumiikun** [comment] 2023-01-17 05:45
@peppy for what it's worth, the issue happened in past releases as well, as it preferred using the player's preferred mode instead of taking the mode stated in the bracket.json, so waiting it out wouldn't be too much of an issue.

**Closed** 2023-01-17 17:47 UTC
Labels: priority:0, type:online, area:tournament

**Comment by bdach** [comment] 2023-01-17 19:40
@Kasumiikun If you are able to test/run latest `master`, all of the issues mentioned in this thread should now be resolved. A ruleset switch *will* require a restart of the client to repopulate ranks, though.

**Comment by Kasumiikun** [comment] 2023-01-20 14:43
I am not able to run it, so I'll wait for next release with those fixes in it.
Got it, though!

**Comment by bdach** [comment] 2023-01-20 14:45
Next release should be out sooner than later now.
