### ISSUE TITLE
osu! window keeps minimizing on workspace/virtual desktop switch

### ISSUE THREAD

**Issue by 2xer** [ppy/osu#20923] opened 2022-10-25 10:24 UTC
### Type

Other

### Bug description

**System specifications**
Linux, Debian 11 bullseye, amd64
Using Xorg, window manager is awesomewm v4.3

**Reproducing**
Run osu!lazer 2022.1022.0 AppImage from CLI, switch to a workspace/virtual desktop other than the one where osu!lazer window is currently on, switch back to the workspace with osu!lazer window, it now appears minimized.

### Screenshots or videos

https://user-images.githubusercontent.com/74143110/197748037-f6987135-b0ac-42cb-822e-3c6c442eb63a.mp4

### Version

2022.1022.0

### Logs

[database.log](https://github.com/ppy/osu/files/9859419/database.log)
[input.log](https://github.com/ppy/osu/files/9859420/input.log)
[network.log](https://github.com/ppy/osu/files/9859421/network.log)
[performance.log](https://github.com/ppy/osu/files/9859422/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9859423/runtime.log)

**Comment by bdach** [comment] 2022-10-25 16:18
Likely a duplicate of https://github.com/ppy/osu/issues/12360.

Does this happen if the game is windowed?

**Comment by 2xer** [comment] 2022-10-25 19:58
> Does this happen if the game is windowed?

Just tried it and no it doesn't, it stays the same size and doesn't get minimized.

I would prefer to keep using fullscreen mode because of the warning about input latency in non-fullscreen modes.
I checked out that issue and from what I understand it's caused by SDL library but older osu!lazer seems to work I guess. I tried out older versions, starting from the one @DavidHusicka mentioned worked for him -  `2021.331.0`. I eventually figured out it started happening on the `2021.410.0` version, `2021.407.1` is the last one that works fine.
Here's my SDL versions:
```
root@deb:~# apt list --installed | grep sdl

libsdl-image1.2/stable,now 1.2.12-12 amd64 [installed,automatic]
libsdl1.2debian/stable,now 1.2.15+dfsg2-6 amd64 [installed,automatic]
libsdl2-2.0-0/stable,now 2.0.14+dfsg2-3+deb11u1 amd64 [installed,automatic]
```

That issue also mentions #9505 @bdach you recommended confining the cursor as a workaround so I tried running borderless and setting cursor confining to "Always" but it still kept happening.

None of those issues have solutions. What advice could you give me? Is there anything I can even do to stop this from happening?

**Comment by bdach** [comment] 2022-10-25 20:08
Your system's SDL versions are irrelevant, we bundle our own in the appimage.

Unfortunately there are as many unique linux desktop configurations as there are linux users, and we don't have the bandwidth to spare to investigate every single config. It may be an issue with SDL, it may be an issue with X, or it may be an issue with awesome. I'll keep this open since this *is* an issue, but you'd have to do your own debugging to find out I'm afraid.

**Comment by bdach** [comment] 2022-10-25 20:10
Actually never mind, the versions you mention line up exactly with #12360, so it seems very likely that it's the same issue and so I'll go ahead and close as duplicate.

**Closed by bdach** 2022-10-25 20:10 UTC
Labels: framework-fix-required, platform:linux
