### ISSUE TITLE
[MacOS] Random instant failing maps at full health

### ISSUE THREAD

**Issue by jaydenamour19** [ppy/osu#27328] opened 2024-02-22 18:23 UTC
### Type

Game behaviour

### Bug description

This has only happened twice, but the behavior is consistent. I have only had this bug since the current update (2024.221.0). I will be playing through a map, full health, and then suddenly for a few frames I see a bunch of circles/sliders appear (shows a static image of 5-6 objects over 2-3 frames) and then the map will fail me instantly. I have no idea how to reproduce, it has happened on different maps.

### Version

2024.221.0

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14377970/compressed-logs.zip)

**Comment by jaydenamour19** [comment] 2024-02-22 18:24
Btw, logs are empty, i closed the game since it happened (sorry this is my first time reporting a bug on here)

**Comment by bdach** [comment] 2024-02-22 18:46
```
2024-02-22 05:28:50 [verbose]: Playback discrepancy detected (1 of allowed 5): 153,943.2 vs 165,799.7
```

Likely duplicate of https://github.com/ppy/osu/issues/26879

**Closed by bdach** 2024-02-22 18:46 UTC
