### ISSUE TITLE
Menu cursor doesn't disappear on skin change mid play

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#12557] opened 2021-04-24 08:22 UTC
Sorry if duplicate, haven't found a similar issue

[Video](https://puu.sh/HB213/e73002bfd0.mp4). Haven't been able to reproduce

Logs:
[network.log](https://github.com/ppy/osu/files/6369228/network.log)
[performance.log](https://github.com/ppy/osu/files/6369229/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6369230/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6369231/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6369232/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6369233/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6369234/updater.log)
[database.log](https://github.com/ppy/osu/files/6369235/database.log)

Version 2021.424.0

**Comment by peppy** [comment] 2021-04-24 08:29
Can you try moving the mouse back into the playfield area? It is never hidden while outside, which it looks to be in your video.

**Comment by RaiLTC** [comment] 2021-04-24 08:32
That "fixed" it. Can you hide it regardless of location? Quite distracting

**Comment by frenzibyte** [comment] 2021-04-24 08:34
Then it's a duplicate of https://github.com/ppy/osu/issues/9523

**Closed by frenzibyte** 2021-04-24 08:34 UTC
Labels: area:gameplay, priority:1
