### ISSUE TITLE
Extra finger gameplay on Android (osu!standard gameplay)

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#6418] opened 2019-10-07 15:57 UTC
**Describe the new feature:** What I'm trying to say in the title is there should be, for Android devices, a feature where people can use more than one finger to play osu!standard. So, where one finger is dragging the cursor, the player can tap the screen with other fingers off to the side to count as a click.

**Proposal designs of the feature:** What it would look like on the outside: https://www.youtube.com/watch?v=uRu5YqsEUBE

**Comment by jai-x** [comment] 2019-10-07 15:58
Duplicate of https://github.com/ppy/osu/issues/4201

Please search for existing issues before creating new ones 👍

**Closed** 2019-10-07 15:59 UTC
