### ISSUE TITLE
Catch does not let final banana shower finish playing

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3049] opened 2018-07-16 10:38 UTC
When I was playing catch in osu lazer (On mac 2018.713.1 app.zip),
the beatmap always finishes before the last banana shower finishes.

Taking https://osu.ppy.sh/beatmapsets/595580#osu/1260494 (difficulty Hard) as an example,
you see the banana shower starting, but before it reaches to a catchable height,
the beatmap stops, the results screen shows up, and you cannot do anything about the remaining notes.

This also happens when you use the Autoplay mod.

**Comment by ticotaco72** [comment] 2018-07-16 18:29
isn't it duplicate of #2956 ?

**Comment by plankp** [comment] 2018-07-16 18:38
It might be, I understood sliders as the small fruit droplets between bigger fruit instead of banana showers (which are spinners)

**Comment by ticotaco72** [comment] 2018-07-16 18:46
sorry then i has mistaken in title of #2956

**Comment by plankp** [comment] 2018-07-16 18:49
I will close this issue then?

**Closed** 2018-07-16 18:54 UTC

**Comment by ticotaco72** [comment] 2018-07-16 18:58
yeah i think it's good idea
