### ISSUE TITLE
Mouse does not response when raw input is on.

### ISSUE THREAD

**Issue by whatheword** [ppy/osu#7119] opened 2019-12-09 10:51 UTC
The cursor is stuck on the sides of the app screen, I can not click or move the cursor, so I can not turn raw input off from the app, I can only navigate using keyboard.

**Comment by mcendu** [comment] 2019-12-09 10:53
Dupe of #6290?

**Comment by peppy** [comment] 2019-12-09 10:53
Ctrl-Alt-R to reset your input settings.

**Closed** 2019-12-09 10:53 UTC

**Comment by whatheword** [comment] 2019-12-09 11:29
oh thx man
