### ISSUE TITLE
Barrel Roll mod causing the hit object out of screen

### ISSUE THREAD

**Issue by normalid-awa** [ppy/osu#29154] opened 2024-07-28 01:52 UTC
### Type

Game behaviour

### Bug description

While I was playing the daily challenge, (which the barrel roll mod was enabled by challenge), the roll caused the playfield out of the screen and almost un-hittable

game resolution: fullscreen 1920*1080

### Screenshots or videos

![image](https://github.com/user-attachments/assets/ab298890-d4de-4b9a-96a7-0f7a26f54b53)
![image](https://github.com/user-attachments/assets/4aab0eac-f809-4832-8703-08124ade12a2)
![image](https://github.com/user-attachments/assets/b2736bd5-3b74-4543-a721-04bfe0db5084)

### Version

latest release 2024.727.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401945/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-28 01:57
Duplicate of https://github.com/ppy/osu/issues/13683

**Closed by frenzibyte** 2024-07-28 01:57 UTC

**Comment by normalid-awa** [comment] 2024-07-28 02:01
> Duplicate of #13683

but its seems to appears again
