### ISSUE TITLE
Playfield is cut off depending on resolution ratio and CS

### ISSUE THREAD

**Issue by koopafou** [ppy/osu#30225] opened 2024-10-11 17:28 UTC
### Type

Game behaviour

### Bug description

Some of the playfield is cut off at the bottom at my normal screen resolution (1920x1080), noticed because the bottom corners aren't showing up completely.
Examples below in windowed mode with different resolution ratios, getting closer to something like 4:3 (second screenshot) will mitigate the issue but who plays lazer on a square CRT anyway ?
And then I realized something else, it gets worse at CS 0 (third screenshot, fullscreen, with Difficulty Adjust).

I tried modifying layout settings but it doesn't change anything. With default settings, it will look like the corners are going out of screen.

### Screenshots or videos

![20241011-170813](https://github.com/user-attachments/assets/d21ccf4b-99a1-4d21-a2e8-f77df79be98c)
![20241011-170823](https://github.com/user-attachments/assets/73fb148e-253b-48d6-9deb-c3255e9b8fea)
![20241011-172546](https://github.com/user-attachments/assets/9ef7fe62-08aa-4a89-8884-d5bf3e124df5)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17345814/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-10-11 22:39
Duplicate of https://github.com/ppy/osu/issues/28604

**Closed by Joehuu** 2024-10-11 22:39 UTC
