### ISSUE TITLE
Permanent freeze on iOS when playing a map

### ISSUE THREAD

**Issue by Royce551** [ppy/osu#6513] opened 2019-10-14 23:13 UTC
**Describe the crash:** 
osu! seems to completely freeze after a while playing a map. Haven't tested on Windows yet, but I was able to reproduce this on 2 different iOS devices - a higher end iPhone 7, which is the device the video was recorded with, and a lower end iPad Mini 2. Audio seems to work and plays until the end.
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=GgkvQvWPf30&feature=youtu.be
**osu!lazer version:** 
2019.1011.0
**Logs:** 

**Computer Specifications:**

**Comment by bdach** [comment] 2019-10-14 23:38
Closing as duplicate of #6355.

**Closed by bdach** 2019-10-14 23:38 UTC
