### ISSUE TITLE
Skin ingame bug (no marks)

### ISSUE THREAD

**Issue by Heto915** [ppy/osu#8610] opened 2020-04-04 04:18 UTC
**Describe the bug:** 
i have no more miss / 100points marks

**Screenshots or videos showing encountered issue:** 
i can show u on discord if u want: Heto#4159
![osu_2020-04-04_06-16-43-1](https://user-images.githubusercontent.com/63136904/78418392-04457e80-763c-11ea-8e1c-86c2dd046a8f.png)
![osu_2020-04-04_06-16-42-3](https://user-images.githubusercontent.com/63136904/78418395-07406f00-763c-11ea-98d8-d77f01186716.png)
![osu_2020-04-04_06-16-42-2](https://user-images.githubusercontent.com/63136904/78418396-08719c00-763c-11ea-84f2-6ec531ce4887.png)

**osu!lazer version:** 
2020.404.0 and the one before (today's updade didnt fix the problem 
**Logs:**

{
[performance.log](https://github.com/ppy/osu/files/4430734/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4430735/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4430736/updater.log)
[database.log](https://github.com/ppy/osu/files/4430737/database.log)
}

**Comment by peppy** [comment] 2020-04-04 04:19
Duplicate of https://github.com/ppy/osu/issues/8604.

**Closed by peppy** 2020-04-04 04:19 UTC
