### ISSUE TITLE
Space and scrool when selecting a beatmap causes the beatmap to start and the game to behave strangely.

### ISSUE THREAD

**Issue by maramowicz** [ppy/osu#12586] opened 2021-04-26 20:36 UTC
I played osu to myself, I lost, it's not important. What my defeat did was try to unwind in some way, I moved the mouse, pressed buttons on the keyboard... until at one point the game crashed. Instead of returning to the game I decided to look for what crashed. After a few crashes, I came to the conclusion that the crash is caused by pressing spacebar very quickly, almost simultaneously (it's important that spacebar, I tried ctrl, alt, several other buttons, but only spacebar worked) and scrolling (whether up or down it doesn't matter).
The most interesting thing to me is why it triggers beatmap at all.

Osu!Lazer 2021.424.0

Logs and video (if video is needed) are in 1 folder on my google drive:
https://drive.google.com/drive/folders/1huT-QL9Z_J6KO_TM10JFyD47DEYP8653?usp=sharing

Oh, and as if something wasn't written right I translated it through Deepl, I wouldn't have written it better anyway.

**Comment by frenzibyte** [comment] 2021-04-26 20:40
Duplicate of https://github.com/ppy/osu/issues/11511

**Closed by frenzibyte** 2021-04-26 20:40 UTC
