### ISSUE TITLE
osu!lazer freezing on macos

### ISSUE THREAD

**Issue by LumaCraftTM** [ppy/osu#12459] opened 2021-04-17 10:59 UTC
**Describe the bug: From time to time, osu!lazer on macos decides to freeze at certain moments (especially in game) the screen freezes but the sound and the game as such is still there (the inputs are well taken into account).It seems that it is at some particular time because the game refreezes exactly at the same time if you decide to replay the map or resume the game in progress.
No matter which beatmap you choose, the moment is always random at each restart of osu!lazer
It takes about 15 seconds for the game to unfreeze, which can sometimes cause the application to crash. It seems that it is at some particular time because the game refreezes exactly at the same time if you decide to replay the map or resume the game in progress.
No matter which beatmap you choose, the moment is always random at each restart of osu!lazer
It takes about 15 seconds for the game to unfreeze, which can sometimes cause the application to crash.
And it's whole screen that freezes and not the osu!lazer window because if I make certains move,like changing windows, playing music on an external source, or anything else that should not be related to the osu!client and make something appear on the screen, the action is well taken into account.
This bug happens only on osu!lazer and, having tested different screens, it is not my monitor that causes the problem.
I don't know if it happens on windows 10 or if it's only on macos
It happened on Fullscreen and borderless, I don't know for sure for the windowed mode
And I tried with 2 monitors at the same time, when the freeze happened, everything works on the non osu! screen, but on the osu! one the picture is stuck.** 

**Screenshots or videos showing encountered issue: https://user-images.githubusercontent.com/82707048/115112120-4100c100-9f84-11eb-94a9-e5f85978085f.mov** 

**osu!lazer version: Lazer 2021.416.0 (latest)** 

**Logs:
[runtime.log](https://github.com/ppy/osu/files/6329090/runtime.log)
[performance.log](https://github.com/ppy/osu/files/6329091/performance.log)
[network.log](https://github.com/ppy/osu/files/6329092/network.log)
[database.log](https://github.com/ppy/osu/files/6329093/database.log)**

**Comment by bdach** [comment] 2021-04-17 11:02
You really need to attach a video of this, preferably with the FPS counter showing. Going to be pretty much impossible to do anything useful with this report otherwise.

**Comment by LumaCraftTM** [comment] 2021-04-17 11:54
> You really need to attach a video of this, preferably with the FPS counter showing. Going to be pretty much impossible to do anything useful with this report otherwise.

I added a video

**Comment by bdach** [comment] 2021-04-17 12:37
This looks like an OS-level freeze rather than something inside the game. The FPS counter is fully frozen along with the rest of the visuals, which means that the game is either not updating at all, or nothing is being drawn to the screen. Due to that I don't believe it is likely that this is a problem with lazer itself.

Do you have any other applications open in the background that could be causing this? When the freeze happens, is any other app taking up CPU or disk resources?

**Comment by LumaCraftTM** [comment] 2021-04-17 13:24
> This looks like an OS-level freeze rather than something inside the game. The FPS counter is fully frozen along with the rest of the visuals, which means that the game is either not updating at all, or nothing is being drawn to the screen. Due to that I don't believe it is likely that this is a problem with lazer itself.
> 
> Do you have any other applications open in the background that could be causing this? When the freeze happens, is any other app taking up CPU or disk resources?

I tried removing everything that was running in the background, but this freeze still occurs...
The game is updating cause the sound and the input are still there, but it's the screen that is frozen. I tried running a gif in the background to see if it's only the osu! windows that freeze or the whole screen, and yup it's the whole screen.
Also I noticed after a freeze the fps display was a little bit glitched : https://user-images.githubusercontent.com/82707048/115114544-4106be00-9f90-11eb-9ff0-903f3ea93ba4.MOV
It only happened once so I don't know it there is a correlation

**Comment by bdach** [comment] 2021-04-17 13:30
The video doesn't seem to work. I don't see anything there.

**Comment by LumaCraftTM** [comment] 2021-04-17 13:32
![image](https://user-images.githubusercontent.com/82707048/115114916-0736b700-9f92-11eb-80e6-da4bd6069f5d.png)


> The video doesn't seem to work. I don't see anything there.

**Comment by bdach** [comment] 2021-04-17 13:33
That would suggest that this is a driver-level issue to me. I don't really know how else to explain it.

Not sure what else to request to make this issue actionable in any way. There are no obvious clues I can see right now.

**Comment by LumaCraftTM** [comment] 2021-04-17 13:38
> That would suggest that this is a driver-level issue to me. I don't really know how else to explain it.
> 
> Not sure what else to request to make this issue actionable in any way. There are no obvious clues I can see right now.

Do you think that showing my computer components could help ?

**Comment by peppy** [comment] 2021-04-17 13:39
Likely duplicate of https://github.com/ppy/osu/issues/11691.

**Comment by bdach** [comment] 2021-04-17 13:43
Yeah, seems to check out, even up to the Radeon graphics card. Closing as duplicate.

**Closed by bdach** 2021-04-17 13:43 UTC
Labels: missing details, platform:macOS

**Comment by LumaCraftTM** [comment] 2021-04-17 13:48
I have a similar configuration, but I don't have an egpu, only an Integrated gpu
MacBook Pro (16 ich, 2019)
CPU : 2,4 GHz Intel Core i9 8 cores
Memory : 64 Go 2667 MHz DDR4
GPU : **AMD Radeon Pro 5600M 8 Go**
