### ISSUE TITLE
Hidden Mod

### ISSUE THREAD

**Issue by CandyCutie** [ppy/osu#11080] opened 2020-12-03 16:34 UTC
**Describe the crash:** 
I try to play the beatmap R4V3 B0Y mapped by DeRandom Otaku with the Hidden mod on and 2 seconds after playing, the game freezes and crashes. 
**Screenshots or videos showing encountered issue:** 
https://streamable.com/0r4pyx
**osu!lazer version:** 
2020.1203.0
**Logs:**
[updater.log](https://github.com/ppy/osu/files/5637467/updater.log)
[runtime.log](https://github.com/ppy/osu/files/5637468/runtime.log)
[performance-update.log](https://github.com/ppy/osu/files/5637469/performance-update.log)
[performance-audio.log](https://github.com/ppy/osu/files/5637471/performance-audio.log)
[performance.log](https://github.com/ppy/osu/files/5637472/performance.log)
[network.log](https://github.com/ppy/osu/files/5637473/network.log)
[database.log](https://github.com/ppy/osu/files/5637475/database.log)

**Computer Specifications:** 
AMD Ryzen 5 3600X
AMD Radeon RX 5700 XT
16GB RAM

**Comment by Eeveelution** [comment] 2020-12-03 16:35
you need to post logs, otherwise we wont know what even happened

**Comment by CandyCutie** [comment] 2020-12-03 16:36
I did, guess they aren't there for some reason. Also posted a link to a video I made.

**Comment by Eeveelution** [comment] 2020-12-03 16:36
doesn't show up either, are u sure you linked them correctly and everything?

**Comment by CandyCutie** [comment] 2020-12-03 16:37
Well, never used GitHub. Dunno if I did it correctly. Just dragged the files under (put them here)

**Comment by Eeveelution** [comment] 2020-12-03 16:38
aaaaa, they may still be commented between the <--- things, can u edit your post and check for that? failing that, maybe try uploading the files elsewhere and provide links

**Comment by CandyCutie** [comment] 2020-12-03 16:38
![image](https://user-images.githubusercontent.com/75440427/101059278-516f4c80-354b-11eb-95d6-78c5cfb034d2.png)

**Comment by CandyCutie** [comment] 2020-12-03 16:38
I dunno.

**Comment by Eeveelution** [comment] 2020-12-03 16:39
yes, remove the , also dont post [](link) just post the link

**Comment by CandyCutie** [comment] 2020-12-03 16:39
I'mma check if it's a skin issue.

**Comment by CandyCutie** [comment] 2020-12-03 16:40
Nope, used the osu!lazer default skin and it still crashed.

**Comment by CandyCutie** [comment] 2020-12-03 16:40
Got it, thanks.

**Comment by bdach** [comment] 2020-12-03 16:43
Presumably duplicate of #11015

**Closed by bdach** 2020-12-03 16:43 UTC

**Comment by CandyCutie** [comment] 2020-12-03 17:00
I never paused nor was anyone spectating me, hm.

**Comment by Pennek** [comment] 2020-12-03 17:03
The issue has been closed and is being investigated. No need to continue the discussion

**Comment by bdach** [comment] 2020-12-03 17:06
i've manually confirmed that the root cause is the same despite the different circumstances.

also for future reference, the logs you uploaded are not from the same run the crash happened on. each restart is a fresh log, so you mustn't restart after a crash if you want to upload the logs with the error.
