### ISSUE TITLE
Triangles Going Out-of-boundaries in Confirmation Pop-ups

### ISSUE THREAD

**Issue by Elepover** [ppy/osu#8024] opened 2020-02-27 05:30 UTC
**Describe the bug:** 
In the open link confirmation and exit confirmation, the triangles inside the OK button will go out-of-boundaries.

It's a very **minor** bug, does not affect anything. I admit that I'm being a little picky but it'll be great to get those tiny details fixed :)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/11826985/75414663-3c361380-5964-11ea-936b-400107b29811.png)
![image](https://user-images.githubusercontent.com/11826985/75414674-47893f00-5964-11ea-8dff-11fc2f34a5a6.png)

**osu!lazer version:** 
`2020.226.0`

**Logs:**
I believe that this is a graphics thing, related logs are here:
[runtime.log](https://github.com/ppy/osu/files/4259601/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4259602/performance.log)

**Comment by GSculerlor** [comment] 2020-02-27 05:31
Duplicate of #4591

**Comment by peppy** [comment] 2020-02-27 05:32
Also related to https://github.com/ppy/osu-framework/issues/1675

**Closed** 2020-02-27 05:31 UTC
