### ISSUE TITLE
Shown beatmap lenght is 0

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#5409] opened 2019-07-19 10:17 UTC
Every beatmap in the song selection shows a lenght of 0 seconds but is actually playable, it's just a visual thing

![Screenshot_1](https://user-images.githubusercontent.com/53081750/61528435-0e2c4080-aa1f-11e9-8943-82bada534ccf.png)
![Screenshot_2](https://user-images.githubusercontent.com/53081750/61528440-11273100-aa1f-11e9-9ce8-b1f70ad74a9a.png)
![Screenshot_3](https://user-images.githubusercontent.com/53081750/61528444-13898b00-aa1f-11e9-8b7c-de803bbe8e6a.png)

Osu!Lazer version: 2019.717.1

I don't know how to get the logs

**Comment by peppy** [comment] 2019-07-19 10:18
This was an intentional regression and will be fixed when we have the ability to reprocess already imported beatmaps. If it worries you you can manually delete then reimport your beatmaps.

**Closed by peppy** 2019-07-19 10:18 UTC

**Comment by LittleEndu** [comment] 2019-09-30 17:14
What's the status of this? This prevents searching for short beatmaps to test with because ``length<35`` is always true when every beatmap has a length of 0

**Comment by smoogipoo** [comment] 2019-10-01 06:24
There has been no work on this.

**Comment by iiSaLMaN** [comment] 2019-10-01 06:27
Automatic reimporting will be a thing later (check #5376)

**Comment by smoogipoo** [comment] 2019-10-01 06:32
This is a separate issue that is not fulfilled by reimporting. The same issue can be applied to the stored star rating.
