### ISSUE TITLE
Unhandled Exception Instant Crash osu-lazer Manjaro Linux

### ISSUE THREAD

**Issue by sangoku116** [ppy/osu#5364] opened 2019-07-15 07:57 UTC
**Describe the crash:** 
When launching the game only the outline of the window appears then it crashes.

**Screenshots or videos showing encountered issue:** 
[Screenshot](https://i.gyazo.com/75155bffe942bfb926298b8cdd21446c.png)
**osu!lazer version:** 
2019.713.0-1
**Logs:** 

Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: button
   at osuTK.Input.JoystickState.SetButton(Int32 button, Boolean value)
   at osuTK.Platform.SDL2.Sdl2JoystickDriver.osuTK.Input.IJoystickDriver2.GetState(Int32 index)
   at osuTK.Platform.SDL2.Sdl2JoystickDriver.osuTK.Input.IJoystickDriver2.GetStates(List`1 result)
   at osu.Framework.Input.Handlers.Joystick.OsuTKJoystickHandler.refreshDevices()
   at osu.Framework.Threading.ScheduledDelegate.RunTask()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Platform.GameHost.<Run>b__112_1(Object <p0>, FrameEventArgs <p1>)
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /tmp/pamac-build/osu-lazer/src/osu-2019.713.0/osu.Desktop/Program.cs:line 48
/usr/bin/osu-lazer: line 3: 23048 Aborted                 (core dumped) dotnet '/usr/lib/osu-lazer/osu!.dll' "$@"

**Computer Specifications:** 
CPU: Intel I7 6800k
GPU: RTX 2070
RAM: 32GB DDR4-3200 Quad Channel
OS: Manjaro Linux XFCE Kernel 5.1.16

**Comment by iiSaLMaN** [comment] 2019-07-15 16:23
can you attach the log files here, also can you provide us a video when starting the game till it crashes

**Comment by sangoku116** [comment] 2019-07-15 20:20
Log Files
[runtime.log](https://github.com/ppy/osu/files/3393994/runtime.log)
[update_success.log](https://github.com/ppy/osu/files/3393995/update_success.log)
Video
[Video](https://youtu.be/duvj3UhFopw)

**Comment by peppy** [comment] 2019-07-16 02:06
Duplicate of https://github.com/ppy/osu-framework/issues/2272.

**Closed by peppy** 2019-07-16 02:06 UTC
