### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by emperorsolar** [ppy/osu#12341] opened 2021-04-08 11:30 UTC
**Describe the new feature:** 
On the iOS beta there is no way to stream so could u please make it so u can drag your finger to follow the stream and use 2 other fingers to spam 
**Proposal designs of the feature:**

**Comment by smoogipoo** [comment] 2021-04-08 11:31
Duplicate of https://github.com/ppy/osu/issues/4201

**Closed by smoogipoo** 2021-04-08 11:31 UTC

**Comment by emperorsolar** [comment] 2021-04-08 11:33
Oh I just noticed I was asking the same thing as that guy
