### ISSUE TITLE
Crash on switching between main menu and song selection too fast

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#2839] opened 2018-06-19 14:02 UTC
to reproduce this, go to song selection and repeatedly press esc-space-space to quickly switch between main menu and song selection until it crashes.

reproducing this seems to be alot harder in debug mode, only managed to do it once in debug, but many times in release.

**Comment by peppy** [comment] 2018-06-19 14:03
Duplicate of #2788

**Closed by peppy** 2018-06-19 14:03 UTC
