### ISSUE TITLE
Changelog Overlay doesn't dim versions if opened from settings/update notification for the first time

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#5900] opened 2019-08-30 16:15 UTC
**Describe the bug:** If you open the `Changelog` Overlay for the first time from the version at the bottom of the settings or from the update notification, it doesn't dim the list of other versions in the header.

**Screenshots or videos showing encountered issue:** 
How it's shown:
![reality](https://user-images.githubusercontent.com/43073074/64035218-8292ed00-cb50-11e9-985a-19bd502f0b25.png)
How it should be shown:
![expectation](https://user-images.githubusercontent.com/43073074/64035242-8f174580-cb50-11e9-9a1e-cf2fb361d8f4.png)

**osu!lazer version:** 2019.830.0

**Comment by bdach** [comment] 2019-08-30 21:56
Also reproduces in visual tests in `TestSceneChangelogOverlay` on the `Show with Lazer 2018.712.0` step... as long as the [first show step is temporarily removed](https://github.com/ppy/osu/blob/b8d3db4d3720fb7e6efe4c82edb322fc547cd1ac/osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs#L35), because this happens only the first time the overlay shows up. I'll try to dig and see what might be causing this.

**Comment by bdach** [comment] 2019-08-30 23:20
This is a fetch race. Since the first time the changelog is displayed there is an API hit to get a list of available streams, [this line in `ChangelogOverlay` fails to update the stream selection](https://github.com/ppy/osu/blob/126fd4d24b8553e3f64e686124f37e4994efa97e/osu.Game/Overlays/Changelog/ChangelogHeader.cs#L64), since there aren't any in the `Items` enumerable yet.

I tried to hook into one of [the `performAfterFetch` continuations to update manually](https://github.com/ppy/osu/blob/fd121a069c967f59ca83ad1ee65c76df3d9ed5b8/osu.Game/Overlays/ChangelogOverlay.cs#L156), but weirdly enough there are still no `Items` at that point, even though [the fetch task is supposed to populate them](https://github.com/ppy/osu/blob/fd121a069c967f59ca83ad1ee65c76df3d9ed5b8/osu.Game/Overlays/ChangelogOverlay.cs#L182). Feels like I'm missing something, I'll dig in a little more but I figured I'd leave at least this much info, maybe someone more experienced with this codebase can help out here.

**Comment by peppy** [comment] 2019-09-02 03:01
Nice deduction looking into this. The true issue lies in `TabControl`'s [implementation](https://github.com/ppy/osu-framework/blame/master/osu.Framework/Graphics/UserInterface/TabControl.cs#L50) of `Items`, which relies on the drawable components of the tab control to provide items back. It is done this way to ensure correctness of order, but in the case here `Items` is being retrieved immediately after being set, meaning the tab control has not yet updated itself.

**Comment by Joehuu** [comment] 2019-09-24 21:57
Can't seem to reproduce on 2019.913.0 and above.

**Comment by bdach** [comment] 2019-09-24 22:04
Actually did get better in lazer itself, weirdly enough, but the issue still persists for me in the visual tests if you do the temporary step removal [as I mentioned above](https://github.com/ppy/osu/issues/5900#issuecomment-526761996).

**Comment by bdach** [comment] 2020-01-25 23:20
This is closer to being fixed now thanks to ppy/osu-framework#2813 being fixed. It would pretty much work out-of-the-box now, *except* for the fact that the change trigger in `performAfterFetch`:

https://github.com/ppy/osu/blob/fd121a069c967f59ca83ad1ee65c76df3d9ed5b8/osu.Game/Overlays/ChangelogOverlay.cs#L156

does not get propagated to the bound copy in `ChangelogHeader`. It could obviously be force-called there too (and that resolves the issue), but I don't consider that the best fix possible, and would instead advocate for a flag that permits forced propagation to other bindables.

If anyone gets to this before I'll have a chance to, it would also be nice to get a test for the original bug - this time it'd be almost free, I'd just refactor `TestSceneChangelogOverlay` to have actual `[Test]` cases to split all of the other cases off, and re-instantiate the overlay in `[SetUp]` so that the bug is reproducible every time (because now it only manifests the first time the overlay is shown). After that all that would be left is just to stick an assertion making sure the selected release stream is highlighted and the rest dimmed.

**Closed** 2020-01-27 06:27 UTC
Labels: changelog, framework fix required, user profile
