### ISSUE TITLE
Circle gets to C but still shows D on ranking panel

### ISSUE THREAD

**Issue by Hubza** [ppy/osu#8491] opened 2020-03-29 15:48 UTC
**Describe the bug:** 
On the ranking panel, when someone achieves a D score but gets very close to a C, sometimes it just straight up brings the circle around to the C and even gets into the C zone even though its still a D.
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/33783503/77853630-e233a280-71dc-11ea-956b-36a5fd995f0d.png)
**osu!lazer version:** 
2020.327.0

**Comment by smoogipoo** [comment] 2020-03-29 15:49
Duplicate of https://github.com/ppy/osu/issues/8313

**Closed by smoogipoo** 2020-03-29 15:49 UTC
