### ISSUE TITLE
Can't load Mikuia's Profile Page

### ISSUE THREAD

**Issue by WithoutKnock** [ppy/osu#3794] opened 2018-11-30 18:37 UTC
If I try to load the profile page of Mikuia it will give me this error.
System.NullReferenceException: Object reference not set to an instance of an object.

![osu_2018-11-30_19-30-06](https://user-images.githubusercontent.com/41303944/49307948-1870ed00-f4d7-11e8-8353-558c260af652.png)

osu!lazer version: 2018.1123.1

[runtime.log](https://github.com/ppy/osu/files/2634582/runtime.log)

**Comment by morguldir** [comment] 2018-11-30 18:48
Duplicate of https://github.com/ppy/osu/issues/3701

**Closed** 2018-11-30 18:59 UTC
