### ISSUE TITLE
Scrolling down far enough in SongSelect and then trying to scroll via mouse crashes the game

### ISSUE THREAD

**Issue by FreezyLemon** [ppy/osu#1637] opened 2017-11-30 14:51 UTC
This needs a fair amount of beatmaps, probably a few hundred sets. But when you scroll down a certain amount and then try to drag with the mouse, `ScrollContainer` gives an error without actual message. Looking into it, it's usually a `Trace.Assert` [call](https://i.imgur.com/8shNfke.png) inside `OnDrag` that fails because the two values are too far apart from each other (looks like a float imprecision).

**Comment by bdach** [comment] 2019-10-28 21:35
The assert has been bumped down to debug-only, but I can't reproduce it failing after minutes of torturing my mouse even on a debug build. Possible I don't have enough beatmaps, though.

**Comment by smoogipoo** [comment] 2019-10-29 06:57
Gonna call this fixed since 1) this code has changed recently, and 2) I can't replicate either with quite a few beatmaps.

Please report back if it's still replicable.

**Comment by peppy** [comment] 2019-10-29 07:37
Reproduction:

- Switch to local framework
- Drop this code in `TestSceneBeatmapCarousel`:
```csharp
[Test]
public void TestLoadMany()
{
    List<BeatmapSetInfo> manySets = new List<BeatmapSetInfo>();

    for (int i = 1; i <= 10000; i++)
        manySets.Add(createTestBeatmapSet(i));

    loadBeatmaps(manySets);

    AddStep("scroll to last", () => carousel.SelectBeatmap(manySets.Last().Beatmaps.First()));
}
```

This probably needs a framework-side issue and fix.

**Comment by frenzibyte** [comment] 2021-04-15 21:13
Since this hasn't been mentioned here, the issue is tracked framework-side here https://github.com/ppy/osu-framework/issues/2697, I guess this would track the framework-side issue?

**Comment by bdach** [comment] 2021-04-17 09:28
No need to double-track this. Closing in favour of framework issue.

**Closed by bdach** 2021-04-17 09:28 UTC
Labels: area:song-select, framework-fix-required
