### ISSUE TITLE
You are able to gain two combo on a single object

### ISSUE THREAD

**Issue by Utiba** [ppy/osu#29831] opened 2024-09-10 04:16 UTC
### Type

Game behaviour

### Bug description

I was playing Ice Angel (map by hehe) in attempt to get the Divination Break medal. I did get the medal, but I noticed at the end of the map before the results screen I had a combo of 2610 which was very weird for what I was doing. It should of been 2609 combo since I missed the spinner at the start, but I randomly had 2610 combo.

While checking the video, I noticed the last object gave me 2 combo which shouldn't be possible. The only explanation I have for this is I did an extra input at the end of the map, so that might of caused it, but I don't know. (apologies for my reaction in advance, was grinding this for a few hours lol)

### Screenshots or videos

https://github.com/user-attachments/assets/6697cef6-f0c3-43b9-b96e-cd10ee29afd3

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16939387/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-10 04:53
The legacy combo counter is bugged, duplicate of https://github.com/ppy/osu/issues/29727.

In the results screen shown in the video, the combo is correct (2609).

**Closed by Joehuu** 2024-09-10 04:53 UTC
