### ISSUE TITLE
Crash when I press \ and Enter at the same time

### ISSUE THREAD

**Issue by coinworld** [ppy/osu#8400] opened 2020-03-22 06:46 UTC
**Describe the crash:** 
The game crashes if I press \ and Enter at the same time in song select

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
I built it myself today (Merge pull request from Fuewburvpoa/MyBranch)

**Logs:**
https://gist.github.com/coinworld/073f1b3ede8009061edb3a6edfae88d2

**Computer Specifications:** 
Ryzen 5 2600, 16GB, RX570
Linux Mint 19.3 MATE

**Comment by peppy** [comment] 2020-03-22 09:57
Please state what upstream commit you are on. I believe this may already be fixed.

**Comment by coinworld** [comment] 2020-03-22 13:02
My git log -1 says this: commit febf9adabd6d034f685223849e8cdb5c73697989 (HEAD -> master, origin/master, origin/HEAD)
Merge: 29775ae27 d6ea14b56
Author: Dean Herbert <pe@ppy.sh>
Date:   Sun Mar 22 02:21:13 2020 +0900

    Merge pull request sharp-8329 from Fuewburvpoa/MyBranch
    
    Fix beat divisor control selecting invalid divisors on drag end

I just performed clean and build and the issue is still there

**Comment by bdach** [comment] 2020-03-22 13:32
I would hazard a guess that this is a duplicate of #8168.

**Closed by bdach** 2020-03-22 13:32 UTC

**Comment by peppy** [comment] 2020-03-23 07:57
@coinworld i can guess how this may happen, but can't reproduce myself (possibly due to platform-specific implementation of keyboard input handling). i'll post a potential fix in #8168 – would be amazing if you could test it out (you will need to checkout and attach a [local framework build](https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) with the PR i made).
