### ISSUE TITLE
Mod incompatibility works only one way

### ISSUE THREAD

**Issue by Flutterish** [ppy/osu#9978] opened 2020-08-25 10:54 UTC
**Describe the bug:** Given mod A is incomptible with mod B, but mod B is not explicitly incompatible with mod A, it is possible to have both enabled. While trivial to fix, not intuitive.

**Screenshots or videos showing encountered issue:**
![obraz](https://user-images.githubusercontent.com/40297338/91165957-e43d5700-e6d1-11ea-8570-5ca133c54578.png)
![obraz](https://user-images.githubusercontent.com/40297338/91166057-07680680-e6d2-11ea-853a-9704662932da.png)

**osu!lazer version:** 2020.805.0

**Comment by smoogipoo** [comment] 2020-08-25 10:55
Duplicate of https://github.com/ppy/osu/issues/7155

**Closed by smoogipoo** 2020-08-25 10:55 UTC
