### ISSUE TITLE
laser HP  increase number

### ISSUE THREAD

**Issue by harumachi** [ppy/osu#12953] opened 2021-05-25 12:28 UTC
Hello!~ 
my suggestion is to increase not kill the current HP system and solve it in a less radical way!
what exactly am I suggesting?
create two new levels of HP and transfer those in the stable two higher: HP 6 becomes HP 8. What is this means? 
I would like the difficulty of passing the existing maps to remain the same, but it would be possible to simplify the passage in the new Laser! mapping. With the addition of two new HP Points, the value of the classic pass can be preserved while reforming the HP system for the future OSU! mapping

**Comment by jai-x** [comment] 2021-05-25 14:08
> I would like the difficulty of passing the existing maps to remain the same,

I'm judging by this line that you are finding the HP drain rate much higher in osu!lazer compared to osu!stable, in which case this may be a duplicate of https://github.com/ppy/osu/issues/7975

**Comment by Javahound** [comment] 2021-05-25 18:07
> create two new levels of HP and transfer those in the stable two higher: HP 6 becomes HP 8. What is this means?

If I'm reading that correctly, you want to Increase the HP Drain of existing maps to counter the slightly nerfed lazer HP Drain?

**Comment by harumachi** [comment] 2021-05-25 18:41
> > I would like the difficulty of passing the existing maps to remain the same,
> 
> I'm judging by this line that you are finding the HP drain rate much higher in osu!lazer compared to osu!stable, in which case this may be a duplicate of #7975 ?

Oh thank you! That sentence really reflects what I wrote! It turns out that this is really a duplicate, I am very sorry that this happened! ;-;

**Comment by harumachi** [comment] 2021-05-25 18:50
> > create two new levels of HP and transfer those in the stable two higher: HP 6 becomes HP 8. What is this means?
> 
> If I'm reading that correctly, you want to Increase the HP Drain of existing maps to counter the slightly nerfed lazer HP Drain?

Sorry, my wording can be very strange, so you understood everything too bravely, I completely accidentally duplicated the issue, referred to by the mister above...

**Comment by frenzibyte** [comment] 2021-05-25 18:51
Closing as a duplicate of the aforementioned issue, #7975.

**Closed by frenzibyte** 2021-05-25 18:51 UTC
