### ISSUE TITLE
Velopack crashes on linux

### ISSUE THREAD

**Issue by nvzeppelin** [ppy/osu#30648] opened 2024-11-15 13:28 UTC
### Type

Crash to desktop

### Bug description

Game prompted me to download an update.
After finishing, it showed a toast to restart.
When I clicked said toast, nothing happened for a while and then I got a toast saying that an unhandled exception occurred and was reported to the developers. When launching the appimage from the terminal it says:
`/tmp/.mount_osu.ApGlKsQ5/usr/bin/UpdateNix: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Unhandled exception. System.Exception: Update.exe process exited too soon (127).
   at Velopack.UpdateExe.Apply(IVelopackLocator locator, VelopackAsset toApply, Boolean silent, Boolean restart, String[] restartArgs, ILogger logger)
   at Velopack.VelopackApp.Run(ILogger logger)
   at osu.Desktop.Program.setupVelopack()
   at osu.Desktop.Program.Main(String[] args)`

### Version

2024.1115.1

### Logs

`/tmp/.mount_osu.ApGlKsQ5/usr/bin/UpdateNix: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Unhandled exception. System.Exception: Update.exe process exited too soon (127).
   at Velopack.UpdateExe.Apply(IVelopackLocator locator, VelopackAsset toApply, Boolean silent, Boolean restart, String[] restartArgs, ILogger logger)
   at Velopack.VelopackApp.Run(ILogger logger)
   at osu.Desktop.Program.setupVelopack()
   at osu.Desktop.Program.Main(String[] args)`

**Comment by nvzeppelin** [comment] 2024-11-15 13:33
No, arch. Gets created when running the appimage and is deleted right after the crash

**Comment by bdach** [comment] 2024-11-15 13:34
Are you running the appimage directly? flatpak? using some AUR package?

**Comment by nvzeppelin** [comment] 2024-11-15 13:34
i'm running the flatpack directly

**Comment by bdach** [comment] 2024-11-15 13:37
Um, can reproduce. Great...

**Comment by nvzeppelin** [comment] 2024-11-15 13:38
UpdateNix is a part of the AppImage

> What on earth is `/usr/bin/UpdateNix`?
> 
> Are you on nixos or something?

**Comment by nvzeppelin** [comment] 2024-11-15 13:44
Fixed by installing [https://aur.archlinux.org/packages/openssl-1.0](https://aur.archlinux.org/packages/openssl-1.0)
For some reason Velopack appears to need legacy openssl libs

**Comment by JDante043** [comment] 2024-11-15 14:05
Same problem after installing [openssl-1.0](https://aur.archlinux.org/packages/openssl-1.0), asks for elevated permissions, crashes anyways. No logs were generated, ran it through the terminal & got this:

```
[20:59:46] [INFO] --
[20:59:46] [INFO] Starting Velopack Updater (0.0.754-g7e9735c)
[20:59:46] [INFO]     Location: /tmp/.mount_osu.Aptj1wLG/usr/bin/UpdateNix
[20:59:46] [INFO]     CWD: /tmp/.mount_osu.Aptj1wLG/usr/bin
[20:59:46] [INFO]     Verbose: false
[20:59:46] [INFO]     Silent: false
[20:59:46] [INFO]     Log File: None
[20:59:46] [INFO] Command: Apply
[20:59:46] [INFO]     Restart: true
[20:59:46] [INFO]     Wait: WaitPid(44517)
[20:59:46] [INFO]     Package: Some("/var/tmp/velopack/osulazer/packages/osulazer-2024.1115.1-linux-x64-full.nupkg")
[20:59:46] [INFO]     Exe Args: None
[20:59:46] [INFO] Waiting 60000ms for process (44517) to exit.
[20:59:47] [INFO] Parent process exited.
[20:59:47] [INFO] Getting ready to apply package to osulazer ver 2024.1009.1: /var/tmp/velopack/osulazer/packages/osulazer-2024.1115.1-linux-x64-full.nupkg
[20:59:47] [INFO] Loading bundle from /var/tmp/velopack/osulazer/packages/osulazer-2024.1115.1-linux-x64-full.nupkg
[20:59:47] [INFO] Extracting bundle to temp file: /var/tmp/velopack/osulazer/packages/VelopackTemp/tmp_gs42FkmWZz0BYrec                                                                                           
[20:59:47] [INFO] Chmod as executable
[20:59:47] [INFO] Moving temp file to target: /tmp/.mount_osu.Aptj1wLG
[20:59:47] [ERROR] An error occurred (Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "mv: inter-device move failed: '/var/tmp/velopack/osulazer/packages/VelopackTemp/tmp_gs42FkmWZz0BYrec' to '/tmp/.mount_osu.Aptj1wLG/tmp_gs42FkmWZz0BYrec'; unable to remove target: Read-only file system\n" }), will attempt to elevate permissions and try again...
[20:59:47] [INFO] Showing user elevation prompt?
[20:59:48] [INFO] User answered yes to elevation...
[20:59:48] [INFO] Writing script for elevation: 
#!/bin/sh
mv -f '/var/tmp/velopack/osulazer/packages/VelopackTemp/tmp_gs42FkmWZz0BYrec' '/tmp/.mount_osu.Aptj1wLG'
[20:59:48] [INFO] Attempting to elevate: pkexec ["/var/tmp/velopack_update_osulazer.sh"]
[20:59:51] [ERROR] Error applying package: pkexec failed with status: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "mv: cannot stat '/tmp/.mount_osu.Aptj1wLG/tmp_gs42FkmWZz0BYrec': Permission denied\n" }
[20:59:51] [ERROR] Apply error: Failed to start_package (Permission denied (os error 13)).
Error: Apply error: Failed to start_package (Permission denied (os error 13)).

```

**Comment by bdach** [comment] 2024-11-15 14:05
From a hurried investigation: This is persistent breakage, because of files that end up in `/var/tmp/velopack`. Anyone who runs into this and doesn't get it fixed by following the above (possibly bad) advice of installing openssl 1.0 will have to remove that folder and downgrade the appimage to 1009.0.

2024.1115.1 has been temporarily pulled for linux. All linux users will see "update failed!" notifications due to this, this is "normal", and by "normal" I mean better than mass bricking.

@caesay would like to make you aware of this mode of failure as this is pretty egregious failure in being persistent through rollbacks.

**Comment by nvzeppelin** [comment] 2024-11-15 14:07
issue is with velopack:
velopack/velopack#355

**Comment by bdach** [comment] 2024-11-15 14:08
@nvzeppelin citation needed for that one? i can't see into that discord link, title of issue seems unrelated.

**Comment by nvzeppelin** [comment] 2024-11-15 14:13
> @nvzeppelin citation needed for that one? i can't see into that discord link, title of issue seems unrelated.

![Screenshot_20241115-150957.png](https://github.com/user-attachments/assets/32d7221c-c915-4da4-b5ef-e25170798bab)

![Screenshot_20241115-151106.png](https://github.com/user-attachments/assets/8da9bb47-d8c1-41e5-bcb8-5e6fd0d5d773)

![Screenshot_20241115-151113.png](https://github.com/user-attachments/assets/69230572-c2e8-4e97-8f6a-845354d9611c)

**Comment by bdach** [comment] 2024-11-15 14:14
ok you mean the *second* issue @JDante043 mentions. right.

**Comment by nvzeppelin** [comment] 2024-11-15 14:19
correct

**Comment by WalmartWhiteCat** [comment] 2024-11-15 14:25
> 2024.1115.1 has been temporarily pulled for linux. All linux users will see "update failed!" notifications due to this, this is "normal", and by "normal" I mean better than mass bricking.

> Not sure what happened here entirely. My bets are on some sort of epic dynamic linking fail due to the game being built on a github runner image that is now too old and presumes existence of libssl 1.0 which is not on modern distros anymore. The fact that I tested velopack releasing locally after the latest bump appears to support this.

Any idea when Linux will be able to play again? My install got bricked since apparently the update still went through. Was really excited to try everything out, but now I can't play at all.

**Comment by bdach** [comment] 2024-11-15 14:28
> Any idea when Linux will be able to play again?

No because I don't completely understand the problem yet.

To fix the brick, re-read https://github.com/ppy/osu/issues/30648#issuecomment-2478931793, or in quick steps:

- Remove `/var/tmp/velopack`.
- Remove the appimage.
- Redownload the appimage for 2024.1009.0 for now.

**Comment by oblivcheck** [comment] 2024-11-15 15:46
same, use --appimage-extract can run(for me)

**Comment by Bruno5430** [comment] 2024-11-15 16:02
`2024.1115.2` still crashes for me with the same libssl 1.0 error

**Comment by bdach** [comment] 2024-11-15 16:05
@Bruno5430 have you had .1 installed at all? and if yes did you wipe `/var/tmp/velopack`?

anyone else in this thread can confirm this? (AFK, can't check myself)

**Comment by Bruno5430** [comment] 2024-11-15 16:09
> @Bruno5430 have you had 1115.1 installed at all?
nope, i saw the update video on yt after 1115.1 got removed from releases

**Comment by Bruno5430** [comment] 2024-11-15 16:15
> and if yes did you wipe /var/tmp/velopack?

didn't have `1115.1` installed but i still tried it, it reverted the game back to `1009.1` and an update started downloading
game didn't restart after clicking the notification to restart the game, and an error came in the console complaining about libssl 1.0 missing (i din't install libssl 1.0 as mentioned on the issue)
> /tmp/.mount_osu.ApVEp5XU/usr/bin/UpdateNix: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

[compressed-logs.zip](https://github.com/user-attachments/files/17778150/compressed-logs.zip)

**Comment by bdach** [comment] 2024-11-15 16:15
@Bruno5430 was https://discord.com/channels/188630481301012481/1097318920991559880/1307006684912418850 you?

I've got one user here and another on discord saying it works fine, and either one or two users in both places saying it's not, so I have no idea what to think now.

**Comment by Bruno5430** [comment] 2024-11-15 16:17
> @Bruno5430 was https://discord.com/channels/188630481301012481/1097318920991559880/1307006684912418850 you?
> 
> I've got one user here and another on discord saying it works fine, and either one or two users in both places saying it's not, so I have no idea what to think now.

no, that's another person

**Comment by andro404-MC** [comment] 2024-11-15 17:13
Something to add here, latest release doesn't have an AppImage option, which means if I click download in the official site it leads to [nowhere](https://github.com/ppy/osu/releases/download/2024.1115.2/osu.AppImage)

**Comment by Bruno5430** [comment] 2024-11-15 17:16
> Something to add here, latest release doesn't have an AppImage option, which means if I click download in the official site it leads to [nowhere](https://github.com/ppy/osu/releases/download/2024.1115.2/osu.AppImage)

It was removed on purpose so people stop bricking their games until it gets fixed
https://discord.com/channels/188630481301012481/1097318920991559880/1307025818089689099

**Comment by andro404-MC** [comment] 2024-11-15 17:23
> > Something to add here, latest release doesn't have an AppImage option, which means if I click download in the official site it leads to [nowhere](https://github.com/ppy/osu/releases/download/2024.1115.2/osu.AppImage)
> 
> It was removed on purpose so people stop bricking their games until it gets fixed (hopefully) https://discord.com/channels/188630481301012481/1097318920991559880/1307031683224174694

My bad here I just read [bdach's reply](https://github.com/ppy/osu/issues/30648#issuecomment-2478931793)

**Comment by tutacat** [comment] 2024-11-15 18:26
This is just compaining, as it said in the output, that the Icon is specified wrong. The appimage references the icon name, as if it was relative, but the icon has to be copied to 'usr/share/icons/hicolor/1024x1024/osu!.png' inside the AppImage. _Removing AppImage from GitHub also breaks the Linux download link_ (since it references the `latest` tag)

**Comment by smallketchup82** [comment] 2024-11-15 18:33
As a quick update for anyone reading this thread but not looking at the osu!dev discord server, here's my explanation of the situation and I guess a quick post-mortem:

### What happened

- A `libssl` dependency was added in 1009 but causes no issues while 1009 is the latest release, since Velopack's `Update.exe` exits early after checking for an update, never calling `UpdateNix` which has the `libssl` dependency. Essentially, a ticking time bomb.
- 1115.1 is released
- Upgrading from 1009 to 1115.1 works, but trying to launch the appimage afterwords doesn't because something (either velopack or the appimage) calls `UpdateNix` which in turn requires `libssl`
- Downloading the latest appimage fresh from the Github release works fine because it's the latest release, so it wont call `UpdateNix` as long as it is the latest release
- Any release that has a dependency on `libssl` (currently 1009-1115.2) will be unable to upgrade. Both up or down.

The name `Update.exe` does NOT imply that it only works on windows. It's just the name for the general velopack updater process. Also note this is just what I've gathered from this situation and I might be wrong on some details

### What will happen
The releases 1115.1 and 1115.2 have been pulled to avoid `Update.exe` calling `UpdateNix` on existing 1009 installations. It is likely that a new release will be made without the `libssl` dependency, but making this release will brick 1009 installations. So the only solution is to manually download the appimage from the hotfix when it is released.

### Fixing a bricked client
If your game doesn't launch, and you were previously on 1009, your best bet is to manually download the 1009 appimage and stay on it until the hotfix is released. If you're on 1115.1-1115.2 and your game does launch, set `OSU_EXTERNAL_UPDATE_PROVIDER=1` until the hotfix is released. This will completely disable velopack for the time being. If you are on 1115.1-1115.2 and your game does not launch, you can try extracting the appimage and running the game manually.

Regardless, when the hotfix is out, you can manually download its appimage and go about your day. Sorry about all of this. Going forwards, I'll probably look into adding beta release support to lazer so that stuff like this can be caught early.

**Comment by AyumiToshiyuki** [comment] 2024-11-15 21:34
What do I do in the very specific case where I successfully launched 1115.2 then downgraded to 1009 and the database is now too newer to play?

**Comment by bdach** [comment] 2024-11-15 21:38
@AyumiToshiyuki either wait for the next hotfix, or i guess try switching to the flatpak maybe if you are in a hurry?

**Comment by AyumiToshiyuki** [comment] 2024-11-15 21:42
> @AyumiToshiyuki either wait for the next hotfix, or i guess try switching to the flatpak maybe if you are in a hurry?

i'll wait
i've made a backup as soon as i realized the game downgraded to 1009 and couldn't read any data anymore
will unzipping the backup and replacing the appimage once the hotfix is out keep my data or is it lost?

**Comment by TechniKris** [comment] 2024-11-16 00:19
To get this out of the way: If `OSU_EXTERNAL_UPDATE_PROVIDER=1` is set (to be specific: in my case set by the [`osu-lazer-bin`](https://aur.archlinux.org/packages/osu-lazer-bin) AUR package) and I've already successfully updated the game and its database to `2024.1115.1` or `2024.1115.2` (the "real" one), is it safe to continue using these?

**Comment by smallketchup82** [comment] 2024-11-16 02:28
@TechniKris Yes, it is safe. If you are using `osu-lazer-bin`, it would make no use of Velopack and therefore this issue does not apply to you. Just make sure that you upgrade to the hotfix release as soon as it is released and made available to you.

**Comment by peppy** [comment] 2024-11-16 02:44
Should be fixed in the next release via https://github.com/ppy/osu/pull/30659

**Closed by peppy** 2024-11-16 02:44 UTC
Labels: priority:0, platform/linux, area:installer

**Comment by smoogipoo** [comment] 2024-11-16 02:55
Note that when the next release comes out you'll need to download the AppImage manually. Existing installs on 1009 or one of the 1115 variants are permanently bricked.

For now, you can set the environment variable `OSU_EXTERNAL_UPDATE_PROVIDER=1` to run existing builds.
