### ISSUE TITLE
Regarding the issue of screen recording on Android phones and "Could not load rulesets from directory." 

### ISSUE THREAD

**Issue by CrimsonEX** [ppy/osu#14432] opened 2021-08-21 06:20 UTC
**Describe the bug:** When I entered osu!lazer on an Android phone and turned on screen recording, the sound ripped and the response slowed. I seem to be able to rule out the low specs on the phone as it works fine with other big games.
In addition, “Could not load rulesets from directory. This error has been automatically reported to the devs.” This problem always comes up every time I go into osu!lazer, and after multiple updates the problem still hasn't been resolved.

**Screenshots or videos showing encountered issue:** [tweet](https://twitter.com/fuka_zora/status/1428880445702172672?s=20)

**osu!lazer version:** 2021.820.0-lazer (Android)

**Logs:**

**Comment by frenzibyte** [comment] 2021-08-21 06:21
The portion about "could not load rulesets from directory" is a duplicate of https://github.com/ppy/osu/issues/6507.

**Closed** 2021-08-21 06:23 UTC
