### ISSUE TITLE
osu!lazer (android) daily challenge, unable to send messages in chat

### ISSUE THREAD

**Issue by whamer100** [ppy/osu#29147] opened 2024-07-27 20:21 UTC
### Type

Game behaviour

### Bug description

I tried to chat while on phone, it won't let me press enter to submit a message. I can read and type, but i can't actually send anything.

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16401402/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-07-27 20:28
Duplicate of https://github.com/ppy/osu/issues/28966

**Closed by Joehuu** 2024-07-27 20:28 UTC
