### ISSUE TITLE
Whistle hitsound still plays after trun it off while the song's playing and pausing doesn't work

### ISSUE THREAD

**Issue by ghost** [ppy/osu#30003] opened 2024-09-26 08:58 UTC
### Type

Game behaviour

### Bug description

To reproduce this bug, See in video linked below.

[【osu!】lazer编辑器内物件打击音bug，播放期间更改将无法正常停止](https://www.bilibili.com/video/BV1pBxjeGEvY)

1. draw a slider
2. select it and click "whistle" in TOGGLES column
3. play the song, and then quickly click the hitsound in the middle of the slider at the timeline
4. quickly turn off the whistle button before the slider ends.
5. do nothing else, try pausing the song before the slider ends and after.

This doesn't work for sliderhead and slidertail.

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17145503/compressed-logs.zip)

**Comment by bdach** [comment] 2024-10-28 14:42
Closing tentatively as duplicate of https://github.com/ppy/osu/issues/30365 closed by https://github.com/ppy/osu/pull/30389

**Closed by bdach** 2024-10-28 14:42 UTC
Labels: area:editor, audio
