### ISSUE TITLE
Fast return bug

### ISSUE THREAD

**Issue by Ponilek** [ppy/osu#2370] opened 2018-04-08 18:53 UTC
https://drive.google.com/open?id=17VArT2euavT4bhZnYWGgPeWkWaKA_KB6

**Comment by jai-sharma** [comment] 2018-04-08 20:03
This is a duplicate of https://github.com/ppy/osu/issues/2282.
Please search the current open issues to see if yours is listen before opening a new one.

**Closed** 2018-04-09 02:02 UTC
