### ISSUE TITLE
Osu!lazer regen problems HP 7+

### ISSUE THREAD

**Issue by kofu145** [ppy/osu#11979] opened 2021-03-07 12:12 UTC
**Describe the bug:** 
For maps on HP 7+, regen seems immensely harsh(?) You can string several amounts of 300s, and yet you won't gain back your hp, in fact here (alongside a few 100s) hp is actually lost throughout the duration until a miss is eventually made. This might be some sort of setting that I'm missing, though I just did a fresh install, this is how it is by default.
I also don't exactly know the differences between the hp drain/regen system within the two games, can someone clarify? (Did some extensive googling about this whole thing, couldn't really find anything.)
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=vFNq18fA6eU
https://www.youtube.com/watch?v=ulJQvcMpMok
**osu!lazer version:** 
2021.302.0
**Logs:**

[logs.zip](https://github.com/ppy/osu/files/6097053/logs.zip)
(I don't think these logs are really necessary, just did a fresh install and imported my stuff over from stable)

**Comment by bdach** [comment] 2021-03-07 12:14
Duplicate of #7975 / #10566

**Closed by bdach** 2021-03-07 12:14 UTC

**Comment by kofu145** [comment] 2021-03-07 12:16
Ah, seems like the keywords I used when searching for the issue were terrible. My bad!
