### ISSUE TITLE
Follow points don't always display the first time around

### ISSUE THREAD

**Issue by cyberkitsune** [ppy/osu#9912] opened 2020-08-18 23:05 UTC
**Describe the bug:** 
Sometimes, follow points won't display the first time they're meant to be shown. You can get them to appear correctly by rewinding a replay or autoplay in these cases. In normal gameplay there is no way to get them to re-appear (retrying does not work)

**Screenshots or videos showing encountered issue:** 
[Sample beatmap used](https://osu.ppy.sh/beatmapsets/191723#osu/456277)
[Video Example on Google Drive](https://drive.google.com/file/d/1jtRe_A_bCm68cu7kI1JLXDwv59TnoaJc/view?usp=sharing)
(I circle my cursor around where follow points should appear, then rewind to show they appear after rewind)

**osu!lazer version:** 
2020.814.0 and 2020.806.0 (Tested both to see if it was a recent regression)

**Logs:**
https://assets.cyberkitsune.net/share/logs.zip

**Comment by enoslayd** [comment] 2020-08-19 00:35
Pretty sure this is a duplicate of #9832 and fixed?? in framework side

**Comment by frenzibyte** [comment] 2020-08-19 01:04
Yes, should be fixed in the next release (may happen today I presume), can be closed.

**Closed** 2020-08-19 01:23 UTC
