### ISSUE TITLE
Collections' dropdown menu appears with a very small height if it has been dragged slightly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#11988] opened 2021-03-08 17:58 UTC
**Describe the bug:** There seem to be 2 problems here:
1. The context menu disappears for some reason after performing a slight drag (similar to the one shown on the video, but I'm not sure if it's intended or not)
2. Upon reopening the collection's dropdown menu, the context menu size is 99x8 pixels (I guess this is its minimum size?):
![draw visualiser](https://user-images.githubusercontent.com/43073074/110360951-aa191e80-803f-11eb-948d-3e4f42f20716.png)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/110360123-9b7e3780-803e-11eb-81d2-692b68397026.mp4

**osu!lazer version:** `2021.302.0` (latest)

**Comment by Joehuu** [comment] 2021-03-08 17:59
Duplicate of https://github.com/ppy/osu/issues/10445

**Closed by Joehuu** 2021-03-08 17:59 UTC
