### ISSUE TITLE
Can't avoid circle fading

### ISSUE THREAD

**Issue by RazjaroQ** [ppy/osu#8327] opened 2020-03-17 19:25 UTC
As the title says. Using default-x(0-9).png as circles don't remove "fading" effect.

Lazer 2020.317.0:
![Screenshot_11](https://user-images.githubusercontent.com/32415868/76893343-41202000-689d-11ea-99d2-f3448f930d39.png)

Stable:
![Screenshot_12](https://user-images.githubusercontent.com/32415868/76893393-5137ff80-689d-11ea-9e13-6ce0fc5b1d07.png)

Logs:
[database.log](https://github.com/ppy/osu/files/4345387/database.log)
[updater.log](https://github.com/ppy/osu/files/4345390/updater.log)
[runtime.log](https://github.com/ppy/osu/files/4345392/runtime.log)
[performance.log](https://github.com/ppy/osu/files/4345393/performance.log)
[network.log](https://github.com/ppy/osu/files/4345394/network.log)

**Comment by bdach** [comment] 2020-03-17 19:47
I'm like 99% sure this is a duplicate of #5537.

**Closed by bdach** 2020-03-17 19:47 UTC
