### ISSUE TITLE
Unable to connect to any internet feature of osu!lazer

### ISSUE THREAD

**Issue by YeetJesus** [ppy/osu#10747] opened 2020-11-09 12:11 UTC
A few days ago i attempted to log in to osu!lazer and it sat on attempting to connect for around 10 seconds.
lazer is also failing to connect to any other internet feature like beatmap listings.
I saw this issue closed on a two posts from 2019 but none any more recent. 
Also i can log into base osu!

![error](https://user-images.githubusercontent.com/61529476/98539387-d79cb980-2251-11eb-8b58-ccd0c5241b9c.PNG)

Version 2020.1031.0

Logs:
[performance.log](https://github.com/ppy/osu/files/5510318/performance.log)
[network.log](https://github.com/ppy/osu/files/5510319/network.log)

**Comment by bdach** [comment] 2020-11-09 12:14
Can you try opening https://osu.ppy.sh/oauth/token in your web browser? It should show a "page missing" error.

**Comment by ItIsApachee** [comment] 2020-11-09 12:15
Same issue, tried 3 last versions of osu!lazer, unable to login in my account

**Comment by YeetJesus** [comment] 2020-11-09 13:17
I have tried that it does come up with a "page missing" error

**Comment by bdach** [comment] 2020-11-09 14:04
what does `ping -n 8 -6 osu.ppy.sh` show if ran in the windows command prompt?

**Comment by ItIsApachee** [comment] 2020-11-09 15:04
> what does `ping -n 8 -6 osu.ppy.sh` show if ran in the windows command prompt?

I have the same kind of issue on arch linux, but IPv6 is disabled on my system, so naturally, it wouldn't work. I guess disabled IPv6 might be the cause of it.

**Comment by bdach** [comment] 2020-11-09 21:13
@ItIsApachee see #3507.

Going to wait until OP's response to this before I close, though.

**Comment by YeetJesus** [comment] 2020-11-09 22:39
I tried it and got a "destination host unreachable" message.
Sent 8 packets, received 0

**Comment by bdach** [comment] 2020-11-09 22:41
That sounds like a network-level problem or misconfiguration, which we can't really help you with here.

Closing as out of scope.

**Closed by bdach** 2020-11-09 22:41 UTC
Labels: type:network

**Comment by peppy** [comment] 2020-11-09 22:46
Actually I think that's what you'd see if this was #3507 (they can probably ping correctly without the `-6`)
