### ISSUE TITLE
Screenshots, taken in-game, are completely empty

### ISSUE THREAD

**Issue by distrair** [ppy/osu#22980] opened 2023-03-26 19:01 UTC
### Type

Game behaviour

### Bug description

Screenshots, took on the latest version of the game, consists of nothing

### Screenshots or videos

![image](https://user-images.githubusercontent.com/78724291/227798024-774ddc3e-87e4-4b28-9514-63892135997d.png)

### Version

2023.326.1

### Logs

[updater.log](https://github.com/ppy/osu/files/11072738/updater.log)
[runtime.log](https://github.com/ppy/osu/files/11072739/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11072740/performance.log)
[database.log](https://github.com/ppy/osu/files/11072741/database.log)
[input.log](https://github.com/ppy/osu/files/11072742/input.log)
[network.log](https://github.com/ppy/osu/files/11072746/network.log)

**Comment by Eeveelution** [comment] 2023-03-26 19:13
having the same issue on my M1 Macbook, using the Metal backend

**Comment by mouzedrift** [comment] 2023-03-26 19:16
duplicate of #22959

**Closed** 2023-03-26 19:34 UTC
