### ISSUE TITLE
Clicking on settings main panel should exit any sub panel

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8706] opened 2020-04-10 10:45 UTC
**Describe the bug:** 
After opening the ``key configuration`` sub panel in the settings, clicking on any of the main panel's sub sections won't exit the key configuration sub panel. You instead have to press <kbd>ESC</kbd> or click outside the settings overlay to close the sub panel.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/9QCMPdFd7lA

**osu!lazer version:** 
2020.408.1

**Comment by bdach** [comment] 2020-04-10 11:31
Duplicate of #6244

**Closed by bdach** 2020-04-10 11:31 UTC
