### ISSUE TITLE
 Osu!Lazer crashes while playing beatmaps on Mac

### ISSUE THREAD

**Issue by aewastaken** [ppy/osu#12118] opened 2021-03-21 02:41 UTC
**Describe the crash:** While casually playing/recording and starting a beatmap, after few seconds after starting it, Osu compleatly stops. nothing happens, instead of that i see last frame (started happening in older versions around month or 2 ago)

**Screenshots or videos showing encountered issue:** the video is to big so here is link to google photos (there is no sound) https://photos.app.goo.gl/FmbJK56SEDLdEnmj8 (quality might be not good so im sorry)

**osu!lazer version:** 2021.320.0 (mac version)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6176729/database.log)
[network.log](https://github.com/ppy/osu/files/6176730/network.log)
[performance.log](https://github.com/ppy/osu/files/6176731/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6176732/runtime.log)

**Computer Specifications:** 
MacBook Pro (16-inch, 2019)
Intel Core I7 (6 cores)
16GB 2667MHz type DDR4
AMD Radeon Pro 5300M (4GB Vram)
macOS Big Sur v. 11.1

**Comment by bdach** [comment] 2021-03-21 07:32
There is nothing relevant in the logs that would point to a conclusion. I am not a macOS user, but please see if you can find any evidence of an error somewhere in the system logs, which I'm told by google reside somewhere in the "Console" app.

Also, does this happen on a specific beatmap? If so, is it always at the same time instant, and can you link it?

**Comment by aewastaken** [comment] 2021-03-21 13:51
The logs arent saving/updating then, but i will try to play osu with system console on and see is there anything there, also it actually can happen everywhere in any beatmap. but it happens on this beatmap everytime when there is a beat drop https://osu.ppy.sh/beatmapsets/727908#osu/1571863

**Comment by aewastaken** [comment] 2021-03-21 13:59
alright so i runned it with console app and i found alot messages with error code -25294, i dont know what does that means

**Comment by bdach** [comment] 2021-03-21 14:06
That error code seems to be [related to the keychain](https://developer.apple.com/documentation/coreservices/1559994-anonymous/errkcnosuchkeychain?changes=_2_8&language=objc), so I don't think it's relevant to the game freezing...?

I've also checked the map you linked on a linux install and it completed fine, so it looks to be either OS- or hardware-specific.

**Comment by aewastaken** [comment] 2021-03-21 14:06
here i started console from starting beatmap until freeze
[Console logs.docx](https://github.com/ppy/osu/files/6177552/Console.logs.docx)

**Comment by frenzibyte** [comment] 2021-03-21 14:08
Can confirm it's not OS specific, ran the beatmap on the highlighted difficulty (`Extra`) and it has finished with no problems whatsoever.

**Comment by bdach** [comment] 2021-03-21 14:13
Upon some searching I stumbled upon this upstream issue: https://github.com/dotnet/runtime/issues/33537. Seems like nothing we can do about it, if just importing the namespace or using its functions can trip this. And [we are using the namespace](https://github.com/ppy/osu-framework/blob/a31c9ac76a882c349c53ea2c6854e94a8f7b9f5c/osu.Framework/Extensions/ExtensionMethods.cs#L11), for hashing, among others.

Then again I'm not at all sure that it's the cause of the freeze, because there are a lot more of those messages than I'd expect if it was a fatal error.

**Comment by aewastaken** [comment] 2021-03-21 14:17
i noticed when osu freezes, system freezes as well. thats intresting...

**Comment by frenzibyte** [comment] 2021-03-21 15:26
The only interesting thing I can see from the console log you attached is this:
```
wartość domyślna	15:02:46.844733+0100	runningboardd	Assertion did invalidate due to timeout: 160-97-474 (target:[app<application.sh.ppy.osu.lazer.5880770.5881941(501)>:843])
wartość domyślna	15:02:46.948194+0100	runningboardd	[app<application.sh.ppy.osu.lazer.5880770.5881941(501)>:843] Ignoring jetsam update because this process is not memory-managed
wartość domyślna	15:02:46.948185+0100	runningboardd	Calculated state for app<application.sh.ppy.osu.lazer.5880770.5881941(501)>: running-active (role: UserInteractiveFocal)
wartość domyślna	15:02:46.948225+0100	runningboardd	[app<application.sh.ppy.osu.lazer.5880770.5881941(501)>:843] Ignoring suspend because this process is not lifecycle managed
wartość domyślna	15:02:46.948266+0100	runningboardd	[app<application.sh.ppy.osu.lazer.5880770.5881941(501)>:843] Ignoring GPU update because this process is not GPU managed
wartość domyślna	15:02:46.948417+0100	runningboardd	[app<application.sh.ppy.osu.lazer.5880770.5881941(501)>:843] Skipping AppNap state - not lifecycle managed
```

Not experienced enough to tell what it's about though, or whether it's any useful (googling it tells it may be). May investigate later on if no one beats me to it.

**Comment by peppy** [comment] 2021-03-23 09:30
Nice find @bdach. Judging from the applied milestones, this looks like it will be fixed in an upcoming .NET release. Going to close this as there's nothing we can do from our end. @aewastaken if you are in a hurry to get things working, I can suggest a reinstall or a reconstruction of your keychain (make sure you know what you are doing, since you may lose some certificates or stored passwords in doing so).

**Closed by peppy** 2021-03-23 09:30 UTC
Labels: platform:macOS

**Comment by aewastaken** [comment] 2021-03-23 09:40
Thanks for suggestion, i will try to do that and see did that worked
