### ISSUE TITLE
Target will not select

### ISSUE THREAD

**Issue by zachary523** [ppy/osu#10040] opened 2020-09-02 22:33 UTC
The mod for osu!lazer Target Will not select for some reason

![image](https://user-images.githubusercontent.com/70669236/92043728-9caa7100-ed4a-11ea-99d6-b4c16b57ce2a.png)

**2020.825.0** 

There are no logs due to this being a game feature and not a crash

**Comment by frenzibyte** [comment] 2020-09-02 22:34
Duplicate of https://github.com/ppy/osu/issues/8549, please search before reporting as mentioned in [the contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

**Closed** 2020-09-02 22:35 UTC
