### ISSUE TITLE
mod selction bug

### ISSUE THREAD

**Issue by Kitichu** [ppy/osu#2083] opened 2018-02-18 08:07 UTC
after clicking the gameplay mods a couple of times it starts to bug out, causing it to select more than one mod at a time. usually when adding nightcore or sudden death. example: https://www.youtube.com/watch?v=nAl8EEYk6vk&feature=youtu.be

**Comment by peppy** [comment] 2018-02-18 08:10
I believe this is a duplicate of #2018

**Closed by peppy** 2018-02-18 08:10 UTC
