### ISSUE TITLE
There are only lines instead of text

### ISSUE THREAD

**Issue by st1lll4zy** [ppy/osu#11962] opened 2021-03-04 16:03 UTC
**Describe the bug:** 
I've installed osu!lazer - tried several versions btw - but almost all of the text is replaced by bunch of horizontal lines. Maybe font problems... 
Also I'm using hackintosh high sierra 10.13.6 if that matters

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/80056035/109991279-3ca57f00-7d1b-11eb-952e-3f50b4659cf1.png)
![image](https://user-images.githubusercontent.com/80056035/109991329-4a5b0480-7d1b-11eb-9fb2-dbf2a7d65147.png)

**osu!lazer version:** 
2021.118.1, 2021.302.0

**Comment by frenzibyte** [comment] 2021-03-04 16:12
Duplicate of https://github.com/ppy/osu/issues/9314, please search for existing issues before reporting as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue).

**Closed by frenzibyte** 2021-03-04 16:12 UTC
