### ISSUE TITLE
profile crashing osu!laser

### ISSUE THREAD

**Issue by TemTemmie** [ppy/osu#1376] opened 2017-10-14 09:28 UTC
weird bug when opening specific accounts

**Comment by ErinvanderVeen** [comment] 2017-10-14 09:31
If you report a issue like this, please provide an example account.

**Comment by EVAST9919** [comment] 2017-10-14 09:33
Before creating a new issue check already existed
https://github.com/ppy/osu/issues/1290

**Comment by peppy** [comment] 2017-10-22 02:39
Duplicate of #1290

**Closed by peppy** 2017-10-22 02:39 UTC
