### ISSUE TITLE
Missing android settings

### ISSUE THREAD

**Issue by The-D6-is-Op** [ppy/osu#28271] opened 2024-05-21 00:00 UTC
### Type

Game behaviour

### Bug description

High precision mouse/raw input is missing on android causing my drawing tablet cursor to fly offscreen or disappear 

### Version

2024.159.1

### Logs

Can't do that right now  it's the latest version though

**Comment by frenzibyte** [comment] 2024-05-21 03:07
Duplicate of #28226

**Closed by frenzibyte** 2024-05-21 03:07 UTC
