### ISSUE TITLE
Leaderboards are not available for this beatmap

### ISSUE THREAD

**Issue by dolkilu** [ppy/osu#6654] opened 2019-10-29 07:04 UTC
**Describe the bug:** 
ranked or loved map showing "Leaderboards are not available for this beatmap"
possibly an import issue, as it can be fixed by placing a new/"correct" .osz from the beatmap page without deleting the map.
An update function like the osu! client would do the job?
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/16611027/67744210-dee49100-fa5b-11e9-9f2b-ba5b15a66d7c.png)
part of the map can show the difficulty
![image](https://user-images.githubusercontent.com/16611027/67744480-91b4ef00-fa5c-11e9-9539-3f095d31c2a4.png)
![image](https://user-images.githubusercontent.com/16611027/67744495-9da0b100-fa5c-11e9-9281-6a01a008dec3.png)

**osu!lazer version:** 
2019.1021.0
**Logs:** 
not sure how to log this

**Comment by smoogipoo** [comment] 2019-10-29 07:08
Duplicate of #4823

**Closed by smoogipoo** 2019-10-29 07:08 UTC

**Comment by evgfilim1** [comment] 2022-04-12 20:22
I've just noticed that some maps are missing "ranked" or "loved" state for me after I imported beatmaps from stable a while ago (about a year or two). Using in-game downloader doesn't allow me to re-download a map because it's already in the client and in an almost valid state. How can I re-import these beatmaps without losing the scores? Will re-importing osz help me?

**Comment by bdach** [comment] 2022-04-12 20:23
you would generally use https://github.com/ppy/osu/issues/4823 when that's implemented.
