### ISSUE TITLE
UNFAIR Health bar for Osu!mania

### ISSUE THREAD

**Issue by CrazinessUwU** [ppy/osu#8074] opened 2020-03-01 14:28 UTC
This is Osu! health bar using for Osu!mania
And this type of health bar is making some level quite impossible to be beaten
![image](https://user-images.githubusercontent.com/61653670/75627571-d8317a80-5c03-11ea-97f1-899520c995b8.png)

so pls fix it plssss

**Comment by bdach** [comment] 2020-03-01 14:34
Duplicate of #7975

**Closed by bdach** 2020-03-01 14:34 UTC
