### ISSUE TITLE
Graphical Glitches on OpenGL

### ISSUE THREAD

**Issue by cheeezie** [ppy/osu#23093] opened 2023-04-02 20:11 UTC
### Type

Game behaviour

### Bug description

Some very unusual graphical glitches in the beatmaps list while on OpenGL and in game, but the issue isn't existent on Direct3D.
Some specs: Windows 11, RTX 3060 Mobile (set as default) Driver version: 531.41, Intel UHD Graphics

### Screenshots or videos

https://user-images.githubusercontent.com/102518950/229376550-1e90b0ec-9f21-41c3-a767-54a01b050e95.mp4

### Version

2023.403.0

### Logs

[database.log](https://github.com/ppy/osu/files/11133224/database.log)
[input.log](https://github.com/ppy/osu/files/11133225/input.log)
[network.log](https://github.com/ppy/osu/files/11133226/network.log)
[performance.log](https://github.com/ppy/osu/files/11133227/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11133228/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11133229/updater.log)

**Comment by mouzedrift** [comment] 2023-04-02 20:32
duplicate of #23088

**Closed** 2023-04-02 22:19 UTC
