### ISSUE TITLE
The orange cursor to resume is not showing up when using hold for menu

### ISSUE THREAD

**Issue by BlauFx** [ppy/osu#5929] opened 2019-08-31 16:13 UTC
**Describe the bug:** The orange cursor to resume is not showing up when using hold for menu

**Screenshots or videos showing encountered issue:** https://streamable.com/fp3zr

**osu!lazer version:** 2019.830.0

**Logs:**

**Comment by HoLLy-HaCKeR** [comment] 2019-08-31 16:15
Duplicate of #5915?

**Comment by phosphene47** [comment] 2019-08-31 16:17
No it's not.

**Comment by mouzedrift** [comment] 2019-08-31 16:20
i mean the cursor is orange but its just slightly orange

**Comment by ticotaco72** [comment] 2019-08-31 16:45
duplicate of  #5905

**Comment by Joehuu** [comment] 2019-08-31 17:14
Nope, it's different.

**Comment by BlauFx** [comment] 2019-08-31 17:19
> duplicate of #5905

no it's not a duplicate 

#5905 is about that the cursor is not orange.
This issue is about that if you press escape and click "on continue" the game is paused until you click on the cursor.
If you use hold for menu and click "continue" then the game is not paused the game continues immediately

**Comment by mouzedrift** [comment] 2019-08-31 17:20
the title and video might be a bit misleading i think.
so the problem here is that the orange cursor to continue doesnt show up when you pause with the "hold for menu" button in the bottom right corner

**Comment by iiSaLMaN** [comment] 2019-08-31 18:21
I think this is intended because you already moved your cursor to the "hold for menu" button, so it's pretty much unnecessary to have a resume overlay.

**Comment by peppy** [comment] 2019-09-02 01:35
This is intended.

**Closed by peppy** 2019-09-02 01:35 UTC
