### ISSUE TITLE
Slider Mid-way through disappearing in editor

### ISSUE THREAD

**Issue by MlerSu** [ppy/osu#24513] opened 2023-08-12 02:11 UTC
### Type

Game behaviour

### Bug description

From what I can tell this bug is really easy to recreate but also really easy to fix, to some extent. Only thing that I believe causes this has to do with the slider unloading at some point but that's really about it. 

It can be fixed by undoing and redoing it again, and going out and back into the map editor of the map. It's only exclusive to the editor too as when testing it's fine but doesn't fix it either.

### Screenshots or videos

https://github.com/ppy/osu/assets/111119321/dc8a3d48-3cf6-4886-9c3b-e554e3e16111

### Version

2023.811.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12326214/database.log)
[input.log](https://github.com/ppy/osu/files/12326215/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12326216/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12326217/network.log)
[performance.log](https://github.com/ppy/osu/files/12326218/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12326219/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12326220/updater.log)

**Comment by bdach** [comment] 2023-08-12 14:16
Essentially duplicate of #22698

**Closed by bdach** 2023-08-12 14:16 UTC
