### ISSUE TITLE
"Now playing" and "profile" menus stacks

### ISSUE THREAD

**Issue by Narzaru** [ppy/osu#22819] opened 2023-03-09 10:05 UTC
### Type

Crash to desktop

### Bug description

i`am not sure that's that correct or incorrect :)

1) click "Now playing"
2) click "profile"
result - menus stacks

### Screenshots or videos

![osu!_N5RS0hxLT1](https://user-images.githubusercontent.com/67306239/223987417-f80b47b5-0858-4e86-b3dd-b7a52401cc91.png)

### Version

osu! 2023.305.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10930131/database.log)
[input.log](https://github.com/ppy/osu/files/10930133/input.log)
[network.log](https://github.com/ppy/osu/files/10930134/network.log)
[performance.log](https://github.com/ppy/osu/files/10930135/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10930136/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10930138/updater.log)

**Comment by Joehuu** [comment] 2023-03-09 18:58
This also happens with notifications so marking this a duplicate of https://github.com/ppy/osu/issues/4726.

**Closed by Joehuu** 2023-03-09 18:58 UTC
Labels: type:UI, area:overlay-nowplaying
