### ISSUE TITLE
Improve in-game tablet driver

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12384] opened 2021-04-12 20:12 UTC
Suggestions for in-game tablet driver:
More precision for offset and area size(00.00mm for example, press shift to adjust these with scroll wheel):
![image](https://user-images.githubusercontent.com/64481039/114455345-f2e26b00-9bdb-11eb-8404-1e4299a3f1f7.png)
simply not enough,

Count offset from actual start of area, not from the center:
![image](https://user-images.githubusercontent.com/64481039/114455434-0b528580-9bdc-11eb-9da5-eaf4dbb8ff3f.png)
who did that?,

Show demo area correctly when rotating area:
![image](https://user-images.githubusercontent.com/64481039/114455279-d9d9ba00-9bdb-11eb-89ac-d1e5a1e10eea.png)
this driver is so broken...

**Comment by frenzibyte** [comment] 2021-04-12 22:10
The first one regarding decimal area support is a duplicate of https://github.com/ppy/osu/issues/12263.

As for the rest, please open an issue for each separately and without irrelevant notes.

**Closed by frenzibyte** 2021-04-12 22:10 UTC
