### ISSUE TITLE
OpenGL renderers have no visual output

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#23466] opened 2023-05-11 10:02 UTC
### Type

Other

### Bug description

OpenGL (Legacy) and Veldrid OpenGL show black screen on launch. The sound is still audible and I'm able to interact with the game via a keyboard and mouse, but nothing is shown on the screen
Also when the game starts it makes the entire system become unresponsive for around 10 seconds and even refreshes the desktop
Direct3D 11 works just fine, the screen is visible and there is no system freeze happening when using it

### Screenshots or videos

https://github.com/ppy/osu/assets/53346335/12636e80-9c10-401c-913d-73ba0734cbbb

### Version

2023.511.0

### Logs

[updater.log](https://github.com/ppy/osu/files/11450826/updater.log)
[network.log](https://github.com/ppy/osu/files/11450827/network.log)
[runtime.log](https://github.com/ppy/osu/files/11450828/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11450829/performance.log)

[DxDiag.txt](https://github.com/ppy/osu/files/11450841/DxDiag.txt)

**Comment by longnguyen2004** [comment] 2023-05-11 16:09
> `2023-05-11 09:53:17 [verbose]: GL Version:                 3.2.0 - Build 24.20.100.6287`

Seems like your graphics driver is outdated, try updating and see if it solves the problem
https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html
(I hope that's the right one, give me your CPU model to confirm)

**Comment by Sinamer** [comment] 2023-05-11 16:16
See my comment over at https://github.com/ppy/osu/issues/23294#issuecomment-1538378678, I am stuck with this version unfortunately

**Comment by longnguyen2004** [comment] 2023-05-11 16:18
Use DDU to fully remove the manufacturer driver, then install the generic driver. There are plenty guides on Google for this.

**Comment by Sinamer** [comment] 2023-05-11 16:31
I'd rather not. This laptop firmware is a special case and last time I tried installing non-manufacturer drivers my system would experience BSoD-s constantly. It is stable in its current form. This doesn't explain how the game has been working fine until renderer changes either

**Comment by bdach** [comment] 2023-05-11 18:24
Does not reproduce on my box, unfortunately :(

@Sinamer are you able to do some testing on your side to see what might have broken this? It's probably one of the framework changes since last release, but I really am failing to understand which one it might have been and why. The most suspect one is probably https://github.com/ppy/osu-framework/pull/5765, but that was supposed to be a revert to a previously-known-working state...

**Comment by Sinamer** [comment] 2023-05-12 03:02
Sorry for the long response time. I ran git bisect on a local framework and here is the result:
```powershell
b972ed213ee3742fa65419c3661bca4b1271f6a7 is the first bad commit
commit b972ed213ee3742fa65419c3661bca4b1271f6a7
Author: Bartłomiej Dach <dach.bartlomiej@gmail.com>
Date:   Sat Apr 29 15:37:36 2023 +0200

    Disable custom mipmap generation

 .../Graphics/OpenGL/Textures/GLTexture.cs          | 247 +++++++++---------
 .../Graphics/Veldrid/Textures/VeldridTexture.cs    | 276 +++++++++++----------
 2 files changed, 271 insertions(+), 252 deletions(-)
```

**Comment by bdach** [comment] 2023-05-12 04:06
Figures. I'll have another look at that change and try to guess how I might have reverted wrong somehow...

**Comment by peppy** [comment] 2023-05-12 06:03
@Sinamer Thanks for the bisect. before i got any further though, can you 101% confirm that legacy GL is also broken, not just veldrid GL? You can confirm you're running legacy GL via `runtime.log`

**Comment by Sinamer** [comment] 2023-05-12 06:15
Yes, I can confirm OpenGL (Legacy) is experiencing this issue. I made sure to check on that exact commit and to look at runtime.log in osu-development folder in AppData/Roaming

**Comment by Sinamer** [comment] 2023-05-12 08:41
Here are RenderDoc captures using osu.Framework.Tests on 2023.403.0, 2023.417.0 (both working) tags and master (no visuals):
[Captures.zip](https://github.com/ppy/osu/files/11461144/Captures.zip)

**Comment by bdach** [comment] 2023-05-12 19:03
Captures attached show that textures on `master` are completely not there, as in not uploaded. Both white pixel and the font atlas are completely transparent-black.

@Sinamer could you give https://github.com/ppy/osu-framework/compare/master...bdach:osu-framework:crapshoot?expand=1 a go? I've identified one issue on my machine that this branch seems to fix, but apparently [you've tested that before and it didn't do anything](https://discord.com/channels/188630481301012481/589331078574112768/1106641373203025921), so my hopes are low. But I'm hoping maybe it didn't build properly or something. Both legacy GL and veldrid GL, please.

**Comment by Sinamer** [comment] 2023-05-13 02:24
The branch fixes the issue for both Legacy and Veldrid GL. I checked the file that "ruled out" the InitialiseLevel changes again and the git diff looks different from your branch, so that explains it not working for me.

**Comment by Sinamer** [comment] 2023-05-13 03:50
Tested osu! with this branch as well. LegacyGL works, VeldridGL crashes shortly after launch (before the intro animation manages to show), here's the runtime log of that:
[runtime.log](https://github.com/ppy/osu/files/11468804/runtime.log)

**Comment by bdach** [comment] 2023-05-13 04:43
Thanks for the testing. I'll go look at what's crashing now...

**Comment by bdach** [comment] 2023-05-13 05:42
@Sinamer can you pull the branch I linked above again and re-test? By all means the issue should be fixed, since I pretty much went the nuclear route and reverted everything that could matter, but I would like a confirmation of that if possible.

**Comment by Sinamer** [comment] 2023-05-13 05:53
Can confirm that all three renderers (LegacyGL, VeldridGL, VeldridD3D 11) are launching and working properly on osu.Framework.Tests and osu! with the latest changes on that branch, and that the issue is resolved

**Closed** 2023-05-13 11:06 UTC
Labels: priority:0, renderer:legacy-gl, renderer:veldrid-gl
