### ISSUE TITLE
Difficulty adjust replays not working properly

### ISSUE THREAD

**Issue by RadekMojzis** [ppy/osu#11505] opened 2021-01-15 21:31 UTC
**Describe the bug:** 
when you try to watch a replay with the mod "difficulty adjust" on, the adjustments in difficulty are not set.
The screenshot below is supposed to have CS0, and hp drain 0, so according to the replay this is a fail...

**Screenshots or videos showing encountered issue:** 
![osu_2021-01-15_22-24-47](https://user-images.githubusercontent.com/22374865/104780386-028b1880-5781-11eb-8095-690fc790d1f6.jpg)
![osu_2021-01-15_22-25-19](https://user-images.githubusercontent.com/22374865/104780323-e12a2c80-5780-11eb-8470-80059d10e02f.jpg)

**osu!lazer version:** 
2021.109.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/5822990/logs.zip)

**Comment by bdach** [comment] 2021-01-15 21:33
Duplicate of #8569

**Closed by bdach** 2021-01-15 21:33 UTC
