### ISSUE TITLE
Allow all modes to be played by touch controls.

### ISSUE THREAD

**Issue by Yilliee** [ppy/osu#11805] opened 2021-02-17 10:58 UTC
All modes like Osu!Catch, osu!mania will have on screen touch buttons.

For Osu!Catch there should by at least the two left and right keys showing on display to move the character or a joystick etc.
And for Osu!Mania the tiles at the bottom should support touch like playing a piano.

**Comment by smoogipoo** [comment] 2021-02-17 10:59
Duplicate of https://github.com/ppy/osu/issues/4201. Please search.

**Closed by smoogipoo** 2021-02-17 10:59 UTC
