### ISSUE TITLE
Duplicate player avatar in the multiplayer lobby header

### ISSUE THREAD

**Issue by 424ever** [ppy/osu#29923] opened 2024-09-18 18:23 UTC
### Type

Game behaviour

### Bug description

In the multiplayer lobby header the number of players was displayed as 3, even though only 2 players were in the lobby. Additionally, there were 2 instances of my own avatar in the list. I first noticed this after after the third player in the lobby left.
multiplayer link: https://osu.ppy.sh/multiplayer/rooms/889326

### Screenshots or videos

![image](https://github.com/user-attachments/assets/3b0015cf-a8f7-4fe6-b313-05ddbd2181ed)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17048532/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-18 18:25
Duplicate of https://github.com/ppy/osu/issues/19691

**Closed by Joehuu** 2024-09-18 18:25 UTC
