### ISSUE TITLE
Edited beatmaps still submit as normal when not supposed to

### ISSUE THREAD

**Issue by Idealosu** [ppy/osu#18025] opened 2022-04-29 23:26 UTC
### Type

Game behaviour

### Bug description

Edited beatmaps are supposed to have the Unsubmitted status. However, it seems that lazer doesn’t account for that and still submits regardless - allowing users to farm playcount with the press of a single button, or to edit the max combo of a map to absurd values and still have it submit as normal.

### Screenshots or videos

I’ll just link the tweet that was made after a player was restricted for doing this, in which a video was included, as I have no access to a computer at the moment:
https://twitter.com/mkachovski/status/1520173769767145472?s=21

### Version

2022.424.1

### Logs

N/A

**Comment by Theighlin** [comment] 2022-04-30 06:03
Duplicate of #11922

**Closed** 2022-04-30 06:05 UTC
