### ISSUE TITLE
Playing beatmap in daily challenge doesn't update beatmap position in song select when sorting by "Last Played"

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#29195] opened 2024-07-30 02:32 UTC
### Type

Other

### Bug description

Playing the current beatmap in the daily challenge doesn't update the beatmaps last played position.

### Version

2024.727.0

### Logs

.

**Comment by frenzibyte** [comment] 2024-07-30 03:26
Duplicate of https://github.com/ppy/osu/issues/28013

**Closed by frenzibyte** 2024-07-30 03:26 UTC
