### ISSUE TITLE
Opening the "now playing" tab makes the game lag like crazy with a lot of songs

### ISSUE THREAD

**Issue by inzork** [ppy/osu#26270] opened 2023-12-30 19:19 UTC
### Type

Performance

### Bug description

My songs folder is 180gb and when I open the now playing tab with "All beatmaps" the game just dies for like a minute. After loading the list the framerate is horibble.

Can't upload the video here because of the file size, so [here's a link](https://streamable.com/ygiegn)

### Version

Lazer 2023.1229.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13799007/compressed-logs.zip)

**Comment by Joehuu** [comment] 2023-12-30 19:49
Duplicate of https://github.com/ppy/osu/issues/7767

**Closed by Joehuu** 2023-12-30 19:49 UTC
