### ISSUE TITLE
Game fully softlocked

### ISSUE THREAD

**Issue by ackhack** [ppy/osu#5872] opened 2019-08-28 17:31 UTC
![bug](https://user-images.githubusercontent.com/43985368/63878479-feaef880-c9c9-11e9-8a64-f86835f4c4f6.PNG)

was playing the osu tutorial v2 by The_CJ (https://osu.ppy.sh/beatmapsets/530360#osu/1124313), while at the Start of Tengaku, the Sliders bugged out and the Game softlocked, showing the Error Message.

**Comment by ackhack** [comment] 2019-08-28 17:32
trying to press continue froze the game.

**Comment by iiSaLMaN** [comment] 2019-08-28 17:32
Can you attach the logs of the game (hopefully you didn't start another instance)

**Comment by ackhack** [comment] 2019-08-28 17:42
[network.log](https://github.com/ppy/osu/files/3552180/network.log)
[performance.log](https://github.com/ppy/osu/files/3552181/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3552182/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3552183/updater.log)
[database.log](https://github.com/ppy/osu/files/3552184/database.log)
I started normal osu! in the meantime, but the logfiles (database/runtime atleast) are still the stuff i did in lazer

**Comment by iiSaLMaN** [comment] 2019-08-28 17:58
Did you switch audio devices before the softlock?

**Comment by ackhack** [comment] 2019-08-28 18:12
maybe headset disconnected for a split second (wireless), but i didnt hear the disconnet sound, but not intentionally.

**Comment by ackhack** [comment] 2019-08-28 18:17
the error in runtime is 4/5 seconds before it crashed.

**Comment by peppy** [comment] 2019-08-29 04:46
Probably duplicate of https://github.com/ppy/osu/issues/1302

**Comment by iiSaLMaN** [comment] 2019-08-29 11:37
Can be closed then?

**Closed** 2019-08-29 11:40 UTC
Labels: audio, framework fix required
