### ISSUE TITLE
Full results table not visible

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu#7163] opened 2019-12-11 22:04 UTC
**Describe the bug:** 
The results screen covers up things such as an overview of number of notes hit at certain timings.

**Screenshots or videos showing encountered issue:** 
![osu_2019-12-11_15-17-41](https://user-images.githubusercontent.com/55364481/70664319-2f910180-1c38-11ea-9e13-4246d2e2c93d.png)

**osu!lazer version:** 
2019.1205.0 on Windows 10 (Screen Resolution 1600 X 900)

**Logs:** 
No logs found.

**Comment by iiSaLMaN** [comment] 2019-12-11 22:11
Duplicate of #4791

**Closed** 2019-12-11 22:18 UTC
