### ISSUE TITLE
osu!lazer does not show user profile for other mode

### ISSUE THREAD

**Issue by Asiimoviet** [ppy/osu#21903] opened 2022-12-28 19:34 UTC
### Type

Game behaviour

### Bug description

The website can show different profile for different modes. However I can only check my osu!std rank in the client profile page.

### Screenshots or videos

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66727875/209863197-74d732a3-7520-473c-b28e-ad51e3464a52.png">
The website can change between 4 modes while the client only show osu!std

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66727875/209863274-7b77baf9-07df-4de4-89b4-f110230b02a4.png">

### Version

2022.1228.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10316079/database.log)
[input.log](https://github.com/ppy/osu/files/10316080/input.log)
[network.log](https://github.com/ppy/osu/files/10316081/network.log)
[performance.log](https://github.com/ppy/osu/files/10316082/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10316083/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10316084/updater.log)

**Comment by LittleEndu** [comment] 2022-12-28 19:37
Duplicate of https://github.com/ppy/osu/issues/3606

**Closed** 2022-12-28 19:38 UTC
