### ISSUE TITLE
Auto misses on taiko maps that have been converted from standard

### ISSUE THREAD

**Issue by yeSpud** [ppy/osu#7397] opened 2019-12-30 06:14 UTC
**Describe the bug:** 
Auto will miss on beatmaps that have been converted from standard to taiko.

(map used to test was [Celestial Horizon - Extra](https://osu.ppy.sh/beatmapsets/751846#osu/1582771))

**Screenshots or videos showing encountered issue:** 
Video had to be stored in a zip due to size
[taiko.mp4.zip](https://github.com/ppy/osu/files/4009076/taiko.mp4.zip)

**osu!lazer version:** 
2019.1227.0

**Comment by mouzedrift** [comment] 2019-12-30 06:38
probably a duplicate of #5677

**Comment by yeSpud** [comment] 2019-12-30 06:48
I did see that issue, but from what I could tell that issue corresponds to taiko beat maps, whereas this is converted beat maps. 


Not to mention I don't think it has to do with the 1/8 speed limit :p

**Comment by smoogipoo** [comment] 2020-01-03 07:16
Same as the mentioned issue.

**Closed by smoogipoo** 2020-01-03 07:16 UTC
Labels: beatmap conversion, osu!taiko, replay
