### ISSUE TITLE
Ranking is covered by graph

### ISSUE THREAD

**Issue by plankp** [ppy/osu#3605] opened 2018-10-17 23:48 UTC
See the screenshot: Canada 404 is behind the graph. This does not happen on the osu webpage.

![image](https://user-images.githubusercontent.com/7527421/47122553-3f37d480-d245-11e8-90b5-f3952fdc1f2d.png)

**Comment by Joehuu** [comment] 2018-10-17 23:49
Duplicate of #3421.

**Closed** 2018-10-17 23:50 UTC
