### ISSUE TITLE
Lazer dates all scores on profiles to January 1. 0001, 00:54:00

### ISSUE THREAD

**Issue by Kfftfuftur** [ppy/osu#19214] opened 2022-07-18 09:39 UTC
### Type

Cosmetic

### Bug description

Running on Linux with some custom rulesets installed. 

No special steps needed to reproduce this. Just open the profile within the game and check the dates of the scores.

### Screenshots or videos

![Screenshot from 2022-07-18 11-25-56](https://user-images.githubusercontent.com/21262777/179484152-004f6596-568d-45a0-9173-b07427f741ca.png)

### Version

2022.716.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9130890/database.log)
[network.log](https://github.com/ppy/osu/files/9130891/network.log)
[performance.log](https://github.com/ppy/osu/files/9130892/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9130893/runtime.log)

**Comment by frenzibyte** [comment] 2022-07-18 09:40
Duplicate of https://github.com/ppy/osu/issues/19146

**Closed by frenzibyte** 2022-07-18 09:40 UTC
