### ISSUE TITLE
Exit button for mobile

### ISSUE THREAD

**Issue by GamerProYT54** [ppy/osu#10569] opened 2020-10-20 22:23 UTC
**Describe the new feature:** 
Exit button for Android (and possibly iOS?)
**Proposal designs of the feature:** 
Add an exit button for the lazer home page, and after the "See ya next time," force quit the app

**Comment by swoolcock** [comment] 2020-10-20 22:57
Duplicate of #5616 and #6072.

Mobile apps do not have an exit button.

**Closed by swoolcock** 2020-10-20 22:57 UTC
