### ISSUE TITLE
Spinner meter does not disappear after going backwards in editor

### ISSUE THREAD

**Issue by Defendium** [ppy/osu#26901] opened 2024-01-31 19:24 UTC
### Type

Cosmetic

### Bug description

When you go to the editor and normally go through a spinner and then go backwards, the spinner meter does not disappear, but is still fully present. Exiting and opening the map in the editor again fixes this.

### Screenshots or videos

https://github.com/ppy/osu/assets/67268017/67cad354-19eb-4fa9-950b-0f8b4cbdf3eb

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14116185/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-31 19:28
Duplicate of https://github.com/ppy/osu/issues/10455

**Closed by bdach** 2024-01-31 19:28 UTC
