### ISSUE TITLE
Watching Replays

### ISSUE THREAD

**Issue by manmathew** [ppy/osu#5207] opened 2019-07-02 04:06 UTC
So to start, I was able to open up a replay file in lazer by dragging it.
The score did load, and when I click on the score the results screen shows up.
The problem is that there is no replay button.
I wasn't sure if this was because I imported a replay, so I set a score and I can't replay that one either.
The main reason why I wanted to watch a replay in osu!lazer is because scorev2 is enforced and so there is hit accuracy on sliders.
I was interested on how having scorev2 would affect scores that have the Perfect mod but someone clicked outside the 300 window on a slider.
That's when I came to this problem of not being able to watch replays.
Whether or not replays would finish or not is worth another thread once we can determine what would happen.

I don't know how to code unfortunately, so I can't program in a replay button or whatever is needed to watch a replay now, but what I am suggesting is the inclusion of a replay button, and for the location of it to be to the right of the "Local Leaderboard" button, since there is plenty of space and it seems appropriate to put it there.

**Comment by iiSaLMaN** [comment] 2019-07-02 04:13
No worries! a replay implementation is coming pretty soon with PR #5189, All you have to do is wait for now. also, this issue is a duplicate of #4991, should be closed.

**Closed** 2019-07-02 04:15 UTC
