### ISSUE TITLE
Mania hold notes can not be extended by dragging the end on the playfield

### ISSUE THREAD

**Issue by OliBomby** [ppy/osu#22663] opened 2023-02-16 10:23 UTC
### Type

Game behaviour

### Bug description

In the osu! stable mania editor you have the ability to change the duration of a hold note by dragging the end of the hold note up and down. This does not require the use of the timeline. This behaviour is missing in the lazer mania editor. 
Also I'm not talking about changing note duration by dragging in the timeline. That does work but it is not intuitive to use in the mania editor.

### Screenshots or videos

https://user-images.githubusercontent.com/17460441/219338226-1855bbeb-4ccd-40ce-b89e-df1b9138acdf.mp4

### Version

2023.207.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/10754838/updater.log)
[performance.log](https://github.com/ppy/osu/files/10754839/performance.log)
[database.log](https://github.com/ppy/osu/files/10754840/database.log)
[input.log](https://github.com/ppy/osu/files/10754841/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10754842/legacy-ipc.log)
[runtime.log](https://github.com/ppy/osu/files/10754843/runtime.log)
[network.log](https://github.com/ppy/osu/files/10754844/network.log)

**Comment by Bruno5430** [comment] 2023-02-17 17:32
Isn't this a duplicate of #19900?

**Comment by OliBomby** [comment] 2023-02-17 23:10
> Isn't this a duplicate of #19900?

Yep turns out this is a duplicate, whoops.

**Closed** 2023-02-19 10:01 UTC
Labels: ruleset:osu!mania, area:editor
