### ISSUE TITLE
Cursor border not in place/missing

### ISSUE THREAD

**Issue by KarstenPH** [ppy/osu#11402] opened 2021-01-02 10:20 UTC
Description: The limit on where you can move the cursor is not there for the menu and menu only. I advise to the people experiencing this issue to be careful.

System Info in the bottom

Instructions on how to replicate:
Move your mouse outward from the center of the screen in any direction (might not work for other people)

osu!lazer Settings:
Window settings: Borderless 1920x1080 with no Screen Scaling
FPS limiter: 8x Refresh rate (60hz x 8)
Mouse settings: Raw input on with 3.10x cursor speed but with absolute input to window off

Logs:
[performance.log](https://github.com/ppy/osu/files/5760009/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5760011/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5760012/updater.log)
[database.log](https://github.com/ppy/osu/files/5760013/database.log)
[network.log](https://github.com/ppy/osu/files/5760018/network.log)

Recorded footage:

https://user-images.githubusercontent.com/66064356/103454577-714b8900-4d20-11eb-8ef3-8702694029d7.mp4

System info:
OS:	Microsoft Windows 10 Home
Version:	10.0.18363 Build 18363
Other OS Description: 	Not Available
OS Manufacturer:	Microsoft Corporation
System Manufacturer:	Acer
System Model:	Nitro 5 AN515-43
System Type:	x64-based PC
System SKU:	0000000000000000
Processor:	AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx, 2300 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date:	Insyde Corp. V1.09, 3/31/2020
SMBIOS Version:	3.1
Embedded Controller Version:	1.01
BIOS Mode:	UEFI
BaseBoard Manufacturer:	PK
BaseBoard Product:	Octavia_PKS
BaseBoard Version:	V1.09
Platform Role:	Mobile
Secure Boot State:	On
PCR7 Configuration:	Elevation Required to View
Windows Directory:	C:\Windows
System Directory:	C:\Windows\system32
Boot Device:	\Device\HarddiskVolume1
Installed Physical Memory (RAM):	16.0 GB
Total Physical Memory:	13.9 GB
Available Physical Memory:	4.84 GB
Total Virtual Memory:	27.9 GB
Available Virtual Memory:	10.2 GB
Page File Space:	14.0 GB
Page File location:	D:\pagefile.sys
Kernel DMA Protection:	Off
Virtualization-based security:	Not enabled
Device Encryption Support:	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions:	Yes
Hyper-V - Second Level Address Translation Extensions:	Yes
Hyper-V - Virtualization Enabled in Firmware:	Yes
Hyper-V - Data Execution Protection:	Yes

Gaming/Editing GPU (for osu! or other games)
Name	NVIDIA GeForce GTX 1650
PNP Device ID	PCI\VEN_10DE&DEV_1F91&SUBSYS_142A1025&REV_A1\4&1A11CB31&0&0009
Adapter Type	GeForce GTX 1650, NVIDIA compatible
Adapter Description	NVIDIA GeForce GTX 1650
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\nvaci.inf_amd64_9f8adc8ebf9ca45d\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvaci.inf_amd64_9f8adc8ebf9ca45d\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvaci.inf_amd64_9f8adc8ebf9ca45d\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvaci.inf_amd64_9f8adc8ebf9ca45d\nvldumdx.dll
Driver Version	27.21.14.6089
INF File	oem28.inf (Section044 section)
Color Planes	Not Available
Color Table Entries	Not Available
Resolution	Not Available
Bits/Pixel	Not Available
Memory Address	0xC1000000-0xC1FFFFFF
Memory Address	0x90000000-0x9FFFFFFF
Memory Address	0xA0000000-0xA1FFFFFF
IRQ Channel	IRQ 4294967255
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\NVACI.INF_AMD64_9F8ADC8EBF9CA45D\NVLDDMKM.SYS (27.21.14.6089, 32.60 MB (34,188,528 bytes), 12/30/2020 6:50 PM)

Light power GPU 
Name	AMD Radeon(TM) RX Vega 10 Graphics
PNP Device ID	PCI\VEN_1002&DEV_15D8&SUBSYS_13661025&REV_C1\4&35FEB52A&0&0041
Adapter Type	AMD Radeon Graphics Processor (0x15D8), Advanced Micro Devices, Inc. compatible
Adapter Description	AMD Radeon(TM) RX Vega 10 Graphics
Adapter RAM	(2,147,483,648) bytes
Installed Drivers	C:\Windows\System32\DriverStore\FileRepository\u0350100.inf_amd64_1aa1a028f1457277\B349878\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0350100.inf_amd64_1aa1a028f1457277\B349878\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0350100.inf_amd64_1aa1a028f1457277\B349878\aticfx64.dll,C:\Windows\System32\DriverStore\FileRepository\u0350100.inf_amd64_1aa1a028f1457277\B349878\amdxc64.dll
Driver Version	26.20.13030.3002
INF File	oem1.inf (ati2mtag_Picasso section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	1920 x 1080 x 60 hertz
Bits/Pixel	32
Memory Address	0xB0000000-0xC01FFFFF
Memory Address	0xC0000000-0xC01FFFFF
I/O Port	0x00001000-0x00001FFF
Memory Address	0xC2600000-0xC267FFFF
IRQ Channel	IRQ 4294967260
IRQ Channel	IRQ 4294967259
IRQ Channel	IRQ 4294967258
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\U0350100.INF_AMD64_1AA1A028F1457277\B349878\ATIKMPAG.SYS (26.20.13030.3002, 583.60 KB (597,608 bytes), 1/14/2020 6:02 PM)

Note: if you need more system info, please tell me what you need so i can send it! also i removed some system info due to privacy reasons

**Comment by bdach** [comment] 2021-01-02 10:22
Duplicate of https://github.com/ppy/osu-framework/issues/2247

**Comment by peppy** [comment] 2021-01-02 10:23
You can avoid this for now by either running windowed or (preferrably) full screen.

**Closed by bdach** 2021-01-02 10:22 UTC
