### ISSUE TITLE
LegacyKeyCounterDisplay not appearing during normal gameplay

### ISSUE THREAD

**Issue by mixdudu** [ppy/osu#29732] opened 2024-09-06 16:51 UTC
### Type

Cosmetic

### Bug description

Legacy key counter shows up normally when watching a replay, but during gameplay it does not appear, and in it's origin place there's only a small box with nothing in it, worth noting that when using autoplay it displays the counter normally

i tested it on 3 different skins, including the official osu "classic" skin from 2013, and different layers, none of them showing the key counter during gameplay

this glitch actually has been happening for a while now, i can't be sure about the exact update, probably always been broken...

### Screenshots or videos

![osu_2024-09-06_13-26-46](https://github.com/user-attachments/assets/de3d60a2-d0b5-4b2e-a5c5-fffa358a70d2)
![osu_2024-09-06_13-27-04](https://github.com/user-attachments/assets/f4690c14-86e9-435f-8901-356b9f601392)
![osu_2024-09-06_13-27-19](https://github.com/user-attachments/assets/7da20105-d678-4ee9-9de3-d47f48b34021)
![osu_2024-09-06_13-27-28](https://github.com/user-attachments/assets/0e7908cf-d3f7-47bc-8f62-156a90f059b5)

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16910899/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-06 17:37
Duplicate of https://github.com/ppy/osu/issues/29686

**Closed by Joehuu** 2024-09-06 17:37 UTC
