### ISSUE TITLE
hovering over cumulative total score in Daily Challenge shows data from previous page

### ISSUE THREAD

**Issue by dooperdoops** [ppy/osu#29126] opened 2024-07-26 23:43 UTC
### Type

Crash to desktop

### Bug description

When you hover over the total score, it shows the pass rate of each score bound from the previous page, prob from not unloading the data or smth idk

### Screenshots or videos

![image](https://github.com/user-attachments/assets/7bb0688e-aa6c-4380-a4f9-270421f0aafb)

### Version

2024.727.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16397438/compressed-logs.zip)

**Comment by dooperdoops** [comment] 2024-07-26 23:45
It also does this on the timer section.

**Comment by Joehuu** [comment] 2024-07-26 23:49
Duplicate of https://github.com/ppy/osu/issues/29122

**Closed by Joehuu** 2024-07-26 23:49 UTC
