### ISSUE TITLE
osu!lazer not open and i need help plz help me

### ISSUE THREAD

**Issue by Felipecconde** [ppy/osu#11787] opened 2021-02-15 16:30 UTC
**Describe the crash:** 
When I try to open osu.AppImage, nothing happens (I already checked the "Allow to run as a program" box and gave the necessary permissions using chmod).

Ok ... let's try to open it using the terminal.

_(If you need to translate something here, the langague is "portuguese")_
```
username@username:~/Área de Trabalho/Documentos/Sistema/Programas/osu!lazer$ ./osu.AppImage
touch: não foi possível tocar '/home/username/.local/share/icons/hicolor/.xdg-icon-resource-dummy': Arquivo ou diretório não encontrado
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
at System.Char.IsDigit(String s, Int32 index)
at osu.Framework.Platform.PassthroughGraphicsBackend.<>c.<getVersionNumberSubstring>b__25_0(String s)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at osu.Framework.Platform.PassthroughGraphicsBackend.getVersionNumberSubstring(String version)
at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window)
at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window)
at osu.Framework.Platform.SDL2DesktopWindow.Create()
at osu.Framework.Platform.GameHost.Run(Game game)
at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
Abortado (imagem do núcleo gravada)
username@username:~/Área de Trabalho/Documentos/Sistema/Programas/osu!lazer$
```

Ok, if it didn't work, it might work if I use "sudo" ...

```
username@username:~/Área de Trabalho/Documentos/Sistema/Programas/osu!lazer$ sudo ./osu.AppImage
cp: não foi possível criar arquivo comum '/root/.cache/thumbnails/normal/994d26e139dbe523f3597988f178f79e.png': Arquivo ou diretório não encontrado
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
at System.Char.IsDigit(String s, Int32 index)
at osu.Framework.Platform.PassthroughGraphicsBackend.<>c.<getVersionNumberSubstring>b__25_0(String s)
at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at osu.Framework.Platform.PassthroughGraphicsBackend.getVersionNumberSubstring(String version)
at osu.Framework.Platform.PassthroughGraphicsBackend.Initialise(IWindow window)
at osu.Framework.Platform.SDL2.SDL2GraphicsBackend.Initialise(IWindow window)
at osu.Framework.Platform.SDL2DesktopWindow.Create()
at osu.Framework.Platform.GameHost.Run(Game game)
at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 55
Abortado
username@username:~/Área de Trabalho/Documentos/Sistema/Programas/osu!lazer$
```

Unfortunately ... nothing happened.

Please help me! I use Ubuntu 20.04 LTS

Edit: Now, the first line of the command error t`ouch: it was not possible to touch '/home/username/.local/share/icons/hicolor/.xdg-icon-resource-dummy': File or directory not found` `cp: it was not possible to create common file '/root/.cache/thumbnails/normal/994d26e139dbe523f3597988f178f79e.png': file or directory not found` I was able to correct it by creating the directory manually, but the rest of the error still appears and I cannot open the osu! leisure. HELP ME PLZ!!!

**Screenshots or videos showing encountered issue:** 
osu! doesnt opens, and i used CLI to explain that, then, i dont need a screenshot.

**osu!lazer version:** 
the latest (i downloaded it on 15/02/2021 [DD/MM/YYYY])

**Logs:**

this error are ocorring in another machine, then i dont have the logs now. sorry, but i think the logs are unseless. a looked at the logs and the only thing that they say are "opening osu!lazer" or something like that. the logs will not help.

**Computer Specifications:** 
idk, but i think that dont have a video card (is using the motherboard intel's videocard), a 2 core processor with 4gb ram, i not remember if are 4 or 8, but i think that is 4. its a 64 bit processor (x86_64). running ubuntu 20.04 lts with the ubuntu graphical interface. i dont know if it are using wayland or xorg, the only thing that i can say is that this are running the default "thing".
sorry about this lol

```
spoiler                                                                                                                                                                very thanks for who can help me and sorry about my english:)
```

**Comment by Joehuu** [comment] 2021-02-15 16:35
Seems like something went wrong with the sdl initialization, try appending `--tk` to the end and see if it works.

If it does, try making it windowed and rerunning it without that arg.

**Comment by bdach** [comment] 2021-02-15 17:23
Duplicate of https://github.com/ppy/osu-framework/issues/4083.

Please read that issue thread and check whether you're using any ["kernel extensions"](https://github.com/ppy/osu-framework/issues/4083#issuecomment-747052522) as the user therein was.

**Closed by bdach** 2021-02-15 17:23 UTC
