### ISSUE TITLE
VSync KeyNotFoundException on window resize

### ISSUE THREAD

**Issue by Tetawex** [ppy/osu#1482] opened 2017-11-09 18:36 UTC
Steps to reproduce the bug:
-open exe
-resize window to minimum height while in main menu
-resize it back
The bug is highly reproducible

**Comment by peppy** [comment] 2017-11-10 10:34
Could you please provide the stack trace and a video of this? I can't reproduce it following your instructions.

**Comment by Tetawex** [comment] 2017-11-10 15:36
Did not mention the issue is with osu!lazer. Sorry for any inconvenience.
Video of the bug https://www.youtube.com/gUIQ-r-Uy-E
The exception randomly appears on window resizing rather consistently

**Comment by peppy** [comment] 2017-11-15 11:15
Could you please check event viewer and provide the exception?

**Comment by naoey** [comment] 2017-12-20 16:36
Happening to me as well at any window size, adding stack trace:
```
{System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenTK.Graphics.GraphicsContext.get_CurrentContext() in D:\temp\67d6772\src\OpenTK\Graphics\GraphicsContext.cs:line 398
   at OpenTK.Graphics.GraphicsContext.Assert() in D:\temp\67d6772\src\OpenTK\Graphics\GraphicsContext.cs:line 364
   at OpenTK.GameWindow.get_VSync() in D:\temp\67d6772\src\OpenTK\GameWindow.cs:line 718
   at osu.Framework.Platform.GameHost.DrawFrame() in C:\Users\naoey\Repositories\osu\osu-framework\osu.Framework\Platform\GameHost.cs:line 301
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\naoey\Repositories\osu\osu-framework\osu.Framework\Threading\GameThread.cs:line 115
   at osu.Framework.Threading.GameThread.runWork() in C:\Users\naoey\Repositories\osu\osu-framework\osu.Framework\Threading\GameThread.cs:line 104
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}
```

**Comment by NITPRUDO** [comment] 2017-12-23 22:55
Can confirm this bug exists. The screenshot below shows the autos when the exception is thrown.
![image](https://user-images.githubusercontent.com/5941912/34323153-ed3ebe44-e809-11e7-92cf-20124b01ee53.png)
For some reason VSync is there. I didn't have it on at the time; I was at 2x frame limit. So, I turned VSync on and tried to reproduce the bug.  I couldn't. This is clearly an issue with VSync.

**Comment by Wieku** [comment] 2018-09-10 15:19
Lazer crashed on me with that exception while moving a window without VSync:

```
10.09.2018 15:13:25: System.Collections.Generic.KeyNotFoundException: The given key '131072' was not present in the dictionary.
10.09.2018 15:13:25: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
10.09.2018 15:13:25: at OpenTK.Graphics.GraphicsContext.get_CurrentContext()
10.09.2018 15:13:25: at OpenTK.GameWindow.get_VSync()
10.09.2018 15:13:25: at osu.Framework.Platform.GameHost.DrawFrame()
10.09.2018 15:13:25: at osu.Framework.Threading.GameThread.ProcessFrame()
10.09.2018 15:13:25: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by peppy** [comment] 2018-09-10 23:16
Good to know this is still an issue. Bumping in priority.

**Comment by peppy** [comment] 2021-02-18 03:32
Has since been resolved by the switch to SDL (although i believe we may have also fixed this issue at the osuTK end too).

**Closed by peppy** 2021-02-18 03:32 UTC
Labels: framework-fix-required
