### ISSUE TITLE
Settings category bar doesn't highlight on the section I clicked on

### ISSUE THREAD

**Issue by CloudyCrayons** [ppy/osu#11109] opened 2020-12-07 05:40 UTC
When selecting a category starting from the top of the list the yellow selector bar doesn't match what I just clicked on.

https://www.youtube.com/watch?v=2rFVbfIXOXY&feature=youtu.be

Lazer 2020.1204.0

[database.log](https://github.com/ppy/osu/files/5650639/database.log)
[network.log](https://github.com/ppy/osu/files/5650640/network.log)
[performance.log](https://github.com/ppy/osu/files/5650641/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5650642/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5650643/updater.log)

**Comment by Joehuu** [comment] 2020-12-07 05:44
Duplicate of https://github.com/ppy/osu/issues/9196

**Closed by Joehuu** 2020-12-07 05:44 UTC
