### ISSUE TITLE
Weird behaviour when selecting multimods

### ISSUE THREAD

**Issue by tom-arrow** [ppy/osu#2046] opened 2018-02-08 21:52 UTC
# Issue
After returning to the main menu and going back to the song selection screen, multimods seem to select other mods when switched.
# Steps to reproduce it
- Open mod overlay
- Select a multimod (e.g. DT/NC) and a single mod (e.g. HD)
- Close mod overlay and go back to main menu.
- Open the  song select screen and mod overlay
- Deselect the single mod
- Select the multimod to switch mod (e.g. DT to NC)
- The single mod will be automatically selected (e.g. HD will be on)

![](https://user-images.githubusercontent.com/28733973/36000157-5156743e-0d22-11e8-9fae-5ba1fd718eee.gif)

**Comment by LittleEndu** [comment] 2018-02-08 22:01
Duplicate of #2018

**Closed** 2018-02-08 22:23 UTC
