### ISSUE TITLE
Huge input latency on macOS in borderless/fullscreen mode

### ISSUE THREAD

**Issue by tivvo** [ppy/osu#30565] opened 2024-11-09 13:54 UTC
### Type

Game behaviour

### Bug description

only found out because i play in windowed / fullscreen
additionally if you're using 2 monitors while plugged in, the other monitor will go black

if its any help, i am currently plugged in to two Dell SE2717H, with my keyboard and mouse using a usb hub thats also attached to my macbook, **using a late-2021 16-inch M1 Pro @ 16gb of ram on Sequoia 15.1**

### Screenshots or videos

[video of windowed/fullscreen input delay](https://files.catbox.moe/vueebs.mp4)

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17687671/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-11-11 10:22
Do you have game mode on? If so, try turning that off.

**Comment by tivvo** [comment] 2024-11-11 16:15
with game mode off it fixes the issue of the input delay 

although the screen is still locked within the default windowed resolution when playing full screen and using the default size, [seems to register the current screen size as the original resolution](https://files.catbox.moe/v0k29c.mp4) 
_(i understand that this is a different issue, but i think its shown in the original video)_

**Comment by frenzibyte** [comment] 2024-11-13 21:34
That would be https://github.com/ppy/osu/issues/26865. I'm not sure if we care about figuring out why macOS's game mode breaks the game (cc @peppy). I don't recall we should, so I'll just close this for now.

**Comment by tivvo** [comment] 2024-11-13 23:59
i think maybe just, disabling game mode on osu as a whole for mac exclusively may be a real solve instead of figuring what i assume is going to be a weird hardware & software challenge with apple

**Comment by peppy** [comment] 2024-11-14 01:34
> That would be https://github.com/ppy/osu/issues/26865. I'm not sure if we care about figuring out why macOS's game mode breaks the game (cc @peppy). I don't recall we should, so I'll just close this for now.

doesn't it default to on?

**Comment by frenzibyte** [comment] 2024-11-14 08:23
It seems it does. Would that be a reason to keep an issue open and investigate it?

**Comment by peppy** [comment] 2024-11-14 09:38
Yes? Else if what you've found is true every installation of macOS is going to be fucked, no??

**Comment by frenzibyte** [comment] 2024-11-14 09:43
It totally slipped my mind that we enabled this ourselves, I'll open an issue thread.

**Comment by frenzibyte** [comment] 2024-11-17 16:49
Okay, apparently I cannot reproduce this issue with "game mode" anymore, and I am specifically running the machine at macOS Sequoia 15.1 (and funny enough, it is the same exact model as OP). I know that when I reproduced the issue I was on an older macOS Sonoma release, but I can't say that's relevant. I will just deprioritise this for now as I'm not sure I can just still blame "game mode" and change that to be disabled.

**Comment by frenzibyte** [comment] 2024-11-17 16:58
I rushed, I'm able to reproduce this reliably by just keeping a Firefox instance running in the background, we probably should disable it for now.

**Closed** 2024-11-18 03:51 UTC
Labels: priority:0, type:input, platform/macOS
