### ISSUE TITLE
Mouse support in mobile version

### ISSUE THREAD

**Issue by jambgaming** [ppy/osu#6343] opened 2019-09-30 21:52 UTC
**Describe the new feature:** 
It would be nice to have mouse support so you can play it like the normal pc version in the mobile version becuase samsung supports mice

**Comment by Joehuu** [comment] 2019-09-30 21:55
Duplicate of https://github.com/ppy/osu-framework/issues/2863

**Closed by Joehuu** 2019-09-30 21:55 UTC
