### ISSUE TITLE
Crash after updating to the latest release.

### ISSUE THREAD

**Issue by jc-hiroto** [ppy/osu#8003] opened 2020-02-26 09:59 UTC
**Describe the crash:** 
Crash when opening osu!. (just right after updating it to the latest version :( )

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
v2020.225.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4254778/database.log)
[network.log](https://github.com/ppy/osu/files/4254780/network.log)
[performance.log](https://github.com/ppy/osu/files/4254783/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4254784/runtime.log)
[system crash log.txt](https://github.com/ppy/osu/files/4254814/system.crash.log.txt)

**Computer Specifications:** 
[system crash log.txt](https://github.com/ppy/osu/files/4254814/system.crash.log.txt)

**Comment by peppy** [comment] 2020-02-26 10:13
Duplicate of https://github.com/ppy/osu/issues/7791

**Closed by peppy** 2020-02-26 10:13 UTC
