### ISSUE TITLE
osu! crashes after resizing window.

### ISSUE THREAD

**Issue by elleyer** [ppy/osu#5443] opened 2019-07-23 22:48 UTC
**Describe the crash:** 
Crashes after resizing window + graphics bugs. Already said about that in discord, so you probably know about this issue (because discord?). Doesn't matter is enabled "front to back render pass" or no. Also all is fine without discord.
**Screenshots or videos showing encountered issue:** 
https://streamable.com/7ayjk
**osu!lazer version:** 
latest
**Logs:** 
[updater.log](https://github.com/ppy/osu/files/3424328/updater.log)
[runtime.log](https://github.com/ppy/osu/files/3424329/runtime.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/3424330/performance-gamethread.update.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/3424331/performance-gamethread.input.log)
[performance.log](https://github.com/ppy/osu/files/3424332/performance.log)
[debug.log](https://github.com/ppy/osu/files/3424333/debug.log)
I hope enough!
**Computer Specifications:** 
G4560, RX470 Sapphite nitro+, 16GB Ram, Windows 10.

**Comment by Joehuu** [comment] 2019-07-23 23:09
Duplicate of #4741.

**Closed** 2019-07-24 02:30 UTC
