### ISSUE TITLE
First game of each update not finishing

### ISSUE THREAD

**Issue by ImAPotatoDude** [ppy/osu#8605] opened 2020-04-03 19:15 UTC
At the end of the first game of each update, the game don't show the result and I had to restart the game to fix.

osu!lazer version:2020.404.0 (play since idk which update, but a week or two)

On Mac

**Comment by bdach** [comment] 2020-04-03 21:42
Can you be more specific what you mean by "first game of each update"? Very first play on a new lazer build?

Logs would be appreciated.

**Comment by ImAPotatoDude** [comment] 2020-04-03 21:52
"Very first play on a new lazer build?" exactly.
My Osu is on the desktop (not a link) (idk if it's what you mean)

**Comment by bdach** [comment] 2020-04-03 22:02
I was asking for log files generated after one of those crashes, which should be located at the path which was visible in the issue template (`~/.local/share/osu/logs`). At this point in time there's not much to go on here in terms of investigating the cause of this issue.

**Comment by ImAPotatoDude** [comment] 2020-04-03 22:17
the game didn't freeze or crash it was just not showing the result. The cursor still move but cannot pause or quit the game and I had to restart the game. I find this in the game files.

[database.log](https://github.com/ppy/osu/files/4430152/database.log)
[network.log](https://github.com/ppy/osu/files/4430153/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/4430154/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4430155/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4430156/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4430157/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4430158/runtime.log)

Trying my best

**Comment by peppy** [comment] 2020-04-04 09:28
Are you able to provide a video showing this behaviour? Does it only happen on certain beatmaps?

**Comment by ImAPotatoDude** [comment] 2020-04-04 09:32
I'll be albe to reproduce the bug with the next release because it happend just once a release but i'll try.

It happend on any different map that I played just after starting a new release.

**Comment by bdach** [comment] 2020-09-19 23:22
@ImAPotatoDude Does this still happen reliably?

**Comment by ImAPotatoDude** [comment] 2020-09-20 18:42
Noヽ(⌐■_■)ノ♪♬

**Comment by bdach** [comment] 2020-09-20 18:43
I'll close this issue for now, then. Please let us know if it happens again.

**Closed by bdach** 2020-09-20 18:43 UTC
Labels: missing details
