### ISSUE TITLE
LegacyRankDisplay flashes gold S ranks every combo increment when they should be silver

### ISSUE THREAD

**Issue by OIAGYT** [ppy/osu#28588] opened 2024-06-25 13:16 UTC
### Type

Cosmetic

### Bug description

this specifically happens only with silver S ranks. i will include a screenshot in this post, but it's pretty bad, cause you can notice this the best during gameplay, it's hard to screenshot it well.

### Screenshots or videos

![osu_2024-06-25_15-07-43](https://github.com/ppy/osu/assets/120472586/1af86915-3f9f-436b-aeca-87d98869f2fc)

### Version

2024.625.0-lazer

### Logs

logs won't be helpful for this, it's just a cosmetic thing

**Comment by bdach** [comment] 2024-06-25 13:28
Duplicate of https://github.com/ppy/osu/issues/28571, will be fixed in upcoming hotfix

**Closed by bdach** 2024-06-25 13:28 UTC
