### ISSUE TITLE
Minimizing the game using Windows + M while in Borderless mode breaks the game's window scaling and changes Display setting

### ISSUE THREAD

**Issue by MartinK99** [ppy/osu#20638] opened 2022-10-08 14:52 UTC
### Type

Other

### Bug description

When minimizing the game by pressing the Windows + M shortcut it closes down into the taskbar as expected, but when reopening it the game window shrinks down to the height of the taskbar at roughly a 21:9 scaling and stays there with the rest of the screen being black. Screenshots attached.
The game seems to be fully working otherwise, and closing down the game with the Alt + F4 shortcut works as well. 
What also works is tabbing into the game in its broken window state, interacting with anything other than the game (Desktop on a second monitor, other program) and clicking within the game fixes the game window size. Theres some mouse weirdness going on as well doing that but I'm not sure if those two things are related to each other.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/25412980/194712974-826d8119-34c6-42ab-8a56-41fe154133e5.png)

### Version

2022.1008.2

### Logs

[network.log](https://github.com/ppy/osu/files/9739538/network.log)
[performance.log](https://github.com/ppy/osu/files/9739539/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9739540/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9739541/updater.log)
[database.log](https://github.com/ppy/osu/files/9739542/database.log)

**Comment by Susko3** [comment] 2022-10-08 15:02
Can also reproduce when pressing <kbd>Win</kbd>+<kbd>Down arrow</kbd> when osu! is in focus.

**Comment by Susko3** [comment] 2022-10-08 23:19
Duplicate of https://github.com/ppy/osu-framework/issues/5407.

**Closed by Susko3** 2022-10-08 23:19 UTC
Labels: framework-fix-required
