### ISSUE TITLE
Square borders around objects in score results on iOS version instead of circular borders

### ISSUE THREAD

**Issue by ghost** [ppy/osu#4196] opened 2019-02-02 08:37 UTC
**Describe your problem:** 
Render issue where there’s no circles but all squares in the iOS version and flat colours. It looks fine on the PC version though.

It also happens with spinners.

**Screenshots or videos showing encountered issue:** 
iOS:
![img_0063](https://user-images.githubusercontent.com/38002802/52161974-cc316b80-2718-11e9-8961-0c13cfd6edb2.png)

PC:
![osu lazer 2_02_2019 6_26_39 pm](https://user-images.githubusercontent.com/38002802/52161975-d2274c80-2718-11e9-92c4-4c84cbe2d137.png)

**osu!lazer version:** 2019.131.0
**iOS device:** iPad 6th generation non-cellular

**Comment by Joehuu** [comment] 2019-09-19 04:06
Can't reproduce on iPad mini 2 at any ui scale on latest release.

**Comment by smoogipoo** [comment] 2019-09-19 11:58
Fixed by https://github.com/ppy/osu-framework/pull/2680

**Closed by smoogipoo** 2019-09-19 11:58 UTC
Labels: bug, iOS, user interface
