### ISSUE TITLE
osu!Lazer on MacOS Mojave 10.14.2

### ISSUE THREAD

**Issue by LOLgameplayer10** [ppy/osu#8139] opened 2020-03-05 01:27 UTC
**Describe the crash:** 
When I attempt to use the osu.app.zip, I extract it, open osu!, but as soon as I open it, it closes and gives me the error, "osu! quit unexpectedly." A fix could be to give the setup.exe file to use Wineskin or with the .zip includes the .zip like the Mac version of regular osu!.
**Screenshots or videos showing encountered issue:** 
https://gyazo.com/50e0001da420b1ef802a45d3941e68f2
**osu!lazer version:** 
2020.229.1

**Computer Specifications:** 
MacOS Mojave 10.14.2, non-modified

**Comment by swoolcock** [comment] 2020-03-05 01:42
Lazer is a native macOS app, it does not run under wine.

Please provide logs if they are available.

**Comment by peppy** [comment] 2020-03-05 01:43
Duplicate of https://github.com/ppy/osu/issues/7791

**Closed by peppy** 2020-03-05 01:43 UTC
