### ISSUE TITLE
Slider speed differs for same slider in stable vs lazer

### ISSUE THREAD

**Issue by wawdili** [ppy/osu#24056] opened 2023-06-27 01:06 UTC
### Type

Game behaviour

### Bug description

The speed of the slider varies on the Lazer., and here is a Beatmap that reveals the problem.
However, if a speed change is added to the timeline, this problem will be resolved.
But if the player does not notice this issue, then Beatmap will have a different experience on Lazer and Stable. (Different difficulty levels)
(In "[disuse] Normal", the first object, the other difficulties have already been fixed.)
[TUYU - Under Kids.zip](https://github.com/ppy/osu/files/11876544/TUYU.-.Under.Kids.zip)

### Screenshots or videos

![FZ(XZG4UB @8 70(MJDOE`S](https://github.com/ppy/osu/assets/87159802/81fc6a3a-5544-4556-9dc6-57f918eb73cd)
![248842780-f3aa666d-f431-4ed2-bd73-1d6f0edfc928](https://github.com/ppy/osu/assets/87159802/a2352e30-6def-49f8-8328-03607a68ed44)
(Expected to be consistent with the stable version)

### Version

2023.617.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11870654/runtime.log)

**Comment by peppy** [comment] 2023-06-28 05:00
Will set this to priority 0 until it's investigated.

**Comment by wawdili** [comment] 2023-06-28 10:32
> Will set this to priority 0 until it's investigated.

I found that the speed of the slider is 1.0x, it should be 0.1x.

It is worth noting that inserting an inheritance time point (SV: 0.1x) before the slider in the stable version can solve the problem, and the inheritance time point cannot coincide with the slider (in fact, some people may prefer to overlap the time point with the object).

Or adjust the speed of the slider to 0.1x in the lazer.

**Comment by newo-2001** [comment] 2023-06-28 14:55
The slider in question has its time set to `641ms`, whereas the control point with the 0.1x sv multiplier is set at `641.666666666662ms` meaning the slider is not affected by the control point and instead uses the default 1.0x sv. Manually changing the time of the control point to `641ms` loads the map correctly. Maybe stable truncates the number and therefor places the timing point at `641ms`.

**Comment by peppy** [comment] 2023-06-28 15:01
I'm so confused now.

Let's take a step back:

- How was the beatmap made?
- Where was it edited?

Because stable cannot set floating-point timing. And lazer can't either because timing is stored against the hitobjects.

**Comment by wawdili** [comment] 2023-06-29 00:05
I used to edit it in the Lazer before, but after losing data, I rebuilt it and then abandoned it to try a new style to create it (at this time, I created it in the stable version with a new difficulty level. However, I used the previous copy to empty the objects and kept the time points, but later I also modified the time points during the production). Afterwards, I did not use Lazer to edit it anymore.

**Comment by wawdili** [comment] 2023-06-29 00:24
However, I have found that in other beatmaps, even if they align time points to objects, they can still take effect in the lazer. Are you saying that my beatmap has accuracy issues?

**Comment by peppy** [comment] 2023-06-29 01:17
Please provide reproduction steps from a fresh beatmap, including a video.

**Comment by wawdili** [comment] 2023-06-29 01:46
> Please provide reproduction steps from a fresh beatmap, including a video.

I will try to reproduce.

How should I transfer a huge video file to you?

**Comment by wawdili** [comment] 2023-06-29 02:37
I think I failed to replicate. When trying to replicate the issue, Beatmap was running normally. The old difficulty level still has problems.

**Comment by peppy** [comment] 2023-06-29 04:21
Will close this for now, pending full steps to reproduce. Sure, this can happen, but I'd argue it can only happen with manual `.osu` editing.

**Closed by peppy** 2023-06-29 04:21 UTC
Labels: priority:0, area:beatmap-parsing

**Comment by wawdili** [comment] 2023-06-29 04:46
It seems that there may be some issues importing from Lazer to the stable version of Beatmap.
![UR G(PVBGUHV0ZB{55EY{CM](https://github.com/ppy/osu/assets/87159802/12bc15b9-72ca-41bf-8a76-f46318e34e25)

I seem to have found a way to fix this problem (even if the time points overlap, the problem does not arise),
But I haven't found out how to reproduce yet.

The video has been recorded, but how can I send it?

**Comment by peppy** [comment] 2023-06-29 04:50
Youtube upload or something.

**Comment by wawdili** [comment] 2023-06-29 04:53
> Will close this for now, pending full steps to reproduce. Sure, this can happen, but I'd argue it can only happen with manual editing.`.osu`

I have never manually edited a file.

**Comment by wawdili** [comment] 2023-06-29 04:55
> Youtube upload or something.

Okay, I will upload it on a video website, and when the video review is completed, I will send a link and mention you.
