### ISSUE TITLE
Hold for menu button overlaps with visual settings

### ISSUE THREAD

**Issue by SandTheNeeT** [ppy/osu#11584] opened 2021-01-23 23:37 UTC
**Describe the bug:** 
When watching a replay, the menu button overlaps with the visual settings menu. It's needed to click on the text next to the menu in order to change that setting, I'm used to click directly on the setting button, not the text.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/26170166/105616911-9b054680-5dda-11eb-8d6b-d275427f201a.png)
https://user-images.githubusercontent.com/26170166/105616995-90977c80-5ddb-11eb-84d0-d229c6898d34.mp4

**osu!lazer version:** 
2021.118.1

**Logs:**
[database.log](https://github.com/ppy/osu/files/5861326/database.log)
[network.log](https://github.com/ppy/osu/files/5861327/network.log)
[performance.log](https://github.com/ppy/osu/files/5861328/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5861329/runtime.log)

**Comment by bdach** [comment] 2021-01-23 23:38
Shortcoming caused by the mostly-temporary placement of the settings overlay on legacy skins.

**Comment by Joehuu** [comment] 2021-01-23 23:41
Duplicate of https://github.com/ppy/osu/issues/9229

**Closed by Joehuu** 2021-01-23 23:41 UTC
Labels: area:gameplay, area:skinning, type:UI
