### ISSUE TITLE
Local Offset by individual map

### ISSUE THREAD

**Issue by Mic238** [ppy/osu#9691] opened 2020-07-27 14:14 UTC
In the stable osu client, local offset can be set by +/- key, and this doesn't seem to work in lazer. Is this feature in dev or it won't be available in lazer at all?

**Comment by jai-x** [comment] 2020-07-27 14:18
Local offset has been brought up before but has not been worked on yet.
The intent is for osu!lazer to have feature parity with osu!stable in terms of gameplay.

Duplicate of https://github.com/ppy/osu/issues/8787

**Closed** 2020-07-27 14:27 UTC
