### ISSUE TITLE
Add support for importing from an osu-stable install on linux

### ISSUE THREAD

**Issue by ppman420** [ppy/osu#10183] opened 2020-09-17 22:45 UTC
**Describe the new feature:** 
osu! currently does not support importing from an osu-stable install on wine because it cannot find the install. To fix this, the user can choose where osu-stable is located.
**Proposal designs of the feature:** 
It can probably look like this:
![import-from-stable](https://user-images.githubusercontent.com/68097633/93535898-ecc22f80-f915-11ea-9f70-fb7ae2ce60a3.jpeg)

**Comment by frenzibyte** [comment] 2020-09-17 22:49
Duplicate of #3763, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Comment by bdach** [comment] 2020-09-17 22:51
Also see instructions in https://github.com/ppy/osu/issues/7234, as an example, how to use symlinks to work around this limitation for now.

**Closed by bdach** 2020-09-17 22:51 UTC

**Comment by ppman420** [comment] 2020-09-17 22:53
Thanks, it worked
