### ISSUE TITLE
Leaderboard stuck in endless retrieving loop

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu#1724] opened 2017-12-22 13:02 UTC
I imported a map and discovered that the game wasn't able to retrieve scores for it. It failed and logged me out. Then it logged me back in to begin the cycle anew...

I was not able to prevent this in any way except from leaving Song Select and logging out (or logging out fast enough in Song Select).

Video: https://streamable.com/d6use

**Comment by Aergwyn** [comment] 2017-12-25 21:18
Must've been a temporary API issue. This is not reproducible on any version with any beatmap.

**Comment by Aergwyn** [comment] 2017-12-26 08:12
It's happening again. Same map. I'll try to debug while I have the chance.

**Comment by Aergwyn** [comment] 2017-12-26 08:25
From the log this is the cycle that is repeated over and over. Want more log? Once you reach the last line, start from the first one again. That is the whole thing.
```
26.12.2017 08:23:26: Queueing a ping request
26.12.2017 08:23:26: Performing request osu.Game.Online.API.Requests.ListChannelsRequest
26.12.2017 08:23:27: Request to https://osu.ppy.sh/api/v2/chat/channels successfully completed!
26.12.2017 08:23:27: We just went Online!
26.12.2017 08:23:27: Performing request osu.Game.Online.API.Requests.ListChannelsRequest
26.12.2017 08:23:27: Request to https://osu.ppy.sh/api/v2/chat/channels successfully completed!
26.12.2017 08:23:27: Performing request osu.Game.Online.API.Requests.GetScoresRequest
26.12.2017 08:23:27: Request to https://osu.ppy.sh/api/v2/beatmaps/1468281/scores failed with System.Net.WebException: 422 (FAILED).
26.12.2017 08:23:27: API failure count is now 1
26.12.2017 08:23:27: Performing request osu.Game.Online.API.Requests.GetScoresRequest
26.12.2017 08:23:27: Request to https://osu.ppy.sh/api/v2/beatmaps/1468281/scores failed with System.Net.WebException: 422 (FAILED).
26.12.2017 08:23:28: API failure count is now 2
26.12.2017 08:23:28: Performing request osu.Game.Online.API.Requests.GetScoresRequest
26.12.2017 08:23:28: Request to https://osu.ppy.sh/api/v2/beatmaps/1468281/scores failed with System.Net.WebException: 422 (FAILED).
26.12.2017 08:23:28: API failure count is now 3
26.12.2017 08:23:28: We just went Failing!
26.12.2017 08:23:28: In a failing state, waiting a bit before we try again...
```

**Comment by Aergwyn** [comment] 2017-12-26 08:31
Also it "logging me out" seems to be only visually as none of the 3 `Logout` occurences is ever reached.

**Comment by Aergwyn** [comment] 2017-12-26 08:36
Logging out is only visually as in `LoginSettings.APIStateChanged()` the UserPanel is overriden when the `APIState` is `Failing` (more like... removed) and thus it defaults to "GuestUser". After changing back to `Online` the user is set again and thus I appear online once more.

**Comment by Aergwyn** [comment] 2017-12-26 08:45
This endless loop seems to be created by `Leaderboard.APIStateChange()`. As the API cycles between `Failing` and `Online` the leaderboard tries to query the scores each time we go `Online`.

**Comment by peppy** [comment] 2017-12-30 05:07
Moving this to January milestone as it seems to be hard to reproduce.

**Comment by naoey** [comment] 2017-12-30 05:14
I remember at one point querying scores for a taiko beatmap with `mode=osu` was causing the API to return 403/422 (don't remember which now) which made the API go into a failing state and hence the user panel offline appearance etc., until the next successful request brought API back to online state. This might be something related?

**Comment by peppy** [comment] 2017-12-30 05:14
Quite possibly. I believe there are issues in how errors are handled in APIAccess at the moment. That class was written in a hurry and definitely requires some huge refactoring going forward.

**Comment by naoey** [comment] 2017-12-30 05:21
I just noticed the 422 in the logs so it probably is the same thing, because that beatmap (1468281) is a taiko map too, so seems like it's querying for scores with the wrong mode parameter. But this shouldn't be happening anymore after you changed song select to no longer show non-convertible beatmaps in the current ruleset 🤔

**Comment by Aergwyn** [comment] 2017-12-30 08:01
Anything to bring it to `Failing` state is enough to reproduce it. Generally I'm not sure if the Leaderboard should react if the state changes to `Online` or if there should be a "LoggedIn" and "LoggedOut" event for this.

**Closed** 2018-03-10 16:38 UTC
Labels: bug, online, pending review
