### ISSUE TITLE
Fast-forwarding past a break and then rewinding to just before it incorrectly shows break overlay

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6879] opened 2019-11-19 14:35 UTC
**Describe the bug:** 
- 
In autoplay/replay mode, scrubbing just past a break and then rewinding to just before it will show the break overlay when it probably shouldn't (the break overlay doesn't show on the fast-forward but plays after rewind).

**Screenshots or videos showing encountered issue:**
-
 [link to video (see 0:26)](https://streamable.com/cqdhf)

**osu!lazer version:** 
-
- app-2019.1113.0

**Logs:**
-

> not required, purely visual, should occur on any map

**Comment by bdach** [comment] 2019-11-19 18:25
The first issue was a duplicate of #5119 and the second one (RAM usage) will probably be functionally equivalent to #6123 and similar and be resolved with implementation of #6136. I've edited your report significantly to only contain necessary information and narrowed scope of this issue to the last problem.

Please search before submitting an issue and please do not group up multiple problems in one issue.

**Comment by Joehuu** [comment] 2020-12-07 06:06
Seems to be fixed in [`977fb3d` (#7361)](https://github.com/ppy/osu/pull/7361/commits/977fb3d1bfe862f9fc38b37b110894a12d0379bd).

**Closed by Joehuu** 2020-12-07 06:06 UTC
Labels: area:replay
