### ISSUE TITLE
A bug with the results screen and saving the replay

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7364] opened 2019-12-26 12:17 UTC
If you click Escape immediately after the end of the map (in the "Osu-stable" mode, we always go to the results screen like this), the animation from the bottom right will succeed, but the results screen will not appear and the replay will not be saved at all.
However, if after the end of the map you do not hold the Escape key for the time specified by the "hold-to-confirm activation time" parameter, then the bug does not occur.

https://www.youtube.com/watch?v=vBG-Q-glpyI (Start at 1:30)

Lazer 2019.1225.0

Logs:
[runtime.log](https://github.com/ppy/osu/files/4002493/runtime.log)
However, in the logs the line of transition to the results screen is shown, but it is clear that at 12:03:40 there was a certain conflict between the main menu and the results screen. In the same log, you can see several more attempts to repeat this bug (several were unsuccessful)

**Comment by smoogipoo** [comment] 2019-12-26 12:21
Duplicate of https://github.com/ppy/osu/issues/7353, fixed.

**Closed by smoogipoo** 2019-12-26 12:21 UTC
