### ISSUE TITLE
Mods dimming dims all content

### ISSUE THREAD

**Issue by AltenGD** [ppy/osu#4383] opened 2019-03-01 17:53 UTC
When opening the mods overlay, instead of just the background being dimmed both the background and mod overlay has been dimmed. 

https://streamable.com/nlow5

**osu!lazer version:** 2019.301.7

**Comment by peppy** [comment] 2019-03-01 18:03
Duplicate of #4376.

**Closed by peppy** 2019-03-01 18:03 UTC
