### ISSUE TITLE
osu.Appimage on Manjaro linux raw input issue

### ISSUE THREAD

**Issue by Ilyandress** [ppy/osu#8092] opened 2020-03-02 12:17 UTC
When I turn on 'raw input' option my cursor go insane and I can't do anything. Cursor tries to reach borders of active screen and avoid everything that is inside of it.

**Comment by jai-x** [comment] 2020-03-02 12:20
Duplicate of https://github.com/ppy/osu/issues/3489

Please search for existing issues first before creating new ones.

**Closed** 2020-03-02 12:21 UTC
