### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by zeroeightysix** [ppy/osu#5198] opened 2019-06-30 19:30 UTC
Right now, launching osu-lazer on a wayland session will fallback to using xwayland (and create a X surface).
Having osu support wayland natively would be awesome.

**Comment by jorolf** [comment] 2019-06-30 19:37
https://github.com/ppy/osuTK is probably the correct place for this issues as we use that fork of openTK to create windows. That said, I'm unsure if it's even possible because we use SDL on linux (see [this](https://github.com/ppy/osu-framework/blob/master/osu.Framework/Host.cs#L20)).

**Comment by zeroeightysix** [comment] 2019-06-30 19:46
@jorolf I'd love to create a new issue on said repo but it's got issues disabled

**Comment by jai-x** [comment] 2019-06-30 19:56
I believe SDL2 already has wayland support so I think it would be possible. You could also try running lazer with the environment variable `SDL_VIDEODRIVER=wayland` set to see if the currently linked version of the library will use wayland now.

**Comment by zeroeightysix** [comment] 2019-06-30 20:03
@jai-x 
![image](https://user-images.githubusercontent.com/27009727/60401513-c6826980-9b82-11e9-8ac5-aab57f728495.png)
Sadly, it will not.

**Comment by jorolf** [comment] 2019-06-30 20:47
🤔 I don't think that's how you export enviroment variables
https://wiki.archlinux.org/index.php/Environment_variables

**Comment by zeroeightysix** [comment] 2019-06-30 20:55
>  I don't think that's how you export enviroment variables
> https://wiki.archlinux.org/index.php/Environment_variables

Oops. Using `export SDL_VIDEODRIVER=wayland`, osu-lazer *does* run natively!
Brilliant, now we just have to make this a default (if on wayland, of course).

**Comment by jorolf** [comment] 2019-06-30 22:38
Feel free to create a pull request to osuTK so that SDL does this automatically on startup

**Comment by Alexmitter** [comment] 2019-08-17 15:55
I can confirm setting SDL_VIDEODRIVER=wayland successfully causes the client to start up in wayland mode. But I also encounter some bugs.

- Scrolling is over sensitive. Scrolling in the settings is nearly impossible. Scrolling for volume seems to treat every scroll wheel step as 50%. So i can step between 0%, 50% and 100%
- There is no window decoration in Window mode.
- It does not start on the primary screen.
- Something is wrong with the colors, color steps are clearly visible.
- If closed, it leaves a black unmovable box on the screen. This may be a Gnome Mutter bug, but no other program causes something like this.

**Comment by Alexmitter** [comment] 2019-11-09 12:02
>"If closed, it leaves a black unmovable box on the screen if it was in full screen mode. This may be a Gnome Mutter bug, but no other program causes something like this."
This is fixed now

**Comment by Alexmitter** [comment] 2020-10-17 09:41
> Scrolling is over sensitive. Scrolling in the settings is nearly impossible. Scrolling for volume seems to treat every scroll wheel step as 50%. So i can step between 0%, 50% and 100%

Fixed

> It does not start on the primary screen.

Fixed

It is now playable. Missing window decoration in windows mode is still a big issue for those playing in windowed mode and the colour issue is still a bit annoying.

**Comment by peppy** [comment] 2020-10-27 08:20
@Alexmitter have you attempted running using `--sdl`? This uses our newer backend which may give you better window manager support.

**Comment by Alexmitter** [comment] 2020-10-27 09:51
Hello @peppy . I did dig a bit into the decoration issue and it seems like something not fixable. Wayland wants clients to draw their own decorations while traditionally the server side did this job. But SDL does not want to support drawing its own decoration. 
Something like [libdecoration](https://gitlab.gnome.org/jadahl/libdecoration) may be the solution but I do not think its ready yet.

--sdl works but I noticed that the sdl2 library is not included in the appimage while all games usually do this. Think about including it.

One thing that is still pretty annoying is the color border issue exclusive to wayland.
With Xorg
![image](https://user-images.githubusercontent.com/6940479/97285121-1c802380-1842-11eb-9a6c-cb1bf1b09891.png)

With Wayland
![image](https://user-images.githubusercontent.com/6940479/97285152-26a22200-1842-11eb-8dca-3e2623387927.png)

Thank you for your help ppy

**Comment by peppy** [comment] 2020-10-27 12:00
I think it's safe to close this issue for now then.

**Closed by peppy** 2020-10-27 12:00 UTC
Labels: platform:linux

**Comment by Alexmitter** [comment] 2021-03-31 20:43
Hello @peppy , would you mind taking a look at this color issue mentioned above? All the major Linux distributions are now looking into enabling wayland by default and the lower latency compared to Xorg will be a benefit for playing osu!.

**Comment by bdach** [comment] 2021-03-31 20:52
Sorry to say but linux is not an immediate priority, and we cannot actively support all possible combinations of user configurations. The main focus for now is completing the major pieces of the game that are not yet on par with stable.

External contributions that fix your issue would definitely be appreciated - this is an open source project after all.
