### ISSUE TITLE
welcome to osu background appears on other intro/songs

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#9562] opened 2020-07-14 15:06 UTC
**steps to reproduce bug:** 
1. start lazer with either triangles (maybe circles too) intro
2. change intro to welcome without restarting
the welcome bg displays and even continues when another song has taken the triangles place. (non supprter btw)

**Screenshots or videos showing encountered issue:** 
at start:
![osu_2020-07-14_22-59-48](https://user-images.githubusercontent.com/41866328/87442028-609a4000-c626-11ea-90d0-2b85e23bc98a.png)

after the intro:
![osu_2020-07-14_23-03-38](https://user-images.githubusercontent.com/41866328/87442101-760f6a00-c626-11ea-8fd0-dfaeee3dc29e.png)

**osu!lazer version:** 2020.714.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4919552/runtime.log)
[database.log](https://github.com/ppy/osu/files/4919553/database.log)

**Comment by MiraiSubject** [comment] 2020-07-14 15:32
You can indeed start osu! with the triangles and circles and then change the background to the `Welcome` screen. It will apply the appropriate background straight away.

The Beatmap background only shows up if you're an osu! supporter

**Comment by bdach** [comment] 2020-07-14 16:20
Closing as intended.

**Closed by bdach** 2020-07-14 16:20 UTC

**Comment by enoslayd** [comment] 2020-07-14 16:23
But should it be only shown when the inro is playing (or at least, display in next restart when welcome is playing)

**Comment by peppy** [comment] 2020-07-15 03:47
This is intended.
