### ISSUE TITLE
Unable to skip intro during multiplayer

### ISSUE THREAD

**Issue by imadofficial** [ppy/osu#19897] opened 2022-08-21 20:47 UTC
### Type

Game behaviour

### Bug description

When playing on a multiplayer match, you are unable to skip the intro of a beatmap despite pressing space.

### Version

2022.821.0

### Logs

[performance.log](https://github.com/ppy/osu/files/9389926/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9389927/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9389928/updater.log)
[database.log](https://github.com/ppy/osu/files/9389929/database.log)
[network.log](https://github.com/ppy/osu/files/9389930/network.log)

**Comment by Joehuu** [comment] 2022-08-21 20:49
Duplicate of https://github.com/ppy/osu/issues/14260

**Closed by Joehuu** 2022-08-21 20:49 UTC
