### ISSUE TITLE
Flicker during Fn Toggle (Volume Toggle)

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#8579] opened 2020-04-02 16:52 UTC
**Describe the bug:** 
During change volume using Fn toggle , the game starting to flicker
**Screenshots or videos showing encountered issue:** 
https://youtu.be/cqnUFF0ir0I
**osu!lazer version:** 
2020.403.0
**Logs:**
https://drive.google.com/file/d/10hfEtDUGYymVod5EIJJxwJF6DSuzrwCY/view?usp=sharing

**Comment by bdach** [comment] 2020-04-02 18:05
Is this full-screen, or borderless?

I'm not sure we're going to be able to do much with this problem. For what it's worth I can't reproduce it.

**Comment by HerendraTJ** [comment] 2020-04-03 02:36
The problem during fullscreen yes.

**Comment by bdach** [comment] 2020-04-03 22:06
I'm just going to go ahead and close this as it is unlikely we'll be able to reproduce or fix it due to it being likely specific to hardware/OS version. Please try and see if running borderless or with the experimental `--sdl` flag helps.

**Closed by bdach** 2020-04-03 22:06 UTC
