### ISSUE TITLE
Tooltip missing for non-default speed DT plays

### ISSUE THREAD

**Issue by randomman254** [ppy/osu#8798] opened 2020-04-19 00:37 UTC
**Describe the bug:** 
Earlier I played a song with DT set to 1.10x speed instead of the default 1.50x speed, but there is not a tooltip on the leaderboard mod that says I had changed it. Including logs anyway even though I don't think there is a need for them.

**Screenshots or videos showing encountered issue:** 
![osu_2020-04-18_19-34-03](https://user-images.githubusercontent.com/30556038/79676436-c43dda00-81ab-11ea-9c3b-df631a6b28bf.jpg)
![osu_2020-04-18_19-34-30](https://user-images.githubusercontent.com/30556038/79676437-c56f0700-81ab-11ea-99fb-bdb07dc2ee8a.jpg)

**osu!lazer version:** 2020.418.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/4498114/network.log)
[performance.log](https://github.com/ppy/osu/files/4498115/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4498116/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4498117/updater.log)
[database.log](https://github.com/ppy/osu/files/4498118/database.log)

**Comment by iiSaLMaN** [comment] 2020-04-19 00:39
Because replays don't have support for customised mods, can say duplicate of https://github.com/ppy/osu/issues/8569

**Closed** 2020-04-19 00:45 UTC
