### ISSUE TITLE
Spinners can be cheesed by moving the cursor in a straight line quickly

### ISSUE THREAD

**Issue by BHNowaru** [ppy/osu#11512] opened 2021-01-16 15:43 UTC
**Describe the bug:** 

Spinners can be cheesed by moving your cursor left and right (or up and down). This permits spins > 490 rpm (possibly above 500) easily. 

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/16274568/104816101-1a40bc00-57d6-11eb-8d52-d6f1cf0e9a85.mp4

**osu!lazer version:** 
osu!lazer 2021.109.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/5824645/database.log)
[network.log](https://github.com/ppy/osu/files/5824648/network.log)
[updater.log](https://github.com/ppy/osu/files/5824649/updater.log)
[performance.log](https://github.com/ppy/osu/files/5824650/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/5824651/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5824652/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5824653/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5824654/runtime.log)

**Comment by bdach** [comment] 2021-01-16 15:44
Duplicate of #8224

**Comment by frenzibyte** [comment] 2021-01-16 15:44
Duplicate of https://github.com/ppy/osu/issues/8224, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2021-01-16 15:44 UTC

**Comment by BHNowaru** [comment] 2021-01-16 21:57
yeah, i saw the post but i didnt see the comments, my bad qq
