### ISSUE TITLE
Osu!direct search crash

### ISSUE THREAD

**Issue by LukaTV939** [ppy/osu#6309] opened 2019-09-28 19:15 UTC
**Describe the crash:** 
By just typing in osu!direct search tab
**Screenshots or videos showing encountered issue:** 
https://photos.app.goo.gl/HTtqn2nGMHYvdAWF6
**osu!lazer version:** 
2019.925.0
**Logs:** 
?
**Phone Specifications:** 
Samsung Galaxy A50 (too lazy to write specifications, just google for my phone specifications) Android 9.0

**Comment by bdach** [comment] 2019-09-28 19:25
Duplicate of #6264.

**Comment by LukaTV939** [comment] 2019-09-28 19:28
Yeah

**Closed** 2019-09-28 22:52 UTC
