### ISSUE TITLE
Cursor glitch with custom cursor sensitivity

### ISSUE THREAD

**Issue by Torphage** [ppy/osu#4606] opened 2019-04-07 15:28 UTC
**Describe the bug:**
When raw input is on and the cursor sensitivity is set to anything except 1 the cursors gets a weird behavior. When the cursor movement is below 1 the cursor can not be moved, it instead shakes in a spot when you try to move it. When the cursor movement is set to anything above 1 the mouse instantly moves to the the end of the window in the direction you are moving. Have tried on windowed, borderless window and fullscreen and gets the same result.

This behavior does only happen when the window is focused, so whenever I do move my mouse on a mouse sensitivity that's not 1 I have to focus something else, did it by alt-tabbing and bringing up the console. Every time the cursor teleport is done by this glitch, even the one time after setting cursor sensitivity to below 1. Also, when the cursor sensitivity is below 1 I do move my hand rather violently trying to make it move. Even if the values would be 0.99 or 1.01 it would still not work correctly.

The OS used is Ubuntu 18.10

**Screenshots or videos showing encountered issue:**
https://streamable.com/2k00o

**osu!lazer version:**
Built locally from 2019.406.0

**Logs:**
[logs.zip](https://github.com/ppy/osu/files/3051656/logs.zip)

**Comment by smoogipoo** [comment] 2019-04-08 02:37
Duplicate of https://github.com/ppy/osu/issues/4606

**Comment by dscnnctd** [comment] 2019-04-08 03:06
>Duplicate of https://github.com/ppy/osu/issues/4606

@smoogipoo this is #4606 I believe...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smoogipoo** [comment] 2019-04-08 03:09
Uh, my bad, thanks.

**Comment by robzombie91** [comment] 2019-04-13 15:46
Can confirm this still happens

**Comment by LastExceed** [comment] 2019-04-14 16:17
Duplicate of #3489

**Comment by peppy** [comment] 2019-04-15 05:25
Closing as duplicate.

**Closed by peppy** 2019-04-15 05:25 UTC
Labels: framework fix required, input, linux
