### ISSUE TITLE
Various issues with quick retry when DT is enabled

### ISSUE THREAD

**Issue by LamGC** [ppy/osu#20908] opened 2022-10-24 16:52 UTC
### Type

Game behaviour

### Bug description

When Double Time is enabled and you enter the game, immediately press the shortcut key '~' to retry, which will cause abnormal speed and BGM loss after the game is retried.

After some tests, if you use the 'Retry' in the UI, the problem will be solved. If you continue to use the '~' shortcut key to retry the game, the problem will continue to grow.

After successfully triggering the bug:
- Game music disappears and Double Time accelerates too fast.

After the bug is triggered, the following problems will occur:
- The speed of game acceleration increases abnormally. ( The more triggered, the faster, and the longer the impact. )
- Music loss ( possibly related to game speed ) ( this situation will also affect the music preview on the song selection interface )
- Certain special effect error (after unable to pause, click the close button of the window to exit the main interface, and the paused sound effect will be retained in the main interface and the song selection interface)
- Adjusting the window size after successfully triggering the bug will cause the game to crash. ( Not confirmed, it may be a problem with my system )

The recurrence frequency of this problem is: `often`, Because I can't reproduce this problem in other Beatmaps. I tried to reproduce the problem in Windows 11, but it did not succeed.

### The relevant Beatmaps are as follows
Beatmap that successfully reproduced the problem:
- https://osu.ppy.sh/beatmapsets/1343575#osu/2782845
- https://osu.ppy.sh/beatmapsets/235477#osu/580225
- https://osu.ppy.sh/beatmapsets/600297#osu/1268627

### Screenshots or videos

https://1drv.ms/u/s!AuZ8JMPu3cmegcErKInNL1A1oRbvJw?e=VOu2Tx

### Version

2022.1022.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9853654/database.log)
[network.log](https://github.com/ppy/osu/files/9853655/network.log)
[performance.log](https://github.com/ppy/osu/files/9853656/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9853657/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9853659/updater.log)

**Comment by peppy** [comment] 2022-10-25 02:26
You mention an "exception" but I can't find any errors in your logs. I am guessing you didn't mean to use the word exception here.

**Comment by LamGC** [comment] 2022-10-25 02:51
> You mention an "exception" but I can't find any errors in your logs. I am guessing you didn't mean to use the word exception here.

I try to reproduce the problem and upload a new log.

In addition, I can easily reproduce the problem in this Beatmap:  
https://osu.ppy.sh/beatmapsets/235477#osu/580225

[network.log](https://github.com/ppy/osu/files/9856731/network.log)
[performance.log](https://github.com/ppy/osu/files/9856733/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9856734/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9856735/updater.log)
[database.log](https://github.com/ppy/osu/files/9856736/database.log)

**Comment by peppy** [comment] 2022-10-25 03:18
There was another issue recently which I can't find, but which is probably related to this (a user reported that the adjusted beatmap rate would not return quickly enough when exiting gameplay/results and returning to song select). If anyone's able to find that issue and link it here it'd be appreciated.

**Comment by LamGC** [comment] 2022-10-25 03:29
> There was another issue recently which I can't find, but which is probably related to this (a user reported that the adjusted beatmap rate would not return quickly enough when exiting gameplay/results and returning to song select). If anyone's able to find that issue and link it here it'd be appreciated.

Issue #20475

**Comment by ShizuVoice** [comment] 2022-12-31 15:35
It seems that there are users who have this issue.

Based on the original poster's video, it seems that his scoreboard doesn't have fully loaded profile images which I assume he had unstable internet but he said it happens in some beatmaps.

In my case this happens everything and I said on #21970 that it happens on unstable WiFi/internet and I've explained my situation there. If I can be able to reproduce this bug in a different system connected to a slow internet then this seems to be a bug in doing requests in-game that becomes "stuck" and going haywire. I will give an update once I did it.

**Comment by ShizuVoice** [comment] 2023-01-11 16:28
After setting up osu!lazer on my Linux desktop PC and then connecting it to my smartphone internet via USB tether and making my phone to connect to 2G, I can confirm that I encounter the two bugs (quick retry and DT) and I also have reproduce additional 3 bugs during the attempt. This might be a problem with people who have unstable DSL or mobile internet that wants to play the game. I can also reproduce it on my recently formatted MacBook Air with the same smartphone with 2G internet.

I have also streamed it doing the process alongside with shortened video for the quick rundown of the bugs.

Videos
[VOD](https://youtu.be/6r8jfZOmzt0)
[Shortened video](https://youtu.be/PQDgkbjaz68)

Logs
[database.log](https://github.com/ppy/osu/files/10394078/database.log)
[input.log](https://github.com/ppy/osu/files/10394079/input.log)
[network.log](https://github.com/ppy/osu/files/10394080/network.log)
[performance.log](https://github.com/ppy/osu/files/10394081/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10394082/runtime.log)

**Comment by bdach** [comment] 2024-04-25 08:48
I'm gonna cross my fingers and hope that this issue is the same one https://github.com/ppy/osu/pull/25253 was supposed to fix, and close it as such.

**Closed by bdach** 2024-04-25 08:48 UTC
Labels: area:gameplay, area:mods, priority:1
