### ISSUE TITLE
Light on sidebar in option menu doesn't follow correctly when going down.

### ISSUE THREAD

**Issue by KingBranBran** [ppy/osu#9529] opened 2020-07-11 14:50 UTC
**Describe the bug:** 
When clicking different option categories going up, it works totally fine. But when going down, the light seems to go one category too high.
**Screenshots or videos showing encountered issue:** 
https://i.imgur.com/GNssWPq.gif
**osu!lazer version:** 
2020.710.0
**Logs:**

[performance-draw.log](https://github.com/ppy/osu/files/4906945/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4906946/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4906947/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4906948/updater.log)
[database.log](https://github.com/ppy/osu/files/4906949/database.log)
[network.log](https://github.com/ppy/osu/files/4906950/network.log)
[performance.log](https://github.com/ppy/osu/files/4906951/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/4906952/performance-audio.log)

**Comment by bdach** [comment] 2020-07-11 15:45
Duplicate of #9196

**Closed** 2020-07-11 15:45 UTC
