### ISSUE TITLE
Latency when clicking with tablet

### ISSUE THREAD

**Issue by slipsy** [ppy/osu#2701] opened 2018-05-31 23:46 UTC
I'm one of those weird people who tap circles with the tablet itself and fall back on keys only when streaming. Lazer takes a good half a second to register clicks when I click this way, That's all :T

**Comment by swoolcock** [comment] 2018-06-01 00:11
I play the same way, and I haven't noticed this.
Can you give some more info on your setup?  Computer, OS, tablet brand/model, etc.

**Comment by peppy** [comment] 2018-06-01 01:04
This is the same issue with touchscreens currently. Duplicate of ppy/osu-framework#1514. Clicks are only handled after a drag begins due to a delay placed by windows.

**Closed by peppy** 2018-06-01 01:04 UTC
