### ISSUE TITLE
Osu crashes when can't connect network.

### ISSUE THREAD

**Issue by Mahua233** [ppy/osu#3715] opened 2018-11-13 06:18 UTC
**Describe your problem:** Osu will crash if open without network connection.

**osu!lazer version: ** 2018.1108.0 

**Logs:** : 
>11/13/2018 06:15:08: ----------------------------------------------------------
11/13/2018 06:15:08: Network Log for mahua (LogLevel: Verbose)
11/13/2018 06:15:08: osu 2018.1108.0.0
11/13/2018 06:15:08: Running on Unix 18.2.0.0, 8 cores
11/13/2018 06:15:08: ----------------------------------------------------------
11/13/2018 06:15:08: Request to https://api.github.com/repos/ppy/osu/releases/latest failed with System.Net.Http.HttpRequestException: Device not configured ---> System.Net.Sockets.SocketException: Device not configured
11/13/2018 06:15:08: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
11/13/2018 06:15:08: --- End of inner exception stack trace ---
11/13/2018 06:15:08: at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
11/13/2018 06:15:08: at System.Threading.Tasks.ValueTask`1.get_Result()
11/13/2018 06:15:08: at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
11/13/2018 06:15:08: at System.Threading.Tasks.ValueTask`1.get_Result()
11/13/2018 06:15:08: at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
11/13/2018 06:15:08: at System.Threading.Tasks.ValueTask`1.get_Result()
11/13/2018 06:15:08: at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
11/13/2018 06:15:08: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
11/13/2018 06:15:08: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
11/13/2018 06:15:08: at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
11/13/2018 06:15:08: at osu.Framework.IO.Network.WebRequest.internalPerform().
11/13/2018 06:15:08: Processing response from https://api.github.com/repos/ppy/osu/releases/latest failed with System.ArgumentNullException: Value cannot be null.
11/13/2018 06:15:08: Parameter name: value
11/13/2018 06:15:08: at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
11/13/2018 06:15:08: at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
11/13/2018 06:15:08: at osu.Framework.IO.Network.JsonWebRequest`1.ProcessResponse()
11/13/2018 06:15:08: at osu.Framework.IO.Network.WebRequest.Complete(Exception e).

**Computer Specifications:** macOS 14.01

**Comment by lolita-is-godddd** [comment] 2018-11-13 09:02
it looks related #3572, doesn't it?

**Comment by peppy** [comment] 2018-11-13 09:11
Closing as duplicate of #3572

**Closed by peppy** 2018-11-13 09:11 UTC
