### ISSUE TITLE
Multitouch support for mobile devices

### ISSUE THREAD

**Issue by Pneu666** [ppy/osu#12230] opened 2021-03-30 20:48 UTC
**Describe the new feature:** like in osu!droid, you could use multiple fingers on touch, more recommended for streams

**Proposal designs of the feature:** an customizable area on the screen for multitouch feature on mobile

**Comment by frenzibyte** [comment] 2021-03-30 20:58
Duplicate of #4201

**Closed by frenzibyte** 2021-03-30 20:58 UTC
