### ISSUE TITLE
Beatmap never finishes (see attachments)

### ISSUE THREAD

**Issue by Thesola10** [ppy/osu#12226] opened 2021-03-30 10:57 UTC
**Describe the bug:** 
When playing through [this specific beatmap](https://osu.ppy.sh/beatmapsets/519505#osu/1906276), once I reach the end, the end screen never appears, and the score isn't saved if I quit manually

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7287268/112978056-21316680-9157-11eb-8523-50c70069c7df.mp4

**osu!lazer version:** 
2021.323.0 AppImage, but the bug started showing up as early as 2021.219.0

**Logs:**
[logs.tar.gz](https://github.com/ppy/osu/files/6228476/logs.tar.gz)

**Comment by Thesola10** [comment] 2021-03-30 11:05
Prior to 219, I could finish the beatmap just fine, which leads me to think this might be a regression. No other beat map does this, and auto play finishes just fine

**Comment by bdach** [comment] 2021-03-30 11:49
This was mentioned in #4095. For what it's worth I could not reproduce.

**Comment by frenzibyte** [comment] 2021-03-30 11:51
Can reproduce with NF and missing almost every object

**Comment by Thesola10** [comment] 2021-03-30 12:03
@bdach Did you ever miss a _slider_ trying to reproduce this? Sliders on this beat map have crazy combos for some reason so this might be related

**Comment by bdach** [comment] 2021-03-30 12:05
I tested both autoplay and no fail (without any input whatsoever) to no avail. Maybe missing "almost" every object matters, whatever *that* is supposed to mean.

**Comment by Firmatorenio** [comment] 2021-03-31 02:45
I can definitely reproduce this sometimes by spamming sliders and not quite failing them:
https://www.youtube.com/watch?v=COV3jHBe0nA
https://www.youtube.com/watch?v=ZQDT6BfEIzA

I originally made these and posted them on a different issue but it seems like it never got fixed with that issue.

**Closed** 2021-03-31 06:48 UTC
Labels: area:gameplay, ruleset:osu!mania
