### ISSUE TITLE
Infinitely looped beatmap import message

### ISSUE THREAD

**Issue by Stehsaer** [ppy/osu#27745] opened 2024-03-28 12:14 UTC
### Type

Game behaviour

### Bug description

Behavior: 
- almost infinitely reporting about beatmap importing
- click "exit" gives a fullscreen warning of "beatmap initializing (0%)"
- my word can't perfectly describe but the video and screenshot attached says it all
- I definitely have no idea how this is triggered, and I can't reproduce either, but I can provide my previous steps:

1. Open Microsoft Edge and click on a beatmap download link from osu.ppy.sh
2. Waited a moment while the dialog that ask me whether to directly open the file or to save to some location. AFAIK, the explorer downloads the file in the background and eventually when I decided to save or to open it's already done downloading.
3. Clicked on save and the browser saved the beatmap file to my desktop.
4. I did some homework, unrelated
5. Notice osu!lazer is somehow opened, and the bug behavior appears

### Screenshots or videos

https://github.com/ppy/osu/assets/54050160/231a2962-03b1-453f-a7ba-a26fa7a6d905
![image](https://github.com/ppy/osu/assets/54050160/3aeae2af-f8c3-41ed-9cce-97bc947a45fd)

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14789282/compressed-logs.zip)

**Comment by Stehsaer** [comment] 2024-03-28 12:20
> # More Info
> I checked the log and the reason seemed very simple:
> 
> ```
> 2024-03-28 11:58:42 [error]: Could not delete original file after import (2070848 Sasuke Haraguchi feat. Kasane Teto - HITO Mania.osz)
> 2024-03-28 11:58:42 [error]: System.IO.IOException: The process cannot access the file 'C:\Users\Lenovo\Desktop\2070848 Sasuke Haraguchi feat. Kasane Teto - HITO Mania.osz' because it is being used by another process.
> ```
> 
> osu! failed to delete the beatmap file because the file was used by another process and the bug was triggered.

This log is located in <the zipped file>/1711627012.runtime.log

**Comment by Stehsaer** [comment] 2024-03-28 12:22
Exact code:
https://github.com/ppy/osu/blob/21201e616d5a67b0868651a913b93ae9b5fb1077/osu.Game/Database/RealmArchiveModelImporter.cs#L209

**Comment by bdach** [comment] 2024-03-28 12:31
please don't quadruple post, the edit function exists.

the log message mentioned is not causing the loop because if you read the code then it doesn't retry on that error or anything, it just logs it and moves on. i just checked that experimentally.

whatever this is probably has to do with the shell integration / microsoft edge.

**Comment by Stehsaer** [comment] 2024-03-28 12:34
Sorry for multiple posts
Will this get fixed, though it's a kinda rare scenario?

**Comment by bdach** [comment] 2024-03-28 12:36
if we can reproduce, then maybe

**Comment by 64ArthurAraujo** [comment] 2024-03-28 13:20
I although i dont use windows so i cant reproduce it, i remember some people having their Desktop folder linked to OneDrive for some reason. If you are doing that maybe thats it since you mentioned that you had the beatmap file saved to your desktop

**Comment by tybug** [comment] 2024-03-28 17:57
@ppy/team-client not sure there's anything actionable here, but an infinite loop is pretty unfortunate. Maybe one of you has an idea.

**Comment by Stehsaer** [comment] 2024-03-28 18:22
> I although i dont use windows so i cant reproduce it, i remember some people having their Desktop folder linked to OneDrive for some reason. If you are doing that maybe thats it since you mentioned that you had the beatmap file saved to your desktop

No I dont have onedrive installed in my PC. I'm looking for ways to reproduce.

**Comment by peppy** [comment] 2024-03-29 07:11
It's pretty clear that something went wrong externally here, with edge likely getting in a loop and queueing up 1,512 import jobs. One could argue that we should be deduping imports better – right now, the same file can be queued for import multiple times due to it being a fire-and-forget operation:

https://github.com/ppy/osu/blob/6adf0ac01ebbdd82c19617fe5e96f291c58365c7/osu.Game/Database/RealmArchiveModelImporter.cs#L116

Probably not immediately actionable, and maybe not worth tracking as an issue unless it comes up for more users.

**Comment by Stehsaer** [comment] 2024-03-29 08:18
> It's pretty clear that something went wrong externally here, with edge likely getting in a loop and queueing up 1,512 import jobs. One could argue that we should be deduping imports better – right now, the same file can be queued for import multiple times due to it being a fire-and-forget operation:
> 
> https://github.com/ppy/osu/blob/6adf0ac01ebbdd82c19617fe5e96f291c58365c7/osu.Game/Database/RealmArchiveModelImporter.cs#L116
> 
> Probably not immediately actionable, and maybe not worth tracking as an issue unless it comes up for more users.

More than 1k5, actually like 10k or so. Osu some how cleared the message count when the total count exceeded 1k5. And I agree something went wrong on the microsoft edge side instead of in osu!. I'll try manually locking the beatmap file and check if osu! behaves the same

**Comment by tybug** [comment] 2024-03-29 16:30
Ok, let's close this for now. Thanks again for reporting @Stehsaer. If you happen to figure out an exact reproduction, let us know — it might be helpful for future users running into the same issue.

**Closed by tybug** 2024-03-29 16:30 UTC
Labels: area:import
