### ISSUE TITLE
Changing osu-lazer folder fails, client.db being used by another process

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu#11564] opened 2021-01-22 05:29 UTC
Err msg:
`The process cannot access the file 'C:\Users\TheZj\AppData\Roaming\osu\client.db' because it is being used by another process.`

Stack trace:
```
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at osu.Game.IO.MigratableStorage.<>c__DisplayClass6_0.<DeleteRecursive>b__0() in [...]\osu\osu.Game\IO\MigratableStorage.cs:line 70
   at osu.Game.IO.MigratableStorage.AttemptOperation(Action action, Int32 attempts) in [...]\osu\osu.Game\IO\MigratableStorage.cs:line 119
   at osu.Game.IO.MigratableStorage.DeleteRecursive(DirectoryInfo target, Boolean topLevelExcludes) in [...]\osu\osu.Game\IO\MigratableStorage.cs:line 70
   at osu.Game.IO.MigratableStorage.Migrate(Storage newStorage) in [...]\osu\osu.Game\IO\MigratableStorage.cs:line 60
   at osu.Game.IO.OsuStorage.Migrate(Storage newStorage) in [...]\osu\osu.Game\IO\OsuStorage.cs:line 105
   at osu.Game.OsuGameBase.Migrate(String path) in [...]\osu\osu.Game\OsuGameBase.cs:line 475
   at osu.Game.Overlays.Settings.Sections.Maintenance.MigrationRunScreen.PerformMigration() in [...]\osu\osu.Game\Overlays\Settings\Sections\Maintenance\MigrationRunScreen.cs:line 97
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
The only differences I've noticed between the previous and new folders, are the `cache` folder, `client.db-shm` and `client.db-wal` not being present in the new one, so I'm guessing it fails at the very end when trying to remove client.db from the old folder?

While lazer is still running 'Open osu! folder` will open the new folder, and new beatmaps will be imported into it.
But after restarting, it will be back to the previous folder.

Both release 2021.118.1 and latest master, tried 3 times on each with this same result every time.

**Comment by smoogipoo** [comment] 2021-01-22 05:34
Not much we can do here. Duplicate of https://github.com/ppy/osu/issues/9746. Keep trying or wait until we've moved to a better DB system.

**Closed by smoogipoo** 2021-01-22 05:34 UTC
