### ISSUE TITLE
Objects in the edge areas are not fully displayed when screen scaling is set to gameplay

### ISSUE THREAD

**Issue by KinseyD** [ppy/osu#31261] opened 2024-12-24 11:52 UTC
### Type

cosmetic

### Bug description

My screen resolution is 2560x1440, and I'm in full-screen mode

When I apply a 75% gameplay screen scaling (`horizontally` and `vertically`), I am experiencing an issue where objects at the edges of the game area are being clipped and not fully rendered

### Settings
![setting-screenshot](https://github.com/user-attachments/assets/61672a0f-4807-4309-824c-a8ed4d40427e)

### Screenshot
![osu-screenshot](https://github.com/user-attachments/assets/a3c9b131-ab51-4034-9325-4f9634a0d88c)

This issue is prevalent

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18239233/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-12-24 12:10
Duplicate of https://github.com/ppy/osu/issues/5353

**Closed by frenzibyte** 2024-12-24 12:10 UTC
