### ISSUE TITLE
Multiple spin rate counters visible for consecutive spinners

### ISSUE THREAD

**Issue by Squiddu** [ppy/osu#7023] opened 2019-11-30 19:56 UTC
(This isn't really a BUG, just a visual that looks off.)

**Describe the bug:** 
When a beatmap has multiple spinners next to each other, the SPM (Spins Per Minute) counter on the next spinner starts to appear.

**Screenshots or videos showing encountered issue:** 
![osu_2019-11-30_14-48-32](https://user-images.githubusercontent.com/55364481/69905421-376fbc80-1381-11ea-8da8-761664ce1117.png)

**osu!lazer version:** 
2019.1128.0

**Logs:** 
As this is not technically a bug, no logs can be found.

**Comment by LastExceed** [comment] 2019-11-30 23:24
Is this for overlapping or consecutive spinners? If overlapping then I'd say its fine like this but if consecutive then we should try to prevent this

**Comment by bdach** [comment] 2019-11-30 23:26
I don't really think it even matters myself, shouldn't show up twice even if overlapping.

**Comment by peppy** [comment] 2019-12-05 02:17
The timing of the display should probably be altered to avoid this. Alternatively we decide to move the SPM counter to be part of the HUD, and have it displayed as a singleton, but this would require some thinking and careful consideration (ie. are there going to be other such counters going forward, to the point it requires this?)

**Comment by smoogipoo** [comment] 2019-12-05 03:16
Doesn't need to be part of the HUD, can be part of OsuPlayfield.

**Comment by peppy** [comment] 2019-12-05 04:28
Let's keep it at the spinner level.

**Comment by smoogipoo** [comment] 2019-12-05 04:42
please suggest how to solve this issue if you keep it at the spinner level.

**Comment by peppy** [comment] 2019-12-05 04:42
As above, the timings should be changed to avoid overlap for now, if this is an issue in ranked beatmaps.

**Comment by frenzibyte** [comment] 2021-03-07 22:34
This looks to be improved with https://github.com/ppy/osu/pull/11626, not sure whether should be closed though.

**Comment by peppy** [comment] 2021-03-08 14:44
@frenzibyte for reference, which beatmap are you testing with? i can't seem to find a reference to the one used in the OP here.

**Comment by frenzibyte** [comment] 2021-03-09 03:35
Just brought up that given that the issue title is talking about consecutive spinners, not sure what the beatmap the OP was using here, and whether the spinners are consecutive or overlapping each other for their case.

**Comment by peppy** [comment] 2021-03-09 03:42
So you haven't visually tested this? Generally if you say "looks to have improved", you would have checked it using something, so I was wanting to know how/where you confirmed this.

**Comment by frenzibyte** [comment] 2021-03-09 03:45
Ah, I see. My bad with the choice of words there.

**Comment by peppy** [comment] 2021-03-09 04:25
@Squiddu (or anyone else) could you please link the beatmap you were seeing this issue with?

**Comment by Joehuu** [comment] 2021-03-09 05:35
OP beatmap is https://osu.ppy.sh/beatmapsets/413117#osu/1036170 (Hard diff) at same spot 23%. Seems to be fixed, so closing.

https://user-images.githubusercontent.com/35318437/110423593-32a2b980-8056-11eb-97a6-037039f4b474.mp4

**Closed by Joehuu** 2021-03-09 05:35 UTC
Labels: area:gameplay, ruleset:osu!, type:UI
