### ISSUE TITLE
Messages in multiplayer chat go out of bound if a word is too long

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu#26819] opened 2024-01-30 16:15 UTC
### Type

Cosmetic

### Bug description

I encountered this issue earlier in multiplayer because i kept miss-pressing Enter during gameplay, which sent my inputs in the multiplayer chat. Not sure if this is actual intended behavior, but since no issue like this was opened i prefer just in case.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/16978299/156ab982-f6a0-4f0b-b833-e95b578a1f8c)

### Version

2024.130.2

### Logs

Logs not relevant to the issue

**Comment by Adrriii** [comment] 2024-01-30 16:57
I'm guessing it's the same behavior as stable, however we had the whole screen width so it wasn't that much of an issue.

Right now it's not too bad either, but idk maybe a language such as German could prove me wrong 😄

**Comment by bdach** [comment] 2024-01-30 17:23
Essentially duplicate of https://github.com/ppy/osu-framework/issues/5007

**Closed by bdach** 2024-01-30 17:23 UTC
