### ISSUE TITLE
Using the perfect mod and missing a circle makes the loading screen freak out 

### ISSUE THREAD

**Issue by q-d-v** [ppy/osu#30687] opened 2024-11-16 10:18 UTC
### Type

Game behaviour

### Bug description

If the Perfect mod is enabled, missing will cause the game to switch to a black screen for a split second then show a glitched version of the loading screen. (Tested on all gamemodes, same result)

### Screenshots or videos

https://github.com/user-attachments/assets/66766040-aaa4-47c3-bb3d-b46e7c506dd7

### Version

2024.1115.1 (Android)

### Logs

[archive.zip](https://github.com/user-attachments/files/17784254/archive.zip)

**Comment by smoogipoo** [comment] 2024-11-16 10:38
Duplicate of https://github.com/ppy/osu/issues/30657

**Closed by smoogipoo** 2024-11-16 10:38 UTC
