### ISSUE TITLE
Mania performance calculation discrepancy to osu! stable

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu#11696] opened 2021-02-07 17:45 UTC
**Describe the bug:**
The mania performance calculation result does not quite match the values from osu! stable.
Haven't encountered an example that shows a difference in map stars so difficulty calculation might not be the cause.

**Screenshots:** 

- Example 1: Difference of only ~0.9 but with rounding its at 299 on lazer but 300 on stable
  - Score card showing 300pp
![score-card-1](https://media.discordapp.net/attachments/579428622964621324/808025886821318676/unknown.png)
  - Exact score pp showing 300.11pp
![score-listing-1](https://media.discordapp.net/attachments/579428622964621324/808025953027620894/unknown.png)
  - osu-tools showing 299.227pp
![osu-tools-1](https://media.discordapp.net/attachments/579428622964621324/808026376061845584/unknown.png)

- Example 2: Considerable difference of ~7 making it 298 on lazer but 305 on stable
  - Score card showing 305pp
![score-card-2](https://media.discordapp.net/attachments/579428622964621324/808026634824974396/unknown.png)
  - Exact score pp showing 305.21pp
![score-listing-2](https://media.discordapp.net/attachments/579428622964621324/808026730983063582/unknown.png)
  - osu-tools showing 298.21pp
![osu-tools-2](https://media.discordapp.net/attachments/579428622964621324/808028646920683570/unknown.png)

**osu!lazer version:** 
2021.129.0

**Comment by smoogipoo** [comment] 2021-02-08 02:06
These are likely to be caused by slightly different SR values, because the deployed diffcalc is actually inaccurate to stable. For example in that second score, stable is 4.49*, web is 4.53*, and lazer is 4.49*. Lazer's more accurate here.

Closing as not an issue, just needs a new diffcalc deploy.

**Closed by smoogipoo** 2021-02-08 02:06 UTC
