### ISSUE TITLE
Osu!lazer big icon bug

### ISSUE THREAD

**Issue by jujuba46** [ppy/osu#5307] opened 2019-07-09 13:45 UTC
**Describe the bug:** Big icon on windows volume mixer audio.

**Screenshots or videos showing encountered issue:** 
![Screenshot_4](https://user-images.githubusercontent.com/52706742/60893011-7c5e4f80-a236-11e9-8b7e-8edb13e3e046.jpg)

**osu!lazer version:** Lazer 2019.704.0

**Logs:**

**Comment by Joehuu** [comment] 2019-07-09 13:47
Duplicate of #2424.

**Closed** 2019-07-09 13:49 UTC
