### ISSUE TITLE
Exiting skin editor too fast will cause layout to be saved as nothing

### ISSUE THREAD

**Issue by BadAimWeeb** [ppy/osu#26532] opened 2024-01-14 21:31 UTC
### Type

Game behaviour

### Bug description

If user exit too fast (for example by misclicking and hit Escape) while skin layout isn't loaded yet, osu! will save as empty layout, overwriting any changes made before (if using custom layout), or create a new empty layout (if using default layout).

### Screenshots or videos

https://github.com/ppy/osu/assets/29724654/23286141-0121-4378-b1b2-cf1836c2a5c2

### Version

2024.114.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/13933160/compressed-logs.zip)

**Comment by Gabixel** [comment] 2024-01-14 23:19
This looks like a duplicate of https://github.com/ppy/osu/issues/26092

**Closed** 2024-01-14 23:20 UTC
