### ISSUE TITLE
Triangles Intro Sequence: Game Mode Sprites' edges are blurry on higher resolution monitor

### ISSUE THREAD

**Issue by Lopolin-LP** [ppy/osu#21363] opened 2022-11-21 15:58 UTC
### Type

Cosmetic

### Bug description

I have a 2560 x 1440 Monitor. During the Triangles Intro Sequence, as soon as the four Game Mode Sprites "get big", their edges are blurry. It seems like they are Pictures instead of Vector Graphics, if I guess correctly.

### Screenshots or videos

(You have too look at them in fullscreen, and not only the preview)
(the third image is the """problematic""" one)
smooth sharp text ![smooth sharp text](https://user-images.githubusercontent.com/82715586/203096978-93e7641f-b58e-4c67-9c79-611da3a9ab86.png)

more smooth sharp text and Triangles ![more smooth sharp text and Triangles](https://user-images.githubusercontent.com/82715586/203097078-0c108cd0-bebf-43d8-80d1-0a38e3702b7b.png)

**NOT smooth circles** ![NOT smooth circles](https://user-images.githubusercontent.com/82715586/203097152-36593675-ab59-4042-861b-8a06096b5dbf.png)

smooth osu! logo ![smooth osu! logo](https://user-images.githubusercontent.com/82715586/203097221-02be5f35-6d0c-402c-8a48-cd98f1a53c57.png)

### Version

osu! 2022.1117.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10057954/database.log)
[input.log](https://github.com/ppy/osu/files/10057955/input.log)
[network.log](https://github.com/ppy/osu/files/10057956/network.log)
[performance.log](https://github.com/ppy/osu/files/10057957/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10057959/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10057961/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10057962/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10057963/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10057964/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10057965/updater.log)

**Comment by Lopolin-LP** [comment] 2022-11-23 15:07
@peppy Maybe generate Sprites (depending on screen resolution) from drawable icons...? Or is using anything related to drawables leading to these issues?

Just a thought that crossed my mind

**Comment by Joehuu** [comment] 2022-11-30 21:46
Duplicate of https://github.com/ppy/osu/issues/8116

**Closed by Joehuu** 2022-11-30 21:46 UTC
Labels: type:UX, priority:3, area:intro
