### ISSUE TITLE
Exit confirmation appears when closing the window

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6383] opened 2019-10-03 17:57 UTC
I'm mean using the X while in windowed mode or when closing the window while it's minimized.

**Comment by bdach** [comment] 2019-10-03 18:02
For windowed mode this is intended behaviour (see description of #6175). Not sure how the minimized case should be handled.

**Comment by LittleEndu** [comment] 2019-10-03 18:07
![](https://i.imgur.com/jc487uC.png)

Why is the exit button treated differently then? Shouldn't they all forgo the confirmation because the user clicked on them. I can see how pressing alt+F4 might not be confirmation enough, but clicking on something should be all the confirmation needed.

**Comment by bdach** [comment] 2019-10-03 18:12
I imagine the primary reason is to avoid accidentally closing the game when misclicking the notifications button in the header. While doing so is not *impossible*

**Comment by peppy** [comment] 2019-10-04 02:02
Confirmation is shown when exit is triggered via external means while something in-game is still happening. This is intended behaviour for now.

**Closed by peppy** 2019-10-04 02:02 UTC
Labels: ux
