### ISSUE TITLE
Raw Input For Me Just Brakes My Game

### ISSUE THREAD

**Issue by SupaOven** [ppy/osu#1989] opened 2018-01-29 00:03 UTC
I go to settings, enable raw input for increased sensitivity, and it just breaks, my cursor goes everywhere and it feels like i just set my sensitivity to 1000%. I'm on a tablet.

**Comment by peppy** [comment] 2018-01-29 00:04
Duplicate of #1301

**Closed by peppy** 2018-01-29 00:04 UTC
