### ISSUE TITLE
Manual input for numeric values within settings. [Mobile-iOS/Android]

### ISSUE THREAD

**Issue by Aquamarine-92** [ppy/osu#11963] opened 2021-03-04 18:29 UTC
**Idea goes here:**
Set a numeric value via the keyboard for settings that require a value.

**Proposal designs of the feature:** 
ANYTHING. As long as the desired result is fulfilled. This change can exclusively be temporary until a more elaborate proposed design is introduced.

**Misc info.**
OK. Grab a standard sized phone and install the game. Next, proceed to to aquire your optimal input (your offset). 
Many factors influence the timing and execution of a note. Your offset is not going to be set to the default of 0. 

Now, try to set your offset to -50.
Yeah, just try it. Set to -50 or anything even approx to this value.

One thing you'd notice is that you will hardly ever see the current (ms) as you as scrolling its range because your finger will block the number being configured. 

The other obvious issue is trying to fine-tune such a small wheel (UI), even when the games UI is at it's maximum value.

You know, I love this game. I've been playing it for 10 years or so. I would also love to transition to mobile, and I would also like to provide feedback from a mobile's perspective once I'm more effcient with the app. 

But- how can this begin, when I can't even begin the actual game? Let's reference the above example- you somehow manage to set the offset to the value of -50ms. You then attempt to test it out, and apparently the offset needs to be tuned a little more. You'll then have to keep repeating, and repeating this "offset" process, until (for me, at least)- you close the game with intention to try again another time when time is more accessible. 

Think about this non-personal as well. How are you going to obtain a large amount of debug info throughout various devices, etc.,- when there are a small amount mobile users that play the game on a consistent basis (due to complications in playing the game in respect towards this main topic)?

This should be top priority to implement. It shouldn't require much time to do so, either.

Thanks for reading this. i hope to see a change in the near future. Mobile devices are reaching the point to where more attention should be fixated towards, in games, in general.

**Comment by bdach** [comment] 2021-03-04 18:56
First off, this is a duplicate of #8377, so closing on that basis. Please use the search function.

Secondly, I'd ask to reconsider your tone and maybe tone down the entitlement a touch. The current aim is to bring the game to a playable state on desktop first and foremost. Even if that weren't the case, there are way more important issues to tackle (for example some rulesets literally *not being playable* with touchscreen yet - see #4201).

**Closed by bdach** 2021-03-04 18:56 UTC

**Comment by Aquamarine-92** [comment] 2021-03-04 19:17
This isn't a duplicate of #8377. That topic relates to finger movement. This topic asks to set number on your keypad to change a setting value . Where did the disambiguation occur? 

I'll remove the 10 yrs. part. That will remove the entitlement. One sentence to give that impression, meh.

**Comment by bdach** [comment] 2021-03-04 19:21
In your opening post you stated:

> One thing you'd notice is that you will hardly ever see the current (ms) as you as scrolling its range because your finger will block the number being configured.

I fail to see how that is *not* a duplicate.

> One sentence to give that impression...

It's hardly the one sentence. I've read many issue reports and very few had been anywhere close to your diatribe in tone.

Anyway, locking this as I see belaboring this further as pointless.

**Comment by peppy** [comment] 2021-03-05 00:38
Also duplicate of https://github.com/ppy/osu/issues/4224 (which is still open and tracking part of the issue). The other thing you touch on is that the slider controls are too small to sanely operate with touch. This will be improved if/when we get to optimising the UX of the game for mobile.

As osu! is PC-first, this may take some time to get right. I would suggest you connect an external keyboard for the time being, which will give you finer control over UI elements like this.
