### ISSUE TITLE
Incorrect Spinner Behaviour 

### ISSUE THREAD

**Issue by davidovski** [ppy/osu#9887] opened 2020-08-17 10:49 UTC
**Describe the bug:** 
A spinner's spin is registered when the cursor is moved laterally (up and down as well as left and right) instead of around the spinner.

**Screenshots or videos showing encountered issue:** 
unable to record, but can be easily reproduced:
- play a map with a spinner
- move the cursor rapidly left and right under the centre of the spinner
- the spinner will spin and points will be given

**osu!lazer version:** 
2020.814.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/5083734/database.log)
[network.log](https://github.com/ppy/osu/files/5083735/network.log)
[performance.log](https://github.com/ppy/osu/files/5083736/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5083737/runtime.log)

**Comment by frenzibyte** [comment] 2020-08-17 10:50
Duplicate of https://github.com/ppy/osu/issues/8224

**Closed** 2020-08-17 10:50 UTC
