### ISSUE TITLE
Visual settings slider values still show after box is hidden

### ISSUE THREAD

**Issue by KittenzExe** [ppy/osu#23674] opened 2023-05-26 18:07 UTC
### Type

Cosmetic

### Bug description

Number values from visual settings sliders in auto play and or replays stick around after held.

When holding down a slider, moving it off the visual settings box, the box hides but the value of the slider still stays with the cursor although it is hidden.

(Just a random thing I found. Had a look for existing bug reports but couldn't find anything) (Also sorry for the odd title. Best way I could word it)

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/67358250/57a95a31-2270-4bfc-81a7-2fbf21717f9f)

### Version

Lazer 2023.513.0

### Logs

[performance.log](https://github.com/ppy/osu/files/11578650/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11578651/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11578652/updater.log)
[database.log](https://github.com/ppy/osu/files/11578654/database.log)
[input.log](https://github.com/ppy/osu/files/11578656/input.log)
[network.log](https://github.com/ppy/osu/files/11578657/network.log)

**Comment by monochrome22** [comment] 2023-05-26 18:55
Duplicate of https://github.com/ppy/osu/issues/6121.

**Closed** 2023-05-26 18:55 UTC
