### ISSUE TITLE
certain osu!taiko gimmick maps are broken in lazer

### ISSUE THREAD

**Issue by lilaccutie** [ppy/osu#22183] opened 2023-01-13 18:36 UTC
### Type

Game behaviour

### Bug description

I was trying to see how osu!lazer would handle osu!taiko gimmick maps created for osu!stable as I thought they might work with lazer, though looking through multiple maps it seems that most of them are broken or don't play how they're supposed to using AM. (automod). 

### Screenshots or videos

https://user-images.githubusercontent.com/122637294/212392322-2ef24b7e-2265-4896-811c-b52d8e3a9373.mp4 

(https://osu.ppy.sh/beatmapsets/1658064#taiko/3384370) ^ 

https://user-images.githubusercontent.com/122637294/212393350-4798cdfc-979c-4305-af45-5cd97efe1645.mp4

(https://osu.ppy.sh/beatmapsets/821339#taiko/1721561) ^ This one in particular isn't supposed to show any type of notes, you're meant to memorize the map by hitting the bar lines. They go fast enough for a terrible reaction time if the barlines weren't there, but it still sort of ruins the point of the map. 

### Version

2022.1228.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10414435/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10414436/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10414437/updater.log)
[database.log](https://github.com/ppy/osu/files/10414438/database.log)
[input.log](https://github.com/ppy/osu/files/10414439/input.log)
[network.log](https://github.com/ppy/osu/files/10414440/network.log)

**Comment by ekrctb** [comment] 2023-01-20 12:32
Duplicate of #20108

**Closed by ekrctb** 2023-01-20 12:32 UTC
Labels: ruleset:osu!taiko, area:beatmap-parsing
