### ISSUE TITLE
Discord status doesn't show the users selected game mode rank

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#17658] opened 2022-04-05 10:43 UTC
### Type

Other

### Bug description

The discord status for osu lazer when hovering over the logo only show the rank for osu!std even when you have one of the other gamemodes selcted. It also show you playing for example taiko in the corner of the logo while still only showing the standard rank. Could be that it only show the gamemode that the user has put on their profile page. With the stable client it will show the rank for the selected gamemode on discord. I also know this has like the lowest priority ever.

The images were taken at the same time.

### Screenshots or videos

<img width="392" alt="Skärmavbild 2022-04-05 kl  12 37 37" src="https://user-images.githubusercontent.com/81715029/161736432-536117aa-2abd-4579-82ef-6f61475690f4.png">

<img width="1440" alt="Skärmavbild 2022-04-05 kl  12 37 56" src="https://user-images.githubusercontent.com/81715029/161736833-5a4a29fc-1732-4870-b501-beea94931a93.png">
<img width="1060" alt="Skärmavbild 2022-04-05 kl  12 38 25" src="https://user-images.githubusercontent.com/81715029/161736858-7e13c629-d15f-4cb0-b541-70a5bcb2642d.png">

### Version

2022.327.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8417287/database.log)
[network.log](https://github.com/ppy/osu/files/8417288/network.log)
[performance.log](https://github.com/ppy/osu/files/8417289/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8417290/runtime.log)

**Comment by HelloYeew** [comment] 2022-04-05 10:53
Is it duplicate of https://github.com/ppy/osu/issues/12898?

**Closed** 2022-04-05 11:03 UTC
