### ISSUE TITLE
Suggestion: Importing local beatmaps on mobile

### ISSUE THREAD

**Issue by BleepoBleapo** [ppy/osu#6628] opened 2019-10-27 19:14 UTC
**WARNING: This is a suggestion rather than an issue.**

When I was playing osu!lazer on mu Android phone (HTC One M8), I was frustrated that osu!direct made the client crash. I was able to download two beatmaps through osu!direct but that was all.  And as osu!direct mostly crashes the phone, maybe an "import from device" option would be great.

**Comment by bdach** [comment] 2019-10-27 19:19
Duplicate of #5761. Please search before submitting an issue (and this _is_ an issue, since it's in the _Issues_ tab).

The direct crash is a xamarin-side problem, and we're waiting for a fix. It should not be used to justify anything (which is not to say import from local storage won't happen).

**Closed by bdach** 2019-10-27 19:19 UTC
