### ISSUE TITLE
Crash on beatmap download/import.

### ISSUE THREAD

**Issue by amepebbles** [ppy/osu#11454] opened 2021-01-10 16:53 UTC
**Describe the crash:** 
Game crashes while downloading/importing songs. Seemingly at random, as follows:
1. Download the game, clean first launch,
2. Log in,
3. Open the beatmap listing,
4. Download maps.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/kdafob

**osu!lazer version:** 
2021.109.0

**Logs:**
[database.log](https://pastebin.com/raw/hwtu2mEc)
[network.log](https://pastebin.com/raw/35X0K6LH)
[performance.log](https://pastebin.com/raw/VLzwdb6j)
[runtime.log](https://pastebin.com/raw/JAUUYCD3)
Terminal emulator's stdout:
```
Unhandled exception. osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the Transforms of a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
   at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member)
   at osu.Framework.Graphics.Transforms.Transformable.AddTransform(Transform transform, Nullable`1 customTransformID)
   at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis](TThis t, Transform transform)
   at osu.Framework.Graphics.TransformableExtensions.TransformTo[TThis,TValue,TEasing](TThis t, String propertyOrFieldName, TValue newValue, Double duration, TEasing& easing, String grouping)
   at osu.Framework.Graphics.TransformableExtensions.FadeColour[T,TEasing](T drawable, ColourInfo newColour, Double duration, TEasing& easing)
   at osu.Framework.Graphics.TransformableExtensions.FadeColour[T](T drawable, ColourInfo newColour, Double duration, Easing easing)
   at osu.Game.Overlays.BeatmapListing.Panels.PlayButton.playingStateChanged(ValueChangedEvent`1 e) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Overlays/BeatmapListing/Panels/PlayButton.cs:line 121
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Overlays.BeatmapListing.Panels.PlayButton.<playingStateChanged>b__24_1() in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Overlays/BeatmapListing/Panels/PlayButton.cs:line 145
   at osu.Game.Audio.PreviewTrack.Stop() in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Audio/PreviewTrack.cs:line 102
   at osu.Framework.Audio.Track.Track.RaiseCompleted()
   at osu.Framework.Audio.Track.TrackBass.<>c__DisplayClass18_0.<.ctor>b__5(Int32 a, Int32 b, Int32 c, IntPtr d)
Aborted

```

**Computer Specifications:** 
OS: Debian GNU/Linux 10 (buster) x86_64 
Host: VILG1 Lenovo G400s Touch 
Kernel: 4.19.0-13-amd64
Shell: bash 5.0.3 
Resolution: 1366x768 
DE/WM: Xfce / Xfwm4
CPU: Intel i3-3110M (4) @ 2.400GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller 
Memory: 4GB RAM and 4GB swapfile

**Comment by bdach** [comment] 2021-01-10 16:54
Duplicate of #11445

**Closed by bdach** 2021-01-10 16:54 UTC
