### ISSUE TITLE
Map search bug

### ISSUE THREAD

**Issue by vladyslavpron** [ppy/osu#12829] opened 2021-05-15 18:22 UTC
Game version 2021.515.0.
When i trying to search maps like this: stars>6 stars<7 game shows me only maps that are >8, but not less (it works fine without dt mod)
![osu_2021-05-15_21-22-27](https://user-images.githubusercontent.com/71853356/118374249-a9fb4900-b5c3-11eb-983d-118aa2520b09.jpg)

**Comment by Joehuu** [comment] 2021-05-15 18:30
Duplicate of https://github.com/ppy/osu/issues/9678

**Closed by Joehuu** 2021-05-15 18:30 UTC
