### ISSUE TITLE
Cursor sometimes being stretched wide in multiplayer spectate mode

### ISSUE THREAD

**Issue by MitsukaiDokuro** [ppy/osu#29176] opened 2024-07-28 19:37 UTC
### Type

Cosmetic

### Bug description

For an unknown reason, the gameplay cursor inside a replay / spectate frame will become streched. I have seen it being normal shortly before it suddenly became wide. It may have resulted from alt-tabbing out and back into the game.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/c21de93b-2d01-40b3-8514-76fc17035495)

### Version

2024.727.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16405001/compressed-logs.zip)

**Comment by bdach** [comment] 2024-07-29 07:25
I'm sure I've seen this reported before, but the best I can find is https://github.com/ppy/osu/issues/14388 which is not what I remember seeing. But it's kind of a duplicate of that issue too so closing as such.

**Closed by bdach** 2024-07-29 07:25 UTC
