### ISSUE TITLE
Changelog overlay text wrapping is broken

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#18187] opened 2022-05-09 12:59 UTC
### Type

Cosmetic

### Bug description

This occurs when a high UI scale is set. When text it wrapped, it appears to wrap up one line instead of down one. See images for more detail and look at specific entries like osu#18149, osu#18097 and framework#5151

### Screenshots or videos

![0DADC3F6-42BE-48B3-9E97-8BFA08641267](https://user-images.githubusercontent.com/10524728/167414300-83ff36ac-48c6-4e94-83b0-1d6f871d1f36.png)

![AACE5386-2D5B-40CF-BB3D-7E7E2D36395D](https://user-images.githubusercontent.com/10524728/167414399-fed83173-7a69-43d9-a82a-dee1df790850.png)

### Version

v2022.509.0

### Logs

will be up in 10-15min but I don’t think they’re necessary

**Comment by jai-x** [comment] 2022-05-09 13:01
Duplicate of https://github.com/ppy/osu/issues/8580

**Closed by jai-x** 2022-05-09 13:01 UTC
Labels: type:UI, area:overlay-changelog, priority:1
