### ISSUE TITLE
Slider numeric indicators are poorly positioned for touch/pen use

### ISSUE THREAD

**Issue by Deckweiss** [ppy/osu#11747] opened 2021-02-12 02:16 UTC
I am playing on a convertable laptop with a pen. 

The numeric value indicators for sliders are exactly under the finger / pen, so you can never see them. Also they stick for some reason, so you can not move the finger / pen down after grabbing the slider. 

Please put them above the slider and make them stay there, so you can always make them visible while dragging, regardless of your input device or handyness. 

Video: https://gofile.io/d/RPHF82

**Comment by peppy** [comment] 2021-02-12 02:21
I guess this is where we need a handedness setting.

**Comment by Joehuu** [comment] 2021-02-12 02:27
Duplicate of https://github.com/ppy/osu/issues/4224, will add more keywords to that issue.

**Closed by Joehuu** 2021-02-12 02:27 UTC
Labels: type:UX
