### ISSUE TITLE
[macOS] Tablet not working with raw input

### ISSUE THREAD

**Issue by ky13osu** [ppy/osu#4359] opened 2019-02-28 06:37 UTC
Just tried osu!Lazer.

My tablet is an XP Pen Star G640. I connected it to my computer, then turned on raw input. When I tried to use my tablet, nothing happened. The cursor wouldn't move or click.

I tried adjusting sensitivity and switching screen modes, but nothing happened either.

My Mac version is Mojave 10.14.1.

**Comment by smoogipoo** [comment] 2019-02-28 06:48
Duplicate of https://github.com/ppy/osu/issues/3842

**Closed by smoogipoo** 2019-02-28 06:48 UTC
