### ISSUE TITLE
Login doesnt work on android

### ISSUE THREAD

**Issue by SnGmng** [ppy/osu#6323] opened 2019-09-29 21:07 UTC
The login doesnt work on mobile, it just tries to connect forever. If i cancel the login request, i cant try to login again, because the sign in button is broken. On my windows pc it works fine tho.

**Comment by bdach** [comment] 2019-09-29 21:12
Most likely duplicate of #6283.

**Comment by SnGmng** [comment] 2019-09-29 21:17
Yes it is a duplicate. Sorry i didnt notice that.

**Closed** 2019-09-29 21:17 UTC
