### ISSUE TITLE
Unexpected question mark in the score when french language is selected

### ISSUE THREAD

**Issue by BlackJamesYT** [ppy/osu#17739] opened 2022-04-09 12:10 UTC
### Type

Other

### Bug description

**Only when French language is selected**

When I see my score at the end of a beatmap (screenshot) a question mark appear at the mid of the score. 

The problem is viewable when I click on a score in map selection.

### Screenshots or videos

![osu_2022-04-09_13-10-58](https://user-images.githubusercontent.com/19538750/162573240-8949a35e-a784-4ed8-8a54-ff45047bca2d.png)

### Version

2022.409.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8456874/runtime.log)

**Comment by Susko3** [comment] 2022-04-09 12:23
Duplicate of #15135.

**Closed by Susko3** 2022-04-09 12:23 UTC
