### ISSUE TITLE
Score shows misses but there is no missed object

### ISSUE THREAD

**Issue by obvMellow** [ppy/osu#27370] opened 2024-02-24 21:19 UTC
### Type

Game behaviour

### Bug description

The score shows 2 miss but in the replay no object is missed. I don't have the recording but in the gameplay my game lagged and I saw 2 misses appear and my combo broke. However in the replay there are no misses.

### Screenshots or videos

https://drive.google.com/file/d/13rBkXmHgFSbmnnvaUidcjI602Ez7fXz8/view?usp=sharing

### Version

2024.221.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14394446/compressed-logs.zip)

**Comment by bdach** [comment] 2024-02-24 23:31
```
2024-02-24 16:05:57 [verbose]: Playback discrepancy detected (1 of allowed 5): 74,629.5 vs 86,483.5
```

in logs. Duplicate of https://github.com/ppy/osu/issues/26879.

Please post information requested in https://github.com/ppy/osu/issues/26879#issuecomment-1961230312 in the other thread.

**Closed by bdach** 2024-02-24 23:31 UTC
