### ISSUE TITLE
an expection error

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#6815] opened 2019-11-11 20:46 UTC
![ohno](https://user-images.githubusercontent.com/44514667/68619236-b2d00380-0490-11ea-9e14-b123d4ba2ee1.PNG)

osu!lazer verison: 20191106

**Comment by bdach** [comment] 2019-11-11 20:49
Please add hardware specifications, check for logs in `%AppData%/osu/lazer` and attach if present, otherwise please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by genericthing** [comment] 2019-11-11 21:00
hardware:
processor(i3-3240 CPU @ 3.40GHz)
ram(6GB)

[event.zip](https://github.com/ppy/osu/files/3833233/event.zip)

**Comment by bdach** [comment] 2019-11-11 21:07
There's a stack trace in there, albeit a not-very-useful one:
```
Application: osu!.exe
CoreCLR Version: 4.700.19.46205
.NET Core Version: 
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Graphics.Transforms.Transformable.updateTransforms(Double time)
   at osu.Framework.Graphics.Transforms.Transformable.UpdateTransforms()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
(...and so on)
```
Logs should be present, mind rechecking? I initially made a mistake in the path, should be fixed in my original comment now.

**Comment by genericthing** [comment] 2019-11-11 21:15
the logs were not there when i checked after the crash
i opened the game after the crash and then there were logs
i have no idea why there were no logs when i checked after the crash

**Comment by bdach** [comment] 2019-11-11 21:18
Would you mind explaining what were you doing before the crash happened? Does the problem reappear when you do the same thing again?

**Comment by genericthing** [comment] 2019-11-11 21:31
i opened the game then i loaded https://osu.ppy.sh/beatmapsets/780833#osu/1640136. 
i then loaded the ultra diff watched autoplay(no mods) and then i loaded the easy diff (also autoplay,no mods). there were huge and long lag spikes near the end of both maps.
then i went to the main menu, opened up osu!direct, changed map search to "any" then searched up "arcaea".
i think the exception happened when i scrolled down
(this is what i can remember and i will check if it can be replicated)

**Comment by genericthing** [comment] 2019-11-11 21:52
more things that happened when the exception occurred:
results screen lagged when loading, i sorted by favorites after searching for "arcaea" on osu mode and then i downloaded A.SAKA-Yosakura Fubuki(Beomsan mapset)
the exception happened when i scrolled down after download the map above.

the error can not be replicated when i tried it again and i had to download the map again

**Comment by bdach** [comment] 2019-11-11 21:59
Thanks for all of the info. It'll be difficult to pin this down precisely, but from the information collected this seems to indicate there might be some threading issues in the direct overlay, since the exception got thrown when updating a transform within a scheduled task.

**Comment by peppy** [comment] 2020-07-30 14:00
I haven't seen this reproduced, and I'm not sure it's still valid, so closing for now.

**Closed by peppy** 2020-07-30 14:00 UTC
Labels: type:crash
