### ISSUE TITLE
Mod icons not being shown on score screen with a lot of them enabled

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29409] opened 2024-08-13 23:55 UTC
### Type

Cosmetic

### Bug description

When playing around i discovered a small bug/cosmetic issue, where with a lot of mods enabled the mods icons get cut.
In the image below, you can see a total of 13 mods, the score has 17 of them enabled
![image](https://github.com/user-attachments/assets/db264b01-9d05-41dd-9ca8-9c9c75290301)
If a lot of mods are enabled, you could make it so you can scroll from left to right, or cut some of them, add 3 dots (to show basically that there are more mods) and when hovering it you get the list of all mods on text rather than icons.
I doubt anyone will trully complain about this, but its just something i wanted to point out.

### Version

osu! version: Lazer 2024.731.0 (latest)

### Logs

Something is wrong with my game and i cant download maps from map listing and can't export. Ill try reinstalling the game to fix this, but this 'issue' doesn't even need my logs (I-think-it-doesnt-im-slow-in-case-you-didnt-notice)

**Comment by Ladwick** [comment] 2024-08-14 00:10
There is currently a redesign on the works that address this issue, see #22237

**Comment by Stoppedpuma** [comment] 2024-08-14 00:20
Duplicate of #13952

**Closed** 2024-08-14 00:33 UTC
