### ISSUE TITLE
Extend "Back" button 1px down

### ISSUE THREAD

**Issue by MarceloTerra0** [ppy/osu#10143] opened 2020-09-11 18:19 UTC
Whenever I want to back, I throw my cursor to the bottom left of the screen, however the button doesn't reach down there, so extending it would be great.

**Comment by Joehuu** [comment] 2020-09-11 18:28
Similar to/duplicate of https://github.com/ppy/osu/issues/4216. You can turn off raw input for now.

**Closed by Joehuu** 2020-09-11 18:28 UTC
