### ISSUE TITLE
osu!lazer doesn't work in extend mode.

### ISSUE THREAD

**Issue by theven1x** [ppy/osu#3096] opened 2018-07-21 10:42 UTC
osu! works on my pc in extend mode. While osu!lazer shows up a blank screen. I've set it back to Pc screen only and it still shows a black screen. I have to restart my PC to use it again. It *sometimes* can be fixed by going into regular osu! and going back into lazer, but not mostly.

**Comment by LastExceed** [comment] 2018-07-21 14:16
- Only happens when the game is run in fullscreen and focused. doesn't happen in windowed mode or when tabbing out during startup
- Bug can be dodged if you press alt+enter to switch to windowed early enough
- I didn't have to restart my pc to fix it

**Steps to reproduce:**
-----
1. plug and enable a second monitor in extend mode
2. run game
3. switch to fullscreen
4. close game
5. run game again
6. stay fullscreen, don't tab out

(steps 2-4 can be skipped if already in fullscreen)

-----

`AccessViolationException` in `GameThread.Draw` (requires JustMyCode to be disabled)
```[Managed to Native Transition] (Unknown Source:0)
OpenTK.dll!OpenTK.Graphics.ES30.GL.DrawElements(OpenTK.Graphics.ES30.PrimitiveType mode, int count, OpenTK.Graphics.ES30.DrawElementsType type, System.IntPtr indices) (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.OpenGL.Buffers.VertexBuffer<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>.DrawRange(int startIndex, int endIndex) (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.Batches.VertexBatch<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D>.Draw() (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.OpenGL.GLWrapper.FlushCurrentBatch() (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.OpenGL.GLWrapper.setMaskingInfo(osu.Framework.Graphics.OpenGL.MaskingInfo maskingInfo, bool isPushing, bool overwritePreviousScissor) (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.OpenGL.GLWrapper.PopMaskingInfo() (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(System.Action<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D> vertexAction) (Unknown Source:0)
osu.Framework.dll!osu.Framework.Graphics.Containers.CompositeDrawNode.Draw(System.Action<osu.Framework.Graphics.OpenGL.Vertices.TexturedVertex2D> vertexAction) (Unknown Source:0)
osu.Framework.dll!osu.Framework.Platform.GameHost.DrawFrame() (Unknown Source:0)
osu.Framework.dll!osu.Framework.Threading.GameThread.ProcessFrame() (Unknown Source:0)
osu.Framework.dll!osu.Framework.Threading.GameThread.runWork() (Unknown Source:0)
System.Threading.Thread.dll!System.Threading.Thread.ThreadMain_ThreadStart() (Unknown Source:0)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) (Unknown Source:0)
[Native to Managed Transition] (Unknown Source:0)
```
[runtime.log](https://github.com/ppy/osu/files/2216204/runtime.log)

**Comment by FreezyLemon** [comment] 2018-07-21 16:07
Can't reproduce this on master..
(Win 10 x64, dedicated GPU)

**Comment by LastExceed** [comment] 2018-07-21 16:40
I am on Win7 x64, nvidia optimus
Should also mention that I get an error message from intel HD graphics along the lines of "display has been restored after an error"

**Comment by smoogipoo** [comment] 2018-07-23 05:03
Seems to be at least partly (minus AccessViolationException) related to #1679.

**Comment by peppy** [comment] 2021-03-29 07:13
Probably resolved via SDL.

**Closed by peppy** 2021-03-29 07:13 UTC
Labels: framework-fix-required
