### ISSUE TITLE
Taskbar issues when right clicking osu! lazer

### ISSUE THREAD

**Issue by DashhPC** [ppy/osu#29481] opened 2024-08-17 13:59 UTC
### Type

Other

### Bug description

When I attempt to right click osu! lazer in my taskbar, as shown in the video, highlighted icons stay highlighted even after moving the cursor away from them, also when full screening videos, the taskbar is placed on top of said video. This only occurs when right clicking osu! lazer

I literally cannot unpin it from my taskbar.

### Screenshots or videos

https://github.com/user-attachments/assets/9933e156-ae63-4fec-8b55-68bd9ccf4081

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16645150/compressed-logs.zip)

**Comment by DoriteLover** [comment] 2024-08-17 14:01
can be explorer.exe fault, try restarting it

**Comment by DashhPC** [comment] 2024-08-17 14:07
> can be explorer.exe fault, try restarting it

I have done that, I did it before and after multiple times with no change.

**Comment by Joehuu** [comment] 2024-08-17 17:24
Duplicate of https://github.com/ppy/osu/issues/28927

**Closed by Joehuu** 2024-08-17 17:24 UTC
