### ISSUE TITLE
Sorting maps by star rating does not count mods

### ISSUE THREAD

**Issue by ibrab000** [ppy/osu#20374] opened 2022-09-19 02:13 UTC
### Type

Game behaviour

### Bug description

This issue is present across all difficulties and on my Android phone as well. I am using Windows.
Whenever I try to sort maps by star rating, it works like normal.
But if I add any mods, it doesn't sort it properly, and the next map could be lower in SR. It doesn't seem that mods affect it.
I tried to deselect and then reselect "Sort by Difficulty", but that doesn't work either.

### Screenshots or videos

https://user-images.githubusercontent.com/113786106/190939633-124b56c3-48db-49e1-8e8d-0b4883af43cd.mp4

### Version

2022.9.11.0

### Logs

[database.log](https://github.com/ppy/osu/files/9595793/database.log)
[network.log](https://github.com/ppy/osu/files/9595794/network.log)
[performance.log](https://github.com/ppy/osu/files/9595795/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/9595796/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/9595797/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/9595798/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/9595799/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9595800/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9595801/updater.log)

**Comment by Theighlin** [comment] 2022-09-19 04:38
Duplicate of #9678.

**Closed** 2022-09-19 06:18 UTC
