### ISSUE TITLE
Crash after preview music ends in osu direct overlay

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu#11478] opened 2021-01-14 02:58 UTC
**Describe the bug:** When I open the beatmap listing/osu direct overlay, click the play button to preview, then let the song play out to the end of the preview, the client crashes. If I start the play of a second preview, that will work, the crash only occurs at the end of a preview. Additionally, if I close the beatmap listing before the preview ends, there is no crash.

**Screenshots or videos showing encountered issue:** Seems pretty self explanatory, but if you'd like a video I can take one.

**osu!lazer version:** 2021.109.0.0

**Logs:**

The bottom of the runtime log looks most relevant to me (at the bottom of the issue)

network.log:

```
2021-01-14 02:54:04 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2021-01-14 02:54:05 [verbose]: Request to https://osu.ppy.sh/api/v2/me/ successfully completed!
2021-01-14 02:54:05 [verbose]: Performing request osu.Game.Online.API.Requests.GetFriendsRequest
2021-01-14 02:54:05 [verbose]: Request to https://osu.ppy.sh/api/v2/friends successfully completed!
2021-01-14 02:54:05 [verbose]: Spectator client connecting...
2021-01-14 02:54:05 [verbose]: Multiplayer client connecting...
2021-01-14 02:54:06 [verbose]: Multiplayer client connected!
2021-01-14 02:54:06 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2021-01-14 02:54:06 [verbose]: Spectator client connected!
2021-01-14 02:54:06 [verbose]: Performing request osu.Game.Online.API.Requests.GetBeatmapRequest
2021-01-14 02:54:06 [verbose]: Request to https://api.github.com/repos/ppy/osu/releases/latest successfully completed!
2021-01-14 02:54:06 [verbose]: Request to https://osu.ppy.sh/api/v2/users/14613516/osu successfully completed!
2021-01-14 02:54:06 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2021-01-14 02:54:06 [verbose]: Request to https://osu.ppy.sh/api/v2/beatmaps/lookup?id=&checksum=27d9765612170a9517f0a5e8b4613f06&filename=cYsmix%20-%20triangles%20(peppy)%20[peppy].osu failed with System.Net.WebException: NotFound.
2021-01-14 02:54:06 [verbose]: Response was: {"error":""}
2021-01-14 02:54:07 [verbose]: Failing request osu.Game.Online.API.Requests.GetBeatmapRequest (osu.Game.Online.API.APIException
2021-01-14 02:54:07 [verbose]: ---> System.Net.WebException: NotFound
2021-01-14 02:54:07 [verbose]: --- End of inner exception stack trace ---)
2021-01-14 02:54:07 [verbose]: Request to https://osu.ppy.sh/api/v2/users/14613516/taiko successfully completed!
2021-01-14 02:54:07 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2021-01-14 02:54:07 [verbose]: Request to https://osu.ppy.sh/api/v2/users/14613516/fruits successfully completed!
2021-01-14 02:54:07 [verbose]: Performing request osu.Game.Online.API.Requests.GetUserRequest
2021-01-14 02:54:07 [verbose]: Request to https://osu.ppy.sh/api/v2/users/14613516/mania successfully completed!
2021-01-14 02:54:07 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2021-01-14 02:54:07 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2021-01-14 02:54:07 [verbose]: Performing request osu.Game.Online.API.Requests.GetMessagesRequest
2021-01-14 02:54:08 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/channels/5/messages successfully completed!
2021-01-14 02:54:08 [verbose]: Performing request osu.Game.Online.API.Requests.ListChannelsRequest
2021-01-14 02:54:08 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/channels successfully completed!
2021-01-14 02:54:12 [verbose]: Performing request osu.Game.Online.API.Requests.GetSeasonalBackgroundsRequest
2021-01-14 02:54:12 [verbose]: Performing request osu.Game.Online.API.Requests.GetSeasonalBackgroundsRequest
2021-01-14 02:54:12 [verbose]: Request to https://osu.ppy.sh/api/v2/seasonal-backgrounds successfully completed!
2021-01-14 02:54:12 [verbose]: Request to https://osu.ppy.sh/api/v2/seasonal-backgrounds successfully completed!
2021-01-14 02:54:13 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2021-01-14 02:54:13 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2021-01-14 02:54:18 [verbose]: Request to https://a.ppy.sh/14613516 failed with System.Net.WebException: NotFound.
2021-01-14 02:54:18 [verbose]: Request to https://a.ppy.sh/14613516.png failed with System.Net.WebException: NotFound.
2021-01-14 02:54:18 [verbose]: Request to https://a.ppy.sh/14613516.jpg failed with System.Net.WebException: NotFound.
2021-01-14 02:54:20 [verbose]: Performing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest
2021-01-14 02:54:20 [verbose]: Request to https://osu.ppy.sh/api/v2/beatmapsets/search successfully completed!
2021-01-14 02:54:20 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2021-01-14 02:54:20 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1340228/covers/cover@2x.jpg?1609978109 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1328174/covers/cover@2x.jpg?1609755222 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1287105/covers/cover@2x.jpg?1610035615 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1307279/covers/cover@2x.jpg?1609738418 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1074758/covers/cover@2x.jpg?1610220295 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/660618/covers/cover@2x.jpg?1609938946 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1178490/covers/cover@2x.jpg?1609939928 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1310206/covers/cover@2x.jpg?1608554260 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1320376/covers/cover@2x.jpg?1609696069 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1281437/covers/cover@2x.jpg?1609712114 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1245686/covers/cover@2x.jpg?1609623835 successfully completed!
2021-01-14 02:54:21 [verbose]: Request to https://assets.ppy.sh/beatmaps/1060234/covers/cover@2x.jpg?1609631096 successfully completed!
2021-01-14 02:54:23 [verbose]: Request to https://b.ppy.sh/preview/1328174.mp3 successfully completed!
2021-01-14 02:54:26 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2021-01-14 02:54:26 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
2021-01-14 02:54:32 [verbose]: Performing request osu.Game.Online.API.Requests.GetUpdatesRequest
2021-01-14 02:54:32 [verbose]: Request to https://osu.ppy.sh/api/v2/chat/updates successfully completed!
```

runtime.log:
```
2021-01-14 02:54:03 [verbose]: Connected MIDI device: Midi Through Port-0
2021-01-14 02:54:03 [verbose]: BASS Initialized
2021-01-14 02:54:03 [verbose]: BASS Version:               2.4.15.26
2021-01-14 02:54:03 [verbose]: BASS FX Version:            2.4.12.1
2021-01-14 02:54:03 [verbose]: Device:                     Default
2021-01-14 02:54:03 [verbose]: Drive:                      default
2021-01-14 02:54:06 [verbose]: Screen changed → Loader
2021-01-14 02:54:06 [verbose]: Screen changed → Disclaimer
2021-01-14 02:54:12 [verbose]: Screen changed → IntroTriangles
2021-01-14 02:54:12 [verbose]: decoupled ruleset transferred ("" -> "osu!")
2021-01-14 02:54:15 [verbose]: Screen changed → MainMenu
2021-01-14 02:54:17 [verbose]: ButtonSystem's state changed from Initial to TopLevel
2021-01-14 02:54:18 [verbose]: ButtonSystem's state changed from TopLevel to Play
2021-01-14 02:54:23 [verbose]: A PreviewTrack was created without a containing IPreviewTrackOwner. An owner should be added for correct behaviour.
2021-01-14 02:54:32 [verbose]: Unhandled exception has been allowed with 0 more allowable exceptions .
```

**Comment by Joehuu** [comment] 2021-01-14 03:00
Duplicate of https://github.com/ppy/osu/issues/11445. Will be fixed next release.

**Closed by Joehuu** 2021-01-14 03:00 UTC

**Comment by memesnightmares** [comment] 2021-01-14 03:02
Ah, thank you! Apologies, I only checked the first page of issues when looking for a duplicate, I'll look further next time.
