### ISSUE TITLE
Changing the range of displayed bitmaps doesn’t filter maps at song select section.

### ISSUE THREAD

**Issue by rafalbrozek98** [ppy/osu#7600] opened 2020-01-24 11:02 UTC
Computer System: Windows 10.
Starting state: Main menu after launching the game.

Steps:
1.	Click the “settings” button.
2.	Go to the “SONG SELECT” section.
3.	Change “Display beatmaps from” sliders
4.	Close settings.
5.	Click play.
6.	Click solo.
7.	Maps are not filtered.

Results: “Display beatmaps from” doesn’t work properly.
Note: Tried to use different values of both sliders – none of them worked.

Video: https://drive.google.com/file/d/1v_J2iKD55VWPyOf2po0dOqI_JwtuqVI3/view

osu!lazer version: 2020.118.0

**Comment by iiSaLMaN** [comment] 2020-01-24 11:08
Duplicate of https://github.com/ppy/osu/issues/2536

**Closed** 2020-01-24 11:09 UTC
