### ISSUE TITLE
mouse back button doesnt work when cursor is in direct

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8794] opened 2020-04-18 17:51 UTC
Describe the bug: the back button on mouse doesnt work if the cursor is on top of direct (any part of direct). you have to move it to the toolbar or the sides for it to work

Screenshots or videos showing encountered issue: 
[2020-04-19 01-45-15.mkv.zip](https://github.com/ppy/osu/files/4497202/2020-04-19.01-45-15.mkv.zip)

osu!lazer version:2020.418.0 and earlier

Logs: IDk if needed but here
[performance-audio.log](https://github.com/ppy/osu/files/4497210/performance-audio.log)
[performance-update.log](https://github.com/ppy/osu/files/4497211/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/4497212/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4497213/updater.log)
[database.log](https://github.com/ppy/osu/files/4497214/database.log)
[performance.log](https://github.com/ppy/osu/files/4497216/performance.log)
[network.log](https://github.com/ppy/osu/files/4497218/network.log)

**Comment by Joehuu** [comment] 2020-04-18 21:29
Duplicate of https://github.com/ppy/osu/issues/6026

**Closed by Joehuu** 2020-04-18 21:29 UTC
