### ISSUE TITLE
Keyboard driver problem

### ISSUE THREAD

**Issue by KorsenKX** [ppy/osu#4941] opened 2019-06-06 19:34 UTC
I use osu!lazer 2019.606.0 , and my keyboard is in azerty but in osu!lazer it is qwerty . In osu! I don't have this problem

**Comment by peppy** [comment] 2019-06-06 20:32
Duplicate of https://github.com/ppy/osu-framework/issues/252

**Closed by peppy** 2019-06-06 20:32 UTC
