### ISSUE TITLE
the cursor gets out of the screen

### ISSUE THREAD

**Issue by kravque** [ppy/osu#6354] opened 2019-10-01 18:52 UTC
**Describe the bug:** 
moving the cursor far away to the right or left makes it get out of the area of the game's screen
( Only on windowed mode )

**Screenshots or videos showing encountered issue:** 
https://streamable.com/tylcf

**osu!lazer version:** 
2019.930.0
**Logs:** 
Not Needed.

**Comment by Joehuu** [comment] 2019-10-01 18:58
Did you have raw input on?

**Comment by kravque** [comment] 2019-10-01 18:59
Yes.

**Comment by Gabixel** [comment] 2019-10-02 07:12
Duplicate of / similar to https://github.com/ppy/osu-framework/issues/2247 ?

**Comment by smoogipoo** [comment] 2019-10-02 09:15
Closing as duplicate ^^

**Closed by smoogipoo** 2019-10-02 09:15 UTC
Labels: framework fix required, input
