### ISSUE TITLE
Song select should select difficulties that match the SR usually played

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8419] opened 2020-03-23 19:23 UTC
**Describe the new feature:** 
Song select, when a default selection is required (when code calls to select a set, some difficulty of said set is needed to be selected), should select a difficulty so that said difficulty is close to the star rating usually played by the user. 

**Proposal designs of the feature:** 
Stable already does this. All random selections, and when navigating beatmaps with left/right arrows, selected difficulty is based on the star rating you usually play.

**Comment by bdach** [comment] 2020-03-23 19:24
Duplicate of / overlaps with #5172

**Closed by bdach** 2020-03-23 19:24 UTC
