### ISSUE TITLE
osu!lazer crashed upon exiting and threw unknown exception message

### ISSUE THREAD

**Issue by PythonTryHard** [ppy/osu#4502] opened 2019-03-20 17:25 UTC
**Describe your problem:** osu!lazer crashed upon exiting and threw unknown exception while still present in memory

```
Exception Processing Message 0xc0000005
Parameters 0x7ffd01f81c38 0x7ffd01f81c38 0x7ffd01f81c38 0x7ffd01f81c38
```

**Screenshots or videos showing encountered issue:** 

- The crash meesage: http://prntscr.com/n0lnr4
- osu! still in memory (taken at least 15min after initial crash message): http://prntscr.com/n0loki

**osu!lazer version:** 2019.321.0 (Release)

**Logs:** https://drive.google.com/open?id=16MiH8wfMZBRP__9qYkBWQJ8xFfiC_fg8

**Computer Specifications:** Windows 10 64-bit on all latest updates http://prntscr.com/n0lpoc

**Comment by peppy** [comment] 2019-03-21 03:55
Probably need event viewer logs. This looks like a very low level issue.

**Comment by PythonTryHard** [comment] 2019-03-21 06:12
Event Viewer Logs confirmed it is raised by .NET Runtime. Gathering all files and log entries.

**Comment by Joehuu** [comment] 2019-06-28 15:00
Lazer hard crashes on me on `2019.628.1` after a certain time. Can reproduce on two systems by just going through the menus, changing screens, etc. Nothing's on the runtime.log. The OP had a similar error on the event log, so I posted it here.
```
Log Name:      Application
Source:        .NET Runtime
Date:          2019-06-28 07:46:22 AM
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Joey-Desktop
Description:
Application: osu!.exe
CoreCLR Version: 4.6.27207.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFBBAEDD149 (00007FFBBAD20000) with exit code c0000005.

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-06-28T14:46:22.867757400Z" />
    <EventRecordID>68459</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Joey-Desktop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 4.6.27207.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFBBAEDD149 (00007FFBBAD20000) with exit code c0000005.
</Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Application Error
Date:          2019-06-28 07:46:25 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Joey-Desktop
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5c0ab1b7
Faulting module name: coreclr.dll, version: 4.6.27207.3, time stamp: 0x5c0a9582
Exception code: 0xc0000005
Fault offset: 0x00000000001bd149
Faulting process id: 0x3bf8
Faulting application start time: 0x01d52dbe2bd32eef
Faulting application path: C:\Users\Joey\AppData\Local\osulazer\app-2019.628.1\osu!.exe
Faulting module path: C:\Users\Joey\AppData\Local\osulazer\app-2019.628.1\coreclr.dll
Report Id: dbbd1084-8892-4170-93bf-0ad67092b027
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-06-28T14:46:25.584798100Z" />
    <EventRecordID>68460</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Joey-Desktop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5c0ab1b7</Data>
    <Data>coreclr.dll</Data>
    <Data>4.6.27207.3</Data>
    <Data>5c0a9582</Data>
    <Data>c0000005</Data>
    <Data>00000000001bd149</Data>
    <Data>3bf8</Data>
    <Data>01d52dbe2bd32eef</Data>
    <Data>C:\Users\Joey\AppData\Local\osulazer\app-2019.628.1\osu!.exe</Data>
    <Data>C:\Users\Joey\AppData\Local\osulazer\app-2019.628.1\coreclr.dll</Data>
    <Data>dbbd1084-8892-4170-93bf-0ad67092b027</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by peppy** [comment] 2019-06-28 15:05
I'd say this is most likely related to #5179.

**Comment by Joehuu** [comment] 2019-07-01 17:41
@PythonTryHard is this issue still happening?

**Comment by PythonTryHard** [comment] 2019-07-07 15:51
@Joehuu Unsure, I haven't touched osu! these days because irl problems, both stable and lazer.

**Comment by peppy** [comment] 2019-07-08 08:13
Closing for now. Please reopen if you get this again.

**Closed by peppy** 2019-07-08 08:13 UTC

**Comment by EdwinOSU** [comment] 2022-06-20 15:18
It not work IDK what to do please 
![image](https://user-images.githubusercontent.com/107872176/174633433-1eeb265a-7964-49e6-a6cd-73b480418ba6.png)

**Comment by smoogipoo** [comment] 2022-06-21 11:05
This is generally going to be a GPU issue. You'll need to wait until we switch over to Veldrid and use DirectX.
