### ISSUE TITLE
Pausing during gameplay desyncs music and hitcircles (duplicate of https://github.com/ppy/osu/issues/18652)

### ISSUE THREAD

**Issue by XredoFin** [ppy/osu#18661] opened 2022-06-12 21:59 UTC
### Type

Performance

### Bug description

I tested this a couple of times and I'm pretty sure its not my brain.
What I did:
Pause the game midmap
Change frame limiter from options (Vsync <-> Unlimited)
Continue playing

I repeated this a couple times just switching between those limiters at  different parts of the beatmap and it seems to desync.

### Version

2022.612.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/8886877/updater.log)
[database.log](https://github.com/ppy/osu/files/8886878/database.log)
[network.log](https://github.com/ppy/osu/files/8886879/network.log)
[performance.log](https://github.com/ppy/osu/files/8886880/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8886881/runtime.log)

**Comment by XredoFin** [comment] 2022-06-12 22:01
This might also happen by just pausing the game. Forgot to test that

**Comment by frenzibyte** [comment] 2022-06-12 22:08
If it's a duplicate then there's no need to track it. Closing as duplicate of https://github.com/ppy/osu/issues/18652.

**Closed by frenzibyte** 2022-06-12 22:08 UTC
