### ISSUE TITLE
Number on Sliderstart Circle Disapears in Editor after testing Map

### ISSUE THREAD

**Issue by SirBerg** [ppy/osu#22470] opened 2023-01-31 14:56 UTC
### Type

Cosmetic

### Bug description

- Ruleset: Osu
- Area: Editor

## Steps to Reproduce:
1. Map for a while in the Editor
2. Test the Map via the Test-Button
3. Play the full Map
4. Return to the Editor at the End of the Map
5. Some of the Slider Head Numbers should be Missing (See Image)

It seems like the Sliders are affected at random, as they change everytime I try and test the Map. Normal Gameplay does not seem to be affected.

EDIT: It might have to do something with the fact that the Background Image also was not loaded correctly after using the Setup for Maps

### Screenshots or videos

![image](https://user-images.githubusercontent.com/87900036/215794193-2d8bf9ea-3602-4a3e-b1ce-525e2b33a917.png)
![image](https://user-images.githubusercontent.com/87900036/215794298-dd119e8f-39f1-477e-896e-cfc2eae5923e.png)

### Version

2023.123.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10547595/network.log)
[performance.log](https://github.com/ppy/osu/files/10547596/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10547597/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10547598/updater.log)
[database.log](https://github.com/ppy/osu/files/10547599/database.log)
[input.log](https://github.com/ppy/osu/files/10547600/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10547601/legacy-ipc.log)

**Comment by peppy** [comment] 2023-02-01 05:20
Duplicate of #21089, fix is in for next release.

**Closed by peppy** 2023-02-01 05:20 UTC
