### ISSUE TITLE
Typing the at symbol collides with selecting Taiko hotkey

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6338] opened 2019-09-30 18:28 UTC
**Describe the bug:** Typing the at symbol (AltGr+2 on some keyboards, ctrl+2 on some others, etc.) collides with the hotkey that selects the second ruleset. Typing at is required to log in.  

**osu!lazer version:** 2019.930.0

**Comment by bdach** [comment] 2019-09-30 18:34
<kbd>AltGr</kbd> is already known to be quite broken due to opentk not distinguishing it from <kbd>Ctrl</kbd>+<kbd>Alt</kbd>. This has been reported *many* times (#3583, #3326, ppy/osu-framework#1965), and as such this can be probably safely closed.

**Comment by LittleEndu** [comment] 2019-09-30 18:42
The ruleset selecting hotkeys aren't remappable tho. This is bound to cause confusion (it already did for me when downloading beatmaps from direct with mania selected)

**Comment by bdach** [comment] 2019-09-30 18:47
Sure, but this is (in cause, not in symptom) a duplicate of the aforementioned issues. As a stop-gap measure the bindings *could* be temporarily moved until a migration to another input-handling library happens, but that's moving the problem somewhere else (unless there's a really good idea for an absolutely safe binding for all possible keyboard layouts).

**Comment by LittleEndu** [comment] 2019-09-30 19:19
Also, all those issues are about textboxes acting funny and not neatly accepting special characters. #3583 is about an hotkey that is already mapped getting triggered by a different key combination.

This issue would about hotkeys getting triggered while a textbox has a focus. This is going to break IDEs even when switching to SDL.

**Comment by peppy** [comment] 2019-10-02 21:48
Are you able to check how the keys come in on pressing this combination? Do we see Ctrl+Alt+2?

**Comment by bdach** [comment] 2019-10-03 18:40
Even though <kbd>AltGr</kbd>+<kbd>2</kbd> is not a valid key combination for any symbol on the Polish layout, I can demonstrate the same thing, because the <kbd>AltGr</kbd> handling is a Windows (and, by extension, probably everything else's) compatibility feature.

[Here's a video.](https://streamable.com/lcn0f) On the left: debug log output of lazer and keyboard visualization using nohboard (which, by the way, also does not distinguish <kbd>AltGr</kbd> from <kbd>Ctrl</kbd>+<kbd>Alt</kbd>). On the right: webcam footage of me pressing the actual keys of my actual keyboard, which I figured was pretty necessary due to nohboard also showing the keypresses wrong (closest thing I could think of that proves I am actually pressing <kbd>AltGr</kbd>).

**Comment by peppy** [comment] 2019-10-04 01:58
Just wondering if a temporary fix would be to require exact inputs for the global actions (this is a supported mode of operation for `KeyBindingContainer` via `KeyCombinationMatchingMode`). That way Ctrl+Alt+2 would not trigger in this case.

**Comment by smoogipoo** [comment] 2022-02-04 04:31
Should be fixed via https://github.com/ppy/osu-framework/pull/4985

**Closed by smoogipoo** 2022-02-04 04:31 UTC
Labels: type:input
