### ISSUE TITLE
Songs that start with a lowercase letter are put at the end of the TITLE sort style

### ISSUE THREAD

**Issue by SpatialBarrel00** [ppy/osu#27266] opened 2024-02-20 06:47 UTC
### Type

Game behaviour

### Bug description

when song sort is set to title songs are sorted normally unless the title starts with a lowercase letter, they they are sent to the end, appears as A-Z then special characters then after that a-z are put in 

### Screenshots or videos

![Screenshot 2024-02-20 014324](https://github.com/ppy/osu/assets/135704953/53929a34-2219-421a-9b1b-4576fae4b2b0)

### Version

2024.219.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14340493/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-02-20 07:01
Duplicate of https://github.com/ppy/osu/issues/27259

**Closed by Joehuu** 2024-02-20 07:01 UTC
