### ISSUE TITLE
Lazer crash on ChromeOS

### ISSUE THREAD

**Issue by X4X5** [ppy/osu#7076] opened 2019-12-06 03:52 UTC
**Describe the crash:** Okay, so I gave it the same name that I did last time I was reporting a Lazer crash, except this time, of course, I'm referring to the Linux port, and not the Android port this time. And it was switching through skins and testing them on my Chromebook to see how well they worked with Lazer. I clicked on one of my choices, and the game just crashed

**Screenshots or videos showing encountered issue:** Can't screen record on a Chromebook

**osu!lazer version:**  2019.1205.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3930324/runtime.log)

**Computer Specifications:** HP Chromebook
Version 78.0.3904.106 (Official Build) (64-bit)

**Comment by peppy** [comment] 2019-12-06 03:52
Duplicate of https://github.com/ppy/osu/issues/7062.

**Closed by peppy** 2019-12-06 03:52 UTC
