### ISSUE TITLE
Importing skins (and probably other files) no longer works on iOS

### ISSUE THREAD

**Issue by peppy** [ppy/osu#23106] opened 2023-04-03 06:18 UTC
I'm 99% sure this used to work, and doesn't now. The file association still shows up in `Files.app` but after opening with osu! nothing happens in the game.

### Discussed in https://github.com/ppy/osu/discussions/23057

<div type='discussions-op-text'>

<sup>Originally posted by **noelmiller** March 30, 2023</sup>
Hello everyone! 

**Tech Information**
iOS Version: 16.3.1
iPad Air 4th Generation
Osu Lazer Version (Through TestFlight): Version 1.0 (2023.326.1)

**Summary**
I have been struggling with getting skins imported and working on OSU Lazer on my iPad. I reviewed the GitHub issues and it appears that this feature has been supported for quite some time: https://github.com/ppy/osu/issues/7658

I have attempted opening the OSK file with the OSU app through the files menu, dragging it into the window, and nothing seems to get it to load in like it does on my PC. The skin I am trying to use is this one: https://osu.ppy.sh/community/forums/topics/1498493?n=1

Anybody have success with attempting to import skins on iPad? 

Thanks, 

Noel</div>

**Comment by Epic62790** [comment] 2023-04-05 11:56
I am also having the same issue

**Comment by Verbosi7y** [comment] 2023-04-14 21:33
Not sure if it is an iPad issue specifically but I’m also facing the same issue on 2023.403.1 (Sideloaded) for iPad (Air 5th Gen M1). Not sure if it’s an issue on iPhone for 2023.326+, but I am still able to import skins on 2023.207.0 (TestFlight but not in it anymore hence old ver.) on my iPhone. Regression must’ve happened between February and March if issue applies to all Apple devices. 

iPadOS 16.2
iOS 16.2

**Comment by letsgoawaydev** [comment] 2023-05-01 13:42
maybe a way this could be fixed is by having an import button underneath the skins icon that opens the little app open file from device dialog? the one that looks like this: ![image](https://user-images.githubusercontent.com/68365423/235459726-d2f0b646-796a-4b23-b07c-09a5cfe05cff.jpeg)

only problem i can think of is that ios 13 and lower wont be supported because the entire files api thing doesnt work on those versions

**Closed** 2023-06-18 06:14 UTC
Labels: priority:0, platform:iOS
