### ISSUE TITLE
Classic Score Overlay

### ISSUE THREAD

**Issue by RyanLaFauci** [ppy/osu#7446] opened 2020-01-05 14:37 UTC
Apologies if this already exists in the game options somewhere.

**Describe the new feature:** 
User would be able to enable classic score overlay, so that accuracy appears in the top-right and the combo in the bottom left. Also would bring back the classic break screen.
**Proposal designs of the feature:** 
See above.

**Comment by iiSaLMaN** [comment] 2020-01-05 15:14
Duplicate of https://github.com/ppy/osu/issues/4632

**Closed** 2020-01-05 17:48 UTC
