### ISSUE TITLE
Video decoding broken on MacOS

### ISSUE THREAD

**Issue by mtrower** [ppy/osu#9397] opened 2020-06-29 08:04 UTC
**Describe the bug:** 
Video playback (looks to me like decoding) is broken for me on MacOS Mojave.

**Screenshots or videos showing encountered issue:** 
[broken behavior](http://manta.sol.blackshard.net/mtrower/public/srv/broken.mov)
[correct behavior](http://manta.sol.blackshard.net/mtrower/public/srv/correct.mov)

**osu!lazer version:**
2020.602.0+
Works fine on 2020.523.0

Bisection reveals commit 90f9905ed0f142121d8e295f8df4873eee3682e7 or 46a209540e65ee40bbbd4020128e4e01fbb91ce8 as the culprit (46a209540e65ee40bbbd4020128e4e01fbb91ce8 is a skip; it crashes on launch).

Looking at the commit messages and contents, I guess it's related to a framework update, but I wouldn't know where to begin bisecting/testing that.

**Logs:**
(from 2020.629.0)
[logs.zip](https://github.com/ppy/osu/files/4844471/logs.zip)

**Platform**
MacOS 10.14.6 Mojave

**Comment by bdach** [comment] 2020-06-29 08:06
Duplicate of #9314

**Closed by bdach** 2020-06-29 08:06 UTC
