### ISSUE TITLE
Display songs from [star rating] to [star rating] not working

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#6938] opened 2019-11-23 17:02 UTC
**Describe the bug:** 
You can adjust the sliders to select the star ratings, but the song selection screen still shows all downloaded beatmaps, even outside the set star range.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.1122.0
**Logs:**

**Comment by bdach** [comment] 2019-11-23 17:02
Duplicate of #2536.

**Closed by bdach** 2019-11-23 17:02 UTC
