### ISSUE TITLE
Add a way to see how long osu!lazer is running

### ISSUE THREAD

**Issue by ZedME** [ppy/osu#12571] opened 2021-04-25 07:33 UTC
In osu!stable, there has been a timer for how long osu!stable has been running in the main menu.

In order to see how long osu!lazer has been running, it would be nice to see this feature implemented.

**Comment by frenzibyte** [comment] 2021-04-25 07:33
Duplicate of https://github.com/ppy/osu/issues/6303.

**Closed by frenzibyte** 2021-04-25 07:33 UTC
