### ISSUE TITLE
In-game cursor doesn't follow mouse unless clicked (ChromeOS)

### ISSUE THREAD

**Issue by clay53** [ppy/osu#6300] opened 2019-09-28 01:24 UTC
**Describe the bug:**
I'm going to assume this is just a missing feature but I'm not sure. So, when using the latest APK release on ChromeOS, the in-game cursor does not follow the actual mouse. Using raw input does not affect whether this occurs or not.

**Screenshots or videos showing encountered issue:** 
https://www.loom.com/share/d4c8891f4d1f470fb21d54fd76149273

**osu!lazer version:** 
2019.925.0 APK

**Logs:** 
Doesn't seem to necessary but:
[network.log](https://github.com/ppy/osu/files/3664941/network.log)
[runtime.log](https://github.com/ppy/osu/files/3664942/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3664943/performance.log)
[database.log](https://github.com/ppy/osu/files/3664944/database.log)

**Comment by ThatsNiceGuy** [comment] 2019-09-28 01:59
This happens on Android devices as well when using a USB mouse.
(Device tested is the Samsung galaxy s8)

**Comment by columna1** [comment] 2019-09-28 01:59
I would think this is because the APK is meant for android so the way it processes input for clicks is a bit different to account for how touch screens work. I would think that for ChromeOS, compiling and running lazer under the new linux app mode would not only work better but faster as it (I assume) wouldn't have to emulate android. Android is usually run on ARM processors so I assume the apk is compiled for arm ISA vs linux where it would be compiled for x86. But this is all assumption, I don't know for sure. .net core may have a way around it all as I don't think c# is a compiled language, but the runtime may have to be emulated. *shrug*🤷‍♀️I have no idea how APKs are run on cromeOS in the first place

**Comment by bdach** [comment] 2019-09-28 08:30
For the ChromeOS case, from the video it looks like the Android apps are running on it similarly to how Android emulators do, ie. they send touch events on click instead of capturing mouse 1-to-1. There might not be much we can do about that, if we're not getting the mouse positions from the system.

For mouse support for Android-targeting devices, see ppy/osu-framework#2863. That being resolved might resolve that case too as a secondary effect.

**Comment by peppy** [comment] 2019-09-28 11:02
Closing as duplicate of framework issue for mentioned reasons.

**Closed by peppy** 2019-09-28 11:02 UTC
