### ISSUE TITLE
Approach circle appear to be cut of while using screen scaling

### ISSUE THREAD

**Issue by theophile-dev** [ppy/osu#9814] opened 2020-08-08 19:00 UTC
**Describe the bug:** 
Approach circle appears to be cut by the gameplay area when using the option "Screen scaling -  gameplay"

**Screenshots or videos showing encountered issue:** 
![circlecut](https://user-images.githubusercontent.com/58123326/89717685-523b0c00-d9b9-11ea-9d1c-c8a9ac807bd6.PNG)

**Screen scaling settings:**
![screenscaling](https://user-images.githubusercontent.com/58123326/89717735-98906b00-d9b9-11ea-9339-0b80a0d9f5aa.PNG)

**osu!lazer version:** 
2020.806.0

**Comment by Joehuu** [comment] 2020-08-08 19:04
Duplicate of https://github.com/ppy/osu/issues/5353

**Closed by Joehuu** 2020-08-08 19:04 UTC
