### ISSUE TITLE
Skin layout editor can load maps in the wrong mode

### ISSUE THREAD

**Issue by CenTdemeern1** [ppy/osu#17587] opened 2022-04-01 02:30 UTC
### Type

Crash to desktop & unexpected game behavior

### Bug description

The using the skin layout editor, you can load "hidden" maps (such as triangles) or load maps in the wrong mode.
For example, you can load an osu!mania map in osu!taiko (which works), or you can load an osu!catch map in osu!std (crashing the game, or throwing an error)

Repro steps:
Select a mode specific map in the beatmap select
Go to the home screen (main menu)
Select a different mode
Open settings
Open skin layout editor
Press the "Gameplay" button to preview gameplay

### Screenshots or videos

https://youtu.be/_g2G-YVJOfM

![wrongmodefullsize](https://user-images.githubusercontent.com/24682280/161183231-9fc5efe1-e403-465c-9d16-cb436b8b01b6.png)

### Version

2022.327.0-lazer, and local debug on up-to-date master branch

### Logs

[network.log](https://github.com/ppy/osu/files/8394212/network.log)
[performance.log](https://github.com/ppy/osu/files/8394213/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8394214/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8394215/updater.log)
[database.log](https://github.com/ppy/osu/files/8394216/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8394217/legacy-ipc.log)

database.log and legacy-ipc.log were not updated today and are probably not relevant.

**Comment by CenTdemeern1** [comment] 2022-04-01 02:38
I marked this as "Crash to desktop & unexpected game behavior" because it was the closest description and it has in fact crashed to desktop before
Let me know if I should change this

**Comment by peppy** [comment] 2022-04-01 02:39
Going do mark this as a duplicate of https://github.com/ppy/osu/issues/17391, as the fix for that issue will also no doubt fix this one (even though the reproduction steps are slightly different).

**Closed by peppy** 2022-04-01 02:39 UTC
