### ISSUE TITLE
@ character does not display in textboxes until a different character is pressed

### ISSUE THREAD

**Issue by carlobolla** [ppy/osu#3884] opened 2018-12-19 13:24 UTC
**Describe your problem:** Typing the character '@' in any textbox won't make it appear, until another character is typed. It is unknown to me whether the same issue happens with other characters

**Screenshots or videos showing encountered issue:** https://youtu.be/hE1o-iJzGow

**osu!lazer version:** 2018.1214.0

**Logs:** 
[debug.log](https://github.com/ppy/osu/files/2694979/debug.log)
[performance.log](https://github.com/ppy/osu/files/2694980/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2694981/runtime.log)
[database.log](https://github.com/ppy/osu/files/2694982/database.log)

**Comment by peppy** [comment] 2018-12-19 13:52
What keyboard layout are you on?

**Comment by carlobolla** [comment] 2018-12-19 13:53
Italian Layout (qwerty, normal)

**Comment by jorolf** [comment] 2018-12-19 13:57
This is probably a duplicate of https://github.com/ppy/osu-framework/issues/1965

**Comment by carlobolla** [comment] 2018-12-19 13:59
I guess it is, note that the combination for @ in italian keyboards is `Alt Gr + ò`

**Comment by peppy** [comment] 2019-08-27 05:33
Closing as duplicate of https://github.com/ppy/osu-framework/issues/1965.

**Closed by peppy** 2019-08-27 05:33 UTC
Labels: framework fix required, input
