### ISSUE TITLE
Volume change direct bug

### ISSUE THREAD

**Issue by TheEZIC** [ppy/osu#10028] opened 2020-09-01 11:46 UTC
Can't change volume in this area, when holding "alt" + scroll
![image](https://user-images.githubusercontent.com/35061249/91845438-d6ec1380-ec61-11ea-934e-beeb169872ea.png)
osu!lazer 2020.825.0 release

**Comment by frenzibyte-alt** [comment] 2020-09-01 11:52
Duplicate of https://github.com/ppy/osu/issues/9799

**Closed** 2020-09-01 12:05 UTC
