### ISSUE TITLE
osu!lazer (hidden) gameplay doesn't look same as in stable gameplay

### ISSUE THREAD

**Issue by Pallid3** [ppy/osu#28316] opened 2024-05-26 06:26 UTC
### Type

Cosmetic

### Bug description

So when I have tried hidden in lazer, I always noticed that hidden looks somehow different in lazer. It looked dull, dim or like gray. 
I think esspecially the combo numbers look too gray/dimmed.

So I recorded (auto) gameplay on a same map in stable and lazer. After that I synced and compared footage (first yt link at "Screenshots or videos" section) and also used paint.net to compare single timestamp after I screensnipped them basically (second yt link below at "Screenshots or videos" section).

---

Skin: https://drive.google.com/file/d/18OyBSgPcB3ATOioEFX25LOct7F0nVUKO/view?usp=sharing
Beatmap used for comparing: https://osu.ppy.sh/beatmapsets/1282054#osu/2671022
Monitor I am using: AOC 24G2U/BK 144HZ 1ms (It's an IPS monitor)

### Screenshots or videos

Stable vs lazer - comparing hidden gameplay: https://youtu.be/l0CTkiQWpAo

Stable vs lazer - comparing hidden screenshots (of recorded gameplay footage) from same timestamp: https://youtu.be/rL6TeYWyeds

### Version

2024-521.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15446334/compressed-logs.zip)

**Comment by bdach** [comment] 2024-05-27 05:49
presumably duplicate of https://github.com/ppy/osu/issues/26855

**Closed by bdach** 2024-05-27 05:49 UTC
