### ISSUE TITLE
Initial chat messages can be displayed (or received?) twice

### ISSUE THREAD

**Issue by marco-stephan** [ppy/osu#1230] opened 2017-09-09 18:24 UTC
Image: https://puu.sh/xvBK0/3798421c01.png

**Comment by EriiYenn** [comment] 2017-12-27 00:35
## Dear (Almighty) Developers and Contributors

**Is the Issue solved?**
It was opened a while ago an I didn't find any completed **PR** about this topic.
I'll take a look on it, if you confirm, it's still active to solve.
#
*Best regars,*
**EriiYenn**

**Comment by MrTheMake** [comment] 2017-12-27 22:33
I myself didn't experience this issue again, but I also stopped contributing a fair while back.

**Comment by peppy** [comment] 2017-12-28 03:43
It's safe to say this is still an issue as it's still open.

**Comment by EriiYenn** [comment] 2017-12-28 17:40
Code seems without problems now!
I tested send **Direct Mesages** and **#lazer chat** in-game and it was without any problems.

Maybe time will tell more, if we missed something :)

**Comment by peppy** [comment] 2017-12-28 21:36
Can you stop? Please go into read-only mode for the time being else i will have to block you from this repository. You are not being helpful even though you a trying to be.

**Comment by Aergwyn** [comment] 2018-09-13 09:53
I had that happen to me a few minutes ago. Sadly I realized that too late so the only logs I could somehow restore (because it was still open) was the `network.log`.

[network.log](https://github.com/ppy/osu/files/2378712/network.log)

To describe what happened:
I opened the chat and the #lazer-channel wouldn't show anything at all. After nothing happening for a few seconds I switched to #osu where it would take really long to load but I could at least see a loading circle and I just waited. After a while everything appeared and further switching displayed messages in all channels. I realized then that the chat in #lazer was showing twice (as a block that repeats). Sadly I didn't check the others for the same issue.

**Comment by Gabixel** [comment] 2018-09-13 10:16
I had the same issue. If you want, I can try to reproduce it reopening Lazer (because it happened to me when I opened the chat for the the first time)

**Comment by peppy** [comment] 2021-02-18 03:15
Going to close this one as I haven't seen it happening recently.

**Closed by peppy** 2021-02-18 03:15 UTC
Labels: type:online
