### ISSUE TITLE
There no way to navigate back to profile

### ISSUE THREAD

**Issue by kafibu** [ppy/osu#29676] opened 2024-09-01 04:03 UTC
### Type

Game behaviour

### Bug description

When browsing beatmap in someone profile there no easy way to navigate back profile because pressing the "back" button collapse the menu

### Screenshots or videos

https://github.com/user-attachments/assets/252eba10-095e-407b-a97e-f24058a63580

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16827210/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-01 04:31
Duplicate of https://github.com/ppy/osu/issues/5063

**Closed by Joehuu** 2024-09-01 04:31 UTC
