### ISSUE TITLE
Practice Mode

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#5593] opened 2019-08-04 00:55 UTC
**Describe the new feature:** 
I would personally love a "practice mode" where you can pick a certain part of the map to practice(from timestamp to timestamp) and you don't have to play the rest of the map to get to that part. This would obviously be unranked, sort of like how the `NoFail` mod that is currently on osu stable at the moment but it would be a step even further.

**Proposal designs of the feature:** 
After you right click on a map, there is a new button on the menu that pops up saying "Practice". Clicking on it will pull up an overlay displaying the `00:00:00`th timestamp of the map and you would get 2 sliders on one bar allowing you to pick the start and end of the practice and showing a preview of the timestamp above it.

**Comment by Joehuu** [comment] 2019-08-04 00:57
Duplicate of #4175.

**Closed** 2019-08-04 03:04 UTC
