### ISSUE TITLE
osu!lazer can't load beatmaps anymore

### ISSUE THREAD

**Issue by chaguy2457** [ppy/osu#12126] opened 2021-03-21 15:40 UTC
**Describe the bug:** I just updated osu!lazer to 2021.320.0, and this may just be because of how many beatmaps I have, but now lazer can't load the beatmaps. When I get to the beatmap selection screen, I get the following error below and everything starts to freeze. I also noticed that my beatmap collections were gone. The more I try to select another beatmap, the more it lags and gives the same error. However, I went back to 2021.312.0 and everything worked with that. Please let me know if I can provide any more details!

**Screenshots or videos showing encountered issue:** 
<img width="1358" alt="Screen Shot 2021-03-21 at 11 35 01 AM" src="https://user-images.githubusercontent.com/10410173/111910969-f732c280-8a39-11eb-8c0d-b7e414048996.png">

**osu!lazer version:** 2021.320.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6177771/database.log)
[network.log](https://github.com/ppy/osu/files/6177772/network.log)
[performance.log](https://github.com/ppy/osu/files/6177773/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6177775/runtime.log)

**Comment by frenzibyte** [comment] 2021-03-21 15:41
Duplicate of https://github.com/ppy/osu/issues/12094

**Closed by frenzibyte** 2021-03-21 15:41 UTC
