### ISSUE TITLE
Skipping to the end of a replay & rewinding causes the replay to break and freeze

### ISSUE THREAD

**Issue by SpikeyScout** [ppy/osu#9328] opened 2020-06-21 04:39 UTC
**Describe the bug:** When you start an autoplay/replay and skip to the end before the replay catches up and then skip back, when the replay does catch up again it freezes up and does not work until you restart the replay. The video (if the beatmap has one) also appears to stay frozen.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=LDvlbBHfEF4

**osu!lazer version:** 2020.620.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4808914/database.log)
[performance.log](https://github.com/ppy/osu/files/4808915/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4808916/runtime.log)
[network.log](https://github.com/ppy/osu/files/4808919/network.log)

**Comment by InvisibleSymbol** [comment] 2020-06-21 09:15
Duplicate of https://github.com/ppy/osu/issues/7295

**Closed** 2020-06-21 09:35 UTC
