### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by Eyad500** [ppy/osu#7442] opened 2020-01-05 08:13 UTC
**Describe the crash:** 
Whenever I launch the game, it shows an "Osu! has stopped working". 

**Screenshots or videos showing encountered issue:** 
![Screenshot_1057](https://user-images.githubusercontent.com/37656144/71777031-74902580-2fa3-11ea-9e8f-989ce8dc320e.png)

![Screenshot_1058](https://user-images.githubusercontent.com/37656144/71777056-a43f2d80-2fa3-11ea-84e6-8863ebd073e8.png)

**osu!lazer version:** 
2020.104.0

**Logs:** 
Error message logs : 

"Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osu!.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5dcec899
  Fault Module Name:	coreclr.dll
  Fault Module Version:	4.700.19.56402
  Fault Module Timestamp:	5dcdf95d
  Exception Code:	c0000005
  Exception Offset:	00000000001924b9
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3073
  Additional Information 1:	f425
  Additional Information 2:	f425748a82fa3ff1bfb6279a2851b08f
  Additional Information 3:	f2b4
  Additional Information 4:	f2b4c25856d28820d3d3c5857bd480eb"

[runtime.log](https://github.com/ppy/osu/files/4023005/runtime.log)

**Computer Specifications:** 
CPU : Intel Core 2 Duo CPU P8700 2.53 GHz
GPU : Mobile Intel(R) 4 Series Express Chipset Family
RAM : 4gb
OS : Windows 7 64bit

**Comment by huoyaoyuan** [comment] 2020-01-05 08:35
The error code is Access Violation, which is not common in managed applications.
Please restart your system and check if you have latest Windows Update installed. The required system updates can be found at https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-windows .

<s>But your symptom(AV) is different from typical missing updates(cannot find dll). Given your hardware is very old, I'm afraid if there's some issue in your system.</s>

Do you have graphics driver supporting certain version of OpenGL installed? I recall that missing OpenGL driver can cause Access Violation.

**Comment by Wieku** [comment] 2020-01-05 10:35
Doesn't lazer use compatibility OpenGL 3? runtime.log says the system supports OpenGL 2.1, which is too low. It's a outdated hardware problem.

**Comment by iiSaLMaN** [comment] 2020-01-05 10:40
Correct. osu!lazer supports at the very least OpenGL 3, see https://github.com/ppy/osu/issues/4235#issuecomment-462597828. Can be closed.

**Comment by huoyaoyuan** [comment] 2020-01-05 10:41
We may prompt some useful message, such as a message box with "no supported OpenGL driver".

**Comment by smoogipoo** [comment] 2020-01-06 05:03
There are ways we will be supporting this in the future. Options include:
1. ANGLE / SwiftShader
2. Veldrid (and eventually DX 9/10)

Message boxes are generally not x-plat, and not something we want to be doing. Closing as duplicate of #4235.

**Closed by smoogipoo** 2020-01-06 05:03 UTC
