### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by LamaanVFX** [ppy/osu#13787] opened 2021-07-05 11:26 UTC
Lazer client crashes on launch after the "welcome to Os" the U cuts out aswell and it just goes to a black screen and crashes

**Comment by frenzibyte** [comment] 2021-07-05 11:27
![CleanShot 2021-07-05 at 14 27 33](https://user-images.githubusercontent.com/22781491/124464667-2547d280-dd9d-11eb-962d-3578a80a694b.png)

**Comment by LamaanVFX** [comment] 2021-07-05 12:39
[runtime.log](https://github.com/ppy/osu/files/6764216/runtime.log)
[session.log](https://github.com/ppy/osu/files/6764218/session.log)
[update_success.log](https://github.com/ppy/osu/files/6764219/update_success.log)
here u go

**Comment by frenzibyte** [comment] 2021-07-05 12:40
Is that from the path mentioned above (`%AppData%/osu/logs`)? The logs you posted look to be from osu!stable.

**Comment by LamaanVFX** [comment] 2021-07-05 12:51
oh yeah my bad
[database.log](https://github.com/ppy/osu/files/6764289/database.log)
[performance.log](https://github.com/ppy/osu/files/6764290/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6764291/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6764292/updater.log)

**Comment by peppy** [comment] 2021-07-05 15:04
There's no crash in your logs. Check windows event viewer for more details.

**Comment by LamaanVFX** [comment] 2021-07-06 08:45
nothing on the event viewer either, the problem is, if I launch lazer normally it launches and works, the minute I click on lazer, it goes black screen and crashes

**Comment by peppy** [comment] 2021-07-06 08:46
Sounds like a driver issue. Please try updating your GPU drivers and closing anything which might be trying to display an overlay on the game.

**Comment by bdach** [comment] 2021-07-06 08:48
Duplicate of #6391, as well.

**Closed** 2021-07-06 08:48 UTC
Labels: missing details, type:reliability
