### ISSUE TITLE
Click counter doesn't stop on breaks

### ISSUE THREAD

**Issue by byDave251** [ppy/osu#6102] opened 2019-09-13 19:53 UTC
**Describe the bug:** 
Click counter is active on breaks while at stable it isn't.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/JQvRKbSXwzY?t=30

**osu!lazer version:** 
2019.913.0 

**Logs:** 
not necessary

**Comment by ticotaco72** [comment] 2019-09-13 20:21
I remember there was already an issue for this and this is intended. Idk

**Comment by Joehuu** [comment] 2019-09-13 20:30
Duplicate of #2707.

**Comment by peppy** [comment] 2019-09-14 03:21
Functionality to stop it counting is already present, just not implemented completely.

**Closed by peppy** 2019-09-14 03:21 UTC
