### ISSUE TITLE
Mouse not moving MacOS Catalina

### ISSUE THREAD

**Issue by Vannzilla** [ppy/osu#9726] opened 2020-07-30 13:40 UTC
I went to play osu for the first time today and it worked perfectly fine the first time I opened it but the second time I opened it it's not getting any input from my mouse whatsoever I tried reinstalling and I might try with a controller in a second but I haven't gotten anything to work.

Edit: and my mouse is working perfectly fine everywhere else

**Comment by frenzibyte** [comment] 2020-07-30 13:43
Most likely a duplicate of https://github.com/ppy/osu/issues/3495 but need to confirm that first, are you running in fullscreen mode? if so, switch to windowed and see if it works.

**Comment by peppy** [comment] 2020-07-30 13:43
Please run windowed for now (opt-enter to switch).

**Closed** 2020-07-30 13:43 UTC
