### ISSUE TITLE
Unable to open .osk and .osz files in osu!lazer on android

### ISSUE THREAD

**Issue by username1947** [ppy/osu#11586] opened 2021-01-24 08:51 UTC
I'm not sure if this is a bug or not, but I have tried to open .osk and .osz files but when i open them it says can't open file. I have allowed osu!lazer to access storage thinking that would solve it but no, I'm just unable to open any .osk or .osz files.

**Comment by bdach** [comment] 2021-01-24 08:54
Please attach a screenshot of the error you're seeing.

**Comment by Game4all** [comment] 2021-01-24 08:55
Do you mind specifying in which app you're encountering this ? As an aside you can import the osk and osz files by sharing them to osu!

**Comment by username1947** [comment] 2021-01-25 09:46
I'm getting these issues in osu!lazer on android

**Comment by username1947** [comment] 2021-01-25 09:47
> Please attach a screenshot of the error you're seeing.

![Screenshot_20210125-094715_Chrome](https://user-images.githubusercontent.com/77916644/105689191-5a98ec00-5ef2-11eb-9d69-5e88620fc7e4.jpg)

It says can't open file

**Comment by bdach** [comment] 2021-01-25 10:01
Duplicate of #11558, pretty sure.

**Closed by bdach** 2021-01-25 10:01 UTC
Labels: missing details

**Comment by Susko3** [comment] 2021-01-26 08:56
@username1947 If you select multiple files (from different sources), and then share them, you will be able to share them to osu!

You can also use your phone's file manager app to open those files.
