### ISSUE TITLE
osu!lazer won't open

### ISSUE THREAD

**Issue by LuiselprraYT** [ppy/osu#10113] opened 2020-09-10 00:34 UTC
**Describe the crash:** After I intall osu!lazer I try to open The Game only appear the loading cursor. After this nothing happens.

**Screenshots or videos showing encountered issue:** 
![Captura de pantalla (10)](https://user-images.githubusercontent.com/71048615/92667893-16e67280-f2c2-11ea-932f-ad5a8490156b.png)
![Captura de pantalla (11)](https://user-images.githubusercontent.com/71048615/92667901-1bab2680-f2c2-11ea-9b6a-3f280aa01f47.png)

**osu!lazer version:** 2020.903.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/5198478/runtime.log)

**Computer Specifications:** Processor: Inter(R) Pentiun(R) Dual CPU T2370 @ 1.73GHz RAM: 2 GB GPU: Mobile Intel(R) 965 Express Chipset Family

**Comment by peppy** [comment] 2020-09-10 00:57
have you followed the instructions in the READNE for old windows versions?

**Comment by LuiselprraYT** [comment] 2020-09-10 00:59
where are READNE?
And I use Windows 10 Pro

**Comment by peppy** [comment] 2020-09-10 01:16
Have you checked what is using100% of your CPU?

**Comment by LuiselprraYT** [comment] 2020-09-10 01:20
Task Manager and the Explorer use all my CPU

**Comment by Joehuu** [comment] 2020-09-10 01:29
It seems like your GPU doesn't support OpenGL 3 (i.e. it's too old). Closing as duplicate of https://github.com/ppy/osu/issues/4235 (seems to be really low priority as I can't find an open issue).

**Closed by Joehuu** 2020-09-10 01:29 UTC
