### ISSUE TITLE
Mouseclick + F10 = Crash

### ISSUE THREAD

**Issue by estorio** [ppy/osu#2840] opened 2018-06-19 15:03 UTC
When i hold Leftclick while playing and toggle off the mouse buttons via F10 the game crashes. It happens everytime.
This is just here to report this bugs, since i am not able to do it via the launcher.
I hope this will be patched sometime in the future, i know there is more important stuff to do

**Comment by LittleEndu** [comment] 2018-06-19 15:09
[runtime.log](https://github.com/ppy/osu/files/2115788/runtime.log) of the issue

**Comment by estorio** [comment] 2018-06-21 16:54
https://gist.github.com/estorio/78dd154d65129a97688d9d0370068aa7
This is the runtime.txt of mine.

**Comment by FreezyLemon** [comment] 2018-07-03 07:36
Is this still reproducible? I just tried it on the latest master, and couldn't get it to crash.

**Comment by ekrctb** [comment] 2018-07-03 07:47
This is not reproducible right now due to #2868. The solution of this issue should close this issue as well.

**Closed** 2018-07-11 09:04 UTC
Labels: bug, input
