### ISSUE TITLE
Custom refresh rates aren't respected in lazer

### ISSUE THREAD

**Issue by ilslkyiu** [ppy/osu#18653] opened 2022-06-12 10:25 UTC
### Type

Performance

### Bug description

OSU! LAZER itself turns off the settings for me in NVIDIA CONTROL PANEL and sets it to 60hz

I can't play with 60hz

### Screenshots or videos

https://www.youtube.com/watch?v=VIhAwt-XnTI

### Version

Lazer 2022.612.0 12 June 2022

### Logs

[performance.log](https://github.com/ppy/osu/files/8885642/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8885644/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8885645/updater.log)
[network.log](https://github.com/ppy/osu/files/8885646/network.log)

**Comment by GopoBoi** [comment] 2022-06-12 10:27
duplicate of https://github.com/ppy/osu-framework/issues/4081

**Comment by peppy** [comment] 2022-06-12 10:28
I don't think so? That one is to do with users hacking their drivers to set "overclocked" settings.

**Comment by GopoBoi** [comment] 2022-06-12 10:31
pretty sure that's what is happening in the video (it's how I've "overclocked" my monitor in the past. can't read the language unfortunately to confirm.

**Comment by ilslkyiu** [comment] 2022-06-12 10:33
I just set 75hz in nvidia settings

**Comment by ilslkyiu** [comment] 2022-06-12 10:39
Can you suggest me what to do? or it's not fixable?

**Comment by peppy** [comment] 2022-06-12 10:40
As it seems to be the same issue, there's no immediate fix, but it's something we're aware of and tracking. It will eventually be resolved. You can follow the linked issue for further activity (https://github.com/ppy/osu-framework/issues/4081).

**Closed by peppy** 2022-06-12 10:40 UTC

**Comment by ilslkyiu** [comment] 2022-06-12 10:42
I hope on release everything will be like in stable version
