### ISSUE TITLE
Import from stable to lazer

### ISSUE THREAD

**Issue by dragonGod97677** [ppy/osu#4344] opened 2019-02-27 08:14 UTC
**Describe your problem:** cant import beatmaps from stable, i've been tried to reinstall stable and lazer but i still cant import the beatmaps from stable. and i've also tried 2019.216.0 but still same

**Screenshots or videos showing encountered issue:** 
![untitled](https://user-images.githubusercontent.com/38875906/53475310-3502ce00-3aa2-11e9-932c-6adb349b6139.png)

**osu!lazer version:**  2019.266.0

**Logs:**  https://www.mediafire.com/file/0513zzjsxt1rbc9/logs.zip/file

**Comment by Gabixel** [comment] 2019-02-27 11:04
Probably related to #4043, did you change the default osu!stable path?

**Comment by peppy** [comment] 2019-02-27 16:35
Closing as duplicate of #4043

**Closed by peppy** 2019-02-27 16:35 UTC
