### ISSUE TITLE
osu! will only start up correctly when the window is on focus

### ISSUE THREAD

**Issue by LovelyA72** [ppy/osu#3183] opened 2018-08-06 02:51 UTC
osu!'s game window will freeze itself if the window is not on focus during the warning section of startup.
The music will go on but the graphic will freeze and stay at the warning screen. Clicking the cross button does nothing and when you stop it via task manager, the music will be stuck for a second then osu! will quit(without "see you next time").

**Comment by peppy** [comment] 2018-08-06 02:53
Operating system? Video?

Cannot reproduce here.

**Comment by LovelyA72** [comment] 2018-08-06 03:10
I am running on Windows 10 1803 workstation ver.
It seems like it will randomly happen. It happened to me yesterday, and also just happened to me... 
Right now I am unable to record a video since I also can not reproduce it...
Does log files help? Next time when it happens I will provide the log file and also see if I can get Windows game recorder on.

**Comment by bieel1503** [comment] 2018-08-06 19:50
For me, it only shows a black screen. I've got to re-start a few times to work.
if helps, a video: https://youtu.be/GTUbwqPlqQo.

[runtime.log](https://github.com/ppy/osu/files/2263876/runtime.log)
[performance.log](https://github.com/ppy/osu/files/2263877/performance.log)

**Comment by peppy** [comment] 2018-08-18 00:05
Does it happen if you set lazer to windowed instead?

**Comment by bieel1503** [comment] 2018-08-18 13:58
Oh, it doesn't. It work fine with windowed or borderless mode.

**Comment by PlanetGamingGG** [comment] 2019-02-18 08:26
Hey, I'm having a similar issue but with Window's 10 Focus Assist (RELATED).
I just resetted my system and when I run osu!, the game froze and sometimes shows a black screen which requires me to force close it. When switching windows and installing beatmaps, it will froze for a while too.
See my topic about this here : https://osu.ppy.sh/community/forums/topics/869576
I first suspect it was the compatibility mode which causes the problem but then I noticed that the Windows 10 Focus Assist keeps turning on and off when osu! launches so I decided to disable it and it works like a charm 👍 .

**Comment by peppy** [comment] 2019-02-19 04:19
Depends if the original poster can confirm their issue is also focus assist related or not.

**Comment by LovelyA72** [comment] 2019-02-20 00:18
Based on @PlanetGamingGG's forum post, it looks like he was reporting an osu!stable issue here. But I'll also test it on my lazer.

**Comment by PlanetGamingGG** [comment] 2019-02-20 07:17
Oh, the original post was meant for osu!lazer??
Yes @LovelyA72 , My issue is with osu!stable and I could not verify that the issue can be reproduced on other system as unfortunately I don't have another Windows 10 System.
Can someone help me verify:

1. Is my issue related to this one or should I just create a new issue
2. Can my issue be reproduced on other system?

Thanks

**Comment by PlanetGamingGG** [comment] 2019-02-22 10:16
Any updates on this?

**Comment by jai-x** [comment] 2019-02-22 11:51
@PlanetGamingGG This Github repo is ***only*** for development of `osu!lazer`. Issues for stable have to be taken elsewhere.

**Comment by PlanetGamingGG** [comment] 2019-02-22 13:53
@jai-x Oh.. I did not notice... sorry for that and where is the stable repo btw?

**Comment by lithiumjs** [comment] 2019-02-22 14:01
@PlanetGamingGG There is none.

**Comment by Aergwyn** [comment] 2019-02-22 14:02
@PlanetGamingGG There is no public osu!stable repo. Issues can be taken to the [forums](https://osu.ppy.sh/community/forums/5).

**Comment by LovelyA72** [comment] 2019-02-22 15:49
Just tested on lazer, it seems like focus assistance does not affect the game from starting up.

**Comment by PlanetGamingGG** [comment] 2019-02-23 02:04
Okay, Thanks for the info and sorry for not noticing this is osu!lazer 😅

**Closed** 2019-02-24 08:37 UTC
Labels: bug, startup crash/issue
