### ISSUE TITLE
i cant install osu lazer

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#4579] opened 2019-04-02 11:33 UTC
**Describe the bug:** i can't install lazer. Win7x32

**Screenshots or videos showing encountered issue:** no

**osu!lazer version:** newest

**Logs:** 
https://pastebin.com/qzK3zWqt

**Comment by qauland** [comment] 2019-04-02 13:19
Windows 32-bit is not supported yet.

**Comment by smoogipoo** [comment] 2019-04-03 03:18
Duplicate of https://github.com/ppy/osu/issues/3984

**Closed by smoogipoo** 2019-04-03 03:18 UTC
