### ISSUE TITLE
Add that ability to adjust difficulty values per hitobject

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6863] opened 2019-11-16 04:45 UTC
Kiddo Kris
-

> Thank you guys making this game better and better.

**Describe the new feature:**
-

> inspired by [Aleph-0](https://osu.ppy.sh/beatmapsets/791900#osu)

In theory, there can only be one circle in the map at the same time.But Preload Circle will show up            before it should appear.If the player hits the lap, he gets missed

>  It should be like the white circle in gif
> ![Pre-spawn](https://user-images.githubusercontent.com/56265123/68988155-234e9a00-086e-11ea-9a96-12ab193cadda.gif)

**Proposal designs of the feature:** 
-

> This is so cool!

- This function is for editor

- Should work like:
Example: At the same time spawning Circle A and B, A is the next circle to hit, B should be hit after 3 seconds.There are circles between A and B that should be hit

- This feature should be able to become Ranked because this feature does not significantly change the game mechanics, and can make the Beatmap more diverse and interesting.

- If it is difficult to read because my English is not good, you can find this idea in the above gif

**Comment by bdach** [comment] 2019-11-16 12:34
I'm not sure what to do with this issue right now to be honest, it's a bit of a mess.

* The beatmap linked doesn't play with full parity with stable due to some parsing failures that should be safely under scope of #750.
* From the description I suppose this might be a request to add support for this sort of placement in the editor?
* Rankability is another issue entirely, since as far as I'm aware ranking criteria are a separate thing from the technical side of the game and therefore anything like this should most likely go through at least a few rounds of community feedback.

**Comment by Kiddo-Kris** [comment] 2019-11-16 14:46
> I'm not sure what to do with this issue right now to be honest, it's a bit of a mess.
> 
> The beatmap linked doesn't play with full parity with stable due to some parsing failures that should be safely under scope of #750.
> From the description I suppose this might be a request to add support for this sort of placement in the editor?
> Rankability is another issue entirely, since as far as I'm aware ranking criteria are a separate thing from the technical side of the game and therefore anything like this should most likely go through at least a few rounds of community feedback.

oh,did i put it in to wrong partition? I create this post for a new mod idea

**Comment by MightyHelper** [comment] 2019-11-16 17:07
I think this has to do with something like also allowing to **dynamically** change **AR** in the timing section.
This is a **MASSIVE** change, or at least I expect it to be because it requires changing the osu! file format to accommodate for the extra value.

**Comment by LeNitrous** [comment] 2019-11-17 00:59
From a mapper's perspective, it can be achieved if the other object had a lower AR compared to the others.

Per-object difficulty settings are planned if I recall it correctly.

**Comment by peppy** [comment] 2019-11-17 01:11
Yes, this is planned.

**Comment by Joehuu** [comment] 2020-09-20 05:06
Duplicate of https://github.com/ppy/osu/issues/4060

**Closed by Joehuu** 2020-09-20 05:06 UTC
Labels: area:beatmap, area:editor, low-priority
