### ISSUE TITLE
Account for mods when filtering by star rating

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu#9678] opened 2020-07-25 23:09 UTC
noticeably, the filter for star rating(both options and search) only accounts for the initial star difficulty which leads to confusion when adding mods as star ratings for songs appear out of filter range

i suggest to use the dynamic difficulty when filtering for star rating so that easier maps bumped into the star rating appear and maps too hard because of a mod will be bumped out

**Comment by peppy** [comment] 2020-07-26 05:02
If you read the PR you can notice this is already planned, but much further off.

**Comment by tybug** [comment] 2022-10-28 21:00
probably a duplicate of #19947 by now given the latter is in milestone

**Comment by peppy** [comment] 2022-10-31 06:16
Let's track with the milestoned issue.

**Closed by peppy** 2022-10-31 06:16 UTC
Labels: area:song-select, area:difficulty, priority:3
