### ISSUE TITLE
wrong button on settings sidebar gets highlighted when clicking them

### ISSUE THREAD

**Issue by LastExceed** [ppy/osu#9356] opened 2020-06-23 18:36 UTC
[Video](https://streamable.com/307dj5)

Repro:
- go to settings
- navigate to any section other than "Debug" by clicking the respective button on the sidebar
- observe how the button above the clicked one gets highlighted instead

The bug doesn't occur when...
- navigating via scroll-wheel or drag instead of clicking the sidebar button
- the previously selected section is below the destination
- the destination is the "Debug" section (somehow that one works fine)

**Comment by Joehuu** [comment] 2020-06-23 18:37
Duplicate of https://github.com/ppy/osu/issues/9196

**Closed by Joehuu** 2020-06-23 18:37 UTC
