### ISSUE TITLE
Suggestion on collection menu at beatmap selection page

### ISSUE THREAD

**Issue by HelloYeew** [ppy/osu#12512] opened 2021-04-21 06:16 UTC
This is a collection menu that when you want to add a song to collection, just right click, go to collection, select on a collection that you want to add beatmap.
![Screen Shot 2564-04-21 at 12 44 38](https://user-images.githubusercontent.com/68165621/115502584-5a18b300-a29f-11eb-8b07-f9e180ce0068.png)

Becuase of when a collection menu is always on right side of main menu box it have a problem.

https://user-images.githubusercontent.com/68165621/115503094-15d9e280-a2a0-11eb-9d73-a16210e9cd4e.mov

**First,** when a cursor is at the right edge of a screen, a main menu box is on a screen but the collection menu is fall of the screen.

![menu-now](https://user-images.githubusercontent.com/68165621/115503558-ce078b00-a2a0-11eb-9d34-db81e45dba9d.jpg)

_My suggestion_
A collection menu must appear on the left side of a main menu box if an area is not enough to show a collection menu like this.
![expected-collection-menu](https://user-images.githubusercontent.com/68165621/115503752-2474c980-a2a1-11eb-8dcd-db158840bb0e.jpg)

**Second,** when a menu is at a bottom of a screen. Like first, a main menu box is not a problem but a collection menu is going down under a screen layout and under osu! icon too.

![menu-bottom-behind-osu-icon](https://user-images.githubusercontent.com/68165621/115504746-9ac5fb80-a2a2-11eb-8c28-ee0fbd66b674.jpg)

_My suggestion_
Just put a collection menu above the screen layout and escape from osu! logo like this.
![expected-corner-menu](https://user-images.githubusercontent.com/68165621/115504913-e1b3f100-a2a2-11eb-98c6-76a583312b6f.jpg)

Ps. This is just my suggestion and sorry for large picture. Thanks for making a good game!

**Comment by frenzibyte** [comment] 2021-04-21 06:17
Duplicate of https://github.com/ppy/osu-framework/issues/3861

**Closed by frenzibyte** 2021-04-21 06:17 UTC
