### ISSUE TITLE
beatmap isnt updating

### ISSUE THREAD

**Issue by IsGris** [ppy/osu#24909] opened 2023-09-24 15:28 UTC
### Type

Cosmetic

### Bug description

when i click update button for beatmap update starts and ends but update button dont disappear
beatmap - https://osu.ppy.sh/beatmapsets/924223#osu/2138408

### Screenshots or videos

https://github.com/ppy/osu/assets/83012795/f2afbda5-86e5-4f29-8cc9-77afff5bed92

### Version

2023.924.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12708889/network.log)
[performance.log](https://github.com/ppy/osu/files/12708890/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12708891/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12708892/updater.log)
[database.log](https://github.com/ppy/osu/files/12708893/database.log)
[input.log](https://github.com/ppy/osu/files/12708894/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12708895/legacy-ipc.log)

**Comment by Joehuu** [comment] 2023-09-24 18:42
Duplicate of https://github.com/ppy/osu/issues/22148

**Closed by Joehuu** 2023-09-24 18:42 UTC
