### ISSUE TITLE
Password box is not recognized as a password on Android

### ISSUE THREAD

**Issue by yesseruser** [ppy/osu#30202] opened 2024-10-10 15:59 UTC
### Type

Game behaviour

### Bug description

On Android, typing in the user login password box doesn't hide the text in keyboards, potentially causing it to get inside auto complete.

My proposal is to make Android keyboards recognize it as a password input.

### Version

2024.1009.1

### Logs

[logs.zip](https://github.com/user-attachments/files/17330985/logs.zip)

**Comment by smoogipoo** [comment] 2024-10-10 16:11
Duplicate of https://github.com/ppy/osu/issues/24041

**Closed by smoogipoo** 2024-10-10 16:11 UTC
