### ISSUE TITLE
Cannot give host in multiplayer on Android

### ISSUE THREAD

**Issue by UnderSampled** [ppy/osu#11692] opened 2021-02-06 14:50 UTC
I was given host of a multiplayer room while playing on Android, and after my round was over, I was not able to give it to the next player. I was told it was just a right-click, but I tried to open the context menu through several gestures (long-press, two finger tap, etc) or by clicking on different elements; I had no way to open it on a touch screen.

Perhaps a menu button could be added to each player, or a drop-down that expands on a single click of their card?

Related: #6975

**Comment by bdach** [comment] 2021-02-06 14:53
Duplicate of https://github.com/ppy/osu-framework/issues/2596 - this is an issue all over the place, not just this particular context menu. Shall be tracked by https://github.com/ppy/osu/issues/4201.

**Closed by bdach** 2021-02-06 14:53 UTC
