### ISSUE TITLE
Changing replay speed moves time even when paused

### ISSUE THREAD

**Issue by BunnyTub** [ppy/osu#30260] opened 2024-10-13 11:20 UTC
### Type

Game behaviour

### Bug description

I found this bug while changing the replay speed.

When adjusting the playback speed during a replay, it should change the speed, without affecting progress. However, when paused, **things still progress forwards, and backwards** _somehow_.

### Screenshots or videos

This video shows the occurrence happening with only the Autoplay mod.
https://github.com/user-attachments/assets/dd7f0fc8-96b3-4eb2-91f4-cf7f735e31c4

This video shows the occurrence happening with my own replay.
https://github.com/user-attachments/assets/9f1102a9-0a20-4fd8-9cea-eb69c866e7d1

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17355336/compressed-logs.zip)

**Comment by BunnyTub** [comment] 2024-10-13 11:35
https://cdn.discordapp.com/attachments/1097318920991559880/1294970667510398996/20241013_063029.mp4?ex=670cf2ea&is=670ba16a&hm=1429fff3f71a268e419229cbedaef4bf352966d0d14ff748780a9f673c06f2a2&
Additional video.

**Comment by BunnyTub** [comment] 2024-10-13 11:36
Here's another instance of this happening
https://github.com/user-attachments/assets/f1c07633-63aa-41b3-bc97-6ba2dcac94bb

**Comment by BunnyTub** [comment] 2024-10-13 11:54
And one more.
https://github.com/user-attachments/assets/1fbd96ca-61da-4758-99e0-7b8029735559

**Comment by dctrng** [comment] 2024-10-14 08:48
> moves time even when paused

Actually, the paused timestamp isn't affected, but the _gameplay state_ is modified to match your desired replay speed. Stepping a frame / a second also follows this behavior. 
I find this approach more intuitive than freezing the game screen.

**Comment by shinmorisawa** [comment] 2024-10-14 12:36
is this intentional? if it isn't, i will make a fix. even if it is, i'll make a fix.

**Comment by bdach** [comment] 2024-10-14 12:46
@shinmorisawa i appreciate your enthusiasm but this should be investigated and understood properly first rather than just "making fixes" blindly

**Comment by BunnyTub** [comment] 2024-10-15 05:57
[dctrng](https://github.com/dctrng) commented
> > moves time even when paused
> 
> Actually, the paused timestamp isn't affected, but the _gameplay state_ is modified to match your desired replay speed. Stepping a frame / a second also follows this behavior. I find this approach more intuitive than freezing the game screen.

It makes sense when moving the time (frame stepping, moving the timeline, etc), but it is a little bit confusing that not moving the frame or time causes the gameplay state to change, but changing the speed that causes the gameplay state to change. (sorry if my English is a little broken, I do not know how to native language properly.)

**Comment by dctrng** [comment] 2024-10-15 09:33
> [BunnyTub](https://github.com/BunnyTub) commented
> but changing the speed that causes the gameplay state to change. 

Notice when turning on Double Time / Half Time, beatmap difficulty settings related to speed (OD, AR, HP) change accordingly?

**Comment by bdach** [comment] 2024-10-15 11:50
As far as I can tell this only happens in two specific circumstances:

- You're on Windows.
- You have a nonzero universal offset applied.

Enter `OffsetCorrectionClock`:

https://github.com/ppy/osu/blob/790f863e0654fd563b57ab699d6be86895e756ab/osu.Game/Screens/Play/OffsetCorrectionClock.cs#L41-L42

`OffsetCorrectionClock` is _rate-compensated_. Which means - I think, because offsets are hell - that you're basically saying, for instance, "I want inputs to be 250ms *behind* the actual audio". But that 250ms is *absolute real time* 250ms because that's what these offsets are for - they're to compensate for absolute real time *latency*. But what that *also* means is that if you want to be 250ms real time behind the audio, and the rate of the track playback changes, *so must the current gameplay position*. Again, I _think_.

But that to me raises a question: *why is universal offset involved for replay playback at all*? I'm not sure I'm qualified to answer that question. @ppy/team-client are you able to help out here?

**Comment by shinmorisawa** [comment] 2024-10-18 12:56
> As far as I can tell this only happens in two specific circumstances:
> 
>     * You're on Windows.
> 
>     * You have a nonzero universal offset applied.
> 
> 
> Enter `OffsetCorrectionClock`:
> 
> https://github.com/ppy/osu/blob/790f863e0654fd563b57ab699d6be86895e756ab/osu.Game/Screens/Play/OffsetCorrectionClock.cs#L41-L42
> 
> `OffsetCorrectionClock` is _rate-compensated_. Which means - I think, because offsets are hell - that you're basically saying, for instance, "I want inputs to be 250ms _behind_ the actual audio". But that 250ms is _absolute real time_ 250ms because that's what these offsets are for - they're to compensate for absolute real time _latency_. But what that _also_ means is that if you want to be 250ms real time behind the audio, and the rate of the track playback changes, _so must the current gameplay position_. Again, I _think_.
> 
> But that to me raises a question: _why is universal offset involved for replay playback at all_? I'm not sure I'm qualified to answer that question. @ppy/team-client are you able to help out here?

I'm on Linux, and I was able to successfully replicate this.

**Comment by bdach** [comment] 2024-10-18 12:58
> I'm on Linux, and I was able to successfully replicate this.

...and? so did i, with nonzero universal offset. what is your universal offset?

**Comment by shinmorisawa** [comment] 2024-10-18 13:18
> > I'm on Linux, and I was able to successfully replicate this.
> 
> ...and? so did i, with nonzero universal offset. what is your universal offset?

I always use zero ms. Even with bluetooth headphones, zero ms offset.

**Comment by bdach** [comment] 2024-10-18 13:27
feel free to investigate yourself and come back with results then because i don't know what you're doing to replicate this and you haven't provided this information. i can only reproduce this behaviour in the circumstances i mentioned above.

**Comment by Shavixinio** [comment] 2024-10-20 10:32
> > moves time even when paused
> 
> Actually, the paused timestamp isn't affected, but the _gameplay state_ is modified to match your desired replay speed. Stepping a frame / a second also follows this behavior. I find this approach more intuitive than freezing the game screen.

We already have a function for moving the frames forward/backwards anyways, so I think freezing the game screen would make more sense anyways, if someone wants to move the frames, they can do so manually.
![image](https://github.com/user-attachments/assets/580c58ff-10b4-4323-a532-92dc32afaf83)

**Comment by BunnyTub** [comment] 2024-10-20 12:39
Sorry about that, I accidentally misclicked 🤦‍♂️

**Comment by frenzibyte** [comment] 2024-10-26 03:33
> But that to me raises a question: _why is universal offset involved for replay playback at all_? I'm not sure I'm qualified to answer that question. @ppy/team-client are you able to help out here?

@bdach If I understand your question correctly, universal offset must be applied for replay playback as well, otherwise players who suffer from audio latency will notice a disconnect between the track and the beatmap when watching a replay, pretty much the same as what they would experience in actual gameplay.

**Comment by bdach** [comment] 2024-10-28 06:47
Then unless someone can provide a reproduction scenario that *isn't* related to offsets, this is a wontfix.

**Closed** 2024-11-13 05:28 UTC
Labels: missing details, area:replay, audio
