### ISSUE TITLE
osu!lazer crashes while selecting different game types in different scenarios

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#3562] opened 2018-10-08 17:40 UTC
# Summary

Either the exception handling or the game type selection fail in certain scenarios so that osu!lazer crashes.

## Steps to reproduce (Scenario 1)

- Start osu
- Select Single Player
- Select a Beatmap
- Start the Beatmap
- While loading, select a different game type at the top left corner
 - Hit it twice (quickly)
 - Message will show up that the Exception has been reported
 - Game crashes

## Logs (Scenario 1)

- See https://pastebin.com/6qSvktcm

## Screenshot (Scenario 2)

![Example of client showing scoreboard of completed map where clicking on a game type crashes osu!](https://puu.sh/BHK6k/8ec6bfce6b.png)

## Video

- [Scenario 1 (YouTube)](https://youtu.be/9T7BQJsdgKA)
- [Scenario 2 (YouTube)](https://youtu.be/ZTpZ_spdWOc?t=123)

**Comment by HoLLy-HaCKeR** [comment] 2018-10-08 17:52
Duplicate of #3548?

**Comment by Morodar** [comment] 2018-10-08 17:57
The crash showed in Scenario 2 is duplicated of #3548 
The crash showed in Scenario 1 is a new one I guess?

**Comment by HoLLy-HaCKeR** [comment] 2018-10-08 17:59
Seems to be the same underlying issue, you shouldn't be able to click those buttons at that time.

**Comment by plankp** [comment] 2018-10-17 15:12
this should be fixed in release 2018.1017.0

**Closed** 2018-10-17 15:17 UTC
Labels: pending review, regression
