### ISSUE TITLE
Clicking the text before Lazer starts on iOS will crash

### ISSUE THREAD

**Issue by TeamSoldierNub2** [ppy/osu#4650] opened 2019-04-19 22:19 UTC
https://streamable.com/nzs95 

Version: latest

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TeamSoldierNub2** [comment] 2019-04-19 22:19
Build: Lazer
Platform: iOS 11.3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment] 2019-04-19 23:33
Can’t reproduce. Does this only happen on iOS 11 and below?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dscnnctd** [comment] 2019-04-19 23:34
I managed to reproduce this by spamming the text link simultaneously.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by peppy** [comment] 2019-04-19 23:54
Please turn off the spammy signature or spot posting.

**Comment by nevespt** [comment] 2019-05-08 06:26
So sad, i cant join to the beta 😭

**Comment by Hubza** [comment] 2019-05-08 11:00
Im guessing the text link at the start (the discord link or support link)

if so i cant reproduce this, im guessing its fixed.

**Comment by peppy** [comment] 2019-05-09 01:58
I've tried and can also not crash the game any more.

**Comment by Joehuu** [comment] 2019-06-28 15:21
Nah, the external link overlay doesn’t appear until in main menu. Happens in both iOS and desktop.
![](https://user-images.githubusercontent.com/35318437/60352815-83a37480-997d-11e9-81dd-ecb102ab11b8.png)

**Comment by Joehuu** [comment] 2019-06-28 16:51
Making another issue for iOS crash when opening external links.

**Comment by jorolf** [comment] 2019-06-30 16:51
Maybe we should add a property to links that bypasses the overlay?

**Comment by peppy** [comment] 2019-07-04 05:42
Crash resolved via https://github.com/ppy/osu-framework/pull/2592.

**Closed by peppy** 2019-07-04 05:42 UTC
Labels: iOS, missing details
