### ISSUE TITLE
Editor doesn't save changes when pressing Ctrl+S

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14211] opened 2021-08-10 13:19 UTC
`Ctrl` + `S` doesn't actually save changes but lets you exit the editor without having the `Do you want to save your changes?`-prompt come up. 

**video:** https://youtu.be/NCpGvDrhkKw
**osu!lazer version:** 2021.809.0-lazer

**Comment by bdach** [comment] 2021-08-10 14:53
Potentially related to / duplicate of #12648.

Saving hitobjects should work 100% correctly for all intents and purposes.

**Comment by peppy** [comment] 2021-08-31 08:08
This issue has nothing to do with pressing `Ctrl+S`, but that the difficulty point you are adding in the video is redundant. It is therefore removed. This removal is happening at the point of *decode* (ie. load) which is why the "save changes" prompt is behaving as you describe.

One could argue that these "redundant" control points should still be displayed in the editor as they may have been added for future use. But given the direction we are going with control points (ie. they will be attached to hit objects), I don't foresee this changing.

**Closed by peppy** 2021-08-31 08:08 UTC
Labels: area:editor
