### ISSUE TITLE
Non-logic leaderboard (what?)

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#12793] opened 2021-05-13 21:52 UTC
**Describe the bug:** 
It's about the result screen after completed a map in solo mode.
I know the leaderboard may be non-accurate because the difference between score v1 and score v2.

But that doesn't explain THIS (see screenshots below)!

Picture 1: How I'm first with obliviously less points than other player from the top 50!? (look at the mods, I'm sure not first)
Picture 2: What I'm doing here?
Picture 3: Nothing wrong here.

**Screenshots:**
Picture 1 (1st):
![osu_2021-05-13_23-37-27](https://user-images.githubusercontent.com/57914482/118191978-bbb6e200-b445-11eb-8530-05730e78bf8a.png)

Picture 2 (27th):
![osu_2021-05-13_23-46-51](https://user-images.githubusercontent.com/57914482/118192008-c83b3a80-b445-11eb-966c-8038d9d1a0f0.png)

Picture 3 (last, normal)
![osu_2021-05-13_23-38-57](https://user-images.githubusercontent.com/57914482/118192052-dab57400-b445-11eb-8bb8-d0b5635acfe6.png)

**osu!lazer version:** 
2021.514.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6475261/network.log)
[performance.log](https://github.com/ppy/osu/files/6475262/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6475263/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6475264/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6475265/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6475266/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6475267/updater.log)
[database.log](https://github.com/ppy/osu/files/6475268/database.log)

**Comment by peppy** [comment] 2021-05-14 04:57
I believe this is intentional with how we have things setup right now, but possibly not what an end user is expecting. @smoogipoo I think you're more familiar with if/why this is showing legacy scores specifically in some cases?

**Comment by smoogipoo** [comment] 2021-05-17 09:42
It's sorted by the total score stored in the `ScoreInfo`, not the post-calculated values. Making this a duplicate of https://github.com/ppy/osu/issues/12305

**Closed by smoogipoo** 2021-05-17 09:42 UTC
Labels: area:results, type:UI
