### ISSUE TITLE
Game lags on first frame of music playback

### ISSUE THREAD

**Issue by Banana090** [ppy/osu#30688] opened 2024-11-16 11:07 UTC
### Type

Game behaviour

### Bug description

Sorry in advance for bad English, tried to describe the issue the best I could

When the starting point of beatmap's music file is before or synced with the first note - game noticeably lags, making hitting x300 very hard and annoying. It is noticeable on every single map with the first note being placed right at the beginning of the audio track or before it, like [this one](https://osu.ppy.sh/beatmapsets/962088#osu/2014469) for example.

You can barely see this behavior on video with normal speed and low framerate, but if you would review provided video example frame by frame (or actually play the map yourself) you will clearly see the approach circle of the first note behaves differently (lags at the end)

Since it is consistent between described maps and not present on any map which has audio track starting with few seconds of silence I am quite confident this has something to do with audio playback starting

![image](https://github.com/user-attachments/assets/18ddbe42-a421-4d3a-8b10-36415e0a5aaf)
![image](https://github.com/user-attachments/assets/4848a4f1-3c7e-496a-9925-18133643994c)
![image](https://github.com/user-attachments/assets/fa726fc8-443e-4c6a-a910-ce43410b05ed)

### Screenshots or videos

Video is too big to fit on github, so here is the [Google Drive](https://drive.google.com/file/d/1GO57O4v9h7mms6evULMeNfvayW8HkNL8/view?usp=sharing) link

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17784294/compressed-logs.zip)

**Comment by hwsmm** [comment] 2024-11-16 17:34
Probably duplicate of https://github.com/ppy/osu/issues/22488

**Closed** 2024-11-17 01:04 UTC
