### ISSUE TITLE
please fix the search for songs in osu!direct

### ISSUE THREAD

**Issue by SharaGGa** [ppy/osu#23615] opened 2023-05-21 16:57 UTC
### Type

Game behaviour
### Bug description

since the keyword search in osu!direct in osu!lazer does not work quite properly, some of the songs that I need I have to download manually through the website and add them to the game, while the keyword search in osu!direct in osu!stable works properly and finds what I need

### Screenshots or videos

![osu! Screenshot 2023 05 21 - 23 25 53 72](https://github.com/ppy/osu/assets/116555608/b0b2ff2c-4e34-416c-8cef-de6c123fa4a9)
![osu! Screenshot 2023 05 21 - 23 26 59 12](https://github.com/ppy/osu/assets/116555608/2f6ffafe-d369-44c5-a83d-d47e92835bd6)

![osu! Screenshot 2023 05 21 - 23 26 19 74](https://github.com/ppy/osu/assets/116555608/71cda45a-af0b-44ff-a79d-a3cc3f963c57)

https://github.com/ppy/osu/assets/116555608/ee7d9f48-15b5-4b82-bdc5-439f1fd82aad

https://github.com/ppy/osu/assets/116555608/c4085cd9-54d3-47c9-b73b-2ac7d80d7b9f

https://github.com/ppy/osu/assets/116555608/c8d95696-bbba-4b9a-8b88-a9f60a510b91

### Version

2023.513.0

### Logs

[network.log](https://github.com/ppy/osu/files/11525084/network.log)

**Comment by Joehuu** [comment] 2023-05-21 17:16
Duplicate of https://github.com/ppy/osu/issues/22009

**Closed by Joehuu** 2023-05-21 17:16 UTC
