### ISSUE TITLE
Playfield Borders not accurate

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu#11096] opened 2020-12-04 18:08 UTC
**Describe the bug:** 
On many ranked maps, when having the Playfield Borders enabled alot of Objects appear outside those said borders

**Screenshots or videos showing encountered issue:** 
![osu_2020-12-04_19-05-58](https://user-images.githubusercontent.com/33634370/101198604-ff6e1a00-3663-11eb-9146-be73916fb113.jpg)
![osu_2020-12-04_19-05-59](https://user-images.githubusercontent.com/33634370/101198608-009f4700-3664-11eb-96b7-e6e271e86868.jpg)

**osu!lazer version:** 
2020.1204.0
**Logs:**

[performance.log](https://github.com/ppy/osu/files/5644549/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5644550/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5644553/updater.log)
[database.log](https://github.com/ppy/osu/files/5644554/database.log)

To reproduce: 
1. Set "Playfield border style" to "Full"
2. Open any map (I tried Bubblegum Bitch by StarCastler) and watch

**Comment by bdach** [comment] 2020-12-04 18:15
Duplicate of #10575

**Closed by bdach** 2020-12-04 18:15 UTC
