### ISSUE TITLE
Map details' overlay shows nothing to Guests

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#4568] opened 2019-03-31 22:12 UTC
**Describe the bug:** If a guest tries to show the details of a map, the overlay is blank (everything is default). If it needs a design, this is a good place to talk about that I guess.
(this is **not** a duplicate of [#3635](https://github.com/ppy/osu/issues/3635))

**Screenshots or videos showing encountered issue:** 
![Guests' details map](https://user-images.githubusercontent.com/43073074/55295763-4167a700-5411-11e9-9dda-0b9d4b3dbab1.jpg)

**osu!lazer version:** 2019.330.0.0

**Logs:** N/A

**Comment by peppy** [comment] 2019-04-01 04:01
Not a duplicate of, but definitely overlapping with #3635.

**Comment by Joehuu** [comment] 2019-07-05 05:21
Did adding the loading animation on #5144 resolve this issue?

**Comment by Joehuu** [comment] 2019-10-16 17:40
Going to close this as the loading animation is there. New design implementation will probably polish it more.

**Closed by Joehuu** 2019-10-16 17:40 UTC
Labels: design, online / API, user interface
