### ISSUE TITLE
Lazer statistics report draw FPS without considering possiblity of framerate being limited.

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#29794] opened 2024-09-08 17:00 UTC
### Type

Game behaviour

### Bug description

My game is running at 144 FPS. Then why is the FPS displayed in red? And why is the max draw FPS 1000? 

### Screenshots or videos

![image](https://github.com/user-attachments/assets/88d22abc-99f6-4521-97d9-5969916595ab)
![image](https://github.com/user-attachments/assets/726e060a-97a0-4563-a218-42301097a8a9)

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16923023/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-08 17:40
Duplicate of https://github.com/ppy/osu/issues/19318

**Closed by Joehuu** 2024-09-08 17:40 UTC
