### ISSUE TITLE
Error when installing osu!Lazer

### ISSUE THREAD

**Issue by zenuu-play** [ppy/osu#9077] opened 2020-05-21 07:49 UTC
**Describe the crash:**
Installer error when starting it

*I have this error with all versions of the installer

**Screenshots or videos showing encountered issue:**
https://sun9-38.userapi.com/c857636/v857636853/1f53b0/Hqz2JzGeqek.jpg
https://vk.com/video235374580_456239128

**osu!lazer version:**  osu!lazer installer (2020.515.0)

**Computer Specifications:** 

Windows 10 1909

Xeon E5 2640
16 GB DDR3
SSD 500 GB
GT 440 2GB

**Comment by bdach** [comment] 2020-05-21 16:09
The log file you've pasted in the issue description before was either truncated or contains no information about how the lazer installation went. Please reattach it in full (by drag-and-dropping files into the comment box) if you have not attached the full contents previously.

**Comment by zenuu-play** [comment] 2020-05-22 02:28
I have an empty log file for some reason

Here's the video:
https://vk.com/video235374580_456239128

**Comment by frenzibyte** [comment] 2020-05-22 02:32
out of curiosity, are you running on a 32-bit windows platform?

**Comment by zenuu-play** [comment] 2020-05-22 02:33
no I have a 64 bit system

**Comment by zenuu-play** [comment] 2020-05-22 02:47
> из любопытства, вы работаете на 32-разрядной платформе windows?

нет у меня есть 64-битная система

**Comment by zenuu-play** [comment] 2020-05-22 12:58
> The log file you've pasted in the issue description before was either truncated or contains no information about how the lazer installation went. Please reattach it in full (by drag-and-dropping files into the comment box) if you have not attached the full contents previously.

So what should I do with this error?I don't even save my logs the video shows everything: https://vk.com/video235374580_456239128

**Comment by bdach** [comment] 2020-05-22 17:17
We have nothing to go on so far to try and pinpoint the cause. You could try attaching Windows Event Viewer info by performing the following steps:

1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

Maybe something useful will be visible there, but I'm not hoping for much.

**Comment by zenuu-play** [comment] 2020-05-23 00:07
> Нам пока не на что опереться, чтобы попытаться установить причину. Вы можете попробовать прикрепить информацию о средстве просмотра событий Windows, выполнив следующие действия:
> 
> 1. Введите `Event viewer`в строке поиска Windows (сочетание клавиш:Windows+S) и нажмите Enterили откройте _запуск... _нажмите кнопку ( Windows+ R), Введите `eventvwr`и нажмите Enter.
> 2. __Появится окно просмотра событий. Разверните _Журналы Windows _слева и выберите _приложение _. Это может занять некоторое время, чтобы загрузить.
> 3. В _области действия _щелкните правой кнопкой _мыши сохранить все события как..._, затем выберите место для сохранения.
> 4. Во всплывающем окне _отображение информации _выберите второй вариант, затем установите флажок, чтобы отобразить все доступные языки, а затем _английский (UK) _(US также было бы хорошо).
> 5. Добавьте полученный `.evtx`файл к этой проблеме.
> 
> Может быть, там и будет видно что-то полезное, но я на многое не надеюсь.


[Events.zip](https://github.com/ppy/osu/files/4670813/Events.zip)

**Comment by bdach** [comment] 2020-05-23 09:55
As expected the event viewer log shows no errors. Unfortunately I don't think I can provide any advice as there is no information about what's causing this that I can use to suggest a solution to the problem.

**Comment by zenuu-play** [comment] 2020-05-23 10:10
> As expected the event viewer log shows no errors. Unfortunately I don't think I can provide any advice as there is no information about what's causing this that I can use to suggest a solution to the problem.

But I have a question the installer needs the "AppData" folder? I just happen to have access rights issues with it

**Comment by bdach** [comment] 2020-05-23 10:11
Yes, the access to both `%AppData%` and `%LocalAppData%` user folders is required.

**Comment by zenuu-play** [comment] 2020-05-23 10:27
I sort of poked something and was able to get the installer logs
[logs.txt](https://github.com/ppy/osu/files/4671551/logs.txt)

**Comment by zenuu-play** [comment] 2020-05-23 10:28
> I sort of poked something and was able to get the installer logs
> [logs.txt](https://github.com/ppy/osu/files/4671551/logs.txt)

There are some lines in Russian if anything

**Comment by bdach** [comment] 2020-05-23 10:29
It confirms it's a permission issue of a lack of access to directories I mentioned before.

```
System.UnauthorizedAccessException: Отказано в доступе по пути "C:\Users\zenuu\AppData\Local\osulazer".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   в System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   в System.IO.Directory.CreateDirectory(String path)
```

Closing as this is an issue specific to your setup.

**Closed by bdach** 2020-05-23 10:29 UTC
Labels: area:installer, missing details
