### ISSUE TITLE
Deleted beatmaps can still be accessed via import notification

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6946] opened 2019-11-24 14:17 UTC
**Describe the bug:** 

After importing a beatmap and deleting it afterwards, it can still be "focused" and accessed.

Steps to reproduce:

1. Open Direct and download any map, or import.
2. Delete that map.
3. Use the import success notification to focus that map.
4. Press enter to play.

**Screenshots or videos showing encountered issue:** 

https://streamable.com/5k7hx

**osu!lazer version:** 2019.1122.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3883665/database.log)
[runtime.log](https://github.com/ppy/osu/files/3883666/runtime.log)

**Comment by salmanmkc** [comment] 2019-12-05 15:46
seems like this is fixed

**Comment by Joehuu** [comment] 2019-12-05 22:12
No, I can still reproduce.

**Comment by Stedoss** [comment] 2019-12-06 02:16
There seems to be no check for a pending delete for the mapset being presented.
Adding this check appears to fix the behavior shown (https://streamable.com/andm5), however isn't the most friendly way of dealing with it.

**Comment by smoogipoo** [comment] 2019-12-06 02:18
Ideally the notification should be dismissed, but that's a first step,

**Comment by enslaughter** [comment] 2020-01-02 21:11
Is this still a persisting issue? If it is, I can take a look at it.

**Comment by Joehuu** [comment] 2020-01-03 00:08
https://puu.sh/EVNEb/4d4af4d15f.mp4 still reproducible

**Comment by enslaughter** [comment] 2020-01-06 20:57
Is that still using the old version of Lazer? In the latest release (2020.104.0) I cannot seem to reproduce the problem, although the notification does not dismiss itself, much like the video that Stedoss had posted earlier. I'll see if an earlier version of Lazer can reproduce this, but I think this may have been fixed in one of the December patches.

**Comment by peppy** [comment] 2020-01-08 06:53
I can't reproduce. If someone can, please provide a video showing the scenario and we'll reopen this issue.

**Closed by peppy** 2020-01-08 06:53 UTC
Labels: good first issue, import, overlays, song select
