### ISSUE TITLE
Video-related crashes on some maps due to apparently negative duration

### ISSUE THREAD

**Issue by xeome** [ppy/osu#17345] opened 2022-03-19 14:31 UTC
### Type

Crash to desktop

### Bug description

system information:  
operating system: endeavouros (arch based)  
kernel: latest zen kernel  
gpu: gtx 760  
gpu driver version: 470.103.01-1  
i start a map and it crashes, log from terminal
```
Unhandled exception. System.ArgumentException: '0' cannot be greater than -0.001.
   at System.Math.ThrowMinMaxException[T](T min, T max)
   at osu.Framework.Graphics.Animations.AnimationClockComposite.get_PlaybackPosition()
   at osu.Framework.Graphics.Video.Video.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass126_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.RunSingleFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-2/ppy/osu/osu.Desktop/Program.cs:line 109
[1]    25924 IOT instruction (core dumped)  ./osu.AppImage
```

### Version

2022.319.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/8309465/database.log)
[network.log](https://github.com/ppy/osu/files/8309466/network.log)
[performance.log](https://github.com/ppy/osu/files/8309467/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8309468/runtime.log)

**Comment by bdach** [comment] 2022-03-19 14:39
the logs do not contain the crash trace you've pasted in, so you must have started the game after the crash again. we explicitly ask not to do that in the template because the logs are now unusable.

please link the map on which this occurs.

**Comment by xeome** [comment] 2022-03-19 14:41
im sorry, im updating the logs  
[the map](https://osu.ppy.sh/beatmapsets/1643234#osu/3354107)

**Comment by enoslayd** [comment] 2022-03-19 14:43
Have you tried to play the map with video turned off?

**Comment by bdach** [comment] 2022-03-19 14:44
@enoslayd turning video off is not a valid solution. this looks like an actual bug. please do not suggest such things.

**Comment by xeome** [comment] 2022-03-19 14:44
i have updated the logs on the main issue post  
but here they are again:  
[database.log](https://github.com/ppy/osu/files/8309454/database.log)
[network.log](https://github.com/ppy/osu/files/8309455/network.log)
[performance.log](https://github.com/ppy/osu/files/8309456/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8309457/runtime.log)

**Comment by xeome** [comment] 2022-03-19 14:57
ok logs didn't include the crash trace again for some reason...
i did it again, these logs include it:
[database.log](https://github.com/ppy/osu/files/8309465/database.log)
[network.log](https://github.com/ppy/osu/files/8309466/network.log)
[performance.log](https://github.com/ppy/osu/files/8309467/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8309468/runtime.log)  

video showing the crash:  

https://user-images.githubusercontent.com/44901648/159126206-d8c70ccf-0d62-4f13-9b83-c8665df3e4a4.mp4

**Comment by xeome** [comment] 2022-03-19 15:10
any other information needed?

**Comment by bdach** [comment] 2022-03-19 15:13
i can't reproduce this locally but i think i can see how this can happen. no more info needed thanks.

**Comment by bdach** [comment] 2022-03-19 15:18
so i'm reasonably sure this is going to boil down to `formatContext->duration` being negative here:

https://github.com/ppy/osu-framework/blob/cd289a0adafdbe1660446a86719c7436b40f7338/osu.Framework/Graphics/Video/VideoDecoder.cs#L340-L343

@Opelkuh do you know if it is perhaps possible that the aforementioned value is negative? i'm guessing it is -1 in this reported case, leading to a clamp failure multiple layers down the line. i don't think there's anything more intelligent than to be done here than fail decoding entirely?

**Comment by roridev** [comment] 2022-03-19 15:41
can't repro on windows, seems to be platform specific.

**Comment by bdach** [comment] 2022-03-19 15:42
yes it will be. it's likely to be linux-specific due to use of VDPAU, probably even ffmpeg-version-specific.

**Comment by Opelkuh** [comment] 2022-03-19 17:53
The duration can be negative if the video stream doesn't provide it. I don't know if there are video containers that do this but it's the case with e.g. RTSP streams. Stopping decoding in that case is probably the safest bet. 

But I'm not sure what's causing it here, the video file does have duration set correctly.

I reprod the crash in osu-framework by hardcoding a RTSP stream as the input:
```csharp
diff --git a/osu.Framework/Graphics/Video/VideoDecoder.cs b/osu.Framework/Graphics/Video/VideoDecoder.cs
--- a/osu.Framework/Graphics/Video/VideoDecoder.cs	(revision 14ed4f4ac0a05e1ce48ec18d019536ad0262114b)
+++ b/osu.Framework/Graphics/Video/VideoDecoder.cs	(date 1647710347145)
@@ -318,10 +318,10 @@
 
             var fcPtr = ffmpeg.avformat_alloc_context();
             formatContext = fcPtr;
-            formatContext->pb = ioContext;
+            // formatContext->pb = ioContext;
             formatContext->flags |= AGffmpeg.AVFMT_FLAG_GENPTS; // required for most HW decoders as they only read `pts`
 
-            int openInputResult = ffmpeg.avformat_open_input(&fcPtr, "dummy", null, null);
+            int openInputResult = ffmpeg.avformat_open_input(&fcPtr, "rtsp://rtsp.stream/pattern", null, null);
             inputOpened = openInputResult >= 0;
             if (!inputOpened)
                 throw new InvalidOperationException($"Error opening file or stream: {getErrorMessage(openInputResult)}");
```

**Comment by bdach** [comment] 2022-03-19 22:52
we may be unable to reproduce due to ffmpeg version differences...

@xeome please post the output of `ffmpeg -v` on your machine.

**Comment by smoogipoo** [comment] 2022-03-22 00:59
I can repro the crash.
```sh
$ ffmpeg -version
ffmpeg version n5.0 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      57. 17.100 / 57. 17.100
libavcodec     59. 18.100 / 59. 18.100
libavformat    59. 16.100 / 59. 16.100
libavdevice    59.  4.100 / 59.  4.100
libavfilter     8. 24.100 /  8. 24.100
libswscale      6.  4.100 /  6.  4.100
libswresample   4.  3.100 /  4.  3.100
libpostproc    56.  3.100 / 56.  3.100
```

**Comment by frenzibyte** [comment] 2022-04-02 13:11
osu!framework seems to run on FFmpeg 4.3.3 as of now, and the issue will probably hide once the ffmpeg libraries get shipped with the linux builds (https://github.com/ppy/osu-framework/issues/4349), to then become apparent once we update to FFmpeg 5.0 (https://github.com/ppy/osu-framework/issues/5051).

Perhaps this sort of issue should be bundled within that thread instead.

**Comment by ThatOneCalculator** [comment] 2022-04-14 02:07
Adding onto this:

Editing line 7 of `/usr/share/applications/osu-lazer.desktop` to 
```
Exec=env OSU_EXTERNAL_UPDATE_PROVIDER=1 LD_LIBRARY_PATH=/usr/lib/ffmpeg4.4:"$LD_LIBRARY_PATH" /usr/bin/osu-lazer
```
does the trick really well for launching from a gui menu

**Comment by itsMapleLeaf** [comment] 2022-04-14 03:16
> Adding onto this:
> 
> Editing line 7 of `/usr/share/applications/osu-lazer.desktop` to
> 
> ```
> Exec=env OSU_EXTERNAL_UPDATE_PROVIDER=1 LD_LIBRARY_PATH=/usr/lib/ffmpeg4.4:"$LD_LIBRARY_PATH" /usr/bin/osu-lazer
> ```
> 
> does the trick really well for launching from a gui menu

Can confirm, this fixed the issue for me, and also made my videos work again

**Comment by ThatOneCalculator** [comment] 2022-04-22 04:06
> Tracking a fix for this at https://github.com/ppy/osu-framework/issues/4349.

Omg thanks peppy 🤩🥰😍
![caption-1.jpeg](https://user-images.githubusercontent.com/44733677/164596250-61f5998f-ba69-49c2-925b-be7a219e95f5.jpeg)

**Comment by Jordan-Jay** [comment] 2022-11-05 10:06
This issue has been fixed as this map doesn't crash Lazer anymore. :+1:

**Comment by bdach** [comment] 2022-11-05 10:44
That's because we're shipping FFmpeg inside the appimage, as described above. Closing as resolved.

**Closed** 2022-11-05 10:44 UTC
Labels: framework-fix-required, platform:linux, area:storyboard
