### ISSUE TITLE
Stable scores to v2 conversion bugged on specific map

### ISSUE THREAD

**Issue by CaptainBasculin** [ppy/osu#29813] opened 2024-09-09 09:11 UTC
### Type

Game behaviour

### Bug description

Stable converted scores to scorev2 from this map exceed the max possible score achievable using the mod combination. 

https://osu.ppy.sh/beatmapsets/284931#osu/1593298

### Screenshots or videos

![image](https://github.com/user-attachments/assets/b216f072-0494-4336-9c28-59590cad25c4)

![image](https://github.com/user-attachments/assets/18dedc2f-b0bd-4377-a858-5fd01a08ed35)

### Version

Lazer 2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16928101/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-10 04:50
Duplicate of https://github.com/ppy/osu/issues/29772

**Comment by bdach** [comment] 2024-09-10 06:41
Claiming that it's a duplicate without investigating is premature. I'm keeping this open for myself until I can investigate properly.

**Comment by bdach** [comment] 2024-09-11 10:31
After investigating I can now confirm that this does appear to be a duplicate based on the symptom that importing one of the affected scores locally returns a much saner total score, meaning that it appears there is something going wrong server-side.

**Closed by bdach** 2024-09-11 10:31 UTC
