### ISSUE TITLE
Slider body volume/sampleset changes are not present in lazer

### ISSUE THREAD

**Issue by LosPedros** [ppy/osu#25394] opened 2023-11-08 13:35 UTC
### Type

Game Behaviour

### Bug description

https://osu.ppy.sh/beatmapsets/1948783#osu/4341427

The slider bodies are supposed to be changing their volumes acording to the song but because of how lazer implements the osu!stable inherited timing points the volume changes are just not present

### Screenshots or videos

https://github.com/ppy/osu/assets/46714621/3ba990d3-41ea-4c2b-bb90-a4545d909f23

### Version

2023.1026.0

### Logs

.

**Comment by bdach** [comment] 2023-11-09 08:23
Basically duplicate of #24997

**Closed by bdach** 2023-11-09 08:23 UTC
