### ISSUE TITLE
Some keys do not work correctly on android

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5283] opened 2019-07-06 22:47 UTC
**Describe the bug:** 
By typing "[" , "]" , "{" , "}" , "|", THE "  , "=" symbols the key will actually register, but it will not appear on the screen as long as the different button is not pressed. Also, the SHIFT key does not fully work. Like you can't hold shift and press a ";" button to get ":" for example.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/g1WT3sWiX9Y

**osu!lazer version:** 
2019.704.0

**Android device Specifications:**
Brand – CHUWI
Model – HI10 PLUS
Device Type – Android LTE Tablet
CPU – Quad-Core 1.44GHz up to 1.92GHz
Chipset – Intel Atom X5 Z8350
GPU – Intel HD Graphics 400

**Comment by peppy** [comment] 2019-07-07 04:01
Duplicate of https://github.com/ppy/osu-framework/issues/2631?

**Comment by peppy** [comment] 2022-01-22 06:28
I believe we have pretty good support these days.

**Closed by peppy** 2022-01-22 06:28 UTC
Labels: framework-fix-required, type:input
