### ISSUE TITLE
Intro song not matching the set song when exiting an area where no song is playing (editor, daily challenge with a non downloaded map etc...)

### ISSUE THREAD

**Issue by yomikomanda** [ppy/osu#29260] opened 2024-08-02 19:39 UTC
### Type

Game behaviour

### Bug description

When I exit a screen where no song is playing into the main menu, it's always Triangles no matter the intro sequence setting. I have the intro sequence set to circles, cuz it's the best song and it doesn't have that flashbang in the intro, and when i exit the editor, multiplayer room or daily challenge with the current map not downloaded, it always plays triangles, and i would really like if it would play the selected song instead.

Update: This is just a suggestion, but it would be nice if you would change the intro and menu song for the current year season (halloween, christmas) just like in stable, it would be nice

### Screenshots or videos

https://github.com/user-attachments/assets/79371058-df03-441a-999d-7d592923bc7c

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16474633/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-08-02 19:48
Duplicate of https://github.com/ppy/osu/issues/21064

**Closed by Joehuu** 2024-08-02 19:48 UTC
