### ISSUE TITLE
Previewing any beatmap under browse causes the game to crash after the preview is finished playing in linux. 

### ISSUE THREAD

**Issue by bndlfm** [ppy/osu#11492] opened 2021-01-15 04:05 UTC
Pretty much just as described above.

**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/16002082/104679734-f38a6480-56b3-11eb-9d85-2390ac8bad03.mp4

**osu!lazer version:**
2021.109.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5818342/database.log)
[network.log](https://github.com/ppy/osu/files/5818343/network.log)
[performance.log](https://github.com/ppy/osu/files/5818344/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5818345/runtime.log)

If you need the terminal output that you can briefly see at the end of my vid I can send it but I assume it's all in the logs.

**Computer Specifications:** 
Ryzen 7 3700x, 32 GB Ram, ADATA 1TB NVME SSD, GTX 1660

**Comment by peppy** [comment] 2021-01-15 04:09
Duplicate of https://github.com/ppy/osu/issues/11478

**Closed by peppy** 2021-01-15 04:09 UTC
