### ISSUE TITLE
Order of maps in song select is inconsistent when sorting by BPM

### ISSUE THREAD

**Issue by mazziechai** [ppy/osu#22054] opened 2023-01-06 19:05 UTC
### Type

Game behaviour

### Bug description

When sorting maps by BPM in song select, the order of the maps change after loading and playing a map.

Intended behavior: The order that the map appears in should be consistent.

Reproduction steps:
1. Sort by BPM
2. Open a map and make sure it loads fully
3. Exit, and where the map appears in song select is different.

In the video provided, Gate Openerz appears below Call me it. After loading into the map and exiting, Oxalis appears below Call me it. Exiting and reentering song select will restore the original order.

### Screenshots or videos

https://youtu.be/vs4rdvj4kJw

### Version

2022.1228.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10362444/runtime.log)
[session.log](https://github.com/ppy/osu/files/10362445/session.log)
[update_success.log](https://github.com/ppy/osu/files/10362446/update_success.log)

I don't think osu!auth.log is necessary (it's also encrypted) so I won't upload that.

**Comment by jai-x** [comment] 2023-01-06 19:08
Possible duplicate of https://github.com/ppy/osu/issues/21926

**Closed** 2023-01-06 19:15 UTC
