### ISSUE TITLE
Overlays and some screens don't work properly

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#12094] opened 2021-03-20 09:39 UTC
**Describe the bug:** I just updated to the latest version and changed some of the new input settings. After relaunching the game, the overlays and some screens were not working properly.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/111865459-62f82b00-8967-11eb-9eb6-1a70f95f2a2a.mp4

**osu!lazer version:** `2021.320.0`

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6175207/runtime.log)
[database.log](https://github.com/ppy/osu/files/6175210/database.log)
[network.log](https://github.com/ppy/osu/files/6175211/network.log)

**Comment by bdach** [comment] 2021-03-20 09:52
Does not seem to be related to any input settings, actually. Probably just something that was never actually reported before.

```
2021-03-20 09:26:04 [error]: An unhandled error has occurred.
2021-03-20 09:26:04 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2021-03-20 09:26:04 [error]: at osu.Game.Beatmaps.DifficultyRecommender.get_orderedRulesets()
2021-03-20 09:26:04 [error]: at osu.Game.Beatmaps.DifficultyRecommender.GetRecommendedBeatmap(IEnumerable`1 beatmaps)
2021-03-20 09:26:04 [error]: at osu.Game.Screens.Select.SongSelect.<>c__DisplayClass57_0.<load>b__5(IEnumerable`1 s)
2021-03-20 09:26:04 [error]: at osu.Game.Screens.Select.BeatmapCarousel.<>c__DisplayClass99_0.<createCarouselSet>b__1(IEnumerable`1 beatmaps)
2021-03-20 09:26:04 [error]: at osu.Game.Screens.Select.Carousel.CarouselBeatmapSet.GetNextToSelect()
2021-03-20 09:26:04 [error]: at osu.Game.Screens.Select.Carousel.CarouselGroupEagerSelect.PerformSelection()
```

To my knowledge that code has not been touched recently.

**Comment by Walavouchey** [comment] 2021-03-20 10:05
Issues like this have happened to me as well in previous releases, albeit to a lesser degree. This build made the problem just as bad as in OP, but I managed to fix all of it by deleting all the game files (in `%APPDATA%/Roaming/osu`) and reinstalling.

**Comment by bdach** [comment] 2021-03-20 10:08
I'm not sure why deleting game files would have anything to do with this error.

**Comment by Walavouchey** [comment] 2021-03-20 10:36
The problem came back and I got the exact same error in the logs. The issue was still present after relaunching and in a local debug. Moving away `client.db` and relaunching fixed the issue and putting it back in didn't break it. So far so good, but I'm not sure either on how this is related.

**Comment by bdach** [comment] 2021-03-20 11:45
@Walavouchey Since you mentioned running local debug, I wonder if you are able to confirm where the `null` is coming from in the trace above. I'm suspecting `recommendedDifficultyMapping` might be in an invalid state, but it's hard to tell without a reproduction.

**Comment by Gabixel** [comment] 2021-03-20 13:23
At the moment, the error seems to have disappeared for me strangely enough: I haven't touched anything inside the game folder (I just re-launched the game), but for some reason, everything seems to be working fine now...

**Comment by JustaPeriod** [comment] 2021-03-20 13:44
Also seeing this problem in the latest update of the game, same as the video. My logs do not appear to have the same errors in them.
[network.log](https://github.com/ppy/osu/files/6175661/network.log)
[performance.log](https://github.com/ppy/osu/files/6175662/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6175663/runtime.log)

I noticed that after I closed my game, lazer kept running in the background, using 130MB/s of disk activity. I checked Process Monitor and it appears to be writing to the Temp folder as well as my client.db. 

![2021-03-20_08-41-18](https://user-images.githubusercontent.com/1241514/111871501-6b953500-8958-11eb-9898-74f8871d470d.png)

This continued for about 10 minutes, and then it stopped. Upon relaunching the game, all overlays/screens are working now.

**Comment by bdach** [comment] 2021-03-20 13:53
@JustaPeriod I don't see any clear evidence that would indicate that your problem is related, except for the claim you're seeing the same symptoms. Did you import any new maps, skins, or anything else that might have touched the DB before closing the game and observing it still be open despite the game window going away?

**Comment by JustaPeriod** [comment] 2021-03-20 13:57
@bdach Only updated the game from a January version to latest. I figured I'd comment because one person mentioned moving their client.db fixed it, and another mentioned that the problem went away by itself randomly. I figured both those people were facing whatever I was.

**Comment by smoogipoo** [comment] 2021-03-20 14:42
Bumping this one into the milestone/priority because it also failed for me on the latest release, just on a fresh update (nothing new imported). Not sure what could be null though.

I also ended up nuking _something_ but don't know what it was (it wasn't client.db), which would support the claim that re-adding client.db back works fine. Unfortunately I did this before I realised the consequences of my actions (not being able to debug)...

I suspect it's actually online.db that got nuked, which would coincide with the error in the database.log above and come as a result of the recent EF5 upgrade - somehow that database error is causing a cascading failure elsewhere stopping the difficulty recommender from being loaded? That's the only way I can imagine its `ruleset` being null...

**Comment by bdach** [comment] 2021-03-20 14:45
Thing is, we don't use EF for `online.db`. We use raw ADO.NET. It used to be dapper but it got booted.

**Comment by frenzibyte** [comment] 2021-03-21 15:46
@chaguy2457 Since you're experiencing this currently, can you try moving away the `online.db` file from osu!lazer folder somewhere else (can open by `Open osu! folder` button in the settings), can be useful to identify the cause.

**Comment by chaguy2457** [comment] 2021-03-21 15:50
@frenzibyte I assume you mean to move the file while the game is open. I just tried it, got the same issue. I'm attaching the logs again:

[database.log](https://github.com/ppy/osu/files/6177795/database.log)
[network.log](https://github.com/ppy/osu/files/6177796/network.log)
[performance.log](https://github.com/ppy/osu/files/6177797/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6177798/runtime.log)

**Comment by frenzibyte** [comment] 2021-03-21 15:51
I meant to move the file while the game is closed, then start the game and check again.

**Comment by peppy** [comment] 2021-03-21 15:54
hopefully resolved by the ef rollback. should not be investigated further until we can confirm that, since it would be wasted effort.

**Comment by chaguy2457** [comment] 2021-03-21 15:56
Got it, moved online.db first, same issue. Logs:
[database.log](https://github.com/ppy/osu/files/6177800/database.log)
[network.log](https://github.com/ppy/osu/files/6177801/network.log)
[performance.log](https://github.com/ppy/osu/files/6177802/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6177803/runtime.log)

The folder re-created the online.db file, so I moved that and client.cb out next while the game was closed and relaunched. Don't have my beatmaps and skin anymore but I downloaded a random beatmap and I didn't have the issue anymore. Logs:

[database.log](https://github.com/ppy/osu/files/6177808/database.log)
[network.log](https://github.com/ppy/osu/files/6177809/network.log)
[performance.log](https://github.com/ppy/osu/files/6177810/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6177811/runtime.log)

**Comment by peppy** [comment] 2021-03-22 05:20
@smoogipoo can you still repro this one? would appreciate if you can check again on master now that we've reverted the EF5 bump.

**Comment by smoogipoo** [comment] 2021-03-22 06:00
I can't repro anymore, no.

**Comment by peppy** [comment] 2021-03-22 06:02
Perfect, should be safe to close.

**Closed by peppy** 2021-03-22 06:02 UTC
Labels: area:song-select, priority:0
