### ISSUE TITLE
Volume changes not visible while the settings menu is open

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu#29139] opened 2024-07-27 14:28 UTC
### Type

Cosmetic

### Bug description

The title expliains this, and thats preaty much it. This could be intentional, but i think it would make more sense for the volume changes to be visible like normaly.
Turn on the volume of the video while watching it, otherwise itll look like it doesn't make sense

### Screenshots or videos

https://github.com/user-attachments/assets/2902c7e1-a0ba-4c9c-8624-efc17234423b

### Version

osu! version: Lazer 2024.727.0 (latest)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16400451/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-07-27 16:31
Duplicate of https://github.com/ppy/osu/issues/11077

**Closed by Joehuu** 2024-07-27 16:31 UTC
