### ISSUE TITLE
Playing a beatmap with a video crashes on Wayland + AMD GPU

### ISSUE THREAD

**Issue by ThatOneCalculator** [ppy/osu#17813] opened 2022-04-14 00:13 UTC
### Type

Crash to desktop

### Bug description

Playing any map with a video causes a crash.

OS: Arch GNU/Linux
WM: Hyprland (Wayland)
GPU: AMD 6700XT
CPU: AMD 5800X

Thoughts: the crash says
```
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[AVHWDeviceContext @ 0x7ff338a945c0] VDPAU device creation on X11 display :1 failed.
corrupted size vs. prev_size
[1]    87298 IOT instruction (core dumped)  osu-lazer
```
but I have an AMD GPU, meaning that it's probably trying to open a non-existent Nvidia backend.

### Version

2022.409.0-lazer

### Logs

- Osu! runtime.log: https://zer0b.in/K-sPJDoP
- Shell crash log + coredumpctl: https://zer0b.in/ip9g7q_F

**Comment by frenzibyte** [comment] 2022-04-14 00:24
Can you confirm you actually have `libva-vdpau-driver` installed in the first place? That will eventually be shipped in-game (see https://github.com/ppy/osu-framework/issues/4349).

**Comment by smoogipoo** [comment] 2022-04-14 00:48
Please post the output of `ffmpeg -version`.

**Comment by ThatOneCalculator** [comment] 2022-04-14 00:59
> Can you confirm you actually have `libva-vdpau-driver` installed in the first place? 

It wasn't installed, after installing it, the issue is resolved. It should probably be added as a dependency in the AUR PKGBUILD.

**Comment by ThatOneCalculator** [comment] 2022-04-14 01:02
Nvm, it crashed again. My FFMPEG version is n5.0

**Comment by frenzibyte** [comment] 2022-04-14 01:03
Is it the same crash? please include the crash logs.

**Comment by smoogipoo** [comment] 2022-04-14 01:03
Downgrading to FFmpeg 4 should fix it for you. This is a dupe of https://github.com/ppy/osu-framework/issues/4349.

**Closed** 2022-04-14 01:03 UTC
Labels: missing details, platform:linux

**Comment by ThatOneCalculator** [comment] 2022-04-14 01:22
Sadly looks like I can't downgrade.

![image](https://user-images.githubusercontent.com/44733677/163295508-e74fc120-8029-47ce-addf-278aefb025d1.png)

**Comment by ThatOneCalculator** [comment] 2022-04-14 02:06
Thank you! Editing line 7 of `/usr/share/applications/osu-lazer.desktop` to 
```
Exec=env OSU_EXTERNAL_UPDATE_PROVIDER=1 LD_LIBRARY_PATH=/usr/lib/ffmpeg4.4:"$LD_LIBRARY_PATH" /usr/bin/osu-lazer
```

does the trick :)
