### ISSUE TITLE
IOS osu! It keeps freezing !

### ISSUE THREAD

**Issue by Squigglz** [ppy/osu#6481] opened 2019-10-12 05:53 UTC
Usually during a song the game freezes, goes completely silent, and just sits there. Nothing happens. It just sits there like that. The only thing I can do is swipe it up, if thats restarting the app.

![005D119C-9E9C-4C9B-8426-CE7D0951746D](https://user-images.githubusercontent.com/56452292/66695709-7e4b0b00-ec8a-11e9-97d8-69ef24823bd9.png)

Idk what version it is, I just know I’m using it on my iPhone.

**Comment by Squigglz** [comment] 2019-10-12 06:01
Now another time it froze but kept playing the music, and I got it recorded

**Comment by Squigglz** [comment] 2019-10-12 06:07
![E0D51D09-3C67-43B9-A1E0-51B15AB2E5A4](https://user-images.githubusercontent.com/56452292/66695922-9754bb80-ec8c-11e9-92eb-de65ccb643d3.png)

**Comment by odenstyle** [comment] 2019-10-12 07:05
same here, the game freezes and the song keeps playing, this usually happens to the first song I open up.

**Comment by swoolcock** [comment] 2019-10-12 07:46
Duplicate of #6355.

**Closed by swoolcock** 2019-10-12 07:46 UTC
