### ISSUE TITLE
Ous lazer opens and closes directly at start.

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu#12246] opened 2021-03-31 21:01 UTC
**Describe the bug:** osu lazer opens for about one second as a background app and then closes whenever I start. Doesn't work to open as a administrator or anything that I've found. It has done this for some weeks now.

**Screenshots or videos showing encountered issue:**  

https://user-images.githubusercontent.com/81715029/113210416-7ca54680-9274-11eb-8612-5ec2f0e6bbe4.mp4

**osu!lazer version:** 2021.331.0

**Logs:** [database.log](https://github.com/ppy/osu/files/6239430/database.log)

**Comment by bdach** [comment] 2021-03-31 21:03
Duplicate of #10480

Please rename/move away/delete `%AppData%/osu/client.db` for now if you wish to continue to play the game. Note that this will purge your beatmap database.

**Closed by bdach** 2021-03-31 21:03 UTC
