### ISSUE TITLE
Edge click in profile's beatmap info panel back to menu, instead to return one-level navigation

### ISSUE THREAD

**Issue by Bryceed** [ppy/osu#12514] opened 2021-04-21 07:12 UTC
**Describe the bug:** When we click on osu!direct and open a beatmap info, it won't return us "back to the game", it just back one level of the navigation (as expected), but doing the same thing on profile beatmaps will close all navigation panel.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/42657376/115511444-3893d900-a257-11eb-8a89-36e03a0cc572.mp4

**osu!lazer version:** 
2021.416.0 (_latest stable_)

**Logs:**
[network.log](https://github.com/ppy/osu/files/6348756/network.log)
[performance.log](https://github.com/ppy/osu/files/6348757/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6348758/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6348759/updater.log)
[database.log](https://github.com/ppy/osu/files/6348760/database.log)

**Comment by frenzibyte** [comment] 2021-04-21 07:13
Duplicate of https://github.com/ppy/osu/issues/5063

**Closed by frenzibyte** 2021-04-21 07:13 UTC
