### ISSUE TITLE
Allow custom rulesets to use non-osu!standard beatmaps

### ISSUE THREAD

**Issue by SilverRoll** [ppy/osu#12662] opened 2021-05-02 20:10 UTC
**Describe the new feature:** 
Right now, ruleset-specific maps can only be played in their appropriate ruleset (osu!taiko maps can only be played in taiko, mania maps can only be played in mania, and so on). Which was reasonable in stable osu!. However, with custom rulesets, I feel this has changed. 

Custom rulesets sometimes implemenmt rhythm game concepts that would only need the specific *beats* in the track to base its gameplay on. [Hitokori]( https://github.com/Flutterish/Hitokori) (A dance of fire and ice) could totally work with a Taiko or Catch map, since it only involves clicking, wouldn't have to care about taiko/catch specific elements. After all, both taiko and catch are made as osu! maps in the (old) editor, they're just presented differently. 

This should all be unranked of course.

**Proposal designs of the feature:** 
Allow mods to process ruleset-specific maps, possibly specify which rulesets it can convert from.

**Comment by Joehuu** [comment] 2021-05-02 20:18
Duplicate of https://github.com/ppy/osu/issues/9263

**Closed by Joehuu** 2021-05-02 20:18 UTC
