### ISSUE TITLE
Song select context menu is not topmost on screen

### ISSUE THREAD

**Issue by yoyyoy** [ppy/osu#22644] opened 2023-02-14 23:17 UTC
### Type

Game behaviour

### Bug description

leaderboard appears on top of context menu. when trying to scroll the context menu it scrolls the leaderboard instead, the context menu should take priority. the menu made its way all the way over there cause I had a long collection name.

### Screenshots or videos

https://user-images.githubusercontent.com/43836438/218884103-e5bf8351-cf2b-4c86-bbdf-85cc494a424a.mp4

### Version

2023.207.0

### Logs

[input.log](https://github.com/ppy/osu/files/10737663/input.log)
[network.log](https://github.com/ppy/osu/files/10737664/network.log)
[performance.log](https://github.com/ppy/osu/files/10737665/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10737666/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10737667/updater.log)
[database.log](https://github.com/ppy/osu/files/10737668/database.log)

**Comment by Joehuu** [comment] 2023-12-15 04:19
Duplicate of https://github.com/ppy/osu/issues/21602

**Closed by Joehuu** 2023-12-15 04:19 UTC
Labels: area:song-select, type:behavioural
