### ISSUE TITLE
Slider follow circles start rectangular

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1494] opened 2017-11-13 05:15 UTC
They're supposed to always be circular.

This is an issue with `CircularContainer`'s Invalidate(), but there's a reason for why it's done the way it is now, and there's a reason why it was done inside Invalidate() previously - traversing Git history will be required to figure out why as both solutions had issues.

**Test cases + comments are a must.**

Making this issue on osu! side because the slider follow circles provide a starting point to resolving this issue.

**Comment by FreezyLemon** [comment] 2017-11-21 23:33
![Current Code](https://i.imgur.com/vsIhCKa.png)

Reading up on this a bit, it seems that (inside `CircularContainer.Invalidate`) the `base.Invalidate()` call was moved to before the if-statement so that _in an older version_, the `CornerRadius` could be set off of freshly evaluated `DrawSize` values (this happened inside Invalidate() at that point).

This has now been moved to the `CircularContainer.Update` method, but the (possible) base / DrawSize invalidation -> update is still done before the cornerRadius invalidation -> update, which I _think_ is also still necessary. So I'm not sure why the cornerRadius isn't updated often enough.. I'll be testing it a bit though.

Side note: The `CircularContainer.Invalidate` currently only returns whether or not the _base_ class has invalidated (or rather, it only returns `base.Invalidate`). This should be changed to also include `cornerRadius.Invalidate` aswell. ([easy fix](https://i.imgur.com/8HQ9fGm.png), will include it in the PR if I do make one for this issue)

**Comment by FreezyLemon** [comment] 2017-11-22 00:01
Update: I've tried setting the CornerRadius to a new value **every** `CircularContainer.Update()` call and the problem is not solved (if it gets better, only marginally) which makes me assume that the `DrawSize` value is not updated / invalidated enough. Still investigating...

**Comment by FreezyLemon** [comment] 2017-11-23 05:45
Update 2: This issue persists even if caching is disabled globally.
Also, the `SliderBall` object (directly inherits from `CircularContainer`) is exactly the same (even same object [reference](https://i.imgur.com/cvU6JxE.png)) at these two update calls / frames:
1. When the follow circle is first drawn but still has the bugged corners
2. One update call later (corners are fixed now)

This shows that it's not a caching issue (and thus not a problem with the (in-)validation, and also leads me to believe that it's some kind of rendering/drawing issue _since_ the object being drawn is exactly the same at both times.

**Closed** 2017-11-27 06:17 UTC
Labels: bug, framework fix required, high priority
