### ISSUE TITLE
Freeze at start of beatmap

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu#11475] opened 2021-01-13 17:28 UTC
**Describe the new feature:** 
I would like for the Beatmap, that is currently being played by the user to be cached into RAM. This does not mean the background-music in the menu, but rather in-gameplay. This would solve issues of osu just plainly freezing, when the disk can't keep up.

Note: This is also an issue on normal osu!

**Proposal designs of the feature:** 

When selecting a beatmap for gameplay, create a small ramdisk, transfer a copy of the beatmap to that ramdisk, and then do all existing operations on the ramdisk. Including starting the Gameplay! 
Since each individual song should be quite small, this should not affect the RAM-cost too much, even if little RAM is available.
Of course there should be a Menu-option to turn on the Ramdisk swapping behavior.

Something, that could be added as well is a size-value, which will determine, if beatmaps should be loaded dynamically.
This could be useful, if some beatmaps are just too large for RAM.
Of course the size-value could also be added as a changeable setting.

**Comment by bdach** [comment] 2021-01-13 17:31
Do you have any experimental results or other proof that would prove that whatever issue you're experiencing is directly related to disk I/O? Otherwise this post is just baseless conjecture. We don't read the beatmap from disk, it *is* already in memory.

**Comment by C0D3-M4513R** [comment] 2021-01-13 17:51
Yes I do.  When I start a beatmap in either osu! clients, The beatmap just ramdomly freezes for a certain amount, and then resumes. The cpu is not maxed. The disk is somewhat close to total disk use. I will try to get a clip of osu! freezing.

**Comment by bdach** [comment] 2021-01-13 17:54
It would have been way more helpful if you stated the problem you're having to begin with instead of attempting to blindly throwing out guesses about how to resolve it.

Please attach game logs for inspection, as in the issue template. Also "cpu is not maxed" does not mean much. A single *logical core* might be maxed, and you won't see 100% CPU in that case. If you're a developer, then attaching a profiler might yield actually useful information.

**Comment by C0D3-M4513R** [comment] 2021-01-13 18:24
So my setup is a little complicated:
HW:
CPU: Ryzen 5 3600 (6 Core x 2 Threads)
GPU1: Nvidia RTX 2060 Super
GPU2: Nvidia GTX 660
RAM: 32G
Storage Media: nvme ssd

HW Linux:
Cpu: 3 Cores / 2 Threads
Gpu: Nvidia GTX 660
Ram: 24G

HW Win:
Cpu: 3 Cores / 2 Threads
Gpu: Nvidia RTX 2060 Super
Ram: 8G

Software:
On my Pc I am running ubuntu linux. I have 3 Cores disabled, for Vm forwarding. Similar with the GPU1, which is also unaccesible from linux.
Then I have a Windows VM. (I know, that this is the culprit, but the game shouldn't freeze regardless, if the beatmap is cached.)
This Windows Vm has 3/6 Cores. Linux has NO possible control over them. they are isolated. No cpu schueduler or task (outside the vm) is running on those Cores. Similar with the Gpu1. Its PCI bus is forwarded. The physical storage medium is shared however. The windows disk lies within a .img inside Linux. Also 8G of ram are allocated at boot for the Vm.


Video: https://www.youtube.com/watch?v=bo-zgq7nSMg

**Comment by bdach** [comment] 2021-01-13 18:29
I have *several* questions, but the two pressing ones are:

* You know that lazer runs natively under linux, right? What's the point of the VM? I'm not sure we should be spending time on VMs when the game should work just fine without one.
* The attached video has no sound, which could be an important clue. Does the sound stop when this freeze happens? The reason why I'm asking is that if the VM is having audio buffering issues then that might be possibly causing this freeze.

**Comment by C0D3-M4513R** [comment] 2021-01-13 18:31
[database.log](https://github.com/ppy/osu/files/5810449/database.log)
[network.log](https://github.com/ppy/osu/files/5810450/network.log)
[performance.log](https://github.com/ppy/osu/files/5810451/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5810452/runtime.log)

**Comment by C0D3-M4513R** [comment] 2021-01-13 18:33
> You know that lazer runs natively under linux, right? What's the point of the VM? I'm not sure we should be spending time on VMs when the game should work just fine without one.
Yeah I know. The vm is mostly for regular osu/other games.
> The attached video has no sound, which could be an important clue. Does the sound stop when this freeze happens? The reason why I'm asking is that if the VM is having audio buffering issues then that might be possibly causing this freeze.
The sound does freeze, although I will upload a new video.

**Comment by bdach** [comment] 2021-01-13 18:33
the logs attached seem to "conveniently" have the bass/opengl audio initialisation entries stripped of them which does not help trying to diagnose.

**Comment by C0D3-M4513R** [comment] 2021-01-13 18:34
> 
> 
> the logs attached seem to "conveniently" have the bass/opengl audio initialisation entries stripped of them which does not help trying to diagnose.

Reuploading...

**Comment by C0D3-M4513R** [comment] 2021-01-13 18:53
I should add, that the streaks, that are drawn, are always appearing, when I tap on my tablet. This does not appear in normal osu!, or anywhere else. (or maybe somewhere else it's filtered?) 
Tablet Driver is the following: https://github.com/InfinityGhost/OpenTabletDriver

Video: https://www.youtube.com/watch?v=krdoJs2DiDs
[database.log](https://github.com/ppy/osu/files/5810529/database.log)
[network.log](https://github.com/ppy/osu/files/5810530/network.log)
 #[performance.log](https://github.com/ppy/osu/files/5810531/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5810533/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5810536/updater.log)

**Comment by bdach** [comment] 2021-01-13 19:20
I mean yeah, the gameplay *looks* broken, but frankly I don't even know where to begin with this report. There's so much possible interference at play, and most of the causes can be ascribed to your... unorthodox setup.

The only thing I can recommend for now is eliminating possible interfering factors, by which I mean

* Remove OpenTabletDriver and see if input improves
* Remove the VM factor and see if the audio stalls still happen (any audio stall will also stall the game clock during gameplay).

If there is still any issue remaining after those are eliminated, then please report back and we'll attempt to deal with it. But as of right now this issue is not actionable on our side as this is still not enough to go on, we'd have to pretty much replicate your setup to even try to look at this, and having 100%-accurate VM support is not something we want to actively prioritise at this stage anyway (and that might not even be possible if the VMs have bugs, which they will do, as all software does).

Due to the above I'm tentatively closing this as out of scope. If you manage to find any more useful information on your side that might point to a definite cause then please report back and we'll assess if it's enough to reopen (that said I'm strongly suspecting audio is at fault here).

**Closed by bdach** 2021-01-13 19:20 UTC
Labels: missing details

**Comment by C0D3-M4513R** [comment] 2021-01-16 19:35
Ok. I changed some things, and now I am up and running. Knowing, that the problem lay within the audio pipeline, I changed some Vm settings, and audio handling. Afterwards everything works as expected.

**Comment by C0D3-M4513R** [comment] 2021-03-01 13:37
Follow up, a bit later. I had this issue, due to high Interrupt times. I checked them using [LatencyMon](https://resplendence.com/latencymon). Apperantly I didn't isolate the CPU's correctly.
