### ISSUE TITLE
Killed in the background on Android

### ISSUE THREAD

**Issue by BiYT-cn** [ppy/osu#15822] opened 2021-11-26 16:28 UTC
On Pixel3 running Android 12, open any osu!Lazer interface, then lock the screen or return to the main interface of the phone,osu!Lazer would restart.

runtime.log:
`2021-11-26 16:17:57 [verbose]: ----------------------------------------------------------
2021-11-26 16:17:57 [verbose]: runtime Log for somebody (LogLevel: Verbose)
2021-11-26 16:17:57 [verbose]: Running  2021.1119.0.0 on .NET 4.0.50524.0
2021-11-26 16:17:57 [verbose]: Environment: Android (Unix 4.9.283.0), 8 cores
2021-11-26 16:17:57 [verbose]: ----------------------------------------------------------
2021-11-26 16:17:57 [verbose]: GL Initialized
2021-11-26 16:17:57 [verbose]: GL Version:                 OpenGL ES 3.2 V@0490.0 (GIT@781e7d0, I46ff5fc46f, 1606819536) (Date:12/01/20)
2021-11-26 16:17:57 [verbose]: GL Renderer:                Adreno (TM) 630
2021-11-26 16:17:57 [verbose]: GL Shader Language version: OpenGL ES GLSL ES 3.20
2021-11-26 16:17:57 [verbose]: GL Vendor:                  Qualcomm
2021-11-26 16:17:57 [verbose]: GL Extensions:              GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather
2021-11-26 16:17:57 [verbose]: Host execution state changed to Running
2021-11-26 16:17:57 [verbose]: Execution mode changed to MultiThreaded
2021-11-26 16:17:58 [verbose]: BASS Initialized
2021-11-26 16:17:58 [verbose]: BASS Version:               2.4.16.7
2021-11-26 16:17:58 [verbose]: BASS FX Version:            2.4.12.6
2021-11-26 16:17:58 [verbose]: BASS MIX Version:           2.4.11.1
2021-11-26 16:17:58 [verbose]: Device:                     Default
2021-11-26 16:17:58 [verbose]: Drive:
`
performance.log:
`2021-11-26 16:17:39 [verbose]: ----------------------------------------------------------
2021-11-26 16:17:39 [verbose]: performance Log for somebody (LogLevel: Verbose)
2021-11-26 16:17:39 [verbose]: Running  2021.1119.0.0 on .NET 4.0.50524.0
2021-11-26 16:17:39 [verbose]: Environment: Android (Unix 4.9.283.0), 8 cores
2021-11-26 16:17:39 [verbose]: ----------------------------------------------------------
2021-11-26 16:17:39 [verbose]: TextureAtlas initialised (1024x1024)
2021-11-26 16:17:40 [verbose]: TextureAtlas initialised (1024x1024)
2021-11-26 16:17:41 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
2021-11-26 16:17:41 [verbose]: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
2021-11-26 16:17:42 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
2021-11-26 16:17:43 [verbose]: TextureAtlas size exceeded 3 time(s); generating new texture (1024x1024)
2021-11-26 16:17:43 [verbose]: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
2021-11-26 16:17:43 [verbose]: Texture requested (1400x310) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:43 [verbose]: Texture requested (1800x600) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:43 [verbose]: Texture requested (1400x310) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:44 [verbose]: Texture requested (1366x768) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:48 [verbose]: TextureAtlas size exceeded 3 time(s); generating new texture (1024x1024)
2021-11-26 16:17:48 [verbose]: Texture requested (1295x1295) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:48 [verbose]: Texture requested (1295x1295) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-11-26 16:17:54 [verbose]: TextureAtlas size exceeded 4 time(s); generating new texture (1024x1024)
 `

**Comment by frenzibyte** [comment] 2021-11-26 16:29
Duplicate of https://github.com/ppy/osu-framework/issues/4200

**Closed by frenzibyte** 2021-11-26 16:29 UTC
