### ISSUE TITLE
Cant use escape key when i switch my ime out

### ISSUE THREAD

**Issue by Lama3L9R** [ppy/osu#9177] opened 2020-06-02 12:19 UTC
Im a Chinese player. I switch my ime out when im playing a beatmap. and then i cant use escape key. even i switch it off. and i cant type anything in search box. sometimes i back to title screen it fix. sometimes i need restart game.

my ime is windows10 default. i think that is not ime`s problem cause in osu! there is no that problem

(I read the logs i think only runtime will useful for debug so i just upload that)

osu!lazer version: latest(update files every time i launch game)

**Logs:**
RuntimeLog: https://paste.ubuntu.com/p/vJ3MRGSwdj/

**Comment by bdach** [comment] 2020-06-02 12:43
Duplicate of ppy/osu-framework#2525, I'd say.

**Closed by bdach** 2020-06-02 12:43 UTC
