### ISSUE TITLE
Pink back button not placed correctly

### ISSUE THREAD

**Issue by honguyenminh** [ppy/osu#7217] opened 2019-12-15 01:34 UTC
**Describe the bug:** 
The pink back button is not placed correctly, leaving a gap under it, occurs in these resolution:
1024x768
1280x768
1360x768
1366x768
Above 1366x768 not checked yet.
All pink back button in song selection, Chart, Multi, score display,... have the same problem

**Screenshots or videos showing encountered issue:** 
https://drive.google.com/open?id=1yY_qcQBAYPKQ1rtvy4NfOoi9HsgRBUSo

**osu!lazer version:** 2019.1213.0

**Logs:** Not necessary, it's visual

**Comment by Joehuu** [comment] 2019-12-15 01:49
Similar/duplicate of https://github.com/ppy/osu/issues/4216. It's probably a problem with raw input, so try disabling that.

**Closed by Joehuu** 2019-12-15 01:49 UTC
