### ISSUE TITLE
DT score multiplier not scaling with the speed increase customization feature.

### ISSUE THREAD

**Issue by ChickenIQ** [ppy/osu#14320] opened 2021-08-15 19:37 UTC
This can result in more score gain without the difficulty increase as the speed of it can be set to 1.01 which does not affect gameplay.
Or it can result in no bonus score gain from using a higher speed.

I'm using the latest version available.
Platform: Linux.

**Comment by frenzibyte** [comment] 2021-08-15 19:38
Duplicate of https://github.com/ppy/osu/issues/7698. Please search.

**Closed by frenzibyte** 2021-08-15 19:38 UTC
