### ISSUE TITLE
Add the function to render replay to video

### ISSUE THREAD

**Issue by poly000** [ppy/osu#10158] opened 2020-09-14 21:29 UTC

**Comment by frenzibyte** [comment] 2020-09-14 21:31
Duplicate of #2967, please search for existing issues before reporting, as mentioned in the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue)

**Closed** 2020-09-14 21:41 UTC
