### ISSUE TITLE
Odd behaviour when toggling "Beatmap hitsounds" mid-replay

### ISSUE THREAD

**Issue by recapitalverb** [ppy/osu#7294] opened 2019-12-19 16:22 UTC
**Describe the bug:** During a replay, toggling the "Beatmap hitsounds" option causes animations in hit objects to act weirdly.

**Screenshots or videos showing encountered issue:** https://youtu.be/AtqWbV7VYp4

**osu!lazer version:** master branch commit 3bd4ba3f9fa842b626d60e47ac817591e0b89009

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3984511/database.log)
[network.log](https://github.com/ppy/osu/files/3984514/network.log)
[performance.log](https://github.com/ppy/osu/files/3984515/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3984516/runtime.log)

**Comment by Gabixel** [comment] 2019-12-19 17:37
Similar to/duplicate of https://github.com/ppy/osu/issues/6104?

**Comment by bdach** [comment] 2019-12-19 17:38
Yeah, the two will most likely be closely related. Closing this & expanding scope of original.

**Closed by bdach** 2019-12-19 17:38 UTC
Labels: bug, replay

**Comment by recapitalverb** [comment] 2019-12-19 17:48
Definitely a duplicate.
