### ISSUE TITLE
Lazer crashes if alt+f4 is pressed before startup intro

### ISSUE THREAD

**Issue by aplefull** [ppy/osu#9016] opened 2020-05-13 19:16 UTC
**Descrition:** 
If you press alt+f4 on "This project in an ongoing wip" screen, game freezes and crashes after intro.

**Video:** 
[streamable](https://streamable.com/ims3q7)
(Pressing altf4 at 0:08)

**Version:** 
2020.508.2

**Logs:**
[performance.log](https://github.com/ppy/osu/files/4624144/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4624145/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4624146/updater.log)
[database.log](https://github.com/ppy/osu/files/4624147/database.log)
[network.log](https://github.com/ppy/osu/files/4624148/network.log)

**Computer Specifications:** 
![image](https://user-images.githubusercontent.com/10453915/81854839-2d283000-9567-11ea-9323-968a1437ceca.png)

**Comment by mouzedrift** [comment] 2020-05-13 19:30
duplicate of #8991

**Closed** 2020-05-13 19:45 UTC
