### ISSUE TITLE
Very very small quality of life thing with a button

### ISSUE THREAD

**Issue by anexistantperson** [ppy/osu#8979] opened 2020-05-09 00:26 UTC
**Describe the new feature:** 
The back button on the song select ( or anywhere else it appears) has its hitbox 1 pixel above the bottom of the screen, this is very infuriating for mouse players because you cant just throw the cursor into the corner of the screen then click to go back to the main menu. you have to move it up one extra pixel every time.
**Proposal designs of the feature:** 
just extend it down 1 pixel plz

**Comment by Joehuu** [comment] 2020-05-09 00:35
Similar to / duplicate of https://github.com/ppy/osu/issues/4216

**Closed by Joehuu** 2020-05-09 00:35 UTC
