### ISSUE TITLE
Add score details when hovering over a score

### ISSUE THREAD

**Issue by Azzirah** [ppy/osu#8975] opened 2020-05-08 13:46 UTC
**Describe the new feature:** When hovering over a score, a little frame should appear stating details of the score, such as the exact time it was submitted,the mods used, as well as the count of 300s, 100s, 50s and misses, pretty much the same way stable does.

**Proposal designs of the feature:** 
![hovering](https://user-images.githubusercontent.com/65025784/81411633-f1463280-9142-11ea-8e6c-ea418cd6162e.jpg)

**Comment by Game4all** [comment] 2020-05-08 13:48
Duplicate of #5906?

**Comment by bdach** [comment] 2020-05-08 14:02
Closing as duplicate.

**Closed by bdach** 2020-05-08 14:02 UTC
