### ISSUE TITLE
Android 14 Pixel 6a dont start

### ISSUE THREAD

**Issue by qwertyuiii-code** [ppy/osu#25144] opened 2023-10-16 14:00 UTC
### Type

Other

### Bug description

I'm have a new device Google Pixel 6a based on android 14, i want test osu!lazer on this device, but it crash

### Screenshots or videos

https://github.com/ppy/osu/assets/85434511/936d4339-c1ca-4853-b9bf-a65472b411e6

### Version

2023.1008.1

### Logs

![Screenshot_20231016-185938](https://github.com/ppy/osu/assets/85434511/f72e8612-cbb0-4d8f-8ead-adcbcd1541ee)
there are no logs to send, so I don’t know where to get them from

**Comment by vegguid** [comment] 2023-10-16 14:01
This is a know issue, see #25020

**Comment by peppy** [comment] 2023-10-16 14:11
Duplicate of #25020.

**Closed by peppy** 2023-10-16 14:11 UTC
