### ISSUE TITLE
Game crashes sometimes after using a lot ctrl+shift+r (random skin) during spectating 

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#10864] opened 2020-11-16 09:37 UTC
**osu!lazer version:** 
2020.1114.0

**Logs:**
[updater.log](https://github.com/ppy/osu/files/5545345/updater.log)
[database.log](https://github.com/ppy/osu/files/5545346/database.log)
[network.log](https://github.com/ppy/osu/files/5545347/network.log)
[performance.log](https://github.com/ppy/osu/files/5545348/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5545349/runtime.log)

**Computer Specifications:** 
OS: windows 10
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8 GB

**Comment by bdach** [comment] 2020-11-16 16:14
Judging from the logs I'm pretty sure this'll be a duplicate of #5798. Closing.

**Closed by bdach** 2020-11-16 16:14 UTC
Labels: area:skinning, type:crash
