### ISSUE TITLE
Pressing "Show more" button will load infinitely if there isn't anymore items

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#26656] opened 2024-01-21 16:07 UTC
### Type

Performance

### Bug description

Probably just shouldn't be there in the first place if there aren't more items.

### Screenshots or videos

[1705852688.webm](https://github.com/ppy/osu/assets/58333920/33bbe7cf-7fe0-4165-abca-db0583fb98cc)

### Version

2024.114.0

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/14001945/shorter_runtime.log)
[shorter_network.log](https://github.com/ppy/osu/files/14001946/shorter_network.log)

**Comment by Gabixel** [comment] 2024-01-21 16:21
Looks like a duplicate of https://github.com/ppy/osu/issues/9203. You can also check that thread for more technical details

**Closed** 2024-01-21 16:32 UTC
