### ISSUE TITLE
osu!Lazer Tournament failing to launch on version 2020.1229.0

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu#11443] opened 2021-01-08 06:40 UTC
I just updated lazer to the most recent version, 2020.1229.0 and now the client is failing to launch in tournament mode.  I can see the app momentarily open in task manager but then it crashes with no visible signs.  Log file shows a stack trace from trying to deserialize a JSON object.

Lazer appears to launch in normal mode just fine, only tournament mode is effected.

## Version ##
2020.1229.0
Windows 10

## Logs ##
Only runtime has things out of the ordinary, but uploading all 3.

[runtime.log](https://github.com/ppy/osu/files/5785604/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5785605/performance.log)
[network.log](https://github.com/ppy/osu/files/5785607/network.log)

**Comment by Snowleopard-osu** [comment] 2021-01-08 06:49
bracket.json
[bracket.zip](https://github.com/ppy/osu/files/5785644/bracket.zip)

**Comment by frenzibyte** [comment] 2021-01-08 07:07
That's a duplicate of https://github.com/ppy/osu/issues/11377, tl:dr you can fix it by deleting bracket.json and starting again.

**Comment by peppy** [comment] 2021-01-08 07:07
Deleting the file is not a valid fix.

**Comment by frenzibyte** [comment] 2021-01-08 07:10
Ah meant it as a local temporary fix, mb.

**Comment by peppy** [comment] 2021-01-08 07:15
It should NOT be considered a local fix. That's basically telling people to throw their ongoing tournaments away. That's not how we deal with issues.

**Closed** 2021-01-08 16:32 UTC
Labels: area:tournament
