### ISSUE TITLE
Grid rotation does not save. (editor)

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu#28895] opened 2024-07-17 16:45 UTC
### Type

Game behaviour

### Bug description

title

### Screenshots or videos

https://youtu.be/JAcqn3C9IN8

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16270552/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-17 19:09
Known issue, see: https://github.com/ppy/osu/pull/28473

**Comment by frenzibyte** [comment] 2024-07-17 19:10
Let's just mark this as a duplicate of https://github.com/ppy/osu/issues/20883

**Closed by frenzibyte** 2024-07-17 19:10 UTC
Labels: area:editor
