### ISSUE TITLE
Score grade is incorrect when lazer replay is exported and re-imported

### ISSUE THREAD

**Issue by JacksonChen666** [ppy/osu#24061] opened 2023-06-27 11:50 UTC
### Type

Cosmetic

### Bug description

I imported a score of my own, clicked to view then saw a contradiction. (See screenshot)

~~I don't know how to better describe these things in the title.~~

[Map](https://osu.ppy.sh/beatmapsets/1234892#fruits/2567137)

[Replay (in a .zip)](https://github.com/ppy/osu/files/11881474/jacksonchen666.playing.nanobii.-.Rainbow.Road.Brunoob.Special.2023-06-26_15-55.osr.zip)

### Screenshots or videos

![](https://github.com/ppy/osu/assets/50755746/ad000d3d-fab5-4712-aa4d-9e4ef9ecb115)

### Version

2023.621.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11881460/database.log)
[input.log](https://github.com/ppy/osu/files/11881461/input.log)
[network.log](https://github.com/ppy/osu/files/11881462/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/11881463/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11881464/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11881465/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11881466/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/11881467/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11881468/runtime.log)

**Comment by monochrome22** [comment] 2023-06-27 14:18
Should be duplicate of https://github.com/ppy/osu/issues/20857.

**Comment by monochrome22** [comment] 2023-06-27 14:32
There was a fail at 0:25, it can be seen by importing the score into stable. Lazer has issues with replay playback, so it might not show.
Was your online score set in multiplayer?

**Comment by novialriptide** [comment] 2024-01-11 09:55
Is this fixed?
<img width="1800" alt="Screenshot 2024-01-11 at 4 47 16 AM" src="https://github.com/ppy/osu/assets/35881688/b029c2f2-b724-4a86-ba61-180e7002ed35">

**Comment by bdach** [comment] 2024-01-11 10:20
![1704968423](https://github.com/ppy/osu/assets/20418176/c21b5bea-fd26-4d35-9978-fe6b8691745e)

if you don't know how bug trackers work, the above generally means that it's not fixed

**Comment by novialriptide** [comment] 2024-01-11 20:29
Yes, but it looks like it's fixed on my end.

**Comment by frenzibyte** [comment] 2024-01-12 05:01
Please clarify your intention next time, and avoid posting screenshots without making sure it shows what you're referring to.

That being said, the accuracy cutoffs has indeed been adjusted in https://github.com/ppy/osu/pull/25601 to match the code snippet mentioned in https://github.com/ppy/osu/issues/24061#issuecomment-1609913748.

However, this has no relevance in the issue thread's main point. As per the title of this thread, the problem is that the score rank gets populated with stable's logic, rather than lazer/`ScoreProcessor`.

**Comment by peppy** [comment] 2024-01-15 06:03
> But upon testing that in real leaderboards, it appears that the accuracy is different on import, potentially being high enough to display a different rank instead

Did you stop investigating at this point? It's a weird place to leave things, just means the next person to follow up is going to have to repeat and continue where you left.

**Comment by peppy** [comment] 2024-01-15 06:04
Bumping to priority 0. Having broken replay round trip is going to cause a lot of headaches as users start to move to lazer.

**Closed** 2024-01-17 10:33 UTC
Labels: priority:0, area:replay
