### ISSUE TITLE
Certain songs changing place after playing when sorting by artist

### ISSUE THREAD

**Issue by SevaOnOss** [ppy/osu#21992] opened 2023-01-01 23:36 UTC
### Type

Game behaviour

### Bug description

when you sort by artist and play a song, after going back in the song menu the song moves places (when sorting by artist). it moves the song if there are other songs by the same artist below it, and it moves the song to the bottom of the same artist's songs.

### Screenshots or videos

https://youtu.be/JwItvjsX9NU

### Version

2022.1228.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/10329674/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10329675/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10329676/updater.log)
[database.log](https://github.com/ppy/osu/files/10329677/database.log)
[input.log](https://github.com/ppy/osu/files/10329678/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10329679/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10329680/network.log)

**Comment by bdach** [comment] 2023-01-01 23:37
Duplicate of #21926

**Closed by bdach** 2023-01-01 23:37 UTC
