### ISSUE TITLE
Long unbroken text overflows popup dialog

### ISSUE THREAD

**Issue by osu-funkyfeelin** [ppy/osu#26200] opened 2023-12-28 22:50 UTC
### Type

Cosmetic

### Bug description

For example, a hyperlink like in the Dec 2023 Project Love message.

### Screenshots or videos

![Screenshot_20231228_172854](https://github.com/ppy/osu/assets/71528455/0969f123-6bf8-4b0e-90bc-5925045da9de)

### Version

2023.1229.0-lazer

### Logs

[1703802503.runtime.log](https://github.com/ppy/osu/files/13789918/1703802503.runtime.log)
[1703802503.performance.log](https://github.com/ppy/osu/files/13789919/1703802503.performance.log)
[1703802503.network.log](https://github.com/ppy/osu/files/13789920/1703802503.network.log)

**Comment by Joehuu** [comment] 2023-12-28 23:04
Duplicate of https://github.com/ppy/osu/issues/10085

**Closed by Joehuu** 2023-12-28 23:04 UTC
