### ISSUE TITLE
Linux: Processing input while window is unfocused

### ISSUE THREAD

**Issue by gabixdev** [ppy/osu#1282] opened 2017-09-16 19:40 UTC
Seems like OpenTK issue, when osu window is not on top it still reacts to input.

**Comment by MrTheMake** [comment] 2017-09-16 19:51
This is very likely a duplicate of https://github.com/ppy/osu-framework/issues/578

**Comment by peppy** [comment] 2017-10-12 03:00
Closing as this is a framework/opentk issue.

**Closed by peppy** 2017-10-12 03:00 UTC
