### ISSUE TITLE
[Android 9] [Xiaomi Mi 8 Lite] Crash reports.

### ISSUE THREAD

**Issue by reschan** [ppy/osu#6596] opened 2019-10-25 00:46 UTC
The game crashes at startup sometimes, usually followed by the osu!direct search bar crash, which makes the game cannot launch. After some times, it can launch again.
Crash at beatmap loading if player touch screens multiple times.
Crash at osu!direct search bar if type too fast.
Phone is a Xiaomi Mi 8 Lite Global, 6GB of ram version. Running Android 9 not rooted.
also is there crash logs save in android, if yes, tell me how to get those and will provide it as soon as possible.
Thanks. Really like the lazer version btw.

**Comment by bdach** [comment] 2019-10-25 00:51
Android logs are in the `Android/Data/sh.ppy.osulazer/logs` directory. However please search for related issues first:

* The direct crash is already tracked at #6264, no need to report it again.
* Is the crash at startup similar to #6315?

I don't recall any reports about crashes during beatmap loading before, please include logs and if possible also a video of that.

**Comment by reschan** [comment] 2019-10-25 01:25
Ah thanks for the quick reply. I'm sorry for the dupes. for the crash at #6315 , it's the same thing.
For the beatmap loading crash, I have only encountered once and currently cannot recreate the crash. I apologize for that.
Does osu!lazer save crash dumps? If not I will save the logs and send asap if I encounter it again hopefully.
Thanks.

**Comment by iiSaLMaN** [comment] 2019-10-25 01:29
All that is required for knowing where the cause is would be in the logs @bdach pointed at, attaching a video would give us precise details on how we can reproduce it. (if you can)

**Comment by peppy** [comment] 2019-10-25 03:38
Closing as duplicate for now.

**Closed by peppy** 2019-10-25 03:38 UTC
