### ISSUE TITLE
Is It Really Like This? 

### ISSUE THREAD

**Issue by NeofetchNpc** [ppy/osu#30742] opened 2024-11-18 06:37 UTC
### Type

Game behaviour

### Bug description

as in the video, that when restarting the map, it's like that, and in my opinion the performance on Android feels like it's decreasing. 

### Screenshots or videos

https://github.com/user-attachments/assets/219e73ca-b468-4b7b-9948-233d9f709679

### Version

latest

### Logs

[logs.zip](https://github.com/user-attachments/files/17795758/logs.zip)

**Comment by smoogipoo** [comment] 2024-11-18 06:38
Duplicate of https://github.com/ppy/osu/issues/30657

Android performance is a work in progress.

**Closed by smoogipoo** 2024-11-18 06:38 UTC
