### ISSUE TITLE
Visual lag during gameplay

### ISSUE THREAD

**Issue by cyrdoctus** [ppy/osu#8271] opened 2020-03-13 20:36 UTC
I have installed the osu!laser recently and I have encountered quite bad performance, I know that it is a developer version, but after seeing other people play with it and don't have the same issue seemed weir.
The issue is about the circles spawning and timing of circles, it is way off and seems very jittery even when the fps monitor is giving way over 800 FPS and under 1 ms latency. the notes just seem off sync, even the circle reacting visually to the click is off, but the press is immediately registered.
So far I have tried reinstalling drivers from gaming one to studio one, and back as well as reinstalling the game.
I have tried the android version and I haven't encountered the same issue at all.

So my question is, is it the current version issue or is it an issue somewhere else. So far I have been using the standard osu launcher but got interested in this one, that's why it felt weird when I have encountered this performance issue.

System specs:
i7 5820k
32 GB ram
RTX 2080 Ti

Game settings: Multicore (Tried single-core and got everything laggy), Framerate unlimited (also tried every other option)

**Comment by oSumAtrIX** [comment] 2020-03-13 22:50
Can confirm, recorded a side by side frame comparison of stable and lazer https://www.youtube.com/watch?v=Trz1HWxgdQs
This started to happen a few releases before

Running 2020.312.0

**Comment by peppy** [comment] 2020-03-14 03:06
> Can confirm, recorded a side by side frame comparison of stable and lazer https://www.youtube.com/watch?v=Trz1HWxgdQs
> 
> This started to happen a few releases before
> 
> 
> 
> Running 2020.312.0
> 
>  

If you know it started happening "a few releases ago" then please take the time to at least go back through each release and confirm this. You can download all old builds from the releases page.

**Comment by oSumAtrIX** [comment] 2020-03-14 17:08
> If you know it started happening "a few releases ago" then please take the time to at least go back through each release and confirm this. You can download all old builds from the releases page.

I don't notice the related issue in releases previous the culprit `2019.1128.0` release. 
It would be helpful if @cyrdoctus can confirmation.

**Comment by cyrdoctus** [comment] 2020-03-14 20:20
> > If you know it started happening "a few releases ago" then please take the time to at least go back through each release and confirm this. You can download all old builds from the releases page.
> 
> I don't notice the related issue in releases previous the culprit `2019.1128.0` release.
> It would be helpful if @cyrdoctus can confirm this.

Can confirm tested all releases past **2019.1113.0** and significant lag or jitteriness around circles approaching was not prominent until version **2019.1128.0**, I have even tested versions **2019.930.0** and **2019.1011.0** and those had only minor lag as it seemed only the sound was off. My test methodology was to run map **Yoru Naku Usagi wa Yume o Miru** on auto and highest difficulty and then tested it on hard difficulty manual, where even cursor click movement was off. To test that this was not truly only sound off, I have run every test past version **2020.208.0** without any sound, which came to the same jitteriness in circles approaching, to verify each 5th run I switched to normal osu launcher (that one run buttery smooth). Also, the lags lowered after version **2020.225.0** or at least they seemed slightly better and that with or without sound, Hopefully this will be helpful. @peppy @oSumAtrIX

**Comment by peppy** [comment] 2020-03-17 02:46
Thanks for providing the version bisect. Could you please open the frame time overlay (Ctrl+F11 until you see graphs) and confirm there are spikes on the audio thread when this occurs?

If so, this is a duplicate of https://github.com/ppy/osu/issues/8185 and can be closed. It matches in terms of commits.

**Comment by cyrdoctus** [comment] 2020-03-17 17:11
> Thanks for providing the version bisect. Could you please open the frame time overlay (Ctrl+F11 until you see graphs) and confirm there are spikes on the audio thread when this occurs?
> 
> If so, this is a duplicate of #8185 and can be closed. It matches in terms of commits.

@peppy Yes it can be closed, after recent update no more lag present, lag spikes at audio are gone.

**Closed** 2020-03-17 17:12 UTC
