### ISSUE TITLE
Missing beats in nightcore mod

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6060] opened 2019-09-10 09:41 UTC
**Describe the missing feature:** 

The beat sounds in nightcore mod are missing.

Stable: https://streamable.com/wlw87
Lazer; https://streamable.com/2c7io

**Comment by souhailelk** [comment] 2019-10-26 19:37
Can I try to solve this issue?

**Comment by CreedsCode** [comment] 2019-10-26 21:19
Wy not, I tried it. But I don't just how to solve it.

**Comment by iiSaLMaN** [comment] 2019-10-27 00:48
@souhailelk Anyone is welcomed to solve any opened issue here unless it's assigned to a specific developer.

**Comment by 2403772980ygy** [comment] 2019-10-30 05:40
It is a skin-based issue I think. osu! Lazer skins, along with the osu! classic ones have no beat sounds. So at first, I didn't reproduce this issue. Please change your skin to a custom one with beat sounds, and try if you can reproduce this issue again, Thanks!

**Comment by phosphene47** [comment] 2019-10-30 06:01
@2403772980ygy wrong. If you read the code https://github.com/ppy/osu/blob/master/osu.Game/Rulesets/Mods/ModNightcore.cs nightcore is not implemented at all. This is not a skin issue.

**Comment by 2403772980ygy** [comment] 2019-10-30 07:55
Ok, I'll try to fix it later, and actually I've already viewed this part of code but this may be implemented in other parts. I'll try to find/fix them.

**Comment by 2403772980ygy** [comment] 2019-10-30 10:24
So I have the NC mod implementation found nowhere. Maybe we should complete it by ourselves......

**Comment by smoogipoo** [comment] 2019-10-31 03:11
Correct, there is no implementation and there are no interfaces for the exact implementation. It needs to be implemented in `ModNightCore` by continually playing a sample at the relevant beats.

* Cymbals every 4 bars,
* otherwise a kick every 2 beats,
* otherwise a clap every second odd beat,
* otherwise a hat.

You can look at other mods for structural references, but you'll need to have another method that gives the mod a skin source to query samples from, and another that gives the clock. The rest can be done in `IUpdateableByPlayfield`.

**Comment by 2403772980ygy** [comment] 2019-10-31 12:55
Well, I didn't get where are the skins implemented. Are they in osu.Framework or just osu?

**Comment by 2403772980ygy** [comment] 2019-11-01 05:17
@smoogipoo May I add a new part named `IUpdatableAudioAddition`? I feel unsafe about simply implement everything in `IUpdatableByPlayField` and `ModNightCore`

**Comment by iiSaLMaN** [comment] 2019-11-01 05:26
What would be the difference between `IUpdatableAudioAddition` and `IUpdatableByPlayfield`? @smoogipoo suggested that it should be on the playfield update interface because it's something to be executed every frame (continuously), and also to be executed when the playfield is loaded and shown on screen.

**Comment by 2403772980ygy** [comment] 2019-11-01 05:29
So there's no difference between those two approaches, right. Actually, I've already deleted that interface...... But I didn't modify my comments yet.

**Comment by 2403772980ygy** [comment] 2019-11-03 09:31
Well, I've concluded my problems as follows:

1. not confident of adding so much things in `NightCoreMod.cs`.
2. not being able to access other parts of the code because not being familiar with them.

So do we have a class reference or something like that? I'm willing to help much, but I have these problems, can someone help me out?

**Comment by iiSaLMaN** [comment] 2019-11-03 15:37
> Well, I've concluded my problems as follows:
> 
> 1. not confident of adding so much things in `NightCoreMod.cs`.
> 2. not being able to access other parts of the code because not being familiar with them.
> 
> So do we have a class reference or something like that? I'm willing to help much, but I have these problems, can someone help me out?

I think It would be best to take a good look at the source code and test with it for understanding how it functions, and if you were concerned about something related to the code or need help with it, you can reach us on the [osu!dev discord server](https://discord.gg/ppy) as we help you potentially help us there!

**Closed** 2019-12-18 09:28 UTC
Labels: audio, good first issue, mods, pending review
