### ISSUE TITLE
Support adding sliders on mobile releases via touch

### ISSUE THREAD

**Issue by nagi-desuuu** [ppy/osu#19422] opened 2022-07-27 17:59 UTC
### Type

Game behaviour

### Bug description

On mobile releases, a slider could not be placed in the editor by any means without hooking up external hardware like keyboards or mice.
For clarification, the user can only put in control points for the slider, not the actual slider itself.

### Screenshots or videos

https://user-images.githubusercontent.com/75596775/181339184-4700fda5-f38d-4073-8988-af965073e303.mp4

### Version

2022.723.0

### Logs

The logs have been condensed to a single zip file for convenience.
[logs.zip](https://github.com/ppy/osu/files/9202397/logs.zip)

**Comment by frenzibyte** [comment] 2022-07-28 06:08
Will be made possible once https://github.com/ppy/osu-framework/pull/5255 gets in.

**Comment by peppy** [comment] 2022-07-28 06:08
I still think this deserves its own attention. Having to hold very still in one place to finish a slider placement doesn't sound like something a user would figure out on their own.

There should be an "end placement" button or something similar.

**Comment by papertek** [comment] 2022-09-08 20:23
> I still think this deserves its own attention. Having to hold very still in one place to finish a slider placement doesn't sound like something a user would figure out on their own.
> 
> There should be an "end placement" button or something similar.

what about double tapping quickly?

**Comment by foxtail286** [comment] 2023-02-08 17:18
I also think that a 'Finalize' button would be more effective than long tapping the end, because this would be a lot more understandable to the user. Either that, or detect when the user taps outside of the playfield in the editor and automatically finalize the slider.

**Comment by bdach** [comment] 2024-07-05 13:09
While adding sliders is *technically possible* now via the drawing thing, it's broken, by which I mean that if you try to drag a finger to draw, it will trigger a selection box instead, and only begin to working as intended if you lift the finger and drag one again. I wanted to look into fixing it today and wasted several hours in a pit of despair to the point that I cannot justify spending any more.

The most I have to show for this is the fact that I'm _pretty_ sure this is caused by the following behaviour:

https://github.com/ppy/osu/blob/master/osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs#L326-L327

This happens on update, so if an input instantly warps from outside the playfield to inside of it, the blueprint will not be created in time, thus it will not receive the correct inputs, meaning that it will not be in the proper initial state to receive input.

To that end I tried many different changes to attempt to ensure that the blueprint is created and that the inputs it potentially dropped are propagated correctly, but it still doesn't work, and I don't know why, and I can't debug either because android tooling is dogwater garbage as usual.

**Comment by bdach** [comment] 2024-07-05 13:13
....which is apparently tracked as https://github.com/ppy/osu/issues/26509, which i couldnt find

whatever closing this one as a duplicate at this point

**Closed by bdach** 2024-07-05 13:13 UTC
Labels: area:editor, type:behavioural, platform/mobile
