### ISSUE TITLE
Osu running in the background on mobile

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#12470] opened 2021-04-18 01:40 UTC
When moving to a different screen or to your home on osu mobile it would run in the background with less usage of the phone so you can conserve battery and memory so you can go back to what you were doing when you go back into the app. You would also be able to listen to music in the background.

**Comment by PercyDan54** [comment] 2021-04-18 02:06
Duplicate of ppy/osu-framework#4200

**Comment by frenzibyte** [comment] 2021-04-18 02:14
Closing as duplicate of the above issue, not sure if you'll be able to listen to music while in the background though.

**Closed by frenzibyte** 2021-04-18 02:14 UTC

**Comment by peppy** [comment] 2021-04-18 05:27
"Listening to music" is out of scope of a game. Please use an app like Spotify for that.
