### ISSUE TITLE
A must have feature

### ISSUE THREAD

**Issue by Styxrich** [ppy/osu#12358] opened 2021-04-10 06:09 UTC
**Describe the new feature:** 
Andriod, Mobile: 
1) Feedback: Change the way how Osu works by not allowing portrait mode and only landscape mode while playing.

**Comment by tybug** [comment] 2021-04-10 06:38
duplicate of https://github.com/ppy/osu/issues/4394

**Comment by peppy** [comment] 2021-04-10 06:46
Also your device should have a rotation lock hardware or software control which you can use for this purpose.

**Closed by peppy** 2021-04-10 06:46 UTC

**Comment by Styxrich** [comment] 2021-04-10 08:43
I understand that there is a rotation lock software control but it is only
for navigation bar. How about thoese people with gestures? Many of my
friends are also would osu to have this rotational lock feature in the app
itself as everyone of them including me are too used to using gestures.
That is the reason for this feedback.
