### ISSUE TITLE
Cant Join in a room or Create Multiplayer room in android 

### ISSUE THREAD

**Issue by hnsrl07** [ppy/osu#11480] opened 2021-01-14 07:02 UTC
**Describe the crash:** 
I cant join in multiplayer rooms and create rooms in android
**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/77430999/104555830-7a6e1b80-5679-11eb-8975-48efee341634.png)

**osu!lazer version:** 
2021.109.0
**Logs:**

**Computer Specifications:**

**Comment by bdach** [comment] 2021-01-14 07:04
Duplicate of #11385

**Closed by bdach** 2021-01-14 07:04 UTC
