### ISSUE TITLE
Dragging the end anchor point to the start of the slider causes a crash 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#5538] opened 2019-07-30 19:52 UTC
**Describe the crash:** 
When youre in the editor, selecting a slider gives you the option to change the angle of them with those anchor points ( i hope they were called that way ) when you drag the end to the start the slider just expands and the game crashes 

**Screenshots or videos showing encountered issue:** 
https://streamable.com/je2eo

**osu!lazer version:** 
8caf9ad 

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3448579/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3448580/runtime.log)

**Computer Specifications:** 
i3 6100 8GB ram GTX 1050Ti Windows 10 x64 1903

**Comment by smoogipoo** [comment] 2019-08-19 04:00
Fixed via https://github.com/ppy/osu-framework/pull/2756

**Comment by Lolihunter1337** [comment] 2019-10-24 17:30
@smoogipoo I managed to get a crash again from that however this time it seems to Crash due to the application ( osu! ) requesting more GPU memory than available 
[NVIDIA OPENGL.txt](https://github.com/ppy/osu/files/3768721/NVIDIA.OPENGL.txt)
[database.log](https://github.com/ppy/osu/files/3768722/database.log)
[network.log](https://github.com/ppy/osu/files/3768723/network.log)
[performance.log](https://github.com/ppy/osu/files/3768724/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3768725/runtime.log)

**Comment by peppy** [comment] 2019-10-25 02:08
i think i managed to reproduce this too, quite recently. reopening for now.

**Comment by peppy** [comment] 2019-11-01 01:17
Not so simple to fix, moving out of milestone for now.

**Comment by bdach** [comment] 2020-11-09 07:33
How opposed would we be to fixing this framework-side by refusing to approximate a perfect slider segment if the three control points are "too collinear", so to speak? That's what I have and it seems to have some hope, it just needs some tweaking of the cutoff threshold of the angle at which to stop approximating.

**Comment by peppy** [comment] 2020-11-09 08:04
Could we potentially refuse the returned output rather than making a framework change?

**Comment by bdach** [comment] 2020-11-09 08:08
Actually now that I think about it we can probably just not call the approximation game-side in the regressive case and it looks like something stable's already doing somewhere. I did have a weird case where a "normal" slider (as in one that doesn't have its endpoints "on the same side" of the midpoint) also pixelated a bit, so I think there might be an actual framework fix to be had there, but I'll have to re-read the code to make sure.

**Comment by smoogipoo** [comment] 2020-11-09 08:36
Beatmap decoding already has a check for colinear paths https://github.com/ppy/osu/blob/567cf932f18b567449d7a7777aa7015499344404/osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs#L359-L360
I believe the framework fix would be to limit the maximum resolution at a BufferedContainer level, but that check is probably something we want at a blueprint level anyway.

**Comment by bdach** [comment] 2020-11-09 08:39
I think that resolution is already limited - see this regressive case I posted on discord:

![2020-11-09-093614_1411x815_scrot](https://user-images.githubusercontent.com/20418176/98518164-52280200-226f-11eb-9277-9f380581abfb.png)

That check is actually somewhat bogus as far as I can tell as it attempts to use the cross product to compute the sine and check for collinearity but doesn't normalise by length first, so it won't catch actual cases if the length of the segments is large enough.

**Comment by smoogipoo** [comment] 2020-11-09 08:48
All it's doing is checking for linear (in)dependence between vectors, which doesn't require normalisation afaik?

**Comment by bdach** [comment] 2020-11-09 08:50
Mathematically speaking it doesn't but we're talking floats and `Precision.AlmostEquals` level here. As far as I can tell any non-trivial increase in segment lengths will make the check stop working, and that's what I observed in my experiments as well.

**Comment by Pennek** [comment] 2020-11-13 03:25
is this not a duplicate of #3858 ?

**Comment by peppy** [comment] 2020-11-13 03:32
It is, but I'll close that one as it has less attention than this one does.

**Closed** 2021-04-08 06:18 UTC
Labels: area:editor, priority:0, ruleset:osu!
