### ISSUE TITLE
Rotate beatmap in portrait

### ISSUE THREAD

**Issue by UnderSampled** [ppy/osu#11693] opened 2021-02-06 15:08 UTC
Playing on a mobile device, portrait mode is the preferred way to interact with the menus, and the interface adapts well. This same adaptive aspect affects gameplay as well, but places the beatmap at a very small portion of the middle of the screen, with tiny bit circles. Once you have started a song, it is too late to rotate, and you will be stuck with this sub-par experience.

In my experience, with a few exceptions when sliders are used to draw an image, it does not matter what orientation beatmaps are presented in. The relative positions and distances are the same, and it's less of a change than mirroring. I have played with a screen locked in landscape before, and it plays fine, but the numbers and HUD are all sideways if you do this.

So, my proposal is that, when the screen is in portrait mode, beatmaps (or the playfield) should be rotated 90 degrees.

This rotation is would also be applied during beatmap creation, so if someone creates a beatmap in portrait, it will be saved in landscape. When played in portait, it would play as the mapper intended, so they may wish to add that to their description, if it were to make a difference.

**Comment by bdach** [comment] 2021-02-06 15:09
Duplicate of #7276

**Closed by bdach** 2021-02-06 15:09 UTC
