### ISSUE TITLE
osu!lazer won't open

### ISSUE THREAD

**Issue by OsuTheBest** [ppy/osu#10639] opened 2020-10-31 15:54 UTC
**Describe the crash:** 
When I install osu!lazer it doesn't open. But when I go to task manager it is open.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
2020.1031.0
**Logs:**
2020-10-31 15:33:15 [verbose]: ----------------------------------------------------------
2020-10-31 15:33:15 [verbose]: runtime Log for Administrator (LogLevel: Verbose)
2020-10-31 15:33:15 [verbose]: osu 2020.1031.0.0
2020-10-31 15:33:15 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 2 cores
2020-10-31 15:33:15 [verbose]: ----------------------------------------------------------

**Computer Specifications:** 
Windows 10 Pro 
4GB ram
Intel core 2 duo 2.00GHz
Intel HD 620

**Comment by bdach** [comment] 2020-10-31 15:56
Is what you pasted the entirety of the log file? If not, please attach the whole file by dragging and dropping into the comment box.

If there is no more info there, please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by OsuTheBest** [comment] 2020-10-31 15:59
I copied everything in the log. I don't know why there's like hardly anything.

**Comment by bdach** [comment] 2020-10-31 16:02
that's what I'm trying to determine by asking you to perform steps outlined above.

also, what is task manager showing? CPU, memory, GPU usage?

**Comment by OsuTheBest** [comment] 2020-10-31 16:03
Its showing CPU memory and disk

**Comment by bdach** [comment] 2020-10-31 16:04
let me clarify the question: is lazer using up a high level of all three at the same time? that sounds concerning.

also, how long have you waited for it to load?

**Comment by OsuTheBest** [comment] 2020-10-31 16:07
No, It's using 0% CPU and memory, but its using 1% of my Disk

**Comment by OsuTheBest** [comment] 2020-10-31 16:08
I waited about 12 minutes

**Comment by bdach** [comment] 2020-10-31 16:08
please perform the steps I listed above. we can't proceed much further than this off the information you've provided thus far alone.

**Comment by OsuTheBest** [comment] 2020-10-31 16:11
It says "Snap-in Unavailable"

**Comment by OsuTheBest** [comment] 2020-10-31 16:15
These are the three errors that appear when I open osu!lazar
Log Name:      Application
Source:        Windows Error Reporting
Date:          10/31/2020 9:13:31 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      N/A
Description:
Fault bucket 1396762832701908661, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: osu!.exe
P2: 0.0.0.0
P3: 5f1757ad
P4: coreclr.dll
P5: 4.700.20.36602
P6: 5f10946b
P7: c0000005
P8: 0000000000191d5b
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER434.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER150E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER159B.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20201023 1 Event Collector_0_inject.etl
\\?\C:\Users\Administrator\AppData\Local\Temp\WER1B0B.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\Users\Administrator\AppData\Local\Temp\WER1B1B.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B27.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1BF3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_osu!.exe_faaa311954768bbc8faa8241f9f3234853e3a47a_50d1e379_101aeacd-915c-4e98-bef9-bb8c4eaa1604

Analysis symbol: 
Rechecking for solution: 0
Report Id: 178606e7-c7e8-4a23-9f9c-ae2b9fa2a9f0
Report Status: 268435456
Hashed bucket: 1a650027b3bdc41993624c655eaa66b5
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-31T16:13:31.7294539Z" />
    <EventRecordID>21899</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-JH15KOM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1396762832701908661</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f1757ad</Data>
    <Data>coreclr.dll</Data>
    <Data>4.700.20.36602</Data>
    <Data>5f10946b</Data>
    <Data>c0000005</Data>
    <Data>0000000000191d5b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER434.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER150E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER159B.tmp.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace User Logger 20201023 1 Event Collector_0_inject.etl
\\?\C:\Users\Administrator\AppData\Local\Temp\WER1B0B.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\Users\Administrator\AppData\Local\Temp\WER1B1B.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1B27.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1BF3.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_osu!.exe_faaa311954768bbc8faa8241f9f3234853e3a47a_50d1e379_101aeacd-915c-4e98-bef9-bb8c4eaa1604</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>178606e7-c7e8-4a23-9f9c-ae2b9fa2a9f0</Data>
    <Data>268435456</Data>
    <Data>1a650027b3bdc41993624c655eaa66b5</Data>
    <Data>0</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          10/31/2020 9:13:23 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      N/A
Description:
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5f1757ad
Faulting module name: coreclr.dll, version: 4.700.20.36602, time stamp: 0x5f10946b
Exception code: 0xc0000005
Fault offset: 0x0000000000191d5b
Faulting process id: 0x2ed4
Faulting application start time: 0x01d6afa0bc8fed77
Faulting application path: C:\Users\Administrator\AppData\Local\osulazer\app-2020.1031.0\osu!.exe
Faulting module path: C:\Users\Administrator\AppData\Local\osulazer\app-2020.1031.0\coreclr.dll
Report Id: 178606e7-c7e8-4a23-9f9c-ae2b9fa2a9f0
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-31T16:13:23.4546974Z" />
    <EventRecordID>21898</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-JH15KOM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>osu!.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5f1757ad</Data>
    <Data>coreclr.dll</Data>
    <Data>4.700.20.36602</Data>
    <Data>5f10946b</Data>
    <Data>c0000005</Data>
    <Data>0000000000191d5b</Data>
    <Data>2ed4</Data>
    <Data>01d6afa0bc8fed77</Data>
    <Data>C:\Users\Administrator\AppData\Local\osulazer\app-2020.1031.0\osu!.exe</Data>
    <Data>C:\Users\Administrator\AppData\Local\osulazer\app-2020.1031.0\coreclr.dll</Data>
    <Data>178606e7-c7e8-4a23-9f9c-ae2b9fa2a9f0</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          10/31/2020 9:13:21 AM
Event ID:      1023
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      N/A
Description:
Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFABDCF1D5B (00007FFABDB60000) with exit code c0000005.

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1023</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-10-31T16:13:21.1694513Z" />
    <EventRecordID>21897</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-JH15KOM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFABDCF1D5B (00007FFABDB60000) with exit code c0000005.
</Data>
  </EventData>
</Event>

**Comment by bdach** [comment] 2020-10-31 16:19
unfortunately that error doesn't tell us very much at all. it's an access violation exception, which might be caused by a faulty device driver, but we have no way of telling where it happened or why from this info alone. we've seen some like these before (#5708, #10174).

tentatively closing as inactionable / partially duplicate. please try updating your device drivers - that might help.

**Closed by bdach** 2020-10-31 16:19 UTC
Labels: missing details

**Comment by smoogipoo** [comment] 2020-11-02 02:43
Also this is likely to be fixed by installing all Windows updates.
