### ISSUE TITLE
Scroll truncated titles

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7794] opened 2020-02-11 20:22 UTC
**Describe the new feature:** Instead of truncating a song's title, how about having it scroll back and forth, like in music players?
Here's Winamp for reference:

![lol](https://user-images.githubusercontent.com/15932372/74275634-8be5cf80-4d14-11ea-99be-0a907cfca32b.gif)

**Comment by bdach** [comment] 2020-02-11 20:26
Duplicate of #3504

**Closed by bdach** 2020-02-11 20:26 UTC
