### ISSUE TITLE
Incorrect display of the downloaded map

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#7706] opened 2020-02-01 19:13 UTC
**Describe the bug:** 
The map is loaded, initialized, but does not appear in the list, however, it plays in the main menu
**Screenshots or videos showing encountered issue:** 
https://youtu.be/Km3yABidpHY
**osu!lazer version:** 
Lazer 2020.130.0

**Logs:** 
[network.log](https://github.com/ppy/osu/files/4143138/network.log)
[performance.log](https://github.com/ppy/osu/files/4143135/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4143136/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4143137/updater.log)

**Comment by bdach** [comment] 2020-02-01 19:41
Mind attaching your `client.db` file for investigation?

**Comment by Moltanicaa** [comment] 2020-02-01 19:44
sorry
[client.zip](https://github.com/ppy/osu/files/4143158/client.zip)

**Comment by mcendu** [comment] 2020-02-01 23:35
I wonfer if a link to the beatmap that causes problems would be useful.

**Comment by bdach** [comment] 2020-02-01 23:38
It's https://osu.ppy.sh/beatmapsets/885178#osu/1850114 (as indicated by `runtime.log`).

**Comment by Joehuu** [comment] 2020-02-01 23:57
This would be a duplicate of https://github.com/ppy/osu/issues/7708, but lazer wrongly recognizes the star rating. I entered this state by pressing the go-to button in direct, enter, and esc.

![image](https://user-images.githubusercontent.com/35318437/73600836-2b33e700-450b-11ea-8545-4432a49e0cc6.png)

![image](https://user-images.githubusercontent.com/35318437/73600810-a34ddd00-450a-11ea-87d7-d529083cc684.png)

**Comment by bdach** [comment] 2020-02-02 00:18
The star rating part is probably due to very large BPM (one timing point in that map has a beat length of `6E-298`), so let's track that over at #750 with other map irregularities.

Since both parts of the issue turned out to be duplicated elsewhere, closing.

**Closed** 2020-02-02 00:18 UTC
Labels: database, import, song select
