### ISSUE TITLE
(IOS) Touch Screen tapping

### ISSUE THREAD

**Issue by deducted** [ppy/osu#4965] opened 2019-06-08 15:42 UTC
**Describe the new feature:** 

**Proposal designs of the feature:** 

Just like in the andriod version of osu (opsu!) they have a distinct tapping feature where u can drag with one hand and tap with the other and I would love it if it could come to osu lazer

**Comment by peppy** [comment] 2019-06-08 15:43
Duplicate of #4201.

**Closed by peppy** 2019-06-08 15:43 UTC
