### ISSUE TITLE
Score not submitting if you press escape at the end of a song.

### ISSUE THREAD

**Issue by KeijiMizumura** [ppy/osu#7038] opened 2019-12-02 07:55 UTC
**Describe the bug:** If you press escape at the end of a song, it will not bring you to the results and you must click escape again because you will be stuck. Pressing escape again will bring you back to song select and your score is not submitted. 

**osu!lazer version:** 2019.1128.0

**Comment by bdach** [comment] 2019-12-02 17:25
Most likely a duplicate of #6848.

**Closed by bdach** 2019-12-02 17:25 UTC
