### ISSUE TITLE
Choppy audio over Bluetooth headphones on mobile

### ISSUE THREAD

**Issue by MishterKirby** [ppy/osu#9214] opened 2020-06-04 17:29 UTC
**Describe the bug:** 
Audio sounds choppy and game lags when my Bluetooth headphones connect to my phone
**osu!lazer version:** 
2020.523.0
**Logs:**

[database.log](https://github.com/ppy/osu/files/4731732/database.log)
[network.log](https://github.com/ppy/osu/files/4731733/network.log)
[performance.log](https://github.com/ppy/osu/files/4731734/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4731735/runtime.log)

**Comment by frenzibyte** [comment] 2020-06-04 17:31
Have you confirmed it wasn't a bad connection between your bluetooth headphones and your phone? (i.e. have you checked other apps, do you listen just fine)

**Comment by bdach** [comment] 2020-06-04 17:31
Generally latency is pretty much to be expected over Bluetooth. If you don't want latency, use wired headphones.

**Comment by Kashouryo** [comment] 2020-06-04 17:31
Bluetooth headphones are not recommended for osu! gaming. Since they can introduce audio latency.

**Comment by MishterKirby** [comment] 2020-06-04 18:21
Everything else works fine, and I tried with my sister's headphones and the same thing happened. Also, it's not latency, it sounds like it freezes for a millisecond, plays a sound, freezes again, etc.

**Comment by bdach** [comment] 2020-06-04 18:28
"lag" is not specific enough information for us to act on. Unless you'd like to provide more information please look out for performance improvements that will be coming, as performance is a constant work-in-progress.

**Comment by Gabixel** [comment] 2020-06-04 18:34
Actually I can confirm something like this. Somehow Bluetooth headphones seem to have some issues with audio (latency excluded), the music seems to stop and resume every few milliseconds. Also, on previous versions I was able to see this issue in the `NowPlayingOverlay`: the music button always changed from "pause" to "resume" and vice-versa very quickly.
I don't have much information to confirm this, but it doesn't seem to be just a latency issue.

**Comment by MishterKirby** [comment] 2020-06-04 18:35
> 
> 
> Actually I can confirm something like this. Somehow Bluetooth headphones seem to have some issues with audio (latency excluded), the music seems to stop and resume every few milliseconds. Also, on previous versions I was able to see this issue in the `NowPlayingOverlay`: the music button always changed from "pause" to "resume" and vice-versa very quickly.
> I don't have much information to confirm this, but it doesn't seem to be just a latency issue.

Exactly my problem

**Comment by bdach** [comment] 2020-06-04 18:40
While I can corroborate that this is the case, I'm not convinced spending time on resolving it is worth the time as even if that issue is fixed gameplay experience over bluetooth is likely to be subpar. I suppose it *is* an actual issue so I'll reopen, but in my view this is very low priority so I'd recommend just using wired headphones for now.

**Comment by MishterKirby** [comment] 2020-06-04 18:49
I just tested on a spare device with the same pair of headphones, and it worked.

**Comment by peppy** [comment] 2020-06-07 10:59
Can those experiencing this confirm it's only an issue in lazer, and not osu-stable?

**Comment by enoslayd** [comment] 2020-06-07 11:35
Theres no osu stable for mobile

**Comment by Jeremiidesu** [comment] 2020-06-07 11:49
Can't reproduce the issue on my end. (Galaxy S8, running Android 10 and using a RYGHT PARTY ROCK XXL bluetooth speaker) Only extreme latency which was expected.

No choppiness either when using the Bluetooth speaker on Windows against latest master at the time of this comment, only moderate latency.
No choppiness, same latency on current osu-stable.

**Comment by peppy** [comment] 2020-06-07 12:32
Right, so this is android specific. I'm going to close the issue for now as we're a long way off being able to consider these edge cases. You won't be able to play well with bluetooth audio in the first place.

**Closed by peppy** 2020-06-07 12:32 UTC
Labels: framework-fix-required, low-priority, platform:mobile, type:audio
