### ISSUE TITLE
Black In-game screenshots since 2023.326.0 update

### ISSUE THREAD

**Issue by aL1NaZ4R** [ppy/osu#23063] opened 2023-03-30 15:19 UTC
### Type

Game behaviour

### Bug description

Taking Screenshots with ingame screenshot keybind became problematic after 326 update. (I realized it now)
Note that they are not corrupted, just black.

Resolution: 1920x1080@75Hz Exclusive Fullscreen, Renderer: Direct3D 11, Hardware Acceleration is on
\+ Tested it with both formats (JPG & PNG) and Show cursor is off
\+ I've changed my screenshot keybind to F5

### Screenshots or videos

![image](https://user-images.githubusercontent.com/89677246/228882114-1625b924-3ee7-4283-a49a-3bd070d18b86.png)
![image](https://user-images.githubusercontent.com/89677246/228883380-e6ccd280-453e-4adc-9ef5-703f1062eb78.png)

### Version

2023.326.0 / 2023.326.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11113181/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11113182/updater.log)
[database.log](https://github.com/ppy/osu/files/11113183/database.log)
[input.log](https://github.com/ppy/osu/files/11113184/input.log)
[network.log](https://github.com/ppy/osu/files/11113185/network.log)
[performance.log](https://github.com/ppy/osu/files/11113186/performance.log)

**Comment by peppy** [comment] 2023-03-30 15:31
Duplicate of https://github.com/ppy/osu/issues/22959. Switch to legacy opengl if you need this immediately, else it should be fixed in the next release.

**Closed by peppy** 2023-03-30 15:31 UTC
