### ISSUE TITLE
Cloud Sync for Beatmaps and Rulesets

### ISSUE THREAD

**Issue by GiraffeMan3125** [ppy/osu#8783] opened 2020-04-17 18:52 UTC
**Describe the new feature:** 
People sometimes have to use a different computer or their computer breaks, But when you reinstall osu!, you need to remember all the beatmaps you had. 
It's the same issue with custom rulesets but it happens every time you update. When custom rulesets are fully implemented, maybe, add a way to at least transfer the rulesets form one osu!lazer version to another.
**Proposal designs of the feature:** 
Every time you get a beatmap (or eventually a ruleset), the name (or ID if that's a thing) of the beatmap could be saved so the next time you sign into a version of osu!lazer that you've never signed into, It could download the beatmaps (and rulesets) that you have downloaded previously and isn't on the device already.

This would help me out a ton. Please find a way to, at least, sync beatmaps.

**Comment by LittleEndu** [comment] 2020-04-17 19:00
Technically duplicate of #2351 

peppy said he wants easier access to beatmaps so that users wouldn't feel the need to download their entire collection.

**Comment by bdach** [comment] 2020-04-17 19:05
Closing as duplicate.

**Closed by bdach** 2020-04-17 19:05 UTC
