### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Rockageek** [ppy/osu#14069] opened 2021-07-30 17:57 UTC
**Describe the bug:** 
Game won't start since Lazer 2021.707.0
Issue might be a duplicate of #13769
**Screenshots or videos showing encountered issue:** 
Clicking on the .exe, game doesn't launch anymore.
**osu!lazer version:** 
Lazer 2021.724.1, tried older ones as well as the one fixing realm libraries for windows 8.1 (#13859)
**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6909248/runtime.log)

I'm running windows 8.0, I know that no one ever is on it anymore but still.

**Comment by bdach** [comment] 2021-07-30 18:29
It is a duplicate of said issue. Closing as such.

**Closed by bdach** 2021-07-30 18:29 UTC

**Comment by Rockageek** [comment] 2021-07-30 18:59
But the other one is closed and locked, that's why I opened it.

**Comment by bdach** [comment] 2021-07-30 19:09
Yes, well, unless realm adds support for Windows versions below 8.1 or we decide to use a different database backend going forward Windows 7 and 8.0 will remain unsupported for the time being. We are aware of this being an issue, however, and we'll assess whether support can and should be introduced.

However, do note that 8.0 is not supported even by Microsoft itself since 2016.

**Comment by Rockageek** [comment] 2021-07-30 19:19
Thanks for taking the time to explain !
