### ISSUE TITLE
Can't put music on osu!lazer editor

### ISSUE THREAD

**Issue by guylolol54** [ppy/osu#18855] opened 2022-06-26 18:50 UTC
### Type

Game behaviour

### Bug description

When i am on the osu!lazer (android ver) editor, when im on the setup screen i cant get music get to the folder with the music it doesn't show the mp3 file.

### Version

2022.621.0

### Logs

there isnt any problem in the logs i think

**Comment by bdach** [comment] 2022-06-26 19:11
duplicate of #11911

**Closed by bdach** 2022-06-26 19:11 UTC
