### ISSUE TITLE
In-Game skin color editor

### ISSUE THREAD

**Issue by SevenChords** [ppy/osu#11699] opened 2021-02-07 23:52 UTC
I personally always adjust the skin colors to my own liking, and i think many other players do this as well.
Problem (at least for mac users) however is that you can only adjust the skin colors in the skin.ini file, which is inaccessible in the lazer file structure. Exporting the skin works fine, you can change the colors in the skin.ini of the exported skin, but afterwards there is no way (that i saw) to get the edited skin back into osu (at least on mac). Renaming a zip file to a .osk doesn't change the file type in newer macos versions (running macos big sur, version 11.1), it is still a zip file, despite the changed extension, which doesn't import the skin when dragged onto the osu lazer window.

It would be really nice to either have a skin importer that can import zips/folders, to have an additional tool that can convert a .zip into a real .osk or, in my opinion the most user friendly option, make it possible to change the combo colors of the currently active skin in-game.

All the methods for converting a skin folder/zip into a skin osk that i found online require either the stable client (completely impossible to install on any macos version since catalina) or renaming the file (which doesn't change the extension anymore since big sur)

**Comment by LeNitrous** [comment] 2021-02-07 23:55
Duplicate of https://github.com/ppy/osu/issues/6883 as it covers the entirety of skin editing in-game.

**Closed** 2021-02-07 23:56 UTC
