### ISSUE TITLE
Crash after creating collection called "All beatmaps"

### ISSUE THREAD

**Issue by Stoppedpuma** [ppy/osu#25834] opened 2023-12-18 10:43 UTC
### Type

Crash to desktop

### Bug description

Discovered while trying to break things to find edge case bugs. Causes hard crash and prevents game from moving past main menu after reopening.

Steps to reproduce: right click map to add to new collection -> create new collection called "All beatmaps" -> crash

Terminal crash output:

Unhandled exception. System.ArgumentException: The item osu.Game.Collections.CollectionFilterMenuItem already exists in this Dropdown.
   at osu.Framework.Graphics.UserInterface.Dropdown`1.addDropdownItem(T value, Nullable`1 position)
   at osu.Framework.Graphics.UserInterface.Dropdown`1.collectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at osu.Framework.Bindables.BindableList`1.addRange(IList items, HashSet`1 appliedInstances)
   at osu.Framework.Bindables.BindableList`1.addRange(IList items, HashSet`1 appliedInstances)
   at osu.Framework.Bindables.BindableList`1.AddRange(IEnumerable`1 items)
   at osu.Game.Collections.CollectionDropdown.collectionsChanged(IRealmCollection`1 collections, ChangeSet changes) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Game/Collections/CollectionDropdown.cs:line 70
   at Realms.NotificationCallbacks`1.Notify(ChangeSet changes, Boolean shallow)
   at Realms.RealmCollectionBase`1.Realms.INotifiable<Realms.NotifiableObjectHandleBase.CollectionChangeSet>.NotifyCallbacks(Nullable`1 changes, Boolean shallow)
   at Realms.NotifiableObjectHandleBase.NotifyObjectChanged(IntPtr managedHandle, CollectionChangeSet* changes, Boolean shallow)

### Version

2023.1218.0

### Logs

[shorter_runtime.log](https://github.com/ppy/osu/files/13702731/shorter_runtime.log)

**Comment by bdach** [comment] 2023-12-18 10:50
let me guess you pressed "compact realm" or something

either way, invariably will end up being a duplicate of #25815

**Comment by Stoppedpuma** [comment] 2023-12-18 10:53
> let me guess you pressed "compact realm" or something
No, I created a new collection called "All beatmaps" and it caused the game to crash, it crashes after relaunching and trying to go past the main menu as well.

**Comment by bdach** [comment] 2023-12-18 11:00
that would be salient information to include in the opening post rather than trying to suggest a solution

**Comment by Stoppedpuma** [comment] 2023-12-18 11:04
My bad, I included it in the title should've include it in description as well

**Comment by Stoppedpuma** [comment] 2023-12-18 11:07
Also unrelated to fixing is there a way to remove this from collections for the time being without deleting all collections? Apparently I didn't backup my client.realm.

**Comment by bdach** [comment] 2023-12-18 11:12
you will have to wait for the hotfix (should be out shortly). or you could try removing it via [realm studio](https://www.mongodb.com/docs/realm/studio/).

**Closed** 2023-12-18 15:32 UTC
Labels: priority:0, type:reliability
