### ISSUE TITLE
osu!lazer won't open

### ISSUE THREAD

**Issue by alexkoala** [ppy/osu#6947] opened 2019-11-24 14:29 UTC
**Describe the bug:** 
osu!lazer won't open.

**osu!lazer version:** 
2019.1122.0

**Logs:** 
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at osuTK.Graphics.ES30.GL.BindFramebuffer(osuTK.Graphics.ES30.FramebufferTarget, Int32)
   at osu.Framework.Graphics.OpenGL.GLWrapper.BindFrameBuffer(Int32)
   at osu.Framework.Graphics.OpenGL.GLWrapper.Reset(osuTK.Vector2)
   at osu.Framework.Platform.GameHost.DrawInitialize()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by bdach** [comment] 2019-11-24 14:31
Please state your platform, attach system specifications and full logs here.

**Comment by alexkoala** [comment] 2019-11-24 14:41
> Please state your platform, attach system specifications and full logs here.

**OS:** Windows 10 1909
**CPU:** Intel i5-2557M
**GPU:** HD Graphics 3000
**RAM:** 4GB
**.NET SDK version:** 3.0.101 (x64)

[runtime.log](https://github.com/ppy/osu/files/3883687/runtime.log)

**Comment by bdach** [comment] 2019-11-24 14:48
99% certain this is a duplicate of #6496; closing.

**Closed by bdach** 2019-11-24 14:48 UTC
Labels: hard crash / startup crash, missing details
