### ISSUE TITLE
Make gameplay pause screen buttons be keyboard clickable like in stable

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#12370] opened 2021-04-11 20:28 UTC
**Describe the new feature:** In stable, when you pause or you fail, you can click the options with the z x keys or the ones you mapped, this is missing in lazer.

**Proposal designs of the feature:**

**Comment by Walavouchey** [comment] 2021-04-11 20:31
duplicate of #3551

**Closed** 2021-04-11 20:32 UTC
