### ISSUE TITLE
osu Android 11+ can't import anything 

### ISSUE THREAD

**Issue by TechyAditya** [ppy/osu#19047] opened 2022-07-08 20:01 UTC
### Type

Game behaviour

### Bug description

I was trying to make osu run on my android 11. But there is no way to give permissions for osu to read Android/Data due to Google's new policies. So, whatever the beatmap you try to download, doesn't gets transferred to Android/data/sh.ppy.osulazer

To fix this issue, please migrate app data to Android/media/sh.ppy.osulazer
The issue will be fixed easily this way, as the bug is minor. 

### Screenshots or videos

Can't show screenshots, but to reproduce problem, on Android 11 device, follow below steps
1. Goto osu app info and give storage permissions
2. Open osu, and press on import beatmap
3. Try opening Android/data
It won't open that, it'll fail. 

### Version

2022.709.0

### Logs

Logs are not even generated, as osu just tried to save logs to Android/data/sh.ppy.osulazer/files/logs but it can't save logs, just because of Android 11 restrictions set by Google on Android/data.

**Comment by peppy** [comment] 2022-07-08 20:05
Duplicate of https://github.com/ppy/osu/issues/11911?

**Comment by toadsworth-jr** [comment] 2022-07-08 20:21
What I'm seeing here is to move the entire working folder of osu from Android/data to Android/media...
That's not a bad idea, if I say so myself.

**Closed** 2022-07-08 20:47 UTC
