### ISSUE TITLE
Add a time limit to load players in multiplayer rooms

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#11367] opened 2020-12-29 23:25 UTC
**Describe the new feature:** 

Today Koifishu hosted an over 150 participants room, but we could never play the map since there was only 1 guy loading forever, i don't really know the reason but it looks like if you have any overlay open you are not going to be loaded into the game (i am not sure about that).

The proposal is to add a time limit for users to load and in case some user takes too long he can be kicked out of the room so the match can start with the loaded players.

**Comment by bdach** [comment] 2020-12-30 12:36
Will require server-side consideration on how to manage timers efficiently.

**Comment by peppy** [comment] 2021-02-09 10:18
Bumping this out of milestone. We now have proper connection timeouts and have fixed several issues which were causing "infinite load" scenarios where the user actually crashed or quit the game.

**Comment by peppy** [comment] 2022-04-21 02:54
Closing as duplicate of #17296 (keeping the newer one as it's assigned and tracked as a current task).

**Closed by peppy** 2022-04-21 02:54 UTC
Labels: area:multiplayer
