### ISSUE TITLE
Mention notifications reappear upon re-entering Multiplayer lobby

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#27486] opened 2024-03-04 05:50 UTC
### Type

Game behaviour

### Bug description

Was playing in a multi and was mentioned before by someone. I left and joined back and I got the same notification about that mention, clearly not intended behavior.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/54728307/b145100b-6862-4a24-a827-a9aeb8b02a19)

This notification is made everytime I join said multiplayer lobby.

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14477025/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-03-04 07:06
Duplicate of https://github.com/ppy/osu/issues/24715

**Closed by frenzibyte** 2024-03-04 07:06 UTC
Labels: area:multiplayer, area:overlay-chat
