### ISSUE TITLE
Hitsounds delay

### ISSUE THREAD

**Issue by Kremator1007** [ppy/osu#12719] opened 2021-05-08 11:25 UTC
**Describe the bug:** 
The hitsounds are severely delayed. The delay can be heard in both compiled from master and .appImage versions. 
**Screenshots or videos showing encountered issue:** 
https://disk.yandex.ru/i/OlrqmqDTIMS68g
**osu!lazer version:** 
One compiled from master branch, one - latest .appImage.
**Logs:**
[database.log](https://github.com/ppy/osu/files/6445759/database.log)
[network.log](https://github.com/ppy/osu/files/6445760/network.log)
[performance.log](https://github.com/ppy/osu/files/6445761/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6445762/runtime.log)

**Comment by bdach** [comment] 2021-05-08 11:32
Duplicate of #3800

This might be caused by custom pulseaudio/alsa settings if you have any. In general linux users are expected to know enough to configure their own system for now.

**Closed by bdach** 2021-05-08 11:32 UTC
