### ISSUE TITLE
User profile close after click on beatmap

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#14134] opened 2021-08-05 11:13 UTC
If I click on my profile and after on the map, then my profile is closed, and I have to open it again, so you can make it work the same way as with the direct

https://user-images.githubusercontent.com/21735205/128341045-01c0f08b-32bd-423c-bf31-e0bcb3624d46.mp4

**Comment by frenzibyte** [comment] 2021-08-05 11:18
Duplicate of https://github.com/ppy/osu/issues/5063. Please search before reporting issues.

**Closed by frenzibyte** 2021-08-05 11:18 UTC
