### ISSUE TITLE
Autoplay misses notes faster than 1/8 on osu!taiko

### ISSUE THREAD

**Issue by luiges90** [ppy/osu#5677] opened 2019-08-11 10:01 UTC
**Describe the bug:** Autoplay misses notes on 1/8. It seems if BPM is fast enough Autoplay simply miss those notes. In degenerate cases like this map https://osu.ppy.sh/beatmapsets/928431#taiko/1939224 autoplay actually _failed_. (were not it also have NoFail)
Autoplay does appear to actually play the notes but the game somehow thinks autoplay misses :thinking: 

**Screenshots or videos showing encountered issue:** 
![Clipboard01](https://user-images.githubusercontent.com/1821496/62832485-77d7ed00-bc61-11e9-8bb7-edab21cb730d.png)

**osu!lazer version:** 2019.809.0

**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3489823/runtime.log)

**Comment by peppy** [comment] 2019-08-11 20:31
This is caused by the key up delay not accounting for the fact that a map would ever require <50ms key presses.

https://github.com/ppy/osu/blob/907cf18960acd6bf460c057dbd60e95f103cbda4/osu.Game/Rulesets/Replays/AutoGenerator.cs#L34

I guess we will want to force a key up in such cases.

Also should note that this delay is not being applied to catch/mania.

**Comment by awesomecuber** [comment] 2019-08-14 19:14
If this delay isn't applied to mania, why does https://osu.ppy.sh/beatmapsets/400302#mania/871033 also fail? Is it a related issue?

**Comment by smoogipoo** [comment] 2019-08-15 03:53
Mania has its own delay:

https://github.com/ppy/osu/blob/58258188cea8a5876d83473a6a8f58796d129b4a/osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs#L15

**Comment by mouzedrift** [comment] 2019-08-26 09:39
autoplay is still missing on this map: https://osu.ppy.sh/beatmapsets/937726#taiko/1958813
Taikoyaki difficult 
miss at 2 min

**Comment by smoogipoo** [comment] 2019-08-26 10:43
Reopening for tracking purposes. The issue isn't to do with the merged PR, but seems to be an issue with replay playback itself, where elapsed time is going < 0 during forward playback.

**Comment by Desconocidosmh** [comment] 2019-08-26 11:24
I think it's also why it misses some notes on the Centipede visualization map

**Comment by PythonTryHard** [comment] 2019-12-18 16:44
Autoplay for Taiko also missed some notes on [this map as well](https://osu.ppy.sh/beatmapsets/1005684#taiko/2104774), 22 to be exact

**Closed** 2020-01-03 07:51 UTC
Labels: pending review, replay
