### ISSUE TITLE
new osu!lazer update (2021-331.0) crashes on my macbook air 2016 (macOS Mojave 10.14.6)

### ISSUE THREAD

**Issue by infinite-pi** [ppy/osu#12244] opened 2021-03-31 14:10 UTC
issue:
since I downloaded the update about 12 hours ago, the game would crash before opening fully, it would show its icon bouncing on the dock and then it would disappear. this only occurs on the new update and I've already tried restarting my laptop and reinstalling the update

https://user-images.githubusercontent.com/81694640/113154194-57abd600-926a-11eb-9970-0933a17fdb3b.mov

version:
osu!lazer 2021-331.0 

Logs:
[database.log](https://github.com/ppy/osu/files/6237101/database.log)
[network.log](https://github.com/ppy/osu/files/6237102/network.log)
[performance.log](https://github.com/ppy/osu/files/6237103/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6237104/runtime.log)

**Comment by peppy** [comment] 2021-03-31 14:16
Can you confirm the previous version still works okay?

https://github.com/ppy/osu/releases/tag/2021.323.0

**Comment by infinite-pi** [comment] 2021-03-31 14:21
> Can you confirm the previous version still works okay?
> 
> https://github.com/ppy/osu/releases/tag/2021.323.0

yes, the previous version works perfectly fine and I'm still using that version because the newer one doesn't work

**Comment by bdach** [comment] 2021-03-31 21:01
The logs attached are from the older version (2021.323.0). I'm unsure whether it's because you have launched that version after trying to launch 2021.331.0 and mistakenly attached those logs instead, or if it's because the game just crashed before it had a chance to log anything. If it's the latter, I'd try launching the "Console" app and seeing if a discernible error message falls out there.

**Comment by infinite-pi** [comment] 2021-04-01 03:59
> The logs attached are from the older version (2021.323.0). I'm unsure whether it's because you have launched that version after trying to launch 2021.331.0 and mistakenly attached those logs instead, or if it's because the game just crashed before it had a chance to log anything. If it's the latter, I'd try launching the "Console" app and seeing if a discernible error message falls out there.

I found some crash report in console for 331
[message (3).txt](https://github.com/ppy/osu/files/6240882/message.3.txt)

**Comment by bdach** [comment] 2021-04-01 04:10
Certainly looks like this might have broken with the recent SDL bump to me.

**Comment by infinite-pi** [comment] 2021-04-01 04:12
is there anything I can do to fix it on my end?

**Comment by peppy** [comment] 2021-04-01 04:13
Please use the previous version for now.

@swoolcock Do you remember what the issue/fix was here? Is building on github actions building against a too-new SDK version? I think we ran into this once before and it was fixed by you building locally on an older macOS version.

Not sure if we want to do this, but I guess it's a consideration we need to take.

**Comment by swoolcock** [comment] 2021-04-01 04:49
Yes, the issue is building against a newer OS than the one it's running on. Unfortunately I am no longer able to build for Mojave as my machines are now running Big Sur.

I'm not sure what the solution is other than to build in a VM.

**Comment by smoogipoo** [comment] 2021-04-01 05:00
It may be enough to set the `MACOSX_DEPLOYMENT_TARGET` environment variable, which is a GCC property. It seems like SDL understands this to some degree https://github.com/libsdl-org/SDL/blob/fa81883418ebf327e5176d8603d7c04e75e807f4/configure#L6942-L6947

May also need older SDKs: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html

**Comment by peppy** [comment] 2021-04-02 04:57
Going to give the above a try (https://github.com/ppy/SDL2-CS/commit/9bf64d5cd1cfa590ee8f7d724f59da99a0af9dea).

**Comment by smoogipoo** [comment] 2021-04-02 05:16
You've put the env variable on the create pull request job, not the build job.

**Closed** 2021-04-02 10:31 UTC
Labels: framework-fix-required, platform:macOS
