### ISSUE TITLE
I got an S rank even with 4 misses

### ISSUE THREAD

**Issue by C0piCat727** [ppy/osu#22323] opened 2023-01-21 21:04 UTC
### Type

Crash to desktop

### Bug description

I was playing a map and I somehow got a 96% acc with 4 misses and it gave me an S, then I though "wait isnt S rank full combo?"

### Screenshots or videos

![Screenshot (66)](https://user-images.githubusercontent.com/123272159/213887046-f9c182b2-176e-4da8-96ae-5e4e6057d897.png)

### Version

2023.121.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/10473062/network.log)
[performance.log](https://github.com/ppy/osu/files/10473063/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10473064/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10473065/updater.log)
[database.log](https://github.com/ppy/osu/files/10473066/database.log)
[input.log](https://github.com/ppy/osu/files/10473067/input.log)

**Comment by qyutell** [comment] 2023-01-21 21:09
Lazer's grading system is in line with the system currently used in osu!mania. Regardless of miss count, anything above 95% accuracy is considered an S rank.

**Comment by C0piCat727** [comment] 2023-01-21 21:13
> Lazer's grading system is in line with the system currently used in osu!mania. Regardless of miss count, anything above 95% accuracy is considered an S rank.

wait so that means that the system of ranking on lazer is not the same as in stable (yet)?

**Comment by bdach** [comment] 2023-01-21 22:32
Duplicate of https://github.com/ppy/osu/issues/4184

**Closed by bdach** 2023-01-21 22:32 UTC
