### ISSUE TITLE
Textbox "freezing" with special characters

### ISSUE THREAD

**Issue by Beyley** [ppy/osu#14002] opened 2021-07-24 17:28 UTC
**Describe the bug:** 
Whenever i type special characters into the lazer textbox it "freezes" until i type a non-special character

**Screenshots or videos showing encountered issue:** 
https://youtu.be/_8Eb3jrqAgc

**osu!lazer version:** 
Local build (from the AUR package `osu-lazer-git`, currently on version `2021.619.0.r136.c624ec79b1-1`)

**Logs:**
[database.log](https://github.com/ppy/osu/files/6872815/database.log)
[performance.log](https://github.com/ppy/osu/files/6872816/performance.log)
[network.log](https://github.com/ppy/osu/files/6872817/network.log)
[runtime.log](https://github.com/ppy/osu/files/6872818/runtime.log)

**Comment by bdach** [comment] 2021-07-24 17:30
Duplicate of https://github.com/ppy/osu-framework/issues/1965 (and several others)

**Closed by bdach** 2021-07-24 17:30 UTC
