### ISSUE TITLE
In song selection screen, changing game's language does not update score's number format

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#22900] opened 2023-03-18 18:17 UTC
### Type

Cosmetic

### Bug description

When you are at the song selection, if you open the options and change the language with a different number format, the scores number format in leader boards aren't updated, until you quit this screen. The weird thing is only the scores numbers are affected, the other numbers (accuracy, star rating, combo, ...) are updated, not the scores...

Exemple of number format.
| English | French |
|----|----|
|1,234.56|1?234,56 (see #15135 for the '?') |

### Screenshots or videos

https://user-images.githubusercontent.com/57914482/226126260-fb7cab8f-8956-45f4-af4d-83a7dbd695c4.mp4

### Version

2023.305.0-lazer

### Logs

(not exactly the one from the video, but I did the same things)

[database.log](https://github.com/ppy/osu/files/11009265/database.log)
[input.log](https://github.com/ppy/osu/files/11009267/input.log)
[network.log](https://github.com/ppy/osu/files/11009268/network.log)
[performance.log](https://github.com/ppy/osu/files/11009269/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11009270/runtime.log)

**Comment by Joehuu** [comment] 2023-03-19 03:04
Duplicate of https://github.com/ppy/osu/issues/14083

**Closed by Joehuu** 2023-03-19 03:04 UTC
