### ISSUE TITLE
Side acting like ZX

### ISSUE THREAD

**Issue by Optimalgitit** [ppy/osu#6402] opened 2019-10-05 04:44 UTC
Both osu!droid and opsu! have this feature, where the side of the screen acts like ZX. lazer doesn't have this.

But we should be able to customize what area will act as ZX, like maybe we want it on the right, or the bottom.

**Comment by Joehuu** [comment] 2019-10-05 04:54
Duplicate of https://github.com/ppy/osu/issues/4201

**Closed by Joehuu** 2019-10-05 04:54 UTC
