### ISSUE TITLE
Can't leave editor on Android

### ISSUE THREAD

**Issue by AlexouWolfy** [ppy/osu#6320] opened 2019-09-29 18:36 UTC
When we are in the editor, it's impossible to go back or we need to restart the game.
We can fix it by adding a button in the high-left corner to go back on the menu.

**Comment by bdach** [comment] 2019-09-29 18:47
The back button works on my device, as does using the *File* menu in the left top corner (*File* → *Exit*). Are you sure neither work for you? If they don't, please specify your device details and attach logs from `Android/data/sh.ppy.osulazer/logs`.

**Comment by AlexouWolfy** [comment] 2019-09-29 18:51
> The back button works on my device, as does using the _File_ menu in the left top corner (_File_ → _Exit_). Are you sure neither work for you? If they don't, please specify your device details and attach logs from `Android/data/sh.ppy.osulazer/logs`.

The back button just close osu for me, and it's very hard to touch the file/exit button

**Comment by bdach** [comment] 2019-09-29 18:57
If the back button closes the app, then I'd wager it's a crash, not a proper close, and as such that issue most likely overlaps with or is a duplicate of #6285 or other device-specific crashes that have been recently reported.

As for the UI being hard to use due to control size, please see the *UI scaling* option in settings.

**Closed** 2019-09-29 19:00 UTC
