### ISSUE TITLE
Autoplay spinning speed depends on rate-changing mods

### ISSUE THREAD

**Issue by integerrr** [ppy/osu#10283] opened 2020-09-28 20:58 UTC
**Describe the bug:** 
The bonus score of a spinner with DT mod is capped by the maximum attainable spinner bonus score (i.e. at 477 rpm / auto). Notice in the video when the map is played with DT, the first spinner does not go pass 850 for its bonus score even with auto mod, which is the spinner score auto mod got for that spinner when played with NM

**Screenshots or videos showing encountered issue:** 
https://streamable.com/m3l50j

**osu!lazer version:** 
2020.925.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5295003/database.log)
[performance-audio.log](https://github.com/ppy/osu/files/5295005/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5295006/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/5295007/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/5295008/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5295009/runtime.log)

**Comment by bdach** [comment] 2020-09-28 21:10
The actual issue is that autoplay is spinning too fast on DT and too slow on HT. Notice the SPM counter. Spinners should have the same SPM regardless of rate-changing mods.

**Comment by signedinteger** [comment] 2020-09-28 21:14
I noticed that too, but anecdotally I think rate changing mods also give you extra/reduced max spinner bonus if DT/HT is used in stable, but in this case the bonus stopped increasing after a certain amount, tho I'm not sure if I have confused something

**Comment by PercyDan54** [comment] 2020-12-20 07:48
Duplicate of #9821

**Comment by frenzibyte** [comment] 2020-12-20 07:50
That is not a duplicate as the previous one (#9821) has been resolved in release `2020.814.0`, while this one is reported in release `2020.925.0`.

**Comment by peppy** [comment] 2020-12-22 04:08
Adding to milestone; we should probably come to a conclusion as to how this should be working.

**Comment by bdach** [comment] 2021-02-01 23:49
As an update, I have 99% of this ready, except for one thing - `ModTimeRamp`. I cannot for the life of me figure out the correct time transformation to apply to the replay generation process in order to keep the spinning rate at a constant 477 with that one.

I thought something like this was going to be correct, but it's still off by a noticeable margin...

![2021-02-02-004649_1832x982_scrot](https://user-images.githubusercontent.com/20418176/106532332-4e172380-64f0-11eb-9cf4-153c238987d5.png)

(`r_0` and `r_f` are starting and final track rates, correspondingly, `t_0` and `t_f` are ramp start and end times, `a` is acceleration. This is all derived from equations of constant acceleration motion.)

**Closed** 2021-02-11 09:30 UTC
Labels: area:mods, ruleset:osu!
