### ISSUE TITLE
Missing hit score sprites on some imported skins.

### ISSUE THREAD

**Issue by MCSulphate** [ppy/osu#8567] opened 2020-04-02 10:49 UTC
**Describe the bug:**
Some skins imported from stable are missing the hit score (300, 100, 50, Miss) sprites in-game. This became an issue for me when I updated my osu!lazer client to the latest version from a version from a few months ago.

Note that this is not an issue with all imported skins as most of them still work, so there's probably something weird going on with a couple of the skins?

**Screenshots or videos showing encountered issue:** https://youtu.be/zsCwWAEpy_4
Here I use the same skin in normal osu and then osu!lazer immediately after importing the skin. I tried looking for this issue but couldn't find it so I hope it's legitimate.

**osu!lazer version:** 2020.402.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4420367/database.log)
[network.log](https://github.com/ppy/osu/files/4420368/network.log)
[performance.log](https://github.com/ppy/osu/files/4420369/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4420370/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4420371/updater.log)

Thanks! :)

**Comment by smoogipoo** [comment] 2020-04-02 10:53
Please post your skin.

**Comment by MCSulphate** [comment] 2020-04-02 10:58
Sorry, here it is. If needed I can post a couple more that also display this issue.

[-        # WhiteCat (1.0) 『CK』 #-.zip](https://github.com/ppy/osu/files/4420543/-.WhiteCat.1.0.CK.-.zip)

**Comment by smoogipoo** [comment] 2020-04-02 11:14
Reposting from discord, this is most likely going to be caused by the default of `startAtCurrentTime = false` in https://github.com/ppy/osu/blob/master/osu.Game/Skinning/LegacySkinExtensions.cs#L18 . We'll likely want this set `true` as a default instead, but need to make sure it handles fine everywhere else, such as the `Catch` catcher (iirc there was some special logic around there).

**Comment by smoogipoo** [comment] 2020-04-07 02:56
Fixed by https://github.com/ppy/osu/pull/8613

**Closed by smoogipoo** 2020-04-07 02:56 UTC
Labels: area:skinning
