### ISSUE TITLE
Windows taskbar focused after notification

### ISSUE THREAD

**Issue by Nat628** [ppy/osu#8058] opened 2020-02-29 15:38 UTC
Someone messaged me on Steam while i am playing a beatmap. The taskbar pops up but does not unfocus. My assumption is that when taskbar notifications appear, the game client does not unfocus  and the taskbar does not appear to prevent distractions. The game client did not unfocus however so i was able to play smoothly, the only problem is that it is a bit distracting because it showed up and never disappeared unless I clicked it to stop it from notifying.

![image](https://user-images.githubusercontent.com/61627236/75610414-e6bc5b00-5b4b-11ea-9148-de4096676622.png)

**Comment by bdach** [comment] 2020-02-29 16:38
Borderless or exclusive fullscreen? Also, does the taskbar disappear after you click inside of the game window?

I believe if there's an alerted taskbar item Windows will force displaying the taskbar when there's an alerted taskbar item (like the steam button as depicted above - usually pulsing or solid orange in colour) and will keep displaying it until focus is explicitly diverted elsewhere by the user. This should be only be an issue on borderless but as it's an OS-level behaviour I'm not sure we could do much about that.

**Comment by Nat628** [comment] 2020-02-29 17:22
I have my game on fullscreen. If I click inside the window, the taskbar does not disappear. I also have auto-hide the taskbar enabled in my taskbar settings in case that helps.

**Comment by peppy** [comment] 2020-03-01 04:07
We don't have any specific logic for this as far as I know.

Does it happen for other games?

**Comment by Nat628** [comment] 2020-03-01 06:21
For the games that I have already played, it does not happen. It also does not happen to the osu stable client so I was confused when it happened in lazer client.

**Comment by Joehuu** [comment] 2021-02-19 21:32
@Nat628 can you still reproduce this? I can't reproduce on the latest build at the time and now. We also switched to SDL which may have already fixed this.

**Comment by peppy** [comment] 2021-03-24 07:51
Going to close this as it's 99% fixed by the switch to SDL.

**Closed by peppy** 2021-03-24 07:51 UTC
Labels: missing details, platform:windows, type:UX
