### ISSUE TITLE
Difficulty attribute skin elements don't get updated when mods are applied

### ISSUE THREAD

**Issue by Spok5508** [ppy/osu#29493] opened 2024-08-18 14:02 UTC
### Type

Game behaviour

### Bug description

When trying to record a youtube video I noticed that the difficulty attributes don't update according to the applied mods.

### Screenshots or videos

https://github.com/user-attachments/assets/40637c49-9d46-42d7-9be7-209d2a0830fc

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16648938/compressed-logs.zip)

**Comment by Gabixel** [comment] 2024-08-18 14:35
I thiiink this is a duplicate of #21946?

**Closed** 2024-08-18 15:57 UTC
