### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by ZaboyZakoby** [ppy/osu#6437] opened 2019-10-08 20:30 UTC
When I launch the game it lets me know that this is the unstable build of the game or whatever it says and then it goes to another screen that shows the following screenshot 

![image](https://user-images.githubusercontent.com/53627704/66430671-6ac04b80-e9cf-11e9-9714-9b7903195309.png)

2019.930.0

[performance.log](https://github.com/ppy/osu/files/3704420/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3704419/runtime.log)
[database.log](https://github.com/ppy/osu/files/3704421/database.log)
[updater.log](https://github.com/ppy/osu/files/3704422/updater.log)

P.S. Opening and closing does not fix it and i havent tried uninstalling and reinstalling bc i have about a lot of beatmaps loaded so i dont want to reinstall them

P.S.S. I'm able to change the volume knobs? I am also able to disable mouse buttons

**Comment by ZaboyZakoby** [comment] 2019-10-08 20:31
P.S. Opening and closing does not fix it and i havent tried uninstalling and reinstalling bc i have about a lot of beatmaps loaded so i dont want to reinstall them

**Comment by ZaboyZakoby** [comment] 2019-10-08 20:31
P.S.S. I'm able to change the volume knobs?

**Comment by iiSaLMaN** [comment] 2019-10-08 20:32
you can find the logs at `%appdata%\osu\logs` for windows. do you hear any audio?

also, please keep notes at the description of your issue rather than "P.S"-ing separately.

**Comment by bdach** [comment] 2019-10-08 20:32
Additionally, does going to windowed mode (by pressing <kbd>Alt</kbd>+<kbd>Enter</kbd>) and/or restarting afterwards help?

Likely a duplicate of #4068 or #6387.

**Comment by iiSaLMaN** [comment] 2019-10-08 20:33
This is probably an audio issue since he can actually see on the screen.

**Comment by Craftplacer** [comment] 2019-10-08 20:34
Duplicate of #6328?

**Comment by iiSaLMaN** [comment] 2019-10-08 20:38
@ZaboyZakoby Out of curiosity, does changing the `IntroSequence` value to `Circles` in the `game.ini` fix this issue? will confirm that this is in-fact audio issue since the new intro `Triangles` doesn't play if cannot start the triangles track.

**Comment by ZaboyZakoby** [comment] 2019-10-08 20:42
I am able to change the screen mode and none of them after restarting work, I do not hear any audio (My SteelSeries engine 3 just told me that there was an unrecoverable error that probably has something to do with it im currently going to restart pc and see if its fixed

**Comment by ZaboyZakoby** [comment] 2019-10-08 20:50
Restarting my computer did fix it but i think it also had something to do with my VR headset overriding my headset for audio?

**Closed** 2019-10-08 20:56 UTC
Labels: audio, graphics, hard crash
