### ISSUE TITLE
Notification count doesn't go past 23

### ISSUE THREAD

**Issue by nerootter** [ppy/osu#25836] opened 2023-12-18 11:06 UTC
### Type

Game behaviour

### Bug description

Was downloding a bunch of maps via direct, and the notification count froze at 23.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/70763403/5d853294-eff0-4141-8108-2974d97fb9be)

### Version

2023.1218.0-lazer

### Logs

none

**Comment by bdach** [comment] 2023-12-18 12:44
It does go past 23, I just checked. It probably just stopped at 23 because that's how many items you had.

Closing unless clear reproduction steps are provided.

**Closed by bdach** 2023-12-18 12:44 UTC

**Comment by nerootter** [comment] 2023-12-18 13:28
the bug's gone now, maybe it was my computer's problem
