### ISSUE TITLE
Display diff name and star rating without selecting a multiplayer lobby

### ISSUE THREAD

**Issue by RaiLTC** [ppy/osu#12087] opened 2021-03-19 17:08 UTC
It's tedious having to select every time just to see the diff name / star rating so simply changing to hover over to display should be good enough

IMO should probably use the space to display diff name and star rating, feels a bit wasted not to do so

**Comment by Joehuu** [comment] 2021-03-19 17:33
Duplicate of https://github.com/ppy/osu/issues/9665

**Closed by Joehuu** 2021-03-19 17:33 UTC
Labels: area:multiplayer, type:UX
