### ISSUE TITLE
lazer menu cursor and system cursor appearing during gameplay

### ISSUE THREAD

**Issue by weihan28** [ppy/osu#30115] opened 2024-10-04 17:59 UTC
### Type

Game behaviour

### Bug description

While playing on tablet, the system cursor (macOS default) or menu cursor appears on top of the game cursor when interacting with the black bar (mac menu bar) at the top of the screen. This issue happens when im in gameplay and also in menu.

Steps to reproduce :
1. play a map 
2. move the pen to the top of screen (where mac menu bar is supposed to be) with hover or drag style
3. if pen was hovering: system cursor appears and wont leave
4. if pen was dragging: gameplay cursor dissapears and menu cursor appears, will return when pen is lifted.

### Screenshots or videos

https://github.com/user-attachments/assets/848de9e7-8753-4f0c-93a1-6f69a9a0fcb5

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17262203/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-10-04 23:23
Duplicate of https://github.com/ppy/osu/issues/24620

**Closed by Joehuu** 2024-10-04 23:23 UTC

**Comment by timiimit** [comment] 2024-10-07 06:51
@weihan28 forgot to say that this bug completely breaks NoScope mod. With that mod cursor is expected to become completely invisible. And that bug makes cursor visible permanently. This bug is extremely apparent when you configure said mod to hide cursor at all times (at combo 0).

I would expect a fix for this bug and a full reset of all scores submitted with this mod.

Is this sufficient evidence that a fix is indeed required? @Joehuu

**Comment by bdach** [comment] 2024-10-07 06:53
> I would expect a fix for this bug and a full reset of all scores submitted with this mod.

No. See https://github.com/ppy/osu/issues/29578#issuecomment-2307233838.
