### ISSUE TITLE
Modifications to working beatmap in conversion step aren't reverted in editor

### ISSUE THREAD

**Issue by sw1tchbl4d3r** [ppy/osu#20994] opened 2022-10-28 13:08 UTC
### Type

Game behaviour

### Bug description

Found while working on https://github.com/ppy/osu/pull/20716
As seen in the video, the modifications to the beatmap (here effect points applied in `TaikoBeatmapConverter.ConvertBeatmap`) persist into the editor, until we change the working beatmap by switching difficulties.
In the editor we should load the original map, and switching to the standard mode also shouldn't keep the conversion changes.

### Screenshots or videos

https://user-images.githubusercontent.com/54949148/198590107-bcdad288-08ed-4875-b6b1-4c987bf89ff4.mp4

### Version

master

### Logs

N/A

**Comment by bdach** [comment] 2022-10-30 13:39
The actual problem is that conversion isn't making a deep clone of the control points before modifying the collection (which is a reference type and therefore subject to indesirable shared mutation).

Extra points for ensuring this can't happen again, by scoping `Beatmap<T>.ControlPointInfo` to an immutable interface (not sure if this is viable).

**Comment by peppy** [comment] 2022-11-01 05:18
I'm bumping this to p0 as the recently merged PR has caused actual regression due to modifying control points across threads on a shared instance of the beatmap:

https://sentry.ppy.sh/organizations/ppy/issues/9960/?project=2&query=firstRelease%3Aosu%402022.1031.0&sort=freq (this is about 8 different null refs merged into a single thread)
https://sentry.ppy.sh/organizations/ppy/issues/9986/?project=2&query=firstRelease%3Aosu%402022.1031.0&sort=freq

**Comment by peppy** [comment] 2022-11-01 08:30
Going to tentatively assign this and look into a solution.

**Closed** 2022-11-01 12:04 UTC
Labels: priority:0, ruleset:osu!taiko, area:beatmap
