### ISSUE TITLE
Possible modification of Beatmap which the bindable is disabled

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#1757] opened 2017-12-26 05:27 UTC
The following sequence:

1. Select a map
2. Press enter
3. Exit back to song select while loading (doesn't need to be particularly quick).
4. Select another map, and press enter.

Leds to:

```
System.InvalidOperationException: Can not set value to "osu.Game.Beatmaps.BeatmapManager+BeatmapManagerWorkingBeatmap" as bindable is disabled.
  at osu.Framework.Configuration.Bindable`1[T].set_Value (T value) [0x00039] in <5be82732e0904ab0a54953f50c0efe6c>:0 
  at osu.Game.Screens.Select.SongSelect+<>c__DisplayClass27_0.<carouselSelectionChanged>b__0 () [0x000dc] in <52cc1329c27b4aec813e0806e7a58138>:0 
  at osu.Framework.Threading.ScheduledDelegate.RunTask () [0x0000e] in <5be82732e0904ab0a54953f50c0efe6c>:0 
  at osu.Framework.Threading.Scheduler.Update () [0x0023c] in <5be82732e0904ab0a54953f50c0efe6c>:0 
  at osu.Framework.Graphics.Drawable.UpdateSubTree () [0x000a1] in <5be82732e0904ab0a54953f50c0efe6c>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree () [0x00001] in <5be82732e0904ab0a54953f5
```

**Comment by peppy** [comment] 2017-12-26 05:28
Likely duplicate of https://github.com/ppy/osu/issues/1719

**Closed** 2017-12-30 18:07 UTC
Labels: bug, pending review, songselect
