### ISSUE TITLE
triangles on the pause menu 'exit' button flow over by 1 pixel at the bottom

### ISSUE THREAD

**Issue by tovc** [ppy/osu#24714] opened 2023-09-04 14:29 UTC
### Type

Cosmetic

### Bug description

this seems to be resolution related; it doesn't occur at 1920x1080 and below, but it does occur at 2560x1440 and 3440x1440

the darker red triangles flow over below the button, but the ytellow/green ones do not
![image](https://github.com/ppy/osu/assets/49025619/b8bb346a-3a65-47e7-ada9-d040e776a455)

I'm unable to reproduce the issue below 1440p

### Screenshots or videos

tested at 3440x1440 and 2560x1440
![3440](https://github.com/ppy/osu/assets/49025619/467be43d-b2f2-4576-8c3f-2db378549ba2)
![2560](https://github.com/ppy/osu/assets/49025619/f81b3781-e3f6-4575-a43b-9388de9c0311)

### Version

2023.815.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12514350/network.log)
[performance.log](https://github.com/ppy/osu/files/12514351/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12514352/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12514353/updater.log)
[database.log](https://github.com/ppy/osu/files/12514354/database.log)
[input.log](https://github.com/ppy/osu/files/12514356/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12514358/legacy-ipc.log)

**Comment by Joehuu** [comment] 2023-09-04 17:21
Duplicate of https://github.com/ppy/osu/issues/4591

**Closed by Joehuu** 2023-09-04 17:21 UTC
