### ISSUE TITLE
Game Grabs 'hitX' instead of hitX-#'

### ISSUE THREAD

**Issue by MLisDreaming** [ppy/osu#4881] opened 2019-05-30 17:35 UTC
osu!lazer is grabbing the hit for the ranking screen for gameplay.
hit0.png is supposed the miss for the ranking screen.
hit0-0.png is supposed the miss for gameplay.
In osu!lazer hit0.png is the miss for gameplay.
In osu!lazer the miss for the ranking screen can't be skinned, yet.
For animated ones it would be hit0-0.png, hit0-1.png, hit0-2.png, ect.
This sucks for people that hide 300s as they show up because the game as the ranking 300, instead of the gameplay 300.
I've noticed this bug forever ago and I'm amazed that everyone has failed to say anything. Like, how am I the first one to report this.
hit0.png:![hit0@2x](https://user-images.githubusercontent.com/43427333/58651127-177a1600-82d6-11e9-93fe-2dd436d53dac.png)
hit0-0.png:![hit0-0@2x](https://user-images.githubusercontent.com/43427333/58651186-37a9d500-82d6-11e9-86f8-9dc4e245eaa9.png)
hit0.png in gameplay:
![image](https://user-images.githubusercontent.com/43427333/58651292-86576f00-82d6-11e9-99f4-ce1f36067e8b.png)
hit0-0.png in gameplay:
![image](https://user-images.githubusercontent.com/43427333/58651396-cf0f2800-82d6-11e9-9ebf-ea5bb75a315c.png)
Valve pls fix.

**Comment by stanriders** [comment] 2019-05-30 17:37
It's intentional and all that hit0-0.png stuff is just a workaround for what's not supported in stable.

**Comment by MLisDreaming** [comment] 2019-05-30 17:42
Are you sure because this doesn't look intentional.
![image](https://user-images.githubusercontent.com/43427333/58651973-31b4f380-82d8-11e9-9013-372f8b7f92dd.png)
I don't see why it's not supported to grab hit0-0.png instead of hit0.

**Comment by jorolf** [comment] 2019-05-30 20:07
This is a duplicate of https://github.com/ppy/osu/issues/4627, animations are not yet supported by skinning.

(this includes animations which only have one frame)

**Closed** 2019-05-30 20:09 UTC

**Comment by Morilli** [comment] 2019-07-03 11:23
I've had this issue too, and today I noticed that my skin works as intended... is this referenced issue resolved too?

**Comment by peppy** [comment] 2019-07-03 11:33
This is resolved, yes (see https://github.com/ppy/osu/pull/5202).
