### ISSUE TITLE
lazer registers mouse clicks even when in background on windows 7

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu#4182] opened 2019-01-29 19:30 UTC
**Describe your problem:** 
When osu!lazer is open in the background it still registers mouse clicks through other windows/ programs in the foreground .
Also happens on full screen mode.
**Operating on:**
Windows 7 64-bit Pro
**osu!lazer version:** 
2019.126.0

**Comment by qwewqa** [comment] 2019-01-29 19:35
Looks like this may be a duplicate of #3580

**Comment by peppy** [comment] 2019-01-30 01:47
Closing as duplicate. We need someone who runs win7 to investigate this. None of us do any more as it's not a maintained operating system.

**Closed by peppy** 2019-01-30 01:47 UTC
