### ISSUE TITLE
In some cases the displayed score do not correspond with the replay score

### ISSUE THREAD

**Issue by MTGPROD** [ppy/osu#9187] opened 2020-06-02 21:23 UTC
**Describe the bug:** 

See the video below to understand

**Screenshots or videos showing encountered issue:** 

[Video](https://youtu.be/0QlzvTo7yHU) 

**osu!lazer version:** 

2020.602.0

**Logs:**
 Android

**Comment by bdach** [comment] 2020-06-02 22:16
As the replay in question was recorded in February, which is before replay recording landed in lazer, I'm guessing it originates from stable, in which case this is a duplicate of #5350. Closing as such.

**Comment by MTGPROD** [comment] 2020-06-03 08:33
@bdach The replay was created with lazer and do not come from the stable !!

**Comment by bdach** [comment] 2020-06-03 08:54
Cultures... Reopening for investigation.

**Comment by smoogipoo** [comment] 2020-06-11 11:41
I believe this is resolved by https://github.com/ppy/osu/pull/9211

**Comment by TheWildTree** [comment] 2020-06-11 11:45
This is about the score difference (463k in the replay vs. 430k on the score panel), not the date format.

**Comment by smoogipoo** [comment] 2020-06-11 11:45
ohhhhh, I misunderstood because of the comments >_<

**Comment by peppy** [comment] 2020-06-12 10:45
Okay I just realised there's only a video attached. We cannot do anything with only that. Please provide something usable, like a replay.

**Comment by MTGPROD** [comment] 2020-06-13 23:33
But this replay is actually on Android how I can provide you any replay ? @peppy

**Comment by peppy** [comment] 2020-06-14 00:00
You would need to grab the file (after you confirm it reproduces every playback), off your device.. As we don’t have replay exporting, you’d just find it in the file store.

**Comment by MTGPROD** [comment] 2020-06-28 22:16
Is this possible to export replay on android ? I re-watched the replay 5th times separated by 2-3d and some phone restart so.. @peppy

**Comment by peppy** [comment] 2020-06-29 02:45
Please reproduce on PC for simplicity. Comment if you manage to better provide details and we'll reopen this.

**Closed by peppy** 2020-06-29 02:45 UTC
Labels: area:replay, missing details
