### ISSUE TITLE
Increase size of playfield on mobile devices

### ISSUE THREAD

**Issue by MikelJohnson** [ppy/osu#6490] opened 2019-10-13 09:15 UTC
Would be really helpful on Android/IOS.
Probably should also have a disclaimer that some gameplay elements might not be visible.

**Comment by peppy** [comment] 2019-10-13 09:20
Renamed in line with our intentions. Should probably be an automatic change.

**Comment by LittleEndu** [comment] 2019-10-13 09:55
Wouldn't circle size modifying mean that there needs to be a separate leaderboard for mobile players?

**Comment by Game4all** [comment] 2019-10-13 11:46
Duplicate of issue #4888 (basically asking for automatic adjusting of CS for mobile) ?

**Comment by bdach** [comment] 2019-10-13 12:01
I'm actually going to go against standard practice here and close the *old* one, since this one has a better title.

**Comment by Vernonlim** [comment] 2019-10-13 14:21
> Wouldn't circle size modifying mean that there needs to be a separate leaderboard for mobile players?

I believe that separate leaderboards were already planned regardless, if i'm not mistaken

**Comment by Joehuu** [comment] 2020-01-26 22:48
Closing as modifying circle size is possible now. We can revisit the CS automation and how this (or anything new really) affects the score/pp leaderboards when lazer replaces stable.

**Closed by Joehuu** 2020-01-26 22:48 UTC
Labels: gameplay, mobile, osu!
