### ISSUE TITLE
Sliders that turn sharply or cut through themselves can get incorrectly rendered

### ISSUE THREAD

**Issue by Azureharp** [ppy/osu#5391] opened 2019-07-17 19:38 UTC
**Describe the bug:** 
First off it happens inconsistently, and mostly to sliders with stranger shapes, though seemingly it happens more to sliders with tight directional changes. 

Here's the map pictured below, it's almost always rendered like that
https://osu.ppy.sh/beatmapsets/724192#osu/1529189

I also tested with the last version pretty thoroughly and it didn't seem to crop up
**Screenshots or videos showing encountered issue:** 
![osu_2019-07-17_13-17-12](https://user-images.githubusercontent.com/42692316/61400510-05f4c980-a896-11e9-9bec-1c78369a70f6.png)
**osu!lazer version:** 
2019.717.1

**Comment by Gabixel** [comment] 2019-07-17 21:18
This seems to happen to me too, here are some examples with [**this**](https://osu.ppy.sh/beatmapsets/16904#osu/67086) song: 

![1](https://user-images.githubusercontent.com/43073074/61412393-0cf8f780-a8e9-11e9-881a-e42e54fe7285.png)
![2](https://user-images.githubusercontent.com/43073074/61412399-0ff3e800-a8e9-11e9-96cb-eebbcd3a60f5.png)
![3](https://user-images.githubusercontent.com/43073074/61412405-14200580-a8e9-11e9-8b1b-ed2f2fcc9873.png)

**Comment by peppy** [comment] 2019-07-18 03:31
Closing as duplicate of #3158.

**Comment by peppy** [comment] 2019-07-18 04:35
Potentially related to https://github.com/ppy/osu-framework/issues/2661

**Closed** 2019-07-18 15:17 UTC
Labels: bug, gameplay, high priority
