### ISSUE TITLE
"Live" mode for editor 

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7094] opened 2019-12-08 09:42 UTC
**Describe the new feature:** 
-

> This feature allows mappers to move the cursor and tapping buttons within the editor to place circles and sliders just like gameplay.

**Proposal designs of the feature:** 
-

> The only purpose of this feature is to reduce the time it takes for mappers to place objects.  It is more convenient to modify the beatmap after preliminary design than to do it one by one.

> It should let the mapper choose whether to use it and allow independent selection of keyboard placement and cursor positioning

**Comment by peppy** [comment] 2019-12-08 11:21
This exists in stable, known as "live" edit mode. It will be added to lazer eventually.

**Comment by bdach** [comment] 2019-12-08 11:41
Duplicate of #6608.

**Closed by bdach** 2019-12-08 11:41 UTC
Labels: editor
