### ISSUE TITLE
Crash after rewinding in spectator mode

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu#11014] opened 2020-11-30 15:07 UTC
**Describe the crash:** 
i started spectating someone on a long map while he was almost through the whole map and after rewinding the game suddenly crashed

**osu!lazer version:** 
2020.1128.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/5616713/database.log)
[network.log](https://github.com/ppy/osu/files/5616714/network.log)
[performance.log](https://github.com/ppy/osu/files/5616715/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5616716/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5616718/updater.log)

**Comment by bdach** [comment] 2020-11-30 15:42
Another strange one:

```
2020-11-30 14:59:36 [error]: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
2020-11-30 14:59:36 [error]: at osu.Game.Rulesets.Scoring.ScoreProcessor.RevertResultInternal(JudgementResult result)
2020-11-30 14:59:36 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.Update()
2020-11-30 14:59:36 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2020-11-30 14:59:36 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

**Comment by smoogipoo** [comment] 2020-12-01 00:15
Probably related to/dupe of https://github.com/ppy/osu/issues/10907

**Comment by peppy** [comment] 2020-12-04 06:40
Confirmed as duplicate; let's track in the other issue.

**Closed by peppy** 2020-12-04 06:40 UTC
Labels: area:spectator, type:crash
