### ISSUE TITLE
Hit sounds not being played in the editor on fast maps (300 BPM)

### ISSUE THREAD

**Issue by xDololow** [ppy/osu#31160] opened 2024-12-16 15:33 UTC
### Type

Other

### Bug description

Basically when watching map in the editor, fast streams hitsounds are not being there. Video shows it. 
Happens on this map: https://osu.ppy.sh/beatmapsets/666834#osu/1411180
and also on this in 300 BPM parts: https://osu.ppy.sh/beatmapsets/795396#osu/2898085

### Screenshots or videos

https://files.xxxd.org/revo1/QIJevEmo74.mp4 sound warning

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18152867/compressed-logs.zip)

**Comment by peppy** [comment] 2024-12-18 14:54
Duplicate of https://github.com/ppy/osu/issues/26559.

**Closed by peppy** 2024-12-18 14:54 UTC
Labels: area:editor, audio
