### ISSUE TITLE
Cannot change folder location.

### ISSUE THREAD

**Issue by LollipopFt** [ppy/osu#11507] opened 2021-01-16 06:07 UTC
Error when changing folder location.

https://user-images.githubusercontent.com/62802897/104798655-8259c700-5803-11eb-8d23-ca5656f95972.mp4

**osu!lazer version:** 2021.109.0

**Logs:**

**Comment by bdach** [comment] 2021-01-16 11:24
Duplicate of #9746

**Closed by bdach** 2021-01-16 11:24 UTC
