### ISSUE TITLE
Scrolling page clips content 1px in the editor modal

### ISSUE THREAD

**Issue by plexiondev** [ppy/osu#14299] opened 2021-08-14 17:20 UTC
**Describe the bug:** When opening the edit menu, scrolling the page will cause all contents of the page (text, icons etc.) to clip 1 pixel onto the header. This happens no matter the screen scaling option, but does scale accordingly. It can be seen most clearly with the new colour swatches at the bottom of the window.

**Screenshots or videos showing encountered issue:** https://youtu.be/GhwDA8UzOAQ

![osu_2021-08-14_18-17-40](https://user-images.githubusercontent.com/46572320/129455248-db1a7ace-7f89-452e-be0e-16533db29552.png)
![osu_2021-08-14_18-17-17](https://user-images.githubusercontent.com/46572320/129455249-ad9b7cf2-3366-49f9-a6f3-44a0111e7ef4.png)
![osu_2021-08-14_18-17-31](https://user-images.githubusercontent.com/46572320/129455250-05f88d76-5fa6-46d2-88d7-6db285e029a8.png)

**osu!lazer version:** 2021.815.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/6986915/database.log)
[network.log](https://github.com/ppy/osu/files/6986916/network.log)
[performance.log](https://github.com/ppy/osu/files/6986917/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6986918/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6986919/updater.log)

**Comment by bdach** [comment] 2021-08-14 17:22
Duplicate of #13340

**Closed by bdach** 2021-08-14 17:22 UTC
