### ISSUE TITLE
Game freezes from quick restarting while exiting the beatmap

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#5129] opened 2019-06-23 18:46 UTC
**Describe the bug:** As stated in the title, the game is stuck in a screen showing only the map's background if you quick restart while exiting the beatmap (? issue is hard to replicate and not sure if those are the right conditions). The only thing you can do is to access chat and social browser overlay - you can't exit to the menu nor exit the game.

**Screenshots or videos showing encountered issue:** https://youtu.be/iWjvpDMfON8

**osu!lazer version:** 2019.621.0

**Logs:** [performance.log](https://github.com/ppy/osu/files/3318409/performance.log)
[database.log](https://github.com/ppy/osu/files/3318410/database.log)
[runtime.log](https://github.com/ppy/osu/files/3318412/runtime.log)

**Comment by TPGPL** [comment] 2019-06-23 18:48
![obraz](https://user-images.githubusercontent.com/19843905/59980573-324f5a00-95f8-11e9-9933-b3b15c6d3814.png)

also I think this issue might be related to the fail animation as i both restarted the beatmap and accessed menu while hearing the fail animation and the freeze happened

**Comment by iiSaLMaN** [comment] 2019-06-24 03:28
it's not really related to fail animation, whenever you pause, the track rate slows down quickly

**Comment by abbradar** [comment] 2019-08-17 09:10
Possibly duplicate of https://github.com/ppy/osu/issues/1020

**Comment by Joehuu** [comment] 2019-09-19 01:12
Fixed in #6093.

**Closed by Joehuu** 2019-09-19 01:12 UTC
Labels: bug, gameplay
