### ISSUE TITLE
Caught objects in catch flip with the Catcher

### ISSUE THREAD

**Issue by amberkowalski** [ppy/osu#12288] opened 2021-04-04 07:54 UTC
When playing lazer's catch gamemode, I've found the CaughtObjects and the HitExplosions flipping with the Catcher to be confusing. Since the hit explosion isn't where you would expect it to be, especially if you've played catch on stable.

The catch players I've brought this up with have also expressed that they do not like how the caught objects flip with the Catcher.

Stable behaviour:
https://user-images.githubusercontent.com/4877041/113501916-7cb07b00-94ee-11eb-95c0-225e01595bc1.mp4
The caught objects are static relative to the Catcher's position. 

Current Lazer behaviour:
https://user-images.githubusercontent.com/4877041/113502155-0dd42180-94f0-11eb-9d0f-96a77de73d17.mp4
Autoplay makes it harder to tell, but the caught objects flip with the Catcher.

Proposed Lazer behaviour:
The caught objects and hit explosions should not flip with the platter. I have a working implementation of this [here](https://github.com/amberkowalski/osu/tree/catch-platterfruit) which replicates stable.

**Comment by bdach** [comment] 2021-04-04 08:05
I believe I've read somewhere that the current flipping behaviour was implemented intentionally, but I can't actually find a commit/pull that would mention that. Maybe @ekrctb will know.

Not that I'm saying that the flip should remain as is.

**Comment by bdach** [comment] 2021-04-04 09:31
Actually, as @Joehuu spotted on discord, this is a duplicate of #11112.

**Closed by bdach** 2021-04-04 09:31 UTC
Labels: area:gameplay, ruleset:osu!catch, type:UI
