### ISSUE TITLE
osu!taiko gameplay area masked at extreme vertical screen scaling

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#14761] opened 2021-09-16 03:42 UTC
**Extremes of Vertical/Horizontal scale clip game elements** 

Settings for this screenshot:
Horizontal Position: 50%
Vertical Position: 50%
Horizontal Scale: 100%
Vertical Scale: 20%
![osu_2021-09-16_04-38-14](https://user-images.githubusercontent.com/30021847/133545561-1c5baeee-ea22-4843-a026-29736f126141.jpg)

changing Horiz/Verti. position does not seem to fix this issue either.
I suspect this "offset" is also what is causing the FL issues not being centred as detailed in #14734 

**osu! 2021.907.0-lazer**

**Comment by peppy** [comment] 2021-09-16 04:08
only in taiko?

**Comment by peppy** [comment] 2021-09-16 04:09
is this using gameplay scale mode? this issue is missing actionable information.

**Comment by mangomizer** [comment] 2021-09-16 04:25
It is bugged for all three schemes of screen scaling (Everything, Excluding Overlays, and Gameplay)

osu! and osu!mania does not have any issues as far as I can tell

Obviously issue in osu!taiko as mentioned before
osu!catch also has an interesting issue where extremes of Vertical scaling makes sliders appear spontaneously?? Also Yuzu has legs?! (see video below)
https://user-images.githubusercontent.com/30021847/133549114-0473a97c-1014-40e3-b39b-b332c7041906.mp4

**Comment by peppy** [comment] 2021-09-16 05:57
That’s behaving as intended.

**Comment by mangomizer** [comment] 2021-09-16 09:43
fwiw, I think this issue was not present when scaling was first introduced. Would need to check though.

Regarding catch - are you sure?
This would change allow one to change stable AR10 to something that feels like AR7 by simply changing the playfield. This was something that was never achievable in the past and I feel would make the game significantly easier - I believe a score set on this mode would be considered "less impressive" in terms of the reading requirement

For both these points I'll try and get confirmation.

**Comment by ekrctb** [comment] 2021-09-16 09:45
The catch issue is #11012

**Comment by Detze** [comment] 2024-01-31 22:15
This was fixed in https://github.com/ppy/osu/pull/23325 I believe.

**Closed** 2024-01-31 23:13 UTC
Labels: ruleset/osu!taiko, priority:2
