### ISSUE TITLE
"Screen scaling: Gameplay" cuts off approach circles

### ISSUE THREAD

**Issue by Qunas101** [ppy/osu#26878] opened 2024-01-31 09:05 UTC
### Type

Game behaviour

### Bug description

If you set Screen scaling to Gameplay, you would see approach circles getting cut of at the edges. This is very distracting during gameplay and turns this option unusable. It's the only option that does not affect other menus and keeps map bg full screen. 

I'm not sure about balancing, maybe that's a separate discussion, but how it looks currently is very wrong imo

I also saw [this discussion](https://github.com/ppy/osu/discussions/20897) and it seems to be a similar issue

### Screenshots or videos

![osu_2024-01-31_10-41-59](https://github.com/ppy/osu/assets/40661883/bfdf06f2-2036-44c3-b310-c5f67b278900)

### Version

2024.130.2

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14109423/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-31 09:07
> I'm not sure about balancing, maybe that's a separate discussion, but how it looks currently is very wrong imo

The balancing _is_ the point. You would have an advantage if approach circles _weren't_ cut off.

**Comment by Qunas101** [comment] 2024-01-31 09:19
I understand that, but you can still play around with horizontal/vertical scaling and essentially trade vertical cutting off with horizontal, depending on the map perhaps. Is it not a balancing concern?
 
For example:
| ![osu_2024-01-31_11-14-05](https://github.com/ppy/osu/assets/40661883/ddf00ab2-2347-40f7-b075-6aaf749ee086) | ![osu_2024-01-31_11-13-51](https://github.com/ppy/osu/assets/40661883/ea77acc7-d7aa-4750-94b9-b9ef8929223c) |
| --- | --- |
|Default settings|More vertical space with less horizontal to stay at the same size

**Comment by bdach** [comment] 2024-01-31 09:22
I'm not sure what those last screenshots are showing.

**Comment by frenzibyte** [comment] 2024-01-31 09:23
I'm just going to mark this as a duplicate of https://github.com/ppy/osu/issues/5353, no need for another thread.

**Closed** 2024-01-31 09:24 UTC

**Comment by Qunas101** [comment] 2024-01-31 09:27
My bad. Do I still describe it or just move on?

**Comment by bdach** [comment] 2024-01-31 09:39
@Qunas101 please do because if the clipping can be somehow bypassed somewhere else then we may need to actually introduce it there too

**Comment by Qunas101** [comment] 2024-01-31 09:53
It's not completely bypassed, you are "trading" vertical slicing for horizontal

So what I did was increase vertical scaling to it's max and decrease horizontal scaling until the playfield overall stays at a desired scale. 
This results in no approach circles getting cut off at the top and bottom of the map, but instead they will get cut off at the sides of the map. So if a map has a few hit circles near the side edges, the impact will be minimal. The reverse logic applies

**Comment by Qunas101** [comment] 2024-01-31 10:01
Personally, I don't think seeing full approach circles is that beneficial, but you probably know more than me. I'm just reporting my observations
