### ISSUE TITLE
loudness normalization

### ISSUE THREAD

**Issue by arily** [ppy/osu#10039] opened 2020-09-02 21:58 UTC
**Describe the new feature:** 
different songs may have their loudness mismatched and sometimes frustrating to switch from on to another.
in recent years iTunes introduced their algorithm to flat-out the loudness.

I think it will be great if osu have the same.
**Proposal designs of the feature:** 
calculate the loudness adjusting offset based on a song's loudness (for iTunes it's -13LUFS)

normalize the hitsound volume to about the same as the adjusted song when the fader is set to 50%(in game volume panel), and 75%(in the beatmap editor)

add the option to enable this feature in the options menu

**Comment by bdach** [comment] 2020-09-02 22:00
Duplicate of #1600

**Closed by bdach** 2020-09-02 22:00 UTC

**Comment by arily** [comment] 2020-09-02 22:11
should I comment on the first issue or just leave this here?

**Comment by frenzibyte** [comment] 2020-09-02 22:25
In addition to the above, please search before reporting an issue next time to avoid duplicates, as [https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#I-would-like-to-submit-an-issue](3) mentions in one of its points.

> should I comment on the first issue or just leave this here?

I don't think there's need to.

**Comment by arily** [comment] 2020-09-02 22:39
sure. I'll do more search before opening a issue next time.
I actually did the search for "loudness", "normalization" and "volume", and the first issue didn't coming out.
