### ISSUE TITLE
Avatars (and other online textures) are being downscaled using nearest-neighbour

### ISSUE THREAD

**Issue by peppy** [ppy/osu#13255] opened 2021-05-31 05:57 UTC
May need framework side consideration, but requires some further investigation. `Linear` filtering is being specified in `LargeTextureStore` but seemingly not used (textures look to be nearest-neighbour downscaling).

![20210531 145503 (dotnet)](https://user-images.githubusercontent.com/191335/120146524-2f1b6a80-c220-11eb-814a-3b5a1bb0c72a.png)

![20210531 145539 (dotnet)](https://user-images.githubusercontent.com/191335/120146599-4a867580-c220-11eb-888d-4ed463a2356f.png)

**Comment by smoogipoo** [comment] 2021-05-31 08:19
It seems like this is the best GL_LINEAR can do here, surprisingly. I'm not sure I 100% believe there is no problem from our side, but I inspected the pipeline via RenderDoc and GL_LINEAR is indeed being applied. I also tried setting the params after the GL.Tex*Image calls and there's no difference.

**Comment by smoogipoo** [comment] 2021-05-31 08:31
Closing this one as invalid. Looks to be working as intended.

**Comment by peppy** [comment] 2021-05-31 08:32
Can we leave it open to track the avatars looking bad? Or shall I make a new issue?

**Closed by smoogipoo** 2021-05-31 08:31 UTC
Labels: framework-fix-required

**Comment by smoogipoo** [comment] 2021-05-31 08:32
Separate please, this issue's already polluted.
