### ISSUE TITLE
Song select crash with tilde key

### ISSUE THREAD

**Issue by xzCobra** [ppy/osu#12566] opened 2021-04-24 18:30 UTC
**Describe the crash:** 
Entering song select and hitting the tilde (`/~) key and escape at the same time causes errors on click, eventually crashing.
(sorry if dupe btw, didnt find any other issues related to this)

**Screenshots or videos showing encountered issue:** 
[Streamable](https://streamable.com/kem7mj)

**osu!lazer version:** 
2021.424.0

**Logs:**
[runtime.log](https://pastebin.com/sRvdEmub)

**Comment by bdach** [comment] 2021-04-24 18:37
This is actually a duplicate of #11511 - the same assertion is being tripped. I couldn't find the issue myself for a good five minutes, though, so I'll rename it for better tracking.

**Comment by frenzibyte** [comment] 2021-04-24 18:37
Technically duplicate of https://github.com/ppy/osu/issues/11511

**Closed** 2021-04-24 18:37 UTC
