### ISSUE TITLE
On local leaderboards when past username is taken by another user their profile is linked to the score.

### ISSUE THREAD

**Issue by Wrongwayscout** [ppy/osu#25291] opened 2023-10-29 09:25 UTC
### Type

Game behaviour

### Bug description

Imported scores under my first username "Wrongwayscout" which nobody else has taken since I used it, are properly displayed as my current profile (the scores from 4 years ago in screenshot) 

But, imported scores under my second username "Megumin_" are displayed as the profile of the person who currently has that username.

I've noticed this for a long time, not sure how it would be fixed, but it definitely confused me a lot the first time I encountered it. 
Maybe the game could check the logged in user's past usernames and prioritize that over other accounts with those usernames?
At the very least it would be nice for replays in lazer to be identified with the user id (if they aren't already) so that this doesn't happen to people in the future.

### Screenshots or videos

<img width="402" alt="Screenshot 2023-10-29 020259" src="https://github.com/ppy/osu/assets/84840821/f6f265b2-f3f9-4329-ac45-2ec78f82e1ff">

### Version

2023.1026.0

### Logs

[database.log](https://github.com/ppy/osu/files/13197657/database.log)
[input.log](https://github.com/ppy/osu/files/13197658/input.log)
[network.log](https://github.com/ppy/osu/files/13197659/network.log)
[performance.log](https://github.com/ppy/osu/files/13197660/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13197661/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13197662/updater.log)

**Comment by peppy** [comment] 2023-10-30 07:33
This is a limitation of the `.osr` format, as it doesn't include a user_id historically.

Not sure there's much more to do heree.

**Comment by bdach** [comment] 2023-10-30 07:34
I don't think we should be doing this:

> Maybe the game could check the logged in user's past usernames and prioritize that over other accounts with those usernames?

but this we definitely could:

> At the very least it would be nice for replays in lazer to be identified with the user id (if they aren't already) so that this doesn't happen to people in the future.

**Comment by frenzibyte** [comment] 2024-01-31 01:50
Duplicate of #24624

**Closed** 2024-01-31 01:50 UTC
Labels: area:replay
