### ISSUE TITLE
Editor audio doesnt follow gameplay in specific cases 

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#14214] opened 2021-08-10 17:10 UTC
It looks like both audio/gameplay are supposed to pause once the end of a song is reached but that's not what happens when we drag to the end and back again. Map in video: https://osu.ppy.sh/beatmapsets/1300480

**video:** https://www.youtube.com/watch?v=pcluiXShqc8
**osu!lazer version:** 2021.809.0-lazer

**Comment by frenzibyte** [comment] 2021-08-10 23:24
Seems to be yet another regression from the BASSmix changes, and doesn't look to be resolved by ppy/osu-framework#4676.

Seeking to the end and then playing again should loop back to the beginning, but it seems that behaviour has changed now as well.

**Closed** 2021-08-11 03:12 UTC
Labels: priority:0, area:editor, type:audio
