### ISSUE TITLE
clicking the orange cursor when unpausing counts as input

### ISSUE THREAD

**Issue by sawawas** [ppy/osu#27505] opened 2024-03-06 01:49 UTC
### Type

Game behaviour

### Bug description

the orange cursor you click when trying to unpause counts as a click ingame, and if it's ontop of a circle that just appeared, you will miss for clicking too early

i dunno
im on apple silicon if that helps

### Version

2024.302.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14503461/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-03-06 03:07
Duplicate of https://github.com/ppy/osu/issues/9658

**Closed by Joehuu** 2024-03-06 03:07 UTC
