### ISSUE TITLE
Show sliderbreaks on score

### ISSUE THREAD

**Issue by Trislot** [ppy/osu#9368] opened 2020-06-24 21:17 UTC
I'm thinking about something until i started play osu! , why can't we see how many sliderbreaks we did on the score pannel at the end of a map. 
I'm pretty sure adding this on lazer client will be cool!

(Sorry for my poor english btw :/)

**Comment by Joehuu** [comment] 2020-06-24 21:18
Duplicate of https://github.com/ppy/osu/issues/8102

**Closed by Joehuu** 2020-06-24 21:18 UTC
