### ISSUE TITLE
Hiding Aspects in Gameplay

### ISSUE THREAD

**Issue by AnxietyWump** [ppy/osu#8908] opened 2020-04-30 07:02 UTC
**Describe the new feature:** 
Pretty simple idea. I came up with this recently actually, and I think it would be nice for someone like me (who EASILY gets distracted). Basically, make a “UI” or “Gameplay” section in the Options menu that allows us to hide certain aspects of the gameplay, such as the score counter in the corner.
**Proposal designs of the feature:** 
Maybe just a toggle button on/off in options. Or you could make it a keybind, kind of like *tab* and how it hides the player scoreboard! 

Thank you!

**Comment by Game4all** [comment] 2020-04-30 07:11
IIRC the new skinning system should allow moving / hiding certain pieces of the game play HUD in the future, so this overlaps with / is a duplicate of #4632. You can use for now the SHIFT+TAB keybind to completely hide the gameplay HUD while playing on lazer and stable.

**Comment by peppy** [comment] 2020-04-30 07:22
Yep, #4632 covers this exact scenario. Also shift-tab may work for you in the mean time.

**Closed by peppy** 2020-04-30 07:22 UTC
