### ISSUE TITLE
[Android]App won't install

### ISSUE THREAD

**Issue by Blue-Beaker** [ppy/osu#11381] opened 2020-12-31 11:26 UTC
**Describe the bug:** 
App won't install, reporting app not installed. even the pm install command won't work.
for 2020.1225.0 app can be installed properly.

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2020.1229.0
**Logs:**

**Comment by bdach** [comment] 2020-12-31 11:28
Can you give any error messages at least, besides just stating that it doesn't work?

**Comment by bdach** [comment] 2020-12-31 11:36
Just quickly tested (along with @Gabixel on discord) and I cannot reproduce this. Closing until any significant details are provided.

**Closed by bdach** 2020-12-31 11:36 UTC

**Comment by Joehuu** [comment] 2020-12-31 21:45
Can reproduce the other way around (when trying to install last release).

**Comment by LeNitrous** [comment] 2021-01-01 00:18
I thought it was my dodgy LineageOS ROM but I can also confirm that it won't install on my device as well.

**Comment by bdach** [comment] 2021-01-01 00:34
I'm still not seeing any more relevant details in the above comments other than "it doesn't work".

**Comment by Blue-Beaker** [comment] 2021-01-01 02:11
I tried to install via su terminal:
`1|:/data/local/tmp # pm install sh.ppy.osulazer.apk                                
Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to c
ollect certificates from /data/app/vmdl138045826.tmp/base.apk:
Failed reading assemblies/osu.Game.Resources.dll in android.uti
l.jar.StrictJarFile@7adb213: META-INF/MANIFEST.MF has invalid d
igest for assemblies/osu.Game.Resources.dll in assemblies/osu.G
ame.Resources.dll]
1|:/data/local/tmp #
`
Device Information:
Model: Xiaomi Mi8
Android:9
ROM:MIUI 11.0.4
Rooted:True, Magisk 20.4
