### ISSUE TITLE
Overlay caught on opening another menu

### ISSUE THREAD

**Issue by SpikyPillow** [ppy/osu#5136] opened 2019-06-24 06:03 UTC
**Describe the bug:** 
When opening the social browser and then chat, the overlay gets stuck on. As far as I have tested this works with any two combinations in any order, as long as you open another menu with one open. The only way I've found to stop the bug is to restart osu!lazer.

**Screenshots or videos showing encountered issue:** 
![gif](https://user-images.githubusercontent.com/51576746/59995009-8b7cb500-961b-11e9-9eba-eb1703bdd66a.gif)

**osu!lazer version:** 
2019.621.0

**Comment by Joehuu** [comment] 2019-06-24 06:05
Duplicate of #5118.

**Comment by smoogipoo** [comment] 2019-06-24 06:07
Closing as duplicate.

**Closed by smoogipoo** 2019-06-24 06:07 UTC
