### ISSUE TITLE
slider start circles sometimes change their position slightly after being hit

### ISSUE THREAD

**Issue by libverest** [ppy/osu#7849] opened 2020-02-15 18:31 UTC
**Describe the bug:** 
So I've had this bug for a long time (since I first dl'd osu!lazer a year ago?). Whenever I play a random osu!std map and I click the slider start circle, it sometimes moves a tiny bit in the direction of the slider body path when fading out, it's barely noticeable. The distance it moves maybe depends on slider velocity. It isn't reproducible with Autoplay and Relax, it also happens with custom skins and in imported replays.
**Screenshots or videos showing encountered issue:** 
[random map](https://www.youtube.com/watch?v=4oKQJlYLgiI)
[slowed down version](https://www.youtube.com/watch?v=vKvBEk4PzpY)
**osu!lazer version:** 
2020.215.0.0
**Logs:** 
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/4208834/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/4208835/performance-gamethread.input.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/4208852/performance-gamethread.audio.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/4208836/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/4208837/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4208838/updater.log)
[database.log](https://github.com/ppy/osu/files/4208839/database.log)
[network.log](https://github.com/ppy/osu/files/4208840/network.log)
[performance.log](https://download849.mediafire.com/i983uftthxbg/ym7zkffy9jojjym/performance.log)

**Comment by TheWildTree** [comment] 2020-02-15 19:12
This has been discussed in #7521 - not a bug, it's intentional for the time being. The sliderhead basically moves together with the sliderball, which might feel very different in high SV maps for example, so I hope there will be more discussion about it in the future.

**Comment by bdach** [comment] 2020-02-15 19:36
Closing as duplicate. Discussion can be continued in the aforementioned issue.

**Closed by bdach** 2020-02-15 19:36 UTC
