### ISSUE TITLE
Osu! Lazer Crashes on boot Linux

### ISSUE THREAD

**Issue by breckin** [ppy/osu#7981] opened 2020-02-24 00:04 UTC
**Describe the crash:** 
Osu! Lazer crash on launch on Ubuntu
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=Jbbj-DP3v2E

**osu!lazer version:** 
2020.221.0 AppImage
**Logs:**
*please attach logs here, which are located at:*
- `%AppData%/osu/logs` *(on Windows),*
- `~/.local/share/osu/logs` *(on Linux & macOS).*
[database.log](https://github.com/ppy/osu/files/4242757/database.log)
[network.log](https://github.com/ppy/osu/files/4242758/network.log)
[performance.log](https://github.com/ppy/osu/files/4242759/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4242760/runtime.log)
**Computer Specifications:** 
AMD Ryzen 7 2700
Radeon RX 580
16GB DDR4-3200
Ubuntu 20.04

**Comment by jai-x** [comment] 2020-02-24 00:11
From your `runtime.log` file:
```
020-02-24 00:00:40: VideoDecoder faulted: System.DllNotFoundException: Unable to load shared library 'avformat' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat: cannot open shared object file: No such file or directory
```
The FFMPEG package along with development libraries is required to decode the video introduction.

Duplicate of https://github.com/ppy/osu/issues/7947

**Comment by breckin** [comment] 2020-02-24 00:19
how do i do that

**Comment by breckin** [comment] 2020-02-24 00:22
how do i install the development libraries?

**Comment by whizvox** [comment] 2020-02-24 00:45
I was having OPs original problem, and installing the dev libraries (`sudo apt-get install libavformat-dev`) only brought up a new message.
[runtime.log](https://github.com/ppy/osu/files/4242801/runtime.log)
(the other log files don't appear to contain anything important)

Googling the error code brings me to [this](https://stackoverflow.com/a/28834708) StackoverFlow answer, which basically is a generic message saying that some sort of input was "invalid".

**Closed** 2020-02-24 02:52 UTC
