### ISSUE TITLE
Reversing slider in the editor doesn't work as expected

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#18042] opened 2022-05-01 11:40 UTC
https://user-images.githubusercontent.com/78441708/166115757-5614bd5d-a285-4bcf-9238-08d221370eb2.mp4

map:
[Duskfox & Vixage - Aurora (Axilotl).zip](https://github.com/ppy/osu/files/8597492/Duskfox.Vixage.-.Aurora.Axilotl.zip)
@ 01:32:600

### Discussed in https://github.com/ppy/osu/discussions/18032

<div type='discussions-op-text'>

<sup>Originally posted by **Axilotl17** May  1, 2022</sup>
https://user-images.githubusercontent.com/78441708/166115757-5614bd5d-a285-4bcf-9238-08d221370eb2.mp4

it changes the shape drastically 

map:
[Duskfox & Vixage - Aurora (Axilotl).zip](https://github.com/ppy/osu/files/8597492/Duskfox.Vixage.-.Aurora.Axilotl.zip)
@ 01:32:600
</div>

**Comment by peppy** [comment] 2022-05-01 11:45
This is going to be an oversight in perfect curve reversing, I think.

**Comment by peppy** [comment] 2022-05-03 07:39
I will say that that slider is really badly made (to the point I think you may be misunderstanding perfect cruves?). For instance, the last three points are set to a perfect curve but the placement of them and the length of the segment suggests it's probably not what you want to be using there.

**Comment by peppy** [comment] 2022-05-03 08:03
Looking into a fix, I'm not sure there's a sane way out of this. From a technical standpoint, the issue is that the end of the slider's actual path ends between the two points of the final perfect curve, causing the reversal to place the points the "wrong way" around, and causing an obtuse perfect curve rather than an acute one.

![osu! 2022-05-03 at 07 58 41](https://user-images.githubusercontent.com/191335/166420981-387d74fc-c7a8-4f84-bf9d-8c82ff1cef25.png)

You can see that the reversal did happen "correctly", but the new starting point causes a different curve to be created (note that I moved the post-reverse nodes slightly to make this visible):

![osu! 2022-05-03 at 07 59 46](https://user-images.githubusercontent.com/191335/166421062-b4d6ae18-6b95-4966-bb5f-a6a0bfefd05c.png)


Put another way, this can be fixed by moving the second-last node ever-so-slightly as to not reverse the direction of the perfect curve:

![osu! 2022-05-03 at 08 02 06](https://user-images.githubusercontent.com/191335/166421273-6a8a7072-e423-424f-8bd0-804d0be94030.png)

![osu! 2022-05-03 at 08 02 15](https://user-images.githubusercontent.com/191335/166421297-078a02a7-c780-41b7-b600-3b5501c83618.png)


I don't have a proposed solution, but maybe someone will come up with something. Will likely require handling on a per-curve type in order to move the nodes accordingly to not cause destruction. Not sure this deserves priority 1 as it's a very edge case scenario.

**Comment by cihe13375** [comment] 2023-04-02 12:45
Just saying, it seems that similar problem also exists for simple perfect curve sliders, if the middle anchor goes beyond the slider path. Idk if the internal cause is same though.
![p1](https://user-images.githubusercontent.com/33959010/229353291-f7598ec2-abb6-49e1-8e82-8a33dd99d1f8.png)
![p2](https://user-images.githubusercontent.com/33959010/229353294-b7433b4e-72f4-4bd8-ac6d-7b50beb6d785.png)

**Closed** 2023-08-21 15:12 UTC
Labels: ruleset/osu!, area:editor, priority:1
