### ISSUE TITLE
Dim volume in menu

### ISSUE THREAD

**Issue by LemonJuicer** [ppy/osu#12562] opened 2021-04-24 13:35 UTC
When in game master volume automatically drops to different value than when surfing menu.

**Comment by bdach** [comment] 2021-04-24 13:40
I have no idea what this issue is attempting to say, and the issue template has been thoroughly ignored. Closing until enough details are provided, please put actual
 effort in reporting issues.

**Closed by bdach** 2021-04-24 13:40 UTC

**Comment by LemonJuicer** [comment] 2021-05-01 19:14
Feature request:
Have 2 different volume levels while browsing maps and while playing actual game.

I dont want music to be as loud as when I am playing game while I am browsing the menu. This can be useful for example when speaking to someone or making breaks. However when I am playing I want volume to be louder so I can focus better on the game itself.

**Comment by bdach** [comment] 2021-05-01 19:48
Mostly duplicate of #11298, then. Scenario described there is more specific but a solution can be more generic, as stated [here](https://github.com/ppy/osu/issues/11298#issuecomment-751158854).
