### ISSUE TITLE
Lazer won't open

### ISSUE THREAD

**Issue by FireFlashing** [ppy/osu#8233] opened 2020-03-11 22:40 UTC
**Describe the crash:** 
I'm in Mac Mojave 10.14.6.
When I click on lazer's icon in my macbook, it does the usual "jump" animation which every application does, and then stops.
If it can be useful to know, I already downloaded some past versions, but now the new one just seems to not work. I thought it could have been because of something in the data, so I deleted the folder and the application, and installed it (the application) back, but the problem is there nonetheless.
I also already confirmed the application, and I'm the only user on my pc

**Screenshots or videos showing encountered issue:** 
![Issue osu](https://user-images.githubusercontent.com/40890953/76469953-b9936680-63ef-11ea-9f38-86813000c3b8.gif)

**osu!lazer version:** 
2020.331.0

**Logs:**
As I explained, I deleted the folder ~/.local/share/osu, and the application doesn't seem to create any new folder

**Computer Specifications:** 
Model name:	MacBook Pro
  Model identifier:	MacBookPro11,3
  Processor:	Intel Core i7
  Processor speed:	2,3 GHz
  Amount of processors:	1
  Total Core Number:	4
  Cache L2 (per Core):	256 KB
  Cache L3:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

**Comment by cupppu** [comment] 2020-03-11 23:14
Duplicate of #7791?

**Comment by FireFlashing** [comment] 2020-03-12 06:46
> Duplicate of #7791?

Might be, but I don’t get any error message at all

**Comment by bdach** [comment] 2020-03-12 18:31
I would try to run the game from command line and see if any errors come up. As it stands right now there is not enough details to begin investigating.

**Comment by FireFlashing** [comment] 2020-03-12 18:50
I tried running it from the terminal, and it returns this line:

LSOpenURLsWithRole() failed with error -10810 for the file /Applications/osu!.app.

**Comment by FireFlashing** [comment] 2020-03-12 19:02
When I try to run the unix executable in _osu\!.app/Contents/MacOS/osu\!_, it returns this:

Unhandled exception. System.TypeInitializationException: The type initializer for 'osuTK.Platform.MacOS.NSApplication' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSystem.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSystem.dylib, 1): image not found
   at osuTK.Platform.MacOS.NS.dlopen(String fileName, Int32 flags)
   at osuTK.Platform.MacOS.NS.LoadLibrary(String fileName)
   at osuTK.Platform.MacOS.Cocoa.Initialize()
   at osuTK.Platform.MacOS.NSApplication..cctor()
   --- End of inner exception stack trace ---
   at osuTK.Platform.MacOS.NSApplication.Initialize()
   at osuTK.Platform.MacOS.MacOSFactory..ctor()
   at osuTK.Platform.Factory..ctor()
   at osuTK.Toolkit.Init(ToolkitOptions options)
   at osu.Framework.Platform.GameHost.SetupToolkit()
   at osu.Framework.Platform.DesktopGameHost.SetupToolkit()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /usr/local/var/buildkite-agent/builds/ppybin-parallels-macos-1/ppy/osu/osu.Desktop/Program.cs:line 57
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by bdach** [comment] 2020-03-12 19:05
Seems like a duplicate judging by that trace - [see this comment](https://github.com/ppy/osu/issues/7791#issuecomment-592934971). Closing as such.

**Closed by bdach** 2020-03-12 19:05 UTC
Labels: missing details, platform:macOS
