### ISSUE TITLE
Game crashes mid song

### ISSUE THREAD

**Issue by VagueConnorg** [ppy/osu#6610] opened 2019-10-25 18:32 UTC
**Describe the crash:** 
The game keeps crashing mid song which freezes the beatmap, background/storyboard, but the song keeps playing.  It crashes every 3 minutes for me and I can’t fix it.
**Screenshots or videos showing encountered issue:** 
N/A
**osu!lazer version:** 
Most recent IOS version
**Logs:** 
N/A
**Computer Specifications:** 
Game affecting crash that I would like fixed ASAP

**Comment by bdach** [comment] 2019-10-25 18:34
Duplicate of #6355.

**Closed by bdach** 2019-10-25 18:34 UTC
