### ISSUE TITLE
Daycore sometimes displays a lower star rating than Half Time

### ISSUE THREAD

**Issue by vicky5124** [ppy/osu#14346] opened 2021-08-16 14:57 UTC
**Describe the bug:** 
Daycore sometimes displays a lower star rating than Half Time
It appears that Daycore is randomly displaying the star rating as if it was at 0.5 speed (the minimum selectable), rather than the current speed set, 0.75 on the video as its default.

Maps used on the video:
https://osu.ppy.sh/beatmapsets/792185#osu/1685500
https://osu.ppy.sh/beatmapsets/724192#osu/1529189
https://osu.ppy.sh/beatmapsets/755311#osu/1589931
https://osu.ppy.sh/beatmapsets/930865#osu/1943817

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/8344197/129582985-3b25663e-7fe6-4c42-99ee-95946a0169cb.mp4

**osu!lazer version:** 
2021.815.0-lazer
Linux `.AppImage` being used.

**Logs:**
[logs2.zip](https://github.com/ppy/osu/files/6993272/logs2.zip)

**Comment by frenzibyte** [comment] 2021-08-17 00:09
Duplicate of https://github.com/ppy/osu/issues/9669. Please search.

**Closed by frenzibyte** 2021-08-17 00:09 UTC
Labels: area:difficulty, priority:1
