### ISSUE TITLE
osu has stopped working.

### ISSUE THREAD

**Issue by darkralts** [ppy/osu#823] opened 2017-05-22 04:14 UTC
when i run the installer it installs fine, then when i run osu!.exe it hangs and then says osu! has stopped working, and then crashes.
![image](https://cloud.githubusercontent.com/assets/16366107/26292402/9a2b481a-3e83-11e7-8557-0c0175f8a54a.png)

**Comment by MrTheMake** [comment] 2017-05-22 11:34
Are you able to debug this yourself? Otherwise, fixing this would be hard as we can not reproduce the exact same scenario with your setup.
Nevertheless, posting your specs would be a good start.

**Comment by huoyaoyuan** [comment] 2017-05-22 11:40
Will it help to make a basic crash logger? Just handles `AppDomain.CurrentDomain.UnhandledException`, and write message and stack trace to text. It helps getting crash information for deployed builds.

**Comment by peppy** [comment] 2017-05-22 11:47
You're welcome to add global crash logging out `Logger` using `LogTarget.Runtime`

**Comment by Lolihunter1337** [comment] 2017-05-23 04:11
i get the same issue. i can open the chat and use key shortcuts. but in the middel of "Welcome to osu" it crashes

**Comment by darkralts** [comment] 2017-05-23 13:54
Oh mine crashes before that

**Comment by Raymonf** [comment] 2017-05-23 20:24
@darkralts Are you using a NVIDIA GPU? If so, try to do a clean install of the drivers. Worked for me. /shrug

**Comment by Shawdooow** [comment] 2017-05-23 20:35
I've noticed older intel graphics (can't give exact date) seem to not run reliably with lazer atm. Not sure the cause as I have no pcs to test with.

**Comment by Lolihunter1337** [comment] 2017-05-24 00:51
@Shawdooow maybe interesting to know that even if i uninstall and re-install and older version of osu!lazer it crashes at the same spot

**Comment by ColdVolcano** [comment] 2017-05-24 00:57
problems with crashing with some intel driver has been since the first pre-release...

**Comment by huoyaoyuan** [comment] 2017-05-24 13:45
The latest version is containing a crash logger. Update or install it, check `AppData\Roaming\osu\logs\runtime.log` and see if there is a log of fatal error.
(Some very low-level crash may not be logged by the logger)

**Comment by Lolihunter1337** [comment] 2017-05-24 14:02
i leave my runtime log here 
[runtime.txt](https://github.com/ppy/osu/files/1025778/runtime.txt)

**Comment by darkralts** [comment] 2017-05-26 11:54
Yeah im using intel integrated graphics...

**Comment by VPeruS** [comment] 2017-05-26 12:56
I used integrated Intel too. But it doesn't crash.

<details>
<summary>glxinfo</summary>

display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4

client glx vendor string: Mesa Project and SGI
client glx version string: 1.4

GLX version: 1.4

Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) Haswell Mobile  (0xa16)
    Version: 17.0.0
    Accelerated: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.0.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 17.0.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.0.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10

</details>

**Comment by darkralts** [comment] 2017-05-26 22:25
how do i get the crash log?

**Comment by ColdVolcano** [comment] 2017-05-26 22:29
![like this](https://cloud.githubusercontent.com/assets/16726733/26514668/db6cd2a4-4238-11e7-8ddf-32de5298c886.png)

**Comment by Yolkis** [comment] 2017-05-28 16:32
![image](https://cloud.githubusercontent.com/assets/17850844/26530313/93aa7daa-43f4-11e7-8f94-81780dd4ca12.png)
[osu!laser](http://pastebin.ru/dQITIaKw)
[osu!](http://pastebin.ru/tk6Z4XqU)
Intel HD Graphics 3000

**Comment by darkralts** [comment] 2017-05-30 11:34
Same exact thing happens to me.
Specs:
Core i5 2520m
Using integrated graphics.
4gb ram
64 bit.

**Comment by peppy** [comment] 2017-05-30 11:35
specs and "same" are useless. please don't

**Comment by Kontorted** [comment] 2017-06-10 17:44
I have also noticed this issue existed for me. There was some corrupt osu files, killing the process before it could run. A re-install should work for you.

**Comment by Lolihunter1337** [comment] 2017-08-21 10:26
Looks like the new Windows 10 x64 Build 16257 Seems to doesnt like the new version 
[runtime.txt](https://github.com/ppy/osu/files/1238518/runtime.txt)

**Comment by peppy** [comment] 2017-11-15 11:10
Closing due to lack of exception log.

**Closed by peppy** 2017-11-15 11:10 UTC
Labels: bug
