### ISSUE TITLE
Game muted on ALT + F4

### ISSUE THREAD

**Issue by jack-hickey** [ppy/osu#9675] opened 2020-07-25 15:43 UTC
When pressing ALT + F4 to exit the game, it mutes the entire thing. The problem is that when pressing escape to come out of the confirmation dialog, the game remains muted until you press ALT + F4 again.

Here's an image below that just shows which dialog im talking about

![image](https://user-images.githubusercontent.com/24756358/88460701-f8edbb80-ce95-11ea-80b6-b2047614a44e.png)

**Comment by bdach** [comment] 2020-07-25 15:44
Duplicate of #3483

**Closed by bdach** 2020-07-25 15:44 UTC
