### ISSUE TITLE
Osu skin name keeps getting longer

### ISSUE THREAD

**Issue by KamelTheAsian** [ppy/osu#30940] opened 2024-12-01 22:15 UTC
### Type

Game behaviour

### Bug description

I noticed that when I keep importing and reimporting skins to osu!lazer, their name keeps getting longer and longer. I tried editing the folder name, skin.ini, and skininfo.json but nothing works. please help

### Screenshots or videos

![Screenshot 2024-12-01 230103](https://github.com/user-attachments/assets/3afe2459-2073-4e40-b8dd-392619eda367)

### Version

Lazer 2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17970484/compressed-logs.zip)

**Comment by Gabixel** [comment] 2024-12-03 08:42
I believe this is a duplicate of https://github.com/ppy/osu/issues/26527.
This seems to happen a lot since exporting and importing a skin multiple times to make quick specific changes is a fairly common thing. I also sometimes end up with rather long and repetitive skin names.
Another example [here](https://discord.com/channels/188630481301012481/1097318920991559880/1271819764515475509) on Discord.

**Closed** 2024-12-03 08:47 UTC
Labels: missing details, area:skinning
