### ISSUE TITLE
Spinner Spinning Sound

### ISSUE THREAD

**Issue by Exaskliri** [ppy/osu#9679] opened 2020-07-26 03:00 UTC
I liked it when slider sounds were re-added to lazer. So, please add spinnerspin sound back (spinner lacks the feedback sound, after all. besides the spinner bonus).

**Comment by frenzibyte** [comment] 2020-07-26 03:01
Duplicate of https://github.com/ppy/osu/issues/4631, PR still requires dependencies and has encountered an issue with the playback so it's currently work-in-progress.

**Closed** 2020-07-26 03:03 UTC
