### ISSUE TITLE
Dashboard shows different statuses on frends/search page

### ISSUE THREAD

**Issue by Proxima36** [ppy/osu#27404] opened 2024-02-27 16:14 UTC
### Type

Cosmetic

### Bug description

The friends tab just shows "online". To get exact status (like MP room name) you have to type the person into the search bar on "currently online" tab.

### Screenshots or videos

| friends   |      search      | 
|----------|:-------------:|
|![NVIDIA_Share_2024-02-27_18-33-50](https://github.com/ppy/osu/assets/65703743/6f685e31-78ac-4d5d-a2d3-858dee21334e)|![NVIDIA_Share_2024-02-27_18-39-54](https://github.com/ppy/osu/assets/65703743/e170fb7a-ccf7-4f9d-a064-2f291245fe78)

### Version

2024.221.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/14422657/logs.zip)

**Comment by frenzibyte** [comment] 2024-07-10 08:41
Safe to say this is a duplicate of https://github.com/ppy/osu/issues/24042

**Closed by frenzibyte** 2024-07-10 08:41 UTC
Labels: type:online, area:overlay-dashboard
