### ISSUE TITLE
Exiting to main menu resets current collection to All beatmaps

### ISSUE THREAD

**Issue by OlenTK** [ppy/osu#26841] opened 2024-01-30 21:27 UTC
### Type

Cosmetic

### Bug description

When you select a collection from the dropdown menu, and then press escape to go to the main menu, the collection goes back to All beatmaps and doesn't stay in the previously selected collection. 
Not sure if this is by design, but it was not like this in stable.

### Screenshots or videos

https://github.com/ppy/osu/assets/126420913/be402871-6360-4be1-a21f-f3d9f249fe2c

### Version

2024.130.2-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14104537/compressed-logs.zip)

**Comment by bdach** [comment] 2024-01-30 21:44
Mostly duplicate of https://github.com/ppy/osu/issues/10507

**Closed by bdach** 2024-01-30 21:44 UTC
