### ISSUE TITLE
Certain beatmaps desynchronise from track after skipping

### ISSUE THREAD

**Issue by MishterKirby** [ppy/osu#14319] opened 2021-08-15 19:37 UTC
**Describe the bug:** 
The hitobjects get offset randomly after a spinner. This happens inconsistently, but is reproducible if you exit the beatmap and reenter it continuosly.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/g3fl0w
_I also have footage of stable, if it's necessary to compare_

**osu!lazer version:** 
2021.815.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/6988758/database.log)
[network.log](https://github.com/ppy/osu/files/6988759/network.log)
[performance.log](https://github.com/ppy/osu/files/6988760/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6988761/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6988762/updater.log)

Not 100% sure this has been reported, but I searched around and didn't find anything, so if it's been reported before, feel free to close.

**Comment by frenzibyte** [comment] 2021-08-15 20:06
The desynchronisation occurs when you press the skip button, appearently. I'll dig further.

**Comment by bdach** [comment] 2021-08-15 20:12
The beatmap has an ogg backing track with variable bitrate, so this is a duplicate of #10671.

**Closed by bdach** 2021-08-15 20:12 UTC
Labels: ruleset:osu!, area:gameplay, priority:1
