### ISSUE TITLE
Crash when playing normal map

### ISSUE THREAD

**Issue by BunnyPL** [ppy/osu#11455] opened 2021-01-10 20:10 UTC
**Describe the crash:** 
Random crash when playing normal solo map, first only playground going freeze (only cursor works) and after some seconds game crashed. (Perfect English :\)

**Screenshots or videos showing encountered issue:** 
![Zrzut ekranu 2021-01-10 210842](https://user-images.githubusercontent.com/59777089/104134131-1e10b080-5388-11eb-80f9-14c17143141b.png)

**osu!lazer version:** 
2021.109.0

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/5793235/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5793236/performance.log)
[updater.log](https://github.com/ppy/osu/files/5793237/updater.log)
[database.log](https://github.com/ppy/osu/files/5793238/database.log)
[network.log](https://github.com/ppy/osu/files/5793239/network.log)

**Computer Specifications:** 
i5-8600k @ 4.7GHz
16 GB DDR4 3000MHz
MSI Z370 SLI PLUS
Aorus RTX 2070 super
3x 1080p monitor

**Comment by bdach** [comment] 2021-01-10 20:26
The logs seem to be either cut short or from another launch of the game entirely. Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by BunnyPL** [comment] 2021-01-10 20:38
Eh, i open once time after crash :/
Hold it:
[osu!lazer-crash-issue#11455-windows-logs.zip](https://github.com/ppy/osu/files/5793277/osu.lazer-crash-issue.11455-windows-logs.zip)

**Comment by BunnyPL** [comment] 2021-01-10 20:49
Can i put here another crash or we must do other thread? If no, catch 5 min ago crash:
[runtime.log](https://github.com/ppy/osu/files/5793288/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5793289/updater.log)
[performance.log](https://github.com/ppy/osu/files/5793290/performance.log)
[database.log](https://github.com/ppy/osu/files/5793291/database.log)
[network.log](https://github.com/ppy/osu/files/5793292/network.log)

**Comment by bdach** [comment] 2021-01-10 20:50
The log cuts out in the middle which indicates this is a higher-level issue. In fact this is in the event log:

```
The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
```

which makes this a duplicate of #10157. Please try upgrading graphics card drivers to rule out this being some sort of driver and report back whether that helps
 in the aforementioned issue.

**Closed by bdach** 2021-01-10 20:50 UTC
Labels: missing details, type:crash
