### ISSUE TITLE
Hitcircles flickering while playing a map in the editor

### ISSUE THREAD

**Issue by riesha** [ppy/osu#18028] opened 2022-04-30 09:26 UTC
### Type

Game behaviour

### Bug description

While playing a map in the editor, the circles will flicker in brightness and sometimes opacity  (this was recorded in windowed mode)

### Screenshots or videos

https://user-images.githubusercontent.com/58556779/166099912-9d0f7174-e703-485a-a843-e4de698c2be3.mp4

https://user-images.githubusercontent.com/58556779/166099979-70262263-bdbd-4cb9-82c4-70524817551e.mp4

### Version

2022.424.1

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/8596545/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8596547/network.log)
[performance.log](https://github.com/ppy/osu/files/8596548/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8596549/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8596550/updater.log)
[database.log](https://github.com/ppy/osu/files/8596551/database.log)

**Comment by riesha** [comment] 2022-04-30 09:30
https://user-images.githubusercontent.com/58556779/166100103-71846e83-4467-43b6-ba69-c382e7ec3062.mp4


here's a stable clip for reference

**Comment by Theighlin** [comment] 2022-04-30 09:35
From my testing on both stable and lazer on another map it looks to me that lazer is applying kiai flashes on editor playback while stable is not?

**Comment by peppy** [comment] 2022-04-30 09:36
This does look kiai related. Can you confirm this only happens during kiai time?

**Comment by riesha** [comment] 2022-04-30 09:41
> This does look kiai related. Can you confirm this only happens during kiai time?

It seems to be kiai related, but it alos happens outside of kiai time in the first map

https://user-images.githubusercontent.com/58556779/166100394-5ba8ec8a-9aef-4e43-8377-5ce8b38adcbb.mp4

It did not on the second one though for some reason.

On a side note even if lazer applying kiai flash in the editor was intentional i feel like it greatly decreases the readability and fankly hurts my eyes (but that is subjective and probably not relevant here)

**Comment by peppy** [comment] 2022-05-05 10:51
Could you please provide a copy of the beatmap you're using in the last post? I downloaded the one from graveyard but the kiai points do not match, and I cannot reproduce what you are seeing.

**Comment by riesha** [comment] 2022-05-05 11:00
> Could you please provide a copy of the beatmap you're using in the last post? I downloaded the one from graveyard but the kiai points do not match, and I cannot reproduce what you are seeing.

Well now thats weird, i deleted the beatmap and redownloaded it from graveyard and the same thing happened but then i deleted it and redownloaded it again and now the kiai points also dont match with the ones from my video?

when i recorded the first videos this control point was a kiai point (from a fresh graveyard dl not a stable import) then i deleted it redownloaded and it was also a kiai point then i deleted it again and redownloaded and now its not a kiai point anymore?
![image](https://user-images.githubusercontent.com/58556779/166909994-0f0cc3de-c1bc-443d-963d-c27adeeacd58.png)

ive also found a new weird bug that might be related? look at the orange triangle in the middle of the editor grid

https://user-images.githubusercontent.com/58556779/166910168-dcb545da-b7a3-449f-9d01-94e165d24d78.mp4

**Comment by peppy** [comment] 2022-05-05 11:03
Going to close this as being another instance of frame stability going wrong. We're tracking this in [multiple issues](https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+frame+label%3Aarea%3Aeditor+) and the solution will likely solve all issues in one swoop.

**Closed by peppy** 2022-05-05 11:03 UTC
Labels: area:editor, type:UX
