### ISSUE TITLE
Can't login on osu!lazer

### ISSUE THREAD

**Issue by salatine** [ppy/osu#4234] opened 2019-02-09 21:00 UTC
I can't login on osu!lazer.
At first I thought I forgot my password, then I changed it and tried again to connect on osu!lazer. I am trying to do it for two days, and it is just not working.

![image](https://user-images.githubusercontent.com/47485804/52526179-46736a00-2c9c-11e9-925e-7cd79b81c185.png)
It just continues like this until it stops randomly.
My username is "salatine".

osu!lazer version: 2019.131.0

[database.log](https://github.com/ppy/osu/files/2848255/database.log)
[network.log](https://github.com/ppy/osu/files/2848256/network.log)
[performance.log](https://github.com/ppy/osu/files/2848257/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2848258/runtime.log)

**Comment by peppy** [comment] 2019-02-10 01:24
Have you disabled any system level services, like Web Client?

**Comment by salatine** [comment] 2019-02-10 12:13
No, I haven't. Tried it now and still the same problem.

**Comment by JSR-Gaming-x** [comment] 2019-05-05 20:27
What operating system are you on? Can you type capital letters? I had to change my password to all lowercase to get it working for me.

**Comment by peppy** [comment] 2019-05-06 02:49
Case is not applicable here. The user has reported it does not return an "invalid username/password" response, but rather that it never actually completes the request. This is 100% network related.

**Comment by Ishidres** [comment] 2019-05-20 18:02
I can reproduce the issue above.
I also noticed that the whole application itself can't connect to the internet.

For example, searching in osu!direct leads to this error in console:
`[network:verbose] 2019-05-20 05:57:58: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)`

**network.log:**
```
2019-05-20 05:57:19: ----------------------------------------------------------
2019-05-20 05:57:19: Network Log for ishidres (LogLevel: Debug)
2019-05-20 05:57:19: osu 0.0.0.0
2019-05-20 05:57:19: Running on Unix 4.17.0.3, 12 cores
2019-05-20 05:57:19: ----------------------------------------------------------
2019-05-20 05:57:19: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:23: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:25: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:28: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:29: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:33: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:53: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:53: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:54: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:55: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
2019-05-20 05:57:58: Failing request osu.Game.Online.API.Requests.SearchBeatmapSetsRequest (System.OperationCanceledException: Request cancelled)
```

**Comment by peppy** [comment] 2019-05-22 02:16
Those operations are likely being cancelled because you are not logged in. If possible, can you run framework visualtests and check network connectivity is available there (`TestWebRequest` from nUnit or `TestSceneAnimation` from visualtests).

**Comment by 45gfg9** [comment] 2019-06-04 04:41
well I guess I am experiencing the same
but that's just my own problem...

network.log:
```
2019-06-04 04:12:20: ----------------------------------------------------------
2019-06-04 04:12:20: Network Log for 45gfg9 (LogLevel: Verbose)
2019-06-04 04:12:20: osu 2019.530.0.0
2019-06-04 04:12:20: Running on Unix 18.6.0.0, 8 cores
2019-06-04 04:12:20: ----------------------------------------------------------
2019-06-04 04:12:20: Request to https://api.github.com/repos/ppy/osu/releases/latest successfully completed!
2019-06-04 04:12:30: We just went Connecting!
2019-06-04 04:12:40: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2019-06-04 04:12:50: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2019-06-04 04:12:50: Login failed!
2019-06-04 04:12:50: We just went Offline!
2019-06-04 04:12:54: We just went Connecting!
2019-06-04 04:13:04: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2019-06-04 04:13:14: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2019-06-04 04:13:14: Login failed!
2019-06-04 04:13:14: We just went Offline!
2019-06-04 04:13:20: We just went Connecting!
2019-06-04 04:13:30: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 0 times). (retrying 1/1).
2019-06-04 04:13:40: Request to https://osu.ppy.sh/oauth/token failed with System.Net.WebException: Request to https://osu.ppy.sh/oauth/token timed out after 10 seconds idle (read 0 bytes, retried 1 times)..
2019-06-04 04:13:40: Login failed!
2019-06-04 04:13:40: We just went Offline!
```

**Comment by peppy** [comment] 2019-06-04 08:18
The weird part is your requests are succeeding to github but not to osu!.

**Comment by Lolihunter1337** [comment] 2019-06-04 08:28
i like to add that i had this issue yesterday. but it fixed it self without me doing any changes to my network settings etc. 
[network.log](https://github.com/ppy/osu/files/3251317/network.log)
[runtime.log](https://github.com/ppy/osu/files/3251318/runtime.log)

**Comment by peppy** [comment] 2020-07-30 13:50
Tentatively closing this as out of scope. I believe this can only happen from system misconfiguration issues and has not been reported recently.

**Closed by peppy** 2020-07-30 13:50 UTC
Labels: type:network

**Comment by 45gfg9** [comment] 2020-07-31 16:13
It's ok, it's reasonable to cleanup old unclear issues
I hadn't run into this problem for some time

**Comment by wolfiiy** [comment] 2020-08-03 22:56
I'm having the same issue :'(
[network.log](https://github.com/ppy/osu/files/5019202/network.log)

**Comment by dolkilu** [comment] 2020-08-10 09:03
Same happened to me for the first time after year long of playing lazer
not able to connect
tried restarting my router/PC, didn't work.
[network.log](https://github.com/ppy/osu/files/5049839/network.log)

**Comment by bdach** [comment] 2020-08-10 09:20
@dolkilu you probably have leftover remembered credentials from the time before we disallowed logging in via email. please try deselecting "remember username/login" when logging in and try again.

**Comment by dolkilu** [comment] 2020-08-10 09:24
> 
> 
> @dolkilu you probably have leftover remembered credentials from the time before we disallowed logging in via email. please try deselecting "remember username/login" when logging in and try again.

thanks, it worked

**Comment by wolfiiy** [comment] 2020-12-22 18:01
Hey, I think I know what went wrong on my end, I'm posting this in case it could help someone.

I am not directly connected to my router, I am using some kind of WLAN connection kit provided by my ISP and it does not support iPV6. Disabling ipv6 on arch (switched from elementary since my last comment) seem to have fixed this issue (among other related problems I had).

I cannot test by connecting to the wifi (no card in the pc) or by cable (too far) with the same device, but other devices work when directly plugged into the router and not when using the same kit.

**Comment by bdach** [comment] 2020-12-22 18:04
@wolfiiy see #3507.

**Comment by SandwichPlays** [comment] 2024-07-22 12:19
welp just happened to me suddenly

**Comment by frenzibyte** [comment] 2024-07-22 14:07
Please open a separate issue thread with details filled out.
