### ISSUE TITLE
i cant play osu :(

### ISSUE THREAD

**Issue by aiden-creates** [ppy/osu#22998] opened 2023-03-26 23:55 UTC
### Type

Other

### Bug description

i set my renderer to openGL (the regular one not legacy). after this, i restarted my game and my game crashed.
this basically prevented me from playing osu lazer
i kept trying to open it again and again, and i had no luck.

i am on ipados 16.3.1
with an M1 iPad Air

### Screenshots or videos

https://user-images.githubusercontent.com/83737418/227812592-dd2ea522-1328-436e-82dc-3ed201f9e24e.mp4

### Version

2023.326.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/11073407/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11073408/performance.log)
[input.log](https://github.com/ppy/osu/files/11073409/input.log)
[database.log](https://github.com/ppy/osu/files/11073410/database.log)

**Comment by Joehuu** [comment] 2023-03-27 00:02
Duplicate of https://github.com/ppy/osu/issues/22978

**Closed by Joehuu** 2023-03-27 00:02 UTC
