### ISSUE TITLE
Using the F5 key

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8850] opened 2020-04-23 09:55 UTC
**Describe the new feature:** 
Now this key in the map selection menu performs the same function as the f2 key. However, we do have a playlist that is formed by the lazer and which will be followed by playback. But in the map selection menu, it still goes randomly.
**Proposal designs of the feature:** 
Let clicking on f5 move us to the playlist, and not by accident.
![image](https://user-images.githubusercontent.com/59089206/80085949-51ae6f00-859c-11ea-8d7d-18534d71fbd2.png)

**Comment by enoslayd** [comment] 2020-04-23 10:26
You can change the key binding in settings

**Comment by Moltanicaa** [comment] 2020-04-23 10:31
You don’t understand what I’m writing about. I write that F5 in the main menu switches the track through the list, and in the map selection menu - randomly.

**Comment by iiSaLMaN** [comment] 2020-04-23 10:42
The <kbd>F5</kbd> key is already doing that? It moves through the playlist in map selection, it's just that the playlist order is different from the song select, that may probably be the reason for letting you mistake it for random selecting.

Unless you're suggesting that <kbd>F5</kbd> should notify that you're actually selecting the next beatmap by the playlist order and open the music controller for that?

**Comment by Moltanicaa** [comment] 2020-04-23 10:49
Strange behavior of this list. If I click on a song myself, it will only go on the list. If not, then he will randomly click.
https://youtu.be/uq7KmNK4uzY

**Comment by iiSaLMaN** [comment] 2020-04-23 11:06
I still fail to understand, what is the issue / feature request here? is it that the <kbd>F5</kbd> key should open up the now-playing overlay with the playlist open? or is it something completely different? please describe more and better.

**Comment by Moltanicaa** [comment] 2020-04-23 11:10
I have a playlist formed. I want to navigate through it in the map menu using f5. Now it only works if I already select a card in the list itself. And I want the game to follow him without unnecessary clicks.
In the video, I include a list to demonstrate how the game interacts with it (now it is ignored unless you manually select a map).

In the correct view, I should have a choice - choose a map randomly (press f2) or select a map from the list (f5).

**Comment by iiSaLMaN** [comment] 2020-04-23 14:35
I think I'm missing this one piece:
> In the video, I include a list to demonstrate how the game interacts with it (now it is ignored unless you manually select a map).

what do you mean by "now it is ignored unless you manually select a map"? what is being ignored?  what should be the expected behaviour?

---

> With all this, I can’t go back to the previous map if I switch it using f5 (if you do not take into account the opening of the list). Can do this with a combination of shift + f5? Shift + f2 ignores switching maps with f5.

So, correct me if I'm wrong, you're saying here that you can't go back to previous map on song select with <kbd>F1</kbd> key due to it conflicting with the <kbd>F1</kbd> key shortcut for opening mod selection overlay, is that right? if so, you can change the key binding to use `Shift + F5` for solving that issue, also this is irrelevant to this issue I think.

**Comment by Moltanicaa** [comment] 2020-04-23 14:44
I'm more interested in the principle of switching cards when you press f5. The lazer does not follow its own list. That's exactly what I show in the video.

**Comment by Moltanicaa** [comment] 2020-04-23 14:47
Yes, I can change the combination, but why can't this be done by default? Okay, if you abandon the shift + f5, but then at least the shift + f2 works for this (in this case, I do not need to manually switch the keys).

**Comment by bdach** [comment] 2020-04-23 15:16
<kbd>F1</kbd> and <kbd>F5</kbd> key bindings always adhere to the order of songs in the music controller, regardless on which screen they're on, and that is intended. It is also intended that the order of songs is shuffled (but *not* randomised - the difference is subtle).

If you would like to scroll through maps in the order the *carousel* shows them, you can use arrow keys: <kbd>←</kbd> and <kbd>→</kbd> for next/previous set, and <kbd>↑</kbd> and <kbd>↓</kbd> for next/previous difficulty.

Closing as intended.

As a side note: @Moltanicaa - as much as reporting issues is appreciated, I'm sorry to say that whichever translator you are using is mangling meaning badly to the point that your issues are nigh impossible to decipher. I still am not sure if the arrow key behaviour is what you want.

**Closed by bdach** 2020-04-23 15:16 UTC
