### ISSUE TITLE
Display system time in top bar ("taskbar")

### ISSUE THREAD

**Issue by Finxert** [ppy/osu#8946] opened 2020-05-05 14:59 UTC
System time would be displayed in the middle of the "taskbar" between the different gamemodes to the left and the other features to the right like changelogs, osu direct and such.

It's very easy to loose track of time when playing osu and it would be nice being able to see it while in game.

**Comment by Game4all** [comment] 2020-05-05 15:02
Duplicate of #6303

**Closed** 2020-05-05 15:16 UTC
