### ISSUE TITLE
All text input areas become unresponsive after switching to an other input method

### ISSUE THREAD

**Issue by ZeroAurora** [ppy/osu#11573] opened 2021-01-23 02:39 UTC
**Describe the bug:** 
If I started the game with English keyboard and never change the IME, everything is fine.
If I started the game using an IME other than English (Microsoft Pinyin (Chinese) for example), or I changed the IME in game, I can control the game using my keyboard, but can't input to any textboxes, like search box and chat. Changing back to English doesn't work.

**osu!lazer version:** 2021.118.1

**Logs:**
I checked the logs and found nothing helpful. I'm attaching runtime logfiles here. There are no useful lines about the issue.
[runtime.log](https://github.com/ppy/osu/files/5859529/runtime.log)

**Additional things**
Multi-language input has always been a problem with lazer. In stable, one can chat in other languages and play using keyboard without switching IME. But in lazer it becomes impossible. I hope this can be fixed to provide a more convenient experience for multi-language players.

**Comment by bdach** [comment] 2021-01-23 10:32
Duplicate of https://github.com/ppy/osu-framework/issues/2525 + https://github.com/ppy/osu-framework/issues/2945

**Closed by bdach** 2021-01-23 10:32 UTC
