### ISSUE TITLE
Changing playback speed rapidly makes autoplay miss

### ISSUE THREAD

**Issue by taizaki69** [ppy/osu#22803] opened 2023-03-07 02:02 UTC
### Type

Game behaviour

### Bug description

When changing playback speed rapidly on mania, autoplay will miss.

### Screenshots or videos

https://user-images.githubusercontent.com/127163458/223299337-3ac2b5b2-d056-49bf-b015-7ba3bcf67326.mp4

### Version

2023.305.0

### Logs

[database.log](https://github.com/ppy/osu/files/10904463/database.log)
[input.log](https://github.com/ppy/osu/files/10904464/input.log)
[network.log](https://github.com/ppy/osu/files/10904465/network.log)
[performance.log](https://github.com/ppy/osu/files/10904466/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10904467/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10904468/updater.log)

**Comment by peppy** [comment] 2023-03-07 06:48
What is your universal offset set to? My hypothesis is that it's high, and the actual issue here is the rapid seeks forward/backwards as the game tries to adjust to this fact.

At very least, this is a duplicate of https://github.com/ppy/osu/issues/8328 so let's track it there.

**Closed by peppy** 2023-03-07 06:48 UTC
