### ISSUE TITLE
Score, accuracy and combo overlap when their values are too high

### ISSUE THREAD

**Issue by Llaurence** [ppy/osu#3977] opened 2018-12-31 10:29 UTC
Hi again,

**Describe your problem:** I ran the autoplay mod on https://osu.ppy.sh/beatmapsets/654313#osu/1399834 and noticed the score, the accuracy and the combo overlap when their value are high enough.

**Screenshots or videos showing encountered issue:**
![screenshot-20181231110031](https://user-images.githubusercontent.com/40535137/50558426-4029bf80-0ce6-11e9-8b18-da277ab122b4.png)

**osu!lazer version:** commit 223bffe
Built with dotnet 2.2.100 on archlinux with the following command:

```
dotnet build --no-restore osu.Desktop /p:TargetFramework=netcoreapp2.2 /p:Configuration=Release /p:GenerateFullPaths=true /m /verbosity:m
```

**Logs:** not relevant?

**Comment by RevertedClock** [comment] 2018-12-31 10:49
Duplicate of #3531

**Closed** 2018-12-31 21:57 UTC
