### ISSUE TITLE
The hit Hitobject cannot be displayed normally after adjusting the time

### ISSUE THREAD

**Issue by RBQcat** [ppy/osu#24345] opened 2023-07-24 11:57 UTC
### Type

Cosmetic

### Bug description

This problem occurs on all rulesets

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/c05c8d3a-8891-484d-90c1-8f00865f7945

### Version

2023.717.0

### Logs

N/A

**Comment by bdach** [comment] 2023-07-24 13:58
Duplicate of https://github.com/ppy/osu/issues/22698

**Closed by bdach** 2023-07-24 13:58 UTC
