### ISSUE TITLE
Mobile keyboard hides input textbox

### ISSUE THREAD

**Issue by Morodar** [ppy/osu#11841] opened 2021-02-19 23:27 UTC
**Describe the new feature:** 
Whenever I try to chat on the mobile version, I can't see what I'm typing.

Might be considered as duplicate of #4201

Multiplayer chat (also affects normal chat) is hidden either in landscape:
![1](https://user-images.githubusercontent.com/10113399/108571834-50abb280-7311-11eb-9dc6-f065b0eb51a6.jpeg)

Or portrait:
![2](https://user-images.githubusercontent.com/10113399/108571847-55706680-7311-11eb-90a5-ebad15330bbe.jpeg)

**Proposal designs of the feature:** 
Show the input above the virtual keyboard like follows:

![3](https://user-images.githubusercontent.com/10113399/108572208-1a226780-7312-11eb-92cc-6a5403c38f3c.jpeg)

**Comment by Joehuu** [comment] 2021-02-19 23:45
Duplicate of https://github.com/ppy/osu/issues/5236

**Closed by Joehuu** 2021-02-19 23:45 UTC
