### ISSUE TITLE
"Description" section of Beatmap Info is missing

### ISSUE THREAD

**Issue by SheepCommander** [ppy/osu#22737] opened 2023-02-25 10:39 UTC
### Type

Cosmetic

### Bug description

> "Description" section of Beatmap Info is missing

### Website
![image](https://user-images.githubusercontent.com/66646514/221352226-b4e9fdf5-abd8-44d5-9750-b37abbde64be.png)
### Lazer client preview
![image](https://user-images.githubusercontent.com/66646514/221352285-f9febe4a-b955-4789-8c2c-739fee6a1758.png)

### Version

2023.207.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/10830884/runtime.log) [updater.log](https://github.com/ppy/osu/files/10830885/updater.log) [database.log](https://github.com/ppy/osu/files/10830886/database.log) [input.log](https://github.com/ppy/osu/files/10830887/input.log) [network.log](https://github.com/ppy/osu/files/10830888/network.log) [performance.log](https://github.com/ppy/osu/files/10830889/performance.log)

**Comment by agatemosu** [comment] 2023-02-25 15:48
Duplicate of #8023

**Closed** 2023-02-25 19:31 UTC

**Comment by SheepCommander** [comment] 2023-02-26 05:46
Aww guess I didn't try hard enough to search for a duplicate
