### ISSUE TITLE
osu!lazer won't start

### ISSUE THREAD

**Issue by 1234gggsie667** [ppy/osu#5585] opened 2019-08-03 15:24 UTC
**Describe the crash:**
After clicking osu!lazer icon (the shortcut file on desktop), the cursor turns to loading mode for 3 seconds and then went back to normal. Nothing happened after that. Not even a message or a popup.

**Screenshots or videos showing encountered issue:**
No need.

**osu!lazer version:**
2019.730.0

**Logs:**
Via event viewer (No logs on osu! folder and others. No database files either.):

Application: osu!.exe
CoreCLR Version: 4.6.27207.3
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFE4BACD149 (00007FFE4B910000) with exit code c0000005.

Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x5c0ab1b7
Faulting module name: coreclr.dll, version: 4.6.27207.3, time stamp: 0x5c0a9582
Exception code: 0xc0000005
Fault offset: 0x00000000001bd149
Faulting process id: 0x4c8
Faulting application start time: 0x01d54a0bc130a14d
Faulting application path: C:\Users\User\AppData\Local\osulazer\app-2019.730.0\osu!.exe
Faulting module path: C:\Users\User\AppData\Local\osulazer\app-2019.730.0\coreclr.dll
Report Id: 05b6727e-ba1d-49c5-8723-f15f8aea284f
Faulting package full name: 
Faulting package-relative application ID: 

**Computer Specifications:** 
Intel Core 2 Duo U9400 1.4GHz
4 GB ram

Windows 10 Pro 1903 x64

What I've done:

1. Install the core SDK

osu!stable ran nicely on my desktop but osu!lazer won't even start. Don't know what to do.

**Comment by iiSaLMaN** [comment] 2019-08-03 15:28
Duplicate of #3323

**Comment by iiSaLMaN** [comment] 2019-08-03 15:33
Can you give us information on your GPU?

**Comment by 1234gggsie667** [comment] 2019-08-03 15:35
![1](https://user-images.githubusercontent.com/53656519/62413896-4e0e3d00-b647-11e9-8bd5-34cc8224814f.png)

**Comment by 1234gggsie667** [comment] 2019-08-03 15:39
Okay, I found this on C:\Users\User\AppData\Roaming\osu\logs\runtime.log

2019-08-03 03:28:09: ----------------------------------------------------------
2019-08-03 03:28:09: runtime Log for User (LogLevel: Verbose)
2019-08-03 03:28:09: osu 2019.730.0.0
2019-08-03 03:28:09: Running on Microsoft Windows NT 6.2.9200.0, 2 cores
2019-08-03 03:28:09: ----------------------------------------------------------
2019-08-03 03:28:09: GL Initialized
2019-08-03 03:28:09: GL Version:                 2.1.0 - Build 8.15.10.2413
2019-08-03 03:28:09: GL Renderer:                Mobile Intel(R) 4 Series Express Chipset Family
2019-08-03 03:28:09: GL Shader Language version: 1.20  - Intel Build 8.15.10.2413
2019-08-03 03:28:09: GL Vendor:                  Intel
2019-08-03 03:28:09: GL Extensions:              GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_EXT_texture_swizzle GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_EXT_framebuffer_blit GL_ARB_vertex_array_object

That's the whole file.

**Comment by iiSaLMaN** [comment] 2019-08-03 15:45
Well, your OpenGL version is 2.1, already explains why

**Comment by 1234gggsie667** [comment] 2019-08-03 15:46
Oof. Okay.

**Comment by 1234gggsie667** [comment] 2019-08-03 15:46
Oof, okay. So I'm closing this issue then...right?

**Comment by iiSaLMaN** [comment] 2019-08-03 15:51
I think so, we wouldn't support ancient graphics cards.

**Comment by 1234gggsie667** [comment] 2019-08-03 15:53
Alright. That sucks though. Hopefully osu!stable will exist as a fallback for osu!lazer when it's released (probably in 2025, haha).

**Comment by 1234gggsie667** [comment] 2019-08-03 16:00
Okay, it's not supported. I'll wait for DirectX or something... 

https://github.com/ppy/osu/issues/4235#issuecomment-462597828

**Closed** 2019-08-03 16:01 UTC
