### ISSUE TITLE
sometimes loging in crashes the game 

### ISSUE THREAD

**Issue by AnasSae-ed** [ppy/osu#19778] opened 2022-08-15 11:52 UTC
### Type

Game behaviour

### Bug description

OS:Artix Gnu/Linux
Init system:OpenRC
Display server:X11(also happens in wayland)
GPU:Quadro K2100M
GPU Driver:nvidia-470x form the artix universal repo  
RAM:8GB
CPU:Intel(R) Core(TM) i7-4910MQ
I play with no account and I use my account to download beatmaps and sometime when I login osu crashes 
didn't notice the issue on older versions

terminal log
```
Unhandled exception. osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the InternalChildren on a Loaded Drawable while not on the update thread. Consider using Schedule to schedule the mutation operation.
   at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String action)
   at osu.Framework.Graphics.Containers.CompositeDrawable.AddInternal(Drawable drawable)
   at osu.Framework.Graphics.Containers.Container`1.AddInternal(Drawable drawable)
   at osu.Game.Overlays.Settings.SettingsItem`1.SetNoticeText(LocalisableString text, Boolean isWarning) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Overlays/Settings/SettingsItem.cs:line 94
   at osu.Game.Overlays.Settings.Sections.UserInterface.MainMenuSettings.<LoadComplete>b__5_0(ValueChangedEvent`1 u) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Overlays/Settings/Sections/UserInterface/MainMenuSettings.cs:line 67
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Online.API.APIAccess.run() in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Game/Online/API/APIAccess.cs:line 145
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
/usr/bin/osu-lazer: line 2: 13510 Aborted                 env OSU_EXTERNAL_UPDATE_PROVIDER=1 /opt/osu-lazer/osu.AppImage "$@"
```

### Screenshots or videos

https://user-images.githubusercontent.com/103464049/184629466-3217327b-c82f-4b29-a26b-9c3479fb7948.mp4

### Version

2022.810.2-lazer

### Logs

logs are uploaded to ix.io
cat ~/.local/share/osu/logs/runtime.log| curl -F 'f:1=<-' ix.io
http://ix.io/47FT
cat ~/.local/share/osu/logs/performance.log | curl -F 'f:1=<-' ix.i
http://ix.io/47FU
cat ~/.local/share/osu/logs/database.log | curl -F 'f:1=<-' ix.io
http://ix.io/47FV
cat ~/.local/share/osu/logs/network.log | curl -F 'f:1=<-' ix.io
http://ix.io/47FW

**Comment by bdach** [comment] 2022-08-15 11:56
I believe #19702 was intended as the fix for this for next release. @peppy do I have that right?

**Comment by peppy** [comment] 2022-08-15 12:40
That's correct. Almost worth pushing a hotfix for, but this is already resolved.

**Closed by peppy** 2022-08-15 12:40 UTC
