### ISSUE TITLE
Hit error meters should use pooling for drawables

### ISSUE THREAD

**Issue by FAJIFBEFJHA** [ppy/osu#18698] opened 2022-06-15 03:20 UTC
### Type

Performance

### Bug description

when you play a map when at the time of a break there is a drop in fps for a short time i have the option of "hide HUD during gameplay"

### Screenshots or videos

https://user-images.githubusercontent.com/95898108/173729179-de376a66-58d7-4d1f-bf28-0864ab395489.mp4

### Version

osu! 2022.621.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8905418/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/8905419/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/8905420/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/8905421/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/8905422/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/8905423/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8905424/updater.log)
[database.log](https://github.com/ppy/osu/files/8905425/database.log)
[network.log](https://github.com/ppy/osu/files/8905426/network.log)

**Comment by smoogipoo** [comment] 2022-06-15 03:25
Looks like it could be related to the hit error meter, since FPS seems to go back to normal after all marks disappear.

**Comment by peppy** [comment] 2022-06-15 03:38
This is actually something I noticed while working on https://github.com/ppy/osu/pull/18669, and something which is greatly reduced by that PR. Now the load is distributed more evenly.

I'd propose dropping the priority of this down to 1 or 2 as a result. I do want to look at making the two classes more performant, using pooling and optimising transform usage, and have it on my bucket list already.

**Comment by smoogipoo** [comment] 2022-06-15 03:39
Ah, I'd thought this was a regression _from_ those changes, but there hasn't been a release. Will drop prio.

**Comment by peipacut** [comment] 2022-10-23 17:21
is this issue still worth doing after merging the aforementioned PR? I'd be happy to try working on it.

**Comment by smoogipoo** [comment] 2022-10-23 22:06
Yep, this is still up for grabs.

**Comment by turbedi** [comment] 2022-12-29 13:07
Fixed by #21240 ?

**Closed** 2023-01-02 13:22 UTC
Labels: type:performance, area:gameplay, priority:2
