### ISSUE TITLE
Skip button does not work 

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5335] opened 2019-07-11 18:29 UTC
**Screenshots or videos showing encountered issue:** 
https://www.twitch.tv/videos/451298182?t=01h17m14s

**osu!lazer version:** 
2019.704.0

**Logs:** 
Unfortunately, I've got no logs on that one, but since it was a stream, maybe it'll help to figure out how this happened.

**Comment by iiSaLMaN** [comment] 2019-07-11 18:40
weird, skip works just fine on the beatmap that was shown on the stream

**Comment by Gabixel** [comment] 2019-07-11 19:08
Seems like there's a precise moment right after the PlayerLoader where if you press the spacebar/the skip button, this one doesn't fade out (and doesn't skip the intro, like on the stream linked above). I reproduced it, but it doesn't seem to be easy to reproduce (in my case I spammed the spacebar for a higher probability): https://streamable.com/n5zu5

**Comment by peppy** [comment] 2019-07-11 19:10
It looks more likely related to lead-in time, since the elapsed time in that video is not changing. #4883 may help fix this.

**Comment by Joehuu** [comment] 2021-01-15 22:06
I'm not sure what the issue is, since the videos expired and there was no beatmap linked in the first place.

Tentatively closing, as I think the only issue left for the skip button is https://github.com/ppy/osu/issues/9787.

**Closed by Joehuu** 2021-01-15 22:06 UTC
Labels: area:gameplay

**Comment by Gabixel** [comment] 2021-01-15 23:15
Unfortunately, I lost the video, but I remember that the problem was about pressing (almost) instantly the skip button as soon as you entered gameplay. This would have caused the button to break and not be able to skip the intro, but it doesn't seem to be happening anymore (I remember the scenario of the video), so I can confirm that it appears to be fixed.
