### ISSUE TITLE
Performance drops on opening web elements

### ISSUE THREAD

**Issue by rubicus3** [ppy/osu#24758] opened 2023-09-08 17:47 UTC
### Type

Performance

### Bug description

In-game FPS drops significantly when opening elements or pages containing web information.

It started to drop after the last release update.

Edit: Also happens on opening mod select tab

OS: Kubuntu 22.04.3 LTS x86_64
Happens in both OpenGL and OpenGL (Legacy).

### Screenshots or videos

https://github.com/ppy/osu/assets/49041272/cc26f6b0-7788-48b6-8745-ad3f30ffec5c

https://github.com/ppy/osu/assets/49041272/1aa12839-84ef-47a0-8e03-95a639deb074

### Version

2023.908.2

### Logs

[network.log](https://github.com/ppy/osu/files/12562440/network.log)
[runtime.log](https://github.com/ppy/osu/files/12562441/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12562442/performance.log)
[input.log](https://github.com/ppy/osu/files/12562443/input.log)
[database.log](https://github.com/ppy/osu/files/12562444/database.log)

**Comment by bdach** [comment] 2023-09-08 18:24
Most likely duplicate of #24751

**Closed by bdach** 2023-09-08 18:24 UTC
