### ISSUE TITLE
Ctrl+A to toggle Auto mod

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu#6551] opened 2019-10-20 09:42 UTC
**Describe the missing feature:** In stable, pressing `Ctrl+A` toggles Auto mod in song selection. In lazer, this shotcut selects all text of the search box.

**Comment by Game4all** [comment] 2019-10-20 09:43
I don't think it is necessary to add another keybind to toggle auto as doing `CTRL + Enter` in song selection will launch selected map with auto enabled

**Comment by bdach** [comment] 2019-10-20 09:45
Duplicate of #5839.

**Closed by bdach** 2019-10-20 09:45 UTC
