### ISSUE TITLE
Beatmap Difficulty Information Details Mismatch

### ISSUE THREAD

**Issue by HerendraTJ** [ppy/osu#6452] opened 2019-10-10 05:01 UTC
**Describe the missing feature:** 
In stable, beatmap difficulty information should be change when adding mods to increase difficulty and/or reduce difficulties.  But in Lazer , this feature not appear.

**Proposal designs of the feature:** 
When adding mods like HR,DT,EZ,HT --> Difficulty information (CS,AR,OD,HP,SR,BPM) should change.

**Prove:**
https://youtu.be/jaRETTQrFmA

**This video tested using mod HR and DT. EZ and HT mods not tested but it should be the same condition**

**Comment by bdach** [comment] 2019-10-10 06:12
Duplicate of #5320.

Some preliminary work was done in #3271 and #3272, but it was never completed.

**Closed by bdach** 2019-10-10 06:12 UTC

**Comment by HerendraTJ** [comment] 2019-10-10 06:29
Just give me the details when this issue is going to be completed? Is this issue is a backlog?

**Comment by smoogipoo** [comment] 2019-10-10 06:36
There's no timeline for when issues will be fixed. It's not quite backlog but it's not on the immediate agenda.
