### ISSUE TITLE
Borderless window caps fps at monitor refresh rate

### ISSUE THREAD

**Issue by Mavgician** [ppy/osu#26911] opened 2024-01-31 22:43 UTC
### Type

Game behaviour

### Bug description

Borderless window on Osu caps the FPS at monitor refresh rate. I have two monitors, I tried switching where Osu is displayed and the first monitor doesn't seem to have the issue. First monitor is has 60 refresh rate while my main one uses 76 refresh rate. It caps fps at 76 when using my main. Windowed and fullscreen doesn't seem to have this issue.

### Screenshots or videos

Main Monitor
![image](https://github.com/ppy/osu/assets/65918350/7057fd41-4b01-4246-8755-7644f84a2de6)

Second Monitor
![image](https://github.com/ppy/osu/assets/65918350/4b1b35e6-7d7b-464e-9402-224a9b5761b0)

### Version

2024.131.0-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14118062/compressed-logs.zip)

**Comment by Stoppedpuma** [comment] 2024-02-01 02:05
iirc borderless is designed that way intentionally to prevent tearing.

**Comment by EVAST9919** [comment] 2024-02-01 11:35
Duplicate of https://github.com/ppy/osu/issues/25828

**Closed** 2024-02-01 11:38 UTC
