### ISSUE TITLE
[Linux] Osu gets stuck before main menu.

### ISSUE THREAD

**Issue by JeppeX** [ppy/osu#11777] opened 2021-02-14 12:24 UTC
**Describe the crash:** 
Osu starts normally up until the point it should load main menu. Then it just does nothing. It doesn't actually freeze because I am still able to change the volume using scroll as screenshot indicates. I believe this is the important part of logs (tail of runtime.log):
```
2021-02-14 12:03:08 [verbose]: Screen changed → Loader
2021-02-14 12:03:08 [verbose]: Screen changed → Disclaimer
2021-02-14 12:03:14 [verbose]: Screen changed → IntroTriangles
2021-02-14 12:03:15 [verbose]: decoupled ruleset transferred ("" -> "osu!")
```

_**However**_ I was earlier able to launch this very latest version normally. When I encountered this crash I tried to perform "a clean install" by deleting `.local/share/osu` folder completely. This didn't work though. (Does osu!lazer store files somewhere else than `.local/share/osu`?)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/29777790/107876253-914c9b80-6ecd-11eb-9745-b7eae6abb708.png)

**osu!lazer version:** 
Tested this with 2021.212.0 and 2021.205.1. Logs and screenshot from 2021.212.0.

**Logs:**

[database.log](https://github.com/ppy/osu/files/5977658/database.log)
[network.log](https://github.com/ppy/osu/files/5977659/network.log)
[performance.log](https://github.com/ppy/osu/files/5977660/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5977661/runtime.log)

**Computer Specifications:** 
OS: Arch Linux
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce RTX 2070

**Comment by bdach** [comment] 2021-02-14 13:10
Such freezes are usually an indication of a wrong audio device being chosen, which stalls the intro due to the audio track being unable to progress.

Tentatively closing as a duplicate of https://github.com/ppy/osu-framework/issues/3297.

**Closed by bdach** 2021-02-14 13:10 UTC
