### ISSUE TITLE
Keyboard config doesn't convert sprite to an icon properly

### ISSUE THREAD

**Issue by Altenhh** [ppy/osu#7091] opened 2019-12-08 03:49 UTC
when opening the Keyboard Configuration menu; in the ruleset listing section, while the toolbar has the correct icon the Keyboard Config does not...

An example can be shown here:
![image](https://user-images.githubusercontent.com/35349837/70383902-ebee7d00-1943-11ea-85cd-0a6474db4dcd.png)

This issue can be found here: https://github.com/ppy/osu/blob/52a0d98012b743993a5374213bebc79c28db5b54/osu.Game/Overlays/KeyBinding/RulesetBindingsSection.cs#L13

**Comment by bdach** [comment] 2019-12-08 08:34
To clarify where the problem is, the icon doesn't work if you provide anything other than a `SpriteIcon` in the ruleset's `CreateIcon()` method due to the safe cast. As `CreateIcon()` is defined to return a `Drawable`, any drawable should probably be supported - albeit stylistically/design-wise it might be a problem if the icon supplied is multicoloured.

**Comment by Joehuu** [comment] 2020-04-26 23:57
Fixed in https://github.com/ppy/osu/pull/8864.

**Closed by Joehuu** 2020-04-26 23:57 UTC
Labels: area:settings, type:UI
