### ISSUE TITLE
Autopilot mod not usable on adroid 

### ISSUE THREAD

**Issue by jimbot03** [ppy/osu#14820] opened 2021-09-21 04:14 UTC
This was apparently already merged and fixed for the Android release but even on the latest version hit notes need to be directly tapped with autopilot on otherwise it gets counted as a miss 

If it helps im running android 11 on a samsung galaxy s10 5G I only say that because it could possibly be a android version or device specific issue given that it was apparently already fixed

**Comment by PercyDan54** [comment] 2021-09-21 04:16
Duplicate of #12731

**Comment by jimbot03** [comment] 2021-09-21 04:19
My god apparently I can't type also my apologies I didn't realise there was a open thread about this other then the one that is marked as solved

**Comment by peppy** [comment] 2021-09-21 04:23
@jimbot03 how did you go about creating this issue? ie. which page did you come from to post what you did?

**Closed** 2021-09-21 04:23 UTC

**Comment by jimbot03** [comment] 2021-09-21 04:38
That is a bit of a tricky question because I don't have enough context as to why it is relevant I can only assume that either wasn't supposed to be able to make this thread or you are curious as to why I made a duplicate thread I could be wrong of course anyway long story short I did a generalised search of the bug in my browser which led me to this https://github.com/ppy/osu/pull/11712 from there I went to the general github page for laser and checked the first few pages of issues and didn't see anything similar to it so I pressed the open new issue button at the top of the guthub page on mobile signed in and made my post riddled with errors in typing

**Comment by peppy** [comment] 2021-09-21 04:39
We recently changed things so an average user should not see the option to open an issue. Can you try again and confirm it doesn't let you?

**Comment by jimbot03** [comment] 2021-09-21 04:42
It looks like I don't have the option anymore it might be worth checking if github has a bug wherein people who aren't signed in can still get the prompt to open a thread and continuing the process let's them just food for thought

**Comment by peppy** [comment] 2021-09-21 04:44
You hit the nail on the head. Clicking "new issue" from a signed out state bypasses this prompt completely. I'll report this to github, thanks.

**Comment by jimbot03** [comment] 2021-09-21 04:47
In all seriousness going back to why I opened the thread it would be nice to see the issue fixed as right now autopilot is really the only way to enjoy osu on android at least until you guys find a good solution to touch controls that said I know you all already have a lot of work on your plate so I want to say thanks for all the effort you guys are putting in to this client and osu in general
