### ISSUE TITLE
Strict tracking makes slider hitsound play earlier than it should.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#23525] opened 2023-05-13 10:44 UTC
### Type

Cosmetic

### Bug description

Strict tracking makes slider end and slider repeat hitsound play earlier than it should, as you can see in the video below. In my opinion, in most case, it make the mod unplayable for me.

### Screenshots or videos

Strict tracking **NOT** applied

https://github.com/ppy/osu/assets/7066150/0adedcff-7781-41fd-bb94-a9e7b751d82d

Strict tracking **applied**

https://github.com/ppy/osu/assets/7066150/7a1985a3-b969-40a7-8f74-295fe943d3dd

Even though video above is from autoplay, the issue apply to the actual play itself also.

*Nothing at the bottom right*

### Version

2023.511.0

### Logs

[input.log](https://github.com/ppy/osu/files/11469438/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11469439/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11469440/network.log)
[performance.log](https://github.com/ppy/osu/files/11469441/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11469442/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11469443/updater.log)
[database.log](https://github.com/ppy/osu/files/11469444/database.log)

**Comment by bdach** [comment] 2023-05-13 13:12
duplicate of https://github.com/ppy/osu/issues/23471

**Closed by bdach** 2023-05-13 13:12 UTC
