### ISSUE TITLE
osu!Lazer - textures not loading

### ISSUE THREAD

**Issue by nybbleosu** [ppy/osu#2420] opened 2018-04-19 09:23 UTC
Some textures don't load. Like the osu! Logo, (only the triangles appear) and others.
I built osu.Desktop and ran it in Visual Studio for macOS.
(macOS High Sierra 10.13.3)

--Terminal--
[runtime:important] GL Initialized
                        GL Version:                 2.1 ATI-10.4.14
                        GL Renderer:                ATI Radeon HD 4670 OpenGL Engine
                        GL Shader Language version: 1.20
                        GL Vendor:                  ATI Technologies Inc.
                        GL Extensions:              GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod 
[performance:verbose] Drawable ["" OsuSpriteText (0,0) 10x10] took 481.96ms to load and was not async!
[performance:verbose] Drawable [OsuTooltipContainer+OsuTooltip (0,0) 0x0] took 494.13ms to load and was not async!
[performance:verbose] Drawable [OsuTooltipContainer (0,0) 1x1] took 504.99ms to load and was not async!
[performance:verbose] Drawable [GlobalActionContainer (0,0) 1x1] took 516.82ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 523.30ms to load and was not async!
[performance:verbose] Drawable [CursorOverrideContainer (0,0) 1x1] took 573.21ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 573.80ms to load and was not async!
[performance:verbose] Drawable [DrawSizePreservingFillContainer (0,0) 1x1] took 601.77ms to load and was not async!
[performance:verbose] Drawable ["ACCOUNT" OsuSpriteText (0,0) 0x0] took 129.43ms to load and was not async!
[performance:verbose] Drawable [OsuTextBox (0,0) 1x40] took 69.80ms to load and was not async!
[performance:verbose] Drawable [FillFlowContainer (0,0) 1x0] took 55.45ms to load and was not async!
[performance:verbose] Drawable [SettingsCheckbox (0,0) 1x0] took 78.98ms to load and was not async!
[performance:verbose] Drawable [LoginSettings+LoginForm (0,0) 1x0] took 248.37ms to load and was not async!
[runtime:verbose] Focus contention triggered by NotificationOverlay (320,0) 320x768.
[performance:verbose] Drawable ["@" OsuSpriteText (0,0) 0x0] took 76.41ms to load and was not async!
[performance:verbose] Drawable [EditorMenuBar (0,0) 1x1] took 83.44ms to load and was not async!
[performance:verbose] Drawable [Top bar (Container) (0,0) 1x40] took 83.61ms to load and was not async!
[performance:verbose] Drawable ["100%" OsuSpriteText (0,0) 0x0] took 77.56ms to load and was not async!
[performance:verbose] Drawable [PlaybackControl+PlaybackTabControl+PlaybackTabItem (0,0) 0x1 value: 1] took 84.92ms to load and was not async!
[performance:verbose] Drawable [OsuTabControl<T>+OsuTabFillFlowContainer<Double> (0,0) 1x1] took 92.23ms to load and was not async!
[performance:verbose] Drawable [PlaybackControl+PlaybackTabControl (0,0) 1x1] took 100.46ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 100.64ms to load and was not async!
[performance:verbose] Drawable [PlaybackControl (0,0) 1x1] took 125.89ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 126.01ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 126.12ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 185.41ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 185.55ms to load and was not async!
[performance:verbose] Drawable [Bottom bar (Container) (0,0) 1x60] took 185.70ms to load and was not async!
[performance:verbose] Drawable [Editor (0,0) 1x1] took 344.45ms to load and was not async!
[performance:verbose] Drawable [SpriteIcon (0,0) 18x18] took 67.38ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 30x30] took 67.75ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 0x0] took 67.88ms to load and was not async!
[performance:verbose] Drawable [IconButton (0,0) 0x0] took 68.24ms to load and was not async!
[performance:verbose] Drawable [TimelineButton (0,0) 30x1] took 70.67ms to load and was not async!
[performance:verbose] Drawable [Container<TimelineButton> (0,0) 0x1] took 74.17ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 0x1] took 74.45ms to load and was not async!
[performance:verbose] Drawable [FillFlowContainer (0,0) 1x1] took 119.09ms to load and was not async!
[performance:verbose] Drawable [ScrollableTimeline (0,0) 1x1] took 121.68ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 121.82ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 122.03ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 56.93ms to load and was not async!
[performance:verbose] Drawable [BeatDivisorControl (0,0) 1x1] took 69.07ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 69.17ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 191.50ms to load and was not async!
[performance:verbose] Drawable [Timeline content (Container) (0,0) 1x1] took 191.57ms to load and was not async!
[performance:verbose] Drawable [Timeline (Container) (0,0) 1x1] took 191.65ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 191.83ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 192.15ms to load and was not async!
[runtime:error] Could not load beatmap sucessfully!
[runtime:important] osu.Game.Rulesets.UI.BeatmapInvalidForRulesetException: Beatmap can not be converted for the current ruleset (converter: osu.Game.Rulesets.Osu.Beatmaps.OsuBeatmapConverter).
  at osu.Game.Rulesets.UI.RulesetContainer`1[TObject]..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap workingBeatmap, System.Boolean isForCurrentRuleset) [0x001a3] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game/Rulesets/UI/RulesetContainer.cs:252 
  at osu.Game.Rulesets.Osu.UI.OsuRulesetContainer..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap, System.Boolean isForCurrentRuleset) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs:25 
  at osu.Game.Rulesets.Osu.Edit.OsuEditRulesetContainer..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap, System.Boolean isForCurrentRuleset) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/Edit/OsuEditRulesetContainer.cs:15 
  at osu.Game.Rulesets.Osu.Edit.OsuHitObjectComposer.CreateRulesetContainer (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs:25 
  at osu.Game.Rulesets.Edit.HitObjectComposer.load (osu.Game.OsuGameBase osuGame, osu.Framework.Timing.IFrameBasedClock framedClock) [0x00014] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game/Rulesets/Edit/HitObjectComposer.cs:47 
[performance:verbose] Drawable [OsuHitObjectComposer (0,0) 1x1] took 61.76ms to load and was not async!
[performance:verbose] Drawable [Compose (0,0) 1x1] took 291.78ms to load and was not async!
[performance:verbose] Drawable [SpriteIcon (0,0) 20x20] took 57.32ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 40x40] took 57.63ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x10] took 64.29ms to load and was not async!
[performance:verbose] Drawable [SpriteIcon (0,0) 20x20] took 69.06ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 0x0] took 69.73ms to load and was not async!
[performance:verbose] Drawable [Notification+CloseButton (0,0) 0x0] took 76.79ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x0] took 141.52ms to load and was not async!
[performance:verbose] Drawable [SimpleNotification (0,0) 1x0] took 152.66ms to load and was not async!
[runtime:verbose] Focus contention triggered by NotificationOverlay (48,0) 320x768.
[performance:verbose] Drawable [EditorMenuBar (0,0) 1x1] took 80.96ms to load and was not async!
[performance:verbose] Drawable [Top bar (Container) (0,0) 1x40] took 81.12ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 98.56ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 98.71ms to load and was not async!
[performance:verbose] Drawable [Bottom bar (Container) (0,0) 1x60] took 98.81ms to load and was not async!
[performance:verbose] Drawable [Editor (0,0) 1x1] took 205.31ms to load and was not async!
[performance:verbose] Drawable [ScrollableTimeline (0,0) 1x1] took 50.28ms to load and was not async!
[performance:verbose] Drawable [Container (0,0) 1x1] took 50.43ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 50.53ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 50.67ms to load and was not async!
[performance:verbose] Drawable [BeatDivisorControl (0,0) 1x1] took 53.50ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 53.65ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 104.39ms to load and was not async!
[performance:verbose] Drawable [Timeline content (Container) (0,0) 1x1] took 104.49ms to load and was not async!
[performance:verbose] Drawable [Timeline (Container) (0,0) 1x1] took 104.68ms to load and was not async!
[performance:verbose] Drawable [GridContainer+CellContainer (0,0) 0x0] took 104.85ms to load and was not async!
[performance:verbose] Drawable [GridContainer (0,0) 1x1] took 105.07ms to load and was not async!
[runtime:error] Could not load beatmap sucessfully!
[runtime:important] osu.Game.Rulesets.UI.BeatmapInvalidForRulesetException: Beatmap can not be converted for the current ruleset (converter: osu.Game.Rulesets.Osu.Beatmaps.OsuBeatmapConverter).
  at osu.Game.Rulesets.UI.RulesetContainer`1[TObject]..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap workingBeatmap, System.Boolean isForCurrentRuleset) [0x001a3] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game/Rulesets/UI/RulesetContainer.cs:252 
  at osu.Game.Rulesets.Osu.UI.OsuRulesetContainer..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap, System.Boolean isForCurrentRuleset) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs:25 
  at osu.Game.Rulesets.Osu.Edit.OsuEditRulesetContainer..ctor (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap, System.Boolean isForCurrentRuleset) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/Edit/OsuEditRulesetContainer.cs:15 
  at osu.Game.Rulesets.Osu.Edit.OsuHitObjectComposer.CreateRulesetContainer (osu.Game.Rulesets.Ruleset ruleset, osu.Game.Beatmaps.WorkingBeatmap beatmap) [0x00000] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs:25 
  at osu.Game.Rulesets.Edit.HitObjectComposer.load (osu.Game.OsuGameBase osuGame, osu.Framework.Timing.IFrameBasedClock framedClock) [0x00014] in /Users/Rythmic/Desktop/osu!lazer/osu/osu.Game/Rulesets/Edit/HitObjectComposer.cs:47 
[performance:verbose] Drawable [Compose (0,0) 1x1] took 117.00ms to load and was not async!
[runtime:verbose] Focus contention triggered by NotificationOverlay (282,0) 320x768.
[runtime:verbose] Focus contention triggered by LoginOverlay (0,40) 360x3.
[runtime:verbose] Focus contention triggered by MusicController (0,40) 400x130.
[runtime:verbose] Focus contention triggered by SocialOverlay (0,0) 1,366x728.
[runtime:verbose] Focus contention triggered by ChatOverlay (0,689) 1,366x728.
[runtime:verbose] Focus contention triggered by ChannelSelectionOverlay (0,412) 1,366x437.
[runtime:verbose] Focus contention triggered by LoginOverlay (0,40) 360x3.

--Logs--
[performance.log](https://github.com/ppy/osu/files/1927452/performance.log)
[runtime.log](https://github.com/ppy/osu/files/1927453/runtime.log)

--Screenshots--
![screen shot 2018-04-19 at 5 18 10 pm](https://user-images.githubusercontent.com/38458543/38983036-fd2fe01a-43f5-11e8-9874-ab1ed6d49373.png)
![screen shot 2018-04-19 at 4 27 28 pm](https://user-images.githubusercontent.com/38458543/38983046-05c95986-43f6-11e8-881f-9588e32660ec.png)

**Comment by Frontear** [comment] 2018-04-19 12:39
Do you have osu-resources as a project? Additionally, can you update that submodule?

**Comment by nybbleosu** [comment] 2018-04-20 08:52
How do I do that?

**Comment by Rythmicode** [comment] 2018-04-22 09:41
Hey, im nybbleosu. (I lost access to my old acc)
What do you mean by "having osu-resources as a project?"
Also, how do you build it properly?
Im afraid this is happening because I didn't do something and I don't know it.

**Comment by Frontear** [comment] 2018-04-22 15:05
Within your git client (or console), make sure that you reinitialize the submodule, the documentation of which can be found [here](https://git-scm.com/docs/git-submodule). If you are using a client, just click the submodule and choose the option *update*.

Make sure that osu.Game.Resources is visible as a project within the solution. It should be visible in the solution Explorer within your development client (Visual Studio or Mono Develop, most likely). If it isn't, update the reinitialize the submodule. If it is, make sure it is building a `*.dll` within the *debug/release folder.

**Comment by FreezyLemon** [comment] 2018-04-22 15:13
This is most likely not an issue with the resources not being present, as the game would not compile without the "osu.Game.Resources" project. 

This might be related to #1488, though.

**Comment by peppy** [comment] 2019-10-29 13:33
Duplicate of https://github.com/ppy/osu/issues/1488

**Closed by peppy** 2019-10-29 13:33 UTC
Labels: bug
