### ISSUE TITLE
Relax clicking wrong

### ISSUE THREAD

**Issue by Tociak** [ppy/osu#29746] opened 2024-09-06 22:37 UTC
### Type

Performance

### Bug description

it seems like relax clicked 2 buttons at the same time and then was clicking to early.

### Screenshots or videos

https://github.com/user-attachments/assets/45cbf7a3-e939-4b87-af0a-29c8370534af

### Version

2024.906.1

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16913394/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-07 01:04
Duplicate of https://github.com/ppy/osu/issues/27307

**Closed by Joehuu** 2024-09-07 01:04 UTC
