### ISSUE TITLE
Selected mods get reset when going to main menu

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#6398] opened 2019-10-04 19:41 UTC
When you exit song select to go to main menu, your selected mods will reset to no selection.

**osu!lazer version:** 2019.930.0

**Comment by Joehuu** [comment] 2019-10-04 19:42
Duplicate of https://github.com/ppy/osu/issues/3186

**Closed by Joehuu** 2019-10-04 19:42 UTC

**Comment by LittleEndu** [comment] 2019-10-04 19:44
Yeah I could have sworn there indeed was an issue opened. That issue should be labeled or make use of the word reset...

**Comment by bdach** [comment] 2019-10-04 19:45
Renamed & labeled.
