### ISSUE TITLE
sliderb and sliderfollowcircle don't scaled correct non-standard-sized elements

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5591] opened 2019-08-03 22:59 UTC
Sliderb and sliderfollowcircle don't scaled correct

Osu!Lazer Sliderb:
![osu_2019-08-04_00-41-18](https://user-images.githubusercontent.com/53025167/62417530-2e304680-b652-11e9-9461-8e49b4f94521.png)
![osu_2019-08-04_00-45-16](https://user-images.githubusercontent.com/53025167/62417531-312b3700-b652-11e9-8391-8a5e8089a9cf.png)

Osu!Stable:
![screenshot10704](https://user-images.githubusercontent.com/53025167/62417533-3be5cc00-b652-11e9-98ae-44c43988f91f.png)

![screenshot10705](https://user-images.githubusercontent.com/53025167/62417534-3ee0bc80-b652-11e9-88b6-d84288eb9293.png)

Osu!Lazer Sliderfollowcircle:
![osu_2019-08-04_00-41-45](https://user-images.githubusercontent.com/53025167/62417539-6c2d6a80-b652-11e9-9e3e-1ba9c0e1c5b8.png)

Osu!Stable Sliderfollowcircle:
![screenshot10706](https://user-images.githubusercontent.com/53025167/62417540-764f6900-b652-11e9-8694-209fad20da70.png)

Non-Standard-sized Skinelements:
![sliderb@2x](https://user-images.githubusercontent.com/53025167/62417544-7fd8d100-b652-11e9-9e1a-ea5e4605df44.png)
![sliderfollowcircle](https://user-images.githubusercontent.com/53025167/62417545-8404ee80-b652-11e9-85c4-63725595c20f.png)
![sliderb](https://user-images.githubusercontent.com/53025167/62417546-86ffdf00-b652-11e9-86c6-269e092a37f4.png)

osu!lazer version: 2019.730.0

Logs: none

**Comment by Joehuu** [comment] 2019-08-03 23:11
Duplicate of #5510.

**Comment by Fatal3ty** [comment] 2019-08-03 23:15
Duplicate of #5510
Is not says sliderb and followcircle

**Comment by Joehuu** [comment] 2019-08-03 23:50
In #5510:
> Some skin creators took the liberty of exceeding skin dimension specifications. Currently lazer will downscale these to avoid unfair advantages from oversized elements.

Downscaling can happen with other elements above the suggested size 128x128 (SD) and 256x256 (HD `@2x`).

The elements you posted are above the size.

**Comment by peppy** [comment] 2019-08-04 03:17
Closing as duplicate. Thanks for another example of this!

**Closed by peppy** 2019-08-04 03:17 UTC
