### ISSUE TITLE
Let 100 and 50 represent not just accuracy of the tap, but also was it early or late

### ISSUE THREAD

**Issue by AntonPetrochenko** [ppy/osu#8931] opened 2020-05-03 10:59 UTC
**Preamble:**
The current hit error bar in osu!stable is an amazing learning tool. It allows you to see just how accurate your taps, are they early or late and by how much, and adjust accordingly, eventually helping you improve your accuracy. However, the major downside that it has is you have to take your eyes away from the hit objects to see it - leading to mis-aims.

**Feature proposal:**
While the hit error bar is cool and all, the more prominent thing that we have to gauge aim is those 100 and 50 numbers that show up when you mistime your taps. The problem with them is that they don't fully represent the timing of the tap - just how far it is from the proper hit window, with no direction. The point of this feature is just that - let them show if the tap was too late or too early. It would let players adjust the timing of their taps accordingly without having to look away.

**Proposal designs of the feature:** 
Given that lazer already changes the text from "300, 100, 50" to "Great, Good, Meh" by default, it could be further changed to something akin to "Faster!, Early, Great, Late, Slower!" either by default or with a toggle in the options.

**Comment by bdach** [comment] 2020-05-03 11:14
Duplicate of #3209

**Closed by bdach** 2020-05-03 11:14 UTC
