### ISSUE TITLE
punch-hole not display picture content

### ISSUE THREAD

**Issue by veliming** [ppy/osu#18717] opened 2022-06-15 17:11 UTC
### Type

Other

### Bug description

Xiaomi Mi 10 is a hole-digging screen. On the side of the hole-digging, no game screen is displayed.

### Screenshots or videos

![Screenshot_2022-06-16-00-57-47-241_sh ppy osulazer](https://user-images.githubusercontent.com/56386526/173885167-f97105b0-0a23-48cb-b831-4f9aba792062.jpg)

### Version

2022.615.0

### Logs

[database.log](https://github.com/ppy/osu/files/8911609/database.log)
[network.log](https://github.com/ppy/osu/files/8911612/network.log)
[performance.log](https://github.com/ppy/osu/files/8911613/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8911614/runtime.log)

**Comment by frenzibyte** [comment] 2022-06-15 17:13
This is known and will improve later on, duplicate of https://github.com/ppy/osu/issues/4330.

**Closed by frenzibyte** 2022-06-15 17:13 UTC
