### ISSUE TITLE
New score meter type

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#12774] opened 2021-05-12 17:24 UTC
So there is the hit error and colour type but what if you combined them as a new "hit error + colour (pos)"

![Screenshot_20210512-122341_GitHub.jpg](https://user-images.githubusercontent.com/54640414/118018040-e5c0b500-b31c-11eb-82b5-b65d3014d49b.jpg)

Something like that

I  like something like that because it's useful for the player and visually appealing in my opinion

**Comment by frenzibyte** [comment] 2021-05-12 17:28
Sounds like something you can support yourself via the new skinning implementation once it's up, not sure what's gonna happen to the "score meter types" dropdown in settings though, I guess this can be kept open?

**Comment by Joehuu** [comment] 2021-05-12 17:39
Actually a duplicate of https://github.com/ppy/osu/issues/7292. Not sure why that was closed, gonna reopen.

**Closed by Joehuu** 2021-05-12 17:39 UTC
Labels: area:gameplay, area:settings, proposal, type:UI
