### ISSUE TITLE
Beatmap is longer available to download notification missing

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu#4950] opened 2019-06-07 12:57 UTC
**Describe the missing feature:** 
Currently downloading a removed map in osu!direct gets you the notification that its donwloading 
![image](https://user-images.githubusercontent.com/17437302/59105217-c69c9a00-8933-11e9-9fb4-3ec92b7a82ed.png) 
or inside the beatmap page it says "importing"
![image](https://user-images.githubusercontent.com/17437302/59105281-ecc23a00-8933-11e9-950f-742fa22793f6.png)

**Proposal designs of the feature:** 
Give a notification that "This beatmap is no longer available to download" or remove the Download button in direct like on the website ( https://osu.ppy.sh/beatmapsets/53853#osu/164005 ) map as demonstration 
![image](https://user-images.githubusercontent.com/17437302/59105453-3743b680-8934-11e9-9843-8c227304907d.png)

**Comment by peppy** [comment] 2019-06-08 06:54
This should already be exposed by the api – adding support should be pretty straightforward.

**Comment by iiSaLMaN** [comment] 2019-06-09 14:11
will look at that

**Comment by peppy** [comment] 2019-06-10 00:54
Note that the link should not be underlined. Just use `LinkFlowContainer`'s implementation.

**Comment by iiSaLMaN** [comment] 2019-06-10 18:42
There seems to be an issue with the Search Results response not including the availability properties (ppy/osu-web#4560)

**Comment by Joehuu** [comment] 2019-06-24 05:05
Duplicate of #3075. Either close this or the referenced issue.

**Closed** 2019-06-27 04:59 UTC
Labels: good first issue, online / API, pending review
