### ISSUE TITLE
Can't skip using keyboard keys

### ISSUE THREAD

**Issue by theonlygusti** [ppy/osu#6511] opened 2019-10-14 21:41 UTC
**Describe the bug:** 

Pressing z / x on skip button in-game doesn't skip the intro/section (i have to click with my mouse)

z clicks on every other button though. I have my keys set up like this:

![Screenshot 2019-10-14 at 22 41 10](https://user-images.githubusercontent.com/10684786/66784961-cc9f1a80-eed3-11e9-96a4-92b469c0bf37.png)
![Screenshot 2019-10-14 at 22 41 23](https://user-images.githubusercontent.com/10684786/66784963-cc9f1a80-eed3-11e9-8a43-bb438027e9fe.png)

**osu!lazer version:** 2019.1011.0

**Comment by bdach** [comment] 2019-10-14 21:59
Yeah, doesn't seem to work as expected, probably something to do with binding priority.

**Comment by Joehuu** [comment] 2019-10-15 01:12
There is a `Skip cutscene` keybind.

![](https://puu.sh/EsFtZ/7d76b1b6e7.png)

Duplicate of https://github.com/ppy/osu/issues/3551 if you want more keys bound or `z` and `x` to be also defaults.

**Closed by Joehuu** 2019-10-15 01:12 UTC
Labels: gameplay, input
