### ISSUE TITLE
Button from different overlaid panel closes the last focused one

### ISSUE THREAD

**Issue by SusieDroid** [ppy/osu#6287] opened 2019-09-27 03:11 UTC
**Describe the bug:** 
I discovered this bug while I tried to stop the music with the settings panel opened. First I played the track. Then, I opened the settings panel and finally, I tried to stop the track by clicking on the play/pause button from the NowPlaying player. This caused the last open panel to close. It seems that the last element keeps focused after an event, however, if I hover on the NowPlaying player, it doesn't set the focus on it. 
  
**Screenshots or videos showing encountered issue:** 
![aa](https://user-images.githubusercontent.com/55773786/65739257-fd511880-e0ba-11e9-9ee7-7c89ec52059b.gif)

**osu!lazer version:**

**Comment by smoogipoo** [comment] 2019-09-27 03:13
This is correct for the moment since we don't have multiple dimming (in this case settings should dim the music controller). See/duplicate of https://github.com/ppy/osu/issues/5901

**Closed by smoogipoo** 2019-09-27 03:13 UTC
