### ISSUE TITLE
Searching freezes entire game with a large beatmap database 

### ISSUE THREAD

**Issue by sr229** [ppy/osu#24874] opened 2023-09-20 18:21 UTC
### Type

Performance

### Bug description

According to some reports from players, there is a large performance slowdown with search to the point of freezing if Lazer's db is tracking a large amounts of beatmaps. The following provided video evidence is from someone with 52k beatmaps in the database.

### Screenshots or videos

https://github.com/ppy/osu/assets/14976516/d7a8cde4-d47d-443e-bf6c-621cff319b71

### Version

2023.0914.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/12676347/performance.log)
[input.log](https://github.com/ppy/osu/files/12676348/input.log)
[updater.log](https://github.com/ppy/osu/files/12676349/updater.log)
[runtime.log](https://github.com/ppy/osu/files/12676350/runtime.log)

**Comment by bdach** [comment] 2023-09-20 18:43
Duplicate of #11571

**Closed by bdach** 2023-09-20 18:43 UTC
