### ISSUE TITLE
Tablet cursor randomly stops moving for a few frames randomly during gameplay

### ISSUE THREAD

**Issue by OffStageMY** [ppy/osu#11432] opened 2021-01-06 13:05 UTC
**Describe the bug:** A few times during normal gameplay on solo, my tablet cursor will stop moving for a few frames. Can't quite tell if the entire screen freezes or if it's only the tablet cursor as it's a very small interval of times. It happens a few times per beatmap relatively consistently.

**osu!lazer version:** 2020.1229.0

**Logs:**
2021-01-06 12:37:45 [verbose]: ----------------------------------------------------------
2021-01-06 12:37:45 [verbose]: performance Log for Panda (LogLevel: Verbose)
2021-01-06 12:37:45 [verbose]: osu 2020.1229.0.0
2021-01-06 12:37:45 [verbose]: Running on Microsoft Windows NT 6.2.9200.0, 12 cores
2021-01-06 12:37:45 [verbose]: ----------------------------------------------------------
2021-01-06 12:37:45 [verbose]: TextureAtlas initialised (1024x1024)
2021-01-06 12:37:45 [verbose]: TextureAtlas initialised (1024x1024)
2021-01-06 12:37:45 [verbose]: Texture requested (1920x8) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:46 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
2021-01-06 12:37:46 [verbose]: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
2021-01-06 12:37:46 [verbose]: TextureAtlas size exceeded 1 time(s); generating new texture (1024x1024)
2021-01-06 12:37:47 [verbose]: Texture requested (1400x310) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:47 [verbose]: Texture requested (1800x600) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:49 [verbose]: TextureAtlas size exceeded 2 time(s); generating new texture (1024x1024)
2021-01-06 12:37:49 [verbose]: Texture requested (1400x310) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:49 [verbose]: Texture requested (1366x768) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:53 [verbose]: Texture requested (1295x1295) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:53 [verbose]: Texture requested (1295x1295) which exceeds TextureStore's atlas size (1024x1024) - bypassing atlasing. Consider using LargeTextureStore.
2021-01-06 12:37:53 [verbose]: TextureAtlas size exceeded 3 time(s); generating new texture (1024x1024)
2021-01-06 12:38:10 [verbose]: TextureAtlas size exceeded 4 time(s); generating new texture (1024x1024)
2021-01-06 12:38:18 [verbose]: TextureAtlas size exceeded 5 time(s); generating new texture (1024x1024)
2021-01-06 12:38:29 [verbose]: TextureAtlas size exceeded 3 time(s); generating new texture (1024x1024)

**Comment by bdach** [comment] 2021-01-06 13:08
This log tells us nothing. Please attach a video of this, with the built-in FPS counter showing.

**Comment by peppy** [comment] 2021-01-18 07:16
Closing for now. This usually means that something on your system is blocking the input loop. This could be some application interfering with the windows event loop, or it could be your tablet drivers/software itself. Please check what is running on your system (and try shutting down applications / uninstalling unnecessary software to see if you can pinpoint the cause yourself).

**Closed by peppy** 2021-01-18 07:16 UTC
Labels: missing details
