### ISSUE TITLE
Cursor ripples

### ISSUE THREAD

**Issue by MightyHelper** [ppy/osu#6799] opened 2019-11-10 17:41 UTC
**Describe the new feature:** 
On click, add ripples like in osu!stable.
**Proposal designs of the feature:** 
I suggest you make this togglable in settings.

**Comment by Joehuu** [comment] 2019-11-10 17:41
Duplicate of https://github.com/ppy/osu/issues/5070

**Comment by iiSaLMaN** [comment] 2019-11-10 17:42
Adding to that, please consider searching for existing issues to avoid opening duplicates.

**Closed by Joehuu** 2019-11-10 17:41 UTC

**Comment by MightyHelper** [comment] 2019-11-10 18:05
Oops yeah. Sorry.
