### ISSUE TITLE
Cursor can be dragged off-screen

### ISSUE THREAD

**Issue by ZyerTCoder** [ppy/osu#9752] opened 2020-08-02 02:20 UTC
Cursor can be dragged off-screen

Shown in video:
https://cdn.discordapp.com/attachments/550808239957213206/739301470486396968/2020-08-02_02-58-48.webm
and https://imgur.com/b50NzD4

**osu!lazer version:** 
2020.801.0

**Comment by bdach** [comment] 2020-08-02 08:58
Duplicate of ppy/osu-framework#2247

**Closed by bdach** 2020-08-02 08:58 UTC
