### ISSUE TITLE
Score not registering when pressing the pause button right after the map is finished

### ISSUE THREAD

**Issue by Nelplays** [ppy/osu#7065] opened 2019-12-04 17:18 UTC
If you press the pause button right after the map is done, it's either puts you on the song select or stare at a blank playfield (you can quit but the score won't register). 

![osu_2019-12-05_01-14-02](https://user-images.githubusercontent.com/58525521/70164734-a7bd6b80-16fc-11ea-9fbb-916c50c95f0c.jpg)

**Comment by bdach** [comment] 2019-12-04 17:24
Duplicate of #6848.

**Closed by bdach** 2019-12-04 17:24 UTC
