### ISSUE TITLE
osu!lazer crashes in songselect after certain mouse buttons are pressed

### ISSUE THREAD

**Issue by Morilli** [ppy/osu#3153] opened 2018-07-31 19:18 UTC
I was playing around with clicking both mouse buttons and was doing all sorts of shenanigans with that. Doing that I noticed that it's relatively simple to crash the game in songselect if you do the following:

1. Activate the "Right mouse drag to absolute scroll" option if it isn't selected already.
2. Rightclick into the scrollable part of the song select screen and hold the button, then move the cursor to scroll.
3. While moving the cursor, do a left click.

This should immediately crash the game. Sometimes an error window pops up, sometimes it doesn't.
The console logs the following:
```
...
[runtime:error] fatal error:
[runtime:important] NUnit.Framework.AssertionException: We should never receive OnDrag if we are not dragging.
   at osu.Framework.Logging.ThrowingTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at osu.Framework.Graphics.Containers.ScrollContainer`1.OnDrag(InputState state)
   at osu.Game.Graphics.Containers.OsuScrollContainer.OnDrag(InputState state) in C:\Users\Moritz\osu\osu.Game\Graphics\Containers\OsuScrollContainer.cs:line 51
   at osu.Framework.Input.MouseButtonEventManager.HandleMouseDrag(InputState state)
   at osu.Framework.Input.MouseButtonEventManager.HandlePositionChange(InputState state)
   at osu.Framework.Input.InputManager.HandleMousePositionChange(InputState state)
   at osu.Framework.Input.UserInputManager.HandleMousePositionChange(InputState state)
   at osu.Framework.Input.StateChanges.MousePositionRelativeInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Unhandled Exception: NUnit.Framework.AssertionException: We should never receive OnDrag if we are not dragging.
   at osu.Framework.Logging.ThrowingTraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at osu.Framework.Graphics.Containers.ScrollContainer`1.OnDrag(InputState state)
   at osu.Game.Graphics.Containers.OsuScrollContainer.OnDrag(InputState state) in C:\Users\Moritz\osu\osu.Game\Graphics\Containers\OsuScrollContainer.cs:line 51
   at osu.Framework.Input.MouseButtonEventManager.HandleMouseDrag(InputState state)
   at osu.Framework.Input.MouseButtonEventManager.HandlePositionChange(InputState state)
   at osu.Framework.Input.InputManager.HandleMousePositionChange(InputState state)
   at osu.Framework.Input.UserInputManager.HandleMousePositionChange(InputState state)
   at osu.Framework.Input.StateChanges.MousePositionRelativeInput.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
   at osu.Framework.Threading.GameThread.runWork()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by ekrctb** [comment] 2018-08-01 05:01
Duplicate of ppy/osu-framework#1721.

**Closed by ekrctb** 2018-08-01 05:01 UTC
