### ISSUE TITLE
At signs won't show up unless you type something after them 

### ISSUE THREAD

**Issue by LiterallyFabian** [ppy/osu#14270] opened 2021-08-13 11:27 UTC
**Describe the bug:** At signs won't show up or play a key sound unless you type something after them, for example if you're going to write johnsmith@gmail.com, the text field will jump from `johnsmith` to `johnsmith@g`. This seem to happen everywhere, but I showed it in the registration process as it's probably more likely that users will come across it there.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/47401343/129350364-2561c4f3-6a1b-4993-8841-4c1cbd38418c.mp4

**osu!lazer version:** 2021.809.0

**Logs:** n/a

**Comment by Theighlin** [comment] 2021-08-13 11:57
I think this was brought up in #6386

**Comment by bdach** [comment] 2021-08-13 12:19
No. This is more likely to be a duplicate of #6338.

@LiterallyFabian please confirm whether you are typing in `@` with the use of an AltGr key.

**Comment by LiterallyFabian** [comment] 2021-08-13 12:22
Yes, AltGr+2. Pasting it in from the clipboard worked, so it looks to be a duplicate of those two

**Comment by bdach** [comment] 2021-08-13 12:22
Closing as such.

**Closed by bdach** 2021-08-13 12:22 UTC
