### ISSUE TITLE
Memory allocated for storyboards is never being released

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu#23258] opened 2023-04-20 23:13 UTC
### Type

Performance

### Bug description

Whenever you are trying to start a map with storyboard - osu! will increase the memory consumption and will never decrease it. Restarting the map or exiting to the song-select screen and starting again will increase it further and further and will stay at that point until the game being closed.
Upon quick look I noticed that `TextureStore` in `DrawableStoryboard` is never being disposed, so that's potentially the cause, but that's just a speculation for now.
With [this map](https://osu.ppy.sh/beatmapsets/1236988#osu/2573493) the issue is easy to reproduce, however it's not a map-specific problem since it happens with basically every storyboard as far as I can tell.

### Version

master

### Logs

n/a

**Comment by frenzibyte** [comment] 2023-04-21 09:24
It doesn't seem like `TextureStore` holds any resources that it can dispose of on disposal, since textures generally never get disposed, they continue to exist until all references to it are lost (which happens when all sprites no longer use the texture and the texture store containing it no longer has any references).

I do see the memory usage increasing however (consistently happens with https://osu.ppy.sh/beatmapsets/499488#osu/1077683), so there's definitely something bad going on.

**Comment by peppy** [comment] 2023-04-21 11:25
It's fine here. Releases fine.

Probably opengl renderer issues or something.

**Comment by frenzibyte** [comment] 2023-04-21 11:35
As per above, please check this isn't a duplicate of https://github.com/ppy/osu/issues/23252.

**Comment by EVAST9919** [comment] 2023-04-21 11:50
With LegacyGL memory usage goes down after some time, yes, but with D3D it's stays the same even after leaving the game idling in the main menu for 15 mins.

**Comment by peppy** [comment] 2023-04-24 05:38
@EVAST9919 can you try tapping the "clear all caches" button in settings and confirm it doesn't help?

![2023-04-24 14 38 29@2x](https://user-images.githubusercontent.com/191335/233908685-c3ea16f5-784d-4a18-833b-dd2ff6ab2087.png)

**Comment by EVAST9919** [comment] 2023-04-25 02:35
Yep, I tried - still doesn't help. Here's an example:
- Entered song-select - 500mb
- Starting gameplay with storyboard - 1400mb
- Went back to main menu - same
- Clear caches - 1200 mb (multiple times or after waiting for some time - still the same)
- Repeat multiple times to get more

As I said with LegacyGL memory consumption will be reduced by it's own after a bit, however clearing caches will do that instantly, so it should work as expected.
I can attach video showing the process however I'm not sure that can tell anything useful.

**Comment by frenzibyte** [comment] 2023-04-25 03:59
> As I said with LegacyGL memory consumption will be reduced by it's own after a bit, however clearing caches will do that instantly, so it should work as expected.

That would be textures getting garbage collected I believe, so yes that's working correctly

For the issue you're seeing, that sounds like unmanaged GPU resources not being disposed correctly, but I couldn't reproduce on any backend with the storyboards I had. I'll double check again, but this may potentially somehow depend on platform (maybe platform-specific code in Veldrid?)

**Comment by peppy** [comment] 2023-04-25 09:26
> Basically you need to get ~1.6 GB of memory usage and then go to any beatmap and continuously restart it

This is highly likely not a leak. It's just the .NET runtime expanding its used memory due to fragmentation or high memory requirements.

**Comment by EVAST9919** [comment] 2023-05-24 05:03
Found a small hint hopefully: I have only 4gb of vram, and after looking at it's usage it became obvious that it's not being freed in veldrid after textures disposal (for me at least). So huge ram usage - is actually overflowed vram.
But sorry if it was already obvious.

**Comment by peppy** [comment] 2023-05-24 05:26
I'm not sure how relevant, but there was an issue opened over at veldrid regarding ballooning Direct X memory usage. https://github.com/veldrid/veldrid/issues/508

**Comment by EVAST9919** [comment] 2023-06-21 02:30
Probably should be moved to the framework as it has nothing to do with storyboards but textures in general.

**Comment by peppy** [comment] 2023-06-21 03:02
Fine to keep it here for now.

**Comment by smoogipoo** [comment] 2024-05-12 14:58
Will likely be fixed in the next release by https://github.com/ppy/veldrid/pull/54

**Closed by smoogipoo** 2024-05-12 14:58 UTC
Labels: type:performance, area:storyboard, priority:1
