### ISSUE TITLE
Game crashes in 2019.1106.0

### ISSUE THREAD

**Issue by Cat375** [ppy/osu#6814] opened 2019-11-11 19:39 UTC
**Describe the bug:** 
Game crashes when i type some words in Direct > type to search 
**Screenshots or videos showing encountered issue:** 
Video here:
[Screenrecorder-2019-11-11-21-29-37-80(0).zip](https://github.com/ppy/osu/files/3832956/Screenrecorder-2019-11-11-21-29-37-80.0.zip)
**osu!lazer version:** 
2019.1106.0, Android
**Logs:** 
[runtime.log](https://github.com/ppy/osu/files/3832915/runtime.log)
[performance.log](https://github.com/ppy/osu/files/3832919/performance.log)
[network.log](https://github.com/ppy/osu/files/3832921/network.log)
[database.log](https://github.com/ppy/osu/files/3832923/database.log)

**Comment by bdach** [comment] 2019-11-11 19:44
Not only is this a duplicate of #6264, you should have been made aware we are not accepting mobile reports for the time being when creating this issue. Please read & search next time; closing.

**Closed by bdach** 2019-11-11 19:44 UTC
