### ISSUE TITLE
Osu!Lazer keep crashing after switched from Metal to OpenGL 

### ISSUE THREAD

**Issue by KoyuKansou** [ppy/osu#23007] opened 2023-03-27 05:55 UTC
### Type

Game behaviour

### Bug description

After i switched the renderer from Metal (which is enable by default on my iphone 7+) to Opengl to comparing the performace, the game didn't open anymore and just keep crashing after opening the game for few secs

### Screenshots or videos

https://user-images.githubusercontent.com/127967206/227852502-216f827d-553b-4620-be8b-d8d315d59687.mp4

### Version

2023.326.1-lazer (iOS TestFlight)

### Logs

[runtime.log](https://github.com/ppy/osu/files/11075122/runtime.log)
[database.log](https://github.com/ppy/osu/files/11075123/database.log)
[input.log](https://github.com/ppy/osu/files/11075124/input.log)
[network.log](https://github.com/ppy/osu/files/11075125/network.log)
[performance.log](https://github.com/ppy/osu/files/11075127/performance.log)

**Comment by longnguyen2004** [comment] 2023-03-27 05:57
Duplicate of #22978

**Closed** 2023-03-27 06:00 UTC

**Comment by peppy** [comment] 2023-03-27 06:02
use the "Legacy" renderer only for now.

to recover, uninstall the app then reinstall it, or wait for the next release.
