### ISSUE TITLE
elemental ranking

### ISSUE THREAD

**Issue by GDcheeriosYT** [ppy/osu#12888] opened 2021-05-20 14:39 UTC
this sounds kinda dumb but I think it would be really cool, adding like an elemental like ranking based on pp or something, elemental ranking like how other games do it like: rainbow six siege, league of legends, or overwatch. 

it would look something like this 
![image](https://user-images.githubusercontent.com/54640414/118993351-0efbc980-b94b-11eb-8e02-c7d4ee4d6d49.png)

the color and detail would change based on which rank and tier you are

potential ranking
iron = 100pp to 500pp or 1 million to 800k
bronze = 501pp to 1000pp or 799k to 550k
silver = 1001pp to 2000pp or 549k to 300k
gold = 2001pp to 3000pp or 399k to 150k
platinum = 3001pp to 4000pp or 149k to 95k
diamond = 4001pp to 5000pp or 94k to 50k
masters =  5001pp to 7000pp or 49k to 10k
grand_masters = 7001pp to 8000pp or 10k to 6k
cirlce_clicking_master = 8001pp to 9000pp or 5.9k to 3.15k
circle_clicking_legend = 9001pp to 10000pp or 3.14k to 1.5k
circle_clicking_demon = 10001pp and up or 1.4k to 1

there could also be tiers in between like bronze 3 or something

for example:
799k-700k bronze 1
699k-600k bronze 2
599k-550k bronze 3

**Comment by jai-x** [comment] 2021-05-20 14:56
I think this counts as a duplicate of https://github.com/ppy/osu/issues/4178 but with the added design constraint of adding elemental ranks to the matchmaking ranges.

**Closed by jai-x** 2021-05-20 14:56 UTC
