### ISSUE TITLE
settings, options, etc. can be interacted with after the respective menu is "closed"

### ISSUE THREAD

**Issue by XeZey** [ppy/osu#28920] opened 2024-07-18 15:36 UTC
### Type

Game behaviour

### Bug description

You can hold an option slider down and then press enter/esc to get rid of the mod/main menu. the slider will continue being fully interactable as long as the mouse is hold down. even holding down a non-interactable menu will keep a map from being started. you can also use the mouse to scroll through beatmaps and do the same thing etc. 

### Screenshots or videos

https://github.com/user-attachments/assets/ac88cd0c-41b1-4363-92e9-50cc49509b33

### Version

2024.718.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16285513/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-19 00:51
Duplicate of https://github.com/ppy/osu/issues/6121

**Closed by frenzibyte** 2024-07-19 00:51 UTC
Labels: type:input
