### ISSUE TITLE
osu!catch Juice Stream incorrectly generated

### ISSUE THREAD

**Issue by K3VRAL** [ppy/osu#20508] opened 2022-09-27 12:53 UTC
### Type

Game behaviour

### Bug description

While writing code on another project; I stumbled onto an issue regarding osu!lazer vs osu! stable's working mechanisms; the issue being how a Juice Stream (maybe also Slider because of the Timing Point) is implemented. A lot of the time it seems that osu!lazer and osu! stable works but then there are times in which it breaks since the Juice Stream on osu!lazer is generating more nested objects than in osu! stable as demonstrated in the YouTube videos in the `Screenshots or videos` section.

I believe the code linked below may have allowed for this bug to happen; or either the variable of `sinceLastTick` or `timeBetweenTiny`.

https://github.com/ppy/osu/blob/8642ed76313c128e2ad698cb5a8509a869d3d67f/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs#L81

The beatmap source code (while shortened) is enough for the beatmap to reproduce the bug in both stable and lazer and is located in the `Screenshots or videos` section as well.

Not sure if this does, but I believe this issue somewhat links to https://github.com/ppy/osu/issues/6184

### Screenshots or videos

[osu!catch on stable with 1 Tiny Droplet](https://www.youtube.com/watch?v=7m9pmFg0VdA)
[osu!catch on lazer with 3 Tiny Droplet](https://www.youtube.com/watch?v=A-0oAIeAGd0)

Beatmap:
osu file format v14

[General]
Mode: 2

[Difficulty]
SliderMultiplier:3
SliderTickRate:1

[TimingPoints]
15,937.5,4,2,1,50,1,0
15,-33.3333333333333,4,2,1,50,0,0

[HitObjects]
256,384,15,6,0,L|256:0,1,227

### Version

`Local Debug` and `osu! 2022.923.1-lazer`

### Logs

This seems to be more of an implementation issue than it is a user issue.

**Comment by peppy** [comment] 2022-09-28 11:07
Lazer:

![JetBrains Rider-EAP 2022-09-28 at 11 04 52](https://user-images.githubusercontent.com/191335/192763650-c581d9be-4031-4785-b0a0-d33d68303d83.png)


Stable:

![Parallels Desktop 2022-09-28 at 11 05 35](https://user-images.githubusercontent.com/191335/192763757-589b0651-8234-4da5-a2c2-2e34a7a4a371.png)


Note the rounding of values.

@smoogipoo is it correct here to match stable and floor to `int` local to catch slider logic?

```diff
diff --git a/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs b/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
index 015457e84f..f25260c79b 100644
--- a/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
+++ b/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
@@ -70,7 +70,8 @@ protected override void CreateNestedHitObjects(CancellationToken cancellationTok
                 // generate tiny droplets since the last point
                 if (lastEvent != null)
                 {
-                    double sinceLastTick = e.Time - lastEvent.Value.Time;
+                    // int matches stable
+                    int sinceLastTick = (int)(e.Time - lastEvent.Value.Time);
 
                     if (sinceLastTick > 80)
                     {

```

This does fix the attached beatmap in this issue. I'm not sure how sane it is going forward, and why this hasn't come up in diffcalc or otherwise noticed.

**Comment by K3VRAL** [comment] 2022-09-28 23:05
I believe that the reason as to why this has been hidden for so long is because; the difficulty calculator on osu!catch is not reliant on the Tiny Droplet meaning you can have an `x >= 0` amount of Tiny Droplets and always have the same difficulty of the map.

https://github.com/ppy/osu/blob/f3184525107b29018d7271e7bbcf779eec7ad1d8/osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs#L65

**Comment by smoogipoo** [comment] 2022-09-29 04:08
> @smoogipoo is it correct here to match stable and floor to `int` local to catch slider logic?

Possibly, though I imagine there will still be edge cases such as `(int)(999.999999998 - 500) = 499.99999998 -> (truncate) -> 499` where stable may be expecting `1000 - 500 -> 500`.

Best I could do is probably add a diffcalc attribute and run through every beatmap to look for differences, then compare those with stable.

**Comment by peppy** [comment] 2022-09-29 05:11
Ignoring that, is the correct direction to apply this change across the board (even to new beatmaps)? Seems like it probably not going to cause an actual issue as long as we stick to one or the other.

**Comment by smoogipoo** [comment] 2022-09-29 05:25
I wouldn't disagree with applying it across the board.

**Comment by bdach** [comment] 2023-12-13 13:22
This was brought up again [on discord](https://discord.com/channels/188630481301012481/188630652340404224/1184418808291667988). I've reviewed the situation as requested, by running the beatmap conversion test cases that already exist on `master`, as well as the reproduction beatmap provided in the OP.

The results are thus:

| interval calculation method | existing conversion tests | beatmap from OP |
| :- | :-: | :-: |
| `e.Time - lastEvent.Value.Time` (at the time of issue report) | ❌ fails: /b/1597806, /b/2190499, /b/2768615, /b/3644427, droplet-count | ❌ 3 droplets ![osu_2023-12-13_14-07-59](https://github.com/ppy/osu/assets/20418176/22c77c55-1cc1-4128-94cb-335fe91d7ed3) |
| `(int)e.Time - (int)lastEvent.Value.Time` (currently in master) | ✔️ no failures | ✔️ 1 droplet ![osu_2023-12-13_14-05-44](https://github.com/ppy/osu/assets/20418176/b9a4a0c1-668a-487a-a812-dac91189852a) |
| `(int)(e.Time - lastEvent.Value.Time)` (proposed above) | ❌ fails: /b/2190499, /b/3644427 | ✔️ 1 droplet ![osu_2023-12-13_14-09-01](https://github.com/ppy/osu/assets/20418176/95c33d1a-5012-4719-8631-01c346bcb1d6) |

For reference, the beatmap in question on stable looks like this:

![screenshot002](https://github.com/ppy/osu/assets/20418176/bd5a3a5b-4041-4b4e-a303-ae57232dff9c)

To sum up:

- The issue as reported in the OP is already fixed in `master` by https://github.com/ppy/osu/pull/25685/commits/7d602c792da2446375e73d1ed211f3d7f62f432f.
- The alternate fix as proposed in https://github.com/ppy/osu/issues/20508#issuecomment-1260746384 is less correct than the one already in `master`.
- I've also reviewed the stable code, and the variant currently in `master` does appear to be matching stable the closest. [This subtraction](https://github.com/peppy/osu-stable-reference/blob/7272e19dcc0d3e5a9bb66a636cc2c7174f82cb58/osu!/GameplayElements/HitObjects/Fruits/SliderFruits.cs#L124) is a subtraction of two truncated ints, not a truncated result of subtraction of two floats.

As such, I am closing this issue as resolved, and closing the draft PR opened above as superseded.

**Closed by bdach** 2023-12-13 13:22 UTC
Labels: ruleset/osu!catch, area:gameplay
