### ISSUE TITLE
Discrepancy between performance points (PP) on score card and Performance Breakdown

### ISSUE THREAD

**Issue by brainage04** [ppy/osu#21565] opened 2022-12-07 15:18 UTC
### Type

Game behaviour

### Bug description

After completing a play on any map, the game lets me browse through the top 50 scores on the leaderboard. When I clicked on the top 1 player's score card on this map (https://osu.ppy.sh/beatmapsets/307163#osu/687303) in osu!lazer, the performance points values on the score card and the Achieved PP in the Performance Breakdown section are different. I believe this may be because the user was using Double Time, but changed the speed multiplier to 1.1x, and the value on the score card was calculated with the default 1.5x speed.

### Screenshots or videos

![osu_2022-12-08_01-15-45](https://user-images.githubusercontent.com/101778999/206217454-2cfa45b7-59a7-4c86-9622-51a649f4df07.jpg)

### Version

latest (2022.1207.0-lazer)

### Logs

[network.log](https://github.com/ppy/osu/files/10177279/network.log)
[performance.log](https://github.com/ppy/osu/files/10177280/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/10177281/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10177282/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10177283/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10177284/updater.log)
[database.log](https://github.com/ppy/osu/files/10177285/database.log)
[input.log](https://github.com/ppy/osu/files/10177286/input.log)

**Comment by jai-x** [comment] 2022-12-07 16:34
Duplicate of https://github.com/ppy/osu/issues/19386

**Closed by jai-x** 2022-12-07 16:34 UTC
