### ISSUE TITLE
Raw Input Cursor Glitch

### ISSUE THREAD

**Issue by SummonedYa** [ppy/osu#3443] opened 2018-09-16 02:32 UTC
So on my new computer, when I play osu with my wacom tablet with raw input on, the cursor randomly jumps to the top left corner of the screen and back.

A week ago, it would only happen once in a while, so the game was still playable for the most part. However, it has gotten worse and now I am unable to play if raw input is turned on.

Although I have seen many other posts about cursor glitches, I cannot find a specific one where the cursor jumps to the top left corner and then pops back, so I decided this was worth a post.

Here's a play where the glitch is apparent.
http://www.mediafire.com/file/p81g7709r5qma0q/HopeOfPandora_-_Aoshima_Moka_%28CV_Mimori_Suzuko%29_-_kibo_refrain_%5BLight_Insane%5D_%282018-09-14%29_Osu.osr/file

On side note, does playing without raw input on a tablet with a sized active area have any difference from when you play with raw input?

**Comment by peppy** [comment] 2021-03-05 05:02
Closing as duplicate of https://github.com/ppy/osu/issues/3911 (leaving that one open as it has more discussion than this).

**Closed by peppy** 2021-03-05 05:02 UTC
Labels: type:input
