### ISSUE TITLE
In case ESC and CapsLock keys swapped

### ISSUE THREAD

**Issue by Samega7Cattac** [ppy/osu#12522] opened 2021-04-21 22:42 UTC
I have my CapsLock and ESC swapped bc I prefer, and every time I need to go back or exit my ESC (CapsLock key) doesn't work and when I click on my CapsLock (ESC key) it exits or goes back but also enables my CapsLock.
Using Arch Linux, KDE

**Comment by frenzibyte** [comment] 2021-04-21 22:44
Duplicate of https://github.com/ppy/osu/issues/11143

**Closed by frenzibyte** 2021-04-21 22:44 UTC

**Comment by frenzibyte** [comment] 2021-04-21 22:48
Actually doesn't look like it, I'm confused by your description, is it that osu!lazer takes your actual physical keys you press on your keyboard? can you record a video you pressing on the keys or describe in details, please. (like what does "ESC (CapsLock key)" mean, which is which)

**Comment by Samega7Cattac** [comment] 2021-04-21 22:53
When I say ESC (without the "key") I mean what is for me.
When I say CapsLock/ESC KEY (with the "key" word), means the physical key on the keyboard.

**Comment by frenzibyte** [comment] 2021-04-21 22:54
Ok then that is indeed a duplicate of https://github.com/ppy/osu/issues/11143.
