### ISSUE TITLE
Default cursor keeps disappearing.

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu#8837] opened 2020-04-22 15:47 UTC
**Describe the bug:** 
On almost every version, this bug always happens. The cursor randomly disappears at startup and then never reappears until I restart it, which is also based on chance. I haven't done too much research on how the cursor goes away and when but please just fix this. Even though its possible to navigate with just mouse hover animations, its pretty hard. No problem with game-play yet though.

**Screenshots or videos showing encountered issue:** 
![osu_2020-04-22_11-30-24](https://user-images.githubusercontent.com/32044067/80003133-91873080-848e-11ea-8cde-a347c07d877c.jpg)

**osu!lazer version:** 
 Latest(2020.421.0)

**Logs:**
[network.log](https://github.com/ppy/osu/files/4517197/network.log)
[performance.log](https://github.com/ppy/osu/files/4517198/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4517200/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4517201/updater.log)
[database.log](https://github.com/ppy/osu/files/4517202/database.log)

**Comment by bdach** [comment] 2020-04-22 17:04
Guessing this'll be a duplicate of #8487.

It's not as simple as "please just fix this" as it seems hardware-specific and we need a reproduction case - which would likely boil down to having the exact same hardware - to be able to do something about it.

**Closed by bdach** 2020-04-22 17:04 UTC
