### ISSUE TITLE
Replay Beatmap Colour Crash

### ISSUE THREAD

**Issue by Shiwari101** [ppy/osu#12011] opened 2021-03-13 18:07 UTC
**I played a Beatmap, at the score section I clicked to watch my replay. When i clicked "Beatmap colours" and changed back to normal the game freezes and close :** 

**Screenshots or videos showing encountered issue (sorry for low quality):** 
https://user-images.githubusercontent.com/64597370/111039539-617dae80-840d-11eb-9eeb-0b49d266af6c.mp4

**osu!lazer version: Lazer 2021.312.0
 

**Logs:**

[runtime.log](https://github.com/ppy/osu/files/6135266/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6135267/updater.log)
[database.log](https://github.com/ppy/osu/files/6135268/database.log)
[network.log](https://github.com/ppy/osu/files/6135269/network.log)
[performance.log](https://github.com/ppy/osu/files/6135270/performance.log)

-->

**Computer Specifications: Ryzen 3200g VEGA 8 2GB vRAM  8GB RAM **

**Comment by bdach** [comment] 2021-03-13 18:10
Duplicate of #5798

**Closed by bdach** 2021-03-13 18:10 UTC
