### ISSUE TITLE
Switching between two different beatmaps in Song Select that have the same first red timing point doesn't play the preview point.

### ISSUE THREAD

**Issue by Skubers** [ppy/osu#25666] opened 2023-12-04 14:32 UTC
### Type

Game behaviour

### Bug description

Import these two beatmaps:
https://osu.ppy.sh/beatmapsets/802214#osu/1683700
https://osu.ppy.sh/beatmapsets/2046139#osu/4271043

And switch between them in Song Select. Notice how the song continues from the first picked beatmap, instead of starting the song over from the preview point of the second map.

I've checked what is similar between them and I've found that they have the same time signature for the first red timing point
![image](https://github.com/ppy/osu/assets/82095491/4536c568-cd07-45ed-a6da-a85f472fa8de)
![image](https://github.com/ppy/osu/assets/82095491/c9aa661a-b47b-4db2-94bb-2ff1a7f2bbea)

### Screenshots or videos

https://github.com/ppy/osu/assets/82095491/58089cae-7090-44a2-9838-2c33b03688f3

### Version

2023.1130.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13547351/database.log)
[input.log](https://github.com/ppy/osu/files/13547352/input.log)
[network.log](https://github.com/ppy/osu/files/13547353/network.log)
[performance.log](https://github.com/ppy/osu/files/13547354/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13547355/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13547356/updater.log)

**Comment by bdach** [comment] 2023-12-04 14:36
The timing point has nothing to do with it. The two beatmaps in question have identical audio files.

```
$ sha256sum 2046139\ Halozy\ -\ S.A.T.O.R.A.R.E/audio.mp3 
1ece89f0fbea4c48b076efed242500df96471ef93cb77df25e898afc9dd8798d  2046139 Halozy - S.A.T.O.R.A.R.E/audio.mp3
$ sha256sum 802214\ Halozy\ -\ S.A.T.O.R.A.R.E/audio.mp3 
1ece89f0fbea4c48b076efed242500df96471ef93cb77df25e898afc9dd8798d  802214 Halozy - S.A.T.O.R.A.R.E/audio.mp3
```

See also / duplicate of: https://github.com/ppy/osu/discussions/19370.

**Closed by bdach** 2023-12-04 14:36 UTC
