### ISSUE TITLE
Music vanished after pressing ESC when Osu!Direct Preview is playing

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6849] opened 2019-11-14 06:36 UTC
**Describe the bug:** 
Press ESC when Osu!Direct Preview playing , the music gone
Manually stop Osu!Direct Preview will bring back the music

**Screenshots or videos showing encountered issue:** 
Sorry for this oversized file
https://www.mediafire.com/file/y6pelfugr7htd04/vanished.mp4/file
                 ###  **_14 DAY LIMITED FROM 2019-11-14 14:35 HK_**

**osu!lazer version:** 
app-2019.1113.0

**Logs:** 
[logs.zip](https://github.com/ppy/osu/files/3844925/logs.zip)

**Comment by peppy** [comment] 2019-11-14 06:44
Duplicate of https://github.com/ppy/osu/issues/6835.

**Closed by peppy** 2019-11-14 06:44 UTC
