### ISSUE TITLE
Local leaderboard does not display country flag

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu#8574] opened 2020-04-02 14:16 UTC
This is not a transfer, it’s exactly the games played in the lazer
![image](https://user-images.githubusercontent.com/59089206/78259581-3a053d00-7540-11ea-86b1-c0c7d5be8262.png)
![image](https://user-images.githubusercontent.com/59089206/78259609-44273b80-7540-11ea-8b83-eff2a029be50.png)
**osu!lazer version:** 
2020.402.0

**Comment by peppy** [comment] 2020-04-02 14:18
Duplicate of https://github.com/ppy/osu/issues/5966

**Closed by peppy** 2020-04-02 14:18 UTC
