### ISSUE TITLE
Dragging in editor timeline cannot select all notes

### ISSUE THREAD

**Issue by solstice23** [ppy/osu#20557] opened 2022-10-03 06:34 UTC
### Type

Game behaviour

### Bug description

Dragging in the editor timeline (top part of editor with circles inside) cannot select all notes. Some notes will be missed.

I wanted to create a practice map. I dragged in the timeline to select all notes that precede a specific time. But there were always some notes missing, so I had to repeat this progress until all of them were deleted.

### Screenshots or videos

https://user-images.githubusercontent.com/23134847/193514193-0ff47436-c99b-4490-8c71-62f2ff84a27d.mp4

### Version

2022.923.1

### Logs

[performance.log](https://github.com/ppy/osu/files/9695145/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/9695146/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/9695147/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/9695148/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9695149/updater.log)
[database.log](https://github.com/ppy/osu/files/9695150/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9695151/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9695152/network.log)

**Comment by peppy** [comment] 2022-10-03 06:41
Duplicate of https://github.com/ppy/osu/issues/16410

**Closed by peppy** 2022-10-03 06:41 UTC
