### ISSUE TITLE
Music stops after skin editor's automatic track looping when window is unfocused

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu#27811] opened 2024-04-08 16:02 UTC
### Type

Game behaviour

### Bug description

1. open the skin editor and click `Gameplay` (opening the skin editor from a replay or autoplay won't make gameplay loop)
2. wait or seek until the track ends 
3. have the game tabbed out when it loops
4. the music stops instead of restarting from the beginning
    - seeking anywhere else plays the music normally
    - letting it loop again normally restarts the music

### Screenshots or videos

https://github.com/ppy/osu/assets/36758269/5a48d25b-aae0-4d20-bcb6-8cb9969bb68f

### Version

tested on 2024.312.1-lazer and latest master (`b226a056377d3cc5ab537c2f9fd98fa851923c2c`)

### Logs

[1712590529.runtime.log](https://github.com/ppy/osu/files/14907913/1712590529.runtime.log)

**Comment by Gabixel** [comment] 2024-04-25 14:42
This looks like a duplicate of https://github.com/ppy/osu/issues/26022. Not sure which one is better to keep open in this case.

**Closed** 2024-04-25 15:23 UTC
Labels: audio, area:skin-editor
