### ISSUE TITLE
Missing small droplets in converted Catch the Beat maps.

### ISSUE THREAD

**Issue by Appreciativeness** [ppy/osu#3964] opened 2018-12-29 02:02 UTC
**Describe your problem:** Missing small droplets in converted Catch the Beat maps. I know this can be considered a duplicate of #3882, however, this only occurs with the one slider of the three with a large droplet in this difficulty, it is also the only one of the two difficulties causing this. I linked the map to help you narrow down what sliders are causing issues.
[R3 Music Box - Zankoku na Tenshi no These](https://github.com/ppy/osu/files/2715979/R3.Music.Box.-.Zankoku.na.Tenshi.no.These.zip)

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/46136945/50532043-49126980-0b0b-11e9-9ade-29636168ec08.png)

**osu!lazer version:** 2018.1228.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/2715988/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2715989/runtime.log)
[database.log](https://github.com/ppy/osu/files/2715990/database.log)

**Comment by ekrctb** [comment] 2019-01-21 12:46
Closing as duplicate of #3882.

**Closed by ekrctb** 2019-01-21 12:46 UTC
Labels: beatmap conversion, gameplay, high priority, osu!catch
