### ISSUE TITLE
Combo Colors not cycling properly

### ISSUE THREAD

**Issue by FireStorm680** [ppy/osu#13776] opened 2021-07-04 22:05 UTC
For some reason, on [this map](https://osu.ppy.sh/beatmapsets/366440#osu/804164) in lazer, the same combo color is being used twice in a row. I have no idea why this is happening.

Before anyone says it is custom combo colors, I had those very clearly disabled, and the combo colors would be cyan and gray in some parts, and cyan and blue in the others if I have it enabled.

Also, I played the [second map](https://osu.ppy.sh/beatmapsets/661483#osu/1400414) as a reference, showing that this bug where combo colors play twice in a row only happens in some maps. Also, I have tested this is stable, and this doesn't occur in either map.

That map is not the only map that incorrectly cycles through combo colors. [This map](https://osu.ppy.sh/beatmapsets/1253246#osu/2604568) also fails to cycle properly.

Video on [Streamable](https://streamable.com/jl3fmn) as the file is too large.

**Comment by frenzibyte** [comment] 2021-07-04 22:07
Duplicate of https://github.com/ppy/osu/issues/8282. Please search as it's already stated in the issue template.

**Closed by frenzibyte** 2021-07-04 22:07 UTC
