### ISSUE TITLE
Several errors on playlist mode

### ISSUE THREAD

**Issue by aphelionosu** [ppy/osu#12813] opened 2021-05-14 14:52 UTC
So I encountered two errors on playlist mode. 

First, is the map info, background dim and blur, disabling hitsounds and SB that whatever when you clicked on map to start to play it, it shows nothing but main menu background instead

https://user-images.githubusercontent.com/41836319/118287560-c2a12b80-b4fd-11eb-8149-b8054df05cbb.mp4

Second, when you want to retry a map either from result screen or pause menu, it will redirect you to playlist room instead

https://user-images.githubusercontent.com/41836319/118288022-36dbcf00-b4fe-11eb-9b86-48f785b10439.mp4

**osu!lazer version:2021.514.0** 

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6479499/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6479500/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6479502/updater.log)
[database.log](https://github.com/ppy/osu/files/6479503/database.log)

**Comment by frenzibyte** [comment] 2021-05-14 14:55
Duplicate of both #12797 and #12790.

**Closed by frenzibyte** 2021-05-14 14:55 UTC
