### ISSUE TITLE
Add Exit button on android

### ISSUE THREAD

**Issue by ojh050118** [ppy/osu#6072] opened 2019-09-11 14:12 UTC
**Describe the new feature:** 
1.Use the back button to pause the game you are playing.

2.Quit the game by adding an exit button. 

3.Press and hold the Back button on the main menu to end the game.

*Proposal designs of the feature:** 
osu-framework/osu.framework.android/AndroidGameHost.cs

Line 41: CanExit => true;

(I don't know anything else.)

**Comment by swoolcock** [comment] 2019-09-11 14:14
Duplicate of #5616.  Mobile apps do not have an exit button.

**Closed by swoolcock** 2019-09-11 14:14 UTC
