### ISSUE TITLE
Triangles bleed outside their container

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8395] opened 2020-03-21 19:28 UTC
**Describe the bug:** 
On exit confirmation screen, with 1920x1080 at 0.80x UI scale, triangle animation bleeds outside the bottom "Just a little more" button.

**Screenshots or videos showing encountered issue:** 
![osu_2020-03-21_21-06-48](https://user-images.githubusercontent.com/11320483/77234918-99676280-6bba-11ea-961f-8995e6791867.png)

**osu!lazer version:** 
2020.320.1

**Comment by bdach** [comment] 2020-03-21 19:28
Duplicate of #4591

**Closed by bdach** 2020-03-21 19:29 UTC
