### ISSUE TITLE
song select "sort by" dropdown menu sometimes does not work

### ISSUE THREAD

**Issue by Saerdna123** [ppy/osu#28631] opened 2024-06-27 03:14 UTC
### Type

Game behaviour

### Bug description

its buggy :/

### Screenshots or videos

https://github.com/ppy/osu/assets/33616260/b3640bce-16ba-4a7a-8064-74220ffb1aad

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16007458/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-06-27 05:39
This is caused by, and as far as I can tell fixed by https://github.com/ppy/osu-framework/pull/6315

**Closed by smoogipoo** 2024-06-27 05:39 UTC
