### ISSUE TITLE
Some skins exceed template skin and are scaled down

### ISSUE THREAD

**Issue by peppy** [ppy/osu#5510] opened 2019-07-29 10:19 UTC
Some skin creators took the liberty of exceeding skin dimension specifications. Currently lazer will downscale these to avoid unfair advantages from oversized elements. We probably want to define an allowable margin (32px?) for some elements and using masking rather than resizing in oversize scenarios.

Example:

356x356 approach circle (actual circle part is correct, but glow and transparent pixels add 100px)

![approachcircle@2x](https://user-images.githubusercontent.com/191335/62041063-c8992000-b235-11e9-92ba-5b71e6189d67.png)

**Comment by Joehuu** [comment] 2019-08-03 23:54
Duplicate of #2358?

**Closed** 2019-08-05 01:13 UTC
Labels: skinning
