### ISSUE TITLE
Touch doesnt work as cursor

### ISSUE THREAD

**Issue by Zen1thOrSomething** [ppy/osu#10755] opened 2020-11-09 20:48 UTC
I have no idea if this is a feature or not to be honest but I have been trying to use the touch controls as a cursor to play with my keyboard but I avent found a way to do it, I hope someone can help me

**Comment by bdach** [comment] 2020-11-09 20:52
What "touch controls" are you talking about? The "stylus"?

If you're on the release that was pulled today, please downgrade for now. Otherwise please actually elaborate as to what your issue is. I'm pretty sure touch controls *were* working at some point.

**Comment by Zen1thOrSomething** [comment] 2020-11-09 20:55
so im using  one of those styluses where you have to touch the screen to use it

**Comment by peppy** [comment] 2020-11-09 21:31
Use a previous version. Duplicate of https://github.com/ppy/osu/issues/10749.

**Closed** 2020-11-09 21:30 UTC

**Comment by Joehuu** [comment] 2020-11-09 21:39
FWIW, they are using the previous release as said in https://github.com/ppy/osu/issues/10754#issue-739334744.

@Zen1thOrSomething if you plan on making more issues, please fill in the template provided instead of outright deleting it.
