### ISSUE TITLE
Mania hidden mod go hard on linux

### ISSUE THREAD

**Issue by megaUwU-ui** [ppy/osu#23068] opened 2023-03-31 10:29 UTC
### Type

Game behaviour

### Bug description

long note render not correct

### Screenshots or videos

https://user-images.githubusercontent.com/63283109/229094934-21403e51-2ad5-4331-bcf7-af5f715acd6f.mp4

### Version

2023.326.1-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/11120832/runtime.log)
[performance.log](https://github.com/ppy/osu/files/11120833/performance.log)
[network.log](https://github.com/ppy/osu/files/11120834/network.log)
[input.log](https://github.com/ppy/osu/files/11120835/input.log)

**Comment by mouzedrift** [comment] 2023-03-31 14:57
likely a duplicate of #23009

**Comment by bdach** [comment] 2023-04-01 08:03
It is.

**Closed by bdach** 2023-04-01 08:03 UTC
