### ISSUE TITLE
Not confining mouse cursor when in fullscreen

### ISSUE THREAD

**Issue by makkarakka3** [ppy/osu#11973] opened 2021-03-06 18:18 UTC
**Describe the bug:** 
I really don't know what to title this, but when i have my second monitor plugged in, i can drag my cursor not into the second monitor when in fullscreen.

and btw i cant play in lazer when i have my second monitor plugged in because of hopefully this.
**Screenshots or videos showing encountered issue:** 
I couldn't get to record both of my screens, but hopefully this is somewhat helpful.
https://1drv.ms/u/s!AiDvP750cgLCiKNG3j4-OzzWNdSAHw?e=Ou2hZv
**osu!lazer version:** 
2020.302.0
**Logs:**
[network.log](https://github.com/ppy/osu/files/6095849/network.log)
[performance.log](https://github.com/ppy/osu/files/6095850/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6095851/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6095852/updater.log)
[database.log](https://github.com/ppy/osu/files/6095853/database.log)

**Comment by bdach** [comment] 2021-03-06 19:49
To confirm, because the video doesn't show it:

* What is your display mode? Borderless or fullscreen?
* What is your current "confine mouse mode" setting?

**Comment by makkarakka3** [comment] 2021-03-06 19:56
My current display mode is fullscreen and confine mouse mode is set to always.

**Comment by bdach** [comment] 2021-03-06 20:00
Do you have raw input on?

**Comment by makkarakka3** [comment] 2021-03-06 20:04
Yes

**Comment by bdach** [comment] 2021-03-06 20:05
Sounds like a duplicate of https://github.com/ppy/osu-framework/issues/2247, then.

**Closed by bdach** 2021-03-06 20:05 UTC
Labels: missing details
