### ISSUE TITLE
Group by star rating missing.

### ISSUE THREAD

**Issue by floppypp** [ppy/osu#30967] opened 2024-12-04 02:33 UTC
### Type

Cosmetic

### Bug description

Group by star rating is missing.

### Version

2024.1115.3

### Logs

[totally real a real log file.txt](https://github.com/user-attachments/files/18001831/totally.real.a.real.log.file.txt)

**Comment by Joehuu** [comment] 2024-12-04 02:40
Duplicate of https://github.com/ppy/osu/issues/4919

**Closed by Joehuu** 2024-12-04 02:40 UTC
