### ISSUE TITLE
crashing after start

### ISSUE THREAD

**Issue by theklensi** [ppy/osu#13571] opened 2021-06-19 04:01 UTC
**Describe the bug: crashing after start** 

**Screenshots or videos showing encountered issue:
![image](https://user-images.githubusercontent.com/86139035/122630338-3f668d00-d0dc-11eb-8032-24156bb5f5e4.png)** 

**osu!lazer version: 2021.619.0** 

**Logs: [runtime.log](https://github.com/ppy/osu/files/6679955/runtime.log)
[database.log](https://github.com/ppy/osu/files/6679964/database.log)
[network.log](https://github.com/ppy/osu/files/6679966/network.log)
[performance.log](https://github.com/ppy/osu/files/6679967/performance.log)
[updater.log](https://github.com/ppy/osu/files/6679968/updater.log)**

**logs path: C:\Users\User\AppData\Roaming\osu\logs**

**Comment by gagahpangeran** [comment] 2021-06-19 04:07
The error is the same as #13570 but in windows...

**Comment by theklensi** [comment] 2021-06-19 04:12
> The error is the same as #13570 but on windows...
![image](https://user-images.githubusercontent.com/86139035/122630605-67ef8680-d0de-11eb-8d51-2b728694aed8.png)
reinstalled game lol

**Comment by bdach** [comment] 2021-06-19 04:43
@theklensi can you please confirm that you are running Windows 8.1? that seems too be the case going by the log, but i want to make sure.

**Comment by theklensi** [comment] 2021-06-19 04:49
> @theklensi can you please confirm that you are running Windows 8.1? that seems too be the case going by the log, but i want to make sure.

yes im living on 8.1

**Comment by bdach** [comment] 2021-06-19 05:32
Closing as duplicate of #13570 and expanding scope of that issue to also cover older Windows versions. A fix for this will be coming soon.

**Closed by bdach** 2021-06-19 05:32 UTC
