### ISSUE TITLE
Imported scores have no profile picture & do not sort by score

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#11409] opened 2021-01-03 00:48 UTC
Imported scores do not sort by score & do not have a profile picture.

_Scores without profile pictures are imported, the others ones were made on lazer_
![osu_2021-01-02_19-39-07](https://user-images.githubusercontent.com/40531871/103469406-571aa680-4d32-11eb-8025-70ed3e6dac3e.png)

Osu lazer 2020.1229.0

Edit : Might be related to https://github.com/ppy/osu/issues/9402, impossible to click on the avatar

**Comment by Joehuu** [comment] 2021-01-03 00:57
Duplicate of https://github.com/ppy/osu/issues/5966 and https://github.com/ppy/osu/issues/10517.

**Closed by Joehuu** 2021-01-03 00:57 UTC
