### ISSUE TITLE
Imported stable library not detected

### ISSUE THREAD

**Issue by Meowzila** [ppy/osu#11778] opened 2021-02-14 19:04 UTC
**Describe the bug:** 
I imported my library from osu stable (~15k beatmaps) last night. All of the songs showed up just fine in my lazer library. Now, when I boot up lazer there are no beatmaps detected despite the installation folder having a size indicative of my entire osu library (~120gb). I have attached the database log, I don't have the original log file from last night as I think it was overwritten today.

**Screenshots or videos showing encountered issue:** 
Unsure what would be helpful here. Lazer shows the same "Import from Stable" or "Start from scratch" options as when I first installed it.

**osu!lazer version:** 
2021.212.0

**Logs:**

**Comment by frenzibyte** [comment] 2021-02-14 19:14
Could it potentially be that you incompletely moved the osu! folder to another location? Check whether you have a `storage.ini` file persisting at the original osu! folder location, and where is it pointing at (by the value of `FullPath` set inside that file).

Also can you check whether it works fine with a fresh database file (could be useful to identify whether it's an issue with lazer or the database file itself got weirdly corrupted somehow)? You can do that by moving the `client.db` file in the osu! folder somewhere else and do your previous steps but with a single beatmap (start lazer, import certain beatmap, restart, check whether it exists).

**Comment by Meowzila** [comment] 2021-02-14 19:36
Unfortunately, I could find storage.ini anywhere in the original osu folder. I moved client.db out of the lazer folder and reimported some maps which worked fine. After importing the maps and restarting the lazer client, a new client.db was not generated, but the few maps I had important were still in my library.

Below should be the logs. For some reason it didn't upload when I made the first post?
[database.log](https://github.com/ppy/osu/files/5978377/database.log)
[network.log](https://github.com/ppy/osu/files/5978378/network.log)
[performance.log](https://github.com/ppy/osu/files/5978379/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5978380/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5978381/updater.log)

**Comment by Meowzila** [comment] 2021-02-14 22:44
Okay, I think I figured out what the issue was. After I initially installed osu lazer, I tried to migrate the install folder to a different ssd other than my main one because it doesn't have much space on it and somehow the client.db files stayed in my C drive osu folder while the songs were on the other drive. Whenever I try to migrate it says it cannot be completed.
[https://i.imgur.com/D3G1wj2.png](url)
Are the original files at %AppData%/Roaming/osu supposed to remain there?

**Comment by frenzibyte** [comment] 2021-02-15 00:21
Well, that issue is known and all I can say is keep making more migration attempts, that error should go away after a number of tries. Otherwise you have to wait until that's fixed, by moving to a better DB system. (specific issue traked at https://github.com/ppy/osu/issues/9746)

> Are the original files at %AppData%/Roaming/osu supposed to remain there?

After a successful data migration, all files and folders except for `framework.ini`,`storage.ini`,`cache/` should be moved into the new location.

Closing as a somewhat duplicate of the aforementioned issue thread.

**Closed by frenzibyte** 2021-02-15 00:21 UTC
Labels: missing details

**Comment by peppy** [comment] 2021-02-15 01:39
You can recover from this by moving the database file (`client.db`) over to the new location and updating the path in `storage.ini`.

**Comment by Meowzila** [comment] 2021-02-15 19:37
Thank you for the response. I was able to get the game to see my entire library by moving the client.db file over but the beatmap files are not located by osu. I cannot seem to locate a storage.ini file anywhere in the original Appdata/Roaming/osu location or the new location on my other ssd.

Would it be possible for me to download someone else's storage.ini and just change the file path inside?
[https://i.imgur.com/m3HUfKn.png](url)

**Comment by frenzibyte** [comment] 2021-02-16 00:18
Just create a text file in the folder, type `FullPath=D:/path/to/new` with replacing `D:/path/to/new` with the actual full path to the new location in your SSD, and save it as `storage.ini`.
