### ISSUE TITLE
The icon of map still exist after deleting it

### ISSUE THREAD

**Issue by EatKFCinMc** [ppy/osu#21323] opened 2022-11-20 05:32 UTC
### Type

Performance

### Bug description

As title said, when I delete a map, its icon still remain in the selection screen and may cover other map's icon. But it won't exist when I start playing a map.

### Screenshots or videos

https://user-images.githubusercontent.com/69470365/202887162-7021a2d4-7be3-44a5-9c5c-da312c05bf18.mp4

### Version

2022.1117.0

### Logs

[input.log](https://github.com/ppy/osu/files/10048929/input.log)
[network.log](https://github.com/ppy/osu/files/10048930/network.log)
[performance.log](https://github.com/ppy/osu/files/10048931/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10048932/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10048933/updater.log)

**Comment by papertek** [comment] 2022-11-20 06:12
dupe of #21272

**Comment by EatKFCinMc** [comment] 2022-11-20 06:15
> dupe of #21272

got it. Can I delete this issue?

**Closed** 2022-11-20 07:45 UTC
