### ISSUE TITLE
Black on circles, main menu, beatmap menu, on texts, etc. [ osu!lazer ]

### ISSUE THREAD

**Issue by kravque** [ppy/osu#5902] opened 2019-08-30 19:15 UTC
**Describe the bug:** 
the game is black in black on circles and anything, tried to change settings, deleted it and moved it and nothing worked.

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/9dWtbW2
( 4 images )

**osu!lazer version:** 
2018,8,30 ( latest version )
**Logs:** 
https://drive.google.com/open?id=1YXRnnSSAcYWeYo7nEJBKiQiWfTBD9Wi5

**system information:**
Net Framework Update: 4.8
OS: Windows 7 Professional 6.1 ( Build 7601: Service Pack 1 )
Graphics Card: Intel(R) HD Graphics ( 128MB VRAM ) latest version
Memory: 4GB DDR3 1330MHz
Hard drive: Hitachi 250GB
Processor: Intel Celeron CPU B815 1.6GHz

**Comment by iiSaLMaN** [comment] 2019-08-30 19:17
Duplicate of #5199

**Comment by iiSaLMaN** [comment] 2019-08-30 21:51
Can be closed..?

**Comment by kravque** [comment] 2019-08-31 04:18
alright then, that means yall are trying to search about it and working on it?
btw i can say this happend on the 2018.8.14 update.

**Closed** 2019-08-31 04:19 UTC

**Comment by iiSaLMaN** [comment] 2019-08-31 14:40
> alright then, that means yall are trying to search about it and working on it?
> btw i can say this happend on the 2018.8.14 update.

Just saying, this is an old issue and may not be fix-able due to IHD3000's limitations, you can check the issue I linked and read more information on it.
