### ISSUE TITLE
Global Offset Is Not Consistent Like In Stable

### ISSUE THREAD

**Issue by jacques-jd** [ppy/osu#27663] opened 2024-03-18 17:22 UTC
### Type

Game behaviour

### Bug description

I'm a 7k player. When I played osu!stable, I used an offset of -32ms. It never changed, that was the right offset for my audio latency / keyboard situation. However, moving to osu!lazer, the offset doesn't work the same way. It's ok, because there's a button right? You play a few maps you can do 99% on, and then you press the button. The problem is the offset mechanism just seems very buggy in lazer. 

The reason I say this is because in the same play session, my recommended offset wildly changes from let's say -28ms to +15ms (not changing the number visually, but internally) for example. I'll usually adjust it as it tells me to just to see how it feels, and lo and behold my hits are indeed timed with the music again. But, when starting a new play session (restarting the game), the offset changes again. +15 all of a sudden is so clearly making the hit objects appear way too early. So I go back to the -30 or whatever I had before, and my hits are not earlier. This issue is *so* confusing that I genuinely don't know how to explain/replicate it. This is an issue that I NEVER experienced with Stable.

I don't obsessively go into the menu to look at the recommended offset, but if I play a tune and it feels wrong, I might go play another one and see how it feels there. Then, if it still feels off, I'll go check.

Another thing I've noticed with offset is that if you're watching a replay and you mess with the recommended offset on the right-hand UI (speed, seek, etc), it can offset your global offset weirdly. Like, I had to use -60 to reach -30, because I had applied -30 in the replay. This kind of stuff makes it really hard for me to switch from stable to lazer because I don't feel like I can trust the value that's shown to me as the truth.

Does anyone else experience this, or know why this is happening to me?

EDIT/Addon:
Similarly. Sometimes, when playing songs at HT, the map will randomly gain a crazy offset that makes notes a whole beat off-time. 

### Screenshots or videos

https://youtu.be/X9_0p-dknD8

Example of this happening. In this video, I show wild inconsistencies in the global offset between a restart.

It starts out in the Editor to show the delay happening. Notice the visual lag every time I press play, too. Maybe the audio engine struggles to get going? Idk.

 Running the song from the beginning at 100%  playrate shows the map starting on the wrong sound, but if I play it from the first note, the song starts where it should. Similarly, if I slow down the map to 25% you can tell the hit is supposed to be on the first note of the song. I then play it a couple times to show

_No response_

### Version

2024.312.1-lazer

### Logs

Logs: [compressed-logs.zip](https://github.com/ppy/osu/files/14640197/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-03-18 23:03
For DT/HT offset inconsistencies, see: https://github.com/ppy/osu/discussions/26132. 

According to the video and how you're describing the issue, it seems like there's an accumulating audio latency that goes away by restarting the game. This is a known issue but the problem with it is that it's only reported by a select number of players, and we could not find a way to reproduce it on our machines as far as I'm aware.

Closing as duplicate of https://github.com/ppy/osu/issues/26237.

**Closed by frenzibyte** 2024-03-18 23:03 UTC

**Comment by jacques-jd** [comment] 2024-03-18 23:09
Thanks for looking into it & linking the proper issues. I tried finding them but was not successful.
