### ISSUE TITLE
the font in internal profile viewer looks small, thin and ugly

### ISSUE THREAD

**Issue by thenotsosh** [ppy/osu#22321] opened 2023-01-21 20:47 UTC
### Type

Cosmetic

### Bug description

very old ugly bug, it's nothing critical but very weird

### Screenshots or videos

![image](https://user-images.githubusercontent.com/70341224/213886471-fb8cf0c0-df1f-46b5-8883-dae6bdf712fa.png)

### Version

2023.121.0

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/10473023/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10473024/network.log)
[performance.log](https://github.com/ppy/osu/files/10473025/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10473026/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10473027/updater.log)
[database.log](https://github.com/ppy/osu/files/10473028/database.log)
[input.log](https://github.com/ppy/osu/files/10473029/input.log)

**Comment by bdach** [comment] 2023-01-21 22:50
The root cause here is https://github.com/ppy/osu/issues/17940. tl;dr: the overlays are using pixel dimensions from web, but the way the client does measurements and font sizes doesn't match, leading to disproportionately small fonts.

This will be addressed properly with a scaling pass that will bring the two into parity. Closing as duplicate.

**Closed by bdach** 2023-01-21 22:50 UTC
