### ISSUE TITLE
Issues downloading "Super*Affection"

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#8792] opened 2020-04-18 13:05 UTC
**Describe the bug:** 
When downloading [Super*Affection](https://osu.ppy.sh/beatmapsets/41244) or [its TV size counterpart](https://osu.ppy.sh/beatmapsets/36137), after the download finishes beatmap imports correctly but ``DirectGridPanel`` nor ``HeaderButton`` aren't reflecting that it got imported (they display it as still downloading) and downloaded beatmaps have no option to view details.

**Screenshots or videos showing encountered issue:** 
Imported state not reflecting:
![osu_2020-04-18_15-59-31](https://user-images.githubusercontent.com/11320483/79638497-461f0a80-818e-11ea-909a-a93697623039.png)

No details:
![osu_2020-04-18_15-59-51](https://user-images.githubusercontent.com/11320483/79638503-4f0fdc00-818e-11ea-9942-df328f6b773e.png)

**osu!lazer version:** 
2020.418.0

**Logs:**
[super_affection_logs.zip](https://github.com/ppy/osu/files/4496655/super_affection_logs.zip)

**Comment by bdach** [comment] 2020-04-18 13:59
There's nothing in the logs or nothing to indicate this would be caused by this particular beatmap.

**Comment by LittleEndu** [comment] 2020-04-18 14:45
Yes, I did add the logs to show that there's nothing about it logged.

**Comment by peppy** [comment] 2020-04-20 06:05
This is due to in correct filename metadata at the database's end. Downloads cannot be correctly tracked without them getting a set ID on import. This is one of the edge cases where the beatmap is too old to have embedded online IDs.

Not really a fault of lazer, but has helped identify an issue with the beatmap and also an issue with osu-web's lookup logic (this case should have fallen back to checksums, which *do* match the database).

Will be fixing those two issues, but closing this one for now.

**Closed** 2020-04-20 11:23 UTC
Labels: missing details
