### ISSUE TITLE
Quick retry persist music for a while

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu#9789] opened 2020-08-06 06:02 UTC
Music persist for a while after a quick retry.

15 sec video 2 normal retries vs 2 quick retries https://clips.twitch.tv/AdventurousColdTireDendiFace

2020.801.0

[runtime.log](https://github.com/ppy/osu/files/5032900/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5032899/performance.log)
[database.log](https://github.com/ppy/osu/files/5032897/database.log)
[network.log](https://github.com/ppy/osu/files/5032898/network.log)
[updater.log](https://github.com/ppy/osu/files/5032896/updater.log)

**Comment by peppy** [comment] 2020-08-06 06:04
Not sure which behaviour is more expected, looks to be a race condition. May be fixed by other audio changes which are currently in the pipeline.

**Comment by Joehuu** [comment] 2020-08-06 06:28
Duplicate of https://github.com/ppy/osu/issues/5735.

Issue description in https://github.com/ppy/osu/issues/5735 (because title is somewhat misleading):
> The background music is played where the background music should not be.(loading page)
It's not always happening, it's sometimes happening.

**Closed by Joehuu** 2020-08-06 06:28 UTC
Labels: area:gameplay
