### ISSUE TITLE
Unable to launch - Ubuntu Linux

### ISSUE THREAD

**Issue by Rexyislive** [ppy/osu#12595] opened 2021-04-27 07:54 UTC
**Describe the bug:** 
Unable to launch / install from AppImage on Linux

**Logs:**

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.SDL_Init(UInt32 flags)
   at osu.Framework.Platform.SDL2DesktopWindow..ctor()
   at osu.Framework.Platform.Linux.LinuxGameHost.CreateWindow()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /var/lib/buildkite-agent/builds/debian-gnu-linux-vm-1/ppy/osu/osu.Desktop/Program.cs:line 54
Aborted

**Comment by smoogipoo** [comment] 2021-04-27 07:59
Duplicate of https://github.com/ppy/osu/issues/12523

**Closed by smoogipoo** 2021-04-27 07:59 UTC
