### ISSUE TITLE
Add [Photosensitive Epilepsy / PSE] Warning

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#6881] opened 2019-11-19 15:22 UTC
Kiddo_Kris
-

> I don't want to see the games I like involve legal issues. 
We never know if this will really help a player with PSE in the future.

**Describe the new feature:** 
-
> This is a real risk, even if it happens very rarely

Show photosensitive epileptic warning when needed
- Doing this **can help a player with Photosensitive Epilepsy avoid misfortune**
- Do this to make osu! and related personnel **avoid falling into legal problems**

**Proposal designs of the feature:** 
-
- Declare that there may be a flash in the game and affect the player with Photosensitive Epilepsy and inform the player to stop the game if there is any discomfort.
- Do it like Osu!Standard

> Osu!Stardard PSE warning
> ![TIM截图20191119232048](https://user-images.githubusercontent.com/56265123/69159665-42298680-0b23-11ea-95b2-693ebab03498.png)

**Comment by STCapricorn** [comment] 2019-11-19 15:28
Duplicate of #3114

**Closed** 2019-11-19 16:33 UTC
