### ISSUE TITLE
Submitted score different from replay

### ISSUE THREAD

**Issue by zealain** [ppy/osu#27705] opened 2024-03-23 16:05 UTC
### Type

Game behaviour

### Bug description

The score shown after watching the replay does not match the submitted score. The submitted score in the example below has 27 100s, whereas after watching the replay the result screen shows only 25 100s. This only seems to happen if you watch all or most of the replay.

Score: https://osu.ppy.sh/scores/2554529211

### Screenshots or videos

Result screen after watching the replay
![Result screen](https://github.com/ppy/osu/assets/56395201/33304c9c-9a93-4b68-b9a3-ce5042195f7b)

Submitted score
![Submitted score](https://github.com/ppy/osu/assets/56395201/e27a33aa-4c16-44b8-b507-2c3447a76d95)

Replay
https://drive.google.com/file/d/1p_CHFWzG79IIeHYL4i_jIZ-epQXXfiMW/view?usp=sharing (GitHub didn't accept the file type)

### Version

Lazer 2024.312.1

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14732119/compressed-logs.zip)

**Comment by ssz7-ch2** [comment] 2024-03-23 16:34
duplicate of https://github.com/ppy/osu/issues/11311

**Closed** 2024-03-23 19:14 UTC
