### ISSUE TITLE
Releasing a zero-length hold note (not hitting it, just releasing on it after hitting it) causes the game to crash

### ISSUE THREAD

**Issue by linearaccelerator** [ppy/osu#12518] opened 2021-04-21 09:34 UTC
**Describe the bug:** 
When releasing the key while tapping (holding?) a zero length hold note, the game crashes with a System.ArgumentException from the framework, but holding and missing the release timing works just fine and doesn't crash
**Screenshots or videos showing encountered issue:** 
![stacktrace](https://user-images.githubusercontent.com/64271566/115531282-e376b800-a294-11eb-8c2e-c8a1bf800e92.png)
[test map](https://drive.google.com/file/d/1T5QKy5tTpkAZbiCRldJIi6yYXZCPekzp/view?usp=sharing)
video:
https://user-images.githubusercontent.com/64271566/115531630-4ec08a00-a295-11eb-93b0-88b8906f9c0b.mp4
**osu!lazer version:** 
2020.410.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6349731/database.log)
[network.log](https://github.com/ppy/osu/files/6349732/network.log)
[performance.log](https://github.com/ppy/osu/files/6349733/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6349734/runtime.log)

**Comment by peppy** [comment] 2021-04-21 09:35
Please link the beatmap in question.

**Comment by frenzibyte** [comment] 2021-04-21 09:37
Sounds like the same exception and stack trace from https://github.com/ppy/osu/issues/12477, probably a duplicate.

**Comment by linearaccelerator** [comment] 2021-04-21 09:39
> Sounds like the same exception and stack trace from #12477, probably a duplicate.

That's a different report I made, regarding a different bug relating to those holds

**Comment by linearaccelerator** [comment] 2021-04-21 09:41
> Please link the beatmap in question.

[here](https://drive.google.com/file/d/1T5QKy5tTpkAZbiCRldJIi6yYXZCPekzp/view?usp=sharing)

**Comment by peppy** [comment] 2021-04-21 10:59
But this isn't a ranked beatmap, nor is it even uploaded? How did you make it?

**Comment by linearaccelerator** [comment] 2021-04-21 11:26
> But this isn't a ranked beatmap, nor is it even uploaded? How did you make it?

I don't know if this question is satirical or not, but osu!lazer has a mania editor which is accessed by opening the editor when having osu!mania selected as gamemode

**Comment by peppy** [comment] 2021-04-21 11:37
Right, this is a duplicate of https://github.com/ppy/osu/issues/12477 then.

**Comment by linearaccelerator** [comment] 2021-04-21 11:43
It's not though? #12477 is area:editor, this is area:gameplay

**Comment by bdach** [comment] 2021-04-21 11:48
Same stack trace implies same root cause. Fix for one will 99% fix the other.

**Comment by smoogipoo** [comment] 2021-04-22 09:54
Reopening this one because it tracks the gameplay crash, even though the editor was fixed and resulted in the closure of #12477.

**Comment by peppy** [comment] 2021-04-22 09:59
Are there actually beatmaps that have zero length holds? If not I'd propose removing them from the beatmap on parsing or something..

**Comment by bdach** [comment] 2021-04-22 10:37
I know that there are hacky osu! maps that have zero-length sliders (for whatever reason), so I imagine this might pop up again in the case of conversion of such maps to mania. Probably best to guard against it just for the peace of mind I suppose.

**Comment by smoogipoo** [comment] 2021-04-22 11:25
Only 2 beatmaps with at least one 0-length hitobject:
- https://osu.ppy.sh/beatmapsets/113175#mania/311122 (ranked; mania)
- https://osu.ppy.sh/beatmapsets/647515#mania/1371707 (loved; mania)

Not sure about unranked beatmaps, but given one of them is quite recent... I'm going to go ahead with the fix for now.

**Closed** 2021-04-22 12:14 UTC
Labels: area:gameplay, missing details
