### ISSUE TITLE
osu!lazer Crash on Launch

### ISSUE THREAD

**Issue by hamcoremusic** [ppy/osu#10114] opened 2020-09-10 01:59 UTC
**Describe the crash:** 
When attempting to open osu!lazer, it shows a black screen then crashes. This was not an issue a week ago.

**Screenshots or videos showing encountered issue:** 
N/A - I open, it black screens, and then closes.
**osu!lazer version:** 
2020.903.0
**Logs:**

[network.log](https://github.com/ppy/osu/files/5198735/network.log)
[database.log](https://github.com/ppy/osu/files/5198736/database.log)
[runtime.log](https://github.com/ppy/osu/files/5198738/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5198739/performance.log)
[updater.log](https://github.com/ppy/osu/files/5198740/updater.log)
**Computer Specifications:** 
![image](https://user-images.githubusercontent.com/28895283/92672820-95094000-f2e7-11ea-8350-c8f2e2043ce2.png)

**Comment by hamcoremusic** [comment] 2020-09-10 02:00
It says it is a database error. When opening the database log, it says something about an imported song AFAIK.

**Comment by peppy** [comment] 2020-09-10 02:00
Please delete client.db and try again. We are working on a fix for this elsewhere, but this is the simplest method right now.

**Closed by peppy** 2020-09-10 02:00 UTC

**Comment by hamcoremusic** [comment] 2020-09-10 02:07
Sorry, is there a way to restore my previously downloaded beatmaps?

**Comment by peppy** [comment] 2020-09-10 02:07
If you attach your client.db I can fix it for you.

**Comment by hamcoremusic** [comment] 2020-09-10 02:10
Wow! I really appreciate that. Here: https://we.tl/t-Yb6wILsu0F

I couldn't send via GitHub unfortunately.

**Comment by peppy** [comment] 2020-09-10 02:37
This this version:

[client.db.zip](https://github.com/ppy/osu/files/5198859/client.db.zip)

**Comment by hamcoremusic** [comment] 2020-09-10 02:42
Thank you so much!

**Comment by peppy** [comment] 2020-09-10 03:22
Just to leave a paper trail, this case was caused by a score being left behind and containing a reference to a beatmap that was to be purged on startup. Foreign key said no.

The manual fix for this is to remove the `ScoreInfo`s that are attached to `DeletePending` beatmap sets.

I've checked how this can happen and the only feasible possibility is that the deletion flow was interrupted (by quit or crash) before the event could fire in `OsuGameBase` to delete the scores.

Another possibility is that the score was set after the beatmap was in a `DeletePending` state (nothing is protecting against this).

Using database-level foreign keys for these kinds of patterns isn't feasible unless all related operations are correctly transactioned, which this one is not. I think we will need to re-think that particular flow, likely:

- Remove the event hooks from `OsuGameBase`
- Remove the foreign key
- Perform cleanup on the score store as a separate pass.

There is also documentation of another approach to this in an inline comment in `OsuGameBase`:

https://github.com/peppy/osu/blob/4dd6594547c3f9f622bd132653e19fde14d0accc/osu.Game/OsuGameBase.cs#L203-L205
