### ISSUE TITLE
Different score in the replay 

### ISSUE THREAD

**Issue by Gojomatte** [ppy/osu#31111] opened 2024-12-13 11:24 UTC
### Type

Performance

### Bug description

I wanted to show to my brother my top play and when i found the replay we watched it, but that at the end there was something different so i press esc and the score from the score selector on the right was different from the score at the end of the replay, in the replay i hit 12 note better.
At that point i change my skin and my cursor size to the one from when i sat that score but nothing change.
After that i was wondering if the other map had the same issues and the answer is yes, every map that i played has a different score in the replay.
P.s. i'm a laptop player, my monitor is 60hz, I don't use the laptop keyboard but am external one (no rapid trigger), I use a wacom tablet whit his normal pen

(Sorry for any error, english it's not my native languages)

### Screenshots or videos

https://github.com/user-attachments/assets/f4ead8d4-1d06-4c13-870a-54cfcff2d22f

### Version

2024.1208.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18125438/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-12-13 11:27
Duplicate of many other issues https://github.com/ppy/osu/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%3Areplay

**Closed by smoogipoo** 2024-12-13 11:27 UTC
