### ISSUE TITLE
Folder migration doesn`t work

### ISSUE THREAD

**Issue by Tresquel** [ppy/osu#10896] opened 2020-11-18 17:44 UTC
**Describe the bug:**
Yeah so when i tried to migrate the folder to my other disk i encountered these errors:

**Screenshots or videos showing encountered issue:**
![image](https://user-images.githubusercontent.com/43729305/99566775-9d5bb680-29cd-11eb-8f86-257f893ad3c7.png)

**osu!lazer version:**
2020.1114.0

**Logs:**

**Comment by bdach** [comment] 2020-11-18 17:47
Duplicate of #9746 for error no. 1. Error no. 2 is probably caused by you trying twice.

**Closed by bdach** 2020-11-18 17:47 UTC
