### ISSUE TITLE
Wrong mapper profile opening / wrong diffnamer name showed

### ISSUE THREAD

**Issue by tutis12** [ppy/osu#31331] opened 2024-12-29 02:38 UTC
### Type

Cosmetic

### Bug description

title

### Screenshots or videos

https://github.com/user-attachments/assets/cb96c6be-3e69-46e0-9edd-653b08bf0e40

### Version

2024.1224.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18268254/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-12-29 03:18
Duplicate of https://github.com/ppy/osu/issues/12965. Try searching before reporting an issue.

**Closed by frenzibyte** 2024-12-29 03:18 UTC
