### ISSUE TITLE
No osu!stable installation available on Mac error

### ISSUE THREAD

**Issue by SWAGEDGAR** [ppy/osu#12184] opened 2021-03-25 14:30 UTC
(There is also an error when I load up lazar. "IOException: Failed to open stream"
**Describe the bug:** 
When clicking anything button related to import from stable (skins, beatmaps, collections) it responds with a notification saying "No osu!stable installation available".
**Screenshots or videos showing encountered issue:** 
![osu_2021-03-25_10-30-51](https://user-images.githubusercontent.com/39568131/112489843-3708eb00-8d55-11eb-98cb-d5bcf7f6bc5c.jpg)
**osu!lazer version:** 
2021.323.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/6205371/database.log)
[network.log](https://github.com/ppy/osu/files/6205372/network.log)
[performance.log](https://github.com/ppy/osu/files/6205373/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6205374/runtime.log)

Mac specifications:
![Screen Shot 2021-03-25 at 10 29 52 AM](https://user-images.githubusercontent.com/39568131/112489700-1345a500-8d55-11eb-9f5d-9e70410d27b9.png)

**Comment by frenzibyte** [comment] 2021-03-25 14:35
There are two issues here:
 - The main one, duplicate of https://github.com/ppy/osu/issues/3763, for now you have to symlink your osu!stable folder to `~/.osu`.
 - `IOException: Failed to open stream`, presuming you're using a Wacom CTL-472, this is a common issue at OTD (see https://github.com/OpenTabletDriver/OpenTabletDriver/issues/848)

**Closed by frenzibyte** 2021-03-25 14:35 UTC

**Comment by SWAGEDGAR** [comment] 2021-03-25 15:21
> * The main one, duplicate of #3763, for now you have to symlink your osu!stable folder to `~/.osu`.
~/.osu leads to nowhere am I supposed to make a folder named that?

**Comment by frenzibyte** [comment] 2021-03-25 15:23
https://apple.stackexchange.com/questions/115646/how-can-i-create-a-symbolic-link-in-terminal
`ln -s path/to/stable ~/.osu`

**Comment by SWAGEDGAR** [comment] 2021-03-25 17:30
> https://apple.stackexchange.com/questions/115646/how-can-i-create-a-symbolic-link-in-terminal
> `ln -s path/to/stable ~/.osu`

thank you

**Comment by SWAGEDGAR** [comment] 2021-03-25 17:48
> https://apple.stackexchange.com/questions/115646/how-can-i-create-a-symbolic-link-in-terminal
> `ln -s path/to/stable ~/.osu`

hmmm when I put it in it goes through but it still doesn't work if I put it in anytime after that it responds with ln: `/Users/ree/.osu: File exists`

**Comment by bdach** [comment] 2021-03-25 17:53
The command won't work twice, correct. The symlink has already been created after all.

We cannot provide any help without more details. The symlink workaround has worked for multiple people before. If it doesn't for you then it might be an issue with your system specifically.
