### ISSUE TITLE
Deleting a beatmap still allows you to join and play aforedeleted beatmap in multiplayer

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu#3986] opened 2019-01-02 09:37 UTC
Upon deleting a beatmap in multiplayer song select and going back, the song remains playable in the multiplayer room.

Worth noting that once the client is restarted, the game will no longer detect the beatmap anymore.

<img width="962" alt="screen shot 2019-01-02 at 6 35 56 pm" src="https://user-images.githubusercontent.com/5578000/50586587-72414a00-0ebd-11e9-8443-e7643fcb6c4a.png">
<img width="958" alt="screen shot 2019-01-02 at 6 35 42 pm" src="https://user-images.githubusercontent.com/5578000/50586588-74a3a400-0ebd-11e9-9441-f6fc124629e7.png">

**Comment by peppy** [comment] 2019-01-02 09:39
This is correct behaviour to some extent. lazer will not delete beatmaps immediately (everything is a soft delete).

As for how this should be handled in this case, that is debatable. Currently we are always allowing usage of "deleted" beatmaps in `ConsumableItems`, but maybe this should change? Not sure.

**Comment by smoogipoo** [comment] 2019-01-08 10:47
Going to close this issue as intended for now, because we allow this everywhere else.

**Closed by smoogipoo** 2019-01-08 10:47 UTC
Labels: database, multiplayer
