### ISSUE TITLE
Applaud samples won't shut up

### ISSUE THREAD

**Issue by chayleaf** [ppy/osu#3831] opened 2018-12-07 08:39 UTC
Happens here: https://osu.ppy.sh/beatmapsets/139525/#taiko/361158

Once applauds start, they don't stop for like 30 seconds

**Comment by HoLLy-HaCKeR** [comment] 2018-12-14 22:32
Seems to be 2 issues:
1. Lazer doesn't look for `taiko-` prefixes on hitsound samples
2. Lazer will try to always load custom samples, even if CustomSampleBank is 0

I can't seem to find a way to fix 2, since SampleControlPoint is completely decoupled from LocalSkinOverrideContainer, where I believe the ISkinSource is decided.

**Comment by peppy** [comment] 2023-01-11 06:49
I know this is a very old one, but I can't reproduce the issue anymore. So it's probably fixed? @holly-hacker are you able to confirm?

**Comment by holly-hacker** [comment] 2023-01-11 16:36
I compared lazer's behavior (2022.1228.0) to stable's (20230101.2) using autoplay and the issue still seems to exist.

In lazer, on each large red note (and possibly some blue notes, I'm not too familiar with hitsamples in taiko) the applause/normal-hitfinish sample plays for about 5 seconds before fading out quite quickly. I'm not sure how this was supposed to last 30s considering the sample file is only 5s long. Presumably OP thought it kept on playing since it gets started multiple times.
In stable, there is no applause sound at all. I tried various combinations of skin settings but I always heard just the default hitsounds.

**Comment by peppy** [comment] 2023-01-13 06:02
At what point do you hear the sound?

**Comment by holly-hacker** [comment] 2023-01-13 11:10
https://user-images.githubusercontent.com/13605369/212306248-81ead849-ae14-4e47-bd47-6b8ed05eb458.mp4

It happens at every large red note, see attached video.

Since you don't seem to be able to repro this, I removed the map and downloaded it again. With a fresh import of the beatmap, it doesn't seem to happen anymore. I assume this is an old bug wrt importing beatmaps that has since been fixed?

**Comment by peppy** [comment] 2023-01-17 08:33
That is likely it. If that's the case, let's close this one as that's not going to be feasible to fix.

**Closed by peppy** 2023-01-17 08:33 UTC
Labels: ruleset:osu!taiko, area:gameplay
