### ISSUE TITLE
Cursor locked to an area in the right corner of the screen using OpenTabletDriver

### ISSUE THREAD

**Issue by matheusfsreinert** [ppy/osu#12415] opened 2021-04-14 21:17 UTC
**Describe the bug:** I'm running OTD on windows, when I play a map my cursor gets stuck in an area in the right corner of the screen, only happens with the tablet and while playing.

**Screenshots or videos showing encountered issue:** https://streamable.com/rcg1s1

**osu!lazer version:** 2021.410.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6313695/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6313696/updater.log)
[database.log](https://github.com/ppy/osu/files/6313697/database.log)

**Comment by frenzibyte** [comment] 2021-04-14 21:22
What window mode were you playing on while encountering this issue? and can you confirm whether switching to other window modes fixes it?

Also do you have "high precision mouse" enabled? have you tried turning it off?

**Comment by matheusfsreinert** [comment] 2021-04-14 21:26
I was playing on borderless, switching to fullscreen locks the cursor even in the menus and windowed is the same result as borderless. Disabling high precision mouse does fix the issue.

**Comment by frenzibyte** [comment] 2021-04-14 21:31
Marks it a duplicate of https://github.com/ppy/osu-framework/issues/4323 then, you'll have to disable cursor confinement and not use fullscreen in settings, or disable "high precision mouse", both as a temporary workaround.

**Closed by frenzibyte** 2021-04-14 21:31 UTC
