### ISSUE TITLE
StackOverflowException when opening chat overlay during triangle intro

### ISSUE THREAD

**Issue by bdach** [ppy/osu#6006] opened 2019-09-05 12:35 UTC
Originally this was a duplicate of #5075 as pointed out by @Joehuu later, but the issue from the title seems like a separate problem, see first comment in the thread below for specifics.

<strike>**Describe the bug:** Clicking escape during triangle intro sequence opens the social browser. The overlay cannot be dismissed using mouse or keyboard presses, and does not capture any mouse or keyboard events. It can be however closed by navigating to the menu (and therefore revealing the header) and clicking on the social browser button twice.

**Screenshots or videos showing encountered issue:** https://streamable.com/1u6vk

**osu!lazer version:** Latest master (9d0151f)

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3579283/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3579284/runtime.log)
[network.log](https://github.com/ppy/osu/files/3579285/network.log)</strike>

**Comment by bdach** [comment] 2019-09-05 21:24
So since I discovered this while bisecting #6005 and I just wanted to report it as to not forget about it later, it didn't occur to me to think how *insane* it is that it was the Escape key. So let me just fix my idiocy here: I had the social browser bound to `Esc`. I have no idea how that happened. I think it was while I was mucking around in the visual tests.

My brain decided to work for a little while and test the chat overlay too, and that also causes a bug, and that one is more spectacular - attempting to open the chat overlay on the triangles menu causes an instant crash with a `StackOverflowException`.

Here's [video evidence](https://streamable.com/9x80t) and some logs:

[network.log](https://github.com/ppy/osu/files/3581276/network.log)
[performance.log](https://github.com/ppy/osu/files/3581277/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3581278/runtime.log)

The amount of dumb luck I had involved with finding this is honestly impressive even to my standards.

**Comment by Joehuu** [comment] 2019-09-05 21:31
Duplicate of #5075.

**Comment by bdach** [comment] 2019-09-05 21:36
True to a degree I guess, but that crash to desktop might warrant a separate looking into. I'll leave it up to somebody smarter to decide if this should be closed or not.

**Comment by bdach** [comment] 2019-09-06 13:31
More details:
* This races, ie. it reproduces better in debug mode without the "this is a development build" splash screen, and sometimes I had to spam the binding to reproduce under debugger attached.
* WinDbg spews this stack:
```
0:034> !clrstack
OS Thread Id: 0x42fc (34)
        Child SP               IP Call Site
0000008009884498 00007ff98b25f1a6 [HelperMethodFrame: 0000008009884498] 
00000080098845b0 00007ff92bcc2ffa osu.Framework.Audio.AudioComponent.EnqueueAction(System.Action) [C:\projects\osu-framework-a4n7e\osu.Framework\Audio\AudioComponent.cs @ 41]
0000008009884620 00007ff92d0ea006 osu.Framework.Audio.Sample.SampleChannelBass.Play(Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Audio\Sample\SampleChannelBass.cs @ 84]
0000008009884660 00007ff92d0e9d71 osu.Game.Graphics.Containers.OsuFocusedOverlayContainer.onStateChanged(osu.Framework.Bindables.ValueChangedEvent`1<osu.Framework.Graphics.Containers.Visibility>) [D:\Open Source\osu\osu.Game\Graphics\Containers\OsuFocusedOverlayContainer.cs @ 115]
0000008009884720 00007ff92b844a4f DomainNeutralILStubClass.IL_STUB_MulticastDelegate_Invoke(System.__Canon)
0000008009884770 00007ff92c913baf osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].TriggerValueChange(osu.Framework.Graphics.Containers.Visibility, osu.Framework.Bindables.Bindable`1<osu.Framework.Graphics.Containers.Visibility>, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009884830 00007ff92c91397f osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].set_Value(osu.Framework.Graphics.Containers.Visibility) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009884880 00007ff92d0e9d0c osu.Game.Graphics.Containers.OsuFocusedOverlayContainer.onStateChanged(osu.Framework.Bindables.ValueChangedEvent`1<osu.Framework.Graphics.Containers.Visibility>) [D:\Open Source\osu\osu.Game\Graphics\Containers\OsuFocusedOverlayContainer.cs @ 110]
0000008009884940 00007ff92b844a4f DomainNeutralILStubClass.IL_STUB_MulticastDelegate_Invoke(System.__Canon)
0000008009884990 00007ff92c913baf osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].TriggerValueChange(osu.Framework.Graphics.Containers.Visibility, osu.Framework.Bindables.Bindable`1<osu.Framework.Graphics.Containers.Visibility>, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009884a50 00007ff92c91397f osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].set_Value(osu.Framework.Graphics.Containers.Visibility) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009884aa0 00007ff92d0efcdc osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__1(osu.Framework.Bindables.ValueChangedEvent`1)
0000008009884b00 00007ff92bc8783d osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].TriggerValueChange(Boolean, osu.Framework.Bindables.Bindable`1, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009884bc0 00007ff92b81f03a osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].set_Value(Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009884c10 00007ff92d0ee6ef osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__2(osu.Framework.Bindables.ValueChangedEvent`1<osu.Framework.Graphics.Containers.Visibility>) [D:\Open Source\osu\osu.Game\Overlays\ChatOverlay.cs @ 178]
0000008009884cb0 00007ff92b844a4f DomainNeutralILStubClass.IL_STUB_MulticastDelegate_Invoke(System.__Canon)
0000008009884d00 00007ff92c913baf osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].TriggerValueChange(osu.Framework.Graphics.Containers.Visibility, osu.Framework.Bindables.Bindable`1<osu.Framework.Graphics.Containers.Visibility>, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009884dc0 00007ff92c91397f osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].set_Value(osu.Framework.Graphics.Containers.Visibility) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009884e10 00007ff92d0efcdc osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__1(osu.Framework.Bindables.ValueChangedEvent`1)
0000008009884e70 00007ff92bc8783d osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].TriggerValueChange(Boolean, osu.Framework.Bindables.Bindable`1, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009884f30 00007ff92b81f03a osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].set_Value(Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009884f80 00007ff92d0ee6ef osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__2(osu.Framework.Bindables.ValueChangedEvent`1<osu.Framework.Graphics.Containers.Visibility>) [D:\Open Source\osu\osu.Game\Overlays\ChatOverlay.cs @ 178]
0000008009885020 00007ff92b844a4f DomainNeutralILStubClass.IL_STUB_MulticastDelegate_Invoke(System.__Canon)
0000008009885070 00007ff92c913baf osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].TriggerValueChange(osu.Framework.Graphics.Containers.Visibility, osu.Framework.Bindables.Bindable`1<osu.Framework.Graphics.Containers.Visibility>, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
0000008009885130 00007ff92c91397f osu.Framework.Bindables.Bindable`1[[osu.Framework.Graphics.Containers.Visibility, osu.Framework]].set_Value(osu.Framework.Graphics.Containers.Visibility) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
0000008009885180 00007ff92d0efcdc osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__1(osu.Framework.Bindables.ValueChangedEvent`1)
00000080098851e0 00007ff92bc8783d osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].TriggerValueChange(Boolean, osu.Framework.Bindables.Bindable`1, Boolean, Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 255]
00000080098852a0 00007ff92b81f03a osu.Framework.Bindables.Bindable`1[[System.Boolean, System.Private.CoreLib]].set_Value(Boolean) [C:\projects\osu-framework-a4n7e\osu.Framework\Bindables\Bindable.cs @ 88]
00000080098852f0 00007ff92d0ee6ef osu.Game.Overlays.ChatOverlay+c__DisplayClass24_0.b__2(osu.Framework.Bindables.ValueChangedEvent`1<osu.Framework.Graphics.Containers.Visibility>) [D:\Open Source\osu\osu.Game\Overlays\ChatOverlay.cs @ 178]
(...and so on)
```
Possibly related to these lines? They look like they _might_ create a feedback loop:
https://github.com/ppy/osu/blob/75476df1af9b3dfed4e17dd9a8a4fc31a28b1ae1/osu.Game/Overlays/ChatOverlay.cs#L174-L178

**Closed** 2019-09-11 10:39 UTC
Labels: bug
