### ISSUE TITLE
Judgement counter during gameplay is not accurate 

### ISSUE THREAD

**Issue by AntonEvang** [ppy/osu#24505] opened 2023-08-11 19:58 UTC
### Type

Game behaviour

### Bug description

While playing a map, sometimes game interprets clicks the wrong way, so I have wrong amount of misses, 50's, and so on. These scores go to the local and global scoreboards. Some scores get "This score is still being calculated" and some give pp. After watching a replay, I have different accuracy numbers.
Replay scores can be better or worse than local/global.

I think this has something to do with sliders because:
1. The first time I got (or noticed) this bug couple days ago while hitting easy slider and getting a miss (when I watched the replay, there was no miss)
2. The score is more broken on slider-heavy map (screenshots 1 and 2)

Settings: nomod
Snaking in sliders: off
Snaking out sliders: on

### Screenshots or videos

![localscore1](https://github.com/ppy/osu/assets/90830607/9502b4c5-84c1-49d8-bacf-9a10dc206110)
![replayscore1](https://github.com/ppy/osu/assets/90830607/a50d0087-fa94-4ccf-b112-049871affc75)
![givespp1](https://github.com/ppy/osu/assets/90830607/ff7d0938-e454-4452-a192-88a759bf4556)

![localscore2](https://github.com/ppy/osu/assets/90830607/4660033e-3862-4773-9c00-87ab5b68bc06)
![replayscore2](https://github.com/ppy/osu/assets/90830607/307095de-f2b0-44b6-8363-7376cccc9ac0)
![givespp2](https://github.com/ppy/osu/assets/90830607/7be60d79-6be5-4660-8f5f-57677c8f8412)

![localscore3](https://github.com/ppy/osu/assets/90830607/7c06f3d4-cbc1-4304-86af-ef15012fed33)
![replayscore3](https://github.com/ppy/osu/assets/90830607/f96bc1e6-1872-43d5-ae7a-8707b74dc3b1)
![givespp3](https://github.com/ppy/osu/assets/90830607/4978ee9f-0cd2-4a39-8c16-7c8d0aa218e0)

![localscore4](https://github.com/ppy/osu/assets/90830607/1cf3a954-9daf-45b9-a3bd-879ba6bb06d1)
![replayscore4](https://github.com/ppy/osu/assets/90830607/9c101c9d-8a32-42f6-9861-442afd9147c4)
![givespp4](https://github.com/ppy/osu/assets/90830607/01f1bdc6-431b-4f1c-884e-9900703e41d0)

### Version

2023.803.0

### Logs

[database.log](https://github.com/ppy/osu/files/12324620/database.log)
[input.log](https://github.com/ppy/osu/files/12324621/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12324623/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12324624/network.log)
[performance.log](https://github.com/ppy/osu/files/12324625/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/12324626/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12324627/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12324628/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/12324629/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12324630/updater.log)

**Comment by bdach** [comment] 2023-08-11 20:27
Duplicate of https://github.com/ppy/osu/issues/19766 and probably like 5 other instances of this

**Closed by bdach** 2023-08-11 20:27 UTC
