### ISSUE TITLE
Opening settings mid loading will result in a static, not interactive window

### ISSUE THREAD

**Issue by l3lackShark** [ppy/osu#5367] opened 2019-07-15 16:16 UTC
**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=rpbhfY7A0dw

**osu!lazer version:** 
2019.713.0

**Comment by iiSaLMaN** [comment] 2019-07-15 16:18
Duplicate of #5075

**Closed** 2019-07-15 16:19 UTC
