### ISSUE TITLE
Game is on low quality

### ISSUE THREAD

**Issue by Yoru-Kitsune** [ppy/osu#23256] opened 2023-04-20 19:34 UTC
### Type

Other

### Bug description

All custom skins are on a low quality. Some ui objects too.
It isn't my display because other ui objects or preset skins work totally fine.
I also tried removing the not "@2x" files from the skins. It didn't work too well tho.

### Screenshots or videos

![UI](https://user-images.githubusercontent.com/108625654/233468504-0bed49b3-cf05-4e8d-a24a-d36879df46cb.png)
![Skin 1](https://user-images.githubusercontent.com/108625654/233468511-3fd1e00d-e93e-4433-b80d-e70dce4551de.png)
![Skin 2](https://user-images.githubusercontent.com/108625654/233468517-a5331711-185e-4c80-be1b-0b77d363f383.png)
![Skin 3](https://user-images.githubusercontent.com/108625654/233468520-058cebb0-9078-49d6-8f6d-31f1ce55568d.png)

### Version

2023.419.0 (Amdroid)

### Logs

[Database](https://github.com/ppy/osu/files/11289840/database.log)
[Performance](https://github.com/ppy/osu/files/11289843/performance.log)
[Network](https://github.com/ppy/osu/files/11289844/network.log)
[Runtime](https://github.com/ppy/osu/files/11289846/runtime.log)

**Comment by Joehuu** [comment] 2023-04-20 19:53
Duplicate of https://github.com/ppy/osu/issues/23249

**Closed by Joehuu** 2023-04-20 19:53 UTC
