### ISSUE TITLE
Rewinding Autoplay Replay, breaks CTB

### ISSUE THREAD

**Issue by mmatt625** [ppy/osu#2880] opened 2018-06-25 13:33 UTC
When you go to a part in a CTB replay with Autoplay, then rewind, the fruit that was played when you rewind it stays there.

**Comment by ekrctb** [comment] 2018-06-25 13:40
Duplicate of #2729.

**Comment by mmatt625** [comment] 2018-06-25 13:41
sorry about that, didn't know :p

**Closed** 2018-06-25 13:40 UTC
