### ISSUE TITLE
Crash & errors with "Imported beatmapsests" notification

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#3980] opened 2019-01-01 14:12 UTC
**Describe your problem:** When clicking on the "Imported `number of beatmapsets` beatmapsets!" notification, the game shows up some errors, but if you're going to spam-click the same notification, the game freezes for few seconds and then crashes.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/uifbd

**osu!lazer version:** 2018.1228.0.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2719349/database.log)
[debug.log](https://github.com/ppy/osu/files/2719350/debug.log)
[network.log](https://github.com/ppy/osu/files/2719351/network.log)
[performance.log](https://github.com/ppy/osu/files/2719352/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2719353/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2719354/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2719355/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2719356/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2719357/runtime.log)

**Computer Specifications:** 
OS: Windows 10 Home (x64)
RAM: 8GB DDR4
CPU: AMD Ryzen 5 1600 Six-Core Processor, 3.2 GHz
GPU: AMD Radeon™ RX 580 Series (8GB GDDR5)

**Comment by peppy** [comment] 2019-01-02 02:31
Checking your logs, it looks like there may have also been some import failures. Can you confirm whether or not this was the case?

**Comment by peppy** [comment] 2019-01-02 02:40
Also on trying to reproduce your issue, when I click the import message it successfully dismisses.

**Comment by Gabixel** [comment] 2019-01-02 11:16
> Checking your logs, it looks like there may have also been some import failures. Can you confirm whether or not this was the case?

Yes, I can confirm because in the last days these errors appear every time I try to check/import maps (I can see something like `DeletePending`, could it be caused by just one or a few maps?):
![error 1](https://user-images.githubusercontent.com/43073074/50589455-fb895a00-0e86-11e9-8b4a-5b88cf687ac7.png)
And this error:
![error 2](https://user-images.githubusercontent.com/43073074/50589461-fe844a80-0e86-11e9-9389-66cd16f71fd5.png)

**Comment by Gabixel** [comment] 2019-01-02 11:24
Also, in the first screenshot it says "_Import of Suzuki Konomi - Suzuki Konomi - This Game (TV Size) (Cuked) failed an has been rolled back_" ([this map](https://osu.ppy.sh/beatmapsets/229249#osu/533494)), maybe it could be something related.

**Comment by Gabixel** [comment] 2019-01-02 11:39
I deleted the map from osu! stable and osu!lazer (and then reimported), and the first bunch of errors seems to don't appear anymore. But now if I try to click the notification, it sends me to `Solo` (if I'm on the main menu, and the notification doesn't dismiss anyway).

I'll attach new logs:
[database.log](https://github.com/ppy/osu/files/2720609/database.log)
[debug.log](https://github.com/ppy/osu/files/2720610/debug.log)
[network.log](https://github.com/ppy/osu/files/2720611/network.log)
[performance.log](https://github.com/ppy/osu/files/2720612/performance.log)
[performance-gamethread.audio.log](https://github.com/ppy/osu/files/2720613/performance-gamethread.audio.log)
[performance-gamethread.draw.log](https://github.com/ppy/osu/files/2720614/performance-gamethread.draw.log)
[performance-gamethread.input.log](https://github.com/ppy/osu/files/2720615/performance-gamethread.input.log)
[performance-gamethread.update.log](https://github.com/ppy/osu/files/2720617/performance-gamethread.update.log)
[runtime.log](https://github.com/ppy/osu/files/2720618/runtime.log)

**Comment by peppy** [comment] 2019-04-03 08:39
Could you please check whether this still happens?

**Comment by Gabixel** [comment] 2019-04-03 15:29
Seems fixed: https://streamable.com/qso64
It sends you to a random map but that's ok I guess, the only weird thing is that the playing song, after you click the notification, on the `PlaylistList` doesn't seem to set `selected` to True, so it remains a white text even though it is playing (but this must be checked again, I'm not sure).

**Comment by smoogipoo** [comment] 2019-04-04 06:24
That'll probably be fixed with @nekodex 's rework of rearrangeable lists. Closing as the original issue was fixed.

**Closed by smoogipoo** 2019-04-04 06:24 UTC
Labels: bug, import
