### ISSUE TITLE
Results screen doesn't display profile cover when entered from scoreboard

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#7161] opened 2019-12-11 17:24 UTC
**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/15932372/70644514-76382900-1c43-11ea-96a5-1bf2e80847c1.png)

**osu!lazer version:** 2019.1205.0

**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3951709/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3951710/runtime.log)
[updater.log](https://github.com/ppy/osu/files/3951711/updater.log)
[database.log](https://github.com/ppy/osu/files/3951712/database.log)
[network.log](https://github.com/ppy/osu/files/3951713/network.log)

**Comment by iiSaLMaN** [comment] 2019-12-11 19:19
Almost duplicate of #5966 that it would be fixed at once.

**Comment by peppy** [comment] 2019-12-12 02:28
Going to close this as duplicate – it hinges on the same shortcoming.

**Closed by peppy** 2019-12-12 02:28 UTC
Labels: results
