### ISSUE TITLE
Add helping text for Guest users that they need to login to use osu!direct

### ISSUE THREAD

**Issue by vruss** [ppy/osu#7386] opened 2019-12-28 22:14 UTC
**Describe the new feature:** 
A text that teaches new users that they need to create an account in order to download songs with osu!direct

**Proposal designs of the feature:** 
Currently when a Guest user tries to go to the multiplayer page, a notification is displayed telling the user to sign in. I'm thinking something similar can be added for the osu!direct page. 

This is what it currently looks like
![This is what it currently looks like](https://i.imgur.com/GQpWDc7.png)

**Comment by iiSaLMaN** [comment] 2019-12-28 22:16
Duplicate of https://github.com/ppy/osu/issues/4550

**Closed** 2019-12-28 22:20 UTC
