### ISSUE TITLE
mania notes render at the center of stage on sudden slow scrolling speeds

### ISSUE THREAD

**Issue by enoslayd** [ppy/osu#8826] opened 2020-04-21 14:33 UTC
Describe the bug: title says it, its just that this beatmap: https://osu.ppy.sh/beatmapsets/372942 has a very slow mid section and in lazer, that part generates notes at the center parts of the screen. *just change the title, i really dont know what title it must be*

Screenshots or videos showing encountered issue: (just remove .zip)
[My Movie.mp4.zip](https://github.com/ppy/osu/files/4510595/My.Movie.mp4.zip)

osu!lazer version: 2020.421.0

Logs:
[updater.log](https://github.com/ppy/osu/files/4510585/updater.log)
[database.log](https://github.com/ppy/osu/files/4510587/database.log)
[performance.log](https://github.com/ppy/osu/files/4510588/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4510589/runtime.log)

**Comment by Coppertine** [comment] 2020-04-21 14:43
I think that's intended, it's just the notes not being rendered when a low scroll speed is changed in the playfield.

**Comment by enoslayd** [comment] 2020-04-21 14:44
i dont agree??????

**Comment by Coppertine** [comment] 2020-04-21 14:45
Basically, it's working as intended, however I think you are pointing out the issue where objects are only appearing later than expected and not from the top as you thought?

**Comment by enoslayd** [comment] 2020-04-21 14:46
But it should appear from the top. Cause thats just like applying fade in mod

**Comment by Coppertine** [comment] 2020-04-21 14:49
Change title to "Mania notes render too late under slow scrolling speeds"

**Comment by enoslayd** [comment] 2020-04-21 14:54
ok

**Comment by peppy** [comment] 2020-04-22 03:02
This is due to (quite arbitrary) lifetime specifications, which probably need to be more dynamic based on the scroll speed of the hitobject.

**Comment by bdach** [comment] 2020-05-20 21:59
I'm reasonably certain I have a fix for this one, just need another day to get a visual test going, double-check that the lifetime as tight as it can be and package the fix in an understandable manner.

**Closed** 2020-05-22 06:17 UTC
Labels: area:gameplay, ruleset:osu!mania
