### ISSUE TITLE
Fail Screen continues to play music after exiting the beatmap

### ISSUE THREAD

**Issue by ValkoNova** [ppy/osu#22343] opened 2023-01-22 05:33 UTC
### Type

Game behaviour

### Bug description

Basically, I'm using a skin from osu!Stable and whenever I fail a map, music plays. However, after the update, the music continues playing even if I exit the beatmap.

I even tested what would happen if I failed twice within the duration the music plays. It just gets worse.

It didn't do this in the previous updates either.

### Screenshots or videos

[

https://user-images.githubusercontent.com/123286420/213902032-41d11df2-a12a-4be9-b940-3933166eb806.mp4

](url)

### Version

2023.121.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10473829/database.log)
[input.log](https://github.com/ppy/osu/files/10473830/input.log)
[network.log](https://github.com/ppy/osu/files/10473831/network.log)
[performance.log](https://github.com/ppy/osu/files/10473832/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10473833/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10473834/updater.log)

**Comment by Joehuu** [comment] 2023-01-22 05:38
Duplicate of https://github.com/ppy/osu/issues/22173

**Closed by Joehuu** 2023-01-22 05:38 UTC
