### ISSUE TITLE
No way to modify base slider velocity

### ISSUE THREAD

**Issue by Pennek** [ppy/osu#11003] opened 2020-11-29 23:07 UTC
Base slider velocity can't be modified inside the Editor yet.

**osu!lazer version:** 2020.1128.0

**Comment by peppy** [comment] 2020-11-30 09:25
For what it's worth, I don't think we will have a "base" slider velocity going forward. This will be 1x and will be modified either via adding a difficulty control point of by changing it on a per-slider basis.

**Comment by peppy** [comment] 2021-03-17 08:16
Duplicate of #7882

**Closed by peppy** 2021-03-17 08:16 UTC
Labels: area:editor, priority:2
