### ISSUE TITLE
SPM is still growing even if not "spinning"

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#9750] opened 2020-08-01 16:39 UTC
**Describe the bug:** 
SPM is still growing even if not "spinning"

**Screenshots or videos showing encountered issue:** 
https://streamable.com/h046qf

**osu!lazer version:** 
app-2020.801.0
[performance.log](https://github.com/ppy/osu/files/5010929/performance.log)

**Logs:**
[performance-audio.log](https://github.com/ppy/osu/files/5010923/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/5010924/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/5010925/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/5010926/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/5010927/runtime.log)
[database.log](https://github.com/ppy/osu/files/5010928/database.log)

**Comment by frenzibyte** [comment] 2020-08-01 17:19
Not in the issue topic, but as a tip, the issue title was kinda misleading, it reads to me like the `SPM` counter grows up while the spinner isn't being spinned (incorrect counter issue), while it is about the spinner rotates and counting spins while the user isn't really spinning his mouse/finger around it.

Either way, counts as a duplicate of https://github.com/ppy/osu/issues/8224, as the fix should probably be tracking the user movements to identify proper spins from "extremely tapping between 2 sides" and otherwise.

**Comment by bdach** [comment] 2020-08-01 18:51
Closing as duplicate.

**Closed by bdach** 2020-08-01 18:51 UTC
