### ISSUE TITLE
Mania longnotes don't work properly on my skin

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu#12490] opened 2021-04-19 20:48 UTC
**Describe the bug:** 

I imported my skin from stable to lazer, and the long notes don't show at all.
I tried exporting the .osk file and drag dropping to lazer but it didn't work either.
I also tried putting the long notes which are located in the assets folder to the root folder and changing the route in skin.ini but again it didn't work.

**Screenshots or videos showing encountered issue:** 

Lazer video: Here I do a comparison with another skin which I called "lazer" and then I switch to the one which I originally use with the name of "official".
Just to clarify, the problem doesn't happen when you change skins, even if you just started the game the skin will have the same problem.

https://user-images.githubusercontent.com/41755816/115297673-7a733100-a12a-11eb-8604-200be7a2a581.mp4

Stable video: Here's how my skin (the official) works on stable and should work on lazer

https://user-images.githubusercontent.com/41755816/115297695-80691200-a12a-11eb-8378-87091e2bb196.mp4

**Screenshot comparison:**

Lazer:
![screenshot lazer](https://user-images.githubusercontent.com/41755816/115298068-f5d4e280-a12a-11eb-9ca0-d52547fb06e9.jpg)
Stable:
![screenshot stable](https://user-images.githubusercontent.com/41755816/115298073-f7060f80-a12a-11eb-944b-a89442a0ce02.jpg)

**Skin**

https://drive.google.com/file/d/1JfPdTS9MD3foYgEKTLJywhuGulF_haXj/view?usp=sharing

**osu!lazer version:** 

2021.416.0

**Logs:**

[performance.log](https://github.com/ppy/osu/files/6338980/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6338981/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6338982/updater.log)
[database.log](https://github.com/ppy/osu/files/6338983/database.log)
[network.log](https://github.com/ppy/osu/files/6338984/network.log)

**Comment by bdach** [comment] 2021-04-19 21:13
Duplicate of #12057

The long note image in the attached skin is 40,000 (that is *forty thousand*) pixels high.

**Closed by bdach** 2021-04-19 21:13 UTC

**Comment by Gonzalo-Bruna** [comment] 2021-04-19 21:17
I see, I couldn't find the name of the mentioned issue because the title is not very self-describing
