### ISSUE TITLE
SDL3 issue: Cannot finish typing a word when using IME

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu#28274] opened 2024-05-21 06:56 UTC
### Type

Game behaviour

### Bug description

Pretty sure this is due to SDL3 messing up stuff somewhere, since it didn't break before the SDL3 release. I also noticed the [SDL3 upgrade PR](https://github.com/ppy/osu-framework/pull/6234) mentioned "minor IME regressions on windows", but I didn't expect it to be this bad.

Reproduction step:
1. Install the Vietnamese language pack on Windows, with the Vietnamese Telex IME (I haven't tried other IMEs yet, but this one reproduces the problem for me)
2. Enter the game, open chat, and type "thuwr" (which becomes "thử")
3. Press Space. Notice that the input is "stuck" and pressing Space doesn't finish typing the word
4. At this point, all non-IME input will be blocked (See video - I switched back to English (US), mashed my keyboard and nothing got through, even Backspace didn't work)

### Screenshots or videos

https://github.com/ppy/osu/assets/15729831/3b59ac67-310d-42a0-a45b-5096837ce312

### Version

2024.519.1

### Logs

[1716274049.auth.log](https://github.com/ppy/osu/files/15385768/1716274049.auth.log)
[1716274049.input.log](https://github.com/ppy/osu/files/15385769/1716274049.input.log)
[1716274049.network.log](https://github.com/ppy/osu/files/15385770/1716274049.network.log)
[1716274049.performance.log](https://github.com/ppy/osu/files/15385771/1716274049.performance.log)
[1716274049.runtime.log](https://github.com/ppy/osu/files/15385772/1716274049.runtime.log)
[1716274049.updater.log](https://github.com/ppy/osu/files/15385773/1716274049.updater.log)

**Comment by bdach** [comment] 2024-05-21 06:57
Maybe related to https://github.com/ppy/osu/issues/28261, maybe not. Let's track in one spot. We're reverting sdl3 temporarily right now anyhow.

**Comment by bdach** [comment] 2024-11-15 09:59
Reopening this since https://github.com/ppy/osu/issues/28261 got closed but [OP said it's still broken on discord](https://discord.com/channels/188630481301012481/1097318920991559880/1306913003484086312). cc @Susko3

**Comment by Susko3** [comment] 2024-11-15 10:10
Can reproduce on osu! SDL3. It's fixed by https://github.com/ppy/osu-framework/pull/6419 (but that PR has not made it into the latest release).

This will be fixed by the next osu-framework + osu update. You can set the environment variable `OSU_SDL3` to `0` for now.

**Closed by Susko3** 2024-11-15 10:10 UTC
Labels: type:input, priority:1, sdl issue
