### ISSUE TITLE
Click the circle to resume using mouse is broken when "Disable clicks during gameplay" turned on

### ISSUE THREAD

**Issue by ItzKeyYT** [ppy/osu#29984] opened 2024-09-24 13:56 UTC
### Type

Game behaviour

### Bug description

This bug effects people that uses mouse. This bug only works if the "Disable clicks during gameplay" option is turned on. When they pause the game and hit the continue button, it will tell the player to click the circle to resume playing. But clicking the circle using mouse won't work since the toggle is turned on.

### Screenshots or videos

https://github.com/user-attachments/assets/56858e4a-3baa-4c3f-a75b-c18929093d08

### Version

2024.906.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17115686/compressed-logs.zip)

**Comment by ominoussage** [comment] 2024-09-25 02:11
This isn't a bug. Clicking a circle is part of gameplay so why did you have the setting turned on in the first place? It's not like you use mouse click just to resume and go back to using keyboard, right? Because you could just use your keyboard for that.

Unless if you don't click circles with mouse, you shouldn't really turn that option on. That option is for players that use keyboard for clicking circles.

**Comment by peppy** [comment] 2024-09-25 02:59
Is the report here that the text just reads wrong? Because if that's the case, I dunno. I think people can figure it out.

**Comment by Y2nn1c** [comment] 2024-09-25 19:01
The option "Disable clicks during gameplay" ignores all inputs from your mouse while you play a map. 
This goes for breaks as well. The only time you can use them is before a play to skip ahead if the map allows it. 
But yes, this is not a bug it's just that you disabled your mouse buttons. Furthermore this will not be an issue since somebody who does not play with mouse buttons can just end the pause with a key input

**Comment by peppy** [comment] 2024-09-27 03:59
Closing as this seems to be a mis-report. @ItzKeyYT Feel free to leave further commentary if you think there's still an issue.

**Closed** 2024-09-27 03:59 UTC
Labels: area:gameplay

**Comment by ominoussage** [comment] 2024-09-27 14:05
I think the text should be "Press the orange circle to resume." if that option is turned on. Not really necessary but it feels right and avoids confusion for other people, if any.

**Comment by Y2nn1c** [comment] 2024-09-27 14:08
> I think the text should be "Press the orange circle to resume." if that option is turned on. Not really necessary but it feels right and avoids confusion for other people, if any.

Not relevant and this has never been a point of confusion before. 
Please make a new issue if this is really that important in your eyes.

**Comment by ominoussage** [comment] 2024-09-27 15:31
> > I think the text should be "Press the orange circle to resume." if that option is turned on. Not really necessary but it feels right and avoids confusion for other people, if any.
> 
> Not relevant and this has never been a point of confusion before. Please make a new issue if this is really that important in your eyes.

I'm just going to be making this exact same issue if I'm making a new one since that's what I'm talking about here, so no.
I know this doesn't affect everyone at all, including myself. Just gave a suggestion that could perhaps make it more looking right. 

Also, the text is relevant and is part of the main reason why this issue was made in the first place. That's exactly why @ItzKeyYT thought it was a bug since he expected that "Clicking the orange cursor" would work.
