### ISSUE TITLE
Hitsounds are delayed from the actual keystrokes. 

### ISSUE THREAD

**Issue by KrosisBH** [ppy/osu#9846] opened 2020-08-14 01:03 UTC
**Describe the bug:** 

I'm running Arch Linux on the 5.4.57-1-lts kernel (xfce DE if it matters). The hit sounds are very audibly off from the key press. Like 1/3 of a second. Changing the offset does nothing, and if I turn off the effects sound, I can play the game just fine with no timing issues. Of course, I'd rather play with hit sounds. 

I noticed that the audio uses BASS, which I believe is the same audio library as Quaver, a 4k/7k rhythm game also written in C#, which I've also had an issue with, but they've appeared to have resolved the issue, and I really have no more audio troubles from it anymore.
[A link to the issue for reference, was deemed fixed](https://github.com/Quaver/Quaver/issues/420)

**Screenshots or videos showing encountered issue:** 
https://streamable.com/5uy0rl

**osu!lazer version:**  2020.806.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5072076/runtime.log)
[performance.log](https://github.com/ppy/osu/files/5072077/performance.log)
[network.log](https://github.com/ppy/osu/files/5072078/network.log)
[database.log](https://github.com/ppy/osu/files/5072079/database.log)

**Comment by peppy** [comment] 2020-08-14 01:06
The said bass option you've referenced is already applied (it is only relevant when music is not already playing).

If you're still seeing latency, it is likely related to your linux setup. [Here's a thread](https://github.com/ppy/osu/issues/3800) with further troubleshooting (also a duplicate of your issue, so will close this one)

**Closed by peppy** 2020-08-14 01:06 UTC
