### ISSUE TITLE
Raw Input doesn't let me move my mouse (Windows)

### ISSUE THREAD

**Issue by xfln** [ppy/osu#11947] opened 2021-03-02 12:19 UTC
**Describe the bug:** 
as in title
**Screenshots or videos showing encountered issue:** 
https://user-images.githubusercontent.com/79914332/109647604-c7d71700-7b59-11eb-9160-adac37926cce.mp4
**osu!lazer version:** 
2021.226.0
**Logs:**

i dont think they're needed

**Comment by frenzibyte** [comment] 2021-03-02 12:26
Likely relevant to https://github.com/ppy/osu/issues/3364, potentially a duplicate.

**Comment by bdach** [comment] 2021-03-02 16:41
This issue does not have enough information to be actionable. Please provide:

* info about the input device being used (and whether you're using custom drivers)
* info about your current display settings (which mode you're using, whether cursor confine is on or off)
* another video with the frame graph visible (<kbd>Ctrl</kbd>+<kbd>F11</kbd> twice)

**Comment by smoogipoo** [comment] 2021-03-03 06:26
Closing as duplicate of #3364 .

**Closed by smoogipoo** 2021-03-03 06:26 UTC
Labels: missing details, type:input
