### ISSUE TITLE
Lazer won't start starting from version 2022.319.0

### ISSUE THREAD

**Issue by spookybear0** [ppy/osu#17353] opened 2022-03-19 19:09 UTC
### Type

Game behaviour

### Bug description

When game is started, lazer does not appear to start, but is seen active in background tasks using ~20% cpu usage.

When checking Event Viewer, I found this error:
```
Message: Cannot use file stream for [C:\Users\Collin\AppData\Local\osulazer\app-2022.319.0\osu!.deps.json]: No such file or directory
```

System specs:

OS: Windows 10 Home Version 10.0.19044 Build 19044 64 bit
CPU: Intel i5-9400
GPU: Radeon RX 570 8gb vram

Lazer was working yesterday on build 2022.314.0 then I installed the latest build this morning then this problem started. I'm not entirely sure why it is looking for `osu!.deps.json`, I have checked with another friend and this file is not included in their folder either but the game still launches.

### Version

2022.319.0

### Logs

[network.log](https://github.com/ppy/osu/files/8309904/network.log)
[performance.log](https://github.com/ppy/osu/files/8309905/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8309906/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8309907/updater.log)
[database.log](https://github.com/ppy/osu/files/8309908/database.log)

**Comment by bdach** [comment] 2022-03-19 22:37
the `osu!.deps.json` file missing error [has been mentioned a few times before](https://github.com/ppy/osu/discussions/15876#discussioncomment-1872005) and i have no clue what causes it but i don't believe it should be fatal / the cause of this error.

are you sure there are no more errors in event viewer that look related? logs don't really help here at all, there is no crash trace in sight.

**Comment by spookybear0** [comment] 2022-03-19 23:14
Unfortunately, that is the only thing that comes from ".NET Runtime". I saw those issues but I could not find any resolution. I'm not sure exactly what could be the problem.

**Comment by spookybear0** [comment] 2022-03-19 23:20
Starting the gaming again and looking through the Event Viewer I actually found another error, it reads:
```
Faulting application name: osu!.exe, version: 0.0.0.0, time stamp: 0x621b7cb2
Faulting module name: osu!.exe, version: 0.0.0.0, time stamp: 0x621b7cb2
Exception code: 0xc0000005
Fault offset: 0x00004e72
Faulting process id: 0x6a44
Faulting application start time: 0x01d83bbb3e7ff2a4
Faulting application path: C:\Users\Collin\AppData\Local\osulazer\osu!.exe
Faulting module path: C:\Users\Collin\AppData\Local\osulazer\osu!.exe
Report Id: 49e04f2e-fa9b-4f01-b5c5-8233b4ed170e
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by bdach** [comment] 2022-03-19 23:29
that looks more related and is a longstanding unknown-cause hardware-specific issue please read https://github.com/ppy/osu/issues/17354#issuecomment-1073129516 for more info.

going to close this as to not duplicate issues.

**Closed by bdach** 2022-03-19 23:29 UTC
Labels: missing details

**Comment by spookybear0** [comment] 2022-03-20 00:04
Issue has been resolved by updating graphics drivers.
