### ISSUE TITLE
Weird text rendering

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#6487] opened 2019-10-12 18:38 UTC
**Describe the bug:** 
There appears to be some issue with text in this release, letters are missing from some buttons and strings in the game.
Some areas are the beatmap options, the “Description” text in the beatmap info, the little label that says ranked, loved or WIP. On some maps, difficulty names are missing letters.

**Screenshots or videos showing encountered issue:** 
![71478987-413D-45C8-84EB-569EC9DCAC3B](https://user-images.githubusercontent.com/10524728/66706191-019d4880-eced-11e9-9cfc-813b3e232962.png)

**osu!lazer version:** 
2019.1011.0 TestFlight | iPadOS 13.2 Public Beta 2 

**Logs:** 
Not applicable

**Comment by jai-x** [comment] 2019-10-12 19:01
Possibly a duplicate of this issue in which the texture atlas size gets exceeded: https://github.com/ppy/osu/issues/1488

Would you be able to post your log files so we can confirm?

**Comment by ThatsNiceGuy** [comment] 2019-10-12 19:03
I don’t know how to get the logs from the TestFlight release, sorry.
(I don’t even think you actually can)

**Comment by peppy** [comment] 2019-10-22 06:26
Closing as duplicate.

**Closed by peppy** 2019-10-22 06:26 UTC
Labels: graphics, iOS
