### ISSUE TITLE
Adjust difficulty mod settings reset issue

### ISSUE THREAD

**Issue by Ceynou** [ppy/osu#13799] opened 2021-07-06 13:22 UTC
**Describe the bug:** 
In multiplayer, when you set the mod a first time and play a map, it works as intended, however, the settings are reset on the next map chosen, it basically acts like the mod isn't enabled, this doesn't happen in solo.

In solo, when you play a map matching the settings of the mod, those settings are unlocked, on the next map you play it will be the settings of the map and not the mod:

> Adjust difficulty: AR10
> Play a map with AR9
> Change is applied
> Play a map with AR10
> Well nothing happens it matches
> Play any map, it won't be AR10 anymore

**osu!lazer version:** 
2021.703.0

**Comment by bdach** [comment] 2021-07-07 20:26
Following today's attempts on tackling this and resulting discussion I tried again to try and fit my concept of having the user difficulty settings stored in a `float?` rather than how they are right now (both beatmap values and user values in one bindable), with as little changes as feasible, but I cannot find a way to do that without significant code reorganisation.

And I don't really see a good way of just serialising the `userChangedSettings` dictionary without marking it `[SettingsSourceAttribute]` (which is not desirable because those spawn user controls). `APIMod` would have to have a special type check for this one mod jammed in it.

The issue is that the mod settings are way too coupled to both the API serialisation logic on one side, and to the UI presentation logic on the other. Anything else than a simple bindable just does not work because both sides are relying on simple bindables. I tried to frankenstein two bindables into one via a weird delegating interface but what works for one side does not work for the other because of the tight coupling.

**Comment by peppy** [comment] 2021-07-08 01:52
@bdach we do have the ability to provide custom controls, which is the path I was considering taking for resolving this one. I think "hidden" variables may be able to return an empty drawable, to address your direct concern above?

**Comment by bdach** [comment] 2021-07-08 02:27
> we do have the ability to provide custom controls

While true, that ability is somewhat tied to the fact that the underlying setting has to be a bindable with a fixed inner data type. So if I change the serialisation side to use `IBindable<int?>`, the UI side changes to that, too. Which was undesirable as I tried to preserve all current behaviour.

> I think "hidden" variables may be able to return an empty drawable

I'm pretty sure `[SettingSource]`s also have titles/descriptions, so doing only that might not suffice.

**Closed** 2021-07-12 03:03 UTC
Labels: area:mods, priority:1
