### ISSUE TITLE
osu!lazer showing up in Task Manager but not running

### ISSUE THREAD

**Issue by freshleaf1095** [ppy/osu#17801] opened 2022-04-13 08:44 UTC
### Type

Game behaviour

### Bug description

I have just installed osu!lazer to my computer but after seeing the installer loading bar, there was nothing. I checked the Task Manager and it is showing that osu! is running but simply not displaying on the screen. I tried downloading different versions of osu!lazer and modifying the graphics settings but to no avail. The game also does **not** provide any logs for the error ( I cannot see nor find any logs folder within the osu!lazer folder); the only one I can find is through the Event Viewer in Windows. I am running Windows 10 version 21H2 build 19044.

### Version

2022.409.0

### Logs

![blob](https://user-images.githubusercontent.com/70712987/163136934-f4a03a8e-2c27-4216-a2d2-726c7c9f8608.jpg)

**Comment by peppy** [comment] 2022-04-13 08:45
Duplicate of https://github.com/ppy/osu/issues/17654.

Please check the mentioned overlays in that thread (medal.tv and overwolf) and add any information you can.

**Closed by peppy** 2022-04-13 08:45 UTC
