### ISSUE TITLE
"Perfect" combo displayed when score isn't an FC

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#15355] opened 2021-10-29 07:37 UTC
### Discussed in https://github.com/ppy/osu/discussions/15354

<div type='discussions-op-text'>

<sup>Originally posted by **Flamiii** October 29, 2021</sup>
The game thinks that I got a "perfect" combo when I didn't actually FC. I missed a slider tick on one of the sliders at about halfway through the map and it broke my combo, hence why I only have 737k score instead of having a score closer to 1 million. I set this score in a playlist and I got a 656x combo when an FC score is actually 1052x combo.

Playlist: https://osu.ppy.sh/multiplayer/rooms/114659
Beatmap: https://osu.ppy.sh/beatmapsets/782791#osu/1643641

My score:
![osu_2021-10-29_02-05-15](https://user-images.githubusercontent.com/74088315/139391987-7a25ebb5-e677-4fda-bc3f-563a276c7565.png)

Perfect score:
![osu_2021-10-29_02-13-05](https://user-images.githubusercontent.com/74088315/139391997-e9c1e0b8-1934-4500-99c0-0cf83f0006cf.png)

</div>

This is because the counter currently only checks for the score not having any misses. Should be able to look up max combo from either the online score info data or the `BeatmapDifficultyCache`.

**Comment by Joehuu** [comment] 2021-10-29 21:13
Duplicate of https://github.com/ppy/osu/issues/13238

**Closed by Joehuu** 2021-10-29 21:13 UTC
Labels: type:UI, area:results, priority:2
