### ISSUE TITLE
show if you hit the sliderend using held/not held

### ISSUE THREAD

**Issue by genericthing** [ppy/osu#9093] opened 2020-05-22 23:17 UTC
since there is no way to tell if you sliderbroke other than a combobreak, it would nice to show if you hit the sliderend by giving a judge rating of held if you held the slider for its full duration and not held if you didn't hold the slider for its full duration

the amount of helds/not helds should also be shown on the result screen to look at when your not playing

helds will also not affect accuracy but not getting all helds means no full combo

for issue #2106, the hide setting will also apply to held rating but will show if you got a not held rating

**Comment by bdach** [comment] 2020-05-22 23:54
Mostly duplicate of #8700

**Closed by bdach** 2020-05-22 23:54 UTC
