### ISSUE TITLE
[iOS] Keyboard input does not work after typing and then playing

### ISSUE THREAD

**Issue by Soruji** [ppy/osu#17513] opened 2022-03-28 19:16 UTC
### Type

Game behaviour

### Bug description

After typing in any place in the game (song select search bar, chat etc.), and then playing, no keyboard inputs register. Not the main buttons (Z and X), nor space to skip song intro or any other keyboard shortcuts work. 

The issue occurs if, after having typed something, you start a beatmap by tapping it with an Apple Pencil. It does not happen if you start a beatmap with the 'enter' key, a mouse click, or by tapping it with touch. It also does not happen if you deselect the bar you typed in before starting a beatmap. Even after finishing a beatmap, keyboard inputs do not register, but keyboard input works again if you select and deselect a bar (search bar, chat etc.).

I have been bumping into this issue for some time now, and have been able to consistently reproduce it.

Setup:
- iOS (iPadOS) 15.4 (also happens on 15.3.1)
- iPad Pro 11" (2nd gen, from 2020)
- Apple Pencil (2nd gen)
- Apple Magic Keyboard (cover)

### Screenshots or videos

Vids too big so here are some links. You might have to download them to watch them.
Here I show that it works, then the issue, and at last the 'fix':
https://drive.google.com/file/d/1Pi-8yXf-1tZAp0QOW2EmVWwvi1fCyDNs/view?usp=sharing

Here you can see how it looks from a camera's perspective:
https://drive.google.com/file/d/1Lbgv9nv3Xq94Dlfwe-INygFAcB34GeRN/view?usp=sharing

Note how a small Apple Pencil icon pops up from the bottom of the screen when I start playing. Maybe related to the issue?

Side note: I believe the freezing at the start of the beatmap is the same bug as referenced in #6200, but it only happens on some beatmaps.

### Version

2022.327.0

### Logs

[database.log](https://github.com/ppy/osu/files/8365569/database.log)
[network.log](https://github.com/ppy/osu/files/8365570/network.log)
[performance.log](https://github.com/ppy/osu/files/8365571/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8365572/runtime.log)

**Comment by peppy** [comment] 2022-03-29 03:26
I do recall reproing this before but didn't figure out the steps required to make it fail. This seems like the missing piece of the puzzle.

**Comment by frenzibyte** [comment] 2022-04-15 01:10
I've attempted to reproduce this on iOS Simulator with a bit of low-level adjustment to get physical keyboard simulated properly, but I may require an Apple Pencil simulation somehow to get this exact behaviour. 

For anyone looking to debug this, I will start off by looking at whether [the keyboard handler switching logic in `IOSGameHost`](https://github.com/ppy/osu-framework/blob/56fa81946850b314276a380d4e2e1a1057668e3c/osu.Framework.iOS/IOSGameHost.cs#L39-L63) is actually working properly, as it feels quite flaky and might have unintended effects with an Apple Pencil.

We can solidify that logic by using `GCKeyboard.coalesced != null`, but that's only available for iOS 14+, so we'll still require the old logic in place, potentially with more hacks as well...

**Comment by frenzibyte** [comment] 2022-04-15 01:12
> Side note: I believe the freezing at the start of the beatmap is the same bug as referenced in https://github.com/ppy/osu/issues/6200, but it only happens on some beatmaps.

That's not relevant to #6200 (I'm not even sure what #6200 is about anymore), this is an issue in single-threaded mode which was reported in https://github.com/ppy/osu/discussions/17361, and has since been resolved in the latest releases.

**Comment by frenzibyte** [comment] 2022-04-16 22:16
On a second check, this can actually break in very weird ways...

https://user-images.githubusercontent.com/22781491/163692928-b1aebe84-0027-4eb9-84a5-15f95185cd32.mp4

**Closed** 2022-05-14 18:23 UTC
Labels: type:input, platform:iOS, priority:1

**Comment by frenzibyte** [comment] 2022-05-14 18:24
I suppose you have confirmed this issue no longer occurs for you?

**Comment by Soruji** [comment] 2022-05-14 18:26
> I suppose you have confirmed this issue no longer occurs for you?

Yes, so I figured the issue has been resolved and thus I might as well close the issue

**Comment by frenzibyte** [comment] 2022-05-14 18:27
Thanks for the confirmation.
