### ISSUE TITLE
Background dim is disabled when in gameplay

### ISSUE THREAD

**Issue by serenityP** [ppy/osu#4231] opened 2019-02-09 10:52 UTC
**Describe your problem:** 
Background dim seldom is disabled randomly when in gameplay since the last update in my PC.
When I meet the BG with the main color of white and trigger this bug, I can not see notes clearly.
**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 
2019.131.0
**Logs:**

**Comment by HoLLy-HaCKeR** [comment] 2019-02-09 10:59
Duplicate of #4204?

**Comment by nyquillerium** [comment] 2019-02-12 05:20
Closing as a duplicate of https://github.com/ppy/osu/issues/4204

**Closed by nyquillerium** 2019-02-12 05:20 UTC
