### ISSUE TITLE
Must confirm exit from editor even if map is empty

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu#12587] opened 2021-04-26 20:44 UTC
**Describe the bug:** 
Accidentally clicking on edit instead of play in the main menu opens up new beatmap setup screen which if you want to exit immediately requires 3 clicks - either pressing <kbd>ESC</kbd> twice to first lose focus of automatically selected text box and then to exit, or navigating to File -> Exit via mouse, and then another click to actually confirm the exit.

**Screenshots or videos showing encountered issue:** 
(See that no metadata was entered but confirmation to save changes still appears)
![osu_2021-04-26_23-33-34](https://user-images.githubusercontent.com/11320483/116147140-04ea0080-a6e8-11eb-8f21-d4e4682e8478.png)

**osu!lazer version:** 
2021.424.0

**Comment by frenzibyte** [comment] 2021-04-26 20:44
Duplicate of https://github.com/ppy/osu/issues/10628

**Closed by frenzibyte** 2021-04-26 20:44 UTC
