### ISSUE TITLE
Score displaying `?` between the hundreds

### ISSUE THREAD

**Issue by MidKnightXI** [ppy/osu#24028] opened 2023-06-24 16:39 UTC
### Type

Game behaviour

### Bug description

I guess it has always been reported but I couldn't find the issue for it?

But for every scores, a `?` is getting displayed between the hundreds.

### Screenshots or videos

![image](https://github.com/ppy/osu/assets/35759490/069fe3fa-faa2-4f58-bde3-da7ca13b18ff)
![image](https://github.com/ppy/osu/assets/35759490/07949fe3-63e7-48e0-8681-572073fb3fed)

### Version

2023.621.0

### Logs

[database.log](https://github.com/ppy/osu/files/11857693/database.log)
[network.log](https://github.com/ppy/osu/files/11857694/network.log)
[performance.log](https://github.com/ppy/osu/files/11857695/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11857696/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11857697/updater.log)

**Comment by monochrome22** [comment] 2023-06-24 16:58
Duplicate of https://github.com/ppy/osu/issues/15135.

**Closed** 2023-06-24 17:10 UTC
