### ISSUE TITLE
Rotating group of sliders causes a severe drop in frames

### ISSUE THREAD

**Issue by 19peytonsmith** [ppy/osu#20291] opened 2022-09-14 02:55 UTC
### Type

Performance

### Bug description

Screenshot attached of the group of sliders I was trying to rotate, turns out that it causes my game to nearly crash in doing so. 

### Screenshots or videos

![Screenshot_1](https://user-images.githubusercontent.com/54728307/190048103-7f564789-e639-4d76-a977-7d78bd926dec.png)

### Version

2022.911.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9562229/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9562230/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9562231/updater.log)
[database.log](https://github.com/ppy/osu/files/9562232/database.log)
[network.log](https://github.com/ppy/osu/files/9562234/network.log)

**Comment by peppy** [comment] 2022-09-14 02:56
Duplicate of https://github.com/ppy/osu/issues/20208.

Please search first.

**Closed by peppy** 2022-09-14 02:56 UTC
