### ISSUE TITLE
Sudden Death mod causes screen flickering

### ISSUE THREAD

**Issue by Redapple-one** [ppy/osu#30809] opened 2024-11-21 14:55 UTC
### Type

Crash to desktop

### Bug description

When I am playing osu! and using **Sudden Death** mod.

### Screenshots or videos

https://github.com/user-attachments/assets/49ecb380-df14-4e93-9d48-1a0134cd8e7c

At the end of the video, you can see the screen flash(red)

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17847709/compressed-logs.zip)

**Comment by smoogipoo** [comment] 2024-11-21 16:33
Duplicate of https://github.com/ppy/osu/issues/30657

**Closed by smoogipoo** 2024-11-21 16:33 UTC
