### ISSUE TITLE
After reaching the end of a song in the editor the music keeps playing while paused

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu#14229] opened 2021-08-11 11:59 UTC
When reaching the end of a song in the editor if you then click to a previous point in the song the music keeps going make strange noises when you move forward or backward in the song if you unpause it fixes itself and places you where you were at in the song.

https://youtu.be/S7jrTGNzQFA

this was on the latest version of osu!lazer(2021.809.0)

[runtime.log](https://github.com/ppy/osu/files/6968157/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6968158/updater.log)
[database.log](https://github.com/ppy/osu/files/6968159/database.log)
[network.log](https://github.com/ppy/osu/files/6968162/network.log)
[performance.log](https://github.com/ppy/osu/files/6968164/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/6968165/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6968166/performance-update.log)

**Comment by peppy** [comment] 2021-08-11 12:17
Duplicate of https://github.com/ppy/osu/issues/14214, will be fixed in the next release!

**Closed** 2021-08-11 12:24 UTC
