### ISSUE TITLE
Tooltips for customisable mods don't show mod settings of completed plays

### ISSUE THREAD

**Issue by cupppu** [ppy/osu#8926] opened 2020-05-02 09:13 UTC
**Describe the bug:** 
- tooltip shows on bottom bar
![osu_2020-04-30_01-50-03](https://user-images.githubusercontent.com/7279624/80860015-89ea3780-8c97-11ea-80f2-8ddeb0a152fc.png)
- also shows on score screen after play
![osu_2020-04-30_01-48-13](https://user-images.githubusercontent.com/7279624/80860033-ba31d600-8c97-11ea-9624-3e6eb1248a85.png)
- but it stops showing once exit then return to score screen, as well as score standings
![osu_2020-04-30_01-49-56](https://user-images.githubusercontent.com/7279624/80860057-f107ec00-8c97-11ea-9469-1c05c5d52c1d.png)
![osu_2020-04-30_01-50-07](https://user-images.githubusercontent.com/7279624/80860073-07ae4300-8c98-11ea-9e2d-d32527af27fa.png)

**osu!lazer version:** 2020.429.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/4567378/database.log)
[network.log](https://github.com/ppy/osu/files/4567379/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/4567380/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/4567381/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/4567382/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/4567383/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4567384/runtime.log)

**Comment by smoogipoo** [comment] 2020-05-03 16:30
Duplicate of https://github.com/ppy/osu/issues/8569 (we have no storage for mod settings in legacy replays).

**Closed by smoogipoo** 2020-05-03 16:30 UTC
Labels: area:mods, type:UI
