### ISSUE TITLE
Editor crash with buggy slider repeats

### ISSUE THREAD

**Issue by m-sama** [ppy/osu#20876] opened 2022-10-23 00:11 UTC
### Type

Crash to desktop

### Bug description

Change slider velocity, adjust length, and add slider repeat will result in crash

osu!lazer did not generate any logs
Event Viewer log provided

### Screenshots or videos

https://user-images.githubusercontent.com/54123532/197366912-1c224f3a-50b7-4869-8970-2f000b53c212.mp4

### Version

2022.1022.0-lazer

### Logs

Log Name:      Application
Source:        .NET Runtime
Date:          10/22/2022 8:01:51 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-16TONKH
Description:
Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at osu.Game.Rulesets.Osu.Objects.Slider.UpdateNestedSamples()
   at osu.Game.Rulesets.Osu.Objects.Slider.CreateNestedHitObjects(CancellationToken cancellationToken)
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
   at osu.Game.Screens.Edit.EditorBeatmap.UpdateState()
   at osu.Game.Screens.Edit.EditorBeatmap.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass133_0.<abortExecutionFromException>b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.RunSingleFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-10-23T00:01:51.5453728Z" />
    <EventRecordID>123024</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-16TONKH</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: osu!.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at osu.Game.Rulesets.Osu.Objects.Slider.UpdateNestedSamples()
   at osu.Game.Rulesets.Osu.Objects.Slider.CreateNestedHitObjects(CancellationToken cancellationToken)
   at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken)
   at osu.Game.Screens.Edit.EditorBeatmap.UpdateState()
   at osu.Game.Screens.Edit.EditorBeatmap.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.processFrame()
--- End of stack trace from previous location ---
   at osu.Framework.Platform.GameHost.&lt;&gt;c__DisplayClass133_0.&lt;abortExecutionFromException&gt;b__0()
   at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal()
   at osu.Framework.Threading.Scheduler.Update()
   at osu.Framework.Threading.GameThread.processFrame()
   at osu.Framework.Threading.GameThread.RunSingleFrame()
   at osu.Framework.Platform.ThreadRunner.RunMainLoop()
   at osu.Framework.Platform.GameHost.windowUpdate()
   at osu.Framework.Platform.SDL2DesktopWindow.Run()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args)
</Data>
  </EventData>
</Event>

**Comment by WyvernX-YT** [comment] 2022-10-23 10:03
> ### Type
> 
> Crash to desktop
> ### Bug description
> 
> Change slider velocity, adjust length, and add slider repeat will result in crash
> 
> osu!lazer did not generate any logs Event Viewer log provided
> ### Screenshots or videos
> osu._xpaPjRS2mE.mp4
> ### Version
> 
> 2022.1022.0-lazer
> ### Logs
> 
> Log Name: Application Source: .NET Runtime Date: 10/22/2022 8:01:51 PM Event ID: 1026 Task Category: None Level: Error Keywords: Classic User: N/A Computer: DESKTOP-16TONKH Description: Application: osu!.exe CoreCLR Version: 6.0.222.6406 .NET Version: 6.0.2 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at System.Collections.Generic.List`1.get_Item(Int32 index) at osu.Game.Rulesets.Osu.Objects.Slider.UpdateNestedSamples() at osu.Game.Rulesets.Osu.Objects.Slider.CreateNestedHitObjects(CancellationToken cancellationToken) at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken) at osu.Game.Screens.Edit.EditorBeatmap.UpdateState() at osu.Game.Screens.Edit.EditorBeatmap.Update() at osu.Framework.Graphics.Drawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Platform.GameHost.UpdateFrame() at osu.Framework.Threading.GameThread.processFrame() --- End of stack trace from previous location --- at osu.Framework.Platform.GameHost.<>c__DisplayClass133_0.b__0() at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal() at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.processFrame() at osu.Framework.Threading.GameThread.RunSingleFrame() at osu.Framework.Platform.ThreadRunner.RunMainLoop() at osu.Framework.Platform.GameHost.windowUpdate() at osu.Framework.Platform.SDL2DesktopWindow.Run() at osu.Framework.Platform.GameHost.Run(Game game) at osu.Desktop.Program.Main(String[] args)
> 
> Event Xml: 1026 0 2 0 0 0x80000000000000 123024 Application DESKTOP-16TONKH Application: osu!.exe CoreCLR Version: 6.0.222.6406 .NET Version: 6.0.2 Description: The process was terminated due to an unhandled exception. Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') at System.Collections.Generic.List`1.get_Item(Int32 index) at osu.Game.Rulesets.Osu.Objects.Slider.UpdateNestedSamples() at osu.Game.Rulesets.Osu.Objects.Slider.CreateNestedHitObjects(CancellationToken cancellationToken) at osu.Game.Rulesets.Objects.HitObject.ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyInfo difficulty, CancellationToken cancellationToken) at osu.Game.Screens.Edit.EditorBeatmap.UpdateState() at osu.Game.Screens.Edit.EditorBeatmap.Update() at osu.Framework.Graphics.Drawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() at osu.Framework.Platform.GameHost.UpdateFrame() at osu.Framework.Threading.GameThread.processFrame() --- End of stack trace from previous location --- at osu.Framework.Platform.GameHost.<>c__DisplayClass133_0.<abortExecutionFromException>b__0() at osu.Framework.Threading.ScheduledDelegate.RunTaskInternal() at osu.Framework.Threading.Scheduler.Update() at osu.Framework.Threading.GameThread.processFrame() at osu.Framework.Threading.GameThread.RunSingleFrame() at osu.Framework.Platform.ThreadRunner.RunMainLoop() at osu.Framework.Platform.GameHost.windowUpdate() at osu.Framework.Platform.SDL2DesktopWindow.Run() at osu.Framework.Platform.GameHost.Run(Game game) at osu.Desktop.Program.Main(String[] args)

I see, an index issue, seems simple enough to fix.

**Comment by WyvernX-YT** [comment] 2022-10-23 10:11
To give more context, I have found that it happens when you make a small slider on 1/4 beat snap, change slider veloctity, then attempt to move the object via the timeline.

**Comment by peppy** [comment] 2022-10-24 05:18
@m-sama I can't seem to reproduce this. Could you please either provide the beatmap, or share the timing settings you have to make this happen?

**Comment by WyvernX-YT** [comment] 2022-10-24 05:20
> @m-sama I can't seem to reproduce this. Specifically, after changing the velocity you are somehow able to make the slider zero length, which should not be possible.
> 
> Could you please either provide the beatmap, or share the timing settings you have to make this happen?

I can, let me explain use 1/4 snap then make a slider with the end point just barely inside the slider whew you can change velocity then move it inwards all timings work

**Comment by Trung0246** [comment] 2022-10-26 08:50
> @m-sama I can't seem to reproduce this. Specifically, after changing the velocity you are somehow able to make the slider zero length, which should not be possible.
> 

> Could you please either provide the beatmap, or share the timing settings you have to make this happen?

Also followed the instruction and reliably replicate the bug.

[Weird - Crash bug (Trung0246).zip](https://github.com/ppy/osu/files/9867760/___.-.Crash.bug.Trung0246.zip)

Just rename .zip to .osz

**Comment by peppy** [comment] 2022-10-27 05:10
@Trung0246 I've tried to reproduce using your example beatmap but can't seem to:


https://user-images.githubusercontent.com/191335/198196872-f251aa1d-e5da-46a1-b87f-c662f3ae34a9.mp4

Can you explain where I'm going wrong?

**Comment by Trung0246** [comment] 2022-10-27 22:38
> @Trung0246 I've tried to reproduce using your example beatmap but can't seem to:
> 
> 
>  osu.2022-10-27.at.05.07.28.mp4 
> Can you explain where I'm going wrong?

Have to hold shift when dragging the slider end node, something like this.

https://user-images.githubusercontent.com/11626920/198411147-930c8812-83cd-476e-a4a9-4d1c47cd2030.mp4

**Comment by Trung0246** [comment] 2022-10-27 22:56
Just noticed there's a relevant issue https://github.com/ppy/osu/issues/10959

**Comment by peppy** [comment] 2022-10-28 03:28
Thanks, I completely overlooked that as it wasn't obvious that it was a requirement.

**Comment by peppy** [comment] 2022-10-28 03:38
This may be "fixed" on master due to #20828. I don't think shift-dragging a slider on the playfield should have changed anything in the first place. Can you explain how shift is changing anything here, because for me it does nothing (even without #20828 holding shift does not trigger the issue).

**Comment by Trung0246** [comment] 2022-10-28 03:55
> This may be "fixed" on master due to #20828. I don't think shift-dragging a slider on the playfield should have changed anything in the first place. Can you explain how shift is changing anything here, because for me it does nothing (even without #20828 holding shift does not trigger the issue).

Huh weird does hold shift then drag the slider end does not cause zero length on your end?

**Comment by peppy** [comment] 2022-10-28 05:30
I can reproduce on the latest release without holding shift. I'm not sure which change since the release has fixed the issue, but I can no longer reproduce on `master`.

What I'll do is close this issue for now, but please comment / reopen after the next release if you find a way to still reproduce the issue.

**Closed by peppy** 2022-10-28 05:30 UTC
Labels: ruleset:osu!, area:editor, type:reliability
