### ISSUE TITLE
Odd slider causes a big performance drop

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu#25707] opened 2023-12-09 01:57 UTC
### Type

Performance

### Bug description

The title and video are pretty self explanatory, I assume this is happening due to the odd way the slider is made to like accelerate midway. It happens both in gameplay, replay and editor, right-clicking the slider element in editor would send me to the main osu screen after some seconds of basically freezing. This is the first time this happens to me so I'm not sure since which version this issue is occuring.
I experimented this issue in this map https://osu.ppy.sh/beatmapsets/1746664#osu/3598398

### Screenshots or videos

https://github.com/ppy/osu/assets/37979533/bdc0d09a-30d0-4b1a-91b0-8ca96c7eea7f

### Version

2023.1130.0

### Logs

[database.log](https://github.com/ppy/osu/files/13622298/database.log)
[input.log](https://github.com/ppy/osu/files/13622299/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/13622300/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13622301/network.log)
[performance.log](https://github.com/ppy/osu/files/13622302/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/13622303/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/13622304/performance-update.log)

**Comment by plaguemask** [comment] 2023-12-09 05:49
Duplicate of https://github.com/ppy/osu/issues/21495

**Closed** 2023-12-09 06:11 UTC
