### ISSUE TITLE
Accuracy and cursor options

### ISSUE THREAD

**Issue by AKAMER9** [ppy/osu#12483] opened 2021-04-19 05:56 UTC
I think it could be nice if you could change the in game accuracy display between the current average (like it is right now), additive (like in step mania), and maybe subtracting too. I also think it would be nice to be able to use a cursor from any skin via changing it in the settings menu so if you like using a specific cursor you don't have to edit every skin you download.

**Comment by peppy** [comment] 2021-04-19 06:11
accuracy is duplicate of https://github.com/ppy/osu/issues/9885.
cursor is duplicate of (part of) https://github.com/ppy/osu/issues/4924

**Closed by peppy** 2021-04-19 06:11 UTC
