### ISSUE TITLE
Using Keyboard in Android

### ISSUE THREAD

**Issue by matthewanderson0607** [ppy/osu#8591] opened 2020-04-03 06:30 UTC
**Describe the bug:** 
I can't use my keyboard to register an account or sign in help me
I tried to tap the keyboard but the game didn't respond

**Comment by MTGPROD** [comment] 2020-04-03 09:51
Do you have a Samsung phone with the Samsung Keyboard ? Because i have the same problem with a Galaxy Note 9

**Comment by smoogipoo** [comment] 2020-04-03 10:37
Duplicate of https://github.com/ppy/osu/issues/8264

**Closed by smoogipoo** 2020-04-03 10:37 UTC

**Comment by matthewanderson0607** [comment] 2020-04-04 04:53
> Do you have a Samsung phone with the Samsung Keyboard ? Because i have the same problem with a Galaxy Note 9. 
> 
> And if you really want to use your keyboard on osu! NOW, you can install the SwiftKey keyboard. it is working.

Thanks for telling me, i'll try it now
