### ISSUE TITLE
Screen and mouse problem.

### ISSUE THREAD

**Issue by cardenasx** [ppy/osu#10931] opened 2020-11-20 23:31 UTC
**Describe the bug:** 

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 

**Logs:**
 the problem is the following, when you put the cursor out of the screen it gets lost causing that sometimes it is not able to find it or simply the screen ends up bogged down. I would like you to be able to fix it as soon as possible

![osu_2020-11-19_22-17-15](https://user-images.githubusercontent.com/32501216/99859546-55b86480-2b5e-11eb-8bb2-4363793349f0.jpg)

**Comment by Joehuu** [comment] 2020-11-20 23:33
Duplicate of https://github.com/ppy/osu/issues/10465. Please see the pinned issues or search before making more issues.

**Closed by Joehuu** 2020-11-20 23:33 UTC
