### ISSUE TITLE
Android chat issue

### ISSUE THREAD

**Issue by BoredCook** [ppy/osu#10527] opened 2020-10-16 07:38 UTC
Heya, just got the latest apk, using oxygen os 10.3.5 and fleksy keyboard wanted to type stuff in chat but it get hidden by the keyboard
![Screenshot_20201016-093308](https://user-images.githubusercontent.com/48600611/96226580-24fb7300-0f93-11eb-8500-136d9cc90b6c.jpg)
![Screenshot_20201016-093252](https://user-images.githubusercontent.com/48600611/96226586-27f66380-0f93-11eb-810a-a2493ccf6978.jpg)

**Comment by l3lackShark** [comment] 2020-10-16 11:39
Duplicate of #5284

**Closed** 2020-10-16 11:40 UTC
