### ISSUE TITLE
Music controller playlist is extremely laggy with many maps (80000+)

### ISSUE THREAD

**Issue by AlexCatDev** [ppy/osu#13579] opened 2021-06-19 12:26 UTC
I couldn't find this as an already reported issue, also this is my first issue ever i hope it's ok

[Video of issue](https://streamable.com/tkgaul)

Seems like every element in the playlist is rendered at the same time
And mouse events causes everything to refresh idk

I'd like to add even if I have chosen to show only a collection with 1 map in it, the same lag occurs

[runtime.log](https://github.com/ppy/osu/files/6680641/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6680642/updater.log)
[network.log](https://github.com/ppy/osu/files/6680643/network.log)
[performance.log](https://github.com/ppy/osu/files/6680644/performance.log)

**Comment by peppy** [comment] 2021-06-19 12:35
Duplicate of https://github.com/ppy/osu/issues/7767.

**Closed by peppy** 2021-06-19 12:35 UTC
