### ISSUE TITLE
Tablet driver doesn't detect tablet

### ISSUE THREAD

**Issue by floriankorstanje** [ppy/osu#12159] opened 2021-03-23 22:21 UTC
**Describe the bug:** 
When I launch osu, it shows a notification with the error: `DeviceIOException: Unable to open HID class device (OK).`
It also says there is no tablet detected while there is one connected.

**Screenshots or videos showing encountered issue:** 
Error:
![osu_2021-03-23_23-19-25](https://user-images.githubusercontent.com/66821749/112226263-3a558700-8c2e-11eb-9a74-3e429cc0c66e.jpg)
No tablet detected:
![osu_2021-03-23_23-23-10](https://user-images.githubusercontent.com/66821749/112226697-c9629f00-8c2e-11eb-80ee-b74ec971f268.jpg)

**osu!lazer version:** 
2021.323.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6193042/database.log)
[network.log](https://github.com/ppy/osu/files/6193043/network.log)
[performance.log](https://github.com/ppy/osu/files/6193044/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6193045/runtime.log)

I don't know if this is helpful, but I'm using Ubuntu 20.04.2 LTS as my OS

Tablet is recognized by xsetwacom:
![Screenshot from 2021-03-23 23-24-50](https://user-images.githubusercontent.com/66821749/112226819-fa42d400-8c2e-11eb-831e-7234c674ad4b.png)

I use the digimend drivers for my tablet https://github.com/DIGImend/digimend-kernel-drivers

**Comment by jai-x** [comment] 2021-03-23 23:06
Duplicate of https://github.com/ppy/osu/issues/12116

Please read the OpenTabletDriver FAQ for a resolution: https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#the-driver-fails-to-open-the-tablet-deviceioexception

Please search for existing issues before opening a new one.

**Closed by jai-x** 2021-03-23 23:06 UTC
