### ISSUE TITLE
Spinner filling animation is shifted down compared to stable

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu#9894] opened 2020-08-17 18:42 UTC
**Describe the bug:** The spinner filling animation isn't in the same position as stable in this skin. I waited posting this because i thought it was gonna be fixed by #9763 , but it didn't. You can see the white dots not lining up on the gray ones beyond.

**Screenshots or videos showing encountered issue:** 
Stable:
![Screenshot_2](https://user-images.githubusercontent.com/53081750/90431041-b69c5080-e0c8-11ea-9180-07acf0504cf2.png)
Lazer:
![osu_2020-08-17_20-25-22](https://user-images.githubusercontent.com/53081750/90431071-c451d600-e0c8-11ea-9fba-b1e490248cd0.jpg)

**osu!lazer version:** 2020.814.0

**Comment by bdach** [comment] 2020-08-17 18:43
Please attach the skin.

**Comment by Theighlin** [comment] 2020-08-17 18:50
I actually wanted to post it right away but it weighted too much for github. I found the link i got it from https://drive.google.com/file/d/1euE-UtCRU6S2D69MA2LRDW8StroFVBP4/view

**Comment by peppy** [comment] 2020-08-17 21:12
From screenshots provided it's hard to tell what you're pointing at. Could you please highlight the issue in your screenshots?

**Comment by bdach** [comment] 2020-08-17 21:14
I think the expectation is for these to line up:

![2020-08-17-231250_219x193_scrot](https://user-images.githubusercontent.com/20418176/90445106-6c729980-e0df-11ea-94ee-9a38533bfbf8.png)

**Comment by lanpai** [comment] 2020-08-18 07:37
The UI is centered as intended, the skin seems to be misaligned. If it were originally aligned in osu!stable, maybe there's an issue in stable?

Both textures placed on top of each other in an image editor (both are the same resolution)
![image](https://user-images.githubusercontent.com/40352447/90484388-f2481200-e0ea-11ea-9f09-a5ded011f101.png)

**Comment by bdach** [comment] 2020-08-18 07:43
Whether or not there's an issue in stable it should probably be replicated for legacy spinners as clearly users expect backwards compatibility.

**Comment by smoogipoo** [comment] 2020-08-18 09:42
Seems like a duplicate of https://github.com/ppy/osu/issues/9742 ?

**Comment by bdach** [comment] 2020-08-18 09:48
Not sure if it's an exact duplicate (offset seems much larger in linked issue) but we might as well track in one place, I suppose? Might be a separate issue for old and new style, not that I checked.

**Closed** 2020-08-30 03:09 UTC
Labels: area:skinning, ruleset:osu!
