### ISSUE TITLE
Missing metadata fields

### ISSUE THREAD

**Issue by UndeadCapulet** [ppy/osu#12022] opened 2021-03-17 01:10 UTC
Current setup panel is missing several important metadata fields:
UnicodeArtist, UnicodeTitle, Source, Tags, and also perhaps the website genre tags buttons if those are intended to be included.
https://puu.sh/HpONa/dd1dd821bf.png vs. https://puu.sh/HpONr/7965ebf8c8.png

**Comment by frenzibyte** [comment] 2021-03-17 01:12
Closing as a duplicate of https://github.com/ppy/osu/issues/2434, which tracks implementing everything remaining for the song setup screen.

**Closed by frenzibyte** 2021-03-17 01:12 UTC
