### ISSUE TITLE
Dynamic Collection

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#12616] opened 2021-04-29 03:34 UTC
**Describe the new feature:** 

> Allow collection to have "tags" that will add beatmaps with the correct tag into the collection automatically. This should make collection organization much easier

**Proposal designs of the feature:** 

> Allow player to add tags for a collection, check and add beatmaps into the collection when a new beatmap detected

**Comment by peppy** [comment] 2021-04-29 03:45
Duplicate of https://github.com/ppy/osu/issues/4071. Please search first.

**Closed by peppy** 2021-04-29 03:46 UTC
