### ISSUE TITLE
darken long notes when they aren't being held properly

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu#10612] opened 2020-10-29 04:24 UTC
darkening long notes when not being held gives feedback to the player that they are not holding the long note properly 
currently, long notes don't darken in any case

**Comment by enoslayd** [comment] 2020-10-29 05:30
#8594

**Comment by smoogipoo** [comment] 2020-10-29 05:33
Closing as duplicate of https://github.com/ppy/osu/issues/8594

**Comment by igontusuwu** [comment] 2020-10-29 05:34
yea, i think
i'll add suggestions to the other post

**Closed by smoogipoo** 2020-10-29 05:33 UTC
Labels: area:gameplay, ruleset:osu!mania
