### ISSUE TITLE
Cursor trail artifacts in new update

### ISSUE THREAD

**Issue by Phippe** [ppy/osu#8571] opened 2020-04-02 13:04 UTC
**Describe the bug:** In the new version, the cursor trail has some weird white artifacts as seen in the video. Skin used was [Seouless' Momoko Skin](http://ck1t.ru/s-621). Happens on PC and iPhone and both during gameplay and replay.

May be similar to #6042, but in my case it has been working just fine until today.

**Screenshots or videos showing encountered issue:** [fist half old version, second half current version](https://streamable.com/o6uly8) (video made on the mobile version)

**osu!lazer version:** 
2020.402.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/4421155/runtime.log) (logs obviously from PC)

**Comment by mcendu** [comment] 2020-04-02 13:06
Dupe of #8547 (fixed)

**Closed** 2020-04-02 13:06 UTC
