### ISSUE TITLE
Beatmap ranking status not updating in song select

### ISSUE THREAD

**Issue by minasminas** [ppy/osu#14107] opened 2021-08-02 12:55 UTC
If I download a beatmap and the maps ranking status gets updated (for example qualified -> ranked), the beatmap will still show as qualified in song select and not update to ranked.

Not 100% sure if this is a bug or just not implemented yet.

**Comment by jai-x** [comment] 2021-08-02 13:00
Duplicate of https://github.com/ppy/osu/issues/4823 I think?

**Comment by frenzibyte** [comment] 2021-08-02 13:02
I wouldn't really consider this a duplicate assuming that one beatmap could change status while on the same exact version.

Would be rather a duplicate to https://github.com/ppy/osu/issues/11922. I presume there'll be some background component checker that updates such online status.

**Closed** 2021-08-02 13:01 UTC
Labels: area:beatmap, type:online

**Comment by greenmg2003** [comment] 2022-02-27 04:58
This also happened to me on the 2022.226.0 version. I re-downloaded the beatmap (Time Machine) via in-game download and this happened (Downloaded it when the map got Qualified, then after many versions, it still shows "Qualified" like the image below
![image](https://user-images.githubusercontent.com/65149680/155868798-d20c29df-29ee-4251-b298-eed8517cdf78.png)
Video: https://streamable.com/hazyzx
