### ISSUE TITLE
Performance Observations (Draw Calls and Memory Usage)

### ISSUE THREAD

**Issue by samueldong-us** [ppy/osu#3252] opened 2018-08-19 08:37 UTC
I was trying out the visualization map The Empress by Plutia, which is obviously not a normal use case, but did stress test the program well. With auto mode, it runs at lower than 1FPS and the rendering of the map continues long after the song ends. With no-fail, it runs at 15FPS normally and can drop further.

While I don't actually know how this is done in code, there are a few observations I made using RenderDoc and task manager. For reference, I am on a laptop with an i7-6700HQ and a Geforce GTX 1070.

At its peak, I saw 7k+ draw calls, mostly drawing quads for the sprites I assume. Each call also called glBufferSubData. I assume this is a consequence of the polymorphic render function common to object-oriented architectures. The redundant state changes and especially the draw call have CPU overhead, which is most likely bottlenecking the GPU. Batching will mostly solve this issue, and architecturally, it should only require modifying the sprite drawing function to build a pseudo command list. Having the data copied at once and called with a minimal number of draw calls should reduce CPU usage by a lot. Transparency is automatically handled by the order in which the sprites are already being drawn.

I assume the key difference between auto and no-fail is the scrubbing and playback speed features. The draw calls are pretty much the same, so it must be somewhere else. Not sure what the reasoning behind the discrepancy is though.

The load time of the map does seem a bit high, taking almost 20 seconds. I noticed that osu was taking 2GB of RAM extra when loading the map and rose to 4.5GB of RAM by the end. At 20,000 hit objects, that is an average of 100-200KB per hit object, which seems strange (I don't know if the growth is due to lack of garbage collection or streaming in the rest of the data). The RAM usage doesn't go away when a song is over, but it does seem to drop whenever the RAM is used to the point where there is no more room left, so maybe garbage collection is the culprit.

I apologize that this isn't that organized and may not be that helpful. My background is in computer graphics, so the only thing I am sure of is that 7k+ draw calls for a mostly homogeneous rendering workload is excessive. With most draw calls being glDrawElements(6), it is obvious that it comes from the sprite rendering code, but then again, approach circles are drawn in one batch, leading me to believe this might have been done for alpha blending reasons, though the framebuffer blending pass is ordered by the triangle order passed in, meaning separate draw calls are not necessary.

Given the observations, I doubt the rendering code is necessarily the bottleneck, but the processing time spent on submitting rendering commands can definitely be reduced significantly, on the order of one thousandth I believe. As for the other issues (load time, RAM usage, Auto speed discrepancy),  I don't what the code is doing, but I do believe it would be worth checking out.

**Comment by AdmiralSam** [comment] 2018-08-19 13:56
The beatmap link is [here](https://osu.ppy.sh/beatmapsets/328780/#osu/729138), but it is a visualization map, so it does have 100's of objects on screen at once. For normal maps the number of draw calls should be around 100-200. It definitely isn't representative of normal gameplay, but the old client was able to play it without as much issue. The song is only circles and a couple spinners, with 20,000 hit objects total. The memory usage can get high enough to freeze up the game after playing it a few times in a row though.

I see what you are saying, it is pretty limiting that you have to switch between additive and alpha blending for so many objects, which would limit performance a bit, but the bottleneck is unlikely to rendering/driver overhead. The problem is definitely elsewhere.

**Comment by AdmiralSam** [comment] 2018-08-19 14:06
About that additive and alpha blending switch, have you considered using premultiplied alpha? If the blending function is the only state change that is needed due to shadows and glow, then maybe the rest can be batched as usual.

**Comment by peppy** [comment] 2018-08-19 14:38
it’s not just blending. see the shader uniform changes in drawEdgeEffect(). it needs some deep logic changes.

**Comment by AdmiralSam** [comment] 2018-08-19 16:00
With all of the different shaders needing different uniforms, it does seem to be more challenging to batch most of the draw calls. The only reasonable solution would be a form of ubershader with the changing uniforms in a buffer that can be looked up. I also noticed the changing scissor rectangle which would prevent batching. Does that actually serve a purpose during gameplay, or is it the result of sharing code between UI elements and gameplay elements?

In the end it is a lot of work for not the highest impacting gain since there are other priorities or bottlenecks. I guess I just like to think about things like this because it is my area of focus. Architecturally, polymorphic hierarchies are definitely not GPU/driver friendly, and to really squeeze out the most performance possible requires some context-specific code, like treating gameplay as a special case. I do believe this can be done without turning the code into a mess, but might require restructuring of the framework.

I guess at this stage in development it may not be worth it, but I guess it is food for thought.

**Comment by CSharpProgramming** [comment] 2018-08-27 23:06
I might be totally retarded but from my experience mapping a buffer yields slightly better performance than glBufferSubData with opentk, i thought i'd just add that to the conversation

**Comment by peppy** [comment] 2018-08-27 23:34
We are aware of that one. You’re more than welcome to make the change and do some profiling on it!

**Comment by peppy** [comment] 2018-08-28 00:01
If you are interested in looking into draw thread performance, here's a starting point (song select):

![image](https://user-images.githubusercontent.com/191335/44692939-3ece5900-aaa0-11e8-9e83-0d76cc8dfee5.png)

- Time in `SwapBuffers` being this is (in a non-vsync execution) can be related to the currently high number of batch interruptions (due to edge effects and texture bind switches)
- `GenerateMipmap` is called on any texture upload. This is hugely expensive as it is mipmapping the full 4096x texture atlas each time. We should consider moving this to a CPU operation or investigating regional mipmap generation, if that's a thing. If neither of these are feasible, we may need to batch texture uploads more (ie. in the case of each panel at song select loading individually and being subsequently uploaded).

I have some ideas on how to improve song select specifically as it is very texture hungry for on-screen beatmap panels. That (along with mipmap improvements) will be one of my focus areas over the coming weeks as time is available. I won't be looking at individual gl function overheads such as `BufferSubData` just yet, so this is open for grabs at the moment.

**Comment by peppy** [comment] 2018-08-28 01:27
Mipmapping is highly beneficial to improve the look of fonts and images when being scaled more than around 20% (osu! does a lot of scaling). It also allows for fine-grained control over sharpening during downwards scaling via the third paramter of `texture2D` (fs), see `sh_TextureRounded`.

Padding is accounted for (I believe there may be some cross-talk at very low mipmap levels, but this is not visible in normal use).

We may be able to disable mipmapping on a per-atlas level. A larger problem is that song select loads the full beatmap background just to display a thin slice of it, basically requiring a new 4096x atlas texture per 1-4 beatmap panels (this needs to be confirmed, since debug output doesn't seem to be showing this but i'm 99% sure it's happening).

**Comment by peppy** [comment] 2018-08-28 01:31
As an correction, atlasing is bypassed for beatmap backgrounds, luckily (see `LargeTextureStore`). Mipmapping is still applied, so there's a potential for further investigation there, but I think the quality loss will require a manual replacement implementation if it was to be disabled.

**Comment by peppy** [comment] 2018-08-28 01:44
For a visual example of why we have mipmapping on:

![image](https://user-images.githubusercontent.com/191335/44695680-4c3f0f80-aaaf-11e8-8519-1456c57e21a2.png) ![image](https://user-images.githubusercontent.com/191335/44695668-3d585d00-aaaf-11e8-9d8f-fa17795c4898.png)

![image](https://user-images.githubusercontent.com/191335/44695607-f66a6780-aaae-11e8-85e5-29cae3671f5a.png) ![image](https://user-images.githubusercontent.com/191335/44695598-ece0ff80-aaae-11e8-97a1-ca202ead34fe.png)

**Comment by Wieku** [comment] 2018-09-30 01:35
About draw calls on The Empress, i've got 54629 calls near the beginning, so at the most intense part i suppose it will be around 120k+. I've also noticed that there are a lot of buffers allocated.
There's a RenderDoc's [dump](https://img.wieku.me/18/lazer.rdc) if anyone is interested.

**Comment by peppy** [comment] 2018-09-30 23:18
what is “The Empress”? are you sure you’re in the right place?

**Comment by Wieku** [comment] 2018-09-30 23:36
Yes, it's the beatmap mentioned above.

**Comment by peppy** [comment] 2018-09-30 23:59
The high draw calls is likely a bug. The high buffer allocations are sliders, which are pending an optimisation to use a buffer stack for this.

**Comment by peppy** [comment] 2019-07-18 04:48
As an update to this, renderbuffer allocation has been resolved via https://github.com/ppy/osu/pull/5383. We still need to address high draw calls (and excessive VBOs) via further optimisations.

**Comment by peppy** [comment] 2022-01-22 06:22
Most of this has been resolved either via pooling or other optimisations. There are also still planned improvements framework side with VBO management, which will come in the near future.

**Closed by peppy** 2022-01-22 06:22 UTC
Labels: type:performance, area:gameplay
