### ISSUE TITLE
Mouse input stopping at start

### ISSUE THREAD

**Issue by Alexramos0988** [ppy/osu#11711] opened 2021-02-09 05:13 UTC
while launching osu!lazer, the mouse becomes unresponsive at the start. Unknown of how this happens but the mouse input becomes disable regardless if its a trackpad or wire/wirelessmouse connected. Issue occurred while opening osu!lazer from desktop shortcut.

Version 2021.205.1

[performance.log](https://github.com/ppy/osu/files/5949015/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5949016/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5949017/updater.log)
[database.log](https://github.com/ppy/osu/files/5949018/database.log)
[network.log](https://github.com/ppy/osu/files/5949019/network.log)

**Comment by peppy** [comment] 2021-02-09 06:23
Have you tried toggling raw input to see if that helps at all?

**Comment by Alexramos0988** [comment] 2021-02-09 06:33
Yes I have. I have enabled raw input and disabled it. The mouse seems to be disabled at start. Closing and reopening the app fixes it. The issue also occurs in game as well after completing a map or watching a replay. The mouse goes off screen and becomes disabled.

**Comment by peppy** [comment] 2021-02-09 06:37
Could you try disabling the "Confine mouse cursor to window" setting?

![20210209 153729 (dotnet)](https://user-images.githubusercontent.com/191335/107325214-bbc4e000-6aec-11eb-8786-eb3915d4e80a.png)

**Comment by smoogipoo** [comment] 2021-02-19 01:05
99.999% going to be a dupe of https://github.com/ppy/osu/issues/11813, which is tracked framework-side in https://github.com/ppy/osu-framework/issues/4086

**Closed by smoogipoo** 2021-02-19 01:05 UTC
Labels: missing details, type:input
