### ISSUE TITLE
Searching settings will show the categories of hidden settings.

### ISSUE THREAD

**Issue by Mou-Ikkai** [ppy/osu#21039] opened 2022-10-31 19:55 UTC
### Type

Game behaviour

### Bug description

I was trying out the search feature for the settings, then I discovered that, even though the setting itself is hidden, the setting search showed the categories for the phone Notch setting, though usually if you have an invalid search, it shows no categories at all.

### Screenshots or videos

https://user-images.githubusercontent.com/45863583/199098444-65f4869a-cfa7-4fa8-afd8-e3e33b128531.mp4

### Version

2022.1031.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/9904636/performance.log)
[updater.log](https://github.com/ppy/osu/files/9904637/updater.log)
[input.log](https://github.com/ppy/osu/files/9904638/input.log)
[database.log](https://github.com/ppy/osu/files/9904639/database.log)
[runtime.log](https://github.com/ppy/osu/files/9904640/runtime.log)
[network.log](https://github.com/ppy/osu/files/9904641/network.log)

**Comment by bdach** [comment] 2022-10-31 20:01
Duplicate of #18003

**Closed by bdach** 2022-10-31 20:01 UTC
