### ISSUE TITLE
Beatmap visual and audio settings are not editable during play

### ISSUE THREAD

**Issue by akiya-nagatsuka** [ppy/osu#25018] opened 2023-10-05 10:49 UTC
### Type

Game behaviour

### Bug description

Not possible to change the visual and audio settings applied to specific beatmap after the beatmap playing has started and pressed the pause though It's possible in osu! classic.

### Screenshots or videos

osu!lazer visual and audio settings are shown on beatmap loading:
<img width="410" alt="Screenshot 2023-10-05 at 19 20 41" src="https://github.com/ppy/osu/assets/38129679/451a19b3-56a3-428e-88dd-270374543135">

osu! classic visual settings
![image](https://github.com/ppy/osu/assets/38129679/d77b1934-915c-405c-96d0-5c8762e8f3e1)

### Version

2023.924.1

### Logs

N/A

**Comment by bdach** [comment] 2023-10-05 10:54
Duplicate of https://github.com/ppy/osu/issues/3853

**Closed by bdach** 2023-10-05 10:54 UTC

**Comment by akiya-nagatsuka** [comment] 2023-10-05 10:59
Thank you @bdach. Not found this issue in the list.
