### ISSUE TITLE
Incorrect hit result showing during replay rewind

### ISSUE THREAD

**Issue by FeatherPrince** [ppy/osu#17567] opened 2022-03-31 04:35 UTC
### Type

Game behaviour

### Bug description

At first, game shows hit100, but there is no sound and after the circle fades away it shows hit0
I seem to have misstimed and not hit the circle at all but it still showed hit100
And I am pretty positive that displaying both hit100 and hit0 on the same hit is not intended

### Screenshots or videos

![Screenshot (56)](https://user-images.githubusercontent.com/69608110/160974840-969c0474-1949-4239-8c1e-f879fccd7697.png)

https://user-images.githubusercontent.com/69608110/160976687-17352f82-ecff-4d83-8c39-d0d429d75ac1.mp4

### Version

2022.327.0-lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8385932/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8385933/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8385934/updater.log)
[database.log](https://github.com/ppy/osu/files/8385935/database.log)
[network.log](https://github.com/ppy/osu/files/8385936/network.log)

**Comment by peppy** [comment] 2022-03-31 04:36
Please attach the replay.

**Comment by peppy** [comment] 2022-03-31 04:39
Also please confirm that this doesn't happen without rewinding. It looks to potentially be an issue with rewind logic, if anything.

**Comment by FeatherPrince** [comment] 2022-03-31 04:43
It just shows hit0 if i don't rewind
![image](https://user-images.githubusercontent.com/69608110/160978093-5f049712-81d9-4007-8843-9f2ed045ac5a.png)
and i can't exactly send the replan through github

**Comment by bdach** [comment] 2022-03-31 04:45
> and i can't exactly send the replay through github

you can. hint: zip is a supported extension.

**Comment by FeatherPrince** [comment] 2022-03-31 04:45
[Feather Prince playing Seiryu - Critical Crystal (Priti) [Yuki's Another].zip](https://github.com/ppy/osu/files/8386069/Feather.Prince.playing.Seiryu.-.Critical.Crystal.Priti.Yuki.s.Another.zip)

**Comment by FeatherPrince** [comment] 2022-03-31 04:48
Technically i could send it as a png because the information that's kept in the file doesn't change, my bad.

**Comment by FeatherPrince** [comment] 2022-03-31 04:52
[Feather Prince playing Seiryu - Critical Crystal (Priti) [Yuki's Another].zip](https://github.com/ppy/osu/files/8386092/Feather.Prince.playing.Seiryu.-.Critical.Crystal.Priti.Yuki.s.Another.zip)

**Comment by smoogipoo** [comment] 2022-03-31 05:21
Sounds like a duplicate of https://github.com/ppy/osu/issues/17413 then.

**Closed by smoogipoo** 2022-03-31 05:21 UTC
Labels: ruleset:osu!, area:replay
