### ISSUE TITLE
Black area around icons and fonts

### ISSUE THREAD

**Issue by ZeroAurora** [ppy/osu#6118] opened 2019-09-15 01:45 UTC
**Describe the bug:** 
The icons and fonts look strange.
**Screenshots or videos showing encountered issue:** 
![截图_2019-09-15_09-22-51](https://user-images.githubusercontent.com/25359455/64915545-0e855580-d79c-11e9-8cd9-211f3e059463.png)
![截图_2019-09-15_09-23-52](https://user-images.githubusercontent.com/25359455/64915546-0e855580-d79c-11e9-9ea4-8c384b99a53b.png)
**osu!lazer version:** 
local build (tag 2019.913.0)
(The bug has existed since tag 2019.823.0)
**Logs:** 
[performance.log](https://github.com/ppy/osu/files/3613318/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3613319/runtime.log)

**Comment by MeguMario** [comment] 2019-09-15 03:54
it's also happen on Windows too, can you provide the specs?
![image](https://user-images.githubusercontent.com/44724359/64916379-0e3e8780-d7a7-11e9-8132-f613ac26cfa1.png)
![image](https://user-images.githubusercontent.com/44724359/64916380-18608600-d7a7-11e9-8534-ef6d6995db98.png)

**Comment by sr229** [comment] 2019-09-15 08:21
Also happens to me: MSI CX-640 (Intel i7 / Intel HD Graphics 3000)

![image](https://user-images.githubusercontent.com/14976516/64918720-eb2acc80-d7d4-11e9-9899-b2c29700408d.png)

**Comment by Joehuu** [comment] 2019-09-15 08:37
Duplicate of #5199.

**Closed by Joehuu** 2019-09-15 08:37 UTC

**Comment by iiSaLMaN** [comment] 2019-09-20 09:00
Correcting the above comment, this is a duplicate of https://github.com/ppy/osu/issues/5885.
