### ISSUE TITLE
Non-disappearing hitcircle causes map to not end

### ISSUE THREAD

**Issue by fangerm** [ppy/osu#2267] opened 2018-03-21 16:20 UTC
While playing a map in osu!standard, a hitcircle didn't fully disappear. It caused a 1s lag spike and left behind a ring (approach circle?) that stayed for the rest of the play, and the game didn't continue to the results screen at the end of the map.

https://i.imgur.com/vWsYCkV.png

**Comment by peppy** [comment] 2018-03-21 16:21
Duplicate of #1591.

**Closed by peppy** 2018-03-21 16:21 UTC
