### ISSUE TITLE
Spinner Scratch Disc (unsure if intentional or not)

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu#12338] opened 2021-04-08 11:02 UTC
You can "spin" a spinner quite well by turning it like a scratch disc. Not sure if this is intended behaviour, but you can't do this in stable.

LAZER:
https://user-images.githubusercontent.com/30021847/114015512-ac9aae00-9861-11eb-99d3-a2dacc1f5367.mp4

STABLE:
https://user-images.githubusercontent.com/30021847/114015919-2f236d80-9862-11eb-8f3e-8582a7bcbf7d.mp4

osu!lazer version: 2021.407.1
osu!stable version: b20210316

**Comment by frenzibyte** [comment] 2021-04-08 11:04
Duplicate of https://github.com/ppy/osu/issues/8224.

**Closed by frenzibyte** 2021-04-08 11:04 UTC
