### ISSUE TITLE
Cursor stuck in bottom right corner of screen

### ISSUE THREAD

**Issue by blackwiz1** [ppy/osu#9465] opened 2020-07-08 21:28 UTC
Upon launching osu!lazer, the cursor becomes stuck in the very far bottom right corner, and will not respond to any mouse input while in the osu!lazer tab. Attempting to swap tabs (I'm using Mac) frees the cursor, but going back to osu!lazer relocks the cursor. I think it might have something to do with being in fullscreen, but I'm not sure how to exit fullscreen without interacting with any sort of menu.

**Comment by bdach** [comment] 2020-07-08 21:30
Duplicate of #8280

Please use <kbd>Alt</kbd>+<kbd>Enter</kbd> to cycle display modes.

**Closed by bdach** 2020-07-08 21:30 UTC
