### ISSUE TITLE
Slider reverse arrows are dimmer than stable

### ISSUE THREAD

**Issue by floppypp** [ppy/osu#30966] opened 2024-12-04 02:26 UTC
### Type

Cosmetic

### Bug description

Really throws off reading.

### Version

2024.1115.3

### Logs

[totally real a real log file.txt](https://github.com/user-attachments/files/18001790/totally.real.a.real.log.file.txt)

**Comment by Joehuu** [comment] 2024-12-04 02:40
Duplicate of https://github.com/ppy/osu/issues/26566

**Closed by Joehuu** 2024-12-04 02:40 UTC
