### ISSUE TITLE
allow hit-100 and hit-50 skin elements to indicate whether you're hitting a note late or early.

### ISSUE THREAD

**Issue by hostilew** [ppy/osu#6213] opened 2019-09-22 22:22 UTC
**Describe the new feature:** 
When in a long stream, it can be difficult to tell whether you're over or under-streaming. A majority of players have the hit-error bar enabled. This is to check local offset, but also to monitor whether they're falling behind a stream or overstreaming. 
![](https://i.imgur.com/W6VpWs1.png)
 it's impossible to tell if you are ahead of or behind a stream just by in-game visuals alone. 

**Proposal designs of the feature:** 
The proposal is to create a new skin element hit-100late, When hit-100late is used in a skin, it replaces 100s that comes from a late note hit. The same goes for hit-50, katu, and @2x variants. 

This way of showing late and early hits would be much more intuitive than having to look down at the hit error bar, instead it would show right under the note you just hit.

**Comment by bdach** [comment] 2019-09-22 22:54
A proposal for the same kind of feature was made in #3209, albeit slightly different in execution.

**Comment by iiSaLMaN** [comment] 2019-09-22 23:39
Essentialy duplicate of #3209.

**Comment by Joehuu** [comment] 2019-09-22 23:45
Closing as duplicate.

**Closed by Joehuu** 2019-09-22 23:45 UTC
