### ISSUE TITLE
Beatmap custom hitsounds don’t work anymore

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu#9164] opened 2020-06-01 04:20 UTC
**Describe the bug:** 
Beatmap hitsounds do not work on iOS osu!lazer 2020.523.0.
I also tested on osu!lazer 2020.306.0 and they worked fine there 

**Screenshots or videos showing encountered issue:** 
https://youtu.be/YKkXdHl87p8

**osu!lazer version:** 
Listed above

**Logs**
N/A

**Comment by peppy** [comment] 2020-06-01 04:23
Could you please include a link to the beatmap you were testing with?

**Comment by ThatsNiceGuy** [comment] 2020-06-01 04:27
Sure, lemme find it

**Comment by ThatsNiceGuy** [comment] 2020-06-01 04:29
Here ya go: https://osu.ppy.sh/beatmapsets/5240#osu/26158

**Comment by peppy** [comment] 2020-06-01 04:35
Can reproduce on desktop platforms. Likely related to `SkinnableSound` changes, will investigate.

**Comment by peppy** [comment] 2020-06-01 04:57
Actually I'm now confused. I've checked and some of the hitsounds are playing correctly on lazer and stable, but the ones you show in the video don't play on stable or lazer for me.

**Comment by ThatsNiceGuy** [comment] 2020-06-01 05:47
Okay, I’ll try deleting and redownloading to make sure I have the latest version of the map.

**Comment by ThatsNiceGuy** [comment] 2020-06-01 06:08
Okay now I’m confused too, getting different hitsounds as well after a redownload. https://youtu.be/T3u0QPwap3g
This is still on 2020.306.0, as they do not work in 2020.523.0

**Comment by peppy** [comment] 2020-06-02 08:25
Can you confirm that they sound as you "expect" on osu-stable?

**Comment by peppy** [comment] 2020-06-03 03:30
May be related to https://github.com/ppy/osu/issues/8928, since both maps use `normal-hitnormal2.wav` number suffixed hitsounds.

**Comment by ThatsNiceGuy** [comment] 2020-06-04 05:33
They sound as I expect in stable and I agree with that it may be related

**Comment by bdach** [comment] 2020-07-02 20:51
The samples on the particular section highlighted here are triggering this conditional:

https://github.com/ppy/osu/blob/ab9149844af06a2a15dcab2c7f880b94dc6f73ee/osu.Game/Skinning/LegacyBeatmapSkin.cs#L43-L47

The beatmap skin is providing non-suffixed samples (such as `normal-hitfinish`) which then end up being ignored by the aforementioned check.

**Comment by smoogipoo** [comment] 2020-07-07 11:12
I'm not sure how you all reached the conclusions made in this thread. As far as I can see there is nothing in the beatmap that indicates custom sample sets should be used:
1. It's version 5, so it uses CSS=0 by default. Versions < 4 should always use CSS=1 it seems (not implemented in lazer).
2. It doesn't have a `CustomSamples` property in the `[General]` section. A value of `1` would indicate using CSS=1 (not implemented in lazer).
3. All control points list CSS=0.
4. No hitobjects request a CSS. The beatmap is from a time where per-hitobject CSS didn't even exist (it was implemented in version 11 in 2012).

In debugging stable, I can confirm that at no point does a hitobject request CSS>0.

I'm almost wondering whether this is some long-standing bug that's been broken in stable for the last ~12 years (ever since per-timingpoint CSS was implemented)?

**Comment by bdach** [comment] 2020-07-07 17:09
I have downloaded the map linked by @ThatsNiceGuy and ran it on stable. It does not play the custom hit sounds from the beatmap skin which I remember hearing in the videos that were attached here, which would indicate that @smoogipoo is correct and this is not actually a valid issue.

When I went and *manually* chose custom sample bank 1 for all timing points I did get the custom hit sounds.

@ThatsNiceGuy can you attach the `.osu` file from your stable install on which you're hearing the beatmap samples for inspection?

**Comment by ThatsNiceGuy** [comment] 2020-07-08 18:44
yep will upload it as soon as possible (although idk what it’s even supposed to sound like anymore, this is one old map)

**Comment by bdach** [comment] 2021-01-06 18:03
Going to tentatively close this as outdated/possibly-not-an-issue-whatsoever.

**Closed by bdach** 2021-01-06 18:03 UTC
Labels: area:gameplay, missing details, type:audio
