### ISSUE TITLE
Cursor sometimes freezing mid-map

### ISSUE THREAD

**Issue by Panguwuk** [ppy/osu#30443] opened 2024-10-28 22:31 UTC
### Type

Crash to desktop

### Bug description

Sometimes my cursor (and also seems to be key presses aswell) just completely freezes for about half a second. This has only happened on lazer and very rarely happens ever

just would be annoying if it happened during a very important play

this has been going on ever since i started playing lazer which is around 8 months or so ago

it looks like it does record my input, but just delays it to whenever it stops freezing

### Screenshots or videos

https://github.com/user-attachments/assets/e84f9482-1e4d-4c12-8b8b-4d185ac8d87c

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17549454/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-10-28 23:02
This is a duplicate of pinned issue https://github.com/ppy/osu/issues/27227.

**Closed by Joehuu** 2024-10-28 23:02 UTC
