### ISSUE TITLE
osu! crashes after random interacting (alt-tab, adding skin / map by file)

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu#21319] opened 2022-11-19 20:42 UTC
### Type

Crash to desktop

### Bug description

Hello, i was trying to record osu!lazer gameplay with OBS and NVENC codec and i got game crashed thrice after alt-tabbing from obs to osu!, ~~however, there was no crashes when i switched to x264 or i just was "lucky"~~ (it happened again, probably OBS issue). After this all, i put NVENC back, tried to load skin with .osk file and got osu crashed again. 

It doesn't matter if you're using borderless or fullscreen. Attaching logs after skin loading crash
### Screenshots or videos

![image](https://user-images.githubusercontent.com/42616718/202870734-4b067208-f377-4f51-aa4a-4d01fcb1738d.png)
![image](https://user-images.githubusercontent.com/42616718/202870770-db7713b3-b040-43ab-a31c-c6e0155f2e70.png)

### Version

20221117

### Logs

[runtime.log](https://github.com/ppy/osu/files/10047910/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10047911/updater.log)
[database.log](https://github.com/ppy/osu/files/10047912/database.log)
[input.log](https://github.com/ppy/osu/files/10047913/input.log)
[performance.log](https://github.com/ppy/osu/files/10047914/performance.log)

**Comment by bdach** [comment] 2022-11-19 20:44
Please attach Windows Event Viewer info by performing the following steps:
1. Type `Event viewer` in the Windows search bar (shortcut: <kbd>Windows</kbd>+<kbd>S</kbd>) and press <kbd>Enter</kbd>, or open the *Run...* button (<kbd>Windows</kbd>+<kbd>R</kbd>), type in `eventvwr` and press <kbd>Enter</kbd>.
2. The *Event viewer* window will appear. Expand *Windows Logs* on the left and choose *Application*. It might take a while to load.
3. In the *Actions* pane on the right click *Save All Events As...*, then choose a location to save to.
4. On the *Display Information* popup, select the second option, then the checkbox to show all available languages, then *English (UK)* (US would also do fine).
5. Append the resulting `.evtx` file to this issue.

**Comment by Dopaminos** [comment] 2022-11-19 20:47
![123](https://user-images.githubusercontent.com/42616718/202871027-223fef09-3380-4285-9c69-0f47c85547a7.png)

rename to 123.evtx, github does not support .evtx

**Comment by Dopaminos** [comment] 2022-11-19 20:48
![image](https://user-images.githubusercontent.com/42616718/202871064-5f886ef7-c173-4677-a50b-ffeb62df92dc.png)
i guess that's what you need, five same errors at same IP

**Comment by bdach** [comment] 2022-11-19 20:51
Looks like a duplicate of #17354.

Not sure I can offer much more help since this error seems to be hardware-dependent. Try updating device drivers, as it is known to help in some cases. Failing that you may need to wait for compatibility mode to be brought back.

**Closed by bdach** 2022-11-19 20:51 UTC
Labels: missing details

**Comment by Dopaminos** [comment] 2022-11-19 20:52
just in case, my hw is R7 5800H + 3050 Ti Laptop, all drivers is updated (even bios)
