### ISSUE TITLE
Crash on beatmap start

### ISSUE THREAD

**Issue by Pebor** [ppy/osu#17605] opened 2022-04-01 17:06 UTC
### Type

Crash to desktop

### Bug description

Opening most of my beatmaps on a fresh install (appimage) crashes osu! a bit after the loading map screen appears for the beatmap.
I also tried compiling myself.

OS: Linux (arch)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/32438954/161309033-3b79059c-826d-472f-9bc9-c81985b5afdd.png)
![image](https://user-images.githubusercontent.com/32438954/161309502-d0b670f9-d812-473f-a7d2-a918f2427d8e.png)

### Version

2022.327.0

### Logs

[database.log](https://github.com/ppy/osu/files/8399668/database.log)
[network.log](https://github.com/ppy/osu/files/8399669/network.log)
[performance.log](https://github.com/ppy/osu/files/8399670/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8399671/runtime.log)

**Comment by jai-x** [comment] 2022-04-01 17:18
Related: https://github.com/ppy/osu/discussions/17566

**Comment by bdach** [comment] 2022-04-01 17:19
Actually a duplicate of https://github.com/ppy/osu/issues/17457

**Closed by bdach** 2022-04-01 17:19 UTC

**Comment by Pebor** [comment] 2022-04-01 17:22
Am also using an AMD gpu
drivers seem to be all over the place recently, I will try mesa-git

**Comment by Pebor** [comment] 2022-04-01 18:53
This can be fixed by just simply disabling all storyboards/videos

**Comment by bdach** [comment] 2022-04-01 18:54
the crash is in FFmpeg, so yes, although i wouldn't call it a "fix". a workaround, at best.

an actual fix on our side would be https://github.com/ppy/osu-framework/issues/4349.
