### ISSUE TITLE
SR on map title shown defferent from actual SR.

### ISSUE THREAD

**Issue by IkaWaAyuMu** [ppy/osu#14070] opened 2021-07-30 22:31 UTC
**Describe the bug:** SR on map title shown different from actual SR (calculated SR). Effect map and difficulty that downloaded and imported before #13483. This is checked by hover the cursor on difficulty icon on map title.

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/7066150/127717806-aa852ac0-a46b-4ebe-88ee-22ac5453dcb9.png)

**osu!lazer version:** 2021.724.1-lazer

**Comment by frenzibyte** [comment] 2021-07-30 22:55
Duplicate of https://github.com/ppy/osu/issues/10242.

**Closed by frenzibyte** 2021-07-30 22:55 UTC
