### ISSUE TITLE
Invalid displayed keys in the keys configuration (with non-QWERTY keyboard?)

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu#12794] opened 2021-05-13 22:12 UTC
**Describe the bug:** 
The keys displayed in the keys configuration are incorrect with some keys (for example, displays Z instead of W, displays A instead of Q, ...). I have a french AZERTY keyboard. Also, there isn't problem with a QWERTY keyboard.

I think that happens only with non-QWERTY keyboard and I think the bug exists because the keys bindings aren't converted with non-QWERTY keyboards...

**Screenshots or videos showing encountered issue:** 
![osu_2021-05-14_00-05-20](https://user-images.githubusercontent.com/57914482/118193626-4ef11700-b448-11eb-8988-3f0a1c84c6ba.png)
I swear I pressed W for the osu! left button...

**osu!lazer version:** 
2021.514.0

**Logs:**
[performance.log](https://github.com/ppy/osu/files/6475326/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6475327/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6475328/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6475329/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6475330/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6475331/updater.log)
[database.log](https://github.com/ppy/osu/files/6475332/database.log)
[network.log](https://github.com/ppy/osu/files/6475333/network.log)

**Comment by bdach** [comment] 2021-05-13 22:16
Duplicate of #11143

Please search.

**Closed by bdach** 2021-05-13 22:16 UTC
