### ISSUE TITLE
I can't view the chat on osu!lazer tournament

### ISSUE THREAD

**Issue by Nokeira** [ppy/osu#7061] opened 2019-12-04 15:41 UTC
**Describe the bug:** 
Hi,
I need your help for the chat, I don't know why my ipc-channel is empty.
and the chat can't view the player on the room
thank dudes.
**Screenshots or videos showing encountered issue:** 
[Screen on the osu lazer tournament](https://i.imgur.com/TwSIiis.png)
**osu!lazer version:** 
2019.1128.0
**Logs:** 
[network.log](https://github.com/ppy/osu/files/3922665/network.log)
[runtime.log](https://github.com/ppy/osu/files/3922669/runtime.log)

**Comment by peppy** [comment] 2019-12-04 15:48
This is not yet supported for non-admin users. We are working on a solution for this which should go live this week.

**Comment by peppy** [comment] 2019-12-04 15:48
Closing as duplicate of https://github.com/ppy/osu/issues/5366.

**Closed by peppy** 2019-12-04 15:48 UTC
