### ISSUE TITLE
DT/NC/HT does not decrease/increase song length in song selector

### ISSUE THREAD

**Issue by UnknownUP** [ppy/osu#21066] opened 2022-11-01 23:10 UTC
### Type

Game behaviour

### Bug description

I really don't know if it's a bug, I just found it strange that in the _stable_ version these mods do change the length of the song in the song selector. Maybe it's made for some purpose, if not, then you already know about it.
I discovered the bug at the moment of activating the mods mentioned in the title

### Screenshots or videos

https://user-images.githubusercontent.com/117231363/199355431-316c3827-3d3a-4e00-9a81-ac0c7642d1e3.mp4

### Version

osu! 2022.1101.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9914581/database.log)
[input.log](https://github.com/ppy/osu/files/9914582/input.log)
[performance.log](https://github.com/ppy/osu/files/9914583/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9914584/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9914585/updater.log)

**Comment by tybug** [comment] 2022-11-02 00:09
duplicate of #10580

**Closed** 2022-11-02 00:41 UTC
