### ISSUE TITLE
video plays early on lazer, not on sync with audio

### ISSUE THREAD

**Issue by aryamanv** [ppy/osu#7033] opened 2019-12-01 18:54 UTC
if you play a video beatmap on lazer, the video starts playing immediately, but the beatmap and audio start a few seconds after, making the audio delayed and harder to play on lazer with video.

heres the video: https://www.youtube.com/watch?v=e26kQ-buDb4&t

**Comment by Game4all** [comment] 2019-12-01 18:57
Duplicate of issue #6101

**Closed** 2019-12-01 18:58 UTC
