### ISSUE TITLE
Program-wide graphics glitch

### ISSUE THREAD

**Issue by ikkue** [ppy/osu#23254] opened 2023-04-20 11:32 UTC
### Type

Game behaviour

### Bug description

Sprites and graphics game-wide seems to be glitched and randomly appear and disappear.

It randomly happened over time, and I have only a YouTube video opened on another monitor (set to Auto Quality, which it defaulted to 480p) on Mozilla Firefox and Discord opened in the background but minimised.

I did use Efficiency Mode in Task Manager on Firefox and Discord and made osu!(lazer) high priority (sorry peppy, I know you're against that).

My computer's specs:

> **CPU**: AMD Ryzen 5 3400G with Radeon Vega Graphics @ 3.70 GHz
> **GPU**: AMD Radeon RX 570 Series
> **RAM**: 16.0 GB
> **System**: Windows 11 Pro for Workstations Version 22H2

It's also 36–38°C so I don't know if that's a factor, and I'm using the OpenGL renderer.

Update: It happened the second time after I closed and restarted the game again. It happened after 5–10 minutes or 4–5 times of restarting a map. It starts with many grey squares in the background and deteriorates over time until every single sprite disappears and the program becomes completely black.

### Screenshots or videos

https://youtu.be/uAG5O3_BPWk

### Version

2023.419.0

### Logs

[database.log](https://github.com/ppy/osu/files/11285667/database.log)
[input.log](https://github.com/ppy/osu/files/11285668/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11285669/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11285670/network.log)
[performance.log](https://github.com/ppy/osu/files/11285671/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/11285672/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/11285673/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/11285674/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/11285675/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11285676/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11285677/updater.log)

**Comment by frenzibyte** [comment] 2023-04-20 17:54
Sounds related to #23252, can you check memory usage and see if it's rising over time? Maybe Veldrid isn't cleaning up GL resources properly.

**Comment by frenzibyte** [comment] 2023-04-21 10:30
Marking this as `missing-details` as one pending answer to above question.

**Comment by ikkue** [comment] 2023-04-21 11:02
[Here](https://youtu.be/lv2YAaGRffU) is the video. There are timestamps so you can skip to when it happens.

Memory usage seems to increase over time until it reaches the limit of my RAM (~15.9 GB).

**Comment by frenzibyte** [comment] 2023-04-21 11:10
Closing as duplicate of #23252 then.

**Closed by frenzibyte** 2023-04-21 11:10 UTC
Labels: type:performance, missing-details, renderer:veldrid-gl
