### ISSUE TITLE
Glow effect not properly dimmed

### ISSUE THREAD

**Issue by Stehsaer** [ppy/osu#27629] opened 2024-03-16 08:30 UTC
### Type

Cosmetic

### Bug description

Opening the settings or the notifications menu dims the background. However the glow effect around certain elements are not correctly dimmed.

### Normal
![Normal Select](https://github.com/ppy/osu/assets/54050160/ddb22b06-b90c-4cf9-b4d7-095ebcd9fc4f)
### Incorrectly dimmed
![Notice the glow around the elements](https://github.com/ppy/osu/assets/54050160/7dd188d2-985a-4d15-844c-7e7ccb824a33)
![Notice the glow around the elements](https://github.com/ppy/osu/assets/54050160/e7d298ee-8ca1-4d7b-9b8e-d50d7f2e9dc7)
Notice the incorrectly dimmed glow effect around the elements
![image](https://github.com/ppy/osu/assets/54050160/fd12f081-811a-4846-b81d-ade48eddba3f)

### Version

2024.312.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/14622930/compressed-logs.zip)

**Comment by EVAST9919** [comment] 2024-03-16 17:12
Duplicate of https://github.com/ppy/osu/issues/4229

**Closed** 2024-03-16 19:37 UTC
