### ISSUE TITLE
Implement beatmap carousel grouping support

### ISSUE THREAD

**Issue by peppy** [ppy/osu#4920] opened 2019-06-05 09:38 UTC
Show collapsable groups that can be customised by user setting.

- [ ] Depends on design (#2547)

**Comment by iiSaLMaN** [comment] 2019-09-21 09:52
This should also move to the `Candidate issues` milestone.

**Comment by smoogipoo** [comment] 2019-09-21 10:00
Closing as duplicate of mentioned issue.

**Closed by smoogipoo** 2019-09-21 10:00 UTC
Labels: song select
