### ISSUE TITLE
Game freezes if using bound button to get to virtual desktop (alt+tab) and it freezes when taking screenshots using the hot key

### ISSUE THREAD

**Issue by Dengekiko** [ppy/osu#8421] opened 2020-03-23 21:01 UTC
If I use my logitech mouse to try to to get to the window overview in windows 10 since the thumb button is assigned to that it freezes osu and shows  the main cursor under the game one but you cant get out of that state.

The easy way to get to this state is to try to screen shot in game with the default screen shot command. Super + Shift+ S. 

Osu 2020-320-1
Latest windows revision

**Comment by bdach** [comment] 2020-03-23 21:13
I'm not sure what you're getting at here in the first part in particular. Mind attaching a video?

As for the freeze when pulling up the windows screenshot tool with <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>, that is the expected behaviour of a screenshot tool. It needs to freeze current screen state for the user to be able to take a screenshot of that particular instant.

**Comment by tmillerklugman** [comment] 2020-03-23 21:57
Here is a example. It doesn't really freeze more like locks the game up. This is with going into alt+tab there is a part when the screenshot crosshair showed up and vanashed but I couldn't even crop to take a pic before it bugged out. https://youtu.be/0QWOHOm1jKU

**Comment by tmillerklugman** [comment] 2020-03-23 22:00
If you're wondering why it took my so long to exited it's because I couldn't. I was completed locked on the osu window... if it helps I am using a AMD Vega 56. Also I didn't notice this at first but for some reason discord has part of it's window flashing in the upper right corner at the start.

**Comment by bdach** [comment] 2020-03-23 22:28
Are you playing borderless, or exclusive fullscreen? If the latter, maybe try borderless.

Not sure we will be able to do much about this. Windows's new bells and whistles don't seem to play nice with osutk in general.

**Comment by tmillerklugman** [comment] 2020-03-23 23:17
I am playing in fullscreen mode it appears to work in borderless :D

**Comment by peppy** [comment] 2020-03-24 01:36
Screenshots using windows game bar work correctly here. Might be a driver specific issue, or some combination of overlays loaded by the user causing the weird behaviour. Try closing other overlays like discord/steam and see if it plays better.

**Comment by bdach** [comment] 2020-09-19 23:22
@Dengekiko Is this still occurring? Have you tried to disable other overlays as suggested above?

**Comment by Dengekiko** [comment] 2020-09-19 23:24
It appears to be working now :D

**Comment by bdach** [comment] 2020-09-19 23:25
Good to hear. Closing as resolved.

**Closed by bdach** 2020-09-19 23:25 UTC
Labels: missing details, platform:windows
