### ISSUE TITLE
Importing a skin with the same name and version does not actually update the textures, even when skins are deleted.

### ISSUE THREAD

**Issue by 9hax** [ppy/osu#6517] opened 2019-10-15 11:35 UTC
**Describe the bug:** 
Deleting an imported skin, then importing a modified version of that skin does not update the skin to the modified version. 
Deleting the old skin, restarting and then importing the new skin works.

[**Screenshots or videos showing encountered issue:** ](https://youtu.be/pc4QEwxL7LQ)
The Video was too big for GitHub Issues.

Timestamps:
0:00 - 0:40 : Importing the unmodified Skin and short gameplay demo
0:40 - 0:50 : Deleting the unmodified Skin
0:50 - 1:00 : Importing the new skin
1:00 - 1:15 : Selecting the Skin in the Settings does not update the selection (why? Could not reproduce)
1:15 - 1:30 : Updating the Skin didn''t work, the modified version has not been loaded
1:30 - 1:50 : Deleting all Skins, restarting the osu!lazer client
1:50 - 2:10 : Importing the modified Skin (and forgetting to set it oops)
2:10 - 2:25 : Setting the modified Skin
2:25 - end : Short Gameplay demo with the modified skin which doesnt hide the numbers.

**osu!lazer version:** 

2019.1011.0 Precompiled Windows Version from the "releases" page.

**Logs:** 
The first ZIP contains the logs folder with the unsuccessful update.
[first run.zip](https://github.com/ppy/osu/files/3728973/first.run.zip)
The second ZIP contains the logs folder with the successful import.
[second run.zip](https://github.com/ppy/osu/files/3729001/second.run.zip)

**Comment by peppy** [comment] 2019-10-15 18:08
Deletions only occur on the next startup. As a workaround, please restart osu! after deleting the skin.

Alternatively, make a change to skin.ini as well, since it is currently used as the checksum for whether a skin has changed on re-import.

**Comment by peppy** [comment] 2021-02-18 07:21
Going to close this one as expected behaviour. Will eventually be a better workflow when there's a built-in skin editor.

**Closed by peppy** 2021-02-18 07:21 UTC
Labels: area:database
