### ISSUE TITLE
New HP Drain feature doesn't working well on spinner

### ISSUE THREAD

**Issue by Kiddo-Kris** [ppy/osu#7428] opened 2020-01-03 08:02 UTC
Describe the bug:
-
As the title, HP doesn't regenerate by spinning spinner

**Screenshots or videos showing encountered issue:** 
-
[HP Drain.zip](https://github.com/ppy/osu/files/4018461/HP.Drain.zip)

**osu!lazer version:** 
-
Lazer 2019.1227.0

**Logs:** 
-
_No need I guess_

**Comment by mcendu** [comment] 2020-01-03 08:06
Looks like a dupe of some other issue.

**Comment by smoogipoo** [comment] 2020-01-03 08:11
Will be resolved by https://github.com/ppy/osu/pull/5782

**Closed** 2020-07-24 15:14 UTC
Labels: area:gameplay, ruleset:osu!
