### ISSUE TITLE
Option for back-button behaviour

### ISSUE THREAD

**Issue by scott-tancock** [ppy/osu#5978] opened 2019-09-03 22:28 UTC
**Describe the new feature:** 
In the new Osu!, the back button (ESC) must be held for a **really** long time to effect certain changes: quitting the game from the main menu and pausing while in-game.  The first of these scenarios makes sense.  The second scenario (pausing in-game) is more annoying that anything else, since:

- If I fail (or know I am about to fail) the beatmap, I have to hold the back button for a very long period of time to ge to the retry menu, or sit through the long failure animation.  This gets very annoying after a while.
- If I need to pause the game because I need to physically move away from the keyboard (RL gets in the way sometimes), it takes a lot longer to pause and I need a lot larger gap between notes to actually pause it.

Therefore, I propose that we add an option to change the back button behaviour.  This could be a checkbox named "hold back to menu" (default on) or "immediate menu" (default off), or it could be a slider with the number of seconds that it has to be held (lowest value being 0 = immediate, highest value being e.g. 5 seconds).

Alternatively, we could introduce a double- or tripple-tap on the back button for an immediate menu or escape.

**Comment by bdach** [comment] 2019-09-03 22:32
Duplicate of #5402 (I think?)

**Comment by peppy** [comment] 2019-09-04 00:23
"really" long as in 200m. Are you sure you're on the latest version?

**Comment by Joehuu** [comment] 2019-09-19 21:33
Resolved in https://github.com/ppy/osu/pull/6166.

**Closed by Joehuu** 2019-09-19 21:33 UTC
Labels: ux
