### ISSUE TITLE
Mouse won't move in game menu

### ISSUE THREAD

**Issue by malis079407** [ppy/osu#7313] opened 2019-12-20 20:34 UTC
When the game is launched, my mouse will be stuck in position and will only move ever so slightly if i move the mouse fast enough but will then remain stuck again for a while. The keys still work but my mouse doesn't. Same problem with both wired and wireless mouses. This is on the macOS version.

This has only occurred in all versions above 2019.1205.0 including the latest one.

**Comment by Luxiono** [comment] 2019-12-20 21:10
Can you provide any log files that may be relevant?

**Comment by Game4all** [comment] 2019-12-20 21:16
Have you tried resetting input settings ? (by pressing Ctrl / Cmd + Alt + R)

**Comment by swoolcock** [comment] 2019-12-20 22:26
Duplicate of all of these issues:
#7102 #6519 #4359 #3448 

Please search before creating an issue.

As mentioned, reset input with Ctrl+Alt+R.

**Closed by swoolcock** 2019-12-20 22:26 UTC
