### ISSUE TITLE
Norwegian flag has wrong proportions

### ISSUE THREAD

**Issue by Sr3qt** [ppy/osu#18676] opened 2022-06-13 13:41 UTC
### Type

Cosmetic

### Bug description

The images show the norwegian flag in game and a reference image from wikipedia.
The blue line in the middle is too thin in-game and it looks more like a danish flag. It's supposed to be twice as thick as a single white line.
Its the same flag in profiles and leaderboards afaik.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/105977398/173365635-657b511a-8d1e-4219-b454-b997ede4b45d.png)
![image](https://user-images.githubusercontent.com/105977398/173365673-a5ce8229-fa9a-4fdb-83d3-39b225ea2e3d.png)

### Version

2022.612.0 - lazer

### Logs

[performance.log](https://github.com/ppy/osu/files/8891515/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8891516/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8891517/updater.log)
[database.log](https://github.com/ppy/osu/files/8891519/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/8891520/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/8891521/network.log)

**Comment by smoogipoo** [comment] 2022-06-13 13:45
Duplicate of https://github.com/ppy/osu/issues/16422

**Closed** 2022-06-13 13:46 UTC
