### ISSUE TITLE
ingame text is only half visible

### ISSUE THREAD

**Issue by Swizznegg** [ppy/osu#4840] opened 2019-05-21 19:12 UTC
**Describe the bug:** all the beatmap titles are crazy or somthing like that

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/50886175/58123858-1a597480-7c0d-11e9-8e20-ecb8727d3d4a.png)
![image](https://user-images.githubusercontent.com/50886175/58124018-791eee00-7c0d-11e9-9545-1fb1b7dc04ea.png)
![image](https://user-images.githubusercontent.com/50886175/58124126-c0a57a00-7c0d-11e9-9a3d-d11b7f8af898.png)

**osu!lazer version:** 2019.518.0

**Logs:**

**Comment by GSculerlor** [comment] 2019-05-21 19:16
Looks like similar with #1488

**Comment by Swizznegg** [comment] 2019-05-21 19:19
but I have a 16:9 screen
or did I understand something wrong?

**Comment by GSculerlor** [comment] 2019-05-21 19:21
Maybe attaching logs can help to figure it out

**Comment by Swizznegg** [comment] 2019-05-21 19:24
sry my english is not that great, so I dont know what you mean with logs

**Comment by SweDerpZ** [comment] 2019-05-21 21:28
the same is happening for me and some numbers don't show either. Also, the difficulty stars arent showing

**Comment by peppy** [comment] 2019-05-22 02:00
Duplicate of #1488. Still searching for a solution or reproduction case.

**Closed by peppy** 2019-05-22 02:00 UTC
