### ISSUE TITLE
Difference in 100/50/miss count when viewing replays

### ISSUE THREAD

**Issue by IoIosaurus** [ppy/osu#23166] opened 2023-04-08 18:03 UTC
### Type

Other

### Bug description

I just set my first 400pp score in osu!lazer with the mod combination classic+DT 1.1x. The has 20 100 hits but when i watched the replay the score had 21 100 hits which brought my play down to 399pp. This bug is quiet common especially on longer maps. 

### Version

Lazer 2023.403.1

### Logs

[database.log](https://github.com/ppy/osu/files/11183826/database.log)
[input.log](https://github.com/ppy/osu/files/11183827/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/11183828/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/11183829/network.log)
[performance.log](https://github.com/ppy/osu/files/11183830/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11183831/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11183832/updater.log)

**Comment by bdach** [comment] 2023-04-10 11:52
Likely duplicate of #11311

**Closed by bdach** 2023-04-10 11:52 UTC
