### ISSUE TITLE
Win32Exception when moving the cursor while Windows' User Account Control (UAC) window pops up

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu#9410] opened 2020-06-30 13:22 UTC
**Describe the crash:** When I try to launch my tablet driver, Windows brings up the [_User Account Control_](https://support.microsoft.com/en-us/help/4462938/windows-about-user-account-control-settings) window (which dims the whole screen behind it). Sometimes, if I move the mouse while that window appears, Lazer crashes and gives a `Win32Exception` saying "Access denied".

**Logs:** The only relevant portion of the logs is this one in `runtime.log`:
```
2020-06-30 12:54:37 [verbose]: Focus contention triggered by NotificationOverlay.
2020-06-30 12:54:37 [error]: An unhandled error has occurred.
2020-06-30 12:54:37 [error]: System.ComponentModel.Win32Exception (5): Accesso negato.
2020-06-30 12:54:37 [error]: at osuTK.Platform.Windows.WinGLNative.HandleMouseMove(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
2020-06-30 12:54:37 [error]: at osuTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam)
2020-06-30 12:54:37 [error]: at osuTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
2020-06-30 12:54:37 [error]: at osuTK.Platform.Windows.WinGLNative.ProcessEvents()
2020-06-30 12:54:37 [error]: at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
2020-06-30 12:54:37 [error]: at osuTK.GameWindow.Run()
2020-06-30 12:54:37 [error]: at osu.Framework.Platform.GameWindow.Run()
2020-06-30 12:54:37 [error]: at osu.Framework.Platform.GameHost.Run(Game game)
2020-06-30 12:54:37 [error]: at osu.Desktop.Program.Main(String[] args)
```
One weird thing is that the "Access denied" description is in Italian (my OS language), but that's not very important.

**Computer Specifications:** 
OS: Windows 10 Home (Version 1909), Build 18363.900

**Comment by Gabixel** [comment] 2020-06-30 13:25
Just to clarify: I tried to open other apps that use this _UAC_ window. For example, the Registry Editor (aka Regedit). It crashes anyway, so it's not a problem of the tabler driver.

**Comment by frenzibyte** [comment] 2020-06-30 13:54
May be worth to try reproducing this in SDL.

**Comment by smoogipoo** [comment] 2020-07-01 05:38
Please test in SDL (`--sdl` program argument), have a feeling this will probably be fixed.

**Comment by Gabixel** [comment] 2020-07-05 00:41
I've tried reproducing it almost 50 times with the `--sdl` argument (even replicating some edge-cases and weird/unusual scenarios using the taskbar and the start menu), but Lazer never crashed. So... I guess it's probably fixed!
Closing as resolved.

**Comment by frenzibyte** [comment] 2020-07-05 00:43
Good to hear! although since this issue does not appear frequently, I think this issue should still be opened until the game fully uses SDL as its default backend and leaves osuTK away.

**Comment by Joehuu** [comment] 2020-12-04 04:06
Fixed in SDL as of now.

**Closed by Joehuu** 2020-12-04 04:06 UTC
Labels: fixed-in-sdl, platform:windows
