### ISSUE TITLE
Score and Replay are out of sync (Replay reports 1 miss, regaurdless of skipping through, even though the score is an S)

### ISSUE THREAD

**Issue by N0Y0U2114** [ppy/osu#31012] opened 2024-12-09 00:24 UTC
### Type

Game behaviour

### Bug description

Set an S rank score 10 minutes ago (taiko), when going through the replay it reports a miss at a double Large Don, even though no miss was reported for score or during gameplay. If the area with the miss is moved through slowly (using progress bar), the replay counts the hit correctly with no miss. 

### Screenshots or videos

Score on Leaderboard 
![image](https://github.com/user-attachments/assets/86a8b782-9446-4e27-a4d6-5953a6676ae2)
Score when replay is played normally 
![image](https://github.com/user-attachments/assets/652f2b54-b805-492d-b9ea-ab51b8ee5ce5)
Replay when pause scrubbed at "miss" 
![image](https://github.com/user-attachments/assets/00834988-8f84-4e3a-8fbe-61fa11e44dd7)
 

https://osu.ppy.sh/beatmapsets/2181323#taiko Map
https://osu.ppy.sh/scores/3987739957 Score
[compressed-logs.zip](https://github.com/user-attachments/files/18054666/compressed-logs.zip) logs
[N0Y0U2114 playing Umeboshi Chazuke - ICHIBANBOSHI_ROCKET (_gt) [FUTSUU] (2024-12-08_17-48).zip](https://github.com/user-attachments/files/18054667/N0Y0U2114.playing.Umeboshi.Chazuke.-.ICHIBANBOSHI_ROCKET._gt.FUTSUU.2024-12-08_17-48.zip) replay
[Recording 2024-12-08 182243.zip](https://github.com/user-attachments/files/18054691/Recording.2024-12-08.182243.zip) Recording (Video was 11mb)

### Version

2024.1115.3-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18054666/compressed-logs.zip) logs

**Comment by smoogipoo** [comment] 2024-12-09 00:46
Likely duplicate of https://github.com/ppy/osu/issues/11311

**Closed by smoogipoo** 2024-12-09 00:46 UTC
Labels: area:replay
