### ISSUE TITLE
Point of Failure graph becoming upside down when using larger UI scale. 

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu#8682] opened 2020-04-08 12:47 UTC
**Describe the bug:** 
When setting a larger than normal UI scale, the point of failure graph becomes upside down. It happens at around 1.25x scaling on a 1080p screen.

**Screenshots or videos showing encountered issue:** 
 
![Screenshot_20200408-204032](https://user-images.githubusercontent.com/12001167/78785541-e4b2ab00-79d9-11ea-8eec-6eca0c0c6ecd.jpg)
![Screenshot_20200408-204023](https://user-images.githubusercontent.com/12001167/78785543-e67c6e80-79d9-11ea-8a1b-804aec8792b8.jpg)

**osu!lazer version:** 
2020.408.0

**Comment by EVAST9919** [comment] 2020-04-08 12:50
Dupe of https://github.com/ppy/osu/issues/4931

**Closed** 2020-04-08 13:44 UTC
