### ISSUE TITLE
osu! reloads upon focus regain on Android.

### ISSUE THREAD

**Issue by R0slaN** [ppy/osu#8080] opened 2020-03-01 17:33 UTC
**Describe the crash:** 
When osu! gains focus again after losing it, it reloads itself. 

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=8Zx9ips-rgE

**osu!lazer version:** 
2020.229.1

**Phone Specifications:** 
Samsung Galaxy S9+ / SM-G965F / 6 GB RAM
Android 10, February security patch.

**Comment by bdach** [comment] 2020-03-01 17:35
Duplicate of #6593

[See reasoning for why this is the case for now.](https://github.com/ppy/osu/issues/6593#issuecomment-546041485)

**Closed by bdach** 2020-03-01 17:35 UTC
