### ISSUE TITLE
Replay gets better result than original score

### ISSUE THREAD

**Issue by Sinamer** [ppy/osu#14573] opened 2021-08-29 21:30 UTC
**Describe the bug:** The original score has three 100 judgements, but after watching the replay, this score is shown to only have one.

Replay file (in .zip format to upload here): [Sinamer playing Krewella - Say Goodbye.zip](https://github.com/ppy/osu/files/7073235/Sinamer.playing.Krewella.-.Say.Goodbye.Nightcore.ver.zip)
Beatmap link: https://osu.ppy.sh/beatmapsets/544049#osu/1152958

Side note, this replay is also affected by #13352 so make sure you don't get a miss trying to test this.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/53346335/131265712-b429dc94-a663-461a-9651-d841ca7eb061.mp4

**osu!lazer version:** 2021.828.0-lazer

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/7073234/runtime.log)

**Comment by tybug** [comment] 2021-10-30 20:42
The issue here is that both of the 100s in this replay are exactly on the boundary of the 100 hitwindow (100 hitwindow is 29ms and both of these hits have a 29ms error.

This is easily fixed with the following patch:

```diff
diff --git a/osu.Game/Rulesets/Scoring/HitWindows.cs b/osu.Game/Rulesets/Scoring/HitWindows.cs
index 2d008b58ba..adf0e72c79 100644
--- a/osu.Game/Rulesets/Scoring/HitWindows.cs
+++ b/osu.Game/Rulesets/Scoring/HitWindows.cs
@@ -128,7 +128,7 @@ public HitResult ResultFor(double timeOffset)
 
             for (var result = HitResult.Perfect; result >= HitResult.Miss; --result)
             {
-                if (IsHitResultAllowed(result) && timeOffset <= WindowFor(result))
+                if (IsHitResultAllowed(result) && timeOffset < WindowFor(result))
                     return result;
             }
```

For reference, both of the 100s occur on the stream at 2:41 lazer-time (this is with the patch above applied, so they show properly as 100s. I cross-checked with stable):

![image](https://user-images.githubusercontent.com/31628143/139557786-fb6ca696-31fb-406f-b320-b7295bf854c1.png)


The only reason I'm not pring is that I'm not sure if stable also uses exclusive ranges for hitwindows, and that's really the only issue here, or if there's something deeper going on. If someone can confirm it's the former I'll pr this.

**Comment by bdach** [comment] 2021-10-30 21:17
Well, you see... if I'm reading stable source correctly, it does *and* it doesn't. To qualify that, as far as I can tell, all rulesets *except for mania* use exclusive and mania uses inclusive.

I don't even know what to do with that information right now to be honest.

**Comment by abstrakt8** [comment] 2021-10-31 09:45
Probably related issue: #11311

**Comment by bdach** [comment] 2021-10-31 09:54
@abstrakt8 it is "related" in a sense that on the beatmap difficulty stats that you cited in that issue, stable looks to be subtracting 0.5ms from the actual hitwindow for all rulesets except mania, and adding 0.5ms for mania, likely in an effort to "compensate" for this.

however this looks to *only be applied on the display in song select*, gameplay logic still looks to be using the hitwindow values without that 0.5ms adjustment. in gameplay logic the inclusive/exclusive inequality check is used.

**Comment by smoogipoo** [comment] 2022-03-31 05:18
As mentioned above, this is a duplicate of #11311, and I've posted my thoughts regarding this in there. Closing this one.

**Closed by smoogipoo** 2022-03-31 05:18 UTC
Labels: area:replay
