### ISSUE TITLE
Broken sound at the start of songs

### ISSUE THREAD

**Issue by Gunnest663** [ppy/osu#1550] opened 2017-11-21 07:53 UTC
The sound on any beatmap at the start is always broken and fixes after 10 seconds which already i have lost my beat and missed some circles. Is that an issue with my computer or the game?

**Comment by peppy** [comment] 2017-11-21 08:00
you have to provide details

video? audio? anything really?

**Comment by Gunnest663** [comment] 2017-11-21 08:09
https://www.youtube.com/watch?v=ub_3V_Hh3W4

Do you mean a recorded video like that? that sound just bothers me and happens whenever it wants

**Comment by peppy** [comment] 2017-11-22 04:14
I can reproduce this on one of my testing setups. Thanks for the video, we'll look into it.

Looks like the audio is getting started/stopped very rapidly.

**Comment by peppy** [comment] 2017-11-24 12:55
@Gunnest663 if you are able to build from source, could you please try against the latest osu/framework master? I can't seem to reproduce any more.

**Comment by Gunnest663** [comment] 2017-11-26 05:02
Didn't see this before but i have tried the newest version but it does the same issue sometimes

**Comment by peppy** [comment] 2017-11-27 03:10
just to confirm, you built from source?

**Comment by peppy** [comment] 2017-12-22 06:28
Has been resolved by https://github.com/ppy/osu/pull/1717 and https://github.com/ppy/osu-framework/pull/1275.

**Closed by peppy** 2017-12-22 06:28 UTC
Labels: audio, bug
