### ISSUE TITLE
Enabling raw input stops tablets from working as expected (jumping cursor position)

### ISSUE THREAD

**Issue by Fvern** [ppy/osu#3911] opened 2018-12-24 16:41 UTC
With Raw Input enabled using tablet, whenever M1 is pressed the cursor glitches out like:
![capture133](https://user-images.githubusercontent.com/25032854/50403944-cb362180-07dd-11e9-900f-7fdcec07a794.PNG)
It happens inconsistently, half of the clicks not causing this. It only happens with Raw Input enabled, and using tablet. M1 from any source works, whether tablet tap or mouse click. I made sure it's not due to the mouse moving on the table.
osu!lazer version is in the screenshot

**Comment by Vernonlim** [comment] 2018-12-25 07:16
Already disabled

**Comment by Fvern** [comment] 2020-10-21 16:10
somehow, nearly 2 years later, this issue still exists.
![osu_2020-10-22_00-09-25-2](https://user-images.githubusercontent.com/25032854/96747451-e1719080-13fa-11eb-8957-9d874c22a08e.png)

I can't reproduce this in osu!stable, and I believe this is also affecting me in menus (will create a separate issue mentioning this one).

**Comment by bdach** [comment] 2020-10-21 16:13
That's how issue trackers generally work, things are open until they are fixed. You haven't given us any details to go on, either (like the tablet make/model, to begin with). This might also be fixed when SDL raw input lands, which hopefully it will soon.

**Comment by Fvern** [comment] 2020-10-21 16:33
> That's how issue trackers generally work, things are open until they are fixed. You haven't given us any details to go on, either (like the tablet make/model, to begin with). This might also be fixed when SDL raw input lands, which hopefully it will soon.

Yeah, I wasn't complaining, just observing that such a long time has passed (for me), yet this hasn't changed (unlike many other things in my life). I'll add on what tiny bit of info I have, but it's definitely best to wait and see if that SDL raw input changes it first.

It isn't worth another issue, so I'm just tagging it on — this causes rapid scrolling in menus. The cursor teleportation causes menus to scroll at extreme velocities with only small movements. 

Tablet make/model and drivers does not affect this, since in the time between the original post and now I have changed both (from a Huion New 1060PLUS + Hawku Drivers to a Wacom CTH-480 + OpenTabletDriver), and it still happens. 
'Confine mouse cursor to window' doesn't change anything, and 'Map absolute input to window' doesn't either.

**Comment by bdach** [comment] 2020-10-21 16:38
I'm pretty sure other users can get tablet running, so the OpenTabletDriver you mention would probably be the primary point of inquiry if this will end up needing an investigation.

**Comment by peppy** [comment] 2021-03-05 05:03
@Fvern can you confirm this is resolved when you turn off raw input in lazer? If so, this is a duplicate of #8434 (and will be fixed with the integration of `OpenTabletDriver` in a coming release).

**Comment by Fvern** [comment] 2021-03-05 05:05
yes, this only happens with raw input enabled

**Comment by peppy** [comment] 2021-03-05 05:10
Thanks for the quick confirmation! You'll be happy to know that this is now a focus and should be fixed in the next release or two.

**Comment by YourSandwich** [comment] 2021-03-22 14:38
I have the same issue on Linux, this OpenTablet drivers are interfearing with libwacom ones, when High Precision is enabled and disabled. After removing libwacom, I get two Cursors, first cursor with my own Tablet area, and one Cursor following Full Tablet Area. Tablet: Wacom CTH-480

**Comment by peppy** [comment] 2021-03-22 14:46
high precision input has nothing to do with tablets.

and yes, that is correct. please read the changelog, or the opentabletdriver faq.

closing this issue as no longer relevant.

**Closed by peppy** 2021-03-22 14:46 UTC
Labels: type:input
