### ISSUE TITLE
Bug message while importing beatmaps from stable to lazer

### ISSUE THREAD

**Issue by grizzly0304** [ppy/osu#2599] opened 2018-05-21 12:49 UTC
https://user-images.githubusercontent.com/39487486/40308167-88c855ee-5d05-11e8-80ad-3374e2aade08.png

This is the notification I got while importing my beatmaps from stable into lazer and tabbing out in the process. I don't know what to make of this but maybe you will.

**Comment by peppy** [comment] 2018-05-21 13:47
Duplicate of #2236

**Closed by peppy** 2018-05-21 13:47 UTC
