### ISSUE TITLE
When A Beatmap Updated And Went To Different Beatmap At The Same Time

### ISSUE THREAD

**Issue by TryhardPickles** [ppy/osu#21321] opened 2022-11-20 00:59 UTC
### Type

Cosmetic

### Bug description

When I move to a beatmap right after a beatmap updates, the beatmap starts to act weird.

check below

### Screenshots or videos

<img width="1440" alt="Screen Shot 2022-11-20 at 9 51 01" src="https://user-images.githubusercontent.com/107992426/202877601-0469cfaf-02e9-43ee-8c22-b10c7d6c5f30.png">

### Version

2022.1117.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/10048204/database.log)
[input.log](https://github.com/ppy/osu/files/10048205/input.log)
[network.log](https://github.com/ppy/osu/files/10048206/network.log)
[performance-draw.log](https://github.com/ppy/osu/files/10048207/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/10048208/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/10048209/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10048210/runtime.log)

**Comment by frenzibyte** [comment] 2022-11-20 01:16
Duplicate of https://github.com/ppy/osu/issues/21272

**Closed by frenzibyte** 2022-11-20 01:16 UTC
