### ISSUE TITLE
skin is in lower resolution than stable

### ISSUE THREAD

**Issue by FAB1150** [ppy/osu#7980] opened 2020-02-23 23:30 UTC
**Describe the bug:** 
whenever I play on Lazer, the skin is in a noticeable lower resolution than in stable. Resolution is set at 1440p in both stable and lazer.

**Screenshots or videos showing encountered issue:** 
how it is in Lazer:
![osu_2020-02-24_00-20-53](https://user-images.githubusercontent.com/23463665/75122235-f47d6680-569b-11ea-8482-394aeebc94ef.png)
How it is in stable:
![screenshot009](https://user-images.githubusercontent.com/23463665/75122341-c4829300-569c-11ea-864d-5a2b6bf25851.png)

(the hit circle always is low-res but that's the skin, I'm talking about the circles and sliders)

**osu!lazer version:** 
2020.221.0 but not unique to it

**Comment by peppy** [comment] 2020-02-24 02:51
The game is running at different resolutions in your screenshot.

**Comment by bdach** [comment] 2020-09-19 23:14
Closing as I'm not sure what the expected outcome is, and because the skin required to reproduce has not been provided. Will reopen if the skin is attached and it is deemed that there's an actual issue here.

**Closed by bdach** 2020-09-19 23:14 UTC
Labels: missing details
