### ISSUE TITLE
Wrongly pitched storyboard sfx on Double Time

### ISSUE THREAD

**Issue by Catzzye** [ppy/osu#29117] opened 2024-07-26 18:38 UTC
### Type

Game behaviour

### Bug description

I was just playing through maps while I noticed it sounded off. The hitsounds of the map are correctly pitched, but the SFX of the storyboard (sfx folder) used in the map in question is always Nightcore pitched. 
(focus on the 1, 2, AY! in the video just at the break)
I've attached video which displays the difference stable vs lazer. 

Beatmap in question: https://osu.ppy.sh/beatmapsets/4434#osu/24133

### Screenshots or videos

https://youtu.be/fhous8o9O2A

### Version

2024.726.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16395542/compressed-logs.zip)

**Comment by frenzibyte** [comment] 2024-07-29 23:56
Duplicate of https://github.com/ppy/osu/issues/10069

**Closed by frenzibyte** 2024-07-29 23:56 UTC
Labels: area:storyboard
