### ISSUE TITLE
iOS app submission guideline regression

### ISSUE THREAD

**Issue by peppy** [ppy/osu#7443] opened 2020-01-05 08:22 UTC
As of the latest build, we regressed what was previously fixed (but have fixed importing files in the process).

We will need to address this as it will mean the app cannot be submitted in the future.

> ITMS-90737: Missing Document Configuration - By declaring the CFBundleDocumentTypes key in your app, you've indicated that your app is able to open documents. Please set the UISupportsDocumentBrowser key to "YES" if your app uses a UIDocumentBrowserViewController. Otherwise, set the LSSupportsOpeningDocumentsInPlace key in the Info.plist to "YES" (recommended) or "NO" to specify whether the app can open files in place. All document-based apps must include one of these configurations. For more information, visit https://developer.apple.com/document-based-apps/.

**Comment by dtsdao** [comment] 2020-01-07 13:01
Duplicate of #5500

This means we need to let osu! act like a **document-based app**, which means we need to let users access files saved in `/Documents`, like Word or something.

But all the files are automatically generated and it's dangerous to give users permission to modify these files. So all the generated files except `/logs` need to be moved to `/Library/Documents`, where we're supposed to put our files.

**This needs changes to the framework**, so this task is a little complicated and needs time to be accomplished.

For now, we can just disable file-sharing on iOS to test other functions, or just do the migration. A simple patch like #5533 won't fix this problem.

Reference:
https://github.com/ppy/osu/pull/5574
https://github.com/ppy/osu-framework/pull/2714

**Comment by peppy** [comment] 2020-01-07 13:32
Yep, is a duplicate but will leave this one open tracking it.

**Closed** 2024-12-19 01:49 UTC
Labels: area:tooling, platform/iOS
