### ISSUE TITLE
Addd support for skin animations

### ISSUE THREAD

**Issue by CerberusRoze** [ppy/osu#5579] opened 2019-08-03 02:19 UTC
**Describe the missing feature:** In osu! skinners can skin the hit circle to be a blank png and have the number png as a hicircle removing the expanding circle hit effect, as well as skin the "300,100,50,x" effect to be visible for a fraction of the time it is set as by default by having it work like an animation
![this](https://user-images.githubusercontent.com/53631671/62405912-be8d6d80-b5f7-11e9-8424-8da6d1878b9b.PNG)

**Proposal designs of the feature:** i haven't seen anyone bring up specifically this issue so sorry if it has and i missed it but this is kind of a niche skin design so i dont know many people actually know or care about this
i currently dont see that there is any way for "fixing" this or making it work in lazer but adding a simple option for completely removing hit animations and reducing the time you see a "100" on screen would be great

i was looking and i saw that skin animations arent working yet but that post was in 2018
it probably shouldnt have to be done by animating and maybe actually coding it in the skin would be cool (can you actually do that already? i dont know i dont code LOL)

THANK YOU FOR READING

**Comment by peppy** [comment] 2019-08-03 02:43
animations are already a work in progress (https://github.com/ppy/osu/pull/5497)

**Comment by Joehuu** [comment] 2019-08-03 02:50
Duplicate of #4627?

**Comment by CerberusRoze** [comment] 2019-08-03 03:15
im talking about when the numbers are literally the circles 
like this 
![circ](https://user-images.githubusercontent.com/53631671/62406407-a02b7000-b5ff-11e9-8412-922b7fc325bf.PNG)

from what i understand now the numbers have the same animation the hit circle does when being tapped
i do not have a hitcircleoverlay-0.png like that post because this isnt an animation issue or my hit circle not appearing at all

regular numbers are skinned like this 
![defff](https://user-images.githubusercontent.com/53631671/62406478-9ce4b400-b600-11e9-9688-5d0cf166d62f.PNG)

i hope this makes sense!

my main point is when skinning the numbers to be circles is it takes out an extra animation i do not want and i get this in lazer i dont see any other way around this

also thanks for the fast replies

**Comment by peppy** [comment] 2019-08-03 06:15
Closing as duplicate

**Closed by peppy** 2019-08-03 06:15 UTC
Labels: skinning
