### ISSUE TITLE
triangles beatmap (the one linked to the triangles intro) is playable by selecting it through the music player

### ISSUE THREAD

**Issue by CenTdemeern1** [ppy/osu#17682] opened 2022-04-06 10:53 UTC
### Type

Other

### Bug description

The (normally unplayable) built-in triangles beatmap used in the triangles intro sequence is playable by playing the triangles song through the music player.

### Screenshots or videos

https://user-images.githubusercontent.com/24682280/161959095-d96bd411-1dee-40b5-b112-cb0dd4d17c46.mp4

### Version

2022.405.0-lazer, local debug build on 2c8fcadb9738df7dbaa42b5c2c58e5e6d80b68cc

### Logs

[database.log](https://github.com/ppy/osu/files/8426201/database.log)
[performance.log](https://github.com/ppy/osu/files/8426202/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8426203/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8426204/updater.log)

**Comment by Gabixel** [comment] 2022-04-06 10:58
I think this is a duplicate of [this discussion](https://github.com/ppy/osu/discussions/15484)

**Comment by CenTdemeern1** [comment] 2022-04-06 10:59
Ah whoops

**Closed** 2022-04-06 10:58 UTC
