### ISSUE TITLE
Chat will be auto close when click join channel

### ISSUE THREAD

**Issue by james58899** [ppy/osu#3987] opened 2019-01-02 15:34 UTC
**Describe your problem:** Chat will be auto close when click join channel

**Screenshots or videos showing encountered issue:** https://streamable.com/oo64s

**osu!lazer version:** 2018.1228.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/2721123/database.log)
[network.log](https://github.com/ppy/osu/files/2721124/network.log)
[performance.log](https://github.com/ppy/osu/files/2721125/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2721126/runtime.log)

**Comment by peppy** [comment] 2019-01-03 02:55
I tried to fix this once but it wasn't as simple as I hoped.

**Comment by UselessToucan** [comment] 2019-01-03 10:49
Tried to reproduce the bug on [6156359ff14f428e1e12c33d9533c3d56e769222](https://github.com/ppy/osu/commit/6156359ff14f428e1e12c33d9533c3d56e769222). Here is some additional info.

It works ok when I am already joined some channels.
https://www.youtube.com/watch?v=nrPRviD-Y3g

The problem happens when I am not joined to any channel.
https://www.youtube.com/watch?v=iUPga6NNAaw
[network.log](https://github.com/ppy/osu/files/2723403/network.log)
[runtime.log](https://github.com/ppy/osu/files/2723404/runtime.log)

**Comment by peppy** [comment] 2019-01-06 03:34
The issue is actually more to do with the overflow behaviour (when there's a dropdown list of channels and the '+' ends up in there).

**Comment by ThePyrotechnic** [comment] 2019-02-12 02:27
Potential duplicate of #3670

**Comment by peppy** [comment] 2019-02-12 03:00
Closing as duplicate

**Closed by peppy** 2019-02-12 03:00 UTC
Labels: bug, chat, user interface
