### ISSUE TITLE
Memory leak and freezing on Experimental Direct3D renderer

### ISSUE THREAD

**Issue by dee-eep** [ppy/osu#28855] opened 2024-07-14 03:44 UTC
### Type

Performance

### Bug description

After playing for a while in a session (>10 minutes), I would notice that the game would occasionally freeze for half a second and then continue as normal. This freezing would start by happening around once a minute or so, then over time become more and more frequent. I checked task manager and saw osu using over 5gb of ram (went down to 3gb while I was tabbed out and typing this, still excessive compared to the around 500mb it used to use), so I'm assuming that this is caused by a memory leak and is causing the freezes as well. 

I use the experimental renderer since I noticed significant input lag decrease and some fps increase over the normal Direct3D renderer. This issue started from the latest update (2024.625.0 I think); it did not occur before. I am using a Galaxy Book3 Pro 360 with an eGPU (AMD RX 6800) however Windows is set to not use the eGPU for osu.

I've seen bug reports for the Vulkan experimental and OpenGL renderers but not Direct3D experimental

### Screenshots or videos

![image](https://github.com/user-attachments/assets/c81a4bbd-8fd0-4cf3-8162-5520d111c703)

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16215587/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-07-14 04:16
Experimental renderer issues go in https://github.com/ppy/osu/discussions/27659.

**Comment by smoogipoo** [comment] 2024-07-16 03:35
Going to reopen this one for now until it's confirmed to be isolated to the experimental renderer, because there was a similar/related issue [here](https://github.com/ppy/osu/issues/26368) that was supposed to be resolved by https://github.com/ppy/veldrid/pull/54 .

@dee-eep can you check if this happens on the non-experimental renderer?

**Comment by smoogipoo** [comment] 2024-07-16 03:50
I'm able to repro this on https://osu.ppy.sh/beatmapsets/17670#osu/62963 with the depth mod (as per previously mentioned issue). I'll treat it separate from all the other deferred renderer fails, because this one is a native memory leak.

**Comment by dee-eep** [comment] 2024-07-16 04:00
Hi, I won't be able to test for around 24 hours but here's information I know. 

Happens on any beatmap, will provide some once I can test later
It happens with no mods selected
The skin is default osu argon pro edited, with the only change being adding the letter grade display which was added in a recent patch in the top right 

I'll have more information tomorrow once I can test, but  feel free to ask if any other info is needed

**Comment by dee-eep** [comment] 2024-07-16 04:03
If it's important, if I hit a circle on time at the same time as the game freezes, it ends up giving me a 50 or a miss, even though multi threaded rendering is on

**Comment by smoogipoo** [comment] 2024-07-16 06:01
https://github.com/ppy/osu-framework/pull/6331 Should fix this in the next release.

**Closed** 2024-07-16 08:01 UTC
Labels: osu!framework issue, renderer/directx

**Comment by dee-eep** [comment] 2024-07-16 15:35
Just tested, memory usage didn't go over 1GB on D3D11 non-experimental

Skin: 
[osu_ _argon_ pro (2022) (modified) (Unknown).zip](https://github.com/user-attachments/files/16252284/osu_._argon_.pro.2022.modified.Unknown.zip)

Just reproduced on D3D11 experimental by playing these 5 maps, memory usage hit almost 4GB: 
https://osu.ppy.sh/beatmapsets/1727589#osu/3530438
https://osu.ppy.sh/beatmapsets/921889#osu/1928891
https://osu.ppy.sh/beatmapsets/596704#osu/1262271
https://osu.ppy.sh/beatmapsets/1674456#osu/3433650
https://osu.ppy.sh/beatmapsets/2161281#osu/4557702
