### ISSUE TITLE
Audio not showing up on map editor

### ISSUE THREAD

**Issue by Shudhanshu-Raj** [ppy/osu#22459] opened 2023-01-29 15:30 UTC
### Type

Game behaviour

### Bug description

I tried getting different types of audio format like mp3 and m4a but it still doesn't show up 

### Version

2023.123.0

### Logs

[database.log](https://github.com/ppy/osu/files/10530084/database.log)
[network.log](https://github.com/ppy/osu/files/10530085/network.log)
[performance.log](https://github.com/ppy/osu/files/10530086/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10530087/runtime.log)

**Comment by Shudhanshu-Raj** [comment] 2023-01-29 15:32
![Screenshot_20230129-205419](https://user-images.githubusercontent.com/76690780/215336816-db3d361c-3c39-488d-9985-bda2ce6de462.png)

**Comment by bdach** [comment] 2023-01-29 16:02
Duplicate of #11911

**Closed by bdach** 2023-01-29 16:02 UTC
