### ISSUE TITLE
Where my mouse pointer?

### ISSUE THREAD

**Issue by yansaan** [ppy/osu#9258] opened 2020-06-11 20:16 UTC
**Describe the bug:** 
idk Why mouse pointer hide in menu?
position osu!lazer run as admin
**Screenshots or videos showing encountered issue:** 
[https://youtu.be/cujNHMqOU2A](https://youtu.be/cujNHMqOU2A)
**osu!lazer version:** 
2020.603.0
**Logs:**
[performance.log](https://github.com/ppy/osu/files/4767099/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4767100/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4767101/updater.log)
[database.log](https://github.com/ppy/osu/files/4767102/database.log)
[network.log](https://github.com/ppy/osu/files/4767103/network.log)

**Comment by bdach** [comment] 2020-06-11 20:26
Please state your hardware specifications.

**Comment by yansaan** [comment] 2020-06-11 21:28
![Screenshot_2020-06-12 System Information Report](https://user-images.githubusercontent.com/21020026/84440988-24f60a00-ac65-11ea-9975-7120f57f51fe.png)

**Comment by yansaan** [comment] 2020-06-11 21:29
Possessor:   Intel(R) Core(TM) i3-3225 CPU @ 3.30GHz

**Comment by frenzibyte** [comment] 2020-06-11 21:31
Duplicate of https://github.com/ppy/osu/issues/8487 from your GPU.

**Comment by bdach** [comment] 2020-06-11 21:32
As I suspected, this is a known issue (#8487) specific to your graphics card. As it requires specific hardware, we don't quite know why it happens.

Closing as duplicate of aforementioned issue.

**Closed** 2020-06-11 21:32 UTC
