### ISSUE TITLE
"Change folder location" setting won't show anything if network disk is unavailable

### ISSUE THREAD

**Issue by TommyGodlike** [ppy/osu#19515] opened 2022-08-01 07:18 UTC
### Type

Game behaviour

### Bug description

First time I tried to change location, the game crashed. After reading logs found out that it can't reach network disk, which is unavailable at the moment. Changing install location work after I disconnected disk manually. 

### Screenshots or videos

[cfl.webm](https://user-images.githubusercontent.com/13316619/182093376-431bd666-5364-47a2-a466-9e6a3c694787.webm)

### Version

2022.731.1-laser

### Logs

[database.log](https://github.com/ppy/osu/files/9231701/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/9231702/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/9231703/network.log)
[performance.log](https://github.com/ppy/osu/files/9231704/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9231705/runtime.log)
[updater.log](https://github.com/ppy/osu/files/9231706/updater.log)

**Comment by frenzibyte** [comment] 2022-08-01 07:19
Duplicate of https://github.com/ppy/osu-framework/issues/5306

**Closed by frenzibyte** 2022-08-01 07:19 UTC
