### ISSUE TITLE
Differentiate 8K & 7K+Scratch in Mania

### ISSUE THREAD

**Issue by Puffycheeses** [ppy/osu#9134] opened 2020-05-28 02:28 UTC
**Describe the new feature:** 8K maps should offer an option for mappers to differentiate the left-most/right-most lane as a "Scratch" lane, Similar to other games such as [IIDX](https://en.wikipedia.org/wiki/Beatmania_IIDX). This lane can then be on the [left](https://i.ytimg.com/vi/Ci_MogPlLyc/maxresdefault.jpg) or [right](https://i.ytimg.com/vi/2JOxbsmGahg/maxresdefault.jpg) of the playfield depending on the players prefered position. This would be similar to the way IIDX handles its 8K mode with the [8th "button" being a turntable](https://i.ytimg.com/vi/q30dw-_Zi90/maxresdefault.jpg). Right now as an IIDX player 8K maps are strange to play as all 8 lanes are treated as notes.

**Proposal designs of the feature:** Provide a way of differentiating 8K & 7K+s maps either through standard mania mode or through a new Ruleset that allows the use of [.bms files](https://en.wikipedia.org/wiki/Be-Music_Source) (or something similar) for maps. Players would have an option to have the scratch lane on the left (1P mode) or on the right (2P mode).

**Comment by peppy** [comment] 2020-05-28 02:29
Very far away from being something we are focused on, but has been something we are aware of.

**Comment by smoogipoo** [comment] 2020-05-28 04:41
Duplicate of https://github.com/ppy/osu/issues/2203

Maps can already change the special style via:
```
[General]
SpecialStyle: 1
```

But that isn't implemented in lazer yet (neither is the skin component of that).

**Closed by smoogipoo** 2020-05-28 04:41 UTC
Labels: low-priority, ruleset:osu!mania
