### ISSUE TITLE
PP in lazer

### ISSUE THREAD

**Issue by kricher123** [ppy/osu#22910] opened 2023-03-19 13:26 UTC
### Type

Game behaviour

### Bug description

Ive noticed that when i click on the replay the amount of pp it says the replay is worth isnt matching that when i open my profile through laser .

### Screenshots or videos

![image](https://user-images.githubusercontent.com/128300493/226177975-b4f57dbc-6568-4b00-8490-d2004c23e5c5.png)
![image](https://user-images.githubusercontent.com/128300493/226177998-1ca3fd43-6a87-482a-a73e-a3dfcaa96212.png)

### Version

2023.305.0

### Logs

[input.log](https://github.com/ppy/osu/files/11011139/input.log)
[network.log](https://github.com/ppy/osu/files/11011140/network.log)
[performance.log](https://github.com/ppy/osu/files/11011141/performance.log)
[performance-draw.log](https://github.com/ppy/osu/files/11011142/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/11011143/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/11011144/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11011145/updater.log)
[database.log](https://github.com/ppy/osu/files/11011146/database.log)

**Comment by agatemosu** [comment] 2023-03-19 14:57
Duplicate of #21815

**Closed** 2023-03-19 18:46 UTC
