### ISSUE TITLE
osu!mania timing based colouring should be applied more selectively

### ISSUE THREAD

**Issue by peppy** [ppy/osu#23978] opened 2023-06-21 03:43 UTC
Currently it looks really bad on argon, as it is applied to the whole note:

![osu! 2023-06-21 at 03 42 45](https://github.com/ppy/osu/assets/191335/779c93c3-75eb-4f89-81c9-3d994bf521d6)

We could either

- Replace the note colour (usually taken from the column)
- Only colour the white pieces (the line at the bottom and the symbol)

Interested in more opinions on this.

**Comment by peppy** [comment] 2023-06-21 03:43
We should also consider migrating it to the "Synesthesia" mod if this is a considerable change.

**Comment by Joehuu** [comment] 2023-06-21 04:00
Seems to be a duplicate of https://github.com/ppy/osu/issues/20977?

**Comment by peppy** [comment] 2023-06-21 04:06
weirdly, couldn't find that, even using keywords which are in the title...

**Closed** 2023-06-21 04:07 UTC
Labels: ruleset:osu!mania, priority:1

**Comment by longnguyen2004** [comment] 2023-09-08 11:12
Not related to argon, but since it also follows the theme of "selectively apply coloring", can we get a switch to disable coloring the LN tail? For dense LN, it becomes really distracting, and sometimes I misread the tail as being a note.
