### ISSUE TITLE
cursor weird on auto pilot

### ISSUE THREAD

**Issue by Neon095** [ppy/osu#17578] opened 2022-03-31 14:36 UTC
### Type

Game behaviour

### Bug description

The cursor is working weird on auto pilot like not smooth and sometimes teleporting, in auto works good
(Sorry for the weird zoom of the video)

### Screenshots or videos

https://mega.nz/file/3XpjUa6J#2dS-M8wndik8z-tJsk09dZy8_JIcUelybJPzJfDLLDI

### Version

2022.327.0 windows

### Logs

[network.log](https://github.com/ppy/osu/files/8390415/network.log)
[performance.log](https://github.com/ppy/osu/files/8390416/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8390417/runtime.log)
[updater.log](https://github.com/ppy/osu/files/8390418/updater.log)
[database.log](https://github.com/ppy/osu/files/8390419/database.log)

**Comment by Theighlin** [comment] 2022-03-31 14:44
#9716

**Comment by Neon095** [comment] 2022-03-31 15:19
But why?

**Comment by bdach** [comment] 2022-03-31 17:55
Either going to be a duplicate of https://github.com/ppy/osu/issues/9716 as mentioned above or https://github.com/ppy/osu/issues/10565. Closing as duplicate either way.

**Closed by bdach** 2022-03-31 17:55 UTC
