### ISSUE TITLE
Incorrect work of windowed mode

### ISSUE THREAD

**Issue by Proxima36** [ppy/osu#13638] opened 2021-06-23 16:30 UTC
After update 2021.619.0 the game is displayed incorrectly in windowed mode, instead of being displayed in the window, it remains maximized to full screen.

**Screenshots or videos showing encountered issue:** 
https://youtu.be/bS0yki3wy4E

**osu!lazer version:** 
2021.623.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6703348/database.log)
[performance.log](https://github.com/ppy/osu/files/6703350/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6703351/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6703352/updater.log)

**Comment by bdach** [comment] 2021-06-23 16:37
Are you sure that the window isn't windowed? Maybe it is windowed, but the window size is equal to the screen size, and the window titlebar/decoration is not visible? Can the game be maximised/minimised in the state shown on the video?

I'm asking because https://github.com/ppy/osu-framework/issues/4507 was an issue that sounds extremely similar to this, and is now fixed, but that issue may have caused your window size to be stuck (as it is saved to config). If that is the case, then just resizing the window to a better size may fix it for you.

**Comment by Proxima36** [comment] 2021-06-23 17:05
@bdach no, i can't interact with the tilebar at all in windowed mode, because it offscreen
After some digging, I found that in the framework.ini file, WindowedSize parameter set to 1921x1081, after manually changing it to something else solved my problem. Thanks

**Comment by bdach** [comment] 2021-06-23 17:08
Can you confirm that changing window mode to windowed and back after applying that configuration change works correctly? If it does, I'll close this issue as resolved.

**Comment by Proxima36** [comment] 2021-06-23 17:36
I actually can reproduce this behavior again if drag window to top border of the screen and cycle screen modes. It fixes only after restarting game.
https://youtu.be/mVnZk0wiFy0

**Comment by peppy** [comment] 2021-06-24 04:37
Maybe regressing behaviour from https://github.com/ppy/osu-framework/pull/4499? Thought I can't yet imagine how/why. Will take a look.

**Comment by peppy** [comment] 2021-06-24 12:46
Can reproduce this.

**Closed** 2021-06-27 13:52 UTC
Labels: framework-fix-required, priority:1
