### ISSUE TITLE
Show Key Count in song select for mania maps

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu#9453] opened 2020-07-08 09:50 UTC
Currently I don't seem to see the key count when browsing mania maps in lazer:
![osu_2020-07-08_11-47-00](https://user-images.githubusercontent.com/34809632/86904350-e3943580-c110-11ea-8779-35e294fe8cd1.jpg)
Maybe put it in with the other map data like duration, bpm and single / long notes

**Comment by smoogipoo** [comment] 2020-07-08 11:51
Kinda related to https://github.com/ppy/osu/issues/9412

@arflyte need to consider somehow displaying the key count of mania maps.

**Comment by enoslayd** [comment] 2020-07-08 12:22
It is showing in details tab btw (though not that much visible)

**Comment by peppy** [comment] 2020-07-13 23:10
This is also an issue on osu-web to some degree (have to hover to see key count).

Would you be happy enough with it showing in the hover tooltip, or are you hoping for something more visible? Maybe a number overlaying the mania difficulty icon or a dot count around the icon or something?

**Comment by enoslayd** [comment] 2020-07-13 23:29
Something more visible without going to details tab

**Comment by smoogipoo** [comment] 2020-07-14 11:20
It really should be displayed in two places: the wedge and on the panels. Going through beatmaps in a set to figure out which are 4K and which are 7K is bound to be annoying.

**Comment by lanpai** [comment] 2020-08-18 03:43
Addressed the issue in https://github.com/ppy/osu/pull/9898 which adds it the statistics wedge at the left (Duration, BPM, Note Count, etc.).

I agree with @smoogipoo and it should also be displayed on the difficulty itself as it would be better for users as it requires a lot of eye movement to sift through mania maps without it.

**Comment by peppy** [comment] 2020-11-02 08:37
@arflyte make sure this is in your song select design updates.

**Comment by peppy** [comment] 2022-02-11 06:06
Closing as duplicate of #5668.

**Closed by peppy** 2022-02-11 06:06 UTC
Labels: ruleset:osu!mania, area:song-select, type:UI
