### ISSUE TITLE
iOS releases crash on startup

### ISSUE THREAD

**Issue by FleurduLapin** [ppy/osu#27017] opened 2024-02-04 12:33 UTC
### Type

Crashed

### Bug description

osu!lazer iOS crashed
module：iPhone13
iOS version：iOS17.4 beta1

### Version

2024.130.2-2024.131.0

### Logs

log

**Comment by frenzibyte** [comment] 2024-02-04 13:02
Thank you for your report, but I'm afraid to say this report is completely incomplete. There are no reproduction steps attached, neither there are logs to look at. Even the version must be incorrect, because both versions are not published on iOS due to runtime startup errors.

I'll close this for now, but if there's anything you can provide, please do it in here and I'll update the state of this issue thread accordingly.

**Comment by peppy** [comment] 2024-02-04 13:58
This is a known issue, which is why we haven't published a testflight release. It's 100% reproducible and has been mentioned multiple times internally.

**Comment by peppy** [comment] 2024-02-04 14:00
We don't have a tracking issue for this yet, so let's keep this open.

**Comment by CodeSoftGit** [comment] 2024-02-04 19:17
is this ever planned to be fixed? I am having to run a release from a couple months ago due to this, or is there a way I could fix this by building it differently?

**Comment by frenzibyte** [comment] 2024-02-04 19:36
It will most definitely be fixed, but mobile issues are not of utmost priority, so be patient on how long it takes to be resolved.

**Comment by peppy** [comment] 2024-02-15 08:15
Tentatively closing this based on feedback from @smoogipoo that things are looking good with veldrid + net80 updates.

**Closed by peppy** 2024-02-15 08:15 UTC
Labels: platform/iOS, type:reliability
