### ISSUE TITLE
bad ranked puntuation

### ISSUE THREAD

**Issue by TetraNut** [ppy/osu#5564] opened 2019-08-01 21:54 UTC
**Describe the bug:** 
i was playin' a little time ago to try this version and i was encountered that is bad puntuated my acc on ctbo why i have an SS with 4 misses? i wasn't touched the code and this is my first time in lazer version of osu

**Screenshots or videos showing encountered issue:** 

![imagen](https://user-images.githubusercontent.com/53584110/62329758-355a2780-b48d-11e9-8b71-bea97085dc3e.png)

**osu!lazer version: 2019.730.0 DEVELOPMENT BUILD** 

**Logs: i don't know where i find the logs, sorry**

**Comment by Game4all** [comment] 2019-08-01 22:17
Duplicate of issue #4184

For now , all rulesets use mania grade scaling in lazer.

**Comment by TetraNut** [comment] 2019-08-01 22:28
how it's that? @Game4all

**Comment by smoogipoo** [comment] 2019-08-02 02:37
Because lazer's not complete. Closing as duplicate.

**Closed by smoogipoo** 2019-08-02 02:37 UTC
