### ISSUE TITLE
online rank is different depending on where you look

### ISSUE THREAD

**Issue by L0tsen** [ppy/osu#26752] opened 2024-01-27 22:34 UTC
### Type

Game behaviour

### Bug description

idk how i else could describe it just look at the image.

### Screenshots or videos

![2024-01-27 23_27_44-Window](https://github.com/ppy/osu/assets/81811972/5d1241b8-6ea2-43d9-920b-be9098819050)

### Version

2024.114.0

### Logs

[1705854762.network.log](https://github.com/ppy/osu/files/14074017/1705854762.network.log)
[1705854762.performance.log](https://github.com/ppy/osu/files/14074018/1705854762.performance.log)
[1705854762.runtime.log](https://github.com/ppy/osu/files/14074019/1705854762.runtime.log)
[1705854762.updater.log](https://github.com/ppy/osu/files/14074020/1705854762.updater.log)
[1705860741.database.log](https://github.com/ppy/osu/files/14074021/1705860741.database.log)
[1705860741.input.log](https://github.com/ppy/osu/files/14074022/1705860741.input.log)
[1705860741.network.log](https://github.com/ppy/osu/files/14074023/1705860741.network.log)
[1705860741.performance.log](https://github.com/ppy/osu/files/14074024/1705860741.performance.log)
[1705860741.runtime.log](https://github.com/ppy/osu/files/14074025/1705860741.runtime.log)
[1705860741.updater.log](https://github.com/ppy/osu/files/14074026/1705860741.updater.log)
[1705862334.database.log](https://github.com/ppy/osu/files/14074027/1705862334.database.log)
[1705862334.input.log](https://github.com/ppy/osu/files/14074028/1705862334.input.log)
[1705862334.network.log](https://github.com/ppy/osu/files/14074029/1705862334.network.log)
[1705862334.performance.log](https://github.com/ppy/osu/files/14074030/1705862334.performance.log)
[1705862334.runtime.log](https://github.com/ppy/osu/files/14074031/1705862334.runtime.log)
[1705862334.updater.log](https://github.com/ppy/osu/files/14074032/1705862334.updater.log)
[1705954403.database.log](https://github.com/ppy/osu/files/14074033/1705954403.database.log)
[1705954403.input.log](https://github.com/ppy/osu/files/14074034/1705954403.input.log)
[1705954403.network.log](https://github.com/ppy/osu/files/14074035/1705954403.network.log)
[1705954403.performance.log](https://github.com/ppy/osu/files/14074036/1705954403.performance.log)
[1705954403.runtime.log](https://github.com/ppy/osu/files/14074037/1705954403.runtime.log)
[1705954403.updater.log](https://github.com/ppy/osu/files/14074038/1705954403.updater.log)
[1705992267.database.log](https://github.com/ppy/osu/files/14074039/1705992267.database.log)
[1705992267.input.log](https://github.com/ppy/osu/files/14074040/1705992267.input.log)
[1705992267.network.log](https://github.com/ppy/osu/files/14074041/1705992267.network.log)
[1705992267.performance.log](https://github.com/ppy/osu/files/14074042/1705992267.performance.log)
[1705992267.runtime.log](https://github.com/ppy/osu/files/14074043/1705992267.runtime.log)
[1705992267.updater.log](https://github.com/ppy/osu/files/14074044/1705992267.updater.log)
[1706079527.database.log](https://github.com/ppy/osu/files/14074045/1706079527.database.log)
[1706079527.input.log](https://github.com/ppy/osu/files/14074046/1706079527.input.log)
[1706079527.network.log](https://github.com/ppy/osu/files/14074047/1706079527.network.log)
[1706079527.performance.log](https://github.com/ppy/osu/files/14074048/1706079527.performance.log)
[1706079527.runtime.log](https://github.com/ppy/osu/files/14074049/1706079527.runtime.log)
[1706079527.updater.log](https://github.com/ppy/osu/files/14074050/1706079527.updater.log)
[1706204949.database.log](https://github.com/ppy/osu/files/14074051/1706204949.database.log)
[1706204949.input.log](https://github.com/ppy/osu/files/14074052/1706204949.input.log)
[1706204949.network.log](https://github.com/ppy/osu/files/14074053/1706204949.network.log)
[1706204949.performance.log](https://github.com/ppy/osu/files/14074054/1706204949.performance.log)
[1706204949.runtime.log](https://github.com/ppy/osu/files/14074055/1706204949.runtime.log)
[1706204949.updater.log](https://github.com/ppy/osu/files/14074056/1706204949.updater.log)
[1706210182.database.log](https://github.com/ppy/osu/files/14074057/1706210182.database.log)
[1706210182.input.log](https://github.com/ppy/osu/files/14074058/1706210182.input.log)
[1706210182.network.log](https://github.com/ppy/osu/files/14074059/1706210182.network.log)
[1706210182.performance.log](https://github.com/ppy/osu/files/14074060/1706210182.performance.log)
[1706210182.runtime.log](https://github.com/ppy/osu/files/14074061/1706210182.runtime.log)
[1706210182.updater.log](https://github.com/ppy/osu/files/14074062/1706210182.updater.log)
[1706252080.database.log](https://github.com/ppy/osu/files/14074063/1706252080.database.log)
[1706252080.input.log](https://github.com/ppy/osu/files/14074065/1706252080.input.log)
[1706252080.network.log](https://github.com/ppy/osu/files/14074066/1706252080.network.log)
[1706252080.performance.log](https://github.com/ppy/osu/files/14074067/1706252080.performance.log)
[1706252080.runtime.log](https://github.com/ppy/osu/files/14074068/1706252080.runtime.log)
[1706252080.updater.log](https://github.com/ppy/osu/files/14074069/1706252080.updater.log)
[1706254793.database.log](https://github.com/ppy/osu/files/14074070/1706254793.database.log)
[1706254793.input.log](https://github.com/ppy/osu/files/14074072/1706254793.input.log)
[1706254793.network.log](https://github.com/ppy/osu/files/14074073/1706254793.network.log)
[1706254793.performance.log](https://github.com/ppy/osu/files/14074074/1706254793.performance.log)
[1706254793.runtime.log](https://github.com/ppy/osu/files/14074075/1706254793.runtime.log)
[1706254793.updater.log](https://github.com/ppy/osu/files/14074076/1706254793.updater.log)
[1706258560.database.log](https://github.com/ppy/osu/files/14074077/1706258560.database.log)
[1706258560.input.log](https://github.com/ppy/osu/files/14074078/1706258560.input.log)
[1706258560.network.log](https://github.com/ppy/osu/files/14074079/1706258560.network.log)
[1706258560.performance.log](https://github.com/ppy/osu/files/14074080/1706258560.performance.log)
[1706258560.runtime.log](https://github.com/ppy/osu/files/14074081/1706258560.runtime.log)
[1706258560.updater.log](https://github.com/ppy/osu/files/14074082/1706258560.updater.log)
[1706282915.database.log](https://github.com/ppy/osu/files/14074083/1706282915.database.log)
[1706282915.input.log](https://github.com/ppy/osu/files/14074084/1706282915.input.log)
[1706282915.network.log](https://github.com/ppy/osu/files/14074085/1706282915.network.log)
[1706282915.performance.log](https://github.com/ppy/osu/files/14074086/1706282915.performance.log)
[1706282915.runtime.log](https://github.com/ppy/osu/files/14074087/1706282915.runtime.log)
[1706282915.updater.log](https://github.com/ppy/osu/files/14074088/1706282915.updater.log)
[1706291189.database.log](https://github.com/ppy/osu/files/14074089/1706291189.database.log)
[1706291189.input.log](https://github.com/ppy/osu/files/14074090/1706291189.input.log)
[1706291189.network.log](https://github.com/ppy/osu/files/14074091/1706291189.network.log)
[1706291189.performance.log](https://github.com/ppy/osu/files/14074092/1706291189.performance.log)
[1706291189.runtime.log](https://github.com/ppy/osu/files/14074093/1706291189.runtime.log)
[1706291189.updater.log](https://github.com/ppy/osu/files/14074094/1706291189.updater.log)
[1706297929.database.log](https://github.com/ppy/osu/files/14074095/1706297929.database.log)
[1706297929.input.log](https://github.com/ppy/osu/files/14074096/1706297929.input.log)
[1706297929.network.log](https://github.com/ppy/osu/files/14074097/1706297929.network.log)
[1706297929.performance.log](https://github.com/ppy/osu/files/14074098/1706297929.performance.log)
[1706297929.runtime.log](https://github.com/ppy/osu/files/14074099/1706297929.runtime.log)
[1706297929.updater.log](https://github.com/ppy/osu/files/14074100/1706297929.updater.log)
[1706299060.database.log](https://github.com/ppy/osu/files/14074101/1706299060.database.log)
[1706299060.input.log](https://github.com/ppy/osu/files/14074102/1706299060.input.log)
[1706299060.network.log](https://github.com/ppy/osu/files/14074103/1706299060.network.log)
[1706299060.performance.log](https://github.com/ppy/osu/files/14074104/1706299060.performance.log)
[1706299060.runtime.log](https://github.com/ppy/osu/files/14074105/1706299060.runtime.log)
[1706299060.updater.log](https://github.com/ppy/osu/files/14074106/1706299060.updater.log)
[1706301566.database.log](https://github.com/ppy/osu/files/14074107/1706301566.database.log)
[1706301566.input.log](https://github.com/ppy/osu/files/14074108/1706301566.input.log)
[1706301566.network.log](https://github.com/ppy/osu/files/14074109/1706301566.network.log)
[1706301566.performance.log](https://github.com/ppy/osu/files/14074110/1706301566.performance.log)
[1706301566.runtime.log](https://github.com/ppy/osu/files/14074111/1706301566.runtime.log)
[1706301566.updater.log](https://github.com/ppy/osu/files/14074112/1706301566.updater.log)
[1706348040.database.log](https://github.com/ppy/osu/files/14074113/1706348040.database.log)
[1706348040.input.log](https://github.com/ppy/osu/files/14074114/1706348040.input.log)
[1706348040.network.log](https://github.com/ppy/osu/files/14074116/1706348040.network.log)
[1706348040.performance.log](https://github.com/ppy/osu/files/14074117/1706348040.performance.log)
[1706348040.runtime.log](https://github.com/ppy/osu/files/14074118/1706348040.runtime.log)
[1706348040.updater.log](https://github.com/ppy/osu/files/14074119/1706348040.updater.log)
[1706360845.database.log](https://github.com/ppy/osu/files/14074120/1706360845.database.log)
[1706360845.input.log](https://github.com/ppy/osu/files/14074121/1706360845.input.log)
[1706360845.network.log](https://github.com/ppy/osu/files/14074122/1706360845.network.log)
[1706360845.performance.log](https://github.com/ppy/osu/files/14074123/1706360845.performance.log)
[1706360845.runtime.log](https://github.com/ppy/osu/files/14074124/1706360845.runtime.log)
[1706360845.updater.log](https://github.com/ppy/osu/files/14074125/1706360845.updater.log)
[1706377073.input.log](https://github.com/ppy/osu/files/14074126/1706377073.input.log)
[1706377073.network.log](https://github.com/ppy/osu/files/14074127/1706377073.network.log)
[1706377073.performance.log](https://github.com/ppy/osu/files/14074128/1706377073.performance.log)
[1706377073.runtime.log](https://github.com/ppy/osu/files/14074129/1706377073.runtime.log)
[1706377073.updater.log](https://github.com/ppy/osu/files/14074130/1706377073.updater.log)
[1706377185.input.log](https://github.com/ppy/osu/files/14074131/1706377185.input.log)
[1706377185.network.log](https://github.com/ppy/osu/files/14074132/1706377185.network.log)
[1706377185.performance.log](https://github.com/ppy/osu/files/14074133/1706377185.performance.log)
[1706377185.runtime.log](https://github.com/ppy/osu/files/14074134/1706377185.runtime.log)
[1706377185.updater.log](https://github.com/ppy/osu/files/14074135/1706377185.updater.log)
[1706377538.database.log](https://github.com/ppy/osu/files/14074136/1706377538.database.log)
[1706377538.input.log](https://github.com/ppy/osu/files/14074137/1706377538.input.log)
[1706377538.network.log](https://github.com/ppy/osu/files/14074138/1706377538.network.log)
[1706377538.performance.log](https://github.com/ppy/osu/files/14074139/1706377538.performance.log)
[1706377538.runtime.log](https://github.com/ppy/osu/files/14074140/1706377538.runtime.log)
[1706377538.updater.log](https://github.com/ppy/osu/files/14074141/1706377538.updater.log)
[1706380949.database.log](https://github.com/ppy/osu/files/14074142/1706380949.database.log)
[1706380949.input.log](https://github.com/ppy/osu/files/14074143/1706380949.input.log)
[1706380949.network.log](https://github.com/ppy/osu/files/14074144/1706380949.network.log)
[1706380949.performance.log](https://github.com/ppy/osu/files/14074145/1706380949.performance.log)
[1706380949.runtime.log](https://github.com/ppy/osu/files/14074146/1706380949.runtime.log)
[1706380949.updater.log](https://github.com/ppy/osu/files/14074147/1706380949.updater.log)
[1706382778.database.log](https://github.com/ppy/osu/files/14074148/1706382778.database.log)
[1706382778.input.log](https://github.com/ppy/osu/files/14074149/1706382778.input.log)
[1706382778.network.log](https://github.com/ppy/osu/files/14074150/1706382778.network.log)
[1706382778.performance.log](https://github.com/ppy/osu/files/14074151/1706382778.performance.log)
[1706382778.runtime.log](https://github.com/ppy/osu/files/14074152/1706382778.runtime.log)
[1706382778.updater.log](https://github.com/ppy/osu/files/14074153/1706382778.updater.log)
[1706383489.input.log](https://github.com/ppy/osu/files/14074154/1706383489.input.log)
[1706383489.network.log](https://github.com/ppy/osu/files/14074155/1706383489.network.log)
[1706383489.performance.log](https://github.com/ppy/osu/files/14074156/1706383489.performance.log)
[1706383489.runtime.log](https://github.com/ppy/osu/files/14074157/1706383489.runtime.log)
[1706383489.updater.log](https://github.com/ppy/osu/files/14074158/1706383489.updater.log)
[1706393765.database.log](https://github.com/ppy/osu/files/14074159/1706393765.database.log)
[1706393765.input.log](https://github.com/ppy/osu/files/14074160/1706393765.input.log)
[1706393765.network.log](https://github.com/ppy/osu/files/14074161/1706393765.network.log)
[1706393765.performance.log](https://github.com/ppy/osu/files/14074162/1706393765.performance.log)
[1706393765.runtime.log](https://github.com/ppy/osu/files/14074163/1706393765.runtime.log)
[1706393765.updater.log](https://github.com/ppy/osu/files/14074164/1706393765.updater.log)
[1705848938.database.log](https://github.com/ppy/osu/files/14074165/1705848938.database.log)
[1705848938.input.log](https://github.com/ppy/osu/files/14074166/1705848938.input.log)
[1705848938.network.log](https://github.com/ppy/osu/files/14074167/1705848938.network.log)
[1705848938.performance.log](https://github.com/ppy/osu/files/14074168/1705848938.performance.log)
[1705848938.runtime.log](https://github.com/ppy/osu/files/14074169/1705848938.runtime.log)
[1705848938.updater.log](https://github.com/ppy/osu/files/14074170/1705848938.updater.log)
[1705854762.database.log](https://github.com/ppy/osu/files/14074171/1705854762.database.log)
[1705854762.input.log](https://github.com/ppy/osu/files/14074172/1705854762.input.log)

**Comment by Flamiii** [comment] 2024-01-27 23:44
Seems like a duplicate of https://github.com/ppy/osu/issues/23834. There are many lazer scores that are either bugged or from an older version of lazer that may have had a different scoring algorithm and got recalculated or it could be due to failed F rank scores being removed from leaderboards or something else entirely.

**Closed** 2024-01-28 04:31 UTC
