### ISSUE TITLE
Forever attempting to connect

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu#6283] opened 2019-09-26 19:42 UTC
**Describe the bug:** Trying to log in on Android doesn't work, as the client doesn't seem to be able to connect.

**Screenshots or videos showing encountered issue:** 
![Screenshot_20190926-213923](https://user-images.githubusercontent.com/15932372/65719573-5ebabc80-e0a6-11e9-87b1-1e10061f7950.jpg)

**osu!lazer version:** 0.1 / 2019.925.0

**Logs:** 
[database.log](https://github.com/ppy/osu/files/3659610/database.log)
[network.log](https://github.com/ppy/osu/files/3659611/network.log)
[performance.log](https://github.com/ppy/osu/files/3659612/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3659613/runtime.log)

**Comment by bdach** [comment] 2019-09-26 20:06
Logs look clean. Mind trying to wait longer and seeing if anything changes (ie. the text changes to *Connection is failing, will attempt to reconnect...* or something of the sort), and then attaching logs again? That would probably help pin down the cause.

**Comment by smileyhead** [comment] 2019-09-26 20:23
Thanks for replying. Here you go, I left it running for 10 minutes.
The text didn't change, but the panel did go back to asking me my credentials about every 4 minutes.
[database.log](https://github.com/ppy/osu/files/3659752/database.log)
[network.log](https://github.com/ppy/osu/files/3659753/network.log)
[performance.log](https://github.com/ppy/osu/files/3659754/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3659755/runtime.log)

**Comment by bdach** [comment] 2019-09-26 20:32
Judging from the logs your time estimate seems correct. Now I'm seeing HTTP request timeouts in the logs, so it's possible it's something from your side, since I'm not seeing any availability issues on [osu!status](https://status.ppy.sh/). Do you have any firewall software running, or anything else that could possibly be blocking outgoing requests?

**Comment by smileyhead** [comment] 2019-09-26 20:34
No, unless Android does that by default (which I doubt, since I have no issues on my phone).

**Comment by SnGmng** [comment] 2019-09-29 21:18
Same issue here.

**Comment by iiSaLMaN** [comment] 2019-09-30 12:46
> Same issue here.

Do you have any additional info for this issue that might help resolve it?  if not, saying that you have the same issue is redundant.

**Comment by smileyhead** [comment] 2019-09-30 16:36
**Update:** seems to be fixed on 2019.930.0

[database.log](https://github.com/ppy/osu/files/3672264/database.log)
[network.log](https://github.com/ppy/osu/files/3672265/network.log)
[performance.log](https://github.com/ppy/osu/files/3672266/performance.log)
[runtime.log](https://github.com/ppy/osu/files/3672267/runtime.log)

**Comment by peppy** [comment] 2019-09-30 16:37
If fixed, please close the issue.

**Comment by smileyhead** [comment] 2019-09-30 16:40
I didn't close the issue because I wasn't the only person having it, and I haven't heard back from the others.

**Comment by SnGmng** [comment] 2019-09-30 20:00
The bug suddenly disappeared after i restarted my phone (before i installed the update), so i cant say that the newest update fixed the bug, or if the bug is still not fixed.

**Comment by bdach** [comment] 2019-12-17 17:42
Closing due to inactivity - assuming as fixed. Please leave a comment or reopen if still occurring.

**Closed by bdach** 2019-12-17 17:42 UTC
Labels: android, missing details
