### ISSUE TITLE
Sliderscorepoint and Reversearrow not scaled from circle size

### ISSUE THREAD

**Issue by Fatal3ty** [ppy/osu#5395] opened 2019-07-18 01:22 UTC
Reversearrow and Sliderscorepoint not scaled with the high circle size

 Screenshot: https://puu.sh/DU9PZ/5dab62db5a.png

2019.717.1

Sliderscorepoint and Reversearrow don't scaled this circle size. Not fixed that the actual client.

**Comment by peppy** [comment] 2019-07-18 02:26
Please include your skin for reference.

**Comment by peppy** [comment] 2019-07-18 03:31
Closing as duplicate of #3158.

**Closed by peppy** 2019-07-18 03:31 UTC
Labels: bug, skinning

**Comment by Fatal3ty** [comment] 2019-07-18 20:13
Oh, i didn't see that Post, i will use "search" for the future. That is my personal skin (Ameliorate Fatal v2.2 Lazer), i try anoter Skins - all the same bugs with reversearrow and sliderscorepoint.
