### ISSUE TITLE
Cannot open replays

### ISSUE THREAD

**Issue by MinisBett** [ppy/osu#6462] opened 2019-10-10 16:22 UTC
I was making some changes in the osu framework and accidentially clicked on the view replay button at the end of the beatmap in the osu lazer build I had in the same solution. Then my osu crashed and visual studio gave me the following exception:

System.InvalidOperationException: "Sequence contains no matching element"
Source: System.Linq

By inspecting the stack trace I found out that the problem occours in line 236 in the GameHost.cs file. (captured.Throw())

Then I tried it again with a clean download of the osu-framework but it still happened.

**Comment by Gabixel** [comment] 2019-10-10 17:24
Duplicate of / similar to https://github.com/ppy/osu/issues/6448 ?

**Comment by iiSaLMaN** [comment] 2019-10-10 17:25
Based on what we have from details at the moment, we can't confirm that.

**Comment by MinisBett** [comment] 2019-10-11 11:11
`
at System.Linq.ThrowHelper.ThrowNoMatchException()\r\n   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at osu.Game.Scoring.LegacyDatabasedScore..ctor(ScoreInfo score, RulesetStore rulesets, BeatmapManager beatmaps, IResourceStore`1 store) in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Game\\Scoring\\LegacyDatabasedScore.cs:line 19\r\n   at osu.Game.Scoring.ScoreManager.GetScore(ScoreInfo score) in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Game\\Scoring\\ScoreManager.cs:line 62\r\n   at osu.Game.OsuGame.PresentScore(ScoreInfo score) in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Game\\OsuGame.cs:line 299\r\n   at osu.Game.Screens.Play.ReplayDownloadButton.<>c__DisplayClass5_0.<load>b__0() in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Game\\Screens\\Play\\ReplayDownloadButton.cs:line 55\r\n   at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Graphics\\Containers\\ClickableContainer.cs:line 29\r\n   at osu.Game.Graphics.UserInterface.OsuAnimatedButton.OnClick(ClickEvent e) in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Game\\Graphics\\UserInterface\\OsuAnimatedButton.cs:line 101\r\n   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Graphics\\Drawable.cs:line 1876\r\n   at osu.Framework.Input.MouseButtonEventManager.<>c__DisplayClass38_0.<PropagateMouseButtonEvent>b__0(Drawable target) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\MouseButtonEventManager.cs:line 271\r\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at osu.Framework.Input.MouseButtonEventManager.PropagateMouseButtonEvent(IEnumerable`1 drawables, MouseButtonEvent e) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\MouseButtonEventManager.cs:line 271\r\n   at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\MouseButtonEventManager.cs:line 199\r\n   at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\MouseButtonEventManager.cs:line 153\r\n   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\InputManager.cs:line 483\r\n   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\InputManager.cs:line 445\r\n   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\UserInputManager.cs:line 53\r\n   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\StateChanges\\ButtonInput.cs:line 74\r\n   at osu.Framework.Input.InputManager.Update() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\InputManager.cs:line 238\r\n   at osu.Framework.Input.PassThroughInputManager.Update() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Input\\PassThroughInputManager.cs:line 129\r\n   at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Graphics\\Drawable.cs:line 438\r\n   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Graphics\\Containers\\CompositeDrawable.cs:line 802\r\n   at osu.Framework.Platform.GameHost.UpdateFrame() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Platform\\GameHost.cs:line 300\r\n   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\GameThread.cs:line 140\r\n   at osu.Framework.Threading.GameThread.runWork() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\GameThread.cs:line 110\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at osu.Framework.Platform.GameHost.<>c__DisplayClass92_0.<handleException>b__0() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Platform\\GameHost.cs:line 236\r\n   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\Scheduler.cs:line 320\r\n   at osu.Framework.Threading.Scheduler.Update() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\Scheduler.cs:line 158\r\n   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\GameThread.cs:line 137\r\n   at osu.Framework.Threading.InputThread.RunUpdate() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Threading\\InputThread.cs:line 28\r\n   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Platform\\GameHost.cs:line 544\r\n   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)\r\n   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)\r\n   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)\r\n   at osuTK.GameWindow.Run()\r\n   at osu.Framework.Platform.GameWindow.Run() in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Platform\\GameWindow.cs:line 270\r\n   at osu.Framework.Platform.GameHost.Run(Game game) in C:\\Users\\Niklas\\Source\\Repos\\osu-framework\\osu.Framework\\Platform\\GameHost.cs:line 555\r\n   at osu.Desktop.Program.Main(String[] args) in C:\\Users\\Niklas\\Source\\Repos\\osu\\osu.Desktop\\Program.cs:line 56"

**Comment by MinisBett** [comment] 2019-10-11 11:12
```
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Game.Scoring.LegacyDatabasedScore..ctor(ScoreInfo score, RulesetStore rulesets, BeatmapManager beatmaps, IResourceStore`1 store) in C:\Users\Niklas\Source\Repos\osu\osu.Game\Scoring\LegacyDatabasedScore.cs:line 19
   at osu.Game.Scoring.ScoreManager.GetScore(ScoreInfo score) in C:\Users\Niklas\Source\Repos\osu\osu.Game\Scoring\ScoreManager.cs:line 62
   at osu.Game.OsuGame.PresentScore(ScoreInfo score) in C:\Users\Niklas\Source\Repos\osu\osu.Game\OsuGame.cs:line 299
   at osu.Game.Screens.Play.ReplayDownloadButton.<>c__DisplayClass5_0.<load>b__0() in C:\Users\Niklas\Source\Repos\osu\osu.Game\Screens\Play\ReplayDownloadButton.cs:line 55
   at osu.Framework.Graphics.Containers.ClickableContainer.OnClick(ClickEvent e) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Graphics\Containers\ClickableContainer.cs:line 29
   at osu.Game.Graphics.UserInterface.OsuAnimatedButton.OnClick(ClickEvent e) in C:\Users\Niklas\Source\Repos\osu\osu.Game\Graphics\UserInterface\OsuAnimatedButton.cs:line 101
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Graphics\Drawable.cs:line 1876
   at osu.Framework.Input.MouseButtonEventManager.<>c__DisplayClass38_0.<PropagateMouseButtonEvent>b__0(Drawable target) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\MouseButtonEventManager.cs:line 271
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.MouseButtonEventManager.PropagateMouseButtonEvent(IEnumerable`1 drawables, MouseButtonEvent e) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\MouseButtonEventManager.cs:line 271
   at osu.Framework.Input.MouseButtonEventManager.HandleMouseClick(InputState state) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\MouseButtonEventManager.cs:line 199
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind, Double currentTime) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\MouseButtonEventManager.cs:line 153
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\InputManager.cs:line 483
   at osu.Framework.Input.InputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\InputManager.cs:line 445
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\UserInputManager.cs:line 53
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\StateChanges\ButtonInput.cs:line 74
   at osu.Framework.Input.InputManager.Update() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\InputManager.cs:line 238
   at osu.Framework.Input.PassThroughInputManager.Update() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Input\PassThroughInputManager.cs:line 129
   at osu.Framework.Graphics.Drawable.UpdateSubTree() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Graphics\Drawable.cs:line 438
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Graphics\Containers\CompositeDrawable.cs:line 802
   at osu.Framework.Platform.GameHost.UpdateFrame() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Platform\GameHost.cs:line 300
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\GameThread.cs:line 140
   at osu.Framework.Threading.GameThread.runWork() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\GameThread.cs:line 110
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at osu.Framework.Platform.GameHost.<>c__DisplayClass92_0.<handleException>b__0() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Platform\GameHost.cs:line 236
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\Scheduler.cs:line 320
   at osu.Framework.Threading.Scheduler.Update() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\Scheduler.cs:line 158
   at osu.Framework.Threading.GameThread.ProcessFrame() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\GameThread.cs:line 137
   at osu.Framework.Threading.InputThread.RunUpdate() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Threading\InputThread.cs:line 28
   at osu.Framework.Platform.GameHost.<Run>b__113_1(Object <p0>, FrameEventArgs <p1>) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Platform\GameHost.cs:line 544
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osuTK.GameWindow.Run()
   at osu.Framework.Platform.GameWindow.Run() in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Platform\GameWindow.cs:line 270
   at osu.Framework.Platform.GameHost.Run(Game game) in C:\Users\Niklas\Source\Repos\osu-framework\osu.Framework\Platform\GameHost.cs:line 555
   at osu.Desktop.Program.Main(String[] args) in C:\Users\Niklas\Source\Repos\osu\osu.Desktop\Program.cs:line 56
```

**Comment by bdach** [comment] 2019-10-11 11:14
Stack trace confirmed as exact same as in #6448; closing as duplicate.

**Closed by bdach** 2019-10-11 11:14 UTC
Labels: missing details
