### ISSUE TITLE
Numpad dot delayed in text fields

### ISSUE THREAD

**Issue by Ruoibeishi** [ppy/osu#5824] opened 2019-08-24 18:40 UTC
**Describe the bug:** Text fields (login fields, config search...) doesn't show the numpad's dot until you press another key.

**Screenshots or videos showing encountered issue:** 
https://s3.gifyu.com/images/GIF974a17aa5d794756.gif
https://s3.gifyu.com/images/GIF2b31e64a5d705ff50.gif

**osu!lazer version:** 2019.823.0

**Logs:** none

Using a QWERTY (ABNT2, tho, if it matters) keyboard.

**Comment by hbnrmx** [comment] 2019-08-24 19:11
Similar to / duplicate of #3884

**Comment by Ruoibeishi** [comment] 2019-08-24 19:19
It seems related, indeed. But as you can see in the first example, my @ is working normally, it's happening only to the dot.

Btw, edited the issue with layout info.

**Comment by peppy** [comment] 2019-08-27 05:33
Closing as duplicate of https://github.com/ppy/osu-framework/issues/1965.

**Closed by peppy** 2019-08-27 05:33 UTC
