### ISSUE TITLE
`BeatmapAttributeText` stats uses default values even with selected mods like DT

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu#29771] opened 2024-09-07 20:20 UTC
### Type

Other

### Bug description

`BeatmapAttributeText` in skin layout uses default beatmap stats, even when selected mods is DT or HR

### Screenshots or videos

https://github.com/user-attachments/assets/8e3252a4-b35c-4e5e-ac80-9436eab35350

### Version

2024.906.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16919829/compressed-logs.zip)

**Comment by Joehuu** [comment] 2024-09-07 21:38
Duplicate of https://github.com/ppy/osu/issues/21946

**Closed by Joehuu** 2024-09-07 21:38 UTC
