### ISSUE TITLE
Relax mod spams clicks when cursor is off note

### ISSUE THREAD

**Issue by Repulles** [ppy/osu#8096] opened 2020-03-02 21:02 UTC
While using relax mode the game/relax is clicking keys like +/-100 times per note if the cursor is off the note. 
It's fine when cursor is on the note (single click).

**Comment by bdach** [comment] 2020-03-02 21:53
Can't reproduce, mind linking the beatmap & providing some video evidence?

**Comment by Moltanicaa** [comment] 2020-03-03 02:29
https://youtu.be/jqhQq_fXq7A - the cursor should be close to the note

**Comment by smoogipoo** [comment] 2020-03-03 02:32
Can definitely be replicated, thanks.

**Comment by peppy** [comment] 2020-04-09 08:37
Fixed via https://github.com/ppy/osu/pull/8522.

**Closed by peppy** 2020-04-09 08:37 UTC
Labels: area:mods, ruleset:osu!
