### ISSUE TITLE
Metal renderer stutters a lot only on M2

### ISSUE THREAD

**Issue by freihy** [ppy/osu#23008] opened 2023-03-27 06:46 UTC
### Type

Performance

### Bug description

Using Metal renderer causes the game to stutter a lot. OpenGL and its legacy counterpart both run smoother somehow. I'm using Macbook Pro M2 14". Using an external display makes the issue more obvious. Playing on the in built screen seems to be better but still stutters. However, on my M1 Air, the game runs smooth with little to no stutter.

### Screenshots or videos
[FPS Counter](https://cdn.discordapp.com/attachments/963377244384948277/1089802094007042078/IMG_1382.mp4), excuse my dusty ass monitor xd

### Version

2023.326.1-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/11075395/database.log)
[input.log](https://github.com/ppy/osu/files/11075396/input.log)
[network.log](https://github.com/ppy/osu/files/11075397/network.log)
[performance.log](https://github.com/ppy/osu/files/11075398/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11075399/runtime.log)

**Comment by peppy** [comment] 2023-03-27 07:43
For me, the main thing I noticed on M2 hardware was that the game tears when not using vsync, even when in a window. I'm not sure that is what we want.

It's already very clear that we need to look into metal rendering further on both desktop and iOS because we aren't getting the expected performance on all devices.

**Comment by reo-the-enby** [comment] 2023-03-27 07:45
same for me on m1 macbook air. The latency is 8ms with metal and 2ms with openGL

Metal
<img width="393" alt="Skärmavbild 2023-03-27 kl  09 44 03" src="https://user-images.githubusercontent.com/81715029/227874533-61962bd0-e58b-413a-95e7-d80c23aab549.png">

openGL
<img width="388" alt="Skärmavbild 2023-03-27 kl  09 42 22" src="https://user-images.githubusercontent.com/81715029/227874564-a4178a69-ee5b-43fb-9995-42e6dda45754.png">

**Comment by peppy** [comment] 2023-03-27 08:09
Just note: those numbers are not "latency". They are frame times.

**Comment by wilkmaciej** [comment] 2023-03-28 16:00
I have similar results so far on M1 MacBook Air. Also, maybe I'm just imaging things, but I feel like the new renderer is way more unstable in terms of performance when there are a lot of hit objects on screen.

<img width="990" alt="Screenshot 2023-03-28 at 17 55 11" src="https://user-images.githubusercontent.com/73193760/228297955-9ee369e4-46bc-4470-a230-e7be9ee62246.png">
<img width="990" alt="Screenshot 2023-03-28 at 17 53 42" src="https://user-images.githubusercontent.com/73193760/228297965-6fa85f77-b057-4d3b-974d-ff9f222db8e1.png">

**Comment by smoogipoo** [comment] 2023-03-28 16:27
I think one thing we're lacking with Metal right now is that it should always be running at VSync, via `CADisplayLink` telling us when the next frame is ready to be rendered, similar to the D3D implementation.

Can you check that it is visually smooth when running VSync?

**Comment by freihy** [comment] 2023-03-29 01:33
Yes, it's smooth when running with VSync, but the draw frame times are real bad with it on 

Vsync On
![Screenshot 2023-03-29 at 9 30 24 AM](https://user-images.githubusercontent.com/24803877/228403380-660280d6-f3ec-4e2a-a6fc-c3a46ef2a64f.png)
x4 
![Screenshot 2023-03-29 at 9 30 38 AM](https://user-images.githubusercontent.com/24803877/228403422-4e9d26b2-5dc9-45d8-b87c-c825720297ab.png)

**Comment by wilkmaciej** [comment] 2023-04-03 15:58
> Yes, it's smooth when running with VSync, but the draw frame times are real bad with it on

Same for me

**Comment by peppy** [comment] 2023-05-02 07:56
Bumping this up to p0 as I can reproduce and it causes the game to be unplayable on anything other than vsync.

**Comment by peppy** [comment] 2023-06-06 04:40
Fixed in the latest release. If you get this as a user try changing thread mode to single thread as it will make things even better (for now).

**Closed by peppy** 2023-06-06 04:40 UTC
Labels: priority:0, platform:macOS, renderer:metal

**Comment by freihy** [comment] 2023-06-06 12:36
Tried it out! Thanks so much for you and the teams effort! I can finally play standard again and not just taiko and mania haha... Multithreaded seems to still work better for me, single thread seems to have a bit more input latency (albeit could just be placebo though)
