### ISSUE TITLE
Slider Type Changing Midplay with Classic Mod

### ISSUE THREAD

**Issue by chrisPST** [ppy/osu#24464] opened 2023-08-04 20:37 UTC
### Type

Game behaviour

### Bug description

1. Start a map with classic mod enabled
2. Ctrl+O as the song is still on the loading screen
3. Switch skin
4. Close settings tab and let map start playing
5. Map will have sliders using Lazer style and classic style

### Screenshots or videos

Lazer -> Classic -> Lazer -> Classic -> 0:14 Lazer (100'd slider) -> Classic

https://github.com/ppy/osu/assets/56751122/9d4d271c-9006-4117-a366-ea5e0f1fad1d

### Version

2023.803.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/12264417/database.log)
[input.log](https://github.com/ppy/osu/files/12264418/input.log)
[network.log](https://github.com/ppy/osu/files/12264419/network.log)
[performance.log](https://github.com/ppy/osu/files/12264420/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12264421/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12264422/updater.log)

**Comment by chrisPST** [comment] 2023-08-04 20:38
My apologies, it looks look like the video I uploaded plays like an audio (thanks GitHub)
Heres a streamable link to the video: https://streamable.com/axq6ki

**Comment by bdach** [comment] 2023-08-05 22:33
I don't understand this report in the slightest. What is "slider style" referring to here? Also what does switching skin have to do with it?

Can you attach the replay of this play so that I can look at it? Because this reproduction scenario makes no sense and I'm like 95% confident that whatever's happening here is not what you're saying is happening.

**Comment by chrisPST** [comment] 2023-08-05 22:58
By slider type, I mean how the slider functions when it's being played. I never wrote a report for osu! I apologize for this confusion when I wrote this report.

For this report, I described Lazer slider style as this:
![osu!_hxOhsKuNP1](https://github.com/ppy/osu/assets/56751122/e2aadfc5-7ac5-41d8-80cb-e14caa11be52)


For Classic, I described it as this:
![osu!_ivn0VyK1jq](https://github.com/ppy/osu/assets/56751122/2547c109-6a19-4940-a491-577ecd8b64fc)


When the skin was changed while the map was loading, both slider styles are used in play with Classic mod enabled as seen here:
![ezgif com-optimize](https://github.com/ppy/osu/assets/56751122/52d82439-281b-491b-9539-20822eef9ed5)

**Comment by bdach** [comment] 2023-08-05 23:07
Okay, right, I see now.

It's probably this getting reset somehow:

https://github.com/ppy/osu/blob/e13eb7588d4284409c04d4eeb82726bffc608261/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs#L26-L30

**Comment by bdach** [comment] 2023-09-19 10:25
Tentatively marking as closed by #24810

**Closed by bdach** 2023-09-19 10:25 UTC
Labels: ruleset/osu!, area:gameplay, type:behavioural, priority:1
