### ISSUE TITLE
Parallax on mouse goes outside of screen boundaries.

### ISSUE THREAD

**Issue by RzoregDe96** [ppy/osu#9524] opened 2020-07-11 07:40 UTC
**Describe the bug:** 
as the title says, with the video (compressed vid to match github's 10MB limit)
**Screenshots or videos showing encountered issue:** 
[osu! 2020-07-11 15-27-08-319.zip](https://github.com/ppy/osu/files/4906456/osu.2020-07-11.15-27-08-319.zip)

**osu!lazer version:** 
2020.707.0/2020.710.0
**Logs:**
[database.log](https://github.com/ppy/osu/files/4906447/database.log)
[performance.log](https://github.com/ppy/osu/files/4906448/performance.log)
[runtime.log](https://github.com/ppy/osu/files/4906449/runtime.log)
[updater.log](https://github.com/ppy/osu/files/4906450/updater.log)

**Comment by LastExceed** [comment] 2020-07-11 08:16
Please upload to youtube or streamable in the future

**Comment by RzoregDe96** [comment] 2020-07-11 08:24
yes, i'll take note to that next time...

**Comment by bdach** [comment] 2020-07-11 19:33
Was this video taken on a setup with multiple vertically-stacked displays? I'm not sure however else you would be able to move the mouse outside of the screen bounds like that...

It seems to be true however that the parallax is still taking effect if the mouse cursor is on another screen, which is probably unintended. Dampening the parallax at the edges of the screen might be a decent way to go, maybe?

**Comment by RzoregDe96** [comment] 2020-07-12 01:11
no, i don't have multiple displays.. just one
and i noticed this bug since last update (2020.707.0)

**Comment by Joehuu** [comment] 2020-07-12 01:41
Were you in fullscreen and did you have raw input on and confine mouse cursor to window set to never?

![dotnet_qOJwOpEBjA](https://user-images.githubusercontent.com/35318437/87236944-903a1580-c3a4-11ea-95ce-91976cd51d65.png)

This is a duplicate of https://github.com/ppy/osu-framework/issues/2247 if it is.

**Comment by RzoregDe96** [comment] 2020-07-12 01:57
![osu_2020-07-12_09-53-08](https://user-images.githubusercontent.com/56816547/87237190-c1a6f580-c425-11ea-9dd2-66d7230c3c49.png)
yeah, i didn't notice that...
maybe i'll change it to 'always' later..

and since this is related to 2247, closing this thread is possible...

**Comment by Joehuu** [comment] 2020-07-12 01:59
Closing as duplicate.

**Closed by Joehuu** 2020-07-12 01:59 UTC
Labels: area:main menu, type:UI

**Comment by bdach** [comment] 2020-07-12 06:58
I'm not 100% sure this should have been closed. For one the multiple-monitor issue is still an issue.

**Comment by RzoregDe96** [comment] 2020-07-12 07:03
hmm... yes but, i only have single monitor
![image](https://user-images.githubusercontent.com/56816547/87240961-ccc34b00-c450-11ea-9764-1dd33a799aa7.png)

**Comment by bdach** [comment] 2020-07-12 07:06
Yes, I get it, but *I* don't and I see how the parallax effect could be problematic with multiple screens.
