### ISSUE TITLE
Low performance with new multiplayer/playlist room design

### ISSUE THREAD

**Issue by Bryceed** [ppy/osu#14314] opened 2021-08-15 15:01 UTC
**Describe the bug:** 
The new multiplayer room (pull #14127) is extremely heavy, affecting even the waiting room's performance.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/42657376/129482445-6c177ede-1173-4ed0-b138-de0bee5452e1.mp4

_(low FPS video capture to better register the real performance at lower right)_

**osu!lazer version:** 
2021.815.0-lazer

**Logs:**
[database.log](https://github.com/ppy/osu/files/6988334/database.log)
[network.log](https://github.com/ppy/osu/files/6988335/network.log)
[performance.log](https://github.com/ppy/osu/files/6988336/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6988337/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6988338/updater.log)

**Comment by frenzibyte** [comment] 2021-08-15 15:01
Duplicate of https://github.com/ppy/osu/issues/14276. Please search.

**Closed by frenzibyte** 2021-08-15 15:01 UTC
