### ISSUE TITLE
Database error when importing maps from stable

### ISSUE THREAD

**Issue by szmarczak** [ppy/osu#12810] opened 2021-05-14 13:30 UTC
**Describe the bug:** 

Lazer imports only 28 of 29 maps.

**Screenshots or videos showing encountered issue:** 

![image](https://user-images.githubusercontent.com/36894700/118277429-13e2f800-b4c9-11eb-825e-8c3ded38dfda.png)

**osu!lazer version:** https://github.com/ppy/osu/releases/tag/2021.514.0

**Logs:**

[logs.import.crash.zip](https://github.com/ppy/osu/files/6479064/logs.import.crash.zip)

**Comment by frenzibyte** [comment] 2021-05-14 13:33
```
2021-05-14 13:22:50 [error]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
2021-05-14 13:22:50 [error]: ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
2021-05-14 13:22:50 [error]: at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2021-05-14 13:22:50 [error]: at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
2021-05-14 13:22:50 [error]: --- End of inner exception stack trace ---
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
2021-05-14 13:22:50 [error]: at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
```

Your database file has been corrupted somehow, delete your database `client.db` file in `%appdata%/osu` and try again.

**Comment by peppy** [comment] 2021-05-14 13:34
Please upload a copy of your database before you delete it, if possible

**Comment by szmarczak** [comment] 2021-05-14 13:36
[client.db.zip](https://github.com/ppy/osu/files/6479103/client.db.zip)

**Comment by szmarczak** [comment] 2021-05-14 13:45
I have created a backup of the entire `osu` directory just in case.

**Comment by szmarczak** [comment] 2021-05-14 13:49
My bindings got reset, but other settings remained the same.

**Comment by frenzibyte** [comment] 2021-05-14 13:53
Gonna close this as a duplicate of #10480.

**Closed by frenzibyte** 2021-05-14 13:53 UTC

**Comment by peppy** [comment] 2021-05-15 06:24
@szmarczak the database you attached works fine. are you sure it's the correct one?

**Comment by szmarczak** [comment] 2021-05-18 12:08
Yes, definitely. The database doesn't seem to be corrupted, lazer just errors when importing a map that has been edited and completed. See my video in #10480
