### ISSUE TITLE
Storyboard does not display correctly

### ISSUE THREAD

**Issue by ghost** [ppy/osu#10894] opened 2020-11-18 15:06 UTC
~~The autoplay doesn't seem to be working correctly with transform for some odd reason. It would work ok for a second and then just... starts to get broken. Here's the gif:~~

~~https://drive.google.com/file/d/1_zFW9hV14uQncrrcyHfz_mhuo9BI7_vO/view?usp=sharing~~

There is also a problem with the storyboard. In this example, I used a very heavy storyboarded beatmap "emotional". See the problem yourselves:

How it is supposed to look: https://drive.google.com/file/d/1ROaOUpRNYDLcpW5V7PucEpR6YS-dTGBW/view?usp=sharing
How it looks in osu!lazer: https://drive.google.com/file/d/1j-vRA3OXIi9WnXmk-mw-zLH6m29i5PZU/view?usp=sharing

osu!lazer version: 2020.1114.0

Logs:
[network.log](https://github.com/ppy/osu/files/5560898/network.log)
[performance.log](https://github.com/ppy/osu/files/5560899/performance.log)
[runtime.log](https://github.com/ppy/osu/files/5560900/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5560901/updater.log)
[database.log](https://github.com/ppy/osu/files/5560902/database.log)

**Comment by bdach** [comment] 2020-11-18 15:31
Transform issue was already reported in #10848 and will be fixed next release.

**Comment by bdach** [comment] 2020-11-18 17:25
Beatmap is https://osu.ppy.sh/beatmapsets/554758#osu/1174377.

**Comment by Wieku** [comment] 2021-09-25 15:17
After analyzing the .osb file this issue is a duplicate of #2084

**Closed** 2021-09-25 15:28 UTC
Labels: area:storyboard
