### ISSUE TITLE
osu!lazer // Menu Cursor not showing on Windows 10

### ISSUE THREAD

**Issue by TardisPeanut** [ppy/osu#8507] opened 2020-03-30 13:22 UTC
**Describe the bug: Menu Cursor not showing on Windows 10** 

**Screenshots or videos showing encountered issue:** 
![image](https://user-images.githubusercontent.com/32435849/77916956-90555000-72a2-11ea-97fd-179bdcf788bb.png)

**osu!lazer version:2020.327.0** 

**Logs:**

**Comment by Game4all** [comment] 2020-03-30 13:24
Similar / Duplicate of #8487

**Comment by TardisPeanut** [comment] 2020-03-30 13:25
basically yeah, @Game4all  😅

**Comment by Game4all** [comment] 2020-03-30 13:27
In that case please close that issue thread as it is already being tracked on the aforementioned issue

**Closed** 2020-03-30 13:29 UTC

**Comment by 9847046046** [comment] 2024-08-15 06:06
super

**Comment by 9847046046** [comment] 2024-08-15 06:06
can you send it an me?
